### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers#1001]
_From @krthr on August 30, 2018 23:4_

### Steps to reproduce

- [ ] populateAccessToken functions isn't getting the accessToken token property. 

### Expected behavior
Login and create a new resource from the client.

### Actual behavior
Login and getting and error when i try to create a new resource:

```bash
Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at Object.eval (populate-access-token.js?39da:9)
    at promise.then.hookObject (hooks.js?8408:142)
(anonymous) @ populate-access-token.js?39da:9
promise.then.hookObject @ hooks.js?8408:142
...
```

**Module versions** (especially the part that's not working): 
- "@feathersjs/authentication-client": "1.0.3"
- "@feathersjs/feathers": "3.2.0"
- "@feathersjs/socketio-client": "1.1.1"

**NodeJS version**: 8.9.4
**Operating System**: Windows 10

_Copied from original issue: feathersjs/authentication-client#108_

**Comment by daffl** [comment]
_From @krthr on August 30, 2018 23:5_

When i type `ApiClient.get('accessToken')` in the console I get the accessToken

**Comment by daffl** [comment]
What logs do you get if you add

```
app.hooks({
  before(context) {
    console.log(context);
    return context;
  }
});
```

In your client side application? Also, does this still happen when explicitly installing `@feathersjs/feathers@3.1.7`?

**Comment by daffl** [comment]
_From @Torge on August 31, 2018 19:2_

I got the same error. Its on the clientside for me. I think the problem isn't the access token but hook.params. It is undefined for me.
populateAccessToken tries to Object.assign it.
```
    Object.assign(hook.params, { accessToken: app.get('accessToken') });
```
context in populateAccessToken:
```
"{
  "type": "before",
  "method": "create",
  "path": "draft",
  "data": {}
}"
```
Setting the @feathersjs/feathers version from 3.2.0 to 3.1.7 solved the issue for me.

context in populateAccessToken @ 3.1.7:
```
{
  "type": "before",
  "method": "create",
  "path": "draft",
  "params": {},
  "data": {}
}
```

**Comment by daffl** [comment]
I am not able to reproduce this with a new client build in the [feathers-chat](https://github.com/feathersjs/feathers-chat). How does your client side application setup look like?

**Comment by daffl** [comment]
_From @krthr on September 1, 2018 0:43_

Its a Vue app with `feathers-vuex` plugin

**Comment by daffl** [comment]
_From @krthr on September 1, 2018 0:50_

I have tested it with `@feathersjs/feathers@3.1.7` and it worked....

**Comment by daffl** [comment]
Can someone try this with `@feathersjs/feathers@3.2.1` and the latest versions of all other packages. It might've just been a dependency clash that I think should be resolved now.

**Comment by daffl** [comment]
_From @krthr on September 3, 2018 3:7_

It worked fine for me using `@feathersjs/feathers@3.2.1`

**Comment by daffl** [comment]
Sweet. I think we can close this then. Anybody running into this issue make sure that all the latest versions are installed.

**Comment by daffl** [comment]
_From @MartinBucko on September 7, 2018 8:14_

Hi guys, i have same issue with latest versions..

```
"dependencies": {
    "@feathersjs/authentication-client": "^1.0.4",
    "@feathersjs/client": "^3.6.0",
    "@feathersjs/socketio-client": "^1.1.2",
    "chart.js": "^2.7.2",
    "chartjs-plugin-datalabels": "^0.4.0",
    "feathers-authentication-management": "^2.0.1",
    "feathers-hooks-common": "^4.16.3",
    "feathers-vuex": "^1.4.8",
    "lodash": "^4.17.10",
    "moment": "^2.22.2",
    "quasar-extras": "^2.0.6",
    "quasar-framework": "^0.17.12",
    "socket.io-client": "^2.1.1",
    "vue": "^2.5.17",
    "vue-chartjs": "^3.4.0",
    "vue-i18n": "^8.1.0",
    "vue-router": "^3.0.1",
    "vuelidate": "^0.7.4",
    "vuelidate-error-extractor": "^2.2.2",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.0.1",
    "@vue/cli-plugin-eslint": "^3.0.1",
    "@vue/cli-service": "^3.0.1",
    "husky": "^0.14.3",
    "lint-staged": "^7.2.2",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.1",
    "vue-cli-plugin-quasar": "^0.2.1",
    "vue-template-compiler": "^2.5.17"
  }
```

Edit: Server don't get any request, is only client side issue as described here https://github.com/feathersjs/authentication-client/issues/108#issuecomment-417761316 from @Torge

**Comment by daffl** [comment]
_From @dottodot on September 7, 2018 12:7_

I think the issue is in @feathersjs/client as the only thing that worked for me was going back to 3.5.6

**Comment by daffl** [comment]
_From @petebytes on September 8, 2018 7:33_

Same exact error for me running latest versions on a project setup on Aug 30th.
Unfortunately setting older versions did not resolve the issue.  

An older nearly identical project is working, however changing all the dependencies from working project to new project did not resolve the issue either.

**Comment by daffl** [comment]
_From @petebytes on September 8, 2018 8:31_

Was able to workaround the issue as follows:
- delete yarn.lock
- delete node_modules
- copy package-lock.json from working project
- npm install

So it seems it was a package that is not explicitly in package.json, as simply copying the working package.json did not work.

**Comment by daffl** [comment]
_From @petebytes on September 8, 2018 15:54_

"@feathersjs/feathers": "3.1.7" works - 3.2.1 does not.
The reason it did not seem to work when I tried 3.1.7 before is that I forgot to remove ^ from package.json and when I installed it was automatically installing 3.2.1

**Comment by daffl** [comment]
Since I am not able to reproduce the problem someone has to provide a breaking example. A starting point would be including all the VueJS stuff since that is the main difference I am seeing.

**Comment by daffl** [comment]
_From @petebytes on September 8, 2018 17:35_

@daffl I have a repo here with a works and broken commits.
https://github.com/petebytes/trello-clone.git

**Comment by daffl** [comment]
_From @arjitkhullar on September 8, 2018 22:35_

As @dottodot mentioned, downgrading @feathers/client to v3.5.6 seems to be a workaround for now.

**Comment by daffl** [comment]
_From @joeinnes on September 9, 2018 14:39_

Can confirm, the problem is that hook.params is empty on the create method (but not find). For me it's also in feathers-vuex, same as everyone else in this thread so I think maybe this is a downstream issue.

**Comment by daffl** [comment]
_From @andygott on September 14, 2018 11:48_

I ran into the same thing without using any additional stuff (like Vue). I was using my service like this:

```
feathersClient.service( 'myService' ).create( myData, myParams )
```

But sometimes I call the service with `myParams` undefined, which hadn’t caused a problem using previous feathersjs versions (I don’t think — unless I’d just missed it, which is definitely possible!).

So my fix was simply:

```
feathersClient.service( 'myService' ).create( myData, myParams || {} )
```

Great work on feathersjs — really enjoying using it.

**Comment by testless** [comment]
I am afraid, I am experiencing a similar issue without using vue, but with the reduxify... libraries.

The error happens here:
https://github.com/feathersjs/authentication-client/blob/master/lib/hooks/populate-access-token.js#L9

hook.params may be undefined...

A simple `hook.params = hook.params || {}` could solve this.

Is there a good reason not to this?

**Comment by daffl** [comment]
Yes, the reason is that `params` should _never_ even be undefined (Feathers is making sure of that internally). I can't reproduce this with the normal [feathers-chat](https://github.com/feathersjs/feathers-chat) so a more minimalistic example to show the issue would be useful.

**Comment by petermikitsh** [comment]
Hey @daffl I noticed this bug today:

Shouldn't this file be updated => https://github.com/feathersjs/feathers/blob/34a51a3f370a728fbac1b3ade5b8404f41a71f18/packages/authentication-client/lib/hooks/populate-access-token.js

Particularly this line:

```
Object.assign(hook.params, { accessToken: app.get('accessToken') });
```

Should be something like:

```
hook.params = {...hook.params, {accessToken: app.get('accessToken') });
```

Object.assign doesn't like when it's first parameter is `null` or `undefined` :)

**Comment by petermikitsh** [comment]
Re-read the thread. I'm using the `feathers-redux` library. Perhaps a change is needed there. It doesn't seem like a regression has been introduced-- the populateAccessToken implementation hasn't been changed in years. Does this sound about right?

**Comment by daffl** [comment]
It could be a regression in `@feathersjs/feathers@3.2.0` but I can't reproduce it with the latest versions and so far nobody has been able to _give me an actually reproducible example_.

**Comment by eddyystop** [comment]
As an aside, `feathers-redux` hasn't changed since January.

**Comment by petermikitsh** [comment]
@daffl Here's a repro of this issue => https://github.com/petermikitsh/feathers-issue-1001

**Comment by petermikitsh** [comment]
If you take the same repo (linked in my prior comment), except use @feathersjs/feathers@3.0.5, you get this stack trace:

```
Uncaught (in promise) Error: Params for 'find' method must be an object
    at validateArguments (arguments.js:32)
    at Object.mixin.(:3000/anonymous function) (http://0.0.0.0:8080/client.js:2521:9)
    at Object.find (proto.js:30)
    at Module../client.js (client.js:10)
    at __webpack_require__ (bootstrap:724)
    at fn (bootstrap:101)
    at Object.0 (log.js:47)
    at __webpack_require__ (bootstrap:724)
    at bootstrap:791
    at bootstrap:791
```

**Comment by daffl** [comment]
Perfect, that helped a lot. So it appears that the regression is that previous if `params` was falsy it got replaced with an object and now that only happens when it is `undefined`.
