### ISSUE TITLE
Problem with hook.service.patch

### ISSUE THREAD

**Issue by andysay** [feathersjs/feathers#1005]
hi! i,m try made next 

after: {
  get: [   hook => hook.service.patch(hook.id, { views: hook.result.views + 1 }) ],
}

when i get on client side     let good = await axios.get(process.env.baseUrl+'/messages?slug='+ok), 

and when i get message from db , this hook not working(why? i use axios.post, why in logger show find method ??) , only when i change data in DB(rethinkdb) use for this another client ; works,  but have infinity reload) ; what wrong, show this error. many times, 5 sec > 200 times change views in data.

 after hook for 'get' method returned invalid hook object
error:  message=after hook for 'get' method returned invalid hook object, stack=Error: after hook for 'get' method returned invalid hook object, its only when

**Comment by daffl** [comment]
You have to return the `hook` context or `undefined`.

```js
after: {
  get: [ hook => {
    hook.service.patch(hook.id, { views: hook.result.views + 1 });
    return hook;
  } ],
}
```

**Comment by andysay** [comment]
> You have to [return the `hook` context or `undefined`](https://docs.feathersjs.com/api/hooks.html#hook-functions).
> 
> ```js
> after: {
>   get: [ hook => {
>     hook.service.patch(hook.id, { views: hook.result.views + 1 });
>     return hook;
>   } ],
> }
> ```

this example also updates data infinitely

**Comment by daffl** [comment]
Is this the users service? Is `patch` itself running a `get` for some reason in one of its hooks?

**Comment by andysay** [comment]
![screencaptureproject2](https://user-images.githubusercontent.com/5610952/45601257-d4f7fe00-ba12-11e8-9840-aad7b091c3d3.gif)

**Comment by daffl** [comment]
I just tried the same hook in the [feathers-chat](https://github.com/feathersjs/feathers-chat) and it worked as expected. If your application is doing another `context.service.get` in any of the hooks on the `patch` method you will need a breaking clause just like with any other recursive method call though.

**Comment by andysay** [comment]
i check my install version , and i have 2.3.5 , now i'm try upgrade my app, and again , write about results later :)
All done. 
Results: 
0 errors
83 unmodified
1 skipped
14 ok

**Comment by daffl** [comment]
As I said, if your service is calling itself for some reason (e.g. on the `users` service this will happen because of the `authenticate('jwt')`) you will have to add a breaking condition. With the information that I have, I was able to get it working in the [feathers-chat](https://github.com/feathersjs/feathers-chat) as expected by updating https://github.com/feathersjs/feathers-chat/blob/master/src/services/messages/messages.hooks.js#L18-L26 to

```js
  after: {
    all: [populateUser()],
    find: [],
    get: [async hook => {
      const { views = 0 } = hook.result;

      hook.result = await hook.service.patch(hook.id, { views: views + 1 });

      return hook;
    }],
    create: [],
    update: [],
    patch: [],
    remove: []
  },
```

Now every time I call a `client.service('messages').get(_id)` it will show an updated `views` property.
