### ISSUE TITLE
oauth2 provider for actions-on-google (smarthome)

### ISSUE THREAD

**Issue by InnerPeace080** [feathersjs/feathers#1006]
Hi all.

I currently need to setup actions-on-google smarthome, and i need setup oauth2 provider (author code) for it can get access-token from my server (feathersjs)

Have anyone know to do this with feathers-authentication provider instead of support oauth2 all by hand ?

Thank u verymuch

**Comment by daffl** [comment]
Authentication with an existing oAuth access token is now possible in the new v4 [oAuth authentication](https://crow.docs.feathersjs.com/api/authentication/oauth.html#configuration).
