### ISSUE TITLE
Problems with auth (oauth2 with Google, Github, Facebook) while switching to HTTPS

### ISSUE THREAD

**Issue by nriesco** [feathersjs/feathers#1009]
### Steps to reproduce

I cannot use Google, Github and Facebook authentication services when using https. Without https it will work fine (except for facebook that requires https) but when enabling https something changes and I get 505 errors:

```
error: Unknown authentication strategy 'google'
error: Unknown authentication strategy 'github'
error: Unknown authentication strategy 'facebook'
```

I set up a repo to illustrate this problem (you'll need mongodb running)

```
git clone https://github.com/riescorp/feathers-auth-https-fail-private.git
cd feathers-auth-https-fail-private
npm install
npm start
```

You'll need to set this var to true/false to test https and http versions [https://github.com/riescorp/feathers-auth-https-fail-private/blob/5a4e7898cf6fc85724720b3c7e43c8db2b9055cb/src/index.js#L6](https://github.com/riescorp/feathers-auth-https-fail-private/blob/5a4e7898cf6fc85724720b3c7e43c8db2b9055cb/src/index.js#L6)

Make sure you use a valid cert and key here: [https://github.com/riescorp/feathers-auth-https-fail-private/blob/5a4e7898cf6fc85724720b3c7e43c8db2b9055cb/src/index.js#L27-L28](https://github.com/riescorp/feathers-auth-https-fail-private/blob/5a4e7898cf6fc85724720b3c7e43c8db2b9055cb/src/index.js#L27-L28)

Start your app (`npm start`) and open [https://localhost:3030](https://localhost:3030)

Click on "Google", "Github" or "Facebook"

### Expected behavior
You should be redirected to Github Site but if you are not using the correct credentials you won't be able to actually log in.

Very similar for Google and Facebook

### Actual behavior
You see a 505 error when trying to load [https://localhost:3030/auth/github](https://localhost:3030/auth/github) and in the console you'll see `error: Unknown authentication strategy 'github'`

Very similar for Google and Facebook

### System configuration

**Module versions** 

```
MYPROMPT$ npm list --depth=0
feathers-auth-https-fail-private@0.0.0 ~/git/riescorp/feathers-auth-https-fail-private
├── @feathersjs/authentication@2.1.10
├── @feathersjs/authentication-jwt@2.0.4
├── @feathersjs/authentication-local@1.2.4
├── @feathersjs/authentication-oauth2@1.2.3
├── @feathersjs/configuration@2.0.2
├── @feathersjs/errors@3.3.2
├── @feathersjs/express@1.2.5
├── @feathersjs/feathers@3.2.1
├── @feathersjs/socketio@3.2.4
├── compression@1.7.3
├── cors@2.8.4
├── eslint@5.5.0
├── feathers-mongodb@3.3.0
├── helmet@3.13.0
├── mocha@5.2.0
├── mongodb@3.1.6
├── nodemon@1.18.3
├── passport-auth0@1.0.0
├── passport-facebook@2.1.1
├── passport-github@1.1.0
├── passport-google-oauth20@1.0.0
├── request@2.88.0
├── request-promise@4.2.2
├── serve-favicon@2.5.0
└── winston@3.0.0

MYPROMPT$
```
**NodeJS version**: v8.11.1

**Operating System**: Darwin 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

**Browser Version**: Chrome Version 69.0.3497.92 (Official Build) (64-bit)

**Module Loader**: npm 6.4.1

**Comment by daffl** [comment]
One of the problems might be that the default URL builder will only use HTTPS when `NODE_ENV` is set to `production`. If it is not you will have to set the complete redirect URLs yourself.

**Comment by nriesco** [comment]
@daffl but if I run the app like this: `NODE_ENV=production node src/` I see the same error.

I tried doing some debug and when ssl/https is on the passport object won't load the strategies. Adding `console.log(passport)` [here](https://github.com/feathersjs/authentication/blob/master/lib/passport/authenticate.js#L62) will show something like this:

```
Authenticator {
  _key: 'passport',
  _strategies:
   { session: SessionStrategy { name: 'session', _deserializeUser: [Function: bound ] } },
  _serializers: [],
  _deserializers: [],
  _infoTransformers: [],
  _framework: { initialize: [Function], authenticate: [Function] },
  _userProperty: 'user',
  _sm: SessionManager { _key: 'passport', _serializeUser: [Function: bound ] },
  Authenticator: [Function: Authenticator],
  Passport: [Function: Authenticator],
  Strategy: { [Function: Strategy] Strategy: [Circular] },
  strategies:
   { SessionStrategy: { [Function: SessionStrategy] super_: [Object] } },
  _feathers: {},
  createJWT: [Function: createJWT],
  verifyJWT: [Function: verifyJWT],
  options: [Function] }
```

and when running the non https version something like this:


```
Authenticator {
  _key: 'passport',
  _strategies:
   { session: SessionStrategy { name: 'session', _deserializeUser: [Function: bound ] },
     jwt:
      JwtStrategy {
        name: 'jwt',
        _secretOrKeyProvider: [Function],
        _verify: [Function: bound bound verify],
        _jwtFromRequest: [Function],
        _passReqToCallback: true,
        _verifOpts: [Object] },
     local:
      Strategy {
        _usernameField: 'email',
        _passwordField: 'password',
        name: 'local',
        _verify: [Function: bound bound verify],
        _passReqToCallback: true },
     facebook:
      Strategy {
        name: 'facebook',
        _verify: [Function: bound bound verify],
        _oauth2: [Object],
        ...
     google:
      Strategy {
        name: 'google',
        _verify: [Function: bound bound verify],
        _oauth2: [Object],
        ...
     github:
      Strategy {
        name: 'github',
        _verify: [Function: bound bound verify],
        _oauth2: [Object],
        ...
  _serializers: [],
  _deserializers: [],
  _infoTransformers: [],
  _framework: { initialize: [Function], authenticate: [Function] },
  _userProperty: 'user',
  _sm: SessionManager { _key: 'passport', _serializeUser: [Function: bound ] },
  Authenticator: [Function: Authenticator],
  Passport: [Function: Authenticator],
  Strategy: { [Function: Strategy] Strategy: [Circular] },
  strategies:
   { SessionStrategy: { [Function: SessionStrategy] super_: [Object] } },
  _feathers:
   { jwt:
      { name: 'jwt',
        bodyKey: 'accessToken',
        secret: 'xxxxxxxxxxxxxxxxxxxx',
        header: 'Authorization',
        entity: 'user',
        service: 'users',
        passReqToCallback: true,
        session: false,
        jwt: [Object] },
     local:
      { name: 'local',
        usernameField: 'email',
        passwordField: 'password',
        entity: 'user',
        service: 'users',
        passReqToCallback: true,
        session: false },
     auth0:
      { idField: 'auth0Id',
        path: '/auth/auth0',
        ...
      },
     facebook:
      { idField: 'facebookId',
        path: '/auth/facebook',
        __oauth: true,
       ...
        scopeSeparator: ',' },
     google:
      { idField: 'googleId',
        path: '/auth/google',
        __oauth: true,
        entity: 'user',
        ...
        callbackPath: '/auth/google/callback',
        authorizationURL: 'https://accounts.google.com/o/oauth2/v2/auth',
        tokenURL: 'https://www.googleapis.com/oauth2/v4/token' },
     github:
      { idField: 'githubId',
        path: '/auth/github',
        __oauth: true,
        ...
        callbackPath: '/auth/github/callback',
        authorizationURL: 'https://github.com/login/oauth/authorize',
        tokenURL: 'https://github.com/login/oauth/access_token',
        scopeSeparator: ',',
        customHeaders: [Object] } },
  createJWT: [Function: createJWT],
  verifyJWT: [Function: verifyJWT],
  options: [Function] }
```

**Comment by tweikiang** [comment]
i facing the same issue too, during my switch to https, even my local & jwt strategy not working

**Comment by daffl** [comment]
Indeed, when using [HTTPS as documented](https://docs.feathersjs.com/api/express.html#https) `app.setup(httpsServer)` *must* be called. Closing again since that should solve it.

**Comment by nriesco** [comment]
Thanks @tweikiang that indeed solved the issue in my case too.
