### ISSUE TITLE
infernojs npm run build error

### ISSUE THREAD

**Issue by sxwebdev** [feathersjs/feathers#1015]
I upgraded client packages to

```
"@feathersjs/authentication-client": "^1.0.6",
"@feathersjs/feathers": "^3.2.3",
"@feathersjs/socketio-client": "^1.1.4",
```
When I try to run build of infernojs app, i get next error
![image](https://user-images.githubusercontent.com/3129246/45903410-4b6d7500-bdf2-11e8-9f49-3bca22221a05.png)

My webpack prod config.
```js
{
            test: /\.(js|jsx)$/,
            exclude: /node_modules(\/|\\)(?!(@feathersjs))/,
            loader: require.resolve('babel-loader'),
            options: {
                  babelrc: false,
       		  plugins: ["transform-decorators-legacy"],
          	  presets: [require.resolve('babel-preset-env'),require.resolve('babel-preset-inferno-app')],
                  compact: true,
            },
}
```
Previously everything works as expected. I noticed this error right away in several projects

**Comment by daffl** [comment]
This is because of breaking changes in the `debug` module. Like Feathers and probably more module in the future it does not ship an ES5 build anymore. This means the build `exclude` should now be:

```js
exclude: /node_modules(\/|\\)(?!(@feathersjs|debug))/,
```

**Comment by sxwebdev** [comment]
> This is because of breaking changes in the `debug` module. Like Feathers and probably more modules in the near future it does not ship an ES5 build anymore. The issue can probably be fixed by updating the build `exclude` to:
> 
> ```js
> exclude: /node_modules(\/|\\)(?!(@feathersjs|debug))/,
> ```

Thank you! It helped me)

**Comment by sxwebdev** [comment]
It would be nice to update the documentation. [https://docs.feathersjs.com/api/client.html](https://docs.feathersjs.com/api/client.html)

![image](https://user-images.githubusercontent.com/3129246/45917932-b321cf80-be87-11e8-9e23-3fa58e0e91b0.png)

**Comment by daffl** [comment]
Done. I forgot to update it when I noticed that it was something that changed.
