### ISSUE TITLE
Bug in service generate > RethinkDb

### ISSUE THREAD

**Issue by andysay** [feathersjs/feathers#1016]
now service generate get  this 

`// Initializes the `transactions` service on path `/transactions`
const createService = require('feathers-rethinkdb');
const hooks = require('./transactions.hooks');

module.exports = function (app) {
  const Model = app.get('rethinkdbClient');
  const paginate = app.get('paginate');

  const options = {
    name: 'transactions',
    Model,
    paginate
  };

  // Initialize our service with any options it requires
  app.use('/transactions', createService(options));

  // Get our initialized service so that we can register hooks and filters
  const service = app.service('transactions');

  service.hooks(hooks);
};
`

webpack get error   const Model = app.get('rethinkdbClient');
                   ^

but need for work change on this >

module.exports = function () {

  const app = this;

**Comment by daffl** [comment]
This has been added in Feathers v3. Make sure you have the latest versions of everything (`feathers --version` should show `3.8.4` or later), I just successfully created a RethinkDB service with it.
