### ISSUE TITLE
What may be the reason for error 'passport.initialize() middleware not in use'

### ISSUE THREAD

**Issue by flight9** [feathersjs/feathers#1024]
While I integrate this oauth2 with lib 'passport-wechat', and visit `http://localhost:3035/auth/wechat` I got error 'passport.initialize() middleware not in use'.
I check this error is from some lines in 'passport-wechat':
```
if (!req._passport) {
    return this.error(new Error('passport.initialize() middleware not in use'));
  }
```
and why req._passport is undefined? Could anyone help?

### versions
"@feathersjs/authentication": "^2.1.7",
"@feathersjs/authentication-jwt": "^2.0.0",
"@feathersjs/authentication-local": "^1.1.0",
"@feathersjs/authentication-oauth2": "^1.2.4"
"passport-wechat": "^2.0.4"

**Comment by flight9** [comment]
It seems a problem in `passport-wechat`, and you can comment out the above lines and that lib can still work fine. I've made a new ticket https://github.com/liangyali/passport-wechat/issues/24 in `passport-wechat` for anyone has the same question to track.

**Comment by daffl** [comment]
This might still be Feathers related but would be easier to track down with a full example to reproduce the problem.

**Comment by flight9** [comment]
@daffl 
If you are interested in this, you can reproduce the error by following:
1. clone my previous project https://github.com/flight9/feathers-chat2 and npm install.
2. create a `config.js` file inside folder `src/modules/wechat/` with content like this:
```
module.exports = {
  appId: 'wx****df', // YOUR_WECHAT_APPID
  appSecret: '905****88', // YOUR_WECHAT_APPSECRET
  serverDomain: 'http://****.server.cc/',   // should be set in wechat dashboard
  clientDomain: 'http://****.client.cc/'  
};
```
NOTE In fact that error occurs before real oauth process, so you don't need a genuine wechat developing account, just offer some fake wechat info in above **** part.
3. visit: localhost:3035/auth/wechat
