### ISSUE TITLE
create-react-app build fails with @feathersjs/rest-client

### ISSUE THREAD

**Issue by dtwilliams** [feathersjs/feathers#1025]
### Steps to reproduce

- npx create-react-app feathers-bug
- cd feathers-bug/
- npm install @feathersjs/rest-client --save
- add `import rest from '@feathersjs/rest-client';` to index.js
- npm run build

### Expected behavior
Creating an optimized production build...
Compiled successfully.

### Actual behavior
> feathers-bug@0.1.0 build /Users/newcross/BitBucket/feathers-bug
> react-scripts build

Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/@feathersjs/rest-client/lib/base.js:2 

Read more here: http://bit.ly/2tRViJ9

### System configuration
package.json

{
  "name": "feathers-bug",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@feathersjs/client": "^3.7.3",
    "@feathersjs/rest-client": "^1.4.5",
    "react": "^16.5.2",
    "react-dom": "^16.5.2",
    "react-scripts": "1.1.5"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}

**Comment by daffl** [comment]
Please see the [section on create-react-app in the documentation](https://docs.feathersjs.com/api/client.html#create-react-app).

**Comment by dtwilliams** [comment]
thanks, i read that but didn't have any joy. I also tried https://github.com/feathersjs/rest-client/issues/14 but had no luck

apologies if i'm doing something stupid!

**Comment by daffl** [comment]
You might get a much smaller build just using `@feathersjs/client`. As [shown in the documentation for @feathersjs/client](https://docs.feathersjs.com/api/client.html#feathersjsclient) the modules you need are available as properties on the export of `@feathersjs/client`:

```
import feathers from '@feathersjs/client';

const { authentication, rest } = feathers;

const app = feathers().configure(rest()) /// etc.
```

**Comment by dtwilliams** [comment]
sweet! even better, cheers.
