### ISSUE TITLE
feathers-sequelize with hook update only selected columns.

### ISSUE THREAD

**Issue by suravdalyan** [feathersjs/feathers#1026]
Hi.
I have one issue:
Some users have admin role on my project.
They must have ability to  change dataes of other users.
My users model have a password field and I getting this error
"BadRequest: notNull Violation: users.password cannot be null",but if i set this "allowNull: true" password field is updateing automaticly but it must not update.
I tried to disable auto updating functionality and write my custom logic(with custom queries) for users data updating, but first mentioned found a crash.
I know, I can write a new class and don't use feathers-sequelize, but I don't need it.
Please give me an advice.

**Comment by daffl** [comment]
You have to use [patch](https://docs.feathersjs.com/api/services.html#patchid-data-params) to do partial updates, not `update` (which always replaces the entire object).

**Comment by suravdalyan** [comment]
Thanks for replying so fats.
I have change put method to patch and my functionality already working correctly.
Thank you, @daffl very much.
