### ISSUE TITLE
Oauth2 Social login(Facebook, Google) not work on Feathers API backend server, React frontend.

### ISSUE THREAD

**Issue by SeunghunSunmoonLee** [feathersjs/feathers#1027]
### Steps to reproduce

I've followed the oauth2 implementation tutorial for feathers but it's not working. it says invalid grant on google's response. After clicking my account google's sign in view, it successfully redirects to my frontend but there is no cookie or token frontend catches. On backend it says it's an invalid grant.

https://gist.github.com/SeunghunSunmoonLee/e8cf7328c0c414698ad3db9695ab8cac

backend is running on localhost:3030, frontend localhost:3000

I set up proxy on frontend as localhost:3030.

I would appreciate your help!

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**: v9.11.1

**Operating System**: mac high sierra

**Browser Version**: latest crome

**React Native Version**:

**Module Loader**:

**Comment by daffl** [comment]
This should be fixed with the new Feathers v4 oAuth authentication. See the [migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information.
