### ISSUE TITLE
[authentication-client] Remove non-shimmable ES6 features

### ISSUE THREAD

**Issue by petermikitsh** [feathersjs/feathers#1028]
### Steps to reproduce

- [X] Tell us what broke. The more detailed the better.
- [X] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc. This makes it much easier for us to debug and issues that have a reproducable example will get higher priority. **Not applicable here**

### Expected behavior

`@feathersjs/authentication-client` should work (without transpilation) in all major browsers, including [IE10 and up](https://docs.feathersjs.com/api/client.html) (per the docs).

### Actual behavior

`@feathers/authentication-client` uses non-shimmable ES6 features like [arrow functions](https://github.com/feathersjs/feathers/blob/master/packages/authentication-client/lib/hooks/populate-entity.js#L23) that do not work in IE11.

I see 3 options moving forward (and punt to maintainers to choose which):

- The library should be transpiled using `@babel/preset-env` (with the supported browsers specified using the [targets](https://babeljs.io/docs/en/babel-preset-env#targets))
- The code is manually inspected and non-shimmable ES6 features are replaced with their ES5 equivalents.
- Update the documentation to tell users they need to transpile the library themselves.

In my opinion, since the docs say IE10+ is supported, the appropriate choice would be either of the first two options, both of which leave us with shipping a module works out-of-the-box in IE10+.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working): Latest
**Operating System**: Windows 8
**Browser Version**: IE 11
**Module Loader**: Webpack

**Comment by daffl** [comment]
The [client documentation](https://docs.feathersjs.com/api/client.html) already points out, the modules have to be transpiled to the browser you want to support. Module loader configuration is documented [here](https://docs.feathersjs.com/api/client.html#module-loaders) and mentions:

> All modules in the @feathersjs namespace are using ES6. They must be transpiled to support browsers that don't completely support ES6. 

Usage of the pre-transpiled `@feathersjs/client` (that _does_ support IE10) is documented [here](https://docs.feathersjs.com/api/client.html#feathersjsclient).
