### ISSUE TITLE
featherjs + graphql

### ISSUE THREAD

**Issue by GlauberF** [feathersjs/feathers#1033]
Hello,
I have an application already in featherjs and would like to implement graphql for queries.
can someone tell me how to do this, what files should I change?

## Version
Feathers version  3.5.0

## BD
MongoDB with Mongoose

## Helpe me :)

**Comment by eddyystop** [comment]
Use the [graphql adapter](https://generator.feathers-plus.com/api/#service-adapters). If you need more examples of how to use that adapter, gen a small project including `generate grapgql` using [f+/cli](https://generator.feathers-plus.com/) and look at the code generated.
