### ISSUE TITLE
Service .create() doesn't return ids for array

### ISSUE THREAD

**Issue by fratzinger** [feathersjs/feathers#1036]
### Steps to reproduce

```
  await context.app.service("customers").create([{  
    email: "test@test.com",  
  }, {  
    email: "test2@test2.com"  
  }]).then(result => {  
    console.log(result);  
  });
```
shown `result` is an array with the newly created data. But each entries id is `null`. For me it would be really helpful if it returned data with the ids. Workaround as of today is to do a `.find()` afterwards but that takes some overhead which in my opinion is unnecessary.

When I create a single customer the resulting data has the correct id.

Is there a certain reason for this behaviour? Answers, suggestions, tips are highly appreciated.

### Expected behavior
Same behavior as if I create a single customer. `.create({email: "test@test.com"}).then(result => console.log(result));` -> result has `id`.

### Actual behavior
returning data `result` is an array of created objects which have the property: `id` but they are `null`

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
```
    "@feathersjs/configuration": "^2.0.4",
    "@feathersjs/errors": "^3.3.4",
    "@feathersjs/express": "^1.2.7",
    "@feathersjs/feathers": "^3.2.3",
    "@feathersjs/socketio": "^3.2.6",
    "feathers-hooks-common": "^4.17.10",
    "feathers-sequelize": "^3.1.2",
```

**NodeJS version**: v10.8.0

**Operating System**: Win10

**Browser Version**: Chrome 69

**Comment by daffl** [comment]
This is a database restriction when using `feathers-sequelize`. Only PostgreSQL allows to return the ids on `bulkCreate`. See https://github.com/sequelize/sequelize/issues/5466 and https://github.com/sequelize/sequelize/issues/2908

**Comment by fratzinger** [comment]
I'm using postgres. I will test it out. I searched for this but I didn't find anything. 

Sorry for your time and thank you very much! It's impressive and inspiring how much effort you put into this framework. You're amazing!

**Comment by daffl** [comment]
Thank you, I appreciate that 😄 Going to close this issue since I don't think it is something we can change in Feathers. Switching to PostgreSQL is probably the best solution to this problem.
