### ISSUE TITLE
Catch errors on connection initialization

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers#1037]
Some services in the generator currently use a promise to initialize that does not log the error. It would be nice to add a `promise.catch(error => console.error(error))` (or `logger.error`) that surfaces the error. This applies to

- Mongodb (https://github.com/feathersjs/feathers/blob/master/packages/generator-feathers/generators/connection/templates/mongodb.js#L15)
- RethinkDB (https://github.com/feathersjs/feathers/blob/master/packages/generator-feathers/generators/connection/templates/rethinkdb.js#L26)

**Comment by B1tF8er** [comment]
Can I help with this?

**Comment by IamRaviTejaG** [comment]
@daffl Please review the PR and merge if okay. 😄

**Comment by IamRaviTejaG** [comment]
@daffl For the above PR, Travis CI failed with the error that `console.error` is an unexpected console statement. What changes do you suggest here?!

**Comment by daffl** [comment]
Ah yes, it should indeed use the logger. At the top, the files add a `const logger = require('./logger');` and then use `logger.error(error)` instead of `console`

**Comment by IamRaviTejaG** [comment]
@daffl I don't see any file/dependency named `logger` anywhere. So, I believe the CI to fail even after doing what you suggested above. Correct me if I'm wrong.

**Comment by daffl** [comment]
There will be a generated `logger.js` in the same folder (see the `logger.js` in the [feathers-chat src/ folder](https://github.com/feathersjs/feathers-chat/tree/master/src)).
