### ISSUE TITLE
use feathers authentication & service within standalone express path

### ISSUE THREAD

**Issue by issy123** [feathersjs/feathers#1040]
### Comment/Problem

Hi,

I have created a new express url called 'uploads' using:

in app.js:
`app.use('/uploads',uploadHandler);`
the uploadHandler looks like this:
```javascript
var fs = require('fs');
var path = require('path');
const express = require('@feathersjs/express');
var uploadHandler = express();
uploadHandler.get('/', function (req, res) {
  res.download("/opt/coding/uploads/user/1/d2332d7-5055-4c5f-9aa5-ce9047d141df", 'test.png');
});
module.exports = uploadHandler;
```

The code works for downloading files, but now I want to use authentication and some feathers service for meta data (e.g. a database table holds the filename)

**question**: How can I use feathers authentication & services within a standalone express path?

### System configuration (optional)

Using: '@feathersjs/authentication', `Sequelize`

**NodeJS version**: v8.12.0

**Operating System**: Ubuntu 18.04

**Comment by issy123** [comment]
Ok here is my solution (probably far from optimal):

```javascript
var fs = require('fs');
var path = require('path');
var util = require('util');
const jwt = require('@feathersjs/authentication-jwt');
const express = require('@feathersjs/express');
var uploadHandler = express();
module.exports = function handler(app){
  uploadHandler.get('/', async function (req, res) {
    let auth = req.query.auth;
    let attachmentId = req.query.attachmentId;

    try{
      let passport = app.service('authentication');
      let authUser = await passport.verifyJWT(auth, passport._feathers.jwt);
      let user = await app.service('users').get(authUser.userId);
      let attachment = await app.service('attachments').get(attachmentId);
      
      res.download(attachment.filePath, attachment.filename);

    } catch(e) {
      res.status(404).end();
    }

  });
  return uploadHandler;
}
```

I need more info on how to do this correctly.

The auth is now passed in the get query (?auth=d1330od320d30o230d23d0o0o3d2)
verify auth is being done by using the verifyJWT method

**Comment by daffl** [comment]
That works. You could also use the [authentication Express middleware](https://docs.feathersjs.com/api/authentication/server.html#express-middleware). Usage is documented in the [SSR guide](https://docs.feathersjs.com/guides/auth/recipe.express-middleware.html).
