### ISSUE TITLE
whats the best way to implement passport-http

### ISSUE THREAD

**Issue by mohitmayank** [feathersjs/feathers#1046]
For some API endpoints, i would like to ask user his password again. What is the best way to do this. If there's way to implement http basic auth. for select methods, auth hook can allow only http basic auth. But I could not find any way to easily implement basic auth.

**Comment by mohitmayank** [comment]
I have created a crude version of http-basic auth with authentication-local code. 

https://github.com/mohitmayank/feathers-authentication-http-basic

**Comment by daffl** [comment]
Looks good, thank you for sharing!
