### ISSUE TITLE
Question on internal routing

### ISSUE THREAD

**Issue by nickerlan** [feathersjs/feathers#1056]
What is the best way to use one service endpoints from others?

e.g. i write: 

`app.use('/d/*', find(url,req) { ... }) `

and then parse url to get what I want from query.
Then I use it more like

`/d/sites/sitename.com/page1/?params`

now i want to call it from another endpoint.
It feels strange to do

`fetch("/d/sites/sitename.com/page1/?params")`

So I try around with 

```
#1 app.service('/d/sites/sitename.com/page1/?params')
#2 app.service('/d/*').find({route:{0:'/d/sites/sitename.com/page1/},query:{...params}}')
```

Option #1 doesnt find service
Option #2 works but looks ugly and requires me to choose function manually

Is there a way to do it properly?

Using nested endpoints logic I want to find a way to use it everywhere

**Comment by daffl** [comment]
The challenge is that Websockets (and most other non-HTTP protocols) don't really have a concept of routes. You can however use the (currently undocumented) `app.lookup` to get the route information:

```js
const { data, params } = app.lookup('/d/sites/sitename.com/page1/?params');

data.service // app.service('/d/*')
data.path // d/*
params // params.route
```
