### ISSUE TITLE
Shorthand for disabling service methods

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers#106]
I think it would be nice to be able to disable or specify that you **only** want certain default service methods to be enabled. Especially when using an existing service plugin (ie. mongoose, mongo, etc).

This can be obtained by extending the original service and then overriding the service methods and returning an error, like so:

```js
var service = Service.extend({
    create: function(data, params, callback){
      if (_.isFunction(params)) {
        callback = params;
        params = {};
      }
      
      callback(new app.errors.NotImplemented());
    }
});
```

However, I thought it would be really awesome to only enable certain service methods like this:

```js
var app = feathers();
var service = mongodb({ collection: 'users' });
app.use('/users', service.only(['find', 'get']));
```

**Comment by daffl** [comment]
I would think this is something the pre-build services or separate hooks should do. Probably be fairly simple, too:

```js
var onlyMixin = {
  only: function(...names) {
    var mixin = {};
    for(let name of names) {
      mixin[name] = function() {
        var callback = arguments[arguments.length - 1];
        callback(new errors.NotImplemented('Not allowed'));
      }
    }
    return this.extend(mixin);
  }
}
```

**Comment by ekryski** [comment]
Ya it's definitely the individual service's concern but I'd like to enforce that as a required method (ie. we'll need to document it for writing service plugins). I can go through and add the mixin to the services (since it is my feature request).

You're right that it doesn't belong in feathers core. I just wanted to bring it up in this repo so that we could discuss it in a more central place.

**Comment by marshallswain** [comment]
I think this needs to be in 1.1.0.  It goes along great with what we were talking about in #108.  I don't see why it shouldn't be in Feathers core.

**Comment by ekryski** [comment]
:+1:

**Comment by daffl** [comment]
I'm still a little hesitant about this but I can see the point and adding it as a plugin would be total overkill and somewhat pointless. I added it to 1.1.0 but suggest to go the other way around and disable methods (instead of telling it which ones to allow):

```js
var service = mongodb({ collection: 'users' });
app.use('/users', service);

app.service('users').disable('find', 'update');
```

In fact, we could even add the external flag mentioned [in the FAQ](http://feathersjs.com/faq/#toc5)

```js
app.use(function(req, res, next) {
  req.feathers.external = 'rest';
  next();
});

app.configure(feathers.socketio(function(io) {
  io.use(function(socket, next) {
    // For websockets the feathers object does not exist by default
    if(!socket.feathers) {
      socket.feathers = {};
    }

    socket.feathers.external = 'socketio';
    next();
  });
}));
```

By default and then use `.disable` to also conditionally disable methods:

```js
app.service('users').disable('find', function(params, callback) {
   if(params.external === 'rest') {
    return callback(null, false);
  }
  return callback();
});
```

**Comment by marshallswain** [comment]
Sounds good.  Adding the external flag by default will be quite convenient. :+1:

**Comment by ekryski** [comment]
I agree. Both sound great!

**Comment by daffl** [comment]
I'm going to bump this to 1.2 (or 2.0 whichever one comes first) unless it is a must have feature for you guys for 1.1. If not I think we're feature complete and can focus on the website and the guides.

**Comment by ekryski** [comment]
We ended up having a private discussion in Slack and it looks like the interface will actually just utilize hooks. So it would look something like this:

```js
// disable socketio provider on all todo service methods
app.service('todos').before(hooks.disable('socketio'));
// or
app.service('todos').before({
  all: hooks.disable('socketio')
});

// disable for other random use cases
app.service('todos').before(hooks.disable(function(hook) {
  return true/false/promise
}));

// disable specific methods
app.service('todos').before({
  patch: hooks.disable('socketio'),
  update: hooks.disable('socketio'),
  remove: hooks.disable('socketio')
}));


// disable any external transport calls (ie. REST, socket, or any future one)
app.service('todos').before({
  remove: hooks.disable()
}));
// or
app.service('todos').before({
  remove: hooks.disable('external')
}));

// disable any call including internal calls in code for remove
app.service('todos').before({
  remove: hooks.disable('all')
}));
```

**Comment by daffl** [comment]
To disable methods use the [disallow](https://feathers-plus.github.io/v1/feathers-hooks-common/#disallow) hook from [feathers-hooks-common](https://feathers-plus.github.io/v1/feathers-hooks-common).
