### ISSUE TITLE
@feathersjs/commons is using === to compare Symbols

### ISSUE THREAD

**Issue by elaijuh** [feathersjs/feathers#1062]
`===` comparison on Symbols will cause all hooks returning `SKIP` throwing an error here. I haven't checked all common hooks but `softDelete2` is one of them.

https://github.com/feathersjs/feathers/blob/c6e7e638c9d1c7978c018123768ece0ecc373228/packages/commons/lib/hooks.js#L118

**Comment by daffl** [comment]
It is comparing the actual instance, not the symbol. There is a difference between

```js
const mySymbol = Symbol('testing');

console.log(mySymbol === mySymbol); // true
```

And

**Comment by elaijuh** [comment]
Ah sorry, my problem is `@feathersjs/commons` version conflict which created 2 instances.
