### ISSUE TITLE
How use $contains with multiple query

### ISSUE THREAD

**Issue by andysay** [feathersjs/feathers#1064]
Hello, please who know give me answer ) 

How use $contains with multiple query 

like this ?param[$contains]=www&w3 - no
?param[$contains]=www&param[$contains]=w3 - no

**Comment by daffl** [comment]
This is now possible with `feathers-rethinkdb` version 0.5.4 or later.

**Comment by andysay** [comment]
@daffl thanks , but if we have 

{

  "id": "b1cfb84a-9ce0-4c41-a4b3-ef9959bcaa87",

  "param": [
    "www",
    "w3"
  ],

}

#### Another object in this table

{

  "id": "11cfb84a-9ce0-4c41-a4b3-ef9959bcadsw2",

  "param": [
    "w4"
  ],

}

and try ?param[$contains]=w4&param[$contains]=w3 - we nothing found , 

but now after update work like this ?param[$contains]=www&param[$contains]=w3

**Comment by daffl** [comment]
For nested queries you have to [create a customized query](https://github.com/feathersjs-ecosystem/feathers-rethinkdb/#customizing-the-query) yourself.
