### ISSUE TITLE
authentication-client does not re-authenticate on reconnect with socket when custom verifier throw error

### ISSUE THREAD

**Issue by hong-duc** [feathersjs/feathers#1067]
### Steps to reproduce
- I have a feathers server with socket, auth plugin
- In auth.js file I use `@feathersjs/authentication-jwt` and `@feathersjs/authentication-local` strategy with custom verifier
- On client first time login use `local strategy` -> success -> shutdown server and restart -> client reconnect and re-authenticate with `jwt strategy`-> On server in jwt custom verifier I throw an error -> then I shutdown and restart server again -> client reconnect but not re-authenticate again.
- The client should re-authenticate when reconnect everytime, even when the server throw error last time it re-authenticate

### Expected behavior
The client should re-authenticate when reconnect everytime

### Actual behavior
The client not re-authenticate

### System configuration

**Module versions** (especially the part that's not working):
@feathersjs/authentication-client: ^1.0.6
**NodeJS version**:
8.11.1
**Operating System**:
Manjaro Linux
**Browser Version**:
Version 70.0.3538.67 (Official Build) Arch Linux (64-bit)

**Comment by daffl** [comment]
This should be fixed in Feathers v4 authentication. See the [Migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information on how to upgrade.
