### ISSUE TITLE
$in with single query parameter

### ISSUE THREAD

**Issue by eakarpov** [feathersjs/feathers#1071]
### Steps to reproduce

Feathers does not parse single $in patameter in query correctly.

/service?prop[$in]=4&prop[$in]=10 - this works correctly ( prop: { $in: [4, 10] } )
/service?prop[$in]=4 - this fails with error (value.map is not a function) -  prop: { $in: '4' }

- [x ] Tell us what broke. The more detailed the better.

### Expected behavior
Expected to parse as the following: prop: { $in: [4] }

### Actual behavior
Query string with $in parameter is parsed as a simple string:  prop: { $in: '4' }

### System configuration

Tell us about the applicable parts of your setup.

**Module versions**: 
@feathersjs/feathers: ^3.1.7
feathers-sequelize: ^3.1.2

**NodeJS version**: 8.11.4

**Operating System**: ubuntu 18.04

**Browser Version**: postman 6.4.4

**Module Loader**: webpack 4.16.5

**Comment by daffl** [comment]
To indicate an array with one entry, [qs](https://www.npmjs.com/package/qs) will look for a `[]` so it would be `/service?prop[$in][]=4`
