### ISSUE TITLE
Express: The app.configure() function has been removed.

### ISSUE THREAD

**Issue by leoj3n** [feathersjs/feathers#1090]
In Express 4, the `.configure` function [was removed](https://expressjs.com/en/guide/migrating-4.html#other-changes), but it seems [`@feathersjs/express`](https://github.com/feathersjs/feathers/tree/master/packages/express) still uses it.

Looking at the `package.json` of `@feathersjs/express`, I see [express@4](https://github.com/feathersjs/feathers/blob/master/packages/express/package.json#L41) is being used, but nowhere in the project do I see anything wiring up `configure`, so I'm just wondering how `configure` is implemented and if it's different from Express 3's `configure` function?

It can be a little confusing, and I had to rework some parts of my app when removing feathers support because configure is not a function (essentially I just ended up passing `app` around manually, which is something I wonder would work with `@feathersjs/express` and avoid a `configure` function).

**Comment by daffl** [comment]
[app.configure](https://docs.feathersjs.com/api/application.html#configurecallback) is a core Feathers specific method and documented as such and also explained in more detail [in the basics guide](https://docs.feathersjs.com/guides/basics/generator.html#configure-functions). It is needed to extend the application especially when it comes to handling websocket connections. I believe it works the same as in Express 3 Feathers has been relying on Express 4 ever since it got released out almost five years ago.

**Comment by leoj3n** [comment]
Okay, we can close this then. Maybe consider adding a note to `@feathersjs/express` that the `configure` function is not the same as was removed from Express 3 and is core to Feathers.

Thanks.

**Comment by daffl** [comment]
Side note, the polyfill for this functionality is fairly straightforward (see https://github.com/feathersjs/feathers/blob/a38eddb6c99d41047af859955acf9c86b3369122/packages/feathers/lib/application.js#L58-L62):

```js
app.configure = function (fn) {
  fn.call(this, this);
  return this;
}
```

That's pretty much all it does.

**Comment by bertho-zero** [comment]
@daffl Have you ever thought about doing a PR to add this method to Express?

**Comment by daffl** [comment]
It used to be included in old versions of Express but got deprecated in favour of using only middleware (and passing the app around in a function if necessary). It's still useful for Feathers though because it makes it easier to set up websockets and other transports that don't rely on middleware.
