### ISSUE TITLE
Wrong status code on nested routes

### ISSUE THREAD

**Issue by christiansaiki** [feathersjs/feathers#1096]
### Steps to reproduce
Hey guys, I'm loving to use feathers. It's really awesome :)
I'm using a nested route `/credential-requests/:id/credential`
And when I'm throwing the error I'm receiving 500 in the response. This behavior is only happening for nested routes
```javascript
const { NotFound } = require('@feathersjs/errors');

const { credentialRequests: credentialRequestsServiceName } = require('../../routes');

async function getCredentialRequest(context) {
  const { id } = context.params.route;

  const credentialRequestsService = context.app.service(credentialRequestsServiceName);
  try {
    const credentialRequest = await credentialRequestsService.get(id, {
      query: {
        $select: ['credentialId']
      }
    });
    // eslint-disable-next-line no-param-reassign
    context.credentialRequestId = id;
    // eslint-disable-next-line no-param-reassign
    context.params.query = {
      id: credentialRequest.credentialId
    };
  } catch (error) {
    throw new NotFound('Please check your credential request id');
  }
}
```

![image](https://user-images.githubusercontent.com/7768082/48666027-2ff4b280-eaa1-11e8-9e52-5608a72e24d9.png)

### Expected behavior
To get the proper error status code

### Actual behavior
I'm getting always 500

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working): @feathersjs/feathers@3.2.3

**NodeJS version**: v10.10.0

**Operating System**: MacOS High Sierra

Thank you so much!

**Comment by daffl** [comment]
Thank you! I feel [this FAQ](https://docs.feathersjs.com/faq/readme.html#why-am-i-not-getting-json-errors) might be related. You are using the `errorHandler` and do get JSON formatted errors with the right status code for any other service?

**Comment by christiansaiki** [comment]
Hey, @daffl thanks for the quick reply.
Yes, I'm using the express errorHandler and I'm getting the right statusCode with JSON formatted errors for any other service except for this one that's the only one with a nested route.

**Comment by daffl** [comment]
I created a test in #1106 and it looks like it is working as expected. The problem may be somewhere else in your application.
