### ISSUE TITLE
Multiple Rest Clients

### ISSUE THREAD

**Issue by tim-field** [feathersjs/feathers#1102]
Hi I'm trying to have my service A use remote services B and C should this be possible?  It works perfectly if I just have service B, but fails with `Only one default client provider can be configured` once I add service C.

I've tried various invocations of `use` and `configure`  without any luck 

```
const B = rest("http://localhost:3030")
const C = rest("http://localhost:3080")

const requestClient = request.defaults({})

const app = express(feathers())
  .use(express.json())
  .use(express.urlencoded({ extended: true }))
  .use(cors())
  .configure(B.request(requestClient))
  .configure(C.request(requestClient))
  .configure(express.rest())
  .configure(A)
  .use("/", (req, res) => {
    res.json({ service: "period-report", status: "running" })
  })
```

Thanks

**Comment by tim-field** [comment]
Is there no way to do this natively ?

**Comment by daffl** [comment]
The REST clients are just normal services themselves and can be registered directly. They require a `connection` (reference to the transport library), `name` and `base`:

```
const superagent = require('superagent');
const SuperAgentClient = require('@feathersjs/rest-client/lib/superagent');

app.use('/users', new SuperAgentClient({
  connection: superagent,
  name: 'users',
  base: 'http://myotherFeathersServer.com'
});
```

**Comment by tim-field** [comment]
Thanks @daffl that worked.  This is quite different from the example here https://docs.feathersjs.com/api/client/rest.html#restbaseurl

So it seems one should only use `@feathersjs/rest-client` when a single rest service will be used?

**Comment by daffl** [comment]
Going to reopen because I did want to make it a little easier to instantiate separate clients. Right now, only the main single client usage is documented. Not sure how the API would look like yet though.

```js
const server1 = rest('http://feathers-api1.com')
const server2 = rest('http://feathers-api2.com')

app.use('/users', server1.superagent('/users', superagent));
app.use('/messages', server2.superagent('/messages', superagent));
```

**Comment by tim-field** [comment]
@daffl is the above an example of something that should work now, or a design goal?

But what I would like to know is if I can call a sub service of one of these registered services. 
```JS
.use(
    "/foo",
    new requestClient({
      connection: request,
      name: "foo",
      base: "foo-ap1.com"
    })
  )
```

Lets say my `foo` api ( which is now a service used in this api ) internally has a number of services  which I'd call like so `foo-ap1.com/users` if accessing directly.   How do I use the these services here ? 

I was hoping that in my app I could  `

```JS
const fooService = app.use('foo')
const fooUsersService = fooService.use('users')   // users is a sub service of foo
```
Or am I way off track? Would I instead need to register each sub service in my client ?

```JS
.use(
    "/foo-users",
    new requestClient({
      connection: request,
      name: "users",
      base: "http://ap1.com" // note same api URI here
    })
  )
.use(
    "/foo-products",
    new requestClient({
      connection: request,
      name: "products",
      base: "http://ap1.com" // note same api URI here
    })
  )
```

**Comment by daffl** [comment]
I just realized that this has been possible for years already. Now documented at https://docs.feathersjs.com/api/client/rest.html#connecting-to-multiple-servers
