### ISSUE TITLE
Share object to service 

### ISSUE THREAD

**Issue by bilicio** [feathersjs/feathers#1104]
Hey @daffl , just a question if you can help me. 
I need to share an object to a service (rest) to use in find method. The object is in (app.js). how do i send this object to be used inside the service (newdb.class.js) ? i tried a lot of options like, putting the object inside app with app.set, and using module.export but none of them work. do you have any tips to do that?

thank you!

**Comment by bilicio** [comment]
sorry to bother you with this, no rush, anytime . :)

**Comment by daffl** [comment]
I'm not sure I follow. If you need access to the `app` in a service you can implement the [setup method in your service](https://docs.feathersjs.com/api/services.html#setupapp-path).

**Comment by bilicio** [comment]
I think i wasn't clear enough sorry, but sort of. im my app.js i have all feathers configuration like this.
All the libs and configurations

`const middleware = require('./middleware');
const services = require('./services');
const appHooks = require('./app.hooks');
const channels = require('./channels');

const app = express(feathers());

// Load app configuration
app.configure(configuration());
// Enable CORS, security, compression, favicon and body parsing
app.use(cors());
app.use(helmet());
app.use(compress());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(favicon(path.join(app.get('public'), 'favicon.ico')));
// Host the public folder
app.use('/', express.static(app.get('public')));`

etc

then i start my gun server (i needed start gun outside the service because it wasnt syncing)

with this

`const gun = new Gun(config); `

then i use the feathers generate service to create a service for gun.

now i need to retrive this 'const gun' inside my service.

**Comment by daffl** [comment]
`app.gun = gun` or `app.set('gun', gun)` and implementing the `setup` method as shown in the link will give you access to `this.app.gun` or `this.app.get('gun')` in the service.

**Comment by bilicio** [comment]
awesome David! thank you!!
