### ISSUE TITLE
Service life-cycle events (setup and clean)

### ISSUE THREAD

**Issue by KrishnaPG** [feathersjs/feathers#1107]
When service starts, it gets a chance to setup the resources using the `setup` method. What is the method to `cleanup` the resources, when the service is no more available?

For example, when the server is stopped, or process is about to exit, would like to cleanup the resources being consumed by the service (such as database connections etc.).

````
class Service {
	constructor(options) {
	}
	setup(app, path) {
          // the initialization of database connections etc.
        }
        cleanup() {
           // release / disconnect the database connections etc.
        }
};
module.exports = function init(options) {
	return new Service(options);
};

// index.js
const server = app.listen(port, host);
const exitHook = require('exit-hook');
exitHook(() => {
   server.close();
   // for each service in the feathers, do cleanup. How ????
});
````

**Comment by daffl** [comment]
There currently is no app level teardown method but your services could implement a custom `teardown` method to call for each service by going through [app.services](https://docs.feathersjs.com/api/application.html#services):

```js
exitHook(() => {
   server.close();
   Object.keys(app.services).forEach(path => {
     const service = app.service(path);
     if(typeof service.teardown === 'function') {
       service.teardown();
     }
   });
});
```

**Comment by KrishnaPG** [comment]
Thanks @daffl 

I realized that some of the services are using adapters such as feathers-mongodb etc. And many of them are do not have cleanup code inside them.

As Feathers keep growing and more adapters / services are being built, I think it would be good idea if a built-in function (similar to `setup`) was provided as a framework level method, so that all adapters can take care of their own resource cleanup in a graceful manner.
