### ISSUE TITLE
How to query 'and' and 'or' together in feathers query ?

### ISSUE THREAD

**Issue by issy123** [feathersjs/feathers#1109]
How can i query multiple 'and' and 'or' in feathers?

I have three conditions that could return results:

- column 'startDate' is greater or equal to startOfYear2020 **AND** 'startDate' is lower or equal to endOfYear2020

**OR**
- column 'endDate' is greater or equal to startOfYear2020  **AND**  'endDate' is lower or equal to endOfYear2020

**OR**
- column 'startDate' is lower than startOfYear2020 **AND** 'endDate' is greater than endOfYear2020

**What I tried**
```javascript
service.find({
  query: {
    userId: userId,
    $sort: {
      id: -1
    },
    $or: [{
     startDate: {
        $gte: startOfYear2020
      },
      startDate: {
        $lte: endOfYear2020
      }
    }]
  }
});
```

**What I found doing research**

https://github.com/feathersjs-ecosystem/feathers-swift/issues/26

With no answer

**Comment by edwardsmarkf** [comment]
should this question be asked in the sequelize forum?
