### ISSUE TITLE
Missing flatmap-stream dependency - Failing to install

### ISSUE THREAD

**Issue by aaaee2** [feathersjs/feathers#1111]
npm install fails due to a dependency not resolving.
The dependency is flatmap-stream and appears to no longer exist in the npm repository.
https://www.npmjs.com/package/flatmap-stream

Expected behaviour
@feathersjs/feathers should install

Actual behaviour
@feathersjs/feathers failed to install with the following error:

> npm ERR! code E404
> npm ERR! 404 Not Found: flatmap-stream@0.1.1

Steps to reproduce
Just run:
`% npm i @feathersjs/feathers`

**Comment by bertho-zero** [comment]
I have the same issue, this block my deploiement.

**Comment by daffl** [comment]
That module has been removed due to [a security issue](https://www.npmjs.com/advisories/737). Feathers itself and none of the official modules depend on it however. It is probably caused by another dependency.
