### ISSUE TITLE
Support for express-jwt-authz

### ISSUE THREAD

**Issue by yeager-j** [feathersjs/feathers#1114]
I am following the auth0 guide here: https://auth0.com/docs/architecture-scenarios/spa-api/api-implementation-nodejs

I could be mistaken, but I don't see any feathers documentation that supports this:

```javascript
// set dependencies - existing code omitted
const jwtAuthz = require('express-jwt-authz');

// Enable CORS - code omitted

// Create middleware for checking the JWT - code omitted

// Enable the use of request body parsing middleware - code omitted

// create timesheets API endpoint
app.post('/timesheets', checkJwt, jwtAuthz(['create:timesheets']), function(req, res){
  var timesheet = req.body;

  // Save the timesheet to the database...

  //send the response
  res.status(201).send(timesheet);
})

// launch the API Server at localhost:8080 - code omitted
```

The code `jwtAuthz(['create:timesheets'])` checks if the incoming JWT has the `create:timesheets` scope.

**Comment by daffl** [comment]
Your example is purely Express. Since Feathers is fully compatible with Express the middleware should work as shown.
