### ISSUE TITLE
How to receive user object after authenticated

### ISSUE THREAD

**Issue by SeaDog505** [feathersjs/feathers#1116]
I try to get full document without password the user has been logged but I don't know how it do it. 
I use feathers-authentication

    `app.authenticate({
        strategy: 'jwt',
        accessToken: token
     }).then(response => {

          // I want here the document (response) but I receive only accessToken

      });`

I tried also with channels but isn't work  me app.emit() to client. Maybe it will be better solution with unique channel for user? Please help.

**Comment by daffl** [comment]
This is [documented in the authentication client example](https://docs.feathersjs.com/api/authentication/client.html#complete-example).

**Comment by SeaDog505** [comment]
I read it more times. I receive only accessToken. I'm not sure I'm doing it right but my authenticate is by client side. I'm using:

    <script type="text/javascript" src="//unpkg.com/feathers-client@^2.0.0/dist/feathers.js"></script>
    <script type="text/javascript" src="//unpkg.com/socket.io-client@1.7.3/dist/socket.io.js"></script>

**Comment by daffl** [comment]
It's right in the docs I linked:

```js
const feathers = require('@feathersjs/feathers');
const rest = require('@feathersjs/rest-client');
const auth = require('@feathersjs/authentication-client');

const superagent = require('superagent');
const localStorage = require('localstorage-memory');

const feathersClient = feathers();

feathersClient.configure(rest('http://localhost:3030').superagent(superagent))
  .configure(auth({ storage: localStorage }));

feathersClient.authenticate({
  strategy: 'local',
  email: 'admin@feathersjs.com',
  password: 'admin'
})
.then(response => {
  console.log('Authenticated!', response);
  return feathersClient.passport.verifyJWT(response.accessToken);
})
.then(payload => {
  console.log('JWT Payload', payload);
  return feathersClient.service('users').get(payload.userId);
})
.then(user => {
  feathersClient.set('user', user);
  console.log('User', feathersClient.get('user'));
})
.catch(function(error){
  console.error('Error authenticating!', error);
});
```

**Comment by SeaDog505** [comment]
Yes I see that. Can you tell me how can I used this example?  Where?

For example, I have a index.html and script.js. In my script is below code:

$('.form-signin').submit(function(){
		
		app.authenticate({
			strategy: 'local',
			email:		$('#inputEmail').val(),
			password:	$('#inputPassword').val()
			}).then(result => {
                        // Here is load content and my result is only accessToken
                        
                    });

Where I should using your code by server side?

**Comment by daffl** [comment]
I updated my example

**Comment by SeaDog505** [comment]
that's what I wanted. Thanks a lot daffl
