### ISSUE TITLE
Guidance: Best place to instrument feathers

### ISSUE THREAD

**Issue by RickEyre** [feathersjs/feathers#1117]
I'm currently in the process of instrumenting my Feathers app with Newrelic. I'm using Primus and realtime. I'm wondering if there is any suggestions on where the best place to hook into Feathers to instrument it are?

I'm currently doing something like this with the Primus object after Feathers has configured it.

```js
import dotprop from 'dot-prop-immutable';
import { isNil } from 'lodash';
import newrelic from 'newrelic';

const isRequest = type => (
  type === 0
);

const isSupportedMethod = method => (
  ['find', 'get', 'create', 'update', 'patch', 'remove'].includes(method)
);

const toHttpMethod = method => ({
  find: 'get',
  get: 'get',
  create: 'post',
  update: 'put',
  patch: 'patch',
  remove: 'delete'
})[method];

const getRequestParts = request => {
  try {
    const json = JSON.parse(request);

    if (isRequest(json.type)) {
      return {
        method: dotprop.get(json, 'data.0'),
        url: dotprop.get(json, 'data.1'),
        id: dotprop.get(json, 'id')
      };
    }

    return { id: dotprop.get(json, 'id') };
  } catch (error) { // It's not an error to receive non-json requests.
    return {};
  }
};

export const monitor = primus => {
  primus.on('connection', spark => {
    const transactions = {};

    spark.on('incoming::data', request => {
      const { url, id, method } = getRequestParts(request);
      if (isNil(url) || isNil(id) || !isSupportedMethod(method)) {
        return;
      }
      newrelic.startWebTransaction(`${toHttpMethod(method)} ${url}`, () => {
        transactions[id] = newrelic.getTransaction();
      });
    });

    spark.on('outgoing::data', request => {
      const { id } = getRequestParts(request);
      if (isNil(id)) {
        return;
      }
      const transaction = transactions[id];
      if (transaction) {
        transaction.end();
        delete transactions[id];
      }
    });
  });
};
```

One of the issues is because I'm not wrapping the Feathers call that runs the service method, Newrelic doesn't pick up any instrumentation for accessing my database, etc. 

I'm also checking the 'type' being sent on the socket. Type 0 seems to be a request and 1 is a response? Is that correct?

I'm sure there is a better way than this?

**Comment by daffl** [comment]
The best way to profile Feathers methods calls are [application level hooks](https://docs.feathersjs.com/api/hooks.html#application-hooks). If you are not doing anything outside of that it should pick up everything you need. Doesn't Newrelic have any more high level monitoring that doesn't require to fake out HTTP methods?

**Comment by eddyystop** [comment]
There is also @feathers-plus/feathers-profiler.

**Comment by daffl** [comment]
The Feathers way for this would look like this:

```
app.hooks({
  async before(context) {
    return new Promise((resolve, reject) => {
      newrelic.startWebTransaction(`${toHttpMethod(context.method)} ${context.path}`, error => {
        if (error) {
          return reject(error);
        }

        context.transaction = newrelic.getTransaction();

        resolve(context);
      });
    });
  },

  async after (context) {
    if(context.transaction) {
      context.transaction.end();
    }

    return context;
  }
});
```

This will indeed not profile any low-level websocket infotmation but it doesn't look like this is really something NewRelic is set up for anyway. It will however cover the 90% case to get profiling information in the likely bottlenecks, somewhere in your service/database calls and apply to any way the call is made (REST, websockets etc.).
