### ISSUE TITLE
"Before find hook" triggering infinite loop when using async call

### ISSUE THREAD

**Issue by VladWulf** [feathersjs/feathers#1120]
### Steps to reproduce

So the problem appears when you try to put filtering conditions in the "before find hook".
Let's say that you want to replace the default data returned by find based on what you have in a database.

I've pushed a repo with the bug so you can test. Start the server and make a GET request with postman to http://localhost:3030/users
https://github.com/VladWulf/feathers-bug

```javascript
module.exports = {
  before: {
    all: [],
    find: [async context => {
      console.log('hello')
      const users = await context.app.service('users').find({
        query: {
          first_name: "Vladimir"
        }
      })
      console.log(users)
    }],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  },

  after: {
    all: [],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  },

  error: {
    all: [],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  }
};

```
it will print "hello" an infinite amount of time

### Expected behavior
Not produce an infinite loop and print the object that is registered in the database in the console

### Actual behavior
Infinite loop in the console and the request is not returning

**Comment by daffl** [comment]
As with any recursive self-referential call you need a breaking condition or somehow indicate that it shouldn't keep calling itself, e.g. by adding a `runHook` flag in `params`:

```js
module.exports = {
  before: {
    all: [],
    find: [async context => {
      if (!context.params.runHook) {
        console.log('hello')
        const users = await context.app.service('users').find({
          runHook: false,
          query: {
            first_name: "Vladimir"
          }
        })
        console.log(users)
      }
    }],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  },

  after: {
    all: [],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  },

  error: {
    all: [],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  }
};
```

**Comment by VladWulf** [comment]
Ah, I didn't realise that hooks were also firing when you were calling a service function outside of the "rest" context.
While the solution is not very elegant, it works.
Thanks @daffl
