### ISSUE TITLE
How to set three fields as local login?

### ISSUE THREAD

**Issue by olaferlandsen** [feathersjs/feathers#1126]
Well, this is not a bug, is a question about login strategy.
In my case, I wanna login with three fields: user, pass and domain.
How I can set the third field on configuration?

I don't see anything [Authentication Docs](https://docs.feathersjs.com/api/authentication/local.html#local-authentication)

Thanks

**Comment by rafamedina** [comment]
I think there's not a natural way for that.
It invokes the find only with the usernameField
Ref: https://github.com/feathersjs/authentication-local/blob/master/lib/verifier.js#L72

What about sending in the usernameField "domain\username"?
Or if you want to send them separated, you could concatenate domain and user using a hook 
```javascript
  //auth.js
module.exports = function (app) {
  const config = app.get('authentication');
  app.configure(authentication(config));
  app.configure(jwt());
  app.configure(local());
  ...

  const concatenateDomainAndUser= context => {
    context.data = `${context.data.domain}\\${context.data.user}`
  }

  app.service('authentication').hooks({
    before: {
      create: [
        concatenateDomainAndUser,
        authentication.hooks.authenticate(config.strategies)
      ],
      remove: [
        authentication.hooks.authenticate('jwt')
      ]
    }
  });
}
```

And then process them with a [Custom Verifier](https://docs.feathersjs.com/api/authentication/local.html#verifier) if you need match them against a LDAP

**Comment by olaferlandsen** [comment]
thanks @rafamedina thanks too much
Gracias!

**Comment by rafamedina** [comment]
No problem Sir,
By the way, did you find another solution? hahahaha
