### ISSUE TITLE
Authenticate hook with multiple Passport strategies

### ISSUE THREAD

**Issue by jawadst** [feathersjs/feathers#1128]
@## Expected behavior
Passport allows multiple strategies to be provided to the `authenticate` call: `authenticate(['strategy1', 'strategy2', etc.], ...)` (https://stackoverflow.com/questions/20745296/passport-js-with-multiple-authentication-providers)

The `authenticate` hook allows providing multiple strategies but only uses the first one when that is the case: https://github.com/feathersjs/feathers/blob/master/packages/authentication/lib/hooks/authenticate.js#L28

### Actual behavior
Feathers should pass the list of strategies provided to the hook as is to allow multiple Passport strategies to be used.

Would you accept a MR that does that?

**Comment by EliSadaka** [comment]
This issue still hasn't been resolved. I was able to come up with a workaround for my use case, but it's not ideal:
```
iffElse((context) => { context.params.provider == "rest" },
    [authenticate("apiKey")],
    [authenticate("jwt")]
)
```

**Comment by daffl** [comment]
This has been addressed in Feathers v4 authentication which allows to register multiple strategies (and different services). See the [Migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information on how to upgrade.
