### ISSUE TITLE
saving data into multiple databases

### ISSUE THREAD

**Issue by vylink** [feathersjs/feathers#1136]
Hi,

I have built an app with Feathers.js and I'm trying to find the way, how can I save any record to the multiple databases? I would like to save a "message" for example to the mysql and also to the elastic search.

I would like to use elastic search for "full text" search, but I would also like to have all data saved in some relational database.

I've created a service using:

feathers generate service

but I can select only one specific database there.

Any help will be really appreciated.

**Comment by daffl** [comment]
There are several different ways to do this. You could listen to [service events](https://docs.feathersjs.com/api/events.html#service-events) and replicate the data or do the same in an after `create`, `patch`, `update` and `remove` [hook](https://docs.feathersjs.com/api/hooks.html) or create [your own service](https://docs.feathersjs.com/api/services.html#) that connects to both databases. As long as the ids are the same it should be fairly straightforward though:

```js
app.service('mainservice').hooks({
  after: {
  }
