### ISSUE TITLE
FacebookId null will try to create user but email does exist so it will give error 500

### ISSUE THREAD

**Issue by emeagenciadigital** [feathersjs/feathers#1137]
HI, i got this issue using feathers oauth 2 facebook strategy.

When a user creates himself with local strategy and then wants to login with facebook, a error 500 shows. The reason is that Facebook will look for the facebookId on the users entity and as the user don't have it it will try to create him but the user email does exist so it will throw a error.

If I create the user for the first time with facebook y will not have any issue.

**Comment by daffl** [comment]
You need to add the email to the oAuth scope and [customize the oAuth response](https://docs.feathersjs.com/api/authentication/oauth2.html#customizing-the-oauth-response) to find the right user.
