### ISSUE TITLE
Route param variables with feathers client

### ISSUE THREAD

**Issue by aronsuarez** [feathersjs/feathers#1138]
How can i add route params to a request sent with feathers-rest-client?

I have the following service on the server:

app.use('/messages/:messageId', serviceXY);

On the client i setup with this the service with this url '/messages/:messageId', now how can i set the :messageId on the client to send the request to the server like this, /messages/76232492?

On the server, i god this object in the params {query: {}, route:{messageId:':messageId'}}, how can i set :messageId?

Thanks for help

**Comment by daffl** [comment]
Use the URL you want to request (`/messages/76232492`), not `'/messages/:messageId'`

**Comment by aronsuarez** [comment]
Sorry, my question was unclear. I want to set this parameter dynamically on every request.

**Comment by daffl** [comment]
It's the same as you would do with any HTTP library. Create the URL dynamically:

```js
const getService = messageId => {
  return app.service(`/messages/${messageId}`);
}
```

Note that real-time updates are currently only available at `app.service('/messages/:messageId')` and [this FAQ](https://docs.feathersjs.com/faq/readme.html#how-do-i-do-nested-or-custom-routes) on why we recommend using query parameters instead of parameterized routes.

**Comment by daffl** [comment]
There might also be a misunderstanding on how services work because a `messages/<id>` route will be set up for you automatically (for the mapping between routes and services see [this documentation](https://docs.feathersjs.com/api/client/rest.html#http-api))

**Comment by aronsuarez** [comment]
Thanks for the answer, my example was not so good sorry about that. This with the autogenerated routes is clear my question is more for routes line that. /support/:userId/tickets/:ticketId.

I wiml read now this f
FAQ first. Sorry about my unclear question, it's a little late in my timezone.
