### ISSUE TITLE
Add debug module and messages

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers#114]
Add the [debug module](https://www.npmjs.com/package/debug) and debug messages for feathers core (and probably all official plugins, too). Because it is super helpful and easy to use.

**Comment by marshallswain** [comment]
You mind if we leave this open?  I'd like to add documentation for this in the readme.

**Comment by daffl** [comment]
Can you open another issue or PR? Should it look like http://expressjs.com/guide/debugging.html?

**Comment by marshallswain** [comment]
Yeah.  Thanks for showing me that.  I'll see if I notice anything else that needs to be in it.

**Comment by daffl** [comment]
I would say for now it should just be a point in the FAQ at https://github.com/feathersjs/feathers/blob/gh-pages/faq.md until we figure out what the new website is going to look like.

**Comment by marshallswain** [comment]
Sounds good.  Just a list of available debug options with a basic example of how to turn them on/exclude some should be enough I think.
