### ISSUE TITLE
Authentication with third party system, the right way!

### ISSUE THREAD

**Issue by shomalgan** [feathersjs/feathers#1143]
Imagine a particular architecture that uses a third-party web service to log in.
When a username and password are sent, a third-party web-service is called instead of a local database query.
The third-party web service only returns TRUE/FALSE in response.
What is the right way to do this?
Can I use feathers local authentication strategy to handle this situation?

**Comment by shomalgan** [comment]
Finally, I used custom strategy & custom verifier in my case.
[](https://github.com/feathersjs-ecosystem/feathers-authentication-custom)

**Comment by daffl** [comment]
Yep, that's the way to go.
