### ISSUE TITLE
How to use RSA with the authentication plugin?

### ISSUE THREAD

**Issue by khuongduybui** [feathersjs/feathers#1145]
Basically there are 2 ways of JWT verification: using symmetric (such as HS256) vs asymmetric (such as RSA256) encryption.

It is very easy to go the symmetric way by providing the `secret` option [here](https://docs.feathersjs.com/api/authentication/server.html#options).

If I want to go the asymmetric way and providing the content of a public key to that `secret` option instead, where exactly in the client code do I provide the private key? I don't see anything [here](https://docs.feathersjs.com/api/authentication/client.html#options).

**Comment by daffl** [comment]
This can now be done with the v4 [authentication service](https://docs.feathersjs.com/api/authentication/service.html) by passing or customizing the [createAccessToken](https://docs.feathersjs.com/api/authentication/service.html#createaccesstoken-payload) and [verifyAccessToken](https://docs.feathersjs.com/api/authentication/service.html#verifyaccesstoken-accesstoken) methods.
