### ISSUE TITLE
Feathers client recieves all previous custom events

### ISSUE THREAD

**Issue by apmcodes** [feathersjs/feathers#1146]
### Steps to reproduce
On backend - Emit a custom event in service create method
On frontend - Listen to the custom event and do console log
Now call create method few times. Every time, the console log is outputting the event data of all previous events as well. In short the events are getting accumulated. The events gets cleared on browser refresh.

 **Could Vuex be storing the events?**

- Tried to debug but not able to understand what's causing this.
- All events are being sent to 'authenticed' channel
- Feathersjs is correctly emitting event only once.

### System configuration
Backend FeathersJs
Frontend FeathersJs socket client, Quasar

**please someone point me in the right direction to understand this behaviour.**

**Comment by apmcodes** [comment]
It seems socketio is firing multiple events.

**Comment by daffl** [comment]
Do you have a complete minimum example to reproduce this?

**Comment by apmcodes** [comment]
Fixed. 

It was cause by the event listener (inside Vue file) that needed to be removed by removeListener. 

```
uploadFile(file, updateProgress) {
      ...
      uploadService.on("uploadProgress", applyProgress);
      return new Promise((resolve, reject) => {
          ...
          uploadService.removeListener("uploadProgress");
      }
}
```
_It was happening with both built-in as well custom events_

Working with featherjs is getting easier by day ...
