### ISSUE TITLE
add search to query

### ISSUE THREAD

**Issue by issy123** [feathersjs/feathers#1147]
### Problem

I have a find query like this:

```
query:{
    activated:true,
    ...
}
```
Now I want to add a search to this query, since feathersjs does not support it but does have a context.params.sequelize, where i could add:
```
context.params.sequelize = {
    where:{
        $like: "%san diego%"
    }
}
```
### Actual behavior

This results into two queries:
`SELECT ... FROM ... WHERE activated = true AND ....`
`SELECT ... FROM ... WHERE LIKE '%san diego%'`

### Expected behavior
Though that is not what i wanted, I want to add a search onto the find query that is being build.
So the query would look like this
`SELECT ... FROM ... WHERE activated = true AND .... AND LIKE '%san diego%'`

And the `context.result` should return the results of the query

**Comment by issy123** [comment]
Oh nice! Can it also support an array of search keywords?

Will try in a bit

**Comment by issy123** [comment]
Hmm no luck.
`s.replace is not a function`

it tries to do `s.replace` on `Symbol(like)` which is a instance of a class named `Symbol` but probably expected a string like `'$like'`

Which version is 'the latest version' ?
And you mean the version of 'feathers-sequelize' ?
What version of 'sequelize' package does it need and do i need to update other packages like feathersjs?

**Comment by daffl** [comment]
An array is what [$or](https://docs.feathersjs.com/api/databases/querying.html#or) or a custom query is for.

**Comment by issy123** [comment]
Yes thank you

What about the `$like:'%san diego%' `? What requirements does it have for me to work?

**Comment by daffl** [comment]
There must be something else wrong. I just added a test that `$like` works for `feathers-sequelize` in https://github.com/feathersjs-ecosystem/feathers-sequelize/commit/e62179a49a3cc24ff70f1d0aba5d766ddf53f9d0

**Comment by issy123** [comment]
Thank you so much sir!
