### ISSUE TITLE
Multi tenant REST

### ISSUE THREAD

**Issue by Mangatt** [feathersjs/feathers#1148]
We are developing multi tenant app and clients have separate databases. As far I have learned, there is a way how to handle requests based on data in JWT. But is there a way how to separate them through REST (dynamic nested routes)?

- api.example.com/client1/users
- api.example.com/client2/users
- eg. api.example.com/{dbname}/{service}

There should be only one feathers process running and serving all clients that would be added dynamicaly.

**Comment by daffl** [comment]
See the [FAQ on nested routes](https://docs.feathersjs.com/faq/readme.html#how-do-i-do-nested-or-custom-routes) and the [documentation on Express routing](https://docs.feathersjs.com/api/express.html#routing). You could e.g. set the `service.Model` based on the dynamic parameters.

**Comment by Mangatt** [comment]
Thanks, @daffl, I'll look into that.

DB is swapped then on service basis or through entire app? Because authorization and other hooks should still run from main database, not from tenant-specific one.

**Comment by daffl** [comment]
Services can also be registered dynamically at runtime (important for routes is that the `notFound` Express middleware is placed properly) so you may not even need dynamic routes (just register the service for each client). Note that unregistering won't be possible but can be fairly easy handled with a hook that checks if the client is still enabled.

Other than that it looks like rather specific requirements that you'll probably won't find an out-of-the-box solution for. Separate databases per customer are much more difficult to handle than the standard multi-user/company setup where the JWT contains the user and company information and `api.example.com/messages` then just returns all appropriate messages. The only case I ever ran into where a multi-db setup made sense was when it was legally required.
