### ISSUE TITLE
WebSocket is closed before the connection is established

### ISSUE THREAD

**Issue by youjunke** [feathersjs/feathers#1149]
The following errors are often found：

websocket.js?0882:235 WebSocket connection to 'ws://192.168.199.201:3030/socket.io/?EIO=3&transport=websocket' failed: WebSocket is closed before the connection is established.

<img width="964" alt="wechatimg1" src="https://user-images.githubusercontent.com/4092206/50506540-6700af80-0ab4-11e9-964c-d7a838ac3fab.png">

i Don't know why，i need to refresh the page many times until i can continue to connect.
It happens on average once a day. Please instruct me.

**Comment by daffl** [comment]
Forcing websockets via `{transports: ['websocket']}` when establishing the socket usually solves these kinds of issues. Another thing mentioned [here](https://support.pusher.com/hc/en-us/articles/202085586-WebSocket-is-closed-before-the-connection-is-established) is to restart your browser if you are using Chrome.

**Comment by youjunke** [comment]
No effect, I local two computer connection is very difficult, a server, a front end. Very distressed.

It's already set up like this:

// Set up Plugins and providers
app.configure(express.rest());
app.configure(
  socketio({ transports: ['websocket'], wsEngine: 'uws' }, function(io) {
    // Registering Socket.io middleware
    io.use(function(socket, next) {
      // Exposing a request property to services and hooks
      socket.feathers.ip =
        socket.handshake.headers['x-forwarded-for'] || socket.handshake.address;
      next();
    });
  })
);

**Comment by daffl** [comment]
`transports: ['websocket']` needs to be used on the client establishing the connection, not on the server.

**Comment by youjunke** [comment]
yes, i have set like this:

const socket = io('http://xxxxxxxxx', {
  transports: ['websocket']
  upgrade: false
})


but it‘’s still unstable.

and I found a new situation, if the server in the local LAN, the connection is not stable, but on the external network server, the connection becomes much more stable, so this may be the problem of the LAN router?

**Comment by TakiRahal** [comment]
Some probleme : 
![Capture](https://user-images.githubusercontent.com/14108577/57071283-d6401780-6cd1-11e9-9dc0-1b9b6e6fcb9b.PNG)

**Comment by ecda909** [comment]
Found a fix for this?

**Comment by greyivy** [comment]
Also experiencing this issue. Version 4.4.3 of all libraries.

**Comment by daffl** [comment]
There is a lot of information e.g. in this question: https://stackoverflow.com/questions/41381444/websocket-connection-failed-error-during-websocket-handshake-unexpected-respon for example, when using an NginX proxy it needs some additional configuration. You also should not use clusters with pm2 (see https://github.com/socketio/socket.io/issues/798) unless you are using something like https://github.com/feathersjs-ecosystem/feathers-sync

**Comment by lehoangthienan** [comment]
> There is a lot of information e.g. in this question: https://stackoverflow.com/questions/41381444/websocket-connection-failed-error-during-websocket-handshake-unexpected-respon for example, when using an NginX proxy it needs some additional configuration. You also should not use clusters with pm2 (see [socketio/socket.io#798](https://github.com/socketio/socket.io/issues/798)) unless you are using something like https://github.com/feathersjs-ecosystem/feathers-sync

I turn off pm2 cluster  > fixed error socket 400
