### ISSUE TITLE
Feathers client doesn't connect to server on iOS device

### ISSUE THREAD

**Issue by riobijanero** [feathersjs/feathers#1150]
Hi I have a feathers server with a few services and a react-native client that uses feathers-client and a websocket connection.

On the simulator it works well. but when I build on a device, the connection doesn't work and I get a "Connection timed out" Error.

I have no idea why that is. Can anybody help me out?

**here is the client code - app.js:**

`
```
import {Alert, AsyncStorage} from 'react-native';
import {observable, action, computed} from 'mobx';
import {autobind} from 'core-decorators';
import io from 'socket.io-client';
import feathers from 'feathers/client'
import hooks from 'feathers-hooks';
import socketio from 'feathers-socketio/client'
import authentication from 'feathers-authentication-client';
const PLACEHOLDER = 'https://raw.githubusercontent.com/feathersjs/feathers-chat/master/public/placeholder.png';
const API_URL = 'https://itchy-liger-88.localtunnel.me';

@autobind
export default class Store {
  @observable isAuthenticated = false;
  @observable isConnecting = false;
  @observable user = null;
  @observable messages = [];
  @observable appointments = [];
  documents = [];
  forms = [];
  @observable hasMoreMessages = false;
  @observable skip = 0;

  constructor() {
    const options = {transports: ['websocket'], pingTimeout: 5000, pingInterval: 5000};
    const socket = io(API_URL, options);

    this.app = feathers()
      .configure(socketio(socket))
      .configure(hooks())
      .configure(authentication({
        storage: AsyncStorage // To store our accessToken
      }));

    this.connect();

    this.app.service('messages').on('created', createdMessage => {
      this.messages.unshift(this.formatMessage(createdMessage));
    });

    this.app.service('messages').on('removed', removedMessage => {
      this.deleteMessage(removedMessage);
    });

    if (this.app.get('accessToken')) {
      this.isAuthenticated = this.app.get('accessToken') !== null;
    }
    this.printAppointment();
  }

  connect() {
    this.isConnecting = true;

    this.app.io.on('connect', () => {
      this.isConnecting = false;
      this.authenticate().then(() => {
        console.log('authenticated after reconnection');
      }).catch(error => {
        alert('error authenticating after reconnection', error);
      });
    });

    this.app.io.on('disconnect', () => {
      console.log('disconnected');
      this.isConnecting = true;
    });
  }

  createAccount(email, password) {
    const userData = {email, password};
    return this.app.service('users').create(userData).then((result) => {
      return this.authenticate(Object.assign(userData, {strategy: 'local'}))
    });
  }

  login(email, password) {
    const payload = {
      strategy: 'local',
      email,
      password
    };
    return this.authenticate(payload);
  }

  authenticate(options) {
    options = options ? options : undefined;
    return this._authenticate(options).then(user => {
      console.log('authenticated successfully', user._id, user.email);
      this.user = user;
      this.isAuthenticated = true;
      this.loadPatientData();
      return Promise.resolve(user);
    }).catch(error => {
      alert('authenticated failed', error.message);
      alert(error);
      return Promise.reject(error);
    });
  }

  _authenticate(payload) {
    return this.app.authenticate(payload)
      .then(response => {
        return this.app.passport.verifyJWT(response.accessToken);
      })
      .then(payload => {
        return this.app.service('users').get(payload.userId);
      }).catch(e => Promise.reject(e));
  }

  loadPatientData(){
    this.loadDocuments();
    this.loadAppointments();
    this.loadForms();
  }

  promptForLogout() {
    Alert.alert('Sign Out', 'Are you sure you want to sign out?',
      [
        {
          text: 'Cancel', onPress: () => {
        }, style: 'cancel'
        },
        {text: 'Yes', onPress: this.logout, style: 'destructive'},
      ]
    );
  }

  logout() {
    this.app.logout();
    this.skip = 0;
    this.messages = [];
    this.user = null;
    this.isAuthenticated = false;
  }`
```

**this is the server code:**

```
`const path = require('path');
const favicon = require('serve-favicon');
const compress = require('compression');
const helmet = require('helmet');
const cors = require('cors');
const logger = require('./logger');

const feathers = require('@feathersjs/feathers');
const configuration = require('@feathersjs/configuration');
const express = require('@feathersjs/express');
const socketio = require('@feathersjs/socketio');


const middleware = require('./middleware');
const services = require('./services');
const appHooks = require('./app.hooks');
const channels = require('./channels');

const authentication = require('./authentication');

// feathers-blob service
const blobService = require('feathers-blob');
// Here we initialize a FileSystem storage,
// but you can use feathers-blob with any other
// storage service like AWS or Google Drive.
const fs = require('fs-blob-store');
const blobStorage = fs(__dirname + '/uploads');


const app = express(feathers());

// Load app configuration
app.configure(configuration());
// Enable security, CORS, compression, favicon and body parsing
app.use(helmet());
app.use(cors());
app.use(compress());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(favicon(path.join(app.get('public'), 'favicon.ico')));
// Host the public folder
app.use('/', express.static(app.get('public')));

// Set up Plugins and providers
app.configure(express.rest());
app.configure(socketio());

// Configure other middleware (see `middleware/index.js`)
app.configure(middleware);
app.configure(authentication);
// Set up our services (see `services/index.js`)
app.configure(services);
// Set up event channels (see channels.js)
app.configure(channels);

// Upload Service
app.use('/uploads', blobService({Model: blobStorage}));

// Configure a middleware for 404s and the error handler
app.use(express.notFound());
app.use(express.errorHandler({ logger }));

app.hooks(appHooks);

module.exports = app;
`
```

**default.json:**

```
{
  "host": "https://itchy-liger-88.localtunnel.me",
  "port": 8000,
  "public": "../public/",
  "paginate": {
    "default": 10,
    "max": 50
  },
  "nedb": "../data",
  "authentication": {
    "secret": "a76a80ee32398506d67771a820837d98ebf223691e8e7ea05b0449a922222f24405490ab8f1a83415743728e87b34e842b5d52c9e1cb60283156cbf728d2a96f3174b68ec5e9690f622307113e83aa012d4e7c2ddefbfc9364d12b2d0e7448beeb3519b870d09bea26f6de18e03e55c25c6482fbb224568be27a90011076eb32605d55a45c9b99d5d55b3f52005dc7dc1d1210d56e54d71d87ed6378ab0e71670d5cdfa6621f4433e6ffbff02187e8be079a91c16b222dc1cfe39218acc89ae116e571f96cd8b83bdce8a42508243c5a34b106d66af01dae928b18d78132264a2d3d0c1443f2052fe3228b61d8fe7a363d1fa842336f98b4c68d395ca9533ff1",
    "strategies": [
      "jwt",
      "local"
    ],
    "path": "/authentication",
    "service": "users",
    "jwt": {
      "header": {
        "typ": "access"
      },
      "audience": "https://itchy-liger-88.localtunnel.me",
      "subject": "anonymous",
      "issuer": "feathers",
      "algorithm": "HS256",
      "expiresIn": "1d"
    },
    "local": {
      "entity": "user",
      "usernameField": "email",
      "passwordField": "password"
    }
  }
}
```

### Expected behavior
When I log in, it should work

### Actual behavior
it doesn't connect to the server

### System configuration

feathers Version: 3.8.7
react-native-cli: 2.0.1
react-native: 0.57.5
xcode: 10.1
Node: v9.11.2

**Comment by daffl** [comment]
Without a more detailed error message it is difficult to say. It could be anything from a firewall setting to a misconfiguration in the React Native CORS access rights.

**Comment by emeagenciadigital** [comment]
We have the same issue. When working on the IOs simulator feathers client with sockets works fine, but on a real device, it does not work. 

Error message: Timeout of 5000ms exceeded calling ....

**React Native app Package.json**

`{
  "name": "Cityprime",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "@feathersjs/authentication-client": "^1.0.10",
    "@feathersjs/client": "^3.7.7",
    "@feathersjs/feathers": "^3.3.1",
    "@feathersjs/rest-client": "^1.4.7",
    "@feathersjs/socketio-client": "^1.2.1",
    "moment": "^2.23.0",
    "react": "16.6.3",
    "react-instantsearch-native": "^5.3.2",
    "react-native": "0.57.8",
    "react-native-custom-qr-codes": "^2.0.0",
    "react-native-intercom": "^12.5.1",
    "react-native-iphone-x-helper": "^1.2.0",
    "react-native-linear-gradient": "^2.5.3",
    "react-native-loading-spinner-overlay": "^1.0.1",
    "react-native-mixpanel": "^1.1.1",
    "react-native-navigation": "^2.6.0",
    "react-native-progress": "^3.5.0",
    "react-native-render-html": "^3.10.0",
    "react-native-responsive-grid": "^0.41.992",
    "react-native-snap-carousel": "^3.7.5",
    "react-native-svg": "^9.0.0",
    "react-redux": "^6.0.0",
    "redux": "^4.0.1",
    "rn-viewpager": "^1.2.9",
    "socket.io-client": "^2.2.0"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.51.1",
    "react-test-renderer": "16.6.3"
  },
  "jest": {
    "preset": "react-native"
  }
}
`

**Feathers Server Package.json**

`{
  "name": "city-prime",
  "version": "1.0.0",
  "description": "ads",
  "main": "src/index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "test:all": "npm run eslint && NODE_ENV=test npm run mocha",
    "start:seed": "NODE_ENV=test node src/ --seed",
    "dev": "nodemon",
    "feathers:generate:all": "feathers-plus generate all"
  },
  "repository": {
    "type": "git",
    "url": "https://emeagenciadigital.visualstudio.com/City%20Prime/_git/api-feathersjs-cityprime"
  },
  "author": "e-me agencia digital - Ezequiel Alfonso Bahoque Lopez",
  "license": "ISC",
  "dependencies": {
    "@e-me/feathers-awesome-permissions": "^1.0.1",
    "@feathersjs/authentication": "^2.1.13",
    "@feathersjs/authentication-jwt": "^2.0.7",
    "@feathersjs/authentication-local": "^1.2.7",
    "@feathersjs/authentication-oauth2": "^1.2.5",
    "@feathersjs/configuration": "^2.0.4",
    "@feathersjs/errors": "^3.3.6",
    "@feathersjs/express": "^1.2.7",
    "@feathersjs/feathers": "^3.2.3",
    "@feathersjs/socketio": "^3.2.7",
    "ajv": "^5.5.2",
    "algoliasearch": "^3.32.0",
    "aws-sdk": "^2.392.0",
    "compression": "^1.7.3",
    "cors": "^2.8.5",
    "credit-card-validator": "^1.0.8",
    "cross-env": "^5.2.0",
    "epayco-node": "0.0.5",
    "feathers-authentication-hooks": "^0.3.1",
    "feathers-hooks-common": "^4.19.4",
    "feathers-sequelize": "^3.1.3",
    "greenlock-express": "^2.6.7",
    "helmet": "^3.15.0",
    "lodash.merge": "^4.6.1",
    "moment": "^2.23.0",
    "mysql2": "^1.6.4",
    "nanoid": "^2.0.1",
    "passport-facebook": "^2.1.1",
    "passport-google-oauth20": "^1.0.0",
    "react-s3-uploader": "^4.8.0",
    "sequelize": "^4.41.2",
    "serve-favicon": "^2.5.0",
    "uuid": "^3.3.2",
    "winston": "^3.1.0"
  },
  "devDependencies": {
    "eslint": "^5.10.0",
    "mocha": "^5.2.0",
    "nodemon": "^1.18.7",
    "request": "^2.88.0",
    "request-promise": "^4.2.2"
  }
}
`

If needed I can give @daffl access to the Source code of react native and feathers api.

**Comment by emeagenciadigital** [comment]
> Hi I have a feathers server with a few services and a react-native client that uses feathers-client and a websocket connection.
> 
> On the simulator it works well. but when I build on a device, the connection doesn't work and I get a "Connection timed out" Error.
> 
> I have no idea why that is. Can anybody help me out?
> 
> **here is the client code - app.js:**
> 
> `
> 
> ```
> import {Alert, AsyncStorage} from 'react-native';
> import {observable, action, computed} from 'mobx';
> import {autobind} from 'core-decorators';
> import io from 'socket.io-client';
> import feathers from 'feathers/client'
> import hooks from 'feathers-hooks';
> import socketio from 'feathers-socketio/client'
> import authentication from 'feathers-authentication-client';
> const PLACEHOLDER = 'https://raw.githubusercontent.com/feathersjs/feathers-chat/master/public/placeholder.png';
> const API_URL = 'https://itchy-liger-88.localtunnel.me';
> 
> @autobind
> export default class Store {
>   @observable isAuthenticated = false;
>   @observable isConnecting = false;
>   @observable user = null;
>   @observable messages = [];
>   @observable appointments = [];
>   documents = [];
>   forms = [];
>   @observable hasMoreMessages = false;
>   @observable skip = 0;
> 
>   constructor() {
>     const options = {transports: ['websocket'], pingTimeout: 5000, pingInterval: 5000};
>     const socket = io(API_URL, options);
> 
>     this.app = feathers()
>       .configure(socketio(socket))
>       .configure(hooks())
>       .configure(authentication({
>         storage: AsyncStorage // To store our accessToken
>       }));
> 
>     this.connect();
> 
>     this.app.service('messages').on('created', createdMessage => {
>       this.messages.unshift(this.formatMessage(createdMessage));
>     });
> 
>     this.app.service('messages').on('removed', removedMessage => {
>       this.deleteMessage(removedMessage);
>     });
> 
>     if (this.app.get('accessToken')) {
>       this.isAuthenticated = this.app.get('accessToken') !== null;
>     }
>     this.printAppointment();
>   }
> 
>   connect() {
>     this.isConnecting = true;
> 
>     this.app.io.on('connect', () => {
>       this.isConnecting = false;
>       this.authenticate().then(() => {
>         console.log('authenticated after reconnection');
>       }).catch(error => {
>         alert('error authenticating after reconnection', error);
>       });
>     });
> 
>     this.app.io.on('disconnect', () => {
>       console.log('disconnected');
>       this.isConnecting = true;
>     });
>   }
> 
>   createAccount(email, password) {
>     const userData = {email, password};
>     return this.app.service('users').create(userData).then((result) => {
>       return this.authenticate(Object.assign(userData, {strategy: 'local'}))
>     });
>   }
> 
>   login(email, password) {
>     const payload = {
>       strategy: 'local',
>       email,
>       password
>     };
>     return this.authenticate(payload);
>   }
> 
>   authenticate(options) {
>     options = options ? options : undefined;
>     return this._authenticate(options).then(user => {
>       console.log('authenticated successfully', user._id, user.email);
>       this.user = user;
>       this.isAuthenticated = true;
>       this.loadPatientData();
>       return Promise.resolve(user);
>     }).catch(error => {
>       alert('authenticated failed', error.message);
>       alert(error);
>       return Promise.reject(error);
>     });
>   }
> 
>   _authenticate(payload) {
>     return this.app.authenticate(payload)
>       .then(response => {
>         return this.app.passport.verifyJWT(response.accessToken);
>       })
>       .then(payload => {
>         return this.app.service('users').get(payload.userId);
>       }).catch(e => Promise.reject(e));
>   }
> 
>   loadPatientData(){
>     this.loadDocuments();
>     this.loadAppointments();
>     this.loadForms();
>   }
> 
>   promptForLogout() {
>     Alert.alert('Sign Out', 'Are you sure you want to sign out?',
>       [
>         {
>           text: 'Cancel', onPress: () => {
>         }, style: 'cancel'
>         },
>         {text: 'Yes', onPress: this.logout, style: 'destructive'},
>       ]
>     );
>   }
> 
>   logout() {
>     this.app.logout();
>     this.skip = 0;
>     this.messages = [];
>     this.user = null;
>     this.isAuthenticated = false;
>   }`
> ```
> **this is the server code:**
> 
> ```
> `const path = require('path');
> const favicon = require('serve-favicon');
> const compress = require('compression');
> const helmet = require('helmet');
> const cors = require('cors');
> const logger = require('./logger');
> 
> const feathers = require('@feathersjs/feathers');
> const configuration = require('@feathersjs/configuration');
> const express = require('@feathersjs/express');
> const socketio = require('@feathersjs/socketio');
> 
> 
> const middleware = require('./middleware');
> const services = require('./services');
> const appHooks = require('./app.hooks');
> const channels = require('./channels');
> 
> const authentication = require('./authentication');
> 
> // feathers-blob service
> const blobService = require('feathers-blob');
> // Here we initialize a FileSystem storage,
> // but you can use feathers-blob with any other
> // storage service like AWS or Google Drive.
> const fs = require('fs-blob-store');
> const blobStorage = fs(__dirname + '/uploads');
> 
> 
> const app = express(feathers());
> 
> // Load app configuration
> app.configure(configuration());
> // Enable security, CORS, compression, favicon and body parsing
> app.use(helmet());
> app.use(cors());
> app.use(compress());
> app.use(express.json());
> app.use(express.urlencoded({ extended: true }));
> app.use(favicon(path.join(app.get('public'), 'favicon.ico')));
> // Host the public folder
> app.use('/', express.static(app.get('public')));
> 
> // Set up Plugins and providers
> app.configure(express.rest());
> app.configure(socketio());
> 
> // Configure other middleware (see `middleware/index.js`)
> app.configure(middleware);
> app.configure(authentication);
> // Set up our services (see `services/index.js`)
> app.configure(services);
> // Set up event channels (see channels.js)
> app.configure(channels);
> 
> // Upload Service
> app.use('/uploads', blobService({Model: blobStorage}));
> 
> // Configure a middleware for 404s and the error handler
> app.use(express.notFound());
> app.use(express.errorHandler({ logger }));
> 
> app.hooks(appHooks);
> 
> module.exports = app;
> `
> ```
> **default.json:**
> 
> ```
> {
>   "host": "https://itchy-liger-88.localtunnel.me",
>   "port": 8000,
>   "public": "../public/",
>   "paginate": {
>     "default": 10,
>     "max": 50
>   },
>   "nedb": "../data",
>   "authentication": {
>     "secret": "a76a80ee32398506d67771a820837d98ebf223691e8e7ea05b0449a922222f24405490ab8f1a83415743728e87b34e842b5d52c9e1cb60283156cbf728d2a96f3174b68ec5e9690f622307113e83aa012d4e7c2ddefbfc9364d12b2d0e7448beeb3519b870d09bea26f6de18e03e55c25c6482fbb224568be27a90011076eb32605d55a45c9b99d5d55b3f52005dc7dc1d1210d56e54d71d87ed6378ab0e71670d5cdfa6621f4433e6ffbff02187e8be079a91c16b222dc1cfe39218acc89ae116e571f96cd8b83bdce8a42508243c5a34b106d66af01dae928b18d78132264a2d3d0c1443f2052fe3228b61d8fe7a363d1fa842336f98b4c68d395ca9533ff1",
>     "strategies": [
>       "jwt",
>       "local"
>     ],
>     "path": "/authentication",
>     "service": "users",
>     "jwt": {
>       "header": {
>         "typ": "access"
>       },
>       "audience": "https://itchy-liger-88.localtunnel.me",
>       "subject": "anonymous",
>       "issuer": "feathers",
>       "algorithm": "HS256",
>       "expiresIn": "1d"
>     },
>     "local": {
>       "entity": "user",
>       "usernameField": "email",
>       "passwordField": "password"
>     }
>   }
> }
> ```
> ### Expected behavior
> When I log in, it should work
> 
> ### Actual behavior
> it doesn't connect to the server
> 
> ### System configuration
> feathers Version: 3.8.7
> react-native-cli: 2.0.1
> react-native: 0.57.5
> xcode: 10.1
> Node: v9.11.2

Where you able to solve the issue?
