### ISSUE TITLE
Force pass data in parameters of the socketio

### ISSUE THREAD

**Issue by GlauberF** [feathersjs/feathers#1151]
### Info:
**Feathers version**: 3.5.0
**NodeJS version**:v10.11.0

I'm using client side angularjs, I want to pass some more information when a new connection is made, eg token of another application.

In my code, I have the following:
ps: I am trying to pass inside an object in the variable (socketOpts)

![deepin screenshot_selecionar area_20181231150714](https://user-images.githubusercontent.com/11314585/50564714-8c88f580-0d0e-11e9-9efb-a9b348f21e66.png)

I want to be able to get the information I passed in the socketio connection:

![deepin screenshot_selecionar area_20181231150640](https://user-images.githubusercontent.com/11314585/50564717-8f83e600-0d0e-11e9-96b0-14fdd6a57434.png)

Today, it returns only this:

![deepin screenshot_selecionar area_20181231151752](https://user-images.githubusercontent.com/11314585/50564803-56984100-0d0f-11e9-973f-2a1535f41c60.png)

I need to have my data enter with this object 
```{provider: socketio}```, 
example ```{provider: socketio, token: '2312432432423'}```

**Comment by GlauberF** [comment]
perfect, but that would be server side, but I want to pass more information from the client side to the server.
When a new client connects, I want to pass on more information.

why today, when there is a new connection, when a console.log in connection on the server, only prints (provider).

**Comment by daffl** [comment]
Yes, you have to do this in two steps. First, add the parameters you want, e.g. in the [query option](https://socket.io/docs/client-api/#new-Manager-url-options) on the client when connecting the socket and then on the server assign that information to `socket.feathers` in the middleware.

**Comment by GlauberF** [comment]
Ok, I get it.
but I still can not figure out how to do this on the client side, because the options I want to pass on are personalized ie passing custom value on the client side.

second, how do I modify the channel file or featherjs socket middleware to receive these values?

if it is not too much, could I pass two small snippets of code, 1 on the client side passing custom data, for example (token).

And another server-side featherjs, receiving that value (token) and passing it forward.
