### ISSUE TITLE
How to use $not with $elemMatch in query

### ISSUE THREAD

**Issue by SeaDog505** [feathersjs/feathers#1154]
I have next problem after upgrade feathers. I have below query in hook before:

`var query = { query: {
    					"_id": obj._id,
    					"payments": {
    						$not: {
    							$elemMatch: { "year": year }
    						}
    					}}
    				};`

It's worked fine in previous version but after upgrade feathers version to Buzzard I receive an error:

`error: BadRequest: Invalid query parameter $not`

and after remove $not parameter this:

`error: BadRequest: Invalid query parameter $elemMatch`

Why? Please help.

**Comment by daffl** [comment]
Please read the migration guide on [whitelisting in database adapters](https://crow.docs.feathersjs.com/migrating.html#whitelisting).
