### ISSUE TITLE
Suggestion: cli generator to create generatorLog.txt 

### ISSUE THREAD

**Issue by msimonc** [feathersjs/feathers#1158]
After using the cli generator multiple times it would have been great to have a generatorLog.txt created so I knew what options I chose.

Maybe a "replay" capability...?

Thanks for the project!!

**Comment by eddyystop** [comment]
feathers-plus/cli does what you asked and has an inherent regeneration capability. You can also scaffold your own generator over cli+. The current cli will start being sunset with the Crow release.

https://medium.com/feathers-plus/write-your-own-app-generator-by-leveraging-feathers-plus-cli-37ad8dad9847
