### ISSUE TITLE
Support for flutter

### ISSUE THREAD

**Issue by netwrkx** [feathersjs/feathers#1166]
Is there any plan to support [flutter](www.flutter.io)

Correct me if I'm wrong
The only way to use feathersjs with flutter is via http api

**Comment by chenryhabana205** [comment]
I'm starting to write a flutter client with some friends in https://pub.dev/packages/feathers_socket_client

**Comment by daffl** [comment]
When you think it's ready, please feel free to add it to https://github.com/feathersjs/awesome-feathersjs.

**Comment by chenryhabana205** [comment]
> When you think it's ready, please feel free to add it to https://github.com/feathersjs/awesome-feathersjs.

Ready to use at a basic level, I use it for several projects that use the wonderful feathers. But I am extracting the parts that I can extract from the projects to be able to make it public little by little, every time I have time I will dedicate it to adding more functions to humanize the use of it. As soon as some use it and validate it, I add it to the repository you sent me.

**Comment by gedw99** [comment]
good news !

There is now a Flutter client with demo.


Demo
https://github.com/Dahkenangnon/flutter_feathersjs_demo_app

Package
https://github.com/Dahkenangnon/flutter_feathersjs.dart

**Comment by Dahkenangnon** [comment]
> good news !
> 
> There is now a Flutter client with demo.
> 
> Demo https://github.com/Dahkenangnon/flutter_feathersjs_demo_app
> 
> Package https://github.com/Dahkenangnon/flutter_feathersjs.dart

Updated and maintained. Every recommendation about features is welcome. Thank

New release coming in March.
