### ISSUE TITLE
Feathers socket client needs to receive events from 2 feathers apps

### ISSUE THREAD

**Issue by apmcodes** [feathersjs/feathers#1169]
We have 2 Feathers apps, both have 1 similar service named 'List' (with same model, schema) and share a common DB. 

UI - (Quasar, Feathers-veux) A Feathers socket client is connected to App1 as of now. Is it possible to receive List service events from App2. App2 updates DB so these needs to be reflected in the UI.
(We have duplicated the service List so that both the apps can be run independent of each others)

Please suggest, how can we make this possible. Should the client connect to both the apps and update the data with Feathers-veux ... Is this even possible ...

**Comment by daffl** [comment]
You could setup [feathers-sync](https://github.com/feathersjs-ecosystem/feathers-sync/) for both applications and have them use the same synchronization mechanism. That way events will be published to all instances.

**Comment by apmcodes** [comment]
OMG, this is what is needed. Just can't below featherjs is so versatile for real-world projects...

**Comment by apmcodes** [comment]
So easy to setup. Thanks working great.
