### ISSUE TITLE
Provide Auth as collection of hooks and let registration of service to the user

### ISSUE THREAD

**Issue by mohamed-seada-1994** [feathersjs/feathers#1171]
I think authentication should just be available as hooks and the developer can define his own service and endpoints.
- This will make it easy to support some additional functionality as new hooks without thinking of configuring them by default or they should be optional.
- This hooks package can combine both **feathers-authentication** and **feathers-authentication-management**.

The both could be there...
- What about providing all auth functionalities as just hooks and provide other package that wrap these hooks in good production ready way?

**Comment by daffl** [comment]
This has been done in in Feathers v4 authentication which does not require to add any hooks to the authentication service anymore and more easily allows to customize the authentication service. See the [Migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information on how to upgrade.
