### ISSUE TITLE
params.user in after.create hook not populated with strategy: 'jwt'

### ISSUE THREAD

**Issue by josiahbryan** [feathersjs/feathers#1172]
### Steps to reproduce

On client, after successful auth and storage of token in localStorage, reload page, and call `client.authenticate()` with no args, triggering a `{strategy: 'jwt'}` auth call to the server.

If I call authenticate() on client as described, then on the server, in my `src/authentication.js` file, in my `after.create` hook, `context.params.user` is not set.

This seems to be related to [https://github.com/feathersjs/authentication/issues/545](https://github.com/feathersjs/authentication/issues/545), not sure though

Relevant keys from context after the `after.create` hook runs:

```
     data: 
      { strategy: 'jwt',
        accessToken: 'TOKEN_HERE },
     params: 
      { authenticated: true,
        query: {},
        provider: 'socketio',
        headers: {},
        session: {},
        cookies: {},
        user: {},
        payload: [Object] },
     result: 
      { accessToken: 'TOKEN_HERE',
        user: {} } },
```
I checked params.payload, and this is all it has - no userId or anything related to user:
```
{ iat: 1547678246,
     jti: 'c1232263-f2fd-4f15-9da5-0c5e1adf3dc6',
     exp: 1547764646,
     aud: 'https://danceableapp.com',
     iss: 'feathers',
     sub: 'anonymous' }
```

### Expected behavior
`context.params.user` should be set

### Actual behavior
`context.params.user` is an empty object

### System configuration

**Module versions** 
```
    "@feathersjs/authentication": "^2.1.15",
    "@feathersjs/authentication-jwt": "^2.0.9",
    "@feathersjs/authentication-local": "^1.2.9",
    "@feathersjs/authentication-oauth2": "^1.3.0",
    "@feathersjs/configuration": "^2.0.6",
    "@feathersjs/errors": "^3.3.6",
    "@feathersjs/express": "^1.3.1",
    "@feathersjs/feathers": "^3.3.1",
    "@feathersjs/socketio": "^3.2.9",
```

**NodeJS version**:
`v8.11.3`

**Operating System**:
```[josiah@JosiahsLaptop server]$ lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.2.1511 (Core) 
Release:        7.2.1511
Codename:       Core
```

**Comment by daffl** [comment]
This is usually due to a misconfiguration of the authentication plugin (most likely an invalid id or a non-standard user service). Would need a complete example/repository to reproduce the problem to say for sure.

**Comment by josiahbryan** [comment]
Thanks. Could be - I use a custom ORM for my services. I found that I could fix this particular issue by by adding this `before.create` hook to the `authentication` service:
```javascript
hook => {
  hook.params.payload = {
    ...hook.params.payload,
    userId: hook.params.user.id
  };
}
```
