### ISSUE TITLE
How to kill session in channels login?

### ISSUE THREAD

**Issue by olaferlandsen** [feathersjs/feathers#1176]
Well, I'm trying to kill session in channels.
If the user has "bock" property in database, I need kick it.
How??
Thanks

**Comment by daffl** [comment]
Please have a look at the [Channels API](https://docs.feathersjs.com/api/channels.html#apponlogin) and [documentation on how to keep channels updated](https://docs.feathersjs.com/api/channels.html#keeping-channels-updated). It should have all the information you need, if the user has a `blocked` flag you just check it and don't join the channel if it is set.

```js
// Join a channel given a user and connection
const joinChannels = (user, connection) => {
  if (!user.blocked) {
    app.channel('authenticated').join(connection);
  }
}
```
