### ISSUE TITLE
S3 support, yes or no?

### ISSUE THREAD

**Issue by cekvenich** [feathersjs/feathers#1178]
Hi, I'm very interested in this - I read blog and twitter that S3 (and compatible, eg, Digital Ocean Spaces, Minio.js) are supported. BUT: there are no docs anywhere on how this works.

So question please: is S3 | compatible supported as DB | storage?

**Comment by Hobbs1210** [comment]
it's supported through [feathers-blob](https://github.com/feathersjs-ecosystem/feathers-blob/)

**Comment by daffl** [comment]
Yep. It is indeed. Documentation in the linked repository.
