### ISSUE TITLE
REST GET service throws NotAuthenticated even it is unprotected 

### ISSUE THREAD

**Issue by sachinsawant71** [feathersjs/feathers#1184]
### Steps to reproduce

I have users REST service with following hook configuration for "before" -
before: {
    all: [],
    find: [authenticate('jwt'), modifySearchQuery()],
    get: [],
    create: [ checkOrg(), hashPassword(), lowerCase('email')],
    update: [hashPassword(), authenticate('jwt')],
    patch: [hashPassword(),  checkOldPassword()],
    remove: [authenticate('jwt')]
  }

Please note that I do not call authenticate('jwt') for "get" and "create" methods.

### Expected behavior

I should be able to call "get" method without jwt token.

### Actual behavior

When I call "get" method using  users REST service I get "NotAuthenticated" error. But at the same time, I am able to call unprotected "create" method using REST without any issues. 

I see similar behavior for "find" method too, if I make it unprotected i.e. it throws "NotAuthenticated" error. 

Am I missing any configuration?

### System configuration

**Module versions** (especially the part that's not working):

**NodeJS version**:  Node v10.14.2

**Operating System**: Windows 8

**Browser Version**: Chrome 

**React Native Version**: NA

**Module Loader**: npm

**Comment by daffl** [comment]
Most likely your `get` is calling `find` internally passing `params`. That will still trigger the `authenticate('jwt')` for `find`. It is hard to say without more information though.

**Comment by sachinsawant71** [comment]
Even if I make find unprotected, I get "NotAuthenticated" error for both - find and get. My service is based on Mongo/Mongoose model.

**Comment by issy123** [comment]
Do these hooks query from other services / service methods that do require authentication?

I am using authentication in some parts of my service methods and others not and it works fine.

**Comment by sachinsawant71** [comment]
I figured out the issue. I wrote a custom service and I configured it incorrectly. I fixed it and now the service is working as expected. 

Thanks for your help. We can close the issue.
