### ISSUE TITLE
[authentication-local] Error: the `id` property must be set on the entity service for authentication

### ISSUE THREAD

**Issue by Mangatt** [feathersjs/feathers#1188]
### Steps to reproduce

When you combine `@feathersjs/authentication-local` with custom service (e.g. not with provided one), you'll get this error `Error: the 'id' property must be set on the entity service for authentication` from [verifier.js#81](https://github.com/feathersjs/feathers/blob/master/packages/authentication-local/lib/verifier.js#L81).

I took me quite a while to reverse engineer where is the problem. Appareantly it is talking about `users` service, not `authentication` one and setting `this.id` on custom service makes magically everything working again.

### Expected behavior
There should be mention about that in docs or added configuration option for auth plugin.

### Actual behavior
It makes you wonder what is going on instead of making you productive.

**Comment by daffl** [comment]
This will be fixed by Authentication v3 (https://github.com/feathersjs/feathers/issues/1045) where you can explicitly set the `entityId` in your configuration.

**Comment by averri** [comment]
@Mangatt  and @daffl , could you please provide more information about how to set the `entityId`? Please post the hooks for the `users` service.

**Comment by daffl** [comment]
This has been done in Feathers v4 authentication where `entityId` can be set in the [service configuration](https://crow.docs.feathersjs.com/api/authentication/service.html#configuration). See the [migration guide](https://crow.docs.feathersjs.com/migrating.htmlhttps://crow.docs.feathersjs.com/migrating.html) for more information.
