### ISSUE TITLE
how to pass current/login user id in find query of hook

### ISSUE THREAD

**Issue by sanmeetsingh** [feathersjs/feathers#1189]
how to pass current/login userid 

i want to pass the userid in subscriber 
 subscribeData = await Subscribe.find({ subscribed: hook.result._id , subscriber : userid });

i also try with,

const { authenticate } = require('@feathersjs/authentication').hooks;

authenticate('jwt')
console.log(hook.params.user);
but not get any value

////////////////////////////////////////////////////////////////////////

CODE
////////////////////////////////////////////////////////////////////////////
module.exports = (options = {}) => {
  return async hook => {
    if (hook.type !== 'after') {
      throw new Error(`The 'checksubscribe' hook should only be used as a 'after' hook.`);
    }
    if (!(hook.method === 'get' || hook.method === 'find')) {
      throw new errors.MethodNotAllowed(`The 'checksubscribe' hook should only be used on the 'get', 'find' service methods.`);
    }
    
    
    const Subscribe = hook.app.services.subscribe.Model
    if (hook.method === 'get') {
    
     
      
      subscribeData = await Subscribe.find({ subscribed: hook.result._id });
 
    if(subscribeData.length != 0)
      {
      hook.result.subscribe = true
      }
      else
      hook.result.subscribe = false
    
    } else { 
      
      let results = hook.result.data.map(item => {
        return new Promise(async function(resolve, reject) {
         //console.log(item._id);
          subscribeData = await Subscribe.find({ subscribed: item._id});
         // console.log("sam",subscribeData);
          if(subscribeData.length != 0)
         {
          item.subscribe = true
         }
        
        else{
          item.subscribe = false
        }

          resolve(item)
        });
      })
      hook.result.data = await Promise.all(results)
    }
    return hook
  }
}

**Comment by edwardsmarkf** [comment]
i use this: (it was provided for me on slack)

return async context => {
  if  (  _.has(context, 'data.google.profile')  ) {
    if  ( _.has(context.data.google.profile, 'displayName' ) )    {
      context.data.displayName = context.data.google.profile.displayName;
      logger.info('displayName: ' + context.data.displayName);
    }
    if  ( _.has(context.data.google.profile, 'emails' ) ) {
      context.data.email = context.data.google.profile.emails.find(email =>
email.value).value;
      logger.info('email:       ' + context.data.email);
    }
    if  ( _.has(context.data.google.profile, 'name' ) ) {
      ['familyName', 'givenName'].forEach( (val) => {
        if  ( _.has(context.data.google.profile.name, val )     ) {
          context.data[val] = context.data.google.profile.name[val];
          logger.info(val + ': ' + context.data[val]);
        }
      })
    }
  } // end if has data.google.profile


Thank you,

Mark Edwards

**Comment by sanmeetsingh** [comment]
not  helpful

**Comment by sanmeetsingh** [comment]
> use `context.params.user` for authenticated/current user data.
> 
> Also please next time [highlight your code](https://help.github.com/articles/creating-and-highlighting-code-blocks/)
> 
> Example is here: https://docs.feathersjs.com/guides/chat/processing.html#sanitize-new-message
> Scroll a bit down

as i mention above i already use this 
console.log(hook.params.user);
but not getting any value 

response is undefine

**Comment by daffl** [comment]
That probably means an issue in your configuration. Try going through the [chat guide](https://docs.feathersjs.com/guides/chat/readme.html) to see if you can reproduce the problem.

**Comment by sanmeetsingh** [comment]
> That probably means an issue in your configuration. Try going through the [chat guide](https://docs.feathersjs.com/guides/chat/readme.html) to see if you can reproduce the problem.

ok i will try to find the solution

**Comment by sanmeetsingh** [comment]
> That probably means an issue in your configuration. Try going through the [chat guide](https://docs.feathersjs.com/guides/chat/readme.html) to see if you can reproduce the problem.

Ahh, its self now ,

Actually i am calling this after get hook and authenticate('jwt') not work in after hook
