### ISSUE TITLE
Regression in location/path name with latest refactor (for sockets)

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers#119]
We now have two `service` methods.  
One here: https://github.com/feathersjs/feathers/blob/master/lib/application.js#L25
The other gets mixed in here: (or in primus.js): https://github.com/feathersjs/feathers/blob/master/lib/providers/socket/socketio.js#L16

`stripSlashes()` is only called in the first one.  Since the second `service` method gets called directly from `app.use()`, is the proper fix to simply add a `stripSlashes()` here: https://github.com/feathersjs/feathers/blob/master/lib/application.js#L76

**Comment by daffl** [comment]
This should be fixed via https://github.com/feathersjs/feathers-commons/commit/f05b9502160d2c3c7326222027956d1cedf54476
