### ISSUE TITLE
Password isn't being hashed for new user

### ISSUE THREAD

**Issue by nathansgithub** [feathersjs/feathers#1190]
I am trying to figure out why this code isn't hashing the password for a new user. I used to have the hashPassword function in a hook like this:
`create: [ local.hooks.hashPassword() ]`
But this doesn't let me access the username and password I need to look at to make sure they are valid. I have tried to configure the hook a few different ways, but it isn't hashing the password before writing it to the database.

```
app.service('users').hooks({
  before: {
    find: auth.hooks.authenticate('jwt'),
    create: [
      async function (context) {
        await validateNewUser(context.data)
        await local.hooks.hashPassword({ passwordField: 'password' })
        return context
      }
    ],
  },
  after: local.hooks.protect('password')
})
```

### Expected behavior
The password should hashed.

### Actual behavior
It is stored in plaintext.

### System configuration
Node version 10.15.1
Feathers version 3.3.1

**Comment by daffl** [comment]
Calling `local.hooks.hashPassword()` returns a [hook function](https://docs.feathersjs.com/api/hooks.html#hook-functions). You either have to call what is returned again with the context (`await local.hooks.hashPassword({ passwordField: 'password' })(context)`) or register as a separate hook which is how it is intended to be used:

```js
app.service('users').hooks({
  before: {
    find: auth.hooks.authenticate('jwt'),
    create: [
      async function (context) {
        await validateNewUser(context.data)
        return context
      },
      local.hooks.hashPassword({ passwordField: 'password' })
    ],
  },
  after: local.hooks.protect('password')
})
```

**Comment by nathansgithub** [comment]
Ah, ok. That works now. Thank you for the quick reply!
