### ISSUE TITLE
Multi-sort example

### ISSUE THREAD

**Issue by issy123** [feathersjs/feathers#1191]
I've found no example on multisort but tried:

```javascript
$sort: 
        [{
          'type': -1
        }, {
          'category': -1
        }],
```

This fails, what format does it expect?

**Comment by bertho-zero** [comment]
```js
{
  type: { $sort: -1 },
  category: { $sort: -1 }
}
```
?

**Comment by issy123** [comment]
I don't think it's like that

**Comment by daffl** [comment]
```js
{
  $sort: {
    type: -1,
    category: -1
  }
}
```

Should work. More complex sorting mechanisms (e.g. by priority) will be database adapter specific.

**Comment by issy123** [comment]
Yes but this does not enforce a certain order right? I've read in the docs that an array is accepted but not in which format

**Comment by issy123** [comment]
fixed it by using a hook with the sequelize adapter.

```javascript
module.exports = function () {
  return async context => {

    context.params.sequelize = {
      order: [
        ['type', 'ASC'],
        ['category', 'ASC'],
      ]
    };
    
    return context;
  };
};

```

**Comment by akvaliya** [comment]
How to use it in REST api?
