### ISSUE TITLE
How to create and call a custom action via socket.io?

### ISSUE THREAD

**Issue by wkamir** [feathersjs/feathers#1193]
I have a basic example running and using socket.io as transport like so:

```
import feathers from '@feathersjs/client';
import * as io from 'socket.io-client';
import { environment } from 'environments/environment';


let socketio = feathers.socketio;
let auth = feathers.authentication;

let socket = io(environment.backendBase);
let app = feathers()

app.configure(socketio(socket, { timeout: 300000 }));
app.configure(auth({
    storage: window.localStorage
}));
```

Everything works really nicely - I can find(), get(), create(), etc... use the standard service methods like so (client again):

```app.service('users').get(some_id)```

How would I go about creating some custom action (that is not find()/get()/etc.)? How do I need to extend a service on the server side and how would I call this service from the client (vie socket.io)?

I have found how to do it with express:

```
app.get('/tasks/custom-action', cookieParser(), authenticate('jwt'), async (req, res) => {
   let data = await app.service('the-data').find()
   // do some more complex logic here
   res.send(data);
});

// Initialize our service with any options it requires
app.use('/tasks', createService(options));
```
How could I build the same thing with socket.io?

Please provide me with some pointers on where to look for documentation - on the server as well as how to call the custom action from the client.

Thanks!

**Comment by daffl** [comment]
Please see [this FAQ](https://docs.feathersjs.com/faq/readme.html#how-do-i-create-custom-methods). Usually all "custom methods" can be implemented through the standard service interface.

**Comment by wkamir** [comment]
Hehe :) Short but to the point.

So I was just going about it the wrong way. I will try to embrace the standard service idea more and probably will be able to accomplish what I need to.

Thank you!

**Comment by daffl** [comment]
The challenge with opening it up to all methods is that

- It does not align well with the REST architecture so mapping it back to HTTP is challenging (the way HTTP was designed, action names should not occur in a URL)
- The parameters are not known so things are difficult to secure (e.g. no `params` and `params.user`)
- Most things that look like they'd require a custom method at first are usually workflows which can be handled through hooks

Happy to talk it through if you have a specific example.

**Comment by wkamir** [comment]
My case is not really that specific. 

The action would have been named "get-next-three-tasks" - which are selected very specific - the standard find query params are not enough. The tasks are selected based on which tasks the user already had accomplished as well as the user's experience points and some other  factors (it's a little browser game).

I will probably build a find hook that reacts on a specific query parameter on the 'tasks' service - right?

**Comment by wkamir** [comment]
So i got something running now in a hook... does this look like a standard feathersjs approach?

```
const { SKIP } = require('@feathersjs/feathers');

module.exports = function () {
  return async context => {

    let query = context.params.query;

    if (query.$select_next_tasks) {
      // more complicated logic to come
      let nextTasks = await context.service.find({ query: { $limit: 3 } });

      context.result = nextTasks;
      return SKIP;
    }

    return context;
  }
}
```

**Comment by daffl** [comment]
There shouldn't be a need to skip or set the result. I would just change the query accordingly:

```js
const _ = require('lodash');

module.exports = function () {
  return async context => {
    let query = context.params.query;

    if (query.$select_next_tasks) {
      context.query = _.omit(query, '$select_next_tasks');
      
      context.query.$limit = 3;
    }

    return context;
  }
}
```

**Comment by wkamir** [comment]
Hehe - indeed this will work :) Thanks again and also for the work you put into this great framework!
