### ISSUE TITLE
How do I make the difference between 2 connections of the same browser but different tabs with socketio as transport layer

### ISSUE THREAD

**Issue by achilsowa** [feathersjs/feathers#1198]
Hey guys. First amazing job with feathers.
This is not really an issue but more a question.
I'm using feathers with socketio as transport layer and local/jwt as authentication mecahnism.
1. For an authenticated user I wanted to know how can I differentiate 2 connections on the same browser with using 2 differents tabs, and more important, how can I know that those 2 connections are from the same browser

2. Is it possible to have the same information on a non authenticated user ?

Thanks

**Comment by daffl** [comment]
Two different browsers will establish two connections and send two different `login` events (with the same user attached to it). They will end up in the same channels and get the same updates. To uniquely identify them you could pass the [socket.id](https://socket.io/docs/server-api/#socket-id) generated by Socket.io [into Feathers params and connection](https://docs.feathersjs.com/api/socketio.html#params):

```js
app.configure(socketio(function(io) {
  io.use(function (socket, next) {
    socket.feathers.socketId = socket.id;
    next();
  });
}));
```

Now you can access `params.socketId` in service calls and `connection.socketId` in [channel connections](https://docs.feathersjs.com/api/channels.html).

**Comment by achilsowa** [comment]
Thanks for your prompt answer.
I got that.
Here is my point:

1. When it is the same browser but different tabs I want that behaviour (having both connections end in the same channels and get the same updates)
2. When it is two different browsers (or the same browser with one tab in incognito mode) I want them to be not related.

And I think feathers already works like that. For example if I'm authenticated with the same user in three different tabs: Tab1A, Tab2A, Tab1B. With Tab1A and Tab2A from a browser A and the 3rd tab Tab1B from a 2nd browser B.
When I logout from Tab1A, I'm also logged out from Tab2A (even thought I'm not automatically notified), but nothing changes in Tab1B. Which is totally normal.

I'm already using [this to keep my channels updated](https://docs.feathersjs.com/api/channels.html#keeping-channels-updated), but I would have preferred to keep channels per session and not per user.

**Comment by daffl** [comment]
You'll need a client side way to identify the browser. E.g. by setting a unique flag in `localStorage` which will be shared across tabs but not browser (or private mode). Then you can pass it with the Socket.io connection query (see [this answer on Stackoverflow for how](https://stackoverflow.com/questions/54421486/how-to-add-parameters-to-a-feathersjs-socket-connection/54453737#54453737)).

**Comment by achilsowa** [comment]
Ok Thanks. I'll try that.
At the same time (to solve the my problem) I also tried to integrate express session. I could add it on the server, and save session to the database (mongodb). The problem now is a new session is created any time I refresh the browser page, which is not what I expected. I think I missed something like what you suggested up [there](https://stackoverflow.com/questions/54421486/how-to-add-parameters-to-a-feathersjs-socket-connection/54453737#54453737) to be able to send the express sessionId after page refresh (so it will not create a new one)

So if there were a way to use the express sessionId in lieu of the generated token you suggested up there, that will be the best I think
