### ISSUE TITLE
MySQL + Sequelize convert tinyint to boolean. Is it possible?

### ISSUE THREAD

**Issue by zaruda** [feathersjs/feathers#1199]
raw: false isn't an option here. Population using fastJoin from feathers-hooks-common stops working

**Comment by daffl** [comment]
Could you clarify? What are you trying to accomplish? What stops working? What is expected?

**Comment by zaruda** [comment]
I'm using fastJoin from feathers-hooks-common for some data population in my hooks.
Example below:  
```
const postResolvers = {
  joins: {
    author: () => async post => post.author = (await users.find({ query: {
      id: post.userId
    } }))[0],
  }
};
module.exports = {
  before: {
    patch: [ disableMultiItemChange() ],
    remove: [ disableMultiItemChange() ]
  },
  after: {
    all: [ fastJoin(postResolvers) ],
  },
}; 
```

But boolean values comes as 0 and 1 (like stored in mysql db).
This behaviour appears only if using feathers service for quering. When I tried sequelize model instead of service, everything works fine

**Comment by daffl** [comment]
Closing since this more looks like a fastJoin specific question. At the service level, data values can always be converted in a hook to what you need.
