### ISSUE TITLE
Customising service route paths

### ISSUE THREAD

**Issue by TheFoot** [feathersjs/feathers#1203]
Hi. As corporate policy we have to use singular naming conventions for single resources (E.g. `/user/:id` vs `/users/:id`). Can you please give me a clue as to how to achieve this?

### Steps to reproduce

//app.use ( '/users', createService ( options ) );
const usersService = createService ( options );
app.get ( '/users', usersService.find );
app.get ( '/user/:id', usersService.get );

### Expected behavior
I'd like to be able to instantiate each route/service method manually using something similar to the above.

### Actual behavior
I'm obviously breaking some part of the service initialisation as I'm now getting this error:

```
service.hooks ( hooks );
	        ^
TypeError: Cannot read property 'hooks' of undefined
```

### Full Users Service

```
/*
	Global users service
 */
const createService = require ( 'feathers-mongodb' );
const hooks = require ( './users.hooks' );

module.exports = app => {

	const appConfig = app.get ( 'appConfig' );
	const mongoClient = app.get ( 'mongoClient' );
	const options = {
		paginate: appConfig.paginate
	};

	// Initialize our service with any options it requires
	//app.use ( '/users', createService ( options ) );

	const usersService = createService ( options );
	app.get ( '/users', usersService.find );
	app.get ( '/user/:id', usersService.get );

	// Get our initialized service so that we can register hooks and filters
	const service = app.service ( 'users' );

	// Get a mongo connection
	mongoClient
		.then ( db => {

			// Attach model to service
			service.Model = db.collection ( 'users' );

		} )
	;

	service.hooks ( hooks );
};
```

**Comment by daffl** [comment]
Service names always have the same hierarchical identifier [according to the specification for resource URIs (RFC 3986](https://tools.ietf.org/html/rfc3986#section-1.2.3). You can always alias the `find` method with a [custom service](https://docs.feathersjs.com/api/services.html) though:

```js
// Makes `GET /users` available.
app.use('/users', {
  find (params) {
    return app.service('user').find(params);
  }
});

const { disable } = require('feathers-hooks-common');

// Disable external `GET /user` requests if needed
app.service('user').hooks({
  before: {
    find: disable('external')
  }
});
```

**Comment by TheFoot** [comment]
Thanks for your response.. I see, so for "users" service disable the singleton resource URL methods, and use a custom "user" service which aliases "users" svc for the single resource URLs? Makes sense..

It might be easier to try and convince my "powers that be" to let the singleton naming for resource URLs go though :)

Cheers!

**Comment by daffl** [comment]
The URI RFC I linked might give you some ammunition that this is the expected behaviour for REST APIs so it's at least worth a try. If not, the alias should work fine, too. Good luck 😄

**Comment by TheFoot** [comment]
Thanks!

I don't see a reference to singular/plural naming convention in that spec? 

Their argument is that a collection is plural, a single resource is by definition, singular.. Quite hard to argue the point tbh..

**Comment by TheFoot** [comment]
> Nor should it be assumed that a system
>       using URIs will access the resource identified: in many cases,
>       URIs are used to denote resources without any intention that they
>       be accessed.  Likewise, the "one" resource identified might not be
>       singular in nature (e.g., a resource might be a named set or a
>       mapping that varies over time).

That might work.. :)
