### ISSUE TITLE
Params are being overwritten

### ISSUE THREAD

**Issue by NickBolles** [feathersjs/feathers#1210]
### Steps to reproduce
Call a service with params and try to access the params from a hook

### Expected behavior
Be able to pass params to a service call and be able to access them on the server (maybe I'm not using params correctly? 

### Actual behavior
The params are overwritten by the socket.io transport

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working): Transport commons 4.1.6

This is the line that I'm broken on in the screenshots below
https://github.com/feathersjs/feathers/blob/master/packages/transport-commons/lib/socket/utils.js#L94

If I step over `methodArgs[position] = params` it overwrites my params that I'm passing into the service.

Am I not using params the correct way? I just wanted to pass something along with my patch call.

![image](https://user-images.githubusercontent.com/7891759/52654291-4ef3bc80-2eb7-11e9-8cd5-923cde5d7568.png)

![image](https://user-images.githubusercontent.com/7891759/52654261-3d121980-2eb7-11e9-9bba-82a893166ad5.png)

**Comment by daffl** [comment]
From [the Socket.io transport documentation](https://docs.feathersjs.com/api/socketio.html#paramsquery): 

> Only `params.query` is passed between the server and the client, other parts of `param`s are not. This is for security reasons so that a client can't set things like params.user or the database options. You can always map from params.query to params in a before hook.

**Comment by NickBolles** [comment]
@daffl perfect. That's what I was looking for, I just skimmed over it. That's actually what I'm doing as a workaround anyways. Thanks for the quick reply!

**Comment by NickBolles** [comment]
@daffl Follow up to that. Is there a reason we don't slam the params the client sends into params.clientParams or requestParams something?

**Comment by eddyystop** [comment]
Use the paramsForServer utility and paramsFromClient hook, both from common hooks.

**Comment by NickBolles** [comment]
@eddyystop perfect, thank you! Sorry for the nooby question you guys! probably should have asked in slack too... sorry!
