### ISSUE TITLE
Publish custom socket.io events from client to server

### ISSUE THREAD

**Issue by deskoh** [feathersjs/feathers#1216]
Is there a way to publish a socket.io event from client to sever? For example, client has a list of chat rooms to join. Instead of using Service Events, could something like the following work?

```Javascript
const socket = io('http://localhost:3030', { transports: ['websocket'] });
feathersClient = feathers()
  .configure(feathers.socketio(socket));

// Tried the following
// The websocket frame emitted is: 42["room join",{"id":"hy11AzMfF47mwabS"}]
feathersClient.service('room').emit('join', { id: roomId });
```

On server, is there anyway to subscribe to this custom event?

```JavaScript
// Following does not work

const service = app.service('room');
service.on('join', (data) => {
  console.log(data);
});

service.on('workspace join', (data) => {
  console.log(data);
});
```

**Comment by daffl** [comment]
There is by using a custom room management service. @Mattchewone just recently published an article about this: [FeathersJS Channel Subscriptions](https://blog.feathersjs.com/feathersjs-channel-subscriptions-647c771ca6c8).
