### ISSUE TITLE
authentication: extract JWT with jwtFromRequest

### ISSUE THREAD

**Issue by ThomasHalwax** [feathersjs/feathers#1222]
### Expected behavior
Allow passport's ```ExtractJwt.fromUrlQueryParameter(param_name)``` to extract a JWT from th query string.

### Actual behavior
I stepped into ```@feathersjs/authentication-jwt``` (lib/index.js) and found hard-coded extractors:

```
const extractors = [
      ExtractJwt.fromAuthHeaderWithScheme('jwt'),
      ExtractJwt.fromAuthHeaderAsBearerToken(),
      ExtractJwt.fromHeader(jwtSettings.header.toLowerCase()),
      ExtractJwt.fromBodyField(jwtSettings.bodyKey)
]
```

Since I did not find any configuration to add (or replace) the default extractors, I edited the ```lib/index.js``` and added a new extractor:

```
const extractors = [
      ExtractJwt.fromAuthHeaderWithScheme('jwt'),
      ExtractJwt.fromAuthHeaderAsBearerToken(),
      ExtractJwt.fromHeader(jwtSettings.header.toLowerCase()),
      ExtractJwt.fromBodyField(jwtSettings.bodyKey),
      ExtractJwt.fromUrlQueryParameter('jwt')
]
```

When I pass a valid JWT to my API ```/api?jwt=...```, passport throws an error because the function call to ```fromUrlQueryParameter``` requires a ```request```parameter with an ```url```property. This property is ```undefined```:

```
return function (request) {
        var token = null,
            parsed_url = url.parse(request.url, true);
        if (parsed_url.query && Object.prototype.hasOwnProperty.call(parsed_url.query, param_name)) {
            token = parsed_url.query[param_name];
        }
        return token;
    }
```

**Module versions** (especially the part that's not working):

@feathersjs/authentication: ^2.1.16"
@feathersjs/authentication-jwt: ^2.0.10
@feathersjs/authentication-local": ^1.2.9

**NodeJS version**:

v10.15.0

**Comment by daffl** [comment]
This is now more easily possible with Feathers v4 authentication by customizing the [JWT strategy](https://crow.docs.feathersjs.com/api/authentication/jwt.html) `parse` function. See the [Migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information on how to upgrade.
