### ISSUE TITLE
A data object must be provided to the 'create' method (Error)

### ISSUE THREAD

**Issue by Vinay328** [feathersjs/feathers#1224]
### Steps to reproduce

Hello Guys, I am calling an endpoint which is of HTTP post method, the data type of request body is plain text and I have set the content-type as text/plain. I am using the POSTMAN tool to make a rest call.

Since Feathers supports only JSON, I have installed body-parser and added as middleware in my application. please find the source code below

app.js file

```js
const feathers = require('@feathersjs/feathers');
const express = require('@feathersjs/express');

const todosService = require('./todos-service');

const bodyParser = require('body-parser');

// This creates an app that is both, an Express and Feathers app
const app = express(feathers());

// Turn on JSON body parsing for REST services
app.use(express.json());

// Turn on URL-encoded body parsing for REST services
app.use(express.urlencoded({ extended: true }));

//Turn on text body parsing for REST services
app.use(bodyParser.text({type: 'text/plain'}));  **//Adding here before rest transport**

// Set up REST transport using Express
app.configure(express.rest());

//Runs a callback function that gets passed the application object, It is used to initialize plugins or services
app.configure(todosService);

// Set up an error handler that gives us nicer errors
app.use(express.errorHandler());

// Start the server on port 3030
const server = app.listen(3030);

server.on('listening', () => console.log('Feathers REST API started at http://localhost:3030'));
```

todos-service.js file

```js
module.exports = function(app) {

    //Register a service
    app.use('todos', {

        async find(params) {
            return "find function called";
        },

        async get(id, params) {
            return "hello " + id + this.count;
        },

        async create(data) {
            console.log("create function called");
            return data;
        }
    });
};
```

Now if the make request -> http://localhost:3030/todos (url)
The response is "A data object must be provided to the 'create' method"

**version**:
 "@feathersjs/express": "^1.3.1",
  "@feathersjs/feathers": "^3.3.1",
"body-parser": "^1.18.3"

**Comment by daffl** [comment]
The bodyparser you are using needs to set `req.body` to an object. If it doesn't you will have to convert it first accordingly in a middleware:

```js
app.use(bodyParser.text({type: 'text/plain'}));
app.use((req, res, next) {
  if (req.body && typeof req.body !== 'string') {
    req.body = { data: req.body };
  }
  next();
});
``

**Comment by Vinay328** [comment]
Hello daffl,

First of all, thank you for your quick reply

About the body-parser module, since feathers internally uses the express framework for rest API calls and express has used the body-parser npm module which I am using for parsing content-type and express supports only JSON parsing ie app.use(express.json());

Requirement for me is to parse the content-type which is text/plain

I implemented the same code shown above without using feathers, but only using the express framework, the code is working, I am able to hit the end point and got a success response, the solution which you proposed you are enforcing that the req.body should be of the object data type.  Does the API of feathers service method ie data parameter accepts only object data type??.

**Comment by daffl** [comment]
Yes, as the error message says, only objects are accepted. As shown in the middleware it should be fairly straightforward to convert between the required types.

**Comment by Vinay328** [comment]
Thank you @daffl
