### ISSUE TITLE
UWS Websocket

### ISSUE THREAD

**Issue by jafri** [feathersjs/feathers#1228]
There is a new faster TS release of uWS, https://github.com/uNetworking/uWebSockets.js

https://medium.com/@alexhultman/millions-of-active-websockets-with-node-js-7dc575746a01

The new version does not work with this library at the moment:

```
  this.ws = new wsModule.Server({
            ^

TypeError: wsModule.Server is not a constructor
```

**Comment by 8BallBomBom** [comment]
Was also wondering the same as this went through.
https://github.com/feathersjs/feathers/issues/1223

Does this perform better than the default Socket.io websocket engine?

**Comment by jafri** [comment]
Yes @8BallBomBom 

While the creator of the project is an interesting and brash maintainer, https://github.com/uNetworking/uWebSockets from a code-level is a mature project existing for over 3 years.

**Comment by 8BallBomBom** [comment]
I was previously using uws this way.
`app.configure( socketio( { wsEngine: 'uws', pingTimeout: 30000 } ) );`
Does that not work with the latest Feathers?

**Comment by daffl** [comment]
This is one of the reasons why Feathers also has a [Primus](https://github.com/primus/primus) adapter which allows support for many other websocket libraries and this looks like an ideal candidate to add to Primus.

Native Feathers transport adapters are usually for more established libraries (this includes reliable maintenance as in not being unpublished at random - currently planned are KoaJS and native HTTP/HTTP2) or will have to be community contributions.

**Comment by 8BallBomBom** [comment]
Sorry for all the confusion.
So best bet would be convert to Primus and then use uWS that way?
Just figuring out a few things for when i upgrade Feathers :+1:

**Comment by daffl** [comment]
Yes, Primus can be used [with all its supported Websocket frameworks](https://github.com/primus/primus#supported-real-time-frameworks)

**Comment by J3m5** [comment]
[New uws related issue](https://github.com/primus/primus/issues/713)
Support not planned, now news since February...

**Comment by daffl** [comment]
Same answer here. If somebody wants to take this on, I'll be happy to help (most websocket commonalities are already taken care of by `@feathersjs/transport-commons`) but it's currently not on my roadmap.

I believe that Feathers will get a lot more out of support for HTTP2 + SSE (server sent events) and other protocols like RabbitMQ which my attention will be focussed on after v4.
