### ISSUE TITLE
Massive Mongodb collection socket timeout

### ISSUE THREAD

**Issue by nsherron90** [feathersjs/feathers#1229]
Hey guys! Any advice on handling a Mongodb collection with 180M documents in it?

Pagination gives a socket timeout and I’d like to be able to have a default limit value for find queries. Any help would be much appreciated :)

**Comment by daffl** [comment]
If pagination is enabled and you still get a timeout it is also important that the fields that are being queried have [proper indexes](https://docs.mongodb.com/manual/indexes/) set up.

**Comment by nsherron90** [comment]
Thanks for the quick reply @daffl ! I have the proper indexes setup but I think the problem is the aggregate count opperation to determin how many docs there are.

For example if I just do a generic get request 

``` bash
curl http://localhost:3000/myendpoint
```

The following aggreation gets triggered in mongodb. Which does a full COLLSCAN.   


```
    "command" : {
        "aggregate" : "import", 
        "pipeline" : [
            {
                "$match" : {

                }
            }, 
            {
                "$group" : {
                    "_id" : null, 
                    "n" : {
                        "$sum" : NumberInt(1)
                    }
                }
            }
        ], 
        "cursor" : {

        }, 
        "lsid" : {
            "id" : BinData(4, "HlHWZ9z1RPiY8GYJJv59+g==")
        }, 
        "$db" : "data"
    }, 
    "planSummary" : "COLLSCAN", 
}
```

My thoughts so far on a possible sollution would be to set a default $limit before hook and disable pagination but I'm still quite stumped. 

I hope I'm articulating my question well enough and can figure this out because I absolutely love feathers thus far.

**Comment by daffl** [comment]
[Here](https://github.com/feathersjs-ecosystem/feathers-mongodb/blob/master/lib/index.js#L106) is the code for the `feathers-mongodb` service. You ca [extend it to customize](https://docs.feathersjs.com/api/databases/common.html#classes-es6) the querying functionality you need. It currently does not have a built-in option to skip the count but a pull request to allow that would be appreciated.
