### ISSUE TITLE
How to use $geoNear using mongodb feathersjs without mongoose

### ISSUE THREAD

**Issue by rehancg** [feathersjs/feathers#1230]
I am trying featherjs for the first time. And stuck on how to use $geoNear to fliter by geo location. I am not using mongoose, only feathers-mongodb

**Comment by daffl** [comment]
Try to create the query by using the MongoDB collection directly using `app.service('myservice').Model`:

```js
const results = await app.service('myservice').Model.aggregate([ {
    $geoNear: {
      includeLocs: "location",
      distanceField: "distance",
      near: {type: 'Point', coordinates: [lng, lat]},
      maxDistance: 1000,
      spherical: true
    }
]);
```

You can set this as `context.result` [in a hook](https://docs.feathersjs.com/api/hooks.html) or use it anywhere else you need it.

**Comment by rehancg** [comment]
Great it worked, just needed to loop through cursor to get the actual result
`while(await cursor.hasNext()) {
            const doc = await cursor.next();
            docs.push(doc);
          }`
