### ISSUE TITLE
Return 400 if url does not map to a service

### ISSUE THREAD

**Issue by nilsboy** [feathersjs/feathers#1232]
### Steps to reproduce

Call any URL that does not map to an implemented service.

### Expected behavior
A service is deployed at /customer
I would like to differentiate between 
- no service deployed behind this URL - should return 400 (i.e. GET /product)
- resource not found by a deployed service - should return 404 (i.e. GET /customer/333)

I have a  feathers instance that gets a lot of requests that are meant for a completely different system. The caller does not notice this though because he expects only status 200 or 404 and 404 is all he gets.

How can this be implemented.

Thank you.

### Actual behavior
Returns 404

**Comment by daffl** [comment]
Implement your own [notFound](https://docs.feathersjs.com/api/express.html#expressnotfoundoptions) middleware that returns a [BadRequest](https://docs.feathersjs.com/api/errors.html) error:

```js
const { BadRequest } = require('@feathersjs/errors');

module.exports = function ({ verbose = false } = {}) {
  return function (req, res, next) {
    const { url } = req;
    const message = `Page not found${verbose ? ': ' + url : ''}`;
    next(new BadRequest(message, { url }));
  };
};
```

**Comment by nilsboy** [comment]
Your solution does not seem to help it just *always* returns 400 now.

This does seem to work but is hacky. Is there a cleaner way?:

`app.use((req, res, next) => {
  let path = require(`url`).parse(req.url).pathname
  path = path.replace(/\/[^\/]+(?!\/$)$/, ``)
  if (!app.service(path)) {
    return res.status(400).send({error: `Invalid URL`})
  }
  next()
})

`

**Comment by daffl** [comment]
This middleware needs to be added **after** all other middleware and before the `errorHandler`, just like the `notFound()` handler [in a generated application](https://github.com/feathersjs/feathers-chat/blob/master/src/app.js#L48)

**Comment by nilsboy** [comment]
Ok, your suggestion does work if I always throw a `NotFound` error from my services.
What I usually do is use a plain `return` (which returns `undefined`) which results in the default fallback which is `NotFound`.
I guess I better throw `NotFound` instead.

Thank you for you help!
