### ISSUE TITLE
IE11 errors with @feahtersjs and @feahtersjs/client

### ISSUE THREAD

**Issue by onexdata** [feathersjs/feathers#1234]
IE11 crashes due to ES6 not being transpiled.

I understand I need to use babel and I am using both babel and webpack.  I need help getting the config right so that it transpiles feathers and debug along with my code, or help getting @feathersjs/client working.  Neither solution is working.

I have spent 2 days reading on this, but nothing has been able to quite solve it. I also see more than half a dozen people asking for help on this in the debug repo, and they get told to google it dispite them saying they have tried.  I also see some people asking for help in this repo, but the issues stagnate. Can you please point me in the right direction and help the community?

I followed the feathers docs here:
https://docs.feathersjs.com/api/client.html#module-loaders

Which suggested I add this to my webpack loaders:
```
{
  test: /\.jsx?$/,
  include: '/src/*', // If I don't add this, babel stops transpiling my /src folder
  exclude: /node_modules(\/|\\)(?!(@feathersjs|debug))/,
  loader: 'babel-loader'
}
```
However, that isn't working. I know it utilizes that rule because my entire repo stops working unless I add '/src/*'
But still, the raw ES6 feathers code is sent to IE11.

This is my babel config...
```
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "useBuiltIns": "usage"
      }
    ]
  ],
  "plugins" : [
    "@babel/plugin-syntax-dynamic-import"
  ]
}
```

I also tried @feathersjs/client which is supposed to have ES5 tanspiled code, and this gets me past some of the feathers errors, but then I get this in IE11:

SCRIPT1003: Expected ":'
in "./node_modules/@feathersjs/commons/lib/commons.js"

So it looks like something still needs commons, which is ES6?

This is the feathers related stuff I have in my dependancies:
```
    "@feathersjs/client": "^3.7.3",
    "feathers-localstorage": "^3.0.0",
    "feathers-vuex": "^1.4.8",
```

**Comment by daffl** [comment]
The `@featherjs/client` module is already transpiled. The error is probably coming from `feathers-localstorage`. If you want a transpiled version of it you need to load `feathers-localstorage/dist/feathers-localstorage`.

**Comment by onexdata** [comment]
Thanks! That fixed it! You're the man!
