### ISSUE TITLE
Complex query 

### ISSUE THREAD

**Issue by wliyongfeng** [feathersjs/feathers#1235]
I use features-mongoose, while my model looks like this:

```javascript
new Schema(
    {
        arr: [Item],
        status: : { type: String }
   }
```

In my app I want to query records with condition like following code:

```javascript
!['a', 'b'].includes(status) && (status !== 'c' || status === 'c' && arr.length <= 0)
```

I checked the [query](https://docs.feathersjs.com/api/databases/querying), but I can not figure out how to compose the query. Do feathers support complex composed or nested query or mongo db native queries?

**Comment by daffl** [comment]
The query syntax allows for a set of standard querying mechanism but there is no limitation on the queries a Feathers service can support but it is important to be familiar with the adapter technology ([Mongoose](https://mongoosejs.com/)) you are using.

If you can write your query as a [Mongoose query](https://mongoosejs.com/docs/queries.html) you can either return that in a [custom service](https://docs.feathersjs.com/api/services.html) or by setting `context.result` (using the model from `context.service.Model` [in a hook](https://docs.feathersjs.com/api/hooks.html)).

**Comment by wliyongfeng** [comment]
@daffl Thanks. Maybe the standard querying is a little weak, and I will search more how to integrate with mongoose query.
