### ISSUE TITLE
socket io - logout event not fired for anonymous users

### ISSUE THREAD

**Issue by FelixButzbach** [feathersjs/feathers#1238]
I read a lot through all the issues and half of the internet but it seams that the disconnect event is not passed through on the server.

In my app I want to track all users that open the page. I also need to know when they leave the page. The only way way I found to know when someone disconnects is by hacking the original io object into the app, like this:

in app.js
```
app.configure(socketio(io => {
    // Registering Socket.io middleware
    io.use(function (socket, next) {
        // Exposing a request property to services and hooks
        socket.feathers.clientId = socket.id;
       // Adding the original socket
        socket.feathers.io = socket
        next();
    });
}));
``` 

And now I am able to do this in channels.js
```
app.on('connection', connection => {
  // On a new real-time connection, add it to the anonymous channel
  app.channel('anonymous').join(connection);
  
  // Keep the clientId around for later
  const clientId = connection.clientId
  
  // Do something with the clientId
  console.log('connection ', clientId);

  // Register the listener for the disconnect event
  connection.io.on('disconnect', event => {
    console.log('dissssss', event, clientId);  
  })

});
```

This seams pretty hacky and I can't believe there is no other way, but I couldn't find it. Please let me know if this is a legitimate way of doing this.
I am using the latest version of feathers.

ps. The solution given here https://github.com/feathersjs/feathers/issues/957 is not working for me, I think because I don\t authenticate the users...

**Comment by tregoning** [comment]
Same here, interested in listening to the 'disconnect' event but looks like is not exposed.

**Comment by FelixButzbach** [comment]
I assume that the answer on this issue (https://github.com/feathersjs/feathers/issues/1243) are valid here as well, but I would be happy about some comment on my approach. Good, Bad, Can do?

**Comment by FelixButzbach** [comment]
@daffl nice. Thanks!
