### ISSUE TITLE
'disconnect' event not exposed.

### ISSUE THREAD

**Issue by tregoning** [feathersjs/feathers#1243]
Looks like the 'disconnect' event not exposed. is this by design?

How can I detect on the server when a user has disconnected? (either via pingTimeout or explicitly calling disconnect() on the client socket?

### Steps to reproduce

app.configure(socketio());
app.on('connection', () => {console.log('connected');});
app.on('disconnect', () => {console.log('disconnected');});

The disconnect callback is never called, after user disconnects.

### Expected behavior
console gets 'connected' and eventually 'disconnected' after the user has disconnected and heartbeat expires, or he/she calls disconnect() directly from the client.

### Actual behavior
console gets 'connected' but never 'disconnect'

**Comment by daffl** [comment]
This will be added in the next version. For now, the [`disconnect`](https://socket.io/docs/server-api/#Event-%E2%80%98disconnect%E2%80%99) event on the [Socket.io socket](https://docs.feathersjs.com/api/socketio.html#appconfiguresocketiocallback) can be used:

```js
app.configure(socketio(function(io) {
  io.on('connection', function(socket) {
    socket.on('disconnect', () => {
     // Do something here
    });
  });
```

**Comment by tregoning** [comment]
Great news, thanks for the super quick reply and for all the effort you have put into this project + open-source, support, etc. Outstanding really appreciate it👍
