### ISSUE TITLE
Websockets timing out with React Native?

### ISSUE THREAD

**Issue by KuanHanrong** [feathersjs/feathers#1249]
Having issues trying to setup a simple test project with websockets.
Followed the Getting Started guide for server-side, and the React Native client side guide listed here: https://docs.feathersjs.com/api/client.html#react-native

So **index.js** on local server is basically :
```
/* eslint-disable no-console */
const logger = require('./logger');
const app = require('./app');
const port = app.get('port');
const server = app.listen(port);

const memory = require('feathers-memory');

process.on('unhandledRejection', (reason, p) =>
  logger.error('Unhandled Rejection at: Promise ', p, reason)
);

server.on('listening', () =>
  logger.info('Feathers application started on http://%s:%d', app.get('host'), port)
);

app.on('connection', connection => app.channel('everybody').join(connection));

app.publish(() => app.channel('everybody'));

// Initialize the messages service
app.use('messages', memory({
  paginate: {
    default: 10,
    max: 25
  }
}));
```
And **App.js** on client side : 

```
import io from 'socket.io-client';
import feathers from '@feathersjs/feathers';
import socketio from '@feathersjs/socketio-client';

const WEB_SOCKETS_URL = 'http://127.0.0.1:3030';

const socket = io(WEB_SOCKETS_URL, {
  transports: ['websocket'],
  forceNew: true,
  pingInterval: 10000,
  pingTimeout: 50000
});

const client = feathers();
client.configure(socketio(socket));

const messageService = client.service('messages');
messageService.on('created', message => console.log('Created a message', message));

type Props = {};
export default class App extends Component<Props> {

  constructor(props) {
    super(props);
  }

  componentDidMount() {
    this.SendMessage();
  }

  async this.SendMessage() {
    try
    {
        await messageService.create({text: 'Message from client'});
    }

    catch(e)
    {
        console.log(e);
    }
  }
```
Error message is simply "Timeout: Timeout of 5000ms exceeded calling create on messages"

Versions:
react-native-cli: 2.0.1
react-native: 0.59.0

**Comment by kfern** [comment]
WEB_SOCKETS_URL can't be 127.0.0.1:3030. This IP is local

**Comment by KuanHanrong** [comment]
Ah, alright.
Sorry, but since I have zero web/backend experience, just to confirm again, there's no way to test websocket functionality via a local server?

**Comment by joaquinwojcik** [comment]
Try to put your IPV4 address. 
For example: 192.168.0.10 
`const WEB_SOCKETS_URL = 'http://192.168.0.10:3030';`

It should work

**Comment by KuanHanrong** [comment]
> @KuanHanrong Try to put your IPV4 address.
> For example: 192.168.0.10
> `const WEB_SOCKETS_URL = 'http://192.168.0.10:3030';`
> 
> It should work

Hmm, tried that and passed in the address I got from ipconfig, still the same issue. I'm going to assume for now that it's a network configuration issue. Will test this out again on other networks and see what results I get.
