### ISSUE TITLE
ES6 all the things!

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers#125]
Seeings as how easy it was authoring in ES6 and using [BabelJS](https://babeljs.io/) to publish in [feathers-commons](https://github.com/feathersjs/feathers-commons) I would suggest to migrate the main repository over to that workflow as well and also pull feathers-commons back in.

With #124 the shared functionality that I initially intended feathers-commons for is all contained in here again so there is no point in pulling it out in 1.x versions. It will make sense for version 2 since I would like to put the providers into separate modules like `feathers-rest`, `feathers-socketio`, `feathers-primus` etc.

Also:

![27zd0v](https://cloud.githubusercontent.com/assets/338316/6542888/34f9bfd8-c4c5-11e4-841f-7f5c40f72eb6.jpg)

**Comment by ahdinosaur** [comment]
> It will make sense for version 2 since I would like to put the providers into separate modules like `feathers-rest`, `feathers-socketio`, `feathers-primus` etc.

:+1:

**Comment by ekryski** [comment]
We should convert the service adapters as well but that will be a breaking change to switch to ES6 classes. The database adapters requiring changes are:

- [ ] mongoose
- [ ] mongodb
- [ ] postgres
- [ ] mysql
- [ ] sqlite
- [ ] mariadb
- [ ] nedb
- [ ] memory

This should be done in conjunction with #164.

**Comment by ekryski** [comment]
Update: This is now being tracked in #170.
