### ISSUE TITLE
Is possible bulk-create using service methods without block the event loop?

### ISSUE THREAD

**Issue by joaquinwojcik** [feathersjs/feathers#1250]
Hello!

Im trying to "bulk-create" ~50k rows using:

```
// transactions is an array with all the data.
transactionService.create(transactions)
```

but the event loop always get stuck. Any suggestions?

**Comment by daffl** [comment]
Can you provide more information? Which database? Outside of `feathers-memory` none of them should be blocking the event loop.

**Comment by joaquinwojcik** [comment]
@daffl Im using `feathers-sequelize@4.1.1`.

**Comment by daffl** [comment]
This won't be blocking the event loop. It is just going to take a bit.

**Comment by joaquinwojcik** [comment]
Hmm, but the server can't process another request until transactions create ends.
Is this method asynchronous?

**Comment by daffl** [comment]
Yes, those methods should be asynchronous but the database will be quite busy processing the requests. At the Feathers level, everything will be processed in parallel.
