### ISSUE TITLE
Feathers - Sequelize - PostgreSql no id returns after create multi entry

### ISSUE THREAD

**Issue by Arc009** [feathersjs/feathers#1253]
### Steps to reproduce
- Enable  option "multi" to allow create bulk
- Post array [{"text":"entity1"},{"text":"entity2"}]

### Expected behavior
return id after creating
[
    {
        "id": 1,
        "text": "entity1",
        "createdAt": "2019-03-19T10:24:03.674Z",
        "updatedAt": "2019-03-19T10:24:03.674Z"
    },
    {
        "id": 2,
        "text": "entity2",
        "createdAt": "2019-03-19T10:24:03.674Z",
        "updatedAt": "2019-03-19T10:24:03.674Z"
    }
]

### Actual behavior
no id returned
[
    {
        "id": null,
        "text": "entity1",
        "createdAt": "2019-03-19T10:24:03.674Z",
        "updatedAt": "2019-03-19T10:24:03.674Z"
    },
    {
        "id": null,
        "text": "entity2",
        "createdAt": "2019-03-19T10:24:03.674Z",
        "updatedAt": "2019-03-19T10:24:03.674Z"
    }
]
### System configuration

**feathers version
3.9.0
**NodeJS version**:
v10.15.1
**Sequelize ORM**:
4.43.0

**Comment by edwardsmarkf** [comment]
In sequelize-mariadb, the model needs to specify the primary key like this:

    id       { type: DataTypes.INTEGER , primaryKey: true, allowNull:
false, autoIncrement: true     }

**Comment by Arc009** [comment]
Can you apply this to UUID ? (postgreSql)
id: {
      type: DataTypes.UUID,
      allowNull: false,
      primaryKey: true,
      defaultValue: DataTypes.UUIDV4
}
With multi entry id returns is always null.

**Comment by edwardsmarkf** [comment]
>>>  Can you apply this to UUID ?

i have used the awesome FeathersJS against cockroachDB, which uses postgres
calls.

to get it to work using cockroachDB, i used this:

type: Sequelize.STRING

instead of DataTypes.UUID

also, you might go into sequelize.js and change logging to "true" to see
the initial table create [IF NOT EXISTS], what it looks like.

hope this helps!

Thank you,

Mark Edwards

**Comment by soorur** [comment]
Same issue with feathers-sequelizee 4.1.1

**Comment by daffl** [comment]
I added a test in https://github.com/feathersjs-ecosystem/feathers-sequelize/pull/282 that verifies that this works with the standard Sequelize adapter. Please provide a breaking example to reproduce the issue.

**Comment by joserobleda** [comment]
@Arc009 any luck with your issue? I'm facing the same problem and I can't get any clue on what may happens. Thanks!

**Comment by Arc009** [comment]
Hello @joserobleda I have to check my code, as I can remember the problem is the ORM Sequelize, I had to bypass it and write a plain SQL INSERT . I played a long time ago with Sequelize, some simple query are simply impossible to achieve, keep it in mind.

**Comment by a7mad206** [comment]
You can add the following to the create hook for the service. It worked for PostgreSQL + Sequelize
`context.params.sequelize = { individualHooks: true };`

Sample service.hooks.js:

`let moduleExports = {
  before: {
    // Your hooks should include:
    //   all   : authenticate('jwt')
    // !code: before
    all: [],
    find: [],
    get: [],
    create: [async (context) => {
      context.params.sequelize = { individualHooks: true };
      return context;
    }],
    update: [],
    patch: [],
    remove: []
    // !end
  },`
