### ISSUE TITLE
Error $limit/$skip

### ISSUE THREAD

**Issue by GlauberF** [feathersjs/feathers#1254]
### Version Featherjs
3.9.0

### Problem

I have a total of 11 records, I am saturating a limit of 10 records per page.
Automatically, it would have to have two pages, one page with 10 records and another page with the remaining 1 record.

($ skip = 1) returns 10 records, only removing the first one and changing the last one.

always returning 10.

But I want it to return what has to register on that page, in case if I skipped 1 page, it returns the rest that is on that page which is 1 record.

![Captura de Tela_selecionar área_20190319092434](https://user-images.githubusercontent.com/11314585/54605872-105aa000-4a29-11e9-9fd4-fdc01e5a6877.png)

in this next call, it should return 1 record, since it has 11 in total

![Captura de Tela_selecionar área_20190319092614](https://user-images.githubusercontent.com/11314585/54605921-27998d80-4a29-11e9-8cbe-6ba3fc537bef.png)

I tried several possible ways and I could not identify what I'm doing wrong, since the paging already defaults to the framework

**Comment by daffl** [comment]
The second page or `pageNumber` in general is `$skip: (pageNumber - 1) * pageSize`. If you want the second page of 10 you'd do `{ $skip: 1 * 10, $limit: 10 }`, the third would be  `{ $skip: 2 * 10, $limit: 10 }` etc.

**Comment by GlauberF** [comment]
thanks
