### ISSUE TITLE
Cancel hook in find()

### ISSUE THREAD

**Issue by dmenne** [feathersjs/feathers#1255]
I have seen https://github.com/feathersjs/feathers/issues/635, but I still do not understand what's the easiest way to request something like

```
      service.find(params, cancelAllHooks = true )
```

to call the vanilla find, without making changes in the hooks.

**Comment by daffl** [comment]
With the latest version of the standard database adapters you can call the method without hooks by using `service._find(params)` (see the [migration guide](https://crow.docs.feathersjs.com/migrating.html#hook-less-service-methods)).

**Comment by dmenne** [comment]
Great!
