### ISSUE TITLE
http-errors version referenced by package.json is broken

### ISSUE THREAD

**Issue by SephReed** [feathersjs/feathers#1258]
### Steps to reproduce

Using fuse-box, create a project which imports feathers-express

### Expected behavior
Should compile

### Actual behavior
See this issue.  The version of http-errors you are using breaks the compile if tree shaking removes a random uneeded depedency 

https://github.com/jshttp/http-errors/pull/9

This is a really simple change for you, but I'd have to fork your entire project to update your package.json to not use the broken version of http-errors.

**Comment by daffl** [comment]
This module is not a direct dependency of any Feathers module so I'm not sure what exactly the required change would be.

If it has been fixed in a more recent version, `rm -rf node_modules package-lock.json && npm install` in your project might fix this already.
