### ISSUE TITLE
params.user in next hook before by internal service

### ISSUE THREAD

**Issue by SeaDog505** [feathersjs/feathers#1259]
I have a service named for example wallet. I use authorization all users. I used below code in my project:

    function(hook){

       /* Hook before */

       var user = hook.params.user;
       var data = hook.data;

       data.user = {
           _id: user._id,
           name: user.name
       }
    }

I want get info about user, which creates a new document so when I called my service from my javascript, the information about logged user is added to mongo document but when I try running the wallet service from another hook after, I receive error the user._id is undefined. The user params is undefined, the user object is not exists. How can I get info about user, which in fact not run the service but the service is run by hook?

**Comment by daffl** [comment]
You either have to pass `params.user` manually or pass `params.authentication` using the new Feathers v4 authentication. See the [Migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information on how to upgrade.

**Comment by lokeshdangi** [comment]
migrated from v3 to v4, switched out the  authenticate to `const { authenticate } = require("@feathersjs/express");`
`params.authentication`  contains this object.
`
``` 
{
 strategy: 'jwt',
 accessToken:  'token 
}
```
It is not adding the user object to the params.
Reverting the import to `const { authenticate } = require("@feathersjs/authentication").hooks;` works as expected.
Am I missing something in the migration ?
