### ISSUE TITLE
Error format

### ISSUE THREAD

**Issue by PowerMogli** [feathersjs/feathers#1262]
### Steps to reproduce

We are using @feathersjs/feathers version 3.1.3 with @feathersjs/errors version 3.3.0. 

We configure authentication service with some hooks:
```ts
app.service('authentication').hooks(authHooks(app));

function authHooks(app) {
  const config = app.get('authentication');
  return {
    before: {
      create: [validateUserAccess, authentication.hooks.authenticate(config.strategies)],
      remove: [authentication.hooks.authenticate('jwt')],
    },
  };
}
```
When we throw a Forbidden error object inside the validateUserAccess hook then we get a json object back (called by rest&ws). When we throw a Forbidden error object inside service hook we get html back without error code (rest&ws). Why is that? 

We would like to get the same json output for hooks before service calls and hooks for authentication.

**Comment by daffl** [comment]
The error format is determined by the client request by setting the `Accept` header. For JSON it should be `application/json` and then you should get back what you are expecting.

**Comment by PowerMogli** [comment]
I am sorry but that did not the trick. We still receive html.

**Comment by daffl** [comment]
What is your setup? Did you configure the [error handler](https://docs.feathersjs.com/faq/readme.html#why-am-i-not-getting-json-errors)?

**Comment by PowerMogli** [comment]
```ts
import { factory, mongodb } from '@alberta/konexi-api-shared';
import feathersSync = require('@bitscheme/feathers-sync');
import configuration = require('@feathersjs/configuration');
import express = require('@feathersjs/express');
import feathers = require('@feathersjs/feathers');
import socketio = require('@feathersjs/socketio');
import compress = require('compression');
import cors = require('cors');
import helmet = require('helmet');

import { hooks } from './app.hooks';
import authentication from './authentication';
import { channels } from './channels';
import { discovery } from './discovery';
import { services } from './services';

const app = express.default(feathers.default());

app.configure(configuration());

app.set('logger', factory(app.get('service')));

app.use(cors());
app.use(helmet());
app.use(compress());
app.use(express.json({ limit: '100mb' }));
app.use(express.urlencoded({ limit: '100mb', extended: true }));
app.configure(express.rest());
app.configure(
  socketio.default(
    {
      allowUpgrades: false,
      serveClient: false,
      transports: ['websocket'],
      pingInterval: 40000,
    },
    io => {
      io.use((socket, next) => {
        (socket as any).feathers.connection_id = socket.id;
        next();
      });
    },
  ),
);
app.configure(mongodb);
app.configure(authentication);
app.configure(discovery);
app.configure(services);
app.configure(channels);
app.use(express.errorHandler());

app.get('mongoClient').then(client => {
  app.configure(
    feathersSync.mongodb({
      db: client.db('sync'),
      collection: 'sync',
    }),
  );
});

app.hooks(hooks);

export default app;
```

**Comment by daffl** [comment]
And what's the code for when you are getting the right error and when not?

**Comment by PowerMogli** [comment]
This is when right error:
```ts
import authentication = require('@feathersjs/authentication');
import jwt = require('@feathersjs/authentication-jwt');
import local = require('@feathersjs/authentication-local');

import apikey from './auth-strategies/apikey';
import { authHooks } from './hooks/auth-hooks';

export default function(app) {
  const config = app.get('authentication');

  // Set up authentication with the secret
  app.configure(authentication.default(config));
  app.configure(jwt.default());
  app.configure(local.default());
  app.configure(apikey({ header: config.apiKey.header }));
  // The `authentication` service is used to create a JWT.
  // The before `create` hook registers strategies that can be used
  // to create a new valid JWT (e.g. local or oauth2)
  app.service('authentication').hooks(authHooks(app));
}
```
inside ./hooks/auth-hooks:
```ts
export function authHooks(app) {
  const config = app.get('authentication');
  return {
    before: {
      create: [validateUserAccess, authentication.hooks.authenticate(config.strategies)],
      remove: [authentication.hooks.authenticate('jwt')],
    },
  };
}

const validateUserAccess = async (context: HookContext<any>) => {
  const userService = context.app.service('users');
  const config = context.app.get('authentication');
  const users = await userService.find({
    query: {
      [config.local.usernameField]: context.data[`${config.local.usernameField}`],
      $limit: 1,
    },
  });

  if (users && users.length && typeof users[0].active === 'boolean' && !users[0].active) {
    throw new Forbidden('You don`t have the permission to execute the requested operation.');
  }

  return context;
};
```

when not: 
```ts
const validateUserAccess = async (context: HookContext<any>) => {
  const {
    params: { user },
  } = context;

  if (typeof user.active === 'boolean' && !user.active) {
    throw new Forbidden('You don`t have the permission to execute the requested operation.');
  }

  return context;
};

export function registerRoute(app: Application<any>, route: IRoute) {
  app.use(`/${route.apiRoute}`, new Proxy(route.apiRoute, route.upstreamUrl, route.customEvents));
  const proxy = app.service(route.apiRoute);
  proxy.hooks({
    before: {
      all: [
        commonHooks.paramsFromClient('apiKey', 'accessToken', 'changes', 'authorization', 'fromExternalApi'),
        ctx => {
          const config = ctx.app.get('authentication');
          if (ctx.params.accessToken) {
            ctx.params.headers = { ...ctx.params.headers, authorization: ctx.params.accessToken };
          }
          if (ctx.params.headers && !ctx.params.headers.hasOwnProperty(config.apiKey.header)) {
            ctx.params.headers[config.apiKey.header] = ctx.params.apiKey;
          }
        },
        authenticate(),
        populateAuthUser(),
        commonHooks.iff(ctx => ctx.params.fromExternalApi, populateUserWithAuthorization()),
      ],
      find: [validateUserAccess, validatePermission(Permission.Synchronize)],
      create: [validateUserAccess, validatePermission(Permission.Write)],
      patch: [validateUserAccess, validatePermission(Permission.Write), changeTrackerLog(), changeTrackerWriteDb()],
    },
  });
}
```

**Comment by PowerMogli** [comment]
I am sorry that is all I can answer for. I hope it is enough to find out the issue.

**Comment by KidkArolis** [comment]
Could you put a breakpoint or `console.log(req.headers)` on [`node_modules/@feathersjs/errors/lib/error-handler.js#97`](https://github.com/feathersjs/feathers/blob/master/packages/errors/lib/error-handler.js#L97) to show us what headers the request is receiving in both cases?

**Comment by PowerMogli** [comment]
The breakpoint for html response never gets hit in error-handler.js

The error code goes the following path: 
[node_modules/@feathersjs/express/lib/rest/wrapper.js#84](https://github.com/feathersjs/feathers/blob/master/packages/express/lib/rest/wrappers.js#L84) then [node_modules/express/lib/router/route.js#135](https://github.com/expressjs/express/blob/master/lib/router/route.js#L135) and finally [node_modules/express/lib/router/layer.js#67](https://github.com/expressjs/express/blob/master/lib/router/layer.js#L67)

**Comment by DattaramNaik** [comment]
I am using feather js backend  ....

I am getting error response in html format 

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Error</title>
    </head>
    <body>
        <pre>
            NotAuthenticated: Invalid login<br>
            &nbsp;&nbsp;at LocalStrategy.findEntity (D:\pracup\Pracup Devlopment\pracup_backend\node_modules\@feathersjs\authentication-local\lib\strategy.js:60:19)<br>
            &nbsp;&nbsp;at process.processTicksAndRejections (node:internal/process/task_queues:95:5)<br>
            &nbsp;&nbsp;at async LocalStrategy.authenticate (D:\pracup\Pracup Devlopment\pracup_backend\node_modules\@feathersjs\authentication-local\lib\strategy.js:105:24)<br>
            &nbsp;&nbsp;at async AuthenticationService.create (D:\pracup\Pracup Devlopment\pracup_backend\node_modules\@feathersjs\authentication\lib\service.js:82:28)<br>
            &nbsp;&nbsp;at async AuthenticationService.&lt;anonymous &gt;(D:\pracup\Pracup Devlopment\pracup_backend\node_modules\@feathersjs\authentication\lib\hooks\connection.js:4:5)<br>
            &nbsp;&nbsp;at async AuthenticationService.&lt;anonymous &gt;(D:\pracup\Pracup Devlopment\pracup_backend\node_modules\@feathersjs\authentication\lib\hooks\event.js:6:5)<br>
            &nbsp;&nbsp;at async AuthenticationService.&lt;anonymous &gt;(D:\pracup\Pracup Devlopment\pracup_backend\node_modules\@feathersjs\schema\lib\hooks\resolve.js:115:5)<br>
            &nbsp;&nbsp;at async AuthenticationService.logError (file:///D:/pracup/Pracup%20Devlopment/pracup_backend/src/hooks/log-error.js:5:5)<br>&nbsp;&nbsp;at async D:\pracup\Pracup Devlopment\pracup_backend\node_modules\@feathersjs\express\lib\rest.js:33:25
        </pre>
    </body>
</html>

I want json format 

I am sending application/json through client still getting html response .

**Comment by daffl** [comment]
When submitted from the browser, it will always prefer HTML. You can disable HTML responses completely with the [`{ html: false }` option](https://feathersjs.com/api/express.html#app-use-errorhandler-options)
