### ISSUE TITLE
Where is @feathersjs/authentication-oauth2?

### ISSUE THREAD

**Issue by sjones6** [feathersjs/feathers#1264]
I'm looking for the source code for @feathersjs/authentication-oauth2 to troubleshoot some issues I'm seeing in my app. I found the archived repo which states it's been moved to the monorepo: https://github.com/feathersjs/authentication-oauth2. However, it doesn't seem to be here either. The[ NPM listing](https://www.npmjs.com/package/@feathersjs/authentication-oauth2) points back to the monorepo.

Can someone point me to where this package lives now?

(sorry if this isn't the right forum for the question—wasn't sure where else to ask)

**Comment by KidkArolis** [comment]
Authentication modules are being rewritten at the moment, I think that's the reason they're gone from master. The new oauth modules are still in progress. So to see the code, you need to jump back the commit history a bit, e.g. here's the code from January:

https://github.com/feathersjs/feathers/tree/3ad094ee4099775237c0d78806208696bb744e84/packages/authentication-oauth2

**Comment by daffl** [comment]
You can also go directly to the `buzzard` branch: https://github.com/feathersjs/feathers/tree/buzzard

**Comment by sjones6** [comment]
Thanks @KidkArolis and @daffl .

The issues I'm seeing are around error handling. For instance, I was using google-oauth2 passport strategy and had an invalid client secret (so token verification would fail). Instead of dropping into the error handler I was passing in, it'd hit the generic error handler and dump out the error stack. Happy to file a separate issue if you want but I imagine this is changing if it's being rewritten right now.

**Comment by KidkArolis** [comment]
Shall we close this issue?

**Comment by sjones6** [comment]
@KidkArolis . Sure.
