### ISSUE TITLE
Verifier doesnt seem to support async verify functions

### ISSUE THREAD

**Issue by CheyenneForbes** [feathersjs/feathers#1265]
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [x] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc. This makes it much easier for us to debug and issues that have a reproducable example will get higher priority.

**require('@feathersjs/authentication-local').Verifier doesnt seem to support async verify functions**

I'm interested in using a async verify function because my verification process uses a few awaits

```
const authentication = require('@feathersjs/authentication');
const jwt = require('@feathersjs/authentication-jwt');
const local = require('@feathersjs/authentication-local');

class LoginVerifier extends local.Verifier {
  async verify(req, email, password, done){
    throw(123);
  }
}

module.exports = function (app) {
  const config = app.get('authentication');

  // Set up authentication with the secret
  app.configure(authentication(config));
  app.configure(local({ Verifier: LoginVerifier }));

  // The `authentication` service is used to create a JWT.
  // The before `create` hook registers strategies that can be used
  // to create a new valid JWT (e.g. local or oauth2)
  app.service('authentication').hooks({
    before: {
      create: [
        authentication.hooks.authenticate(config.strategies)
      ],
      remove: [
        authentication.hooks.authenticate('jwt')
      ]
    }
  });
};
```

### Expected behavior
I expected that errors would be handled properly just as when they are thrown in async service method functions

### Actual behavior
I get `error: Unhandled Rejection at: Promise`

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
    "@feathersjs/authentication": "^2.1.13",
    "@feathersjs/authentication-jwt": "^2.0.7",
    "@feathersjs/authentication-local": "^1.2.7",
    "@feathersjs/configuration": "^2.0.4",
    "@feathersjs/errors": "^3.3.4",
    "@feathersjs/express": "^1.2.7",
    "@feathersjs/feathers": "^3.2.3"

**NodeJS version**: 11.0.0

**Operating System**: Ubuntu via WSL

**Comment by daffl** [comment]
All Feathers v4 authentication strategies are now asynchronous by default. See the [Migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information on how to upgrade.
