### ISSUE TITLE
Authentication: 2 different user services, 2 different configs, 2 different tokens

### ISSUE THREAD

**Issue by jnardone** [feathersjs/feathers#1267]
Using feathers authentiation 2.1.x and related...

Is it possible to have 2 different authentication configurations supported by a single app?  We have both a main app and a (for lack of a better word) external user portal we want to serve in the same app.  These two sites essentially are independent from an auth scheme - there are separate user services, separate auth configs (including different local storage names, secrets, expirations, etc.) 

My first problem is that `app.configure(authentication(config));` hardcodes an `app.set` on `authentication`.  Is there a way of having independent configs, or do they need to be combined?  

If they are combined in a single configuration, what is the proper format of the configuration JSON to declare two completely independent authentication schemes?  https://docs.feathersjs.com/api/authentication/server.html#options implies a single-level and no hierarchy; is there a way to namespace multiple configurations within the configuration JSON?

Thanks for any ideas on how I can solve this.

**Comment by jnardone** [comment]
I've reached a quandary point, and I'm further confused by whether I can even do this in Buzzard/2.1.x or not. I can (seemingly) define 4 different strategies in my config (a local and JWT for my primary, and a local and JWT for my other service).  That gives me one config.  However, due to hook differences I *must* register *two different authentication services* using this config.  Is there a way to have 2 distinct auth services, even if they share the same config, even if the 2 are explicit about using either one set of strategies or the other?  

It is frustrating that the current source in github/master is NOT the current production code but is not-yet-ready v3 code.  It makes researching this really tricky.  I cannot wait for Crow, unfortunately.

**Comment by jnardone** [comment]
This is possible, but not cleanly.  Hoping Crow will be better.

**Comment by daffl** [comment]
It will be indeed. You can explicitly register the authentication service with the configuration key you want it to use:

```js
const auth1Service = new AuthenticationService(app); // uses `authentication`
const auth1Service = new AuthenticationService(app, 'otherAuth'); // uses `otherAuth`

app.use('/auth1', auth1Service);
app.use('/auth2', auth2Service);
```

Currently in master and about to be published as a beta release shortly (just working on oAuth).

**Comment by UDB** [comment]
**this is for version 4.x**
 
the `defaultAuthentication` is always the one whichever is initialized  first. 

> const auth1Service = new AuthenticationService(app); // uses `authentication`
const auth2Service = new AuthenticationService(app, 'otherAuth'); // uses `otherAuth`

in this case the `defaultAuthentication` will be set as the config-key(i.e. default 'authentication') of first statement. 

Now suppose If there two authentication configuration in config file for authenticating two different entities, say one for `users` named `user-authentication` and one for `admin` named `admin-authentication`.

```
const userAuth = new AuthenticationService(app,'user-authentication'); //defaultAuthentication is 'user-authentication'
const adminAuth = new AuthenticationService(app, 'admin-authentication');

app.use('/user-auth', userAuth);
app.use('/admin-auth', adminAuth);
```

So in the service hooks where specific authentication service is required we can call the authenticate hook as(taking JWT as an example):

`authenticate( { service: 'admin-auth',  strategies : [ 'jwt' ] } )`

In case if not using role based access this can be followed by a custom `authorisation` hook. For example

```
const {NotAuthenticated}= require('@feathersjs/errors');

module.exports.authorize = function () {
 
 return async function (hook) {
    let isAuthorized = hook.params.admin ? hook.params.admin instanceof hook.app.service('admin').Model : false;

    if(!isAuthorized){
     //use forbidden if that fits the case
      throw new NotAuthenticated('Unauthorized: Admin Only');
    }

    hook.params.authorized = {
      status: isAuthorized,
      userType: 'admin'
    };

    return hook;
  };
};
```
