### ISSUE TITLE
Sequelize Database Error - Sequelize.DataTypes.UUID fails

### ISSUE THREAD

**Issue by Asher978** [feathersjs/feathers#1273]
### Steps to reproduce

- [x] create id with 
```javascript

import Sequelize from "sequelize";
const DataTypes = Sequelize.DataTypes;


id: {
        type: DataTypes.UUID,
        allowNull: false,
        primaryKey: true,
        autoIncrement: true
      },
```
### Expected behavior
an id should be generated with incrementation for every new resource thats being generated

### Actual behavior
error reported with a code 42601

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by daffl** [comment]
UUIDs can not be auto incremented. Your field definition should be

```js
id: {
  type: DataTypes.UUID,
  allowNull: false,
  primaryKey: true,
  defaultValue: Sequelize.UUIDV4
},
```

**Comment by Asher978** [comment]
So sorry for the trouble. Worked as expected per your directions.


Thanks so much!
