### ISSUE TITLE
Auto increment column value null in publish event in case of call create method with array of objects

### ISSUE THREAD

**Issue by vinaykharecha** [feathersjs/feathers#1279]
### Steps to reproduce

- When i call **create** method with **array of objects** as input i.e. more than one insert, at that time **publish event** on that method is sending out **null value for auto increment** column.
- However when i call **create** method with **only single object** instead of array of object at that time auto increment column is populating

### Expected behavior
Behaviour should be consistent! either publish event should always have null for auto increment column or it should always have value regardless or input type

### Actual behavior
In case of array of object auto increment column's value is null

### System configuration

- I am using feathers-sequelize with model for postgres table without any association

**Module versions** (especially the part that's not working): 
 - @feathersjs/feathers : 3.2.3  
 - feathers-sequelize : 3.1.0
 - pg : 7.4.3

**NodeJS version**: v11.7.0

**Operating System**: Linux - Ubuntu

**Browser Version**: N.A.

**React Native Version**: N.A.

**Module Loader**: N.A.

**Comment by daffl** [comment]
[Set params.sequelize](https://github.com/feathersjs-ecosystem/feathers-sequelize#paramssequelize) `params.sequelize.returning = true;`. See https://stackoverflow.com/questions/35079286/sequelize-bulkcreate-returns-null-value-for-primary-key/35081421#35081421.

**Comment by vinaykharecha** [comment]
@daffl you are saviour as always and thanks for a really quick response :)

That did work! I just had to put following code in create hook of the service
```javascript
before: {
    all: [authenticate('jwt')],
    find: [],
    get: [],
    create: [(context) => {
      context.params.sequelize = {
        returning: true
      };
      return context;
    }],
    update: [],
    patch: [],
    remove: []
  }
```
I wanted this behaviour in all the service so instead of putting it at service level i placed above function in application level create hook.

FYI: as per sequelize doc they says that it is only supported for postgres ([link](http://docs.sequelizejs.com/class/lib/model.js~Model.html)) however i tried for MS SQL and that flag has a same effect for create method call as it has for postgres

**PS:** @daffl Shouldn't this be made **default** in feathers, so that behaviour of feathers stays **consistent**?

**Comment by daffl** [comment]
This used to be the default but it might've accidentally gotten lost in https://github.com/feathersjs-ecosystem/feathers-sequelize/pull/281

**Comment by daffl** [comment]
Nevermind, that only applied to patch. What's odd is that the test I added in https://github.com/feathersjs-ecosystem/feathers-sequelize/pull/282/files is passing either way. Anyway, added it as a default in https://github.com/feathersjs-ecosystem/feathers-sequelize/pull/286 and `feathers-sequelize` 5.1.1

**Comment by vinaykharecha** [comment]
Okay that is great; now i can remove the hook code with feathers-sequelize 5.1.1. Thank you @daffl
