### ISSUE TITLE
Authenticate with case-insensitive usernames

### ISSUE THREAD

**Issue by EliSadaka** [feathersjs/feathers#1282]
By default local authentication fails if the given username's case doesn't match exactly with what is stored in the database. How can I implement authenticating with case-insensitive usernames?

**Comment by daffl** [comment]
This can all be done through hooks. E.g. by `.toLowerCase()`ing `hook.data.email` before saving it and adding the same hook `before` the `/authentication` service or by using the database adapters case-insensitive querying mechanism.

**Comment by EliSadaka** [comment]
The usernames still need to be stored in a case-sensitive manner so that first method wouldn't work for me. How would I change the query that performs the db lookup to replace it with my own implementation?

**Comment by daffl** [comment]
By [customizing the verifier](https://docs.feathersjs.com/api/authentication/local.html#verifier).

**Comment by EliSadaka** [comment]
Thanks for the help. I figured it out by copying the `verify` method from [here](https://github.com/feathersjs/authentication-local/blob/master/lib/verifier.js) and making modifications to the query.
