### ISSUE TITLE
[Security] Service patch(null) method does not follow the `$limit` modifier in query params.

### ISSUE THREAD

**Issue by JorgenVatle** [feathersjs/feathers#1283]
### Steps to reproduce
- Create service
- Fill service with test entries
- Run `service.patch(null, { patched: true }, { query: { $limit: 1 } })`

### Expected behaviour
The service `patch()` call should only update the given quantity of entries when called with a query containing the `$limit` modifier.

### Actual behaviour
The `patch()` request updates all entries in the service. If you specify additional query parameters, the update will only update the matched entries. But the `$limit` modifier is still not adhered to.

Omitting additional query parameters, leaving just a `$limit` updates everything in the service.

### System configuration
Happens in a fresh FeathersJS project.

See the following project branch for a test asserting the behaviour.
https://github.com/JorgenVatle/feathers-factory/blob/patch-%24limit-not-working/test/FeathersFactory.spec.ts#L86

### Notes
I'm not sure whether or not this behaviour is intentional. If it is, I'd argue it might be a better idea to throw an exception when someone attempts to pass a `$limit` modifier to a `patch` request. As it is easy to assume that the `$limit` modifier does indeed limit `patch` requests considering the documentation on the modifiers in the [Feathers Documentation](https://crow.docs.feathersjs.com/api/databases/querying.html#querying) implying that it does indeed work with `patch` requests when the `id` argument is set to `null`.

**Module versions**:
- `@feathersjs/feathers` v3.3.1

**Tested with the following DB modules**
- `feathers-memory` v3.0.2 
- `feathers-mongoose` v7.3.2
- `mongoose` v5.4.22

**NodeJS version**:
v10.15.3

**Comment by daffl** [comment]
Fair point, `$limit` or `$skip` were not intended to work for multi updates or remove. A PR to throw an exception for all database adapters would be much appreciated. A generic `before` hook can also be used to handle this case:

```js
const { BadRequest } = require('@feathersjs/errors');

const multiProtectHook = async context => {
  const { id, params: { query = {} } } = context;

  if (id === null && (query.$limit !== undefined || query.$skip !== undefined)) {
    throw new BadRequest('Query is not allowed');
  }

  return context;
}
```
