### ISSUE TITLE
how send data to user on new socket connection?

### ISSUE THREAD

**Issue by matiaslopezd** [feathersjs/feathers#1286]
Hi! I want send data to the client after socket connection based if I not exist data like `token` and `uuid`.

But in client-side never recieve response :pensive:.

**channels.js**
```javascript
  app.on('connection', async connection => {
    if (connection.socketQuery.token && connection.socketQuery.uuid){
      // On a new real-time connection, add it to the anonymous channel
      const decoded = await jwt.decode(connection.socketQuery.token, secret, false, 'HS256');
      const account = await hasher.decode(decoded.rac);
      app.channel(`${account}/${connection.socketQuery.uuid}`);
    }else{
      const random = `${Math.random().toString(30).substring(2)}/${Math.random().toString(36).substring(2)}`;
      // Option 1
      app.channel(random).join(connection);
      app.channel(random).send({
        code: 401,
        msg: `Token is ${connection.socketQuery.token} or UUID ${connection.socketQuery.uuid}`
      });
      // Option 2
      throw new errors.BadRequest(`Token is ${connection.socketQuery.token} or UUID ${connection.socketQuery.uuid}`);
    }
  });
```

Thanks!

**Comment by KidkArolis** [comment]
The publish/filter/send functions on channels are used to declaratively configure what data will go to what channels. They don't do any sending on their own.

The data to sockets is sent by emitting events on services (or sockets).

So you could try `connection.emit('initial-payload', {})` (not sure if that will work).

Or better yet, create a new service, e.g. `app.use('/init', init)` and then call `app.services('init').create({ some: 'data'})`. Now your client will receive `init create` event with the payload. That is you can listen to this on client with `app.services('init').on('create')`.

Alternatively again, you can follow the custom event guide: https://crow.docs.feathersjs.com/api/events.html#custom-events if you prefer to not use this `create` event but want a custom one..

I hope one of these options works for you.

**Comment by KidkArolis** [comment]
@matiaslopezd perhaps you could close this issue if the above helped resolve your problem?
