### ISSUE TITLE
help - feathers as a backend for nuxt.js with apollo or graphql

### ISSUE THREAD

**Issue by syffs** [feathersjs/feathers#1287]
I'm considering reworking a rest api mainly using express to use a more structured backend framework with graphql.

Hence, I'm testing feathers out, and I'm honestly getting lost trying to figure out how to set it up with Nuxt.js. Here are a my concerns:

- **Nuxt / apollo**: they work well together, thanks to [nuxt-apollo](https://github.com/nuxt-community/apollo-module), so in order to set up graphql with nuxt, it might make sense to use apollo
- **Nuxt / feathers**: official examples are outdated - I'm quite unsure about the recommended way to go
    - [nuxt official example](https://github.com/nuxt/nuxt.js/tree/dev/examples/with-feathers) uses feathers 2
    - [@feathers-plus/vuex](https://github.com/feathers-plus/feathers-vuex) / [gustojs/nuxt-feathers-vuex](https://github.com/gustojs/nuxt-feathers-vuex) seem to be good option, but not sure how it'd work with feathers/graphql
    - unofficial example seem messy
        - [fexell/Feathers-Nuxt](https://github.com/fexell/Feathers-Nuxt)
        - [silvestreh/feathers-nuxt](https://github.com/silvestreh/feathers-nuxt)
- **feathers / graphql**
    - _does it make sense to run feathers with apollo-server ?_ I'm under the (maybe wrong) impression that feathers and apollo both attempt to solve same issues but not exactly the same way (`@feathers/client` vs `apollo-client`)
    - `feathers-plus/graphql`
- **feathers / esm**: _Is there a way to make feathers and its generators work with esm ?_
I'd like consistency as Nuxt lets you use latest js standards, and even if I could set up esm quite easily with feathers, generators (cli and cli+) seem to generate everything with cjs. 

if some feathers guru could shed some light, any help is appreciated, thanks !

**Comment by bskimball** [comment]
I have set up nuxt and feathers project which was pretty easy but I used web sockets and vuex-feathers. The integration is really nice and you can build a real-time app pretty quickly. I did not use graphql but I have wanted to play with Apollo.

The examples below can probably get you going on your integration. 

Here is a vue-cli, apollo, feathers example

“Get a rapid start on IBM Cloud with VueJS, FeathersJS, and GraphQL” by Thomas Reinecke https://link.medium.com/rBGTLXL6MW

And a nuxt feathers example
https://github.com/silvestreh/feathers-nuxt?files=1
