### ISSUE TITLE
infinite wait request and CPU leak due to pending promise: global timeout?

### ISSUE THREAD

**Issue by blackholegalaxy** [feathersjs/feathers#1290]
### Steps to reproduce

By mistake we created an never-ending promise resolution in our code. We were then able to detect a potential problem under feathers.

In a service we used this method:
```javascript
 async update(id: Id, params: Params) {
    const request = this.findInQueue(id);
    return new Promise (async (resolve, reject) => {
      !!request && !!request.chunks.set(params.index, params.value) ?
        request.errorCount = 0 && await resolve(true) :
        await reject('Unable to update request');
    });
  }
```

The missing second `=` in `request.errorCount = 0` makes this attribution always returning `true` as you can guess. So our promise never resolves nor reject.

### Expected behavior
We expect feathers to trigger a global promise/async timeout and finally triggers an error at framework level when this infinite state is triggered. An option should be available in configuration of framework maybe.

The request being stuck in `wait` state the feathers app is being stuck there. Chain of execution is broken there. Maybe feathers could detec whenever a promise or something else causes such problem. And it should timeout the request, killing the pending stuck execution.

### Actual behavior
The http request in browser stays at `wait` state undefinitely. And CPU rises on server side until the machine finally crashes.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
```
"@feathersjs/authentication": "2.1.16",
"@feathersjs/authentication-jwt": "2.0.10",
"@feathersjs/authentication-local": "1.2.9",
"@feathersjs/configuration": "2.0.6",
"@feathersjs/errors": "3.3.6",
"@feathersjs/express": "1.3.1",
"@feathersjs/feathers": "3.3.1"
```

**NodeJS version**:
10.15.0

**Operating System**:
Ubuntu 18.04 and macOS

ping @daffl

**Comment by daffl** [comment]
The Feathers server does not have a built-in timeout mechanism, it is up to you to handle it. In your case a better use of `async` methods without wrapping it in a `Promise` would probably avoid those kinds of issues completely:

```js
 async update(id: Id, params: Params) {
  const request = this.findInQueue(id);

  if (request && !!request.chunks.set(params.index, params.value)) {
    request.errorCount = 0;

    return {};
  }

  throw new Error('Unable to update request');
}
```

**Comment by Balou05** [comment]
Thx for your time and your answer :)

**Comment by blackholegalaxy** [comment]
I'm surprised feathers doesn't have a timeout mechanism. How to handle it the proper way? Create some kind of hook to start a timeout watcher? I understand in this particular case we can remove promise here. 

It could be useful to have a documented and recommanded proper way to achieve that timeout behavior.

**Comment by daffl** [comment]
Just like Express Feathers does not make any assumptions about your application logic (the client side timeout still exists only for historical reasons). There shouldn't be anything Feathers specific to add timeout to an `async` function. You could e.g. wrap it in a helper:

```js

const withTimeout = (method, timeout = 5000) => (...args) => {
  const result = method.apply(this, args);

  return new Promise((resolve, reject) => {
    const timeout = setTimeout(() => reject(new Error('Timeout')), timeout);

    result.then(resolve, reject);
  });
}

update: withTimeout(async function (id: Id, params: Params) {
  const request = this.findInQueue(id);

  if (request && !!request.chunks.set(params.index, params.value)) {
    request.errorCount = 0;

    return {};
  }

  throw new Error('Unable to update request');
});
```

**Comment by blackholegalaxy** [comment]
Ok we'll close this issue then :) Will do with custom logic.
