### ISSUE TITLE
socket.io client doesnot respond to server.

### ISSUE THREAD

**Issue by shahulideas2it2017** [feathersjs/feathers#1291]
i have feathers js application where it act as a socket client and another server application. when client connects to server , it emits to server for every two seconds. after a particular interval of time server emits an action to perform in client application . while client performs the application, the emit which happens for every two seconds , stop . after the current action is performed only, the emit to server begins to perform. 
can u clarify it

**Comment by daffl** [comment]
Could you clarify with a small code example? It seems like an issue with the processing in your application. Everything Feathers does is non-blocking.

**Comment by shahulideas2it2017** [comment]
socket server :
```
const feathers = require('@feathersjs/feathers');
const socketio = require('@feathersjs/socketio');
const needle = require('needle');

const app = feathers();
let sequenceNumberByClient = new Map();
app.configure(socketio(function(io) {
io.on("connection", (socket) => {
    console.info(`Client connected [id=${socket.id}]`);
    
    socket.on('hearBeat', (clientMessage) => {
        console.log(`the client ${socket.id} message ${clientMessage}`);
    })
    
     socket.emit('postRequest', '');
    socket.on("disconnect", () => {
        sequenceNumberByClient.delete(socket);
        console.info(`Client gone [id=${socket.id}]`);
    });
});

}));
app.listen(3031);

```
Socket Client :

```
const feathers = require('@feathersjs/feathers');
const socketio = require('@feathersjs/socketio-client');
const io = require('socket.io-client');
const fs = require('fs');
const needle = require('needle');

const socket = io.connect('http://localhost:3031');
const app = feathers();

setInterval(function () {
    socket.emit('hearBeat', new Date());
  }, 500);

// initialize this client's sequence number
socket.on('postRequest', async () => {
    await needle.get('https://google.com');
    var out = fs.createWriteStream('logo.png');
    console.log(await needle.get('https://google.com/images/logo.png'));
})
```

In the above code when client emits the hearBeat for every half second to server, this hearbeat stops when the postRequest execution has happened. after the postRequest completes the hearbeat continues.

**Comment by daffl** [comment]
This might be a websocket restriction. The upload probably still happens asynchronously but the connection can't receive events until it is done.
