### ISSUE TITLE
RethinkDB Adapter

### ISSUE THREAD

**Issue by chovy** [feathersjs/feathers#130]
Are there any plans to support rethinkdb?

I see you have feathers-mongoose and feathers-mongo, but I'm learning towards KOA/Rethink on my next project.

**Comment by daffl** [comment]
Not that I am aware of but if you want to contribute I can set the plugin repository scaffold (including some compatibility tests) up and add you to it. I don't think it would be a lot of work, somebody just has to do it (the complete MongoDB adapter is [less than 200 lines of code](https://github.com/feathersjs/feathers-mongodb/blob/master/lib/mongodb.js)).

If you end up using Koa you will have to do the exact same work (but not have it as easily share- and reusable as in a service).

**Comment by marshallswain** [comment]
I started work on this last night.

**Comment by niallobrien** [comment]
@marshallswain Any update on this?

**Comment by marshallswain** [comment]
@niallobrien @chovy  It shouldn't take much more work.  I've pushed what's working to https://github.com/feathersjs/feathers-rethinkdb.  The todo list is in the readme.  If you have any experience with RethinkDB, maybe you can review what I've done or even help out a bit.  That would be greatly appreciated.

**Comment by ekryski** [comment]
Work **is** being done on this as Marshall mentioned above. But now that we have made the decision to support ORMs and not specific databases directly, we might get some features for rethink when [feathers-waterline](https://github.com/feathersjs/feathers-waterline) lands, as there is [waterline-rethink](https://github.com/jmdobry/waterline-rethinkdb) (although looks to be abandoned).

Alternatively, [thinky](https://github.com/neumino/thinky) is rethinkdb specific ORM that would be similar to [feathers-mongoose](https://github.com/feathersjs/feathers-mongoose).

**Comment by daffl** [comment]
I am closing this issue since we have several options to use RethinkDB now. Issues can be opened either in [feathers-rethinkdb](https://github.com/feathersjs/feathers-rethinkdb) or [feathers-waterline](https://github.com/feathersjs/feathers-waterline)
