### ISSUE TITLE
Service `setup` called before `app.io` instantiated

### ISSUE THREAD

**Issue by oscarhaggerty** [feathersjs/feathers#131]
I need access to `io` in an service `setup()` method. This is instantiated in the `feathers.socketio()` configuration function. However, testing seems to indicate that my services `setup()` method is being called before the socketio configuration function.

Here's my usage:

```coffeescript
        testService = mongodb 'test'
        app
        .configure  feathers.rest()
        .configure  feathers.socketio (io)->
          debugger # this is called after `extendedTestService.setup()`
        .use bodyParser.json()
        .use '/test', extendedTestService
        .listen 3000
```

**Comment by daffl** [comment]
I can confirm this. There is an easy fix with the only drawback that the service event handlers aren't set up but in the configuration function but I don't think that would be an issue. I'll land the fix tonight and make a 1.1.0-pre.0 release that you can use.

**Comment by daffl** [comment]
Sorry, took a little longer but the issue should be fixed in version 1.1.0-pre.0 which is available on NPM.

**Comment by oscarhaggerty** [comment]
Great! Thanks for the fix. Big fan of feathers (come from Sails JS), would be happy to contribute in future.
Oscar

**Comment by daffl** [comment]
Awesome! Any contributions are welcome :) I'd still be curious in a Feathers vs Sails comparison.

**Comment by oscarhaggerty** [comment]
Sails is annoyingly opinionated in my experience. It is difficult to manage middle-ware properly. Sails-Waterline (database ORM) is fairly limited & slow in trying to support so many databases. Feathers elegantly bridges the gap, is lightweight & easily customizable.

I am currently building a fresh mongodb service - one that supports query criteria such as `limit` etc, as well as mongodb aggregate commands. Been meaning to github repo it but it needs some polish in the mean time.
