### ISSUE TITLE
How to disable HTML responses?

### ISSUE THREAD

**Issue by averri** [feathersjs/feathers#1310]
How to disable the HTML responses? I'm sending the following headers in the request:
```json
Content-Type:application/json
Accept:application/json
```
But the server reply with HTML for 404 errors, for example. I would like to have only JSON responses from REST or any other transport.

**Comment by daffl** [comment]
The [Express error handler](https://docs.feathersjs.com/api/express.html#expresserrorhandler) will send the most appropriate response. If it does not when setting the content type it may be configured wrong. You can also completely disable HTML responses by setting `html: false` as [documented here](https://docs.feathersjs.com/api/express.html#appuseexpresserrorhandleroptions).

**Comment by averri** [comment]
Thanks for informing that. I have tried:

```javascript
app.use(cors())
    .use(express.json())
    .use(express.urlencoded({extended: true}))
    .configure(express.rest())
    .configure(socketio())
    .configure(auth(authOptions))
    .configure(local())
    .use('users', new UsersService(db.collection('users')))
    .use('register', new RegisterUsers())
    .use(express.errorHandler({html: false}))
```

But the server continue to send responses with HTML, even with a request like 

```
POST /nonexistent-endpoint HTTP/1.1
Host: localhost:3000
Content-Type: application/json
Accept: application/json
Cache-Control: no-cache

{
  "username": "alex",
  "password": "123"
}
```

The server response:
```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /nonexistent-endpoint</pre>
</body>
</html>
```

**Comment by averri** [comment]
I have found the solution here: https://docs.feathersjs.com/api/express.html#expressnotfoundoptions

It just need to set:
```javascript
app.use(express.notFound({ verbose: true });
   .use(express.errorHandler({html: false}))
```
