### ISSUE TITLE
Missing TypeScript definitions for channels 

### ISSUE THREAD

**Issue by brane53** [feathersjs/feathers#1313]
### Steps to reproduce

When I try to use app.channels I get a typescript error saying that the property `channels` does not exist on type `Application`. Here's the interface defined in @types/feathersjs__socket-commons.

```
interface Application<ServiceTypes> {
    channel(...names: string[]): Channel;

    // tslint:disable-next-line void-return
    publish<T>(callback: (data: T, hook: HookContext<T>) => Channel | Channel[] | void): Application<ServiceTypes>;

    // tslint:disable-next-line void-return
    publish<T>(event: string, callback: (data: T, hook: HookContext<T>) => Channel | Channel[] | void): Application<ServiceTypes>;
}
```

`channels` is still part of the API right? If so I think that needs to be added to the interface. In the mean time what's the best way to get around this error?

**Comment by daffl** [comment]
This should be fixed in Feathers v4 authentication which has those typings built in. See the [Migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information on how to upgrade.
