### ISSUE TITLE
jwtStrategies vs httpStrategies

### ISSUE THREAD

**Issue by KidkArolis** [feathersjs/feathers#1321]
What's the difference between jwtStrategies vs httpStrategies? Do I need both?

<img width="150" alt="image" src="https://user-images.githubusercontent.com/324440/57072662-5ec0b700-6cd6-11e9-94fb-44cf33fa5b37.png">

**Comment by daffl** [comment]
Not anymore, in https://github.com/feathersjs/feathers/pull/1308 they have both been merged into `authStrategies`. Basically it's the list of strategies you want to allow for creating `/authentication` and for parsing HTTP requests.

**Comment by KidkArolis** [comment]
What do you mean by `parsing HTTP requests`, still not very clear to me?

**Comment by KidkArolis** [comment]
In case of `/authentication` endpoint you pick which strategies are allowed to access that endpoint. Makes sense.

In case of all of your services, you use `authenticate('jwt')`, etc. hook.

So where would "http parsing" or `httpStrategies` come in? Or is that simply completely gone in 4.0.0?

**Comment by daffl** [comment]
A strategy can do two thins

1) [.authenticate](https://deploy-preview-1291--feathers-crow-docs.netlify.com/api/authentication/strategy.html#authenticate-authentication-params) against an authentication request. For the `authenticate` hook, this usually comes from `params.authentication`, for `authenticationService.create(data)` it comes from `data`.
2) An authentication strategy can also [implement a parser](https://deploy-preview-1291--feathers-crow-docs.netlify.com/api/authentication/strategy.html#parse-req-res) that returns the `params.authentication` for an HTTP request. For example, the JWT strategy would turn an `Authorization: Bearer <token>` header into a `params.authentication` of `{ strategy: 'jwt', accessToken: '<token>' }`.

Hope that makes sense.
