### ISSUE TITLE
[Feathers 4.0.0-pre] Trying every strategy and throwing is wasteful

### ISSUE THREAD

**Issue by KidkArolis** [feathersjs/feathers#1323]
I have custom errors in my LocalStrategy subclass, e.g.:

```
async comparePassword(entity, password) {
    if (entity.googleId) {
      throw new errors.GSuiteEmail(`Please use 'Sign in with Google' button`)
    }
    return super.comparePassword(entity, password)
}
```

Because of this, I can't order my strategies as `[jwt, local]`, I have to order them `[local, jwt]`. But jwt is obviously much more frequently used, and so it seems wasteful that the local has to always be tried first and throw an error right on this line:

```
if (data.strategy && data.strategy !== this.name) {
      throw new NotAuthenticated(errorMessage);
    }
```

This has another strange effect, this swallows the error from jwt, even though that's the more appropriate error. (in fact, this point is the same point made above, but reversed).

Proposal: in authentication/core, do not _even_ run those strategies whose name doesn't match `data.strategy`. Then, check if any strategies were in fact run and only then proceed.

This way:

- only relevant strategies will be executed
- the most appropriate error will be shown
- the ordering of `[local, jwt]` or `[jwt, local]` becomes less important

**Comment by KidkArolis** [comment]
I could PR if the proposal sounds good.

**Comment by daffl** [comment]
The reason it was doing it that way is to allow other strategies to fall back to. One thing that used to be difficult is e.g. allowing an anonymous strategy (`[jwt, local, anonymous]`). `anonymous` should still always run no matter the `strategy`.

**Comment by lvivier** [comment]
I've just run into this too. Here's another proposal: in the event that all strategies throw, instead of getting the first error, could we preferentially get the error thrown from the strategy indicated by `data.strategy`? I think it's more intuitive and it would be a big help.

Also happy to submit a PR for this.

**Comment by KidkArolis** [comment]
When is fallback useful? What about something like fallbackStrategy option? Its a little strange to mix them into one array if they immediately throw when requested strategy name mismatches.. and also swallowing errors in the process

**Comment by daffl** [comment]
Hm, I can see that this might be confusing. I'd just like to be able to give a strategy the opportunity to run regardless of the `strategy` name that is passed. For example, a `local` strategy might want to always run if an `email` and `password` is passed, regardless of the name. It's also the only way I can think of to easily allow anonymous authentication (you have to hack around this with hooks at the moment where it really should be a normal authentication strategy).

What if when a `strategy` name is passed (and allowed), it will _always run first_ and only try the others if it fails and then return the first error (similar to what @lvivier suggested)?

**Comment by daffl** [comment]
Actually scratch that. I think you are both right 😄 I think what makes the most sense is that:

- If a `strategy` name is passed, _only_ try that one strategy and return its success or error
- If nothing is passed, run through everything (this will still trigger e.g. an `anonymous` strategy)

I think this should make things fairly clear unless I'm missing something else.

**Comment by lvivier** [comment]
@daffl that sounds good to me
