### ISSUE TITLE
error: BadRequest: Invalid query parameter $search

### ISSUE THREAD

**Issue by farhad-arjmand** [feathersjs/feathers#1328]
app.service('news')
      .find({
        query: { $search: 'cat', $skip: parseInt(req.query.page,0), $sort: { updatedAt: -1 } }
      })

error : error: BadRequest: Invalid query parameter $search

**Comment by daffl** [comment]
`$search` is not a valid query parameter. Have a look at the [FAQ about searching](https://docs.feathersjs.com/faq/readme.html#how-do-i-do-search). If it is supported by a database adapter or a plugin [it has to be whitelisted](https://crow.docs.feathersjs.com/migrating.html#whitelisting).
