### ISSUE TITLE
Implement caching for Mongodb 

### ISSUE THREAD

**Issue by philoez98** [feathersjs/feathers#1329]
Hello,

I need to implement some sort of caching (Redis) within Feathers for a Mongodb database. Is there a preferred way of doing so? I was thinking about hooking that up for all Mongo related services. Does Feathers have this implemented in some way or provides any useful tools to implement it? 
I searched around a bit but haven't found anything useful. 

Thanks

**Comment by daffl** [comment]
There is the [cache hook in feathers-hooks-common](https://feathers-plus.github.io/v1/feathers-hooks-common/#cache) and the [feathers-hook-rediscache](https://github.com/idealley/feathers-hooks-rediscache). Both essentially use [hooks](https://docs.feathersjs.com/api/hooks.html) similar to something like this:

```js
const cache = {};

app.service('myservice').hooks({
  before: [async context => {
    const { query = {} } = context.params;

    const cached = cache[JSON.stringify(query)];

    if (cached) {
      context.result = cached;
    }
  }],
  after: [async context => {
    const { query = {}, result } = context.params;

    cache[JSON.stringify(query)] = result;
  }]
});
```

**Comment by philoez98** [comment]
Thanks for the explanation  @daffl !
