### ISSUE TITLE
Add documentation for custom service events

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers#133]
#128 adds the functionality but the documentation has to be updated (now in the main repository because of #127).

**Comment by ekryski** [comment]
This probably still needs to be added to the docs.

**Comment by daffl** [comment]
It does indeed. I didn't get the `service.filter` functionality into 1.1 though so custom events are not too useful since they get dispatched to all clients without a way to filter it.

**Comment by marshallswain** [comment]
I've set up a placeholder for this here: https://github.com/feathersjs/feathers-docs/blob/master/05_events.md#custom-events

**Comment by daffl** [comment]
This has been added at http://docs.feathersjs.com/clients/readme.html#custom-events

**Comment by marshallswain** [comment]
I think the service setup stuff belongs on the [events page](http://docs.feathersjs.com/real-time/events.html).  But we would want to still show how the client can listen to custom service events on the clients page where you have it now.  Something like:

> If you're using [custom events](http://docs.feathersjs.com/real-time/events.html#custom-events) you can listen to them on the client like this...

**Comment by joeyzhao0113** [comment]
Does it support add custom event at runtime?

**Comment by daffl** [comment]
You can add services at runtime (that can have custom events) but not new events to an already registered service.

**Comment by zhaoyi0113** [comment]
Is there a way to support add events after service has been registered? Otherwise, is it support to unregister and register the service again when adding new events
