### ISSUE TITLE
Setting the 'subject' in JWT

### ISSUE THREAD

**Issue by averri** [feathersjs/feathers#1330]
How to set the `subject` in the JWT, for example, using the user's email?

The documents https://docs.feathersjs.com/api/authentication/server.html show that the `subject` is a fixed value:

```
subject: 'anonymous', // Typically the entity id associated with the JWT
```

**Comment by daffl** [comment]
This has been addressed in Feathers v4 where the subject will contain the user id. Have a look at the [migration guide](https://crow.docs.feathersjs.com/migrating.html) to test out the current prerelease.
