### ISSUE TITLE
error: Error: A data object must be provided to the 'update' method

### ISSUE THREAD

**Issue by isaialbarran** [feathersjs/feathers#1331]
Hi! I'm working with feathers and get an error. This is my hooks. I'm trying to get id from one table and change to a real name. But in the end, when I try to update my object it says "error: Error: A data object must be provided to the 'update' method". I'm trying to send eventData which is an object. 

module.exports = function (options = {}) {
  return async context => {
    let events = context.result.data;
    let locationsIds = events.map(function (location){
      return location.location_id;
    });

    context.app
      .service('location')
      .find({
        query: {
          id: {
            $in: locationsIds
          }
        }
      })
      .then(location => {
        //console.log(location.data[0].city); //Barcelona
        const answer = events.map(function (event) {
          let eventData = {
            id: event.id,
            name: event.name,
            status: event.status,
            created_at: event.created_at,
            updated_at: event.updated_at,
            created_by: event.created_by,
            location_id: event.location_id
          };
          if(event.location_id === location.data[0].id){
            //console.log(event.location_id = location.data[0].city);
            eventData = {
              location_id: location.data[0].city
            };
            context.app.service('event').update(eventData);
          }
          else{
            eventData = {
              location_id: 'None city yet'
            };
            context.app.service('event').update(eventData);
          }
        })
      })
    return context;
  };
};

**Comment by daffl** [comment]
The [signature of `update`](https://docs.feathersjs.com/api/services.html#updateid-data-params) is `.update(id, data, params)` where `id` and `data` is mandatory.

**Comment by isaialbarran** [comment]
Thanks! I got it
