### ISSUE TITLE
error: No authentication strategies allowed for creating a JWT (jwtStrategies)

### ISSUE THREAD

**Issue by alvise** [feathersjs/feathers#1334]
After migrating to featherjs V4 (CROW) following the guide (https://crow.docs.feathersjs.com/migrating.html) the authentication no longer works.

Right after the migration to V4 i received an error that @featherjs/authentication-oauth was missing (even if i do not use oauth at all) so i installed the missin module.

Now i get the error: featherjs error: No authentication strategies allowed for creating a JWT (jwtStrategies)

**Comment by daffl** [comment]
This has been fixed in version 4.0.0-pre.1

**Comment by alvise** [comment]
Tnx its working now.

**Comment by daffl** [comment]
Cool. Let me know if you run into any other issues. Since it's a prerelease there may still be some. I'm working on finalizing the documentation, too.
