### ISSUE TITLE
Intermittent NotAuthenticated: No auth token 

### ISSUE THREAD

**Issue by dottodot** [feathersjs/feathers#1339]
I have a bizarre issue that I can't find the root cause of and it's only just manifested itself. The request I'm making to a service then has a few hooks that perform updates on other services but every so often during the various updates I get the error `NotAuthenticated: No auth token`. Restarting the feathers app seems to clear it sometimes and then the exact same request will work.

I'm assuming that somehow on occasion my headers are getting removed but I have no idea what would cause that to happen, and I've checked to make sure the header is being sent every time.

**Comment by ThomasGHenry** [comment]
I started getting this after switching to `yarn`. I think there's a breaking change in one of the releases downstream from me (probably many releases, I think I'm on old stuff) that package-lock.json was protecting me from. Nuking everything and going back to `npm` fixed it.

**Comment by daffl** [comment]
This has been addressed in the new v4 [authentication client](https://crow.docs.feathersjs.com/api/authentication/client.html). An authenticated connection will always be re-authenticated on reconnection before making any other requests.

See the [Authentication API](https://crow.docs.feathersjs.com/api/authentication/) and the [Migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information on how to upgrade.
