### ISSUE TITLE
REST module can't query numeric fields

### ISSUE THREAD

**Issue by skycult** [feathersjs/feathers#1345]
Hello there,

I tried to query a simple feathers REST API:

```js
const feathers = require('@feathersjs/feathers')
const express = require('@feathersjs/express')
const Service = require('feathers-memory').Service
const http = require('http')

const app = express(feathers())
  .use(express.json())
  .use(express.urlencoded({ extended: true }))
  .configure(express.rest())
  .use('/customers', new Service({
    multi: true,
    paginate: false
  }))

const server = http.createServer(app)

server.on('listening', () => {
  console.log('Server running at http://localhost:3000')
})

app.setup(server)

server.listen(3000)

app.service('customers').create([
  {
    name: 'Sam',
    age: 30
  },
  {
    name: 'Tom',
    age: 40
  }
])
```

When I try to query from a browser using `http://localhost:3000/customers?age=30` or `http://localhost:3000/customers?age=40` I can't get the customer. All customers are listed when I try without parameters: `http://localhost:3000/customers`.

What am I doing wrong?
Thank you

**Comment by daffl** [comment]
This is how HTTP works (see e.g. [the REST API documentation](https://docs.feathersjs.com/api/client/rest.html#http-api) and [this faq](https://docs.feathersjs.com/faq/readme.html#my-queries-with-null-values-arent-working). ORMs like Mongoose or Sequelize do the conversion automatically but for some other adapters that don't have a schema definition it has to be done in a hook as shown in the linked FAQ entry.

**Comment by skycult** [comment]
Thank you very much David!
Feathers is awesome!
All the best
