### ISSUE TITLE
[Feathers 4.0.0-pre.1] Throw 401 instead of 500 for expired tokens

### ISSUE THREAD

**Issue by KidkArolis** [feathersjs/feathers#1347]
I had to customize AuthenticationService to do that:

```js
class CustomAuthenticationService extends AuthenticationService {
  async verifyAccessToken(...args) {
    try {
      return await super.verifyAccessToken(...args)
    } catch (err) {
      if (err.name === 'TokenExpiredError') {
        throw new errors.NotAuthenticated('Token expired')
      }
      throw err
    }
  }
}
```

I can contribute a PR if this seems right? I would probably check for `error instanceof TokenExpiredError` in the PR.

**Comment by daffl** [comment]
Makes sense. I was at it already so I put a fix into #1357. It will throw a `NotAuthenticated` with the error message but include the error information (e.g. `name` and `expiredAt`) in the `data` property of the error.
