### ISSUE TITLE
Better support for pagination

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers#135]
I'd like to add better support for pagination and something similar to GitHubs `Link:` HTTP headers (see [here](https://developer.github.com/guides/traversing-with-pagination/)) like:

```
Link: <https://api.github.com/search/code?q=addClass+user%3Amozilla&page=15>; rel="next",
  <https://api.github.com/search/code?q=addClass+user%3Amozilla&page=34>; rel="last",
  <https://api.github.com/search/code?q=addClass+user%3Amozilla&page=1>; rel="first",
  <https://api.github.com/search/code?q=addClass+user%3Amozilla&page=13>; rel="prev"
```

This actually shouldn't be too hard to implement and backwards compatible. All we need to do is have `service.find` return an object with information about it's pagination data (you should use an object with `{ "data": [] }` anyway for security reasons):

```js
/// /todos
{
  "total": 1000,
  "limit": 20,
  "start": 0,
  "data": []
}
```

Our quasi standard is to use `$` for query parameters like `$limit=10&$start=20`. Then we would know how to generate a link header like:

```
Link: <http://feathersjs.com/todos?$limit=20&$start=19>; rel="next",
  <http://feathersjs.com/todos?$limit=20&$start=979>; rel="last"
```

If we make the pre-built services support this out of the box it will be really nice to use (I had to code this manually a couple of times already).

**Comment by loris** [comment]
Great idea,
- would it make more sense in the core module or as a plugin?
- I think it would be better to let the user define the query parameters name, what would be the cleanest way to do that? as an object you would pass to the `feathers.rest()` call?

**Comment by ekryski** [comment]
@loris you can use `$skip` has a query string param to do this currently. All the service adapters support this functionality. With that said we have more work planned to provide meta data in responses in v2.0.

**Comment by ekryski** [comment]
This is implemented in core but we are updating all the db adapters at the same time. It goes hand in hand with #170.

**Comment by ekryski** [comment]
@daffl do we want to also implement the Link Header spec or just leave the meta data in the response.

I can't help but feel we should be returning:

- the page that you are currently on,
- a link to the previous page
- a link to the next page

I like that we are bringing back more data than Django REST but I sort of like how [their response](http://www.django-rest-framework.org/api-guide/pagination/) is looking.

I realize that you can calculate the page based on the `$limit` and `$skip` but it sure would be nice to have a response like so:

```json
/// /todos
{
  "total": 1000,
  "limit": 20,
  "skip": 40,
  "page": 3,
  "next": "https://api.feathersjs.com/todos/?$page=4",
  "previous": "https://api.feathersjs.com/todos/?$page=2",
  "data": []
}
```

Thoughts?

**Comment by daffl** [comment]
Our paging only works with `$offset` and `$limit`. We could add a hook that calculates and sets the page numbers from it. We could also add one that adds the links you are suggesting. The tricky part is that you can't make a full URL out of it if you are using websockets. Maybe a query object like

```js
{
  "total": 1000,
  "limit": 20,
  "skip": 40,
  "next": {
    "$skip": 60,
    "$limit": 20
  },
  "previous": {
    "$skip": 20,
    "$limit": 20
  },
  "last": {
    "$skip": 980,
    "$limit": 20
  },
  "data": []
}
```

Would be more appropriate.

**Comment by ekryski** [comment]
Ah right. I had forgotten about websockets. Then I think we're at a point where we dictate our own spec since I don't think anyone else allows you to do as much over websockets as we do.

I like what you posted @daffl for query object. I was thinking the same thing. It's not quite as elegant as `$page` but it totally works and doesn't require much extra effort. I'm inclined to leave `$page` off the table for now until we have more experience interfacing with this new pagination mechanism. We already currently have:

```js
{
  "total": 1000,
  "limit": 20,
  "skip": 40,
  "data": []
}
```

I also, would like to hear from @corymsmith because I know that he has already written some mobile list views and infinite scrolls in react native against feathers prior to us returning the pagination data as part of the response.

**Comment by corymsmith** [comment]
This looks good to me, I was using $skip and $limit and just updating the next $skip when a page is returned, currently resulted in an additional request to see if theres a next page. Would be really nice to not have to redo all that work in each client.

**Comment by daffl** [comment]
A general pagination object can be easily implemented as a hook now that we have pagination. I'm moving this issue into https://github.com/feathersjs/feathers-rest/issues/2 and off the Feathers 2.0 milestone since HTTP link headers are a "would be nice" but not a blocker for the v2 release.
