### ISSUE TITLE
How to increment a value in nested document ?

### ISSUE THREAD

**Issue by suchcodemuchwow** [feathersjs/feathers#1351]
I am trying to develop sample api to learn feathers but I'm stuck at some point which documentations and googling couldn't help me. I have several nested documents like this:

```
const PollsSchema = new Schema(
{ question: { type: QuestionSchema, required: true } },
);
```

```
const QuestionsSchema = new mongoose.Schema({
  options: { type: [OptionsSchema], required: true }
});
```

```
const OptionsSchema = new mongoose.Schema({
  voteCount: { type: Number, default: 0 },
});
```

I want to upvote||downvote based on the id parameter but I guess patch method by default only allows you to do $set.

What I have tried is:
- Adding static method to polls schema to run the query. (I guess it's kind of an antipattern for feathers, because if I decided to change db I need to implement it for that db too)
- I searched through issues and see maybe `alterItems` and `stashBefore` can work for my purposes but I couldn't make them work.
- I also find  [https://github.com/feathersjs-ecosystem/feathers-mongoose/issues/95](url) this issue has been solved but I couldn't understand how to work with $inc. (Any help to this particular bullet point would really help on other tasks too)

**Comment by suchcodemuchwow** [comment]
I figured out by running following statement in client library:

```
  const query = {
    'question.options._id': '5cd836dbad6aed504755223e'
  };

  const result = await client.service('polls').patch(
    '5cd836dbad6aed504755223b',
    {
      $inc: {
        'question.options.$.voteCount': 200
      }
    },
    { query }
  );
```

But here is the questions that confuses me now:
- I felt little bit scared about security issues this query mechanism on client side can create. Do we need to check each condition on backend and ignore others.
- Can we do that operation on backend, I tried to run code snippet inside before patch hook but it went into infinite loop and I don't want to use different http method and call this inside of it.

**Comment by daffl** [comment]
1) You should update to the latest version of the adapter which requires non-standard parameters to be whitelisted explicitly. See the [migration guide](https://crow.docs.feathersjs.com/migrating.html#whitelisting) for more information.
2) Yes you should be able to but have to make sure to prevent infinite loops manually by using the correct breaking condition. E.g. if you call `patch` recursively in a `patch` hook pass some additional parameter to check for to not run the hook again.
