### ISSUE TITLE
feathersjs not mapping parameters when call services internal 

### ISSUE THREAD

**Issue by mohanagy** [feathersjs/feathers#1354]
I have a service and I want to add custom routes to this service with custom methods 
my service like this :
```
  app.use('/users/followers', createService(options));

  app.use('/users/:id/followers', {
    find: (params) => app.service('/users/followers')
      .find(params),

  });

  const service = app.service('/users/followers');

```
what I'm trying to do is to call it internally in another place like this 
```
const id =1;
context.app.service(`/users/${id}/followers`)
        .find({
          ...context.params, paginate: false
        });
```

### Expected behaviour
the expected behaviour is to get the id's followers 
### Actual behaviour
the actual behaviour is Cannot read property 'find' of undefined
but if called the exact route like this 
```
context.app.service(`/users/:id/followers`)
        .find({
          ...context.params, paginate: false
        });

```
it works fine 
so feathers somehow not mapping the parameters
### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
feathers 3.3.1
**NodeJS version**:
v10.15.3

**Operating System**:
Ubuntu

So do I missed something?

**Comment by daffl** [comment]
This only possible for calls through a transport provider. Internally the service name is always `/users/:id/followers`, with the `id` passed through `params.route` manually:

```js
context.app.service(`/users/:id/followers`)
        .find({
          ...context.params, paginate: false,
          route: { id: 'something' }
        });
```

**Comment by mohanagy** [comment]
Thank you so much @daffl,
it really works,
Does the API documentation miss this part? because I didn't see anything that explains this part

Kind regards
