### ISSUE TITLE
Update record based on existing value?

### ISSUE THREAD

**Issue by nathansgithub** [feathersjs/feathers#1359]
Is there a way to mass update records based on existing values in those records? For example, I want a hook that is triggered when I create a new item in an ordered list with a "position" attribute. The hook should add 1 to the position of all items with a position greater than or equal to the position of the new item. The easiest way to do this might be with a database trigger, but I want to see if it is possible through Feathers. Can I do this without doing a separate patch request for each existing item?

```
    let new_pos = context.data.position

    context.service.patch(null, { position: ?? }, {
      query: {
        position: { $gte: new_pos }
      }
    })
```

**Comment by daffl** [comment]
This is usually handled by the database/ORM adapter you are using directly, e.g. with [the MongoDB $inc operator](https://docs.mongodb.com/manual/reference/operator/update/inc/).
