### ISSUE TITLE
Change auth storage after init?

### ISSUE THREAD

**Issue by james2mid** [feathersjs/feathers#1361]
Is it possible to change the auth storage after calling the default `auth from '@feathersjs/authentication-client'` (with the `storage` param).

I've attempted to change the `storage` property on `passport` in the client object from `localStorage` to `sessionStorage` but it seems to make no difference.

**Comment by daffl** [comment]
In Feathers v4 authentication you can use `app.set('storage', myStorage)` in the [authentication client](https://crow.docs.feathersjs.com/api/authentication/client.html). See the [Migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information on how to upgrade.
