### ISSUE TITLE
A way to not update timestamp when using update method

### ISSUE THREAD

**Issue by mohanagy** [feathersjs/feathers#1362]
Hello there, I'm using update method, and I know it used to update the whole row and replace it,
 but is there a way to avoid updating these columns created_at,created_by which has only value and you know we update these fields once,

### Expected behaviour
update the whole row and avoiding  the created_at, created_by columns
### Actual behavior
updated it with null

**Comment by fmoessle** [comment]
This depends on how the created_at and created_by properties are created and updated in your application. Please feel free to use https://stackoverflow.com for those kind of questions :)

If you provide me a link to your applications or an example I will try to answer your question anyway.
