### ISSUE TITLE
I want to make a custom api, can you please just help me to get started.

### ISSUE THREAD

**Issue by umairalii** [feathersjs/feathers#1366]
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [x] Tell us what broke. The more detailed the better.
- [x] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc. This makes it much easier for us to debug and issues that have a reproducable example will get higher priority.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by umairalii** [comment]
I want to create an api like (http//localhost:3030/messages/:room_id)

**Comment by daffl** [comment]
This is described in [this FAQ](https://docs.feathersjs.com/faq/readme.html#how-do-i-do-nested-or-custom-routes) and the [Express API documentation](https://docs.feathersjs.com/api/express.html).
