### ISSUE TITLE
Feathers Service Typings

### ISSUE THREAD

**Issue by deskoh** [feathersjs/feathers#1369]
Shouldn't the type for `service` below be `Service<ServiceTypes[L]>` instead of `ServiceTypes[L]`?

https://github.com/feathersjs/feathers/blob/1a92f5377652e844b6a5b20a59a6667192ce68e5/packages/feathers/index.d.ts#L207

**Comment by daffl** [comment]
Not every service necessarily returns the same type for all methods. I think it makes more sense to be able to set the actual service type which gives more flexibility.

**Comment by deskoh** [comment]
So the expected usage would be something like the following?

```ts
import { Application } from '@feathersjs/express';
import { Service } from '@feathersjs/feathers';

type App = Application<{
  'messages': Service<Message>,
}>;
```

**Comment by daffl** [comment]
Exactly. I know it's different from what is on DefinitelyTyped for v3 but I still think it makes the most sense. That way you can do things like

```ts
type App = Application<{
  'messages': Service<Message>,
  'status': CustomStatusService
}>;
```
