### ISSUE TITLE
Question: how to proxy all the app service methods

### ISSUE THREAD

**Issue by averri** [feathersjs/feathers#1378]
I would like to proxy all the service methods, and add a try/catch around each of them. The purpose is to create features like retry mechanisms in case of errors.

**Comment by daffl** [comment]
[Application level hooks](https://docs.feathersjs.com/api/hooks.html#application-hooks) can probably be used for that. A global `error` hook can set `context.result` to swallow any error.

**Comment by averri** [comment]
Hi @daffl, I think it's not possible to do with the application level hook, the main requirement is to be able to retry the failed method automatically, according to some retry policy.

**Comment by daffl** [comment]
Why not? Something like

```js
app.hooks({
  error: {
    create: [context => {
      const { params, service, data, method } = context;

      return new Promise((resolve, reject) => {
        setTimeout(() => {
          service[method](data, params).then(resolve).catch(reject);
        }, 2000)
      }).then(result => {
        context.result = result;
        return context;
      }).catch(error => {
        context.error = error;
        return error;
      });
    }]
  }
})
```

Would re-try a failed `create` method call every two seconds until it passes.

**Comment by averri** [comment]
Cool, I didn't know that after the error the service is still available for invoking. This is very nice. Thanks.

**Comment by daffl** [comment]
There probably will need to be some breaking conditions or flags you can check to avoid having it run forever but basically it should work that way. Also, this should delay the returned result until it is successful or runs into the final failure.
