### ISSUE TITLE
Authentication cookie not set when 'authentication' service called internally.

### ISSUE THREAD

**Issue by cdgriffith** [feathersjs/feathers#1380]
### Steps to reproduce
Have a before hook in use on a service as such: 

```javascript
const { authenticate } = require('@feathersjs/authentication').hooks;

  module.exports = (_strategies, options = {}) => context => {
    if (no_existing_cookie()) {
      return context.app.service('authentication').create({}, context.params).then(x => {
        context.params.accessToken = x.accessToken;
        return authenticate(_strategies, options)(context);
      }).catch(x => {
        console.log(`could not authenticate: ${x.message}`);
        return authenticate(_strategies, options)(context);
      });
    }
  };
```

### Expected behavior

A cookie should be sent in the response when calling the `/authentication` service. 

### Actual behavior

No cookie was sent in response. Hitting the Authentication endpoint directly does set it properly. 

### System configuration

```
  'authentication': {
    'path': '/authentication',
    'service': 'api/v1/users',
     ...
    'cookie': {
      enabled: true,
      name: 'my-cookie',
      httpOnly: false, 
      secure: false, 
    },
```

**Module versions** (especially the part that's not working):
```
    "@feathersjs/authentication": "^2.1.15",
    "@feathersjs/authentication-jwt": "^2.0.9",
    "@feathersjs/authentication-local": "^1.2.9",
    "@feathersjs/configuration": "^2.0.4",
    "@feathersjs/errors": "^3.3.4",
    "@feathersjs/express": "^1.2.7",
    "@feathersjs/feathers": "^3.2.3",
    "@feathersjs/socketio": "^3.2.7",
```
**NodeJS version**: v10.13.0

I would prefer to keep everything in the existing before Hook if possible, but understandable if it requires a separate after Hook. (Have tried looking into how to set the cookie manually and have not had luck.) 

The end goal is to have transparent authorization that if a user hits an endpoint, but they are not authenticated already, it will attempt to automatically authenticate them and set the cookie properly for follow up requests.

**Comment by daffl** [comment]
I am closing since Feathers v4 authentication no longer requires a cookie but instead uses a cross-domain redirect by default. See the [Migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information on how to upgrade.
