### ISSUE TITLE
Partial Service Methods Typings

### ISSUE THREAD

**Issue by deskoh** [feathersjs/feathers#1381]
Refer to the current Service Methods typings below.

https://github.com/feathersjs/feathers/blob/515b916b6ae286c22e5bccdfdd6885a5ee9d2743/packages/feathers/index.d.ts#L143-L157

Propose not to make the Service Methods optional, as TypeScript has a `Partial` helper to create an equivalent type (i.e. `Partial<ServiceMethods> === ServiceMethods` for current definitions). Moreover `app.use` is already accepting a `Partial<ServiceMethod<any>>`.

https://github.com/feathersjs/feathers/blob/515b916b6ae286c22e5bccdfdd6885a5ee9d2743/packages/feathers/index.d.ts#L212

For service implementing partial service methods, they could either inherit from `Partial<ServiceMethods>`, or can be more specific using the `Omit` helper that is officially included in [TypeScript 3.5](https://devblogs.microsoft.com/typescript/announcing-typescript-3-5/#the-omit-helper-type). E.g.

```ts
export class MessageService implements Omit<ServiceMethods<any>, 'find'> {
  //
}
```

Then the Feathers Application could be typed as follows since the `ServiceType` can be now generalised to `any` type as discussed in #1369.

```ts
import { MessageService } from './services/messages/messages.class';

export type App = Application<{
  'messages': typeof MessageService,
}>;
```

**Comment by daffl** [comment]
I think this is a good point.

**Comment by deskoh** [comment]
Closed by https://github.com/feathersjs/feathers/pull/1409
