### ISSUE TITLE
@feathersjs/authentication-local Debug logs show passwords in cleartext

### ISSUE THREAD

**Issue by MichaelJCole** [feathersjs/feathers#1384]
### Steps to reproduce

1) Start the app with DEBUG=* npm run dev
2) Login with local strategy
3) Notice your password is in cleartext in the logs :-(

### Expected behavior

Either show a placeholder "<password>", or show the hash to match in the database.  The cleartext password isn't actually useful for anything but creating the hash to match.

### Actual behavior

The cleartext password is written to the logs, which are designed to stick around!

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

    "@feathersjs/authentication": "^2.1.16",
    "@feathersjs/authentication-jwt": "^2.0.10",
    "@feathersjs/authentication-local": "^1.2.9",
    "@feathersjs/configuration": "^2.0.6",
    "@feathersjs/errors": "^3.3.6",
    "@feathersjs/express": "^1.3.1",
    "@feathersjs/feathers": "^3.3.1",
    "@feathersjs/socketio": "^3.2.9",

**NodeJS version**:

node --version                                                                                                                                                      v10.15.3

**Comment by MichaelJCole** [comment]
The password is in these debug statements:

```
2019-06-03T14:10:10.857Z @feathersjs/authentication:passport:authenticate Passport request object { query:
<request object>.query
<request object>.body
2019-06-03T14:10:10.859Z @feathersjs/authentication-local:verify Checking credentials michael@capnow.org <password>
```

**Comment by MichaelJCole** [comment]
(as an aside, it would be much easier to contribute patches if there were more [comments in the code](https://github.com/feathersjs/feathers/blob/master/packages/authentication-local/src/strategy.ts))

**Comment by daffl** [comment]
I'm not sure if it's a problem with comments or that you are trying to fix an issue from an old version that has already been addressed in the version of this code 😄

**Comment by MichaelJCole** [comment]
Hi David, I may be confused.  What's the best version?

I thought from the package.json that I'm using this one: https://www.npmjs.com/package/@feathersjs/authentication-local at 1.2.9

Thanks!

**Comment by daffl** [comment]
The code is for Feathers v4 which is currently in beta test. I'm pretty sure that version won't log the plain text password anymore. See the [Migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information on how to upgrade.

**Comment by MichaelJCole** [comment]
Awesome, thanks!
