### ISSUE TITLE
Mongoose Unique Constraint Ignored

### ISSUE THREAD

**Issue by pzach01** [feathersjs/feathers#1386]
### Steps to reproduce

feathers g service
? What kind of service is it? Mongoose
? What is the name of the service? new-service
? Which path should the service be registered on? /new-service
? Does the service require authentication? Yes
...
// new-service-model.js - A mongoose model
//
// See http://mongoosejs.com/docs/models.html
// for more of what you can do here.
module.exports = function(app) {
  const mongooseClient = app.get("mongooseClient");
  const { Schema } = mongooseClient;
  const newService= new Schema(
    {
      someField: {
        type: String,
        unique: true,
        ref: "teams"
      }
    },
    {
      timestamps: true
    }
  );
  return mongooseClient.model("newService", newService);
};

### Expected behavior
This correctly creates a collection on my **MongoDB Atlas** database. However the unique constraint is ignored.

### Actual behavior
This works correctly if I change this
return mongooseClient.model("newService", newService);
to this
return mongooseClient.model("new-service", newService);

I haven't tested this on a local MongoDB so it is possible that it is an issue with Atlas but I suspect it is a feathers bug.

**Comment by philoez98** [comment]
I guess you should have the name match the one of the service you have created. That's the issue in my opinion.

**Comment by pzach01** [comment]
Similarly, if we do something like 

? What kind of service is it? Mongoose
? What is the name of the service? new-services
? Which path should the service be registered on? /new-services
? Does the service require authentication? Yes

now, 
return mongooseClient.model("new-services", newService); 
does not work.
instead, use an underscore:
return mongooseClient.model("new_services", newService); 
This may be an issue with how mongoose pluralizes or an issue with the DB adapter. 
It seems like using an underscore may be the fail-safe way to do it.

**Comment by daffl** [comment]
Closing since the original issue has been solved and the related mentioned is already tracked in https://github.com/feathersjs/generator-feathers/issues/416
