### ISSUE TITLE
Auth0 Oauth Provider

### ISSUE THREAD

**Issue by Sieabah** [feathersjs/feathers#1387]
### Steps to reproduce

My configuration for Auth0

```
authentication: {
    secret: 'some valid secret',
    authStrategies: [
      'jwt',
    ],
    entity: 'user',
    service: "users",
    jwtOptions: {
      header: {
        "typ": "access",
      },
      audience: 'http://localhost',
      issuer: "feathers",
      algorithm: "HS256",
      expiresIn: "1d",
    },
    oauth: {
      redirect: 'http://localhost',
      defaults: {
        host: `localhost`,
      },
      auth0: {
        key: process.env.AUTH_CLIENTID, // originally clientID
        secret: process.env.AUTH_SECRET, // originally clientSecret
        subdomain: process.env.AUTH_SUBDOMAIN, // originally domain
      }
    },
  }
```

```
// authentication.js
'use strict';

const { AuthenticationService, JWTStrategy } = require('@feathersjs/authentication');

const { expressOauth, OAuthStrategy } = require('@feathersjs/authentication-oauth');

module.exports = function () {
  const app = this;

  const config = app.get('authentication');
  const authentication = new AuthenticationService(app);

  authentication.register('jwt', new JWTStrategy());
  authentication.register('oauth', new OAuthStrategy());

  app.use('/authentication', authentication);
  app.get('oauth/cookie', (req, res) => {
    const { access_token } = req.query;

    if(access_token && config.cookie.enabled) {
      res.cookie(config.cookie.name, access_token, { ...config.cookie.options });
    }

    res.redirect(config.oauth.redirect);
  });

  app.configure(expressOauth());
};
```

### Expected behavior

It should allow me to authenticate with auth0

### Actual behavior

Allows me to authenticate but when redirected back to the callback it claims the session is missing.

`error=Grant%3A%20missing%20session%20or%20misconfigured%20provider`

Or, more readably

`error=Grant: Missing session or misconfigured provider`

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

- "@feathersjs/authentication": "^4.0.0-pre.3"
- "@feathersjs/authentication-oauth": "^4.0.0-pre.3"
- "@feathersjs/feathers": "^4.0.0-pre.3",
- "@feathersjs/errors": "^4.0.0-pre.3",

**NodeJS version**: v10

**Operating System**: Docker - node:10

**Browser Version**: Chrome

**Comment by ivanninet** [comment]
Hi @Sieabah 
I have same problem. Have you manage to solve this?

**Comment by Sieabah** [comment]
I have not.

**Comment by daffl** [comment]
A working example for [auth0 login has been added to the Cookbook](https://docs.feathersjs.com/cookbook/authentication/auth0.html)

**Comment by soullivaneuh** [comment]
@daffl I just came to this error after following your guide.

Could you please specify what is missing related to this error so we would know how to fix the issue?

Thanks

**Comment by johnjjung** [comment]
https://github.com/feathersjs/docs/pull/1501

**Comment by mategvo** [comment]
I have a clean feathers installation, I've set this up auth0 exactly as per the documentation. I am using Mongoose.

Getting an error when authenticating, cannot find user with id:
`/#error=No%20record%20found%20for%20id%20'6076145f3abcab07049783c2'`

I've also tried setting `"entityId": "_id",` in the default config. 

Anyone having similar problem?
