### ISSUE TITLE
Authentication : Token expired not manage in express (but sockets)

### ISSUE THREAD

**Issue by yd021976** [feathersjs/feathers#1388]
### Steps to reproduce

login user with HTTP request (HTTP "POST" with url :  /authenticate). Wait for the token expiration (for tests purpose I set it to 10s)

Thank for your help, I need this feature as it is already provided for the "socket" handler in the @feathers/authentication module

### Expected behavior
> When token expired after 10s, application should emits an event 'logout' as it is for the socket handler
This way, others feathers services could react to this event

### Actual behavior
> No "logout" app event is emitted (mainly because there is no managed "timeout" in the express handler) 

**NOTE** : With socket handler, there is a timeout function that trigger when the token expire and then emits "logout" (at application level, not only the socket) : Why this behaviour is different with "express" handler ?

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
@feathersjs/feathers@3.1.4
@feathersjs/authentication@2.1.5

**NodeJS version**:
v12.3.1

**Operating System**:
Macos Mojave 10.14.5

**Browser Version**:
Safari 12.1.1

**React Native Version**:
NOT USED

**Module Loader**:
NOT USED

**Comment by daffl** [comment]
This is not really possible with HTTP which is stateless. You will only know at request time if the token of that request is expired or not. You can keep track of all generated tokens and trigger your own expiration event though.

**Comment by yd021976** [comment]
Thank you for your reply, but I don't expect the client side to be notified when token expired in http (because of stateless).

To be more clear with what I expect : I want **on server side** to be notified (i.e In the feathers app) when token is expired to clean up some things.

For example I want in a given custom feathers service to do (either HTTP or socket) :
```
this.app.on('logout',(user)=>{
// Do something or clean something
})
```

**NOTE**
I also note that in the socket handler the expired token event doesn't work as expected because when token reach expired time, socket handler call authenticate.remove service method, but as token is expired, the authenticate service throws error (token expired).
**So, the socket handler never emit "logout" when token expired.**

It should call the authentication service method or verifyJWT with "ignoreExpiration".

The bug is in @feathersjs/authentication/lib/socket/handler.js line 124 and then in the logout function of the socket handler line 52

I don't know if you plan to solve those 2 bugs/PR, but at this time I implemented a workaround in a service that fire when token expires and then emit a "token expired" event.

That works great with HTTP and whatever protocol because I only want to notify feathers app that a token expired.

**Comment by daffl** [comment]
This has been fixed in the new authentication of Feathers v4
