### ISSUE TITLE
Rest client logout() not clearing header token

### ISSUE THREAD

**Issue by msimonc** [feathersjs/feathers#1389]
Using the latest @feathersjs/rest-client (config: localstorage)

I found that when I call logout()
if I don't manually delete feathers-jwt from localstorage first,
the header of subsequent anonymous api calls will still contain the old Authorization token.

Also, when .authenticate() is called in the logout() callback the accessToken returns valid.

**Comment by daffl** [comment]
What version does latest `@feathersjs/rest-client` mean? This should be fixed in `4.0.0-pre.3` (see [migration guide](https://crow.docs.feathersjs.com/migrating.html) for how to upgrade from previous versions).

**Comment by msimonc** [comment]
Good to hear, thanks:
		"@feathersjs/authentication-client": "^1.0.11",
		"@feathersjs/client": "^3.7.8",
		"@feathersjs/feathers": "^3.3.1",
		"@feathersjs/rest-client": "^1.4.7",
