### ISSUE TITLE
Feathers hook running twice, Github you are my last hope... 

### ISSUE THREAD

**Issue by SysOpsNet** [feathersjs/feathers#1391]
Hello Everyone,

I don't think this is a bug, but I'm hopeless so I turn to Github for assistance. 

I've got a service like this and for some reason it's running twice every time, please help me figure it out. 

`

                const createService = require("feathers-mongodb");
                const hooks = require("./landers.hooks");
                var webshot = require("webshot");
                function webs(input, output) {
                return new Promise(function(resolve, reject) {
                    
                    webshot(input, output, function(err, data) {
                        if (err !== null) reject(err);
                        else resolve(data);
                    })
                });
                }

                module.exports = function (app) {
                const paginate = app.get('paginate');
                const mongoClient = app.get('mongoClient');
                const options = { paginate };

                // Initialize our service with any options it requires
                app.use('/landers', createService(options));

                // Get our initialized service so that we can register hooks and filters
                const service = app.service('landers');

                mongoClient.then(db => {
                    service.Model = db.collection('landers');
                });
                app.service('landers').hooks({
                    before: {
                    async create (context) {
                        context.data.pages = [{pages: "Index (Lander Page)", filename: "index.html"}];
                        return context;  
                    },
                    async update (context) {
                        try {
                        const fs = require('fs');
                        var appRoot = process.env.PWD;
                        let guid =  Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15);
                        let dir = appRoot + "/public/publish/" + guid + "/";
                        if (!fs.existsSync(dir)){
                            fs.mkdirSync(dir);
                        }
                        let defCSS = "<link rel='stylesheet' type='text/css' href='https://fonts.googleapis.com/icon?family=Material+Icons'/><link rel='stylesheet' type='text/css' href='https://fonts.googleapis.com/css?family=Roboto'/><link rel='stylesheet' type='text/css' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css'/><link rel='stylesheet' type='text/css' href='https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css'/>";
                        let defJS = "<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script><script src='https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.1/js/materialize.min.js'></script>";
                        let defHead = "<head>" + defCSS + defJS + "</head>";
                        let css = "<style>" + context.arguments[1].pages[context.arguments[1].lastPageEdited].css + "</style>";
                        let js = "<script>" + context.arguments[1].pages[context.arguments[1].lastPageEdited].js + "</script>";
                        let body = "<body>" + context.arguments[1].pages[context.arguments[1].lastPageEdited].html + "</body";
                        let payload = "<html>" + defHead + css + js + body + "</html";
                        await fs.writeFile(dir + "/" + context.arguments[1].pages[context.arguments[1].lastPageEdited].filename, payload);
                        let host = app.get('protocol') + app.get('host') + ":" + app.get('port');
                        let input = host + '/publish/' + guid + "/" + context.arguments[1].pages[context.arguments[1].lastPageEdited].filename;
                        let output = dir + '/thumb.png';
                        await webs(input, output);
                        context.arguments[1].link = "/publish/" + guid + "/";
                        context.arguments[1].thumb = "/publish/" + guid + "/thumb.png";

                        let backupData = {
                            link: "/publish/" + guid + "/", 
                            thumb: "/publish/" + guid + "/thumb.png", 
                            date: new Date(),
                            html: context.arguments[1].pages[context.arguments[1].lastPageEdited].html,
                            css: context.arguments[1].pages[context.arguments[1].lastPageEdited].css,
                            js: context.arguments[1].pages[context.arguments[1].lastPageEdited].html,
                            components: context.arguments[1].pages[context.arguments[1].lastPageEdited].components,
                            styles: context.arguments[1].pages[context.arguments[1].lastPageEdited].styles,
                            userID: context.arguments[1].userID,
                            pageID: context.arguments[1].lastPageEdited
                        };
                        await app.service('landerbackups').create(backupData);
                        context.arguments[1].lastPageEdited = unset;
                        return context;  
                        } catch (error) {
                        console.log(error);
                        }          
                    },
                    }
                })
                

                service.hooks(hooks);
                
                };
`

### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc. This makes it much easier for us to debug and issues that have a reproducable example will get higher priority.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by SysOpsNet** [comment]
Without this line it's only running once: 

await app.service('landerbackups').create(backupData);

**Comment by SysOpsNet** [comment]
Is there a more elegant way to create something in a different service?

**Comment by J3m5** [comment]
Hi, does your landerBackups service call the lander service in some way?
If this is the case, this is maybe why it is called twice.

**Comment by SysOpsNet** [comment]
It does not, it's just everything default from "feathers generate service"

**Comment by SysOpsNet** [comment]
`// Initializes the `landerbackups` service on path `/landerbackups`
const createService = require('feathers-mongodb');
const hooks = require('./landerbackups.hooks');
var webshot = require('webshot');
function webs(input, output) {
  return new Promise(function(resolve, reject) {
    
      webshot(input, output, function(err, data) {
        if (err !== null) reject(err);
        else resolve(data);
    })
  });
}

module.exports = function (app) {
  const paginate = app.get('paginate');
  const mongoClient = app.get('mongoClient');
  const options = { paginate };

  // Initialize our service with any options it requires
  app.use('/landerbackups', createService(options));

  // Get our initialized service so that we can register hooks and filters
  const service = app.service('landerbackups');

  mongoClient.then(db => {
    service.Model = db.collection('landerbackups');
  });

  service.hooks(hooks);
};
`

`
const { authenticate } = require('@feathersjs/authentication').hooks;
module.exports = {
  before: {
    all: [ authenticate('jwt') ],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  },

  after: {
    all: [],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  },

  error: {
    all: [],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  }
};

`

**Comment by SysOpsNet** [comment]
Actually I might have just found the issue. 

var webshot = require('webshot');
function webs(input, output) {
return new Promise(function(resolve, reject) {

            webshot(input, output, function(err, data) {
                if (err !== null) reject(err);
                else resolve(data);
            })
        });
        }


Testing now

**Comment by SysOpsNet** [comment]
I removed it and tested it, and it is still running twice.

**Comment by SysOpsNet** [comment]
I found it, from postman it only does it once, so the issue is in the frontend, I'm sorry for wasting anyone's time.
