### ISSUE TITLE
Custom Jwt Verifier V4

### ISSUE THREAD

**Issue by philoez98** [feathersjs/feathers#1399]
Hello, 
I need to write a custom Jwt verifier to handle token blacklisting. I upgraded to feathers v 4.0.0-pre.3 and I cannot find any up to date examples in the docs on how to do it.
Is there something to know? I tried to implement something but I couldn't come up with anything useful, mostly because of the new api. How do you tackle this? Is extending the *Verifier* class still recommended?
Any help is appreciated.

Thanks

**Comment by daffl** [comment]
This definitely still needs to be added to the [cookbook](https://crow.docs.feathersjs.com/cookbook/) but basically looks like this:

[Customize the authentication service](https://crow.docs.feathersjs.com/api/authentication/service.html#customization), specifically the [verifyAccessToken(accessToken)](https://crow.docs.feathersjs.com/api/authentication/service.html#verifyaccesstoken-accesstoken) and [remove()](https://crow.docs.feathersjs.com/api/authentication/service.html#remove-id-params) method:

```js
const { AuthenticationService } = require('@feathersjs/authentication');
const { NotAuthenticated } = require('@feathersjs/errors');

// Global blacklist, ideally should use e.g. a Redis or other database store
const blackList = {};

class MyAuthService extends AuthenticationService {
  async verifyAccessToken(accessToken) {
    // Check blacklist for access token
    if (blackList(accessToken)) {
      throw new NotAuthenticated('Access not allowed');
    }

    return super.verifyAccessToken(accessToken);
  }

  async remove (id, params) {
    const result = super.remove(id, params);
    const { accessToken } = result;

    if (accessToken) {
      // Add `accessToken` to blacklist here
      blackList[accessToken] = true;
    }

    return result;
  }
}

app.use('/authentication', new MyAuthService(app));
```

**Comment by philoez98** [comment]
@daffl Wow thanks for the super quick response! I am going to try this indeed. If I get it right there is no more need for an external service to handle the the blacklisting process, it can be done straight in the auth service. I am wrong on this?

**Comment by daffl** [comment]
It's up to you really. You can still access `this.app.service('blacklistService')` in those methods and store/check things there. But since you probably just need some kind of a key/value store it might be easier to access e.g. Redis directly (for any other database an internal service may still make sense).

**Comment by philoez98** [comment]
It makes sense. Thank you again for the super valuable help. I am going to close this now and I'll reopen it just in case something goes terribly wrong. BTW: the new upcoming release is looking sick!
