### ISSUE TITLE
use feathers-cli, generate service, how to delete multiple data by one http？

### ISSUE THREAD

**Issue by wwbluechip** [feathersjs/feathers#1400]
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc. This makes it much easier for us to debug and issues that have a reproducable example will get higher priority.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by daffl** [comment]
[Enable removing of multiple entries](https://crow.docs.feathersjs.com/api/databases/common.html#service-options) via `{ multi: [ 'remove' ] }` then multiple remove is possible using and `id` of `null` (documented [here](https://docs.feathersjs.com/api/services.html#removeid-params) and [here](https://docs.feathersjs.com/api/databases/common.html#adapterremoveid-params)) or sending a `DELETE` request to the main endpoint (documented [here](https://docs.feathersjs.com/api/client/rest.html#remove)).
