### ISSUE TITLE
Error handling in @feathers/rest-client

### ISSUE THREAD

**Issue by piwo1984** [feathersjs/feathers#1401]
### Steps to reproduce

I have 2 feathers service. One instanciates a feathers/rest-client. When I call `create` of the first service the mentioned client calls the second service.
This is working as expected for regular calls.
Now when the second service throws/returns an error (e.g. 409) I can see a perfect response, when calling the second service through `Postman`. The problem is, the client only receives a GeneralError with a shorten `message` indicating the 409.
Is it possible to configure the client in any way to get the "underlying" `@feathers/error`?

### Expected behavior
Cath a ConflictError (status: 409)

### Actual behavior
Catch a GeneralError (status: 500).

**Comment by daffl** [comment]
Feathers errors are usually passed through with all their information. Do you have a complete example that shows the issue?

**Comment by piwo1984** [comment]
I've found the problem. I got another error in another request which I wasn't aware of. I fixed this one and now I get the error I'm expecting.
