### ISSUE TITLE
How do I roll back the files I generated by the "generate" command?

### ISSUE THREAD

**Issue by ReadRou** [feathersjs/feathers#1402]
I have a question. When I use the "generate" command to generate "service" or "authentication", I cannot roll back the operation. I can only manually delete the generated file.

**Comment by daffl** [comment]
The CLI does not handle this, but this is exactly what Git is for. Commit your current working directory you want to be able to roll back to and run the command. To undo it run

```sh
# Hard reset to last commit
git reset --hard
# Deletes all new files
git clean -f
```

**Comment by ReadRou** [comment]
Thank you, I think I know what to do. 

:)

**Comment by ReadRou** [comment]
> The CLI does not handle this, but this is exactly what Git is for. Commit your current working directory you want to be able to roll back to and run the command. To undo it run
> 
> ```shell
> # Hard reset to last commit
> git reset --hard
> # Deletes all new files
> git clean -f
> ```

Thank you, I think I know what to do.

:)
