### ISSUE TITLE
v3 auth - one place to get inbound JWT?

### ISSUE THREAD

**Issue by jnardone** [feathersjs/feathers#1403]
### Steps to reproduce

I'm trying to extract some additional info from the JWT that the user authenticates with.  I realize this all changes in v4 but waiting for that isn't an option for us right now (and we won't migrate right away)

I'm trying to figure out if there's a better way to do this.  Ideally what I want is access to a decoded JWT, server-side, that was used to authenticate the request.  We use both REST and socket.io in different places, so it needs to work with both.

I'd prefer to NOT re-find/re-extract/re-decode the token from the headers/etc. again -- auth-jwt (via passport) already did this.  

Here's what I have so far, but I'm unhappy at the inconsistency of it.
1) for REST calls, I can access the decoded payload as part of a custom Verifier in the authentication service.  The payload is passed in and I can extract the info I need (and as a side benefit, re-author the outputted token with my custom fields, which gets dropped in the default verifier).  This works for REST because every call via REST has a token to verify.

```

class DecorateLoggerVerifier extends Verifier {
  // grab stuff from payload before we let the base class do its thing
  verify(req, payload, done) {
    const custom = payload['custom'];

    // for REST calls
    if (custom && logger.addToScope) {
      logger.addToScope('custom', custom);
    }

    // call default implementation, which will look up user etc
    // and then re-attach custom to JWT
    super.verify(req, payload, function(err, entity, newPayload) {
      if (err) {
        return done(err);
      }

      newPayload['custom'] = custom;
      return done(null, entity, newPayload);
    });
  }
}
```

2) for socket.io calls, I have to check (in a hook post-authentication) if params.connection (and params.connection.payload) are there and access info.

```
    // for socket.io calls
    if (params.connection && params.connection.payload && params.connection.payload.custom) {
      if (logger.addToScope) {
        logger.addToScope('custom', params.connection.payload.custom);
      }
    }
```

But... ew.  There's no context in a passport verifier, so I can't just check the context in a hook in one place (even if I have to look at two different things in `hook.params`)  The socket.io stuff doesn't call the authentication service on every request but just when the socket reconnects, so I can't just do the Verifier trick.  

Am I missing something?  Is the decoded JWT exposed in some other way in the v3 stuff?  Is there some missing link where I can bridge the verifier to the context params?  The incongruousness of this worries me from a code maintenance perspective.

**Comment by daffl** [comment]
You are not missing anything, that's why v4 auth exists and no longer uses Passport because handling cases like this turned out to be inconsistent and unreliable. In v4 the decoded payload will be in `params.authentication.payload` for any request.

PS: I feel like you may have already spent more time on this than it takes to try and upgrade to v4.pre. If nobody does it there's no way for me to make upgrade easier or address common problems.

**Comment by jnardone** [comment]
I'd love to try v4, the trick is prioritization. :)  we also have some custom stuff tied in for SAML support so we'd have to check that out.

Is there a timeframe for v4 GA?

**Comment by jnardone** [comment]
@daffl curious if you have any insight into a GA for v4...

**Comment by daffl** [comment]
Next 4 weeks. If I don't get any more feedback on migration issues other than the currently open ones it will go out pretty much as is.

**Comment by jnardone** [comment]
ok.  i'll try to take a swing at our code before then and provide feedback.  this is great stuff.
