### ISSUE TITLE
does v4 auth config support multiple configurations?

### ISSUE THREAD

**Issue by jnardone** [feathersjs/feathers#1405]
### Steps to reproduce

In v3, you could (with a few workarounds, like not naming your configurations "jwt" or "local") define multiple configurations of the same type in a single config, e.g.

```
"secret": "foo",
"config1": {
  "service": "users1",
  "header": "Authorization",
  "jwt": {
    "audience": "aud1",
    ...
  }
},
"config2": {
  "service": "users2",
  "jwt": {
    "audience": "aud2",
     ...
  }
 ...
}
```

instantiated with

```
const authentication = require('@feathersjs/authentication');
const jwt = require('@feathersjs/authentication-jwt');
// load config object from somewhere
app.configure(authentication(config));
app.configure(jwt({ name: 'config1'});
app.configure(jwt({ name: 'config2'});
```

Is this possible in v4?  It's not documented at https://crow.docs.feathersjs.com/migrating.html#manual-upgrade though I'm guessing it's not a well-used feature.  
(This wasn't limited to -jwt, you could do this with -local as well.)

It's also not clear from the migration documentation where the configuration information from a file or JSON object is passed to the new authentication core.  (formerly `app.configure(authentication(config));`)

**Comment by daffl** [comment]
Yes. You can [instantiate the v4 authentication service](https://crow.docs.feathersjs.com/api/authentication/service.html#constructor-app-configkey) with a `configKey` that points to a different configuration. It will allow for completely separate authentication configuration:

```js
const { AuthenticationService, JWTStrategy } = require('@feathersjs/authentication');
const { LocalStrategy } = require('@feathersjs/authentication-local');

module.exports = app => {
  const auth1 = new AuthenticationService(app, 'auth1');
  const auth2 = new AuthenticationService(app, 'auth2');

  auth1.register('jwt', new JWTStrategy());
  auth1.register('local', new LocalStrategy());
  auth2.register('jwt', new JWTStrategy())

  app.use('/v1/authentication', auth1);
  app.use('/v2/authentication', auth2);
}
```

Will look for a configuration as:

```js
{
  "auth1": {
    "secret": "CHANGE_ME",
    "entity": "user",
    "service": "v1/users",
    "authStrategies": [ "jwt", "local" ],
    "jwtOptions": {
      "header": { "typ": "access" },
      "audience": "https://yourdomain.com",
      "issuer": "feathers",
      "algorithm": "HS256",
      "expiresIn": "1d"
    }
  },
  "auth2": {
    "secret": "CHANGE_ME",
    "entity": "user",
    "service": "v2/users",
    "authStrategies": [ "jwt", "local" ],
    "jwtOptions": {
      "header": { "typ": "access" },
      "audience": "https://yourdomain.com",
      "issuer": "feathers",
      "algorithm": "HS256",
      "expiresIn": "1d"
    }
  }
}
```

To merge configurations you could e.g. [extend the authentication service](https://crow.docs.feathersjs.com/api/authentication/service.html#customization) and overwrite the [configuration getter](https://crow.docs.feathersjs.com/api/authentication/service.html#configuration-2).

**Comment by jnardone** [comment]
True.  Earlier we had to register just a single auth service.  (My apologies on missing the crow primary docs on this, I just saw the migration guide.)

What am I missing though in terms of how these services know their config?  In my case, I can't rely just on a file on the filesystem (we don't store our secrets on disk) - I want to pass an explicit configuration object to the service.  I'm guessing the `app.set` method is the way to go there?

In v3 I basically couldn't have 2 auth services because `app.configure(authentication(config));` would implicitly do an `app.set` on a fixed key.  It looks like in v4, I can have 2 independent configs for the 2 services and specify different `configKey` values to the two services to reference configs in `app.get`?  (if so, yay!)

**Comment by daffl** [comment]
Exactly. It's using `app.get('auth1')` and `app.get('auth2')` (see the service constructor docs 😄) and they are both completely separate. Unlike in the previous auth it will also always use the latest value from that location so you can update the configuration (`app.set('auth1')`) at runtime if so needed.
