### ISSUE TITLE
using @feathersjs/socketio with socket.io-redis

### ISSUE THREAD

**Issue by adambezecny** [feathersjs/feathers#1411]
Hi,

we were using socket.io library with socket.io-redis. In a same way we would like to use socket.io-redis with @feathersjs/socketio. Unfortunatelly socket created by @feathersjs/socketio function does not expose adapter function. Can you advise how/if at all is it possible to use @feathersjs/socketio with redis adapter?

**Comment by daffl** [comment]
After configuring Socket.io the instance is available as `app.io` (documented [here](https://docs.feathersjs.com/api/socketio.html#appconfiguresocketio).  So you can do

```js
const redisAdapter = require('socket.io-redis');

app.configure(socketio());
app.io.adapter(redisAdapter({ host: 'localhost', port: 6379 }));
```

**Comment by daffl** [comment]
As a side note, [feathers-sync](https://github.com/feathersjs-ecosystem/feathers-sync/) is probably an easier way to scale real-time events with a Feathers only server.

**Comment by adambezecny** [comment]
thanks David! approach with app.io works fine for us! feathers-sync looks promising (redis HA setup is quite a pain) but because we need to support legacy clients (which are not using native feathersjs api) at the moment we cannot use it.

**Comment by averri** [comment]
@adambezecny , what versions of libraries are you using? The example @daffl posted above is not working for me. Clients on different servers does not receive events on the same channel.

**Comment by adambezecny** [comment]
"@feathersjs/socketio": "^3.2.9",
"socket.io": "^2.1.1",
"socket.io-redis": "^5.2.0"
"@feathersjs/configuration": "^2.0.6",
"@feathersjs/errors": "^3.3.6",
"@feathersjs/express": "^1.3.1",
"@feathersjs/feathers": "^3.3.1",
"@feathersjs/socketio": "^3.2.9",

**Comment by jiangts** [comment]
would there be any problems in using `feathers-sync` and `socket.io-redis` together?
I'm using some socket.io rooms and messaging outside of feathers, and also have feathers service events I'd like to sync. I'm worried feathers-sync will cause some socket.io emits that will then get propagated a lot. Do feathers channels use socket.io rooms?

**Comment by daffl** [comment]
Channels do not use rooms. You'd probably end up using either or as long as socket.io-redis keeps a client connected to the same instance (otherwise you wouldn't know who is authenticated or not).
