### ISSUE TITLE
how to search by pagination?i want to get page 2 data,how can i write query params?

### ISSUE THREAD

**Issue by wwbluechip** [feathersjs/feathers#1412]
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc. This makes it much easier for us to debug and issues that have a reproducable example will get higher priority.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by daffl** [comment]
This is done with the [$limit](https://docs.feathersjs.com/api/databases/querying.html#limit) and [$skip](https://docs.feathersjs.com/api/databases/querying.html#skip) parameters. If you want page two with a page size of 10 items it would be `{ $limit: 10, $skip: 10 }` (`$limit=10&$skip=10`), page 3 would be `{ $limit: 10, $skip: 20 }`.

**Comment by wwbluechip** [comment]
> This is done with the [$limit](https://docs.feathersjs.com/api/databases/querying.html#limit) and [$skip](https://docs.feathersjs.com/api/databases/querying.html#skip) parameters. If you want page two with a page size of 10 items it would be `{ $limit: 10, $skip: 10 }` (`$limit=10&$skip=10`), page 3 would be `{ $limit: 10, $skip: 20 }`.

thanks.Same as I thought
