### ISSUE TITLE
@feathersjs/socketio socket not accepting custom headers

### ISSUE THREAD

**Issue by adambezecny** [feathersjs/feathers#1414]
we are creating feathersjs  socket in following way:

```js
const express = require('@feathersjs/express')
const app = expressFs(feathers())
  app.configure(socketio({
    path: '/channel/webchat'
  }))
```

websocket works fine, from client app we are creating connection like this (i.e. not using featherjs client library):

```js
socket = window.io(wsHostName, { reconnectionDelayMax: RETRY_INTERVAL, path: wsParse.pathname })
```

when we want to include custom header:

```js
socket = window.io(wsHostName, { reconnectionDelayMax: RETRY_INTERVAL, path: wsParse.pathname,   transportOptions: {
    polling: {
      extraHeaders: {
        'at': 'abc'
      }
    }
  } })
```

browser suddenly tries to do CORS preflight check (HTTP OPTIONS) which is failing with error 400 Bad Request

Please advise how to force feathersjs websocket to accept custom header.

**Comment by daffl** [comment]
I'm advising to always force the `websockets` transport. Polling shouldn't be necessary for any browser anymore. To allow CORS requests you will need the [cors middleware](https://www.npmjs.com/package/cors).
