### ISSUE TITLE
i use JWT authentication . how can i log out?

### ISSUE THREAD

**Issue by wwbluechip** [feathersjs/feathers#1417]
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc. This makes it much easier for us to debug and issues that have a reproducable example will get higher priority.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by daffl** [comment]
With the authentication client this is done by calling [app.logout](https://docs.feathersjs.com/api/authentication/client.html#applogout).

Internally this will call [remove on the authentication service](https://docs.feathersjs.com/api/authentication/server.html#serviceremovedata) which will trigger the [logout event](https://docs.feathersjs.com/api/authentication/server.html#apponlogout-callback). Through HTTP this means `DELETE /authentication/<jwt>` or `DELETE /authentication` with the header `Authorization: <jwt>`.

**Comment by wwbluechip** [comment]
but 

> With the authentication client this is done by calling [app.logout](https://docs.feathersjs.com/api/authentication/client.html#applogout).
> 
> Internally this will call [remove on the authentication service](https://docs.feathersjs.com/api/authentication/server.html#serviceremovedata) which will trigger the [logout event](https://docs.feathersjs.com/api/authentication/server.html#apponlogout-callback). Through HTTP this means `DELETE /authentication/<jwt>` or `DELETE /authentication` with the header `Authorization: <jwt>`.

i use this way `DELETE /authentication with the header Authorization: <jwt>` ,but i use this accessToken can also  pass authentication.why?

**Comment by daffl** [comment]
I'm not sure I follow?

**Comment by wwbluechip** [comment]
> I'm not sure I follow?

DELETE /authentication with the header Authorization: <jwt> is not working. the deleted accessToken also can be approved

**Comment by hnahmed** [comment]
hes right it doesn't work

**Comment by edwardsmarkf** [comment]
here is how i log out -- not sure if this is optimum or not, i am still
waiting confirmation:

<a href='#' onClick='javascript: (async () => { await
feathersClient.logout(); })(); '>logout</a>

https://github.com/feathersjs/docs/issues/1369



Thank you,

Mark Edwards

**Comment by hnahmed** [comment]
> here is how i log out -- not sure if this is optimum or not, i am still waiting confirmation: a href='#' onClick='javascript: (async () => { await feathersClient.logout(); })(); '>logout</a [feathersjs/docs#1369](https://github.com/feathersjs/docs/issues/1369) Thank you, Mark Edwards
> […](#1752 


That works if your front end and backend are both run with feathers. Doesn't work if you're trying to log a user out with HTTP requests from the frontend.

Here's what I found for that function:


```
{
--
1148 | key: "logout",
1149 | value: function logout() {
1150 | var _this6 = this;
1151 |  
1152 | return Promise.resolve(this.app.get('authentication')).then(function () {
1153 | return _this6.service.remove(null).then(function (authResult) {
1154 | return _this6.removeAccessToken().then(function () {
1155 | return _this6.reset();
1156 | }).then(function () {
1157 | _this6.app.emit('logout', authResult);
1158 |  
1159 | return authResult;
1160 | });
1161 | });
1162 | }).catch(function (error) {
1163 | return _this6.handleError(error, 'logout');
1164 | });
1165 | }
1166 
```| }

**Comment by wwbluechip** [comment]
> > here is how i log out -- not sure if this is optimum or not, i am still waiting confirmation: a href='#' onClick='javascript: (async () => { await feathersClient.logout(); })(); '>logout</a [feathersjs/docs#1369](https://github.com/feathersjs/docs/issues/1369) Thank you, Mark Edwards
> > […](#1752
> 
> That works if your front end and backend are both run with feathers. Doesn't work if you're trying to log a user out with HTTP requests from the frontend.
> 
> Here's what I found for that function:
> 
> ```
> {
> --
> 1148 | key: "logout",
> 1149 | value: function logout() {
> 1150 | var _this6 = this;
> 1151 |  
> 1152 | return Promise.resolve(this.app.get('authentication')).then(function () {
> 1153 | return _this6.service.remove(null).then(function (authResult) {
> 1154 | return _this6.removeAccessToken().then(function () {
> 1155 | return _this6.reset();
> 1156 | }).then(function () {
> 1157 | _this6.app.emit('logout', authResult);
> 1158 |  
> 1159 | return authResult;
> 1160 | });
> 1161 | });
> 1162 | }).catch(function (error) {
> 1163 | return _this6.handleError(error, 'logout');
> 1164 | });
> 1165 | }
> 1166 
> ```| }
> ```

so,it look like  ```removeAccessToken()``` doesn't be called when using http request?

**Comment by daffl** [comment]
JWTs have no built in mechanism to invalidate them. Any valid JWT will continue to be usable until it expires. To logout a client has to "forget" it. The logout is just a convenience method to indicate to the server that the user wishes to log out.

It can be used e.g. blacklist the token so that it can not continue to be used. This is possible in v4 but I have not finished the docs for it. The issue for this is https://github.com/feathersjs/feathers/issues/1336

**Comment by wwbluechip** [comment]
> JWTs have no built in mechanism to invalidate them. Any valid JWT will continue to be usable until it expires. To logout a client has to "forget" it. The logout is just a convenience method to indicate to the server that the user wishes to log out.
> 
> It can be used e.g. blacklist the token so that it can not continue to be used. This is possible in v4 but I have not finished the docs for it. The issue for this is #1336

alright, I understand. So in client i just need to do this for logout.```localStorage.removeItem('accessToken')```,is that right?

**Comment by wwbluechip** [comment]
> > JWTs have no built in mechanism to invalidate them. Any valid JWT will continue to be usable until it expires. To logout a client has to "forget" it. The logout is just a convenience method to indicate to the server that the user wishes to log out.
> > It can be used e.g. blacklist the token so that it can not continue to be used. This is possible in v4 but I have not finished the docs for it. The issue for this is #1336
> 
> alright, I understand. So in client i just need to do this for logout.`localStorage.removeItem('accessToken')`,is that right?

or remove cookie of accessToken

**Comment by daffl** [comment]
Correct. When using Feathers on the client this will happen automatically when calling `app.logout()`.

**Comment by wwbluechip** [comment]
> Correct. When using Feathers on the client this will happen automatically when calling `app.logout()`.

Thank you very much for your reply
