### ISSUE TITLE
no record found for id , unexpected behavior

### ISSUE THREAD

**Issue by mohanagy** [feathersjs/feathers#1418]
### Steps to reproduce

I don't know if we have an issue here or I didn't follow the instructions.
My system has a table which has a unique constraint for a compound of two columns.
my database is MySQL and I'm using Knex.
I'm trying to create a record   for every change in the below object
the issue is when I'm trying to insert a record with this data  for the second time
```
     {
     shipment_id: '311',
     updated_at: '2019-06-26 10:18:49',
     updated_by: '29',
     tracking_reference: 'test_tracking_ref',
     broker_key: 'test_broker_key',
     start_tracking_date: '2020-02-22 18:20:00',
     created_at: '2019-06-26 10:18:49',
     created_by: '29',
 },
```
if I insert the previous object for the first time , it will record it normally
if I made any changes as below
```
     {
     shipment_id: '311',
     updated_at: '2019-06-26 10:18:49',
     updated_by: '29',
     tracking_reference: 'test_again',// I changed this value
     broker_key: 'test_broker_key', 
     start_tracking_date: '2020-02-22 18:20:00',
     created_at: '2019-06-26 10:18:49',
     created_by: '29',
    batch_run_id:'1'
 },
```
I will get an error 
my compound constraint is ['shipment_id','batch_run_id']
my service call for the two times 
```
    const alsEld = await context.app.service('/als_eld/:shipment_id')
        .create(data, params)
```
and the error object is 

```
{
     message: 'No record found for id \'311\'',
     code: 404,
     extraData: {},
     hook:
      { type: 'error',
        arguments: [Array],
        service: [Object],
        app: [EventEmitter],
        method: 'create',
        path: 'als_eld/:shipment_id',
        data: [Object],
        params: [Object],
        original: undefined,
        error: [Circular] } } 
```
my service options are 
```
  const options = {
    name: 'Als_Eld',
    Model,
    paginate: false,
    id: 'shipment_id'
  };
```
### Expected behaviour
the expected behavior is creating a new recored  
### Actual behaviour
No record found for id 311 
### System configuration

**Module versions** (especially the part that's not working):
```
    "knex": "^0.16.5",
    "@feathersjs/configuration": "^2.0.6",
    "@feathersjs/errors": "^3.3.6",
    "@feathersjs/express": "^1.3.1",
    "@feathersjs/feathers": "^3.3.1",
    "feathers-knex": "^5.0.7",
```
**NodeJS version**:
v10.15.3
**Operating System**:
 Ubuntu 18.10

Did I miss anything?

**Comment by mohanagy** [comment]
@daffl any help?

**Comment by daffl** [comment]
Compound ids are not supported by default. If you want to use `shipment_id` as the primary key field it should be set as the [`id` option](https://docs.feathersjs.com/api/databases/common.html#serviceoptions).

**Comment by mohanagy** [comment]
as I mentioned before, I already did it
```
 const options = {
    name: 'Als_Eld',
    Model,
    paginate: false,
    id: 'shipment_id'
  };
```
Actually, I removed all Unique constraints on this table and the problem is still there

**Comment by daffl** [comment]
Then your service path should be `'/als_eld'` not `'/als_eld/:shipment_id'`

**Comment by mohanagy** [comment]
@daffl 
Actually no,
According to my code 
```
// Initializes the `als_eld` service on path `/als_eld`
const createService = require('feathers-knex');
const jwkToPem = require('jwk-to-pem');

const createModel = require('../../models');
const hooks = require('./alsEld.hooks');
const {
  trackActiveShipmentsHooks,
  trackActiveShipmentsService
} = require('./methods/trackActiveShipments');
module.exports = (app) => {
  const Model = createModel(app);
  const jwk = app.get('jwt');
  const pem = jwkToPem(jwk);

  const options = {
    name: 'Als_Eld',
    Model,
    paginate: false,
    id: 'shipment_id',
  };

  // Initialize our service with any options it requires

  // Get our initialized service so that we can register hooks and filters
  app.use('/als_eld/shipment_tracking', trackActiveShipmentsService(app));
  app.use('/als_eld/:shipment_id', createService(options));
  app.service('/als_eld/shipment_tracking').hooks(trackActiveShipmentsHooks({ pem }));

  const service = app.service('/als_eld/:shipment_id');
  service.hooks(hooks({ pem }));
};


```
As I said before , if there is no record in the database it works fine ,
if we tried to add another record with the same data `which will be fine because we removed any unique condition ` we will face the error mentioned before which is no record found .

**Comment by daffl** [comment]
I still don't think I understand the problem. A complete minimal repository to reproduce the problem would go a long way.

**Comment by mohanagy** [comment]
ok sorry for making you confused @daffl ,
I hope the below details make everything simple and clear
this is my table indexes : 

![image](https://user-images.githubusercontent.com/11216054/60394772-fd7c5f00-9b31-11e9-9600-48d0f5eb32e9.png)

 this is my service
![code](https://user-images.githubusercontent.com/11216054/60394570-15061880-9b2f-11e9-8507-b152679a32db.png)
this is my hooks list
![code](https://user-images.githubusercontent.com/11216054/60394581-3961f500-9b2f-11e9-83b0-ea55736663df.png)

and I'm using only beforeCreateAlsEld as a **before hook**
![code](https://user-images.githubusercontent.com/11216054/60394590-6dd5b100-9b2f-11e9-83da-934ef76f05dc.png)

and this hook not important  which I used it to clean 
![code](https://user-images.githubusercontent.com/11216054/60394621-ac6b6b80-9b2f-11e9-80a4-1b62cfb5c945.png)

and this my first request 

![image](https://user-images.githubusercontent.com/11216054/60394679-fef95780-9b30-11e9-8817-60e3e2ac7aa5.png)

if we tried again  with the same data 
![image](https://user-images.githubusercontent.com/11216054/60394719-76c78200-9b31-11e9-8781-e7aa7f3f57bc.png)

**Comment by daffl** [comment]
Unfortunately screenshots of code don't really help. For more complex issues like this a minimal repository and the step to reproduce the problem is really the only option.

**Comment by tvld** [comment]
I get this same error message ``no record found for id`` when the authentication expired.
