### ISSUE TITLE
Disable socket emits

### ISSUE THREAD

**Issue by yurian14** [feathersjs/feathers#142]
Hello, and great work on the feathers project! I have been trying to use feathers but my issue is that when I set it up with socketio, the event filtering option executes the code for every socket client. This makes the complexity for created/updated/patched/removed events O(N) where N is the number of clients on the node. It also does not cover sockets that are distributed on other load-balanced nodes.

I could try to address these issues by implementing my own custom socket notification module. However, I do not see a way to disable the feathers socket emit. The only way I can disable it is either to not set it up with socketio (and I do want my API to be reacheable by websockets), or again through returning a falsy valu through event filtering, which goes back to complexity O(N). Is there another way I am missing to disable socket emits? Many thanks!

**Comment by daffl** [comment]
To synchronize service events through different Nodes you can use the [feathers-mubsub](https://github.com/feathersjs/feathers-mubsub) plugin which uses MongoDB as the event hub.

I do not see how to reduce the complexity to anything less than O(N)? Did you run into any performance issues? There is a number a maximum connections a server can reasonably handle which I put at around 10k and as long as the checks are quick (everything needed is already in memory) it didn't seem to be more than a couple of milliseconds.

**Comment by yurian14** [comment]
Thank you for your response! The use case I was thinking of is a chat application with multiple users and chat rooms. Any time a user posts in a chat room, only the few clients present in that room need to be notified. As it stands, feathers loops through every connected client for every create/update/remove event. Suppose there are ten thousand users in five thousand chatrooms (two users per chat room) communicating at the same time, I imagine these milliseconds will add up as feathers needlessly loops through every socket on every event.

I could try to implement my own socket messaging system where I keep sockets separated by chatrooms and only loop through the relevant sockets on a create/update/remove event. But I need to be able to disable the default feathers socket emits. Is there way to do this?

**Comment by yurian14** [comment]
To further clarify, I have not run into any performance issues but I am still at the design stage. I seek to avoid any O(N) complexity on the number of users as I believe any chat application should be able to scale without linear dependence on the global user base. I am willing to admit I may be wrong, though!

**Comment by daffl** [comment]
I hope the mubsub plugin (I'm thinking of renaming it to feathers-sync when adding other messaging hubs like Readis) answers your question about synching all service events.

I was thinking more about your other point as well and you are right, there might be a way we could add "room" capabilities to socket filtering. For example, create groups of socket connections where the users all belong to the same company. When a new Todo is created, only the sockets that belong to the same company than the Todo will be looped through. I'm not sure how this would look like yet but basically additionally to Socket filtering (which I would like to streamline a little more in the future anyway) you would also check on a Socket connection what room to stick it into.

**Comment by daffl** [comment]
The last point mentioned should be improved now in Feathers 2 with the advanced event filtering (see http://docs.feathersjs.com/real-time/filtering.html).
