### ISSUE TITLE
_patch call on nedb adapter throws error : "error: TypeError: Cannot read property 'nedb' of undefined"

### ISSUE THREAD

**Issue by pratikmachchar** [feathersjs/feathers#1423]
### Steps to reproduce
_patch is not working
Gives "error: TypeError: Cannot read property 'nedb' of undefined"
I am calling this from custom service on *server*

```
this.app.service('myservice').patch("bbyphADEt7RMIHqJ", { balance: 450});//This work

//NOT WorKING
this.app.service('myservice')._patch("bbyphADEt7RMIHqJ", { balance: 450}); //NOT working
```
bug git repo.
https://github.com/pratikmachchar/_patch_feathersjs_nebd

### Expected behavior
_patch should be called successfully 
### Actual behavior
Throws an error  "error: TypeError: Cannot read property 'nedb' of undefined"

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
"@feathersjs/feathers": "^3.3.1",
"feathers-nedb": "^4.0.1",

**NodeJS version**:  v10.6.0
**Operating System**: Ubuntu 18.04
**Module Loader**: npm

**Comment by daffl** [comment]
Fixed in `feathers-nedb@4.0.2`
