### ISSUE TITLE
.logout() from auth-client throws a server-side error (no strategy) (v4)

### ISSUE THREAD

**Issue by jnardone** [feathersjs/feathers#1428]
### Steps to reproduce

Using @feathersjs/authentication-client, I set up authentication settings and establish a REST app.

```
const auth = authentication({
  storage: window.localStorage,
  storageKey: 'foo-jwt',
  path: '/authentication',
  jwtStrategy: 'my-jwt'
});

const restApp = feathers()
  .configure(rest(site).axios(axios))
  .configure(auth);
```

Later, I should be able to call `restApp.logout()` to log out.  In v2 this works.  I would expect that the logout() call would use the information from the configuration for the strategy.

### Expected behavior
Logout happens client-side, and DELETE /authentication endpoint is called server-side.

### Actual behavior
An error is thrown:

```
 stack='NotAuthenticated: Invalid authentication information (no `strategy` set)
    at new NotAuthenticated (/.../node_modules/@feathersjs/errors/lib/index.js:93:17)
    at Object.<anonymous> (/.../node_modules/@feathersjs/authentication/lib/core.js:150:23)
    at Generator.next (<anonymous>)
    at /.../node_modules/@feathersjs/authentication/lib/core.js:7:71
```

### System configuration

Tell us about the applicable parts of your setup.
4.0-pre.3 (all)
node 10.16
macos

**Comment by jnardone** [comment]
this was caused by a socket/rest problem.

**Comment by SeveHo** [comment]
Hi @jnardone how did you resolve this?

**Comment by SeveHo** [comment]
Alright thanks!
