### ISSUE TITLE
TodoMVC example links are broken

### ISSUE THREAD

**Issue by ebourmalo** [feathersjs/feathers#143]
Hey guys,

On the documentation, section [Building a frontend](http://feathersjs.com/quick-start/#toc6) of the quick-start page, the links for `jQuery`, `Angular`, `React` and `CanJS` are all broken.

By looking directly on your [todoMVC page](http://feathersjs.github.io/todomvc/), I couldn't find any angular example.

**Comment by daffl** [comment]
It's at https://github.com/feathersjs/todomvc/tree/master/feathers/angularjs but apparently hasn't been copied over to gh-pages yet. In fact, I don't think it works right even though with the little I know or care about Angular it should by just changing the service to what it looks like now (https://github.com/feathersjs/todomvc/blob/master/feathers/angularjs/js/services/todoStorage.js). Maybe @ekryski or anybody else who knows a little more about it can have a look.

**Comment by ebourmalo** [comment]
Thank you. No big deal, it was mostly for the dead links in the documentation :)

**Comment by daffl** [comment]
Yes, thank you for pointing that out! I can fix the link but I'd rather then not have a broken example.

**Comment by ebourmalo** [comment]
Same case for the link `API documentation`. Its points out to `http://feathersjs.com/api/` instead of `http://feathersjs.com/docs` :)

**Comment by ebourmalo** [comment]
Is there any repo for the official documentation on the website? I couldn't find it. I could make some PRs as well for fixing that :)

**Comment by daffl** [comment]
Yes, it's all in the gh-pages branch of this repository (https://github.com/feathersjs/feathers/tree/gh-pages) and runs with the standard [Jekyll](http://jekyllrb.com/) setup.

**Comment by daffl** [comment]
I moved the example over to gh-pages so the link should work now. I still don't think it works right but maybe it'll encourage one of the many Angular experts to look into fixing it. Closing this issue though.
