### ISSUE TITLE
How using settings from ./config/production.json?

### ISSUE THREAD

**Issue by tolyanor** [feathersjs/feathers#1434]
I use node ./src for starting my feathersjs app. It always take configs from ./config/default.json I read [this documentation](https://docs.feathersjs.com/api/configuration.html) and not see how start using ./config/production.json in production
Thanks!

**Comment by KidkArolis** [comment]
Feather's is using https://github.com/lorenwest/node-config under the hood. See this section in particular https://github.com/lorenwest/node-config/wiki/Configuration-Files#file-load-order.

In a nutshell, it will load production file if env variable NODE_ENV is set to production.

**Comment by daffl** [comment]
There is also an example in the [@feathersjs/configuration API documentation](https://docs.feathersjs.com/api/configuration.html#example).

**Comment by yskkuwahara** [comment]
It seemed like written in a command of your scripts part of package.json like below,

```
  "scripts": {
    "start": "NODE_ENV=production npm run compile && node lib/",
```

You just start with `NODE_ENV=production npm run start`.
