### ISSUE TITLE
feathers - client - axios

### ISSUE THREAD

**Issue by doronnahum** [feathersjs/feathers#1435]
When i run feathers.logout()
and then try to log in,
the request includes the Authorization header

until I full reload the app

to fix it I run this
delete axios.defaults.headers.common["Authorization"]

**Comment by daffl** [comment]
This should not happen when using the REST Axios client as recommended. Are you setting that header somewhere yourself or using any other third party libraries?

**Comment by doronnahum** [comment]
i am using with axios in other place in the app, with axios.create() to create a different instance

**Comment by daffl** [comment]
I can't reproduce this. This looks like an error in your Axios configuration.
