### ISSUE TITLE
How to make route from service

### ISSUE THREAD

**Issue by garfewsab** [feathersjs/feathers#1444]
i can use route on service ?  or i should make function to check before 

i wanna  make verify password and verify email in same servie users 

ex 

route - >  update password  
route - > enable user veridify

in service("users")

**Comment by daffl** [comment]
It would be a separate service. It can be registered under a `/users/<somethingservice>`. Also see the FAQ [here](https://docs.feathersjs.com/faq/readme.html#how-do-i-create-custom-methods), [here](https://docs.feathersjs.com/faq/readme.html#how-do-i-do-nested-or-custom-routes) and [here](https://docs.feathersjs.com/faq/readme.html#how-can-i-do-custom-methods-like-findorcreate).
