### ISSUE TITLE
Question related to real time service

### ISSUE THREAD

**Issue by virus-pk** [feathersjs/feathers#1450]
I created a vue js front with feathers back and sequelize  (mysql 8.0 for windows) database, but the real problem is my **database gets data from a desktop application** and all I wanted to achieve with feathers is whenever data is updated on db feathers should update my vue component but it's not. Maybe because of the data is not getting created through feathers or I have it all wrong and feathers is not made to work like that. I'm confused 🤔🤐😴

**Comment by daffl** [comment]
Feathers does not directly observe the database for changes. In order to get real-time updates all calls have to go through the Feathers API server.
