### ISSUE TITLE
Old versions 4 of @feathersjs/commons and @feathersjs/transport-commons

### ISSUE THREAD

**Issue by vonagam** [feathersjs/feathers#1451]
When feathers packages switched to a single version mode with version four there were two packages which already had such version: [@feathersjs/commons with `4.0.0`](https://www.npmjs.com/package/@feathersjs/commons?activeTab=versions) and [@feathersjs/transport-commons with `4.2.1`](https://www.npmjs.com/package/@feathersjs/transport-commons?activeTab=versions).

It creates a problem, since a version range `^4.0.0-pre4` picks version `4.0.0` for commons and `4.2.1` for transport-commons. That's why, for example, in [`feathers-knex`](https://github.com/feathersjs-ecosystem/feathers-knex/blob/c5466b9417927edd90df53714010d63ce54d459c/package.json#L57) after a recent update of feathers dependencies `@feathersjs/commons` stayed on its previous version - `^4.0.0`. Or why feathers [`primus-client`](https://github.com/feathersjs/feathers/blob/2efa6468f9b93810b4cbc35e6ec0815dc1cb654f/packages/primus-client/package.json#L39), [`primus`](https://github.com/feathersjs/feathers/blob/2efa6468f9b93810b4cbc35e6ec0815dc1cb654f/packages/primus/package.json#L39), [`socketio-client`](https://github.com/feathersjs/feathers/blob/2efa6468f9b93810b4cbc35e6ec0815dc1cb654f/packages/socketio-client/package.json#L39), [`socketio`](https://github.com/feathersjs/feathers/blob/2efa6468f9b93810b4cbc35e6ec0815dc1cb654f/packages/socketio/package.json#L39) packages still use `transport-commons` of version `^4.2.1`. 

There have been changes to those packages since then (especially for [`transport-commons`](https://github.com/feathersjs/feathers/blob/2efa6468f9b93810b4cbc35e6ec0815dc1cb654f/packages/transport-commons/CHANGELOG.md)) and while in development of feathers packages you will get current code because lerna links folders, outside of such development users will get outdated packages.

Thoughts? It may not matter much if you plan to do v4 release really soon and start it with version `4.3.0`.

**Comment by daffl** [comment]
That totally makes sense, I was wondering why `@feathersjs/commons` was behaving odd.

Since those two packages are backwards compatible the global version number should start at 4.3.0. There may be more prereleases so I published everything as `4.3.0-pre.1`.

**Comment by vonagam** [comment]
Yeah, thanks for rapid response.

You also should update version of `@feathersjs/commons` in packages that you updated last week like `feathers-knex` (version range `^4.0.0` does not pick pre release, so greenkeeper will not help).

Also note: i was mistaken in my assumption that lerna will link those, so new code was not accessible to depending packages even in development.
