### ISSUE TITLE
Two identical client-server tests fails due to behavior of `app.listen()/server.close()`

### ISSUE THREAD

**Issue by IwoHerka** [feathersjs/feathers#1453]
### Steps to reproduce

Create fresh application or use https://github.com/feathersjs/feathers-chat.
Create two test suites with identical code (`test1.test.js`, `test2.test.js`):

```
const makeClient = require('./services/utils');
const app = require('../src/app');

const host = app.get('host');
const port = app.get('port');

// Assume user exists
const email = 'franz';
const password = 'testtest';

describe('foo', function () {
    let server;
    let client;

    before(async () => {
        server = app.listen(port);
        client = await makeClient(host, port, email, password);
    });

    after(() => {
        client.logout();
        server.close();
    });

    describe('bar', () => {
        it('baz', async () => {
            // Do anything
        });
    });
});
```
This code is taken from https://docs.feathersjs.com/guides/chat/testing.html#clientserver-testing.
`makeClient` is exactly the same as in documentation's sample.

Run tests with mocha via `npm run mocha`.

### Expected behavior

Two tests should pass without problems.

### Actual behavior

Second test timeouts:

```
  'users' service - client
    1) "before all" hook
    2) "after all" hook


  1 passing (3s)
  2 failing

  1) 'users' service - client
       "before all" hook:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/siegmeyer/Code/mathnet-server/test/services/users.test.js)
  

  2) 'users' service - client
       "after all" hook:
     TypeError: Cannot read property 'logout' of undefined
      at Context.after (test/services/users.test.js:19:16)
```

This leads me to believe that `app.listen()` and subsequent `server.close()` does not work as expected. Single test (single file) run in isolation works just fine.

What's more, if I give different port each test the tests will fail all the same.

**Comment by fmoessle** [comment]
Do your tests run sequential or in parallel?
