### ISSUE TITLE
[Question] - PostgreSQL Schema

### ISSUE THREAD

**Issue by jfajardo** [feathersjs/feathers#1456]
it is possible to develop a saas app with postgres schema with feathersjs
client1.example.com
client2.example.com
client3.example.com 

thanks

**Comment by jnardone** [comment]
That's a really broad question.  The answer is yes, but feathers is just part of an overall architecture for something like this.  

So the answer is "yes" but the full "so how would you do it" answer is too big a thing to answer in a forum like this.

**Comment by jfajardo** [comment]
> That's a really broad question. The answer is yes, but feathers is just part of an overall architecture for something like this.
> 
> So the answer is "yes" but the full "so how would you do it" answer is too big a thing to answer in a forum like this.

thanks, I understand that I must use many technologies for this

**Comment by daffl** [comment]
Here is links to the information of the pieces that are necessary to provide different database connections for a domain name:

- [feathers-sequelize](https://github.com/feathersjs-ecosystem/feathers-sequelize) has a `getModel(params)` method which [can be customized like any other adapter](https://docs.feathersjs.com/api/databases/common.html#classes-es6) according to the parameters, e.g. having a model repository per `params.domain`
- The domain name can be parsed and passed to the service `params` [in a custom middleware](https://docs.feathersjs.com/api/express.html#params)
