### ISSUE TITLE
proposal: "afterAll" hooks

### ISSUE THREAD

**Issue by jnardone** [feathersjs/feathers#1457]
The 'all' shortcut for hooks is great for brevity and for consolidating important logic in one place in various services.

BUT: sometimes you need things that are common to run before method-specific hooks, and sometimes you need it after.  Right now the `all` hooks run before `create`, `get`, etc.

Has any thought been given to an `afterAll` or a `finally`-named set of hooks that run for all methods AFTER the method-specific hooks have run?

My immediate use case is a set of things that filter data out of the result, but some of the after hooks need access to that information (to further enhance the result etc.).

**Comment by daffl** [comment]
`.hooks` can be called multiple times and will be chained. So

```js
app.service('service1').hooks(hookObject);
app.service('service1').hooks({
  after: { all: [ afterAllHook1 ] }
});
```

Would add the `afterAllHook1` after all the ones registered in `hookObject`.

**Comment by jnardone** [comment]
oh duh.  thanks.
