### ISSUE TITLE
service  not working loads forever  and returns an error "This page isn’t working empty response"

### ISSUE THREAD

**Issue by themcmaneh** [feathersjs/feathers#1460]
### Steps to reproduce

I check this answer but it didn't help
  https://github.com/feathersjs/feathers/issues/917

I deployed a feathers backend on an ec2 instance on port 3000 it worked the first day. but later when I try accessing it it load forever and returns and error. But if I try typing myIp:3000/anything which is not registered as a service I get a "404 Page Not Found" which shows that feathers is running but when I try something like myIp:3000/cards which is a service, it loads forever and returns "This page isn’t working" Locally everything works fine. I don't know what goes wrong after hosting on aws ec2 instance.

 
### Expected behavior
The expected behavior is that  when i do  myIp:3000/cards, it should load a JSON file or show [ ] which means the file is empty

### Actual behavior
The actual behavior when i do myIp:3000/cards it loads forever  and returns "This page isn’t working" 

**Module versions** (especially the part that's not working):
feathers-versions@0.2.1
service

**NodeJS version**:
v8.11.3

**Operating System**:
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

**Browser Version**:
Every Browser

example service 

       // Initializes the `providers` service on path `/providers`
       const createService = require('feathers-mongoose');
      const createModel = require('../../models/providers.model');
      const hooks = require('./providers.hooks');

      module.exports = function (app) {
      const Model = createModel(app);
      const paginate = app.get('paginate');

      const options = {
         Model
         //paginate
      };

       // Initialize our service with any options it requires
      app.use('/providers', createService(options));

      // Get our initialized service so that we can register hooks
      const service = app.service('providers');

      service.hooks(hooks);
      };

        const publications = require('./publications/publications.service.js');
       const cards = require('./cards/cards.service.js');
       const uploads = require('./uploads/uploads.service.js');
       const providers = require('./providers/providers.service.js');
     // eslint-disable-next-line no-unused-vars
       module.exports = function (app) {
       app.configure(publications);
       app.configure(cards);
       app.configure(uploads);
       app.configure(providers);
     };

**Comment by daffl** [comment]
This is probably an EC instance configuration and not a Feathers issue. Check your logs and proxy etc. configuration.
