### ISSUE TITLE
React - Authentication - socketIO

### ISSUE THREAD

**Issue by THEJean-Kevin** [feathersjs/feathers#1461]
Hello, I create a react application and connect to feathersjs with socket io.

Actually I have a problem with authenticate with jwt's strategy. 
When I call `client.authenticate({strategy: 'jwt', accessToken: jwt })` from react, all hooks after authentication.hooks.authenticate(config.strategies) was call twice.

This produce only with react and socketIo, i haven't probleme with postman and fetch react method.

<details>
  <summary>authenticate.js (featherjs)</summary>

  ```javascript
  const authentication = require('@feathersjs/authentication');
const jwt = require('@feathersjs/authentication-jwt');
const local = require('@feathersjs/authentication-local');

async function test(context){
  console.log("TEST authentication")
  return context
}

module.exports = function (app) {
  const config = app.get('authentication');

  // Set up authentication with the secret
  app.configure(authentication(config));
  app.configure(jwt());
  app.configure(local());

  // The `authentication` service is used to create a JWT.
  // The before `create` hook registers strategies that can be used
  // to create a new valid JWT (e.g. local or oauth2)
  app.service('authentication').hooks({
    before: {
      create: [
        authentication.hooks.authenticate(config.strategies),
        test
      ],
      remove: [
        authentication.hooks.authenticate('jwt')
      ]
    }
  });
};
  ```
</details>

<details>
  <summary>Init feathers and socket io connection (REACT)</summary>

  ```javascript
import feathers from 'feathers-client';
import io from 'socket.io-client';
const host = 'http://localhost:3030';
const socket = io(host);

export const app = feathers()
.configure(feathers.socketio(socket))
.configure(feathers.authentication({
    storage: window.localStorage
}));
  ```

</details>

<details>
  <summary>Function using jwt (REACT)</summary>

  ```javascript
import feathers from 'feathers-client';
import io from 'socket.io-client';
const host = 'http://localhost:3030';
const socket = io(host);

signInWithToken = () => {
        return new Promise((resolve, reject) => {
            console.log("Call function")

            /*fetch('http://localhost:3030/authentication',{
                method:'POST',
                headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json',
              },
              body: JSON.stringify({
                    "strategy": "jwt",
                    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6ImFjY2VzcyJ9.eyJ1c2VySWQiOjQwLCJpYXQiOjE1NjI5NDY3MzksImV4cCI6MTU2MzAzMzEzOSwiYXVkIjoiaHR0cHM6Ly95b3VyZG9tYWluLmNvbSIsImlzcyI6ImZlYXRoZXJzIiwic3ViIjoiYW5vbnltb3VzIiwianRpIjoiNzUzZTk0ZTUtOGJiNC00NjExLWExNzgtNWQxNGUyMjNiN2VmIn0.Bu8ZqVaLFLNRWj3jp4xIEjcERIoMmYhCwuUl5xKYtdY"
                })
            }).then(e=>console.log(e)).catch(e=>console.log(e))*/

            app.authenticate({
              "strategy": "jwt",
             "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6ImFjY2VzcyJ9.eyJ1c2VySWQiOjQwLCJpYXQiOjE1NjI5NDY3MzksImV4cCI6MTU2MzAzMzEzOSwiYXVkIjoiaHR0cHM6Ly95b3VyZG9tYWluLmNvbSIsImlzcyI6ImZlYXRoZXJzIiwic3ViIjoiYW5vbnltb3VzIiwianRpIjoiNzUzZTk0ZTUtOGJiNC00NjExLWExNzgtNWQxNGUyMjNiN2VmIn0.Bu8ZqVaLFLNRWj3jp4xIEjcERIoMmYhCwuUl5xKYtdY"
            }).catch((e)=>console.log(e))
        });
    };

export const app = feathers()
.configure(feathers.socketio(socket))
.configure(feathers.authentication({
    storage: window.localStorage
}));
  ```
</details>

Result with socketIO
https://i.imgur.com/0GMSqzw.png

Result with fetch method
https://i.imgur.com/eyZbJup.png

Furthermore if i switch test and authenticate hook test was called twice but not followed

 app.service('authentication').hooks({
    before: {
      create: [
        test,
        authentication.hooks.authenticate(config.strategies)
      ],
      remove: [
        authentication.hooks.authenticate('jwt')
      ]
    }
  });
};

Result
https://i.imgur.com/zazzCaf.png

To finish all this error occurs if I reload the react's page.
I haven't problem if I start feathersjs after react's page was started.

So i don't know if it's a probleme of feathers or react side.

Version used : 
"@feathersjs/authentication": "^2.1.16",
"@feathersjs/authentication-jwt": "^2.0.10",
"@feathersjs/authentication-local": "^1.2.9",
"@feathersjs/feathers": "^3.3.1",
 "@feathersjs/socketio": "^3.2.9",

"react": "16.8.5",
"feathers-client": "^2.4.0",
"socket.io-client": "^2.2.0",

**Comment by daffl** [comment]
In this version hooks do not run on socket authentication. It has been fixed in the new [authentication client](https://crow.docs.feathersjs.com/api/authentication/client.html#configuration) of Feathers v4. See the [Migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information on how to upgrade.
