### ISSUE TITLE
Easiest Way to apply schema (validation+population) to NeDB in feathers?

### ISSUE THREAD

**Issue by hammooooody** [feathersjs/feathers#1463]
Sorry for the noob question! 
I am using NeDB services with feathers and I would like to validate and/or populate data before going to the db. It would be just Perfect if it is similar to that of Mongoose's.
Mongoose schema sample:
```
const systems = new Schema({
      info: { type: Map },
      hardware_id: { type: String, default: "" },
      name: { type: String, default: "name" },
      comments: { type: Array, default: [] },
      isOnline: { type: Boolean },
    })

```
I did take a look at:
- [camo](https://github.com/scottwrobinson/camo) but I was not sure how to integrate it, as I wanted to keep things close to `@feathers/cli` generated code structure.
- [feathers-schema](https://github.com/BenZed/feathers-schema#readme) but I got this error 
 `Error: Cannot find module 'babel-runtime/helpers/asyncToGenerator'`

Any hint or advice is highly appreciated!

System configuration
@feathersjs/cli `v3.9.0`
package.JSON
```
"dependencies": {
    "@feathersjs/authentication": "^2.1.16",
    "@feathersjs/authentication-jwt": "^2.0.10",
    "@feathersjs/authentication-local": "^1.2.9",
    "@feathersjs/configuration": "^2.0.6",
    "@feathersjs/errors": "^3.3.6",
    "@feathersjs/express": "^1.3.1",
    "@feathersjs/feathers": "^3.3.1",
    "@feathersjs/socketio": "^3.2.9",
    "compression": "^1.7.4",
    "cors": "^2.8.5",
    "feathers-nedb": "^4.0.2",
    "helmet": "^3.18.0",
    "multer": "^1.4.1",
    "nedb": "^1.8.0",
    "serve-favicon": "^2.5.0",
    "winston": "^3.2.1"
  }
```

NodeJS version:
```
node v12.6.0
npm 6.9.0
```

Operating System:
```
Description:    Ubuntu 19.04
Release:        19.04
```

**Comment by daffl** [comment]
When choosing a non-ORM adapter this is entirely up to your discretion. Feathers hooks give you the flexibility to implement any schema validation mechanism you may want to choose with very little code.

One common approach is the [validateSchema hook](https://feathers-plus.github.io/v1/feathers-hooks-common/#validateschema) that uses JSON schema.

**Comment by hammooooody** [comment]
Thank you chief @daffl. Yes, I guess i'll resort to building my own hooks. Much appreesh!
