### ISSUE TITLE
How to handle SPA Routing + API

### ISSUE THREAD

**Issue by nodefish** [feathersjs/feathers#1465]
Starting with a CLI generated app, is there a best practice for serving an SPA from `/public` in a way that supports client-side routes? e.g. `example.com/users`, `example.com/profile` etc. would all need to hit `index.html` (which contains the SPA bundle). Currently, I'm getting 404s with such routes, for obvious reasons, since Feathers.js expects each sub-route to be a service.

Should I just implement some kind of prefixing for services? I saw this: https://github.com/feathersjs/feathers/issues/579 but it feels like going against the grain a bit.

**Comment by daffl** [comment]
This is up to you. Usually the SPA and API are running on different domains or paths but as long as your SPA and API routes don't conflict you can also add a catch-all middleware instead of the `notFound` handler that serves the `index.html` which then does the routing.

**Comment by nodefish** [comment]
Thank you, that makes sense. I thought some "native" (for lack of a better word) feathers approach might have been eluding me, but what you've suggested is perfect.

**Comment by bilicio** [comment]
if you got here in this thread and wants to enable reactsjs routes with feathersjs just put this code :
```
app.get('*', (req, res) => {
  res.sendFile( path.resolve('public/index.html') );
});
```
before `app.use(notFound())`

**Comment by oujunhao** [comment]
How would this work in v5 with Koa? I'd like to serve an SPA using react router

**Comment by howlettt** [comment]
I got it to work for Koa using the following
```
app.use(async (ctx, next) => {
  return await serveStatic(app.get("public"))(
    Object.assign(ctx, { path: "index.html" }),
    next,
  );
});
```
