### ISSUE TITLE
Authenticate without failure on certain routes

### ISSUE THREAD

**Issue by domagoj-orioly** [feathersjs/feathers#1466]
How can I check if a user is authenticated without causing my application to explode if the user isn't authenticated?

For example, I want to see if I need to render certain bits of template or not, depending if the user is authenticated or not. Currently, if I use authenticate middleware on a route or group of routes,  I get traditional unauthorized error. I just want to do something like this

```
router.use((req, res, next) {
const authentication = ???????
req.user = authentication.authenticateUserWithJWTAndReturnHimJustLikeYouDoWhenUsedAsMiddleware;  //
next();
})
```

Standard approach works (when using authenticate.express middleware), i.e. if cookie exists, user is loaded and granted access but if cookie doesn't exist, it returns 401. 

I have no idea how to get authentication service manually and authenticate user manually, without killing the access, just return him if token is alright and return null if it isn't. All official guides show how to use it as middleware, or if I'm mistaken, please direct me to one that can be used in my case.   

EDIT: the real excerpt

```
const express = require('@feathersjs/express');
const router = express.Router();
const { authenticate } = require('@feathersjs/authentication').express; // What to import?

router.use((req, res, next) => {
  let a = authenticate('jwt')(req, res); // How to use imported function?
  req.user = ''; assign the user, same way authenticate assigns it automatically on guarded routes
  next(); // Pass on to next middleware, in each check if user exists
});
```

EDIT2: Current attempt

```
const express = require('@feathersjs/express');
const router = express.Router();
const { authenticate } = require('@feathersjs/authentication').express;

router.use((req, res, next) => {
  authenticate('jwt')(req, res, next);
  next();
});

router.get('', (req, res) => {
  res.render('homepage/index.html.njk');
});

```

Now this manages to authenticate used but the request object used in subsequent isn't the same one, i.e. doesn't contain `req.user` or `req.feathers` which is populated by `authenticate('jwt')`.

EDIT: Successful attempt
```
const express = require('@feathersjs/express');
const router = express.Router();

router.use(async (req, res, next) => {
  const { userId } = await req.app.passport.verifyJWT(req.cookies.feather, { secret: req.app.get('authentication').secret});
  req.user = await req.app.service('api/users').get(userId);
  next();
});

router.get('', (req, res) => {
  // I now have access to req.user which can be undefined or user object
  res.render('homepage/index.html.njk');
});
```

My question now is, is there any official way to achieve this? Or should be? I noticed `allowUnauthorized` property for `authenticate.hooks`, is that something similar?

**Comment by jnardone** [comment]
We wrapped the authenticate hook in another hook e.g. (this is for v4 but syntax is mostly the same for v3)

```
const { authenticate } = require('@feathersjs/authentication');
const verify = authenticate('jwt');

module.exports = async hook => {
  try {
    return await verify(hook);
  } catch (err) {
    // you can check what error happens here if you want
    return hook;
  }
};
```

If you use this hook as  your `before` hook it will attempt to verify the auth, but if it fails it keeps going.  You'll either end up with the new context which includes `authenticated: true` or you'll have the original context which doesn't (and if you're using v4, you'll have the user in the authenticated case).
