### ISSUE TITLE
Feathers not passing along google oauth profile information

### ISSUE THREAD

**Issue by nvitaterna** [feathersjs/feathers#1467]
### Steps to reproduce
I've setup a very basic application via the generator with a users service using memory and google oauth. Added credentials and scope under the oauth section in the config:
```
"google": {
  "key": "****",
  "secret": "*",
  "scope": ["profile", "email", "openid"]
}
```
Also tried different combinations of scope with no luck.

### Expected behavior
Should be able to access user profile information (email, etc) in the user before create hook.

### Actual behavior
The only data accessible in the user create hook is `googleId`:
```
{
  "data": {
    googleId: '*****'
  }
}
```

### System configuration

**Module versions**: `4.3.0-pre.1` (originally had `4.0.0-pre.3` and it wasn't working either)

**NodeJS version**: `10.16.0`

When I originally tried this with my actual application I'm working on (with input validation), the error shows that it is getting the profile information from google:
```
{
    "type": "FeathersError",
    "name": "GeneralError",
    "code": 500,
    "className": "general-error",
    "errors": {},
    "hook": {
        "type": "before",
        "method": "create",
        "path": "authentication",
        "params": {
            "authStrategies": [
                "google"
            ],
            "authentication": null
        },
        "data": {
            "strategy": "google",
            "id_token": {
                "header": {
                    "alg": "RS256",
                    "kid": "*****",
                    "typ": "JWT"
                },
                "payload": {
                    "iss": "accounts.google.com",
                    "azp": "*****",
                    "aud": "*****",
                    "sub": "*****",
                    "email": "*****",
                    "email_verified": true,
                    "at_hash": "*****",
                    "nonce": "*****",
                    "iat": 1563473531,
                    "exp": 1563477131
                },
                "signature": "*****"
            },
            "access_token": "*****",
            "raw": {
                "access_token": "*****",
                "expires_in": 3600,
                "scope": "https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email openid",
                "token_type": "Bearer",
                "id_token": "*****"
            }
        }
    }
}
```

**Comment by daffl** [comment]
This is what [customizing the oAuth strategy](https://crow.docs.feathersjs.com/api/authentication/oauth.html#customization) is used for, specifically overriding [getEntityData](https://crow.docs.feathersjs.com/api/authentication/oauth.html#getentitydata-profile-entity-params) which gets the entire profile and should return the data that you want to include in the user object.

**Comment by nvitaterna** [comment]
Thank you! Recently started working with v4 and must have skimmed over that too quickly.
