### ISSUE TITLE
How to connect a Python Socket.io client to a service ?

### ISSUE THREAD

**Issue by jogiji** [feathersjs/feathers#1471]
My Requirement is that I connect my Python based IOT device to the feathersjs server and maintain a realtime connection between them. Earlier we used to rely on Firebase which worked most of the time but failed in on premise/ offline first scenario.

Can someone guide me with regards to Socket.io connection to a FeathersJS service using Python.

The library that I am using is this https://python-socketio.readthedocs.io/en/latest/client.html

**Comment by daffl** [comment]
As long as the library supports acknowledgement callback, usage is the same as the one documented in the [direct Socket.io connection](https://docs.feathersjs.com/api/client/socketio.html#direct-connection) API.

**Comment by jogiji** [comment]
Hi, I am a noob to understand socket.io concepts properly..
The way its mentioned in the direct connection docs. I don't seem to find that kind of connectivity option in the python library.
Assuming that any socket.io client can connect to feathers.js server.. I have hit a dead end in python library.
Basically I am not able to find any method where i can set the path of service while emitting.
Is Namespace === service ??

**Comment by jogiji** [comment]
Never mind I figured it out.
Basically we need to provide the service name along with method name so it would be like this :
client.emit('servicename::methodname',<your data>) in python

**Comment by daffl** [comment]
That is the legacy format, if possible the new format like `client.emit('methodname', 'servicename', {})` should be used.

**Comment by jogiji** [comment]
The problem is python library doesn't support the new format I guess.. 
I am not able to find any such documentation which suggests so..

**Comment by jogiji** [comment]
Fyi this solution provided by the python client author works :

Try client.emit('methodname', ('servicename', {})).
