### ISSUE TITLE
V4 CROW - Recipe: Express middleware (SSR) 

### ISSUE THREAD

**Issue by alvise** [feathersjs/feathers#1472]
In the previous version (v3) I was using the cookie to authenticate my express routes and generate personalized pages based on the user permissions.

Now I am trying to do something similar in v4 but obviously I have no user info in express routes.

Should I manually set a cookie after authentication or I am missing something?

**Comment by abecks** [comment]
I am also looking for the v4 documentation regarding using cookies. Maybe @daffl could point us in the right direction?

**Comment by alvise** [comment]
I don't know if it is the best way but i ended adding **this to my app.js**

`app.use((req, res, next) => {
  if(req.cookies && req.cookies['myCookie']){
    req.headers.authorization = 'Bearer ' + req.cookies['tools.datatv.it'];    
  }
  next();
});`

and something like this in **my middleware:**

`module.exports = function ( app ) {  
  app.set( 'view engine', 'ejs' );

  // LOGOUT For the logout route we remove the JWT from the cookie
  app.get( '/logout', cookieParser(), ( req, res ) => {
    res.clearCookie( 'myCookie' );
    res.redirect( '/login' );
  } );

  // PAGE HOME
  app.get( '/home', authenticate ('jwt'), checkPermissions( 'Home Page' ), ( req, res ) => {
    const { user, permittedPages } = req;
    const thisPage = { nome: 'Home Page' };
    res.render( 'home', { user, permittedPages, thisPage, mySite, myExpiration } );
  } );
 
};`

**Comment by daffl** [comment]
This has now been added to https://docs.feathersjs.com/cookbook/express/view-engine.html
