### ISSUE TITLE
Question: can I generate my own IDs

### ISSUE THREAD

**Issue by svendeckers** [feathersjs/feathers#1477]
Sorry if this is the wrong place to ask.
I would like to customize the way IDs are generated when a service's CREATE method is called. 

I haven't found anything on Google that relates to this, apart from something on Feathers-Mongoose, but I'm using NeDB.

Thanks in advance for any advice!

**Comment by daffl** [comment]
In NeDB you can just set the `_id` field to your generated id using any id generator (e.g. [shortid](https://github.com/dylang/shortid)).

**Comment by svendeckers** [comment]
You mean in a before-hook, just set `_id` to any generated value?

**Comment by daffl** [comment]
Any data with `{ _id: 'someid' }` will set the `_id` to `_someid`. That can come from the client or be set in a hook.

**Comment by svendeckers** [comment]
Got it, thank you!
