### ISSUE TITLE
"error: Timeout of 5000ms exceeded calling $METHOD on $SERVICE"

### ISSUE THREAD

**Issue by cfm** [feathersjs/feathers#1483]
### Steps to reproduce

As [suggested](https://github.com/feathers-plus/feathers-vuex/issues/188#issuecomment-51) by @marshallswain, this ticket offers a reproduction of the problem originally reported in feathers-plus/feathers-vuex#188, #1239, etc.

    git clone git@github.com:cfm/feathers-1483.git
    cd feathers-1483
    npm i
    npm run dev

Now open <http://localhost:3030/admin> and watch the console.

### Expected behavior

Debug output for `app.service('counters').find()`.

### Actual behavior

    error: Timeout of 5000ms exceeded calling find on counters {"type":"FeathersError","name":"Timeout","code":408,"className":"timeout","data":{"timeout":5000,"method":"find","path":"counters"},"errors":{}

—although the request succeeds insofar as the default `feathers-memory` empty result is returned.

For comparison:

1. restart `npm run dev`;
2. open (via `file://`) [`test.html`][test];
3. observe no timeouts via a direct Socket.IO connection.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

    ozymandias:ex cfm$ feathers --version
    3.9.0

Otherwise see [`package.json`][package].

**NodeJS version**:

    ozymandias:ex cfm$ node --version
    v12.6.0

**Operating System**:

    ozymandias:ex cfm$ uname -a
    Darwin ozymandias.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64

**Browser Version**:  Chrome 75.0.3770.142

**Module Loader**:  see [`package.json`][package]

[package]: https://github.com/cfm/feathers-1483/blob/master/package.json
[test]: https://github.com/cfm/feathers-1483/blob/master/test.html

**Comment by daffl** [comment]
I haven't had time to look at the example but the error message is definitely coming from an old Feathers client version so the first thing that should be done is updating the client to the latest official version.

**Comment by cfm** [comment]
@daffl, thanks for your suggestion.  I'm very open to this possibility,
as a newcomer to this ecosystem.  But I've done my best to rule out this
case in this webpack-based configuration (see
[log](https://gist.github.com/cfm/879019a38995b39fa500b85782decc3d)).
I've also tried switching the client to a webpacked
`@feathersjs/client@3.7.8`, with the same result.  Of note, the request
*succeeds* despite this error message, as does not appear to be the case
in other reports of a mismatch in version between server and client.

Also, this error message *appears* to still be
[present](https://github.com/feathersjs/feathers/blob/master/packages/transport-commons/src/client.ts#L83)
in `@feathersjs/transport-commons`.

I appreciate your time and assistance.

**Comment by daffl** [comment]
First of all, thank you for providing a repository to reproduce. Unfortunately I still can't tell what exactly is going on. It looks like the server side rendering is doing something weird with the socket connection (people were having issues with that before).

It is usually a good idea to switch to REST in an SSR environment which seems to work. I don't think there is anything here that can be done on the Feathers side since its Websocket implementation doesn't really do anything special.

**Comment by cfm** [comment]
@daffl, your instinct is spot on.  The errors disappear with Nuxt.js set
to {mode: 'spa'}.

For my purposes here, the Socket.IO transport is more important than
server-side rendering, so this is an adequate resolution.  I'll leave
it at that, since I don't have any insight into whether this suggests
an incompatibility or an outright bug in Nuxt.js.

Many thanks for taking a look and offering this diagnosis.
