### ISSUE TITLE
how to cancel callback after hook?

### ISSUE THREAD

**Issue by SeaDog505** [feathersjs/feathers#1484]
I have a service named classes. This service update selected classes and their pupils. After updated the classes this service return a callback and I want this it was but in this service I have too another service sound like as pupils which update an pupils of this class and I need stop the callback from this service. How can I do it?

Below I show what I mean:

**/src/service/classes/classes.hook.js**

    after: {
    update: [
        function(hook){
           hook.app.service('classes').patch(null, data, params).then(result => {  

          /* Here I want a callback */

           hook.app.service('pupils').patch(null, data, params);

          /* Here I want the service patched an pupils but
             I don't want return a callback for event/listener but only here
             (in this file classes.hook.js) */
       });
        }
    ]
    }

**Comment by jnardone** [comment]
so you're calling `patch` on the same service you're calling `update`?  

I'm not quite understanding your question though.  Especially "Here I want the service patched an pupils but I don't want return a callback for event/listener but only here".  Can you clarify?

**Comment by SeaDog505** [comment]
OK I'll try clarify. I have more services but I've conflict with two services. In first service I use patch  method for "pupils" documents. All is fine. A second service update an selected documents named "classes" but when I use update method in classes service in hook after for this service I  call patch method too for documents named "pupils". In another javascript file I have created callback function like:

socket.on('classes updated', result => {
});
socket.on('pupils patched', ', result => {
});

And now I would like to when I use patch method in pupils service a callback is return but when I use update classes service where in used is pupils service with patch method too I want the callback be disable. I don't want receive a callback. I want receive a callback only from updated classes service.

**Comment by daffl** [comment]
This is what [channels](https://docs.feathersjs.com/api/channels.html) are for. A channel publisher also gets the hook context, so if you don't want to publish an event you can add a flag to `params` in the nested call and check for it.

```js
after: {
  update: [
    async function(hook){
       const result = await hook.app.service('classes').patch(null, data, params);

      /* Here I want a callback */

      await hook.app.service('pupils').patch(null, data, {
        ...params,
        publishEvent: false
      });
    }
  ]
}
```

Then in `channels.js`

```js
app.service('pupils').publish((data, context) => {
  if (context.params.publishEvent !== false) {
    return app.channel('something');
  }
});
```

**Comment by SeaDog505** [comment]
thank's daffI.
