### ISSUE TITLE
Feathers client not returning all join data in Many:Many relationship

### ISSUE THREAD

**Issue by markdid** [feathersjs/feathers#1485]
I have a table members and a table careers in sequelize. Then I have a join table members-careers that takes the member id and career id in a many to many relationship. I'm getting some weird behavior. If I query all the members the career data shows up normally - [{"name": "Lawyer"}] etc but i'm trying to query so that only members that are lawyers or judges show up in my results:
(Done in react feathers/client by the way)
```js
const member = client.service('members');
Promise.all([
            member.find({
                query: {
                    $sort: {created_at: 1 },
                    $limit: 25,
                    careers: {
                       $in: ["Lawyer"]
                 };
            })
        ])
```
This works correctly, as in the correct members with the mentioned careers are returned, however the data is not being returned correctly.
In the case where a member is both a Lawyer and a judge, if I only query for Lawyer, that member is returned but his Judge career is not included in the results.

expected: 
```
{ "id":"example_id","email":"ex@email","given_name":"exname","created_at":"2019-07-31T17:39:08.194Z","updated_at":"2019-07-31T17:39:08.194Z","languages":[],"careers":[{"name":"Lawyer"}, {"name":"Judge"}] }
```

actual: 
```
{ "id":"example_id","email":"ex@email","given_name":"exname","created_at":"2019-07-31T17:39:08.194Z","updated_at":"2019-07-31T17:39:08.194Z","languages":[],"careers":[{"name":"Lawyer"}] }
```

Though if I leave out the career query altogether, both lawyer and judge careers are included correctly as expected.

I assume this is a bug in feathers client but i'm probably missing something in the backend configuration possibly. Any help appreciated, thanks.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working): "@feathersjs/client": "^3.7.8"

**NodeJS version**: 12.4.0

**React Version**: 16.8.6

**Module Loader**: npm

**Comment by daffl** [comment]
I don't think the `$in` query works the way you seem to expect. `$in` takes an array of elements of the same primitive type (string, number, boolean) and returns all matching entries. So `career: { $in: [ 'lawyer', 'accountant' ] }` would return any member with `career: "lawyer"` and `career: "accountant"`.

What you are trying to do is a more database specific query and depends on the database adapter you are using.

**Comment by markdid** [comment]
@daffl Oh my mistake.. But that's even more confusing because like I said, It does work as expected, i'm just not getting all the joined data back. Is this a problem with sequelize then?
Thanks for the quick reply

**Comment by daffl** [comment]
Potentially. Try to [test the query in isolation](https://github.com/feathersjs-ecosystem/feathers-sequelize#testing-sequelize-queries-in-isolation) to see if it can be reproduced (side note, in the latest version the Feathers query parameters have to be replaced with their [Sequelize operators](https://sequelize.org/master/manual/querying.html#operators))

**Comment by markdid** [comment]
Sorry to take your time but since the data is being joined in feathers, If I run the query in isolation like you said, it just tells me column member.career does not exist since it has not been combined by the feathers hooks.
I feel like the answer is simple, i'm just too much of a noob. ㅠㅠ

Also not sure I understand your last note, how can I use the sequelize operators with feathers/client?

**Comment by markdid** [comment]
Also the documentation about $in isn't very clear, per the docs
```js
// Find all messages in room 2 or 5
app.service('messages').find({
  query: {
    roomId: {
      $in: [ 2, 5 ]
    }
  }
});```
To me it sounds like this query should return any messages with roomId = 2 || roomId = 5, but you said it is an "and" operation?

**Comment by daffl** [comment]
That's how it works but your examples is showing your `careers` data to be `"careers":[{"name":"Lawyer"}, {"name":"Judge"}]` which are actual nested objects so I'm not quite sure how you were expecting the `careers: { $in: ["Lawyer"] }` query to work.

As mentioned, querying nested objects is quite different per DB and querying relationships in Sequelize needs to do be done by setting [params.sequelize](https://github.com/feathersjs-ecosystem/feathers-sequelize#paramssequelize) with the includes setting up the query.

**Comment by markdid** [comment]
Ah I see what you mean. Originally I thought I was going to need to query the nested object differently but since I tried it this way and it worked I assumed it was the correct way. :/ It must just be working due to some weird exception I guess. 
At this point i'm lost though. It's not clear how to set params.sequelize from the frontend (I understand the client only sends params.query). Maybe If you could point me in the right direction where this is explained I could find my way.
Thanks again

**Comment by edwardsmarkf** [comment]
i keep wondering what a many-many relationship looks like in feathers.  it
seems to me they always resolve into a many--->one<---many relationship,
even if the middle table is nothing but a set of indexes.

Thank you,

Mark Edwards

**Comment by markdid** [comment]
@edwardsmarkf  Right that's how I have mine setup

**Comment by edwardsmarkf** [comment]
i will be curious to know what you finally come up with.  i am using a view
as a feathers-service which works, but is not optimum.  another solution is
to use a raw SQL query as a service, but that approach has its own set of
issues.  please keep me informed.

Thank you,

Mark Edwards
