### ISSUE TITLE
Just a question: v4.0 When will it be released?

### ISSUE THREAD

**Issue by harrytang** [feathersjs/feathers#1486]
Just a question: v4.0 When will it be released?

**Comment by loongmxbt** [comment]
Can't wait to use the feathers crow!

**Comment by edwardsmarkf** [comment]
nothing is stopping you now - we are going LIVE with crow - from what i can
see there are no issues, but our new application is probably pretty
simplistic.

Thank you,

Mark Edwards

**Comment by daffl** [comment]
Indeed. You can install the versions `@pre` or use it with `@feathersjs/cli@pre` and read the [new docs](https://crow.docs.feathersjs.com/) - the docs and website are actually what is still getting some work. The guide is being overhauled to be more concise and there also are a few more cookbook recipes that should be added. It will hopefully get wrapped up in the next two weeks.
