### ISSUE TITLE
GraphQL Support?

### ISSUE THREAD

**Issue by kwcto** [feathersjs/feathers#149]
I'm still learning GraphQL (https://learngraphql.com) but my first impression is that the support for multiple/batched reads/writes and "selectable" schema would be powerful when combined with the rest of the feathers workflow.  Thoughts?

**Comment by daffl** [comment]
I read the [introductory post](https://facebook.github.io/react/blog/2015/05/01/graphql-introduction.html) a while ago and just scrolled through [the GraphQL spec](https://facebook.github.io/graphql/) and I think it makes sense to explore this option a little more. 

Currently Feathers support query batching through [feathers-batch](https://github.com/feathersjs/feathers-batch) and all 1.0 db adapters support field querying through the `$select` special query param (see e.g. [here for feathers-nedb](https://github.com/feathersjs/feathers-nedb#select)). We are also working on nested services in [feathers-associations](https://github.com/feathersjs/feathers-associations) and schemas can be easily implemented via [feathers-hooks](https://github.com/feathersjs/feathers-hooks).

It seems like those are doing a lot of the things that - at least from what I understand - GraphQL covers as well. It almost looks as if a GraphQL adapter would just consolidate all those separate features into a unified interface (the full spec looks like a bit to work through ;).

Once you learned a little more maybe you can help answer some of the questions that came to my mind:

- How does the Feathers service model tie into GraphQL?
- Can the existing plugins be combined to provide this functionality?
- What is missing?
- Where are the potential implementation challenges?
- What's the deal with https://github.com/graphql/graphql-js? I don't see any tests and if it is a reference client implementation I am not sure how you can verify that you built a server that implements the spec.

**Comment by daffl** [comment]
Also, besides the current real-time events (which might potentially be hard to correlate with your GraphQL query results), could we have such thing as real-time GraphQL queries? How could that look like?

**Comment by daffl** [comment]
In fact, this may be solved with adding support for Waterline because we can just use https://github.com/wistityhq/waterline-graphql. /cc @ekryski

**Comment by kwcto** [comment]
Haven't had a chance to experiment with GraphQL much more but I'm glad there may be a simple way to add support.  Makes evangelizing Feathers that much easier :+1:

**Comment by ekryski** [comment]
We're making some progress here. Once https://github.com/feathersjs/feathers-waterline is complete (still in the works) you will be able to use https://github.com/wistityhq/waterline-graphql and should make using graphql rather trivial.

We'll probably just need to document an example.

**Comment by daffl** [comment]
The first version of [feathers-waterline](https://github.com/feathersjs/feathers-waterline) has been published which should allow using the Waterline GraphQL module. I haven't tested it yet but if there are any issues with the integration it can be reported in the Waterline adapter.

**Comment by andrejunges** [comment]
https://twitter.com/feathersjs/status/753312499882201088

http://halcyonlabs.io/blog/2016/07/13/eagle-has-landed/

**Comment by ekryski** [comment]
Thanks for adding that @andrejunges! ^ that is the recommended way so far. I believe the repo is a bit more up to date. https://github.com/swarthout/feathers-apollo

**Comment by zusamann** [comment]
How about being able to use other middlewares? something like this is pretty great. https://github.com/calebmer/postgraphql

Though as the name suggests it only works with postgres.

I'm pretty new to feathers, but would love to be able to write a `feathers-postgraphql` service for a middleware like this if possible.

**Comment by thelaith** [comment]
Status on @subodhpareek18 suggestion - would love to know if a decision has been made, since it's been a year.

**Comment by eddyystop** [comment]
One option is the docs for the feathers-plus graphql adapter will be available within a month. A repo to help generate resolvers will be available the month after that.
