### ISSUE TITLE
Linking accounts with `feathers-jwt` cookie is not working?

### ISSUE THREAD

**Issue by orszaczky** [feathersjs/feathers#1491]
I see this answer at the bottom of every similar and closed issue:

With cookies enabled and the existing JWT set as `feathers-jwt` in the cookie, account linking is now possible with `@feathersjs/authentication-jwt@^2.0.0` and `@feathersjs/authentication-oauth@^1.2.0`.

_Originally posted by @daffl in https://github.com/feathersjs/feathers/issues/661#issuecomment-416627857_

I have `@feathersjs/authentication-jwt@^2.0.7` and `@feathersjs/authentication-oauth2@^1.2.5` installed, cookies are enabled, and existing JWT is set as `feathers-jwt`. In the oauth2 verifier I found the following part:

```
// Check request object for an existing entity
if (req && req[options.entity]) {
  existing = req[options.entity];
}

// Check the request that came from a hook for an existing entity
if (!existing && req && req.params && req.params[options.entity]) {
  existing = req.params[options.entity];
}
```

options.entity is `'user'` and when I log out the values, req.user is always undefined and req.params is always an empty object.

Am I missing something? Can it be that the cookies are not being read?
Should these be set automatically if the cookie is present (if yes, then where does it get set)?
Or should I set it manually (if yes, then how)?

**Comment by hiei189** [comment]
@orszaczky have you been able to work around this? I need to access the authenticated user object inside the verifier but, as you said, is always undefined or {}.

**Comment by daffl** [comment]
This is fixed in Feathers v4 which allows [account linking without a cookie](https://crow.docs.feathersjs.com/api/authentication/oauth.html#account-linking). See the [migration guide](https://crow.docs.feathersjs.com/guides/migrating.html) for more information.
