### ISSUE TITLE
[question] - Docker support?

### ISSUE THREAD

**Issue by philippefutureboy** [feathersjs/feathers#1493]
Hello all 👋

Quick question for the feathersjs team. Is there any official docker image or any documentation on how to deploy using docker? I couldn't easily find anything regarding the subject in the documentation, so I figured it be better that I ask the question here :)
My motto when it comes to doc is _if it can't be found easily, either it doesn't exist or the docs need some refactoring_ :P

So again, is there any official docker image or any documentation on how to deploy using docker?

Thanks a lot for your answer 🚀

Have a great day!

Cheers,

Phil

**Comment by daffl** [comment]
Any Feathers application is just a normal NodeJS app, so the [main tutorial on how to Dockerize a Node.js application](https://nodejs.org/en/docs/guides/nodejs-docker-webapp/) has all the information you should need.

**Comment by philippefutureboy** [comment]
Great! Thanks for the info. I'd suggest including it under a page of feathers.js, a bit like [Cube.js's Deployment page](https://cube.dev/docs/deployment) :)

**Comment by fmoessle** [comment]
I would love to create an easy example for this. As @daffl mentioned, this is nothing feathers specific but related to Node.js.

**Comment by daffl** [comment]
Closed via https://github.com/feathersjs/docs/pull/1332
