### ISSUE TITLE
[question] How do I query an array with nedb adapter???

### ISSUE THREAD

**Issue by JAB-Freeware** [feathersjs/feathers#1499]
Here is an example datastore

```
  {
    "Participants": [
      {
        "ParticipantID": "peaches",
        "Amount": 10,
        "ParentUser": "11111111"
      },
      {
        "ParticipantID": "apples",
        "Amount": 20,
        "ParentUser": "22222222"
      }
    ],
    "BillingName": "test person",
    "Last4": "****",
    "Date": "2019-08-13T20:25:19.197Z",
    "_id": "IYboK0SeNIvbf7O0"
  },
  {
    "Participants": [
      {
        "ParticipantID": "pears",
        "Amount": 10,
        "ParentUser": "11111111"
      },
      {
        "ParticipantID": "bananas",
        "Amount": 20,
        "ParentUser": "22222222"
      }
    ],
    "BillingName": "a different person",
    "Last4": "****",
    "Date": "2019-08-13T20:25:19.197Z",
    "_id": "ASDboK0SeNIvbf7O0"
  }
```

What I want is to query the database for documents that contain a specific ParticipantID in the Participants array.

For example querying for "peaches" or "apples" would return the first document. "pears" or "bananas" would return the second.

My issue is I cant figure out a way to basically do .includes() on an array in featherjs/neDB.

I tried simplifying it to a simple array of numbers to avoid the complexity of the nested object, but I just cant figure out how to search an array. $in operator receives an array as input and checks the values against the database. Its the opposite of what I need.

I am so frustrated right now. I apologize if this is not the correct place or "this is an NeDB repo question" but  but I already been over their documentation and repo issues. Their documentations gives an example:

```
// Use the dot-notation to navigate arrays of subdocuments
db.find({ "completeData.planets.name": "Mars" }, function (err, docs) {
  // docs contains document 5
});
```
This doesn't work in feathers query. I tried `$contains` from a solution to another issue posted here. That throws a feathers undefined error, so I feel like this related to featherjs. I would be grateful for any help, I have spent hours on this and have gotten nowhere.

**Comment by JAB-Freeware** [comment]
I finally got it!!!

This: https://github.com/feathersjs-ecosystem/feathers-nedb pointed me to the whitelist field. Add $elemMatch to that list. NeDB query parameters do not just work out of the box. You must add any you want to use to the whitelist.

Then for the query do this:

`{ Participants: { $elemMatch: { ParticipantID: 'aRqY513oTHUHfc2W'} } }`
For example. elemMatch documented here. https://github.com/louischatriot/nedb#array-fields

I'm so stupid. Hopefully this saves someone time.

**Comment by daffl** [comment]
Thanks for sharing! The whitelist option will show up in the main docs soon, it's definitely a little hidden at the moment.
