### ISSUE TITLE
How to authorization by socket.io with client html without nodeJS

### ISSUE THREAD

**Issue by Happybe** [feathersjs/feathers#1500]
Here example 

`<script type="text/javascript" src="//unpkg.com/socket.io-client@1.7.3/dist/socket.io.js"></script>`
`<script type="text/javascript" src="//unpkg.com/@feathersjs/client@^3.0.0/dist/feathers.js"></script>`

>let io = socket.io();
>let client = feathers();

>client.configure(feathers.socketio(socket));

I would like authentication with JWT Just verify.

Like a call RestFul  headers { authorization : {$JWT} }

**Comment by daffl** [comment]
This is documented [in the guide](https://docs.feathersjs.com/guides/chat/frontend.html) and [the API here](https://docs.feathersjs.com/api/authentication/client.html)

**Comment by Happybe** [comment]
Thanks, 
> This is documented [in the guide](https://docs.feathersjs.com/guides/chat/frontend.html) and [the API here](https://docs.feathersjs.com/api/authentication/client.html)

Ok, I don't used authentication, Just I create middleware and verify JWT with `jsonwebtoken` also It's worked, But when i call websocket , The system not working on middleware.

Do you have any idea?

I'm try this

```
app.configure(socketio( io => {
    // Registering Socket.io middleware
  io.use(function (socket, next) {
     // I can't get JWT in this
    next();
  });
}));
```

**Comment by daffl** [comment]
Express middleware does not work with websockets. Enabling authentication for REST and websockets is what Feathers authentication does for you. You can also parse the handshake Manually in the middleware:

```js
app.configure(socketio( io => {
    // Registering Socket.io middleware
  io.use(function (socket, next) {
     const authHeader = socket.handshake.headers.authorziation;
     // I can't get JWT in this
    socket.feathers.payload = verifyJwt(authHeader);
    next();
  });
}));
```

On the client you have to set the header with the `extraHeaders` option:

```js
var socket = io("http://localhost", {
  extraHeaders: {
    Authorization: "Bearer authorization_token_here"
  }
});
```

**Comment by Happybe** [comment]
Thanks, for this

> Express middleware does not work with websockets. Enabling authentication for REST and websockets is what Feathers authentication does for you. You can also parse the handshake Manually in the middleware:
> 
> ```js
> app.configure(socketio( io => {
>     // Registering Socket.io middleware
>   io.use(function (socket, next) {
>      const authHeader = socket.handshake.headers.authorziation;
>     socket.feathers.payload = verifyJwt(authHeader);
>     next();
>   });
> }));
> ```
> 
> On the client you have to set the header with the `extraHeaders` option:
> 
> ```js
> var socket = io("http://localhost", {
> transportOptions: {
>        polling: {
>          extraHeaders: {
>           Authorization: window.localStorage.getItem('access_token')
>         }
>        }
>      }
> });
> ```


After that I handles on service hook , I think It's work for me.
---
In this case, I try handle with JWT (RS256) which verify by public key without user, My app just provide micro service ( http and ws ).
