### ISSUE TITLE
Suggestion: npm create feathers

### ISSUE THREAD

**Issue by bertho-zero** [feathersjs/feathers#1501]
```
$ npm install -g @feathersjs/cli
$ mkdir my-new-app
$ cd my-new-app/
$ feathers generate app
$ npm start
```

can be replaced by

```
$ npm create @feathersjs/app my-new-app
$ cd my-new-app
$ npm start
```
or
```
$ npx @feathersjs/create-app my-new-app
$ cd my-new-app
$ npm start
```

**Comment by daffl** [comment]
Is there documentation how to implement this?

**Comment by bertho-zero** [comment]
I have not seen any documentation but this example: https://github.com/facebook/create-react-app/tree/master/packages/create-react-app

**Comment by daffl** [comment]
Oooh... found it in the [npm init](https://docs.npmjs.com/cli/init) documentation. Basically you create a `create-feathers-app` repo and then can use `npm init feathers`.

**Comment by edwardsmarkf** [comment]
will this be put into the documentation?

**Comment by daffl** [comment]
Well, it doesn't exist yet. When it does yes, it probably will.
