### ISSUE TITLE
stop hooks call

### ISSUE THREAD

**Issue by wwbluechip** [feathersjs/feathers#1502]
i know that using 'throw new BadRequest' can stop next hook function call.but this cause the respond status is 400.i want the response status is 200 .how can i do?
ps: i also use 'context.result' ,but this also call next hook function .so i give up.

findOrCreate.js
```
module.exports = function() {
  return async function(hook) {
    const service = hook.app.service('/emailcodes')
    let params = {
      query: {
        email: hook.data.email
      }
    }
    const info = await service.find(params)
    const response = info.data || info
    if (response.length > 0) {
      const { _id, email } = response[0]
      const updateInfo = await service.patch(_id, { email })
      throw new BadRequest('ok')
    } else {
      return hook
    }
```
here are hooks functions
```
 before: {
    all: [],
    find: [],
    get: [],
    create: [findOrCreate(), generateCode('create')],
    update: [generateCode('update')],
    patch: [generateCode('patch')],
    remove: []
  },
```

when create ,i just want findOrCreate() call. generateCode('create') doesn't call.
help me .thanks a lot~

**Comment by daffl** [comment]
Usually `context.result` is intended to be set to the raw, unprocessed data so that you'd expect all hooks to run the same way as they would if it did make the database call.

**Comment by wwbluechip** [comment]
if i use `context.result` in `findOrCreate()` ,the next function `generateCode('create')` still call

**Comment by daffl** [comment]
You can [run hooks conditionally](https://feathers-plus.github.io/v1/feathers-hooks-common/#iff) e.g. based on a flag (for example adding `context.params.existing = true` when setting `context.result` and look for that) or it can check e.g. if there already is a code.
