### ISSUE TITLE
V4 authenticate custom service error

### ISSUE THREAD

**Issue by sxwebdev** [feathersjs/feathers#1504]
### Actual behavior
I use 4.3.0-pre.2

```js
app.use('/users/me', {
	async find(params) {

		console.log(params)
	}
});
app.service('users/me').hooks({
	before: authenticate('jwt')
});
```

When I use ``authenticate`` hook in this example, i get next error ``An id must be provided to the 'get' method``.

What could it be?

### System configuration

Tell us about the applicable parts of your setup.

**NodeJS version**:
12.3

**Operating System**:
Windows 10

**Browser Version**:
latest chrome

**Comment by daffl** [comment]
As long as you don't set the [`entity` option](https://crow.docs.feathersjs.com/api/authentication/service.html#configuration) to `null`, the user service must at least have a `find` (by `query`) and a `get` method.

You can also customize that behaviour by [customizing](https://crow.docs.feathersjs.com/api/authentication/jwt.html#customization) the JWT strategy [getEntity](https://crow.docs.feathersjs.com/api/authentication/jwt.html#getentity-id-params) method (same for `local` and `oauth` if it is being used).

**Comment by sxwebdev** [comment]
I have a standard user service.

```js
module.exports = function (app) {
	const Model = createModel(app);
	const paginate = app.get('paginate');

	const options = {
		Model,
		paginate
	};

	app.use('/users/me', {
		get(id,query) {
			console.log(id)
		},
		async find(params) {

			console.log(params)
			
		}
	});
	app.service('users/me').hooks({
		before: authenticate('jwt')
	});

	app.use('/users', createService(options));

	const service = app.service('users');

	service.hooks(hooks);
};
```

This problem occurs anywhere. for example here

```js
app.use('/driverstats', new DriverStats());
app.service('/driverstats').hooks({
	before: {
		all: [ authenticate('jwt'), iff( isProvider('server'), ctx => { throw new Error('Unavailable request from server'); } ) ]
	}
});
```

And DriverStats class

```js
class DriverStats {

	setup(app, path) {
		this.app = app;
	}

	async get(id,query) {
		console.log(id,query)
	}

	async find(params) {
             console.log(params)
        }
}
```

**Comment by sxwebdev** [comment]
I used to create a service this way and it worked. Now it does not work.

```js
const { authenticate } = require('@feathersjs/authentication').express;

module.exports = function (app) {
	app.use('/some/endpoint', authenticate('jwt'), someFunction(app));
};
```

**Comment by daffl** [comment]
Please provide a complete example to reproduce your issue.

**Comment by sxwebdev** [comment]
I figured out what was the matter. An SMS authentication strategy generated an invalid token. And when we used an invalid token, this error appeared.

And another question. How to use authentication in version 4 using express?

I used to use the following method. Now it does not work.

```js
const { authenticate } = require('@feathersjs/authentication').express;
const fcmRefreshToken = require('./fcm-refresh-token');
module.exports = function (app) {
    app.post('/token/refresh', authenticate('jwt'), fcmRefreshToken(app));
};
```

**Comment by daffl** [comment]
I realized yesterday that I forgot to document the Express middleware. It's now in `@feathersjs/express`, so

```js
const { authenticate } = require('@feathersjs/express');
```

Should work.

**Comment by sxwebdev** [comment]
```js
const { authenticate } = require('@feathersjs/express');
class Stats {

	setup(app, path) {
		this.app = app;
	}

	async find(params) {

		console.log(params)

                // params.user === undefined

		if(!params.user) throw new Error('User undefined');
		
	}
}
app.use('/tracker/stats', authenticate('jwt'), new Stats());
```


Thanks for the quick response. Why in this example ```params.user === undefined```?

**Comment by sxwebdev** [comment]
![image](https://user-images.githubusercontent.com/3129246/63286730-590cd280-c2c1-11e9-94d6-69e4ebeb3347.png)

**Comment by sxwebdev** [comment]
![image](https://user-images.githubusercontent.com/3129246/63286790-878aad80-c2c1-11e9-9c1c-776e7ba5be92.png)

**Comment by daffl** [comment]
Because on a service you should use the [authenticate hook](https://crow.docs.feathersjs.com/api/authentication/hook.html). The Express middleware should only be used to authenticate other Express middleware.

**Comment by sxwebdev** [comment]
Everything works as expected. Thank

**Comment by sxwebdev** [comment]
I've got one more question.

All responses from the server are wrapped in this format

![image](https://user-images.githubusercontent.com/3129246/63362427-781b6b00-c37a-11e9-9d66-5786d88756e2.png)


I do it like this
```js
app.configure(express.rest(function(req, res) {
	if(req.headers.mobileplatform) {
		return res.set('X-Robots-Tag','noindex').json({ ok: true, result: res.data });
	} else {
		return res.set('X-Robots-Tag','noindex').json(res.data);
	}
}));
```

But with authentication this does not work as expected
![image](https://user-images.githubusercontent.com/3129246/63362522-a26d2880-c37a-11e9-89cf-196f06f1eaba.png)

The answer in an custom authentication strategy looks like this

```js
return {
	authentication: { strategy: this.name },
	[entity]: await this.getEntity(user, params)
};
```

Why does express not process the response for authentication?

**Comment by daffl** [comment]
If you need the formatter, `app.configure(express.rest` should happen _after_ `app.configure(authentication)`.
