### ISSUE TITLE
in a service.how can disable `delete`,`update`?i just want service can `create`

### ISSUE THREAD

**Issue by wwbluechip** [feathersjs/feathers#1505]
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc. This makes it much easier for us to debug and issues that have a reproducable example will get higher priority.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by KidkArolis** [comment]
Use a hook, e.g. https://feathers-plus.github.io/v1/feathers-hooks-common/#disallow

```js
const { disallow, iff } = require('feathers-hooks-common');
module.exports = {
  before: {
    // Users can not be created by external access
    create: disallow('external'),
    // A user can not be deleted through the REST provider
    remove: disallow('rest'),
    // disallow calling `update` completely (e.g. to allow only `patch`)
    update: disallow(),
    // disallow the remove hook if the user is not an admin
    remove: iff(context => !context.params.user.isAdmin, disallow())
  }
};
```

**Comment by wwbluechip** [comment]
> Use a hook, e.g. https://feathers-plus.github.io/v1/feathers-hooks-common/#disallow
> 
> ```js
> const { disallow, iff } = require('feathers-hooks-common');
> module.exports = {
>   before: {
>     // Users can not be created by external access
>     create: disallow('external'),
>     // A user can not be deleted through the REST provider
>     remove: disallow('rest'),
>     // disallow calling `update` completely (e.g. to allow only `patch`)
>     update: disallow(),
>     // disallow the remove hook if the user is not an admin
>     remove: iff(context => !context.params.user.isAdmin, disallow())
>   }
> };
> ```

thank u very much~
