### ISSUE TITLE
V4 CROW - 404 error - documentation of authentication API

### ISSUE THREAD

**Issue by devashishsethia** [feathersjs/feathers#1511]
### Steps to reproduce
Please go to the crow docs and click on the authentication section in guides. 
This will redirect you to the following URL which is broken:

https://crow.docs.feathersjs.com/api/authentication/server.html

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc. This makes it much easier for us to debug and issues that have a reproducable example will get higher priority.

### Expected behavior
The URL should lead to the correct documentation.

### Actual behavior
The visitor is presented with a 404 error.
<img width="938" alt="Screenshot 2019-08-18 at 11 45 19 AM" src="https://user-images.githubusercontent.com/17251082/63220888-21613600-c1ae-11e9-9741-b8315ff9825a.png">
<img width="589" alt="Screenshot 2019-08-18 at 11 49 46 AM" src="https://user-images.githubusercontent.com/17251082/63220908-4eade400-c1ae-11e9-8f51-2173ca7cd072.png">

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by daffl** [comment]
There is a redirect in https://github.com/feathersjs/docs/blob/crow/_redirects#L53 but I believe it will only kick in once it graduates to docs.feathersjs.com
