### ISSUE TITLE
how to Authentication with E-mail verification code？

### ISSUE THREAD

**Issue by wwbluechip** [feathersjs/feathers#1514]
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc. This makes it much easier for us to debug and issues that have a reproducable example will get higher priority.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by harrytang** [comment]
Hi,

1. create an service to save the verification code, for example called 'otp'
2. create an authentication otp strategy 'OTPStrategy'
3. config feathers app
```
module.exports = app => {
  const authentication = new AuthenticationService(app);

  authentication.register('jwt', new JWTStrategy());
  authentication.register('otp', new OTPStrategy());

  app.use('/authentication', authentication);
  //app.configure(expressOauth());
};

```
and in config/default.json
```
"authentication": {
   ...
    "otp": {
      "emailField": "email",
      "phoneField": "phone",
      "maxAttempts": 3
    }
  }

```
I'm creating the plugin called "https://github.com/powerkernel/feathers-authentication-otp", its not done yet, if interesting, you are welcome to contribute.

**Comment by TheSinding** [comment]
There is also the feathers-authentication-management library, it hasn't been patched for v4 yet, but it does what you want.
Btw, please follow the guide to file an issue or at least change the text to something meaningful

**Comment by wwbluechip** [comment]
> There is also the feathers-authentication-management library, it hasn't been patched for v4 yet, but it does what you want.
> Btw, please follow the guide to file an issue or at least change the text to something meaningful

thank u for your suggestions

**Comment by rdewolff** [comment]
Do you have more info on how to do this  How do you generate the JWT token for the user and validate his auth ?

**Comment by wwbluechip** [comment]
> Do you have more info on how to do this How do you generate the JWT token for the user and validate his auth ?
This can help you to generate the JWT token:
```javascript
const token = await app
                    .service("api/authentication")
                    .createAccessToken({
                      sub: createAccont._id
                    });
```
