### ISSUE TITLE
Question: Are there any plans for reworking NeDB module? Or maybe I'm getting this wrong?

### ISSUE THREAD

**Issue by fexell** [feathersjs/feathers#1518]
So, I'm currently developing an app in Electron, Vue and Feathers. I decided to try generating a service with NeDB (for storage if the user is offline, or don't have any connection). Because of this, you have to code for the case, looking at it, as if the user don't have an account (for my app/service). But, then as soon as the user connects, and is offline(/not signed in), and tries to create an item, they wouldn't be able to recieve the authentication-required message. So, they'd have to been on the "anonymous" channel, which would mean that everything that they create, etc, would get published to everyone else(?). I might be understand this wrong, or just my brain overthinking this, in the middle of the night.
Don't know if it's possible to get something like a mac-address from Electron, which you then could use as the channel-name.
Just Googled it, and it seems you can generate a machine-id, with something like this: https://github.com/automation-stack/node-machine-id .
Then it would be even better if something like this was implemented to work out of the box with Feathers, seeing as the point of NeDB is to be able to run it on a local machine (with no internet connection)... kind of.
So would this be interesting to implement? Might actually take a look at your source code for the NeDB-module to maybe figure it out - but then I'd also have to go through how the channels work.

Oh, well, I'm gonna stop rambling here. :)

**Comment by daffl** [comment]
Offline support is a tricky issue and not something that Feathers core or the adapters are currently handling. You can use `feathers-nedb` or `feathers-memory` or `feathers-localstorage` client-side in the browser but by default it will not synchronize with any server.

Channels are currently a purely server side concept if a real-time transport is used. I've had some ideas to adapt it for a more decentralized approach that also works in the browser but it didn't get very far as of yet.

**Comment by fexell** [comment]
> 
> 
> Offline support is a tricky issue and not something that Feathers core or the adapters are currently handling. You can use `feathers-nedb` or `feathers-memory` or `feathers-localstorage` client-side in the browser but by default it will not synchronize with any server.
> 
> Channels are currently a purely server side concept if a real-time transport is used. I've had some ideas to adapt it for a more decentralized approach that also works in the browser but it didn't get very far as of yet.

Yup, offline support sure is a tricky thing.
But it should be possible to create a custom channel to listen to, right? Like, if I generate a machine-id and uses that

**Comment by fexell** [comment]
Whoops, did not mean to close this. But I understand it's tricky to implement offline-support. I'm currently running NeDB as a stand-alone, instead of using Feather's NeDB, for the offline-case. I just really like (if not love) Feathers.
I might take a look at solving this somehow, but use integrate it with Feathers.

Thanks for the awesome work you guys do. Seriously; I wish more developers knew (and used) Feathers. All we can do is spread the word about it. Again, keep up the phenomenal work! :)
