### ISSUE TITLE
Authentication-client removes acces token on failed reauthenticate.

### ISSUE THREAD

**Issue by rybaczewa** [feathersjs/feathers#1522]
https://github.com/feathersjs/feathers/blob/6d723e81509c8e3c3020b723c696e33150ff2023/packages/authentication-client/src/core.ts#L136-L138

Authentication client removes authentication token on every failed reauthentication. It's not referenced in docs and is problematic when authentication server goes offline.
In my use case, I want to check if user can be authenticated with current token. No matter what the error is, on fail, it's removed - I would like to keep the token and try again later.

**Comment by KidkArolis** [comment]
Related to https://github.com/feathersjs/feathers/pull/1506

**Comment by daffl** [comment]
I added a `handleError` method to the authentication client in #1525 that handles this. Similar to @KidkArolis extra option but we're able to go through the customization mechanism that's already documented.
