### ISSUE TITLE
v4 service events bug

### ISSUE THREAD

**Issue by sxwebdev** [feathersjs/feathers#1528]
I upgraded to the latest version. ( 4.3.0 )

In ```channels.js``` I patch user service like this
```js
app.on('login', (authResult, { connection }) => {
    app.service('users').patch(user._id,{ last_visit: Date.now(), is_online: true });
});
```

Then my client receive unsafe data (without any after user hooks);

after hooks contains ```discard('field1','field2')```, but these fields are sent to the client.

**Comment by sxwebdev** [comment]
Thank. It works

**Comment by sxwebdev** [comment]
Why, if I add parameters, as in the example above, then I get error 401? Although the user is actually authorized

**Comment by TimNZ** [comment]
@sxwebdev check if you have any hooks on 'users' that disallow the call for a situation matching your passed params e.g. params.provider = 'external'
