### ISSUE TITLE
trying to tigger a parallel feathers client call using Promise.all, getting timeout from server

### ISSUE THREAD

**Issue by co2nut** [feathersjs/feathers#1529]
trying to perform parallel client.service().find through Promise.all

first try with few calls(5 client.service().find) -> works fine

but when it comes to large amount of calls(500 client.service().find) -> gets timeout from feathers api.

question: since it work as parallel call, every calls are triggered parallel , wonder why it gets timeout?

note: each of the calls(client.service.find()) having $limit:5

**Comment by fmoessle** [comment]
Maybe 500 service calls are a bit too much to handle for the machine you are running your application on?

**Comment by co2nut** [comment]
@daffl @fmoessle u guys are right, I'm trying to use socket.io to do the get method.

Below is my code. I'm using Reactjs as my web and  I tried to use it in my component.

![image](https://user-images.githubusercontent.com/4594000/63872456-51031000-c9f0-11e9-8cd0-bd464d7132c7.png)

![image](https://user-images.githubusercontent.com/4594000/63872517-67a96700-c9f0-11e9-95c5-3293d915a39b.png)

Please correct me if I'm wrong.

Sorry if this had gone too far from feathers related topic.

**Comment by TimNZ** [comment]
I read there is still a limit of 256 websocket connections
https://bugs.chromium.org/p/chromium/issues/detail?id=429419

**Comment by fmoessle** [comment]
@co2nut I recommend you to use the official [@feathersjs/client](https://docs.feathersjs.com/api/client.html#feathersjs-client) and the [@feathersjs/socketio-client](https://docs.feathersjs.com/api/client/socketio.html#feathersjs-socketio-client) module instead of using socket.io directly.

**Comment by daffl** [comment]
Those are good suggestions. There will be a limit of number of requests you can make at the same time. 500 of them from a single client at once definitely shouldn't be necessary and will cause issues on the client or (with more users) the server eventually.
