### ISSUE TITLE
Issue authenticating with HTTP request

### ISSUE THREAD

**Issue by SeveHo** [feathersjs/feathers#1530]
### Steps to reproduce

Hi,

since my update to v4 the authentication with plain HTTP requests is not working anymore.
My setup looks like this: 

I have a file service with a middleware that is applying the token from the qs to the authorization header

```node
const applyTokenMiddleware = async (req, res, next) => {
    const { query } = req;
    if (query.token) {
      req.headers.authorization = `Bearer ${query.token}`;
      // Remove unallowed params from query for GET
      req.query = {};
    }
    next();
  };
```

And then in the before hook of the server the authentication hook usually verified that token:
```
before: {
  all: [authenticate('jwt')],
}
```

The header still gets applied to the request headers but somehow the hook is not accepting the token anymore.
 
The error is simply: 
`error: NotAuthenticated: Not authenticated`

The params object before the authentication hook looks like this:
```
PARAMS: {
  query: {},
  route: {},
  provider: 'rest',
  headers: {
    host: 'localhost:3030',
    connection: 'keep-alive',
    'upgrade-insecure-requests': '1',
    'user-agent':
     'Mozilla/5.0 (Linux; Android 8.0.0; Pixel 2 XL Build/OPD1.170816.004) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Mobile Safari/537.36',
    accept:
     'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
    referer: 'http://localhost:3000/home',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'de,en;q=0.9,en-US;q=0.8,de-DE;q=0.7',
    cookie: 'io=SLyIzFM2uNIKTD9IAAAA',
    authorization:
     'Bearer <token>'
  },
  files: undefined
}
```

Where token is a actual value.

Did I miss something in the new version? Do I have to pass more information with the request now? 
I would highly appreciate help because this breaks huge parts of functionality for my application.

Regards

### System configuration

The app is generated with the cli so its the standard setup.

**Module versions** (especially the part that's not working):
"@feathersjs/authentication": "^4.3.0-pre.3",
"@feathersjs/authentication-jwt": "^2.0.7",
"@feathersjs/authentication-local": "^4.3.0-pre.3",
"@feathersjs/authentication-oauth": "^4.3.0-pre.3",
"@feathersjs/configuration": "^4.3.0-pre.3",
"@feathersjs/errors": "^4.3.0-pre.3",
"@feathersjs/express": "^4.3.0-pre.3",
"@feathersjs/feathers": "^4.3.0-pre.3",
"@feathersjs/socketio": "^4.3.0-pre.3",

**NodeJS version**:
v10.15.3

**Operating System**:
OSX 10.14

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by fmoessle** [comment]
You should not send your token inside the query of your request.
Instead, your HTTP request should contain an authorization-header with the bearer token inside of it.

Example with curl:
`curl -i http://dev.myapp.com/api/users -H "Authorization: Bearer mytoken123"`

[More information about authentication](https://docs.feathersjs.com/guides/basics/authentication.html#get-a-token)

**Comment by SeveHo** [comment]
@fmoessle unfortunately this is not possible. I need to provide a download link for files. With a link I cannot pass header information

**Comment by SeveHo** [comment]
@daffl Du you mean before the configuration of express in app.js `app.configure(express.rest());`

If yes how am I supposed to register middleware before?

**Comment by fmoessle** [comment]
I think @daffl means something like this in your `app.js`:
```javascript
...
app.use((req, res, next) => {
  const { query } = req;
  if (query.token) {
    req.headers.authorization = `Bearer ${query.token}`;
    // Remove unallowed params from query for GET
    req.query = {};
  }
  next();
});
// Set up Plugins and providers
app.configure(express.rest());
app.configure(socketio());
...
```

**Comment by SeveHo** [comment]
Awesome! Thanks @fmoessle

**Comment by corepay** [comment]
> Exactly. I also realized that the generator should now probably also `app.configure(middleware)` before `express.rest()`.

....so you're saying we can or should move the `app.configure(middleware)` before `express.rest()` in our existing V4 builds?

PS:  I am on `^4.3.0-pre.1` and tried upgrading to latest just the other day but it completely nuked my feathers-vuex client so I rolled back....FYI so you dont have to suggest upgrade to latest - I want to but....
