### ISSUE TITLE
getting error from feathers api when trying to authenticate through 'google' strategy

### ISSUE THREAD

**Issue by co2nut** [feathersjs/feathers#1531]
### Steps to reproduce
First Login was success

After client.logout and login using the same method will get the error message as screenshot below:
![image](https://user-images.githubusercontent.com/4594000/63870715-1481e500-c9ed-11e9-8421-ca96114c5711.png)

But when I refresh the page, the error does not appears.

Is there any missing part that I miss out during my client.logout?

**Comment by co2nut** [comment]
this error is happening in server

![image](https://user-images.githubusercontent.com/4594000/63880966-63d21080-ca01-11e9-8a25-11a4ad514307.png)

, Below are my package.json
![image](https://user-images.githubusercontent.com/4594000/63881134-bca1a900-ca01-11e9-9020-9e543686dafb.png)

**Comment by co2nut** [comment]
@daffl I tried to generate a new app and "feathers generate authentication" but I'm still getting the same error when I generate a new app using feathers cli version  @feathersjs/cli@4.1.0

**Comment by co2nut** [comment]
@daffl I found out the issue, it was from the front end react-google-login.  It returns the accessToken as null.

**Comment by co2nut** [comment]
sorry, I found out even if I have access_token it will still get the error. What I found out is that the does no go though any before hook(all) process. I try to console.log at the api to see if anything passed in. The error occurs when it does not flow into before hook process

**Comment by daffl** [comment]
A [recipe for Google authentication](https://docs.feathersjs.com/cookbook/authentication/google.html) has now been added to the Cookbook.
