### ISSUE TITLE
Custom OAuth strategy - ADFS

### ISSUE THREAD

**Issue by jirimoravcik** [feathersjs/feathers#1533]
Greetings,

I've been trying to implement authentication using ADFS. I have managed to make it work on backend, the whole process and code/configuration is here:
### Code used
authentication.js
```
const { AuthenticationService, JWTStrategy } = require('@feathersjs/authentication');
const { expressOauth, OAuthStrategy } = require('@feathersjs/authentication-oauth');

class AdfsStrategy extends OAuthStrategy {
  async getProfile(oauth, params) {
    // console.log('oauth is', oauth);
    // console.log('params are', params);
    return oauth.id_token.payload;
  }

  async getEntityQuery(profile, params) {
    // console.log('profile is', profile);
    // console.log('params are', params);
    return {
      email: profile.email,
    }
  }

  async updateEntity(entity, profile, params) { } // eslint-disable-line

  async createEntity(profile, params) { } // eslint-disable-line
}
module.exports = (app) => {
  const authService = new AuthenticationService(app);

  authService.register('adfs', new AdfsStrategy());
  authService.register('jwt', new JWTStrategy());

  app.use('/authentication', authService);
  app.configure(expressOauth());
}
```

settings
```
"authentication": {
    "secret": "super secret",
    "authStrategies": [
      "jwt"
    ],
    "service": "users",
    "jwtOptions": {
      "header": {
        "typ": "access"
      },
      "audience": "https://example.com",
      "issuer": "feathers",
      "algorithm": "HS256",
      "expiresIn": "1d"
    },
    "oauth": {
      "redirect": "/frontend",
      "adfs": {
        "authorize_url": "https://example.com/adfs/oauth2/authorize",
        "access_url": "https://example.com/adfs/oauth2/token",
        "oauth": 2,
        "key": "adfs-key"
      }
    }
  }
```
authentication hook used in other services
```
const { authenticate } = require('@feathersjs/authentication');

export default function() {
  return [authenticate('jwt')];
}
```
### Auth steps
1. go to localhost:5000/oauth/adfs
2. get redirected to adfs authentication
3. log in
4. end up redirected to localhost:5000/frontend#access_token=abc123...

I can get to point 4. But I don't know how to achieve authentication because when I try to visit any page I get unauthorized. And trying to take the access_token and post it to /authentication will not work. Is my backend configuration wrong?

When I try to post the token with strategy "jwt" to the /authentication
I get `Error: An id must be provided to the 'get' method`

### System configuration
**Module versions** (especially the part that's not working):
I would prefer to not update anything
```
"@feathersjs/authentication": "^4.3.0",
    "@feathersjs/authentication-client": "^4.3.0",
    "@feathersjs/authentication-jwt": "^2.0.10",
    "@feathersjs/authentication-local": "^4.3.0",
    "@feathersjs/authentication-oauth": "^4.3.0",
    "@feathersjs/client": "^3.7.8",
    "@feathersjs/configuration": "^2.0.2",
    "@feathersjs/errors": "^3.3.2",
    "@feathersjs/express": "^1.2.5",
    "@feathersjs/feathers": "^3.2.1",
    "@feathersjs/socketio": "^3.2.4",
```
**NodeJS version**:
v11.15.0
**Operating System**:
Windows 10
**Browser Version**:
Latest Google Chrome
**Module Loader**:

**Comment by daffl** [comment]
If you are not logged in and call `client.reAuthenticate()` [like shown in the guide](https://docs.feathersjs.com/guides/basics/authentication.html), the client will log you in automatically with the token from step 4.
