### ISSUE TITLE
Error: Cannot find module '@feathersjs/express/errors'

### ISSUE THREAD

**Issue by andysay** [feathersjs/feathers#1536]
internal/modules/cjs/loader.js:775
    throw err;
    ^

Error: Cannot find module '@feathersjs/express/errors'

whats is mean ?? debian 9.8, nodejs 12.9.1, npm 6.10.2

**Comment by jnardone** [comment]
try `('@feathersjs/express').errorHandler`

**Comment by daffl** [comment]
That module name has been deprecated a while ago and is not included anywhere in the current documentation. It has been moved to what @jnardone suggested.

**Comment by andysay** [comment]
@daffl hi, now i fix my errors , and i have next problem 

/v4/node_modules/@feathersjs/authentication/lib/hooks/authenticate.js:22
    if (!originalSettings || settings.strategies.length === 0) {
                                                 ^

TypeError: Cannot read property 'length' of undefined
