### ISSUE TITLE
lock Service

### ISSUE THREAD

**Issue by mohanagy** [feathersjs/feathers#1538]
I wondering if there a way to handle service's requests inside a loop
I mean let's suppose that we have service number1.
we fired get request on this service and we get an array of items,
and this service has a hook after, and the job of this hook to loop through the array of items and fire request to another service, we know that it is hard to handle loop with  async requests,
yes we can Promise. all but we still will face issues, 
for example: 
we faced a problem with changing the status of a list of items from a to b, and every time we check if still, any item have status a, then we fire notification,
what is happening is all the status changed and the check failed and no notification fired.

anyway, what I think is find a  way to handle something can lock the service,

### Expected behaviour
changing status from a to b then fire a notification, then keep going through the array until all items have b status 
### Actual behaviour
all items become b as a status then check and no notification fired

**Module versions** (especially the part that's not working):
v3

**Comment by daffl** [comment]
This is what multi updates are for that do this at the database level. So changing status from `A` to `B` would be

```js
app.service('myservice').patch(null, { status: 'B' }, { query: { status: 'A' } });
```

There are no locks necessary. As an alternative, if the status is dependent on subsequent requests, they should be done sequentially instead of `Promise.all`.
