### ISSUE TITLE
How to authenticate user in express midlleware?

### ISSUE THREAD

**Issue by denabe** [feathersjs/feathers#1539]
Hi all. Can not authenticate user in service middleware.
At previous version i make this:
`const { authenticate } = require('@feathersjs/authenticate').express
app.use('/path', authenticate('jwt'), (req, res, next) => {
...
}, new Service());`
Now it not works and i not found any information about this.

**Comment by daffl** [comment]
It was moved to `require('@feathersjs/express').authenticate` and I totally forgot to add it to the docs. Added to the migration guide and documented now [here](https://docs.feathersjs.com/api/express.html#express-authenticate).
