### ISSUE TITLE
Upgrade/Generator does not work with .JS files

### ISSUE THREAD

**Issue by TheSinding** [feathersjs/feathers#1541]
### Steps to reproduce
- Create a non v4 project.
- Change the `default.json` to `default.js`
- Run `feathers upgrade`

### Details 
I have an existing project, which have a `.js` file extention on the default config.
When I run the `upgrade` command, I get a `Cannot set property 'authentication' of undefined`.
This is due to the upgrade / generator is expecting an `default.json` and not a `default.js`.

### Expected behavior
I should upgrade the project.

### Actual behavior
It throws an `Cannot set property 'authentication' of undefined` error

**Comment by daffl** [comment]
I published a fix that won't make it error. `.js` configuration files won't be updated automatically though.
