### ISSUE TITLE
Generate Services via DBDiagram.io JSON File

### ISSUE THREAD

**Issue by wipro-ivan** [feathersjs/feathers#1542]
Apologies in advance if I am putting this in the wrong place as it is most definitely not an "issue", I looked at the guidelines and didn't find an appropriate place (apart from maybe the plugin generator github). Please point me to the correct place if I am barking up the wrong tree

My query is this: 

1. Currently my development process (as regular) is to create a conceptual/logical model via a tool called DBDiagram.io (https://dbdiagram.io) 
2. Create an app and create the services using the cli generator
3.  Add the fields and relations in each model file 
etc. 

I was wondering if there has been any ideas around the community to skip step 2 and 3 and generate an entire back-end app via the export (a JSON that has all the entities, their fields and their relations) from DBDiagram.io? It's something I've been thinking about doing if I had the time but would love to know if anyone has already had the idea

**Comment by daffl** [comment]
I'm going to close this since it has been open for a while and does not have anything actionable at the moment. Feel free to comment on this issue or create a new one if there is anything new to share.

**Comment by J3m5** [comment]
That's funny, I'm using this tool and I've been thinking about this idea.
The sad part is that it's not open source, and we can't export as JSON, just MySQL or PostgreSQL.
It would be nice to have a simple GUI for managing schemas that let you see them all and their relationships in one place.
It would  keep them in sync in two ways, editing in the GUI reflect the changes in the schema files and inversely.
For now I don't have the time to work on another project like this one, but I would certainly help if someone would like to make it happens.
