### ISSUE TITLE
Authenticate JWT Hook, An id must be provided to the 'get' method

### ISSUE THREAD

**Issue by masterbater** [feathersjs/feathers#1544]
I upgraded to new V4
```
  "@feathersjs/authentication": "^4.3.0",
    "@feathersjs/authentication-local": "^4.3.0",
    "@feathersjs/authentication-oauth": "^4.3.0",
    "@feathersjs/configuration": "^4.3.0",
    "@feathersjs/errors": "^4.3.0",
    "@feathersjs/express": "^4.3.0",
    "@feathersjs/feathers": "^4.3.0",
    "@feathersjs/socketio": "^4.3.0",
```

When using hooks  authenticate("jwt")  for featherjs v4,  I encounter this error
`{
    "name": "GeneralError",
    "message": "An id must be provided to the 'get' method",
    "code": 500,
    "className": "general-error",
    "data": {},
    "errors": {}
}`

I fix it by following the migrate guide for supporting LegacyJWTStrategy, the legacy has required userId field so that it populates the hooks.params.user after the authenticate('jwt') hook.

Are there any changes in payload format with the new update or is it an issue authenticate('jwt') hook?

**Comment by daffl** [comment]
Yes, there are changes. The entity id is now in the proper standard JWT `subject` field where it is supposed to be. This is why it is recommended to change the secret to expire all previous tokens. 

A [backwards compatible strategy is documented in the migration guide](https://docs.feathersjs.com/guides/migrating.html#backwards-compatibility) but should only be used if clients can't be updated at the same time.
