### ISSUE TITLE
[FR] Support reverse application hooks

### ISSUE THREAD

**Issue by rayfoss** [feathersjs/feathers#1548]
### Steps to reproduce
If you need before hooks to run after all services, you'd have to copy paste the hook to every single service, or hack it into an extended adapter.

### Solutions:
1. add applications hooks: afterBefore, beforeAfter, beforeError that can handle the reverse scenario.
2. make the cli generate apps with a hook filter on the service that can facility support for these cases. Hook middleware in a way.

### My current solution: 
Usage in service: service.hooks(proxyHooks(hooks))
```
// Application hooks that run for every service

const proxiedHooks = {
  before: {
    all: [],
    find: [],
    get: [],
    create: [ ],
    update: [ ],
    patch: [ ],
    remove: []
  },

  after: {
    all: [ ],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  },

  error: {
    all: [],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  }
}

modules.exports = function proxyHooks (hooks) {
  for (const baeK of Object.keys(hooks)) {
    const cruds = hooks[baeK]
    for (const crudK of Object.keys(cruds)) {
      const hook = cruds[crudK]
      if (Array.isArray(hook)) {
        cruds[crudK] = baeK === 'before'
          ? [...hook, ...proxiedHooks[baeK][crudK]]
          : [...proxiedHooks[baeK][crudK], ...hook]
      }
    }
  }
  return hooks
}
```

Conversation that inspired this: https://pastebin.com/fQh43HhT

**Comment by rayfoss** [comment]
Other applications, running dummy queries that don't touch the adapter for security and validation when using hookless methods. Implementing safe multi object patch.

@daffl my proposed backwards compatible API:
```
preBefore: [], // Alias to before
postBefore: [],
preAfter: [],
postAfter: [], // Alias to after
preError: [],
postError: [] // Alias to error
```

Taking PRs?

**Comment by sean-nicholas** [comment]
I hope I understand your problem correctly. So to rephrase it, you like to have a hook chain that looks like this:

```
hook1() // defined in app hooks
hook2() // defined in service hooks
hook3() // defined in app hooks again
```

Is that correct?

I had the same problem this week and solved it like that:

```ts

// in app.ts
[...]
app.configure(services)
[...]
// must run after all service.hooks() calls
app.configure(runAfterServiceHooks('before', 'find', someHook()))

// in run-after-service-hooks.ts
export function runAfterServiceHooks(type: string, method: string, hook: Hook) {
  return (app: Application) => {
    for (const serviceName of Object.keys(app.services)) {
      const service = app.service(serviceName)
      service.hooks({
        [type]: {
          [method]: [hook]
        }
      })
    }
  }
}

```

This should work for before, after & error if I'm not mistaken.

**Comment by bertho-zero** [comment]
Have you seen this proposal: https://github.com/feathersjs/feathers/issues/932 ?

With that you can add hooks like:
```js
app.hooks({
  async: {
    all: [],
    find: [],
    get: [],
    create: async (ctx, next) => {
      // some stuff before
      await next(); // run all next async hooks with adapter call
      // some stuff after
    },
    update: [],
    patch: [],
    remove: []
  }
});
```

If you need to add hooks before all others you can do:
```js
Array.prototype.unshift.apply(app.__hooks.before.create, someHooks)
```

The ideal would be to have something to use push or unshift as needed:
```js
app.hooks({
  async: {
    all: [],
    find: [],
    get: [],
    create: {
      $unshift: [],
      $push: []
    },
    update: [],
    patch: [],
    remove: []
  }
});
```

That happens here:
https://github.com/feathersjs/feathers/blob/7818aec0dd9fe7af6ec6c6c4971df8426ef4a5d6/packages/commons/src/hooks.ts#L180-L186

**Comment by rayfoss** [comment]
@bertho-zero  that koa approach seems to complicate hook type conversions... Such as Patch to Update. My current solution works fine, but hooks built on it will work for no one else, I just want a standard solution that supports most use cases and we can build  common hooks on.

My newest dilema is implementing deep discard query into deep patch queries

**Comment by bertho-zero** [comment]
`async` is another type of hooks that surrounds others, it's backward compatible.

The conversions is very simple:
```js
const beforeHook = async (ctx, next) => {
  // hook stuff...
  await next(); // or return
};

const afterHook = async (ctx, next) => {
  await next();
  // hook stuff...
};
```

---

The second thing of my comment is the recording of hooks with `$unshift` and `$push`, you could just do this anywere:
```js
app.hooks({
  before: {
    find: {
      $unshift: someHook()
    }
  }
})
```
