### ISSUE TITLE
Using TypeScript and avoiding `any`

### ISSUE THREAD

**Issue by cdeutsch** [feathersjs/feathers#1556]
In the [Quick Start](https://docs.feathersjs.com/guides/basics/starting.html) the following example is given for TypeScript

```typescript
const main = async () => {
  // Create a new message on our message service
  await app.service('messages').create({
    text: 'Hello Feathers'
  });

  // And another one
  await app.service('messages').create({
    text: 'Hello again'
  });
  
  // Find all existing messages
  const messages = await app.service('messages').find();

  console.log('All messages', messages);
};
```

How do you get `app.service('messages')` to return something that isn't an `any`?

In a TypeScript friendly app, I'd expect the compiler to know `.create` is a function, but that's not the case in this example.

**Comment by thanh-nguyen-95** [comment]
In my experience, you can use something like this:

```typescript
// Type `Messages` should be available when you register a service
// (or at least those that are generated using the CLI)

const MessageService: Messages = app.service('messages');

MessageService.create({ ... })
```

**Comment by cdeutsch** [comment]
Thanks that seems to work.

I would have expected `app.service` to accept a type that dictates the return type. Eg:

```typescript
app.service<MessageService>('messages').create({ ... });
```

Not sure if that's possible to add?

**Comment by daffl** [comment]
You can also add a service name map interface which is what's used in the generated application. I left it out for simplicity's sake but it might be worthwhile adding.

**Comment by daffl** [comment]
This has been addressed in the [new quick start guide](https://dove.feathersjs.com/guides/basics/starting.html) as well as in the v5 CLI which generates a fully typed client.
