### ISSUE TITLE
Split feathers transports into their own modules

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers#156]
We should do this so that people don't need to include compile engine.io when they don't need to. It also helps with our mantra of keeping things small and modular.

Modules that should be created:

- [x] [feathers-rest](https://github.com/feathersjs/feathers-rest)
- [x] [feathers-socketio](https://github.com/feathersjs/feathers-socketio)
- [x] [feathers-primus](https://github.com/feathersjs/feathers-primus)

**Comment by ahdinosaur** [comment]
this would be awesome. :+1:

**Comment by ahdinosaur** [comment]
i reckon it'd be even more magical if these modules also contained their respective client transport functionality in [`feathers-client`](https://github.com/feathersjs/feathers-client), specified using [the `browser` field](https://github.com/defunctzombie/package-browser-field-spec). :cherry_blossom:

**Comment by daffl** [comment]
@ahdinosaur What do you mean? I would think since the client adapters are so small (e.g. https://github.com/feathersjs/feathers-client/blob/master/src/sockets/base.js is the code for websocket clients) we probably don't need to split those up.

Status of this is that I already split out the server side REST API provider at [feathers-rest](https://github.com/feathersjs/feathers-rest) with the other ones to follow very quickly.

**Comment by ahdinosaur** [comment]
@daffl let's say i'm using the mythical `feathers-primus`, then i only want the code you linked, not the code for the rest client adapters. similarly, if i'm using `feathers-rest` then i only want the code for the rest adapters (you could even split these up). so i think it'd be pretty sweet to combine the server and the client code into the same module, also because i'm interested in isomorphic feathers (removing `feathers-client` entirely). :smile:

**Comment by ekryski** [comment]
Hmm. @ahdinosaur I sort of get what you're going after but not really... ha ha.

`feathers-client` **is** isomorphic and can be used both server and client side. @daffl is currently in the process of splitting out the purely server side pieces into `feathers-rest`, `feathers-socketio`, and `feathers-primus` so that you don't have install them if you aren't going to use them (it's rare that you need socketio and primus at the same time).

So were you thinking that you wanted to use the server side stuff client side as well? Maybe you didn't know that `feathers-client` is isomorphic?

**Comment by ahdinosaur** [comment]
hmm, yeah i messed up my comment about isomorphism. i guess the question on my mind is what it'd mean for feathers to provide an interface like [multilevel](https://www.npmjs.com/package/multilevel), [multiplex-rpc](https://www.npmjs.com/package/multiplex-rpc), or [muxrpc](https://www.npmjs.com/package/muxrpc).

so here's a more concrete strawman proposal, to throw some more spaghetti on the wall and see if anything sticks :spaghetti:

- `feathers`
  - `require('feathers')` in node returns the same as it does now
  - `require('feathers/client`) in node returns what is now `feathers-client`
  - `require('feathers')` in browser returns what is now `feathers-client`
- `feathers-rest`
  - `require('feathers-rest')` in node returns the same as it does now
  - `require('feathers-rest/client`) in node returns what is now [`require('feathers-client/lib/rest')`](https://github.com/feathersjs/feathers-client/blob/master/src/rest/index.js)
  - `require('feathers-rest')` in browser returns what is now [`require('feathers-client/lib/rest')`](https://github.com/feathersjs/feathers-client/blob/master/src/rest/index.js)
- `feathers-primus`
  - `require('feathers-primus')` in node returns the same as we'd expect now
  - `require('feathers-primus/client`) in node returns what is now [`require('feathers-client/lib/sockets/base')`](https://github.com/feathersjs/feathers-client/blob/master/src/sockets/base.js)
  - `require('feathers-primus')` in browser returns what is now [`require('feathers-client/lib/sockets/base')`](https://github.com/feathersjs/feathers-client/blob/master/src/sockets/base.js)
- `feathers-primus`
  - `require('feathers-socketio')` in node returns the same as we'd expect now
  - `require('feathers-socketio/client`) in node returns what is now [`require('feathers-client/lib/sockets').socketio`](https://github.com/feathersjs/feathers-client/blob/master/src/sockets/index.js)
  - `require('feathers-socketio')` in browser returns what is now [`require('feathers-client/lib/sockets').socketio`](https://github.com/feathersjs/feathers-client/blob/master/src/sockets/index.js)

**Comment by daffl** [comment]
I like it. We'd just make Feathers v2 depend on `feathers-client` and pull out the transports for the client into the respective server provider module (`feathers-rest`, `feathers-socketio` and `feathers-primus`). Everything else is just mapping it correctly in the `browser` field.

Could you maybe create a small example app we can test it with?

**Comment by ekryski** [comment]
:+1: to all of that.

**Comment by ahdinosaur** [comment]
sweet. :)

> Could you maybe create a small example app we can test it with?

yep, [here's an quick example i just threw together](https://github.com/ahdinosaur/multifeathers-example) that demonstrates the three different use cases (node server, node client, browser client) of using the rest transport. hope that helps, not sure exactly what kind of example is most helpful.

**Comment by ekryski** [comment]
As I was showering this morning I had a thought that we'll need to make sure that it still works in React Native as well because it's not a Node runtime and it's not a browser so sometimes things get a bit quirky.
