### ISSUE TITLE
mongodb app generated with feathers generate app doesnt have unique index on user email

### ISSUE THREAD

**Issue by Freundschaft** [feathersjs/feathers#1565]
I created an app with feathers generate app, and selected mongodb as my database.

now when I create users, I can create any amount of users with the same email address. obviously this cant be right, am I missing something here?

**Comment by daffl** [comment]
Since MongoDB doesn't have any models, they will have to be created on the database manually. You can find more information in the [MongoDB indexes documentation](https://docs.mongodb.com/manual/indexes/).

**Comment by Freundschaft** [comment]
I understand but right now feathers generate app creates an application that doesnt work properly when used with mongodb, since its possible to create the same user over and over again, wouldnt it make sense to add createindex for the user in the generated app during creation?
