### ISSUE TITLE
feathers auth assumes an accessToken exists for socket (regression)

### ISSUE THREAD

**Issue by jnardone** [feathersjs/feathers#1568]
Prior to https://github.com/feathersjs/feathers/commit/2707c3331721be6a4a0a943b0fbc118379a1ad2a#diff-847cf0caf6782a09a6a9cf0969d02f50R35 in 4.3.0 you could (in an after hook) remove the `accessToken` from `hook.result` in an after hook.  We are doing this to enforce a 2fa flow in our application, to request further info in a future auth request.  We however still wanted to return a 20x response code with the request.

With the above the code assumes there is an access token in the result, and throws an ugly "jwt must be provided" error in this situation.

Is it reasonable to assume that a successful call to authenticate always includes an accessToken, and we need to rethink our design?  Or should this socket code check for accessToken existence prior to running this block of code?

We could return an error in this case if that's our only option.

**Comment by daffl** [comment]
Whoops. https://github.com/feathersjs/feathers/commit/2707c3331721be6a4a0a943b0fbc118379a1ad2a#diff-847cf0caf6782a09a6a9cf0969d02f50R33 definitely should also check if there is an access token so

```js
const { accessToken } = authResult;

if (accessToken && authResult && event === 'login') {
  debug('Adding authentication information to connection');
```
