### ISSUE TITLE
Integrating Feathers with .NET app

### ISSUE THREAD

**Issue by dariuspranskus** [feathersjs/feathers#1574]
Hello

This is not an issue as such, I just would like your advise on integrating FeathersJS with .NET fronted.

First I would like to thank you for the wonderful framework you’ve built. 

I am making an Unity game and I want to use FeathersJS as a backend. I know, that I can use it with a REST protocol, but I will need some real time capabilities also. I also am building an manager front end app using VueJs, so the FeathersJS backend makes a lot of sense.

Do you have any sample code you can share of such .NET real time integration? I tried to look for it online, but was not able to.

Thanks

**Comment by vonagam** [comment]
To my knowledge feathers currently does not have .NET client implementation.

There are multiple ways to bridge nodejs and c# sides that you might explore:

1) Using an existing transport adapter. Feathers supports `socketio` transport. And there are two c# client implementations for it: [`SocketIoClientDotNet`](https://github.com/Quobject/SocketIoClientDotNet) and [`socket-io`](https://github.com/IBM/socket-io) from IBM. Unfortunately, first one is depreciated and second one might not be suitable for unity.

2) Using new websockets adapter. Write a feathers transport adapter for websocket server of your choice (for example [`ws`](https://github.com/websockets/ws)) using code for [`socketio`](https://github.com/feathersjs/feathers/blob/718126802382ad3f15c4a548e1e5ba21df063f6c/packages/socketio/lib/index.js) and [`primus`](https://github.com/feathersjs/feathers/blob/718126802382ad3f15c4a548e1e5ba21df063f6c/packages/primus/lib/index.js) as a reference. And use one of websocket clients for .NET (for example [`websocket-sharp`](https://github.com/sta/websocket-sharp)).

3) Using other nodejs framework with .NET client as a bridge between feathers and c# sides. Might look into [`colyseus`](https://github.com/colyseus/colyseus) as an option for this.

**Comment by dariuspranskus** [comment]
@vonagam Thanks. Approach 2 looks pretty decent to me, not sure how much work it might involve. Will have a look.

**Comment by daffl** [comment]
As suggested, basically it comes down to connecting to Socket.io with .NET. The Feathers specific message format is described at https://docs.feathersjs.com/api/client/socketio.html#direct-connection
