### ISSUE TITLE
option to select partial rest service [feature request]

### ISSUE THREAD

**Issue by osman-mohamad** [feathersjs/feathers#1578]
### Steps to reproduce
- add option to apply only needed methods for specific service. or remove selected methods from service use
users.service.js
```js
  app.use('/users', createService(options), {'only': ['find', 'get']]});
// or
  app.use('/users', createService(options), {'except': ['remove']]});
```

### Expected behavior
to allow only set methods in the options to be available to internal or external use

### Actual behavior
now there is not options like this and the programmer need to add hook
```js
hooks : {
  before: [
    disallow('external')
 ]
}
```

**Comment by daffl** [comment]
With a standard adapter this can already be implemented with a single fairly simple application level hook:

```js
options.allow = [ 'find', 'get' ];

app.use('/users', createService(options));

app.hooks({
  before: {
  }
});
```

**Comment by osman-mohamad** [comment]
@daffl thank you for your response and the hook implementation.

I know it could be implemented from the hook layer from the beginning. but after I used feathers in complex app. I found that the hooks files for the services become more complicated and crowded.

So I asked this feature to extract this simple common use case to the service layer of the application.

**Comment by daffl** [comment]
The hook I am suggesting is a single application hook (`app.hooks.js`), not per service. Adding a new option to all official adapters and testing, documenting and maintaining it is a lot of work. I am not sure it is worth the effort in this case to replace three lines of code in the application.

**Comment by osman-mohamad** [comment]
OK . thank you very much
