### ISSUE TITLE
Associating a sequalize model throws TS2684

### ISSUE THREAD

**Issue by shtrived** [feathersjs/feathers#1579]
### Steps to reproduce

- [ ] Tell us what broke. The more detailed the better.
Have two data models created in feathers using sequelize implemented in typescript. While doing association the script complains with error 

```
TS2684: The 'this' context of type 'typeof Model' is not assignable to method's 'this' of type 'ModelCtor<Model<unknown, unknown>>'.   Type 'typeof Model' is not assignable to type 'new () => Model<unknown, unknown>'.     Cannot assign an abstract constructor type to a non-abstract constructor type.
 ```

- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc. This makes it much easier for us to debug and issues that have a reproducable example will get higher priority.

My code:

```
  // eslint-disable-next-line no-unused-vars
  (organizations as any).associate = function (models: any) {
    // Define associations here
    // See http://docs.sequelizejs.com/en/latest/docs/associations/

    organizations.hasMany(models.entitlements); // Will add organizationId to entitlements model
    // organizations.hasMany(models.externalaccounts); // Will add organizationId to externalaccounts model
  };
```

### Expected behavior
Tell us what should happen

### Actual behavior
Stuck with the error, cant proceed.

### System configuration

Tell us about the applicable parts of your setup.

Not able to create mode associations.

**Module versions** (especially the part that's not working):
"feathers-sequelize": "^6.0.1",
"sequelize": "^5.16.0",

**NodeJS version**:
v12.7.0

**Operating System**:
Mac

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by JakobBisander** [comment]
I'm having the same issue as described above since i recently started a new project in typescript. In an older project in normal js i'm not having any problems. Generating a generic service with the feathers cli and then trying to add an association on the model gives the error. 
From what i could find the issue may be due to sequelize.define (See bottom part of this page https://sequelize.org/master/manual/typescript) but i don't see how this would work with the way feathers generates the model.

Any help appreciated.

**Comment by JakobBisander** [comment]
I found a solution:

models.organizations.hasMany(models.locations, { as: 'organizationId' });

This works, and the only change is to put the 'models' part before whatever your service is called (In this case its my organizations-service).
This is not necessary in javascript though, which is what confused me.
