### ISSUE TITLE
Generator for scaffolding new plugins

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers#158]
To make it easier for us to crank out services and to make it more approachable for others we should have some sort of generator. Possibly just use yeoman. It's pretty robust and supports quite a bit, without us hand rolling our own.

**Comment by ekryski** [comment]
The project has been started here: https://github.com/feathersjs/generator-feathers-plugin

**Comment by daffl** [comment]
I would think that project is - besides some tweaks - mostly done unless there are other suggestions for improvements. I'm already using it to create new plugins written in ES6. The documentation could probably use some love.

**Comment by daffl** [comment]
I'm going to close this since I think the plugin generator does everything it needs to by now.
