### ISSUE TITLE
CLI generate middleware with TS wrong folder?

### ISSUE THREAD

**Issue by alinex** [feathersjs/feathers#1582]
I have a feathers app generated using the CLI with typescript using src folder. But when I try to add a new middleware it fails:

```bash
$ feathers generate middleware
? What is the name of the Express middleware? swagger
? What is the mount path? /swagger
events.js:186
      throw er; // Unhandled 'error' event
      ^

Error: /home/alex/code/node-server/lib/middleware/index.ts doesn't exist
    at EditionInterface.module.exports [as read] (/usr/lib/node_modules/@feathersjs/cli/node_modules/mem-fs-editor/lib/actions/read.js:12:11)
```

**Comment by daffl** [comment]
I am not able to reproduce this in https://github.com/feathersjs/feathers-chat-ts. Most likely cause of this issue is that `directories.lib` in `package.json` should be set to `src/`.
