### ISSUE TITLE
Remove method - Before hook - query.param is not populated when Id is provided

### ISSUE THREAD

**Issue by sachinsawant71** [feathersjs/feathers#1584]
### Steps to reproduce

I am calling feathers.js service's remove method from a client. I pass both id as well as params to it. I plan to use param to do additional validation before I delete/remove the record from the database e.g.

await contentService.remove("content123",{ organizationId: "xyzorg" });

I want to check if the user has valid access in  organization ("xyzorg") before the content "content123" is deleted. 

I created a custom "before" hook and tried to access the above query using hook.params.query object. I noticed that the query object is empty. 

Does feathers.js ignores query params when "id" is provided to remove service call?

Is there a way for me to pass the additional information to the remove method?

### System configuration
Feathers.JS - version v4.3.1
node.js - version v10.36

**Comment by jnardone** [comment]
`await contentService.remove("content123",{ organizationId: "xyzorg" });`

Remember that only `query` in the params gets sent from the client.

You want

`await contentService.remove("content123",{ query: { organizationId: "xyzorg" } });`

**Comment by sachinsawant71** [comment]
Thank you.
