### ISSUE TITLE
Export service as package/module?

### ISSUE THREAD

**Issue by svendeckers** [feathersjs/feathers#1586]
More of a question than a bug.
We are a company developing decentralised applications.
A 3rd party will develop a web application for us using React and Feathers.
As an addition to the webapp they will develop, we would like to provide them with a registration module that will include some React components (like a form) and a Feathers service (to store the registration and maybe have a hook or 2).

Let's assume we can't share a git repo with the 3rd party, what is considered the best way to share our code with them?
We can pack the React components like an npm package for instance, but what about the Feathers service and possible hooks?

**Comment by daffl** [comment]
Why not also publish them as an npm package that exports a [configure function](https://docs.feathersjs.com/guides/basics/generator.html#configure-functions)? That's what most Feathers plugins are doing.

**Comment by svendeckers** [comment]
will look into it, thank you!
