### ISSUE TITLE
** Conditionally ** insert record to DB in normal service?

### ISSUE THREAD

**Issue by corepay** [feathersjs/feathers#1587]
Brain is dead or I am not grasping a fundamental concept...

- Have an API server with endpoints and normal services CRUD to postgres using Sequelize
- Have a "client" server that supports a Vue/Quasar client app that receives requests via feathers-vuex, doing some data scrubbing and validation then  sending request to the API server for data via an axios http call.  (I want to setup client server as feathers client to api server but cant figure out - still looking for a solution that does not require me to stuff everything in the app.js....)

Anyway - here is the question I can't wrap my head around.  I have a normal service - say `receipts` with out of the box crud.  If this service receives a flag in the create request `is_test` I do not want it to create a record in the database.  Is there a way to loop it back as a response as if it was created in db?

**Comment by daffl** [comment]
This is what [setting context.result](https://docs.feathersjs.com/api/hooks.html#context-result) is for. If it is set in a `before` hook, the original database call will be skipped:

```js
context => {
  if (context.data.is_test) {
    context.result = context.data;
  }

  return context;
}
```
