### ISSUE TITLE
[FR] Adapterless Hooks / $skipAdapter /Adapter NoOp

### ISSUE THREAD

**Issue by rayfoss** [feathersjs/feathers#1589]
There are situations with hookless services and application hooks where running all update or create hooks successfully would indicate the user has permission and the data is valid. Which then gives the server permission to continue using a hookless service.

In these situations one would want to run all create or update hooks, but not actually execute the adapter call.

The best way to do this right now is to make a phony request and handle the BadRequest or cause a unique key violation on ID. The latter would be different and inconsistent across adapters. The former, is not specific and only works with update calls.

This could simplify some common hooks and make exotic application hooks that require running after service `before` hooks work in services. Resulting in more portable hooks.

I'm willing to PR this.

**Comment by KidkArolis** [comment]
Did you try setting `context.result` to something in a before hook? That should skip the adapter call. See: https://docs.feathersjs.com/api/hooks.html#context-result

**Comment by rayfoss** [comment]
Well. Okay. That seems like an API. Now it's better documented. Thanks!
