### ISSUE TITLE
Generator for scaffolding a feathers app

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers#159]
Since feathers is very modular it can be tough for a newcomer to get a handle on all the modules required for an app. We want to keep everything modular and flexible but still provide all the functionality you would expect in a real-time framework. We are inspired by, and run on top of Express after all!

So with that we should create a yeoman generator that scaffolds an application.

It should promp you for:

- [x] Project Name
- [x] Description
- [x] ~~License~~ (using Proprietary by default)
- [x] ~~URL~~ (left to the user, we may pre-poulate with your-app.feathersjs.com)
- [x] ~~Author~~ (left to the user)
- [x] Database
- [x] Whether you need websockets and if so which type
- [x] ~~Whether it serves static content~~ (should always as it's baked into Express)

It should then generate the app with the following dependencies if the user answered yes to above questions:

- [x] `body-parser`
- [x] `CORs`
- [x] `serve-favicon`
- [x] `compress`
- [x] `winston`
- [x] `feathers`
- [x] `feathers-config`
- [x] ~~`feathers-logger`~~ (deprecated in favour of using your own)
- [x] `feathers-hooks`
- [x] `feathers-authentication`
- [X] ~~`feathers-sync`~~ (not ready, it's more of an advanced guide thing)
- [x] `feathers-[database adapter]`
- [x] `feathers-[transport plugin]`

A suggested folder structure would look like:

```
root
    -> public/
        -> 404.html
        -> 500.html
        -> index.html
    -> client/
        -> js/
        -> css/
    -> server/
        -> config/
            -- development.json
            -- production.json
        -> services/
        -> routes/
            -> api/
            -> public/
        -> lib/
            -> hooks/
            -> middleware/
        -> views/
        -> test/
        -- index.js
    -> README.md
    -> package.json
    -> Dockerfile
    -> .gitignore
    -> .npmiginore
    -> .jshintrc
```

## High Level Tasks Remaining

- [x] Update to feathers-2.0.0
- [x] Update to hooks-1.0.0
- [x] Inject data store setup based on database selected
- [x] Scaffold a user model based on database selected
- [x] Scaffold a user service based on database selected
- [ ] Scaffold JWT authentication based on auth method(s) selected
    - [x] Local (username/password) **(in progress)**
    - ~~Twitter~~ (not going to make it for this release. [OAuth1 support](https://github.com/feathersjs/feathers-authentication/issues/42) won't make this release)
    - [x] Facebook
    - [x] LinkedIn
    - [x] Google
    - [x] Github
    - [x] Bitbucket
- [x] Scaffold a basic logger
- [x] Generate basic error pages 
- [x] Generate error handler middleware
- [x] Be able to generate a new service
- [x] Be able to generate a new before hook (using promises)
- [x] Be able to generate a new after hook (using promises)
- [x] Style error and index pages
- [x] Add favicon
- [x] Add code comments

**Comment by ekryski** [comment]
Work has started on this here: https://github.com/feathersjs/generator-feathers

**Comment by daffl** [comment]
Since I need this anyway, I started working more on it in https://github.com/feathersjs/generator-feathers/tree/app-architecture. I think https://github.com/feathersjs/generator-feathers/tree/app-architecture/app/templates/src is a good start.

**Comment by marshallswain** [comment]
Do we want to take cookie-parser off this list, since we'll be using tokens, now?

**Comment by ekryski** [comment]
Ya I think we can scratch out cookie parser.

**Comment by ekryski** [comment]
Finally this is done! Closed by https://github.com/feathersjs/generator-feathers/pull/49
