### ISSUE TITLE
Authenticating user from existing table in MySQL database

### ISSUE THREAD

**Issue by fortydegrees** [feathersjs/feathers#1593]
Hi, not a bug, but I've been pulling my hair out all day trying to figure this out so I thought I'd try here.

I have a NextJS app that users can register on. The registration is handled by a Node server using sequelize and MySQL and PassportJS. The node server sends the NextJS app (client) a token, which is stored in Local Storage.

I want to add a realtime websocket feature to the site, so have chosen FeathersJS. I figure for the communication between user and Feathers, I need to authenticate them. 

I see three ways of approaching this:
*send the pre-existing localstorage token to feathersJS and use this as an auth
*change the way feathersJS generates the JWT token to match the way the node server does it
*have the user identify again with feathersJS and use that token for the real time communication.

Problem is, I can't work out how to any either of them. Been playing around with hooks and studying the documentation. I can connect to my database and read/write data, but not sure how to integrate this with authorization, or even if I'm framing this in the right context.

Are there clearer guidelines or examples on how to do this? How to essentially tap into a pre-existing authentication system?

**Comment by edwardsmarkf** [comment]
for whatever this is worth, i found i needed to create a new table (or
should i say let seqeulize create it for me).  and all the auth stuff is
maintained in there.  i never have to touch the table, so it seems.

Thank you,

Mark Edwards

**Comment by fortydegrees** [comment]
Thanks Mark! My only concern is that all my user info is *already* in a user table. My project is also a game, so I want to securely and efficiently authenticate them with the same info, so i can do things like retrieve their previous scores, and add to their current one

**Comment by edwardsmarkf** [comment]
i think we are sort of restricted to using something of an internal table
for Oauth stuff.  its certainly easy enough to get the email address out of
it, and whatever else you might need.   in other words, i have email in two
diffeent tables, one the Oauth "internal" one, and the one i use for
everything else.  maybe "internal" is not the right word to use, but its a
table that Oauth maintains.  so if somebody does log in successfully, they
are in the internal table.  but you may reject them if they are not a
member of your game database.    hopefully this helps you.  i really
struggled with feathers at first, since there is no really good beginning
point, imho.   the feathers people are very helpful, but somehow they
expect a certain level of experience.  imho, we should be seeing lots and
lots of newbie examples.  but that's just me i guess!

Thank you,

Mark Edwards

**Comment by fortydegrees** [comment]
If the Feathers team are reading this, I agree that as a relative novice, I've found it a bit difficult to pick up with regards to the scope of the examples etc. Maybe this is by design, but happy to talk more if this is something the team want to address.

**Comment by daffl** [comment]
That's what [the Cookbook](https://docs.feathersjs.com/cookbook/) is intended for. What you are asking for is also somewhat specific but should be possible by implementing your own strategy which is [documented here](https://docs.feathersjs.com/api/authentication/strategy.html#setname-name). Based on the [anonymous authentication](https://docs.feathersjs.com/cookbook/authentication/anonymous.html) example, your custom authentication just needs to implement the `authenticate` method:

```js
const { AuthenticationBaseStrategy } = require('@feathersjs/authentication');

class MyTokenStrategy extends AuthenticationBaseStrategy {
  async authenticate(authentication, params) {
    const { clientToken } = authentication;

    // Verify the token. Since it's custom this is up to you
    // Then return whatever should be merged with `params`
    return {
      myToken: clientToken,
      // user: userObject if there is one
    }
  }
}

module.exports = app => {
  // ... authentication service setup
  authentication.register('my-token', new MyTokenStrategy());
}
```

Then add `my-token` to the list in `config/default.json` in `"authentication": { "authStrategies" }` and you can authenticate with `{ strategy: 'my-token', clientToken }`.
