### ISSUE TITLE
User one authentication service for many feathers apps

### ISSUE THREAD

**Issue by Polqk** [feathersjs/feathers#1595]
Hello,

I want to separate my chat api from main api with separate mongodb databases, user table is in main database. I need to have same authentication token for both . What is best way to do it?

Thanks for help.

**Comment by daffl** [comment]
To add more context, if the server share the same secret issues JWTs can be used to authenticate against each server. See also [this answer on Stackoverflow](https://stackoverflow.com/questions/41076627/evaluating-featherjs-authentication-needs/41095638#41095638).
