### ISSUE TITLE
what should i use in the place of "authenticate('jwt', {         allowUnauthenticated: true       })" to run my app?

### ISSUE THREAD

**Issue by somyaranjank** [feathersjs/feathers#1598]
In prevoius version i used 
authenticate('jwt', {
        allowUnauthenticated: true
      })
 to allow both authenticate user and non authenticated user.
When i updated my previous version to new version then it is throwing "Not authenticated "  error.
Is there any method to allow non authenticated user as well as authenticated user in a single phrase like before?

**Comment by daffl** [comment]
The [anonymous authentication strategy](https://docs.feathersjs.com/cookbook/authentication/anonymous.html).
