### ISSUE TITLE
feathers generate service - bug with service template generated code

### ISSUE THREAD

**Issue by Peter-Fogarty** [feathersjs/feathers#1602]
### Steps to reproduce
Hi Team. Apologies if this is logged. I did look but couldn't find it.

I created a new feathers app with feathers generate app. I then created some services with feathers generate service. I then worked on some model definitions in the model directory. And then decided that I needed to start again from scratch, because I hadn't added Auth from the beginning. So I reran feathers generate app, and started running feathers generate service again, but this time starting with a new service that I had not added the first time through. My app then fails to compile with errors the strategies.model.js file. Specifically on line 8

`const strategies = sequelizeClient.define('strategies', {`

it was reporting that sequelizeClient was null.

I created a test project and started again from scratch in a new directory this time and can confirm that when you do a 

`feathers generate app`

it replaces the src/services/index.js with the template version and hence removes all of the 

`app.configure(testService)`

items that were previously in there. 

The problem is that when you rerun feathers generate service for a service with the same name as was originally in the project, it silently does not add it back into the src/services/index.js

Any new services that were not there before are able to be added but attempts to re-add old services silently fail.

**Module versions** (especially the part that's not working): (from my package.json)

```
"dependencies": {
    "@feathersjs/authentication": "^4.3.4",
    "@feathersjs/authentication-local": "^4.3.4",
    "@feathersjs/authentication-oauth": "^4.3.4",
    "@feathersjs/configuration": "^4.3.4",
    "@feathersjs/errors": "^4.3.4",
    "@feathersjs/express": "^4.3.4",
    "@feathersjs/feathers": "^4.3.4",
    "@feathersjs/socketio": "^4.3.4",
    "compression": "^1.7.4",
    "cors": "^2.8.5",
    "feathers-sequelize": "^6.0.2",
    "helmet": "^3.21.1",
    "serve-favicon": "^2.5.0",
    "winston": "^3.2.1"
  },
  "devDependencies": {
    "axios": "^0.19.0",
    "eslint": "^6.5.1",
    "jest": "^24.9.0",
    "nodemon": "^1.19.3"
  }
```

**NodeJS version**:
6.11.3

**Operating System**:
macOS Mojave (10.14.6)

**Comment by daffl** [comment]
I'm not entirely sure I follow but if you run `feathers generate app` again in an existing application it will prompt you to overwrite any existing files. In general, `feathers generate app` also isn't really intended to be run again in an existing application. If you need to add authentication separately you can run `feathers generate authentication`.
