### ISSUE TITLE
How add payload to JWT in v4

### ISSUE THREAD

**Issue by matiaslopezd** [feathersjs/feathers#1610]
Hi! I need add data to payload of JWT. In v3 I implemented this:

```js
class MyCustomLocalVerifier extends Verifier {
   verify(req, username, password, done) {
       ...
       const payload = { id: entity.id, account: entity.account };
       done(null, entity, payload);
       ...
   }
}
```

But now I really not understand how do that. Thanks!

**Comment by daffl** [comment]
You [customize the authentication service](https://docs.feathersjs.com/api/authentication/service.html#customization) which even includes an example for adding a custom payload.

**Comment by matiaslopezd** [comment]
@daffl Thanks! If you can see this issue/purpose in docs :smile:

https://github.com/feathersjs/docs/issues/1378

**Comment by matiaslopezd** [comment]
@daffl I have a problem in authentication strategy migration.

When I try to login with local strategy, returns a entity error:

```js
{
  "name": "NotAuthenticated",
  "message": "Could not get local entity",
  "code": 401,
  "className": "not-authenticated",
  "errors": {}
}
```

In server returns:
```js
express:router <anonymous>  : /login +0ms
  express:router <anonymous>  : /login +0ms
  @feathersjs/authentication/base Strategies parsing HTTP header for authentication information [ 'jwt', 'local' ] +7s
  express:router <anonymous>  : /login +1ms
  @feathersjs/express/rest REST handler calling `create` from `/login` +7s
  @feathersjs/authentication/base Running authenticate for strategy local [ 'jwt', 'local' ] +1ms
  @feathersjs/authentication-local/strategy Finding entity with query {} +4m
  @feathersjs/authentication-local/strategy Verifying password +78ms
  @feathersjs/errors NotAuthenticated(401): Could not get local entity +8s
  @feathersjs/errors {} +0ms
error: NotAuthenticated: Could not get local entity
    at new NotAuthenticated (/home/matias/WebstormProjects/videsk-api/node_modules/@feathersjs/errors/lib/index.js:93:17)
    at LocalStrategy.<anonymous> (/home/matias/WebstormProjects/videsk-api/node_modules/@feathersjs/authentication-local/lib/strategy.js:67:23)
    at Generator.next (<anonymous>)

```

**Comment by daffl** [comment]
This error happens if you did not set the expected `entityId` in your authentication configuration or the entity returned does not have that property name set in `entityId`. If you do not wish to include the user entity, set `entity` to `null` in your authentication configuraiton.

**Comment by matiaslopezd** [comment]
@daffl sorry I don't understand. I need set `entityUsernameField` and `entityPasswordField`? I start with new default configuration of authentication and returns that error. My authentication configuration:

```js
const { AuthenticationService, JWTStrategy } = require('@feathersjs/authentication');
const { expressOauth } = require('@feathersjs/authentication-oauth');
const { LocalStrategy } = require('@feathersjs/authentication-local');

module.exports = app => {
  const authentication = new AuthenticationService(app);

  authentication.register('jwt', new JWTStrategy());
  authentication.register('local', new LocalStrategy());

  app.use('/login', authentication);
  app.configure(expressOauth());
};

```

Where I need set the `entityId`?

**Comment by daffl** [comment]
Since this is a different issue than the original question, please open a new issue with a repository to reproduce your problem. It is likely in the setup of your `users` service. If it is not a standard Feathers database adapter some things need to be configured manually.

**Comment by matiaslopezd** [comment]
Ok @daffl 

https://github.com/feathersjs/feathers/issues/1612

**Comment by matiaslopezd** [comment]
Ok @daffl 

https://github.com/feathersjs/feathers/issues/1610
