### ISSUE TITLE
Where is set entityId?

### ISSUE THREAD

**Issue by matiaslopezd** [feathersjs/feathers#1612]
I started migration v3 to v4 with the new default configuration of authentication and returns `entity` error. My authentication configuration:

```js
const { AuthenticationService, JWTStrategy } = require('@feathersjs/authentication');
const { expressOauth } = require('@feathersjs/authentication-oauth');
const { LocalStrategy } = require('@feathersjs/authentication-local');

module.exports = app => {
  const authentication = new AuthenticationService(app);

  authentication.register('jwt', new JWTStrategy());
  authentication.register('local', new LocalStrategy());

  app.use('/login', authentication);
  app.configure(expressOauth());
};
```
Where I need set the `entityId`?

**Comment by matiaslopezd** [comment]
@daffl referenced to https://github.com/feathersjs/feathers/issues/1610#issuecomment-540172159, I use [feathers-mongoose](https://github.com/feathersjs-ecosystem/feathers-mongoose) database adapter.

**Comment by daffl** [comment]
Your [authentication configuration](https://docs.feathersjs.com/api/authentication/service.html#configuration) is probably not correct. With a normal setup, `entityId` does not need to be set explicitly.

**Comment by codemagician2016** [comment]
> Your configuration is probably not correct. With a normal setup, `entityId` does not need to be set explicitly. All configuration options including `entityId` are documented in the [authentication service settings API](https://docs.feathersjs.com/api/authentication/service.html#configuration).
