### ISSUE TITLE
Oauth authentication redirecting to feathers localhost app running behind nginx

### ISSUE THREAD

**Issue by UDB** [feathersjs/feathers#1615]
I have following config for feathers app running on `localhost:3030` in a **dev** environment
   
    server {
      server_name my.domain.com;
      location / {
          proxy_set_header X-Forwarded-For $remote_addr;
          proxy_set_header Host $http_host;
          proxy_pass "http://localhost:3030";
      }

      listen 443 ssl; # managed by Certbot
      ssl_certificate /etc/letsencrypt/live/my.domain.com/fullchain.pem; # managed by Certbot
      ssl_certificate_key /etc/letsencrypt/live/my.domain.com/privkey.pem; # managed by Certbot
      include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
      ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
      }
      server {
        if ($host = my.domain.com) {
            return 301 https://$host$request_uri;
      } # managed by Certbot

      listen 80;
      server_name my.domain.com;
      return 404; # managed by Certbot
    }

### Expected behavior
In the middle stage on issuing request in browser `my.domain.com/oath/[facebook | google]` the providers after login should go like **`https://my.domain.com/oauth/facebook/callback?code=AQA83S8S7SD-mtbB7JT5R14cohz7VmiEwrCYh_Kbx-...`** then to the actual redirect url.

### Actual behavior
but the provider is going to **`http://localhost:3030/oauth/facebook/callback?code=AQA83S8S7SD-mtbB7JT5R14cohz7VmiEwrCYh_Kbx-...`** after login

**Comment by daffl** [comment]
You have to set the `hostname` in the default configuration (`config/default.json`) accordingly (see [here](https://github.com/feathersjs/feathers-chat/blob/master/config/default.json#L2)).

**Comment by UDB** [comment]
> You have to set the `hostname` and `port` in the default configuration (`config/default.json`) accordingly (see [here](https://github.com/feathersjs/feathers-chat/blob/master/config/default.json#L2)). Alternatively you can set the oAuth configuration redirect URLs explicitly as well (https://github.com/simov/grant#configuration).

tried this also changed the localhot to my.domain.com but after it callback url changed to `http://my.domain.com:3030/...` and this port is not open. 

Even just for the sake of social login I open this port only google will allow `http` protocol but facebook will not as `https` is mandatory now for facebook login redirects

**Comment by UDB** [comment]
@daffl Thanks for suggesting alternative approach. Referred to this [stackoverflow question](https://stackoverflow.com/q/28674550) for nginx configuration and changed `default.json` and added defaults to oauth.
` "oauth": {
      "defaults":{
        "host":"my.domain.com",
        "protocol":"https",
        "transport":"session"
      },....`

facebook was denying access token because of its `https` policy that's why protocol value is https. Now its is working for both google and facebook and redirecting to redirect url with #access_token
