### ISSUE TITLE
How to get socket connection event name ?

### ISSUE THREAD

**Issue by somyaranjank** [feathersjs/feathers#1617]
I have a feathers js server in which i am publishing  a event when user service is patched through channels js. 

I want to catch that event on my another server which does not have feathers. so i am using socket-io-client npm package  to achieve this , but for that i need the event name to catch the published event.
 How can i get the event name , so that i can use it on any other server with direct socket client ?

**Comment by daffl** [comment]
This is documented in the Socket.io client API [section about listening to events](https://docs.feathersjs.com/api/client/socketio.html#listening-to-events).
