### ISSUE TITLE
Question -> fetch original request path

### ISSUE THREAD

**Issue by corepay** [feathersjs/feathers#1619]
Is it possible to fetch the original request path?

I have several hooks that lookup other services before returning response.  One particular service for example - if the resource is not found it returns a 404 and I can throw an after error message there no problem for that code but what I would like to do is throw different messages for that code based on the original path.  

I printed out `context` in the after error of one of the downstream services and only saw the originating path listed among the other services. 

Anything?  I was thinking a solution (or workaround) is to put the path name in the all/before hook to something like `context.params.path` then lookup that  value in the service/error hook...

**Comment by corepay** [comment]
^^ UPDATE:  my workaround will not work - `context.path` returns the current service path so if set in before all hook then will continually be overwritten with current service...

**Comment by daffl** [comment]
Any additional information needs to be passed via `params`:

```js
async context => {
  const otherData = await context.app.service('otherservice').create({ name: 'test' }, {
    originator: context.path
  });
  // Or when using the original params
  const otherData = await context.app.service('otherservice').create({ name: 'test' }, {
    ...context.params,
    originator: context.path
  });
}
```

Then you can check `context.params.originator` in any hook.
