### ISSUE TITLE
Adding a Authentication Servicee throws a TypeError

### ISSUE THREAD

**Issue by pamnanaimanish169** [feathersjs/feathers#1621]
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [x] Tell us what broke. The more detailed the better.

I am writing an application for authenticating a user on certain endpoints. I have written the code (attached below). I am trying to authenticate the user via local strategy i.e. email & password. I am trying to secure the following endpoint: ' /api/authentication' on the PORT 3030(localhost) with the following credentials:
strategy: 'local',
  email: 'someone@gmail.com',
  password: '1234567890'

My directory structure is 
|
|-client
|    |
|    --feathers.js
|-node_modules
|-services
|    |
|     - users.hooks.js
|     - users.service.js
|
|-app.js
|-auth.js
|-package.json

The problem is that whenever I run the code I am running into the error:

**'TypeError: feathers.service is not a function'**

- [x] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc. This makes it much easier for us to debug and issues that have a reproducable example will get higher priority.

This is the link of the repository which contains the code:

https://github.com/pamnanaimanish169/feathersauthentication

### Expected behavior
The endpoint (/api/authentication)  should be authenticated and nobody without authorization should access the endpoint.

### Actual behavior
TypeError: Cannot read property 'create' of undefined

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
+-- @feathersjs/authentication@4.3.5
| +-- @feathersjs/errors@4.3.4
| | `-- debug@4.1.1 deduped
| +-- @feathersjs/feathers@4.3.4 deduped
| +-- @feathersjs/transport-commons@4.3.4
| | +-- @feathersjs/commons@4.3.0 deduped
| | +-- @feathersjs/errors@4.3.4 deduped
| | +-- debug@4.1.1 deduped
| | +-- lodash@4.17.15 deduped
| | `-- radix-router@3.0.1
| +-- debug@4.1.1
| | `-- ms@2.1.2
| +-- jsonwebtoken@8.5.1
| | +-- jws@3.2.2
| | | +-- jwa@1.4.1
| | | | +-- buffer-equal-constant-time@1.0.1
| | | | +-- ecdsa-sig-formatter@1.0.11
| | | | | `-- safe-buffer@5.1.2 deduped
| | | | `-- safe-buffer@5.1.2 deduped
| | | `-- safe-buffer@5.1.2 deduped
| | +-- lodash.includes@4.3.0
| | +-- lodash.isboolean@3.0.3
| | +-- lodash.isinteger@4.0.4
| | +-- lodash.isnumber@3.0.3
| | +-- lodash.isplainobject@4.0.6
| | +-- lodash.isstring@4.0.1
| | +-- lodash.once@4.1.1
| | +-- ms@2.1.2 deduped
| | `-- semver@5.7.1
| +-- lodash@4.17.15
| +-- long-timeout@0.1.1
| `-- uuid@3.3.3
+-- @feathersjs/authentication-local@4.3.5
| +-- @feathersjs/authentication@4.3.5 deduped
| +-- @feathersjs/errors@4.3.4 deduped
| +-- @feathersjs/feathers@4.3.4 deduped
| +-- bcryptjs@2.4.3
| +-- debug@4.1.1 deduped
| `-- lodash@4.17.15 deduped
+-- @feathersjs/authentication-oauth@4.3.5
| +-- @feathersjs/authentication@4.3.5 deduped
| +-- @feathersjs/errors@4.3.4 deduped
| +-- @feathersjs/express@4.3.5 deduped
| +-- @feathersjs/feathers@4.3.4 deduped
| +-- debug@4.1.1 deduped
| +-- express-session@1.17.0
| | +-- cookie@0.4.0
| | +-- cookie-signature@1.0.6
| | +-- debug@2.6.9
| | | `-- ms@2.0.0
| | +-- depd@2.0.0
| | +-- on-headers@1.0.2
| | +-- parseurl@1.3.3
| | +-- safe-buffer@5.2.0
| | `-- uid-safe@2.1.5
| |   `-- random-bytes@1.0.0
| +-- grant@4.6.3
| | +-- qs@6.7.0
| | +-- request-compose@1.2.1
| | `-- request-oauth@0.0.3
| |   +-- oauth-sign@0.8.2
| |   +-- qs@6.7.0 deduped
| |   `-- uuid@3.3.3 deduped
| +-- grant-profile@0.0.5
| | +-- qs@6.9.0
| | +-- request-compose@1.2.1 deduped
| | `-- request-oauth@0.0.3 deduped
| `-- lodash@4.17.15 deduped
+-- @feathersjs/express@4.3.5
| +-- @feathersjs/commons@4.3.0
| +-- @feathersjs/errors@4.3.4 deduped
| +-- @types/express@4.17.1
| | +-- @types/body-parser@1.17.1
| | | +-- @types/connect@3.4.32
| | | | `-- @types/node@12.7.12 deduped
| | | `-- @types/node@12.7.12
| | +-- @types/express-serve-static-core@4.16.9
| | | +-- @types/node@12.7.12 deduped
| | | `-- @types/range-parser@1.2.3
| | `-- @types/serve-static@1.13.3
| |   +-- @types/express-serve-static-core@4.16.9 deduped
| |   `-- @types/mime@2.0.1
| +-- debug@4.1.1 deduped
| +-- express@4.17.1
| | +-- accepts@1.3.7
| | | +-- mime-types@2.1.24
| | | | `-- mime-db@1.40.0
| | | `-- negotiator@0.6.2
| | +-- array-flatten@1.1.1
| | +-- body-parser@1.19.0
| | | +-- bytes@3.1.0
| | | +-- content-type@1.0.4 deduped
| | | +-- debug@2.6.9
| | | | `-- ms@2.0.0
| | | +-- depd@1.1.2 deduped
| | | +-- http-errors@1.7.2
| | | | +-- depd@1.1.2 deduped
| | | | +-- inherits@2.0.3
| | | | +-- setprototypeof@1.1.1 deduped
| | | | +-- statuses@1.5.0 deduped
| | | | `-- toidentifier@1.0.0
| | | +-- iconv-lite@0.4.24
| | | | `-- safer-buffer@2.1.2
| | | +-- on-finished@2.3.0 deduped
| | | +-- qs@6.7.0 deduped
| | | +-- raw-body@2.4.0
| | | | +-- bytes@3.1.0 deduped
| | | | +-- http-errors@1.7.2 deduped
| | | | +-- iconv-lite@0.4.24 deduped
| | | | `-- unpipe@1.0.0 deduped
| | | `-- type-is@1.6.18 deduped
| | +-- content-disposition@0.5.3
| | | `-- safe-buffer@5.1.2 deduped
| | +-- content-type@1.0.4
| | +-- cookie@0.4.0 deduped
| | +-- cookie-signature@1.0.6 deduped
| | +-- debug@2.6.9
| | | `-- ms@2.0.0
| | +-- depd@1.1.2
| | +-- encodeurl@1.0.2
| | +-- escape-html@1.0.3
| | +-- etag@1.8.1
| | +-- finalhandler@1.1.2
| | | +-- debug@2.6.9
| | | | `-- ms@2.0.0
| | | +-- encodeurl@1.0.2 deduped
| | | +-- escape-html@1.0.3 deduped
| | | +-- on-finished@2.3.0 deduped
| | | +-- parseurl@1.3.3 deduped
| | | +-- statuses@1.5.0 deduped
| | | `-- unpipe@1.0.0
| | +-- fresh@0.5.2
| | +-- merge-descriptors@1.0.1
| | +-- methods@1.1.2
| | +-- on-finished@2.3.0
| | | `-- ee-first@1.1.1
| | +-- parseurl@1.3.3 deduped
| | +-- path-to-regexp@0.1.7
| | +-- proxy-addr@2.0.5
| | | +-- forwarded@0.1.2
| | | `-- ipaddr.js@1.9.0
| | +-- qs@6.7.0 deduped
| | +-- range-parser@1.2.1
| | +-- safe-buffer@5.1.2
| | +-- send@0.17.1
| | | +-- debug@2.6.9
| | | | `-- ms@2.0.0
| | | +-- depd@1.1.2 deduped
| | | +-- destroy@1.0.4
| | | +-- encodeurl@1.0.2 deduped
| | | +-- escape-html@1.0.3 deduped
| | | +-- etag@1.8.1 deduped
| | | +-- fresh@0.5.2 deduped
| | | +-- http-errors@1.7.2 deduped
| | | +-- mime@1.6.0
| | | +-- ms@2.1.1
| | | +-- on-finished@2.3.0 deduped
| | | +-- range-parser@1.2.1 deduped
| | | `-- statuses@1.5.0 deduped
| | +-- serve-static@1.14.1
| `-- uberproto@2.0.4
`-- @feathersjs/feathers@4.3.4
  +-- @feathersjs/commons@4.3.0 deduped
  +-- debug@4.1.1 deduped
  +-- events@3.0.0
  `-- uberproto@2.0.4 deduped

**NodeJS version**:

v10.15.3

**Operating System**:
Windows 10 64 Bit

**Browser Version**:
 Chrome 77 on Windows 10

**React Native Version**:

**Module Loader**:

**Comment by daffl** [comment]
Thank you for the repository to reproduce. It looks like it's missing a few important pieces to set up a whole server with authentication. For example it appears the `users` service never gets registered.

I recommend using the `@feathersjs/cli` [as shown in the guide](https://docs.feathersjs.com/guides/) to get your first server project set up with all the necessary settings.

**Comment by pamnanaimanish169** [comment]
Sure, I will try it out and let you know.
