### ISSUE TITLE
feathers-authentication requires @types/jsonwebtoken to be installed in my project

### ISSUE THREAD

**Issue by josephstgh** [feathersjs/feathers#1627]
### Steps to reproduce

Hi,

I am trying to manually upgrade to `feathers-v4`. 

I'm using typescript, if I were to compile my project, the following error would occur.
`node_modules/feathersjs/authentication/lib/core.d.ts`: could not find a declaration file module `jsonwebtoken`. `.../node_modules/jsonwebtoken/index.js` implicitly has an 'any' type. try `npm install @types/jsonwebtoken` if it exists ...

The dependency is in `feathers-authentication` and should be defined in there? Rather than installing it directly in my project?

Am I missing something?

Thanks!

### Expected behavior

The dependency is in `feathers-authentication` and should be defined in there? Rather than installing it directly in my project? I should not be required to install `@types/jsonwebtoken` dependency in my project.

### Actual behavior

I need to install `@types/jsonwebtoken` in my project.

**Comment by daffl** [comment]
Closed via https://github.com/feathersjs/feathers/pull/1626
