### ISSUE TITLE
How to use services in another service

### ISSUE THREAD

**Issue by subash891** [feathersjs/feathers#1628]
this is reset.class.js
const { Service } = require('feathers-sequelize');
const axios = require('axios');
const app = require('../../app');

exports.ResetPassword = class ResetPassword extends Service {

create(data){
  console.log(app);
  const users = app.service('users');
  //   var id = 1;
  //   return users.patch(id,data);
}
};

here how to i use user service,

**Comment by jnardone** [comment]
A service class has a `setup(app)` method that will be called.

You should be able to define a class method:

```
  setup(app) {
    super.setup(app);
    this.app = app;
  }
```

**Comment by daffl** [comment]
As pointed out, this is what [app.setup](https://docs.feathersjs.com/api/services.html#setup-app-path) can be used for. The linked API documentation also has an example on how to use a service in another service.

**Comment by subash891** [comment]
Tnx bro
