### ISSUE TITLE
merge call in authentication breaks references in params

### ISSUE THREAD

**Issue by greyivy** [feathersjs/feathers#1629]
### Steps to reproduce

Create a simple service with the authenticate hook in before[], and a hook that joins a channel in after[] (I know this is frowned upon, but it's the best way I've found to demonstrate this).

Call the service. The connection is added to the channel, however, the socket isn't found in the WeakMap when the time comes to dispatch the event, here:
https://github.com/feathersjs/feathers/blob/ed9e9340c0e3a5cd17fcd4af17ab451de630d70d/packages/transport-commons/src/socket/utils.ts#L44

The event is never dispatched.

Now, before the authenticate hook, add a hook that sets context.params.authenticated to true, bypassing the call to lodash merge.

https://github.com/feathersjs/feathers/blob/71a74765f23c1799546c2816f1d431e0a9a3c8e3/packages/authentication/src/hooks/authenticate.ts#L43-L45

Everything now works correctly because the connection reference is not broken allowing the access to the socket in the WeakMap.

The culprit, I believe, is here:
https://github.com/feathersjs/feathers/blob/71a74765f23c1799546c2816f1d431e0a9a3c8e3/packages/authentication/src/hooks/authenticate.ts#L54

I have also run into issues with this merge when my user object in params contains an object and a key within it is removed during authentication. Due to the way params merged, the key is never removed in the resulting object.

There is also a call to omit that could be causing the issue. I'm not sure and not sure how to diagnose further.

Thanks!

### Expected behavior
The authentication hook should not break references in params.

### Actual behavior
The authentication hook breaks references in params.

### System configuration

node 10
all feathers packages 4.3.7

**Comment by daffl** [comment]
Thanks for the detailed report. This has been fixed in [v4.3.11](https://github.com/feathersjs/feathers/releases/tag/v4.3.11).
