### ISSUE TITLE
v4 migration: calling authenticate in application before hook

### ISSUE THREAD

**Issue by jamesholcomb** [feathersjs/feathers#1631]
In v3, I used the before:all application hook to call `authenticate('jwt')` for all services.  This combined with an `iff()` hook lets me employ an opt-out (rather than opt-in) approach for service authentication.

Doing this in v4 causes this error:

`The authenticate hook does not need to be used on the authentication service`

Is there a way to achieve this in v4?

**Comment by daffl** [comment]
If you use the opt-out for the `/authentication` service everything should work as before.
