### ISSUE TITLE
User hook exposing password on error with protect.all hook enabled

### ISSUE THREAD

**Issue by StevePavlin** [feathersjs/feathers#1633]
Same issue as this old one: [https://github.com/feathersjs-ecosystem/authentication/issues/691](https://github.com/feathersjs-ecosystem/authentication/issues/691), except the error payload is slightly different. This is what I'm seeing when registering a duplicate user:

![53242b59ad23d7109a6434552a878f8c](https://user-images.githubusercontent.com/8277473/67186603-61af8100-f3b6-11e9-9e9b-02f770584fd8.png)

Exact same configuration using the feathers-generator as the above issue. This is my users.hooks:
```
const { authenticate } = require('@feathersjs/authentication').hooks;

const {
  hashPassword, protect
} = require('@feathersjs/authentication-local').hooks;

module.exports = {
  before: {
    all: [],
    find: [ authenticate('jwt') ],
    get: [ authenticate('jwt') ],
    create: [ hashPassword('password') ],
    update: [ hashPassword('password'),  authenticate('jwt') ],
    patch: [ hashPassword('password'),  authenticate('jwt') ],
    remove: [ authenticate('jwt') ]
  },

  after: {
    all: [ 
      // Make sure the password field is never sent to the client
      // Always must be the last hook
      protect('password')
    ],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  },

  error: {
    all: [],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  }
};

```

I can fix it by adding a custom error.all hook:
```
    all: [
      async context => {
        const { error } = context;


        if (
          Array.isArray(error.errors)
          && error.errors.length > 0
          && error.errors[0].instance
          && error.errors[0].instance.password
        ) {
          delete error.errors[0].instance.password;
        }

        return context;
      },
    ]
```

... but I'm curious if there's a configuration option I'm missing, or its a bug in the package itself. Thanks, awesome framework by the way!

**Comment by jnardone** [comment]
In this case this is the data sent up from the client, not the data already stored in the DB?  

The after hooks etc. are protecting the data retrieved from the data store and returned to the client, but these values look to be "inbound" values from the client.  

Which database etc. adapter are you using?

**Comment by StevePavlin** [comment]
I'm using feathers-sequelize. The other issue I noted was using the same adapter, might be something to do with the incoming data like you said.

**Comment by AnthonyDugarte** [comment]
Is there any update about this? I am also using feathers-sequelize and I am facing the same error about hashed password being sent through the error message.

**Comment by daffl** [comment]
This is a Sequelize error handling issue. Possible solutions are

- Don't pass any errors back in https://github.com/feathersjs-ecosystem/feathers-sequelize/blob/master/lib/utils.js#L17
-  Modify the error to what you want an `error` hook

**Comment by daffl** [comment]
Closing this here since it is Sequelize specific and the error shows the _hashed password that the user submitted in the same request_, not an existing hashed password.
