### ISSUE TITLE
Prevent concurrent processing in feather.js

### ISSUE THREAD

**Issue by mohanagy** [feathersjs/feathers#1634]
I still faceing a problem with  concurrent processing in feather.js.
so what is going on is

> REQUEST1 ---> DATABASE_READ
> REQUEST2 ---> DATABASE_READ
> DATABASE_READ complete ---> EXPENSIVE_OP() --> REQUEST1_END
> DATABASE_READ complete ---> EXPENSIVE_OP() --> REQUEST2_END
> 
and this will cause a duplication and many other issues 
but what I'm looking for is 
> REQUEST1 ---> DATABASE_READ
> DATABASE_READ complete ---> DATABASE_UPDATE
> DATABASE_UPDATE complete ---> REQUEST2 ---> DATABASE_READ ––> REQUEST2_END
>                          ---> EXPENSIVE_OP() --> REQUEST1_END
> 

**Module versions** :
    "@feathersjs/express": "^1.3.1",
    "@feathersjs/feathers": "^3.3.1",
**NodeJS version**:
v10.16.3
**Operating System**:
 osx 10.15

**Comment by KidkArolis** [comment]
https://www.npmjs.com/package/redlock

**Comment by mohanagy** [comment]
seems like it should be used with Redis which is not used in my system

**Comment by jnardone** [comment]
> > REQUEST1 ---> DATABASE_READ
> > DATABASE_READ complete ---> DATABASE_UPDATE
> > DATABASE_UPDATE complete ---> REQUEST2 ---> DATABASE_READ ––> REQUEST2_END
> > ---> EXPENSIVE_OP() --> REQUEST1_END

I'm not sure how this is a feathers problem.  You have requests inside requests here and an expensive operation that makes no sense in your flow.

What is your API supposed to do?  Each API call is meant to be independent.  If you need to block at certain points then you can lock parts of a given transaction (using the DB, or a data store, or something else) but that's not what you're describing above.  Should "EXPENSIVE_OP" run after every request?  If not, what are the rules?  Should REQUEST1 finish before REQUEST2 is served?

**Comment by daffl** [comment]
I'm going to close this since we don't have more information and as mentioned it isn't really a Feathers issue.
