### ISSUE TITLE
Data Not Saving to Database

### ISSUE THREAD

**Issue by PatrickLumenus** [feathersjs/feathers#1635]
I have this problem in my FeathersJS Application. I have a user Mongoose model like below.

// users-model.js - A mongoose model
//
// See http://mongoosejs.com/docs/models.html
// for more of what you can do here.
import { Application } from '../declarations';

export default function (app: Application) {
  const mongooseClient = app.get('mongooseClient');
  const users = new mongooseClient.Schema({

    first_name: { type: String, },
    last_name: { type: String, },
    email: {type: String, unique: true, lowercase: true},
    password: { type: String },
    dob: {type: Date, },

  }, {
    timestamps: true
  });

  return mongooseClient.model('users', users);
}
However, when I call my api to create a user, like this.

POST /users?first_name=Patrick&amp; last_name=Lumenus&amp; email=abc@gmail.com&amp; password=ABC123&amp; dob=1991-10-10 HTTP/1.1
Host: localhost:3030
User-Agent: PostmanRuntime/7.18.0
Accept: */*
Cache-Control: no-cache
Postman-Token: 2749d3e8-a7fc-45f8-96ae-0b04a4c51bc0,b1fb4da4-b9e1-4824-917a-5965250d6f9b
Host: localhost:3030
Accept-Encoding: gzip, deflate
Content-Length: 0
Connection: keep-alive
cache-control: no-cache
It only seems to save the generated ObjectID and times stamps. It does not save the data I passed in for the new user. Here's the data in my database that was created.

{"_id":{"$oid":"5dade949612103041bd7653c"},"createdAt":{"$date":{"$numberLong":"1571678537003"}},"updatedAt":{"$date":{"$numberLong":"1571678537003"}},"__v":{"$numberInt":"0"}}
Any advice on what I am doing wrong? This is a brand new Feathers project by the way. I have not added any hooks or any other additional code besides the above.

Well, I did make a tweak to my mongoose.ts file, as recommended, to use the updated engine. Although, I only added the useUnifiedTopology: true argument to silence the warning I was getting on app startup.

import mongoose from 'mongoose';
import { Application } from './declarations';
import logger from './logger';

export default function (app: Application) {
  mongoose.connect(
    app.get('mongodb'),
    { useCreateIndex: true, useNewUrlParser: true, useUnifiedTopology: true }
  ).catch(err => {
    logger.error(err);
    process.exit(1);
  });

  mongoose.Promise = global.Promise;

  app.set('mongooseClient', mongoose);
}

**Comment by daffl** [comment]
That's not how POST requests should come in. Feathers is expecting a JSON or url encoded body not a query string.
