### ISSUE TITLE
About express-session

### ISSUE THREAD

**Issue by somyaranjank** [feathersjs/feathers#1638]
When i am deploying my feathers app in production it shows a warning, i could not found the reason.
If any one faced this and resolved this please give any suggestions.
Thanks in advance.

This is the warning
"connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
"

**Comment by krynne** [comment]
Same problem here...

**Comment by KidkArolis** [comment]
See `expressSession` option in oauth middleware: https://docs.feathersjs.com/api/authentication/oauth.html#setup-express.

Basically, when you install `oauth` middleware, you should also configure your `express-session`. For example:

```js
  const store = new PgSessionStore({
    knex: app.get('knex'),
    log: log('session'),
  })

  // Configure your express session instance
  const expressSession = session({
    secret: app.get('authentication').sessionCookieSecret,
    resave: false,
    saveUninitialized: false,
    cookie: {
      maxAge: 30 * 60 * 1000,
    },
    store,
  })

  app.sessionStore = store

  const authentication = new CustomAuthenticationService(app)

  authentication.register('local', new CustomLocalStrategy())
  authentication.register('jwt', new CustomJWTStrategy())
  authentication.register('google', new CustomGoogleStrategy())

  app.use('/api/authentication', authentication)
  app.configure(oauth({ expressSession }))
```

You can use whatever store is appropriate in your application - redis, postgres, mongo, etc. See this for the list of available express-session plugins: https://github.com/expressjs/session.

Note - all of this is only necessary when using OAuth.

**Comment by daffl** [comment]
This has [now been added to the documentation](https://docs.feathersjs.com/api/authentication/oauth.html#redirects)

**Comment by somyaranjank** [comment]
Thanks Everyone i got  some lead, i will implement that close the issue.
