### ISSUE TITLE
Oauth when state param is required 

### ISSUE THREAD

**Issue by rxb** [feathersjs/feathers#1639]
I'm working on implementing Reddit Oauth in my feathers app. I have Oauth working with Facebook and Google, but not Reddit (/oauth/reddit/callback returns a 403 error). It seems the big difference with Reddit Oauth is that the state param is required. I have a vague sense that the state param requires sessions or some kind of persistence on the feathers server, but I'm not really clear on how it works. Any nudges in the correct direction would be greatly appreciated!

@RickEyre @davejtoews any luck sorting things out from this issue in the pre-v4 feather authentication? https://github.com/feathersjs-ecosystem/authentication/issues/677

**Comment by davejtoews** [comment]
Never got this working myself, no.

**Comment by flyboarder** [comment]
@rxb could you share your oAuth config for Reddit?

**Comment by daffl** [comment]
State can be enabled by adding `state: true` to [your configuration](https://github.com/simov/grant#configuration). I think I'm going to copy that part from Grants docs.

**Comment by rxb** [comment]
Thanks! That was one half, but the other half was a reddit-specific misconfiguration over in grant-profile. `profile_url` needs to be `https://oauth.reddit.com/api/v1/me` when you're accessing via oauth token instead of the `api.reddit.com` host they have listed. That was causing the 403. 

I'll file a PR over at grand-profile, but for now, any feathers users needing to auth with reddit can override in the config like this:

```
"reddit": {
        "key": "...",
        "secret": "...",
        "scope": ["identity"],
        "duration": "temporary",
        "state": true,
        "profile_url": "https://oauth.reddit.com/api/v1/me"
      }
```

**Comment by simov** [comment]
:wave: published the updated Reddit URL and a few others in v0.0.7 Once I go through all of them I'll bump the version to v1 so it will be easier to receive updates with a `^`.
