### ISSUE TITLE
Convert database adapters to support promises.

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers#164]
I'm not sure whether we should kill callbacks altogether but we should definitely support promises. We could potentially use native promises (since node is now v4+) or we could use [bluebird](https://github.com/petkaantonov/bluebird). I'm leaning a bit more towards bluebird.

Database adapters needing converting:

- [ ] mongoose
- [ ] knex
- [ ] waterline
- [ ] sequelize
- [ ] nedb
- [x] memory
- [ ] mongodb

This should probably also be done at the same time as #125.

**Comment by daffl** [comment]
Reference implementation is being worked on at https://github.com/feathersjs/feathers-memory/tree/es6. With the bugfixes in latest Uberproto and Rubberduck it should be fully compatible with Feathers 1.x while supporting ES6 syntax, Promises and pagination.

**Comment by ekryski** [comment]
:+1: Looks like you're using native promises. Totally cool with that as it's less overhead. I'm not sure how Babel translates that, but @daffl do you think this will this have any backwards compatibility issues?

**Comment by daffl** [comment]
I thought it inlines the polyfills but apparently you need to add https://babeljs.io/docs/usage/polyfill/ as a dependency.

**Comment by daffl** [comment]
This is also being tracked in #170
