### ISSUE TITLE
Is returning the hook context from a hook required if hook object ref is unchanged?

### ISSUE THREAD

**Issue by jnardone** [feathersjs/feathers#1644]
A hook generally follows the form

```
const myHook = hook => {
  // do stuff
  if (hook.type)...

  // optionally change stuff in hook
  hook.result = {...};

  return hook;  // <-- do I need to do this?  Even if I modified data inside 'hook'?
}
```

My question: if we don't create a new hook object but simply mutate the existing one, is `return hook` necessary?  I don't think it is but I haven't seen it explicitly documented anywhere.

I do realize that if you

```
  ...
  // you can also change the entire hook object
  const newHook = Object.assign({}, hook);

  return newHook;  // you MUST do this
```

then you have to explicitly return the context.

Is there a preferred "you should always return the hook context from any hook that modifies hook data?" style or convention to follow?

**Comment by daffl** [comment]
It is not required, a hook can also return nothing (see [Hooks API](https://docs.feathersjs.com/api/hooks.html#hook-functions)).

Returning a new context will probably be deprecated with the new hook system as discussed in https://github.com/feathersjs/feathers/issues/1443

**Comment by jnardone** [comment]
ok, so if #1433 goes forward, there's no real use case for having to return the context since it'll be the one same object all the way through

**Comment by daffl** [comment]
It already is if your hook returns nothing. You can already safely remove `return hook;` from all your hooks.

**Comment by jnardone** [comment]
Superb.  Thanks.
