### ISSUE TITLE
Update or create hook always creating new record

### ISSUE THREAD

**Issue by fortydegrees** [feathersjs/feathers#1649]
I've managed to hook FeathersJS up to my MySQL database with sequelize and have the basic flow with hooks etc. working well. 

I want it so that a user can submit a prediction for an event. If they already have an answer, update their record; if not, create a new one.

My hook is something like:

```
const { Answer } = require('../sequelize')

module.exports = function (options = {}) {
  // eslint-disable-line no-unused-vars
  return async context => { //updates if entry already exists
    const { data } = context
    const { user } = context.params
    const { app, method, result, params } = context

    let questionId = data.questionId
    let userId = user._id

    Answer.findOne({ where: { questionId, userId } }).then(a => {
      if (a != null) {
        a.update({
          questionId: data.questionId,
          userAnswer: data.answer,
          userId: user._id
        }).then(() => {
return Promise.resolve()
        })
      } else {
        Answer.create({
          questionId: data.questionId,
          userAnswer: data.answer,
          userId: user._id
        }).then(() => {
return Promise.resolve()
        })
      }
    })
    return context
  }
}
```

While this does successfully 'update' the record if it exists, it also creates a new record will all NULL apart from 'questionId'.

I've tried multiple variations like removing the return, removing the Promise.resolve() etc.

I realise I can probably do this client side by calling patch(), and if that fails then do create. However I feel like best practise would tell me to do this server side?

I also feel like I shouldn't be calling sequelize functions in my hook and that that's also not best practise, so advice on that would be apreciated too!

**Comment by Gektor0508** [comment]
There is no need to call _patch_ from the client side because you can call it internally.
I would suggest the following: 
1. You can try to find the record using **.find()**.
2. If it exists patch it and skip the create service call
3. If not: Create the record

**You have to use this as a BEFORE hook on CREATE.** And don't forget to set **context.result**  otherwise the actual create service call will be called too. 


```javascript
const patchOrCreate = async context => {

const { data, service, params } = context;
  const { questionId, answer: userAnswer } = data;
  let userId = params.user._id;

  const payload = { questionId, userAnswer, userId };

  // try to find the record ( we destructure the first entry from array)
  const [record] = await service.find({ query: { questionId, userId }, paginate: false });

  // if records exists -> patch it using id and return
    if(record){
      // important set the context.result so that the actual service call (CREATE) will be skiped
      context.result =  await service.patch(record.id, payload); // else patch it
      return context;
    }

    // rename fields in data to match fields of sequelize 
    context.data = payload;

  return context;
};
```

**Comment by fortydegrees** [comment]
@Gektor0508 , that answer worked absolutely perfect and has helped me understand what's going on with feathers a lot more. Thanks very much!
