### ISSUE TITLE
Update documentation on service adapters for new special params

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers#165]
The new params are:

- [x] $in
- [x] $nin
- [x] $lt
- [x] $lte
- [x] $gt
- [x] $gte
- [x] $or
- [x] $not

**Comment by daffl** [comment]
I added this in https://github.com/feathersjs/feathers-service-tests/commit/fe6a9148dc82cbb03b040b283c9aa2bd67a5b6a6. https://github.com/feathersjs/feathers-service-tests/blob/master/docs.md is the document that should be updated when the spec changes and then copied to all service adapters that implement it.
