### ISSUE TITLE
npm run dev failed when generating a new ts app

### ISSUE THREAD

**Issue by YUFENGWANG** [feathersjs/feathers#1653]
### Steps to reproduce

Just follow the instrutions and generated a new app. when I run  `npm run dev`, things seem not working. Here is the error 

```js
> feathers-chat@0.0.0 dev /Users/richard/me/feathers-chat
> ts-node-dev --no-notify src/

Using ts-node version 8.4.1, typescript version 3.6.4
[ERROR] 23:58:58 ⨯ Unable to compile TypeScript:
src/channels.ts:5:17 - error TS2339: Property 'channel' does not exist on type 'Application<ServiceTypes>'.

5   if(typeof app.channel !== 'function') {
                  ~~~~~~~
src/channels.ts:12:9 - error TS2339: Property 'channel' does not exist on type 'Application<ServiceTypes>'.

12     app.channel('anonymous').join(connection);
           ~~~~~~~
src/channels.ts:23:11 - error TS2339: Property 'channel' does not exist on type 'Application<ServiceTypes>'.

23       app.channel('anonymous').leave(connection);
             ~~~~~~~
src/channels.ts:26:11 - error TS2339: Property 'channel' does not exist on type 'Application<ServiceTypes>'.

26       app.channel('authenticated').join(connection);
             ~~~~~~~
src/channels.ts:43:7 - error TS2339: Property 'publish' does not exist on type 'Application<ServiceTypes>'.

43   app.publish((data: any, hook: HookContext) => {
         ~~~~~~~
src/channels.ts:50:16 - error TS2339: Property 'channel' does not exist on type 'Application<ServiceTypes>'.

50     return app.channel('authenticated');
```
![image](https://user-images.githubusercontent.com/12859005/67695705-7c01e400-f9e0-11e9-8df0-b99b3fe71a18.png)

### Expected behavior
Run app correctly
### Actual behavior
App crashed

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**: v10.15.0

**Operating System**: MacOS majave

**Browser Version**: N/A

**React Native Version**: N/A

**Module Loader**:

**Comment by daffl** [comment]
I am not able to reproduce with the same settings in `@feathersjs/cli` v4.2.2. This error probably comes from a missing `import '@feathersjs/transport-commons';`.

**Comment by YUFENGWANG** [comment]
@daffl I have to install '@feathersjs/transport-commons' by hand and errors are all gone. why this module isn't installed by cli?

**Comment by daffl** [comment]
I just noticed that it is pulled in by the authentication file. So you're right, that import should be moved.
