### ISSUE TITLE
local authentication configuration is not working

### ISSUE THREAD

**Issue by Chellhooo** [feathersjs/feathers#1654]
hi.
After i update feathers to v4，following error occurs `Error: 'local' authentication strategy requires a 'usernameField' setting`.

I do as what the document said, do I miss something important？:(

my authentication.js is following.
```js
const { AuthenticationService, JWTStrategy } = require('@feathersjs/authentication');
const { LocalStrategy } = require('@feathersjs/authentication-local');
const { expressOauth } = require('@feathersjs/authentication-oauth');

module.exports = app => {
  const config = app.get('authentication');
  const authService = new AuthenticationService(app, config);

  authService.register('jwt', new JWTStrategy());
  authService.register('local', new LocalStrategy());

  app.use('/authentication', authService);
  app.configure(expressOauth());
};

```

and my authentication config like this: 

```json 
"authentication": {
    "local": {
      "usernameField": "email",
      "passwordField": "password"
    },
  },

```

**Comment by daffl** [comment]
It should be:

```js
const { AuthenticationService, JWTStrategy } = require('@feathersjs/authentication');
const { LocalStrategy } = require('@feathersjs/authentication-local');
const { expressOauth } = require('@feathersjs/authentication-oauth');

module.exports = app => {
  const authService = new AuthenticationService(app);

  authService.register('jwt', new JWTStrategy());
  authService.register('local', new LocalStrategy());

  app.use('/authentication', authService);
  app.configure(expressOauth());
};
```

Also see [API docs](https://docs.feathersjs.com/api/authentication/service.html#setup)

**Comment by screets** [comment]
Any solution so far?

**Comment by ericuldall** [comment]
I'm implementing this the way you suggest @daffl, yet I'm still getting an error saying I haven't set the usernameField config. Any thoughts?

**Comment by screets** [comment]
Hey Feathersjs/feathers,

We got your help request!
One of our agents will respond to you, asap (usually in *1 business day*).

Note that we don't work on weekends.
However, if we release a major update recently, we are following the
issues.

For support questions, please also email us *Screets API key* which is
required for support questions. If you already included in your message,
you don't need to do anything else.
{#HS:1130426287-6044#}
