### ISSUE TITLE
[FR] authentication-local: hashPassword() with source field

### ISSUE THREAD

**Issue by rayfoss** [feathersjs/feathers#1656]
Currently the client sends in an object with a password field containing a plain text password.

user.password on the server is not user.password on the client. This inconsistency can cause problems. An easy truthful solution is to use 'newPassword' and save the hash to 'password' from there. This simplifies hooks as you can just discard the password field on create/patch/update, and only allow newPassword.

You can run into problems with this when caching, testing or converting patch calls to update. I can PR if this is a welcome feature.

Proposed Spec:
```js
hashPassword('password', {source: 'newPassword'})
// hashes newPassword, saves to password, discards newPassword
```

Update:
This would also be. A good time to implement an "enforceNew" parameter, where given an old hash or array of hashes, it would go through and make sure non of them are it, then add the old hash to the list. Or fail validation if not.

**Comment by daffl** [comment]
Having a difference source field sounds reasonable to me,  a PR with tests and according updates in the documentation would be welcome.
