### ISSUE TITLE
Setup public access to the slack channel

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers#166]
Take a look at [this post](https://wiredcraft.com/blog/using-slack-as-a-public-chat/) on how to setup [slackin](https://github.com/rauchg/slackin).

We should then add this to the website and all our README's instead of Gitter.

**Comment by loris** [comment]
Are you sure about using Slack? All the rage right now is about moving out FOSS projects from Slack because it was not intended to host them in the first place (hard limit on the number of users, etc.)
See: https://drewdevault.com/2015/11/01/Please-stop-using-slack.html

**Comment by daffl** [comment]
Well GitHub isn't open source and has a paid plan, too and we're using it to host the project.

Just keeping the options open. There's still a Gitter channel and if there is enough members I am going to pay for a https://sameroom.io tube to hook them all together. At least @ekryski, @marshallswain and I have Slack open all day for work already though. It's very annoying having to open five different messaging clients in the morning (at one time I had to run Skype, IRC, HipChat and Slack).

**Comment by loris** [comment]
I do agree, and I also forget to launch Gitter, whereas my Slack is always open for work. So personally, I’m all for Slack. Was just warning about complaints from other big open source projects which had to move away from Slack recently.
PS: Would be glad to be added to the Slack channel (loris.guignard@gmail.com)

**Comment by ekryski** [comment]
Now the public can join us on slack. Simply go to http://slack.feathersjs.com.

I'll add SSL certs for that stuff in a bit.

**Comment by gurisko** [comment]
Hey guys. Did you manage to make this work? I just see token_revoked when trying to get the invite.

**Comment by ekryski** [comment]
Ah shit. I got a notification from slack a while back but thought it was from something else. I will fix this right away

**Comment by ekryski** [comment]
When I was dicking around a long time ago I accidentally published our slack token in commented out code :scream:. Slack was nice enough to notify me and automatically revoke it so I've fixed it now with a new token and made sure that it's not published anywhere.
