### ISSUE TITLE
Socketio is missing the original request headers

### ISSUE THREAD

**Issue by averri** [feathersjs/feathers#1662]
### Steps to reproduce

Configure any application to use Socketio. Let the client connect to the server via websockets.

```javascript
app.configure(socketio(function (io) {
  io.on('connection', function (socket) {
   // No information about original headers here, impossible to get user-agent.
  })
}))
```

### Expected behavior
According to Socketio documentation, the `socket` object should include the original request
with the headers (ref. https://socket.io/docs/server-api/)

### Actual behavior
The `socket` does not contain the original headers, useful for getting the `user-agent` and other important headers.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

```json
"dependencies": {
    "@feathersjs/authentication": "^4.3.10",
    "@feathersjs/authentication-local": "^4.3.10",
    "@feathersjs/authentication-oauth": "^4.3.10",
    "@feathersjs/configuration": "^4.3.10",
    "@feathersjs/errors": "^4.3.10",
    "@feathersjs/express": "^4.3.10",
    "@feathersjs/feathers": "^4.3.10",
    "@feathersjs/socketio": "^4.3.10",
    "@hapi/joi": "15.1.1",
    "aqb": "^2.1.0",
    "arangojs": "^6.11.1",
    "compression": "^1.7.4",
    "cors": "^2.8.5",
    "date-fns": "^2.6.0",
    "express-handlebars": "^3.1.0",
    "feathers-authentication-hooks": "^1.0.1",
    "feathers-hooks-common": "^4.20.7",
    "feathers-permissions": "^1.1.0",
    "feathers-sync": "^1.1.3",
    "glob": "^7.1.5",
    "helmet": "^3.20.0",
    "joi-errors-for-forms": "^0.2.6",
    "lodash": "^4.17.15",
    "nodemailer": "^6.3.1",
    "nodemailer-express-handlebars": "^3.1.0",
    "prom-client": "^11.5.3",
    "prometheus-api-metrics": "^2.2.3",
    "qrcode": "^1.4.2",
    "rate-limiter-flexible": "^1.1.6",
    "serve-favicon": "^2.5.0",
    "speakeasy": "^2.0.0",
    "stackimpact": "^1.3.21",
    "ua-parser-js": "^0.7.20",
    "uid-generator": "^2.0.0",
    "uuid": "^3.3.3",
    "winston": "^3.0.0"
  }
```
**NodeJS version**: 12.13.0

**Operating System**: Linux Ubuntu 18.04

**Browser Version**: Chrome

**Module Loader**: require

**Comment by daffl** [comment]
The Socket.io handshake headers are available in [socket.headers.handshake](https://socket.io/docs/server-api/#socket-handshake):

```js
app.configure(socketio(function (io) {
  io.on('connection', function (socket) {
    console.log(socket.handshake.headers)
  })
}))
```

**Comment by ericuldall** [comment]
@daffl I see the headers in my application but for some reason the extraHeaders from the socket client aren't showing up...should those be included or would they be elsewhere?
