### ISSUE TITLE
CrosswordSolver on feathersjs.com

### ISSUE THREAD

**Issue by emraeshine3** [feathersjs/feathers#1663]
Hi there,

I hope you had a wonderful weekend! My name is Emily with CrosswordSolver.com, a sponsor of feathersjs.com.

We were hoping to get our logo & link added to your website. Is this possible? If so, would you need our logo?

Let me know and thank you very much for your help!

Smiles,
Emily

**Comment by edwardsmarkf** [comment]
it looks as if your website is a way for people to "cheat" on crossword
puzzles!

Thank you,

Mark Edwards


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by daffl** [comment]
Thank you but no.
