### ISSUE TITLE
How to call a middleware from @feathersjs/client?

### ISSUE THREAD

**Issue by skaptox** [feathersjs/feathers#1670]
### Expected behavior
Hello, there is something like

```
const response = await api.middleware('terms-and-conditions').get();
```

This is my middleware in the backend

```
app.use("/terms-and-conditions", (req: Request, res: any, next: any) => {
    res.sendFile(path.join(app.get("public") + "/terms-and-conditions.html"));
});

```

I want to get plain html in react native app. 

### Actual behavior
I have to use axios and fetch manually the data or use a service instead.

**Comment by marshallswain** [comment]
Feathers runs on top of Express, by default, so you can research how to do this with Express.  If you expect to receive realtime notifications for your middleware, you might want to convert it to a service (a custom service if `terms-and-conditions` isn't a database resource.
