### ISSUE TITLE
Oauth # hash based redirects

### ISSUE THREAD

**Issue by ikakosta** [feathersjs/feathers#1672]
Hash-based redirects are not possible.
I'm tried to redirect to Vuejs frontend with Vue-router (history) in hash mode. It's working when redirecting to the landing page but not to the dashboard route.
This is a URL I'm getting is:
`www.sitename.com/#/dashboard#access_token=eyJhbG...`

 I'm looking solution to customizing the getRedirect method of the oAuth strategy. I'm not sure how to do that, maybe sending authentication result in JSON?

**Comment by daffl** [comment]
This has been improved in [v4.3.11](https://github.com/feathersjs/feathers/releases/tag/v4.3.11). It will now redirect to `www.sitename.com/#/dashboard?access_token=eyJhbG...`. The `access_token=eyJhbG...` part needs to be in the hash in order for the client to retrieve that information unless you customize it yourself.
