### ISSUE TITLE
On a newly generated app with the CLI on a typical email password login form will generate a new user if user does not exist

### ISSUE THREAD

**Issue by mylastore** [feathersjs/feathers#1674]
Since the endpoint is /users,  on a typical login form if user is not created yet I will just create a new one.  What am I missing here is this normal or there should be a /users/login /users/signup ?

**Comment by daffl** [comment]
Please have a look at the [authentication chapter of the guide](https://docs.feathersjs.com/guides/basics/authentication.html) which explains that `POST /users` will create a new user and `POST /authentication` will create an authentication token (login).
