### ISSUE TITLE
create custom events | TypeScript

### ISSUE THREAD

**Issue by gromov-io** [feathersjs/feathers#1680]
Please, tell me how to add custom events. I create a service through feathers generate. And then nothing is clear, what is described in the documentation - does not work, typescript does not even allow me to compile

**Comment by daffl** [comment]
The typings include settings events. As [documented here](https://docs.feathersjs.com/api/events.html#custom-events) for an existing adapter, the `events` array can be added in the service options in your `<name>.service.ts` file (e.g. [here](https://github.com/feathersjs/feathers-chat-ts/blob/master/src/services/messages/messages.service.ts#L19)):

```ts
  const options = {
    Model,
    paginate,
   events: [ 'my-event' ]
  };

  // Initialize our service with any options it requires
  app.use('/messages', new Messages(options, app));
```
