### ISSUE TITLE
[FR] Provide offline documentation in Dash docset format

### ISSUE THREAD

**Issue by rayfoss** [feathersjs/feathers#1681]
### Steps to reproduce

Feathers is missing from the conversation in the popular Dash based docs apps, in https://devdocs.io/   etc... the list of Js projects that support it is very long... our absence is disconcerting

It seems to be easy... we just need to wget it, ship it and automate it.

## use case
The benefits over PDF are, better search, more exposure, centralized docs for all major components, easier to manage updates for all the docs, easier to ensure your offline docs are good to go before an offline hiatus, easier to backup the offline docs...

#### Apps that support Dash:
Dash, Mac, iOS, Android
Zeal, Linux, Windows
Poopdocs, windows
https://devdocs.io/: Web pwa with offline sync

#### Projects that support Dash
React, Vue, NodeJS, Mongoose, Vuex, Qt, SVG, Typescript, MariaDB

**Comment by daffl** [comment]
If someone wants to own this, awesome. It should indeed just mean just publishing the docs site build there as well.
