### ISSUE TITLE
Error with authentication after migration

### ISSUE THREAD

**Issue by andysay** [feathersjs/feathers#1686]
Hello, i'm try upgrade feathers from v3 to v4 ,

i'm have config

`  
"authentication": {
    "entity": "user",
    "service": "users",
    "secret": "***",
    "authStrategies": [
      "jwt",
      "local"
    ],
    "jwtOptions": {
      "header": {
        "typ": "access"
      },
      "audience": "localhost",
      "issuer": "feathers",
      "algorithm": "HS256",
      "expiresIn": "1d"
    },
    "local": {
      "usernameField": "email",
      "passwordField": "password"
    }
  },
`

but console give that 

@feathersjs/authentication/lib/hooks/authenticate.js:23
    if (!originalSettings || settings.strategies.length === 0) {

TypeError: Cannot read property 'length' of undefined

**Comment by daffl** [comment]
Your authenticate hook needs a strategy name

```js
authenticate('jwt')
```

**Comment by andysay** [comment]
ah ok , before was 

  create: [
     // You can chain multiple strategies
   
     auth.hooks.authenticate(['jwt', 'local'])
    ],

**Comment by daffl** [comment]
It would be

```js
auth.hooks.authenticate('jwt', 'local')
```

Now but it is very unlikely the `local` strategy will be used with the hook since the hook no longer needs to be added to the `/authenticate` service.
