### ISSUE TITLE
Config for making default "GET" instead of "FIND"?

### ISSUE THREAD

**Issue by SephReed** [feathersjs/feathers#1689]
### Steps to reproduce
```
app.use("/test", {
	get: async () => "hello",
} as any);

app.listen(4000, () => {
  console.log('Listening at localhost:4000...')
});
```

Then navigate to localhost:4000/test

### Expected behavior
Expected response "hello".  But if FIND is going to be the default, there should be someway to make it so GET is instead.  

### Actual behavior
> MethodNotAllowed: Method `find` is not supported by this endpoint.

**Comment by SephReed** [comment]
<img width="379" alt="Screen Shot 2019-11-18 at 5 02 06 PM" src="https://user-images.githubusercontent.com/14002040/69101428-3a83b800-0a25-11ea-9045-5e283400c083.png">

**Comment by danlupascu** [comment]
Get and find are not the same.

Get is: /service/id
Find is: /service

The HTTP method though is the same, which is "GET", because there's no "FIND" http method.

If you want to receive back "hello", then use this url: http://localhost:4000/test/any_id_here

**Comment by SephReed** [comment]
I figured out that choice had been made, and I wanted to undo it.  I found other means.
