### ISSUE TITLE
how to broadcast message created through rest

### ISSUE THREAD

**Issue by sgireddy** [feathersjs/feathers#169]
I am supporting both REST & socket endpoints and would like to broadcast messages created via rest endpoint (just like those created through sockets). Is it possible? How can I access socket object from REST handlers? 

I could quickly establish a socket, connect, broadcast but I think this is not optimal.

**Comment by daffl** [comment]
Feathers does broadcast all changes to all connected websocket clients no matter where they came from (see the FAQ at http://feathersjs.com/support/#toc4).
However, there is no way around having an open websocket connection to receive those updates. REST connections can't receive push updates from the server.
I know that many people open websocket connections only to listen to (`created`, `patched`, `updated`, `removed`) messages and then make other changes via the REST APIs - but the sockets do have to stay open.

**Comment by sgireddy** [comment]
I am working on a signals dashboard for a corporate company (https://github.com/mattkauffman/signaller). The application would interact with about 100,000 employees. Broadcasting signals to these many numbers seems prohibitively expensive even after customizing in the service. Is there a way to support something like a socket rooms concept (if not already supported).

var mongoose = require('feathers-mongoose');
var Proto = require('uberproto');
var subscription;
var MessageService = mongoose.Service.extend({
    setup: function (app) {
        subscription = app.service('subscriptions');
		//for some reason this.service is not evaluating elsewhere 
        //this.service = app.service.bind(app); 
    },
    created: function (data, params, callback) {
        subscription.find({ query: { username: 'test1' } }, function (err, result) {
            console.log(result);
            console.log(err);
        });
        return callback(null, false);
    },
    updated: function (data, params, callback) {
        //TODO Write logic
        return callback(null, false);
    }
});
module.exports = function (modelName, schema, options) {
    return Proto.create.call(MessageService, modelName, schema, options);
};

module.exports.Service = MessageService;

**Comment by daffl** [comment]
You are already implementing `created` and `updated`. If an event is filtered it will never broadcast. The only problem is that with that many clients making a database query every time will be pretty slow. You will somehow have to cache the information you need locally to make sure that those methods run as fast as possible.

It was brought up before but I am not sure how SocketIO rooms could help with this (and they only work with SocketIO).

Also, I'm not sure if a single application instance can handle 100k concurrent socket connections (I would go for around 10k/application instance) which means it would run ten thousand times per instance which should be fast enough if everything is available in memory.

Also, for the problem in your overwritten `setup` you will have to call the original method like this:

```js
setup: function (app) {
  this._super.apply(this, arguments);
  subscription = app.service('subscriptions');
}
```

**Comment by daffl** [comment]
Actually I think there might be a bug in the dispatcher (`created`, `updated` though). It looks like the context is not being set to the service (you should be able to call `this.service('xyz')` in `created` and `updated`).

**Comment by ekryski** [comment]
On a slightly unrelated note, @sgireddy I would use [feathers-hooks](https://github.com/feathersjs/feathers-hooks) for processing data after your create call, rather than extending the service. Not really a big deal right now, but it allows you to chain multiple post create actions.

**Comment by daffl** [comment]
The context issue should now be fixed (with an `npm cache clean` and reinstalling all dependencies). I added tests for it in https://github.com/feathersjs/feathers/pull/172. I am going to close this issue. Feel free to reopen or create a new one if you have any other questions.
