### ISSUE TITLE
How to get created items in multi-item create operations that ultimately fail?

### ISSUE THREAD

**Issue by aminnaggar** [feathersjs/feathers#1691]
### Steps to reproduce

1. initiate a multi-item create call on a service with 10 items, ensure item 9 has bad info to ensure that the create call as a whole fails
2. observe an error response from feathers, also observe that 9 items were successfully created

---

I'd like to have an error hook that does some work on the items that were successfully created, despite the call as a whole being a failure. So my question is, does that exist in the context somewhere?

**Comment by aminnaggar** [comment]
Forgot to mention that I'm using `feathers-mongoose` for the create service. 👍

**Comment by daffl** [comment]
This is probably more of a Mongoose question since the adapter just passes the data through to `MongooseModel.create`.

**Comment by aminnaggar** [comment]
Thank you will take a look at it there. If I reach a dead end I might reopen this if it's ok
