### ISSUE TITLE
support rethinkdb in crow

### ISSUE THREAD

**Issue by andysay** [feathersjs/feathers#1697]
hello , now when use feathers generate service cant found rethinkdb adapter . 
not support yet ?

**Comment by daffl** [comment]
Please see this issue: https://github.com/feathersjs-ecosystem/feathers-rethinkdb/issues/119

If someone wants to maintain it, I'll be happy to transfer it but so far nobody stepped up.

**Comment by kevin192291** [comment]
Hello, I am interested in maintaining the rethinkdb repo. The primary reason I use feathers is for rethinkdb. There was a brand new release of rethinkdb pushed today and I would love to see it back in the CLI options.
How should we go about making this happen?
I don't see any current issues other than the build not working.
If I get a bit of direction, I think I can get this back working and maintain it pretty well.

**Comment by daffl** [comment]
To make it an official adapter that can be included in the CLI again there is actually quite a bit to do which is outlined in this comment: https://github.com/feathersjs-ecosystem/feathers-rethinkdb/issues/119#issuecomment-478182035
