### ISSUE TITLE
After Upgrade to Feathers 4.3.7, generated hooks break with errors.

### ISSUE THREAD

**Issue by adavie1** [feathersjs/feathers#1699]
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [x] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc. This makes it much easier for us to debug and issues that have a reproducable example will get higher priority.

### Expected behavior
For the generated hook to work, I've not added any code yet.
This is a totally fresh install of feathers and @feathers/cli which I did today, since I want to learn Feathers to move away from Laravel.

### Actual behavior
Added a **service hook** using:
`feathers generate hook`
_- for messages.db, create and before hook._

This is the hook created by `feathers generate hook` in file `src/hooks/lower-case.js`:
```
module.exports = (options = {}) => {
  return async context => {
    return context;
  };
};
```
The actual `messages.hooks.js` code looks like this (auto-generated):
```
...
const lowerCase = require('../../hooks/lower-case');
module.exports = {
  before: {
    all: [],
    find: [],
    get: [],
    create: [lowerCase],
    update: [],
    patch: [],
    remove: []
  },
...

```
On testing in Postman- I get this error:
`{"name":"GeneralError","message":"before hook for 'create' method returned invalid hook object","code":500,"className":"general-error","data":{},"errors":{}}`

If I change the lowerCase require code to this:
`const {lowerCase} = require('../../hooks/lower-case');`

Then I get this error:
`{"name":"GeneralError","message":"Cannot read property 'eventMappings' of undefined","code":500,"className":"general-error","data":{},"errors":{}}`

### System configuration
Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
My package.json dependencies are:
```
...
  "@feathersjs/authentication": "^4.3.7",
    "@feathersjs/authentication-local": "^4.3.7",
    "@feathersjs/authentication-oauth": "^4.3.7",
    "@feathersjs/commons": "^4.3.7",
    "@feathersjs/configuration": "^4.3.7",
    "@feathersjs/errors": "^4.3.7",
    "@feathersjs/express": "^4.3.7",
    "@feathersjs/feathers": "^4.3.7",
    "@feathersjs/socketio": "^4.3.7",
    "@feathersjs/transport-commons": "^4.3.11",
    "compression": "^1.7.4",
    "cors": "^2.8.5",
    "feathers-nedb": "^5.1.0",
    "helmet": "^3.21.1",
    "nedb": "^1.8.0",
    "serve-favicon": "^2.5.0",
    "winston": "^3.0.0"
...

```
**NodeJS version**:
v12.13.1

**Operating System**:
Ubuntu 18.04 - Postman v7.10.0
**Browser Version**:
N/A
**React Native Version**:
N/A
**Module Loader**:

**Comment by daffl** [comment]
The code to call the hook should be

```js
module.exports = {
  before: {
    all: [],
    find: [],
    get: [],
    create: [ lowerCase() ],
    update: [],
    patch: [],
    remove: []
  },
```

Note the function call via `lowerCase()`. This is also what the generator puts into the `*.hooks.js` file it you choose to add it in the CLI.
