### ISSUE TITLE
Can't login with user created from cli

### ISSUE THREAD

**Issue by soullivaneuh** [feathersjs/feathers#1700]
### Steps to reproduce

- [ ] Create a basic `seed.ts` file following this example: https://github.com/feathersjs/feathers/issues/290#issuecomment-205046553
- [ ] Try to authenticate with the freshly created user.

```typescript
import app from './app';

const users = async () => {
  const user = await app.service('users').create({
    email: 'example@example.com',
    password: 'testtest',
  });
  console.log(user);
}
users();
```

### Expected behavior

I should be able to login with the created user.

### Actual behavior

Invalid login error:

```
❯ http POST localhost:3333/authentication strategy=local email=example@example.com password=testtest
HTTP/1.1 401 Unauthorized
Access-Control-Allow-Origin: *
Allow: POST,DELETE
Connection: keep-alive
Content-Length: 108
Content-Type: application/json; charset=utf-8
Date: Sun, 24 Nov 2019 20:34:05 GMT
ETag: W/"6c-rbBKWCmdUDcz9iRK5CDFVh+/LVA"
Strict-Transport-Security: max-age=15552000; includeSubDomains
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-DNS-Prefetch-Control: off
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block

{
    "className": "not-authenticated",
    "code": 401,
    "errors": {},
    "message": "Invalid login",
    "name": "NotAuthenticated"
}
```

Not that I did tries with a manually created user and it works.

It looks like the password is not hashed the same way, but I can't figure out why.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** 4.3.10

**NodeJS version**: v12.13.0

**Operating System**: Linux

**Browser Version**: Irrevelant

**React Native Version**: Irrevelant

**Module Loader**: Irrevelant

**Comment by soullivaneuh** [comment]
Hmm, I can make it working outside my docker env.

It's need more investigation, but I don't think it's related to feathers.

**Comment by soullivaneuh** [comment]
I found what is the issue and it's finally not related to docker at all.

Considering this `seed.ts` file:

```typescript
/* eslint-disable no-console */
import fs from 'fs-extra';
import app from './app';

(async (): Promise<void> => {
  if (fs.existsSync('data')) {
    fs.readdirSync('data').forEach((dataFile) => fs.outputFileSync(`data/${dataFile}`, ''));
  }

  const users = await Promise.all(
    [
      { email: 'admin@test.com' },
      { email: 'driver1@test.com' },
      { email: 'driver2@test.com' },
      { email: 'driver3@test.com' },
    ].map(async (data) => app.service('users').create({
      ...data,
      password: 'testtest',
    }).then((user) => user)),
  );
  console.dir(users);
})();
```

And the following command:

```
"dev": "ts-node-dev --no-notify src/",
"seed": "ts-node src/seed.ts",
```

1. Launch the app: `npm run dev`
2. Run `npm run seed` on an another terminal.
3. Try to authenticate with the user created: It will fail.
4. Strop the app and launch again: `npm run dev`
5. Retry authentication: It works!

Did I missed something?

Note: I'm using NeDB as bakend.

**Comment by daffl** [comment]
This is probably related to how [NeDB persistence](https://github.com/louischatriot/nedb/#persistence) works. If you want the seeds to be available with NeDB on a _running_ application you may want to connect to the API [as a client](https://docs.feathersjs.com/api/client.html).
