### ISSUE TITLE
oAuth redirects to /success when error in after hook

### ISSUE THREAD

**Issue by jamesholcomb** [feathersjs/feathers#1701]
### Steps to reproduce

- Initiate oAuth flow on client with valid provider, username, password
- Throw error on server in authentication:create after hook
- Client is redirected to /auth/success?error=The%20error%20message

### Expected behavior
oAuth should redirect to /auth/error

### Actual behavior
oAuth redirects to /auth/success?error=

### System configuration

v3 client, v4 server with legacy support for cookies per guideline

**Module versions** (especially the part that's not working):
client
    "@feathersjs/feathers": "3.1.7"
server
    "@feathersjs/authentication": "4.3.10",
    "@feathersjs/authentication-local": "4.3.10",
    "@feathersjs/authentication-oauth": "4.3.10",
    "@feathersjs/configuration": "4.3.10",
    "@feathersjs/errors": "4.3.10",
    "@feathersjs/express": "4.3.10",
    "@feathersjs/feathers": "4.3.10",
    "@feathersjs/socketio": "4.3.10",

**NodeJS version**:
10 LTS

**Operating System**:
Mac

**Browser Version**:

**React Native Version**:
0.59.7

**Module Loader**:

**Comment by daffl** [comment]
You'd have to [customize](https://docs.feathersjs.com/api/authentication/oauth.html#customization) the [getRedirect](https://docs.feathersjs.com/api/authentication/oauth.html#getredirect-data) method of the oAuth strategy.
