### ISSUE TITLE
use hook to populate relation with sequalize

### ISSUE THREAD

**Issue by abdolrhman** [feathersjs/feathers#1702]
### Steps to reproduce
basically i have sequalize with feather, every thing cool,
i only want to use hook to populate the relation of the model, 
So how to do so, using sequalize,

thanks for this great repo,
the effort done in this framework ,is unbelievable ^^

**Comment by daffl** [comment]
Hi @abdolrhman. A hook how to do that is [documented in the feathers-sequelize](https://github.com/feathersjs-ecosystem/feathers-sequelize#paramssequelize) repository.

**Comment by abdolrhman** [comment]
yeah thanks daffl, 
i did it the hard way, 
i did get the user id and then got his courses, by getting all courses by user id, 
i wanted to use this hooks in the documentation ,
Because, Why would i use a before hook ????
it should be after, right, because i will want to get the data,
right ??

**Comment by abdolrhman** [comment]
@daffl bro, i have used what u mentioned in your comment, 
yet i get only one record from relation 1 to many ,
not an array of records, any idea why ?? please replay :)

**Comment by abdolrhman** [comment]
i know why, row data should be set to false ,
its some thing ward with sequalize >.<
ty @daffl
