### ISSUE TITLE
Broken Documentation links

### ISSUE THREAD

**Issue by daslicht** [feathersjs/feathers#171]
eg:
http://feathersjs.com/todomvc/feathers/angularjs/guide.html
https://github.com/feathersjs/examples

**Comment by daffl** [comment]
What pages are those links on?

**Comment by daslicht** [comment]
http://feathersjs.com/quick-start/#

**Comment by ekryski** [comment]
Thanks @daslicht! I also found a couple more. Will fix shortly.

**Comment by daslicht** [comment]
Thank you !
