### ISSUE TITLE
Auth "after" hooks and events not fired on reconnect if the first connection was unsuccessful

### ISSUE THREAD

**Issue by panstromek** [feathersjs/feathers#1714]
### Steps to reproduce
Using this code on client with realtime and auth on the server.
```js
 feathers.service('authentication').hooks({
    after: {
      all: [ctx => console.log('auth')]
    }
  })
feathers.on('login', () => console.log('auth'))
feathers.on('authenticated', () => console.log('auth'))

feathers.reAuthenticate().then(/* ... */)
```
1. Turn the server off. 
2. Reload the app.
3. Get the timeout error (correct)
4. Turn the server on
5. Look at the dev tools - feathers reconnects, `create authentication` is sent, response received, but nothing shows up in the console - eg. no registered hooks or events are fired

Note: 
This error happens only on the first connection, if the first attempts were unsuccessful.

Hooks and events are correctly fired if the app disconnects and reconnects again after it was already connected.

### System configuration

**Feathers**: 4.4.1
**NodeJS version**: 12
**Operating System**: Win 10
**Browser Version**: Chrome 76

**Comment by daffl** [comment]
Related to https://github.com/feathersjs/feathers/issues/1532 - clearing the buffer would fix it. But the timeout should really be removed.

**Comment by panstromek** [comment]
Note: Quick workaround for this for now is to call force reAuth on `reconnect` event like this ;)

```js
socket.on('reconnect', () => {
  if (!app.authentication.authenticated) {
    app.reAuthenticate(true)
  }
})
```

**Comment by daffl** [comment]
This should happen automatically already. #1696 was supposed to fix the reconnection behaviour with queued requests as well. I'll have to double check what's happening there.

**Comment by panstromek** [comment]
Ok, cool. I haven't updated yet. I'll try tomorrow ;)

**Comment by daffl** [comment]
I believe this should work now in the latest version. The next major version will probably remove the client internal timeouts and let the connection (REST/Socket.io) handle that.
