### ISSUE TITLE
Fetching user data from hook returns password

### ISSUE THREAD

**Issue by soullivaneuh** [feathersjs/feathers#1715]
### Steps to reproduce

On a hook, attach some user data by calling a service:

```typescript
  after: {
    all: [],
    find: [
      async (context: HookContext) => {
        for (const ride of context.result.data) {
          const driver = await context.app.service('users').get(ride.driverId);
          ride.driver = driver;
        }
      }
    ],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: [],
  },
```

### Expected behavior

I expect to get user data without sensitive fields. 

In a nutshell, the same behavior as when I call the API from an external REST client.

### Actual behavior

The password is returned.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**: v12.11.1

**Operating System**: Linux

**Browser Version**: N/A

**React Native Version**: N/A

**Module Loader**: N/A

**Comment by daffl** [comment]
As shown [in the guide](https://docs.feathersjs.com/guides/basics/hooks.html#populate-the-message-sender) you need to pass `context.params` (or at least `context.params.provider`) along:

```js
const driver = await context.app.service('users').get(ride.driverId, context.params);
// Or
const driver = await context.app.service('users').get(ride.driverId, {
provider: context.params.provider
});
```

**Comment by daffl** [comment]
To avoid `await` in a for loop, those calls can be made in parallel using `Promise.all` like this:

```js
  after: {
    all: [],
    find: [
      async (context: HookContext) => {
        const userService = context.app.service('users');
        const promises = context.result.data.map(async ride => {
          const driver = await userService.get(ride.driverId, context.params);

          return {
            ...ride,
            driver
          };
        });

        context.result.data = await Promise.all(promises);

        return context;
      }
    ],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: [],
  },
```
