### ISSUE TITLE
QUESTION How to logout feathers-client on jwt expiry

### ISSUE THREAD

**Issue by apmcodes** [feathersjs/feathers#1721]
How can we logout a logged in feathers socket client whose jwt token has expired when they access any part of the app. Currently, user get error about jwt expired notAuthenticated. Is there a way to logout the user?
 
Currently, using sample chat app auth code.

```
node -v
v12.13.0
```
```
    "@feathersjs/authentication": "^4.3.11",
    "@feathersjs/authentication-local": "^4.3.11",
    "@feathersjs/authentication-oauth": "^4.3.11",
    "@feathersjs/configuration": "^4.3.11",
    "@feathersjs/errors": "^4.3.11",
    "@feathersjs/express": "^4.3.11",
    "@feathersjs/feathers": "^4.3.11",
    "@feathersjs/socketio": "^4.3.11",
```

**Comment by daffl** [comment]
You can use the [jwt-decode](https://www.npmjs.com/package/jwt-decode) package and check the expiration before making the request.

**Comment by corepay** [comment]
FYI related - just found this on [Feathers Vuex](https://github.com/feathersjs-ecosystem/feathers-vuex/issues/376) issue for anyone lurking this topic:

```
await store.dispatch("users/remove", this.user._id); //remove user
document.cookie = `feathers-jwt=;expires=Thu, 01 Jan 1970 00:00:01 GMT;`; //delete cookie, yes this is how you delete a cookie
await feathersClient.get('storage').removeItem("feathers-jwt");
```

**Comment by apmcodes** [comment]
For our requirement, used client side error hook to catch not authenticated error and refreshed the browser page (to take the user to login page). #1858

**client.js**
```
client.hooks({
    error(context) {
        const { error } = context;

        if (error.code === 401) {
            client.emit('authFailure', error);
            window.location.reload(true);   // reload page | should work on both desktop, mobile (cordova)
        }

        return context;
    }
});
```

But, this applies to incorrect login as well.
