### ISSUE TITLE
Feathers.SKIP functionality no longer working in version 3 buzzard

### ISSUE THREAD

**Issue by tedhuang** [feathersjs/feathers#1722]
### Steps to reproduce

- Do a fresh install with no package-lock of feathers version 3. 
- Implement a hook that uses feathers.SKIP

According to the current [docs](https://buzzard.docs.feathersjs.com/api/hooks.html#hook-functions) on v3:
> return feathers.SKIP to skip all further hooks

This functionality no longer works as npm install no longer pulls in the feathers common package that includes the source code for skip functionality inside @feathersjs/commons/lib/hooks.js ([removed here](https://github.com/feathersjs/feathers/pull/1269)). 

I guess either the docs needs to be updated or the versioning for the @feathersjs package.json on "@feathersjs/commons" needs to be more strict. 

### Expected behavior
Subsequent hooks should be skipped.

### Actual behavior
Returning feathers.SKIP does nothing.

**Module versions** (especially the part that's not working):

feathersjs - 3.3.1
commons - 4.4.1

**NodeJS version**:

10.16

**Operating System**:

Linux ubuntu

**Comment by tedhuang** [comment]
Thanks for the fix!

**Comment by daffl** [comment]
I don't think the fix has been published yet, or is it working? I was going to say that one solution would be to lock the version in your `package.json` via `"@feathersjs/commons": "4.0.0"`
