### ISSUE TITLE
QUESTION respond with unhandled exception output instead of timeout

### ISSUE THREAD

**Issue by consciousweb** [feathersjs/feathers#1726]
Currently in feathers if an endpoint is presented with bad data that results in an unhandled exception, the console will show the error, but the endpoint will 'hang'. Is there a way to respond to the endpoint with the error shown in the app log by default instead of hanging, and without creating an individual error response for every situation? Or at least respond with a general error?

**Comment by daffl** [comment]
In a normal application setup all errors are handled and there should be no timeouts (unless your actual db call times out).

**Comment by daffl** [comment]
Going to close this. If you can provide an example for the case you are mentioning, please feel free to reopen.
