### ISSUE TITLE
How to refresh token when expired with authentication local, jwt

### ISSUE THREAD

**Issue by bigboss27051** [feathersjs/feathers#1728]
I don't know how to handle when access token expired. i want to know how to refresh token in front-end please tell me

**Comment by daffl** [comment]
The user needs to log in again with another strategy. This is explained in the [authenticaiton guide](https://docs.feathersjs.com/guides/basics/authentication.html) and [API documentation](https://docs.feathersjs.com/api/authentication/)

**Comment by yashika-sharma** [comment]
What if we are only using Local Authentication strategy? In my case I am getting Error code 401 when I try to log in. Shouldn't it make a new JWT token now?
