### ISSUE TITLE
'app.defaultAuthentication is not a function' on authenticate hook

### ISSUE THREAD

**Issue by m0dch3n** [feathersjs/feathers#1729]
### Steps to reproduce

You can check out a test repo here.

```
git clone https://github.com/m0dch3n/testfeathers.git
cd testfeathers
npm install
npm run dev
```

The repo consists of 2 services

/users -> in memory
/remote-users -> socket.io proxy of /users, using `@feathersjs/socketio-client` (but rest is also not working)

### Expected behavior
/remote-users service should work as an authentication service too...

### Actual behavior
```javascript
// Initializes the `remote-users` service on path `/remote-users`
const feathersClient = require('./feathersClientSocket');
// const feathersClient = require('./feathersClientRest');
const hooks = require('./remote-users.hooks');

module.exports = function (app) {
  let client = feathersClient('http://localhost:3030', 'users');
  app.use('/remote-users', client.service('users'));
  app.service('remote-users').hooks(hooks);
};

```
My /remote-users proxy is working without any problem. Meaning all the REST stuff is working, **when I comment the hooks** in this example.

However, when I try to transform the service as my authentication service by adding in my `config/default.json`
```
    "authentication": {
    "entityId": "id",
    "entity": "user",
    "service": "remote-users",
```

And then try to authenticate i.e. by  

creating the user (I'm creating the user over /users and not /remote-users as, the hooks fail also on create)
```
curl 'http://localhost:3030/users/' \
  -H 'Content-Type: application/json' \
  --data-binary '{ "email": "hello@feathersjs.com", "password": "supersecret" }'
```

and authenticating then 
```
curl 'http://localhost:3030/authentication/' \
  -H 'Content-Type: application/json' \
  --data-binary '{ "email": "hello@feathersjs.com", "password": "supersecret" }'
```

I get
```
{
    "name": "GeneralError",
    "message": "app.defaultAuthentication is not a function",
    "code": 500,
    "className": "general-error",
    "data": {},
    "errors": {}
}
```

**Comment by harwee** [comment]
@m0dch3n Were you able to solve this problem?

**Comment by daffl** [comment]
I am not able to reproduce this in the latest version and it looks like the test repository has been removed. Please reopen a new issue with an up-to-date example if this issue still persists.

**Comment by mategvo** [comment]
@daffl I had the same problem. Steps to reproduce:

- install featherjs without authentication, without users service (mongodb, koa, typescript)
- add local authentication via commandline 
- the `app.ts` is missing `app.configure(authentication);` and as a result when calling the user create the `app.defaultAuthentication is not a function` error appears

**Comment by ericirish** [comment]
Just encountered this myself with the same reproduction steps as @mategvo
