### ISSUE TITLE
The canonical way of handling a CRUD opration of many types

### ISSUE THREAD

**Issue by vlopp** [feathersjs/feathers#1730]
Consider a `conversation` microservice. A couple of CRUD operations can be performed on it:
 - append a message object to its `messages` array
 - increase its `likes` counter
 - change a name of one of its participants
 - ... et cetera...

**Given a microservice exposes only a couple of CRUD methods, how is this situation best handled?**

Currently, I'm passing a `type` property in the POST's data, then routing it with a `switch` appropriately. It doesn't sound too sophisticated however, are there any better ways?

**Comment by daffl** [comment]
Feathers services do not have to be individual "microservices". You can split them up across multiple instances but that doesn't change the resources (services) that e.g. a `conversations` application would use:

- append a message object to its messages array

`.create` a new message on the `messages` endpoint:

```js
client.service('messages').create({ conversationId, userId, text })
```

- increase its likes counter:

Simple case: 

```js
client.service('messages').patch(message.id, { likes: message.likes + 1 });
```

With more flexibility to e.g. associate likes with users and like/unlike:

```js
client.service('likes').create({ messageId: message.id });
```

- change a name of one of its participants

```js
client.service('users').patch({ displayName });
```

More details on the high level concepts can be found in [this article](https://blog.feathersjs.com/design-patterns-for-modern-web-apis-1f046635215?source=activity---post_recommended_rollup).
