### ISSUE TITLE
How to use Continuation Local Storage (CLS) with Feathers

### ISSUE THREAD

**Issue by averri** [feathersjs/feathers#1731]
I would like to enhance Featherjs logging with information provided in the client requests, like que client IP, add request ID for tracing, etc. 

One possible way is to use CLS, which works well in a middleware like:

```
const cls = require('cls-hooked')
const uuidv4 = require('uuid/v4')

const clsNamespace = cls.createNamespace('app')

const clsMiddleware = (req, res, next) => {
  // req and res are event emitters. We want to access CLS context inside of their event callbacks
  clsNamespace.bind(req)
  clsNamespace.bind(res)

  const traceID = uuidv4()

  clsNamespace.run(() => {
    clsNamespace.set('traceID', traceID)
    next()
  })
} 
```
Reference: https://itnext.io/nodejs-logging-made-right-117a19e8b4ce

I'm looking into a solution to use this in the SocketIO middleware, or even in the `before hook` of the application scope. In order to work, the method `set` of the cls namespace needs to be invoked inside a callback function and the implementation of this function must call the middleware `next` function (see example above). The problem is that the function `next` is not available in the hooks from Feathers v4 nor in the SocketIO middleware.

Question: how to integrate it with Feathersjs, in a way that it could handle calls from any provider?

**Comment by daffl** [comment]
Callbacks can be easily turned into a normal promise that is used in hooks like this:

```js
  const traceID = uuidv4()

  await new Promise(next => {
    clsNamespace.set('traceID', traceID)
    next()
  }); 
```

**Comment by averri** [comment]
Hi @daffl, thanks, absolutely, I have tried that already, forgot to mention. It does not work. 

The SocketIO middleware does not work:

```javascript
const logger = require('../logger')
const socketio = require('@feathersjs/socketio')
const tracer = require('../tracer')
const sync = require('feathers-sync')

module.exports = app => {
  app.configure(socketio(io => {
    // https://docs.feathersjs.com/api/socketio.html#params
    io.use((socket, next) => {
      tracer.run(() => {
        tracer.set('ip', socket.conn.remoteAddress)
        next()
      })
    })
  }))
}
```

But the standard Express middleware works fine:

```javascript
const tracer = require('../tracer')

module.exports = (req, res, next) => {
  tracer.run(() => {
    tracer.set('ip', req.ip)
    next()
  })
}
```

The `tracer.js`:

```javascript
const cls = require('cls-hooked')
const tracer = cls.createNamespace('app')
module.exports = tracer
```

The remaining approach to make CLS to work uniformly with any provider is to use it in the application `before` hook. The issue is how to trigger the next hook without using promises!

**Comment by daffl** [comment]
Using Promises is now pretty standard in JavaScript. If it doesn't work you might have to create an issue in the other projects since I don't see anything Feathers related that might be in the way.

**Comment by averri** [comment]
Yes, I agree, but I was trying to solve using the Framework APIs. 
The old hook signature would solve the issue: 

```javascript
      (ctx, next) => {
        tracer.run(() => {
          tracer.set('ip', ctx.params.ip)
          next()
        })
```

... but it seems that `next` is not available as part of the hook signature anymore.

**Comment by averri** [comment]
I could implement other solution using hooks, but I need to know how to propagate the `params` context when calling services from other services.
