### ISSUE TITLE
[Question] Typescript service class array promises

### ISSUE THREAD

**Issue by osman-mohamad** [feathersjs/feathers#1734]
when I set this create function in service class. it is shows type error inside the is Array Condition 
```ts
  async create(data: User, params?: Params): Promise<User> {

    if (Array.isArray(data)) {
      // error here
      let users = data.map(current => this.create(current, params))
      console.log(users);
      return Promise.all(users)
    }

    const user = new User()
    user.firstName = data.firstName
    user.lastName = data.lastName
    user.age = data.age
    return this.repository.save(user)
  }
```
I know this is not feathers related directly . but if some one can direct me to the right link to handle this type problem. 

thank you
**Typescript**: 3.7.2
**NodeJS version**: 12.*

**Comment by osman-mohamad** [comment]
I even tried to change the return type to
```ts
Promise<User> | Promise<User>[]
```
but it did not work.

**Comment by daffl** [comment]
It would be

```js
create(data: User|User[], params?: Params): Promise<User|User[]>
```

**Comment by osman-mohamad** [comment]
thank you very much.

the error moved to `Promise.all(_users_)` . but I used any like `Promise.all<any>(users)` to skip the type error.
