### ISSUE TITLE
Setting socket default timeout

### ISSUE THREAD

**Issue by bwgjoseph** [feathersjs/feathers#1735]
Based on the documentation [socketio-socket-options](https://docs.feathersjs.com/api/client/socketio.html#socketio-socket-options), it is possible to set the `timeout` of the service, globally or per service.

I have tried to set it, but wants to know how can I verify it by inspecting the `socket` object? Because when I looked through the options, there doesn't seem to have the value that I set it in.

This is the value I have set to.

`app.configure(socketio(socket, { timeout: 30000 }));`

This is the printout of the `socket` object.

![image](https://user-images.githubusercontent.com/37484538/70734755-cbf5f980-1d47-11ea-9086-be7f75e364b6.png)

I have gone through a couple of those, but none are displaying `30000`.

**Comment by daffl** [comment]
The timeout is only set on a per-service level: `app.service('messages').timeout`

**Comment by bwgjoseph** [comment]
In that case, wouldn't be documentation be wrong since it said as such...

```
// Set up Socket.io client with the socket
// And a timeout of 2 seconds
app.configure(socketio(socket, {
  timeout: 2000
}));
```

**Comment by daffl** [comment]
You can set the default timeout but it's only stored in a closure. If you want to change it later it needs to be set on each service.

**Comment by bwgjoseph** [comment]
> You can set the default timeout but it's only stored in a closure.

Sorry, I don't really get this. Do you mind going in a bit more details on this?
How does it affect whether I store it in `app.configure(socket(socket { timeout: x}))`? or configure directly on each service call? If I have to set it in each service, then what's the point of setting in the `app` level?

Also since I can call the service by `app.service('x').find().timeout(y)`, in other words, in each of this service call, I can set it on demand. Based on your experience, what are the use-cases for this type of on-demand timeout per service?

**Comment by J3m5** [comment]
If I'm understanding correctly, the value set with `app.configure(socket(socket { timeout: x}))` will be the default value used by all services.
But you can't change this default value after that, you need to change it per service.
Am I correct @daffl ?

**Comment by bwgjoseph** [comment]
> will be the default value used by all services.

That's my understanding from the documentation as well. But the printout from the `socket` object doesn't seem to agree with it, unless I'm looking at the wrong place?

**Comment by J3m5** [comment]
You won't see it in the socket object, as daffl said, it's stored in a closure.
But where I don't know.

**Comment by daffl** [comment]
This in happening in https://github.com/feathersjs/feathers/blob/master/packages/socketio-client/lib/index.js. To clarify:

- The default timeout can't be changed once initialized
- If you want to change the timeout for existing services use [app.services](https://docs.feathersjs.com/api/application.html#services) and set it

```js
const servicePaths = Object.keys(app.services);

servicePaths.forEach(path => {
  const service = app.service(path);

  service.timeout = newTimeout;
});
```

- Socket timeouts may be removed in the next version. It was really just a workaround the old socket message syntax that didn't have a way to know if a service existed and which was changed in Feathers 3 already.

**Comment by bwgjoseph** [comment]
I see, thank you @daffl and @J3m5.

If removed, that means I no longer can specify the timeout? Or there would be an alternate way to set those timeouts.

**Comment by daffl** [comment]
All websocket libraries have their own timeout and reconnect functionality already and timeouts shouldn't really be something that happens when you app runs normally.
