### ISSUE TITLE
Feathers v4: Debug typescript files with source-map

### ISSUE THREAD

**Issue by ismail-codinglab** [feathersjs/feathers#1739]
### The problem

The feathers v4 does not come with support for typescript sourcemaps or anything to refer to the original files. So by mistake I have edited a file in `lib/` because the error logs refer to the transpiled versions of the code. As seen in the screenshot below

![image](https://user-images.githubusercontent.com/48755937/70866893-7439d700-1f6f-11ea-8842-949cd2bc260c.png)

### Why a problem

My normal workflow is to click on the file of the error log, edit the line, and run it again. However this makes me by mistake edit a transpiled file which will be overwritten by re-transpiling the code.

The actual error is in the typescript file:
![copyshot](https://user-images.githubusercontent.com/48755937/70866901-874ca700-1f6f-11ea-8559-7a34ab364bc4.png)

### The solution

There is a solution to sourcemaps for nodejs.

which can be found here and works in my case:
https://stackoverflow.com/questions/42088007/is-there-source-map-support-for-typescript-in-node-nodemon
![copyshot](https://user-images.githubusercontent.com/48755937/70867020-db0bc000-1f70-11ea-8d91-b0cad876ac64.png)

Though this is fixed for me, I would like to share my knowledge so other people having the same problems will have a fix

**Comment by kevin192291** [comment]
I was awake until a bit past 2am last night dealing with this issue, Thank you for that fix!

**Comment by issy123** [comment]
Well now you can finally rest without debug nightmares!

**Comment by daffl** [comment]
This would be nice to add to the generated application, I'm just not sure how to avoid pulling in a development dependency in production.

**Comment by Ismail-codinglab** [comment]
Not sure what you mean.
Install npm packages without devdependencies? (npm install --only=prod) ?
Are you on slack for a chat?

**Comment by daffl** [comment]
I was just wondering if it had to be a dependency in prod but it probably makes sense since you want the correct stack traces there as well. Also, I'm not sure if the sourcemaps _have_ to be inline for it to work.

**Comment by Ismail-codinglab** [comment]
Ah good point, stacktraces of ts in prod are indeed useful

**Comment by daffl** [comment]
This is available in v5.0.0-pre.1 and is now in beta testing. Latest prereleases can be installed via `@feathersjs/<packagename>@pre`, updating the version numbers of all `@feathersjs` packages to `^5.0.0-pre.1` or by running

```
npx ncu -u --newest
```

Upgrade instructions are continuously updated and can be found in the [v5 migration guide](https://dove.docs.feathersjs.com/guides/migrating.html).
