### ISSUE TITLE
Create a guide for using feathers-client with React Native.

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers#174]
It's actually pretty darn easy.

**Comment by marshallswain** [comment]
I've set up a placeholder for this here: https://github.com/feathersjs/feathers-docs/blob/master/09.1_react-native.md

**Comment by ekryski** [comment]
I added just documentation for using each transport in React Native http://docs.feathersjs.com/clients/feathers.html and provider specific sub chapters.
