### ISSUE TITLE
Feathers V4 converting log.js to typescript

### ISSUE THREAD

**Issue by Ismail-codinglab** [feathersjs/feathers#1740]
Does context.toJson still exist?  and why is that check there?

![image](https://user-images.githubusercontent.com/48755937/70868138-cf72c600-1f7d-11ea-9b9f-997338652453.png)

**Comment by daffl** [comment]
For upgrading from v3 and moving to TypeScript at the same time I'd recommend to generate a new application with the latest CLI and moving your existing code into it. A lot of the logging cruft (and other things) has been removed so that people can just use their own.

**Comment by issy123** [comment]
Is there a logger in v4 that logs the errors in the console?

**Comment by daffl** [comment]
You can add an application level error `all` hook that calls `logger.error(context.error)`. The generator no longer makes assumptions on what logging should be done (noisy logs confused beginners and most people customize the logging setup later on anyway).
