### ISSUE TITLE
How to make `context.app.service('service-name')` Typed?

### ISSUE THREAD

**Issue by ismail-codinglab** [feathersjs/feathers#1742]
I am running a feathers v4 app converted from v3 and am trying to make everything typed.

This is perfectly typed
![copyshot](https://user-images.githubusercontent.com/48755937/70871429-7caa0600-1f9f-11ea-9f31-223bd03b15a2.png)

But when I do it this way, it's not typed at all.

![copyshot](https://user-images.githubusercontent.com/48755937/70871443-98ada780-1f9f-11ea-84fc-747e3b84c9fc.png)

I did my research, could not find it in the docs, nor in known examples

Two questions:
- How can I make it typed?
- Is there an example that is fully typed?

**Comment by daffl** [comment]
This is currently not possible other than casting the app into the `Application` from the declarations but will change in a future version.

**Comment by Ismail-codinglab** [comment]
`but will change in a future version.`

Does this mean you have a possible solution in mind I can work with?
Or should I try myself to get something like that working?

**Comment by Ismail-codinglab** [comment]
As a temporary workaround can you make the context.app.service accept a generic?
e.g.

```
context.app.service<AsdModel>('asd');
```

**Comment by robbyphillips** [comment]
As a workaround, I have found that extending `HookContext` in the declarations file is sufficient.

```typescript
// declarations.d.ts

import { Application as ExpressFeathers } from '@feathersjs/express'
import { HookContext as FeathersHookContext } from '@feathersjs/feathers'

// A mapping of service names to types. Will be extended in service files.
export interface ServiceTypes {}
// The application instance type that will be used everywhere else
export type Application = ExpressFeathers<ServiceTypes>

export interface HookContext<T = any> extends FeathersHookContext<T> {
  app: Application
}
```

Then I import the `HookContext` from declarations instead of feathers.

**Comment by ismail-codinglab** [comment]
Yes that's exactly what I did. And I have put in eslint/tslint the hookContext from feathers in the banned imports so developers can't by accident import the wrong hookccontext

**Comment by bwgjoseph** [comment]
Hi @ismail-codinglab, are you able to share how you did the `eslint` rule to disable import of certain class/module/file?

**Comment by latipun7** [comment]
> This is currently not possible other than casting the app into the `Application` from the declarations but will change in a future version.

It would be great if `app.get(name)` is typed too. #1952

**Comment by chrisbag** [comment]
> As a workaround, I have found that extending `HookContext` in the declarations file is sufficient.
> 
> ```ts
> // declarations.d.ts
> 
> import { Application as ExpressFeathers } from '@feathersjs/express'
> import { HookContext as FeathersHookContext } from '@feathersjs/feathers'
> 
> // A mapping of service names to types. Will be extended in service files.
> export interface ServiceTypes {}
> // The application instance type that will be used everywhere else
> export type Application = ExpressFeathers<ServiceTypes>
> 
> export interface HookContext<T = any> extends FeathersHookContext<T> {
>   app: Application
> }
> ```
> 
> Then I import the `HookContext` from declarations instead of feathers.

Thanks for the solution, works like a charm !

**Comment by yobdl** [comment]
> As a workaround, I have found that extending `HookContext` in the declarations file is sufficient.
> 
> ```ts
> // declarations.d.ts
> 
> import { Application as ExpressFeathers } from '@feathersjs/express'
> import { HookContext as FeathersHookContext } from '@feathersjs/feathers'
> 
> // A mapping of service names to types. Will be extended in service files.
> export interface ServiceTypes {}
> // The application instance type that will be used everywhere else
> export type Application = ExpressFeathers<ServiceTypes>
> 
> export interface HookContext<T = any> extends FeathersHookContext<T> {
>   app: Application
> }
> ```
> 
> Then I import the `HookContext` from declarations instead of feathers.

@robbyphillips thanks. 

However, when I try to use HookContext (imported from declaration) in my hook (`async (context:HookContext)`) I get the following TS error :  

```
Argument of type '{ before: { all: never[]; find: never[]; get: never[]; create: ((context: HookContext) => Promise<void>)[]; update: never[]; patch: never[]; remove: never[]; }; after: { all: never[]; find: never[]; get: never[]; create: never[]; update: never[]; patch: never[]; remove: never[]; }; error: { ...; }; }' is not assignable to parameter of type 'Partial<HooksObject<any>>'.
  Types of property 'before' are incompatible.
    Type '{ all: never[]; find: never[]; get: never[]; create: ((context: HookContext) => Promise<void>)[]; update: never[]; patch: never[]; remove: never[]; }' is not assignable to type 'Partial<HookMap<any>> | Hook<any, Service<any>> | Hook<any, Service<any>>[] | undefined'.
      Type '{ all: never[]; find: never[]; get: never[]; create: ((context: HookContext) => Promise<void>)[]; update: never[]; patch: never[]; remove: never[]; }' is not assignable to type 'Partial<HookMap<any>>'.
        Types of property 'create' are incompatible.
          Type '((context: HookContext<any>) => Promise<void>)[]' is not assignable to type 'Hook<any, Service<any>> | Hook<any, Service<any>>[] | undefined'.
            Type '((context: HookContext<any>) => Promise<void>)[]' is not assignable to type 'Hook<any, Service<any>>[]'.
              Type '(context: HookContext) => Promise<void>' is not assignable to type 'Hook<any, Service<any>>'.
                Types of parameters 'context' and 'context' are incompatible.
                  Type 'HookContext<any, Service<any>>' is not assignable to type 'HookContext<any>'.
                    Types of property 'app' are incompatible.
                      Type 'Application<{}>' is not assignable to type 'Application'.
                        Type 'Application<{}>' is missing the following properties from type 'Express': request, response, init, defaultConfiguration, and 40 more.
```

Is this the correct way to use it ?

**Comment by robbyphillips** [comment]
I think the type definitions changed and broke this a while ago.  Not sure if there's another way.

**Comment by yobdl** [comment]
> I think the type definitions changed and broke this a while ago. Not sure if there's another way.

Thanks @robbyphillips, I'll switch to `Dove` version

**Comment by daffl** [comment]
I'm not aware that those types changed in v4 but this has indeed been improved significantly in v5. I put up a reference for upgrading the TypeScript chat app in https://github.com/feathersjs/feathers-chat-ts/tree/dove-pre and you can see the changes necessary to upgrade in https://github.com/feathersjs/feathers-chat-ts/compare/dove-pre?expand=1

This includes typed hook context and proper service types (e.g. `app.service('authentication')` will give you all authentication service methods not just the normal service types). It only demonstrates the steps to upgrade and does not have new features like schema types and typed configuration yet.
