### ISSUE TITLE
How to get the data of currently signed in user?

### ISSUE THREAD

**Issue by umairalii** [feathersjs/feathers#1743]
i have used followings but got undefined or error,

`
client.authenticate().then(r => {
        dispatch({ type: 'CHECK_AUTHORIZATION', payload: r });
     return client.passport.verifyJWT(r.accessToken);
        }).then(payload => {
            dispatch({ type: 'JWT_PAYLOAD', payload: payload })
            return client.service('users').get(payload.userId);
        }).then(user => {
           dispatch({ type: 'PROFILE', payload: user })
        })
    .catch(() => {})
`

and also

`const {user} = client.get('authentication');
const res = client.get('authentication');`

**Comment by daffl** [comment]
Please make sure you are using the latest version. You probably aren't because `client.passport` has been removed.

**Comment by umairalii** [comment]
> Please make sure you are using the latest version. You probably aren't because `client.passport` has been removed.

than what to do?

`const {user} = client.get('authentication');`
is not working also.

**Comment by daffl** [comment]
For the previous version refer to the [old documentation](https://buzzard.docs.feathersjs.com/) which has a [complete example how to get the user](https://buzzard.docs.feathersjs.com/api/authentication/client.html#complete-example).

For the current version it is documented [here](https://docs.feathersjs.com/api/authentication/client.html#app-get-authentication) (you need `const { user } = await app.get('authentication')`

**Comment by umairalii** [comment]
`const { user } = await app.get('authentication')`
returns undefined.

**Comment by umairalii** [comment]
`const { user } = await app.get('authentication')` return only the accessToken.

**Comment by daffl** [comment]
Yes, it will if you are not using the latest version (or are not authenticated). If you are using `client.passport` anywhere in your application you are _not_ using the latest version.

**Comment by daffl** [comment]
This should not happen in a standard setup. You can use https://github.com/feathersjs/feathers-chat and the [authentication guide](https://docs.feathersjs.com/guides/basics/authentication.html) as a reference how everything should work. Adding that line e.g. in https://github.com/feathersjs/feathers-chat/blob/master/public/app.js#L184 will show you the logged in user.

**Comment by umairalii** [comment]
> This should not happen in a standard setup. You can use https://github.com/feathersjs/feathers-chat and the [authentication guide](https://docs.feathersjs.com/guides/basics/authentication.html) as a reference how everything should work. Adding that line e.g. in https://github.com/feathersjs/feathers-chat/blob/master/public/app.js#L184 will show you the logged in user.

<img width="435" alt="Screenshot 2019-12-17 at 12 06 10 AM" src="https://user-images.githubusercontent.com/41395451/70935091-39b06700-2061-11ea-98b4-f00bf2e0d36c.png">
see the attachment please.

**Comment by umairalii** [comment]
upgrading to 4.2.4 resolved the problem
