### ISSUE TITLE
QUESTION respond with general error instead of "hanging"

### ISSUE THREAD

**Issue by consciousweb** [feathersjs/feathers#1746]
Currently in feathers if an endpoint is presented with bad data that results in an unhandled exception, the console will show the error, but the endpoint will 'hang'. Is there a way to respond to the endpoint with a general error default instead of hanging, and without creating an individual error response for every situation?

Edit: 
@daffl 
You mentioned in a normal application setup this will be handled, can you elaborate what you mean "normal"? My feathers 3.3.1 application has been built entirely from the command line generation tools. 

You asked for a code representation but any code will recreate this issue...just create an unhandled error and feathers will "hang". 

For example, the following will result in just hanging if presented with an id that does not exist in the database (ignore any minor errors, i have stripped site code for this example that otherwise works if the rejection is handled)

get-database-by-id.js
```
const errors = require('@feathersjs/errors');

module.exports = function (options = {}) {
  return async context => {
  	let promise = new Promise((resolve,reject) => { 
  					context.app.service('database').find({
				query: {"id":context.data.id}
				}).then(result => {
					  
					  resolve(result.data[0].data)
                                           // console: error: Unhandled Rejection at: Promise 
                                           //browser:  hangs

			});
  	});
  	let result = await promise;
  	if (result) {
  		return context;
  	}
    
  };
};
```

database.service.js

```
// Initializes the `database` service on path `/database`
const createService = require('feathers-mongodb');
const hooks = require('./database.hooks');

module.exports = function (app) {
  const paginate = app.get('paginate');
  const mongoClient = app.get('mongoClient');
  const options = { 
    paginate,
    id: '_id' 
  };

  // Initialize our service with any options it requires
  app.use('/database', createService(options), function(req, res, next) {
    var resData = res.data
    res.data = {
      data:resData,
      status:200
    }
    next();
  });

  // Get our initialized service so that we can register hooks and filters
  const service = app.service('database');

  mongoClient.then(db => {
    service.Model = db.collection('database');
  });

  service.hooks(hooks);
};

```

database.hooks.js

```
const { authenticate } = require('@feathersjs/authentication').hooks;

const getDatabaseById = require('../../hooks/get-database-by-id');

const errors = require('@feathersjs/errors');

const errorHandler = ctx => {
  if (ctx.error) {
    const error = ctx.error;
    if (!error.code) {
      const newError = new errors.GeneralError("server error");
      ctx.error = newError;
      return ctx;
    }
    if (error.code === 404 || process.env.NODE_ENV === "production") {
      error.stack = null;
    }
    return ctx;
  }
};


module.exports = {
  before: {
    all: [ authenticate('jwt')],
    find: [],
    get: [],
    create: [
      getDatabaseById(),
    ],
    update: [],
    patch: [],
    remove: []
  },

  after: {
    all: [],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  },

  error: {
    all: [errorHandler],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  }
};
```

**Comment by daffl** [comment]
For custom logic involving promises it is up to you to implement a failure or timeout mechanism. In your case your Promise is never rejected and it can be solved by simply not using the unnecessary `new Promise` (I believe this is also mentioned somewhere in the the docs):

```js
module.exports = function (options = {}) {
  return async context => {
    const result = await context.app.service('database').find({
      query: { "id": context.data.id }
    });

    if (result) {
      return context;
    }

    const { data } = result.data[0];

    // Do something with data

    return context;
  };
};
```

Now all errors will get propagated properly and you removed a bunch of unnecessary code.

**Comment by consciousweb** [comment]
The following returns the below error in the console, but the client shows no error and the application completes returns context as if it was successful

```
module.exports = function (options = {}) {
  return async context => {
    const result = await context.app.service('database').find({
				query: {_id:context.data.id}
				})

    if (result) {
      return context;
    }

    const { data } = result.data[0];

    console.log(result.data[0].data)

    return context;
  };
};
```

**Comment by daffl** [comment]
I don't think it is in that code. It more sounds like your authenticated user does not exist.

**Comment by consciousweb** [comment]
The entire user object exists within context.params.user if logged at the beginning of the function and the object is valid as a current database entry. Is that what you mean? Is there some other code that would be helpful to see? I just want the operation to stop on any error, and report it to the client.

**Comment by jnardone** [comment]
You are doing something else wrong/weird with promises then; we do not see this problem with async code.  If you are seeing "error: Unhandled Rejection at: Promise" it means you aren't properly handling your promises.  I don't see it in this code, but it's not clear what your code is at this point.  The routine @daffl posted shouldn't lead to an unhandled rejection, so I'm guessing it's elsewhere.  Also that hook doesn't actually do anything with the results.  (The code probably has a bug - the first `if (result)` should be `if (!result)`)

I'm curious about this middleware you run after you get a result from feathers

```
function(req, res, next) {
    var resData = res.data
    res.data = {
      data:resData,
      status:200
    }
    next();
  });
```

is this necessary?  This might be interfering; do you get correct error propagation without it?
