### ISSUE TITLE
how to use @feathersjs/errors in other place(with express.js) ,not in hook?

### ISSUE THREAD

**Issue by wwbluechip** [feathersjs/feathers#1749]
```
const { BadRequest } = require("@feathersjs/errors");
   app.use("/wechat/login", async function(req, res, next) {
         // something...
         try {
            const createAccont = await userService.create({
              nickname,
              sex,
              avatar: headimgurl,
              unionid,
              password: defaultPassword,
              code: defaultPassword,
              province,
              city
            });
            if (createAccont) {
              // create accessToken
              const token = await app
                .service("api/authentication")
                .createAccessToken({
                  sub: createAccont._id,
                  unionid
                });
              res.status(200).send({ token, ...createAccont });
            }
          } catch (error) {
            logger.error(error);
           // here i want use BadRequest func to return 400 error to Browser instead of res.status(400).send
            res.status(400).send("oh something went wrong~");
          }
   }
```
###### I want use `@feathersjs/errors` , because i want to keep the return value consistent

**Comment by daffl** [comment]
You call `next` with the error (`next(error)`). See [error handling in Express](https://expressjs.com/en/guide/error-handling.html).

**Comment by wwbluechip** [comment]
thanks

> You call `next` with the error (`next(error)`). See [error handling in Express](https://expressjs.com/en/guide/error-handling.html):
> 
> ```js
> app.use("/wechat/login", async function(req, res, next) {
>          // something...
>          try {
>             const createAccont = await userService.create({
>               nickname,
>               sex,
>               avatar: headimgurl,
>               unionid,
>               password: defaultPassword,
>               code: defaultPassword,
>               province,
>               city
>             });
>             if (createAccont) {
>               // create accessToken
>               const token = await app
>                 .service("api/authentication")
>                 .createAccessToken({
>                   sub: createAccont._id,
>                   unionid
>                 });
>               res.status(200).send({ token, ...createAccont });
>             }
>           } catch (error) {
>             logger.error(error);
>             next(new BadRequest(error.message));
>           }
>    }
> ```

got it. thank u very much~
