### ISSUE TITLE
Does feathers.js provide a method to decode access_token?

### ISSUE THREAD

**Issue by wwbluechip** [feathersjs/feathers#1750]
### So i need decode the token for user's detail

In [jwt.io](https://jwt.io/),i decode the access_token `eyJhbGciOiJIUzI1NiIsInR5cCI6ImFjY2VzcyJ9.eyJ1bmlvbmlkIjoib1BrcXp3b2Jqc09zNW41bnhQQ0VmVE1VWmdiRSIsInN1YiI6IjVkZmEx**********PueUKRVNq2IgCEWV_QohVO0UWKUE_vl7QcD0`
### then i get some info ,like this:
```
{
  "sub": "5dfa18db87101251f1b3805f",
  "iat": 1576828850,
  "exp": 1576915250,
  "aud": "******",
  "iss": "feathers",
  "jti": "d3f2b6c3-2032-41fd-90c7-d498d4f34c97"
}
```
I need use the `sub` param.
# Does feathers.js provide a method to decode access_token? 
I read the doc but i don't find the method

**Comment by daffl** [comment]
On the server you can verify and decode the token with [verifyAccessToken](https://docs.feathersjs.com/api/authentication/service.html#verifyaccesstoken-accesstoken) on the authentication service:

```js
const payload = await app.service('authentication').verifyAccessToken(accessToken);
```

On the client you can use the [jwt-decode](https://www.npmjs.com/package/jwt-decode) package.

**Comment by wwbluechip** [comment]
> On the server you can verify and decode the token with [verifyAccessToken](https://docs.feathersjs.com/api/authentication/service.html#verifyaccesstoken-accesstoken) on the authentication service:
> 
> ```js
> const payload = await app.service('authentication').verifyAccessToken(accessToken);
> ```
> 
> On the client you can use the [jwt-decode](https://www.npmjs.com/package/jwt-decode) package.

thank u !!
