### ISSUE TITLE
Empty .update() call detected! Update data does not contain any values to update. This will result in a faulty query

### ISSUE THREAD

**Issue by SephReed** [feathersjs/feathers#1751]
I get this error all the time.  It would be a lot more useful if it gave me any amount of information about what table/column/etc it's trying to update and what kind of data it has.

**Comment by SephReed** [comment]
Here's the stack btw:
```
 Error: Empty .update() call detected! Update data does not contain any values to update. This will result in a faulty query.
             at QueryCompiler_PG._prepUpdate (/Users/seph/Code/RSLTS/api/node_modules/knex/lib/query/compiler.js:814:13)
             at QueryCompiler_PG.update (/Users/seph/Code/RSLTS/api/node_modules/knex/lib/dialects/postgres/query/compiler.js:39:29)
             at QueryCompiler_PG.toSQL (/Users/seph/Code/RSLTS/api/node_modules/knex/lib/query/compiler.js:64:29)
             at Builder.toSQL (/Users/seph/Code/RSLTS/api/node_modules/knex/lib/query/builder.js:76:44)
             at /Users/seph/Code/RSLTS/api/node_modules/knex/lib/runner.js:30:36
         From previous event:
             at Runner.run (/Users/seph/Code/RSLTS/api/node_modules/knex/lib/runner.js:25:16)
             at Builder.Target.then (/Users/seph/Code/RSLTS/api/node_modules/knex/lib/interface.js:14:43)
             at _findOrGet.then.results (/Users/seph/Code/RSLTS/api/node_modules/feathers-knex/lib/index.js:275:29)
             at processImmediate (timers.js:638:19)
         From previous event:
             at Object._patch (/Users/seph/Code/RSLTS/api/node_modules/feathers-knex/lib/index.js:265:9)
             at callMethod (/Users/seph/Code/RSLTS/api/node_modules/@feathersjs/adapter-commons/src/service.ts:10:20)
             at Object.patch (/Users/seph/Code/RSLTS/api/node_modules/@feathersjs/adapter-commons/src/service.ts:120:12)
             at processHooks.call.then.hookObject (/Users/seph/Code/RSLTS/api/node_modules/@feathersjs/feathers/lib/hooks/index.js:56:27) },
```

**Comment by daffl** [comment]
Since this isn't really an error coming directly from Feathers I'd recommend to double check with the Knex project.

**Comment by SephReed** [comment]
https://github.com/knex/knex/issues/3591

**Comment by daffl** [comment]
Could be an issue in the adapter but it needs more context. We need the exact call that is failing, all dependency version etc (basically all the things that were in the issue template) and ideally a complete example to reproduce the problem.

**Comment by SephReed** [comment]
Found the bug.  `patch()` was ran without anything to update, pretty sure on the feathers knex service.  This is more a knex issue than anything else, but you could potentially catch these, check the error, and add more useful output if knex is too slow to add anything.

It's practically impossible to fix one of these issues without getting a hint about what table is being updated.

**Comment by daffl** [comment]
One way to get more info would be an [error hook](https://docs.feathersjs.com/api/hooks.html) that logs `context.method` and `context.path` with the error message. Other than that I agree that since the error message itself is coming from Knex it should probably be improved there.

**Comment by SephReed** [comment]
They fixed the issue.  Thanks for the help.

**Comment by Natannegara** [comment]
> Here's the stack btw:
> 
> ```
>  Error: Empty .update() call detected! Update data does not contain any values to update. This will result in a faulty query.
>              at QueryCompiler_PG._prepUpdate (/Users/seph/Code/RSLTS/api/node_modules/knex/lib/query/compiler.js:814:13)
>              at QueryCompiler_PG.update (/Users/seph/Code/RSLTS/api/node_modules/knex/lib/dialects/postgres/query/compiler.js:39:29)
>              at QueryCompiler_PG.toSQL (/Users/seph/Code/RSLTS/api/node_modules/knex/lib/query/compiler.js:64:29)
>              at Builder.toSQL (/Users/seph/Code/RSLTS/api/node_modules/knex/lib/query/builder.js:76:44)
>              at /Users/seph/Code/RSLTS/api/node_modules/knex/lib/runner.js:30:36
>          From previous event:
>              at Runner.run (/Users/seph/Code/RSLTS/api/node_modules/knex/lib/runner.js:25:16)
>              at Builder.Target.then (/Users/seph/Code/RSLTS/api/node_modules/knex/lib/interface.js:14:43)
>              at _findOrGet.then.results (/Users/seph/Code/RSLTS/api/node_modules/feathers-knex/lib/index.js:275:29)
>              at processImmediate (timers.js:638:19)
>          From previous event:
>              at Object._patch (/Users/seph/Code/RSLTS/api/node_modules/feathers-knex/lib/index.js:265:9)
>              at callMethod (/Users/seph/Code/RSLTS/api/node_modules/@feathersjs/adapter-commons/src/service.ts:10:20)
>              at Object.patch (/Users/seph/Code/RSLTS/api/node_modules/@feathersjs/adapter-commons/src/service.ts:120:12)
>              at processHooks.call.then.hookObject (/Users/seph/Code/RSLTS/api/node_modules/@feathersjs/feathers/lib/hooks/index.js:56:27) },
> ```

**Comment by Natannegara** [comment]
> Here's the stack btw:
> 
> ```
>  Error: Empty .update() call detected! Update data does not contain any values to update. This will result in a faulty query.
>              at QueryCompiler_PG._prepUpdate (/Users/seph/Code/RSLTS/api/node_modules/knex/lib/query/compiler.js:814:13)
>              at QueryCompiler_PG.update (/Users/seph/Code/RSLTS/api/node_modules/knex/lib/dialects/postgres/query/compiler.js:39:29)
>              at QueryCompiler_PG.toSQL (/Users/seph/Code/RSLTS/api/node_modules/knex/lib/query/compiler.js:64:29)
>              at Builder.toSQL (/Users/seph/Code/RSLTS/api/node_modules/knex/lib/query/builder.js:76:44)
>              at /Users/seph/Code/RSLTS/api/node_modules/knex/lib/runner.js:30:36
>          From previous event:
>              at Runner.run (/Users/seph/Code/RSLTS/api/node_modules/knex/lib/runner.js:25:16)
>              at Builder.Target.then (/Users/seph/Code/RSLTS/api/node_modules/knex/lib/interface.js:14:43)
>              at _findOrGet.then.results (/Users/seph/Code/RSLTS/api/node_modules/feathers-knex/lib/index.js:275:29)
>              at processImmediate (timers.js:638:19)
>          From previous event:
>              at Object._patch (/Users/seph/Code/RSLTS/api/node_modules/feathers-knex/lib/index.js:265:9)
>              at callMethod (/Users/seph/Code/RSLTS/api/node_modules/@feathersjs/adapter-commons/src/service.ts:10:20)
>              at Object.patch (/Users/seph/Code/RSLTS/api/node_modules/@feathersjs/adapter-commons/src/service.ts:120:12)
>              at processHooks.call.then.hookObject (/Users/seph/Code/RSLTS/api/node_modules/@feathersjs/feathers/lib/hooks/index.js:56:27) },
> ```

This is Knex Bug, I found the solution to keep updating the table using raw query instead of Knex query. it worked !!
