### ISSUE TITLE
unable to create the correct records in the db.    ": "BadRequest",     "message": "validation failed: age: Path `age` is required

### ISSUE THREAD

**Issue by jpca999** [feathersjs/feathers#1753]
### Steps to reproduce

contacts.model.js  is a service made with mongoose via the feathers gererate service contacts. 

// contacts-model.js - A mongoose model
// 
// See http://mongoosejs.com/docs/models.html
// for more of what you can do here.
module.exports = function (app) {
  const mongooseClient = app.get('mongooseClient');
  const { Schema } = mongooseClient;
  const contacts = new Schema({

    name: { type: String, required: true },
    age: { type: Number, required: true , index: true },
    bio: { type: String, match: /[a-z]/ },
    date: { type: Date, default: Date.now },
    
  }, {
    timestamps: true
  });

  // This is necessary to avoid model compilation errors in watch mode
  // see https://github.com/Automattic/mongoose/issues/1251
  try {
    return mongooseClient.model('contacts');
  } catch (e) {
    return mongooseClient.model('contacts', contacts);
  }
};

When I try to create a record: it spits error: 

I wonder if im doing anythign wrong at my end : 

![image](https://user-images.githubusercontent.com/1026325/71300711-7207bc00-2365-11ea-9560-e89ce6763a33.png)

**Comment by daffl** [comment]
Your JSON is invalid, single quotes are not allowed. You also need to set the `Content-Type` header to `application/json` for the header to be parsed properly.

**Comment by jpca999** [comment]
Your right.  Resolved!
