### ISSUE TITLE
Regarding #1746, Operation now completes with error unhandled

### ISSUE THREAD

**Issue by consciousweb** [feathersjs/feathers#1755]
Regarding [#1746](https://github.com/feathersjs/feathers/issues/1746#event-2890524609), I converted my chain of hooks to your recommendation and while the browser no longer hangs, the operation is simply allowed to complete with the error unhandled. The app log shows the error, but but the browser/client is not presented with any error and the operation completes with faulty data. Can you please advise?

**Comment by daffl** [comment]
Please provide a complete example to reproduce your issue and add it to #1746
