### ISSUE TITLE
Feathers - Mongoose : server instance pool was destroyed

### ISSUE THREAD

**Issue by farhadarjmandf** [feathersjs/feathers#1757]
i generated service with Generator and after some times feathers API show error in reading and writing

**Comment by marshallswain** [comment]
Hmm..  I've been using feathers-mongoose for years without seeing anything like this.  Feathers-mongoose doesn't really handle any connection-level logic.  You have to provide it a Mongoose model: https://github.com/feathersjs-ecosystem/feathers-mongoose/blob/master/lib/service.js#L10.

I don't see anything in feathers-mongoose that could have created this problem.

Can you post error messages?  We're for sure going to require more information to track down the source of the problem.
