### ISSUE TITLE
How can the client send real time data to the server

### ISSUE THREAD

**Issue by gamcoh** [feathersjs/feathers#1758]
I'm trying to build a live video service with Vue in the front and Feathers in the back.

So when a user in a certain room pauses the video i'd like that every other users in the same room have the video paused as well but I really don't understand how the events works.

First of all, when I try to send any data from the client to the server I don't see anything.
Can't I send any events to server other than created, updated and removed?

Here's my code:

client side
```
feathersClient.service('rooms').emit('test', {msg: 'hey'})
```

server side
```
app.service('rooms').on('test', (data) => {
  console.log(data);
})
```

Also, even if I managed to get this to work how can I say from the client: well, I'd like to pause this video but only in this room with this id?

**Comment by daffl** [comment]
Look at it from the resource perspective (explained more on a high level [here](https://blog.feathersjs.com/design-patterns-for-modern-web-apis-1f046635215)): You want to update the room/video or watch session state to be `paused`. This means you can create a service for that and `patch` to update the state:

```js
app.service('video').patch({
  roomId: '<room id>',
  paused: true
});
```

Client can listen to that `video patched` event:

```js
app.service('video').on(patched, 'video' => {
  pauseOrResumeVideo(video.paused)
});
```

**Comment by gamcoh** [comment]
Thanks @daffl, 

Alright so that means that I have to create a new service on the back end without any database attachment.

And then on the client side I just need to update the service so that the server can send out to all the users of this specific room the data.

But how, the server catches the data and then send it?

Does this code seems good to you?
```
// server
app.service('video').on('patched', video => {
  app.channel('room/<video.roomId>').emit('isPaused', video.paused)
});
```

**Comment by daffl** [comment]
Channels just determine _who_ can see the event. What you would do in `channels.js` would be:

```js
// Publish any event from the `video` service to their room channel
app.service('video').publish(video => app.channel(`room/${video.roomId}`));
```

Then users will join the channels for the rooms they want to get notifications for. The [channel API docs](https://docs.feathersjs.com/api/channels.html) have more details on that.

**Comment by gamcoh** [comment]
Alright but then how do I emit the data from the client to the server and then to all of the users?

**Comment by daffl** [comment]
This is what Feathers does for you by sending [real-time events](https://docs.feathersjs.com/api/events.html) automatically. All you have to do is determine in the Channels file who is allowed to see it (the default is that any authenticated user will see anything).

**Comment by J3m5** [comment]
In the example daffl gave you, the client would call the patch method on the video service with the paused property set to true in the payload.
Then the service would emit the patched event.
The event would then be sent to all the users in the room.
On the client, you listen to this event and react to it accordingly.

**Comment by gamcoh** [comment]
Alright, thanks I understand how it works now.

But when I'm trying to code it I get an error:
```
// client
feathersClient.service('video-events-handler').patch({
  roomId: this.room._id,
  ...data
});
```

I got this error:
`Error: A data object must be provided to the 'video-events-handler.patch' method`

**Comment by gamcoh** [comment]
So I think it's working, 

The problem was that the code in the channels file should be:
```typescript
app.service('video-events-handler').publish(video => app.channel(`room/${video.roomId}`).join(connection));
```

Now I just have to figure out how I can manage to hide the event from the user who has patched the service, thanks to you all!
