### ISSUE TITLE
How to perform internal login?

### ISSUE THREAD

**Issue by jaideepghosh** [feathersjs/feathers#1764]
### Steps to reproduce

- Create a generic service.
- Create a function in before hook in the `create` method. It should check the payload and retrieve the email from the payload.
- By using that payload, Get the user record from users table, and request auth service with email and password

### Expected behavior
In the response of this api, user should recieve the `authToken` after successful login.

### Actual behavior
User gets `Invalid login` error because the password in db is hashed. and the authenticate() compares the password after hashing the password payload.

**Comment by J3m5** [comment]
By doing that anybody that know the email of a user can be internally logged in and can receive the JWT token.
That make it insecure.
But you could totally do it by creating a custom authentication adapter that only need the email in order to authenticate the user.

What would be the use case here exactly?

**Comment by jaideepghosh** [comment]
The use case is:
- After user signup, he/she recieves the verification email.
- By clicking the provided verification link in the email, The user gets verified. As a response to this api, we're planning to send authToken after internal login.

**Comment by J3m5** [comment]
There is this package that does it: https://github.com/feathers-plus/feathers-authentication-management/blob/master/docs.md

Basically, what it does is that once the user signup, it generates a token, save it in the user record in the db and send it in a link in an email to the address of the user, then the user click on the link, it redirects him to a feathers service that get the token and check if it match with the token in the db, if it match, then the field "verified" on the user record is set to "true".

No need to authenticate the user "internally".

**Comment by jaideepghosh** [comment]
Thanks @J3m5 for your response. After a proper research I can conclude here that we can't perform internal login by getting the credentials from DB.
