### ISSUE TITLE
Feathers authentication with OAuth. JWT token expired

### ISSUE THREAD

**Issue by jirimoravcik** [feathersjs/feathers#1766]
Greetings,

Is there any way to prevent "jwt expired" when using feathers oauth?

The solution uses socket.io to communicate.

The issue is that the token expires at given moment, socketio cannot communicate with feathers backend anymore and you need to refresh the page. (refresh fixes the issue by recalling oauth backend)

Is there any way to prevent this either by preemptively "refreshing" the page or can this be achieved with socketio only?

Versions used:
"@feathersjs/authentication": "^4.3.0",
"@feathersjs/authentication-client": "^4.3.0",
"@feathersjs/authentication-local": "^4.3.0",
"@feathersjs/authentication-oauth": "^4.3.0",

**Comment by daffl** [comment]
This error probably doesn't have much to do with oAuth. If your JWT expires you can catch the error and redirect the user back to the login/oAuth flow. You can also check for expiration manually using the [jwt-decode](https://www.npmjs.com/package/jwt-decode) library on the client.
