### ISSUE TITLE
Set defult sorting to all queries

### ISSUE THREAD

**Issue by farhadarjmandf** [feathersjs/feathers#1767]
I want to set Sort param to all queries by default whitout calling sort function in api address in Hooks

in hook

export default {
  before: {
    all: [],
    find: [],
    get: [],
    create: [authenticate('jwt')],
    update: [authenticate('jwt')],
    patch: [authenticate('jwt')],
    remove: [authenticate('jwt')]
  },

**Comment by J3m5** [comment]
To do that you need to modify the query object in the before hook context context to add the $sort query.
[https://docs.feathersjs.com/api/hooks.html#context-params](https://docs.feathersjs.com/api/hooks.html#context-params)
[https://docs.feathersjs.com/api/services.html#params](https://docs.feathersjs.com/api/services.html#params)
