### ISSUE TITLE
nested object query

### ISSUE THREAD

**Issue by wwbluechip** [feathersjs/feathers#1769]
### mongodb document like this:
<img width="370" alt="截屏2019-12-30下午2 02 51" src="https://user-images.githubusercontent.com/24524783/71569885-12e83b00-2b0d-11ea-9ea2-e7e76f160565.png">

### i use http request :
```
 http://localhost:3030/api/pets?owner._id=5e0992c07caedc672aa4e897
 ```
### then i got :
```javascript
{
    "total": 0,
    "limit": 10,
    "skip": 0,
    "data": []
}
```
### however i use :
```
 http://localhost:3030/api/pets?owner.nickname=18855559357
 ```
### then i got correct response:
```javascript
{
    "total": 1,
    "limit": 10,
    "skip": 0,
    "data": [
        {
            "_id": "5e05d8954005d8d1b11ca53e",
            "sicks": [],
            "images": [
                "******"
            ],
            .................
            "price": "",
            "owner": {
                "nickname": "18855559357",
                "_id": "5e0992c07caedc672aa4e897",
                "unionid": "testunionid"
            },
            "createdAt": "2019-12-27T10:10:29.229Z",
            "updatedAt": "2019-12-27T10:10:29.229Z",
            "__v": 0
        }
    ]
}
```
# why can't use owner._id to query? i use mongoose

**Comment by J3m5** [comment]
What adapter are you using?
Mongodb or mongoose?
If you are using mongodb, this is because ObjectIDs needs to be converted in a before hook.

https://github.com/feathersjs-ecosystem/feathers-mongodb#querying

> Important: External query values through HTTP URLs may have to be converted to the same type stored in MongoDB in a before hook otherwise no matches will be found. Websocket requests will maintain the correct format if it is supported by JSON (ObjectIDs and dates still have to be converted).

**Comment by wwbluechip** [comment]
> What adapter are you using?
> Mongodb or mongoose?
> If you are using mongodb, this is because ObjectIDs needs to be converted in a before hook.
> 
> https://github.com/feathersjs-ecosystem/feathers-mongodb#querying
> 
> > Important: External query values through HTTP URLs may have to be converted to the same type stored in MongoDB in a before hook otherwise no matches will be found. Websocket requests will maintain the correct format if it is supported by JSON (ObjectIDs and dates still have to be converted).

i use mongoose..

**Comment by J3m5** [comment]
Did you try to put quotes around the id?
`http://localhost:3030/api/pets?owner._id="5e0992c07caedc672aa4e897"`

**Comment by wwbluechip** [comment]
> Did you try to put quotes around the id?
> `http://localhost:3030/api/pets?owner._id="5e0992c07caedc672aa4e897"`

I have tried. But it doesn't working

**Comment by wwbluechip** [comment]
I know that the _id in front-end is a string,but the _id in service side is an Object.it;s ObjectId().

**Comment by RossMck** [comment]
I know this is a oldie but if anyone wants to a nested select in feathersjs_nedb

 client.service('things').find({query: {$select: {'thing.nestedthing': 1,'thing.nestedthing2': 1 , 'notnestedthing': 1,'_id':1}}})
