### ISSUE TITLE
Feature request: listen to a specific ID's update/patch events

### ISSUE THREAD

**Issue by dbkaplun** [feathersjs/feathers#177]
I don't want to receive all update/patch events for a service, only for a certain object in that service. I think for now I can manually emit events for specific IDs, but it would be great if this was done automatically.

Fix would be implemented here: https://github.com/feathersjs/feathers-commons/blob/62f68921e41ec8a32fee604e730639320da3aa7d/src/sockets/helpers.js#L23-L75

**Comment by daffl** [comment]
You can filter events on the service side by implementing `updated`, `removed`, `patched` or `created` methods (see http://feathersjs.com/docs/#toc22). In there you can filter by id (or anything else) like this:

```js
var idsToListenTo = [ 0, 2, 33 ];

app.use('todos', {
  update: function(id, data, params, callback) {
    // Update
    callback(null, data);
  },

  updated: function(todo, params, callback) {
    // params === socket.feathers
    if(idsToListenTo.indexOf(todo.id) !== -1) {
      // Dispatch the todo data to this client
      return callback(null, todo);
    }

    // Call back with a falsy value to prevent dispatching
    callback(null, false);
  }
});
```

**Comment by dbkaplun** [comment]
I didn't know that I could use `callback` with a falsy value to prevent dispatching. But I don't think that will help, unless there's a way to detect what events a client is listening to. My goal is to always dispatch the event, but only to clients that are listening for `update`/`patch` events for a particular ID. Does that make sense?

**Comment by marshallswain** [comment]
This is a pretty cool idea.  I'm not sure I've thought it through all the way, but you might be able to extend one of the database adapters so that GET requests would work as a subscribe method that would maintain a list of ids the clients that are subscribed.  Then, in your custom event, you could use that list to send messages to only those clients.

**Comment by daffl** [comment]
I'm pretty sure that SocketIO and Primus don't dispatch events to clients that are not listening to them. Dispatching only to clients that actually requested the resource is a great idea though. This is how I think it could be done with hooks:

```js
app.configure(feathers.socketio(function(io) {
  io.use(function (socket, callback) {
    // Authorize using the /users service
    app.service('users').find({
      username: socket.request.username,
      password: socket.request.password
    }, function(error, user) {
      if(!error || !user) {
        return callback(new Error('Not authenticated!'));
      }

      socket.feathers = {
        user: user,
        ids: []
      };

      callback();
    });
  });
}));

app.use('/todos', {
  update: function(id, data, params, callback) {
    // Update
    callback(null, data);
  },

  updated: function(todo, params, callback) {
    // params === socket.feathers
    if(params.ids.indexOf(todo.id) !== -1) {
      // Dispatch the todo data to this client
      return callback(null, todo);
    }

    // Call back with a falsy value to prevent dispatching
    callback(null, false);
  }
});

// Update the ids list in a hook
app.service('todos').after({
  find: function(hook, next) {
    var ids = hook.params.ids;
    hook.result.forEach(function(todo) {
      ids.push(todo.id);
    });
    next();
  },

  get: function(hook, next) {
    hook.params.ids.push(hook.id);
    next();
  }
});
```

The problem is the question when to clean up the id store (other than on remove) but I don't think the id array would get too big and it will only stick around for the duration of the socket connection.

**Comment by marshallswain** [comment]
Maybe wait x number of seconds after a disconnect event to clear the ids.  That way if the user experiences a short hiccup in their connection and reconnects quickly, their subscriptions will still be in place (if that's how it works.  I'm just guessing.)
```js
socket.on('disconnect', function() {
      setTimeout(clearSubscriptions, 1000 * 60 * 2)
});
```

**Comment by marshallswain** [comment]
@dbkaplun if you get something working, it would be great if you could share your final code.  This would be a cool "recipe" to show off somewhere.

**Comment by ekryski** [comment]
So I think this should be solved by [event filtering](http://docs.feathersjs.com/real-time/filtering.html) now. Either you can prevent the emitting from the server side by adding a filter or the client probably shouldn't be listening to the event or you could explicitly just ignore it based on your criteria.

@dbkaplun my suggestion would be to add the the user's interests on the user object like so: `hook.params.user.interests`. This could already come as part of the user object directly from the db or be added in a hook. Then filter the events sent out if your `if (user.interests.indexOf('bikes') === -1) { `
