### ISSUE TITLE
patch request without object id

### ISSUE THREAD

**Issue by somyaranjank** [feathersjs/feathers#1770]
How can patch a mongodb document with a separate key (other than object id)?

**Comment by J3m5** [comment]
You need to pass null as the id and add a query object that match the record with the property you want to patch.
https://docs.feathersjs.com/api/databases/common.html#adapter-patch-id-data-params

**Comment by somyaranjank** [comment]
But i don't want to enable multi patch feature on my service

**Comment by J3m5** [comment]
I don't know if you really need to enable the multi patch feature if your query can only match one record.
You should try.

**Comment by daffl** [comment]
You probably still do in that case. Alternatively you can change the [name of the id property](https://docs.feathersjs.com/api/databases/common.html#options) though.
