### ISSUE TITLE
Problem getting rawBody

### ISSUE THREAD

**Issue by SeveHo** [feathersjs/feathers#1771]
Hey, I have a problem keeping the raw body for stripe signature verifications. I am able to copy the raw buffer but every time calling `stripe.webhooks.constructEvent()` stripe throws the error that says:

`'No signatures found matching the expected signature for payload. Are you passing the raw request body you received from Stripe? `

Somehow my buffer is still changed during parsing or copying but I really have now clue were.

References like this didn't help me so far: https://github.com/stripe/stripe-node/issues/341 even though it seems that setups like mine (see below) helped people solving this issue.

Using a simple ```app.post()``` setup like described [here](https://stripe.com/docs/payments/checkout/fulfillment#webhooks) in `app.js` with works for me but this is obviously no solution.

Has anyone encountered the same so far or knows why my the request body isn't in the original format anymore?

I'd really appreciate your help.

Here is my code:

`app.js`
```node
app.use(
  express.json({
    limit: "100mb",
    verify: (req, res, buf) => {
      if (req.headers["stripe-signature"] && Buffer.isBuffer(buf)) {
        req.rawData = buf;
      }
    }
  })
);
```

And later on in the service I copy the raw data to the feathers object
`payment-webhooks.service.js`
```node
const rawBodyMiddleWare = async (req, res, next) => {
    req.feathers.rawBody = req.rawBody;
    next();
  };

 app.use(
    "/payment-webhooks",
    rawBodyMiddleWare,
    new PaymentWebhooks(options, app)
  );
```

And in my custom service class I'm using the rawBody like this:
``payment-webhooks.class.js``
```node
async create(data, params) {
    const { endpointSecret } = await this.app.get("payments");

    const signature = params.headers["stripe-signature"];

    let event;
    try {
      event = stripe.webhooks.constructEvent(
        params.rawBody,
        signature,
        endpointSecret
      );
    } catch (err) {
      console.log(err);
      return new BadRequest(`Webhook Error: ${err.message}`);
    }

    // Handle the checkout.session.completed event
    if (event.type === "checkout.session.completed") {
      const session = event.data.object;
      // TODO
    }
    return { received: true };
  }
```

### System configuration

Feathers versions: 4.3.x

**Comment by rodrigorellana** [comment]
same problem even using oficial docs https://github.com/stripe/stripe-node/blob/master/examples/webhook-signing/express.js

**Comment by florianbepunkt** [comment]
I'm using a similiar setup for woocommerce webhooks.

I can confirm that this gives me the unaltered buffer

```
app.use(
  express.json({
    verify: (req: IRequestRawBody, res, buf) => {
      const rawEndpoints: string[] = ["/wc-webhook"];

      if (req.url && rawEndpoints.includes(req.url)) {
        req.rawBody = buf;
      }
    }
  })
);
```

If I calculate a signature on the raw request body, I can verify the authenticity. Since concept and setup is similiar to stripe, my guess is that the problem is not with the request body parsing but with the way the signature is verified. Have you tried to manually sign and verify a request? Does this work?

**Comment by daffl** [comment]
Feathers is not changing anything in the data and I've used this kind of setup before. If it is the same problem with a plain Express application it is probably more related to Stripe than Feathers.

**Comment by SeveHo** [comment]
Just to let you know how I solved the problem:
I did a similar workaround as proposed in [feathers-stripe-webhooks](https://github.com/fixate/feathers-stripe-webhooks) by evaluating the signature **before** the express body parser.

My setup now looks like this:
**app.js**
```node
const stripe = require("stripe");
const stripeSignatureValidationMiddleware = require("./custom-middleware/stripeSignatureValidationMiddleware");

app.stripe = stripe(app.get("payments").apiKey);

// IMPORTANT: Define stripe middleware before json body parser
app.configure(
  stripeSignatureValidationMiddleware(app.stripe, "/payment-webhooks")
);

app.use(express.json());
```

**stripeSignatureValidationMiddleware.js**
```node
const bodyParser = require("body-parser");

module.exports = function stripeSignatureValidationMiddleware(stripe, route) {
  return function() {
    const app = this;
    const bodyParserRaw = bodyParser.raw({ type: "*/*" });
    const { endpointSecret } = app.get("payments");

    app.post(route, bodyParserRaw, (req, res, next) => {
      const signature = req.headers["stripe-signature"];
      if (!signature) {
        res.status(400).end();
        return;
      }
      let event;
      try {
        event = stripe.webhooks.constructEvent(
          req.body,
          signature,
          endpointSecret
        );
        req.body = event;
      } catch (err) {
        res.status(400).end();
        return;
      }
      next();
    });
  };
};
```

I'd also appreciate suggestions about improvements.

**Comment by SeveHo** [comment]
@florianbepunkt even your solution did not work for me but I think this is definitely the cleaner approach.

**Comment by florianbepunkt** [comment]
As David said this would indicate, that the problem lies with stripe or some configuration issue. I use my implementation with two different webhooks. Maybe it is the type param. It would be interesting to have some info from the stripe docs how they calculate they signature of the request.

**Comment by SeveHo** [comment]
This is also working for you with stripe or just woocommerce?

**Comment by florianbepunkt** [comment]
Haven't used stripe. Using this with woocommerce and an internal webhook.

**Comment by php4umagento** [comment]
@SeveHo your solution worked perfectly for me! thanks
