### ISSUE TITLE
Read nested object from config/*.json files

### ISSUE THREAD

**Issue by corepay** [feathersjs/feathers#1773]
##### config/default.json

```json
{
  "host": "localhost",
  "port": 3030,
  "public": "../public/",
  "paginate": {
    "default": 40,
    "max": 200
  },
  "keys": {
    "encryption": "hamburger",
    "master": "hotdog"
  },
...
}
```

##### ANY `.js` FILE - here is actual example in hook

```javascript
const feathers = require('@feathersjs/feathers');
const configuration = require('@feathersjs/configuration');
const config = feathers().configure(configuration());
const { Forbidden } = require('@feathersjs/errors');

module.exports = {
  before: {
    all: [
      async context => {
        const { params, path } = context;

        if (path.startsWith('admin')) {
          if (!params.headers['X-Master-Key']) {
            throw new Forbidden(
              'You are not authorized to access these resources'
            );
          }
          if (
            !config
              .get('keys/masterKeys')
              .includes(params.headers['X-Master-Key'])
          ) {
            throw new Forbidden('The master key provided is not authorized');
          }
        }
      }
    ],
```
Getting ERROR the config `keys/masterKeys` is not found

### Expected behavior

Should be able to fetch nested `keys/masterKey` from config file

### Actual behavior

Not reading the the nested `keys/masterKey` in the config file.  Receiving `undefined`

I also tried `keys.masterKey` without success

I went to [node-config](https://github.com/lorenwest/node-config) and it tells me a nested json object is accepted.  Your config files also have nested params for `paginate` and `authentication` so I assume this is possible and easy - just (embarrassingly) have not been able to figure it out.  Having no problems of course with top-level values in the .json config but OCD is kicking in hard now as I am refactoring and organizing the mess I initially made learning Feathers.

Any help of course very appreciated.

**Comment by daffl** [comment]
Configuration is accessed via [app.get](https://docs.feathersjs.com/api/application.html#get-name) which does not support dot notation. So it would be `app.get('keys').master`. Alternatively you can require `node-config` directly and access its values:

```
const config = require('node-config');

config.get('keys.master');
```

**Comment by corepay** [comment]
aha - perfect and thank you very much David!  Appreciate your work….
