### ISSUE TITLE
allowUnauthenticated works, or do we have any other approach to achieve this?

### ISSUE THREAD

**Issue by jaideepghosh** [feathersjs/feathers#1775]
### Steps to reproduce
As metioned in this [stackverflow](https://stackoverflow.com/questions/51830738/hook-to-check-if-user-is-authenticate-in-feathers-without-send-unauthorized-err#51855033) solution by @daffl 
in which he mentioned that `The authenticate hook has a currently undocumented allowUnauthenticated option which, if set to true, just ads a params.authenticated flag.`

```
find: [
  authenticate('jwt', {
    allowUnauthenticated: true
  }),
  doSomething(),
]
```

### Expected behavior
It should execute the next hook method.

### Actual behavior
It is returning with `NotAuthenticated` error without executing the next hook method.

The use-case is, I want to execute methodA() is the user is authenticated, or else execute methodB() if not.

Let me know if we can do this by using `feathers-hooks-common`
```
iffElse(isAuthenticated(),[methodA()],[methodB()]
```

**Comment by daffl** [comment]
There now is a [Cookbook entry for anonymous authentication](https://docs.feathersjs.com/cookbook/authentication/anonymous.html). I updated the answer accordingly.

**Comment by jaideepghosh** [comment]
Thanks @daffl :+1:
