### ISSUE TITLE
Custom methods in Service

### ISSUE THREAD

**Issue by banisirohi** [feathersjs/feathers#1777]
Based on official documentation (https://docs.feathersjs.com/help/faq.html#how-do-i-create-custom-methods),  not custom methods are allowed.

I'm meaning to use featherjs for my next project. But due to above constraint, I wanted to know how it would work in few scenarios where I need to have multiple find methods like FindById() or FindByName or FindByOrg something of that sort. How do we achieve that thru Featherjs.

I would really appreciate if anyone can direct me to some real world working opensource featherjs code base.

Thank you so much.

**Comment by daffl** [comment]
That functionality is already supported by a Feathers server out of the box:

- `FindById` - `app.service('myservice').get(id)` or `GET /myservice/<id>`
- `FindByName` - `app.service('myservice').find({ query: { name } })` or `GET /myservice?name=nametofind`
- `FindByOrg` - `app.service('myservice').find({ query: { organizationId } })` or `GET /myservice?orgnizationId=<organizationId>`

For more information see the [querying API docs](https://docs.feathersjs.com/api/databases/querying.html) and the [Express REST method mappings](https://docs.feathersjs.com/api/express.html#express-rest).
