### ISSUE TITLE
Adding an OR query to a before hook

### ISSUE THREAD

**Issue by emilesteen** [feathersjs/feathers#1783]
In my API I have a security-group service. This security-group service has 2 security-groups by default, admin and user groups. These security-groups do not belong to any company in particular and should be available to all companies, therefor their companyId is set to null. When I call the find endpoint for security-groups, I pass in my companyId through an authentication token. I would then like to add a before hook that filters my results to only return security-groups that corresponds to the given companyId or security-groups that have a null companyId, meaning it is available to all companies. I have 3 solutions for this problem but all of them have a catch unfortunately.

## Solution 1: Add an OR to the query string in the before hook

`context.params.query['$or'] = [ { companyId: companyId }, { companyId: null } ];`

The problem with this approach is that this overrides any OR that is passed with the query string. For example, if i were to call this endpoint 

> /security-groups?$or[0][name]=someone&$or[1][name]=someone else

it would replace the or[0] with companyId=companyId and or[1] with companyId=null

## Solution 2: Add an IN to the query string in the before hook

`context.params.query.companyId = { $in: [null, companyId] };`

The problem with this approach is that the SQL IN operator does not work as you would expect and does not return values where the companyId is equal to null, therefor it only return values where the companyId equals the given companyId and not where the companyId is equal to null. Our fix for this solution is to give our admin and user security group some default companyId, but this is not possible in our system.

## Solution 3: Adding our own sequelize object

`context.params.sequelize = {
    where: {
      [Op.or]: [
        {
          companyId: null
        },
        {
          companyId: companyId
        }
      ]     
    }
  }`

The problem with this approach is that the passed in query string then no longer generates its own sequelize object, meaning we sacrifice a lot of built in feathers functionallity which we would prefer not to do.

## Conclusion

I am either looking for a fix for any of these solutions or another alternative for my problem

**Comment by emilesteen** [comment]
We managed to find a solution for out problem:

`!!context.params.query["$and"]
        ? null
        : (context.params.query["$and"] = []);`
`context.params.query["$and"].push({
        $or: [{ companyId: companyId }, { companyId: null }]
      });`

we push the OR operator onto a AND operator. This AND operator is not documented here: https://docs.feathersjs.com/api/databases/querying.html

but it works similarly to the OR operator.

**Comment by daffl** [comment]
Ah yes, `$and` is Sequelize and MongoDB specific. To extend or set the `$or` you could also use some JavaScript destructuring magic:

```js
const { query = {} } = context.params;
const { $or = [] } = query;

$or.push([ { companyId: companyId }, { companyId: null } ]);

context.params.query = {
  ...query,
  $or
}
```

This will either create a new `$or` or extend the existing one.

**Comment by edwardsmarkf** [comment]
this might make a great recipe example.

Thank you,

Mark Edwards
