### ISSUE TITLE
Setting usernameField to 'username' breaks local auth

### ISSUE THREAD

**Issue by plhosk** [feathersjs/feathers#1785]
### Steps to reproduce

Create feathers app with authentication:

`feathers generate app`
`npm start`

Create a user:
```
POST http://localhost:3030/users { email: "test", password: "test" }
```
Authenticate user: 
```
POST http://localhost:3030/authentication { email: "test", password: "test" }
```
Result: authentication is successful.

Now stop the app, change all instances of the string "email" in the project to "username"

`npm start'
Create a user:
```
POST http://localhost:3030/users { username: "test", password: "test" }
```
Authenticate user: 
```
POST http://localhost:3030/authentication { username: "test", password: "test" }
```
Result: authentication fails.

The problem seems to be in the configuration object in AuthenticationBaseStrategy. When usernameField = "username" in config.json, the config object instead sets usernameField to the name of my Windows login account "Paul". This seems to be why the authentication fails.

If I put `console.dir(config)` in a couple of spots in strategy.js in the authentication-local module, this is the result after attempting authentication:

```
{ usernameField: 'Paul', passwordField: 'password' }
{
  hashSize: 10,
  service: 'users',
  entity: 'user',
  entityId: undefined,
  errorMessage: 'Invalid login',
  entityPasswordField: 'password',
  entityUsernameField: 'Paul',
  usernameField: 'Paul',
  passwordField: 'password'
}
{ usernameField: 'Paul', passwordField: 'password' }
{ usernameField: 'Paul', passwordField: 'password' }
```

### Expected behavior

It should return JWT like it does with usernameField = "email"

### Actual behavior

```
{
  "name": "NotAuthenticated",
  "message": "Invalid login",
  "code": 401,
  "className": "not-authenticated",
  "errors": {}
}
```

### System configuration

**Module versions** (especially the part that's not working):

@feathersjs/authentication 4.4.3

**NodeJS version**:

12.14.1

**Operating System**:

Windows 10 1903

**Comment by daffl** [comment]
This is mentioned in the [__Important__ section in the local authentication configuration API](https://docs.feathersjs.com/api/authentication/local.html#configuration).

**Comment by plhosk** [comment]
I see. I was following the Quick Start and missed this information. It's an unfortunate problem because `username` is the obvious choice for usernameField...

**Comment by plhosk** [comment]
Specifically I think the notice should also be added here: https://docs.feathersjs.com/guides/basics/authentication.html#registering-a-user
