### ISSUE TITLE
Authentication In middleware

### ISSUE THREAD

**Issue by zer0-two** [feathersjs/feathers#1786]
Hi, I'm new to Feathersjs and I'm trying to implement authentication with strategies like (local / jwt) in middleware  and here is my codes in `src/middleware/index.js`: 
```js
const { authenticate } = require('@feathersjs/express');

module.exports = app => {
	app.use('/login', (req, res) => {
		res.render('login', {title: "Login"});
	});	
	app.use('/panel',authenticate('local'), (req, res) => {
		res.render('panel', {title: "panel"});
	});
};
```
### Actual behavior
I get HTTP 401 error code, Is there something that I'm missing here ? :sweat_smile: 

### System configuration
**NodeJS version**: v10.16.0

**Operating System**: windows 7 (64bit)

**Browser Version**: Chrome V79

**Comment by daffl** [comment]
The `local` strategy is not supported for middleware authentication. See the [API docs](https://docs.feathersjs.com/api/express.html#express-authenticate) how to add JWT authorization.

**Comment by zer0-two** [comment]
:disappointed: Sad, is there any other way to do this? or something like this ?

**Comment by daffl** [comment]
It's possible but not something I'm particularly keen on adding and maintaining docs for (always welcome as a [Cookbook](https://docs.feathersjs.com/cookbook/) contribution).

Basically, [set up the Express session](https://expressjs.com/en/resources/middleware/session.html), call `app.service('authentication').create` in your `login` endpoint and then register the `accessToken` on the session:

```js
app.use(session());
app.use((req, res, next) => {
  req.authentication = req.session.authentication;

  next();
});

app.get('/login', (req, res) => {
  res.render('login', {title: "Login"});
});

app.post('/login', (req, res, next) => {
  app.service('authentication').create(req.body).then(authResult => {
    req.session.authentication = {
      strategy: 'jwt',
      accessToken: authResult.accessToken
    }

    res.redirect('/panel')
  }).catch(next);
});

app.get('/panel', authenticate('jwt'), (req, res) => {
  // req.user
  res.render('panel', {title: "panel"});
});
```

**Comment by daffl** [comment]
This has now been documented in https://docs.feathersjs.com/cookbook/express/view-engine.html
