### ISSUE TITLE
How to suppress Property 'xxx' does not exist on type error?

### ISSUE THREAD

**Issue by elixiao** [feathersjs/feathers#1788]
I registered a sayHello mixin  following the [doc](https://docs.feathersjs.com/api/application.html#mixins)

```js
app.mixins.push((service, path) => {
  service.sayHello = function() {
    return `Hello from service at '${path}'`;
  }
});
```
by got the following error when trying to use the mixin:

```sh
error TS2339: Property 'sayHello' does not exist on type 'HelloService'.
```

here is my HelloService:

```js
export class HelloService {
  async find(params: Params) {
    this.sayHello()
    return super.find(params)
  }
}
```

How to suppress the typescript error ?

**Comment by daffl** [comment]
If possible, I'd recommend not to use mixins and extend the service classes instead.

It is also possible to extend the registered interface (e.g. in https://github.com/feathersjs/feathers-chat-ts/blob/master/src/services/messages/messages.service.ts#L11) with the type you are extending:

```ts
interface SayHello {
  sayHello () : string;
}

declare module '../../declarations' {
  interface ServiceTypes {
    'messages': Messages & ServiceAddons<any> & SayHello;
  }
}
```

**Comment by elixiao** [comment]
@daffl after adding `& SayHello`, still get `Property 'sayHello' does not exist on type 'ArticleService'` error. Here is my code: 

```ts
interface SayHello {
  sayHello () : string;
}

declare module '../../declarations' {
  interface ServiceTypes {
    'articles': ArticleService & ServiceAddons<any> & SayHello;
  }
}
```

```ts
export class ArticleService extends Service {
  async find(params: Params) {
    this.sayHello()
    return super.find(params)
  }
}
```

![image](https://user-images.githubusercontent.com/2291033/72791686-b17e3c80-3c72-11ea-9f89-faa47eebe4c5.png)

by the way, how to extend the service classes? I want to add some functions for all services. After reading the [doc](https://docs.feathersjs.com/api/application.html#mixins), I found the following comment: 

> Adding your own mixins allows to add functionality to every registered service.

So why mixins are not best practice for extending classes?

**Comment by daffl** [comment]
This will only work if you are retrieving the service with `app.service()`. The reason why adding methods via mixins are not recommended here (and with TypeScript in general) is exactly the issue you are running into. If you want to use that functionality in your class implementation then it should be added in the same place not somewhere entirely different.
