### ISSUE TITLE
Integrating Apollo with Feathers service/hooks

### ISSUE THREAD

**Issue by hybridmuse** [feathersjs/feathers#1789]
How can an Apollo graphql endpoint integrate with a Feathers service (i.e. have access to hooks, authentication guard, etc.)?

Apollo abstracts out Express's `app.use`, providing us instead with these registration instructions:
```js
const apolloServer = new ApolloServer({
    typeDefs,
    resolvers,
    context: ({ req, res }) => ({
        provider: req.feathers.provider,
	headers: req.feathers.headers
    })
})

apolloServer.applyMiddleware({ app })
```

I'm currently forced to use the endpoint independently from Feathers, as it isn't clear where/how the Apollo middleware must be piped on the graphql.service.js file.

I'm aware of [this closed issue](https://github.com/feathersjs/feathers/issues/929) and [this stackoverflow answer](https://stackoverflow.com/questions/56440162/how-do-we-use-hook-for-feathersjs-apollo-v2), which didn't solve it for me. Any help appreciated.

**Comment by kfern** [comment]
@hybridmuse You can see an example in https://github.com/EuropeanRespiratorySociety/api-ers

**Comment by hybridmuse** [comment]
Thanks for the example, although it doesn't use Apollo nor does it integrate the /graphql endpoint to Feathers service hooks.

**Comment by daffl** [comment]
That is currently not possible. You can however use the [Express authentication](https://docs.feathersjs.com/api/express.html#express-authenticate) middleware to authenticate requests with a token issued by Feathers authentication and call `app.service('')` for any service in your resolvers (which will also run hooks).

There was some work in progress [for a Feathers Apollo Server integration](https://github.com/feathersjs-ecosystem/apollo-server/tree/feathers-apollo) but it was written for a previous version and has not yet been updated.

**Comment by hybridmuse** [comment]
Thank you, this gets the job done. Also nice work on extracting the hooks functionality!

**Comment by hybridmuse** [comment]
I believe this can be closed, as the graphql endpoint isn't really a service in itself but rather an entry point for service resolvers. Or feel free to leave open for now if further apollo/graphql integration is on the way.
