### ISSUE TITLE
How to work with Feathersjs on Android

### ISSUE THREAD

**Issue by borkowsky** [feathersjs/feathers#1791]
Can i use Feathers.js framework to build backend API server for Android application? How can i do it?

**Comment by petersaints** [comment]
Yes, you can. If you don't need real-time updates you can just connect to it using the RESTful HTTP API exposed by Feathers services by using a library such as OkHttp or Volley.

If you need real-time communication you can connect to your Feathers using the Socket.io API. To do that you just need a Socket.io Client library, such as this one: https://github.com/socketio/socket.io-client-java

You can then interact with your server from your Android app, using Java or Kotlin code, just like you would if you used the JavaScript-based Socket.io Direct Connection as explained here: https://docs.feathersjs.com/api/client/socketio.html#direct-connection
