### ISSUE TITLE
sequelize associate in typescript

### ISSUE THREAD

**Issue by syns2191** [feathersjs/feathers#1796]
i generate service and i got models associate like this
```
(donation as any).associate = function (models: any) {
    // Define associations here
    // See http://docs.sequelizejs.com/en/latest/docs/associations/
  };
```

and then i try to add the associate like this

```
(donation as any).associate = function (models: any) {
    donation.belongsTo(models.category, {foreignKey: 'kategori_id', as: 'categories'})
    // Define associations here
    // See http://docs.sequelizejs.com/en/latest/docs/associations/
  };
```

and i got error like this

> The 'this' context of type 'typeof Model' is not assignable to method's 'this' of type 'ModelCtor<Model<unknown, unknown>>'.
>   Type 'typeof Model' is not assignable to type 'new () => Model<unknown, unknown>'.
>     Cannot assign an abstract constructor type to a non-abstract constructor type.ts(2684)

the question is how to associate model using typescript ?

**Module versions** (especially the part that's not working):
**NodeJS version**: 10.11.0
**Operating System**: macos

**Comment by erfanSW** [comment]
@syns2191 I have the same issue . what should I do?
