### ISSUE TITLE
How to get the user from a service created with Express function?

### ISSUE THREAD

**Issue by averri** [feathersjs/feathers#1799]
This is a question.

How can I get the authenticated user in the service created with an Express function?

Example:
```javascript
module.exports = app => {
  app.use('/test', (req, res) => {
   // I want get the authenticated user here.
    res.send({status: 'ok'})
  })
}
```

There is an application hook already configured to authenticate all requests:
```javascript
  before: {
    all: authenticate('jwt')
  },
```

**Comment by daffl** [comment]
This is documented in [the express.authenticate()](https://docs.feathersjs.com/api/express.html#express-authenticate) API documentation.

**Comment by averri** [comment]
Cheers @daffl.
