### ISSUE TITLE
How to handle errors uniformly on the Client ？

### ISSUE THREAD

**Issue by idreamin** [feathersjs/feathers#1800]
How to handle errors uniformly on the Client ？ Now I have to catch each request individually！ Like this...
feathersClient.service('users').find({}).then(response => {
  console.log('Authenticated!', response);
}) .catch(function(error){
    console.error('Error authenticating!', error);
 });
Thank you very much !

**Comment by J3m5** [comment]
You can use hooks with the client too.
So you can set catch errors on the app error hook or per service.
