### ISSUE TITLE
Is there a way to hook the request chain?

### ISSUE THREAD

**Issue by jnardone** [feathersjs/feathers#1801]
Using latest (4.5.1) with node 12.14.1...

I'm trying to use https://github.com/vicanso/async-local-storage (which is based on Node's async_hooks: https://nodejs.org/api/async_hooks.html) to track some information across the lifetime of a request.

For example: code calls service(a) which calls service (b) which calls service(c), I want to register a request ID during (a) so that I can still access that ID in (c). 

What does work:
- if I hook requests inside the transport (e.g. as REST/socket.io middleware) prior to feathers services, I can create a scope in a-l-s and mostly persist this through.

What does not work:
- If I simply call a service's method (for example, an internal service) then this apparently has no call chain; if service (a) calls service (b), then in app.hooks.js when I go to get the current context, it doesn't exist.  

I'm not quite sure the specific thing i'm asking (other than "why doesn't this seem to work? are feathers calls to dependent services not related in some way?") and if there are alternative approaches I can take.  One solution that is NOT suitable is explicitly passing state through every `params` parameter to every service.  This needs to be something that can be introspected vs. explicitly passed to all children.

**Comment by daffl** [comment]
Every Feathers service call is stateless and there is no hidden magic in how Feathers call contexts are passed. It is the exact same as with any other normal JavaScript call. The only solution _is_ to explicitly pass the state you need to all dependent calls.

**Comment by jnardone** [comment]
Hm.  So has nobody asked for some kind of correlating ID to track essentially a request chain for a given service? Or the ability to identify the parent of a service invocation?

**Comment by daffl** [comment]
Yes but everybody is just passing it along in `params`. That's kind of what it is intended for.

**Comment by jnardone** [comment]
We've got a few thousand calls we'd have to do this for, so we'll figure out some other path

**Comment by daffl** [comment]
Maybe with a Codemod that adds it everywhere. Thinking about it for a bit I can't seem to come up with a way to do this reliably in a dynamic way in Node (it would be different with other languages that use a separate thread for each request).

**Comment by jnardone** [comment]
async-local-storage mostly does this, but the framing event is the network event that generally happens in the REST or socket handler (like I said, in this way we can persist state across the request lifecycle, it's mostly a problem with internal chains and wanting to replicate this with without hoping for a new asynchronous resource inside the node engine.  async hooks are weird and tough to grasp (for me) so it's not entirely clear how I could force that behavior on my own.  or if it's even worth it.
