### ISSUE TITLE
how to get fully usage of feather socket for my social-network app 

### ISSUE THREAD

**Issue by abdolrhman** [feathersjs/feathers#1807]
- I am new to feather "Best framework ever :))" 
I am building something like Facebook,
in which when someone posts something all his friends get alerted, 

now the problem is, I need to save all users socket-id, 
yet socket-id always change whenever restart or whatever happen, 
is there any way I can use feather-Js to solve this problem,

Thank you best team, 
I really appreciate the work done for this framework.

**Comment by daffl** [comment]
Socket IDs are generated randomly. Feathers handles reconnection and identifying sockets via channels which is documented in more detail in the [channel API](https://docs.feathersjs.com/api/channels.html).

**Comment by abdolrhman** [comment]
Thanks, @daffl , also good profile picture :))

**Comment by daffl** [comment]
Haha, thanks! Was about time to replace the 8+ year old one 😄
