### ISSUE TITLE
How to set the number of rounds used by Bcryptjs to generate a password salt?

### ISSUE THREAD

**Issue by averri** [feathersjs/feathers#1810]
Using `@feathersjs/authentication`, how to configure the number of rounds used by Bcryptjs to generate the password salt? 

Bcryptjs uses the default value of 10, some applications may require setting another value respecting the trade-off between speed and security.

References of Bcryptjs configuration: 
- https://github.com/dcodeIO/bcrypt.js#gensaltsyncrounds-seed_length
- https://github.com/dcodeIO/bcrypt.js#gensaltrounds-seed_length-callback

**Comment by daffl** [comment]
You can [customize](https://docs.feathersjs.com/api/authentication/local.html#customization) the [hashPassword](https://docs.feathersjs.com/api/authentication/local.html#hashpassword-password) method of the local strategy.

**Comment by jnardone** [comment]
The 2nd parameter to `.hash`, if a number, is the number of rounds.

The local strategy does this

```
  async hashPassword (password: string, _params: Params) {
    return bcrypt.hash(password, this.configuration.hashSize);
  }
```

Thus, if you set `hashSize` in your configuration for the `local` strategy you should be able to define the number of rounds.

**Comment by daffl** [comment]
I thought `hashSize` was the size of the hash that is being generated? Also realized that that options should also be part of the docs.

**Comment by jnardone** [comment]
Nope!  You don't get to do that.

bcrypt.hash:

https://github.com/dcodeIO/bcrypt.js/blob/master/src/bcrypt.js#L160

```
if (typeof s === 'string' && typeof salt === 'number')
            bcrypt.genSalt(salt, function(err, salt) {
                _hash(s, salt, callback, progressCallback);
            });
```

in this case `s` is the string to hash, and `salt` is the number of rounds.  Badly named.

`salt` is passed to `genSalt`

https://github.com/dcodeIO/bcrypt.js/blob/master/src/bcrypt.js#L111

where the first parameter (`salt` earlier, `rounds` inside `genSalt`) is passed (as `rounds`) to `genSaltSync`.

**Comment by daffl** [comment]
Weird, the [bcryptjs docs on npm](https://www.npmjs.com/package/bcryptjs) say "Salt length to generate or salt to use". Maybe the parameter should be renamed then.
