### ISSUE TITLE
how to generate token after create user

### ISSUE THREAD

**Issue by abdolrhman** [feathersjs/feathers#1811]
I want to return token when user created, I know there is authentication API that do that
but I want to have a token when creating a user,

thank you

**Comment by abdolrhman** [comment]
btw, i tried use after hook with this
`    const user = context.data;
    const data = await context.app.service('authentication').create({
      email: user.email,
      password: user.password,
      strategy: 'local'
    });`

didnt work

**Comment by abdolrhman** [comment]
figure it out, dam it took me a while, well u need to pass "password without encryption"
so I used context argument which holds the password without encryption

> context['arguments'][0]['password']
dont know if there is another way

**Comment by daffl** [comment]
You could copy `context.data` into another property in the context in a `before` hook. Then it will be available unmodified there.

**Comment by abdolrhman** [comment]
@daffl thanks buddy as always, u always there :))
but btw is it right to gett the password this way `context['arguments'][0]['password']
`?
thanks, bro ^^

**Comment by daffl** [comment]
Well, it works but I'd say my suggestion would be more explicit on what's supposed to happen here.

**Comment by abdolrhman** [comment]
yeah, I just wanted to make sure of me getting understanding argument variable, I went with ur suggest the moment u wrote it^^
