### ISSUE TITLE
Is it possible to return nothing?

### ISSUE THREAD

**Issue by MarcGodard** [feathersjs/feathers#1813]
Is there a way to prevent the hook from returning anything? Reason: I am saving a form as they enter stuff, and the returned data causes a refresh and the focus of the form is lost so you cannot tab to the next field. I tried `context.result = null` and it still returned null which caused a lot of other issues.

If I throw an error and catch it on the front end, this works, but there must be a better way.

I was thinking if result is null (and dispatch of course) the sockets or rest connection doesn't return anything. Not talking about returning a `null` or `{}` I am talking about not returning.

**Comment by daffl** [comment]
It is not, any call requires a response to the client. It is probably easiest to return an empty or other kind of special object to handle the case you need.

**Comment by MarcGodard** [comment]
Ok thanks
