### ISSUE TITLE
Authenticating with just the JWT Token

### ISSUE THREAD

**Issue by rasmusgadensgaard** [feathersjs/feathers#1817]
Im trying to create a client which displays values from a /comment endpoint. I got everything working via REST, and I'm trying to make it realtime via the featherjs client

All users are anonymous, so user authentication is not needed. Instead I have generated a single JWT token which the REST client currently sends in a authorization header like this: 

```
headers: {
            'Accept': 'application/json',
            'Content-Type': 'application/json',
            'Authorization': JWT_TOKEN
        },`
```

I cannot get the feathersjs client to work in this way, I keep getting "not authenticated. Clearly there is something I'm missing

The client setup looks like this:

```js
import io from 'socket.io-client';
import feathers from '@feathersjs/client';
import auth from '@feathersjs/authentication-client';

const socket = io('http://localhost:3030');
const client = feathers();

//Setup transport
client.configure(feathers.socketio(socket));

client.configure(auth({
    clientstorageKey: 'auth'
}))


//Setup auth
client.authentication.setAccessToken("JWT_TOKEN")

client.reAuthenticate().then((res) =>
{
    console.log(res);
}).catch((err) =>
{
    console.log(err);
});


export default client;
```

And here I try to get the comments

```js
import client from './Comments/server';
const crosstable = client.service('crosstable');
crosstable.find();
```

I've tried different solutions, but I think I would expect being able to set the authentication completely on the client setup phase?

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
"@feathersjs/authentication-client": "4.5.1",
"@feathersjs/client": "4.5.1",
"react": "16.8.6",
"socket.io-client": "2.3.0",

**NodeJS version**:
v10.16.0

**Operating System**:
Windows 10

**Module Loader**:
"Webpack": "4.20.2"

**Comment by daffl** [comment]
If you have the token already you still need to authenticate the socket with the [`jwt` strategy](https://docs.feathersjs.com/api/authentication/jwt.html#options):

```js
import io from 'socket.io-client';
import feathers from '@feathersjs/client';
import auth from '@feathersjs/authentication-client';

const socket = io('http://localhost:3030');
const client = feathers();

//Setup transport
client.configure(feathers.socketio(socket));

client.configure(auth());

client.authenticate({
  strategy: 'jwt',
  accessToken: 'YOUR JWT'
}).then(() => {
 // Make authenticated requests here
}).catch(error => {
  // Handle errors here
});
```

**Comment by rasmusgadensgaard** [comment]
I see, but does that mean that I cannot use the 'client' again like you do in the react-chat example. Essentially, Im trying to accomplish something similar to this:

https://github.com/feathersjs-ecosystem/feathers-chat-react/blob/master/src/application.js

```
// Add new messages to the message list
    messages.on('created', message => this.setState({
      messages: this.state.messages.concat(message)
    }));
```

So right now after the client.authenticate() above, I export default client, and use it in the my application's componentDidMount() method like this:

```
const comments = client.service('comments');
comments.find();
```
but then I get the error: 

```
type: "FeathersError"
name: "NotAuthenticated"
message: "No auth token"
code: 401
className: "not-authenticated"
```

So I thought: Ah, I have to wait for the authentication like you do, so I tried this in the componentDidMount:



```
const comments= client.service('comments');
		comments.on('authenticated', login => {

			Promise.all([
			  comments.find()
			]).then( ([ comments ]) => {
			  // We want the latest messages but in the reversed order
			  const commentData = comments.data;
	  
			  console.log(commentData );
			  // Once both return, update the state
			});
		  });

```

but nothing at all happens here. As you can see Im trying to setup sort of a listener in the componentDidMount

**Comment by daffl** [comment]
Ideally you wouldn't render those components until the authentication has returned. If you do want to wait as suggested, the `authenticated` event is emitted on the `app`:

```js
const comments = client.service('comments');

client.on('authenticated', login => {
  Promise.all([
    comments.find()
  ]).then( ([ comments ]) => {
    // We want the latest messages but in the reversed order
    const commentData = comments.data;

    console.log(commentData );
    // Once both return, update the state
  });
});
```
