### ISSUE TITLE
Multi-sort syntax of rest api

### ISSUE THREAD

**Issue by akvaliya** [feathersjs/feathers#1819]
I know this is only for bug & feature request. But i tried to find solution for this & was unable to find any example at all

Documentation provides only example of single sort like `/messages?$limit=10&$sort[createdAt]=-1`

I want to do sorting by multiple fields.

How can i do that?

**Comment by daffl** [comment]
You use it like any other query string:

```
/messages?$limit=10&$sort[createdAt]=-1&sort[otherField]=1
```

For more complex sorting mechanisms you will have to fall back to the database you are using though.
