### ISSUE TITLE
Security Issue of JWT stored in LocalStorage

### ISSUE THREAD

**Issue by codyng** [feathersjs/feathers#1820]
Hi there,

For security reason, will the JWT stored in the LocalStorage get encrypted?
The JWT now is in very plain and can be used for the authenticated users to query API calls manually they themselves.

Also, is it possible to integrate with redux-persist and redux-persist-transform-encrypt?

Thanks!!!!!

**Comment by daffl** [comment]
That's possible with any other mechanism as well. An attacker can only get access if they can inject code onto your page in which case they will be able to make authenticated requests with anything else (sessions etc.) as well.

See the [FAQ on JWT](https://docs.feathersjs.com/help/faq.html#why-are-you-using-jwt-for-sessions) for more information and the [Awesome FeathersJS](https://github.com/feathersjs/awesome-feathersjs) repository as a resource for plugins.
