### ISSUE TITLE
Different typing definition for @feathersjs/client and @feathersjs/authentication-client

### ISSUE THREAD

**Issue by bwgjoseph** [feathersjs/feathers#1821]
### Steps to reproduce

Configure auth in `client` using this configuration.

```js
import io from 'socket.io-client';
import feathers from '@feathersjs/client';

const socket = io(serverUrl);
const app = feathers<ServiceTypes>();

app.configure(feathers.socketio(socket));
app.configure(
  feathers.authentication({
    storage: window.localStorage,
  }),
);
```

This is using `feathers.authentication` to configure, hence, you will lose the typing.

![image](https://user-images.githubusercontent.com/37484538/75052053-f0214400-5509-11ea-95fb-9af3f1e6bdc4.png)

However, if you install `@feathersjs/authentication-client` even without using it, you will get such error but you will be able to get the type.

![image](https://user-images.githubusercontent.com/37484538/75052195-28288700-550a-11ea-83d1-1da122e32ada.png)

I guess this is because, in `@feathersjs/authentication-client`, this is being declared as such...

```js
declare module '@feathersjs/feathers' {
    interface Application<ServiceTypes = {}> {
        io?: any;
        rest?: any;
        primus?: any;
        authentication: AuthenticationClient;
        authenticate: AuthenticationClient['authenticate'];
        reAuthenticate: AuthenticationClient['reAuthenticate'];
        logout: AuthenticationClient['logout'];
    }
}
```

whereas, in `@featherjs/client`, it being declared as ...

```js
interface FeathersClient extends Feathers {
    authentication: FeathersAuthenticationClient;
    errors: FeathersErrors;
    primus: FeathersPrimusClient;
    rest: FeathersRestClient;
    socketio: FeathersSocketIOClient;
}
```

Why the difference both declaration? There is no `authenticate` and so on in `@featherjs/client`.
Or rather both are mismatch, even the name.

Using `feathersjs 4.5.1`, `typescript 3.7.5`.

You can use do this though, for now.

```js
import auth from '@feathersjs/authentication-client';

const app = feathers<ServiceTypes>();

app.configure(feathers.socketio(socket));
app.configure(auth());
```

**Comment by daffl** [comment]
The `@featherjsjs/client` currently does not automatically install the dependencies that have the typings. You need to

```
npm install @feathersjs/feathers @feathersjs/authentication-client @feathersjs/errors @feathersjs/primus-client @feathersjs/rest-client @feathersjs/socketio-client --save-dev
```

To get them which should also fix that issue.
