### ISSUE TITLE
[Question] Authenticating services when running tasks/jobs

### ISSUE THREAD

**Issue by jchamb** [feathersjs/feathers#1822]
I wasn't able to find any specific examples or best practices, so I'm curious what is the preferred way to authenticate when running services inside of tasks or jobs? I know I can force an authentication using the authentication service or creating a random token to pass with params, it just feels a bit weird to do that for a "non" user scenario so curious how others approach this.

Here's an over simplified hypothetical:

App bootstrap sets up a pub/sub pull listener to ingest event data from [X Service]
The subscription function needs to do a couple different service operations and all services check  for JWT auth.

```
import pubsub from './pubsub';

... app boostrapping ...

app.configure(pubsub);
```

```
module.exports = function (app) {
    
   ... connect to pubsub service ...

     someTopic.subscribe(event => {
          app.service('user').get(event.data.assignee); // has JWT auth check defined in hooks
         
          ... other service calls ...
        
         event.ack();
     });
}
```

Thanks for the suggestions and recommendations

**Comment by J3m5** [comment]
Why would you want to authenticate for a task that is running in the same process as the feathersjs server?
To me, this isn't necessary, the authentication is only necessary if the services are called externally.

**Comment by jchamb** [comment]
It's not that I really want to... I just don't see any automated ignores with the authentication hooks if the context provider is not external. [authenticate hook](https://github.com/feathersjs/feathers/blob/master/packages/authentication/src/hooks/authenticate.ts)
I was asking because I couldn't find any good documentation or issues around best practice. looking at the hook source it looks like you can either:

1. use the service and authenticate manually
2. wrap the authenticate hook with an Iff check using hooks-common: `iff(isProvider('external'), authenticate('jwt'))`
3. Force authenticated = true when doing the call.

I'm actually doing the third at the moment, it just feels hacking. So i'm curious how others are handling it as a best practice, since the authentication docs have very little information of how it hooks works when doing service calls from other services or server side tasks.

**Comment by daffl** [comment]
There is no need to run the hook conditionally. As mentioned in the list in the [authenticate hook API docs](https://docs.feathersjs.com/api/authentication/hook.html#authenticate-options), if the call is internal (`params.provider` is not set), the `authenticate` hook will not run and allow the call.

**Comment by jchamb** [comment]
@daffl  I swear I looked every where for that, not sure how I missed it. Thanks.
