### ISSUE TITLE
how to use forgotten password of  feathers-authentication-management

### ISSUE THREAD

**Issue by abdolrhman** [feathersjs/feathers#1827]
so I am using "feathers-authentication-management"
yet I have no idea how to implement the services it provides,
- I mean where are the routes? 
- how to use or register a functionality ex: forget the password,

all I want is a rest API for frontend, to forget the password,
also, I am not using feather-client for front-end, I want gust rest,

Thank you ^^

**Comment by abdolrhman** [comment]
how Allow user to reset password if not yet verified ?
i tried, 
```
app.configure(authentication)
  .configure(authManagement({
    isVerified: false
  }));
```
didnt work

**Comment by daffl** [comment]
Since this is not an official Feathers module, you are more likely to get and answer by [reopening this question in the feathers-authentication-mangement repository](https://github.com/feathers-plus/feathers-authentication-management/issues/new).

**Comment by abdolrhman** [comment]
@daffl sorry mate, thank you ^^
