### ISSUE TITLE
NotAuthenticated thrown when it shouldn't have

### ISSUE THREAD

**Issue by xtrial** [feathersjs/feathers#1828]
### Steps to reproduce

- generate server with feathers cli
- create hook that will immediately throw error (ie. throw BadRequest)
- put it after authenticate('jwt') in users > before hook
- create hook that will log error.message
- trigger the hook

### Expected behavior
BadRequest thrown.

### Actual behavior
NotAuthenticated thrown

### System configuration

**Feathers CLI**

**Comment by daffl** [comment]
Hooks run in the order they are registered. If you put it after `authenticate('jwt')` the `authenticate` hook will run first and throw the `NotAuthenticated` if there is no authenticated user. If you put it before `authenticate('jwt')` you will get the `BadRequest`. Also note that `all` hooks will [run _before_ all method specific hooks](https://docs.feathersjs.com/api/hooks.html#registering-hooks).

**Comment by xtrial** [comment]
@daffl thanks for the reply.

i manage to solve this by adding provider check in my hook. i didn't know that the hook chain in users service is this sensitive.
