### ISSUE TITLE
socketIO auto-auth in conflict with feathers.authenticate

### ISSUE THREAD

**Issue by SharpBCD** [feathersjs/feathers#1831]
### Situation 1: - login screen
- feathers configured with socketIO - will try to connect and authenticate when started but I rather use the the `feathers.authenticate ({...})` function. Otherwise, the `feathers.authentication.authenticated` will be always `false`
- Solved by configuring feathers and allowing an anonymous connection, only to be ignored on server + calling `authenticate` when required.

### Situation 2: refresh in normal pages
- the token is saved in cookie and the socketIO init will trigger the authentication automatically but I need to get the user and also test if it was successful. I can do this with  `feathers.authentication` functions.
- if I call `feathers.authenticate ({...})` I will double the login. 

### Possible solution
Add possibility to cancel auto-connect from socketIO. Could that work? To start the connection after authentication is successful?

**Comment by daffl** [comment]
I have a feeling there is something odd with your setup. The authentication client will not try to authenticate until you call `app.authenticate` or `app.reAuthenticate`. Once authenticated it will also try to authenticate again whenever the connection drops but that basically just calls `app.reAuthenticate()`.

You should not check `feathers.authentication.authenticated` but instead wait for `app.get('authentication')` as [documented in the client API](https://docs.feathersjs.com/api/authentication/client.html#app-get-authentication).

**Comment by SharpBCD** [comment]
It sure is. :-(
I posted my setup [here](https://github.com/feathersjs/feathers/issues/1830). What am I doing wrong?

**Comment by daffl** [comment]
The code snippets you provided are unfortunately not enough. We'd need a full minimal repository to reproduce the problem.

**Comment by SharpBCD** [comment]
more details were provided in  #1894 
looks like the problem was something else.
