### ISSUE TITLE
socket-IO control who get the notification

### ISSUE THREAD

**Issue by abdolrhman** [feathersjs/feathers#1835]
- So i am trying to make when user create a post, all his followers get notified, 
i am not sure how to do this,
i know that there is a channel layer build in feather but am not sure how to use it

Thank you

**Comment by KidkArolis** [comment]
Check out the channels docs: https://docs.feathersjs.com/api/channels.html#example

In your specific case, create a per user channel, similar to this:

```js
module.exports = function(app) {
  app.on('login', (authResult, { connection }) => {
    if(connection) {
      const user = connection.user;
      
      // add this user to their own private channel
      app.channel(`users/${user.id}`).join(connection);
    }
  });
};
```

And then in your service, configure the publisher:

```js
// this will add a publisher that will be used to figure out which channels
// to send the events to, see: https://docs.feathersjs.com/api/channels.html#app-publish-event-fn
app.service('posts').publish((data, context) => {
  // an after create hook in posts service should fetch the follower list
  // for this post and set it on context.params, so we can use it here
  const followers = context.params.followers

  // create a list of channels that the data should be sent to
  const channels = []
  for (const follower of followers) {
    channels.push(app.channel(`users/${follower.id}`))
  }
  return channels
});
```

Make sure to thoroughly read the docs on this as there are other things you can do, like filtering the data before it gets sent, etc.

**Comment by abdolrhman** [comment]
@KidkArolis thanks buddy appreciated
I will try to implement it, I am trying to wrap my head around this, but I have some difficulties,

thanks again :))
