### ISSUE TITLE
New Version of the Site

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers#184]
We're still not really showcasing the power of feathers all that well and the docs are super confusing! We also have some pretty awesome new stuff coming in this release that will push us passed others. So we should have a site that showcases:

- [x] That we are front end agnostic (with links to guides for implementing the front end clients)
- [x] We are completely isomorphic
- [x] That we are database agnostic and support more databases than any other real time framework. (links to all the ORMs/DBs)
- [x] How we are different from others. I like how [Otto](https://ottoproject.io/intro/vs/index.html) has theirs laid out and how they try to be impartial:
    - Sails
    - Meteor
    - Express + Socket.io
    - Hapi
    - Firebase
    - Strapi
- [x] That you can easily start with micro-services rather than having to start monolithic and break it up later.
- [x] Getting up and running quickly (using the generator)
- [x] Walks you through a comprehensive single app example as part of the docs
     - with authentication
     - with authorization
     - REST + sockets
- [x] Slightly more advanced: takes you through the same app as a series of micro services

**Comment by ekryski** [comment]
@daffl had some thoughts in the Slack room around value props. Going to put them here:

# Feathers is...
​
## Modern but solid
​
Built with and for modern JavaScript, Feathers is a tiny fully compatible wrapper over
Express and Socket.io, both of which have been used in production by thousands of companies.
​
## Service-oriented
​
Services are CRUD objects that can be used just like an Express middleware and automatically
provide events and other functionality added by the many Feathers plugins.
​
## RESTful and real-time
​
## Pluggable
​
Just a tiny service library at its core, Feathers can be turned into a full real-time application framework.
​
## Database-friendly
​
MongoDB? MySQL? PostgreSQL? Feathers has adapters for most popular NodeJS ORMs giving you their built-in validation and access to many databases. Not seeing your? Just wrap it with your own service.
​
## Framework-friendly
​
feathers-client has everything you need to get your JavaScript framework of choice connected
to Feathers. Our Android and iOS clients let you build real-time mobile applications.
​
## Scalable
​
Start as many servers as needed while still keeping everything synchronized. Combine service calls to minimize requests or transparently move high-load services onto their own machine.
​
## A microservice gateway
​
Let your Microservices focus on doing one thing well and Feathers handle the rest. It can act as a gateway for user authentication, permissions and even making your existing REST APIs real-time.

**Comment by daffl** [comment]
I started work on the new documentation layout in the https://github.com/feathersjs/feathers/tree/gh-pages-2.0 branch. The outline currently looks like this:

<img width="969" alt="screen shot 2016-01-09 at 12 10 44 pm" src="https://cloud.githubusercontent.com/assets/338316/12218109/4bb2c4de-b6ca-11e5-8e2d-0f8717f1184a.png">

**Comment by ekryski** [comment]
:+1: looking good!

**Comment by kamakazikamikaze** [comment]
Any chance you can provide an offline/downloadable version of the documentation?

**Comment by ekryski** [comment]
@kamakazikamikaze I don't see why not. Once we get the docs for 2.0 wrapped up. Lots of changes that we need to document first.

I've created a separate issue to track this: https://github.com/feathersjs/feathers/issues/194. If you feel like issuing a PR or elaborating on what format you'd like to see feel free! :smile:

**Comment by ekryski** [comment]
New website is nearly complete. Work is being done on https://github.com/feathersjs/feathers/tree/new-site.
