### ISSUE TITLE
app.hook called twice when using @feathersjs/authentication

### ISSUE THREAD

**Issue by elixiao** [feathersjs/feathers#1840]
### Steps to reproduce

app.hooks.js

```js
export default {
  before: {
    all: [()=>console.log('app.hook', +new Date())],
    find: [],
  }
}
```

user.hook.js

```js
import * as feathersAuthentication from '@feathersjs/authentication'
const { authenticate } = feathersAuthentication.hooks

export default {
  before: {
    all: [],
    find: [authenticate('jwt')] // <--- problem occurs from this line 
  }
}
```

### Expected behavior

```
app.hook 1583047147581
```

### Actual behavior

```
app.hook 1583047147581
app.hook 1583047147587
```

Why app.hook was called twice after adding `authenticate('jwt')` in user.hook.js?

**Comment by J3m5** [comment]
The authenticate hook call the user hook.
So your log hook is triggered on the authentication service and the users service.

**Comment by elixiao** [comment]
@J3m5 I don't think it's the problem of users service. Add another books service lead to the same result.

**Comment by J3m5** [comment]
To be sure, replace your hook with another one that logs the path.
Like this:
```js
all: [ ({path}) => console.log('app.hook', path, +new Date()) ],
```

**Comment by elixiao** [comment]
@J3m5 You're right. The console now giving the following output:

```sh
app.hook books 1583155423326
app.hook users 1583155423328
```

The authenticate hook call the user hooks which include app hooks, right? Is there any way to avoid calling  app hook twice when using `authenticate('jwt')`? Maybe custom jwt authentication?

**Comment by J3m5** [comment]
You can make your hook conditional in a way that it's called only for external call if that is your goal.
You should look at the [provider](https://docs.feathersjs.com/api/services.html#params) property on the [context](https://docs.feathersjs.com/api/hooks.html#hook-context) object.

[You might be interested by this hook too.](https://hooks-common.feathersjs.com/hooks.html#isprovider)

**Comment by elixiao** [comment]
@J3m5 isProvider works great! Thank you for taking the trouble to help me. I do appreciate it.
