### ISSUE TITLE
The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'

### ISSUE THREAD

**Issue by farhad-arjmand** [feathersjs/feathers#1842]
`Access to XMLHttpRequest at 'http://localhost:3030/upload-B2B' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.`

Feathers js app.js:

```
// Load app configuration
app.configure(configuration());
// Enable security, CORS, compression, favicon and body parsing
app.use(helmet());
app.use(cors());
app.use(compress());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(favicon(path.join(app.get('public'), 'favicon.ico')));
```

my service: 

```

// Initializes the `uploads` service on path `/uploads`
const { Uploads } = require('./uploads.class');
const createModel = require('../../models/uploads.model');
var crypto = require('crypto');
const mime = require('mime');
const hooks = require('./uploads.hooks');
var multer = require('multer')
var storage = multer.diskStorage({
  destination: function (req, file, cb) {
    cb(null, './public/uploads/B2B/')
  },
  filename: function (req, file, cb) {
    crypto.pseudoRandomBytes(16, function (err, raw) {
      cb(null, raw.toString('hex') + Date.now() + '.' + mime.getExtension(file.mimetype));
    });
  }
});
var upload = multer({ storage: storage });

var fs = require('fs');

module.exports = function (app) {
  const options = {
    Model: createModel(app),
    paginate: app.get('paginate')
  };

  // Initialize our service with any options it requires
  app.use('/uploads', new Uploads(options, app));


  app.post('/upload-B2B', upload.single('file'), (req, res) => {
    var img = fs.readFileSync(req.file.path);
    var encode_image = img.toString('base64');
    // Define a JSONobject for the image attributes for saving to database

    var finalImg = {
      contentType: req.file.mimetype,
      image: encode_image,
      filename: req.file.filename
    };
    res.send(finalImg)
  })
  // Get our initialized service so that we can register hooks
  const service = app.service('uploads');

  service.hooks(hooks);
};

```

**Comment by farhad-arjmand** [comment]
with postman is OK , but with vuejs app it dosnt work

**Comment by daffl** [comment]
You can configure the [cors package](https://github.com/expressjs/cors) (used in `app.use(cors());`) with the options that your application needs (specifically the [`origin` option](https://github.com/expressjs/cors#configuration-options)).

**Comment by farhad-arjmand** [comment]
i used this app.use(cors()); in app.js
please see app.js code

**Comment by farhad-arjmand** [comment]
other routes work but his route have error

**Comment by daffl** [comment]
See [this Stackoverflow answer](https://stackoverflow.com/questions/44145619/nodejs-express-cors-issue-with-access-control-allow-origin/44146038#44146038) on how configure the `cors` module when you get that error message.

**Comment by milon27** [comment]
I am facing the same problem. any solution? You sent Today at 5:13 PM
Cors origin error occurs.

While uploading a photo using multer in the express post request.

Any solution? 
All other post requests are working fine, I am using
___________
app.use(cors());
___________

**Comment by FURQAN2050** [comment]
is there any update till now?

**Comment by bujji1** [comment]
This worked for me  `app.use(cors({ origin: true, credentials: true }));`
