### ISSUE TITLE
Crash on @feathersjs/socketio-client import with NativeScript

### ISSUE THREAD

**Issue by soullivaneuh** [feathersjs/feathers#1843]
### Steps to reproduce

Checkout this demo PR: https://github.com/soullivaneuh/svelte-native-test/pull/2

- [ ] Run `npm install`
- [ ] Run `tns run android`

### Expected behavior
Working compilation and app push.

### Actual behavior

```
ERROR in ../node_modules/debug/src/node.js
Module not found: Error: Can't resolve 'net' in '/home/sullivan/p/github.com/soullivaneuh/svelte-native-test/node_modules/debug/src'
 @ ../node_modules/debug/src/node.js 193:16-30
 @ ../node_modules/debug/src/index.js
 @ ../node_modules/@feathersjs/transport-commons/lib/client.js
 @ ../node_modules/@feathersjs/transport-commons/client.js
 @ ../node_modules/@feathersjs/socketio-client/lib/index.js
 @ ./App.svelte
 @ ./app.ts
Executing webpack failed with exit code 2.
```

If you install the `net` package (which I'm not sure I have to do that, like for #456) and run the command again, you will have:

```
System.err: TypeError: Cannot read property 'env' of undefined
System.err:     at com.tns.Runtime.runModule(Native Method)
System.err:     at com.tns.Runtime.runModule(Runtime.java:674)
System.err:     at com.tns.Runtime.run(Runtime.java:666)
System.err:     at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
System.err:     ... 8 more
```

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** See PR.

**NodeJS version**: v12.1.1

**Operating System**: Linux

**Browser Version**: Not relevant.

**React Native Version**: Not relevant.

**NativeScript Version**: 6.4.1

**Module Loader**: Webpack

**Comment by daffl** [comment]
Use [@feathersjs/client](https://docs.feathersjs.com/api/client.html#feathersjs-client) instead.
