### ISSUE TITLE
LDAP Authed users are logged out on refresh

### ISSUE THREAD

**Issue by engineertdog** [feathersjs/feathers#1846]
### Steps to reproduce
[Minimal repo here with code](https://gitlab.com/engineertdog/feathers-ldap)

I took the existing Feathers Chat + React and attempted to convert `local` auth to `ldap`. You'll notice in `feathers-chat/src/authentication` that the LDAP strategy is a little different than https://github.com/feathersjs-ecosystem/feathers-authentication-ldap/issues/42. That's because the code provided in that issue would fail on `reject` and not work properly. The code I have is what I needed to get it to work. Otherwise, the actual log in / creation of users based on an LDAP profile works flawlessly.

Once a user gets logged in and has a Feathers account created based on their LDAP user, they're able to view the chat in the React app. On first log in, the user is able to post messages without issue. However, if the user refreshes the page and attempts to submit a message, they'll get an error and nothing will happen. This is because in `feathers-chat/src/services/messages/messages.class`, the `params.user` becomes null / undefined after the page is refreshed (whereas before the refresh, it works). 

The user's JWT is still valid and can be seen in local storage. In a more advanced app where authentication checking is performed, the user is physically logged out of the application, unlike in this demo (on refresh, although the user cannot interact with the chat view, they can still see the chat instead of being redirected to the login view).

### Expected behavior
Users should not be logged out when they have a valid JWT.

### Actual behavior
Users are logged out with a valid JWT.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working): Unsure of the actual culprit
**NodeJS version**: 12
**Operating System**: Windows
**Browser Version**: Latest Chrome
**React Native Version**: N/A
**Module Loader**:

**Comment by brentgroves** [comment]
Thank you for posting this issue.

**Comment by brentgroves** [comment]
Is this issue resolved in ldapauth-fork@5.0.0-rc.5?
see https://github.com/vesse/passport-ldapauth/issues/88

**Comment by engineertdog** [comment]
I’m not quite sure what the real issue was, but I was able to get it working after testing multiple different setups from scratch (via CLI) and from the official chat repos. It was a bit finicky between SQL Server and AD.
