### ISSUE TITLE
Service call ignores "context.dispatch"

### ISSUE THREAD

**Issue by kFp2oito3jt** [feathersjs/feathers#1848]
### Issue

Internal _find_ service call returns context.result instead of context.dispatch. When called externally, everything works as expected. 

### Steps to reproduce

Call "find" users method internally. In my case the returned value is taken from the context.result instead of context.dispatch (even though dispatch is defined).

### Expected behavior
"find" **internal** call supposed to return context.dispatch when both result and dispatch are defined

### Actual behavior
"find" call returns context.result

### System configuration

Node 13.8.0
@feathersjs/feathers@3.3.1
Mac OS X
NPM

**Comment by daffl** [comment]
`context.dispatch` (if set) is only used by the transports (REST, websockets) calling the service. If you want to remove values for everybody, you can modify `context.result` in a hook.

**Comment by kFp2oito3jt** [comment]
> `context.dispatch` (if set) is only used by the transports (REST, websockets) calling the service. If you want to remove values for everybody, you can modify `context.result` in a hook.

May I ask how to achieve my desired result?

I just made my custom local auth strategy and I'm returning authenticated user document when login is successful. I need to have password field after I called "find" however I need to hide it after password is compared and I'm returning a user doc with access token.

How can I run these "protect" hooks after I'm done verifying password in my local strategy?

**Comment by daffl** [comment]
The normal `local` strategy makes two requests

- [one for finding _without_ the provider set](https://github.com/feathersjs/feathers/blob/2b258fda885172c1e523b5232941bff0457cb6e0/packages/authentication-local/src/strategy.ts#L123) (which will return the password to compare)
- another one [for returning the user with the original parameters](https://github.com/feathersjs/feathers/blob/2b258fda885172c1e523b5232941bff0457cb6e0/packages/authentication-local/src/strategy.ts#L129) (which will omit all protected fields)

**Comment by kFp2oito3jt** [comment]
> The normal `local` strategy makes two requests
> 
> * [one for finding _without_ the provider set](https://github.com/feathersjs/feathers/blob/2b258fda885172c1e523b5232941bff0457cb6e0/packages/authentication-local/src/strategy.ts#L123) (which will return the password to compare)
> * another one [for returning the user with the original parameters](https://github.com/feathersjs/feathers/blob/2b258fda885172c1e523b5232941bff0457cb6e0/packages/authentication-local/src/strategy.ts#L129) (which will omit all protected fields)

Thank you daffl, I will not forget the help you are providing 👍
