### ISSUE TITLE
authenticate() no longer working if a time-out error occured

### ISSUE THREAD

**Issue by SharpBCD** [feathersjs/feathers#1850]
In exception cases (returning from hibernate and the token is expired) I got error while trying to reconnect.
The logic I implemented refresh the token and retry to connect. However, after the last update (not sure which) it is no longer working. After the first failed, the `authenticate()` function no longer send to the back-end the request and I just get more: 'vue.esm.js?a026:628 [Vue warn]: Error in v-on handler (Promise/async): "Timeout: Timeout of 2000ms exceeded calling create on authentication"'
As I said, on back-end I do not receive a request.

A hard refresh is required to make it work again. Is there a `reset` method?

**Comment by daffl** [comment]
The [reset method is documented here](https://docs.feathersjs.com/api/authentication/client.html#reset).
