### ISSUE TITLE
Cannot enter FeatherJs app using IP

### ISSUE THREAD

**Issue by eldano1995** [feathersjs/feathers#1851]
I managed to solve the problem, but It took me a long time, so I want to share the answer to avoid others the same inconvinience.

The thing was the when I runned the server (**npm start** or **node lib/**), I could access the server by the browser only when using localhost:PORT, and not using my IP (192.168.X.X:PORT). PORT is by default 3030. This behavios was dued to this code, in the index.js file, in the src folder:

```
import logger from './logger';
import app from './app';

const hostname = app.get('host');
const port = app.get('port');
const server = app.listen(port, hostname);

process.on('unhandledRejection', (reason, p) =>
  logger.error('Unhandled Rejection at: Promise ', p, reason)
);

server.on('listening', () =>
  logger.info('Feathers application started on http://%s:%d', hostname, port)
);
```

The important line is this one:
`const server = app.listen(port, hostname);`

It is telling to the server that only respond to requests that comes from hostname. You fix the problem by simply doing:
`const server = app.listen(port);`

That easy it is ...

The reason it took me a long time to solved this issue was because my co-workers didn't have the same problem, and we all use the feathers-cli to create the app. For some reason, in version 4.2.3 of FeathersJs (the one I had), the listen function received a hostname, but in older versions and the current one (4.3.0, the one my co-workers had) it didn't.

So now you know: upgrade your Feathers-cli version to the latest, and check that in src/index.js, the server.listen function is being called as here:
`const server = app.listen(port);`
And not as here:
const hostname = app.get('host');
const port = app.get('port');
const server = app.listen(port, hostname);

**Comment by daffl** [comment]
Thanks for sharing. The recommended solution is definitely to always make sure you are using the latest version of the CLI. Closing.
