### ISSUE TITLE
use lodash modularized builds to reduce code size

### ISSUE THREAD

**Issue by xixilive** [feathersjs/feathers#1852]
because `@feathersjs` provides several client/browser packages, and so code size is a important concern, It is NOT necessary import the whole of `lodash` modules. 

for examples:

- `@feathersjs/authentication`, which uses `omit` and `merge` actually, but requires full-build.
- `@feathersjs/transport-commons`, which use `noop`, `flattenDeep`, `compact` and `isEqual`, but requires full-build.

**Comment by daffl** [comment]
Those are all server side modules. None of the client side modules use Lodash. Either way, a pull request to change to individual imports would be accepted.
