### ISSUE TITLE
PM2- Authentication configuration is not loading correctly

### ISSUE THREAD

**Issue by yohane55** [feathersjs/feathers#1856]
My configuration is not loaded correctly with pm2, specifically encountered a problem with authentication configuration. It works fine if I run it with `npm start`, `npm run dev`,` node /path/to/index.js` and also `systemd`.

my actual configuration
---------------------------
...
`"authentication": {
    "entity": "users",
    "service": "users",
    "secret": "GzxGEeaY9QIe1MMp7Y8YDexmjkEQo=T^%87ahs46agsh82ajhs36DJAgfdf",
    "authStrategies": [
      "jwt",
      "local"
    ],
    "jwtOptions": {
      "header": {
        "typ": "access"
      },
      "audience": "https://domain.com",
      "issuer": "http://domain.com",
      "algorithm": "HS256",
      "expiresIn": "1d"
    },
    "local": {
      "usernameField": "username",
      "passwordField": "password"
    }
  },`
...

What actually loaded
-----------------------

`2020-03-10T17:26:43.984Z @feathersjs/configuration Setting authentication configuration value to {
npm run dev-0  |   entity: 'users',
npm run dev-0  |   service: 'users',
npm run dev-0  |   secret: 'GzxGEeaY9QIe1MMp7Y8YDexmjkEQo=T^%87ahs46agsh82ajhs36DJAgfdf',
npm run dev-0  |   authStrategies: [ 'jwt', 'local' ],
npm run dev-0  |   jwtOptions: {
npm run dev-0  |     header: { typ: 'access' },
npm run dev-0  |     audience: 'https://domain.com',
npm run dev-0  |     issuer: 'http://domain.com',
npm run dev-0  |     algorithm: 'HS256',
npm run dev-0  |     expiresIn: '20d'
npm run dev-0  |   },
npm run dev-0  |   local: { usernameField: 'user', passwordField: 'password' },
npm run dev-0  | }`

**THE Problem** is that `usernameField` is not the same as the original configuration. It should have been `username` but the loaded one is `user`. and so the user can never login.

**Comment by daffl** [comment]
Please see the __Important__ note at https://docs.feathersjs.com/api/authentication/local.html#configuration

**Comment by yohane55** [comment]
thank you so much  @daffl ! I escaped as per documentation and it is now working. Thank you for creating feathersjs!
