### ISSUE TITLE
Unable to use the service within the service

### ISSUE THREAD

**Issue by jericho2018** [feathersjs/feathers#1857]
It is not possible to invoke other services within a service method, and there are too few examples of official documentation to explain how to use it.

code ----------------
const { Service } = require('feathers-mongoose');

exports.Notice = class notice extends Service {  
  setup(app) {
    this.app = app;
  }

  async get(name, params) {
    const messages = this.app.service('messages');
    const message = await messages.get(1, params);
        return { name, message };
  }
};

Error ---------------------

"name": "GeneralError",
    "message": "Cannot read property 'get' of undefined",
    "code": 500,
    "className": "general-error",
    "data": {},
    "errors": {}

**Comment by daffl** [comment]
This will only work after `app.setup` or `app.listen` has been called. The better way is to set the app in the constructor:

```js
const { Service } = require('feathers-mongoose');

exports.Notice = class notice extends Service {
  constructor(options, app) {
    this.app = app;
  }

  async get(name, params) {
    const messages = this.app.service('messages');
    const message = await messages.get(1, params);
    return { name, message };
  }
};
```

Assuming that `notice.service.js` calls `new Notice(options, app)`.

**Comment by jericho2018** [comment]
ReferenceError: Must call super constructor in derived class before accessing 'this' or returning from derived constructor

The purpose I want to achieve is: in one service, how to invoke another service? Just like I can call any other service in hook.

I used to write all the functional code in hook, but in the new version, there is an extra class.js, under each service, which means it is officially recommended to write code directly under the service, and hook only does general functions？？？

But in the official document, there is not a complete example of how to write a service, which is really very confusing, and the official sample code-feathers-chat, basically does not have a complete functional code and has no learning value.

**Comment by daffl** [comment]
I updated the example but this isn't anything Feathers specific, it's [basic JavaScript class inheritance](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes) and it is also part of the Feathers chat and documentation, speficially in the ["customizing a service" guide chapter](https://docs.feathersjs.com/guides/basics/services.html#customizing-a-service) with another section going into more details [when to use hooks vs extending a service](https://docs.feathersjs.com/guides/basics/hooks.html#hooks-vs-extending-services).

**Comment by jericho2018** [comment]
OK, THANKS A LOT!

by the way,Do you have WeChat or other app ? I can communicate with you , and I can pay for it.

**Comment by chrisbag** [comment]
> This will only work after `app.setup` or `app.listen` has been called. The better way is to set the app in the constructor:
> 
> ```js
> const { Service } = require('feathers-mongoose');
> 
> exports.Notice = class notice extends Service {
>   constructor(options, app) {
>     super(options);
>     this.app = app;
>   }
> 
>   async get(name, params) {
>     const messages = this.app.service('messages');
>     const message = await messages.get(1, params);
>     return { name, message };
>   }
> };
> ```
> 
> Assuming that `notice.service.js` calls `new Notice(options, app)`.

Hey Thanks, works like a charm but throws a Typescript error (service created with feathers-sequelize db adapter)
Any solution to make it work while keeping typings ?

Thanks a lots :)
