### ISSUE TITLE
Feature Request: [authentication-client] event on auth failure

### ISSUE THREAD

**Issue by KrishnaPG** [feathersjs/feathers#1858]
In the authentication-client, when auth attempt is made, `login` and `authenticated` events are generated for the `auth success` case:

https://github.com/feathersjs/feathers/blob/9fe55b32ff252817b9031345c24365e2b42130d2/packages/authentication-client/src/core.ts#L165-L167

However, there is no event for `auth failure` case. Only the promise is rejected.

This feature-request is: please raise an event (something like `authFailure` event) in the failure case, in the catch handler shown below:
https://github.com/feathersjs/feathers/blob/9fe55b32ff252817b9031345c24365e2b42130d2/packages/authentication-client/src/core.ts#L170-L172

Such event makes it possible to watch for the `login` and `authFailure` events from anywhere in the app across different services and enable/disable certain functionality. Currently, we are handling success in the event, and failure in the `catch` handler, not so elegant.
````
fClient.on('login', authResult => Store.setUser(authResult));
fClient.on('logout', () => Store.clearUser());
fClient.on('authFailure', () => Store.clearUser()); //<-- this is not available currently
````

**Comment by daffl** [comment]
This is already possible with a short client side [error hook](https://docs.feathersjs.com/api/hooks.html#context-error):

```
fClient.service('authentication').hooks({
  error (context) {
    fClient.emit('authFailure', context.error);
  }
});
```

**Comment by KrishnaPG** [comment]
Thank you @daffl 

When using `.authenticate()` the hook seems to be getting invoked fine. But when doing `.reAuthenticate(true)` the hook is not getting invoked for some reason.

For example,
````
    fClient.reAuthenticate(true).catch(ex => {
      console.log("caught exception: ", ex);
    });

fClient.service('authentication').hooks({
	error(context) {
		console.log("auth error ", context.error);
	}
});
````
the catch exception handlers gets invoked, but not the hook for reAuth failure when validating an already stored JWT.

That is the main scenario I am trying to handle.

When socket **reconnections** happen the `login` event is generated for successful reAuth (see below `handleSocket ` code). But when the stored JWT is failed to **reAuth** on reconnect, we would not know

https://github.com/feathersjs/feathers/blob/9fe55b32ff252817b9031345c24365e2b42130d2/packages/authentication-client/src/core.ts#L70-L74

**Comment by daffl** [comment]
Ah, indeed, the correct code is

```js
client.hooks({
  error (context) {
    const { error } = context;

    if (error.code === 401) {
      client.emit('authFailure', context.error);
    }

    return context;
  }
});
```

This should emit the event on any authentication failure.
