### ISSUE TITLE
Need to use ArrayFilters with Mongoose (MongoDB)

### ISSUE THREAD

**Issue by kFp2oito3jt** [feathersjs/feathers#1859]
Does FeathersJS support the following option? https://docs.mongodb.com/manual/release-notes/3.6/#arrayfilters.

We are supposed to be able to use ArrayFilters with following code:
`
db.Applicant.updateMany({},
  { $set: { 'comments.$[element].author': 'Baz' } },
  { arrayFilters: [{ 'element.author': 'Bar' }] });`

where arrayFilters is part of the "options" argument for the database query.
How to pass that option with classic "patch" call of the FeathersJS service?

Would it be possible with the following call in Feathers? 
`await app.service('applicants').patch(null, body, { query, arrayFilters: [{ 'element.author': 'Bar' }]  })`

**Comment by daffl** [comment]
There is a discussion in https://github.com/feathersjs-ecosystem/feathers-mongoose/issues/373
