### ISSUE TITLE
Add nsp support to all packages & plugins.

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers#187]
I think it's a good idea to add this into the build/publishing process so we get alerts of vulnerabilities that pop up.  What do you guys think? @feathersjs/core-team
https://nodesecurity.io/tools

We need to do [this](https://github.com/feathersjs/feathers/pull/205/files) to each of these:
- [x] feathers
- [x] feathers-commons https://github.com/feathersjs/feathers-commons/pull/16
- [x] feathers-rest https://github.com/feathersjs/feathers-rest/pull/8
- [x] feathers-socketio https://github.com/feathersjs/feathers-socketio/pull/6
- [x] feathers-primus https://github.com/feathersjs/feathers-primus/pull/4
- [x] feathers-socket-commons https://github.com/feathersjs/feathers-socket-commons/pull/1
- [x] feathers-mongodb https://github.com/feathersjs/feathers-mongodb/pull/19
- [x] feathers-mongoose Accidentally committed directly.  Wrong key command. 🙃 
- [x] feathers-authentication https://github.com/feathersjs/feathers-authentication/pull/26
- [x] feathers-client https://github.com/feathersjs/feathers-client/pull/24
- [ ] feathers-nedb https://github.com/feathersjs/feathers-nedb/pull/10 (error)
- [x] feathers-memory https://github.com/feathersjs/feathers-memory/pull/12
- [x] feathers-sequelize https://github.com/feathersjs/feathers-sequelize/pull/10
- [x] feathers-knex https://github.com/feathersjs/feathers-knex/pull/27
- [x] feathers-waterline https://github.com/feathersjs/feathers-waterline/pull/3
- [x] feathers-query-filters https://github.com/feathersjs/feathers-query-filters/pull/7
- [x] feathers-configuration https://github.com/feathersjs/feathers-configuration/pull/1

**Comment by ekryski** [comment]
:+1: I haven't use nsp before but sounds like a good idea to me.

**Comment by daffl** [comment]
That sounds good. Can you run nsp against this repo and show how it looks?

**Comment by daffl** [comment]
Did you get a chance to test it out? I would figure that all we need to do is add it as an NPM script.

**Comment by marshallswain** [comment]
Nope.  I didn't try it out, yet.  I'll try it now.

**Comment by marshallswain** [comment]
![screen shot 2016-01-05 at 8 53 19 am](https://cloud.githubusercontent.com/assets/128857/12119588/cd4a9880-b389-11e5-84ce-c6b75bbae695.jpg)

**Comment by marshallswain** [comment]
It looks like they currently only use a command line utility, but the gulp-nsp project shows how we could create an npm script to run the nsp package: https://github.com/nodesecurity/gulp-nsp/blob/master/index.js

**Comment by daffl** [comment]
Why couldn't you just install the command line as a devDependency and run it from an NPM script?

**Comment by marshallswain** [comment]
Oh yeah.  Yep it works: `./node_modules/.bin/nsp check`

**Comment by daffl** [comment]
As an npm script you probably won't even have to add `node_modules` anymore.

**Comment by marshallswain** [comment]
You're right.  Where's the best place to integrate it?  At the end of `test`?

**Comment by marshallswain** [comment]
`"test": "npm run compile && npm run jshint && npm run mocha && npm run nap",`

**Comment by marshallswain** [comment]
Actually, running it directly works "test": "npm run compile && npm run jshint && npm run mocha && nsp check",

**Comment by ekryski** [comment]
Here's a list of all the plugins. Can you guys start checking off the ones that are done with this?

- [ ] feathers
- [ ] feathers-commons
- [ ] feathers-rest
- [ ] feathers-socketio
- [ ] feathers-primus
- [ ] feathers-socket-commons
- [ ] feathers-mongodb
- [ ] feathers-mongoose
- [ ] feathers-authentication
- [ ] feathers-client
- [ ] feathers-nedb
- [ ] feathers-memory
- [ ] feathers-sequelize
- [ ] feathers-knex
- [ ] feathers-waterline
- [ ] feathers-query-filters
- [ ] feathers-configuration

**Comment by marshallswain** [comment]
I copied the list to the first comment.  We've only updated feathers core, so far.

**Comment by marshallswain** [comment]
All plugins have a PR.

**Comment by ekryski** [comment]
@marshallswain what's the issue with nedb? Would be nice to close this issue out.

**Comment by marshallswain** [comment]
Looks like @daffl fixed it.

**Comment by ekryski** [comment]
:+1:
