### ISSUE TITLE
How to response to client directly and do not execute following hooks

### ISSUE THREAD

**Issue by elixiao** [feathersjs/feathers#1878]
I have 10 before hooks.  How to response to client in the second hook? Here is my code:

```js
function a(hook){ 
    // ...
}
function b(hook){
    hook.result = {ok:1} // do not work
    hook.dispatch = {ok:1} // do not work neither
}
function c(hook){ 
    // ...
}
function d(hook){ 
    // ...
}
function e(hook){ 
    // ...
}
...
export default {
  before: {
    all: [], 
    find: [a,b,c,d,e,....],
  }
}
```

I just want  to STOP in the second hook and response to client directly and ignore all following before hooks, service methods, after hooks, etc.

**Comment by J3m5** [comment]
Based on the doc [here](https://docs.feathersjs.com/api/hooks.html#setting-context-result) you can set the context.result value **but you need to return the context object to make it effective**.
This will skip all the other before hooks and the method call, but not the after hooks.

For skipping the after hooks call, according to [the migrating docs](https://docs.feathersjs.com/guides/migrating.html#deprecated-context-next-and-skip-functionality) you can [make the hooks run conditionally through a flag](https://hooks-common.feathersjs.com/hooks.html#iff).

**Comment by bertho-zero** [comment]
@J3m5 It's false, The doc says:
> When context.result is set in a before hook, the original service method call will be skipped. All other hooks will still execute in their normal order.

That skip only original service method call.

**Comment by J3m5** [comment]
Woops, right...

**Comment by elixiao** [comment]
@J3m5 @bertho-zero Thanks for the quick reply. Is there any other solution except running hook conditionally using iff? I don't want to add iff to all the following before and after hooks behind the second hook. Isn't it straightforward to handle special case in the second hook?

**Comment by daffl** [comment]
It is not. Run them conditionally and it is clear what is happening and should look something like this:

```js
function a(hook){ 
    // ...
}
function b(hook){
    hook.result = {ok:1} // do not work
    hook.dispatch = {ok:1} // do not work neither
}
function c(hook){ 
    // ...
}
function d(hook){ 
    // ...
}
function e(hook){ 
    // ...
}
...
export default {
  before: {
    all: [], 
    find: [
      a,
      iff(context => !context.result, b,c,d,e)
    ],
  }
}
```

There were good reasons that the SKIP functionality got removed.

**Comment by elixiao** [comment]
@daffl OK. I write a wrapper function to apply iff to every hook and now it works.

```js
function hookWrapper(obj) {
  return Object.keys(obj).reduce((ret, type) => {
    const map = obj[type], kv = (ret[type] = {})
    Object.keys(map).forEach(k => kv[k] = map[k].map(f => iff(ctx => !ctx.dispatch, f)))
    return ret
  }, {})
}

function a(hook){ 
    // ...
}
function b(hook){
    hook.dispatch = {ok:1}
}
function c(hook){ 
    // ...
}
function d(hook){ 
    // ...
}
function e(hook){ 
    // ...
}

module.exports = hookWrapper({
  before: {
    all: [], 
    find: [a, b, c, d, e],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  },
  after: {
    all: [],
    find: [x, y, z],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  }
})
```

**Comment by lijoantony** [comment]
https://feathers-plus.github.io/v1/feathers-hooks-common/#skipremaininghooks
