### ISSUE TITLE
Making remove/patch/update call safe for large collections?

### ISSUE THREAD

**Issue by kFp2oito3jt** [feathersjs/feathers#1879]
I recently did an experiment and figured out that Feathers does return *all* documents deleted by remove service call at once (there is no pagination for remove() call).

Is there any easy & safe way to execute removals and return the deleted documents for collections with millions of documents?

**Comment by daffl** [comment]
This depends on the adapter you are using. `feathers-sequelize` [supports a `$returning` option](https://github.com/feathersjs-ecosystem/feathers-sequelize/#querying) to skip returning the values. For others you may have to [extend the adapter](https://docs.feathersjs.com/api/databases/common.html#extending-adapters) and implement that functionality yourself.

**Comment by kFp2oito3jt** [comment]
> This depends on the adapter you are using. `feathers-sequelize` [supports a `$returning` option](https://github.com/feathersjs-ecosystem/feathers-sequelize/#querying) to skip returning the values. For others you may have to [extend the adapter](https://docs.feathersjs.com/api/databases/common.html#extending-adapters) and implement that functionality yourself.

Is it possible for feathers library to abstract away this part of logic and automatically split one service call into multiple calls with certain stride value? Basically this way Feathers could support it out of the box.

**Comment by daffl** [comment]
Probably not because the most performant bulk update mechanism depends on the database itself and also what kind of operation you are performing. Feathers never tries to hide the underlying database you are using so you can always still access and use it directly.
