### ISSUE TITLE
how to change error messages from english to other language

### ISSUE THREAD

**Issue by wwbluechip** [feathersjs/feathers#1880]
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc. This makes it much easier for us to debug and issues that have a reproducable example will get higher priority.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by daffl** [comment]
This can all be done via [Feathers hooks](https://docs.feathersjs.com/api/hooks.html), specifically by modifying [context.error](https://docs.feathersjs.com/api/hooks.html#context-error) and by [customizing the Feathers errors you throw yourself](https://docs.feathersjs.com/api/errors.html#custom-errors).
