### ISSUE TITLE
Thoughts on cleaning up the .use syntax.

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers#189]
I'm not sure if that's the proper title, but here are the goals behind what I'm trying to say:
 - Standardize the service configuration and hooks into a single file or single point of entry.  (I think this will make it easier to create a drag-and-drop Feathers server builder UI in the future.)
 - Keep the index.js / server.js free of db connection logic , if so desired.  This makes sense to me since the services are the ones using it.
 - Keep the service path in the same file with the server setup (`.use('path/to/service, serviceSetup)`), but everything else to do with a service goes into the service's own file or file/folder structure.

Basically, it would be nice to be able to do something like the following pseudo example.

```js
// index.js
import todoService from 'services/todos';
import feathers from 'feathers';
let app = feathers();
app.use('todos', todoService);
```

```js
// services/todos.js
export default function(app){
  /* * * Do any connection stuff here, if needed * * */

  /* * * DB Adapter Type * * */
  this.adapter = mongooseService({Model: MongooseModel});

  /* * * Before hooks * * */
  this.before({
    all:   [hooks.requireAuthForPrivate()],
    before: [hooks.setUserID()]
  });

  /* * * After hooks * * */
  this.after({
    all: [hooks.removeSomeField()]
  });

  /* * * Set up event filters * * */
  this.created = this.updated = this.patched = this.removed = events.requireAuthForPrivate;

  return this;
}
```

I thought at first that we could simply modify `.use()` to work similar to how `.configure()` works with passing in the `app` as the context, but this doesn't address how we would keep `.use('path/to/service', serviceSetup)` in with the main server config.

I make the distinction of having a single point of entry because in order to create a future GUI tool, we could give each service its own folder with the following files:

**todos-service.js (index.js)** could contain the connection configuration.
**model.js** - like for feathers-mongoose
**hooks.js**
**events.js**

What are your thoughts on making this possible?

**Comment by marshallswain** [comment]
I don't think that this is really an important issue for a microservice architecture, but it is for a multi-service app architecture.

**Comment by ahdinosaur** [comment]
> Standardize the service configuration and hooks into a single file or single point of entry.

:+1:

i was wondering what's the cleanest way to integrate my [`feathers-tcomb`](https://github.com/ahdinosaur/feathers-tcomb) hooks within a service definition. then all the ES6 changes lead me to thinking about feathers services as [composable stamps](https://github.com/stampit-org/stampit), which would be exciting.

**Comment by daffl** [comment]
@ahdinosaur This looks great! If you want we can add it to the documentation. I only skimmed over the stamps but isn't this very similar to what we are doing with ES6 classes and Uberproto/Feathers mixins at the moment?

@marshallswain I think there is a good point there but couldn't most of this be handled either through extension (hooks will use `before` and `after` properties) or via `.configure` like this:

```js
// index.js
import todoService from 'services/todos';
import feathers from 'feathers';

let app = feathers();
app.configure(todoService);
```

```js
// services/todos.js
export default function(){
  /* * * Do any connection stuff here, if needed * * */

  /* * * Service Type * * */
  this.use('/todos', mongooseService({Model: MongooseModel}));
  
  const service = this.service('todos');

  /* * * Before hooks * * */
  service.before({
    all:   [hooks.requireAuthForPrivate()],
    before: [hooks.setUserID()]
  });

  /* * * After hooks * * */
  service.after({
    all: [hooks.removeSomeField()]
  });

  /* * * Set up event filters * * */
  service.created = service.updated = service.patched = service.removed = events.requireAuthForPrivate;
}
```

**Comment by marshallswain** [comment]
@daffl Doh! I didn't even think of simply using configure for the service.  This is a Kodak, face palm moment.  The question is, do we want to utilize `.configure()`  to register services for the generated app?  @ekryski

**Comment by ahdinosaur** [comment]
> I only skimmed over the stamps but isn't this very similar to what we are doing with ES6 classes and Uberproto/Feathers mixins at the moment?

yep yep, but to be honest i think `stampit` does composable OOP better than anything else i've seen (including ES6 classes and Uberproto/Feathers mixins), it's surprisingly simple and powerful.

here's some dream code:

```js
// index.js
import feathers from 'feathers'
import todoService from './todos/service'

let app = feathers()
app.use(todoService)
```

```js
// todos/service
import memory from 'feathers-memory'
import tcomb from 'feathers-tcomb'
import stampit from 'stampit'
import todo from './model'

export default stampit.compose(
  memory(),
  tcomb(todo)
)
```

```js
// feathers-tcomb.js
import hooks from 'feathers-hooks'

export default function (model) {
  ...
  // `hooks` should be a stamp that adds before / after hooks to methods
  // `hooks.before` / `hooks.after` should be a static method like https://github.com/stampit-org/stampit/blob/master/docs/advanced_examples.md#validate-before-a-function-call
  //   that composes the hooks onto a new stamp
  return hooks.before({
    ...
    // a hook may need to access the service within a method, so should be available as `this`.
  })
}
```

but i'm going on a tangent away from @marshallswain's original post, i'm just gonna let the back brain simmer on it for a bit, so feel free to ignore my ramblings. :cat:

**Comment by ekryski** [comment]
@marshallswain @daffl ya I think that is good. It will keep things pretty clean. The only thing I see people maybe being confused of is the magical context of `this` in configure.

That being said didn't we also have `setup()` for services? I personally prefer this method so I think we should ship it for feathers-generator but just sayin'...

@ahdinosaur that is pretty fucking clean (even without knowing anything about how stampit works). Let's definitely keep it on the docket for a 3.0. I'm hesitant to add anything else to our 2.0 milestone as the release date has already been extended a few times and we have some pretty massive changes that need to go out.

So along that vein there are 2 things that I think we should be very cognoscente of:

1) We get this 2.0 release out without getting too distracted or introducing too many breaking changes

2) I think we can humbly say that we are all pretty good JS devs. Therefore, we understand a lot more than someone who is fairly new to Node, JS or development in general. I want to empower both new people but also allow advanced developers to be able to customize Feathers to their specific needs or preferences. So with this being said we need to be careful how much cognitive load we throw on someone before they are able to get up and running.

@ahdinosaur All your ideas really have been awesome! So keep them coming. We'll just need to make sure that they fit, and when they fit in. We only have so much bandwidth as a team. Of course, if you want to help out with some of the current more boring stuff feel free to check out  https://github.com/feathersjs/feathers/milestones/2.0.0.

**Comment by ekryski** [comment]
Apologies, it was late last night and my comment did not convey what I was getting at. @marshallswain I think we should do what you suggested in the generator. Maybe then we should drop the setup method?

**Comment by marshallswain** [comment]
Ok.  I'll work on getting the generator set up starting with feathers-mongoose.

**Comment by marshallswain** [comment]
I think the current setup using .configure works great.  I'm going to go ahead and close this.
