### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by elaijuh** [feathersjs/feathers#1891]
```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 65 connection listeners added to [Namespace]. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:281:17)
    at Namespace.addListener (events.js:297:10)
    at Server.<computed> [as on] (/Users/hjl/code/mobile/monetizer-web/be/node_modules/socket.io/lib/index.js:505:29)
    at /Users/hjl/code/mobile/monetizer-web/be/node_modules/@feathersjs/transport-commons/lib/socket/index.js:55:16
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

I see this nodejs warning after adding an amount of services.

node version: 12.14.1
feathers version: 4.5.2

**Comment by daffl** [comment]
See [this FAQ](https://crow.docs.feathersjs.com/help/faq.html#possible-eventemitter-memory-leak-detected-warning).

**Comment by Caribosaurus** [comment]
@daffl I love those kinds of answers. Go elsewhere and two years later that elsewhere doesn't exist...

**Comment by daffl** [comment]
The elsewhere can still be found at the documentation for the version you are using (e.g. https://crow.docs.feathersjs.com/help/faq.html#possible-eventemitter-memory-leak-detected-warning). However, for the version the documentation is now covering this error will no longer occur at all. I updated the link accordingly.
