### ISSUE TITLE
how to add custom response header in app after hook

### ISSUE THREAD

**Issue by elixiao** [feathersjs/feathers#1892]
I want to add a custom header `server-time` in every response to tell the client what time server is. Is app after hook the best place to add it? How to do that?

**Comment by daffl** [comment]
Per service this can be done with a [custom service middleware](https://docs.feathersjs.com/api/express.html#custom-service-middleware). For all services you can just register a [normal Express middleware](https://expressjs.com/en/guide/using-middleware.html) like `app.use((req, res, next) => { /* set headers here */ next(); })` before the [notFound middleware](https://github.com/feathersjs/feathers-chat/blob/master/src/app.js#L46).

**Comment by elixiao** [comment]
@daffl I put the middleware after `app.hooks(appHooks)` just before `app.use(express.notFound())` but could not get `Server-Time` header in response. Put it before `app.configure(services)` could. Here is my code.

```js
app.configure(express.rest())
app.configure(authentication)
app.configure(mixins)
app.configure(services)
app.hooks(appHooks)
app.use((req, res, next) => {
  res.setHeader('Server-Time', +new Date())
  next()
})
app.use(express.notFound())
```
