### ISSUE TITLE
Custom service without any of standard methods throws error on startup

### ISSUE THREAD

**Issue by 1valdis** [feathersjs/feathers#1893]
### Steps to reproduce

1. Create a custom service without any of the standard methods (setup, create, update, ...). It may contain any custom methods also.
```javascript
module.exports.TestService = class TestService {
  constructor(options) {
    this.options = options || {};
  }
  testMethod() {}
};
```
2. Attach the service to the app.
### Expected behavior
The app starts without any errors and I'm able to get my service and call my custom methods.

### Actual behavior
When trying to run the app, the following error occurs:
```
TypeError: Router.use() requires a middleware function but got a Object
    at Function.use (<app directory>/node_modules/express/lib/router/index.js:458:13)
    at Function.<anonymous> (<app directory>/node_modules/express/lib/application.js:220:21)
   ...
```
The app does not start.

### System configuration

**Module versions**: `@feathersjs/feathers@4.5.2`, `@feathersjs/express@4.5.2`

**NodeJS version**: `12.6.1`

**Operating System**: `macOS 10.14.6`

The documentation says:
> ProTip: Methods are optional, and if a method is not implemented Feathers will automatically emit a NotImplemented error.

It doesn't say that at least one method must be implemented.

I believe this is related to #285.
I also think there are two ways of resolving this:
1. Explicitly say in the documentation that at least one standard method must be implemented. Also create a check which will throw less cryptic and hard to debug error. (It took me once somewhere near an hour to find out why my custom service crashes my app as soon as I attach it.)
2. Allow attaching services without any of the standard methods.

**Comment by daffl** [comment]
A service needs to implement at least one of the [official service methods](https://docs.feathersjs.com/api/services.html#service-methods). When nothing else is needed usually implementing `setup` (even if it is empty) is enough.

**Comment by 1valdis** [comment]
@daffl Yeah that's what I found out after spending my time trying to find out where the error comes from.
I believe this
>A service needs to implement at least one of the official service methods.

Should be put in documentation. Currenrly it only says that methods are optional, which may lead to false conclusion that you may specify none of them at all.

**Comment by daffl** [comment]
Fixed via https://github.com/feathersjs/docs/commit/4725568cf5fb985c735c76197f131ad10d1f113c

**Comment by thomasarbona** [comment]
`"@feathersjs/feathers": "^5.0.24"`

`setup` and `teardown` function doesn't work, it throw the `TypeError: Router.use() requires a middleware function but got a Object`. Works ok with `get`.
