### ISSUE TITLE
logout does not... logout user. Authenticate with another token is failing as the connection stores the old token

### ISSUE THREAD

**Issue by SharpBCD** [feathersjs/feathers#1894]
### Steps to reproduce
Continuing the idea from #1883 :
- logging in user with fresh token (I use firebase generated tokens)
- on expire, I want to refresh the connection token - Issue: there is no method to do it, so I set a new token with `setAccessToken` and call 'reAuthenticate(true)'. 
- on server, in `authenticate` function, the new token is correct but the next call fails.
- after debugging I find out that the first token used on first authentication was used no matter what.
- I tried to logout the user but nothing was happening except to call the logout event.
- learning from #1883, with socket disconnect and open again, it works!

Indeed, disconnecting and reconnecting the socket is very messy, I'll use it as a fix until a better solution will be implemented.

### Expected behavior
1. logout should close the connection and no further access to be allowed. I understand that removing connection data the next calls will end up in error but imho this is not quite a logout. 
2. a method to allow the connection to update token? `setAccessToken` should work just fine!

### Actual behavior
connection is using the initial token with no way to replace it. `setAccessToken` will not replace it
'logout()' is not closing/reset the connection

### System configuration
server
"@feathersjs/authentication": "^4.5.1",
    "@feathersjs/authentication-local": "^4.5.1",
    "@feathersjs/authentication-oauth": "^4.5.1",
    "@feathersjs/cli": "^4.3.0",
    "@feathersjs/configuration": "^4.5.1",
    "@feathersjs/errors": "^4.5.1",
    "@feathersjs/express": "^4.5.1",
    "@feathersjs/feathers": "^4.5.1",
    "@feathersjs/socketio": "^4.5.1",
client:
    "@feathersjs/authentication-client": "^4.5.2",
    "@feathersjs/feathers": "^4.5.2",
    "@feathersjs/socketio-client": "^4.3.11",

I hope I was clear enough. Its 3 am here and I lost the whole day around this :-)

**Comment by SharpBCD** [comment]
More details:
- I have a custom authentication class, similar with JWT but on disconnect it does not delete the authentication information - this was throwing an error, now I know why.
- I console.log the token in `authenticate` and it is the new and correct one on `reAuthenticate` but every other call it's using the old token with no was to change it, at least none that I've found. Setting the token on client has no effect as `parsing` is attaching the info to the connection on the server and it is called only on login.

**Comment by daffl** [comment]
This has been fixed in [v4.5.3](https://github.com/feathersjs/feathers/blob/crow/changelog.md#453-2020-04-17).
