### ISSUE TITLE
Remove environment variable substitution in configuration

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers#1895]
An often recurring issue is changing the local authentication field to `username` in Windows systems in the configuration which needs to be escaped as per the [current conventions for @feathersjs/configuration](https://crow.docs.feathersjs.com/api/configuration.html#usage). This has also been causing difficult to debug problems with other environment variables.

I was briefly debating a different syntax to denote environment variables but after some more research, I am instead proposing a breaking change that removes this functionality and instead use the [environment variable functionality of node-config](https://github.com/lorenwest/node-config/wiki/Environment-Variables#custom-environment-variables).

**Comment by KidkArolis** [comment]
👍 I'm already using the node-config approach and it works great. Could probably create a migration script/command for this?

**Comment by daffl** [comment]
Possibly. Since we don't know the actual environment variables it'd probably mean copying `default.json` into `config/custom-environment-variables.json`. Maybe with the additional assumption that only `UPPERCASE` names are considered environment variables.

**Comment by mkovel** [comment]
@daffl  Hey, 
have you considered moving out from node-config and use another package for feathers-config functionality?
https://github.com/HenrikJoreteg/getconfig
https://github.com/tusharmath/node-config-ts
It looks like they have similar functionality, but lack some of the node-config limitations

Could you please share your thoughts on why splitting a single config file into two files and further supporting two config files (node-config approach) better / more convenient than using a single config file with special syntax for env vars?

**Comment by daffl** [comment]
I think node-config works quite well but as with anything in Feathers, `@feathersjs/configuration` is just a small plugin that you don't have to use if you don't want to and can easily replace with any of the alternatives (especially in the new version, `@featherjs/configuration` is basically 20 lines of code that call `app.set(name, value)` from whatever got loaded into `node-config`).

Personally I'm not a fan of environment variables anymore because you loose type information and they are difficult to validate and figure out what the application actually got passed. I moved all my apps to just pull in the environment specific JSON configuration as one single environment variable.

**Comment by mkovel** [comment]
But where and how you manage secrets? 
Do you store them in the environment-specific JSON configuration?

**Comment by daffl** [comment]
Yes. Editing a single JSON file that's safely stored somewhere has proven _much_ easier than trying to manage (and debug) a bunch of random environment variables (which isn't fun in pretty much any environment, especially Kubernetes and Helm charts). node-config already [supports that out of the box](https://github.com/lorenwest/node-config/wiki/Environment-Variables#custom-environment-variables).

Also closing this issue since this has been done in v5.0.0-pre.1 and is now in beta testing. Latest prereleases can be installed via `@feathersjs/<packagename>@pre`, updating the version numbers of all `@feathersjs` packages to `^5.0.0-pre.1` or by running

```
npx ncu -u --newest
```

Upgrade instructions are continuously updated and can be found in the [v5 migration guide](https://dove.docs.feathersjs.com/guides/migrating.html).
