### ISSUE TITLE
register middleware before notFound didn't work

### ISSUE THREAD

**Issue by elixiao** [feathersjs/feathers#1897]
I want to **add custom response header for ALL services(Not Per service) after(Not Before) service REST methods been called**. From #1892 I registered a express middleware before notFound. But the custom header didn't show up in response headers. Here is my app.js

```js
app.configure(express.rest());
app.configure(mongoose);
app.configure(middleware);
app.configure(authentication);
app.configure(services);
app.use((req, res, next) => {
  res.setHeader('Server-Time', +new Date())
  next()
});
app.use(express.notFound());
app.use(express.errorHandler({ logger }));
app.hooks(appHooks);
module.exports = app;
```

I think the app after hook is the right place to add the header because it's already after REST method been called and just before sending response to client. But I don't know how to add headers in hook. Could some one help me?

**Comment by daffl** [comment]
The service already sends the response so for anything that can be done _before_ the middleware can be registered before: 

```js
app.configure(express.rest());
app.configure(mongoose);
app.configure(middleware);
app.configure(authentication);
app.use((req, res, next) => {
  res.setHeader('Server-Time', +new Date())
  next()
});
app.configure(services);
app.use(express.notFound());
app.use(express.errorHandler({ logger }));
app.hooks(appHooks);
module.exports = app;
```

Anything after all services would be a [custom formatter](https://docs.feathersjs.com/api/express.html#app-configure-express-rest-formatter).

**Comment by elixiao** [comment]
OK, middlewares can only be registered before configure service. So there is no way to add response header for all service after REST methods been called right?

**Comment by elixiao** [comment]
Got it. The following code works. Thanks @daffl 

```
app.configure(express.rest(function(req, res, next) {
  res.setHeader('Server-Time', +new Date())
  res.json(res.data)
}));
```
