### ISSUE TITLE
Feathers 2 tagline

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers#190]
I'm wondering if version 2 is a good time to modify it into something a little bit more of the direction that Feathers is going.

## Current tagline is

> Build Better APIs, Faster Than Ever

## Prevoius taglines

- An ultra scalable, feather weight, data oriented framework
- Shared REST and real-time APIs with Express.

## My suggestions

- A microservice library/framework for modern APIs
- A microservice library/framework for real-time APIs
- A service-oriented library/framework for modern APIs
- A service-oriented library/framework for real-time APIs
- A minimalist, data-oriented library/framework for modern APIs

## Library vs framework

Feathers core really is a library, just like Express (which does call itself a framework though). Our generator will combine all the different plugins and best practises into a full fledged framework. Does anybody else think that the term framework can be too intimidating for people interested? Does it matter?

Feel free to share your thoughts. The tagline will often be the first thing anybody sees so I think it is worth putting some thought into it.

**Comment by loris** [comment]
My vote goes to `A service-oriented library for modern APIs`
- modern vs real-time: real-time looks too narrow to me and will make people think feathers is not a good choice if you’re not doing anything websocket related
- library vs framework: framework sounds bloated
- microservice vs service-oriented: personal choice :)

**Comment by marshallswain** [comment]
"microservices" seems like a good marketing word.
I prefer library over framework.

How about 

```
"A microservice-oriented library for modern APIs"
```  
That gets the buzzword in there, but the "-oriented" part indicates that it's flexible, imo.

**Comment by marshallswain** [comment]
I think that the word microservice really defines the direction we're headed, right?  The next generation of docs will probably include how to let services communicate between each other across servers.

**Comment by BigAB** [comment]
Meteor built it's fame and bazillion dollar investment because it was "real-time".

Seriously that was the big drawing point.

There is still a lack of realtime in a lot of API libraries (loopback, parse, etc...), so though I agree it makes it sound more limiting than feathers is, I think keeping real-time in the tagline will draw more people than it will lose.

$0.02

**Comment by marshallswain** [comment]
```
"A microservice-oriented library for modern, real-time APIs"
```

**Comment by ahdinosaur** [comment]
> never write another CRUD API

---

> real-time microservices for modern CRUD APIs

**Comment by ekryski** [comment]
I agree with @BigAB. I think we should be highlighting the real time component and steer away from the microservice buzzword as the tagline. Microservices will definitely be highlighted on the website as that is probably the major thing that (will) set us apart from everyone else. That being said people aren't going to be searching for "what's the best microservice framework". 'real time" is searched way more often.

![screen shot 2016-01-05 at 11 03 21 pm](https://cloud.githubusercontent.com/assets/599019/12136006/974f20e4-b400-11e5-9e32-112a23f18fe6.png)

In marketing you also want to introduce [**the value** you deliver](http://www.darkcoding.net/future-of-web-apps/kathy-sierra-give-your-users-super-powers/), not necessarily features. How about making a simple change:

> Build Better Real Time Apps, Faster Than Ever

The reason I'm thinking apps is that now with feathers-client we are actually becoming more full stack and it makes it really freaking simple to get going.

**Comment by daffl** [comment]
@ekryski If possible I'd prefer to avoid too marketing focussed words like "Amazing", "Faster" or "Ever" in order to be more descriptive and concise with what you actually get - which is why I brought this issue up. My impression was that Tweets around Feathers more often contained developer focussed terms (buzzwords) like "microservice", "REST", "API" and "real-time" than the complete current tagline.

In the [Diffusion of Innovations](https://en.wikipedia.org/wiki/Diffusion_of_innovations) curve we are definitely still in the innovators phase which means that you ideally want to focus on why and how it is different. 

![Diffusion of Innovations](https://upload.wikimedia.org/wikipedia/commons/1/11/Diffusion_of_ideas.svg)

That is a different value proposition than for other groups like the early adopters (which probably care about more specific features like real-time, multi-database etc.) or the early majority (which wants to know if it is well maintained, used a lot, has many learning resources) etc.

This is what Meteor got right with focussing on real-time back in 2012 but I'm not sure if this will be a good sole differentiator anymore. Claiming the full stack (every framework is for "building apps" now) is tricky, too because there is a difference between making it easier to connect your clients and providing the full solution that Meteor did.

Anyway, thanks everybody for the discussion! I'm not sure why but for some reason I feel this may be important because it will shape a lot of the direction and message and it would be great to have everybody on the same page.
I'll get back to getting stuff done now ;)

**Comment by wuyuanyi135** [comment]
I got to know this project when finding an alternative to Firebase. I need a real-time database service that can work in local network without internet. I think Feather does exactly what I want.

**Comment by ekryski** [comment]
So I've got a few more suggestions. Remember that the feathers logo will be above this.

```
Build real-time apps faster than ever.
Build real-time apps with ease.
Build real-time apps from the future.
A modern real-time framework for tomorrow's apps.
Powering the world's best real-time apps.
A minimalist framework for tomorrow's apps.
A minimalist real-time framework for tomorrow's web.
```

Personally I like

1. _"A minimalist real-time framework for tomorrow's web"_
2. _"Powering the world's best real-time apps."_ (which may be too boastful or untrue right now but "best" is highly subjective :wink:
3. _"Build real-time apps, faster than ever."_ (not very original but it's short, says what we do and how it is beneficial)

**Comment by daffl** [comment]
I like

```
A modern real-time framework for tomorrow's apps.
```

Also a with a slight modification your #1:

```
A minimalist real-time framework for tomorrow's apps
```

**Comment by ekryski** [comment]
Ya I like both of those. Maybe your number 2 even better.

**Comment by marshallswain** [comment]
I like this one:
> A minimalist real-time framework for tomorrow's apps

**Comment by ekryski** [comment]
@marshallswain @daffl I think that's our winner for now. :trophy: 

I already took the liberty and started adding it to the docs, the main repo and the old site. I think we can probably close this now then.
