### ISSUE TITLE
testing gap for database adapters?

### ISSUE THREAD

**Issue by lwhiteley** [feathersjs/feathers#1902]
### Steps to reproduce

adapter test cases do not cover the total count in cases where the data is filtered but data set is actually larger

I recently wrote an [adapter](https://github.com/lwhiteley/feathers-lowdb) and the pagination was returning the full count in the database even when filtered but all test cases passed anyway.

is this the expected behaviour or a test gap?

for eg.

Dataset:

```json
[
   {
      "type":"urgent",
      "message":"tester is testing"
   },
   {
      "type":"not-urgent",
      "message":"tester is testing"
   },
   {
      "type":"urgent",
      "message":"tester is testing"
   },
   {
      "type":"not-urgent",
      "message":"tester is testing"
   }
]
```

Query: `/messages?type=urgent`

What should be the expected result?

Result 1: Test passes  🆗 
```json
{
   "total": 4,
   "data":[
   {
      "type":"urgent",
      "message":"tester is testing"
   },
   {
      "type":"urgent",
      "message":"tester is testing"
   }
  ]
}
```

Result 2: Test passes 🆗 .. 
i believe this is the correct one but in reality the tests allow both
```json
{
   "total": 2,
   "data": [ 
   {
      "type":"urgent",
      "message":"tester is testing"
   },
   {
      "type":"urgent",
      "message":"tester is testing"
   } 
 ]
}
``

**Comment by daffl** [comment]
That's a good question. The idea was Result 2) and the test should definitely be updated accordingly.
