### ISSUE TITLE
Don't resend data on reconnect

### ISSUE THREAD

**Issue by ricardopolo** [feathersjs/feathers#1904]
### Steps to reproduce
There is a behavior in feathers client when every call to a service, while the client is offline is retry when the client is connected back to the server.

### Expected behavior
Is it possible to disable this feature?  Simple forget a call if it fails?

### Actual behavior
Currently an error emits and exception but it is retry silently later.

### System configuration

**NodeJS version**:
12

**Operating System**:
Mac OS Catalina

**Comment by daffl** [comment]
Duplicate of https://github.com/feathersjs/feathers/issues/1532 which has a code sample for addressing this issue.
