### ISSUE TITLE
tab and connection

### ISSUE THREAD

**Issue by codyng** [feathersjs/feathers#1906]
### Steps to reproduce

ENV: featherjs + socket

Using jwt and after login, it brings to the protected page.
The connection was added to "authenticated" channel coz I moved it from anonymous channel to there.

By opening another browser tabs, another connections (but with the same user ID) are added to the "authenticated" channel too....

Now it has over one connection (but with the same user ID) in the authenticated channel.

Is it the socket setting?? It's the shared websocket issue, or we can config something in feathers?

Thanks a lot.

**Comment by daffl** [comment]
The token is stored for the page in localStorage (or the storage you defined) so any page that has access to it will try to use it. If you use an incognito tab it will prompt you for the login again.
