### ISSUE TITLE
call super.patch in create function throw error "No record found for id" 

### ISSUE THREAD

**Issue by Chellhooo** [feathersjs/feathers#1911]
### Steps to reproduce

```js
async create(data, params){
    const obj = await super.create(
        {
          name: name,
          // ...
        },
        {},
    );
    const _id = obj._id;
    await super.find({query: {_id}}).then((res)=>{
      console.log(res);  // correct res
    });
    await super.patch(_id, obj).then((res)=>{
      console.log(res);
    });  // throw error "No record found for id" 
}
```

### Expected behavior
find and patch method both print res

### Actual behavior
find method print correct res
but patch method throw error "No record found for id xxx"

### System configuration

"feathers-mongoose": "^8.3.0",
"node": "12.14.0"

**Comment by Chellhooo** [comment]
I found the reason . I rewrote `this.options`  in  constructor.

 ```javascript
class test extends Service {
    constructor(options) {
        super(options);
        this.options = options || {};  //  it should be removed
  }
}
```

Sorry.  i will close the issue.

**Comment by hputzek** [comment]
> I found the reason . I rewrote `this.options` in constructor.

I had the same problem and searched for ~3 days until I this issue, so thank you  @Chellhooo

**Comment by Chellhooo** [comment]
@hputzek glad to know that~
