### ISSUE TITLE
Registering errorHandler still returns status code 500

### ISSUE THREAD

**Issue by Earthii** [feathersjs/feathers#1912]
### Steps to reproduce

I'm trying to [register the `express.errorHandler()`](https://docs.feathersjs.com/api/express.html#express-errorhandler) in my app.ts . I've registered it at the end of the file like so, but I can't seem to get it to work. I'm doing to since i was getting text errors, and 500 status code all the time. I saw the [FAQ](https://docs.feathersjs.com/help/faq.html#why-am-i-not-getting-json-errors) which is why I'm attempting this. But its still doesn't seem to have any effect. I added a hard coded throw new BadRequest (feathers Error) in a simple one liner get method in my service so that's my react app may hit this endpoint. The response however, is text result of BadRequest with a status code of 500 . I've also tried just `feathersApp.use(express.errorHandler())`;

```
feathersApp.use(
    express.errorHandler({
      // Log with Winston
      logger: logger as Logger,
      html: false,
    })
  );
```

### Expected behavior
I would expect to receive a status code 400 (bad request)

### Actual behavior
Received status code 500 with text error

### System configuration

**Module versions** (especially the part that's not working): 4.3.10

**NodeJS version**: v12.15.0

**Operating System**: Mac Catalina 10.15.3

**Browser Version**: Chrome Version 80.0.3987.163

**Comment by daffl** [comment]
This is usually a ordering issue (where in the file it is registered) but hard to tell without the entire code. You can use the [feathers-chat-ts app.ts](https://github.com/feathersjs/feathers-chat-ts/blob/master/src/app.ts) as a reference to where it should be though.

**Comment by Earthii** [comment]
Thanks for getting back to me on this. You're right, after some investigation, I found that the issue was caused by a `dynamic import` which is asynchronous. This leads to the errorHandler being registered before the dynamic services were registered
