### ISSUE TITLE
Read from a Room/Channel in a Socket.io client

### ISSUE THREAD

**Issue by MrFabio** [feathersjs/feathers#1921]
Hello everyone, I need your help.

I'm registering a user/client to 2 custom channels like so:
```
  app.on('connection', (connection: any) => {
    app.channel(`chat`).join(connection);
  });

  app.on('login', (authResult: any, { connection }: any) => {
    if(connection) {
      // Obtain the logged in user from the connection
      const user = connection.user;
      app.channel(`messages/${user.id}`).join(connection);
    }
  });
```

When a message is created I am publishing the events:
```
  app.service('messages').publish('created', (data) => {
    return [
      app.channel(`messages/${data.userId}`),
      app.channel(`chat`)
    ];
  });
```

On the client I am testing with this anonymous session: 
```
const socket = io('http://localhost:3030/');

socket.on('chat', function(message) {
  console.log('Got a Chat Message!', message);
});

socket.on('messages created', function(message) {
  console.log('Got a Message!', message);
});
```

I have another socket open and sending/creating messages. On this client I receive the messages that are created by the created event, but not the ones from the chat.
My goal was to receive messages targeted/filtered for that client and the Rooms/Channels feature looks like a possible solution for that. All the clients send messages to the same service but are sent/delivered to a target audience.
I tried to use custom events and I guess that it worked, I could filter the messages but It was not possible to have dynamic events (1 per user) that change in runtime and to secure the connection in way that only the User X could read the messages from that event and no other could join/read.
From the [tutorials](http://psitsmike.com/2011/10/node-js-and-socket-io-multiroom-chat-tutorial/) that I saw about this situation with socket.io only, it had something like this on the server : `io.sockets.in(socket.room).emit('updatechat', socket.username, data);` but on the [service.publish([event,] fn)](https://docs.feathersjs.com/api/channels.html#service-publish-event-fn) it doesn't do anything for that. In the Docs it explains the Channels really well but it doesn't have the client part, how to use it.

Thanks, I hope that I could explain myself.

**Client Socket.IO Version**:
v2.3.0
We need to support an Android App so we can't use the feathers client.

**Feathers version**
4.5.2
**NodeJS version**:
v12.16.1
**Operating System**:
Windows 10

**Comment by daffl** [comment]
What you are trying to do will only work if the client is authenticated (that's where the `login` event is coming from). This is shown [in the guide using the recommended way via Feathers on the client](https://docs.feathersjs.com/guides/basics/authentication.html#browser-authentication).

Direct Socket authentication is documented in the [Socket.io client docs](https://docs.feathersjs.com/api/client/socketio.html#authentication).

**Comment by MrFabio** [comment]
The `messages/id` part is what I'll want to use in the future, it was included in the sample. I added the `chat` event to test the rooms anonymously and that one is not working.

**Comment by daffl** [comment]
There is no `chat` event. The only event your clients need to care about is `messages created`. You do not need to do anything on the client other than authenticate (if necessary) and listen those service events.

With your setup from above any client will receive the `messages created` event since they are added to the `chat` channel when they connect.

**Comment by MrFabio** [comment]
Got it. Thank you!
