### ISSUE TITLE
redirect_url to Auth0 doesn't mention port if the application is running on HTTPS.

### ISSUE THREAD

**Issue by kashifnazar** [feathersjs/feathers#1924]
### Steps to reproduce
- Set `NODE_ENV` to production
- Setup OAuth with Auth0 using the [example](https://docs.feathersjs.com/cookbook/authentication/auth0.html)
- Setup HTTPS with using the [example](https://docs.feathersjs.com/api/express.html#https) but use a different port number such as 3043.
- Hit the URL, https://localhost:3043/oauth/auth0

### Expected behavior
The `redirect_uri` Feathers should pass to `auth0.com/authorize` should mention port 3043, like:
`redirect_uri=https://localhost/oauth/auth0/callback`

### Actual behavior
Feathers sends the redirect_uri as:
`https://localhost/oauth/auth0/callback`

In my case it is,
`https://<domain>.auth0.com/authorize?client_id=<client_id>&response_type=code&redirect_uri=https%3A%2F%2Flocalhost%2Foauth%2Fauth0%2Fcallback&scope=openid%20profile%20email`

I am very much sure that this issue happens with other OAuth providers as well.

**Comment by daffl** [comment]
You can customize the `host` accordingly (including the port) in your [oAuth configuration](https://docs.feathersjs.com/api/authentication/oauth.html#configuration). The default assumption for HTTPS is that it is running on the default port (because some oAuth providers do not allow to include a port when using HTTPS).

**Comment by kashifnazar** [comment]
> You can customize the `host` accordingly (including the port) in your [oAuth configuration](https://docs.feathersjs.com/api/authentication/oauth.html#configuration). The default assumption for HTTPS is that it is running on the default port (because some oAuth providers do not allow to include a port when using HTTPS).

It worked. Thanks so much.
