### ISSUE TITLE
Custom user model causes conflict on create

### ISSUE THREAD

**Issue by matthwfalk** [feathersjs/feathers#1925]
### Steps to reproduce

I have old Meteor user records that I want to integrate with Feathers. For this purpose I changed the user model like that to fit with the existing Meteor records:

```
const schema = new mongooseClient.Schema({
    _id: { type: String, unique: true, },
    services: {
      password: {
        bcrypt: { type: String }
      },
      resume: {
        loginTokens : { type: Array }
      }
    },
    email: {type: String},
    emails: [ 
      {
        address: { type: String, unique: true, lowercase: true },
        verified: { type: Boolean }
      }
    ],
    profile: {
      username: { type: String },
      mobile: { type: String },
      street: { type: String },
      streetnumber: { type: String }
    },
    roles: { type: Object },
    createdAt: { type: Date },
  }, {
    timestamps: true
  });
```

After that I changed how passwords are hashed in the authentication service. I also changed **entityUsernameField** and **entityPasswordField** to fit the model entity above. It all works fine!

But when I try to create a new user record I get the following message:

### Post call body:
```
{
    "email": "test5@test.de",
    "password": "12345678"
}
```

### Result:
```
{
    "name": "Conflict",
    "message": "email: null already exists.",
    "code": 409,
    "className": "conflict",
    "errors": {
        "email": null
    }
}
```

I expect, that there is a validation check after the new user record is passed from the custom create method and that check is not using **entityUsernameField** as defined in the defaults.json.

### Current Workaround

I added a field "email" into the model and fill it with "no email at all". Thats not nice and not really a good workaround but for the moment it works.

Hope I could help to improve Feathers :)

FeathersJS: 4.3.0
Node: 12.6.0

**Comment by daffl** [comment]
If you are getting the error already when creating the user, this probably has nothing to do with the authentication flow (yet). Fields not being set as expected often happens when no `Content-Type` has been set for the request.

**Comment by matthwfalk** [comment]
`Content-Type` is set and should work as expected. 

The error occurred, because I had to drop the users collection with old records before inserting new one with the new user model.

Thanks for your help @daffl

**Comment by daffl** [comment]
Ah, fair enough. As a side note, for a different model you can also [customize the local strategy](https://docs.feathersjs.com/api/authentication/local.html#customization) to create the query you need.
