### ISSUE TITLE
The /users route is called with a provider when calling the /authentication route

### ISSUE THREAD

**Issue by SeverinNovack** [feathersjs/feathers#1927]
### Steps to reproduce

Generate an app with (local) authentication and with users as the authentication entity.
Generate a before hook on the find and get method of the /users route and log the context to check if a provider is set in the params.

- I am building a FeathersJS app with authentication and authorization.
  I handle the authorization manually with before hooks on almost every route besides the 
  "/authentication" route because of course you want to leave this route unprotected so everyone is 
  able to authenticate/login.
  
### Expected behavior
When I call the /authentication route it also calls the /users route which is 
protected. Of course this is something which often occurs because this route is called by multiple 
other routes but I filter these calls in the authorization hook with the provider parameter which is 
not set if the call is internal. The call from /authentication to /users should be internal.

### Actual behavior
The context.params.provider parameter is set with "rest", thus I can't allow this call when filtering with the provider.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working): FeathersJS 4.3.0

**NodeJS version**: v12.13.1

**Operating System**: Windows 10

**Browser Version**: I am using Postman

**Module Loader**: npm 6.12.1

Is there a way to filter the /authentication route?

**Comment by daffl** [comment]
This is because the user data is actually being returned when authenticating (example in the authentication guide at https://docs.feathersjs.com/guides/basics/authentication.html#get-a-token). The external request will happen with the user information set. This means a `.service('users').get(user.id)` needs to be allowed for themselves (`context.params.user.id === context.id`).

**Comment by SeverinNovack** [comment]
That pretty much solved it, thank you very much
