### ISSUE TITLE
Handling server errors on any service, client side.

### ISSUE THREAD

**Issue by rybaczewa** [feathersjs/feathers#1933]
Is there a way to handle non 200 responses for every service of feathers-client (Rest / Socket.io)?

I want to run some code client-side, each time any of services responds with `NotAuthenticated` (without doing that each time I call service method). I can't find any listener in documentation that would allow me to do that. Any suggestions?

**Comment by daffl** [comment]
Remember that when using Feathers on the client you get the same functionality of the core application, including [application level hooks](https://docs.feathersjs.com/api/hooks.html#application-hooks). Any error can be handled with an application level error hook:

```js
client.hooks({
  error(context) {
    console.error(`Error in '${context.path}' service method '${context.method}'`, context.error.stack);
  }
});
```
