### ISSUE TITLE
$limit is ignored on patch method

### ISSUE THREAD

**Issue by akashbudhia** [feathersjs/feathers#1934]
Hi, $limit query on a patch request is not getting honoured(ends up patching all records ignoring the limit). The same query on find limits the results as expected.

- DB Adapter - Mongoose
- Feathers Version - 4.3.0

Is there a known reason why $limit doesn't apply on patch methods?

**Comment by asamolion** [comment]
Okay so there are 2 ways you can call the patch method:

1. with an `id`,
in which case it would patch only the document with the relevant `id`.

2. with `null`
in which case it would patch all the items which match the `query`

in either of these cases I'm not sure how `$limit` applies. If you are using method 2 and setting a `$limit` in the query, there is no way for feathers to decide which items to patch and which to leave based on the limit.

**Comment by asamolion** [comment]
@akashbudhia also documentation for multi patch here: https://github.com/feathersjs-ecosystem/feathers-mongoose

**Comment by akashbudhia** [comment]
It's case 2, multi patch with null id. There are other params passed with the $limit, other query params are honored, however $limit isn't.

**Comment by asamolion** [comment]
Yes that is correct. Let me clarify with an example.

Let's say you run have 3 items in 

```json
[
  {
    "id": 1,
    "name": "A",
    "salary": 5000,
    "type": "worker"
  },
  {
    "id": 2,
    "name": "B",
    "salary": 5000,
    "type": "worker"
  },
  {
    "id": 3,
    "name": "C",
    "salary": 10000,
    "type": "manager"
  }
]
```

And you run the following patch query
```javascript
app.service('employees').patch(null, { salary: 6000 }, {
  query: {
    type: "worker",
    $limit: 1
  }
})
```
Now, the patch query has to patch all entries with type "worker". There are 2 entries like this

But you also said to limit the patch to 1 i.e. patch only 1 worker.

How would Feathers decide whether to patch worker 1 or worker 2?

**Comment by J3m5** [comment]
The order could be based on the natural database order or with the $sort operator.

**Comment by akashbudhia** [comment]
I have worked around the use-case for now. However, see if there's any specific reason why this wouldn't be supported considering the native DB adapter supports this.

You may consider closing this/parking to backlog.

**Comment by asasvirtuais** [comment]
Same with feathers-nedb

**Comment by Psycholisk** [comment]
Any managed to solve this issue? 

I am trying to patch documents with params including `$sort` and `$skip` but it seems to be skipping them. There are of course a workaround for it but i wouldn't be as clean.
