### ISSUE TITLE
Remove timeout setting

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers#1937]
Currently the socket (but not Rest) clients support a timeout setting. This is frequently conflicting with the underlying transport reconnection and timeout mechanism and actually mainly a pre-v3 legacy leftover from the old socket message format (where there was no other way to tell if a method existed but to wait for a timeout). The timeout setting should be removed and handled by the underlying transport library or via hooks.

Related to

- #1532

**Comment by mhillerstrom** [comment]
Hi, I'm not sure whether this is directly connected...

I'm (quietly) working on implementing owndata/ownnet for the feathers-offline-realtime and found that it should be very similar to the existing optimistic-mutator with the exception that it does not presuppose connection to the server.

My findings are, that service calls from the client to the service on the server waits forever whereas on the server long running service calls are effectively shutdown (defaults to 5 sec). I would like the remote call on the client side to time-out too. That said, I implemented a wrapper for the service calls to the server that would do just that. But, my timer never triggers - it's as if the service call never relinquishes its grip on the execution thread...

Does my problem have any connection to this issue or should I look elsewhere?

The environment is like the standard for the feathers-offline-realtime i.e.
```json
  "dependencies": {
    "component-emitter": "1.2.1",
    "debug": "^2.6.8",
    "feathers-commons": "0.8.7",
    "feathers-errors": "2.8.1",
    "feathers-offline-snapshot": "^0.0.1",
    "feathers-query-filters": "2.1.2",
    "md5": "2.2.1",
    "shortid": "2.2.8",
    "uberproto": "1.2.0",
    "uuid": "3.1.0"
  },
  "devDependencies": {
    "babel-cli": "^6.24.1",
    "babel-core": "^6.24.1",
    "babel-plugin-add-module-exports": "^0.2.1",
    "babel-preset-env": "^1.7.0",
    "babel-preset-es2015": "^6.24.1",
    "chai": "^4.0.0",
    "feathers": "^2.1.3",
    "feathers-hooks": "^2.0.1",
    "feathers-memory": "^1.1.0",
    "istanbul": "^1.1.0-alpha.1",
    "mocha": "^3.4.2",
    "nyc": "^15.0.1",
    "semistandard": "^11.0.0",
    "shx": "^0.2.2"
  }
```

**Comment by daffl** [comment]
This issue is for Feathers v5. The Feathers versions you posted (v2) are almost three years behind, a lot has been improved since then. I recommend to upgrade first, it is likely it will solve your issue.

- The v2 to v3 migration guide can be found at https://buzzard.docs.feathersjs.com/migrating.html
- The v3 to v4 migration guide is at https://crow.docs.feathersjs.com/guides/migrating.html

**Comment by mhillerstrom** [comment]
Thank you for your input. Upgrading did not help. As it turned out it was all about the convoluted way many levels of async works. I've got a steady grip on it now and I'm proceeding with my take on feathers-offline-owndata.

**Comment by daffl** [comment]
This has been done in v5.0.0-pre.1 and is now in beta testing. Upgrade instructions are continuously updated and can be found in the [v5 migration guide](https://dove.docs.feathersjs.com/guides/migrating.html).
