### ISSUE TITLE
Provide offline documentation

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers#194]
Possibly for [Dash](https://kapeli.com/dash) or PDF or something?

**Comment by kamakazikamikaze** [comment]
I've never heard of Dash before but I'm assuming that trying to format the docs for it would probably allow a clean PDF export.

I'd recommend that the docs start with the API methods, services, and events. I would keep some of the examples separate (such as the functionality with Socket.IO), perhaps placing them in a second section. This would help reduce clutter and distractions when trying to understand Feathers itself. Combining examples specific to their package would also make it easier to understand how to effectively implement/inject Feathers with each.

For example:

* Section 1: Functions (remove REST, Socket.IO, etc. examples)
 * API
 * Services
 * Events
 
* Section 2: Examples (reiterate through functions)
 * Quick Start --> CRUD
 * REST
    * API
    * Services
    * Events
 * Socket.IO
    * API
    * Services
    * Events
 * Primus
   * . . .
* Section 3: Bits and pieces from Support --> FAQ
* Section 4: Learn

**Comment by marshallswain** [comment]
How about this: https://www.gitbook.com/

**Comment by marshallswain** [comment]
It gives you ePub PDFs and mobi formats in addition to an utmost version.  Here is an example: https://www.gitbook.com/book/frontendmasters/front-end-handbook/details

**Comment by marshallswain** [comment]
It looks like the online docs even have Medium-style highlighting and commenting: http://www.frontendhandbook.com/practice/types-of-front-end-dev.html

**Comment by ekryski** [comment]
Ooooh @marshallswain good call on that! That might be perfect, since our docs are already written in markdown anyway.

**Comment by marshallswain** [comment]
@ekryski Do you want to start a gitbook?  I'd like to start contributing to getting the docs going.

**Comment by daffl** [comment]
@marshallswain I'd like to see how it looks and how it would fit into our gh-pages publishing workflow. The new docs structure is currently at https://github.com/feathersjs/feathers/tree/gh-pages-2.0/docs.

**Comment by marshallswain** [comment]
It was actually really easy to throw a repo together: https://github.com/marshallswain/feathers-docs

All I had to do was take the template header off the top of each file, create a SUMMARY.md, a README.md and add a cover.jpg.  

The SUMMARY.md is simply a list of markdown links that becomes the table of contents / site navigation.

The README.md is the text you see at the bottom when you go to the git book page for the project: https://www.gitbook.com/book/marshallswain/feathers-docs/details.  You can also download the PDF, ePub, and Mobi files on that page.

They have their own CI that watches that repo and automatically updates the book as the files are updated.

**Comment by marshallswain** [comment]
It must automatically pull the author name from the github organization, because I can't find a way to change that.

**Comment by marshallswain** [comment]
It's pretty cool.  After you comment on a paragraph you can still add/edit paragraphs and it keeps the comments in the right place.  https://marshallswain.gitbooks.io/feathers-docs/content/02_rest.html

**Comment by marshallswain** [comment]
Here's a screenshot of their editor.  When you edit files, it creates git commits in the repo.

![screen shot 2016-01-16 at 1 39 55 pm](https://cloud.githubusercontent.com/assets/128857/12374366/bbe94a48-bc56-11e5-8bad-59897d1ef130.jpg)

**Comment by daffl** [comment]
Ooh... that looks great. I assume we can keep the Jekyll metadata and just make it a sub-repository of gh-pages so that we can still generate the website from it? Or is there a way to customize the online reader? @marshallswain I just made you an owner. Can you create a new repo and get everything set up (probably copy/move it from your repository)?

**Comment by marshallswain** [comment]
Done.  I've moved it over into feathersjs/feathers-docs.  There is quite a bit of customization available, just short of full access to the web template.

* Customization Docs: https://help.gitbook.com
* Plugins: https://plugins.gitbook.com
* Developer Documentation: https://www.gitbook.com/book/gitbookio/api-guide/details

**Comment by marshallswain** [comment]
I don't see a way to keep the Jekyll metadata.  They do support custom css and custom domains.  What do you think about just using Gitbook for the docs?  If their website ever goes down, we still have the Github repo as a secondary source.  We could set it up at docs.feathersjs.com.  Here are the [docs for DNS setup](https://help.gitbook.com/platform/domains.html).  Then we could keep the website focused on other stuff like demos and plugin discovery.  

Also, Gitbook has a decent metrics page.  Having one official source of docs would make it more useful.

**Comment by daffl** [comment]
Just skimmed over the docs and I think you're right, that's the way to go. It looks like you have a lot of styling options and if we can set a custom header for the web version we're golden. This is great!
Now we just need to start writing some more docs :smile:

**Comment by daffl** [comment]
Oh also, once you're set up, could you write up a quick contribution guide for people on how to use it?

**Comment by marshallswain** [comment]
Absolutely.  Great idea.

**Comment by marshallswain** [comment]
I've set up a contribution guide.  https://feathersjs.gitbooks.io/feathers-docs/content/01_contributing.html
I also set up the basic structure of the docs that we can fill out.

**Comment by ekryski** [comment]
This is so awesome. I'll set up the dns entry.

**Comment by ekryski** [comment]
Alright. DNS done and is now resolving. docs.feathersjs.com

**Comment by daffl** [comment]
Sweet. Now lets make the docs awesome! And eventually we have to look at the customization to make it look at least a little like the website.

**Comment by ekryski** [comment]
I made a couple really small edits to the website styling to test it out.

**Comment by ekryski** [comment]
Alrighty I think this is pretty good. There are just a few updates to be made around authentication and authorization that will get closed out today. The docs live in 2 places:

1. http://docs.feathersjs.com - hosted by gitbook and has offline documentation
2. https://github.com/feathersjs/feathers-docs - repo we build the docs from

Thanks for the suggestion @kamakazikamikaze!
