### ISSUE TITLE
feathers-client get('authentication') is undefined

### ISSUE THREAD

**Issue by gpietro** [feathersjs/feathers#1944]
### Problem description
I'm using redux-saga with feathers-client to authenticate the user.
When the login form is submitted the user is correctly logged in and in the localStorage I see the feathers-jwt.
When refreshing the browser the feathers-jwt still in the localStorage but feathersClient.get('authentication') return undefined.

### This is my feathers client configuration
```
import io from 'socket.io-client';
import feathers from '@feathersjs/client';

const socket = io('http://localhost:3030');
const client = feathers();

client.configure(feathers.socketio(socket));
client.configure(
	feathers.authentication({
		storage: window.localStorage,
	})
);

export default client;
```

[Code: Redux-Saga for authentication](https://gist.github.com/gpietro/72de8df8ee6051e2de35737b89b233fa)

**When this component get rendered, client.get('authentication') returns undefined.**
```
import React, { useLayoutEffect } from 'react';
import { Route } from 'react-router-dom';
import client from 'lib/feathersClient';
import { useDispatch } from 'react-redux';
import { push } from 'connected-react-router';

const PrivateRoute = ({ component: Component, path, ...rest }) => {
	const dispatch = useDispatch();
	useLayoutEffect(() => {
		async function isAuthenticated() {
			const isAuthenticated = await client.get('authentication');
			console.log('isAuth', isAuthenticated);
			if (!isAuthenticated) {
				dispatch(push('/login'));
			}
		}
		isAuthenticated();
	}, [dispatch]);

	return (
		<Route {...rest} path={path} render={(props) => <Component {...props} />} />
	);
};
export default PrivateRoute;
```

**Comment by asamolion** [comment]
You have to call `client.reAuthenticate()` before you can use auth based stuff.

https://docs.feathersjs.com/api/authentication/client.html#app-reauthenticate

**Comment by gpietro** [comment]
Yes, you are right!

```
const PrivateRoute = ({ component: Component, path, ...rest }) => {
	const dispatch = useDispatch();
	useLayoutEffect(() => {
		async function isAuthenticated() {
			let isAuthenticated = await client.get('authentication');
                         if( !isAuthenticated ) {
                                 isAuthenticated = client.reAuthenticate()
                         }
			if (!isAuthenticated) {
				dispatch(push('/login'));
			}
		}
		isAuthenticated();
	}, [dispatch]);

	return (
		<Route {...rest} path={path} render={(props) => <Component {...props} />} />
	);
};
export default PrivateRoute;
```

**Comment by asamolion** [comment]
Not exactly. If you read the "Important Note: " in the docs, it says

> Important: app.reAuthenticate() has to be called when you want to use the token from storage. There’s no need to call it more than once, so you’d typically only do it when the application initializes. Once successful, all subsequent requests will send their authentication information automatically. In some rare cases, for example making sure the user object returned by app.get('authentication') is up-to-date after it was changed on the server, you may safely call it again.

>

So you just have to call `client.reAuthenticate()` once per page load or in this specific case, once your React app initializes. After that all operations with the `client` should receive the auth credentials and function normally.

**Comment by gpietro** [comment]
Ok thanks!
I don't how I missed this info.
