### ISSUE TITLE
context.params.user not defined out of the box using postgres

### ISSUE THREAD

**Issue by jbatx** [feathersjs/feathers#1945]
When attempting to access context.params.user from a hook, the user object is never defined. Additionally, the jwt does not contain id or userId.  I've read several old post and tried all suggestions that seem to make sense.  I've tried the suggestion here https://github.com/feathersjs-ecosystem/authentication/issues/71.  I've tried setting entity in the config.   I've also tried setting userId in the config, just in case that's it and it's not documented.  I'm out of ideas.

### Steps to reproduce
1. Set up a new app using the generator.  Use Postgres and authentication.  I've also set up several other services that don't do anything yet.  Those are immaterial to this issue.   

2. create a new hook on create user service method.

3. Using Postman, authenticate with the default username and password.

4.  Using Postman with the authToken received from the user/pass auth previously, create a new user.  

In the new hook, try accessing context.params.user like this

`module.exports = (options = {}) => {
  return async context => {
    context.result = context.params.user;
    return context;
  };
};`

context.params.user is not defined in the hook you created.

my config
`{
  "host": "localhost",
  "port": 3030,
  "public": "../public/",
  "paginate": {
    "default": 10,
    "max": 50
  },
  "authentication": {
    "entity": "user",
    "service": "users",
    "secret": "SOMETHING",
    "authStrategies": [
      "jwt",
      "local"
    ],
    "jwtOptions": {
      "header": {
        "typ": "access"
      },
      "audience": "https://yourdomain.com",
      "issuer": "feathers",
      "algorithm": "HS256",
      "expiresIn": "1d"
    },
    "local": {
      "usernameField": "email",
      "passwordField": "password"
    },
    "oauth": {
      "redirect": "/",
      "google": {
        "key": "<google oauth key>",
        "secret": "<google oauth secret>",
        "scope": [
          "email",
          "profile",
          "openid"
        ]
      },
      "github": {
        "key": "SOMETHING",
        "secret": "SOMETHING"
      }
    }
  },
  "postgres": "postgres://postgres:foo@localhost:54320/foo"
}
`

### Expected behavior
When I set up the app, context.params.user should be available

### Actual behavior
context.params.user is never there and context.results will always be undefined.

### System configuration
mac 10.15.4
pycharm 2020.1

Tell us about the applicable parts of your setup.

No browser involved yet, 100% postman.

postgres 9.6 (docker)
node v12.16.3
`
 "dependencies": {
    "@feathersjs/authentication": "^4.5.3",
    "@feathersjs/authentication-local": "^4.5.3",
    "@feathersjs/authentication-oauth": "^4.5.3",
    "@feathersjs/configuration": "^4.5.3",
    "@feathersjs/errors": "^4.5.3",
    "@feathersjs/express": "^4.5.3",
    "@feathersjs/feathers": "^4.5.3",
    "@feathersjs/socketio": "^4.5.3",
    "@feathersjs/transport-commons": "^4.5.3",
    "compression": "^1.7.4",
    "cors": "^2.8.5",
    "feathers-sequelize": "^6.1.0",
    "helmet": "^3.22.0",
    "pg": "^8.0.3",
    "sequelize": "^5.21.7",
    "serve-favicon": "^2.5.0",
    "winston": "^3.2.1"
  },
  "devDependencies": {
    "axios": "^0.19.2",
    "eslint": "^6.8.0",
    "mocha": "^7.1.2",
    "nodemon": "^2.0.3"
  }`

**Comment by daffl** [comment]
Hooks on `users.create` will not have a `params.user` because the user that is being created does not exist yet and therefore can't be authenticated. If you want to do something with the created user use `context.result` in an `after` hook.

**Comment by jbatx** [comment]
I want to confirm that the user A, who is accessing  create is allowed to do so before creating the new user B.  

User A must be a member of a group that has the user_admin permission.  I've already created that relationship.  I just need to check it in the hook.

I believe the first step is to get the user A object in the before hook.
