### ISSUE TITLE
Custom routes

### ISSUE THREAD

**Issue by ramzes13** [feathersjs/feathers#1946]
Hello, 
We try to use custom routes, using this example [How do I do nested or custom routes?](https://docs.feathersjs.com/help/faq.html#how-do-i-do-nested-or-custom-routes), everything works fine except for one problem.
We cannot call the service inside the application, ex:

this will throw an error:
```
await app.service('/users/13/posts').find({ name: '1' }); 
```
this work, but we cannot pass the userId value:
```
await app.service('/users/:userId/posts').find({ name: '1' }); 
```

Is there a solution to this problem?

We use Feather version: ^3

**Comment by Tr3ffel** [comment]
I think this should fix your problem :
```
await app.service('/users/:userId/posts').find({
  route: { 
    userId: /*put userId here*/ 
  },
  query: {
    name: '1'
  }
});
```
Also when internally calling a service the query should be inside a query object.

**Comment by ramzes13** [comment]
I did not think of this solution.
Thanks.

**Comment by webafra** [comment]
@Tr3ffel : hi 

please help me to use this custom route
Where did you use this code?
Where did you learn how to create a custom route?


```
await app.service('/users/:userId/posts').find({
  route: { 
    userId: /*put userId here*/ 
  },
  query: {
    name: '1'
  }
});
```
