### ISSUE TITLE
All "post" requests are not found

### ISSUE THREAD

**Issue by SeverinNovack** [feathersjs/feathers#1949]
### Steps to reproduce

This is my app.ts:
```
import path from 'path';
import favicon from 'serve-favicon';
import compress from 'compression';
import helmet from 'helmet';
import cors from 'cors';

import feathers from '@feathersjs/feathers';
import configuration from '@feathersjs/configuration';
import express from '@feathersjs/express';
import socketio from '@feathersjs/socketio';


import { Application } from './declarations';
import Logger from './logger';
import middleware from './middleware';
import services from './services';
import appHooks from './app.hooks';
import channels from './channels';
import authentication from './authentication';
import sequelize from './sequelize';
// Don't remove this comment. It's needed to format import lines nicely.

const app: Application = express(feathers());

// Load app configuration
app.configure(configuration());
// Enable security, CORS, compression, favicon and body parsing
app.use(helmet());
app.use(cors());
// app.use(compress());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(favicon(path.join(app.get('public'), 'favicon.ico')));
// Host the public folder
app.use('/', express.static(app.get('public')));

// set the logger
const logger = new Logger(app.get('logging'));
app.set('logger', logger);
// Set up Plugins and providers
app.configure(express.rest());
app.configure(socketio());

app.configure(sequelize);

// Configure other middleware (see `middleware/index.js`)
app.configure(middleware);
app.configure(authentication);
// Set up our services (see `services/index.js`)
app.configure(services);
// Set up event channels (see channels.js)
app.configure(channels);

// Configure a middleware for 404s and the error handler

app.use(express.notFound());
// app.use(express.errorHandler({ logger } as any));
app.use(express.errorHandler({
    json: (err: any, req: any, res: any, next: any) => {
        err = err.toJSON();
        const errors = {
            errorCode: err.code,
            userMessage: err.message,
            developerMessage: err.data
        };
        res.status(err.code).json({errorCode: err.code,
            userMessage: err.message,
            developerMessage: err.data});
    }
}));


app.hooks(appHooks);

export default app;
```

- After some time I couldn't reach the post endpoints anymore. I created new services and it does not work on them either.
It does not work with postman, which just stays in the loading screen and if I try it from another api the response is "page not found".
All other methods are working fine, just the create and update methods are not working.
When I am using app.post(...) the endpoint is working, but this is destroying the use of the services.

### Expected behavior
The post endpoints are accessable, which means create and update.

### Actual behavior
It does not work with postman, which just stays in the loading screen and if I try it from another api with the "request" module the response is "page not found".

### System configuration

Tell us about the applicable parts of your setup.

Module versions (especially the part that's not working): FeathersJS 4.3.0

NodeJS version: v12.13.1

Operating System: Windows 10

Browser Version: I am using Postman and Google Chrome 73.0.3683.86

Module Loader: npm 6.12.1

I couldn't find anything regarding this specific problem.
Is there a way I "disabled" the post-methods?

**Comment by asamolion** [comment]
Do you use git for this project?

It would help in backtracking and checking each change to find out the culprit.

**Comment by SeverinNovack** [comment]
There was an error on my site. 
Thank you for your answer.
