### ISSUE TITLE
authentication promise caches auth token after logout across tabs/windows

### ISSUE THREAD

**Issue by jnardone** [feathersjs/feathers#1951]
Open an app, log in and get a valid token in local storage.  Open a 2nd tab or window to the same app.  Localstorage is shared, so both instances use the same authentication.

In one window/tab, navigate to a page that gets a reference to a service (e.g. `const fooService = restApp.service('foo');`)

In the other window/tab, log out.

Go back to the first window/tab, execute an action that doesn't navigate but calls something on that service.  It succeeds.

I don't want to force a round-trip (which would work if i did a `reAuthenticate(true)`), but the use of the promise in the client's authentication hook makes this tricky.  One possibility is an event emitter in the storage wrapper, which for localStorage could leverage https://developer.mozilla.org/en-US/docs/Web/API/Window/storage_event across tabs/windows.  We might do something like this to hack it into our layer and call `.reset()` when this happens and the token is emptied, but it's not ideal.

### Expected behavior
The authentication client should react to changes in the storage of the token so that it does not incorrectly use a cached token.

### Actual behavior
The call succeeds because the REST app instance in one tab is independent of another tab/window.  That promise is cached after a successful `authenticate` but does not check the status of the storage to see if it has changed.

### System configuration
This is latest (4.5.3)

**Comment by daffl** [comment]
The most reliable way to prevent this (or the re-use of tokens after logout in general) is to [blacklist it on the server](https://docs.feathersjs.com/cookbook/authentication/revoke-jwt.html)

**Comment by jnardone** [comment]
Yes, we're going to do this.

This also covers the case within the same browser on the client side (and you have to adjust the JWT key name if you use something different):

```
window.addEventListener('storage', (ev) => {
  if (ev.key === 'feathers-jwt' && ev.newValue === null) {
    app.logout();
  }
});
```

**Comment by daffl** [comment]
That may not be unreasonable to add. I'd just like to avoid adding DOM specific code as much as possible since the authentication client can also work on server side environments and to avoid browser incompatibilities.

**Comment by jnardone** [comment]
Yeah, I can see that.  Just pasting in case anyone else needs a workaround to that.
