### ISSUE TITLE
Cannot connect to feathers server through socket with React Native get timeout

### ISSUE THREAD

**Issue by sixclones** [feathersjs/feathers#1953]
### Steps to reproduce

Clone this [repository](https://github.com/sixclones/feathersjs-timeout) and follow instructions on the README.

### Expected behavior
Authenticate to the server

### Actual behavior
Get a timeout
```bash
[Timeout: Timeout of 5000ms exceeded calling create on authentication]
```

### System configuration

**Module versions** (especially the part that's not working):
_Server_
```json
"@feathersjs/authentication": "^4.5.3",
"@feathersjs/authentication-local": "^4.5.4",
"@feathersjs/authentication-oauth": "^4.5.4",
"@feathersjs/configuration": "^4.5.3",
"@feathersjs/errors": "^4.5.3",
"@feathersjs/express": "^4.5.4",    
"@feathersjs/feathers": "^4.5.3",
"@feathersjs/socketio": "^4.5.4",
```
_App_
```json
"@feathersjs/authentication-client": "^4.5.4",
"@feathersjs/feathers": "^4.5.3",
"@feathersjs/socketio-client": "^4.5.4",
"socket.io-client": "^2.3.0"
```

**NodeJS version**:
v12.16.2 

**React Native Version**:
0.62.2

**Operating System**:
Windows 10
Version 1903 (OS Build 18362.778)

_Running the project on WSL (version 2004.2020.424.0)_
Distributor ID: Ubuntu
Description: Ubuntu 18.04.4 LTS
Release: 18.04
Codename: bionic

Also tried the bug on macOS.
**NodeJS version**:
v10.16.0

**Operating System**:
macOS 10.15.2

**Comment by sixclones** [comment]
It seems that the problem comes from the [`forceNode` param](https://github.com/sixclones/feathersjs-timeout/blob/master/app/App.js#L15) in the socket instance.

```js
const socket = io(url, {
  transports: ['websocket'],
  forceNew: true,
  forceNode: true
});
```

This param comes from this [issue](https://github.com/socketio/socket.io-client/issues/1290#issuecomment-606426152) on `socket.io-client` repository. I'm closing this issue as there is no relation with feathersjs.

**Comment by darrenkeenfanduel** [comment]
Just to add, this fixes the warning but with the latest `react-native` there seems to be a timeout error. Is there an alternative for websockets?
