### ISSUE TITLE
Google CloudSQL MySQL

### ISSUE THREAD

**Issue by sketchminds** [feathersjs/feathers#1954]
Hi,

Is it possible to connect to cloudsql with ssl mode?

Thanks.

**Comment by daffl** [comment]
There should be nothing Feathers specific so any resource (like [this one](https://stackoverflow.com/questions/52455507/connecting-sequelize-to-google-cloud-sql) or [this](https://medium.com/google-cloud/node-js-on-app-engine-with-cloud-sql-proxy-43f56279a56b)) on connecting your ORM of choice (Knex, Objection, Sequelize) to Google CloudSQL should apply here.
