### ISSUE TITLE
RESTCLIENT can call FIND but not by REACT CODE

### ISSUE THREAD

**Issue by getforschin** [feathersjs/feathers#1956]
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))
**FEATHER CLIENT IMPORT**
![221](https://user-images.githubusercontent.com/57673631/81812627-09072780-9544-11ea-82d0-e0080fc3b8e1.PNG)

**PROBLEM IN CODE**
![222](https://user-images.githubusercontent.com/57673631/81812781-394ec600-9544-11ea-8e85-9a8808c08e01.PNG)

**EASY RETURN IN POSTMAN**
![gh](https://user-images.githubusercontent.com/57673631/81812926-6c915500-9544-11ea-8ad9-f35b9b8c4575.PNG)

### Expected behavior
should return data in users

### Actual behavior
Tell us what happens instead
![Capture](https://user-images.githubusercontent.com/57673631/81812424-b9286080-9543-11ea-8987-a2ab21d00844.PNG)

### System configuration
windows , 16gb ram 

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working): 4.5.4

**NodeJS version**: Latest

**Operating System**: Windows

**Browser Version**: Latest

**React Native Version**:not use

**Module Loader**: npm

**Comment by J3m5** [comment]
Did you authenticate with the feathers client before making the request?
And I don't if freezing your feathers class is a good idea, as the feathers client handle its state internally.

**Comment by getforschin** [comment]
> Did you authenticate with the feathers client before making the request?
> And I don't if freezing your feathers class is a good idea, as the feathers client handle its state internally.

ok i will change freezing .. and i think the client object it is already authenticate and i can use client.service("users").find() and i authenticate it with client.authenticate function where i pass username and password and in my localhost i can see jwt-token in storing

**Comment by daffl** [comment]
Just having the token in storage is not enough. You have to call [reAuthenticate](https://docs.feathersjs.com/api/authentication/client.html#app-reauthenticate) every time your page loads for the client to use it.

**Comment by getforschin** [comment]
> Just having the token in storage is not enough. You have to call [reAuthenticate](https://docs.feathersjs.com/api/authentication/client.html#app-reauthenticate) every time your page loads for the client to use it.

thanks for the reply @daffl  , now i understand i have to reAuthenticate that token but i cannot under where exactly i have to do it in my code .. when i reload the page again my feather.js loads and again new client object created .. i cannot see the example where developer use reAuthenticate property on reload the page .. i study the chat-app of react app feather application where i cannot find reAuthenticate and when i refresh my page then same screen come without reauthentication.

It is very nice if i found an example where developer use react-router and reauthentication manage there
