### ISSUE TITLE
How to configure HTTPS support?

### ISSUE THREAD

**Issue by averri** [feathersjs/feathers#1958]
I would like to know how to configure HTTPS support in Feathersjs v4.

**Comment by daffl** [comment]
This is documented [in the FAQ](https://docs.feathersjs.com/help/faq.html#how-do-i-set-up-https) and the [Express API documentation](https://docs.feathersjs.com/api/express.html#https).

**Comment by averri** [comment]
Thank you @daffl.

I'm having issues to connect to the server, I created a self signed certificate, which I can access normally via browser, but the Socketio client fails to connect.

Client code: 
```javascript
const feathers = require('@feathersjs/feathers')
const auth = require('@feathersjs/authentication-client')
const socketio = require('@feathersjs/socketio-client')
const api = feathers()
const io = require('socket.io-client')


const socket = io(apiURL, {
  transports: ['websocket', 'polling'],
  rejectUnauthorized: false,
  path: '/socket.io'
})
```

Error message in the browser:
```
websocket.js?0882:120 WebSocket connection to 'wss://192.168.66.101:4000/socket.io/?EIO=3&transport=websocket' failed: Error in connection establishment: net::ERR_CERT_AUTHORITY_INVALID
```

**Comment by daffl** [comment]
Well, if it's self signed it is unauthorized so you have to change the `rejectUnauthorized` that you already have there to `true`.

**Comment by averri** [comment]
Hi @daffl, the `rejectUnauthorized` should be set to `false` for self-signed, please see 
https://github.com/socketio/socket.io-client/issues/982. I have tried using `true` but it didn't work either.

**Comment by daffl** [comment]
Sorry my bad, I clearly did not pay attention 😄 I forgot that the server also needs to be set up accordingly to support self-signed certificates. The test in https://github.com/feathersjs/feathers/blob/master/packages/express/test/index.test.js#L225 has an example for that:

```js
    const httpsServer = https.createServer({
      key: fs.readFileSync(path.join(__dirname, '..', '..', 'tests', 'resources', 'privatekey.pem')),
      cert: fs.readFileSync(path.join(__dirname, '..', '..', 'tests', 'resources', 'certificate.pem')),
      rejectUnauthorized: false,
      requestCert: false
    }, app).listen(7889);
```

**Comment by averri** [comment]
Hi @daffl, that configuration in the server side does not work either. I'm trying to test the application in the local network, so I'll create a valid Let's Encrypt certificate with `nip.io` domain name (https://nip.io).

I have tried to configure the SocketIO client to connect to the server, but it does not work, frustratingly. I have opened an issue on SocketIO: https://github.com/socketio/socket.io/issues/3599

**Comment by daffl** [comment]
Odd, I'm certain I tested this before but maybe something has changed since then. The only other thing I've seen is setting the `NODE_TLS_REJECT_UNAUTHORIZED` environment variable to `0`.

**Comment by junit38** [comment]
Hi i fixed this using nginx, change you configuration to something like this:

```
server {
    listen 443 ssl;
    server_name api.yourdomain.com www.api.yourdomain.com;
    ssl_certificate /etc/letsencrypt/live/api.yourdomain.com/fullchain.pem;  # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/api.yourdomain.com/privkey.pem;  # managed by Certbot

    location / {
        proxy_pass http://localhost:3030;  # Assuming your Feathers app is running on localhost:3030
        proxy_http_version 1.1;

        # Ensure WebSocket support for Feathers real-time communication
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';

        # Pass the correct host header
        proxy_set_header Host $host;

        # Allow Feathers to detect the origin and support websockets
        proxy_cache_bypass $http_upgrade;

        # Optionally, you can pass more headers depending on your setup
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

Also app run by forever.
