### ISSUE TITLE
Angular2 Getting Started Todo

### ISSUE THREAD

**Issue by talensjr** [feathersjs/feathers#196]
Hi there! I am learning Angular 2 for a while and found feathersjs to be the backend I wanted, so I followed the Getting Started tutorial and made it with Angular 2 as a client side. @daffl asked me to post a link here so here it goes! 
https://github.com/talensjr/feathersjs-gs

**Comment by marshallswain** [comment]
Cool!:+1:

**Comment by ekryski** [comment]
@talensjr Awesome! We'll link to it when we get the new site up!

**Comment by talensjr** [comment]
Thank you! Very glad to contribute!

**Comment by drewlio** [comment]
@talensjr I'm struggling to get feathers up and running with Typescript (and Angular2) and it seems you've done it. Although `tsc` and `atom-typescript` both give errors (but still compile to es5): 
```
client/app/todos/todos.service.ts(15,21): error TS2304: Cannot find name 'feathers'.
client/app/todos/todos.service.ts(15,42): error TS2304: Cannot find name 'feathers'.
server/main.ts(1,27): error TS2307: Cannot find module 'feathers'.
server/main.ts(3,29): error TS2307: Cannot find module 'body-parser'.
```
I think this is general problem with using external ambient ES5 modules in Typescript without a typing file. What is your workflow to get past this (don't say 'ignore the errors')?

Also, your `package.json` lists:
```
"dependencies": {
    "rxjs": "^5.0.0-beta.0",
}
```
and as of today it installs `5.0.0-beta.2` which breaks your demo. I downgraded to `5.0.0-beta.0` and it works fine.

**Comment by talensjr** [comment]
Hi @drewlio , sorry for the delay, let me take a look and give you an answer. Thank you for reporting that.

**Comment by talensjr** [comment]
Hi @drewlio ! You were right, both problem and solution with angular2-beta.6. Now the peerDependencies are locked to the needed versions, so there is no break installing them.

About the compilation errors, there is just typescript saying that it can't find the definitions of those variables, cause they, by now, not exist. I added the 'body-parser' typings, so it shouldn't appear as an error, but there are no feathersjs typings. You can define them yourself if you want to, but just don't worry too much, it just does affect you as you don't get IDE intellisense for that 'variable'.

**Comment by ekryski** [comment]
If either of you @talensjr or @drewlio feel like writing a guide with Feathers 2 we'd :heart: you forever. We have a placeholder :wink: https://github.com/feathersjs/feathers-docs/blob/master/guides/angular2.md.

**Comment by ekryski** [comment]
A first crack is done and posted here: http://docs.feathersjs.com/guides/angular2.html.

**Comment by srapionyan4** [comment]
վայ մեռ կլիրը ծծեք

**Comment by marshallswain** [comment]
@srapionyan4 What language?  I don't think Google translate isn't able to detect that phrase, well.
