### ISSUE TITLE
how to use many-to-many or one-to-many relationship

### ISSUE THREAD

**Issue by webafra** [feathersjs/feathers#1960]
hi .

1 - Please also explain the types of relationships between tables, one-to-many, many-to-many relationships and so on.

2 - and how to paginate relationship data ( users.posts limit 10 row ) to response with url parameters?

3 - how to limit output field ( mySQL Example:  select `name`, `email` from posts where `userId` = '5ec03f73d187403674d21092' ) on relationship.

4 - how to save relationship data? for example : many-to-many relation on posts & categories
save postid and categoryId on other table ( or collection )

What is your strategy for capturing a user's posts using the get method?

For example: /users/5ec03f73d187403674d21092$populate[]=posts&$populate[]=messageCount

The feathersjs documentation of the site in this case is very weak.

NodeJs : V 13
DB: MongoDb
ORM: Mongoose
Feathers: V 4.3.0

**Comment by daffl** [comment]
This is documented in detail at https://github.com/feathersjs-ecosystem/feathers-sequelize#associations

**Comment by webafra** [comment]
@daffl : i use Mongo db 
feathers-sequelize not working in mongoDb !

**Comment by daffl** [comment]
Sorry, the Mongoose documentation can be found at https://github.com/feathersjs-ecosystem/feathers-mongoose. There are two important things:

1. Understanding the Mongoose documentation at https://mongoosejs.com.
2. Using [params.mongoose](https://github.com/feathersjs-ecosystem/feathers-mongoose) and [$populate](https://github.com/feathersjs-ecosystem/feathers-mongoose#populate) to pass Mongoose options and populate data

Being familiar with the ORM you chose is very important. If you run into a problem, first try to reproduce it with the ORM directly. If you do have an issue connecting between Feathers and Mongoose, please submit a new issue with a complete example with what you have tried and how to reproduce your problem.
