### ISSUE TITLE
Make app.configure async aware

### ISSUE THREAD

**Issue by AuHau** [feathersjs/feathers#1965]
I am not completely sure, but I believe that `app.configure()` is Feather's addition to Express right? On Express's side, the `app.configure` was removed since version 4.x which I believe you are using latest version for the `@feathers/express` package right?

If that is the case I would like to suggest to make the `app.configure()` async aware. Preferably if Promise is returned by the callback await until its resolution. 

This is important when you want to configure your application from async sources (for example populate some data-stores from database etc.). This would for example "fixed" the need for storing Promise on `app` when syncing database for Sequelize like `app.set('sequelizeSync', sequelize.sync())`.

This I believe should not be a breaking change. Would that be something you would be willing to accept? If so, I could provide PR for this functionality.

**Comment by daffl** [comment]
Asynchronous setup and configuration is slated for the next version. The original issue is https://github.com/feathersjs/feathers/issues/509

**Comment by AuHau** [comment]
That is pretty dope! Thanks for the info! 
Looking forward to the new release :-)
