### ISSUE TITLE
$sort not working in find calls

### ISSUE THREAD

**Issue by startupthekid** [feathersjs/feathers#197]
In combination with `feathers-sequelize`, I'm making a find call to: `localhost:3000/api?$sort[rank]=-1`
and to `localhost:3000/api?$sort[rank]=1` using Postman but both calls return my results in the exact same order. In other words, the `$sort` parameter has no effect.

Using `feathers-hooks`, I'm printing out the params and getting:

```
{ '$sort': { rank: '-1' } }
```

I suspect that this is somewhat related to [this issue](https://github.com/feathersjs/feathers-client/issues/19) except I'm not using `feathers-client` (I made my own api class using RxJS, superagent, and qs) so I figured I'd post it here. Regardless of if I make the request through my own api class or through Postman, `$sort` has no effect.

What's interested though is that doing:

```
const query = { $sort: { rank: -1 } };
app.service(`/`).find(query);
```
works exactly as I would expect it to which leads me to believe whatever issue there is isn't in `feathers-sequelize` but probably in the base feathers library.

My feather's setup is dead simple:

app
  .configure(rest())
  .configure(hooks())
  .use('/', signupService);

I'll do some more research and digging, see if I can find anything.

**Comment by daffl** [comment]
Could it just be a conversion issue that Sequelize needs the actual number `-1

**Comment by daffl** [comment]
Actually I bet it's a problem with the adapter at https://github.com/feathersjs/feathers-sequelize/blob/master/src/utils.js#L39. It should probably be something like

```js
order.push([ name, parseInt(sort[name], 10) === 1 ? 'ASC' : 'DESC' ]));
```

**Comment by startupthekid** [comment]
Wow that was precisely it...so quick.

I tested it by doing a simple hook:

```
find(hook, next) {
    hook.params.query.$sort.rank = parseInt(hook.params.query.$sort.rank);
    next();
  }
```

and it works as expected.

**Comment by daffl** [comment]
Yes, I don't think Feathers should do any type conversion. The hook works (you could maybe make a more generic version for Sequelize) but I'd also welcome a PR in `feathers-sequelize` that adds the number parsing fix.

**Comment by startupthekid** [comment]
Yeah I agree, it's more of something the adapter should take care of. I'll issue a PR in just a minute.

**Comment by realdubb** [comment]
This was helpful with a similar issue I was having. With the latest releases of `feathers-sequelize` the syntax that worked for me in the `find` hook was:

```
hook.params.query.$sort = { id: 1 }
```

Where `id` is the column name and `1` is the rank, in this case `ASC`

**Comment by changliu86** [comment]
Thanks a lot
