### ISSUE TITLE
Typing Proposal - Overload `find` Service Method

### ISSUE THREAD

**Issue by robbyphillips** [feathersjs/feathers#1970]
### Expected behavior
It would be nice if the return type was automatically inferred from adapter services based on `params.paginate`

```typescript
let users: User[] = await app.service('users').find({ paginate: false })
let paginated: Paginated<User> = await app.service('users').find()
```
### Actual behavior

Instead, the type system does not know which return type to use, so we need to cast it.

```typescript
let paginated = await app.service('users').find() as Paginated<User>
```

### Proposal

I think we can solve this with an overload.  Something like:

```typescript
interface ParamsNoPaginate extends Params {  // not a great name, I know..
  paginate: false
}

// service.d.ts
export declare class AdapterService<T = any> implements ServiceMethods<T> {
  // ...
  find(params: ParamsNoPaginate): Promise<T[]>
  find(params?: Params): Promise<Paginate<T>>
  // ...
}
```

I'm less comfortable with conditional types, but I suppose that would work as well and it would avoid having to extend `Params`.

**Comment by GVanderLugt** [comment]
I'm new to TypeScript, so I'm not comfortable commenting on the implementation, but this would definitely be nice to have.
