### ISSUE TITLE
TypeError: Cannot redefine property: default

### ISSUE THREAD

**Issue by IElgohary** [feathersjs/feathers#1974]
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
Suddely, I get this error `TypeError: Cannot redefine property: default` when I run `npm run compile && node lib/`
the stack trace shows that the issue is in the compiled files in a hooks file of one of the services.

- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc. This makes it much easier for us to debug and issues that have a reproducable example will get higher priority.
I'm not sure how to reproduce it because iit was working. I tried changing typescript version and node version but still no luck.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**: 12.4.0

**Operating System**: using docker image `node:12.4.0` which uses linux

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by daffl** [comment]
I ran into this error because of a faulty version of TSLib. Making sure to have the latest TypeScript version installed fixed it.

**Comment by IElgohary** [comment]
> I ran into this error because of a faulty version of TSLib. Making sure to have the latest TypeScript version installed fixed it.

@daffl I tried that but I still get the same issue

**Comment by IElgohary** [comment]
I fixed it by keeping the package-lock in the repo. It's probably caused by conflicting dependencies.

**Comment by josephstgh** [comment]
I believe this issue is caused by typescript version `3.9.0` to `3.9.3`

Try upgrade to `3.9.5` or downgrade back to `3.8.3`
