### ISSUE TITLE
Hook handling after reject results in problem with eventMapping

### ISSUE THREAD

**Issue by geoynomous** [feathersjs/feathers#1975]
### Steps to reproduce

* rejecting the promise of a service's get operation

```
get: function(id, params) {
    return new Promise(function(resolve, reject) {
        // SNAP ...//
        reject(rejectErrors.CLOUD_STORAGE_ACCESS);
    }
}
```

### Expected behavior

Proper error handling

### Actual behavior

```
"Cannot read property 'eventMappings' of undefined"
     at /Users/default/project/node_modules/ feathersjs/commons/lib/hooks.js:115

```
### System configuration

**Module versions** (especially the part that's not working):

4.5.4 (commons)

**NodeJS version**:

v12.13.0

**Operating System**:

MacOS 10.14.6

**Browser Version**:

Firefox 76.0.1

**Comment by geoynomous** [comment]
Somehow in line events.js:8

`    const { app, service } = hook;
`
app and service are both undefined

**Comment by daffl** [comment]
Errors are expected to be an instance of [JavaScript errors](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error) or [Feathers errors](https://docs.feathersjs.com/api/errors.html).

**Comment by geoynomous** [comment]
@daffl you're saying the reject content must be one of those? I will check

**Comment by geoynomous** [comment]
Yes ... I've checked - thanks the reply ... maybe it can be handled - to output something that not an error got used in a reject?

**Comment by daffl** [comment]
I believe this should be working in the upcoming v5. You can see how to test it [here](https://dove.docs.feathersjs.com/guides/migrating.html).
