### ISSUE TITLE
Authentication documentation not up to date or incorrect

### ISSUE THREAD

**Issue by lwhiteley** [feathersjs/feathers#1977]
The Http api documentation for re-authentication is outdated.
https://docs.feathersjs.com/api/client/rest.html#authentication

### Steps to reproduce
- Generate a new feathers app with authentication
- create a user
- login
- perform the suggested re-authentication without a body

```
Then to authenticate subsequent requests, add the 
returned accessToken to the Authorization header as Bearer <your access token>:

curl -H "Content-Type: application/json" \
-H "Authorization: Bearer <your access token>" \
-X POST http://localhost:3030/authentication
```

result:
```json
{
    "name": "NotAuthenticated",
    "message": "Invalid authentication information (no `strategy` set)",
    "code": 401,
    "className": "not-authenticated",
    "errors": {}
}
```

### Expected behavior
Documentation should reflect the real behaviour

### Actual behavior

```
curl -H "Content-Type: application/json" \
-X POST \
-d '{"strategy":"jwt","accessToken":"<your token>"}' \
http://localhost:3030/authentication
```

Please note that this is behaviour of the js function `app.reAuthenticate()`

**Comment by lwhiteley** [comment]
misintepreted as re-authentication syntax for was meant for other requests

**Comment by lwhiteley** [comment]
actually the example is still misleading as the request `POST http://localhost:3030/authentication` without a body will fail currently

**Comment by daffl** [comment]
That is true. It has been changed to `http://localhost:3030/messages`.
