### ISSUE TITLE
Error return from authentication service is not in Feathers errors types

### ISSUE THREAD

**Issue by GoldenHands92** [feathersjs/feathers#1978]
### Steps to reproduce
When I do login with wrong email or password by [authenticate](https://docs.feathersjs.com/api/authentication/client.html#app-authenticate-data) function, I receive an error but it not in [Feathers errors list](https://docs.feathersjs.com/api/errors.html#feathers-errors)

```
{"hook":{"type":"before","method":"create","path":"authentication","params":{},"data":{"strategy":"local","email":"email@test.com","password":"randomstring"}}}
```

but it returns the correct errors type when I called by `curl`: 

```
curl -H "Content-Type: application/json" -d '{"strategy": "local", "email":"email@test.com", "password": "randomstring"}' http://localhost:3000/authentication
```

### Expected behavior
throw an Error in [Feathers errors list](https://docs.feathersjs.com/api/errors.html#feathers-errors)

### Actual behavior
weird error type as mention above

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** : "@feathersjs/authentication-client": "^4.5.4"

**NodeJS version**: 12.13.0

**Comment by daffl** [comment]
Please share the complete client code that is causing that error.

**Comment by GoldenHands92** [comment]
this is my configuration for authentication:

```
 ...
  const feathersClient = feathers();
  const restClient = feathersRest(config.api.url);
  feathersClient.configure(restClient.fetch(fetch));
  feathersClient.configure(
    auth({
      storageKey: 'jwt',
    }),
  );
 ...
```

and then in login function, I use `authenticate` as below:

```
 const authenticate = feathersClient?.authenticate;
 ...
  const handleLogin = async (formData) => {
    setLoading(true);
    try {
      const response = await authenticate({
        strategy: 'local',
        email: formData.email,
        password: formData.password,
      });
      ...
    } catch (error) {
      console.error(JSON.stringify(error)); // expected a Feather error here but get other type of error
    }
  };
  ...
```

**Comment by daffl** [comment]
It should be


```js
 ...
  const handleLogin = async (formData) => {
    try {
      const response = await feathersClient.authenticate({
        strategy: 'local',
        email: formData.email,
        password: formData.password,
      });
      ...
    } catch (error) {
      console.error(JSON.stringify(error)); // expected a Feather error here but get other type of error
    }
  };
```
