### ISSUE TITLE
how to get row by other field ( username )

### ISSUE THREAD

**Issue by webafra** [feathersjs/feathers#1979]
hello .

i want get one row on database with _get method but _get method argument is row id ( _id )

for example :

```
let keys = await app.service('keys')._get({username: 'john'});

```

output is single record on notFound exception
if use find method , output is pagination ( multi record ), I need a record.

**Comment by lwhiteley** [comment]
if you check the api documentation

`adapter.get(id [,params])` gets a single record by its id with the option to pass in a query,

https://docs.feathersjs.com/api/databases/common.html#adapter-get-id-params

if you want your db has a field `username` which is guaranteed to be unique then use the `.find({query: {}})` and pull the first record from the array.

You can also disable pagination for a specific call as well

https://docs.feathersjs.com/api/databases/common.html#adapter-find-params
