### ISSUE TITLE
Anonymous authentication not secure (reason: `context.params.user` not removed after logout)

### ISSUE THREAD

**Issue by ismail-codinglab** [feathersjs/feathers#1981]
### Steps to reproduce

1. login as a user
2. logout
3. do a call to a hook which allows anonymous authentication
4. you will be seen as the last loggedin user, not an anonymous user since `context.params.user` is set.

### Expected behavior

To be an anonymous user, thus `context.params.user` cleaned after logout

### Actual behavior
`context.params.user` is not cleaned thus you will look like that last user

### System configuration

We used the anonymous authentication as documented here:
https://docs.feathersjs.com/cookbook/authentication/anonymous.html

**Module versions** (especially the part that's not working):

Feathers v4

**NodeJS version**:
v12

**Operating System**:
Ubuntu

**Comment by daffl** [comment]
This has been fixed in [v4.5.3](https://github.com/feathersjs/feathers/releases/tag/v4.5.3) so ensure you are using the latest version.
