### ISSUE TITLE
Services sharing same mongoose model ends up with `Error: socket hang up`

### ISSUE THREAD

**Issue by mati0090** [feathersjs/feathers#1983]
### Steps to reproduce

1. `feathers generate app`
2. `feathers generate service` (name: `offers`, path: `/offers`)
3. `feathers generate service` (name: `management/offers`, path: `/management/offers`)

### Expected behavior
Both - `GET /offers` and `GET /management/offers` should return:
```
{
    "total": 0,
    "limit": 10,
    "skip": 0,
    "data": []
}
```

### Actual behavior
`GET /management/offers` returns expected JSON response.
`GET /offers` gets timeout returning `Error: socket hang up `

### System configuration

**Module versions** (especially the part that's not working):

**NodeJS version**: `v11.0.0`

**Operating System**: `MacOS 10.12.6 (16G2128)`

Creating same functionality using MongoDB instead Mongoose works fine.

**Comment by jamesvillarrubia** [comment]
Try using:
```
  const options = {
    Model: app.services['offers'].Model,
    paginate: app.get('paginate')
  };
```
when instantiating the second service.  With some DB connectors, you can't always just create the same model on boot, sometimes you need to leverage the model as already attached to the `app` object.

**Comment by mati0090** [comment]
It works!

**Comment by MarianoAst** [comment]
> Try using:
> 
> ```
>   const options = {
>     Model: app.services['offers'].Model,
>     paginate: app.get('paginate')
>   };
> ```
> 
> when instantiating the second service. With some DB connectors, you can't always just create the same model on boot, sometimes you need to leverage the model as already attached to the `app` object.

Thank you ! Helped me out with same problem 😛
