### ISSUE TITLE
Authentication by Facebook oauth with react native

### ISSUE THREAD

**Issue by Shair17** [feathersjs/feathers#1984]
I have been looking for a guide to do something like this, my idea is to authenticate through facebook and (email, password), that is, two authentication methods, but I could not do it.

https://github.com/feathersjs-ecosystem/authentication-oauth2/issues/80
https://github.com/feathersjs-ecosystem/authentication-oauth2/issues/22

### System configuration

Tell us about the applicable parts of your setup.

**NodeJS version**: 10.19.0

**Operating System**: Ubuntu 20.04

**React Version**: 16.11.0

**React Native Version**: 0.62.2

**Comment by daffl** [comment]
This is handled with [oAuth strategy flow #2](https://docs.feathersjs.com/api/authentication/oauth.html#flow). You have to obtain the oAuth access token through React Native (e.g. https://github.com/magus/react-native-facebook-login) and then authenticate with that oAuth token.

**Comment by Shair17** [comment]
@daffl thanks

**Comment by daffl** [comment]
Once you get it working, a cookbook contribution for this would be great. Or even just a markdown file with some notes of what you did.

**Comment by Shair17** [comment]
@daffl I have tried to do it but have had no results.

**Comment by co2nut** [comment]
@Shair17 what is the issue that you're facing?

**Comment by Shair17** [comment]
@co2nut I want to authenticate by facebook (oauth), actually I am somewhat lost, I have checked the documentation and I have not obtained results, use the library ´react-native-fbsdk´ to get the token from the client side, and from the server configure feathersjs as it says in the documentation and I have not obtained results

**Comment by co2nut** [comment]
do you mean that you can the access token from react native and try to use the feathers client to authenticate it with facebook strategy but got error?

do you mind share some of your codes or errors here?

**Comment by Shair17** [comment]
actually i'm confused with feathersjs working on client side, I trying to install the modules `@feathersjs/feathers`, `@feathersjs/rest-client`, `@feathersjs/authentication-client` in my react native project, I created a separate file for feathers handling, followed the guide for client side: https://docs.feathersjs.com/api/client.html#react-native

For authentication I follow this guide: https://docs.feathersjs.com/api/authentication/client.html#configuration

One thing, how is exactly the `@feathersjs/authentication-client` module know the URL endpoint? I never see a configuration for that, only on the rest-client module.

I going to put here tomorrow the code that I've been using.

**Comment by co2nut** [comment]
this is how I normally defined my feathers.js for my react native project

```js
import io from 'socket.io-client';
import feathers from '@feathersjs/feathers';
import socketio from '@feathersjs/socketio-client';
import authentication from '@feathersjs/authentication-client';

const socket = io('http://10.0.2.2:3030/');//local
const client = feathers();

client.configure(socketio(socket, {
  timeout: 5000
}));
client.configure(authentication({
  storage: window.localStorage
}));

export default client;

```

**Comment by Shair17** [comment]
I am not using socketio, so... How does feathers know the API url? Another thing is, React Native doesn't support window.localStorage, I use AsyncStorage, did u try oauth authentication? With facebook or another else

**Comment by Shair17** [comment]
@daffl I was thinking of opening another issue, but better not, I decided to continue with this one, yesterday I tried feathers with oauth authentication and in the client (React Native), next I will show screenshots of the code, and what comes out when I press to start session.

This is the result when I press on login with facebook
![image](https://user-images.githubusercontent.com/18153674/84689242-4de8fa00-af06-11ea-9338-9536b69916ba.png)

This is the code on client side (React Native), the login button
![Captura de pantalla de 2020-06-15 00-37-00](https://user-images.githubusercontent.com/18153674/84689315-6ce78c00-af06-11ea-9098-92b6bdf8ed81.png)

This is my feathers.js where I declare the feathers, feathers-client & feathers auth modules
![Captura de pantalla de 2020-06-15 00-37-24](https://user-images.githubusercontent.com/18153674/84689481-a5876580-af06-11ea-91d2-37b97b2d80ba.png)

And finally here is my backend (authentication.js)
![Captura de pantalla de 2020-06-15 00-37-12](https://user-images.githubusercontent.com/18153674/84689647-e54e4d00-af06-11ea-97bb-38ead3dac996.png)
![Captura de pantalla de 2020-06-15 00-37-17](https://user-images.githubusercontent.com/18153674/84689669-ebdcc480-af06-11ea-901d-3f308ba1e3ce.png)


I don't understand very well why the react native console out is "error [Not Authenticated: Invalid authentication information (strategy now allowed in authStrategies)]" if I declare a facebook strategy :/

**Comment by Shair17** [comment]
@daffl Apparently the error is in feathers.js, I have tried express and passport and everything works very well.

**Comment by daffl** [comment]
See [this __Note__ in the documentation](https://docs.feathersjs.com/api/authentication/oauth.html#flow):

> Note: If you are attempting to authenticate using an obtained access token, ensure that you have added the strategy (e.g. 'facebook') to your authStrategies.

**Comment by yohane55** [comment]
@daffl Thank you and  in the documentation, there is no explanation about authenticating using accessToken from social auth (for example from separate frontend or mobile app), even automatically adding new users in our db. can you tell us about this.

**Comment by yohane55** [comment]
```
{
    "strategy":"facebook",
    "access_token":"..."

}


```

This is giving me error
```{
    "name": "NotAuthenticated",
    "message": "Invalid authentication information (strategy not allowed in authStrategies)",
    "code": 401,
    "className": "not-authenticated",
    "errors": {}
}
```

my configuration

```
"oauth": {
      "redirect": "/",
      "google": {
        "key": "<google oauth key>",
        "secret": "<google oauth secret>",
        "scope": [
          "openid",
          "email",
          "profile"
        ]
      },
      "facebook": {
        "key": "...",
        "secret": "...",
        "scope": ["email, public_profile"]
      }
```

```
class FacebookStrategy extends OAuthStrategy {
  async getProfile(authResult) {
    // This is the OAuth access token that can be used
    // for Facebook API requests as the Bearer token
    const accessToken = authResult.access_token;

    const { data } = await axios.get("https://graph.facebook.com/me", {
      headers: {
        authorization: `Bearer ${accessToken}`,
      },
      params: {
        // There are
        fields: "id,name,email,picture",
      },
    });

    return data;
  }

  async getEntityData(profile) {
    // `profile` is the data returned by getProfile
    const baseData = await super.getEntityData(profile);

    return {
      ...baseData,
      name: profile.name,
      email: profile.email,
    };
  }
}

module.exports = (app) => {
  const authentication = new AuthenticationService(app);
  authentication.register("facebook", new FacebookStrategy());

....
}
```

**Comment by yohane55** [comment]
@Shair17 add "facebook" to "authStrategies"

```
"authentication": {
    "entity": "user",
    "service": "users",
    "secret": "....",
    "authStrategies": [
      "jwt",
      "local",
      "apiKey", "otp", "facebook"
    ],
```

**Comment by jiangts** [comment]
I just got this working, following this guide. Thanks a million!

A quick summary for others, using Google sign in as an example:
- **The goal: get a JWT signed by your server**. In normal oauth login for web, the feather's auth libraries will set up various routes on your server (i.e. `/oauth/google/callback`, etc), which handle the entire auth handshake with Google. After the flow is completed, you a JWT that is signed by your server. That JWT authenticates all future requests to your feathers server.
- However, on Expo, you are only given a way to get an access token from Google (I followed this guide: https://docs.expo.io/versions/v40.0.0/sdk/google/ -- you gotta get a new client id, but it's really easy after that)

```javascript
import * as Google from 'expo-google-app-auth';

const expoGoogleConfig = {
  iosClientId: '<your-expo-google-client-id>',
  scopes: ['profile', 'email'],
}
const signInWithGoogleAsync = async (config) => {
  try {
    const result = await Google.logInAsync(config);

    if (result.type === 'success') {
      return result;
    } else {
      return { cancelled: true };
    }
  } catch (e) {
    return { error: true };
  }
}
const result = await signInWithGoogleAsync(expoGoogleConfig)
// result.accessToken holds google's access token
```

- **So, how to get a JWT from your own server?** Following this thread, you can create a new authentication strategy that uses Google's accessToken to obtain a JWT from your server! The typical strategies (jwt, local), don't accept Google's tokens for auth, so you need to make a new strategy.
- The way to do it, is to add `"google"` as an auth strategy, and then use the new auth strategy to get your feathers server JWT. (It turns out the `google` and `facebook` auth strategies are built in... I'm guessing it's supported through the `passport` or `grant` library.)
```json
"authentication": {
    "entity": "user",
    "service": "users",
    "secret": "....",
    "authStrategies": [
      "jwt",
      "local",
      "google"
    ],
    ...
}
```

```javascript
app.authenticate({
  strategy: 'google',
  access_token: result.accessToken  // google access token from above
}).then((authResult) => {
  console.log('logged in to our feathers server', authResult) // hooray!
}).catch(e => {
  console.error('Authentication error', e);
});
```

Voila!
