### ISSUE TITLE
Revoking all the tokens belonging to a user

### ISSUE THREAD

**Issue by apmcodes** [feathersjs/feathers#1985]
Have implemented the revokable accessToken (using redis) as per the cookbook docs and its working fine. 

When a user gets disabled/ deleted, trying to revoke that user's all the existing tokens (across devices). To avoid storing/ managing all the accessTokens userwise, have implemented blacklisting the disabled userId in redis (for the jwt expiresIn period, so existing accessToneks will expire on its own). So now, along with verifyAccessToken I also need to do a lookup if the user is blackilisted to be able to successfully authenticate. 

Issue: AFTER verifyAccessToken, I need the userId that just got authenticated to do the user blacklist lookup. Is there a method or place after/ during verifyAccessToken where the user entity is available in the authentication service? (tried getPayload but that is not being called on every request from the frontend)

Appreciate any input. 

```
node -v
v12.18.0

feathers -V
4.3.0

```

**Comment by daffl** [comment]
You can also customize the [`authenticate`](https://docs.feathersjs.com/api/authentication/jwt.html#authenticate-data-params) where the payload is available after calling `super.authenticate`:

```js
const { AuthenticationService, JWTStrategy } = require('@feathersjs/authentication');

class MyJwtStrategy extends JWTStrategy {
  async authenticate (data, params) {
    const result = await super.authenticate(data, params);
    // do things here
    return result;
  }
}
```
