### ISSUE TITLE
Issue using single JWT on multiple socket connections

### ISSUE THREAD

**Issue by ericuldall** [feathersjs/feathers#1986]
I'm building a companion app for a product that we own and we're looking to have the user be automatically signed into the product ( a chrome extension ) after they login on the web app. Right now I have that working. When a user logs in on the web app, we send the accessToken over messaging to the chrome extension where it runs a jwt authentication workflow with `socket.emit('create', 'authentication', ...)`. So, that's great the user is logged in on all products in sync. 

The problem arises when I try to log the user out. This should work similarly. However, it seems the problem here is there is a unique socket connection opened using the same JWT from two places and after the jwt is invalidated in one place, the call the `socket.emit('remove', 'authenticateion',...)` results in a 401 auth error, I'm assuming because that token is now invalid.

The problem is that now I have my extension permenantly connected to the socket server and still able to query for protected information and no way to log out.

I'm still not 100% sure how/why this is happening and I've been running lots of different scenarios to try to figure this out. Has anyone else experienced something similar to this or see a potential solution?

Here's the snippet of code below that manages the automated login from my extension background script:

```
const socket = io('http://localhost:3030');
const API = feathers();
API.configure(feathers.socketio(socket));
socket.on('connect', () => {
    chrome.storage.sync.get(['apiAccessToken'], res => {
        if (res.apiAccessToken) {
            socket.emit('create', 'authentication', {
                strategy: 'jwt',
                accessToken: res.apiAccessToken
            }, () => sendStyles());
        }
    });
    chrome.storage.onChanged.addListener((changes, area) => {
        if (area === 'sync' && changes.hasOwnProperty('apiAccessToken')) {
            if (changes.apiAccessToken.newValue) {
                window.localStorage.setItem('feathers-jwt', changes.apiAccessToken.newValue);
                socket.emit('create', 'authentication', {
                    strategy: 'jwt',
                    accessToken: changes.apiAccessToken.newValue
                });
            }
        }
    });
  // receive login credentials when user logs in on our whitelisted web app
    chrome.runtime.onMessageExternal.addListener((req, sender, sendResponse) => {
        if (req.auth) {
            // create new token for our extension only
            socket.emit('create', 'authentication', {
                strategy: 'local',
                email: req.auth.email,
                password: req.auth.password
            }, (err, { accessToken }) => {
                chrome.storage.sync.set({ apiAccessToken: accessToken });
            });
        }
    });
});
```

Any help is appreciated.

**Comment by daffl** [comment]
The token can be used as long as it is valid. If you do not want to allow the token to be continued to be used you need to implement the [Revoking JWT](https://docs.feathersjs.com/cookbook/authentication/revoke-jwt.html) mechanism.

**Comment by ericuldall** [comment]
Hi @daffl,

I think that may solve my problem, but it doesn't address the exact issue.

In a chrome extension the client (popup) and the background scripts share a local storage. So when one is logged in, that token is available and both can authenticate, however they each run a separate socket server. So the problem seems to be when I logout from my extension popup the token is removed from local storage, and when my background script gets the message to log off the socket server it no longer has a token to send with the request, so that second connections stays open.

I'll try invalidating the jwt and hopefully any future requests on that socket will go too, but if you have any ideas about the root problem it would be great to get a deeper understanding or some new ideas on how that can be addressed. 

Thanks!

**Comment by ericuldall** [comment]
I've decided to go about this a slightly different way which also works, by being a bit more explicit in my handling of connections. Since a logged out user doesn't need a socket connection I'm disconnecting the socket server completely in the background when a users logs out, then reconnecting at login. This achieves the desired end result...even though it doesn't address the issue on the other scenario..hopefully I won't lose too much sleep over it :D
