### ISSUE TITLE
How can I edit the data sent back to user in a Feathers Hook?

### ISSUE THREAD

**Issue by coderinblack08** [feathersjs/feathers#1990]
I was trying to implement something similar to what feathers-authentication-hooks does but more customized towards my application.

I have a schools model that contains an array called members which then contains the id of the valid members of a school. I only want them to be able to have access to see the school, can anyone help me with implementation (before get/find/update/...)? Thanks in advance 🙏.

**Comment by jnardone** [comment]
In an after hook you can change the data about to be sent back to the user in `context.result`
