### ISSUE TITLE
query $and and $or don't work when multiple are used (provider: rest)

### ISSUE THREAD

**Issue by H3r3zy** [feathersjs/feathers#1992]
I use feathers in one of my project and I encountred a problem.

When the $or or the $and operator is not in the first place of query (with rest provider), the parser does not work.

here is my query:
<img src="https://i.imgur.com/P6Fe4jw.png" />

### Expected behavior
I expect to have this in ctx.params.query:
Like you can see after, the from is always in bracket and not parsed

```js
$and: [
 {
  effects: {
   $elemMatch: {
      characteristic: 11,
      $or: [{from: 21}, {from: 400} ],
    },
  },
 },
...
]
```

### Actual behavior
```js
$and: [
 {
  effects: {
   '$elemMatch': {
      characteristic: '11',
      '$or': [ { '[from]': '21' }, { '[from]': '30' } ],
    },
  },
 },
 ...
]
```
### System configuration

**Module versions** (especially the part that's not working):
"@feathersjs/authentication": "^4.5.3",
"@feathersjs/authentication-local": "^4.5.4",
"@feathersjs/authentication-oauth": "^4.5.4",
"@feathersjs/configuration": "^4.5.3",
"@feathersjs/errors": "^4.5.3",
"@feathersjs/express": "^4.5.4",
"@feathersjs/feathers": "^4.5.3",
"@feathersjs/transport-commons": "^4.5.3",

**NodeJS version**:
12.17.0

**Operating System**:
WSL

**Comment by H3r3zy** [comment]
I fixed it temporarly by browsing the whole object ctx.params.query and rename the key with '['

```js
function removeBracketInKeysOfObject(object) {
  if (!object || Array.isArray(object)) {
    return;
  }

  for (let key of Object.keys(object)) {
    if (key.indexOf('[') !== -1) {
      const newKey = key.slice(1, -1);
      object[newKey] = object[key];
      delete object[key];
    }

    if (Array.isArray(object[key])) {
      for (let sub of object[key]) {
        if (object[key] instanceof Object) {
          removeBracketInKeysOfObject(sub);
        }
      }
    } else if (object[key] instanceof Object) {
      removeBracketInKeysOfObject(object[key]);
    }
  }
}
```

**Comment by robbyphillips** [comment]
Feathers uses `qs` (https://github.com/ljharb/qs) to parse query strings.  By default it has a depth limit of 5.

It looks like you can override this with `app.set('query parser', ...)`

https://docs.feathersjs.com/api/express.html#params-query
