### ISSUE TITLE
Access body in remove() method

### ISSUE THREAD

**Issue by ericuldall** [feathersjs/feathers#1994]
Is it possible to access data in a remove() method?

I notice the method accepts `(id, params)` is it possible to use data?
I have a use case where a DELETE also sends extra meta data about the request for metrics.

Example:
```
remove (id, data, params) {
  console.log(data.foo);
}
```

```
curl -XDELETE -d '{"foo": "bar"}` localhost:3000/{service}/{id}
```

**Comment by ericuldall** [comment]
Couldn't find any concrete documentation on this. RFC spec doesn't seem very verbose on the topic and express supports data passed in the DELETE method. So I think it would make sense to allow as much in feathers.

For now I'm doing this:
```
app.use((req, res, next) => {
  if (req.method === 'DELETE') {
    req.feathers.data = req.body;
  }
});
```

Then I just access `params.data`. However it would be nice to keep the api consistent in implementation. I'm interested in what the official position is on this for feathers.

**Comment by bwgjoseph** [comment]
By default, `remove` does not need to pass in any `body` since it's a __remove__

You can use things like `paramsFromClient`, `paramsForServer` to pass things from client to server with additional data. If you would like to get the actual data of the `id` you are going to remove, you can perform a `.get(id)` using before hook and you should be able to get the data you want.

**Comment by ericuldall** [comment]
Hi @bwgjoseph 

My question was not whether or not body is required but, if it would be well received to officially support it. As of now, the remove request does not behave similarly to a POST or PUT which allows users to pass data in the body of the request.

Thanks for the reply.

**Comment by bwgjoseph** [comment]
Hi @ericuldall,

Thanks for the clarification.

For certain use-case, I do certainly agree on supporting `body` in request.

**Comment by daffl** [comment]
Similar to #1375 I would recommend to either use the middleware you showed or use the custom methods from #1976
