### ISSUE TITLE
Only one service hook working at a time.

### ISSUE THREAD

**Issue by irohitb** [feathersjs/feathers#1996]
### Steps to reproduce

- [Clone this git repo](https://github.com/irohitb/featherjs-pos)
- npm run start 

This repo contains [two services](https://github.com/irohitb/featherjs-pos/tree/master/src/services)
- customers 
- orders 

The service which is defined at last only seem to give response back (in postman) whereas the service which is defined before (or at first) gets stuck on loading in postman i.e 

In the code below, `app.configure(orders);` would give a response in postman where `app.configure(customers);` won't give any and keep on loading 

```
import { Application } from "../declarations";
import orders from "./orders/orders.service";
import customers from "./customers/customers.service";
// Don't remove this comment. It's needed to format import lines nicely.

export default function (app: Application) {
  app.configure(customers);
  app.configure(orders);
}
```

If I reverse the order i.e 
```
export default function (app: Application) {
  app.configure(orders);
  app.configure(customers);
}
```
`customers` will give response whereas `orders` won't

Ps: They aren't any logs/errors in console as well. 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/32276134/85213875-cf66df00-b381-11ea-8a1d-a4f4c4618b9b.gif)

### Expected behavior
Should have returned the response

### System configuration

Tell us about the applicable parts of your setup.

**NodeJS version**:
v14.4.0

**Operating System**:
MacOS 10.15.3

**Comment by bwgjoseph** [comment]
Look at `customers.model.ts`, you defined your model name wrongly.

It should be `customers` instead of `products`. That should solve it.
