### ISSUE TITLE
feathersjs.com domain name expired

### ISSUE THREAD

**Issue by Baira** [feathersjs/feathers#1997]
Hello,

I just checked `feathersjs.com` website to see some documentation and noticed that the domain name apparently expired.
![Capture](https://user-images.githubusercontent.com/5349435/85223858-921c4480-b3b5-11ea-99ca-93aafd2396cc.png)

**Comment by J3m5** [comment]
It's back up apparently.

**Comment by RobinKuiper** [comment]
Still down for me, someone forgot to pay ;)

**Comment by J3m5** [comment]
https://vuex.feathersjs.com/ is up again on my side

**Comment by homeranil** [comment]
+1

**Comment by RobinKuiper** [comment]
> https://vuex.feathersjs.com/ is up again on my side

hm, everything still down here.

**Comment by 6lackknight** [comment]
same here, @J3m5 it's probably just your DNS cache saving you. It's down on my side including and ESPECIALLY docs.feathers.com lol

**Comment by RobinKuiper** [comment]
I get a 403 forbidden now.

**Comment by jurajpiar** [comment]
As a temp solution see the github repo: https://github.com/feathersjs/docs/tree/master/api

**Comment by daffl** [comment]
This is now fixed. Sorry about that.
