### ISSUE TITLE
Authenticating with a third party API. 

### ISSUE THREAD

**Issue by Jasperosity** [feathersjs/feathers#1998]
Sorry if this is a RTFM type of question -- and it's not really an issue but I don't know where else to ask & I've been on this for days and I'm failing to see how I can achieve this, even after reading the docs. 
I'm wanting to authenticate users using another API. All I need the user to do is pass me their phone number I send it to the API, the API sends them a sms code they send me the code, I send it the API, the API sends me a user object, I look up the user in the database, create the user if necessary, and repackage the user object before sending it back to the user, with a JWT.

I have successfully been able to get the user authenticated via the 3rd party API, but I can't figure out how I could use the returning user object to authenticate them with feathers. 

I'm not asking for anyone to write the strategy for me, But I would greatly appreciate some direction.

**Comment by asamolion** [comment]
Okay so feathers supports multiple authentication strategies and you can write a custom strategy to suit your specific use case.

If you take a look at how `authentication-local` is implemented.

https://github.com/feathersjs/feathers/blob/master/packages/authentication-local/src/strategy.ts

You will see that it exports and `authenticate` method which does the real magic. The local strategy uses the local database but you can write similar code that uses an external API.

You can start implementing a custom strategy by extending the [AuthenticationBaseStrategy](https://github.com/feathersjs/feathers/blob/a12a1cf8c286b623817078e8b611223c173b04ee/packages/authentication/src/strategy.ts#L4) and take it from there.
