### ISSUE TITLE
Hook context param entity has unexpected redacted credentials

### ISSUE THREAD

**Issue by nsainaney** [feathersjs/feathers#1999]
https://github.com/feathersjs/feathers/blob/a12a1cf8c286b623817078e8b611223c173b04ee/packages/authentication/src/jwt.ts#L133

Should be:

```
const value = await this.getEntity(entityId, omit(params, 'provider'));
```

Shouldn't this omit the provider? I am redacting some private keys from the user record when provider is set and because of this, context.params.[entity].credentials is redacted even for internal use.

**Comment by daffl** [comment]
It should not because if the provider is passed it is the entity that is passed to the client once they log in.

**Comment by nsainaney** [comment]
Am I correct that this is the same entity at context.params[entity]? If not, where is that loaded?

I guess if that's the case, we can do a second internal request for sensitive user credentials. Thanks

Thanks.

**Comment by daffl** [comment]
That should already happen in `getEntity` at https://github.com/feathersjs/feathers/blob/a12a1cf8c286b623817078e8b611223c173b04ee/packages/authentication/src/jwt.ts#L97-L103 but you can also [customize it](https://docs.feathersjs.com/api/authentication/jwt.html#customization) in case you need anything else.
