### ISSUE TITLE
feathers service declaration

### ISSUE THREAD

**Issue by bwgjoseph** [feathersjs/feathers#2005]
Hi,

By default, when generating a new service (Post) using `feathers-cli` will result in this interface declaration.

```ts
// Add this service to the service type index
declare module '../../declarations' {
  interface ServiceTypes {
    'post': Post & ServiceAddons<any>;
  }
}
```

Doing so, will not give us the `overload` type that is defined.. so we lose the overload methods declaration..

Made a small tweak to include interface for it, to illustrate it better

```ts
interface PostInterface {
  title: string;
  message: string;
}

// Add this service to the service type index
declare module '../../declarations' {
  interface ServiceTypes {
    'post': Post & ServiceAddons<PostInterface>;
  }
}
```

![image](https://user-images.githubusercontent.com/37484538/86539046-51333c80-bf2c-11ea-962d-609d9bab52a2.png)

Notice that, it does not provide the `overload` methods by default as shown in the image above. 

Now, if we were to declare as such..

```ts
// Add this service to the service type index
declare module '../../declarations' {
  interface ServiceTypes {
    'post': Post & ServiceOverloads<PostInterface> & ServiceAddons<PostInterface>;
  }
}
```

![image](https://user-images.githubusercontent.com/37484538/86539075-83449e80-bf2c-11ea-8076-eaf77e386538.png)

IDE will be able to pick up the correct overload types and display as such (shown in the image above)

So I thought that the default, should as such instead of `Post & ServiceAddons<PostInterface>`

To add-on, I'm not sure if there's actually any difference between declaring

```ts
// this
declare module '../../declarations' {
  interface ServiceTypes {
    'post': Post & ServiceOverloads<PostInterface> & ServiceAddons<PostInterface>;
  }
}

// and this
declare module '../../declarations' {
  interface ServiceTypes {
    'post': Post & Service<PostInterface>;
  }
}
```

Since that `Service` is defined as such `type Service<T> = ServiceOverloads<T> & ServiceAddons<T> & ServiceMethods<T>;`

---

So my proposal, is to switch from using

`'post': Post & ServiceAddons<PostInterface>;`

to 

~~`'post': Post & Service<PostInterface>;`~~
`'post': Service<PostInterface> & Post;`

update: and because of the way it's defined, the order matters (due to overloading?, or intersecting types?), if define `Post & Service<PostInterface>`, it will not "see" the `ServiceOverloads<T>` first. Which will cause this to happen.

note: the interface is different but the idea remains.

![image](https://user-images.githubusercontent.com/37484538/87851442-5d0aff80-c92b-11ea-8953-18c0d982e96e.png)

![image](https://user-images.githubusercontent.com/37484538/87851445-6eeca280-c92b-11ea-83b0-f134e9ff2eb8.png)

I would have to cast manually - `.create(data) as PostInterface`

But if the definition is switched to `'post': Post & Service<PostInterface>;` It knows it is a single item, and therefore, used the correct overload method and return, without the need to cast.

![image](https://user-images.githubusercontent.com/37484538/87851486-c2f78700-c92b-11ea-8408-2376c110d264.png)

![image](https://user-images.githubusercontent.com/37484538/87851491-cc80ef00-c92b-11ea-8b86-c84c5360d9e8.png)

---

The line to change is probably this 

https://github.com/feathersjs/generator-feathers/blob/5212ac5ac26d72242abd8aa1072c376821bc8756/generators/service/templates/ts/service.ts#L11

If this is alright, I can create a PR for that. Let me know what you think of it.

**Comment by MauriceArikoglu** [comment]
Interesting improvement. Bump
