### ISSUE TITLE
Nested route issue with radix-router

### ISSUE THREAD

**Issue by nsainaney** [feathersjs/feathers#2006]
### Steps to reproduce

I believe I found out what causes #670

1. Create a route e.g. `/organizations`
1. Create a nested route e.g `/organizations/:orgId/people`
1. Perform a REST call to `/organizations`, `/organizations/xyz`, `/organizations/xyz/people` everything works fine
1. Perform a Socket call to `/organizations/xyz/people` - the request goes to `/organizations/xyz` and not `/organizations/xyz/people`

In the radix-router, `function _findNode(path, rootNode)` loops through all the nodes in the router. In the above, the nodes tree looks like so:

+-- organization
|----+-- :__id
|----+-- :orgId
|--------+-- people

When doing a lookup, `/organizations/xyz/people`, radix matches the `__id` node (even though it should match `:orgId/people`

### Expected behavior
The router should match the `:orgId/people` node and not the `:__id` node

### Solutions
Create the following routes instead:
```
/organizations
/organizations/:__id/people
```

which creates a proper node tree within radix:
+-- organization
|---+-- :__id
|-------+-- people

The danger here is that :__id is undocumented and may change in the future. Is this ok? The above does not affect the REST transport, just socketio.

**Comment by daffl** [comment]
I guess this would be another reason to have our own internal Radix-tree router implementation (the other one would be Deno compatibility).
