### ISSUE TITLE
Issue authenticating user via JWT when users service requires query params

### ISSUE THREAD

**Issue by flyboarder** [feathersjs/feathers#2007]
### Copied from Slack Convo
the authenticate hook cannot function as is when the db requires query params to correctly lookup the user entity during authentication, which is a common case for hosted mongodb databases which require a shard-key (specifically when using Azure CosmosDB)

### Expected
Using `authenticate("JWT")` hook successfully authenticates user.

### Actual
Authenticate hook fails with db error, `No record found for id ***`.

**Comment by flyboarder** [comment]
I think the best solution would be a small whitelist option to the authenticate hook, which could filter query params instead of dropping them entirely

**Comment by flyboarder** [comment]
Issue still exists with 4.5.6 - as the `getEntity` now removes the query parameters preventing user lookup.

A whitelist of approved query parameters is still required to correctly lookup users. This could be added to the JWT auth config.

**Comment by daffl** [comment]
To visualize the problem 😄 

![download](https://user-images.githubusercontent.com/338316/87271250-89d09a00-c487-11ea-98b9-a0fd4d0432d2.gif)

I think the strategy should have a `getEntityQuery` like [local auth](https://docs.feathersjs.com/api/authentication/local.html#getentityquery-query-params) already does. I think that might cover everything we need.

**Comment by flyboarder** [comment]
@daffl please review #2013 as a solution
