### ISSUE TITLE
zsh: command not found: feathers

### ISSUE THREAD

**Issue by PenningtonStuart** [feathersjs/feathers#2014]
### Steps to reproduce
Downloaded feathers CLI on a mac running catalina 10.15.3 via

npm install @feathersjs/cli -g

no problems noted there. 
made sure npm and node are installed and are above the minimum required version.
They both are installed and running properly.
I make a directory and swap to it. 
Then I run 

feathers generate app

and I receive this as a response

zsh: command not found: feathers

After this failure, I attempted to force the command as such

npm install -g @feathersjs/cli --force

This resulted in the same as before the "zsh: command....."

### Expected behavior
The CLI did not generate the app nor take me through any of the prompt

### Actual behavior
Tell us what happens instead

### System configuration

Tell us about the applicable parts of your setup.

**NodeJS version**:
12.18.2
**Operating System**:
Mac OS Catalina 10.15.3
**React Native Version**:
6.14.5
**Module Loader**:

**Comment by asamolion** [comment]
Can you see if the global node_modules `bin` folder is added to the ZSH path or not? 

Zsh scans a list of directories from the `PATH` environment variable to get a list of binaries to run. most likely the folder that contains the feathers executable is not in your OS's PATH variable.

**Comment by PenningtonStuart** [comment]
I am unaware of how to accomplish what you have asked, I have tried multiple things.
