### ISSUE TITLE
@types/express as dependency in @feathersjs/express

### ISSUE THREAD

**Issue by PowerMogli** [feathersjs/feathers#2019]
Why is @types/express a dependency in @feathersjs/express? This leads now to some typescript/build issues because of wrong/mismatched typescript definitions in the last version of @feathersjs.

Please fix the type definitions. It is mainly caused by a type "query" in the type definitions within @types/express.

![image](https://user-images.githubusercontent.com/5623081/87824838-55d5ea00-c876-11ea-8250-ca5d38f3d9fb.png)

**Comment by daffl** [comment]
First, please make sure all your dependencies are up to date. If there are still issues, please provide a repository e.g. based on [feathers-chat-ts](https://github.com/feathersjs/feathers-chat-ts) to reproduce the issue.

**Comment by daffl** [comment]
Closing since I haven't heard back and not able to reproduce.
