### ISSUE TITLE
Multiple Socket Clients?

### ISSUE THREAD

**Issue by corepay** [feathersjs/feathers#2020]
Is it possible to connect multiple socket clients from a feathers server?  Trying to break apart app into microserver environment.

The docs describe REST multiple servers but nothing on socket. 

https://docs.feathersjs.com/api/client/rest.html#connecting-to-multiple-servers 

### Expected behavior

Connect multiple socket clients from a feathers server

### Actual behavior

`Error: Only one default client provider can be configured`

### Addendum

So I actually got step one of my Feathers microservices working well by isolating an authentication server/service using sockets.  

FYI for anyone trying this and all comments welcome from experienced folks who see danger in my future.

**Server 1 Auth Server** 

* Normal CLI setup with authentication enabled (`users`)
* Added new service for `tokens` that will allow token lookup 
  * I have Redis and some logic in app.js `login` event to create token:
```
app.on('login', (result, { req }) => {
  result.accessToken_expires = config.get('authentication').jwtOptions.expiresIn,
  result.refreshToken = uuid(),
  redisClient.set(result.user.id, JSON.stringify(result));
  redisClient.expire(result.user.id, config.get('authentication').jwtOptions.expiresIn);
  if(req) {
    console.log('REQ', req);
  }
  console.log('LOGIN RESULT!', result);
});
```

Server 2 Customer Server

* Normal CLI setup without authentication enabled
* CLI create new service `Customers` with authentication creates `/customers` endpoint and allows me to connect to db
* Added feathers client and socketio packages
* Created the following files in the `services` folder
![image](https://user-images.githubusercontent.com/48992923/87828404-d8e14b00-c84a-11ea-8f32-5cc91275709b.png)
* The hooks files are boilerplate hook files
* The auth_server.service.js looks as follows:
```js
//  auth_server.service.js

const userHooks = require('./users.hooks');
const authHooks = require('./auth.hooks');
const tokenHooks = require('./tokens.hooks');

const keys = require('../../keys');  // env var file with auth server url and port
const authEndpoint = `${keys.authServerUrl}:${keys.authServerPort}`;

const socketClient = require('@feathersjs/socketio-client');
const io = require('socket.io-client');

const authServer = io(authEndpoint);

module.exports = function (app) {
  
  // setup auth server
  const AuthServer = app.configure(socketClient(authServer));
  app.use('/users', AuthServer.service('users'));
  app.use('/auth', AuthServer.service('auth'));
  app.use('/tokens', AuthServer.service('tokens'));

  // Get our initialized service so that we can register hooks
  const authService = app.service('auth');
  const tokenService = app.service('tokens');
  const userService = app.service('users');

  userService.hooks(userHooks);
  authService.hooks(authHooks);
  tokenService.hooks(tokenHooks);
};
```

Now with the auth server running and customer server running I can use the auth server services as endpoints on my customer server and leverage the customer server hooks before/after/error on these endpoints.

Auth Server:  http://localhost:3030/auth
Customer Server: http://localhost:3031/auth

Auth Server:  http://localhost:3030/users
Customer Server: http://localhost:3031/users

Auth Server:  http://localhost:3030/tokens
Customer Server: http://localhost:3031/tokens

Now I am working on how to add another service / server to the mix.  I have an `'invoice` server that uses the same pattern and socket connection to the authentication server, but getting errors telling me socket can only have one client when I try to add the invoice server to the customer server so I can access the invoices through the customer server -> example: `http://localhost:3031/invoices`.

The objective is to have all of my apps operate independently on a single database but also can be plugins to other apps when needed.  If familiar with Elixir trying to accomplish something like an 'umbrella app'.  

Anybody have ideas here on how to connect to multiple servers through multiple socket clients on a single server?

**Comment by daffl** [comment]
This is currently not possible. Since websocket connections are not stateless they require _a lot_ more work than just passing a header to make sure authentication is established and kept active (e.g. on reconnection). You can instantiate multiple different Feathers apps with different socket connections though.

**Comment by corepay** [comment]
ok - so...I suppose I'll change server-server to rest and just treat them as a 3rd party api with jwt.  this repo has some ideas to validate server to server:  https://github.com/avanzu/feathers-microservice-sandbox

I'm storing the user data and access token, expire and refresh token in Redis after a `logon` event on auth server.  When customer server receives request with accessToken it will decode the JWT then query Redis for the user.id - so essentially the user is valid.  I may just disallow endpoints to other servers unless the accessToken and user is validated in Redis.  I'll keep the auth server `create.user` and `authentication` path open for users that are not validated so they can login.  That might work.

...or maybe I am just making things very complicated...

**Comment by daffl** [comment]
One way to pass a stateless token to a socket just like for an HTTP connection would be to add it to the query e.g. as an `accessToken` query parameter, then take it out and set it as `params.authentication`:

```js
const setAuthentication = context => {
  const { accessToken, ...query } = context.params.query || {};

  if (accessToken) {
    context.params.authentication = {
      strategy: 'jwt',
      accessToken
    };
    context.params.query = query;
  }
  
  return context;
}
```

**Comment by corepay** [comment]
@daffl yes thank you.  I actually ended up doing this but with a lot more fat than you provided here.  thank you for clarity.
