### ISSUE TITLE
Can't get context.params.user

### ISSUE THREAD

**Issue by coderinblack08** [feathersjs/feathers#2021]
### The Problem
* Sorry that I didn't follow the template, in a hurry and also because its just a syntax question
I am calling a create on a service from an after hooking of a service. But I can't access the context.params.user. I've seen a similar issue somewhere but I think its cause I called it internally (context.app.service)... here is my code
``` js
after: {
  create: [
      async context => {
        try {
          const result = await context.app.service('members').create({
            code: context.result.code
          });
        } catch (error) {
          console.error(error);
        }
        return context;
      }
    ],
}
```

The problem occurs when I try to call context.params in members service hook

``` js
before: {
  create: [
    async context => {
      // ....
      console.log(context.params.user);
      return context;
     }
  ]
}
```

**Comment by daffl** [comment]
When you call a method internally (e.g. in a hook) `params` will be what you pass to it. If you need the user you need to pass it along (also see the guide at https://docs.feathersjs.com/guides/basics/hooks.html#populate-the-message-sender):

```js
after: {
  create: [
      async context => {
        try {
          const result = await context.app.service('members').create({
            code: context.result.code
          }, context.params); // or { user: context.params.user }
        } catch (error) {
          console.error(error);
        }
        return context;
      }
    ],
}
```
