### ISSUE TITLE
Would we have a web GUI dashboard to manage database schemas and REST api in a code less way?

### ISSUE THREAD

**Issue by ruojianll** [feathersjs/feathers#2022]
Feature request.
Would we have a web GUI dashboard to manage database schemas and REST api in a code less way? That will help front end developers to speed up their SPA prototype developing.

Is there a place for feature requests? Please tell me and I will take this request to the correct place.

**Comment by daffl** [comment]
Hi @ruojianll. As previously discussed in #271 this is a feature that is not within the scope of Feathers itself. Have a look at [awesome-feathersjs](https://github.com/feathersjs/awesome-feathersjs) for integrations from the community, e.g. the [React admin or Admin on Rest integrations](https://github.com/feathersjs/awesome-feathersjs#react-admin). Feathers has also been reported to work with [Forest Admin](https://www.forestadmin.com/).

**Comment by ruojianll** [comment]
Hi @daffl. How about it going with Forest Admin?

**Comment by daffl** [comment]
I don't know. It appears they removed all existing examples and GitHub issues so you'd have to contact them to get more information.

**Comment by frastlin** [comment]
I think it is a major con of Feathers that it does not have an Admin Dashboard that it works with by default and that builds a view based on the model file in Feathers, similar to Django.
It's expensive to integrate an Admin dashboard, even one like React Admin, especially with foreign relationships.
It takes 2 hours or so to create one CRUD view on a React Admin service, and that time really adds up. What was the reasoning behind not creating an integrated admin dashboard?

**Comment by daffl** [comment]
Honest question, what would you be willing to pay for something like that? 25$/month? 750+$ one-time for a license? Given the complexity and work required this is simply not something that can (or in my opinion should) be done as an open source project. Some other projects might be trying to pull that right now using their millions of dollars of VC funding but that's not really going to be sustainable in the long term either.

**Comment by frastlin** [comment]
[Django Admin](https://docs.djangoproject.com/en/3.2/ref/contrib/admin/) has built a very nice dashboard.
I'm not aware of other JS frameworks Admin Dashboard functionality out of the box, but almost every project could use an admin dashboard.
I would even be happy if only the most basic functionality was created by default. Most tables just have simple types.
To your question though, a developer spent about a week implementing this feature into our specific application, so between $2000-$5500. Paying for React Admin though does not give you the CRUD tables by default, you still need to build them, which is the cost I'm talking about here.
Django is the only example I have, but their CRUD generates the admin dashboard from your model declarations, which removes that cost for Django for basic tables.
I love Feather's modularity, but defaults are critically important for users who just want something to work, and if they need anything special or advanced, then they'll build it. It's the same for Feathers itself. I would use Feathers Client as an example. I don't need to use Feathers Client, I could use React Query or axios. Django does not have a Feathers client for SPAs, so this is a major competitive advantage for Feathers, even though I could pay a developer to build a Feathers-style client for Django.
An admin dashboard is no different.

**Comment by J3m5** [comment]
[API Platform has built an admin dashboard with React admin](https://api-platform.com/docs/admin/) but all the CRUD tables and views are automatically discovered and rendered thanks to the HATOAS specification formats that are supported by their [api-doc-parser library](https://github.com/api-platform/api-doc-parser).

The result is not perfect but it's there and can certainly be reused with another rest server that support the same API formats.
