### ISSUE TITLE
Cannot read property 'bind' of undefined, on a service

### ISSUE THREAD

**Issue by HoekWax** [feathersjs/feathers#2023]
### Steps to reproduce

Hello, the issue happen in my react native project when I try to interact with my feathers server using a feathers client.
FYI, the feathers client works very well on my web client

### Expected behavior

I want to be able to login with the client and user services from the client like this
```
var user = await client.service("users").get(USER_ID");
```

Here is my initialization of the client
```

const socket = io(SERVER_ENDPOINT);
const client = feathers();
client.configure(
    socketio(socket, {
        timeout: 15000,
    }),
);

const fOptions = {
    header: "Authorization", // the default authorization header for REST
    prefix: "", // if set will add a prefix to the header value. for example if prefix was 'JWT' then the header would be 'Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOi...'
    path: "/authentication", // the server-side authentication service path
    jwtStrategy: "jwt", // the name of the JWT authentication strategy
    entity: "user", // the entity you are authenticating (ie. a users)
    service: "users", // the service to look up the entity
    // cookie: "TOKEN-jwt", // the name of the cookie to parse the JWT from when cookies are enabled server side
    storageKey: "TOKEN-jwt", // the key to store the accessToken in localstorage or AsyncStorage on React Native
    storage: AsyncStorage,
};

client.configure(auth(fOptions));

// Then I try to login or use the service for example
const result = await client.authenticate({
        strategy: "local",
        email,
        password,
});
```

### Actual behavior

I get the following error : "Cannot read property 'bind' of undefined"
I managed to track down the issue [to this line](https://github.com/feathersjs/feathers/blob/f4a9538f56736d5e971502b23511b79081407d53/packages/feathers/lib/hooks/index.js#L164)

I'm using version 4.5.6 of feathers

Do you know if this is an issue in my initialization of the client or something else ?

Thanks

**Comment by daffl** [comment]
We're using that version with React Native and am not seeing any issues. I'd verify that you have the latest or a more recent React Native and also try with the Feathers individual imports and the Feathers client to see if that makes a difference.

**Comment by HoekWax** [comment]
I tried on a brand new project and it worked like a charm, I don't really know what's happening on my main project.
I leave the issue open for now in case I find the solution but i might juste create a new project and copy everything from my main project.

**Comment by HoekWax** [comment]
I've checked on iOS and I don't have this issue, only on android.

There is something esle you can maybe help me with, it's to be authenticated using socketio to the server.
Basically i do this

```
    const result = await client.authenticate({
      strategy: "local",
      email: "email",
      password: "password",
    });

    const { accessToken } = await client.get("authentication");

    var test = await client.service("users").get("5d0ceea010055c00124084d7");
```

The client.authenticate works well, the value for accessToken is the right one, but when I use the service to get a user, the server return "No auth token".

Do you know why that happens ? I've check on the server and context.params.token is undefined, so the hooks authenticate('jwt') can't work.

**Comment by HoekWax** [comment]
If I use version 3.2.1, like on another project of mine where everything works, the get from the service works, because the authentication on the server works. I guess there was a change in the more recent version of feathers and context.params.token doesn't contain the token anymore.

I can I use authenticate('jwt') with the more recent version ?

Thanks for your time.

**Comment by HoekWax** [comment]
About the original issue, I finally figured out where it came from, it's because I had Hermes enabled on the project.

I just disabled it and I don't get this issue anymore.

**Comment by HoekWax** [comment]
The issue about authenticate('jwt') indeed came from a compatibility issue, the version of feathers on the server was too old for the more recent one.

**Comment by FranciscoCHT** [comment]
This issue shouldn' t be closed :(, several apps use Hermes to improve performance and size. Is there any workaround to use Hermes with Feathers Client?
