### ISSUE TITLE
Question regarding oauth access tokens

### ISSUE THREAD

**Issue by smparsons** [feathersjs/feathers#2024]
Hello,

I have a feathers API where I've implemented authentication using oauth. I notice that after authenticating with the third party, feathers will generate its own access token and return it to the client.

What I would like to do is instead of feathers generating an access token, I would like to utilize the access token that was issued to me by the third party. I would like to return this third party access token to the client. And then, when future API requests are made that require authorization, I would like to call some kind of custom hook that will verify that the third-party access token is valid (this third-party API has an endpoint that I can call to validate the access token).

I want to do this because my app also needs to make HTTP requests to the third-party api that require authorization, which will require me to pass the third-party access token. Because of this, I need to store the third-party access token on the client, and I would prefer to not have to work with two different access tokens.

I've been searching through the docs but haven't found an obvious way to do this. What would be the best way to approach this type of problem? Currently I'm trying to override the authenticate function in OAuthStrategy like this:

```
class FooStrategy extends OAuthStrategy {
  ...
  async authenticate(authentication: AuthenticationRequest, originalParams: Params) {
    const result = await super.authenticate(authentication, originalParams);
    return {
      ...result,
      accessToken: authentication.access_token
    }
}
```

I do this because I noticed that the service that calls authenticate won't generate an access token if it finds a field `accessToken` in the response object that is returned from `authenticate`. It also seems like the built-in authenticate hook calls this authenticate function as well, so I suppose I could add the logic to validate the third-party access token in this function as well?

Is there anything obvious I'm missing? Is there a much easier way to do this, or am I on the right track? I ask because I'm not super familiar with this library so any help would be appreciated.

Thanks!

**Comment by smparsons** [comment]
Nevermind, I think I understand what I need to do

**Comment by corepay** [comment]
@smparsons 

> Nevermind, I think I understand what I need to do...

Don't leave us hanging with a teaser like that bro, how about a tip?  I have similar use case and want to use/pass the validated oauth token to Feathers that is used as the access_token in my clients (using feathers vuex).

**Comment by smparsons** [comment]
@corepay Sure, I'll describe the approach that I took, I don't know if this is the best way to solve the problem but it worked for me. I wasted a ton of time trying to figure out how to get this right, so if it helps others save some time then I'm willing to help.

So you'll want to extend `OAuthStrategy`, and override the [authenticate](https://github.com/feathersjs/feathers/blob/83e2f6bb3f6372f8ed859a5e64650c7e7482a68c/packages/authentication-oauth/src/strategy.ts#L148) function. In order to pass your third party access token to the client, you need to return the third party access token from your `authenticate` function like this:

```
    async authenticate(
        authentication: AuthenticationRequest,
        originalParams: Params
    ) {
        ...
        return {
            accessToken: myThirdPartyAccessToken,
            authentication: ...,
            [entity]: ...,
        };
    }
```

It's important that the key name in the object is exactly `accessToken`, otherwise [the feathers authentication service that calls your strategy will make its own JWT access token](https://github.com/feathersjs/feathers/blob/83e2f6bb3f6372f8ed859a5e64650c7e7482a68c/packages/authentication/src/service.ts#L102).

You'll then need to do a couple things to make sure that feathers utilizes your custom authentication strategy. First, you'll need to register your strategy:

```
export default function (app: Application): void {
    const authentication = new AuthenticationService(app);

    authentication.register("foo", new FooStrategy());

    app.use("/authentication", authentication);
    app.configure(expressOauth());
}
```

You'll also need to specify it as your auth strategy in your config file:

```
    "authentication": {
        ...
        "authStrategies": ["foo"],
        ...
    },
```

And then of course pass your strategy name everywhere you use the authenticate hook, like this:

```
export default {
    before: {
        all: [authenticate("foo")],
        find: [],
        get: [],
        create: [],
        update: [],
        patch: [],
        remove: [],
    },
    ...
};
```
On the client side, you need to make sure you pass your custom strategy name to the auth client:
```
client.configure(
    auth({
        ...
        jwtStrategy: "foo",
        ...
    })
);
```

Now for my specific use case, I have an endpoint in my third party api that I call to validate that my access token is still valid. Inside `authenticate` in my custom oauth authentication strategy, I make sure that I call this endpoint. If you use my above approach, `authenticate` in your custom oauth strategy will be called every time an endpoint in your API is called that requires authorization, so you'll probably also want to add logic to prevent `this.getProfile`, `this.createEntity`, and `this.updateEntity` from getting called each time your service needs to authorize a client calling your API.

Oh, and if you're using REST, you'll need to provide a `parse` function so that you can parse the access token from the Authorization header ([here's an example of the parse function from the feathers JWT strategy](https://github.com/feathersjs/feathers/blob/83e2f6bb3f6372f8ed859a5e64650c7e7482a68c/packages/authentication/src/jwt.ts#L148)). If you're using websockets you'll need to provide a `handleConnection` function that's customized to your own needs ([here's an example of the handleConnection function from the feathers JWT strategy](https://github.com/feathersjs/feathers/blob/83e2f6bb3f6372f8ed859a5e64650c7e7482a68c/packages/authentication/src/jwt.ts#L32)).

That was a little tricky to explain so hopefully that all made sense.

**Comment by corepay** [comment]
Thank you @smparsons for the lengthy explanation.  Had a deadline and took a twist but am launching a new feathers servers to see if I can work through this.  Really appreciate your help here!

**Comment by bitflower** [comment]
Thanks for sharing your solution!

**Comment by PieterHartzer** [comment]
For what it's worth, here is how I solved it:

```
export class MicrosoftExtendedStrategy extends OAuthStrategy {
    async getProfile(authResult) {
        const accessToken = authResult.access_token
        // Use the token here (to get the photo and add it to the profile)
        return authResult.profile
    }
}  
```
