### ISSUE TITLE
How to log the message which is send from server to client over websocket on the server?

### ISSUE THREAD

**Issue by alinex** [feathersjs/feathers#2030]
I can listen on the events on the server to log an incomming call, but how do i log the responding message to the client.

I know that i can get it by setting DEBUG=* but how can i get this event within my code?

**Comment by daffl** [comment]
[Application level hooks](https://docs.feathersjs.com/api/hooks.html#application-hooks) are a great place to add logging. To make it conditional to the provider use [params.provider](https://docs.feathersjs.com/api/services.html#params):

```js
const log = context => {
  if (context.params.provider === 'socketio') {
    console.log('Sending socket message', context);
  }
}

app.hooks({
  after: {
    all: log
  },
  error: {
    all: log
  }
})
```

You can also see the socket messages in the network tab in the browser:

<img width="1276" alt="Screen Shot 2020-08-03 at 12 10 51 PM" src="https://user-images.githubusercontent.com/338316/89218167-6da1b380-d582-11ea-819b-62d9a099b081.png">
