### ISSUE TITLE
@feathersjs/adapter-commons still on v.4.5.2 

### ISSUE THREAD

**Issue by mariusheine** [feathersjs/feathers#2032]
Is there any reason why @feathersjs/adapter-commons is still available as v.4.5.2 on npm and yarn?

Everything else is already available with higher versions.

**Comment by daffl** [comment]
Yes. It has been moved to https://github.com/feathersjs/databases and not changed since that version.

**Comment by mariusheine** [comment]
Ok this causes some unconventional side-effects (at least in my opinion). Because we get 2 different sources for all @feathersjs/errors, @feathersjs/commons and @feathersjs/feathers.

Do have any idea how to get rid of this or any plan when to update adapter-commons?

**Comment by daffl** [comment]
I can make a new release but I'm not seeing the problem you are mentioning. The acceptable version dependency ranges should still match the latest version and get de-duped (example from one of our projects):

<img width="369" alt="Screen Shot 2020-08-08 at 5 50 47 PM" src="https://user-images.githubusercontent.com/338316/89722557-cb2d6a00-d99f-11ea-9bfe-0c4335115999.png">

**Comment by mariusheine** [comment]
Ok yes might work in your situation because you probably don't have adapter-commons as a direct dependency.

In our config we have 

```
"dependencies": {
    ...
    "@feathersjs/adapter-commons": "^4.5.2",
    "@feathersjs/configuration": "^4.5.7",
    "@feathersjs/errors": "^4.5.7",
    "@feathersjs/express": "^4.5.7",
    "@feathersjs/feathers": "^4.5.7",
    "@feathersjs/socketio": "^4.5.7",
    "@feathersjs/transport-commons": "^4.5.7",
    ...
}
```

And this results in 
![grafik](https://user-images.githubusercontent.com/42845535/89837011-56f1f280-db68-11ea-866a-a017c7820134.png)
where commons, errors and feathers inside adapter-commons are on version 4.5.2 while the ones in the "top" level are on 4.5.7.

We use yarn with workspaces.

I can provide you a simple repo to reproduce things, if you want to?

Thx already for your patience and help 😄

**Comment by mariusheine** [comment]
Ok i just gave it another tiny research and found out, that this is fixed at least in the current yarn version.

Obiously yarn was calculating the dependencies not "good" enoguh. 

We were on yarn-1.18.0 and now we use yarn-1.21.1.

Thx anyway

**Comment by daffl** [comment]
Great, thanks for the update. I'll probably get a new version out soon anyway but they will digress more as time goes on. It just made way more sense to keep this module together wit some of the actual adapters.
