### ISSUE TITLE
Unregistering services at runtime

### ISSUE THREAD

**Issue by cuddeford** [feathersjs/feathers#2035]
Our organisation is using Feathers as our primary server and are deep into the development of a microservice written with Feathers that connects to our primary. We expose our primary Feathers services to the microservice and use it as a gatekeeper for a particular type of client. We do this by registering all the discovered services as local whenever a connection is established between the primary server and the microservice.

The problem that we've just discovered is that `app.use(serviceName, service)` doesn't overwrite an existing service of the same name, it actually increases the number of events in the socket.io instance. Ideally registering a service with the same name multiple times would destroy the existing one and create a new one.

Without this functionality it makes our (arguably not niche) use case impossible without incurring an inevitable increase in memory whenever the remote server reconnects. Yes, we can check if the service already exists and only register it if it doesn't. But if the central server removes a Feathers service there'd be no way to remove it from the microservice.

#446 floated this idea but it never gained any traction, with the most recent reply in 2018.
In #1200 it was mentioned that this functionality is still not possible, in 2019.

Is this something the Feathers team has on their roadmap?
Is there an unofficial way that this can be handled by manually clearing the references to the events in memory or similar?

**Comment by daffl** [comment]
The problem with unregistering services isn't Socket.io (the legacy event handlers will be removed in the next version anyway), it's that Express does not allow to unregister middleware.

Overwriting a service should work though (since the service is retrieved dynamically at call-time) so this might indeed be an issue.

**Comment by steffanhalv** [comment]
@marshallswain said you discussed to add `app.service(‘users’, null)`into Dove a month ago in the Slack channel. Has this been implemented yet and does it mean featersjs will support unregistering services this way @daffl?
