### ISSUE TITLE
Authenticating user on server side stopped working

### ISSUE THREAD

**Issue by apmcodes** [feathersjs/feathers#2037]
Earlier, on new user creation was able to login the user on the server side, so that in frontend the user doesn't have to login as below. 

**user addition hook**
```
            return context.app.service('authentication').create({
                payload: {
                    userId: context.data.user.id,
                }
            }, {
                user: context.data.user
            })

```
But, now it stopped working (may be after all featherjs module update)

Have tried the below but still dones't work

**getting "Invalid login"**
context.data.user.password contains encrypted password
```
return context.app.service('authentication').create({
                strategy: "local",
                email: context.data.user.email,
                password: context.data.user.password,
            }, context.params)
```
**getting "Invalid authentication information (no `strategy` set)"**
```
            return context.app.service('authentication').create({}, {
                payload: { userId: context.data.user.id }
            })
```

### System configuration

```
    "@feathersjs/authentication": "^4.5.2",
    "@feathersjs/authentication-local": "^4.5.2",
    "@feathersjs/authentication-oauth": "^4.5.2",
    "@feathersjs/cli": "^4.3.0",
    "@feathersjs/configuration": "^4.5.2",
    "@feathersjs/errors": "^4.5.2",
    "@feathersjs/express": "^4.5.2",
    "@feathersjs/feathers": "^4.5.2",
    "@feathersjs/socketio": "^4.5.2",
```

**Comment by apmcodes** [comment]
After spending some good amount of time, seems theres no straight forward way to login user on the user side (without plain password). Would like to know if this is true to keep my quest at rest :) 

#1764

**Comment by daffl** [comment]
To create a token for a user internally you'd use [authService.createAccessToken](https://docs.feathersjs.com/api/authentication/service.html#createaccesstoken-payload) with the default options returned from [getTokenOptions](https://docs.feathersjs.com/api/authentication/service.html#gettokenoptions-authresult-params):

```js
const payload = {};
const jwtOptions = await app.service('authentication').getTokenOptions({
  user // or other entity
}, params); // `params` or `{}`
const jwt = await app.service('authentication').createAccessToken(payload, jwtOptions);
```

In general, this should however be done automatically by a using an existing or custom [authentication strategy](https://docs.feathersjs.com/api/authentication/strategy.html).

**Comment by apmcodes** [comment]
That works. Thank you very much. 

On user activation we wanted to login the user from the server side so that they do not need to login in the front end.
