### ISSUE TITLE
Polymer element for data sync with feather 

### ISSUE THREAD

**Issue by wuyuanyi135** [feathersjs/feathers#204]
Hi, 
I am using Polymer to build my front end. I wonder if there is any plan to implement a element like [\<firebase-element\>](https://elements.polymer-project.org/elements/firebase-element?active=firebase-collection). If not yet, I may try to build one.

**Comment by marshallswain** [comment]
Cool! I'm pretty sure you are the first one with the idea.  Let us know if you need help while you're working on it.

**Comment by ekryski** [comment]
@wuyuanyi135 did you make any headway here?

**Comment by daffl** [comment]
If so we can create a new repository here and give you access. Either way, we probably want to close this issue.

**Comment by wuyuanyi135** [comment]
Well, I just push my code to https://github.com/wuyuanyi135/feathers-element 
This element implements very basic realtime CRUD operations. I may have to add more features later on
