### ISSUE TITLE
Pass context.data while testing services

### ISSUE THREAD

**Issue by thealpha93** [feathersjs/feathers#2045]
### Steps to reproduce

- [ ] While testing a service to remove an user, I encountered an error in one of the hooks that says cannot access `role of undefined`. Undefined is context.data. I undestand that there's a way to mock `context.params`. But Is there a way to mock `context.data`?. I'm using mocha with assert. Is there any other alternative?
- [ ] This is my test
```
it('should remove an user', async () => {
    const params = {
      user,
      query: {},
    }

    await app.service('users').remove(user1._id, params)
  });
```

This is what it looks like in my hook

```
if (user.role !== 'admin') {
      context.data.role = user.role
    }
```

### Expected behavior
The test should remove the user and succeed

### Actual behavior
The tests breaks and gives me an error saying cannot access `role` of undefined.

### System configuration

Tell us about the applicable parts of your setup.

**NodeJS version**: 12.16.3

**Operating System**: Ubuntu 20.0

**Comment by daffl** [comment]
There is no `context.data` in `remove`. It [only exists in the `create`, `patch` and `update` methods](https://docs.feathersjs.com/api/hooks.html#context-data).

**Comment by thealpha93** [comment]
Then how do I pass context.data in create, patch and update methods while testing services? Also how do I pass custom params?

**Comment by daffl** [comment]
See the [Service API documentation](https://docs.feathersjs.com/api/services.html).
