### ISSUE TITLE
authentication does not trigger login event

### ISSUE THREAD

**Issue by bwgjoseph** [feathersjs/feathers#2046]
As mentioned in the [docs](https://docs.feathersjs.com/api/authentication/service.html#create-data-params), posting to `/authentication` should trigger a login event emitted. However, it doesn't seem like so in my test.

You can take a look at this [feathers-login-event](https://github.com/bwgjoseph/feathers-login-event) repo  
This is a newly generated app, with only the following changes

1. src/authentication.ts

```js
// added this following
app.on('login', (_authResult: any) => {
    console.log('hello world');
  });
```

2. test/authentication.test.ts

```js
it.only('should trigger app.login event', async () => {
      const { user, accessToken } = await app.service('authentication').create({
        strategy: 'local',
        ...userInfo
      }, { provider: 'rest' });

      // doesn't trigger app.login event
    });
```

Run `npm run mocha` and the expected result should be printing `hello world` but it doesn't. Having the `provider` or not doesn't matter.

Thanks!

**Comment by daffl** [comment]
I forgot to mention that those events only get sent after `app.setup()` has been called.

**Comment by bwgjoseph** [comment]
Hi @daffl, I don't quite follow what you mean by that? Where should I set it up/configure in my test to get it work? How do I trigger `app.setup` to get called?

Any sample would be great!

**Comment by daffl** [comment]
The event handlers are only set up when `app.setup` (or `app.listen`) is called.

```js
it.only('should trigger app.login event', async () => {
  app.setup();
  
  const loginEvent = new Promise(resolve => app.once('login', resolve));
  const { user, accessToken } = await app.service('authentication').create({
    strategy: 'local',
    ...userInfo
  }, { provider: 'rest' });

  console.log(await loginEvent);
});
```

**Comment by bwgjoseph** [comment]
Thanks @daffl 

I got it working on the sample app, but I'm facing some weird issue getting it to work correctly in my actual app.

If you could help to see if I'm missing anything would be appreciated.

note: `app.on('login')` is in `src/authentication.ts`

The flow is that in `app.on('login')`, I would call a `token` service to create some data. So in my test, I would expect something like

```js
it.only('should trigger app.login event', async () => {
  app.setup();

  const { user, accessToken } = await app.service('authentication').create({
	strategy: 'local',
	...userInfo
  }, { provider: 'test' });

  console.log(await app.service('token').find()); < should have data

  // in my actual app, token.find would return empty data but my db actually has the data
});
```

Thing is that, the events are trigger from the `app.on('login')` event, my data is created and is stored in the db, but when I perform a find in the test, it finds nothing.

But somehow, if I perform a find twice, the second time will have result.

```js
it.only('should trigger app.login event', async () => {
  app.setup();

  const { user, accessToken } = await app.service('authentication').create({
	strategy: 'local',
	...userInfo
  }, { provider: 'test' });

  console.log(await app.service('token').find()); < no data
  console.log(await app.service('token').find()); < has data
});
```

I have no clue why is this happening, and I am not sure what else I should be looking out for at the moment. I am not able to reproduce the same behavior in the sample repo.

I have also updated my [repo](https://github.com/bwgjoseph/feathers-login-event) to show the updated sample code.

Thank you very much

**Comment by daffl** [comment]
Keep in mind that all of those operations are asynchronous. You have to wait for the event just like I showed in my previous code sample:

```js
it.only('should trigger app.login event', async () => {
  app.setup();

  const { user, accessToken } = await app.service('authentication').create({
	strategy: 'local',
	...userInfo
  }, { provider: 'test' });
  const tokenEvent = new Promise(resolve => app.service('token').once('created', resolve));

  console.log(await tokenEvent);
});
```

**Comment by bwgjoseph** [comment]
Yes, I understand that it's all asynchronous operations (maybe I don't quite get it totally) but I don't quite understand why in the multiple sample app that I've created have no issues doing this and getting the data, but in my actual app it doesn't work.

```js
// the sample app code

it.only('should trigger app.login event', async () => {
  app.setup();

  const { user, accessToken } = await app.service('authentication').create({
	strategy: 'local',
	...userInfo
  }, { provider: 'test' });

  console.log(await app.service('token').find()); < always able to find the data created from app.login in sample app but doesn't work in my actual app
});
```

I think I'm missing something obvious

---

ah! Is it because that `app.on('login')` event is already asynchronous so no matter whether I have `awaited` (for the token to be created) inside of the `app.on('login')`, it doesn't matter. Hence, I need to manually wait for it to resolve like you mentioned using `new Promise` then `await` it...

**Comment by bwgjoseph** [comment]
I think it's working fine now, with some minor issue where data is not cleared between test case although I had explicitly made it to.
Will check it out myself first, and it's not relevant to this as well.

Thank you for your help @daffl !
