### ISSUE TITLE
on lasest version feathers / socket have problem with  app.service("messages").on()' client side nothing see

### ISSUE THREAD

**Issue by andysay** [feathersjs/feathers#2047]
hello, i have some problem with my app 

i use last v nuxtjs and feathersjs

my plugin featheres 

```import feathers from "@feathersjs/feathers";
import socketio from "@feathersjs/socketio-client";
import auth from "@feathersjs/authentication-client";
import rest from "@feathersjs/rest-client";
import axios from "axios";

import io from "socket.io-client";

import { CookieStorage } from "cookie-storage";
import { iff, discard } from "feathers-hooks-common";

import feathersVuex, { initAuth, hydrateApi } from "feathers-vuex";

let socket;
let restClient;
//export const host = process.env.baseUrl

//import storage from '../helpers/ssr-storage';
//const storage = new CookieStorage();
//const socket = io(process.env.baseUrl);

if (process.client) {
  socket = io(process.env.baseUrl, { transports: ["websocket"] });
} else {
  restClient = rest(process.env.baseUrl);
}
const transport = process.client ? socketio(socket) : restClient.axios(axios);
const storage = new CookieStorage();

const feathersClient = feathers()
  .configure(transport)
  .configure(auth({ storage }))
  .hooks({
    before: {
      all: [
        iff(
          (context) => ["create", "update", "patch"].includes(context.method),
          discard("__id", "__isTemp")
        ),
      ],
    },
  });

export default feathersClient;

// Setup feathers-vuex
const {
  makeServicePlugin,
  makeAuthPlugin,
  BaseModel,
  models,

  FeathersVuex,
} = feathersVuex(feathersClient, {
  serverAlias: "api", // or whatever that makes sense for your project
  idField: "email", // `id` and `_id` are both supported, so this is only necessary if you're using something else.

  enableEvents: process.client, // Prevent memory leak
});

export {
  makeAuthPlugin,
  makeServicePlugin,
  BaseModel,
  models,
  FeathersVuex,
  initAuth,
  hydrateApi,
};
```
import feathers from "@feathersjs/feathers";
import socketio from "@feathersjs/socketio-client";
import io from "socket.io-client";

 app.configure(socketio(socket));

    console.log(app.service("messages"));

 i recive 

<img width="556" alt=" 2020-08-27 - 11 43 46" src="https://user-images.githubusercontent.com/5610952/91418577-feef0780-e85a-11ea-985b-ab1eddd875c5.png">

    app.service("messages").on("created", (message) => {

      console.log(message); // nothing recive ;

 }

i debug console server side

  const service = app.service("messages");

  service.on("created", (message, context) => console.log("created", message));

 after create message server answer 

created {
 createdAt: '27-08-2020',
  catygories: [ 'test' ],
}

and  on client side 

// UPD

 socket.emit("find", "messages", (error, data) => {
      console.log("Found all messages", data);
    });
    app.configure(socketio(socket));
    const debug = (text) =>
      console.debug(`${new Date().toISOString()}: ${text}`);

    socket.on("connect", () => {
      debug("Connected");
    });

i have 

<img width="307" alt="Снимок экрана 2020-08-27 в 12 03 27" src="https://user-images.githubusercontent.com/5610952/91420433-63ab6180-e85d-11ea-8f86-65aea0587ef3.png">

so why     

app.service("messages").on("created", (message) => {

      console.log(message); // nothing recive ;

 }
not working ?

**Comment by daffl** [comment]
In a generated application [users need to be authenticated](https://docs.feathersjs.com/guides/basics/authentication.html#browser-authentication) in order to see any events.

**Comment by andysay** [comment]
> In a generated application [users need to be authenticated](https://docs.feathersjs.com/guides/basics/authentication.html#browser-authentication) in order to see any events.

for guests no solution ?

**Comment by daffl** [comment]
Yes. This is described in the [API documentation on channels](https://docs.feathersjs.com/api/channels.html).

**Comment by andysay** [comment]
> Yes. This is described in the [API documentation on channels](https://docs.feathersjs.com/api/channels.html).

  app.service("messages").publish("created", () => app.channel("anonymous"));
 works fine , thanks!
