### ISSUE TITLE
Cannot remove item from mongodb

### ISSUE THREAD

**Issue by coderinblack08** [feathersjs/feathers#2050]
Extended from issue: https://github.com/feathersjs/feathers/issues/2044

## Error Message
```bash
Unhandled run time error
NotFound: No record found for id
```

## Client Code 
``` ts
const getStar = await $store.dispatch('stars/find', {
	query: {
		contest_id: $route.params.id,
		user_id: $store.state.auth.user._id,
	},
});
 await $store.dispatch('stars/remove', getStar.data[0]._id);
```

## Backend hook
``` ts
import { ObjectID } from 'mongodb';

// my before remove hook
async (context: any): Promise<any> => {
	context.id = new ObjectID(context.id);
	console.log(context);
	return context;
},
```

## My thoughts

<img width="674" alt="Screen Shot 2020-08-28 at 4 03 38 PM" src="https://user-images.githubusercontent.com/41022901/91621508-18ba4880-e948-11ea-877a-f7da02634f2c.png">

It seems that the query _id and the id property are different... I don't think this is the problem because the id property is the correct id and it is anything this:

<img width="404" alt="Screen Shot 2020-08-28 at 4 05 04 PM" src="https://user-images.githubusercontent.com/41022901/91621558-3e475200-e948-11ea-9170-b9a40afc0902.png">

Resources looked at https://docs.feathersjs.com/help/faq.html#why-should-i-use-feathers, https://github.com/feathersjs-ecosystem/feathers-mongodb#querying

**Comment by coderinblack08** [comment]
<img width="674" alt="Screen Shot 2020-08-28 at 4 03 38 PM" src="https://user-images.githubusercontent.com/41022901/91621508-18ba4880-e948-11ea-877a-f7da02634f2c.png">

It seems that the query _id and the id property are different... I don't think this is the problem because the id property is the correct id and it is anything this:

<img width="404" alt="Screen Shot 2020-08-28 at 4 05 04 PM" src="https://user-images.githubusercontent.com/41022901/91621558-3e475200-e948-11ea-9170-b9a40afc0902.png">

**Comment by marshallswain** [comment]
Have you tried converting the id to an object ID?

**Comment by coderinblack08** [comment]
yes, that is what the hook is supposed to do :)

**Comment by marshallswain** [comment]
Sorry.  I missed the hook on my first read.

**Comment by marshallswain** [comment]
I recommend setting a debugger or breakpoint in the `remove` method of `feathers-mongodb` and see what's actually making it into the adapter.

**Comment by coderinblack08** [comment]
I'm not quite familiar with the vscode debugging tool, may you elaborate or provide a working example if possible? That would be awesome.

**Comment by coderinblack08** [comment]
It seems that the error says id, not _id? Is this a problem?

**Comment by coderinblack08** [comment]
```ts
import { NullableId, Params } from '@feathersjs/feathers';
import { Service, MongooseServiceOptions } from 'feathers-mongoose';
import { model } from 'mongoose';
import { Application } from '../../declarations';

export class Stars extends Service {
  //eslint-disable-next-line @typescript-eslint/no-unused-vars
  constructor(options: Partial<MongooseServiceOptions>, app: Application) {
    super(options);
  }
  async remove(id: NullableId, params: Params) {
    const removedStar = await model('stars').deleteOne({ _id: id });
    return removedStar;
  }
}
```
I overwrote the service, it seems like a hack, is there a better way?

**Comment by marshallswain** [comment]
The better way is for it to just work, but we don't know why it's not working in your case. This override should work just fine.

**Comment by SmartArray** [comment]
Interestingly we are experiencing the same issue with NeDB. Investigations are running...

**Comment by SmartArray** [comment]
I don't think this is the case with your MongoDB driver, but I stumbled across something interesting. So this is for reference purposes only:

The package `@feathers-nedb` expands the deletion request to this NeDB query:
$and: [ { undefined: 'StiJfdsHlnNtkqNX' } ]

Of course it won't find a document with this query.

**EDIT:** Please check if that's the case for you too by placing a console.log after this line: https://github.com/feathersjs-ecosystem/feathers-mongodb/blob/6bf168269f7cbb9f329cc8a530d5ee7677b645f7/lib/index.js#L46
