### ISSUE TITLE
using socketio, on logout: "NotAuthenticated: Invalid authentication information (no `strategy` set)" 

### ISSUE THREAD

**Issue by SharpBCD** [feathersjs/feathers#2052]
### context
I get:
Error in 'authentication' service method 'remove': NotAuthenticated: Invalid authentication information (no `strategy` set)

The weird part is that it appears only on server (linux, remote) and not on localhost.

After digging into and removing nginx, just to be sure, I have the following situation:
On server, the connection looks like this:
```
{
  provider: 'socketio',
  headers: {
    host: '34.....:3030',
    connection: 'Upgrade',
    pragma: 'no-cache',
    'cache-control': 'no-cache',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36',
    upgrade: 'websocket',
    origin: 'http://localhost:8080',
    'sec-websocket-version': '13',
    'accept-encoding': 'gzip, deflate',
    'accept-language': 'en-US,en;q=0.9,de-DE;q=0.8,de;q=0.7,ro-RO;q=0.6,ro;q=0.5',
    'sec-websocket-key': 'O9AyyV7+USP4fmDe7YiZVA==',
    'sec-websocket-extensions': 'permessage-deflate; client_max_window_bits'
  },
  socketId: 'oH91O0DyabH3uuwxAAAA',
  strategy: 'firebase_strategy',
  tokenExpirationTime: 1598732208,
  user: {
    id: 0,
    //... other user data. 
  }
}
```
it is stripped of 'authentication' and other properties.
On local server, the same console.log produce something like this:
``` {
  provider: 'socketio',
  headers: {
    host: 'localhost:3030',
    connection: 'Upgrade',
    pragma: 'no-cache',
    'cache-control': 'no-cache',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) ' +
      'AppleWebKit/537.36 (KHTML, like Gecko) ' +
      'Chrome/84.0.4147.135 Safari/537.36',
    upgrade: 'websocket',
    origin: 'http://localhost:8080',
    'sec-websocket-version': '13',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-US,en;q=0.9,de-DE;q=0.8,de;q=0.7,ro-RO;q=0.6,ro;q=0.5',
// NOTICE cookie
    cookie: 'accessToken=ey......',
    'sec-websocket-key': '25pyzksRO5tQ/MNVbwEs8Q==',
    'sec-websocket-extensions': 'permessage-deflate; client_max_window_bits'
  },
// NOTICE authentication
  authentication: {
    accessToken: 'eyJh ...',
    strategy: 'firebase_strategy',
    connectionInfo: { ip: '::1', device: [Object] }
  },
  strategy: 'firebase_strategy',
  tokenExpirationTime: 1598731148,
  user: {
    id: 0,
    //......
  },
  socketId: '8Mgd6dypr8hI6PGSAAAA'
}
```

I removed nginx, nothing changed. Server is identical with local. 

Not sure what else to try. CORS does not seem to be a problem. 

Any idea?

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
    "@feathersjs/authentication": "^4.5.8",
    "@feathersjs/authentication-local": "^4.5.8",
    "@feathersjs/authentication-oauth": "^4.5.8",
    "@feathersjs/configuration": "^4.5.8",
    "@feathersjs/errors": "^4.5.8",
    "@feathersjs/express": "^4.5.8",
    "@feathersjs/feathers": "^4.5.8",
    "@feathersjs/socketio": "^4.5.8",
    "@feathersjs/transport-commons": "^4.5.8",

**NodeJS version*12.8.3*:

**Operating System*windows, linux*:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by SeaDog505** [comment]
I had a similar problem with middleware after upgrade feathers to version 4.

In my middleware I added this:

```
app.use('/', cookieParser(), (req, res, next) => {

    var cookies = req.cookies;
    var token = cookies['feathers-jwt'];

    req.authentication = {
        strategy: 'jwt',
        accessToken: token
    }

    next();

})
```

and now authenticate function is working

`app.get('/', authenticate('jwt', { failureRedirect: '/login' }), async (req, res) => {});`

**Comment by SharpBCD** [comment]
I have a function `parse(req)` that does this but it is in the custom auth class (extends `AuthenticationBaseStrategy`). It is called only when a connection is established. I also save the IP and device info into connection.
Any idea this is woking on localhost and not on the production server? Maybe nginx is filtering something?

**Comment by SharpBCD** [comment]
After several testing I realized that the `authentication` property is removed from the `authenticate` function result. Any other info it's transferred into `connection` object. So I add it again in  `handleConnection` function and it works just fine.
Not sure why is this necessary but at least I solve it.
@SeaDog505  - you may want to try this as well.
