### ISSUE TITLE
cli for creation of a super user

### ISSUE THREAD

**Issue by gpietro** [feathersjs/feathers#2054]
### Current behaviour

Currently, correct me if wrong, when you want an [authentication system](https://docs.feathersjs.com/guides/basics/authentication.html#registering-a-user) you can register a new user with a POST /users request. This endpoint by default is not protected.
So the procedure, as far as I know, is to deploy the application without protection, create the admin user and then redeploy a new version of the application with the endpoint protected by jwt authorization through hook.

### Desired behavior
Did you already consider to add a cli to be able to create a super user as [Django](https://docs.djangoproject.com/en/3.1/ref/django-admin/#createsuperuser) does?

**Comment by J3m5** [comment]
What I do is manually inserting a user in the database.

**Comment by corepay** [comment]
Take a look at `https://github.com/TheSinding/authentication-api-key`.  I found it super easy and convenient to add a 'master key' api strategy for sys admins to bypasses auth.

**Comment by daffl** [comment]
Another option is to have a simple script that requires the app and creates the user (and other seeds):

```js
const app = require('./src/app');

(async () => {
  await app.service('users').create(superUser);
})();
```

Closing since this is not within the scope of the Feathers CLI.
