### ISSUE TITLE
type definition for update (multi)

### ISSUE THREAD

**Issue by bwgjoseph** [feathersjs/feathers#2055]
Hi,

According to the docs, [adapter.update](https://docs.feathersjs.com/api/databases/common.html#adapter-update-id-data-params) is defined as `Does not allow replacing multiple records (id can't be null). id can not be changed.`

However, in the typings, it is defined as such

https://github.com/feathersjs/feathers/blob/6de92b1c53453c421c59ebd1c6d58ea2908a3c5f/packages/feathers/index.d.ts#L249

However, the adapter implementation rejects `id === null` and will throws `BadRequest: You can not replace multiple instances. Did you mean 'patch'?` error message

From what I saw, the default implementation, mongodb, mongoose have something like this

![image](https://user-images.githubusercontent.com/37484538/92329496-5468b700-f09a-11ea-87c6-0ecbed1f2136.png)

Haven't gone through other database implementation. Is it that some does support `multi-update`? If not, then I can open a PR to remove the typings for `update? (id: null, data: T, params?: Params): Promise<T[]>; `

**Comment by daffl** [comment]
The general service interface is not the same as the database adapter interface and allows for `id` to be `null`. The database adapters [already only allow a normal id for update](https://github.com/feathersjs/databases/blob/master/packages/adapter-commons/src/service.ts#L178) when typed properly:

<img width="802" alt="Screen Shot 2020-09-08 at 9 49 11 PM" src="https://user-images.githubusercontent.com/338316/92555842-6d4da580-f21d-11ea-9e60-15bd4a3a20ca.png">

**Comment by bwgjoseph** [comment]
Ah, I see. Thanks for the clarification!
