### ISSUE TITLE
Google auth strategy not returning phone number and date of birth

### ISSUE THREAD

**Issue by thealpha93** [feathersjs/feathers#2068]
### Steps to reproduce

Reproduce the steps on the documentation to set up google auth. 

Add `'https://www.googleapis.com/auth/userinfo.profile',
          'https://www.googleapis.com/auth/user.phonenumbers.read'` to scopes

### Expected behavior
This should return the user's date of birth and phone number

### Actual behavior
It returns only
```
{
  sub: '********************',
  name: 'Aakash Tm',
  given_name: 'Aakash',
  family_name: 'Tm',
  picture: 'https://lh3.googleusercontent.com/a-/AOh14GhWl4xHunx76RJhh8nw-7Vfrg22EMKCMUYoETPlYg',
  locale: 'en-GB'
}```


### System configuration


**Module versions** (especially the part that's not working): "@feathersjs/authentication-oauth": "^4.5.7",

**NodeJS version**: 14

**Operating System**: Ubuntu

**Browser Version**: Brave 

**React Native Version**:

**Module Loader**:

**Comment by thealpha93** [comment]
How do I get the oauth access token sent by google?

**Comment by daffl** [comment]
By [customizing](https://docs.feathersjs.com/api/authentication/oauth.html#customization) the [getProfile](https://docs.feathersjs.com/api/authentication/oauth.html#getprofile-data-params) method.

**Comment by thealpha93** [comment]
Thanks. That helped :100:
