### ISSUE TITLE
@feathersjs/configuration env loading error

### ISSUE THREAD

**Issue by GaborTorma** [feathersjs/feathers#2075]
### Steps to reproduce

in the @feathersjs/configuration/src/index.ts file you replace the value from env based on value, not the name.

Wrong:
```
            if (process.env[value]) {
                value = process.env[value];
            }

```
Right:
```
            if (process.env[name]) {
                value = process.env[name];
            }

```

Context:
```
export default function init () {
  return (app?: Application) => {
    const convert = (current: any) => {
      const result: { [key: string]: any } = Array.isArray(current) ? [] : {};

      Object.keys(current).forEach(name => {
        let value = current[name];

        if (typeof value === 'object' && value !== null) {
          value = convert(value);
        }

        if (typeof value === 'string') {
          if (value.indexOf('\\') === 0) {
            value = value.replace('\\', '');
          } else {
==>         if (process.env[value]) {
==>           value = process.env[value];
            }
            if (value.indexOf('.') === 0 || value.indexOf('..') === 0) {
              // Make relative paths absolute
              value = path.resolve(
                path.join(config.util.getEnv('NODE_CONFIG_DIR')),
                value.replace(/\//g, separator)
              );
            }
          }
        }

        result[name] = value;
      });

      return result;
    };

    const env = config.util.getEnv('NODE_ENV');
    const conf = convert(config);

    if (!app) {
      return conf;
    }

    debug(`Initializing configuration for ${env} environment`);

    Object.keys(conf).forEach(name => {
      const value = conf[name];
      debug(`Setting ${name} configuration value to`, value);
      app!.set(name, value);
    });

    return conf;
  };
}

if (typeof module !== 'undefined') {
  module.exports = Object.assign(init, module.exports);
}

```

**Comment by daffl** [comment]
That code is supposed to replace the value with the environment variable. E.g. for

```
"port": "MY_PORT"
```

`app.get('port')` should be set to the value of the `MY_PORT` environment. What you are suggesting would replace it with environment variable value of `port`.

**Comment by GaborTorma** [comment]
Thanx, I understand, but this case very dangerous.
I seted some value in the config file to 'dev'. I only want to use it as a 'dev' string.
But when I use pm2 in production mode it set an ENV variable dev with an empty object.
Your converted my changed my 'dev' string value to empty object...

**Comment by daffl** [comment]
That is true and the reason why this behaviour will be removed in the next version (see https://github.com/feathersjs/feathers/issues/1895). For now it'd have to be escaped as `\\env`

**Comment by daffl** [comment]
This has been updated in v5.0.0-pre.1 which is now in beta testing. Latest prereleases can be installed via `@feathersjs/<packagename>@pre`, updating the version numbers of all `@feathersjs` packages to `^5.0.0-pre.1` or by running

```
npx ncu -u --newest
```

Upgrade instructions are continuously updated and can be found in the [v5 migration guide](https://dove.docs.feathersjs.com/guides/migrating.html).
