### ISSUE TITLE
Error "Cannot read property 'bind' of undefined"

### ISSUE THREAD

**Issue by FranciscoCHT** [feathersjs/feathers#2076]
Hello, the issue happens when trying to interact with a Feathers Server (authenticate service), from React-Native projects with FeathersClient/AuthenticationClient/SocketIOClient, and Hermes enabled on Android's build.gradle.
It seems that enable Hermes breaks the authentication. 

According to #2023, that has the same error, the solution was disable Hermes. Are there any workaround to this? or a solution? My project needs Hermes to improve performance and size :/ Thanks in advance!

### Steps to reproduce

- Use FeathersClient, with Authentication client.
- Enable Hermes on React-Native Android projects.
- Interact with a Feathers Server. On authenticate ('local' strategy), throws an error [TypeError: Cannot read property 'bind' of undefined]

### Expected behavior
Succesfully authenticate with Hermes enabled.

### Actual behavior
Throws an error [TypeError: Cannot read property 'bind' of undefined] when authenticate using "local" strategy.

### System configuration

@feathersjs/feathers: 4.5.8
@feathersjs/authentication-client: 4.5.8
@feathersjs/socketio-client: 4.5.8
**React Native Version**: 0.61.5

**Comment by daffl** [comment]
This should really be a Hermes issue because it's apparently somewhere breaking some standard expected behaviour that works in any other JavaScript engine (including a standard React Native setup). It might however also be solved in the upcoming v5 which will no longer rely on the Uberproto library (where the error is coming from).

**Comment by daffl** [comment]
The Uberproto library has been removed in #2178 which will be available in Feathers 5.

**Comment by KryptKode** [comment]
Feathers 5 is not stable for now. How can we use it on feathers 4? 
Can you direct on how to migrate from feathers 4 to feathers 5?

**Comment by daffl** [comment]
The upgrade steps are available in the [v5 migration guide](https://dove.docs.feathersjs.com/guides/migrating.html).

**Comment by angelo-hub** [comment]
is there a patch solution to this? v5 is still in development and doesn't have a stable release

**Comment by daffl** [comment]
v5 is out and official. You can see [the changelog here](https://github.com/feathersjs/feathers/blob/dove/CHANGELOG.md) and read the [release post here](https://blog.feathersjs.com/introducing-feathers-5-the-api-and-real-time-application-framework-101ae2deaaeb)

**Comment by silvestreh** [comment]
At a first glance, upgrading *just* the client to the latest 5.0.0 (backend API is still on 4.x) release solves this issue. 

I still haven't done a thorough test, but will report back if I find any issues.

@daffl would you expect anything to break in this scenario? (connecting to a Crow API using Dove client)

**Comment by daffl** [comment]
I don't think so since the protocol for both HTTP and Socket.io is still the same (just with added custom methods).
