### ISSUE TITLE
Using app.service() to do CRUD in other services suffers from the hook problems.

### ISSUE THREAD

**Issue by codyng** [feathersjs/feathers#2077]
When I called const b = app.service('B') inside the service A, and then called b.find(), b.get(), b.create(), etc
the service object suffers from the hooks of the service B. Those hooks affect here such as field sanitisation, checking permissions, etc.

I just want to simply do the CRUD in another service classes. Now I need to directly use sequelize API by accessing the Model object, which violates the purpose of Feathers Common API.

Using Common API internally seems suck. Does anyone teach me the correct way of this?

Thanks a lot.

**Comment by 8BallBomBom** [comment]
Have a look at [this](https://docs.feathersjs.com/guides/migrating.html#hook-less-service-methods), should do as ya need.

**Comment by daffl** [comment]
Yep, exactly that. I was wondering for a second if it got added to the docs which it also did indeed at https://docs.feathersjs.com/api/databases/common.html#methods-without-hooks

**Comment by codyng** [comment]
That's great! Thanks all!
