### ISSUE TITLE
failureRedirect: '/login' doesn't work

### ISSUE THREAD

**Issue by SeaDog505** [feathersjs/feathers#2078]
app.get('/', authenticate('jwt', { failureRedirect: '/login' }), async (req, res) => {
		
		const { user } = req;
		
		res.render('home', { name: user.firstName });
		
	});

In previously feathersjs version above code worked fine but after upgrade my app to version 4 I see 401 error - not Authorized. How can I redirect my clients to login page?

**Comment by SeaDog505** [comment]
any Ideas?

**Comment by daffl** [comment]
This has now been documented in https://docs.feathersjs.com/cookbook/express/view-engine.html

**Comment by SeaDog505** [comment]
I use socket.io to authentication my users. { failureRedirect: '/login' } it was convenient option. It is possible using socket.io with redirect to login page when token not exists?

**Comment by daffl** [comment]
Probably with a Socket.io middleware that parses the cookie but if you don't rely on server rendered views, I don't see much of a reason to do this instead of relying [on the client side mechanism Feathers already supports](https://docs.feathersjs.com/guides/basics/frontend.html).

**Comment by SeaDog505** [comment]
I use Express Handlebars to rendering pages so I want to check if token exists before render. Do you think that a better is to use a rest to users authentication with redirect to login page as shows a feathers documentation?
