### ISSUE TITLE
Can't exposing request properties

### ISSUE THREAD

**Issue by Nicolas469** [feathersjs/feathers#2079]
I'd like to exposing a request property to services and hooks, like we can see in the docs: https://docs.feathersjs.com/api/socketio.html#app-configure-socketio-callback

```
const feathers = require('@feathersjs/feathers');
const socketio = require('@feathersjs/socketio');

const app = feathers();

app.configure(socketio(function(io) {
  // Registering Socket.io middleware
  io.use(function (socket, next) {
    // Exposing a request property to services and hooks
    socket.feathers.referrer = socket.request.referrer;
    next();
  });
}));

app.listen(3030);
```

### Expected behavior
This should expose this property so it can be used later in services and hooks.
The goal is to archive something like #904.

### Actual behavior
The typescript compiler does not accept the assignment since feathers is not a porperty of SocketIO.Socket type.

`Property 'feathers' does not exist on type 'Socket'.`

**FeatherJS version**:
4.5.8

**NodeJS version**:
12.18.3

**Comment by daffl** [comment]
Looks like it hasn't been types so for now it'd have to be `(socket as any).feathers.referrer = socket.request.referrer;`
