### ISSUE TITLE
404 error on file upload guide

### ISSUE THREAD

**Issue by devops724-2** [feathersjs/feathers#2081]
### Steps to reproduce
open this link
https://github.com/feathersjs/docs/blob/master/guides/advanced/file-uploading.md

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/crow/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc. This makes it much easier for us to debug and issues that have a reproducable example will get higher priority.

### Expected behavior
show 200 ok with upload guide content :)
Tell us what should happen

### Actual behavior
Tell us what happens instead
showing 404 not found
### System configuration
any mobile or desktop browser
Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:
Any
**Operating System**:
Any
**Browser Version**:
Any
**React Native Version**:

**Module Loader**:

**Comment by daffl** [comment]
Mentioned [in this FAQ](https://docs.feathersjs.com/help/faq.html#i-always-get-a-404-for-my-custom-middleware) `app.use('/uploads', blobService({Model: blobStorage}));` _must_ be before 

```js
app.use(express.notFound());
app.use(express.errorHandler());
```
