### ISSUE TITLE
Cannot find name 'Location' in '@feathersjs/authentication-client/lib/core.d.ts'

### ISSUE THREAD

**Issue by ps73** [feathersjs/feathers#2083]
### Steps to reproduce

I'am using typedoc 0.19.2 for automating documentation of my classes and types.
When running `typedoc src/index.ts` I am getting the following error:

```
Using TypeScript 4.0.3 from /Users/**/Documents/**/node_modules/typescript/lib
Error: /Users/**/Documents/**/node_modules/@feathersjs/authentication-client/lib/core.d.ts(24)
Cannot find name 'Location'.
```

### Expected behavior
No error.

### Actual behavior
`Cannot find name 'Location'.`

### System configuration

**Module versions** (especially the part that's not working): @feathersjs/authentication-client 4.5.8

**NodeJS version**: 12.10.0

**Operating System**: macOS 10.15.5

**Comment by daffl** [comment]
This is a DOM global variable. If you changed the configuration from the default update `compilerOptions.lib` in `tsconfig.json` with

```json
{
  "compilerOptions": {
    "lib": [ "DOM" ]
  }
}
```
