### ISSUE TITLE
Signle Sign On with feathers and others node express js, how to do this ? Is possible ?

### ISSUE THREAD

**Issue by Dahkenangnon** [feathersjs/feathers#2084]
# What ?
I'm facing the same problem but with some difference:

# And ?
I have a feathers js app and and others express-node js app.
Now i want to have a sso authentication system for all these system.

# Architecture :woman_technologist: ?
Apps are like:

app1.domain.com
app2.domain.com
app3.domain.com
feathers.domain.com
I'm on a vps.

# Need your help please !
Do you have some suggestion or recommandation for me please ?
Can i use the Oauth of feathers ?
Because there are a miss of feathers and node js app, is this(sso)  possible ?

Thank very for time you spend to respond to this.

**Comment by daffl** [comment]
Since this is a rather general question, your best bet is probably https://auth0.com. There are docs on how to integrate it with Feathers in the Cookbook and probably more than a few tutorials on how to do this with Express.
