### ISSUE TITLE
Can i use feathers js client in nativescript-vue ?

### ISSUE THREAD

**Issue by Dahkenangnon** [feathersjs/feathers#2088]
Hi. This is not truly an issue but i just want to know if 
i can use feather js client in [nativescript ](https://nativescript.org/)vue mobile app.

If this can be done, what are requirements or any thing to known.
Thank for your reply

**Comment by daffl** [comment]
Feathers works in any JavaScript environment. Everything to know is documented in the [Feathers client API](https://docs.feathersjs.com/api/client.html).
