### ISSUE TITLE
Custom event not triggered from app js file

### ISSUE THREAD

**Issue by anuraggi** [feathersjs/feathers#2089]
App level custom events are not possible at the moment. You can `app.service('myservice').emit('customevent')` anywhere, not just in hooks.

_Originally posted by @daffl in https://github.com/feathersjs/feathers/issues/855#issuecomment-399687921_

As mentioned in the above mentioned code I should be able to fire custom events from anywhere in the repo. 

However I've written following code in my app.js file
`
changeStream.on('change', next => {
      const service = app.service('/companies');
      service.emit("hello", { status: 'completed' })
      console.log("\ndata after change\n", next, "\n"
})
`

but I'm not able to listen to this event on client side.
The console log in the last line is printed everytime in the server so I know that code is reaching there.
Above snippet is written at the bottom of my app.js file

And this is how I've initialized my service
`const options = {
    Model: createModel(app),
    paginate: app.get('paginate'),
    events: ["hello"]
  };

  // Initialize our service with any options it requires
  app.use('/companies', new Companies(options, app));
`

what am I doing wrong here?

**Comment by daffl** [comment]
I just confirmed that this setup works in the feathers-chat repository. If it does not, make sure that the custom event gets published properly in your `channels.js|ts` file.
