### ISSUE TITLE
How to 1) join relationship and 2) perform DB transaction with the Common API?

### ISSUE THREAD

**Issue by codyng** [feathersjs/feathers#2093]
Sorry, just the simple questions, which is very important to the DBMS projects.
I don't find any usage examples from the Doc.

Thanks!!!

**Comment by codyng** [comment]
For 1), I've just "Googled" and find the solution:

Just write a hook for the  before hook:

```
const SomeModel = app.service('somemodel').Model;
context.params.sequelize = {
    include: [{ model: SomeModel }]
};
```
However, the result of the JSON is flat but not as an object.
"somemodel.id": ".....",
"somemodel.name": ".....",
"somemodel.createdAt": "....."

Is it possible to make the result as an object?
```
"somemodel": {
    "id": "...",
    "name": "...",
    "createdAt": "..."
}
```
How about question 2)?

In my opinion, I think these two common usage should be introduced in the documentation, although it relies on Sequelize, or
extend the Common API interface.....

**Comment by daffl** [comment]
Each database adapter has their own documentation with a lot of that information, in your case in the readme of [feathers-sequelize](https://github.com/feathersjs-ecosystem/feathers-sequelize), specifically [associations](https://github.com/feathersjs-ecosystem/feathers-sequelize#associations) and [working with model instances](https://github.com/feathersjs-ecosystem/feathers-sequelize#working-with-sequelize-model-instances) section. To get models, set the `raw` option to `false`.
