### ISSUE TITLE
feathers generate app crashes 'unexpected empty function'

### ISSUE THREAD

**Issue by mrobst** [feathersjs/feathers#2094]
I'm using WSL2 (OpenSuse Leap15.2) but I don't think the issue is platform related. 

[2020-10-15T16_00_37_020Z-debug.log](https://github.com/feathersjs/feathers/files/5386284/2020-10-15T16_00_37_020Z-debug.log)

I ran this:
~bin/feathers_iot2> feathers generate app
? Do you want to use JavaScript or TypeScript? TypeScript
? Project name feathers-iot-2
? Description feathers and amqp
? What folder should the source files live in? src
? Which package manager are you using (has to be installed globally)? npm
? What type of API are you making? REST, Realtime via Socket.io
? Which testing framework do you prefer? Mocha + assert
? This app uses authentication No

This error is generated:
~bin/feathers_iot2/src/services/index.ts
  4:26  warning  'app' is defined but never used  @typescript-eslint/no-unused-vars
  4:50  error    Unexpected empty function        @typescript-eslint/no-empty-function

✖ 2 problems (1 error, 1 warning)

My guess is that the error occurs because I declined authentication so no users service gets created. If I run the same set of commands but say yes to authentication then the app is generated fine with the users service. Logging this as an issue so that the error condition could be handled more gracefully (e.g template empty custom service?) 

npm debug log is attached

**Comment by daffl** [comment]
I'm going to close this since the assumption is that your Feathers app has at least one service - otherwise you can always tell ESLint to ignore it. This may also become more customizable via https://github.com/feathersjs/cli/issues/253
