### ISSUE TITLE
Authentcated user that gets deleted making requestes error not found

### ISSUE THREAD

**Issue by axmad22** [feathersjs/feathers#2095]
### Steps to reproduce

This error was reported in [Strategy succeeds even if user is not found](https://github.com/feathersjs-ecosystem/authentication-jwt/issues/27) and its still exists. A user signed in gets deleted and his token not expired tries to access a resource protected with the hook authenticate('jwt') the app throws an errror **404 No record found for id '*****'.**

I tried creating a custom hook in place of authenticate  to manage this scenario, but am getting an error **before hook for 'get' method returned invalid hook object**. Am not sure why this is happening. Note am using this hook on the users service for the before =>all hook. 

``` js

module.exports = function customAuth() {
  return async cxt => {
    if (cxt.params.provider) {
      let user = cxt.params.user;
      if (user) {
        if (!user.enabled) {  // ignore block this just part of an application 
          const message = user.disabledMsg ? user.disabledMsg : 'Server.errors.defaultDisabledMsg';
          throw new errors.Forbidden(message);
        }
       // this part is failing even when there is a cxt.params.user it seems its trying make a user get request
        return await authenticate('jwt')({type: 'before', data: cxt.data, params: cxt.params, app: cxt.app});
      } else {
      // this way is wrong cause unsigned users will get the same message 
        throw new errors.Forbidden('Server.errors.accountDeleted');
      }
    }
    return cxt;
  };
};
```
Is there a point in the AuthenticationService, LocalStrategy or JWTStrategy to handle this case customize it like I have done here 
when users try to login and are disabled
``` js
class CustomLocalStrategy extends LocalStrategy {
  comparePassword(entity, password) {
    const result = super.comparePassword(entity, password);
    if (!entity.enabled) {
      const message = entity.disabledMsg ? entity.disabledMsg : 'Server.errors.defaultDisabledMsg';
      throw new errors.Forbidden(message);
    }
    return result;
  }
}
```

### Expected behavior
deleted user with a valid token trying to access protected resource should receive Forbidden error or at least
mark the error as an authentication error and not a mongoose resource with id not found

### Actual behavior
deleted user with a valid token trying to access protected resource receive Not Found error

### System configuration

    "@feathersjs/authentication": "^4.5.3",
    "@feathersjs/authentication-local": "^4.5.4",
    "@feathersjs/authentication-oauth": "^4.5.4",
    "@feathersjs/configuration": "^4.5.3",
    "@feathersjs/errors": "^4.5.3",
    "@feathersjs/express": "^4.5.4",
    "@feathersjs/feathers": "^4.5.3",
    "feathers-hooks-common": "^5.0.4",
    "feathers-mongoose": "^8.3.1",

**Comment by daffl** [comment]
Yes, you could do the same customization for [getEntity](https://docs.feathersjs.com/api/authentication/local.html#getentity-entity-params) and catch and re-throw the NotFound as a different error

```js
class CustomLocalStrategy extends LocalStrategy {
  comparePassword(entity, password) {
    const result = super.comparePassword(entity, password);
    if (!entity.enabled) {
      const message = entity.disabledMsg ? entity.disabledMsg : 'Server.errors.defaultDisabledMsg';
      throw new errors.Forbidden(message);
    }
    return result;
  }

  async getEntity(entity, params) {
    try {
      const entity = await super.getEntity(entity, params);

      return entity;
    } catch (error) {
      if (error.name === 'NotFound') {
        throw new NotAuthenticated('User has been deleted');
      }

      throw error;
    }
  }
}
```

**Comment by axmad22** [comment]
Thanks  daffl, but I already tried this method it's  only accessed when the user first signs in, but when I delete the user and he uses the same valid  token he bypasses the _getEntity_ method, so it would only work in sign in scenario. 

I think the culprit is the hook method (_authenticate('jwt') of @feathersjs/authentication_) I have set it on the **before->all** hook for _users service_  when the deleted users  tries to update himself  it throws the error for get request and  still allows the request to go through then I get an update error. In all two errors one for a Get and Update both the NotFound error I captured them in a global error parser this way i don't know if a NotFound  is an authentication error or a common database error to send the right message

Here is how am testing it

```js
 it.only('Deleted user with valid token should fail to update account', async () => {
      try {
        const auth = await axios.post(getUrl('authentication/'), {...userInfo, strategy: 'local'});
        await app.service('users').Model.remove({_id: user._id});
        await axios.put(getUrl(`users/${user._id}`),
                 { name: 'foo' },
                 {headers: {'Authorization': `Bearer ${auth.data.accessToken}`}});
        assert.fail('should never get here');
      } catch (error) {
        const {response} = error;
        assert.strictEqual(response.status, 403);
        assert.strictEqual(response.data.message, 'Server.errors.accountDeleted');
      }
    });

```

**Comment by daffl** [comment]
Oops, sorry I meant the [getEntity method of the JWT strategy](https://docs.feathersjs.com/api/authentication/jwt.html#getentity-id-params) 


```js
class CustomJWTStrategy extends JWTStrategy {
  async getEntity(entity, params) {
    try {
      const entity = await super.getEntity(entity, params);

      return entity;
    } catch (error) {
      if (error.name === 'NotFound') {
        throw new NotAuthenticated('User has been deleted');
      }

      throw error;
    }
  }
}
```

**Comment by axmad22** [comment]
thanks man it worked
