### ISSUE TITLE
Rest client restrictions

### ISSUE THREAD

**Issue by ghost** [feathersjs/feathers#2098]
Given that we're only allowed to use the 6 service methods to implement REST, how would someone go about implementing an endpoint that duplicates an existing (Complex) resource/model?

I apologize if this is the wrong place to ask, but we've looked extensively online and we couldn't find an appropriate answer.

Thanks!

**Comment by daffl** [comment]
There is a lot of information about this including examples [in the FAQ](https://docs.feathersjs.com/help/faq.html#how-do-i-create-custom-methods), on [Stackoverflow](https://stackoverflow.com/questions/34251526/feathers-calling-custom-api-method) and [in the guides](https://docs.feathersjs.com/guides/basics/services.html).

**Comment by ghost** [comment]
Thank you @daffl 🙏 , I understand what you mean, but I am asking specifically how can someone implement the example I stated above without having to do custom route / service, binding meaning staying with the constraints of REST which seems quite nice to keep things well organized.

For instance having a REST service: users/:id, what would a "duplicate user" feature look like, besides the obvious none supported way (user/:id/duplicate)  which is against the constraints.

**Comment by daffl** [comment]
That isn't really against the constraints. It's just another custom service:

```js
app.use('/users/:userId/duplicate', {
  async create (data, params) {
    const { userId } = params.route;
    const { id, ...userData } = await app.service('users').get(userId, params);

    return app.service('users').create(userData, params);
  }
});
```

**Comment by ghost** [comment]
I understand, thank you very much @daffl
