### ISSUE TITLE
Unregistering services and hooks #446

### ISSUE THREAD

**Issue by steffanhalv** [feathersjs/feathers#2105]
Ref.: https://github.com/feathersjs/feathers/issues/446

Is this possible now?
I have a use case where services are created and destructed on runtime.

Without this, a restart of the server would have to be done when destructing to not eat up memory.

**Usecase:** Dynamically create & remove service endpoints for a CMS. (Create works just fine)

Using this in an after remove hook works kinda, but then overwriting would not work.
```js
let service = ctx.app.service(ctx.result.name)
  Object.keys(service).forEach(k => {
    delete service[k]
  })
```

**Comment by daffl** [comment]
Unregistering services isn't possible because you can not (easily) remove Express middleware. In a Feathers app without Express `delete app.services[name]` would do it. Most cases for dynamic services can already be handled much more elegantly [with custom routing](https://docs.feathersjs.com/api/express.html#routing) though:

```js
app.service('cms/:name', {
  create (data, params) {
    return getCollection(params.route.name, params.user).create(data);
  }
});
```

**Comment by steffanhalv** [comment]
> Unregistering services isn't possible because you can not (easily) remove Express middleware. In a Feathers app without Express `delete app.services[name]` would do it. Most cases for dynamic services can already be handled much more elegantly [with custom routing](https://docs.feathersjs.com/api/express.html#routing) though:
> 
> ```js
> app.service('cms/:name', {
>   create (data, params) {
>     return getCollection(params.route.name, params.user).create(data);
>   }
> });
> ```

Cool, I actually made this work just now 👍 

Is it also possible to replace hook functions?

F.ex.

```js
let newfunc = () => {}
myservice.hooks.after = [newfunc]
```

**Edit**:

I guess we can reuse this: `service.hooks(hooks)`?

**Edit 2**:
Yup it does. Thats all I need, thank you :) @daffl
