### ISSUE TITLE
Problem using feathers with an existing Express application

### ISSUE THREAD

**Issue by kokujin** [feathersjs/feathers#211]
I have an application that was scaffolded using the standard express generator. According to the docs, one just has to replace 2 lines to use feathers as in:

```````
var express = require('express'); to this   ->>   var feathers = require('feathers');
var app = express(); to this   ->>   var app = feathers();
`````
I also uncommented this line:

`````
// uncomment after placing your favicon in /public
app.use(favicon(path.join(__dirname, 'public', 'favicon.ico')));
````

I cant continue because of this stacktrace

`````````
module.js:328
    throw err;
    ^

Error: Cannot find module 'serve-favicon'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/kokujin/Development/Research/feathers_test/app.js:4:15)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
`````

Is there anything else I have to do? Thanks

**Comment by kokujin** [comment]
By the way, I re-installed "serve-favicon", no luck, same error

**Comment by daffl** [comment]
This still looks more like a general Node error to me. I just tried running the [Express generator](http://expressjs.com/en/starter/generator.html), then I added

```
npm install feathers --save
```

and changed every

```js
var express = require('express');
```

to

```js
var feathers = require('express');
```

Then I added this at the beginning of `app.js` (right after `var app = express();`):

``
var app = express();

app.configure(express.rest());
app.use('/todos', {
  get: function(id, params, callback) {
    callback(null, {
      id: id,
      name: 'You have to do ' + id
    });
  }
});

// view engine setup
app.set('views', path.join(__dirname, 'views'));
```

And going to http://localhost:3000/todos/dishes worked.

**Comment by ekryski** [comment]
@kokujin I think this might be an issue with your node environment. Without more info from you we can't help. Closing for now.
