### ISSUE TITLE
App configuration gets overriden by feathers express

### ISSUE THREAD

**Issue by stellarhoof** [feathersjs/feathers#2113]
### Steps to reproduce

```javascript
import feathers from '@feathersjs/feathers'
import express from '@feathersjs/express'
import configuration from '@feathersjs/configuration'

let app = feathers()
app.configure(configuration())
console.info(app.settings) // Darlings are here.
app = express(app)
console.info(app.settings) // express stuff. Where are my darlings?
```

### Expected behavior

`app.settings` should have all my configuration

### Actual behavior

No configuration :(

### Why would I want to do this?

My usecase: Elastic APM needs to be required before express because some monkey patching magic. I can work around it with some more magic but as a result I don't have access to the app so I have to load the configuration manually. If I could decouple configuration from express stuff I can snuck in apm in the middle.

Thanks!

**Comment by daffl** [comment]
The Express app get mixed in and should be [used as documented](https://docs.feathersjs.com/api/express.html#express-app) during initialization. You can get the configuration separately from the configuration plugin via `import config from 'config';`

**Comment by stellarhoof** [comment]
Ok then 👍 . Thanks for the prompt response!
