### ISSUE TITLE
OAuth not respecting path or prefix

### ISSUE THREAD

**Issue by forgot** [feathersjs/feathers#2116]
I'm attempting to user OAuth with Feathers behind `/api`, but the internal routes created don't seem to respect anything added to `path` or `prefix` in the Grant configuration. Everything works in `localhost`, but I can't figure out how to get it to work with `/api`. I've been trying to debug this for the last three days and, 

I've tried setting `path`, `prefix`, `origin`, `callback`, `redirect_uri`, in every combination that I can think of, but nothing seems to work.

Here are the relevant parts from the `production.json` config file.

```
 "oauth": {
      "redirect": "/home",
      "defaults": {
        "prefix": "/api"
      },
      "github": {
        "key": "GITHUB_KEY",
        "secret": "GITHUB_SECRET",
        "callback": "/api/oauth/github/callback",
        "redirect_uri": "/api/oauth/github/callback"
      }
}
```

I've also tried setting everything explicitly, but still nothing...

Calling `/api/oauth/github` redirects to `/oauth/connect/github?`, which throws a 404. If I add the `/api` to the beginning, I get redirected to Github for login.

I've read through the documentation for Feathers and for Grant several times, but can't come up with a solution. I've seen a few other issues here or questions on StackOverflow with similar problems, but can't find an answer. Any insights as to how I should accomplish this?

**Comment by daffl** [comment]
Probably the same issue as #2031

**Comment by forgot** [comment]
Closing to consolidate discussion in the above linked issue
