### ISSUE TITLE
Feathers demo does not work

### ISSUE THREAD

**Issue by kokujin** [feathersjs/feathers#212]
I cant get the first demo to work either. Straight from the website:

`````
/ app.js
import feathers from 'feathers';
import rest from 'feathers-rest';
import socketio from 'feathers-socketio';
import mongodb from 'feathers-mongodb';
import bodyParser from 'body-parser';

const app = feathers();
const todoService = mongodb({
  db: 'feathers-demo',
  collection: 'todos'
});

app.configure(rest())
  .configure(socketio())
  .use(bodyParser.json())
  .use('/todos', todoService)
  .use('/', feathers.static(__dirname))
  .listen(3000);
`````

`````
import feathers from 'feathers';
^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3
``````
Does one need a particular node version? I am using 5.3.0. Thanks

**Comment by daffl** [comment]
The Readme has the demo for Feathers 2 which uses ES6 and requires https://babeljs.io. You could run

```
npm install babel-cli -g
```

And then

```
babel-node app
```

Or refer to the demo on the main website at http://feathersjs.com which should work with all Node versions.

**Comment by ekryski** [comment]
We'll close this when 2.0 launches.

**Comment by daffl** [comment]
As discussed in the related issue, we will change the import statements back into `require` so that the demo will work out of the box with the latest version of Node.

**Comment by kokujin** [comment]
Thanks @daff, following the instructions on the website produces a working demo. But for your information, this demo fails also when one uses the latest [feathers-nedb](https://github.com/feathersjs/feathers-nedb) module.

**Comment by marshallswain** [comment]
Thanks @kokujin.  We are trying to do a release soon, so it helps a bunch when you bring these loose ends to our attention.

**Comment by ekryski** [comment]
I've updated the examples in a bunch of places for the new Feathers2 syntax. Should be good to go now.

**Comment by v1p** [comment]
So it's better to stick to the `require` instead of es2015 ?

**Comment by marshallswain** [comment]
Stick to CommonJS in Node, ES Modules in the browser.

**Comment by v1p** [comment]
Woa, my comment got deleted ? 😅  , but thanks @marshallswain
