### ISSUE TITLE
TS type of express(feathers()) is any

### ISSUE THREAD

**Issue by SephReed** [feathersjs/feathers#2120]
<img width="424" alt="Screen Shot 2020-11-10 at 2 27 13 PM" src="https://user-images.githubusercontent.com/14002040/98735632-533d5a00-2369-11eb-9f4b-b387fc0eae82.png">

**Comment by SephReed** [comment]
`"allowSyntheticDefaultImports": true,` is required in tsconfig.json, otherwise some imports in the .d.ts files for @feathers/express end up being any, and that gets mixed with a type.

Perhaps add `"allowSyntheticDefaultImports": true,` as a requirement to the getting started/installation page

**Comment by daffl** [comment]
For now, pass the application type as a generic or [a type pointer as used in a generated application](https://github.com/feathersjs/feathers-chat-ts/blob/crow/src/app.ts#L22):

```ts
const app: Application = express(feathers());
// or
const app = express<Application>(feathers());
```
