### ISSUE TITLE
Protect from commit to master on all projects

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers#213]
It would probably be a good idea to keep me from committing to master.  🤓
- [ ] feathers
- [ ] feathers-commons
- [ ] feathers-rest
- [ ] feathers-socketio
- [ ] feathers-primus
- [ ] feathers-socket-commons
- [ ] feathers-mongodb
- [ ] feathers-mongoose
- [ ] feathers-authentication
- [ ] feathers-client
- [ ] feathers-nedb
- [ ] feathers-memory
- [ ] feathers-sequelize
- [ ] feathers-knex
- [ ] feathers-waterline
- [ ] feathers-query-filters
- [ ] feathers-configuration

**Comment by ekryski** [comment]
I dunno if that is a real issue. Just don't do it and do PRs. We should all be putting our stuff through PRs anyway for visibility.

**Comment by daffl** [comment]
I already protected the master branch of this repository from force pushes. GitHub itself doesn't allow locking a branch completely. If one of you guys thinks that the other ones should be locked, feel free to do so.
