### ISSUE TITLE
return stream response from axios

### ISSUE THREAD

**Issue by whelan9453** [feathersjs/feathers#2130]
hi

My scenario is that a client sends a request to the feathers server, and then the feathers server sends a request via axios and gets a stream response. In the last step, I want to respond to feathers clients with this axios stream response.

I get my stream response from axios like this
``` javascript
const instance = axios.create({
  baseURL: myHost,
  headers: {
    'Content-Type': 'application/json',
  },
  responseType: 'stream',
});


const axiosStreamRes = instance.post(myUrl, {
      key1: val1,
})
```

I want to reply with axios stream response in a stream way.
My feathers service be like this.

```javascript
class MessageService {

  async find(params) {
    return axiosStreamRes;
  }
}  


app.use('/messages', new MessageService());
```

I found some discussions [here](https://stackoverflow.com/questions/40170436/streaming-response-in-feathers) and [there](https://github.com/feathersjs/feathers/issues/609), but I couldn't really see a practical solution. 

Is there any recommended way to do so?  Maybe a generator could help? If so, how could we leverage the generator pattern here?

Thanks for helping out.

**Comment by daffl** [comment]
You can initiate a stream in [a custom service middleware](https://docs.feathersjs.com/api/express.html#custom-service-middleware).

**Comment by whelan9453** [comment]
Hi @daffl 
Thanks for your reply.

I tried two different attempts:

It works if I do this (I can return stream response from axios to feathers client)
```javascript
// I use express middleware in this case
const app = express(feathers());
app.use(`/mypath`, async (req, res, next) => {
    const axioStreamRes = await axiosInstance.post(...);
    axioStreamRes.data.pipe(res);
});
```

It won't work if I do this.  

```javascript
// I use feathers custom middleware in this case
  app.use(`/mypath`, {async find() {return Promise.resolve()} }, async (res, req, next) => {
    const axioStreamRes = await axiosInstance.post(...);
    axioStreamRes.data.pipe(res.data);
  });

  // I use hooks in this case
  const service = app.service(myservice);
  service.hooks(hooks);
```

and the log is like this (error occurs at this line: _axioStreamRes.data.pipe(res.data);_)
```
info:  {"hook":"before","state":"begin"}
info:  {"hook":"after","duration":0,"state":"finish","success":true}

Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read property 'on' of undefined
      at IncomingMessage.Readable.pipe (_stream_readable.js:671:8)
      at /my/path/to/project
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
} reason: TypeError: Cannot read property 'on' of undefined
    at IncomingMessage.Readable.pipe (_stream_readable.js:671:8)
    at /my/path/to/project
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

The duration is 0, which is abnormal, and it seems like I need to implement an "on" function to handle the stream finish event somewhere to close this request correctly. (Since the error pops up after the after hook.)

Any advice?

Thanks again!
