### ISSUE TITLE
Custom authentication

### ISSUE THREAD

**Issue by borkowsky** [feathersjs/feathers#2131]
Hi there. I listed google for a days and not found any information about adding custom authentication strategy to my Featherjs project. I need to get token from Google by frontend, verify it at the backend of my application and if email from responce have in database, i need to send auth headers with jwt token to Vue frontend. (Sorry for my bad english)

**Comment by bertho-zero** [comment]
You have a sample custom strategy here: https://docs.feathersjs.com/api/authentication/oauth.html#customization

For the frontend part it's here: https://developers.google.com/identity/protocols/oauth2/javascript-implicit-flow

**Comment by borkowsky** [comment]
> You have a sample custom strategy here: https://docs.feathersjs.com/api/authentication/oauth.html#customization
> 
> For the frontend part it's here: https://developers.google.com/identity/protocols/oauth2/javascript-implicit-flow

Which method i must customize to change logics as i needed?
