### ISSUE TITLE
Error TS2503: Cannot find namespace 'SocketIOClient'

### ISSUE THREAD

**Issue by antonpalermo** [feathersjs/feathers#2132]
### Steps to reproduce

I'm using angular/cli and created a new app using `ng new appname` and installed the following packages

`npm install @feathersjs/authentication-client @feathersjs/client @feathersjs/errors @feathersjs/primus-client @feathersjs/rest-client @feathersjs/socketio-client socket.io-client`

 then I created a service named `feathers.service.ts` like this.

**feathers.service.ts**
```
import { Injectable } from '@angular/core';

import feathers from '@feathersjs/client';
import socketClient from '@feathersjs/socketio-client';

@Injectable({
  providedIn: 'root'
})
export class FeatersService {

  private client= feathers();
  private socketIO = require('socket.io-client')('http://localhost:3030');
  private authetication = require('@feathersjs/authentication-client');

  constructor() {
    this.client.configure(socketClient(this.socketIO)).configure(this.authetication({
      storageKey: 'auth'
    }));
  }

  private user: any;

  public get User(): any {
    return this.user;
  }

  public async authenticate(credentials?: any) : Promise<any> {
    return this.client.authenticate(credentials).then((data) => this.user = data.user);
  }
}
```
then used this service on my `app.component.ts`

**app.component.ts**
```
import { Component } from '@angular/core';
import { FeatersService } from './core/featers.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'app-service';
  constructor(private feathersService: FeatersService) {
                      ^^^^^^^^^^^^^^^
  }
}
```
this will appear on my console after I save any changes on my source.
> Error: node_modules/@feathersjs/socketio-client/index.d.ts:7:14 - error TS2503: Cannot find namespace 'SocketIOClient'.

### Expected behavior
No Error

### Actual behavior

Angular will compile successfully then trow this error in the console.

> Error: node_modules/@feathersjs/socketio-client/index.d.ts:7:14 - error TS2503: Cannot find namespace 'SocketIOClient'.
>   
>    7     (socket: SocketIOClient.Socket, options?: socketioClient.Options): () => void;

### System configuration

**Module versions**: @feathersjs/socketio-client: 4.5.10

**NodeJS version**: v14.15.1

**Operating System**: Windows 10 Version 1909 (OS Build 18363.1082)

**Browser Version**: Version 1.16.76 Chromium: 86.0.4240.198 (Official Build) (64-bit)

**Comment by daffl** [comment]
The `socket.io-client` module must be version 2, not version 3. See #2128

**Comment by antonpalermo** [comment]
It's working now Sir @daffl thank you for the assistance...
