### ISSUE TITLE
Add a SECURITY.md to all packages

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers#214]
From here: https://nodesecurity.io/contribute
```
SECURITY.md

One reason 0day vulnerabilities get released without fixes being available is 
because of ineffective communication.

A SECURITY.md file communicates with the users of your project how you like 
to have security issues reported to you and set expectations about timelines for 
fixes and communication with the finder.
```

### Example security.md files
[Reddit](https://github.com/reddit/reddit/blob/master/SECURITY.md)
[GitLab Community Edition](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/release/security.md)
[discourse.org](https://github.com/discourse/discourse/blob/master/docs/SECURITY.md)

### Packages to update
- [ ] feathers
- [ ] feathers-commons
- [ ] feathers-rest
- [ ] feathers-socketio
- [ ] feathers-primus
- [ ] feathers-socket-commons
- [ ] feathers-mongodb
- [ ] feathers-mongoose
- [ ] feathers-authentication
- [ ] feathers-client
- [ ] feathers-nedb
- [ ] feathers-memory
- [ ] feathers-sequelize
- [ ] feathers-knex
- [ ] feathers-waterline
- [ ] feathers-query-filters
- [ ] feathers-configuration

**Comment by daffl** [comment]
What's the best way to do this? Is there a standardized format and benefits that come with that file? Maybe we should just add one to the main repository instead?

**Comment by ekryski** [comment]
Yeah I'm thinking we just add one to the main repo as well or link to a common one in the docs.

**Comment by marshallswain** [comment]
👍

**Comment by ekryski** [comment]
Ok I just added a security page to the docs. I'm thinking we just link to it from the main Feathers readme and that should be solid.
