### ISSUE TITLE
Need a example that feathersjs working with typeorm😥

### ISSUE THREAD

**Issue by 3lang3** [feathersjs/feathers#2144]
plz.

**Comment by 3lang3** [comment]
I've been stuck for a day

**Comment by J3m5** [comment]
You need to implement typeorm as a database adapter.
You can take a look at the different adapters implementation [here](https://github.com/feathersjs/databases).

**Comment by daffl** [comment]
[The guide](https://docs.feathersjs.com/guides/) and [Service API documentation](https://docs.feathersjs.com/api/services.html) also has more information on how to implement services that call to an ORM. There are also [sponsorship options](https://github.com/sponsors/daffl) that would allow maintenance of an official adapter as has been done for [feathers-couchbase](https://github.com/feathersjs-ecosystem/feathers-couchbase).
