### ISSUE TITLE
LocalStrategy is not being registered

### ISSUE THREAD

**Issue by RickEyre** [feathersjs/feathers#2148]
### Steps to reproduce

I'm attempting to implement LocalStrategy for authentication. This is the code I've setup.

```js
const { AuthenticationService, JWTStrategy } = require('@feathersjs/authentication')
const { LocalStrategy } = require('@feathersjs/authentication-local')

module.exports = app => {
  const authService = new AuthenticationService(app)

  authService.register('jwt', new JWTStrategy())
  authService.register('local', new LocalStrategy())

  app.use('/authentication', authService)
}
```

### Expected behavior
I should be able to login by POSTing `/authentication`
```json
{
  "strategy": "local",
  "email": "example@test.com",
  "password": "Test123"
}
```
### Actual behavior
I get a 500 error with the following message `NotAuthenticated: Invalid authentication information (strategy not allowed in authStrategies)`

### Extra

I found this code https://github.com/feathersjs/feathers/blob/crow/packages/authentication/src/core.ts#L207 and when I console.log `allowed` here it only contains `[ 'jwt' ]`. So it seems like Feathers has not even registered the strategy to begin with. 

I believe something is happening though because if I do not configure the local strategy's settings "usernameField" and "passwordField" it yells at me. So I think something is happening at least.

**Comment by J3m5** [comment]
You must configure your strategy by adding it in the config manually or dynamically.
[https://docs.feathersjs.com/api/authentication/service.html#configuration](https://docs.feathersjs.com/api/authentication/service.html#configuration)

**Comment by RickEyre** [comment]
@J3m5 thanks for the response, I appreciate it.

I have done that already though.

`config/default.json`
```json
{
  "port": "PORT",
  "host": "HOST",
  "authentication": {
    "secret": "AUTH_SECRET",
    "entity": "user",
    "service": "users",
    "authStrategies": ["jwt"],
    "jwtOptions": {
      "header": { "typ": "access" },
      "audience": "AUTH_AUDIENCE",
      "issuer": "radar",
      "algorithm": "HS256",
      "expiresIn": "30m"
    },
    "local": {
      "usernameField": "email",
      "passwordField": "password"
    }
  }
}
```

This is what I meant when I said:

> I believe something is happening though because if I do not configure the local strategy's settings "usernameField" and "passwordField" it yells at me. So I think something is happening at least.

Is there some configuration values I'm missing here?

**Comment by J3m5** [comment]
> Is there some configuration values I'm missing here?

Yep, you need to add `local` to the `authStrategies` property like in the docs:

```json
{
  "authentication": {
    "secret": "CHANGE_ME",
    "entity": "user",
    "service": "users",
    "authStrategies": [ "jwt", "local" ],
    "jwtOptions": {
      "header": { "typ": "access" },
      "audience": "https://yourdomain.com",
      "issuer": "feathers",
      "algorithm": "HS256",
      "expiresIn": "1d"
    }
  }
}
```

**Comment by RickEyre** [comment]
🤦

Thank you.
