### ISSUE TITLE
Google OAuth strategy creates a new user

### ISSUE THREAD

**Issue by francescochiapello** [feathersjs/feathers#2149]
I've implemented the example code as per https://docs.feathersjs.com/cookbook/authentication/google.html#application-client-and-secret. When I try to sign in with a new user calling `/oauth/google` by default the authentication strategy creates a new user.

Is it possible to check if a user exists and if not stop the authentication flow?

**Comment by daffl** [comment]
It depends on what you changed or customized in your application. An existing user is looked up via [getEntityQuery](https://docs.feathersjs.com/api/authentication/oauth.html#getentityquery-profile-params) which can be [customized](https://docs.feathersjs.com/api/authentication/oauth.html#customization) to what you need.
