### ISSUE TITLE
Demos on site do not work

### ISSUE THREAD

**Issue by Tiagojdferreira** [feathersjs/feathers#215]
You might want to take a look at why the ToDo list examples don't work, as it can discourage new users to try it.
Otherwise, the project looks great and I will try it out sometime next week

**Comment by daffl** [comment]
Thank you. We're so focussed on the v2 release that we forgot to update the demo URL for the TodoMVC demos. All fixed now.

**Comment by katopz** [comment]
@daffl http://feathersjs.github.io/todomvc/feathers/react/ It's appear `Failed to load resource: the server responded with a status of 503 (Service Temporarily Unavailable)` at the moment?

**Comment by ekryski** [comment]
@katopz the docker container wasn't running for some reason. Should be good now.

**Comment by katopz** [comment]
@ekryski cool, also 503 here http://todos.feathersjs.com/ from https://github.com/feathersjs/feathers-docs/tree/master/clients#framework-support

**Comment by ekryski** [comment]
@katopz good catch! Thanks. Fixed that as well.
