### ISSUE TITLE
Local Auth Strategy is Setting Provider

### ISSUE THREAD

**Issue by RickEyre** [feathersjs/feathers#2151]
I'm trying to do a global app hook for authentication. I depend on `provider` value to know if I need to authenticate the call or not.

When local strategy executes it makes multiple queries to `users` service. On its call to `get` it passes `params` in. 

https://github.com/feathersjs/feathers/blob/crow/packages/authentication-local/src/strategy.ts#L89

My auth hook rejects this as unauthenticated, even though the call is originating internally.

**Comment by daffl** [comment]
This is necessary to return the sanitized (safe) version of the user object to the client. You can always [customize](https://docs.feathersjs.com/api/authentication/local.html#customization) this method to what you need.

**Comment by RickEyre** [comment]
How would one implement an authenticated `GET /users/:id` *and* use the built in authentication strategy? Is it not possible? As far as my reasoning goes the default `LocalStrategy` requires the `get` method of `users` to be public.

Currently my auth hook => check provider, if internal do not authenticate JWT, otherwise authenticate.

I've since customized the strategy and everything is working okay, but is there a better way?
