### ISSUE TITLE
cors package type error

### ISSUE THREAD

**Issue by bwgjoseph** [feathersjs/feathers#2156]
Hi,

I used the latest `@feathersjs/cli` and generate new app, it throws this error

![image](https://user-images.githubusercontent.com/37484538/102106860-0b2fbc80-3e6c-11eb-9713-4aff91a9195e.png)

This is the full error log

```js
No overload matches this call.
  The last overload gave the following error.
    Argument of type '(req: Request<never, never, never, never>, res: { statusCode?: number | undefined; setHeader(key: string, value: string): any; end(): any; }, next: (err?: any) => any) => void' is not assignable to parameter of type 'RequestHandlerParams<ParamsDictionary, any, any, ParsedQs>'.
      Type '(req: Request<never, never, never, never>, res: { statusCode?: number | undefined; setHeader(key: string, value: string): any; end(): any; }, next: (err?: any) => any) => void' is not assignable to type 'RequestHandler<ParamsDictionary, any, any, ParsedQs>'.
        Types of parameters 'req' and 'req' are incompatible.
          Type 'Request<ParamsDictionary, any, any, ParsedQs>' is not assignable to type 'Request<never, never, never, never>'.
            Type 'ParamsDictionary' is not assignable to type 'never'.
```

Clicking on `index.d.ts` points me to

![image](https://user-images.githubusercontent.com/37484538/102106700-da4f8780-3e6b-11eb-8279-46d8088685ff.png)

---

Also, in another machine with existing package, upgrading from `4.5.9` to `4.5.11` throws me another "similar type" of error as well

![image](https://user-images.githubusercontent.com/37484538/102107308-927d3000-3e6c-11eb-935f-aa7cb326d0be.png)

Have tried to remove `node_modules`, and `npm i`

**Comment by blackfan23** [comment]
I am seeing the same issue on a brand new app and on an updated existing app. 

Changed both 

`"cors": "2.8.4"` and `"@types/cors": "2.8.4"` and at least it is starting properly now. Have not had time to further investigate

**Comment by bwgjoseph** [comment]
Thanks for the hint.

The cause of this should be because of `@types/cors`. I just tested `"cors": "^2.8.5"` with `"@types/cors": "2.8.8"` and it seem to be working fine. Had to pin `@types/cors` just in case

Not sure about the other error though

**Comment by blackfan23** [comment]
I am working on my existing app now but can verify your combination, latest cors and pinned types at 2.8.8. Not a direct feathers issue at that

**Comment by bwgjoseph** [comment]
Yup, and here's something to follow up if you want to keep track

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49130

**Comment by bwgjoseph** [comment]
Based on my current test, the latest version of `@types/express-serve-static-core` should have fixed the issue. If you still face the issue, remove your `node_modules` and run `npm i`

**Comment by daffl** [comment]
Confirmed that this is working now. To reliably clear and reinstall you can run

```
rm -rf package-lock.json node_modules
npm install
```
