### ISSUE TITLE
CLI generated app fails to build with cors type error for Typescript project

### ISSUE THREAD

**Issue by bdmaupin** [feathersjs/feathers#2158]
### Steps to reproduce

- [ ] Generate new feathers app following the [getting started guide](https://docs.feathersjs.com/guides/basics/generator.html#generating-the-application)
- [ ] Use the following settings: 
```
? Do you want to use JavaScript or TypeScript? TypeScript
? Project name my-new-project
? Description
? What folder should the source files live in? src
? Which package manager are you using (has to be installed globally)? npm
? What type of API are you making? REST, Realtime via Socket.io
? Which testing framework do you prefer? Mocha + assert
? This app uses authentication Yes
? What authentication strategies do you want to use? (See API docs for all 180+ supported oAuth providers) Username + Password (Local)
? What is the name of the user (entity) service? users
? What kind of service is it? Sequelize
? Which database are you connecting to? SQL Server
```

### Expected behavior
App should build and run locally using `npm start`

### Actual behavior
App fails to build with the following error:

```
src/app.ts:33:9 - error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type '(req: Request<never, never, never, never>, res: { statusCode?: number | undefined; setHeader(key: string, value: string): any; end(): any; }, next: (err?: any) => any) => void' is not assignable to parameter of type 'RequestHandlerParams<ParamsDictionary, any, any, ParsedQs>'.
      Type '(req: Request<never, never, never, never>, res: { statusCode?: number | undefined; setHeader(key: string, value: string): any; end(): any; }, next: (err?: any) => any) => void' is not assignable to type 'RequestHandler<ParamsDictionary, any, any, ParsedQs>'.
        Types of parameters 'req' and 'req' are incompatible.
          Type 'Request<ParamsDictionary, any, any, ParsedQs>' is not assignable to type 'Request<never, never, never, never>'.
            Type 'ParamsDictionary' is not assignable to type 'never'.

33 app.use(cors());
```

### System configuration

**Module versions** (especially the part that's not working):

`feathersjs: 4.5.11`
` "cors": "^2.8.5",`
`"@types/cors": "^2.8.9",`

**NodeJS version**:

`14.11.0`

**Operating System**:

`Windows 10`

**Module Loader**:

`NPM`

This appears to be a versioning issue between expressjs CORS `2.8.5` and the @types/cors `2.8.9`. Setting the @types/cors version to `2.8.5` seems to fix the build error.

**Comment by daffl** [comment]
See https://github.com/feathersjs/feathers/issues/2156 for discussion

**Comment by bdmaupin** [comment]
Sorry for the dupe. I tried searching before opening but failed to find that one. Thanks for the reply.

**Comment by bwgjoseph** [comment]
Based on my current test, the latest version of `@types/express-serve-static-core` should have fixed the issue. If you still face the issue, remove your `node_modules` and run `npm i`

**Comment by daffl** [comment]
Confirmed that this is working now. To reliably clear and reinstall you can run

```
rm -rf package-lock.json node_modules
npm install
```
