### ISSUE TITLE
Authentication Cookies for SSR

### ISSUE THREAD

**Issue by RickEyre** [feathersjs/feathers#2166]
I'm trying to enable the feathers JWT to be stored in a cookie. I see that this feature has recently been disabled in Feathers for security reasons. That's good.

However, I'm currently building out a React SSR application and need access to the JWT on page load. As far as I can tell the only way to do this is through a cookie. 

Is this feature gone for good, and I must build this myself? Or can someone point me in the right direction here.

**Comment by daffl** [comment]
This is described in the [Authentication section of the "Server Side Rendering"](https://docs.feathersjs.com/cookbook/express/view-engine.html#using-authentication) cookbook entry.

**Comment by RickEyre** [comment]
Thank you @daffl
