### ISSUE TITLE
send back secured files in feathersjs

### ISSUE THREAD

**Issue by devops724-2** [feathersjs/feathers#2172]
Hi there
i try setup secure files access to users
users should only have access to their own files 
but i don't know how can develop this in feathersjs. 
i develop user allow upload files 
and save record on db , but how should i limit users to own files access
they upload some image files 
thanks in advance

**Comment by daffl** [comment]
This is described in the [Authentication section of the "Server Side Rendering"](https://docs.feathersjs.com/cookbook/express/view-engine.html#using-authentication) cookbook entry.
