### ISSUE TITLE
Anonymous Channel leave(connection) does not work ?

### ISSUE THREAD

**Issue by tvld** [feathersjs/feathers#2175]
In channel.js:
```js
app.on('login', (authResult, { connection }) => {
    if(connection) {
      const user = connection.user
      console.log('*** before leave ', app.channels)
      app.channel('anonymous').leave(connection)
      console.log('*** after leave ', app.channels)
```
will output:
```
*** before leave  [ 'anonymous' ]
*** after leave  [ 'anonymous' ]
```
While I expect the client to have left the anonymous channel, it is still subscribed!

Somewhere else in my code, ``.leave()`` is just working fine. I first assumed it must be some side effect from ``app.on('connection', connection => {..}`` but in when I log that, it is not called after initial connection as expected.

I do not use the anonymous channel myself, but still it's not ok, I assume...))

**Comment by J3m5** [comment]
`app.channels` returns a list of channel names, not connections.
If you want to list connections in a channel you should do `app.channel("anonymous").connections`.
Take a look at [the docs here](https://docs.feathersjs.com/api/channels.html#channels-2) to see the differences.

**Comment by tvld** [comment]
oh oh... how shamefull ))))

I was just trying to list all the channels the user was subscribed on, which is not that trivial it seems )))
