### ISSUE TITLE
Cannot modify result/dispatch in get after hook

### ISSUE THREAD

**Issue by tandrej98** [feathersjs/feathers#2176]
Hello, 

I have an issue with the after hooks. No matter what I do I cannot change the object returned in response. I tried debugging and the object is changed in the hook,I tried to add another hook after this and debug it and it was still changed but in the end the response is the same object that was returned from the database. 

### Steps to reproduce

`all: [
      protect('password'),
    ],
    get: [
      async (context) => {
        if (context.dispatch != null) {
          context.dispatch[0].phone = '5';
        }
        context.result[0].phone = '5';
        return context;
      }],`

### Expected behavior
The response should have the modified phone attribute. Like:
` {
        "id": 1,
        "user_name": "test",
        "phone": "5",
    }`

### Actual behavior
The response contains the object that as returned from the database no matter what I do. 

` {
        "id": 1,
        "user_name": "test",
        "phone": "XXXX",
    }`

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
"@feathersjs/authentication": "^4.5.9",
"@feathersjs/authentication-local": "^4.5.9",
"@feathersjs/authentication-oauth": "^4.5.9",
"@feathersjs/configuration": "^4.5.9",
"@feathersjs/errors": "^4.5.9",
"@feathersjs/express": "^4.5.9",
"@feathersjs/feathers": "^4.5.9",
"@feathersjs/transport-commons": "^4.5.9",

**NodeJS version**:
v15.5.0

**Operating System**:
Ubuntu 20.04

**Comment by Psycholisk** [comment]
I am experiencing the same issue after migrating to feathersjs v5. What was the solution for your problem?

**Comment by ashaller2017** [comment]
i too am in the same boat
