### ISSUE TITLE
Using hooks with arrays causes after hooks to run x number of times.

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers#218]
I discovered this odd behavior by using an afterHook on `create` with a beforeHook on another service's `create`.  I'm not sure where this is happening, yet. Update: it's due to how some of the adapters handle arrays.

Below is an example to duplicate the issue.  Switch between the create statements and you'll see the difference.
```js
var feathers = require('feathers');
var feathersHooks = require('feathers-hooks');
var bodyParser = require('body-parser');
var rest = require('feathers-rest');
var memory = require('feathers-memory');

// Create a feathers instance.
const app = feathers()
  .configure(feathersHooks())
  .configure(rest())
  // Turn on JSON parser for REST services
  .use(bodyParser.json())
  // Turn on URL-encoded parser for REST services
  .use(bodyParser.urlencoded({ extended: true }));

// Create an in-memory Feathers service with a default page size of 2 items
// and a maximum size of 4
app.use('/todos', memory());
app.use('/tests', memory());

app.service('/todos').after({
  create: [
    function(hook){
      console.log('todos:after');
      return new Promise(function(resolve){
        console.log('hi');
        app.service('/tests').create({
          text: 'Server test'
        }).then(function(test){
          resolve(hook);
          console.log(test);
        });
      });
    }
  ]
});

app.service('/tests').before({
  create: [
    function(hook){
      console.log('tests:before');
      return new Promise(function(resolve){
        console.log('hi');
        resolve(hook);
      });
    }
  ]
});

// Create Todos
app.service('todos').create([
  {
    text: 'Server todo',
    complete: false
  },
  {
    text: 'Client todo',
    complete: false
  }
]);

// Create a dummy Todo
// app.service('todos').create({
//   text: 'Server todo',
//   complete: false
// });

app.service('todos').find().then(function(todos) {
  console.log('Found todos', todos);
});

// Start the server.
var port = 3030;

app.listen(port, function() {
  console.log(`Feathers server listening on port ${port}`);
});
```

Here's the output when creating a single object:
```
Bitovis-MacBook-Pro:mma-api Bitovi$ node test
todos:after
hi
tests:before
hi
Found todos [ { text: 'Server todo', complete: false, id: 0 } ]
{ text: 'Server test', id: 0 }
```

Here's the output when using create with the array:
```
todos:after
hi
todos:after
hi
tests:before
hi
tests:before
hi
Found todos []
{ text: 'Server test', id: 0 }
{ text: 'Server test', id: 1 }
todos:after
hi
tests:before
hi
{ text: 'Server test', id: 2 }
```

**Comment by marshallswain** [comment]
It's actually running the hooks data.length number of times.

**Comment by marshallswain** [comment]
Found it: https://github.com/feathersjs/feathers-memory/blob/master/src/index.js#L74

**Comment by marshallswain** [comment]
If this is the behavior that we expect, then we probably do not want hooks to handle arrays.  It would be better for hooks to ignore arrays and only process single objects.

**Comment by marshallswain** [comment]
Sequelize is different:
feathers-sequelize: https://github.com/feathersjs/feathers-sequelize/blob/master/src/index.js#L70.

This is the way that makes more sense to me.  Instead of doing x number of rapid-fire requests to the database, it seems smarter to take advantage of the bulk update feature (that's present in at least all of the main db adapters) and make a single request to the database.

We already have the code in place to provide events for all of the items in the array, which is really the only thing that I think needs to be done individually.

**Comment by daffl** [comment]
This is a great catch. Thinking about it (on a Friday night past wine'o clock) I would say the adapters need to have a way to call the original methods without any mixin functionality. One way might be to just store the original methods as `_patch`, `_create` etc. during initialization.

There was similar problems when using pagination. https://github.com/feathersjs/feathers-sequelize/issues/8 is very likely related to it.

**Comment by marshallswain** [comment]
I think we definitely want to treat arrays as single requests to the db, otherwise our apps will hit 5000+ requests per second much too easily.

**Comment by daffl** [comment]
I don't think it is that common to `create` thousands of items in an array but we should indeed use any bulk `create` mechanism that the database provides.

The specific problem here, that hooks and other mixins should not run if the method is called internally and the issue I referenced can probably be fixed by simply adding a `_create` and `_find` that runs the DB operations directly. I will try to get to it today.

**Comment by marshallswain** [comment]
I'm not as concerned about thousands of item in an array as I am about a couple hundred with a lot of users.

I'm able to get `feathers-mongoose` to work correctly by removing the [array check](https://github.com/feathersjs/feathers-mongoose/blob/master/src/service.js#L104) completely.  It passes all of the tests.

**Comment by marshallswain** [comment]
OK.  It took me a while to figure out how `_create` and `_find` would be useful, but nobody said I was smart.   That will be useful for modules like `feathers-memory` where you have to roll your own array support.  For modules with bulk support we can use it, otherwise we fall back to the new functions.  Am I following you correctly?

**Comment by daffl** [comment]
I'm doing an update of the database adapters today (just like https://github.com/feathersjs/feathers-memory/pull/13). Just keeping track of which ones I've done:

- [ ] [feathers-memory](https://github.com/feathersjs/feathers-memory/pull/13)
- [ ] feathers-nedb
- [ ] feathers-mongoose
- [ ] feathers-sequelize
- [ ] feathers-knex
- [ ] feathers-waterline

**Comment by ekryski** [comment]
@marshallswain great find man! I know @corymsmith ran into this a couple times but he wasn't sure if he was just doing something wrong.

**Comment by marshallswain** [comment]
I think this is what was causing issues for @BigAB the other day, too.

**Comment by daffl** [comment]
All database adapters have been updated accordingly. Closing this issue now.

**Comment by orverduzco** [comment]
I'm running into this issue again using `feathers-rethinkdb`, any fix for rethinkdb specifically?

**Comment by daffl** [comment]
This is a different issue, tracked in https://github.com/feathersjs/feathers-rethinkdb/issues/80
