### ISSUE TITLE
Need a way to override paginate.max internally.

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers#219]
In a scenario where I have a list of transactions and I want to set the public pagination max to 250, but on the server I need to be able retrieve 2500+.  I can compare the `data.length` to the `total` and recurse until I have the total, but it would be nicer to be able to disable the max for a single request.

**Comment by daffl** [comment]
Currently there are two workarounds. You can either temporarily set `service.paginate.max = Number.MAX_VALUE` and then set it back or call the new `_find` which does not do pagination by default.

The best way is probably to change `find` to allow a `params.paginate` option. For example, by changing https://github.com/feathersjs/feathers-mongoose/blob/master/src/service.js#L81to something like

```js
find(params) {
  const paginate = (params.paginate || params.paginate === false) ? 
    params.paginate || {} :
    this.paginate.default;
  
  const result = this._find(params, !!paginate, query => filter(query, paginate));
  
  if(!paginate) {
    return result.then(page => page.data);
  }
  
  return result;
}
```

This would allow to set `params.paginate = false;` or to a custom pagination object.
