### ISSUE TITLE
FeathersJS auto-completing information on package.json without been prompted about

### ISSUE THREAD

**Issue by MrAmericanMike** [feathersjs/feathers#2195]
### Steps to reproduce

On an empty folder start a feather project using the CLI command feathers generate app

Answer all the questions. Notice that at no point you are asked about author or e-mail

Open package.json and "surprise" an author name and e-mail shows in that file. We were never asked about those. (Where did feathers got that from, and who is exposing them?)

### Expected behavior

I would expect feathers CLI to ask us at least the same questions an npm init command would ask us and not fill information for us.

### Actual behavior

Author name and email are filled automatically (magically)

**Module versions** (especially the part that's not working):

feathers - 4.4.3

**NodeJS version**:

node - 13.14.0
npm - 6.14.11

**Operating System**:

Windows 7

**Comment by bwgjoseph** [comment]
If I'm not wrong, it should be auto populated with your `.npmrc` config, you can run `npm config ls` to view. You can read [npm-config](https://docs.npmjs.com/cli/v6/using-npm/config#init-author-name), specifically, `init-author-name, init-author-email, and init-author-url`.

Has nothing to do with feathers-cli

**Comment by MrAmericanMike** [comment]
> 
> 
> If I'm not wrong, it should be auto populated with your `.npmrc` config, you can run `npm config ls` to view. You can read [npm-config](https://docs.npmjs.com/cli/v6/using-npm/config#init-author-name), specifically, `init-author-name, init-author-email, and init-author-url`.
> 
> Has nothing to do with feathers-cli

It never happened with other projects or when creating projects simply using npm init.

The values are not on there so they must be coming from somewhere else. My guess would be from github as the values that were inserted on those fields are my Github username and mail. Will do some testing, see if I can remove the github values and start a project again and see what happens.

**Comment by daffl** [comment]
It's from git (see https://github.com/feathersjs/generator-feathers/blob/master/generators/app/configs/package.json.js#L29) which is what most Yeoman based generators are using.

**Comment by MrAmericanMike** [comment]
Confirmed it was coming from the git config user.name and user.email I deleted those and the newly created package left empty values.

```json
"author": {
    "name": "",
    "email": ""
  },
  ```

I don't understand how git lets anyone use those values something like an email should be more protected and not open and accessible by anyone.

At the same time "others" like FeathersJS in this case using those values, should "at least" ask if we are ok using those values for the package.json, otherway just leave them empty or prompt during the generation, we already answering other questions to generate a project, been asked for name and email wont make it much longer of a process.

**Comment by daffl** [comment]
This is information that is locally available on your machine to anybody who has read access to the folder of a git repository. Many other generators do the same thing (you will e.g. get the same defaults running `npm init --yes` in a cloned Git repository). The CLI usually tries to use good defaults and avoids showing prompts for things that are easy to change by opening one file and adjusting it to what you need.
