### ISSUE TITLE
Internal _get() method for service returns "Cannot read property 'query' of undefined", requires 2nd argument

### ISSUE THREAD

**Issue by msvendsentan** [feathersjs/feathers#2197]
I don't know if this is a bug or intended functionality (and whether it even belongs here or in the db adapter github), but when I trigger a `context.app.service('service')._get(id)` call (as a server-side, hook-bypassing call) as part of a "before" hook for another service, it throws "Cannot read property 'query' of undefined."

I've reached the limits of my meager investigative abilities on this one, but here's what I've found below:
- When using a normal `.get(id)` call (no underscore), it works fine
- I can also bypass this and return expected results by using `._get(id, '')` implying that a second argument is required, even if it's empty? Second argument is NOT required for typical `.get(id)` call, and the [documentation](https://docs.feathersjs.com/guides/basics/services.html#service-methods) says that params are optional
- I'm using a typical feathers generate app with yarn, feathers-objection and sqlite3 as my db
- As far as I could tell (not used to the environment), this error did NOT happen in nedb, and `._get(id)` (no second argument) worked fine

Repo can be found at [https://github.com/msvendsentan/feathers-get-bug](https://github.com/msvendsentan/feathers-get-bug)

To recreate:
- Clone
- Make sure /feathers_get_bug.sqlite has come along for the ride (I've seeded 2 records)
- Yarn install, yarn start
- Postman/Insomnia/etc. a no-header GET request to http://localhost:3030/service-b
- Error logged in client, server-side console reports more details
- Full breaking logic in /src/hooks/bug-demo.js

Again, not sure if it's intended or a bug, and whether or not it belongs here or in feathers-objection. Thanks for reading!

**Comment by daffl** [comment]
There is no argument normalization for internal methods so it depends if the database adapter implements a default argument. Most already do but in your case this would be an issue in [feathers-objection](https://github.com/feathersjs-ecosystem/feathers-objection) where e.g. https://github.com/feathersjs-ecosystem/feathers-objection/blob/master/src/index.js#L602 should become `get (id, params = {}) {` instead.

**Comment by msvendsentan** [comment]
Thanks, suspected this might be the case! Will bring to their attention; it's a minor thing.
