### ISSUE TITLE
We need to support relationships between resources

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers#22]
I should be able to hit a route like `GET /users/:id/posts` and get all the users posts.

**Comment by jadedevin13** [comment]
what happened to this? feathers association has not been updated since 2 years.

**Comment by daffl** [comment]
We have an FAQ item about this at http://docs.feathersjs.com/help/faq.html#how-do-i-return-related-entities

**Comment by nikolakanacki** [comment]
@daffl All of the links associated with "associations" are dead. Any fresh ones?

**Comment by daffl** [comment]
Whoops, sorry, the current link is https://docs.feathersjs.com/faq/readme.html#how-do-i-do-associations, for nested and custom routes it is https://docs.feathersjs.com/faq/readme.html#how-do-i-do-nested-or-custom-routes

**Comment by InstanceOfMichael** [comment]
Philosophically speaking, why is `GET /posts?userId=:userId` not better than `GET /users/:id/posts`?

**Comment by daffl** [comment]
It _is_ better because it is much easier to create and serialize an object with `{ userId: 1234 }` into a query string than having to know how your route is composed and having to do some arbitrary string concatenation.
