### ISSUE TITLE
[Error] Calling with feathersjs/rest-client throws ERR_HTTP_INVALID_HEADER_VALUE

### ISSUE THREAD

**Issue by PowerMogli** [feathersjs/feathers#2208]
What needs to be considered if an app connects to the API gateway on the server (feathersjs) via a websocket connection, but you want a connection from the gateway in the Kubernetes cluster to the microservice behind it to make a REST call and you want to use the feathersjs/rest-client on the API gateway for that?

I ask because in our case the following error message is always returned when the feathersjs/rest-client at the API gateway sends a REST call to the microservice behind it: ERR_HTTP_INVALID_HEADER_VALUE

We basically pass the values (id, data, params) coming from the websocket to the REST client.

**Comment by daffl** [comment]
This means that a header value is set to `undefined`. Every request should always have an `Accept` and `Content-Type` value - which ones are being set by default also depends on the HTTP library you are using.
