### ISSUE TITLE
feathersjs rest client download file lack of documentation

### ISSUE THREAD

**Issue by devops724-2** [feathersjs/feathers#2215]
Hi there
i want download a file(img, txt, csv) using rest client and show in site in related section
there is no documentation how can do this
how can i download a file using rest client, or is there a way can access axios or fetch from feathers-rest... to run normally download request use this modules
best regards

**Comment by gerwintown** [comment]
What you are asking for is a basic tutorial on REST APIs and HTTP/AJAX clients and can be found just about anywhere.  It is not at all specific to Feathers or its rest-client.  The only thing you would need to know is how to use it's GET method, which is documented completely.

The documentation for the REST client hints at this in the very first line: 
"@feathersjs/rest-client allows to connect to a service exposed through the Express REST API using jQuery, request, Superagent, Axios or Fetch as the AJAX library."

That line and the descriptions that follow also includes the answer to your last question.

I googled "express rest api download file" and found a bunch of tutorials, here are the first two:
https://stackoverflow.com/questions/7288814/download-a-file-from-nodejs-server-using-express
https://bezkoder.com/node-js-express-download-file/

Hopefully that gives you some direction to find your answer. Anything is else is going to be highly dependent on the front end framework you are using, etc...

**Comment by daffl** [comment]
Additional documentation is now also available in https://docs.feathersjs.com/api/express.html#express-authenticate
