### ISSUE TITLE
Console warning message when you have over 10 services

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers#222]
> (node) warning: possible EventEmitter memory leak detected. 11 connection listeners added. Use emitter.setMaxListeners() to increase limit.
Trace

Maybe we want to set the default a bit higher?

**Comment by daffl** [comment]
It's because in 2.0 the websocket handling is now just a plain service mixin (like events and promises). So every service binds to the `connection` event at https://github.com/feathersjs/feathers-socket-commons/blob/master/src/index.js#L23

It felt a lot cleaner but maybe there still should be just one connection listener that loops through all services on a new connection.

**Comment by marshallswain** [comment]
All of the services seem to work as expected, still.  I wonder if there's a way to increment the max with each service that's added.

**Comment by daffl** [comment]
It would just be `info.connection().setMaxListeners(Object.keys(app.services).length + 1)`. That's probably a good idea since that would still take care of catching memory leaks.

**Comment by ekryski** [comment]
:+1: Ya we should definitely do that. It will also help people feel more comfortable with Feathers. The less warnings/errors that are shown the better, even if they are normal node runtime warnings.

**Comment by lionelrudaz** [comment]
Hi guys,

I updated to 2.0.0, but I still have the message.

```
(node) warning: possible EventEmitter memory leak detected. 11 connection listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Namespace.addListener (events.js:239:17)
    at Server.(anonymous function) [as on] (/Users/lionelrudaz/Sites/wellnow/wellnow-node/node_modules/socket.io/lib/index.js:369:16)
    at EventEmitter.app.setup (/Users/lionelrudaz/Sites/wellnow/wellnow-node/node_modules/feathers-authentication/lib/index.js:120:16)
    at EventEmitter.listen (/Users/lionelrudaz/Sites/wellnow/wellnow-node/node_modules/feathers/lib/application.js:145:10)
    at EventEmitter.listen (/Users/lionelrudaz/Sites/wellnow/wellnow-node/node_modules/uberproto/lib/proto.js:30:17)
    at Object.<anonymous> (/Users/lionelrudaz/Sites/wellnow/wellnow-node/index.js:6:18)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:429:10)
    at startup (node.js:139:18)
    at node.js:999:3
```

My repo: https://github.com/lionelrudaz/wellnow-node

Is there anything I'm doing wrong?

Thanks in advance

**Comment by marshallswain** [comment]
I noticed this same thing on my project last night.

**Comment by ekryski** [comment]
@lionelrudaz no you're not doing anything wrong. That is inside node's event emitter module to just make sure you are aware that you have a bunch of event emitters set up (which is normal for Feathers).

I thought @daffl had made it so that we bumped the max listeners so that we don't get that warning but seems not.

**Comment by daffl** [comment]
I did. Are you all using `feathers-primus` and `feathers-socketio` 1.3? When does this happen? When you have more than 10 connections or more than 10 services?

**Comment by marshallswain** [comment]
I generated a new app, then moved 17 services into it.

**Comment by marshallswain** [comment]
![screen shot 2016-03-03 at 9 19 01 am](https://cloud.githubusercontent.com/assets/128857/13500743/104eb6c4-e121-11e5-941c-0273b84f721b.jpg)

**Comment by lionelrudaz** [comment]
@daffl feathers-primus 1.3.2 and feathers-socketio 1.3.3.

**Comment by daffl** [comment]
This actually did get fixed via https://github.com/feathersjs/feathers-socket-commons/pull/3 but apparently I forgot to make an actual release. I verified that it is not showing the warning anymore with `feathers-socket-commons` version 0.2.1.
