### ISSUE TITLE
Feathersjs mongoose $populate models sort query not working 

### ISSUE THREAD

**Issue by f-i-t-s-u-m** [feathersjs/feathers#2225]
### Feathersjs mongoose $populate models sort query not working 

I noticed nested document query is not working on latest feathersjs 

i have three mongodb collections
1, user collection
2, institution collection
3, user-intuitions collection (many to many relation  )

![Annotation 2021-02-16 221451](https://user-images.githubusercontent.com/79186700/108164833-6b2e2380-70a6-11eb-84f4-ab74c56448b6.png)

user-institutions collection $populate users and institution collection
using 
http://localhost:3030/user-institutions?$populate=user&$populate=institution

but feathers sort query not working for 
http://localhost:3030/user-institutions?$populate=user&$sort[user.createdAt]=-1 or for future
http://localhost:3030/user-institutions?$populate=user&$sort[user.name]=-1 
```
{
    "total": 0,
    "limit": 10,
    "skip": 0,
    "data": []
}

```
### Expected behavior

we are expecting if feathers sort query works for populated nest documents

### Actual behavior

we are keep getting 
```
{
    "total": 0,
    "limit": 10,
    "skip": 0,
    "data": []
}
```

please this is not only our issue we are dealing with this for 2 days 
if you have better idea or feathers idea to do this job

**Comment by daffl** [comment]
Since `$populate` is a Mongoose specific parameter, the options for `.populate` need to be adjusted to include the sorting parameters [example in this Stackoverflow answer](https://stackoverflow.com/questions/11512965/mongoose-sort-query-by-populated-field). This can be done in a hook:

```js
app.service('myservice').hooks({
  before: {
    find: [context => {
      context.params.query.$populate = {
        path: 'spells',
        options: { sort: [['damages', 'asc']] }
      }
    }]
  }
});
```

Closing this issue - follow ups can be opened in the [feathers-mongoose repository](https://github.com/feathersjs-ecosystem/feathers-mongoose) or [as a discussion](https://github.com/feathersjs/feathers/discussions).

**Comment by f-i-t-s-u-m** [comment]
i wish your example helped me but still not working for my problem

I search the whole week for this.
i want to sort parent collection from inner child populated collection 

this result is without any filter sort  query :

http://localhost:3030/user-institutions?$populate=user

``` 
{
  "total": 4,
  "limit": 10,
  "skip": 0,
  "data": [
{
           _id: "some id",
          type : "admin",
          user : {
                name: "zed",
               email:"zed@eg.com"
            }
},

{
           _id: "some id",
          type : "admin",
          user : {
                name: "Jonna",
               email:"zed@eg.com"
            }
},

{
           _id: "some id",
          type : "guest",
          user : {
                name: "Adam",
               email:"zed@eg.com"
            }
},

{
           _id: "some id",
          type : "employee",
          user : {
                name: "Berry",
               email:"zed@eg.com"
            }
},

]}

```

so i try to filter using feathers mongoose query 
http://localhost:3030/user-institutions?$populate=user&$sort[user.name]=1

i was expected to get

```

{
  "total": 4,
  "limit": 10,
  "skip": 0,
  "data": [
{
           _id: "some id",
          type : "guest",
          user : {
                name: "Adam",
               email:"zed@eg.com"
            }
},
{
           _id: "some id",
          type : "employee",
          user : {
                name: "Berry",
               email:"zed@eg.com"
            }
},
{
           _id: "some id",
          type : "admin",
          user : {
                name: "Jonna",
               email:"zed@eg.com"
            }
},
{
           _id: "some id",
          type : "admin",
          user : {
                name: "zed",
               email:"zed@eg.com"
            }
},


] 

```
but I cant get any different result from the first results.  am still getting the first result which is not in alphabetic ascending. 
still getting this result 
``` 
{
  "total": 4,
  "limit": 10,
  "skip": 0,
  "data": [
{
           _id: "some id",
          type : "admin",
          user : {
                name: "zed",
               email:"zed@eg.com"
            }
},

{
           _id: "some id",
          type : "admin",
          user : {
                name: "Jonna",
               email:"zed@eg.com"
            }
},

{
           _id: "some id",
          type : "guest",
          user : {
                name: "Adam",
               email:"zed@eg.com"
            }
},

{
           _id: "some id",
          type : "employee",
          user : {
                name: "Berry",
               email:"zed@eg.com"
            }
},

]} 
```

if you have any solution for this on feathers mongoose adapter please let me know as soon as possible 

thanks for your time

**Comment by f-i-t-s-u-m** [comment]
@daffl   i want to say thank you for your time i found the solution for my problem if anyone walking have the same problem. let me show you my problem 

i was trying to sort by http://localhost:3030/user-institutions?$populate=user&$sort[user.name]=1

which is not correct.
 just what i have to do was 

http://localhost:3030/user-institutions?$populate=user&$sort[user]=1
the above method is correct 

you can use SELECT query method if you have got in trouble 

i want to say thank you for @J3m5  too

**Comment by johnnyx3m** [comment]
@f-i-t-s-u-m i think your solution is not TRUE to all. If your nested/populated object contains "age" and you want to sort by "age", do you think it would work too? no right? I guess there should be a proper implementation on sorting by nested object like you once put. "sort[user.name]=1"
