### ISSUE TITLE
feathers client in UI does not update data correctly

### ISSUE THREAD

**Issue by ariel-david-collab** [feathersjs/feathers#2232]
### Steps to reproduce

- in the company, we have a model to bring data from computers
- when bringing the data from the computer, everything works normally
- when updating the data, we update it through a hook that is in charge of viewing, comparing, and updating the data with the new ones,
- When sending this information to the UI, the data is effectively updated, but the information is duplicated:
- 
### hook =>
**old data ->** 
`chassis.manufacturer = HP`
**new data ->** 
`chassis.manufacturer = Apple`
data sent from the API =>
**updated data ->** 
`chassis.manufacturer = Apple`

### UI =>
the data is received correctly from the UI, but the old representation of the data remains.

**data in UI ->**
```
chassis.manufacturer = Apple
chassis. manufacturer = HP
```

the data in the feathers cache / storage is not updated.

### hook =>
**old data ->** 
`chassis.manufacturer = HP`
**new data ->** 
`chassis.manufacturer = Apple`
### data sent from the API =>
**updated data ->** 
`chassis.manufacturer = Apple`

### UI =>
the data is received correctly from the UI, but the old representation of the data not remains.

**data in UI ->**
`chassis.manufacturer = Apple`
**deleted old data ->** 
`chassis. manufacturer = HP`

you want the storage to be updated

### hook =>
**old data ->** 
`chassis.manufacturer = HP`
**new data ->** 
`chassis.manufacturer = Apple`
data sent from the API =>
**updated data ->** 
`chassis.manufacturer = Apple`

### UI =>
the data is received correctly from the UI, but the old representation of the data remains.

**data in UI ->**
```
chassis.manufacturer = Apple
chassis. manufacturer = HP
```

the data in the feathers cache / storage is not updated.

### System configuration

**Module versions** (especially the part that's not working): ^3.3.1

**NodeJS version**: 10.19.0

**Operating System**: Windows

**Browser Version**: https://whatismybrowser.com/w/WCYAMJA

**React Native Version**: ----

**UI**: vue ^2.6.11

**Module Loader**: node

**Comment by daffl** [comment]
Feathers does not cache or store data on the client. As shown in the [frontend guide](https://docs.feathersjs.com/guides/basics/frontend.html) it is your responsibility to update the view based on the events that you get. Some third party plugins like [feathers-vuex](https://github.com/feathersjs-ecosystem/feathers-vuex) do this for you automatically. Issues related to those integration should be opened in those repositories.
