### ISSUE TITLE
Handling internal auth (between servers)

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers#224]
We need to start having a discussion on how we're handling between-server auth.

**Comment by marshallswain** [comment]
I suppose we could always send the user's JWT token.  :)

**Comment by daffl** [comment]
Discussion done ;) We could also provide servers with their own JWT tokens when they establish a websocket connection between each other.

**Comment by marshallswain** [comment]
Yeah.  I was originally thinking along the lines of server to server auth, but the combination of the user's JWT token and SSL kind of makes it easy.  We'd have to make sure the token is available in hooks, or maybe it would be better to create a short-lived one with the user's id.

**Comment by ekryski** [comment]
@marshallswain you nailed it man! JWT makes this easy. As long as each server has the same secret and algorithm for signing/verifying JWT's you are golden.

Literally the only thing that needs to happen is this issue: https://github.com/feathersjs/feathers-authentication/issues/52

**Comment by daffl** [comment]
Should we close this?

**Comment by ekryski** [comment]
I feel like we can. @marshallswain?

**Comment by marshallswain** [comment]
Yeah.  What we have is enough for the app.  If anything else is desired, it can be handled at the data link or network layer.
