### ISSUE TITLE
 How do I use $in of Querying to find data ？

### ISSUE THREAD

**Issue by idreamin** [feathersjs/feathers#2240]
When the length of the array is greater than or equal to 20， I use $in of Querying to find data，the following error will be reported:
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/38604167/109767033-ee688100-7c31-11eb-9a70-cefeb637b351.png">
This is my code:
<img width="339" alt="image" src="https://user-images.githubusercontent.com/38604167/109766552-48b51200-7c31-11eb-85e1-49cf2871fac8.png">

But I used $in to find the data in the MongoDB visualization tool and it was successful！
The following: 
<img width="581" alt="image" src="https://user-images.githubusercontent.com/38604167/109767737-f4ab2d00-7c32-11eb-9724-648729f32db5.png">
Please help me. Thank you very much !

**Comment by J3m5** [comment]
This limitation is enforced by the query parser [qs](https://github.com/ljharb/qs#parsing-arrays).
It can be changed by customizing it as specified [in the docs](https://docs.feathersjs.com/api/express.html#params-query).

> 
> Note: If an array in your request consists of more than 20 items, the qs parser implicitly converts
> it to an object with indices as keys. To extend this limit, you can set a custom query parser: 
> `app.set('query parser', str => qs.parse(str, {arrayLimit: 1000}))`

**Comment by idreamin** [comment]
I tried it but it didn't work. I wonder if I should put this code in app.js ?
The following:
<img width="984" alt="image" src="https://user-images.githubusercontent.com/38604167/109793602-d6075f00-7c4f-11eb-897c-827f4a54a5df.png">

**Comment by idreamin** [comment]
I tried it but it didn't work. I wonder if I should put this code in app.js ?
The following:
<img width="984" alt="109793602-d6075f00-7c4f-11eb-897c-827f4a54a5df" src="https://user-images.githubusercontent.com/38604167/109793813-19fa6400-7c50-11eb-8e70-b9dc8848407a.png">

**Comment by J3m5** [comment]
You should try to set it before express is configured, I think it will pick the setting in the app when it configure itself.

**Comment by idreamin** [comment]
> You should try to set it before express is configured, I think it will pick the setting in the app when it configure itself.

I've solved the problem，Thank you very much！Do you have WeChat？I want to send a red envelope to thank you, Ha ha.

**Comment by J3m5** [comment]
> I've solved the problem，Thank you very much！

You're welcome!

> Do you have WeChat？I want to send a red envelope to thank you, Ha ha.

No, I don't but you can find me and the others on the [Feathers Slack channel](https://join.slack.com/t/feathersjs/shared_invite/zt-n6ay47eb-HxVUa9sQtbrGyW7kcC8ICw) if you wish.

**Comment by idreamin** [comment]
> > I've solved the problem，Thank you very much！
> 
> You're welcome!
> 
> > Do you have WeChat？I want to send a red envelope to thank you, Ha ha.
> 
> No, I don't but you can find me and the others on the [Feathers Slack channel](https://join.slack.com/t/feathersjs/shared_invite/zt-n6ay47eb-HxVUa9sQtbrGyW7kcC8ICw) if you wish.

Okay.
