### ISSUE TITLE
How to pass app to Tasks? (synchronous and periodic Tasks)

### ISSUE THREAD

**Issue by arddor** [feathersjs/feathers#225]
Hello 

I need in my application several long running task which in the end will also update the database model with the new computed values. They should run when the user requests it (button press) or regularly (each week). 

- The first use case can be achieved with running the task on a socket emit:
```javascript
import socketio from 'feathers-socketio';
import task from 'task';

export default function() {
  const app = this;

  this.configure(socketio(io => {
    io.on('connection', socket => {
      socket.on('task', data => {
        task(app, data);
      });
    });
  }));
}
```
This is my separate socket config which is imported with app.configure. The main issue is that I need app in the task in order to emit some status events as well as the final database update.

- The second use case needs some cron like module to schedule and run the tasks:
```javascript
import schedule from 'node-schedule';

export default function() {
  const app = this;
  const defaultData = {};

  var j = schedule.scheduleJob('* 1 * * *', () => {
    task(app, defaultData)
  });
}
```
Again it is called with app.configure in order to get access to app. 

**My question is:** Are those the right approaches to achieve what I want with feathers? Or can this be better organized? I have just started to use feathers and had no time yet to test both methods. 

I'm thanking for any help and suggestion in advance

**Comment by marshallswain** [comment]
I think you'll want to use `feathers-hooks` for this.  [Docs here](http://docs.feathersjs.com/hooks/readme.html)  Hooks are basically "Feathers Middleware" that run no matter which provider you use (unless, of course, you customize a hook to only run on certain providers.) 

If you look at [this section of the docs](
http://docs.feathersjs.com/hooks/readme.html#servicebeforebeforehooks) you can see the `app` object is made available at `hook.app`.

**Comment by ekryski** [comment]
Hey welcome @arddor! My first question would be do you **need** to have the whole app context in your task?

Your task could in itself use `feathers-client` and the code you need to run your task. It would listen for events, compute some values, and then send the newly computed data back to your feathers app via sockets or REST calls.

**Comment by daffl** [comment]
I think your general structure makes sense as long as the long running tasks don't slow down or block the system too much in which case you may want to do what @ekryski suggested and move the task onto a separate instance.

**Comment by arddor** [comment]
@marshallswain Thank you for your suggestion. I will look into hooks.

@ekryski Thank you. I'm not necessarily need all the context I just did it now as I might need several service in one task. An additional little feathers app would make sense to relieve the load on the 'main' feathers app. I will consider it. However you would say that the general idea / structure is alright the way it is?

@daffl  Thank you. At the current planning point is hard to actually say how much load it will produce but I assume it should work out. I will go this path for now and will outsource it in a separate feathers app if I see problems.

**Comment by ekryski** [comment]
@arddor I would say go with @daffl's solution for now. Like @marshallswain said you could register a hook that for a given endpoint it spins up or calls your worker task.

Probably within a few weeks I'll have an example up of how you can have a distributed app with workers. Feel free to report back with what you've come up with.

**Comment by daffl** [comment]
`publish` callbacks shouldn't be registered dynamically on a hook, only once during application startup. I'm not sure I understand what exactly you would like to do but it seems to me that the job runner would be its own Feathers client that listens to service events and kicks off jobs accordingly.

**Comment by mkozjak** [comment]
@daffl First of all, thank you for responding so swiftly! :)

So my case is, I have a backend in feathers where I define messages meant to be sent to ws connected clients. Once the db entry is created, an aftercreate hook is hit. I would like the hook to actually schedule a one-time job, which would use my message (which will end up in a hook as `data`) at a specified time. I would also need to filter ws clients based on a few paramers of mine...

**Comment by mkozjak** [comment]
@daffl Why would I use a client? This is an example of what I want to do:

```js
  const service = app.service('messages');

  service.on("created", (msg, ctx) => {
      const d = new Date(msg.due_date)

      schedule.scheduleJob(d, () => {
          service.emit("custom", { type: "custom", data: "bar" })
      })
  })
```

Tried a few other things including `.send`, but I just can't get it to work...

**Comment by daffl** [comment]
If you are running that on your server, I don't see a reason why your code sample wouldn't work as long as you set your service up to [publish custom events](https://docs.feathersjs.com/api/events.html#custom-events) (if it should be sent to other clients).

**Comment by mkozjak** [comment]
This is really strange, actually.
I ended up trying to bruteforce everything just to see what I'm doing wrong. Here's the client:
```js
const feathers = require('@feathersjs/feathers');
const socketio = require('@feathersjs/socketio-client');
const io = require('socket.io-client');

const socket = io('http://localhost:3030');
const app = feathers();

// Set up Socket.io client with the socket
app.configure(socketio(socket));

// Receive real-time events through Socket.io
app.service('api/v1/messages').on('created', message => console.log('New message created', message))
app.service('api/v1/messages').on('updated', message => console.log('Message updated', message));
app.service('api/v1/messages').on('created api/v1/messages', message => console.log('New message created', message))
app.service('api/v1/messages').on('updated api/v1/messages', message => console.log('New message created', message))

app.service('messages').on('created', message => console.log('New message created', message))
app.service('messages').on('updated', message => console.log('Message updated', message));
app.service('messages').on('created api/v1/messages', message => console.log('New message created', message))
app.service('messages').on('updated api/v1/messages', message => console.log('New message created', message))


app.service('/api/v1/messages').on('created', message => console.log('New message created', message))
app.service('/api/v1/messages').on('updated', message => console.log('Message updated', message));
app.service('/api/v1/messages').on('created api/v1/messages', message => console.log('New message created', message))
app.service('/api/v1/messages').on('updated api/v1/messages', message => console.log('New message created', message))

socket.on('updated api/v1/messages', function(msg) { console.log("#######", msg) })
socket.on('created api/v1/messages', function(msg) { console.log("###2222", msg) })
socket.on('created api/v1/authentication', function(msg) { console.log("###3333", msg) })
```

Server logs: 
```  @feathersjs/socket-commons/channels Publishing event created api/v1/messages ```

Nothing arrives. I did nothing but add a new service called '/api/v1/messages' just to see if stock events would arrive.

**Comment by daffl** [comment]
Did you register channel publishers as shown in the [channel documentation](https://docs.feathersjs.com/api/channels.html#publishing) and the [migration guide](https://docs.feathersjs.com/migrating.html#adding-channels)?

**Comment by mkozjak** [comment]
At last I didn't. That was the problem! Thanks! And also thank you for this amazing framework!
