### ISSUE TITLE
Cant access req.files in service create(data, params) --> data.files

### ISSUE THREAD

**Issue by spiritkiddie** [feathersjs/feathers#2257]
after "app.use('/courses', upload.array('media'), new Courses(options, app));" in course.service.js i am trying to access images in course.class.js as "data.files" in create(data, params) but returns undefined

**Comment by daffl** [comment]
This is not available automatically. You can use a [custom middleware](https://docs.feathersjs.com/api/express.html#custom-service-middleware) to assign it to either `params.files` or `data.files`:

```js
app.use('/courses', upload.array('media'), (req, res, next) => {
  const { files } = req;
  req.feathers.files = files; // sets `params.files`
  req.body = { files }; // sets `data.files`

  next();
}, new Courses(options, app));
```
