### ISSUE TITLE
Cannot authenticate with socket.io

### ISSUE THREAD

**Issue by ProductOfAmerica** [feathersjs/feathers#2266]
### Steps to reproduce
1. Use my code below. (generated with typescript, nothing has changed, everything is boilerplate from CLI)
2. Start servers.
3. "undefined" is returned from the client after sending authentication.

- [x] Tell us what broke. The more detailed the better.
- [x] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc. This makes it much easier for us to debug and issues that have a reproducable example will get higher priority.

### Expected behavior
- `// authResult will be {"accessToken": "your token", "user": user }`
- It should authenticate... because I'm literally using the wiki example of feathers authentication

### Actual behavior
Fails to create a user successfully.

### System configuration
**NodeJS version**:
v14.16.0

**Operating System**:
Windows 10

**Module Loader**:
Yarn 1.17.3

# Server code:

### authentication.ts:
```typescript
import { ServiceAddons } from '@feathersjs/feathers';
import { AuthenticationService, JWTStrategy } from '@feathersjs/authentication';
import { LocalStrategy } from '@feathersjs/authentication-local';
import { expressOauth } from '@feathersjs/authentication-oauth';

import { Application } from './declarations';

declare module './declarations' {
  interface ServiceTypes {
    'authentication': AuthenticationService & ServiceAddons<any>;
  }
}

export default function (app: Application): void {
  const authentication = new AuthenticationService(app);

  authentication.register('jwt', new JWTStrategy());
  authentication.register('local', new LocalStrategy());

  app.use('/authentication', authentication);
  app.configure(expressOauth());
}
```

### app.ts:
```typescript
import path from 'path';
import favicon from 'serve-favicon';
import compress from 'compression';
import helmet from 'helmet';
import cors from 'cors';

import feathers, { HookContext as FeathersHookContext } from '@feathersjs/feathers';
import configuration from '@feathersjs/configuration';
import express from '@feathersjs/express';
import socketio from '@feathersjs/socketio';

import { Application } from './declarations';
import logger from './logger';
import middleware from './middleware';
import services from './services';
import appHooks from './app.hooks';
import channels from './channels';
import authentication from './authentication';
import mongoose from './mongoose';

const app: Application = express(feathers());
export type HookContext<T = any> = { app: Application } & FeathersHookContext<T>;

// Load app configuration
app.configure(configuration());
// Enable security, CORS, compression, favicon and body parsing
app.use(helmet({
  contentSecurityPolicy: false
}));
app.use(cors());
app.use(compress());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(favicon(path.join(app.get('public'), 'favicon.ico')));
// Host the public folder
app.use('/', express.static(app.get('public')));

// Set up Plugins and providers
app.configure(express.rest());
app.configure(socketio());

app.configure(mongoose);

// Configure other middleware (see `middleware/index.ts`)
app.configure(middleware);
app.configure(authentication);
// Set up our services (see `services/index.ts`)
app.configure(services);
// Set up event channels (see channels.ts)
app.configure(channels);

// Configure a middleware for 404s and the error handler
app.use(express.notFound());
app.use(express.errorHandler({ logger } as any));

app.hooks(appHooks);

export default app;
```
### package.json:
```json
{
  "name": "o",
  "version": "0.0.0",
  "homepage": "",
  "private": true,
  "main": "src",
  "keywords": [
  ],
  "author": {
    "name": "",
    "email": ""
  },
  "contributors": [],
  "bugs": {},
  "directories": {
    "lib": "src",
    "test": "test/",
    "config": "config/"
  },
  "engines": {
    "node": "^14.0.0",
    "yarn": ">= 0.18.0"
  },
  "scripts": {
    "test": "yarn run lint && yarn run compile && yarn run mocha",
    "lint": "eslint src/. test/. --config .eslintrc.json --ext .ts --fix",
    "dev": "ts-node-dev --no-notify src/",
    "start": "yarn run compile && node lib/",
    "mocha": "ts-mocha \"test/**/*.ts\" --recursive --exit",
    "compile": "shx rm -rf lib/ && tsc"
  },
  "standard": {
    "env": [
      "mocha"
    ],
    "ignore": []
  },
  "types": "lib/",
  "dependencies": {
    "@feathersjs/authentication": "^4.5.11",
    "@feathersjs/authentication-local": "^4.5.11",
    "@feathersjs/authentication-oauth": "^4.5.11",
    "@feathersjs/configuration": "^4.5.11",
    "@feathersjs/errors": "^4.5.11",
    "@feathersjs/express": "^4.5.11",
    "@feathersjs/feathers": "^4.5.11",
    "@feathersjs/socketio": "^4.5.11",
    "@feathersjs/transport-commons": "^4.5.11",
    "compression": "^1.7.4",
    "cors": "^2.8.5",
    "feathers-mongoose": "^8.3.1",
    "feathers-permissions": "^2.1.4",
    "helmet": "^4.3.1",
    "mongodb-core": "^3.2.7",
    "mongoose": "^5.11.9",
    "serve-favicon": "^2.5.0",
    "winston": "^3.0.0"
  },
  "devDependencies": {
    "@types/compression": "^1.7.0",
    "@types/cors": "^2.8.10",
    "@types/jsonwebtoken": "^8.5.1",
    "@types/mocha": "^8.2.2",
    "@types/serve-favicon": "^2.5.2",
    "@typescript-eslint/eslint-plugin": "^4.18.0",
    "@typescript-eslint/parser": "^4.18.0",
    "axios": "^0.21.1",
    "eslint": "^7.17.0",
    "mocha": "^8.2.1",
    "shx": "^0.3.3",
    "ts-mocha": "^8.0.0",
    "ts-node-dev": "^1.1.6",
    "typescript": "^4.1.3"
  }
}
```

# Client code:
### index.js:
```javascript
const io = require('socket.io-client');
const feathers = require('@feathersjs/feathers');
const socketio = require('@feathersjs/socketio-client');

const socket = io('http://localhost:3030');
const client = feathers();

client.configure(socketio(socket));

socket.emit('create', 'authentication', {
    strategy: 'local',
    email: 'hello4@feathersjs.com',
    password: 'supersecret'
}, function(error, authResult) {
    console.log(authResult);
    // authResult will be {"accessToken": "your token", "user": user }
    // You can now send authenticated messages to the server
});
```
### package.json:
```json
{
  "name": "testttttttt",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "@feathersjs/feathers": "^4.5.11",
    "@feathersjs/socketio-client": "^4.5.11",
    "socket.io-client": "^2.4.0"
  }
}
```

![Doesn't work](https://i.imgur.com/9hy6NU0.png)

**Comment by daffl** [comment]
The client usage is not the example from the documentation. If you use the Feathers client you should use the [authentication client as documented](https://docs.feathersjs.com/api/authentication/client.html#setup):

```js
const feathers = require('@feathersjs/feathers');
const socketio = require('@feathersjs/socketio-client');
const io = require('socket.io-client');
const auth = require('@feathersjs/authentication-client');

const socket = io('http://api.feathersjs.com');
const app = feathers();

// Setup the transport (Rest, Socket, etc.) here
app.configure(socketio(socket));

// Available options are listed in the "Options" section
app.configure(auth());

// Call in an async function
await app.authenticate({
    strategy: 'local',
    email: 'hello4@feathersjs.com',
    password: 'supersecret'
});
```

**Comment by ProductOfAmerica** [comment]
> The client usage is not the example from the documentation. If you use the Feathers client you should use the [authentication client as documented](https://docs.feathersjs.com/api/authentication/client.html#setup):
> 
> ```js
> const feathers = require('@feathersjs/feathers');
> const socketio = require('@feathersjs/socketio-client');
> const io = require('socket.io-client');
> const auth = require('@feathersjs/authentication-client');
> 
> const socket = io('http://api.feathersjs.com');
> const app = feathers();
> 
> // Setup the transport (Rest, Socket, etc.) here
> app.configure(socketio(socket));
> 
> // Available options are listed in the "Options" section
> app.configure(auth());
> 
> // Call in an async function
> await app.authenticate({
>     strategy: 'local',
>     email: 'hello4@feathersjs.com',
>     password: 'supersecret'
> });
> ```

I would like to bring this to your attention: https://docs.feathersjs.com/api/client/socketio.html#via-authentication-service

the documentation is very confusing...

**Comment by daffl** [comment]
The page you linked right at the beginning explicitly states:

> __Note:__ We recommend using Feathers and the `@feathersjs/socketio-client` module on the client if possible. If however, you want to use a direct Socket.io connection without using Feathers on the client, see the Direct connection section.

I am not sure how to make that less confusing.

**Comment by ProductOfAmerica** [comment]
> The page you linked right at the beginning explicitly states:
> 
> > **Note:** We recommend using Feathers and the `@feathersjs/socketio-client` module on the client if possible. If however, you want to use a direct Socket.io connection without using Feathers on the client, see the Direct connection section.
> 
> I am not sure how to make that less confusing.

1. The link you sent me, is the @feathersjs/authentication-client module, *not* @feathersjs/socketio-client
2. The "note" specifically says, `We recommend using Feathers and the @feathersjs/socketio-client`, again, not the @feathersjs/authentication-client module, which is the link you sent me.
3. If I'm reading the note that says "... [use the] @feathersjs/socketio-client" and I'm literally on the documentation page for @feathersjs/socketio-client, wouldn't it make sense that I would think "ok, great, I'm using the correct module"?
4. It doesn't answer the question as to why I'm getting `undefined` instead of an auth result.

**Comment by daffl** [comment]
If you `console.log(error)` in your original example you will likely see the error that occurred during authentication. Pull request clarifying the documentation are also always welcome.

**Comment by ProductOfAmerica** [comment]
> If you `console.log(error)` in your original example you will likely see the error that occurred during authentication. Pull request clarifying the documentation are also always welcome.

I would be happy to create a PR to make the documentation less confusing.

While we're on the subject of confusion... is it possible to create a new user from Socket.io? It appears from reading the example I'm using, that "create" is being called on the "authentication" service, which to me, seems like it would be the call to create a new user. I notice now that it is intended for authenticating an existing user, not creating a new user.
