### ISSUE TITLE
Realm Adapter

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers#227]
https://realm.io/ is a pretty bad-ass database for mobile. Looks like they don't support React Native yet (https://github.com/realm/realm-cocoa/issues/1921) but when they do or if we have time to help them out we should and then we could create a `feathers-realm` adapter.

**Comment by ekryski** [comment]
I noticed a couple days ago that Realm released their React Native library. So now there should be nothing holding this back. https://realm.io/docs/react-native/latest/

**Comment by marshallswain** [comment]
Well, that was good timing!

**Comment by ekryski** [comment]
@corymsmith and I will be tackling this as part of some work we are doing. Probably in the next 2-4 weeks.

**Comment by ekryski** [comment]
After actually doing a bunch with Realm this past month I think this is lower priority. There are still some things to work out with Realm. For mobile I would actually prefer an SQLite solution. Realm has some interesting idiosyncrasies that make it tricky to use in some ways and the query language is not actually that great.

**Comment by daffl** [comment]
As I mentioned in #291 should we close this issue as well then?

**Comment by ekryski** [comment]
At this point I think we can close it. Realm looked really good on the surface for React Native but after using it I was left underwhelmed. What they have to do for RN is a lot more complex than using AsyncStorage or SQLite and because they also do some live updating it would actually be a pretty complex adapter.

**Comment by n-scope** [comment]
Now that Realm has released a nodejs implementation, would you reconsider this issue ?
