### ISSUE TITLE
[Best Practice] Where should Authentication Strategies go?

### ISSUE THREAD

**Issue by sokulski** [feathersjs/feathers#2277]
When creating a custom Authentication Strategy, where is the best place to to put those?

The [Anonymous authentication](BQJ-JIHu-p2iwOUcyKMF5) section of the docs demonstrates writing the Class right inside authentication.js, though I imagine that's only recommended for simple strategies like that one.

**Comment by robbyphillips** [comment]
I like moving authentication under the services directory and grouping things there.
```
.
├── app.ts
└── services/
    └── authentication/
        ├── hooks/
        │   └── special-auth-hook.ts
        ├── strategies/
        │   ├── anonymous-strategy.ts
        │   └── custom-strategy.ts
        └── authentication.ts
```
(Also, this should probably be a "discussion" rather than an issue)
