### ISSUE TITLE
LevelDB adapter

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers#228]
We could use some help on this one.

**Comment by ahdinosaur** [comment]
if i get capacity i'd be keen to take this on. as a note, this would be a wrapper for [levelup](https://www.npmjs.com/package/levelup), so we can use [leveldown](https://www.npmjs.com/package/leveldown) (or [any other storage backend](https://github.com/Level/levelup/wiki/Modules#storage)) in node and [level-js](https://www.npmjs.com/package/level-js) in the browser.

**Comment by ekryski** [comment]
@ahdinosaur that would be awesome. It's low on our radar right now so any help we can get is amazing.

**Comment by derek-watson** [comment]
I'd be willing to take this on, I'm loving feathers and I've got some experience with levelup.

**Comment by ekryski** [comment]
@derek-watson that would be awesome. I don't think @ahdinosaur has had any time to do it yet.

**Comment by ahdinosaur** [comment]
@derek-watson sweet! :+1:

**Comment by derek-watson** [comment]
Ok great, I'll get going on this now. Are there any coding standards I should be aware of before I start?

**Comment by daffl** [comment]
You can use the [Feathers plugin](https://github.com/feathersjs/generator-feathers-plugin) Yeoman generator which initializes a standard Feathers plugin. Databases are tested against the [feathers-service-tests](https://github.com/feathersjs/feathers-service-tests). You can see how it is used in any of the existing database adapter tests (e.g. [here for feathers-memory](https://github.com/feathersjs/feathers-memory/blob/master/test/index.test.js)).

**Comment by derek-watson** [comment]
Thank you!

**Comment by derek-watson** [comment]
Hello,

I think I've finished the first version and would like some feedback: [derek-watson/feathers-levelup](https://github.com/derek-watson/feathers-levelup).

I'd be happy to write the LevelUP page on the documentation project once this is looking good.

**Comment by ahdinosaur** [comment]
looks great @derek-watson. :smile:

**Comment by derek-watson** [comment]
@ahdinosaur I'd like to finish this work and move on to something else. What is the typical process for getting something incorporated into the `feathersjs` GitHub org? What else has to happen?

**Comment by ahdinosaur** [comment]
@derek-watson speaking for myself, assuming @ekryski and @daffl are keen, the process i recently used was to transfer the repo(s) to their personal account who then transferred to the org account and added me as a contributor. this happened [here](https://github.com/feathersjs/feathers/issues/249), might be the "typical process" now.

**Comment by ekryski** [comment]
@derek-watson: @ahdinosaur nailed it. We are keen for sure! Sorry we've just been really slammed with the new 2.0 release, marketing, polishing examples, docs, all that jazz. Life should resume back to normal in a couple days and then we'll be able to properly help you and delegate stuff we need help on.

I personally am super stoked that you are so stoked to get going. This looks great!

**Comment by ekryski** [comment]
@derek-watson For this repo (and any that you transfer) you can transfer it to me and then I can transfer it to feathers. Then we'll make you a contributor and you will have full access to the repo, we'll just help maintain it :smile:

**Comment by derek-watson** [comment]
@ekryski congratulations on the 2.0 release! I have been talking it up in my part of the world quite a bit.

Transferring the `feathers-levelup` repo now, thanks for all your help team!

**Comment by marshallswain** [comment]
Woot!

**Comment by ekryski** [comment]
Ok transfered. We'll track any new issues and stuff in https://github.com/feathersjs/feathers-levelup. @derek-watson let me know if for any reason you don't have push access to the new repo and we'll fix that.
