### ISSUE TITLE
Upgrade to 5.0 beta

### ISSUE THREAD

**Issue by anyban** [feathersjs/feathers#2282]
info: Feathers application started on localhost:3030
ERROR in node_modules/@feathersjs/transport-commons/src/client.ts:69:5
TS2322: Type 'string[] | undefined' is not assignable to type 'string[]'.
  Type 'undefined' is not assignable to type 'string[]'.
    67 |
    68 |   constructor (options: ServiceOptions) {
  > 69 |     this.events = options.events;
       |     ^^^^^^^^^^^
    70 |     this.path = options.name;
    71 |     this.connection = options.connection;
    72 |     this.method = options.method;

**Comment by daffl** [comment]
What are you trying to import here?
