### ISSUE TITLE
@feathersjs/transport-commons/src/client.ts is missing from the TypeScript compilation

### ISSUE THREAD

**Issue by eduardoRoth** [feathersjs/feathers#2283]
I'm building an app with FeathersJS `5.0.0-beta.0` inside an Nx repo and I'm getting the following error when running an Angular app:

```
Error: ./node_modules/@feathersjs/transport-commons/src/client.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: /node_modules/@feathersjs/transport-commons/src/client.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at /Users/eduardoroth/trabajo/projects/apps/sensa-seguridad/node_modules/@ngtools/webpack/src/ivy/loader.js:42:26

```

**Comment by daffl** [comment]
This seems to be similar to #2282 but I'm still trying to understand what code is causing this error and what is trying to load this because all modules are being published in their transpiled version and should never point to the actual `src` files.

**Comment by eduardoRoth** [comment]
Weird thing is that my FeathersJS API server is running:
![image](https://user-images.githubusercontent.com/5419161/113355640-5330fd00-92fe-11eb-9349-84ea07d10f62.png)

Which is failing for me is the frontend app (Ionic project inside Nx repo).

**Comment by eduardoRoth** [comment]
https://github.com/feathersjs/feathers/blob/687e3c7c36904221b2707d0220c0893e3cb1faa9/packages/socketio-client/package.json#L61

Maybe there's a mismatch between versions?
![image](https://user-images.githubusercontent.com/5419161/113356378-6395a780-92ff-11eb-88ac-19fe10507455.png)

**Comment by daffl** [comment]
Yep, I think that's exactly it 😃  Fix incoming.

**Comment by daffl** [comment]
Strange that it appears to install that version even though it was a `devDependency`
