### ISSUE TITLE
OAuth2 dynamic redirect doesn't work

### ISSUE THREAD

**Issue by punund** [feathersjs/feathers#2285]
### Steps to reproduce

As per documentation, OAuth2 dynamic redirect may be set as:

    <a href='http://myserver.url/oauth/google?redirect=login'>

However, it is ignored.  If `authentication.oauth.redirect` config key is present, it is taken into account, if not, JSON is returned. The query string is never honored.

In general, I wonder what is the optimal scenario for handling redirects, as the API server may be serving varios clients, that shouldn't be obliged to pass their own URLs for redirects, but the server has no means of differentiating between them.

The documentation says that 

> ```
> <a href="/oauth/github?redirect=dashboard">
>   Login with GitHub
> </a>
> 
> ```
> With the above configuration will redirect to `https://app.mydomain.com/dashboard` after the OAuth flow.

Strictly speaking, it will redirect me to `/dashboard` on the server, not to `mydomain.com` which probably initiated the request.

**Module versions**

`4.5.11` and `5.0.0-beta.0`

**Comment by daffl** [comment]
That is how it was intended. _When_ the `authentication.oauth.redirect` option is set, the dynamic `redirect` will allow to redirect to a different path on that same url. If `authentication.oauth.redirect` is not set it will just return JSON and never redirect.

**Comment by punund** [comment]
I see, but it's not doing that.  Even if it worked it wouldn't solve the problem of an API server serving several disctinct clients.

What I ended up doing is saving `Referer:` header in the session, and then using in in the overloaded `getRedirect()` method, but somehow I doubt if this is the right approach.

**Comment by daffl** [comment]
I just tested login with Github with the [feathers-chat](https://github.com/feathersjs/feathers-chat) changing the `Login with GitHub` button to

```html
<a class="button button-primary block" href="/oauth/github?redirect=something">
  Login with GitHub
</a>
```

And it worked as expected redirecting to `/something`.

**Comment by punund** [comment]
This is because `feathers-chat` shares one host for client and server.  If you move `public/` away, tweak some URLs and serve static pages from a different port (8080), OAuth will redirect you to the server, not to the client:

    http://localhost:3030/something#access_token=eyJhbGciOi...

while it should be `localhost:8080`.

**Comment by davez345** [comment]
> I see, but it's not doing that. Even if it worked it wouldn't solve the problem of an API server serving several disctinct clients.
> 
> What I ended up doing is saving `Referer:` header in the session, and then using in in the overloaded `getRedirect()` method, but somehow I doubt if this is the right approach.

I'm facing the same issue with redirecting to multiple domains, can you please provide an example how and where did you set this session?

**Comment by daffl** [comment]
Here is a gist for a customized strategy that supports dynamic redirects to multiple clients:

https://gist.github.com/daffl/d0dee9cda7eee3d270bc99a1f1c67d9b

#2430 is also a follow-up issue for this.
