### ISSUE TITLE
Error with clear installation

### ISSUE THREAD

**Issue by Ajtak** [feathersjs/feathers#2287]
Hi. I started learning featherJS, but I get an error every time I install it. Please see the pictures with my settings and the reported error. Can anyone help me? Thanks 

Used commands:
```
$ npm install -g @feathersjs/cli
$ mkdir my-app
$ cd my-app
$ feathers generate app
$ npm start
```

![01](https://user-images.githubusercontent.com/4963819/113482335-a17d0200-949e-11eb-9e54-1c67ab4cece4.png)
![02](https://user-images.githubusercontent.com/4963819/113482338-a3df5c00-949e-11eb-857f-1699035210f1.png)

**Comment by daffl** [comment]
This is now fixed, the `latest` version on `npm` was wrong. You can either generate the application again or change the `@feathersjs/transport-commons` dependency in you `package.json` to `^4.5.11`.
