### ISSUE TITLE
[5.0.0-beta.1] NPM seems to install pre.1

### ISSUE THREAD

**Issue by eduardoRoth** [feathersjs/feathers#2289]
`npm list --depth=0` returns 5.0.0-pre.1 as latest version. even after running `npx npm-check-updates --upgrade --target newest --filter /@feathersjs/`

**Comment by eduardoRoth** [comment]
package.json

![image](https://user-images.githubusercontent.com/5419161/113647425-720df700-9650-11eb-8fdc-84e3cf64b396.png)

`npm list --depth=0`
![image](https://user-images.githubusercontent.com/5419161/113647479-818d4000-9650-11eb-8220-bb9a079775ca.png)

**Comment by eduardoRoth** [comment]
Had to set the specific version to install the right one:
![image](https://user-images.githubusercontent.com/5419161/113659321-624ddd00-9667-11eb-81bd-4bf79a538a79.png)

**Comment by daffl** [comment]
Well carp 🐟 , good catch. It appears that `-pre` is greater than `-beta` and still version compatible. I guess I'll have to change the prerelease channel back to `.pre` via https://github.com/feathersjs/feathers/pull/2292
