### ISSUE TITLE
Cannot specify passport strategy in config/default.json

### ISSUE THREAD

**Issue by ivanixgames** [feathersjs/feathers#229]
Hello,  I am trying to integrate social login with a basic app created with yeoman.

The docs (http://docs.feathersjs.com/authentication/oauth2.html) only show strategy being specified in one of the server startup js files, i presume src/app.js or src/index.js

However, I would like to keep my social login app credentials in  config/default.json as this seems where that should go.   
The problem is that there seems no way to reference the global? variable FacebookStrategy from within the config.json file.   
"strategy": "FacebookStrategy"  simply shows turns up as a string and  results in a "TypeError: Strategy is not a function"  from node_modules/feathers-authentication/lib/services/oauth2/index.js:41

"strategy": FacebookStrategy 
causes an "Unexpected token A" error in default.json file.

**Comment by daffl** [comment]
Good timing, @ekryski and I are working on integrating this today in https://github.com/feathersjs/generator-feathers. We'll let you know once the generator that includes OAuth2 is released.

**Comment by ivanixgames** [comment]
Wow! that's fast reply!
I have not fully tested, but I think I have a work around by modifying the generated app.js file as such:

let app = feathers();

app.configure(configuration(join(__dirname, '..')));
var authCfg = app.get('auth');
authCfg.facebook.strategy = require('passport-facebook').Strategy;

app.use(compress())
  .options('*', cors())
  .use(cors())
  .use(favicon( join(app.get('public'), 'favicon.ico') ))
  .use('/', serveStatic( app.get('public') ))
  .use(bodyParser.json())
  .use(bodyParser.urlencoded({ extended: true }))
  .configure(hooks())
  .configure(rest())
  .configure(socketio())
  .configure(authentication( authCfg ))
  .configure(services)
  .configure(middleware);
export default app;

**Comment by ekryski** [comment]
@ivanixgames yup that will work as a hack around for now. Thanks for reporting! We're getting close.
