### ISSUE TITLE
Suggestions to migrate to v5

### ISSUE THREAD

**Issue by matiaslopezd** [feathersjs/feathers#2293]
Hi @daffl! I want to update feathers to v5 when will stable to use in production. What do you recommend I can do for now to migrate from v3 to v5, until could be stable. Or is it better to use v4 for now?

Thanks!

**Comment by daffl** [comment]
It is stable in production when some people [test the prerelease](https://dove.docs.feathersjs.com/guides/migrating.html#testing-the-prerelease) let me know if it is stable in production 😄 If you are on v3 I definitely recommend to [upgrade to v4 first](https://docs.feathersjs.com/guides/migrating.html) though.

**Comment by matiaslopezd** [comment]
Thank you @daffl!
