### ISSUE TITLE
Unable to filter referenced models in after hook

### ISSUE THREAD

**Issue by cole-robertson** [feathersjs/feathers#2295]
I am using Feathers and I am trying to filter my model based on whether a category's subcategory has items or not.

I have an after hook like this to accomplish this:
```js
async (hook) => {
        if (hook.params.hasItems) {
          const categories = hook.result;

          const filteredCategories = [];

          for (const category of categories) {
            category.subcategories = category.subcategories.filter(
              (sub) => sub.items.length > 0
            );

            if (category.subcategories.length > 0) {
              filteredCategories.push(category);
            }
          }

          hook.result = filteredCategories;
        }
      },
```

I am able to filter my categories just fine, however it seems like no matter what I do to categories.subcategories, (the referenced model with a hasMany relation for sequelize), the subcategories always return completely unfiltered. I even have tried setting the subcategories to an empty array and there is no result.

It seems like to me Feathers/sequelize is rehydrating the properties of the model so that I cannot alter them. Is there a workaround to this?

**Comment by daffl** [comment]
When setting `raw: false` the returned Sequelize models can not be modified. See the [feathers-sequelize docs on working with model instances](https://github.com/feathersjs-ecosystem/feathers-sequelize#working-with-sequelize-model-instances).
