### ISSUE TITLE
Issue on establishing wss using Brave

### ISSUE THREAD

**Issue by aminlatifi** [feathersjs/feathers#2297]
### Actual behavior
While user can connect using Chrome or Firefox browser, it's not possible sometimes to connect by Brave. It happens periodically and is fixed after server is restarted
https://github.com/Giveth/giveth-dapp/issues/1725#issue-799518472 
### System configuration

Tell us about the applicable parts of your setup.

**Module versions** :
```
    "@feathers-plus/batch-loader": "^0.3.6",
    "@feathersjs/authentication": "2.1.7",
    "@feathersjs/authentication-jwt": "2.0.1",
    "@feathersjs/configuration": "1.0.2",
    "@feathersjs/errors": "3.3.0",
    "@feathersjs/express": "1.2.3",
    "@feathersjs/feathers": "3.1.7",
    "@feathersjs/socketio": "3.2.2",
```

**NodeJS version**: v10.23.0

**Operating System**: Linux

**Browser Version**: Latest

**React Native Version**:

**Module Loader**: npm v6.14.8

**Comment by daffl** [comment]
This problem will probably be solved [upgrading to Feathers 4](https://docs.feathersjs.com/guides/migrating.html) - v3 has not been updated with new dependencies and security updates in over two years (Node 10 will also no longer be maintained by the end of this month). I am using Brave and we have many Brave users and have never encountered this.

**Comment by aminlatifi** [comment]
> This problem will probably be solved [upgrading to Feathers 4](https://docs.feathersjs.com/guides/migrating.html) - v3 has not been updated with new dependencies and security updates in over two years (Node 10 will also no longer be maintained by the end of this month). I am using Brave and we have many Brave users and have never encountered this.

Thanks @daffl

**Comment by daffl** [comment]
Let me know if you need any help. It's always nice to see other open source projects using it (especially since I normally never learn about it). Might be a good opportunity to get everything onto some newer versions.
