### ISSUE TITLE
Documentation issue in violation of Googles TOS

### ISSUE THREAD

**Issue by LindaLawton** [feathersjs/feathers#2303]
Your documentation page found here: [Google](https://docs.feathersjs.com/cookbook/authentication/google.html#application-client-and-secret)

Contains what appears to be a Google Client id and Client secret pair.  Sharing Client Ids with others is against Google's TOS which ou agreed to when you created the project on Google Developer console.    Please see link below to Googles TOS

```
{
  "authentication": {
    "oauth": {
      "google": {
        "key": "481298021138-hv27glb811ocr7pdon5lsg8hh5a6pgjv.apps.googleusercontent.com",
        "secret": "XkWl0witdP4ogeNIgyOi-CeS",
        "scope": ["openid", "email"],
        "nonce": true
      }
    }
  }
}

```

[Changes to the Google APIs Terms of Service](https://developers.googleblog.com/2014/11/subject-changes-to-google-apis-terms-of.html)

>Asking developers to make reasonable efforts to keep their private keys private and not embed them in open source projects.

**Comment by daffl** [comment]
As the document notes at

> Note: Use the generated credentials of the OAuth client ID, the key and secret in the example no longer exist.

The keys and secret shown have never been valid. I modified them for the screenshot and the example but kept them close to what Google shows because people ended up putting in the wrong information when there wasn't a reference how it looks like.
