### ISSUE TITLE
Mounted sub-apps should hook into their parents setup

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers#232]
Initially brought up in https://github.com/feathersjs/feathers-authentication/issues/72, sub-apps will hook into their parent `setup` (so that you don't have to call a sub-apps `setup` manually) only when a real-time provider is configured. This should however always be the case.

Since it may cause odd errors (with `app.setup` being run twice) the best way is probably to change this in v3.

**Comment by sdbondi** [comment]
Hi @daffl Could you please update the docs to reflect the need to call `setup()` on sub apps?  Specifically: http://docs.feathersjs.com/middleware/routing.html - Thanks :smile:
