### ISSUE TITLE
5.0.0-pre.3 Access Token Not Being Stored

### ISSUE THREAD

**Issue by forgot** [feathersjs/feathers#2320]
Prior to `5.0.0-pre.3`, `authentication-client` allowed the access_token from an Oauth login to be stored in localStorage, but this doesn't seem to work now. What changes need to be made to re-enable this?

**Comment by daffl** [comment]
I just tested with https://github.com/feathersjs/feathers-chat/tree/dove-pre and GitHub and it seems to be working there:

<img width="950" alt="Screen Shot 2021-04-29 at 5 42 05 PM" src="https://user-images.githubusercontent.com/338316/116634914-4100a980-a912-11eb-8036-c2b47fe86576.png">

**Comment by forgot** [comment]
Hmm..maybe it's a config issue? I can confirm that the access token is being sent, but for whatever reason it's not being set in localStorage. I'll do a little more digging.

**Comment by forgot** [comment]
After a little digging, I've found a couple of things of note:

- The project you referenced isn't using `authentication-client`, and I think that's where the problem is, but I'm not 100% positive on this.
- When configuring `authentication-client` on Dove, the `storage` option doesn't seem to set, even when it uses the default, but I'm not 100% positive here either.
- I rolled back to Crow, and everything started working correctly again, so it's definitely a change between `4.5.9` and `5.0.0-pre.3`.

So, I'll do some more digging and report back here.

**Comment by daffl** [comment]
It is using the client side pre-build [here](https://github.com/feathersjs/feathers-chat/blob/dove-pre/public/index.html#L14) which includes `@feathersjs/authentication-client` (using the [default configuration](https://github.com/feathersjs/feathers-chat/blob/dove-pre/public/client.js#L9)).

Can you verify that your dependencies all updated? Often issues like that happen with a mismatch between the client and server version - although in this case, nothing in the authentication client code really changed between 4.5.9 and 5.0.0-pre. If it is a breaking change, it should be easily reproducible in a more minimal repository (e.g. based on feathers-chat) which will also make it easier to debug.

**Comment by forgot** [comment]
> It is using the client side pre-build [here](https://github.com/feathersjs/feathers-chat/blob/dove-pre/public/index.html#L14) which includes `@feathersjs/authentication-client` (using the [default configuration](https://github.com/feathersjs/feathers-chat/blob/dove-pre/public/client.js#L9)).

Apologies, I missed that...

The problem turned out to be `feathers-reactive`. After I removed it, everything started working properly again. Thank you for pointing me in the right direction!

**Comment by daffl** [comment]
Interesting. This may be because of a dependency version mismatch. Once this is a little more tested I'll look at updating all the other dependencies as well.
