### ISSUE TITLE
Update config variable dynamically thru app.set

### ISSUE THREAD

**Issue by swina** [feathersjs/feathers#2325]
### Steps to reproduce

Using nedb as local data I'm trying to switch between 2 different folders using app.set ( 'nedb' , new_path ) thru a hook.
```

...
    //change nedb path
    context.app.set ( 'nedb' , path.resolve ( data_folder ) )
   //reconfigure services
   const services = require ( '../services' )
   context.app.configure ( services )
   //checking if current data folder is correct
   console.log ( context.app.get('nedb') )
...  
```

### Expected behavior
Any service after the data folder update thru app.set should use the database in the updated folder

### Actual behavior
After set a new path for nedb any query still refers to the nedb path variable defined in the default.json

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working): above code example is set in a hook

**NodeJS version**: 12.22

**Operating System**: Win10

**Browser Version**: Chrome latest

**React Native Version**: NA

**Module Loader**: NA

**Comment by daffl** [comment]
This is currently not possible. The database model is initialized on application startup. The [upcoming v5](https://dove.docs.feathersjs.com/guides/migrating.html) will allow passing `params.adapter.Model` where you can set the model you would like to use for the request.

**Comment by swina** [comment]
Thank you for your answer! Waiting v5 !
Great job
Antonio
