### ISSUE TITLE
npm Errors When Installing on Mac OS 10.11.3 / Node 5.6.0 / npm 3.6.0

### ISSUE THREAD

**Issue by ericperez** [feathersjs/feathers#233]
I'm having a lot of problems getting the initial setup for Feathers working on the environment listed in the subject. I was following the instructions in the Quick Start but didn't get very far.  My default user does not have root access so I typically run 'npm' commands with 'sudo' so I don't get file permission errors.  

"sudo npm install -g yo generator-feathers" yields:
```
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
/usr/local/bin/yo -> /usr/local/lib/node_modules/yo/lib/cli.js

> yo@1.6.0 postinstall /usr/local/lib/node_modules/yo
> yodoctor


Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version
```

If I run 'sudo yo feathers' in a blank directory for my project, I get the following error:

```
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "feathers" "feathers-hooks" "feathers-errors" "feathers-configuration" "serve-favicon" "compression" "winston" "body-parser" "feathers-rest" "feathers-socketio" "cors" "feathers-authentication" "passport" "passport-facebook" "passport-facebook-token" "passport-github" "passport-github-token" "passport-google-oauth20" "passport-google-token" "sqlite3" "fs-extra" "sequelize" "feathers-sequelize" "--save"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! path /Users/eperez/.npm/pause/0.0.1
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir

npm ERR! Error: EACCES: permission denied, mkdir '/Users/eperez/.npm/pause/0.0.1'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, mkdir '/Users/eperez/.npm/pause/0.0.1']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/Users/eperez/.npm/pause/0.0.1',
npm ERR!   parent: 'passport' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

```

I don't get any errors when I run: "sudo yo feathers:service" but when I run "sudo npm start" I get:

```
> feathers_test@0.0.0 start /projects/feathers_test
> node src/

module.js:341
    throw err;
    ^

Error: Cannot find module 'feathers'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/projects/feathers_test/src/app.js:4:21)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! feathers_test@0.0.0 start: `node src/`
npm ERR! Exit status 1
...
```

I'm not sure if it's a bug or if I'm just missing something.

**Comment by daffl** [comment]
`yo feathers:service` only works in an initialized app which looks like it never finished because of an error that the user that `yo feathers` ran with didn't have access to the `~/.npm` directory.  I never had to use `sudo` with Node on MacOS and in my experience it generally causes more problems that it solves. If your current Node installation requires you to do that you may want to try reinstalling.

I highly recommend using [NVM](https://github.com/creationix/nvm) which makes it really easy to install and switch between Node versions, all local to your user. In a terminal with your user run:

```
$ curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh | bash
$ nvm install 5.6.0
$ nvm alias default 5.6.0
```

Then try running the Feathers generator commands again:

```
$ npm install yo feathers -g
$ mkdir myapp
$ cd myapp
$ yo feathers
```

**Comment by ekryski** [comment]
@ericperez I second nvm. Any luck with it? I don't think this is an issue with Feathers but is an issue installing things because your node environment requires root access.

**Comment by ekryski** [comment]
Looks like you'd run into it regardless of which yeoman generator you run. https://github.com/yeoman/yeoman/issues/1292

I'm going to close this since it's not feathers specific.

**Comment by ericperez** [comment]
Thanks for the details guys. I'll take a stab at using nvm.
