### ISSUE TITLE
Doesn't get events on web socket after upgrading feathers to v4

### ISSUE THREAD

**Issue by mohammadranjbarz** [feathersjs/feathers#2337]
### Steps to reproduce
After upgrading feathers in both server and client , the event listener doesn't work on frontend ( the event listener on server works, for example listening `created` events

### Expected behavior
Should get `created` events when a new entity (donations) generated

### Actual behavior
Doesnt get any event from server

### System configuration

**Module versions** (especially the part that's not working):
* These are the dependencies that doesn't work  for events like this:

```
     "@feathersjs/authentication-client": "^4.5.11",
    "@feathersjs/client": "^4.5.11",
    "@feathersjs/commons": "^4.5.11",
    "@feathersjs/express": "^4.5.11",
    "@feathersjs/feathers": "^4.5.11",
    "@feathersjs/rest-client": "^4.5.11",
    "@feathersjs/socketio": "^4.5.11",
    "@feathersjs/socketio-client": "^4.5.11",
     "feathers-hooks-common": "^5.0.5",
    "feathers-reactive": "^0.8.2",
    "socket.io-client": "^2.4.0"
```
    

 ``` 
feathers()
  .configure(
    socketio(socket, {
      timeout: 30000,
      pingTimeout: 30000,
      upgradeTimeout: 30000,
    }),
  )
  .configure(auth({ storage: localforage }))
  .configure(
    rx({
      idField: '_id',
    }),
  ).service('donations')
  .on('created', message => console.log('reactive-test New donation created', message))
```
    
* Working code and dependencies:

```
feathers()
  .configure(socketio(socket, { timeout: 30000, pingTimeout: 30000, upgradeTimeout: 30000 }))
  .configure(auth({ storage: localforage }))
  .configure(hooks())
  .configure(
    rx({
      idField: '_id',
      matcher,
    }),
  )
  .on('authenticated', feathersRest.passport.setJWT);
feathersClient
  .service('donations')
  .on('created', message => console.log('New donation created', message));
```

**dependencies**:

``` "feathers": "^2.2.3",
    "feathers-authentication-client": "^0.3.3",
    "feathers-client": "^2.3.0",
    "feathers-commons": "^0.8.7",
    "feathers-hooks": "^2.1.2",
    "feathers-hooks-common": "^3.7.2",
    "feathers-reactive": "^0.5.2",
    "feathers-rest": "^1.8.1",
    "feathers-socketio": "^2.0.1",
```

**NodeJS version**:
10
**Operating System**:
MacOs

**Comment by mohammadranjbarz** [comment]
Downgrading `feathers-socketio` fixed the issue, you can checkout my PR in our project

https://github.com/Giveth/giveth-dapp/pull/2125/files

**Comment by daffl** [comment]
Correct. v4 only works with Socket.io v2. The v5 prerelease already uses the latest Socket.io (prerelease upgrade instructions [can be found here](https://dove.docs.feathersjs.com/guides/migrating.html))
