### ISSUE TITLE
Run in production

### ISSUE THREAD

**Issue by perminder-klair** [feathersjs/feathers#234]
Hi,

Just trying out FeatherJS to setup API for one of our project. Amazing system!

Issue I got is, we have node 0.10.40 running on server (as meteorjs support that). We dont have docker yet.

Is it possible to run FeatherJs on server using node 0.10.40?
I tried and it's giving error because of ES6.

Many thanks!

**Comment by daffl** [comment]
Feathers itself is transpiled by Babel and is tested to work with Node 0.10 (see https://travis-ci.org/feathersjs/feathers).

The generated app will only work with Node 5 however. We used to have it use Babel as well but it made startup time significantly slower. There are two options:

1. Enable [Babel](https://babeljs.io/) to transpile all ES6 to ES5. The easiest way is probably via the [require hook](https://babeljs.io/docs/usage/require/).
2. Manually change all ES6 code in your application to use ES5

**Comment by perminder-klair** [comment]
Thank you @daffl of explaination,

Finally got it working using NVM and Node 5.6.0

Many thanks!

**Comment by ekryski** [comment]
@perminder-klair :+1: :tada: :rocket:!
