### ISSUE TITLE
authenticate failureredirect with typescript

### ISSUE THREAD

**Issue by joezappie** [feathersjs/feathers#2343]
### Steps to reproduce

I'm trying to show two a signin page if the user is not already authenticated with a JWT. I found this issue that stated using failureRedirect but cannot get it to work with typescript:

https://github.com/feathersjs-ecosystem/authentication/issues/648

This is my code:

```
   // Load app for authenticated users
    app.get('/*', authenticate('jwt', { failureRedirect: '/signin' }), async (req, res, next) => {
      res.render('index.html');
    });

    // Show signin for non authenticed users
    app.get('/signin', async (req, res, next) => {
      res.render('signin.html');
    });
```
With the proposed solution, I'm getting a typescript error stating its expecting a string not an object for the 2nd parameter:

> error TS2345: Argument of type '{ failureRedirect: string; }' is not assignable to parameter of type 'string'.

### Expected behavior
Type script should compile and redirect to the signin page if authentication fails.

### Actual behavior
Typescript returns a compile error not allowing an object for 2nd paramter.

### System configuration

This is almost a fresh app made with the feathers CLI.

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
All Feather modules 4.5.11

**NodeJS version**: 
14.16.0

**Operating System**:
Windows 10

**Browser Version**:
Chrome

**Comment by daffl** [comment]
That option is no longer an available in the current version and up. You can either set your own Express error handler or initialize the [`errorHandler` middleware with your own error handling](https://docs.feathersjs.com/api/express.html#express-errorhandler) that does the redirect (or anything else) you need.

**Comment by joezappie** [comment]
Thank you for the clarification on that property. I will setup my own error handler.
