### ISSUE TITLE
Support OPTIONS requests??

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers#235]

**Comment by marshallswain** [comment]
If you use the CORS module it automatically adds this.

**Comment by daffl** [comment]
Besides that, it does not seem to be used for what we think (see https://www.mnot.net/blog/2012/10/29/NO_OPTIONS).

We should however set the `Allow` header in a response that lists the HTTP methods a service supports. I created a follow-up issue at https://github.com/feathersjs/feathers-rest/issues/21 and we should probably close this one.

**Comment by ekryski** [comment]
@marshallswain I have CORS added and it didn't seem to do anything. When I issue an options request from Postman. Do I need to configure anything specific?

**Comment by ekryski** [comment]
Regardless, we can definitely close this one and just use https://github.com/feathersjs/feathers-rest/issues/21 to track progress.
