### ISSUE TITLE
Look at my new hook: feathers-validate-hook

### ISSUE THREAD

**Issue by kulakowka** [feathersjs/feathers#236]
I create a hook for json-schema validation based on [is-my-json-valid](https://www.npmjs.com/package/is-my-json-valid).

You can view it here: https://github.com/kulakowka/feathers-validate-hook

#### Usage example:

```javascript
const validateHook = require('feathers-validate-hook')

// Define schema 
const schema = {
  // Required attribute 'text' with type 'string'
  text: {
    required: true,
    type: 'string'
  }
}

// Default options for is-my-json-valid validator
const options = {
  verbose: true,
  greedy: true
}

app.service('/messages').before({
  create: [ 
    validateHook(schema, options)
  ]
})
```

Then you can test it with curl:
```bash
curl -H "Accept: application/json" -X POST http://localhost:3030/messages
```

Server response with **invalid** atttributes:
```json
{
  "name": "BadRequest",
  "message": "Validation failed",
  "code": 400,
  "className": "bad-request",
  "data": {},
  "errors": [
    {
      "field": "data.text",
      "message": "is required",
      "type": "string"
    }
  ]
}
```
Server response with **valid** atttributes:
```json
{
  "text": "Hello world",
  "errors": null
}
```

This is the first version, but it works.

I would be grateful for your feedback and recommendations for improvement.
I decided to make a separate hook for validation. Next I'll do a separate hook for transformation. To be able to modify the data (for example, .trim(), .toLowerCase(), .capitalize(), etc...).

**Comment by daffl** [comment]
This looks great! I'll give it a more in depth try and check if it works on the client (it looks like it should) later this week.

**Comment by daffl** [comment]
This looks great! I'll give it a more in depth try and check if it works on the client (it looks like it should) later this week.

**Comment by kulakowka** [comment]
Now there used ES6 syntax. It will not work on the client without transformation with the babel. I can try to modify it to make it work on the client.

**Comment by kulakowka** [comment]
I published the first version to [npm](https://www.npmjs.com/package/feathers-validate-hook), to make it easier to test.

**Comment by marshallswain** [comment]
:+1:

**Comment by ekryski** [comment]
:+1: also going to give this a try. Probably this weekend.

**Comment by ekryski** [comment]
Going to close this. @kulakowka can you add `feathers-plugin` to the `keywords` of your package.json? We'll get it listed when the new website rolls out.

**Comment by kulakowka** [comment]
Yes i will do it.
