### ISSUE TITLE
Multi tenant and mongoose connection per tenant

### ISSUE THREAD

**Issue by devops724-2** [feathersjs/feathers#2360]
Hi there
i try convert project into multi tenant in feathers
we have database connection per subdomain
we have main db that keep db connections information(tenants collection)
on start server after connect into main db query over tenant collection and find database connections 
how we can make multiple connections and per request find related connection and use it
is this approach ok?
is there any other approach that allow us connect and use related subdomain connection per request? 
best regards

**Comment by daffl** [comment]
In general I recommend to use an `organizationId` or similar property to query based on for multi tenant setups. This is much easier than handling separate databases. The [upcoming v5](https://dove.docs.feathersjs.com/guides/migrating.html) will also also allow passing `params.adapter.Model` where you can set the model you would like to use for the request.
