### ISSUE TITLE
Error when trying new Koa Adapter - TypeError: koa is not a function

### ISSUE THREAD

**Issue by jordanvector** [feathersjs/feathers#2363]
### Steps to reproduce

I am trying out the new koa adapter on the prerelease and I cannot seem to get it to work properly.  Following the directions my app.js looks like this

```
'use strict'
require('dotenv').config()
const feathers = require('@feathersjs/feathers')
const koa = require('@feathersjs/koa')
const sequelize = require('./sequelize')
const services = require('./services')
const appHooks = require('./app.hooks')
const logger = require('./logger')
const cors = require('cors')
const app = koa(feathers())
const corsOptions = {
	credentials: true,
	preflightContinue: true
}
app.use(cors(corsOptions))
    .configure(koa.rest())
	.configure(sequelize)
	.configure(services)
	.hooks(appHooks)
module.exports = app
```

### Expected behavior
App Starts successfully

### Actual behavior

TypeError: koa is not a function

### System configuration

**Module versions** (especially the part that's not working):

```
  "dependencies": {
    "@feathersjs/errors": "^5.0.0-pre.4",
    "@feathersjs/express": "^5.0.0-pre.4",
    "@feathersjs/feathers": "^5.0.0-pre.4",
    "@feathersjs/koa": "^5.0.0-pre.4",
    "@feathersjs/transport-commons": "^5.0.0-pre.4",
    "cors": "^2.8.5",
    "dotenv": "^9.0.0",
    "feathers-sequelize": "^6.2.0",
    "moment": "^2.29.1",
    "mssql": "^7.1.0",
    "pino": "^6.11.3",
    "sequelize": "^6.3.5"
  },
```

**NodeJS version**:

v15.5.0

**Operating System**:

mac os big sur

Any idea what I am doing wrong here?

**Comment by daffl** [comment]
Whoops, it should be `const { koa } = require('@feathersjs/koa')`, I should update and merge those docs. Btw, I don't think the `cors` package will work with Koa.

**Comment by jordanvector** [comment]
Ah ha progress. Ok now this looks like

```
const feathers = require('@feathersjs/feathers')
const { koa } = require('@feathersjs/koa')
const sequelize = require('./sequelize')
const services = require('./services')
const logger = require('./logger')
const app = koa(feathers())

app.configure(koa.rest())
	.configure(sequelize)
	.configure(services)
	.hooks(appHooks)
module.exports = app
```

But I am now seeing TypeError: koa.rest is not a function

is this part correct?

koa.rest()

Also thank you for all of your work on this software, its pretty awesome

**Comment by daffl** [comment]
The best reference at the moment is the test app fixture at https://github.com/feathersjs/feathers/blob/dove/packages/koa/test/app.fixture.ts which has a REST and authentication setup (oAuth is now working yet though).

**Comment by jordanvector** [comment]
@daffl just what I needed.  Working example no auth below


```
const feathers = require('@feathersjs/feathers')
const { koa, rest, bodyParser, errorHandler } = require('@feathersjs/koa')
const sequelize = require('./sequelize')
const services = require('./services')
const appHooks = require('./app.hooks')
const app = koa(feathers())

app.use(errorHandler())
app.use(bodyParser())
    .use(rest())
	.configure(sequelize)
	.configure(services)
	.hooks(appHooks)
module.exports = app
```
