### ISSUE TITLE
Embed Cookie Into OAuth Redirect Response

### ISSUE THREAD

**Issue by RickEyre** [feathersjs/feathers#2369]
Hey all,

Is there any way for me to embed a cookie in the OAuth redirect response? I'm specifically looking at the code that sends the response [here](https://github.com/feathersjs/feathers/blob/501d4164d30c6a126906dc640cdfdc82207ba34a/packages/authentication-oauth/src/express.ts#L80).

I'm aware this may not be best practice from an OAuth flow point of view. However, I really do need to get the token into a Cookie in the response for a NextJS front-end to be able to correctly gain access to the JWT server side.

I was directed to the Feathers documentation on how to do [SSR](https://docs.feathersjs.com/cookbook/express/view-engine.html#server-side-rendering). This may work, but I'm not sure how to get the session information into the response from the OAuth redirect.

**Comment by daffl** [comment]
You can still use a similar middleware and set the redirect to that endpoint. E.g. setting the oAuth `redirect` option to `/oauth-login?` with a middleware like this:

```js
  app.get('oauth-login', (req, res) => {
    const { accessToken } = req.query;

    req.session.authentication = {
      strategy: 'jwt',
      accessToken
    };
    
    res.redirect('Somewhere else');
  });
```
