### ISSUE TITLE
What about users and emails? 

### ISSUE THREAD

**Issue by kulakowka** [feathersjs/feathers#237]
What about `users` service?
Maybe we could make users service that provides the necessary functionality out of the box?
- forgot password
- reset password
- verify password

Please tell me if there are any solutions to send email?
I need to implement the letter that users receive after registering, after a password reset, and so on.

**Comment by kulakowka** [comment]
It is very important that this functionality was out of the box. I tried all the frameworks for node.js that are available today. Many boast that they can be easily integrated with React, Angular, Socket.io, etc... 

But almost nowhere banal things out of the box:
- User registration (with sending letters requesting confirmation email)
- Authorization and authentication
- Password recovery (with sending email with a link to reset your password)
- The confirmation email (with sending email with a link to confirm your email)

It is necessary in every application that I do. And every time I have to write it from scratch. 

It gives me a strong blood from an ass!

Let's do a service for sending email and user service with a basic set of functionality?
It would be great if we add it to the official repository and write documentation for it. 

I can help with the creation of these services.

**Comment by marshallswain** [comment]
I guess it's time to get to work on some of the communication plugins. 🎉

We talked about doing a Twilio plugin for SMS and one for Mandrill.  With Mandrill's recent announcement that you have to have a paid MailChimp account, we probably want to make one for Postmarkapp.com, too.

**Comment by ekryski** [comment]
> It gives me a strong blood from an ass!

LOL. Wat. (not poking fun @kulakowka. Your English is quite good. That just made me laugh really hard)

@kulakowka yes we're all in the same boat there. Like @marshallswain said we've talked about this in terms of communication plugins that register services. `feathers-authentication` was the first plugin with this sort of structure.

I would actually suggest that a `password` service could be part of `feathers-authentication`. If we added a new `sendgrid` or Amazon `ses` plugin that registers a service you would just be able to call that service from a hook. So:

```js
function sendConfirmation(){
  return function(hook) {
     return hook.app.service('sendgrid').create(options);
  }
}

app.service('password').after({
update: sendConfirmation()
});
```

**Comment by kulakowka** [comment]
@ekryski yes, my English is very bad ^_^. My native language is Russian. I try to learn English as soon as possible. But I have great difficulty. Learn javascript was much easier than English. :flushed::flushed::flushed:

**Comment by ekryski** [comment]
@kulakowka you're doing great man! Don't feel embarrassed. It just made me laugh. You're English > than my Russian :wink:

**Comment by kulakowka** [comment]
@ekryski i can give you some lessons. :beers:

Maybe we can use something like [lockit](https://github.com/zemirco/lockit) for quick solve this problem?

**Comment by ekryski** [comment]
Closing this in favour of tracking #241, #242 and https://github.com/feathersjs/feathers-authentication/issues/83

**Comment by kulakowka** [comment]
I agree. In this case, you need to do this as soon as possible. I am ready to help.
