### ISSUE TITLE
Look at my new hook: feathers-transform-hook

### ISSUE THREAD

**Issue by kulakowka** [feathersjs/feathers#238]
I create a hook for transform `hook.data` parameters with [string.js](http://stringjs.com/).

You can view it here: https://github.com/kulakowka/feathers-transform-hook

#### Usage example:

```javascript
const transformHook = require('feathers-transform-hook')

app.service('/users').before({
  create: [ 
    transformHook({
      username: v => v.toLowerCase().replaceAll(/\s/, '')
    })
  ]
})
```

Then you can test it with curl:

```
curl -H "Accept: application/json" -d "username=        adM       in" -X POST http://localhost:3030/users
```

Server response example:

```json
{
  "username": "admin"
}
```

This is the first version, but it works.

I would be grateful for your feedback and recommendations for improvement.

**Comment by kulakowka** [comment]
API changed. Now it looks as:
```javascript
app.service('/users').before({
  create: [ 
    transformHook({
      username: data => data.username.toLowerCase().replaceAll(/\s/, ''),
      slug: data => data.title.slugify()
    })
  ]
})
```

Test request:

```bash
curl -H "Accept: application/json" -d "title=Hello world&username=        adM       in" -X POST http://localhost:3030/users
```

Server response example:

```json
{
  "title": "Hello world",
  "username": "admin",
  "slug": "hello-world"
}
```

**Comment by marshallswain** [comment]
Very cool!  I look forward to trying this out.

**Comment by ekryski** [comment]
:+1: same.

**Comment by ekryski** [comment]
Going to close this. @kulakowka can you add `feathers-plugin` to the `keywords` of your package.json? We'll get it listed when the new website rolls out.

**Comment by kulakowka** [comment]
Yes i will do it.
