### ISSUE TITLE
@feathersjs@5.0.0-pre.4\express\lib\rest.js:87: Destructuring optional options throws TypeError

### ISSUE THREAD

**Issue by w0rdp1ay** [feathersjs/feathers#2391]
### Steps to reproduce
`app.use('my-svc', new MySvc());`
```
@feathersjs\express\lib\rest.js:87
            const { middleware: { before = [] } } = options;
                                  ^
TypeError: Cannot read property 'before' of undefined
```

### Expected behavior
Service is successfully registered without options. Docs: [.use(path, service [, options])](https://dove.docs.feathersjs.com/api/application.html#use-path-service-options)

### Actual behavior
A TypeError is thrown due to a destructuring statement @feathersjs@5.0.0-pre.4\express\lib\rest.js:87.

As a workaround: `app.use('my-svc', new MySvc(), { middleware: {} })`

**Comment by w0rdp1ay** [comment]
```
// @feathersjs\express\src\rest.ts:87
const before = options.middleware?.before || [];
let after = options.middleware?.after || [];
```
Possible solution?

**Comment by daffl** [comment]
I am not able to reproduce this problem - the service options for `app.mixin` will always be normalized first in https://github.com/feathersjs/feathers/blob/dove/packages/feathers/src/application.ts#L96. Can you verify you have the latest pre versions of everything and didn't change any internals yourself?

**Comment by w0rdp1ay** [comment]
My mistake.

**Comment by daffl** [comment]
Do you remember what you did for this error to happen?

**Comment by w0rdp1ay** [comment]
I had wrapped the feathers factory in another factory that returned `Object.assign(instance, { register })` where register wrapped `instance.use()`. No issues now that I'm not doing that.
