### ISSUE TITLE
Koa Adapter Does not parse query parameters with qs compared to express adapter

### ISSUE THREAD

**Issue by jordanvector** [feathersjs/feathers#2393]
Testing the new koa adapter I did find one issue with how the koa adapter parses query parameters compared to how express does documented here https://dove.docs.feathersjs.com/api/express.html#params-query

We found that instead of query parameters being parsed into its proper object, the object was being returned as a string, therefore breaking queries that would use the query object.  Long story short, I need to the add the[ koa qs](https://github.com/koajs/qs) module to my app and everything seemed to work as expected after that.

```
'use strict'
require('dotenv').config()
const feathers = require('@feathersjs/feathers')
const { koa, rest, bodyParser, errorHandler } = require('@feathersjs/koa')
const sequelize = require('./sequelize')
const services = require('./services')
const app = koa(feathers())
require('koa-qs')(app)                      //-->this line made everything work like express transport.
const logger = require('./logger')
const cors = require('@koa/cors')
const corsOptions = {
    credentials: true,
    preflightContinue: true
}
app.use(cors(corsOptions))
app.use(errorHandler({ logger }))
app.use(bodyParser())
    .use(rest())
	.configure(sequelize)
	.configure(services)

module.exports = app
```

Anyways thought I would drop this here for anyone having a similar issue with the koa adapter.

**Comment by daffl** [comment]
Good catch, this will be fixed in the next prerelease. Since it's the official query syntax it should definitely work out of the box.
