### ISSUE TITLE
'login' event firing before 'connection' when making a socket.io connection with JWT in header.

### ISSUE THREAD

**Issue by babysealclubber** [feathersjs/feathers#2396]
### Steps to reproduce
Connect to Feathers server via socket.io-client with authorization JWT in the header via **extraHeaders**.
If authentication is successful, **login** event fires followed by **connect/connection** events sometime later in a subsequent hook.

### Expected behavior
I would expect the **connect/connection** event to be triggered before the **login** event.

### Actual behavior
I am receiving the **login** event before the **connect/connection** event.

### System configuration
macOS Big Sur 11.3
Node.js 12.22.1
socket.io-client 2.4.0
@feathersjs/socketio@4.5.11

**Comment by daffl** [comment]
The order is technically correct since in this case authentication is parsed on handshake in a Socket.io middleware _before_ the connection happens. I'm pretty sure you wouldn't get a `connection` event if authentication in this case throws an error.
