### ISSUE TITLE
A swagger plugin for automatic API docs

### ISSUE THREAD

**Issue by norman784** [feathersjs/feathers#24]
Also a must have feature, if you want to share your api to other developers

``` javascript
var todos = {
  version: 1,
  find: {
    doc : {
        description: 'Return a todo list',
        // The params that the method receive
        params: [ { 
          name: 'limit', 
          description: 'determine the number of items to return',
          type: 'numeric',
          required: false
        } ],
        // An output example
        output: [{
           name: 'Todo name',
           status: 'finished'
        }]
    }
    method: function(params...){...}
  }
}

feathers().configure('documentation', true)....
```

Then you can call it just like `GET /v1/docs/todos` if documentation is set to false it the docs path will not be initialised

It was inspired on [Action Hero](https://github.com/evantahler/actionHero) api documentation method

**Comment by bkniffler** [comment]
Hey, any news on moving this to feathersjs org? Having something like swagger would be a great addition for feathers.

**Comment by ekryski** [comment]
@bkniffler I actually forgot about this! If @Glavin001 is willing to transfer it then yes we'll take it. It was written against 1.0 so might need some work in order to be compatible for 2.0 but probably not much.

I guess the only downer is this only accounts for HTTP(s) documentation and not Websockets but it would be a great addition.

**Comment by ekryski** [comment]
Re-opening for visiblity.

**Comment by Glavin001** [comment]
I also forgot about this! I have transferred feathers-swagger into the feathersjs organization.

**Comment by kulakowka** [comment]
I like the way it is implemented in [GraphQL](https://github.com/facebook/graphql) and debugging [GraphiQL](https://github.com/graphql/graphiql). The documentation is built into the application itself.

**Comment by bkniffler** [comment]
GraphQL is build on strong schema definitions that are part of the API endpoint, which makes it much easier to write something like GraphiQL. So you could either use comments and generate documentation out of them like @daffl pointed out or you let feathers understand its ORMs data schemas (https://github.com/feathersjs/feathers/issues/271) so it can create documentations automatically.

**Comment by ekryski** [comment]
Thanks @Glavin001! We'll probably need to you to add one of us as owners to the npm repo as well. :smile:

**Comment by Glavin001** [comment]
Looks like you and @daffl are owners now :smile: : https://www.npmjs.com/package/feathers-swagger
Let me know if there is anything else I can do!

**Comment by ekryski** [comment]
@Glavin001 Wicked! Thanks mate!

**Comment by daffl** [comment]
An updated version of https://github.com/feathersjs/feathers-swagger has been released and is ready to use (see the example).
