### ISSUE TITLE
Inconsistent behavior for ServiceMethods

### ISSUE THREAD

**Issue by libterty** [feathersjs/feathers#2409]
### Steps to reproduce

Hooks context arguments has inconsistent peformance.

> When you declare you routes without route parameters and let service method handles it. It will not put id into `arguments`
```typescript
// routes/index.ts
app.use('/tests', TestService)

// routes/TestServices
@hooks([
  async (ctx: HookContext, next: NextFunction) => {
    console.log('ctx.get: ', ctx.arguments) // in here it routes parameter is empty object ['something', { route: {} }]
    await next();
  }
])
public async get(id: NullableId, params: Params): Promise<string> {
  return 'get'
}
```

> When you declare you routes with route parameters and let service method handles it. It will put id into `arguments`
```typescript
// routes/index.ts
app.use('/tests/:testId/users/:userId', TestService)

// routes/TestServices
@hooks([
  async (ctx: HookContext, next: NextFunction) => {
    console.log('ctx.get: ', ctx.arguments) // here will receive routes parameter object [null, { route: { testId: '123', userId: '456' } }]
    await next();
  }
])
public async get(id: NullableId, params: Params): Promise<string> {
  return 'get'
}
```

### Expected behavior

- Would expected when we use service methods with `get`, `update` etc.. will put the key value into ctx.arguments even if the routes define is something like `/tests` without route parameter. Since it can route to correct method but it doesn't put the correct value to hook is quite weird.

### Actual behavior

- Didn't receive route value even if when the route handling is correct.

### System configuration

macOS: Big Sur 11.4
Node.js: 2.11.1
@feathersjs/feathers: 4.5.11
@feathersjs/hooks: 0.6.5

**Comment by daffl** [comment]
The path passed to `app.use` is always the top level service path. Feathers will always add an addition `path/:__feathersId` route which is what `get` (and any other method that takes an id) is mapped to.

In your second example, going to something like `/tests/123/users/456` would call your services `find` method, not the `get`. A path like `/tests/123/users/456/hello` should call `get` with `id` as  `'hello'`.
