### ISSUE TITLE
Mailer service

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers#241]
As talked about in #237 it pretty common to need to send emails from an app. Mandrill was going to be my first choice but since they killed their free tier recently, we should start with [SendGrid](https://sendgrid.com) or [mailgun](https://www.mailgun.com/) instead.

**Comment by ekryski** [comment]
@corymsmith started to go with Mailgun because it has some of the best pricing an a great API. Progress can be tracked here: https://github.com/feathersjs/feathers-mailgun.

**Comment by ekryski** [comment]
@corymsmith also created SendGrid plugin https://github.com/feathersjs/feathers-sendgrid.

**Comment by ahdinosaur** [comment]
hehe, i was thinking about this as well. today i wrote [`feathers-mailer`](https://github.com/ahdinosaur/feathers-mailer), should work with any email provider. :smiley: happy to transfer it over to `feathersjs` org if y'all are keen.

**Comment by kulakowka** [comment]
@ahdinosaur looks clean! Maybe you can integrate it with [node-email-templates](https://github.com/niftylettuce/node-email-templates)?

**Comment by ahdinosaur** [comment]
@kulakowka maybe, thanks for the suggestion. first i'll play around with [`feathers-mailer`](https://github.com/ahdinosaur/feathers-mailer) in some projects as it is.

**Comment by ekryski** [comment]
@ahdinosaur Hmm. That's pretty sweet. Some of the mail services support different options, like batch sending, group cc'ing etc. Do you know if those nodemailer transports support those as well?

If so, it might make sense to go with something like your solution and roll it in as _the_ feathers mailer. If not, then it might make more sense have yours as `feathers-mailer` and keep the other 2 @corymsmith already did. Let people choose what they want to use.

**Comment by ahdinosaur** [comment]
> Some of the mail services support different options, like batch sending, group cc'ing etc. Do you know if those nodemailer transports support those as well?

as far as i can tell, yes. the low-level transports seem to all allow for [a common high-level abstraction](https://github.com/nodemailer/nodemailer#sending-mail) (same idea as [`leveldown`](https://github.com/Level/abstract-leveldown) -> [`levelup`](https://github.com/Level/levelup)).

@kulakowka stumbled on [some docs for integrating with email templates](https://github.com/nodemailer/nodemailer#using-templates), happy to accept any pull request that implements templates in a generic way.

**Comment by ekryski** [comment]
@ahdinosaur looking at more of the node-mailer transports I think we should roll yours as *the* feathers-mailer if you are cool with it transferring it. I'd like to add a few more tests for it but since the most common use case is sending email that's probably the best one to package with the generator.

The other ones that @corymsmith made have their place if you need to manage other email platform specific options but should remain separate and are probably for more advanced scenarios.

I've created an issue to discuss how we can manage external modules https://github.com/feathersjs/feathers/issues/249

**Comment by ekryski** [comment]
re-opening for visibility

**Comment by ekryski** [comment]
Now that @ahdinosaur transferred https://github.com/feathersjs/feathers-mailer to the Feathers org that module will be the default for sending email and will come bundled with the generator (see https://github.com/feathersjs/generator-feathers/issues/58).

If someone needs to use anything a bit more specific beyond just sending email they can then use https://github.com/feathersjs/feathers-sendgrid or https://github.com/feathersjs/feathers-mailgun or write a new adapter.
