### ISSUE TITLE
How to use $select over Socket IO

### ISSUE THREAD

**Issue by AshotN** [feathersjs/feathers#2419]
What format does the Socket handler expect to get a similar result to this REST endpoint. 

`my-endpoint/6100ddb6a121a4d632e19144?$select[]=Name`

I couldn't find any similar question being asked or any documentation. If it exists and someone can point me in the right direction I would really appreciate it.

**Comment by daffl** [comment]
This is documented in https://docs.feathersjs.com/api/databases/querying.html#select. With a [direct connection](https://docs.feathersjs.com/api/client/socketio.html#direct-connection) instead of the client you'd pass just the `query` object.

**Comment by AshotN** [comment]
Ok, I figured out what I was doing wrong

I was doing

`{
  "query": {
    "$select": ["Reports"]
  }`

instead of 

`{
  "$select": [
    "Reports"
  ]
}`

Thank you
