### ISSUE TITLE
NeDB package (as used in the Feathers tutorial) is no longer maintained and includes unpatched high severity vulnerabilities

### ISSUE THREAD

**Issue by rdw-software** [feathersjs/feathers#2420]
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/crow/.github/contributing.md#report-a-bug))

- [ ] When following the tutorial at https://docs.feathersjs.com/guides/basics/generator.html, new users are creating an app that relies (amongst others) on https://github.com/louischatriot/nedb).
 
This package is no longer maintained, and in fact has at least one detected high severity vulnerability as displayed by npm:

![image](https://user-images.githubusercontent.com/16489133/127453446-b001d663-48c4-4ceb-bdda-22cab6e40ca4.png)

### Expected behavior

Either a different (still maintained) database provider should be used, or at the very least a huge warning needs to be displayed.
In any event, starting off new users with an app that relies on dependencies that are insecure and could break in the future (assuming other issues go unpatched, as well) is probably not a good starting point.

### Actual behavior

No mention of potential issues is made. Specifically, if someone new to the node ecosystem tries to follow the tutorial, they will see the warnings displayed about said vulnerabilities, and since they "require manual review" they won't know what to do about them. Subsequently, they will likely be confused and disinclined to use feathers as it doesn't bode well if the tutorial seems outdated.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working): Any

**NodeJS version**: Any

**Operating System**: Any

**Browser Version**: Any

**React Native Version**: Any

**Module Loader**: Any

**Comment by daffl** [comment]
Correct. The upcoming version 5 will use an SQL database with SQLite for the tutorial

**Comment by rdw-software** [comment]
Neat! Is there an ETA for this update? I just started looking into Feathers, if things are about to be shaken up I'll just wait a bit and re-do the tutorial afterwards (I'm not in a rush).

**Comment by daffl** [comment]
Official release will be most likely some time in October so still a little ways to go. I can keep you posted when the new tutorial is available to try in the [prerelease docs](https://dove.docs.feathersjs.com/) (probably earlier than that).

**Comment by rdw-software** [comment]
Sure! One thing that might be useful is if the prelease docs featured (or linked to) a high-level/TLDR list of changes:

![image](https://user-images.githubusercontent.com/16489133/128009142-83981465-2652-4268-a789-ab1521c90b96.png)

If it's too many, could also just link to a changelog/to GitHub.

**Comment by swina** [comment]
To use nedb you can install the package @nlt-public/nedb that fixes the underscore package vulnerability. By the way is there any support for filesystem type support in the next release of Feathers like lowdb or lokijs?

**Comment by daffl** [comment]
Feathers lets you use any db you choose in your own services and there may also be existing community adapters (e.g. https://www.npmjs.com/package/feathers-lowdb) but the default will be SQLite which is fast, can handle huge files and - unlike quite a few of the other previously supported databases and ORMs (NeDB, RethinkDB, Waterline etc.) - is very unlikely to end up being unmaintained.

**Comment by daffl** [comment]
This has been addressed https://github.com/feathersjs/generator-feathers/pull/649 to move to a newer fork but as mentioned, NeDB will no longer be used going forward.

**Comment by windymiles** [comment]
So I followed the guide for MongoDB (as apposed to SQL) and the testing page (https://feathersjs.com/guides/basics/testing.html) still suggests using NeDB for unit testing. Is there a feathers suggested alternative (for a MongoDB-like db) similar to SQLite?
