### ISSUE TITLE
ts-node-dev doesn't apply changes in auto reload

### ISSUE THREAD

**Issue by syntheticgoo** [feathersjs/feathers#2427]
### Steps to reproduce
 Clean install of current version with typescript. npm run dev in VSCode, change a file and save. Debugger does not fully restart.
### Expected behavior
`npm run dev` does not automatically restart debugger with current version of ts-node-dev and VSCode. https://stackoverflow.com/questions/62092769/ts-node-dev-doesnt-apply-changes-in-auto-reload/68731406#68731406

### Actual behavior
Terminal says restarting, but then hangs

### System configuration

To fix, need to add `--exit-child` to npm run dev script. `"dev": "ts-node-dev --no-notify --exit-child src/",`

**Comment by daffl** [comment]
Added in the [latest v5 prerelease](https://dove.feathersjs.com/). Thank you for reporting!
