### ISSUE TITLE
HookContext data typing issue for create

### ISSUE THREAD

**Issue by vrepsys** [feathersjs/feathers#2433]
Hey, ran into this typing issue, let me know if I'm missing something.

### Steps to reproduce

A simple users service with a users model and hooks.

### Actual and expected behaviour
The service's create signature (in `ServiceMethods<T>`) is the following, and allows creating multiple entities in the same go.
```
create(data: Partial<T> | Partial<T>[], params?: Params): Promise<T | T[]>;
```

However, the hook for create receives a `context` of type `HookContext<T, Service<T>>` thus context.data becomes of type `T` and the `T[]` is not possible. 
```
create: (context: HookContext<User, Service<User>>) => {
   context.data // <--- it's not clear that this can also be an array of users, because the type is `User` 
}
```

### System configuration
Current version (crow)

**Comment by daffl** [comment]
This is now possible in v5:

<img width="581" alt="Screenshot 2023-02-24 at 12 42 22" src="https://user-images.githubusercontent.com/338316/221287517-a6434352-dfd5-43b7-a3f2-35c2bd7fed61.png">
