### ISSUE TITLE
authenticate uses outdated Grant profiles, please update to latest <grant> and <grant-profile>

### ISSUE THREAD

**Issue by clevercoderAU** [feathersjs/feathers#2437]
### Steps to reproduce

Created a new Feathers app through cli - selected Google as the oAuth Strategy (just for boilerplate)
- [ ] Modified config/default.json and renamed oauth/Google to oauth/linkedin
- [ ] Filled the section out with LinkedIn API specs.
- [ ] ran server in dev mode.
- [ ] the app tries to authenticate to the wrong linkedin API (ie, API version 1) 
- [ ] I checked github grant and the profile for "linkedin" points to the correct API endpoints.
- [ ] I checked the package for @feathers/authenticate-oauth. Its using an older version of grant which lists two linkedin profiles (linkedin, linkedin2)
- [ ] I updated the config/default.json: oauth/linkedin to oauth/linkedin2.  Works fine.
- [ ] I note: linkedin version 1 is fully deprecated by LinkedIn.

### Expected behavior
default feathers authentication oauth strategy for linkedin should use linkedin v2 API

### Actual behavior
default feathers authentication oauth strategy for linkedin points to linkedin v1 API

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
authentication-oauth: 
   "grant: "^4.7.0", 
    "grant-profile": "^0.0.11"

Currently the latest grant: 
    "grant": "^5.4.16",
    "grant-profile": "^1.0.2".  <-- deprecated, grant-profile is now embedded into grant, but still holds correct API endpoints.

Also, I tried adding to package.json:
  "resolutions": {
    "grant": "^5.4.16",
    "grant-profile": "^1.0.2"
  }

but it wouldnt hold, nor work. :(

**Comment by daffl** [comment]
Due to breaking changes the latest version of Grant is only available in the v5 prerelease. You can see how to upgrade [in the migration guide](https://dove.docs.feathersjs.com/guides/migrating.html#testing-the-prerelease).

**Comment by clevercoderAU** [comment]
Oooh. Looks like there are some exciting updates in there. Cheers for your efforts.
