### ISSUE TITLE
Feathers store

### ISSUE THREAD

**Issue by naptiv** [feathersjs/feathers#244]
Is there something similar to sails-store ?
Usage exampe as sails react store : https://github.com/wi2/isomorphic-sails-react-example

**Comment by ekryski** [comment]
@naptiv That's pretty much what services are. Since feathers is isomorphic you can use services client side that automatically map to server side services. If you want to store stuff on the client as well you can use `feathers-localstorage` or `feathers-memory`.

```js
import feathers from 'feathers';
import memory from 'feathers-memory';

const app = feathers();

// user service on client mapped to backend service
let userService = app.service('users');

// message service on client using feathers memory
app.use('message', memory());
```

Then you can easily listen for events or make service calls on those services as described here: http://docs.feathersjs.com/real-time/events.html.

**Comment by naptiv** [comment]
Yep I know but the sails-store is like an out of the box store based on socket.
It's still a bit confusing for me to had the services alongside the client.

I'll spend some time on it (which whill be easier once the auth bug will be solved ^^) and come back with the problems I'll reach, anyway thanks for this awesome job, love it !

**Comment by ekryski** [comment]
@naptiv We have a tutorial coming soon that will help I think. In the mean time you could also look at the React Native app we are working on right now. Specifically, this line for listening for events https://github.com/feathersjs/feathers-react-native-chat/blob/master/components/Chat.js#L32.

Feel free to write what confuses you. We're always looking to improve the docs. It's hard to know where people will have issues when you've written the system.

**Comment by naptiv** [comment]
Feathers-react-native-chat : DOPE! <3

**Comment by ekryski** [comment]
@naptiv thanks :smile:. Still a bit of a work in progress but it's almost there for a first cut.

**Comment by ekryski** [comment]
I think how services work, and between `feathers-localstorage` and `feathers-memory` you are able to accomplish the same things as you would with sails store. We have some guides coming that will make it even more clear how you can do things with Flux and even in place of Flux.
