### ISSUE TITLE
blob storage

### ISSUE THREAD

**Issue by ahdinosaur** [feathersjs/feathers#245]
i think it's common for apps to need a way for users to upload and download binary blobs (images, videos, documents, ...). as far as i can tell, there isn't already a supported way to do this in `feathers`, beyond storing data using the existing services as base64 strings.

fortunately, there's already a [common abstraction in the JavaScript community for blob storage](https://github.com/maxogden/abstract-blob-store) which is [implemented for many existing blob stores](https://github.com/maxogden/abstract-blob-store#some-modules-that-use-this). using this, i wrote [a `feathers-blob-store` module that allows you to use any compatible blob store as a feathers service](https://github.com/ahdinosaur/feathers-blob-store), by implementing `get`, `create`, and `remove` using 'content-addressed storage' (`obj.id = hash(obj)`). i'm happy to transfer `feathers-blob-store` to the `feathersjs` org if y'all are keen. :smile_cat: 

yet, writing this module exposed an open question: how to efficiently pass data to or from a service. ideally (and especially when involving larger files) i'd like to be able to stream the data to and from the service method (TODO: write another issue focusing this into a proposal). for the moment, the only way that i know works to pass binary data is as a data URI in the JSON body. i might be missing something though, keen for feedback on my approach.

**Comment by ekryski** [comment]
@ahdinosaur oooh nice :smile:. Ya I wouldn't mind this one in the core org. Maybe just call it `feathers-blob`?

For efficiently transferring data... that's an interesting question. You could use sockets to "stream" binary data. I'd think eventually if we ever get around to implementing a WebRTC transport layer that would be pretty efficient.

**Comment by daffl** [comment]
This looks great! It would be awesome to move this to the org as `feathers-blob`. I'd actually be interested in a discussion about what everybody thinks on how to incorporate plugins that initially started outside of the organization.
Obviously with moving it there should be benefits like adding it to the main documentation and having a fall back on other NPM publishers (it's easier on GitHub but making new releases can be a bottleneck) if you are too busy. Any other thoughts?

WebRTC for Feathers would be pretty sweet. We could use it for transparent real-time communication between different Feathers client apps. Just like that.

**Comment by ekryski** [comment]
I created an issue to discuss how we would go about handling external modules. https://github.com/feathersjs/feathers/issues/249

**Comment by ekryski** [comment]
@ahdinosaur graciously transferred this to the Feathers org. Any future issues/progress can be tracked in https://github.com/feathersjs/feathers-blob.
