### ISSUE TITLE
static is reserved... rename to lazy?

### ISSUE THREAD

**Issue by FossPrime** [feathersjs/feathers#2452]
https://github.com/feathersjs/feathers/blob/98209b0c5e547d1ff88b69123895d65515d2bb3a/packages/express/src/index.ts#L14

## In dove

we can't do this:
```
import express, { static, notFound, errorHandler } from '@feathersjs/express'
```

which is laaame.

## proposal

```
import express, { lazy, notFound, errorHandler } from '@feathersjs/express'
```

**Comment by daffl** [comment]
I can add another export with a better name, just not sure if `lazy` is the right one. Maybe `serveStatic` or something like that.
