### ISSUE TITLE
Access feathersjs service in external node script (run by cron)

### ISSUE THREAD

**Issue by devops724** [feathersjs/feathers#2455]
Hi there
i try run schedules script
in this scripts in need to pass some params and query over db 
how can i access feathers services inside external scripts run in cron
best regards

**Comment by daffl** [comment]
The generated `app.js` can be imported in third party scripts like any other node module:

```js
// in src/job.js
const app = require('./app');

app.setup();

(async () => {
  const message = await app.service('messages').create({
    text: 'Message created from job'
  });
  console.log(message);
})();
```

Now you can run `node src/job`
