### ISSUE TITLE
Filtering events don't handle promises

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers#247]
I'll try and post a breaking example but I couldn't get event filters to work when a promise is used inside of it.

**Comment by daffl** [comment]
I just wrote a test like:

```js
service.filter(`created`, [
  function(data) {
    return Object.assign({ processed: true }, data);
  },
  
  function(data) {
    return new Promise(resolve =>
      setTimeout(resolve(Object.assign({ promise: true }, data)), 20)
    );
  },

  function(data, connection, hook, callback) {
    data = Object.assign({ next: true }, data);
    callback(null, data);
  }
]);
```

And it passed. Were you able to make a breaking example?

**Comment by ekryski** [comment]
I think it was either an issue with my nested promise implementation or was fixed by https://github.com/feathersjs/feathers-hooks/pull/57.
