### ISSUE TITLE
How to manage external plugins written by others?

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers#249]
I think, at a minimum, on the new website we'll have a searchable list of plugins so if the package.json has a keyword field called `feathers-plugin` it would show up. If the repo is not under the core organization then we won't "officially" support it. It's up to the creator to support it or transfer it the core org if it makes sense to do so.

The benefits of transferring it to the core org is that you have more maintainers and it will be in the core docs. If we agree to transfer it then the core team agrees to maintain it and put out an acceptable end of life date if maintenance is not going to continue.

With regards to transferring we should be able to make the original creator a collaborator through github so that they have read/write access to that specific repo. I've set up a [Feathers npm organization](https://www.npmjs.com/org/feathersjs) so we can add them as a collaborator with read/write access to their specific repo(s).

**Comment by ahdinosaur** [comment]
:+1:, makes sense to have "officially supported" modules under the `feathersjs` org, i'll try to use the generator and follow code styles for any modules i want to be included. at the moment, happy to transfer [`feathers-blob`](https://github.com/ahdinosaur/feathers-blob) and [`feathers-mailer`](https://github.com/ahdinosaur/feathers-mailer), but can't because "You don’t have admin rights to feathersjs".

**Comment by ekryski** [comment]
@ahdinosaur let me see if I can make that happen :smile:

**Comment by ekryski** [comment]
@ahdinosaur I've invited you to a private team. Once accepted I can give you admin rights temporarily and then you can transfer. Alternatively you can transfer it to me and then I can transfer it to the feathers org. Whichever works best for you!

**Comment by ahdinosaur** [comment]
@ekryski cool, transferred them to you. :dash: :baseball:

**Comment by ekryski** [comment]
@ahdinosaur awesome!! Thanks for kicking those off Mikey. They are now in the feathers org and you are added as a collaborator with write access on both.

**Comment by ekryski** [comment]
Going to close this as I think we've come up with a decent solution.
