### ISSUE TITLE
Thrown exception in hook while authenticating keeps getting thrown in all services thereafter

### ISSUE THREAD

**Issue by abscon-ditus** [feathersjs/feathers#2494]
Hello. First of all thank you to the developers and community for this great software.

I'm using a FeathersJS app generated with 'feathers generate app' with local authentication (JWT), a socket.io connection + REST and a 'users' service for the users. For this service, I added a simple 'find' hook on before:
`find: [checkUser]`
In this 'checkUser' hook function, I will sometimes throw an exception like this:
`throw new Error('Not Allowed!')`

Now, in my client app I will authenticate using:
```
feathersClient.authenticate({
    strategy: "local",
    email,
    password
});
```
The authentication process triggers my find hook 'checkUser' in Users service, **and if it throws and exception, all my other service calls (no matter which one) will throw the same exception that was thrown while authentication.**
Say for example I try to authenticate and 'Not Allowed!' exception is thrown. But then when I try to call service 'Products' which doesn't require authentication, it will throw exception 'Not Allowed!'. 
Matter of fact, the 'Products' service hooks are not even called anymore. Even stranger is the fact that feathers app doesn't even go to `'throw new Error('Not Allowed!')'` anymore. It will simple throw the exception somehow, without passing through the hook that originally threw it. It's like somehow it remembers the exception and returns it.

### Steps to reproduce
To reproduce this effect, generate an app with 'feathers generate app' with local authentication and REST + Socket.io.

Set the following hook for the users service (only checkUser hook on find is added, the rest is autogenerated):
```
const checkUser = context => {
    throw new Error('Not Allowed!');
}
before: {
  all: [],
  find: [ authenticate('jwt'), checkUser ],
  get: [ authenticate('jwt') ],
  create: [ hashPassword('password') ],
  update: [ hashPassword('password'),  authenticate('jwt') ],
  patch: [ hashPassword('password'),  authenticate('jwt') ],
  remove: [ authenticate('jwt') ]
},
```
It might require a user to be created first in order to reach the hook checkUser first. You can alternatively remove the authentication hooks.
Now generate another service, say 'Products' without authentication and without hooks. Barebone.
Now in whatever client app, first call (feathersClient being the connection to the backend):
```
feathersClient.authenticate({
    strategy: "local",
    email,
    password
});
```
This will reach checkUser hooks and throw the exception. And now try to call:
```
feathersClient.service('products').find( {} );
```
Here is the problem. This service call will return exception 'Not Allowed!'.
Also, any hooks applicable to this service call are not called. The exception is thrown before it reaches that point.

To be noted that after a while, maybe a minute or a few, the Exception is no longer thrown. Maybe something is cleared? Also, I believe if you call Products service fast enough, sometimes it manages to skip this behavior.

### Expected behavior
All services called after a failed authenticate should work.

### Actual behavior
After a failed authenticate (by an exception in a hook on the users service), all other service calls are being cancel by the same exception that was thrown while authenticating.

### System configuration

**Module versions**:

```
  "dependencies": {
    "@feathersjs/authentication": "^4.5.11",
    "@feathersjs/authentication-local": "^4.5.11",
    "@feathersjs/authentication-oauth": "^4.5.11",
    "@feathersjs/configuration": "^4.5.11",
    "@feathersjs/errors": "^4.5.11",
    "@feathersjs/express": "^4.5.11",
    "@feathersjs/feathers": "^4.5.11",
    "@feathersjs/socketio": "^4.5.11",
    "@feathersjs/transport-commons": "^4.5.11",
    "compression": "^1.7.4",
    "cors": "^2.8.5",
    "feathers-mongoose": "^8.3.3",
    "helmet": "^4.6.0",
    "mongodb-core": "^3.2.7",
    "mongoose": "^5.13.7",
    "serve-favicon": "^2.5.0",
    "winston": "^3.3.3"
  },
  "devDependencies": {
    "axios": "^0.23.0",
    "eslint": "^7.32.0",
    "mocha": "^8.4.0",
    "nodemon": "^2.0.12"
  }
```

**NodeJS version**:
v16.13.0

**Operating System**:
Windows 10

**Browser Version**:
Chrome, latest

**Comment by daffl** [comment]
The authentication client is caching the call from `authenticate` to make sure that all subsequent requests will wait for authentication (and reauthentication) to complete. It will however be reset when it fails. Are you waiting for the `feathersClient.authenticate` call to complete before making other service requests?

**Comment by abscon-ditus** [comment]
Hello, thank you for replying.

I am indeed waiting for the call using await. I am actually using a setInterval to call a service once in a while. It works good until I try to authenticate and get the exception. Then, all my service calls that are not even related receive this exception.
All subsequent calls are affect for up to a few minutes or more, I can't tell exactly if it's time related or something else. 

Can you give some direction on where is this caching done in the feathersjs library so maybe I can debug myself?

Thank you,

**Comment by daffl** [comment]
The relevant code is in https://github.com/feathersjs/feathers/blob/dove/packages/authentication-client/src/core.ts. One thing you could try and see is if `feathersClient.authentication.reset()` has any effect. This *should* already be called when an error happens though.

**Comment by abscon-ditus** [comment]
Excellent deduction David. Calling `feathersClient.authentication.reset()` after `feathersClient.logout()` solves the problem.

Thank you a lot!

**Comment by daffl** [comment]
Ah I think I see what the problem is. When an error other than 401 or 403 is thrown `reset` will not be called automatically. So if you do `throw new Error('Not Allowed!')` you will get back a 500 error. Since it is an authorization error, if you throw the right [Feathers Error](https://docs.feathersjs.com/api/errors.html#feathers-errors) everything will work as expected.
