### ISSUE TITLE
fast counting with $limit=0 not working

### ISSUE THREAD

**Issue by arkabase** [feathersjs/feathers#2497]
Hi,

I have a feathers app with feathers-mongoose as a DB adapter.
When I run a find request on my users DB collection, it returns a correct paginated result.
When I run the same request with $limit=0 in the query params, it returns a total of 0 records instead of the total count in the collection, as said in the [feathers doc](https://docs.feathersjs.com/api/databases/common.html#pagination) : 

> Pro tip: To just get the number of available records set $limit to 0. This will only run a (fast) counting query against the database.

I use curl :

```
curl -X GET https://api.local/users
{"total":24,"limit":10,"skip":0,"data":[...]}

curl -X GET https://api.local/users?'$limit=0'
{"total":0,"limit":0,"skip":0,"data":[]}
```

the last result should be `{"total":24,"limit":0,"skip":0,"data":[]}`

feathers 4.5.11
feathers-mongoose 8.4
mongoose 6.0.10
nodeJS 14.18.1
mongoDB 4.2.17

**Comment by daffl** [comment]
The request should be ` https://api.local/users?$limit=0`. I'm not sure why yours has quotes in it.

**Comment by arkabase** [comment]
the dollar is interpreted as a variable prefix by the shell. so I must quote the querystring or the whole uri

**Comment by daffl** [comment]
I'd recommend putting up a full example to reproduce. It's being tested in https://github.com/feathersjs-ecosystem/feathers-mongoose/blob/master/test/index.test.js#L52 and hasn't changed recently or been reported as an issue anywhere else.
