### ISSUE TITLE
Create a stand alone Feathers CLI

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers#250]
So my thoughts on this are it's nicer to not have to install yeoman explicitly. We also have some thoughts around being able to do `feathers deploy` or `feathers deploy:heroku` and it will deploy your app. Plus it sort of looks a little sexier to just `npm install -g feathers-cli`.

For deployment we can start small and just support heroku but I'm thinking we might want to wrap [Otto](https://www.ottoproject.io/) in the future in order to support easy dev and prod deployments.

A good start would be to create a `feathers-cli` module in it's own repo that requires the Feathers yeoman generator (`generator-feathers`) and be able to call the same generators. Then we could take it from there.

**Comment by derek-watson** [comment]
I'm interested in exploring this, @ekryski can you please provide some high-level detail?

**Comment by ekryski** [comment]
Alrighty @derek-watson! I updated the description. Let me know what you think.

**Comment by derek-watson** [comment]
I love it. Do you have any favourite cli packages to base this around? I've enjoyed using [commander](https://github.com/tj/commander.js/) in the past.

**Comment by ekryski** [comment]
@derek-watson Commander would be the one to go with I think. That's what I use.

**Comment by ekryski** [comment]
I also came across Vorpal today. Looks pretty solid too. http://vorpal.js.org/

**Comment by derek-watson** [comment]
Vorpal it is.

**Comment by derek-watson** [comment]
@ekryski I'd love some feedback on [feathersjs/feathers-cli](https://github.com/feathersjs/feathers-cli)

**Comment by ekryski** [comment]
@derek-watson that is sexy. Going to download and try it tonight.

**Comment by ekryski** [comment]
Alright, so now that work has begun on this I'm going to close and future issues and progress can be tracked in https://github.com/feathersjs/feathers-cli.
