### ISSUE TITLE
Error creating user with feathers-objection/knex/mariadb

### ISSUE THREAD

**Issue by webalizer-gt** [feathersjs/feathers#2504]
### Steps to reproduce
Generate an app as described here [https://docs.feathersjs.com/guides/basics/generator.html#generating-the-application](https://docs.feathersjs.com/guides/basics/generator.html#generating-the-application)

```
Do you want to use JavaScript or TypeScript? JavaScript
Project name test
Description 
What folder should the source files live in? src
Which package manager are you using (has to be installed globally)? npm
What type of API are you making? REST, Realtime via Socket.io
Which testing framework do you prefer? Mocha + assert
This app uses authentication Yes
Which coding style do you want to use? ESLint
What authentication strategies do you want to use? (See API docs for all 180+ supported oAuth providers) Username + Password (Local)
What is the name of the user (entity) service? users
What kind of service is it? Objection
Which database are you connecting to? MySQL (MariaDB)
What is the database connection string? mysql://root:*********@localhost:3306/test
```
I have a local MariaDB server version 10.5.12 with 'test' database created.
On first `npm run dev` the 'users' table gets created as expected.

### Expected behavior
Sending a POST request

`curl 'http://localhost:3030/users/' \
  -H 'Content-Type: application/json' \
  --data-binary '{ "email": "hello@feathersjs.com", "password": "supersecret" }'`

should create the users in users table and return

`{   
  "_id": "<random id>",
  "email": "hello@feathersjs.com",
}
`

### Actual behavior
I get the following error-message:

`{"name":"GeneralError","message":"strict mode: unknown keyword: \"0\"","code":500,"className":"general-error","errors":{}}
`

This does not happen when i use NeDB. So i assume it's somewhere in objection, knex or mariadb but i could not find a solution :-(

**Comment by windwww** [comment]
I am using objection and sqlite3. Some error occurs.

**Comment by windwww** [comment]
Oh!
In users.model.js
change
`password: 'string'`
to
`password: { type: 'string' }`

**Comment by daffl** [comment]
Closing this since the upcoming [v5](https://dove.feathersjs.com/guides/) will have a new approach on how to integrate SQL databases.
