### ISSUE TITLE
returning a single object from a services's find method is not possible

### ISSUE THREAD

**Issue by Arikael** [feathersjs/feathers#2505]
Hi

When I read the feathersjs documentation I stumbled up the following regarding[ service and its find method](https://docs.feathersjs.com/api/services.html#find-params)
> Note: find does not have to return an array; it can also return an object. The database adapters already do this for pagination.

In my project I use the mongodb adapter which inherits from `AdapterService `
AdapterService's find method signature is like `find (params?: AdapterParams): Promise<T[] | Paginated<T>> {` which does not allow for returning a single object `T` 
This contradicts the note found in the documentation,

Am I missunderstanding something?
I have a usecase where I need to return a subdocument (according to a simple query consisting of two ids) but business logic dictates that it can never exists more than once.

### Steps to reproduce

- create a service inheriting from `AdapterService<T>`
- try to return a single object `T`
### Expected behavior
- I can return a single object `T` from my service

### Actual behavior
I can only return `T[]` or `Paginated<T>`

**Comment by daffl** [comment]
The `AdapterService` is just a more specialized type of service. You'd probably just want to implement the basic `ServiceMethods` interface which allows what you want to do.

**Comment by J3m5** [comment]
Hello,

> find does not have to return an array; it can also return an object.

Technically it's true, it can return an object, a paginated response is an object.
It is not stated that it can return a single document or DB row but, more generally, an object. 

>The database adapters already do this for pagination

That is how a pagination is represented, by an object.

`Promise<T[] | Paginated<T>> ` can still contain only one document

**Comment by daffl** [comment]
To add to what @J3m5  said, the `AdapterService` is a bit more of a specialized (subset) service interface. All database adapters will always return an array or paginated data. I don't think it is easily possible to change that return signature but you could create a small wrapper service that is not an `AdapterService`, calls on the original service and returns only the one value.

**Comment by Arikael** [comment]
thank you for your comments.
I will either create a wrapper service or use the `get` method with some mandatory parameters.
