### ISSUE TITLE
schema: reusage of already existing schema will result in `never` for this property

### ISSUE THREAD

**Issue by idaho** [feathersjs/feathers#2507]
If we want to reuse an already defined schema (`schemaA`) in another schema (`schemaB`), the new type for the property where we use `schemaA` will be `never`. This depends on the current type casting in https://github.com/feathersjs/feathers/blob/f56c9e2ce61e067a4eb28b8b8c8f5d1519784170/packages/schema/src/schema.ts#L20. 
 
### Steps to reproduce

```ts
import { schema, Infer } from '@feathersjs/schema';

const schemaA = schema({
  $id: 'schemaA',
  type: 'object',
  additionalProperties: false,
  required: ['name', 'age'],
  properties: {
    name: { type: 'string' },
    age: { type: 'number' }
  }
} as const);


type SchemaA = Infer<typeof schemaA>;

const schemaB = schema({
  $id: 'schemaB',
  type: 'object',
  additionalProperties: false,
  required: ['car', 'person'],
  properties: {
    car: { type: 'string' },
    person: schemaA.definition
  }
} as const);

type SchemaB = Infer<typeof schemaB>
```

### Expected behavior

The structure of `SchemaB` should look like this example

```ts
interface SchemaB {
  car: string;
  person: {
    name: string;
    age: number;
  };
};
```

### Actual behavior

Currently, `SchemaB` has the following structure. However, `person` should have the definition of `SchemaA`, but this is currently always `never`.

```ts
interface SchemaB {
  car: string;
  person: never;
};
```

### System configuration

**Module versions** 
- @feathersjs/schema 5.0.0-pre.15
- typescript 4.5.2

**NodeJS version**: 16.13.0

**Operating System**: macOS 10.15.7

**Comment by daffl** [comment]
Well this actually ended up a little more interesting than I though. One part of the problem is that ideally we'd associate those schemas with the `$ref` keyword (since it will complain about a duplicate `$id` otherwise) but then we'd still get `never` as the type since a `$ref` can't be statically inferred. So I think we need to be able to extend inferred types which all together would look like this:

```ts
import { schema, Infer } from '@feathersjs/schema';

const schemaA = schema({
  $id: 'schemaA',
  type: 'object',
  additionalProperties: false,
  required: ['name', 'age'],
  properties: {
    name: { type: 'string' },
    age: { type: 'number' }
  }
} as const);


type SchemaA = Infer<typeof schemaA>;

const schemaB = schema({
  $id: 'schemaB',
  type: 'object',
  additionalProperties: false,
  required: ['car', 'person'],
  properties: {
    car: { type: 'string' },
    person: { $ref: 'schemaA' }
  }
} as const);

type SchemaB = Infer<typeof schemaB, {
  person: SchemaA
}>
```
