### ISSUE TITLE
feathers configuration does not load environment variable with empty string

### ISSUE THREAD

**Issue by wz5899** [feathersjs/feathers#2512]
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/crow/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc. This makes it much easier for us to debug and issues that have a reproducable example will get higher priority.

A simple example to reproduce the issue is in codesandbox: https://codesandbox.io/s/quirky-shtern-msbec?file=/src/index.js

If feathers configuration file has a variable set to an environment variable (defined in .env file and loaded by dotenv) and that environment variable is an empty string, feathers will not set the variable to empty string but instead to the name of that environment variable.

For example: 
```
// config/default.json
{
    "connection": {
      "user": "DB_USER_DEV",
      "password": "DB_PASSWORD_DEV"
    }
}

// .env
DB_USER_DEV = "root"
DB_PASSWORD_DEV = ""
```
### Expected behavior
Tell us what should happen
Expect user: root, password: ''

### Actual behavior
Tell us what happens instead
Actual: user: root, password: 'DB_PASSWORD_DEV'

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by daffl** [comment]
This is a valid issue but has already been addressed in the v5 prerelease by [replacing the environment variable substitution with what is already supported by node-config](https://dove.docs.feathersjs.com/guides/migrating.html#configuration). I recommend to try and migrate following the [prerelease migration guide](https://dove.docs.feathersjs.com/guides/migrating.html#status). An alternative would be to use a JavaScript configuration file instead and set the variable property to `{ pass: process.env.DB_PASSWORD_DEV }`
