### ISSUE TITLE
Trouble setting up subapps

### ISSUE THREAD

**Issue by RickEyre** [feathersjs/feathers#253]
I'm having trouble getting subapps to work:

**server.js**
```js
const server = feathers()
  .configure(rest())
  .use(bodyParser.json())
  .use(bodyParser.urlencoded({ extended: true }));

server.use('/v1', require('./api/v1api'));

server.listen(process.env.SERVER_PORT);
```

**api/v1api.js**
```js
const feathers = require('feathers');
const path = require('path');
const api = feathers();

[
  'myservice'
].forEach(function(servicename) {
  let service = require(path.join('../services', servicename));
  api.use('/api', service);
});

module.exports = api;
```

**myservice.js**
```js
const feathers = require('feathers');
const Service = require('feathers-sequelize').Service;
const model = require('./model');

class MyService extends Service {
  constructor() {
    super({
      Model: model,
      paginate: {
        default: 2,
        max: 4
      }
    });
  }
}

module.exports = feathers().use('/myservice', new MyService());
```

No errors on startup or at run time. When I try to `GET /v1/api/myservice` it returns 404.

As far as I can tell I've followed the documentation here?

**Comment by ekryski** [comment]
@RickEyre Did you mean to be requiring `./api/v1api`? Did you mean `./api`? Or is the `api.js` file actually `./api/v1api`?

**Comment by ekryski** [comment]
@RickEyre oh. You need to do this:

```js
[
  'myservice'
].forEach(function(servicename) {
  let service = require(path.join('../services', servicename));
  api.use(`/api/${servicename}', service);
});
```

You weren't adding the service name to the api routes. Services, the way you have them, aren't sub apps. That should fix it!

**Comment by ekryski** [comment]
I updated my comment because I missed this line: `module.exports = feathers().use('/myservice', new MyService());`. Looking again. It's probably related to this: https://github.com/feathersjs/feathers/issues/216.

**Comment by RickEyre** [comment]
> @RickEyre Did you mean to be requiring ./api/v1api? Did you mean ./api or is the api.js file actually ./api/v1api?

Yeah, the latter. Sorry about that! I've updated my example.

> I updated my comment because I missed this line: module.exports = feathers().use('/myservice', new MyService());. Looking again. It's probably related to this: #216.

Ah, okay. I was worried it might be that. Was hoping it'd work out of the box. I'll try your solution and post back. Thank you!

**Comment by ekryski** [comment]
@RickEyre I posted example that works the same way you were hoping. https://github.com/feathersjs/feathers-authentication/tree/master/examples/sub-apps2

**Comment by RickEyre** [comment]
Hmm, could it be because I configure the top level feathers app for `rest` and `bodyParser`, etc? You have that in your lowest level services. I'll try that. The first solution you recommended didn't work.

**Comment by RickEyre** [comment]
Yeah, it seems to be that. The feathers app that registers the service has to be configured with those middlewares. That's not the nicest. Probably be better to have that at your top level configuration maybe?

**Comment by ekryski** [comment]
@RickEyre ya. Unfortunately it's a bit of work to make that happen (hence why we haven't done it yet). Mostly due to resolving socket event paths and stuff. We usually recommend that when you start to break up your services into small apps that they are standalone and not mounted as sub apps.

So currently until #216 is resolved you have 3 options:

- Do like the example I posted (not ideal)
- Don't make your services sub-apps for right now just make them services like the generator would do.
- Make your services stand alone apps and use Feathers client to execute remote calls and listen for change events on these services.

**Comment by RickEyre** [comment]
> Unfortunately it's a bit of work to make that happen (hence why we haven't done it yet).

Makes sense.

Thanks for your help :smile: and for this great framework! I've got it working now.

**Comment by ekryski** [comment]
:+1: Thanks! Keep your eyes peeled for when #216 lands. In the mean time we're going to be pushing up more examples and guides.

**Comment by RickEyre** [comment]
Awesome, looking forward to it! :-)
