### ISSUE TITLE
context.StatusCode variable Not Set in app.hooks after all

### ISSUE THREAD

**Issue by palmtown** [feathersjs/feathers#2532]
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/crow/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc. This makes it much easier for us to debug and issues that have a reproducable example will get higher priority.
- [ ] featherjs app.hooks context is not returning the statusCode.

### Expected behavior
context.statusCode should be available in app.hooks after all.

### Actual behavior
context.statusCode is not set in app.hooks after all

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):  
@feathersjs/feathers 4.5.12

**NodeJS version**:
v16.13.0

**Operating System**:  
Ubuntu 20.04.3 LTS

**Browser Version**:  
n/a

**React Native Version**: 
n/a

**Module Loader**:  
n/a

**Comment by daffl** [comment]
This property is only writeable and won't be set explicitly. If the statusCode is not set, the transport will determine the correct status based on the HTTP protocol specification and the kind of Feathers error that was thrown in an error case.

**Comment by palmtown** [comment]
Hello @daffl 

Thanks for your prompt response.  My goal is to get the status code response from the request for logging purposes.  Given no statusCode response is provided in after.all context, how would one obtain it?

**Comment by daffl** [comment]
Since it is HTTP specific you could do that in a [custom service middleware](https://docs.feathersjs.com/api/express.html#custom-service-middleware) or make it a part of a [custom formatter](https://docs.feathersjs.com/api/express.html#app-configure-express-rest-formatter).

**Comment by palmtown** [comment]
Hello @daffl 

Thanks for the update.  I'll give that a try.
