### ISSUE TITLE
Push Notification Service

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers#254]
Not sure if we should bundle multiple platforms into one. I'm thinking possibly a consolidation module for separate Apple and Android push services underneath.

Apple: https://github.com/argon/node-apn
Android: https://github.com/ToothlessGear/node-gcm

Might be able to model it a bit after https://www.npmjs.com/package/node-pushserver.

**Comment by derek-watson** [comment]
We can also look at adapters for [AWS SNS](https://aws.amazon.com/sns/) and [Urban Airship](https://www.urbanairship.com/), which already have popular npm interfaces.

**Comment by harangue** [comment]
A UWP Service (Windows 10 + Windows 10 Mobile) is a must for me as well. As I mentioned to @ekryski I'd definitely take on creating / maintaining it if you all were OK with that. I think it's fine to have them as separate repos / services, as long as we have an easy / well-documented way to unify them for people who just want cross platform support. Personally I'd rather have that service handle cross platform over an external service like SNS, but maybe that's just me.

**Comment by ekryski** [comment]
After looking into this a bit more I think that we should keep them as separate modules. If we need to we can write a feathers-push consolidation module that allows you to add various transports or something so that you could, in effect, use a third party push service in the future as well.

**Comment by swarthout** [comment]
Is this feature still slated for the Auk release in July? I'm trying to decide if it would be worth it to build a custom solution or just wait for feathers push notifications to get more fleshed out. What do you recommend?

**Comment by ekryski** [comment]
@swarthout would love help here or if you've already implemented and care to share that would be great. I'm going to bump this to the Buzzard release.

**Comment by swarthout** [comment]
I built a few custom hooks for one app when I sent notifications when people commented on posts, followed users, etc. I can put the hooks into a gist if you want to see them. They are pretty rudimentary, but it would be a start. Putting it into a service would be nice.

**Comment by marshallswain** [comment]
@swarthout Do you want to at least stick them into a gist and link it here?  That would be helpful, I think.  Thank you.

**Comment by swarthout** [comment]
Here is what I did for an instagram-like app I made. The registration id is stored in the user service, and I check permissions so I don't send to a user who has disabled notifications. Right now I send through both push services, but I plan to detect operating system and have multiple devices per user in the future. Consider this a first draft. I hope this helps

https://gist.github.com/swarthout/9c33b718e9d70d068378d221b1127900

**Comment by ramsestom** [comment]
One thing to start with, I think, could be to support onesignal (https://onesignal.com/) as a push notification service. It supports all current mobile platforms and is totally free. So developing a service for it could be an easy solution to "bundle multiple platforms into one" at start.

**Comment by swarthout** [comment]
@ramsestom I think that would be really smart, especially since you can essentially wrap the notifications endpoint in a feathers service. Documentation is at https://documentation.onesignal.com/docs/server-api-overview for those who are interested. I'll play around with it this week. Are you planning on building this package or are you looking for people to take it on?

**Comment by ramsestom** [comment]
@swarthout I was planning on building a package for onesignal for my app currently in development but not before a few weeks (I have many other things to do first). So if someone want to start it, he is welcome and I would sure try to help ;)

**Comment by swarthout** [comment]
@ramsestom Conveniently enough, I am working on push notifications for an app this week, so I'll get started and publish what I have to a github repo and I can give you access

**Comment by petermikitsh** [comment]
I'll be adding push notifications to my app soon. From what I've looked through so far, it looks pretty straightforward to use existing modules (such as `node-apm`) within service hooks.

**Comment by daffl** [comment]
I'm going to close this since the core team will probably not take this on any time soon. Push notifications can be easily done through hooks and one of the existing Node wrappers.

**Comment by gauravdhiman** [comment]
@swarthout did you get chance to complete your work for push notification with OneSignal, Pushify or any other push notifier service provider ? In case you did some work, can you please share the link to it, it may be helpful for many. I am looking to implement web push-notification in my app, so looking for something which is already existing and established way.
