### ISSUE TITLE
How to secure Authentication secret (JWT)

### ISSUE THREAD

**Issue by FossPrime** [feathersjs/feathers#2547]
### Steps to reproduce

- Look for docs on how to secure JWT secret

### Expected behavior
Secrets should not be found in plain text... which makes sharing the code, open sourcing it, collaborating and deploying it more dangerous.

### Actual behavior
Secrets are handled by a node_modules dependency using a plain text config file. Meaning should the source code become exposed, the production JWT secret may become exposed.

I'm guessing there is an undocumented way of extending the config function in the Auth strategy that would allow you to inject the correct configuration. Yes, I know app.get supports env variables, but that only works on top level variables, authentication.secret is not top level. Even if it did, fetching the secret from Vault or SSH should be a documented option.

### Details

In @feathersjs/authentication v2, one could set the secret using the following API
```
// src/authentication.js
export default function () {
  const app = this
  const config = app.get('authentication')
  config.secret = envJWTSecret

  // Set up authentication with the secret
  app.configure(authentication(config))
  app.configure(jwt())
  app.configure(local(config.local))
  ...
```

https://github.com/feathersjs/feathers/blob/dove/packages/authentication/src/jwt.ts

* * *

We could override [createAccessToken](https://github.com/feathersjs/feathers/blob/dove/packages/authentication/src/core.ts#L175) and [valideateAccessToken](https://github.com/feathersjs/feathers/blob/dove/packages/authentication/src/core.ts#L197). But these are sensitive functions I'd rather not mess with.

The best way I can see is overriding [get configuration ](https://github.com/feathersjs/feathers/blob/dove/packages/authentication/src/core.ts#L108). And merging super.defaultOptions... but as this is an object getter I've never seen this done. This is the approach I'm looking into.

**Comment by daffl** [comment]
I'm pretty sure environment variables work at any level and would be the way that I'd recommend here.

**Comment by FossPrime** [comment]
https://docs.feathersjs.com/api/configuration.html#usage
```
Note: Direct access to nested config properties is not supported via app.get(). To access a nested config property (e.g. Customer.dbConfig.host, use app.get('Customer').dbConfig.host or require('config') directly and use it as documented (opens new window).
```

Looking at the code, I'd have to write a JSON env var to a file at run time and then set node-config to load that.

I went with this approach... which works as long as we don't implement a `set configuration` accessor
https://stackoverflow.com/a/34456245/370238
```
import { JWTStrategy } from '@feathersjs/authentication'
class SecureAuthenticationService extends AuthenticationService {
  get configuration() {
    const config = super.configuration
    console.log('AuthenticationService:', config)

    if (envJWTSecret) {
      config.secret = process.env.FEATHERS_SECRET
    }
    return config
  }
}
```

This gave me a small heart attack... I was using the wrong encryption secret as I forgot about this issue.

**Comment by daffl** [comment]
Hm, the note means that you'd have to do something like `app.get('authentication').secret` if you want the secret (the common question was if something like `app.get('authentication.secret')` works). Environment variable substitution should still work at every level but it has been removed in v5 which instead uses the JSON environment variable like you recommended.

**Comment by FossPrime** [comment]
I'm relieved that breaky config code is gone. We already have feathers-jwt as a LocalStorage cookie, why not make the feathers namespace be a top level configurable, so we can have FEATHERS_SECRET without conflict, in the case where you have multiple feathers apps running in the same node process. This works well in kubernetes environments where using env vars is easy, but dynamically writing files into an image is not trivial.
