### ISSUE TITLE
feather-client maybe wrong feathers.js

### ISSUE THREAD

**Issue by mhorvath** [feathersjs/feathers#255]
hi guy's,

maybe iam wrong, but when i use the feathers.js on the client side in the feathers-client package there is no hook function declared and so iam running into an error...

the correct feathers.js for the client side is implemented in the examples of feathers-authentication -> example/basic

thanks for the great work!

**Comment by ekryski** [comment]
@mhorvath Welcome :smile:! If you can post your error and/or a gist that would be really helpful. Without that we don't have the proper context to help out.

**Comment by ekryski** [comment]
Ah I realized that the examples in the docs and on the website for the browser weren't exactly copy paste. I've fixed them now and so I _think_ your issue should be resolved @mhorvath.

**Comment by mhorvath** [comment]
many thanks! i have updated all modules, implemented the correct dist/feathers.js and now it all works as excepted. yeah :)

**Comment by ekryski** [comment]
:+1: awesome to hear!
