### ISSUE TITLE
Patch method called with an undefined field does not get thru

### ISSUE THREAD

**Issue by dbvcode** [feathersjs/feathers#2553]
### Steps to reproduce
I run 2 patch queries
**A:**
`feathersApp.service('products').patch(productID, { status: 'published' });`
**B:**
`feathersApp.service('products').patch(productID, { status: undefined });`

Patch A works as expected.
In example B the patch fails.
I have logged the `context.data` in the `beforeAll` hook and instead of having `{status:undefined}` I get `{}`.
Upon further investigation I see that feathers-client is cleaning up the data object if I set it to `undefined`.
The appeal of patch is that I can only change one field. I also use a model in the typescript project so I don't want to patch with `null`.
This seems like a bug or I am missing something.

I am using `feathers-reactive` and `@feathersjs/socketio-client` and I connect like this:
```
export function fInit(options: FeathersOptions): SocketIOClient.Socket {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const _feathersAuthClient = require('@feathersjs/authentication-client').default;
    const _feathersApp = feathers();
    let _socket: SocketIOClient.Socket;
    options.noLogging ? noLogging = true : null;

    if (options.email !== undefined && options.pass !== undefined) {
        authCred.email = options.email;
        authCred.pass = options.pass;
    }

    if (options.onlySocketIOTransport) {
        _socket = io(options.feathersIP, {
            transports: ['websocket'],
            forceNew: true,
            path: '/s/'
        });
    } else {
        _socket = io(options.feathersIP, { path: '/s/' });
    }

    if (options.storage === undefined) {
        _feathersApp
            .configure(feathersSocketIOClient(_socket)) 
            .configure(_feathersAuthClient())
            .configure(feathersRx({ 
                idField: '_id'
            }));
    } else {
        _feathersApp
            .configure(feathersSocketIOClient(_socket))
            .configure(_feathersAuthClient({   
                storage: options.storage
            }))
            .configure(feathersRx({
                idField: '_id'
            }));
    }
    return _socket;
}
```

### Expected behavior
I would expect for my `data` object to get to the db and patch that one field in db (mongo) and set it to `undefined`.

### Actual behavior
I get the old object back as the data that gets thru is `{}` and the patch returns the 'new' old object.

### System configuration
I am using these modules to connect to the API
```
import * as feathersRx from 'feathers-reactive';
import * as io from 'socket.io-client';
import feathers from '@feathersjs/feathers';
import feathersSocketIOClient from '@feathersjs/socketio-client';
```

**Module versions** (especially the part that's not working):
    "@feathersjs/authentication": "^4.5.12",
    "@feathersjs/authentication-client": "^4.5.13",
    "@feathersjs/authentication-local": "^4.5.12",
    "@feathersjs/authentication-oauth": "^4.5.12",
    "@feathersjs/configuration": "^4.5.12",
    "@feathersjs/express": "^4.5.12",
    "@feathersjs/socketio": "^4.5.13",
    "@feathersjs/socketio-client": "^4.5.13",
    "feathers-authentication-management-ts": "^2.1.2",
    "feathers-blob": "^2.6.0",
    "feathers-casl": "^0.7.1",
    "feathers-hooks-common": "^5.0.6",
    "feathers-mongodb": "^6.4.1",
    "feathers-reactive": "^0.8.2",
    "feathers-validate-joi": "^4.0.1",

**NodeJS version**:
v14.18.3

**Operating System**:
Linux

**Browser Version**:
Firexox

**React Native Version**:
---
**Module Loader**:
---

**Comment by dbvcode** [comment]
The workaround for now is to use `$unset`:

`feathersApp.service('products').patch(productID, { $unset: {status:''} });`

Should this be like this? Or should the `status:undefined` work?

**Comment by robbyphillips** [comment]
I'm pretty sure this is because there's no way to serialize `undefined` over the wire, not really a feathers specific thing.

```js
JSON.stringify({ a: undefined })
// => result '{}'
```

**Comment by dbvcode** [comment]
Shouldn't this be something the feathers-client needs to worry about?

**Comment by daffl** [comment]
I don't think there is anything the Feathers client can do since it is just how standard JavaScript object serialization works.
