### ISSUE TITLE
Reactive real-time APIs

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers#256]
I started prototyping [RX.js](https://github.com/Reactive-Extensions/RxJS) extensions for Feathers APIs.

## The challenge

Currently you have to listen to `created`, `updated`, `patched` and `removed` events yourself and update any client side state manually. For example:

```js
const socket = io('http://api.my-feathers-server.com');
const app = feathers().configure(socketio(socket));
const messageService = app.service('messages');

// Maintains a list of messages
const messages = [];

// Find all messages and push them into our messages list
messageService.find().then(data => messages.push(... data));

// Listen to `created` events and push to the list
messageService.on('created', message => messages.push(message));

// Listen to `patched` events and update an existing message
messageService.on('patched', message => {
  messages.forEach(current => {
    if(current.id === message.id) {
      Object.assign(current, message);
    }
  });
});
```

This can become a little cumbersome and while it is easily possible to make framework specific integrations (e.g. see [canjs-feathers](https://github.com/feathersjs/canjs-feathers)) I believe it is worth investigating a more generalized approach.

## A solution: Reactive programming

> RxJS is a set of libraries to compose asynchronous and event-based programs using observable collections and Array style composition in JavaScript.

This solves exactly the problem shown above by combining promises and different events into a single stream:

```js
const rx = require('feathers-rx');
const socket = io('http://api.my-feathers-server.com');
const app = feathers()
  .configure(rx())
  .configure(socketio(socket));

const messageService = app.service('messages');

// Get a specific message with id 10. Emit the message data once it resolves
// and every time it changes e.g. through an updated or patched event
messageService.get(10).subscribe(message => console.log('Message is', message));

// Find all messages and emit a new list every time anything changes
messageService.find().subscribe(messages => console.log('New message list', messages));
```

This works great out of the box with reactive UI libraries like React and [Yolk](https://github.com/garbles/yolk) and UIs created in functional languages like [Clojure(script)](http://clojure.org/index).

I am looking forward to working on this plugin because it will make it even easier to build real-time UIs with client-side Feathers.

**Comment by ekryski** [comment]
@daffl this is excellent! :tada: We've talked about this for a while and can't wait to see this land.

For a subscribe on `messages.get` would you also get notified through that same stream if the message was removed?

**Comment by daffl** [comment]
Probably. I was thinking it should just emit `null` in that case.

**Comment by ekryski** [comment]
That was my thought as well. :+1:

**Comment by marshallswain** [comment]
🎇🐰🎩
magic.

**Comment by naptiv** [comment]
looks promising :+1:

**Comment by ekryski** [comment]
After hanging with @garbles yesterday, @daffl you and him should sync up. He would be an invaluable asset in helping us get this supported. I'm hoping for commits :wink: but at least in terms of design direction.

**Comment by petermikitsh** [comment]
This is a really sensible move. Chances are if you are querying for any initial data, you're going to want to know of any changes to that set. And as mentioned, it would play very nicely with react.

I found the way [Meteor did pub/sub](https://www.discovermeteor.com/blog/understanding-meteor-publications-and-subscriptions/) to be fairly elegant. If we had something similar in feathers, it would be a pretty cool feature.

**Comment by ekryski** [comment]
@petermikitsh Thanks for linking that article. I actually think this would be pretty easy. What I'm about to say isn't a fully baked solution, the reactive stuff probably is the better solution to this, but off the top of my head I think we have most of the pieces are already there:

- You can already query your data and filter it already using `app.service('messages').find(query).then...`
- You can filter socket events going out already (http://docs.feathersjs.com/real-time/filtering.html)

So really all you need to do is set up your `create`, `update`, and `remove` listeners in the client and be able to pass query params to them, effectively defining a `where` clause for a given service for a given socket). Your socket filters on the server side would then inspect those socket filters using `socket.feathers.query` and only send data that matches that query, for a given resource, on that socket.

The trick might be negotiating priority over hooks. Which takes priority in filtering data? The socket `query` or a developer specified hook filter? My thought is the former.

cc/ @daffl

**Comment by jonjamz** [comment]
@ekryski Are you essentially saying that the server-side hooks could define a higher-level space to work in (for example, a user can have access to all their own data) and then from the client-side we could pass in more specific filters within that space? Because that would be really cool.

**Comment by petermikitsh** [comment]
Probably out of scope, and I am unsure of its feasibility, but it would be cool if you could reactively watch a raw query.

Use case: Suppose I have an administrative dashboard and want to show, in realtime, the total number of User objects in my database, but didn't want to have to send down the entire list of users to the client for computation, as the payload would be far too large to load on the client.

e.g., `app.service('users').find('SELECT COUNT(*) FROM users;').then...`. Since we have an ORM wrapper associated with each service, I am kind of doubting this being an easy feature to add, but at least it's been documented. The way services are currently structured, they essentially have a 1:1 map with a single model in the data layer.

Since this is a simple and contrived example, it has a pretty straightforward 'workaround' where you could create a new service (e.g., the `analytics` service) for storing the count as a denormalized value. Collection hooks could be applied to the `users` service increment and decrement the count of user objects. However, for more complex queries, or queries involving multiple models or services, this could be inconvenient or perhaps not even apply.

I don't think you can even reactively retrieve a `count` from RethinkDB, so like I said, total stretch.

**Comment by daffl** [comment]
@petermikitsh For count specifically that could work already with the proposed API (and [database adapter pagination enabled](http://docs.feathersjs.com/databases/pagination.html)) as

```js
app.service('users').find().map(page => page.total).subscribe(count => console.log('Count is', count));
```

I think we can cover most Feathers query cases. It does get tricky when including `$limit` or special queries like `$gt` etc. but I think I'm slowly figuring it out and will hopefully have a first prototype up soon.

**Comment by daffl** [comment]
You can find current progress in the [feathers-rx](https://github.com/feathersjs/feathers-rx) repository.

**Comment by daffl** [comment]
The repository has been renamed to [feathers-reactive](https://github.com/feathersjs/feathers-reactive) and is ready for beta testing. I'm going to close this issue, lets keep track of everything else over there.
