### ISSUE TITLE
Pagination and query TypeScript improvements

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers#2564]
The current TypeScript related improvements in v5 are pretty solid but the following improvements should still be included:

- **Typed queries**: This would allow to type `params.query` which will play well with the new schema types.
- **Inferred pagination**: The return value for a `find` is currently `Paginated<T>|T[]` which means you always have to cast the result. We should find a way to either set a fixed `find` return value or infer it from the `paginate` settings.

**Comment by seonglae** [comment]
Inferred pagination is needed for jsdoc which has no manual type casting

**Comment by daffl** [comment]
@seonglae The way it is implemented in #2605 still allows both signatures so that should still be possible.
