### ISSUE TITLE
Slackbot service

### ISSUE THREAD

**Issue by corymsmith** [feathersjs/feathers#257]
A Slackbot service would be pretty useful and fairly simple to implement the most common cases. Slack's API is really solid or we can just wrap a lib like this: https://github.com/mishk0/slack-bot-api

May whip a simple version up up this week / weekend if I have some time.

**Comment by derek-watson** [comment]
What are the most common cases? I have some energy for this and experience building slack bots if anyone needs a hand.

**Comment by corymsmith** [comment]
@derek-watson The most common use cases would probably be to post to a channel or message a user

**Comment by daffl** [comment]
Closing since it doesn't look like anybody has the time to look into this in the near future.
