### ISSUE TITLE
Run migrations at each app startup

### ISSUE THREAD

**Issue by strarsis** [feathersjs/feathers#2573]
It would be great if at each app startup the database migrations can be re-run (this should be idempotent).
I use KnexJS (for SQLite) with FeathersJS and I added a table field/column to the model.
When starting the FeathersJS app, the migrations aren't re-run that would add this field.
Only when the database (`src.sql` in this case) doesn't exist, FeathersJS runs the migrations.

**Comment by DaddyWarbucks** [comment]
Feathers core doesn't know anything about migrations. I usually handle this via scripts in the `package.json`. For example

```
"dev": "migrate && nodemon src/",
"migrate": "whatever your Knex or whatever migration CLI command is"
```

You can also do this on the `postinstall` script, which is generally a good place to do this when deploying the app to production. 

```
"dev": "migrate && nodemon src/",
"postinstall": "migrate"
"migrate": "whatever your Knex or whatever migration CLI command is"
```

**Comment by marshallswain** [comment]
100% what @DaddyWarbucks said.  We want to keep Feathers decoupled from migrations, etc.

**Comment by marshallswain** [comment]
Since he has already provided a good description of the correct solution, I'll go ahead and close this.  Thank you for using Feathers!
