### ISSUE TITLE
Get full API URL

### ISSUE THREAD

**Issue by strarsis** [feathersjs/feathers#2580]
For some applications it is very useful to get the complete API URL of the FeathersJS app.
Currently that URL has to be cobbled together using `context.app.settings.host` and `context.app.settings.port`, 
but other options may also apply (like a base path) - so this approach is additionally to being tedious also very brittle.

**Comment by ShinChven** [comment]
I think `context.app.settings.host` does not represent the external domain for your API.
You should add another field in `config.json` to store the domain you use.

**Comment by strarsis** [comment]
@ShinChven: Yes, the listen host/IP/IP mask (`localhost` or <some IP> or `0.0.0.0`) is not the same as the public URL. I use separate config field for the public API URL now (e.g. `https://api.app.example.com`).

Does FeathersJS have "default" configuration fields, and would it make sense to add a new one for the public API URL? At least for the default/primary one (different API URLs may be used, depending on the particular API/FeathersJS-level load-balancing and such).

**Comment by ShinChven** [comment]
I don't think it's a thing a web application should handle itself, for DNS configuration might be changed in production.
However it is possible to detect the domain/origin/host that clients are using to connect this app if you use a [reverse proxy](https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/#:~:text=proxy_set_header%20Host%20%24host%3B).
