### ISSUE TITLE
Bug Dove - query returns all data if there is a key that is not present in model

### ISSUE THREAD

**Issue by xbubus** [feathersjs/feathers#2581]
### Steps to reproduce

Run the same service on Feathers v4 and Feathers v5.0.0-pre.17

```
GET {{backendURL}}/admin/users?login=gugu.123@gmail.com
```
returns on both feathers v4 and v5 correct:
```
[
    {
        "name": "asdf1234",
        "email": "gugu.123@gmail.com",
        "login": "gugu.123@gmail.com",
        "preferences": {
            "locale": "pl-PL",
            "timezone": "Europe/London"
        },
        "createdAt": "2022-03-15T09:15:03.570Z",
        "id": "62305917fcd48aaf2ecf6723"
    }
]
```

```
GET {{backendURL}}/admin/users?asdfgh=lololo  
```
(key asdfgh does not exist in model)
reutnrs empty list on v4:
```
[]
```
returns list with all users on v5.0.0-pre.17
```
[
    {
        "name": "asdf1234",
        "email": "gugu.123@gmail.com",
        "login": "gugu.123@gmail.com",
        "preferences": {
            "locale": "pl-PL",
            "timezone": "Europe/London"
        },
        "createdAt": "2022-03-15T09:15:03.570Z",
        "id": "62305917fcd48aaf2ecf6723"
    },
    {
        "name": "baba",
        "email": "baba.123@gmail.com",
        "login": "baba.123@gmail.com",
        "preferences": {
            "locale": "en-GB",
            "timezone": "Europe/London"
        },
        "createdAt": "2022-03-15T09:14:45.350Z",
        "id": "62305905fcd48aaf2ecf671e"
    },
    {
        "name": "xxxx",
        "email": "xxxx@gmail.com",
        "preferences": {
            "locale": "en-GB",
            "timezone": "Europe/London"
        },
        "login": "xxxx@gmail.com",
        "createdAt": "2021-09-22T09:37:45.260Z",
        "lastLoginAttempt": "2022-03-15T09:27:08.577Z",
        "loginAttempts": 0,
        "id": "614af9693af92a3bc474bcd3"
    }
]
```

### Expected behaviour
In my opinion it should reutrn allways empty list if query does not match.

Can you tell me if it is bug or just logic of queries will change in official v5 release?

**Comment by daffl** [comment]
That is definitely not something that should've changed. Which database adapter are you using? Can you make a reproducible example?

**Comment by xbubus** [comment]
@daffl 

I am using moongose db adapter.

So the example:
```
const feathers = require('@feathersjs/feathers');
const {Service} = require('feathers-mongoose');
const mongoose = require('mongoose');
const app = feathers();
mongoose.connect('mongodb://localhost:27017/feathers-test');
class MessageService extends Service {
    constructor(options) {
        super(options);
    }
}
app.use('messages', new MessageService({
    Model: mongoose.model('msgs',new mongoose.Schema({
        id: Number,
        text: String
    })),
    multi:true // allow to delete multiple msgs
}));

const run = async ()=>{
await app.service('messages').remove(null);
await app.service('messages').create({id:1, text: 'Hello'});
await app.service('messages').create({id:2, text: 'World'});
await app.service('messages').create({id:3, text: 'Hello'});
const good_messages = await app.service('messages').find({query:{text:'Hello'}});
const bad_messeges = await app.service('messages').find({query:{iamundefined:'World'}});
console.log('good msgs', good_messages);
console.log('bad msgs', bad_messeges);
};
run();
```

for mongoose 5.13.14 output is:
```
...
bad msgs []
```

for mongoose 6.2.6:
```
...
bad msgs [
  {
    _id: new ObjectId("6231331f31b50960eff2255f"),
    id: 1,
    text: 'Hello',
    __v: 0
  },
  {
    _id: new ObjectId("6231331f31b50960eff22561"),
    id: 2,
    text: 'World',
    __v: 0
  },
  {
    _id: new ObjectId("6231331f31b50960eff22563"),
    id: 3,
    text: 'Hello',
    __v: 0
  }
]
```

In fact this is not dove related. This behaviour occurs when using mongoose 6.x.x, for 5.x.x everything works fine, both on feathers v4 and v5.

I am not sure if it is even feathers related or moongose thing, however in my opinion this behaviour is problematic.
For my case if I update mongoose - some unit tests are failing, thanks to that I am aware of this issue, but if somone is not - it may lead to very seroius security issues.

What do you think about that?

**Comment by marshallswain** [comment]
If it's a change in Mongoose, the `feathers-mongoose` adapter will need an upgrade.  Since that project is in a separate Github org, I can't move it to the correct repo.  Could you open an issue for this in the feathers-mongoose repo?  Make sure you reference/link to this issue, please.

https://github.com/feathersjs-ecosystem/feathers-mongoose

Also, since @daffl and I are focused on getting Dove out the door right now, we will need to lean on community contributions for a feathers-mongoose update.

**Comment by daffl** [comment]
As an additional note, you still need to add the proper restrictions to the query to make sure a user can only see what they are allowed (the effect here is basically the same as doing a normal client side `find` with an empty query). Another thing that will be so much easier in v5 with query schemas. Closing this issue since there is already a related one in the Mongoose repository.
