### ISSUE TITLE
FeathersClient v5: Failed to execute 'fetch' on 'Window': Illegal invocation

### ISSUE THREAD

**Issue by lukvermeulen** [feathersjs/feathers#2589]
### Steps to reproduce

My setup uses NextJs 12.1, and I have almost the same functions working with another project, using the v4 feathers client.

I am not entirely sure how to reproduce this, since I had this occur in different implementations, and not every call to the client breaks. 
In the hopes this might help, here some code snippets: 

my app/client setup:
```typescript
import feathers from "@feathersjs/client";

import { API_URL } from "../../config";

const client = feathers();

const restClient = feathers.rest(API_URL);
client.configure(restClient.fetch(fetch));

client.configure(feathers.authentication());

export default client;
```

the breaking code (I call this from a form submit handler function): 
```typescript
export async function signIn(email: string, password: string) {
  console.log("signing in");
  const auth = await client.authenticate({
    strategy: "local",
    email: email,
    password: password,
  });

  return auth;
}
```

### Expected behavior
I expect the client to login and return something of type authenticationResult.

### Actual behavior

Using the feathers client v5 throws this error message on the browser:
`Failed to execute 'fetch' on 'Window': Illegal invocation`

With this "stack trace": 
![image](https://user-images.githubusercontent.com/48993315/161434698-aff819f6-4423-4728-96b9-89ea938e32c1.png)

### System configuration

**Module versions** (especially the part that's not working):

@feathersjs/client: ^5.0.0-pre.17

**NodeJS version**: 16.13.0

**Operating System**: Windows 64 bit

**Browser Version**: Chrome / Opera 

Edit: I just tested the exact same setup with  "@feathersjs/client" : ^4.5.13 and it works like a charm.

**Comment by daffl** [comment]
Apparently this has changed in newer browsers. It needs to be

```js
app.configure(restClient.fetch(window.fetch.bind(window)));
```

Which has now also been updated [in the documentation](https://docs.feathersjs.com/api/client/rest.html#fetch).

**Comment by lukvermeulen** [comment]
Hi, thanks for the response! I fear however, that this does not resolve the issue for me. 

1. If I just replace the line with the one you write above, I get a `ReferenceError: window is not defined`. 
This could be solved by e.g wrapping that line in: 
```
if (typeof window !== "undefined") {
  // Client-side-only code
  client.configure(restClient.fetch(window.fetch.bind(fetch)));
}
```
This however throws the `illegal invocation` again as stated in the original post. Also this would seem a bit unnecessary since the old v4 client works perfectly.

2. As far as I know, NextJS makes fetch globally available and seems to bring its own polyfill, could it have something to do with that?

**Comment by daffl** [comment]
It should be `.bind(window)` not `.bind(fetch)`:

```js
if (typeof window !== "undefined") {
  // Client-side-only code
  client.configure(restClient.fetch(window.fetch.bind(window)));
}
```

A more universal way (if fetch is available but no `window`) would be

```js
const fetchConnection = typeof window !== "undefined" ? window.fetch.bind(window) : fetch

client.configure(restClient.fetch(fetchConnection));
```

One of the things I don't understand is how this would still work in v4 since the REST client code is essentially the same.

**Comment by lukvermeulen** [comment]
Thanks a lot, looks like I wasn't able to copy/paste it correctly - it works now!

That it worked in v4 and not v5 is also confusing me, since everything I had to do to break or repair it was to install the v4 client and the v5 client. I never changed browser nor other package versions on the client. But since it works like this, I guess that's enough for now :) Thank you for your time!
