### ISSUE TITLE
Compatibility with hyper-express

### ISSUE THREAD

**Issue by matiaslopezd** [feathersjs/feathers#2592]
Hi @daffl!

What do I need to consider to make feathers compatible with `hyper-express`? I want to fork `@feathers/express` and make compatible with `hyper-express`.

By now I'm getting the error:

```sh
Error: Invalid service object passed for path `...`
```

Thanks!

**Comment by daffl** [comment]
Do you have a link to your fork? For `@feathersjs/express`, middleware needs to be passed to the express app and service objects to the Feathers app. This is done in https://github.com/feathersjs/feathers/blob/dove/packages/express/src/index.ts#L31
