### ISSUE TITLE
feathers client integration in vue.js

### ISSUE THREAD

**Issue by nor-bu** [feathersjs/feathers#260]
Hi feathers team,

great work with feathers.

Can you help me by the integration of the feathers client in vue.js?

Thanks

**Comment by daffl** [comment]
@niallobrien made a a great example Gist for how to use Feathers with Vue.js here: https://gist.github.com/niallobrien/7eb51d17c977c46babb8

We will hopefully turn that into guide soon.

**Comment by niallobrien** [comment]
Thanks for the mention @daffl
I simply used the Feathers Yeoman generator to create an app in a server directory and ran the Vue CLI to scaffold a Webpack setup into a client directory.
Create a service using the feathers generator and add a new client component to your client app, much like how the initial Hello example component is setup. I'll publish the repo as is later today. I'd like to then expand it to demonstrate auth, filtered socket events etc.

**Comment by ekryski** [comment]
@nor-bu hopefully that helps you. Let us know either way. [We have a placeholder](http://docs.feathersjs.com/guides/vuejs.html) for an official guide but haven't had a chance to write one just yet so if you beat one of us to it feel free to submit a PR :wink:

**Comment by ekryski** [comment]
I'm going to assume we are all good here. We can re-open if not. An official guide will help and that should happen over the next week or so.

**Comment by RXminuS** [comment]
It's been "the next week or so"...any progress on the guide? @niallobrien , did you get a chance to post your boilerplate (expand the yeoman generator)

**Comment by daffl** [comment]
The guide is up at http://docs.feathersjs.com/frameworks/vuejs.html and has a link to a video for more advanced state management.
