### ISSUE TITLE
yo feathers - cors whitelist being returned as object instead of array.

### ISSUE THREAD

**Issue by unsalted** [feathersjs/feathers#261]
Don't know what's causing the issue -  just trying out a pretty standard setup with the yo build.

```
error: Route: / - whitelist.indexOf is not a function
```
```
{ '0': 'https://example.com/', '1': 'http://example.com/' }
```

**Comment by daffl** [comment]
That was a bug in `feathers-configuration`. I released a new version with the fix so reinstalling should solve it.

**Comment by unsalted** [comment]
Thanks



On Mar 12, 2016, at 8:53 AM, David Luecke <notifications@github.com> wrote:

That was a bug in feathers-configuration. I released a new version with the fix so reinstalling should solve it.
