### ISSUE TITLE
Feathers 5.0.0 pre-releases interally use latest dependency instead of same version for sub-deps, causing incorrect version to be loaded

### ISSUE THREAD

**Issue by HexaField** [feathersjs/feathers#2618]
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/crow/.github/contributing.md#report-a-bug))

- [x] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc. This makes it much easier for us to debug and issues that have a reproducable example will get higher priority.

### Expected behavior
installing any feathers package with a specific version, such as `5.0.0-pre.10` should include all sub-dependencies with the same version

### Actual behavior
installing any feathers package with a specific version, such as `5.0.0-pre.10` includes all sub-dependencies with latest patch version of the same minor version, such as `5.0.0-pre.19`

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working): any previous pre release (not the current pre-release version)

**NodeJS version**: 16.14.2

**Operating System**: any

**Comment by daffl** [comment]
Good point, this has been mentioned before. #2623 fixes this but only for the next prerelease. If there are major breaking changes between pre releases that are not already covered in the [migration guide](https://dove.docs.feathersjs.com/guides/migrating.html) it is also worth creating an issue for it.

**Comment by daffl** [comment]
Well :fish: it looks like Lerna doesn't care about the version lock when publishing and changes it all back to carets :neutral_face:
