### ISSUE TITLE
Trouble setting up feathers/client

### ISSUE THREAD

**Issue by RickEyre** [feathersjs/feathers#262]
I have the following code

```js
import feathers from 'feathers/client';
import rest from 'feathers-rest/client';
import request from 'browser-request';
import config from './config';

import User from 'app/utilities/user';

const client = request.defaults({
  headers: {
    Authorization: `Bearer ${User.get().token}`
  }
});

export default feathers().configure(
  rest(config.host).request(client)
);
```

However, when I call `create` on a service it does not send the `Authorization` header.

Alternatively, how can I set up feathers with superagent to send along specific headers?

Thanks!

**Comment by daffl** [comment]
For superagent and any other support REST library you can also set `params.headers` when making a service request:

```
app.service('todos').find({ headers: {
    Authorization: `Bearer ${User.get().token}`
  }
});
```

In the feathers-authentication client we using that [in a hook](https://github.com/feathersjs/feathers-authentication/blob/master/src/client/hooks.js#L18).

The problem with Request here is probably that the headers get overwritten now by those settings (even when they are empty).

**Comment by RickEyre** [comment]
Awesome! :smile: This worked perfectly.

Ended up going with this:

```js
import feathers from 'feathers/client';
import rest from 'feathers-rest/client';
import hooks from 'feathers-hooks';
import superagent from 'superagent';

import User from 'app/utilities/user';
import config from './config';

const app = feathers()
  .configure(hooks())
  .configure(
    rest(config.host).superagent(superagent)
  );

function authHook(hook) {
  hook.params.headers = Object.assign({}, {
    Authorization: `Bearer ${User.get().token}`
  }, hook.params.headers);
}

export default {
  service(url) {
    let s = app.service(url);
    s.before({
      all: authHook
    });
    return s;
  }
};
```

**Comment by daffl** [comment]
Looks great! One other thing you could do is make it a service mixin so it will get added to all services automatically:

```js
app.mixins.push(function(service) {
  service.before(authHook);
});
```

Mixins are not publicly documented yet but it's what all the plugins use to hook into a service.
