### ISSUE TITLE
Calls in authentication after hook are not authenticated

### ISSUE THREAD

**Issue by ericuldall** [feathersjs/feathers#2626]
I have a fastJoin in my after hook that resolves an uploaded image url to an uploadId in the user record.
When I run the resolver in the after hook of the authentication.js file I get an unauthorized error when calling my uploads service.

Is there some way to update the authentication for that call?

My assumption is that it makes sense to be present in the after hook since we are now authenticated but it doesn't seem to be working that way.

**Comment by ericuldall** [comment]
bump, any ideas here @daffl ?

**Comment by daffl** [comment]
Unfortunately I am not familiar with `fastJoin` but if `params` are passed along it should get whatever authentication information is passed in the request.

**Comment by ericuldall** [comment]
I don't think the problem is with fastJoin. The problem is in the after hook of the /authentication call we are not authenticated.

**Comment by daffl** [comment]
Ah, I think an `after` hook like

```js
context => {
  context.params.user = context.result.user
}
```

Before the fastJoin should do it.

**Comment by ericuldall** [comment]
Okay I'll try that. Does it only check for user object when calling
authenticate('jwt') or do I also need to pass params 
{ authentication, user }

**Comment by ericuldall** [comment]
Found minimal working code:
```
                context => {
                    context.params.authentication = context.result.authentication;
                    context.params.authentication.strategy = 'jwt';
                    return context;
                }
```

So you need to switch strategy from `local` to`jwt` for this method to work.

**Comment by daffl** [comment]
Ah sorry with the user it'd be

```js
context => {
  context.params = {
    ...context.params,
    authenticated: true,
    user: context.result.user
  }
}
```

For your example which also totally works, I'd change it to 

```js
context => {
  context.params = {
    ...context.params,
    authentication: {
      ...context.result.authentication,
      strategy: 'jwt'
    }
  }
  return context;
}
```

To avoid mutating any existing objects.
