### ISSUE TITLE
Cross-Origin headers 

### ISSUE THREAD

**Issue by euglv** [feathersjs/feathers#2627]
After upgrading `featherjs` from `4.5.11` to `4.5.14` my frontend that is served using `express.static` middleware stopped working.
It stopped working because new version of `featherjs` started adding extra HTTP headers:
```
Cross-Origin-Embedder-Policy: require-corp
Cross-Origin-Opener-Policy: same-origin
Cross-Origin-Resource-Policy: same-origin
```
How can I disable this headers?
If they are present, the following HTML:
```html
<script src="//unpkg.com/socket.io-client@^2.3.0/dist/socket.io.js"></script>
```
produces `net::ERR_BLOCKED_BY_RESPONSE.NotSameOriginAfterDefaultedToSameOriginByCoep 307` error.

**Comment by euglv** [comment]
To fix my issue this code in generated `app.js` :
```javascript
app.use(helmet({
  contentSecurityPolicy: false
}));
```
should be changed to:
```javascript
app.use(helmet({
  contentSecurityPolicy: false,
  crossOriginEmbedderPolicy: false
}));
```

**Comment by daffl** [comment]
You probably also updated the [helmet dependency](https://www.npmjs.com/package/helmet) which introduced that change. New applications will be generated like this already.
