### ISSUE TITLE
Issue with setting Express options

### ISSUE THREAD

**Issue by cciocov** [feathersjs/feathers#2629]
Up until `5.0.0-pre.15` I was able to use something like this:

```js
const app = express(feathers());
app.set('query parser', function customQueryParser(str) { ... });
```

After `5.0.0-pre.15` this is no longer possible and I tracked the issue to the fact that we call `.use()` on the express app during the `express(feathers())` call, which forces Express to initialise its lazy router (and at this point the `query parser` setting has its default `extended` value. The code I'm talking about is:

```js
  app.use((req, _res, next) => {
    req.feathers = { ...req.feathers, provider: 'rest' };
    return next();
  });
```
(starting on line 109 in `packages/express/src/index.ts`).

Previously (i.e.: up to `5.0.0-pre.15`) this code used to be `packages/express/src/rest.ts` and would only execute on `app.configure(express.rest())`.

I would suggest we keep `express(feathers())` as similar as possible (in terms of the effects on the Express app) as the original `express()` call that people use to create a plain Express app.

**Comment by tobiasheldring** [comment]
@daffl This issue resurfaced after https://github.com/feathersjs/feathers/pull/2811
