### ISSUE TITLE
For version 5.0.0-pre.20, authentication callback and redirect_uri are incorrect

### ISSUE THREAD

**Issue by johnheenan** [feathersjs/feathers#2630]
A fix has been proposed. The problem was not the redirect url, which is for the final phase back to the user browser. The problem was the callback and redirect_uri for authentication providerss

In version 4.5.11 the following `config/default.json` works fine for the specified redirect:

```
{
  "host": "localhost",
  "port": 3030,
  ...
  },
  "ts": true,
  "authentication": {
    "oauth": {
      "redirect": "http://localhost:3000",

```

In version 5.0.0-pre.20, the redirect is taken from host and port.

Tried adding v5 "origins" without "redirect". Same problem

The node server is behind a nginx proxy server

John Heenan

**Comment by johnheenan** [comment]
Some more information. I took a build of code for http://localhost:3000 and placed it on the same server as the version 5.0.0-pre.20 feathersjs server, with "redirect" left at "/". This allows the reverse nginx proxy server to apply a generic `proxy_redirect default` and narrows down the scope.

## Using GitHub for authentication

An attempted login with github just redirects to home page with feathersjs messages including
```
express:router <anonymous>  : /oauth/github/callback?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch +0ms

express:router session  : /oauth/github/authenticate +0ms
  express-session fetching 30Qd5ebzb6QdItunVClTedMOmXIPP7VS +50ms
  express-session session found +0ms
  knex:client acquired connection from pool: __knexUid4 +1m
  knex:bindings [ undefined ] +1m
  knex:client releasing connection to pool: __knexUid4 +0ms
  @feathersjs/errors GeneralError(500): Undefined binding(s) detected when compiling SELECT. Undefined column(s): [githubId] query: select count(`users`.`id`) as `total` from `users` where `githubId` = ? +1m
```

## Using Google for authentication

An attempted login with google resulted in the following redirect from google to what should be feathersjs, which shows what is being passed to oauth providers. Providers should not be told to use http://localhost:3030/.
http://localhost:3030/oauth/google/callback?code=4%2F0AX4XfWiOMBbzCB_AZ_PFRQWgtixD7HOuiGbNR8Nm2hyhtcEq26pvaGLPS17s1eS04am1EQ&scope=email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile&authuser=0&prompt=none

The URL appeared in the browser location bar with resultant 'site unreachable' message. I don't know what the mechanism is that got this URL into the browser, past a proxy redirect. Maybe there was looping and nginx dropped the loop.


Also the following. Unlike with github, no session was found and no database SQL error was reported:
```
 express-session fetching 30Qd5ebzb6QdItunVClTedMOmXIPP7VS +2m
  express-session no session found +0ms
  express-session saving 8rBXMMUsTxHB4E1XE6wah2gqf-Xvh8Xj +1ms
  express:router app  : /oauth/google +3ms
  express-session saving 8rBXMMUsTxHB4E1XE6wah2gqf-Xvh8Xj +2ms
  express-session set-cookie ledglive-auth.sid=s%3A8rBXMMUsTxHB4E1XE6wah2gqf-Xvh8Xj.6STggzn5qroWwDhCIdpBH%2BKABsRmab8YUTQpnyyNhfo; Path=/; Expires=Wed, 11 May 2022 14:20:13 GMT; HttpOnly +2ms

```

John Heenan

**Comment by daffl** [comment]
Could this be related to https://github.com/feathersjs/feathers/pull/2615/files?

**Comment by johnheenan** [comment]
@daffl. The changes in the specific commit linked to are not the cause of the problem but the fix is in the same file. There is no need to reverse a series of commits to fix the problem, just juggle it a bit.

Plese see PR https://github.com/feathersjs/feathers/pull/2631 for a full and tested fix, with explanation, that works with a reverse proxy server.

John Heenan

**Comment by johnheenan** [comment]
I have a `default/config.json` file that worked for me in V4 but does not work for V5 as now proposed. My proposed PR does solve this problem. @daffl wants to wind my changes back a bit but they do not solve my problem. I stated we are at cross purposes and need to state why.

It might help if others can give a view on this style of configuration, but before you do, please read the message in full: the top level host is left at `localhost` for good reasons. It is not a failed omission that I forgot to change.

Below is a shortened similar version of my `config.json` for feathers on a non `localhost` server. Feathers is behind a nginx reverse proxy server.

In V4 feathers uses host for authentication purposes, at the `authentication.oauth.defaults.host` level. In V5, as it is now, feathers uses host at the top level, ignoring the deeper level.

So why don't I just change at the top level to the same as the deeper level for V5?

Five reasons:
1. I did not need to for V4
2. It is more portable, as it is one less item to configure, such as for load balancing
3. It is more flexible, allowing a single instance of feathers to host multiple sites that can be distinguished at lower levels
4. It is consistent with a 'need to know' principle. Feathers does not need to know at a higher level what host it is really on
5. It allows me to confirm if higher level configuration at the nginx reverse proxy level is complete, without feathers acting as a fallback

All I really need at this stage is an acknowledgment that this form of configuration is acceptable. If it is accepted then we can make progress.

John Heenan

```json
{
"host": "localhost",
  "port": 3030,
  "public": "./public/",
  "paginate": {
    "default": 10,
    "max": 50
  },
  "ts": true,
  "authentication": {
    "oauth": {
      "redirect": "https://some.website.io",
      "defaults": {
        "host": "some.website.io",
        "protocol": "https",
        "transport": "session"
      },
      "google": {
        "key": "some_key",
        "secret": "some_secret",
        "scope": [
          "email",
          "profile",
          "openid"
        ],
        "nonce": true
      }
    },
    "entity": "user",
    "service": "users",
    "secret": "some_secret",
    "authStrategies": [
      "jwt",
      "local"
    ],
    "jwtOptions": {
      "header": {
        "typ": "access"
      },
      "audience": "https://some.website.io",
      "issuer": "feathers",
      "algorithm": "HS256",
      "expiresIn": "1d"
    },
    "local": {
      "usernameField": "email",
      "passwordField": "password"
    }
  }
}
```

**Comment by johnheenan** [comment]
My fix, as proposed, has been accepted in https://github.com/feathersjs/feathers/commit/43d8a082d7e1807f8a431c44a1dbd9b04c3af0d2

Thanks @daffl

John Heenan

**Comment by daffl** [comment]
Thank you for your pull request!
