### ISSUE TITLE
Error setting up AsyncStorage for client authentication

### ISSUE THREAD

**Issue by jmmwangi007** [feathersjs/feathers#2632]
I'm following the [docs ](https://docs.feathersjs.com/api/client.html#react-native)to set up for a react native project (made with react native CLI)

I get this error `Error: '0' is not a valid hook type` when I run my app. However on commenting out the code below, the error disappears. 

```
import AsyncStorage from '@react-native-async-storage/async-storage';

...
 client.configure(
   authentication({
   storage: AsyncStorage,
  }),
);
...
```
So I'm wondering how do I setup AsyncStorage and is there another alternative we can use, e.g [redux with persistence](redux-localstorage)?

EDIT
After a lot of tinkering I get this error now `{ [TypeError: undefined is not an object (evaluating 'this.storage.setItem')]}`

**Comment by daffl** [comment]
The module you are importing is not the `AsyncStorage` the authentication client expects. If you have a look at the [React Native client documentation](https://docs.feathersjs.com/api/client.html#react-native) you can see that it should be

```js
import { AsyncStorage } from 'react-native';
````
