### ISSUE TITLE
Dove: Error running Quickstart example

### ISSUE THREAD

**Issue by srebling** [feathersjs/feathers#2633]
On Quick start guide, running the Javascript example for 'An API Server', get the following error:

app.listen(3030).on('listening', () =>
                 ^
TypeError: app.listen(...).on is not a function

**Comment by Virginie-Villard** [comment]
Same error... did you find any answer ?

**Comment by srebling** [comment]
No, unfortunately it just doesn't work. Disappointing...

**Comment by ChielHackman** [comment]
Same problem here. I did find out that you can run the server without the log like this:
```app.listen(3030)```

This way it all works, but you don't get the message logged.

**Comment by daffl** [comment]
The guide hasn't been updated yet but the prerelease got accidentally published as `latest` (which happens at least once every time no matter what I do :angry:). It's set back to v4 now. The v5 quick start guide will unfortunately also only work once everything is official.

**Comment by Virginie-Villard** [comment]
Personally, if it can help, the problem was solved by re-installing the Feathers dependencies in my base app with version 4.5.12

**Comment by ChielHackman** [comment]
@Virginie-Villard that does solve  the issue, but the next step in the quick start will give errors. Like @daffl said: The v5 quick start guide will unfortunately also only work once everything is official. So I guess we need to wait a bit.

**Comment by amitabhdhiwal** [comment]
For anyone facing this, `app.listen(port)` returns a promise. You have to use `await app.listen(port)` to be able to use any HttpServer methods.

Instead of,
`const server = app.listen(3030)`

write,
`const server = await app.listen(3030)` 

It is mentioned [here in the docs](https://dove.docs.feathersjs.com/api/application.html#listen-port)
