### ISSUE TITLE
Dove: How to deal with Params?

### ISSUE THREAD

**Issue by jonasostrom** [feathersjs/feathers#2634]
Where have the possibility to pass objects to the Params gone?
For e.g since the internal service calls don't pass the current user that triggers the service call we use to pass the user object manually here. What is the correct approach to do it now?

In Dove 5.0.0-17

```
export interface Params {
    query?: Query;
    provider?: string;
    route?: {
        [key: string]: any;
    };
    headers?: {
        [key: string]: any;
    };
    [key: string]: any;     <--------
}

```

In the latest Dove 5.0.0-20
```
export interface Params {
    query?: Query;
    provider?: string;
    route?: {
        [key: string]: any;
    };
    headers?: {
        [key: string]: any;
    };
}

```

**Comment by daffl** [comment]
You would create typed params for your service (also see https://dove.docs.feathersjs.com/guides/migrating.html#typed-params-and-query - which also shows how to make it backwards compatible again):

```ts
import { Params } from '@feathersjs/feathers'

export type MyQuery = {
  name: string;
}

export type MyServiceParams extends Params<MyQuery> {
  user: User;
}
```

All services now take the `<ResultType, DataType, ParamsType>` generics so in your `service.ts` file you could do

```ts
import { ServiceInterface } from '@feathersjs/feathers'

// Add this service to the service type index
declare module '../../declarations' {
  interface ServiceTypes {
    'messages': ServiceInterface<MyServiceResult,  MyServiceData, MyServiceParams>
  }
}
```
