### ISSUE TITLE
[Bug] sockets not working (base ts project)

### ISSUE THREAD

**Issue by alexjs-dev** [feathersjs/feathers#2649]
### Steps to reproduce
- Install base ts-feathers project: https://github.com/alexjs-dev/pdf-report-generator
- Run yarn && yarn dev
- Open localhost:3030 (in Browser & open console)
- Observe how socket.io is connected: false

Changed socketio middleware to auto-connect to authenticated

```
  app.on('login', (authResult: any, { connection }: any): void => {
    // connection can be undefined if there is no
    // real-time connection, e.g. when logging in via REST
    if (connection) {
      app.channel('anonymous').leave(connection);
      app.channel('authenticated').join(connection);
    }
  });

```

In index.html connecting like this

```
    <script src="/socket.io/socket.io.js"></script> // tried using socketio official latest version too (from their cdn)
    <script>
      const baseUrl = 'http://localhost:3030/';
      const socket = io(baseUrl, {
        rejectUnauthorized: false, // tried also without this
      });
     socket.on('connect', () => {
        console.log('connected'); // NEVER CALLED
      });
     console.log(socket); // connected = false
      </script>
```

### Expected behavior
Should be able to connect to sockets

### Actual behavior
Does not connect to sockets at all

### System configuration

Tell us about the applicable parts of your setup.

**NodeJS version**: v14.18.2

**Operating System**: MacOS 12.3.1

**Comment by daffl** [comment]
The `login` event will only happen when authentication information is sent from the client. The [API server quick start](https://docs.feathersjs.com/guides/basics/starting.html#an-api-server) has a complete working minimal example Socket setup. If that isn't working it is likely a configuration issue of your system (firewall, etc.).
