### ISSUE TITLE
Publishing for a specific custom event do not work

### ISSUE THREAD

**Issue by ramsestom** [feathersjs/feathers#2653]
I am trying to publish a custom event from a custom service to a specific channel but it is failing at app startup with a message telling me that my custom event is not a valid service event.

Here is my service file where my custom 'webrtc' event is declared into options passed to the service:
```
// Initializes the `signal` service on path `/signal`
const { Signal } = require('./signal.class');
const hooks = require('./signal.hooks');

module.exports = function (app) {
  const options = {
    paginate: app.get('paginate'),
	events: ['webrtc']
  };

  // Initialize our service with any options it requires
  app.use('/signal', new Signal(options, app));

  // Get our initialized service so that we can register hooks
  const service = app.service('signal');

  service.hooks(hooks);
};
```

then in my service class file, I am emiting my 'webrtc' event into the create method of my service like this 
```
async create (data, params) {
	data.from = params.user.id;
	data.type = params.query.type;
	data.to = params.query.to;	
	this.emit('webrtc', data);
        return data; 
}
```

and in my channels.js file I have:

```
 app.service('signal').publish('webrtc', (data) => {
	return app.channel(`userIds/${data.to}`);
  });
```

but when I start my app on the server, it crash with the following error message:

```
C:\Development\feathers\test-server\node_modules\@feathersjs\transport-commons\lib\channels\mixins.js:63
                throw new Error(`'${event.toString()}' is not a valid service event`);
                ^

Error: 'webrtc' is not a valid service event
    at Object.registerPublisher (C:\Development\feathers\test-server\node_modules\@feathersjs\transport-commons\lib\channels\mixins.js:63:23)
    at Object.publish (C:\Development\feathers\test-server\node_modules\@feathersjs\transport-commons\lib\channels\mixins.js:53:25)
    at Function.module.exports (C:\Development\feathers\test-server\src\channels.js:63:25)
    at Function.configure (C:\Development\feathers\test-server\node_modules\@feathersjs\feathers\lib\application.js:59:8)
    at Object.<anonymous> (C:\Development\feathers\test-server\src\app.js:50:5)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
```

if I remove the event name from the publish call (so if I have `app.service('signal').publish((data) => {return app.channel(`userIds/${data.to}`); });` ) the app would no longer crash at startup but then I have also all service events (create, delete, ...) to be published to my output channel; wich is not what I want.

It seems that this problem was already raised more than a year ago but never fixed:
[https://github.com/feathersjs/feathers/issues/1293](url)

EDIT:
I bypassed this bug by declaring my service events directly in it constructor like this:
```
 constructor (options) {
    this.options = options || {};
    this.events = ['webrtc'];
  }
```
but it should be fixed to also work when passed as options from the service declaration

**Comment by daffl** [comment]
The `events` option is only available when using or extending [a Feathers database adapter](https://docs.feathersjs.com/api/databases/common.html#options). In a custom service class events need to be set as [documented here](https://docs.feathersjs.com/api/events.html#custom-events).
