### ISSUE TITLE
How to implement Many-to-many relation with services

### ISSUE THREAD

**Issue by kulakowka** [feathersjs/feathers#267]
We will use postgres from [feathers-sequelize](https://github.com/feathersjs/feathers-sequelize) for example:

- `Article` have many `Users`.
- `User` have many `Articles`.

How to get paginated user articles ? 
How to get paginated article users?

With one to many, i can use hook for paginated list: http://docs.feathersjs.com/hooks/examples.html#fetching-related-items

But i can't understand, how to get related items with many-to-many relation?

How i can make it with REST services?

**Comment by ekryski** [comment]
We have an open issue for this in the docs. So I'll defer to that one for now. I'm hoping to have this something up tomorrow or Friday. https://github.com/feathersjs/feathers-docs/issues/51
