### ISSUE TITLE
[@feathersjs/schema] Schema cannot handle validating properties with date formats

### ISSUE THREAD

**Issue by ejmudrak** [feathersjs/feathers#2682]
### Steps to reproduce

Schemas using the `format` attribute, such as `date-time` are not validating correctly with @feathersjs/schema. I am specifically trying to validate ISO string timestamps from PostgreSQL.

The error looks something like this, depending on your schema property's name:
`Error: unknown format "date-time" ignored in schema at path "#/properties/createdAt"` 

See the below Code Sandbox, it validates the schema fine with standalone AJV, but not with @feathersjs/schema. 
Just comment back in Line 44 to reproduce the error.

https://codesandbox.io/s/ajv-playground-forked-owbvqe?file=/src/index.js

### Expected behavior
Date formats should be recognized by Feathers when validating a schema. 

### Actual behavior
The console throws this error:
`Error: unknown format "date-time" ignored in schema at path "#/properties/<your-field-name>"` 

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
Feathers packages:
```
    "@feathersjs/authentication": "^4.5.11",
    "@feathersjs/authentication-local": "^4.5.15",
    "@feathersjs/authentication-oauth": "^4.5.15",
    "@feathersjs/configuration": "^4.5.15",
    "@feathersjs/errors": "^4.5.11",
    "@feathersjs/express": "^4.5.11",
    "@feathersjs/feathers": "^4.5.11",
    "@feathersjs/schema": "^5.0.0-pre.23",
    "@feathersjs/socketio": "^4.5.15",
    "@feathersjs/transport-commons": "^4.5.11",
```

And AJV packages:
```
    "ajv": "^8.11.0",
    "ajv-errors": "^3.0.0",
    "ajv-formats": "^2.1.1",
```

**NodeJS version**:
v17.0.0 

**Operating System**:
MacOS v12.2.1

**Comment by ejmudrak** [comment]
@daffl do you know of any workarounds that you can suggest for this issue in the meantime?

**Comment by edgar-koster** [comment]
Is there a reason why you added `ajv` seperatly? They are already included in `@feathersjs/schema`. I haven't tried yet myself, I'm getting to a first schema with date-time somewhere this week. What I do when I'm not sure is look in the git code for in this case `@feathersjs/schema` in the packages and the tests. I see in the test file they are actually testing `date-time`. You can see that here: https://github.com/feathersjs/feathers/blob/dove/packages/schema/test/schema.test.ts

Have you seen\tried that? Just wondering, again I haven't gotten there yet.

**Comment by edgar-koster** [comment]
Okay, not a 100% simular situation, but it does work.

My `package.json` contains:
```
        "ajv-errors": "^3.0.0",
        "ajv-formats": "^2.1.1",
        "ajv-keywords": "^5.1.0"
```
Since I didn't have a different schema yet, I used my configuration schema. I added to it:
`date: { type: 'string', format: 'date-time' }`

Since I use custom errors, I added a require and and a properties key for this property as well. This results in custom messages per error :-).

Then I tried starting the application, not changing `default.json` which resulted in the error missing `date`. So I added it with a value `test`. This resulted in my content error, for the format didn't work.

Then in my `default.json` file I added as value for `date`:
`"2022-01-03 15:20:11"`

This succeeds. So I think you need to tweak in the sandbox the `new Date()` and conversion. Maybe use `dayjs` if it really is a dateformat. The docs of ajv do say timezone is also mandatory (not that I did it). I usually use `dayjs` to format a date to the string format of my application.

**Comment by ejmudrak** [comment]
@edgar-koster I was adding AJV separately in the above sandbox to show that it worked standalone, but not with feathers schema. 

The problem with the sandbox ended up being that I forgot to pass the custom ajv instance to the `schema()` function as the second argument. Adding that fixed it, see this sandbox: https://codesandbox.io/s/ajv-playground-date-conversion-fw3zg0?file=/src/index.js

That test file is helpful! I didn't need to use the date converter to get the sandbox working, but that keyword feature is definitely useful.

Alright, so now I've confirmed that date-time validation works with the `schema.validate()` function, but my app still has an issue when validating with a resolver -- which was my original problem. The error:
```
{
    "name": "BadRequest",
    "message": "validation failed",
    "code": 400,
    "className": "bad-request",
    "data": [
        { "instancePath": "/courses/0/createdAt", "schemaPath": "#/properties/courses/items/properties/createdAt/type", "keyword": "type", "params": { "type": "string" }, "message": "must be string" },
}
```

I'm going to troubleshoot resolver validation now, specifically `resolveResult`

**Comment by edgar-koster** [comment]
Off-topic: I also suggest ajv-errors, you can do nice things then

**Comment by ejmudrak** [comment]
I've confirmed that the `<resolver>.resolve()` function is validating dates correctly: https://codesandbox.io/s/ajv-playground-date-conversion-fw3zg0?file=/src/index.js

That just leaves the actual `resolveResult` hook function.

**Comment by ejmudrak** [comment]
I'm struggling to use `resolveResult` in a sandbox, but in my Feathers app, I think the root issue that I'm experiencing is due to arrays in schemas. 

When I try to validate a schema with an array of items that have a property with a `format: 'date-time'`, validation fails. Something as simple as this:
```
dates: {
	type: 'array',
	items: {
		type: 'string',
		format: 'date-time',
	},
},
```
gives the error `"must be string"`

**Comment by ejmudrak** [comment]
I found a workaround by using the result resolvers to format my dates as ISO Strings in a way that the validator can handle. 

```
export const courseResultResolver = resolve<CourseResult, any>({
	schema: courseResultSchema,
	validate: 'after',
	properties: {
		createdAt: async (value: any) => new Date(value).toISOString(),
		updatedAt: async (value: any) => new Date(value).toISOString(),
	},
});
```

I was receiving Date objects for `createdAt` and `updatedAt` from Knex w/ PostgreSQL, which I thought the validator could handle. Was I just assuming incorrectly that feathers/schema could handle ISO formatted date objects like `2022-05-24T15:11:39.104Z`, or is this a bug? @daffl @marshallswain 

I'll close this issue once I get some clarification

**Comment by edgar-koster** [comment]
Just of something reading you comment. Did you also try defining creatingAt as 'object'? I read somewhere that people do that too, and then ofcourse not do the toISOString

**Comment by ejmudrak** [comment]
You're correct, defining it as `type: 'object'` also works. That is probably a better option for the sake of simplicity. 

Since that works, I'm going to go ahead and close this issue. Thanks @edgar-koster !
