### ISSUE TITLE
[feathers-hooks-common][Bug] PreventChanges hook prevents only last defined field

### ISSUE THREAD

**Issue by zaheraldefai** [feathersjs/feathers#2692]
In case of using the preventChanges hook without wanting to throw an error, then it will only remove the last defined field from the context.data.

### Example
context.data => {id: '1234', email: 'test@test.com', username: 'testuser'}

preventChanges(false, 'id', 'email')

**Actual result:**
context.data => {id: '1234', username: 'testuser'}

**Expected result:**
context.data => {username: 'testuser'}

### Root issue
The data variable on [line 25](https://github.com/feathersjs-ecosystem/feathers-hooks-common/blob/a265142578dee3955e2a6b08ff5e6234f6b7db9d/src/hooks/prevent-changes.ts#L25) is never changed and on [line 33](https://github.com/feathersjs-ecosystem/feathers-hooks-common/blob/a265142578dee3955e2a6b08ff5e6234f6b7db9d/src/hooks/prevent-changes.ts#L33) it is always used to bring context.data to the origin state except the field of the current loop. Therefore, just the field of the last loop is removed from the context.data.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
"@feathersjs/feathers": "^4.5.15",
"feathers-hooks-common": "^6.1.3",
"lodash": "^4.17.21",
"typescript": "^4.7.4",

**NodeJS version**:
Node 16

**Comment by zaheraldefai** [comment]
Have created an PR for this bug: https://github.com/feathersjs-ecosystem/feathers-hooks-common/pull/680

PS: Happy to contribute to this wonderful project

**Comment by daffl** [comment]
Great, thank you for the pull request! Closing this issue since it is now tracked in https://github.com/feathersjs-ecosystem/feathers-hooks-common/
