### ISSUE TITLE
Dove database adapters for switching models suggestion

### ISSUE THREAD

**Issue by joezappie** [feathersjs/feathers#2693]
I just upgraded to the latest Dove release and started migrating my code to use the new database adapters which introduced the params.adapter option. This is great and makes a lot of sense to be able to switch your database through a hook. I do however think having the alternative to pass a function for the Model in the service file would still be a useful addition in some scenarios:

```
const options = {
  Model: async (params) => params.tenantDb.collection('users')
};
```

The main reason I'm suggesting this is because I sometimes use the underscore service methods to avoid the overhead or validation of other hooks on the service. This means using a hook automatically generate the Model to use doesn't work here. This requires anytime an underscore method is used to manually pass in the params.adapter option. Also, I think it makes sense to be able to just define the model switching logic at the service level and not have the service requestor have to provide what Model it wants.

To support this, looking through the code I think a simple type check could be added to the getOptions function without any changes to the individual adapter's. I tried this out and it all seems to work but I'm not sure if this would cause conflicts in any of the other adapters.

```
getOptions(params) {
    const paginate = params.paginate !== undefined ? params.paginate : this.options.paginate;
    const options = {
      ...this.options,
      paginate,
      ...params.adapter
    };
    if (typeof options.Model === 'function') {
      options.Model = options.Model(params);
    }
    return options;
  }
```

**Comment by blackmann** [comment]
I can't think of how common a use-case this is and also considering this wasn't in the previous API. How about overriding the `MongoDBService` with this custom implementation? Like

```javascript
type ModelGetter = (params: unknown) => Promise<Collection>

interface AltOptions extends Omit<MongoDBAdapterOptions, 'Model'> {
  Model: ModelGetter
}

export class DynamicCollectionService extends MongoDBService<UsersResult, UsersData, UsersParams> {
  private modelGetter: ModelGetter

  constructor(options: AltOptions) {
    super({
      ...options,
      // your implementation for `ModelGetter` should return a default collection when null is passed
      Model: options.Model.call(null, null),
    })

    this.modelGetter = options.Model
  }

  getOptions(params: object): MongoDBAdapterOptions {
    const original = super.getOptions(params)

    return { ...original, Model: this.modelGetter.call(null, params) }
  }
}
```

**Comment by joezappie** [comment]
I have extended the Mongo Service class and done something similar for changing the model in the getOptions function so I have a solution for myself, just thought it might make sense adding it to the feathers adapter. 

Agreed though that this is a small use case as using a hook to generate the params.adapter model works in most scenarios. I just like it as to me it makes more sense keeping that logic with the service, is a single line of code compared to creating a new  hook and having to add that hook to the services I want to have switchable models (since not all my services are multi-tenant), and works with underscore methods. 

I'll concede though and close this as it hasn't picked up any steam and keep it as a custom adapter in my project.
