### ISSUE TITLE
@feathersjs/mongodb doesn't fully work with transaction sessions

### ISSUE THREAD

**Issue by joezappie** [feathersjs/feathers#2694]
I noticed on services that used transactions when trying to create a document, context.result is undefined.

Looking through the adapter code, the $create method passes the params.mongodb object to the insertMany and insertOne but does not pass it to the subsequent findMany or findOne:

```
// Current Code
const promise = Array.isArray(data)
      ? model
          .insertMany(data.map(setId), writeOptions)
          .then(async (result) =>
            Promise.all(Object.values(result.insertedIds).map(async (_id) => model.findOne({ _id })))
          )
      : model
          .insertOne(setId(data), writeOptions)
          .then(async (result) => model.findOne({ _id: result.insertedId }))

// Working Code
const promise = Array.isArray(data)
      ? model
          .insertMany(data.map(setId), writeOptions)
          .then(async (result) =>
            Promise.all(Object.values(result.insertedIds).map(async (_id) => model.findOne({ _id }, params.mongodb)))
          )
      : model
          .insertOne(setId(data), writeOptions)
          .then(async (result) => model.findOne({ _id: result.insertedId }, params.mongodb))
```

I tested this and my transactions begin working again.

I looked over the rest of the adapter and looks like every other call passes the session in properly but haven't used them yet.

### Steps to reproduce

1. Start a mongo transaction and pass session in under params.mongodb.session. 
2. Try to create a document
3. Check that context.result is undefined

### Expected behavior
Created document should be returned as the result

### Actual behavior
Result is undefined.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
5.0.0-pre.27

**NodeJS version**:
v16.16.0

**Operating System**:
Linux debian

**Browser Version**:
N/A

**React Native Version**:
N/A

**Module Loader**:
N/A

**Comment by daffl** [comment]
Good catch, thank you! Will be fixed via #2699
