### ISSUE TITLE
Feathers dove custom methods are not registered on app-level and cannot be accessed using app hooks.

### ISSUE THREAD

**Issue by MounirYounes** [feathersjs/feathers#2697]
### Steps to reproduce

In app hooks add:
```javascript
  before: {
    all: [
      (context) => {
        console.log('hello world')
        return context
      }
    ]
  },
```

In service class add a custom method (let's call it test):
```javascript
export class ItemsService extends MongoDBService {
//simple custom method that return a json with key method (just for testing purposes)
  async test(data, params) {
    return {
      method: 'test'
    }
  }
}

```
In service `app.use` expose the custom method:
```javascript
//exposing custom method test
 app.use('items', new ItemsService(options), {
    methods:['get','create','test'],
    events: []
  })

```

### The Bug

When calling any predefined route (`get`, `create` etc...) `hello world` is printed on the screen (the before:all hook). When calling a custom method, it is not. This bug only takes place on the app level hooks, but does not occur on the service level hooks. So if the aforementioned  
```javascript
  before: {
    all: [
      (context) => {
        console.log('hello world')
        return context
      }
    ]
  },
```

was to be put in the `ItemsService`, it works correctly without the bug occuring.

### Reasoning
It seems that `app.use` is not registering custom methods on the app level hooks, and is doing so on the service level hooks.

### Expected behavior
When registering a service with `app.use` service level hooks are applied to default routes (get, find, etc...) and custom methods as well. The same functionality should take place on an app-level basis. So `before:{all:[]}` should be triggered for all routes.

### Actual behavior
The hooks for custom methods are triggered on the service-level but not the app level. So for example:
```
before:{all:[context=> context]}
```
would trigger for (get, find, create, etc...) but not custom methods on the app level, but works correctly on the service level.

This is a bug that was discussed with @daffl on discord https://discord.com/channels/509848480760725514/997704733672345710

**Comment by MounirYounes** [comment]
So technically speaking `app.use` is not registering custom methods for app level hooks.

**Comment by noor-tg** [comment]
hello @MounirYounes

### fix the issue description by

> ### Steps to reproduce
> (First please check that this issue is not already solved as [described here](https://github.com/feathersjs/feathers/blob/crow/.github/contributing.md#report-a-bug))

remove the above section.

> * [x ] Tell us what broke. The more detailed the better.

 remove above line. and set description about the bug.

> * [ ]  If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc. This makes it much easier for us to debug and issues that have a reproducable example will get higher priority.

remove above line . and add github repository to show the bug in action (even better with tests).

**Comment by MounirYounes** [comment]
@nour-dev done. The bug does not need tests, it is very simple to reproduce, and it isn't technically a bug that takes place in a certain scenario or that something is broken, it's just that it seems the implementation is missing probably.

And as mentioned before this was discussed with @daffl in the following thread: https://discord.com/channels/509848480760725514/997704733672345710

You can read the thread for more information.

Thanks a bunch.
