### ISSUE TITLE
Default.json successRedirect is not overriding default

### ISSUE THREAD

**Issue by brianmmorton** [feathersjs/feathers#270]
Hey guys,

I am following this section of your documentation: http://docs.feathersjs.com/getting-started/user-management.html#signing-up-new-users

Got everything working great, but I changed my "successRedirect": in default.json to be different than "/auth/success" and it is not overwriting it. Even with a restart of the server a few times. I changed the db config and that worked, but not the successRedirect, so I am assuming this is a accidental bug. 

Any ideas?

**Comment by ekryski** [comment]
@brianmmorton might be a bug related to https://github.com/feathersjs/feathers-authentication/issues/89. Can you post your JSON config with any sensitive stuff redacted?

**Comment by brianmmorton** [comment]
Its basically the default from the yeoman setup: 

{
  "host": "localhost",
  "port": 3030,
  "mongodb": "mongodb://localhost:27017/dbname",
  "public": "../public/",
  "auth": {
    "token": {
      "secret": "---------"
    },
    "local": {}
  },
  "successRedirect": "/app"
}

I noticed a comment in the code for feathers-authentication:
`      // If they passed a custom success redirect then we'll
      // leave it to the developer to set up their own route.
      if (providerOptions.successRedirect) {
        authOptions.setUpSuccessRedirect = false;
      }`

Would that mean I should setup my own route/middleware?

**Comment by brianmmorton** [comment]
And in regards to

**Comment by ekryski** [comment]
@brianmmorton yup! That's what the http://docs.feathersjs.com/getting-started/user-management.html#signing-up-new-users section gets you to do. At least it should be! Maybe the way the doc is laid out is a bit confusing?

**Comment by brianmmorton** [comment]
Hey erik, figured it out. Turned out that i had my successRedirect outside of the auth block. Just needed to step away from the computer and come back to see it! Sorry for the trouble.

**Comment by ekryski** [comment]
@brianmmorton :+1: :+1: Glad you got it figured! No trouble at all.
