### ISSUE TITLE
[feathers-dove] - How to perform transactions?

### ISSUE THREAD

**Issue by csotiriou** [feathersjs/feathers#2718]
I'm just beginning with Feathers 5.x pre-release using Postgres, and although I can find support for transactions inside the feathersjs code (inside the knex/hooks.ts file), it's not clear to me from the documentation how I can approach this as an end user.

I couldn't find anything in the documentation either. Is there an example somewhere?

Thank you for your hard work on this!

**Comment by marshallswain** [comment]
@csotiriou did you read this documentation?  https://github.com/feathersjs-ecosystem/feathers-knex#transaction-support

**Comment by daffl** [comment]
This is now documented in https://feathersjs.com/api/databases/knex.html#transactions
