### ISSUE TITLE
Services API Enhancement

### ISSUE THREAD

**Issue by hnordt** [feathersjs/feathers#272]
Here is my suggestion for enhancing Services API:

```js
// feathers-service package

class Service {
  constructor(db, options) {
    if (!db) {
      throw new Error('db is required')
    }
    this.db = db
    this.id = options.id || '_id'
    this.beforeCreate = options.beforeCreate
    // other hooks
    this.paginate = options.paginate || {}
  }
  // ...
}

// feathers-nedb package

import Service from 'feathers-service'
import NeDB from 'nedb'

class NeDBService extends Service {
  constructor(options) {
    if (!options.filename) {
      throw new Error('filename is required')
    }
    const db = new NeDB({
      filename: options.filename,
      autoload: true
    })
    super(db, options)
  }
  find() {
    // ...
  }
  // ...
}

// usage

import NeDBService from 'feathers-nedb'

const messageService = new NeDBService({
  filename: '/some/path/messages.db',
  beforeCreate(data) { // pure function :)
    return { ...data, createdAt: new Date() }
  },
  validate({ author, text }) { // "Syntax" sugar, inside Service it'll be called by create(), update(), patch() and errors wrapped in errors.BadRequest()
    const errors = []
    if (!author || !author.name) {
      errors.push({
        {
          path: 'author.name',
          message: 'Author Name is required'
        }
      })
    }
    if (!text) {
      errors.push({
        {
          path: 'text',
          message: 'Text is required'
        }
      })
    }
    return errors
  }
})
```

I would like to help writing the implementation if @ekryski and @daffl likes it.

**Comment by ekryski** [comment]
You can already `extend` services to add custom functionality like your `validate` and `beforeCreate` methods (I just realized that's not in the docs).

However, I think the better solution is to use [hooks](http://docs.feathersjs.com/hooks/readme.html) for what you want. This is really what they were made for. You might want to look at:

- https://github.com/kulakowka/feathers-transform-hook
- https://github.com/kulakowka/feathers-validate-hook

IMHO this actually makes the services a bit more bloated than they need to be and makes them more ORM-like.

**Comment by ekryski** [comment]
Based on our discussion in Slack. I'm going to close this.

Basically, for anyone else, the gist of the discussion was that this is already accomplished in a more flexible nature using hooks and we've made an update to the hooks docs to hopefully make it more clear why you would use hooks over having things like a `validate` method at the service level.
