### ISSUE TITLE
hook params empty after authenticate

### ISSUE THREAD

**Issue by ramsestom** [feathersjs/feathers#2720]
I have a 'media' service that requiere authentication and that is called internally from other services (like an 'upload' files middleware that also requiere authentication) like so:

```
return await app.service('media').create({
	filename: filename,
        path: filePath,
	mediaType: mediaType,
	mimeType: mediaMimetype,
});
```

the problem is that in my 'media' service, the hook `params` object remains empty even after the `authenticate('jwt')` hook (whereas it should contain the authenticated `user ` object). 
My `media` service hooks are defined like that:

```
const { authenticate } = require('@feathersjs/authentication').hooks;
const { disallow } = require('feathers-hooks-common')

const setAuthorID = async context => {
  if (context.params.user){
	context.data.authorID = context.params.user.id;
  }
  console.log(context.params);
  return context;
};

const disableEvents = async context => {
  context.event = null;
  return context;
}

module.exports = {
  before: {
    all: [  disallow('external'), authenticate('jwt') ],
    find: [],
    get: [],
    create: [setAuthorID],
    update: [setAuthorID],
    patch: [setAuthorID],
    remove: []
  },

  after: {
    all: [disableEvents],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  },

  error: {
    all: [],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  }
}; 
```

the `context.params` is logged has empty (`{}`) even if the `authenticate('jwt')` hook seems to be previously correctly performed (in DEBUG=* mode, I have the log line `@feathersjs/authentication/hooks/authenticate Running authenticate hook on 'media' +62ms` that appears just before the `{}` line resulting from the `console.log(context.params);` command).
So how can I obtain the `user.id` of the authenticated user to populate it as `data.authorID` in my `media` service?

**Comment by daffl** [comment]
The `authenticate` hook will do nothing if it is an internal call (which is probably the case since you added `disallow('external')`) and there is no existing `params.authentication` value.

**Comment by ramsestom** [comment]
OK. So is there a simple way to pass in some `params.authentication` from my authenticated middleware that is performing the `app.service('media').create(..)` internal call? 
This middleware is defined like this: 
`app.use('/media-upload', authenticate('jwt'), multipartMiddleware.array("files"), mediaUpload(app));` and this is inside the `mediaUpload(app)` function that the `app.service('media').create(..)` internal service call is done.

**Comment by daffl** [comment]
Passing `req.feathers` as `params` to the `create` call should do that:

```js
return app.service('media').create({
	filename: filename,
        path: filePath,
	mediaType: mediaType,
	mimeType: mediaMimetype,
}, req.feathers);
```

**Comment by ramsestom** [comment]
OK Thanks. Had to pass in only the `authentication` part of the `req.feathers` params object because is contains a `provider: "rest"` value that will fail the `disallow('external')` hook (error message: `Provider 'rest' can not call 'create'. (disallow)`). But it works.

**Comment by philipimperato** [comment]
> Passing `req.feathers` as `params` to the `create` call should do that:
> 
> ```js
> return app.service('media').create({
> 	filename: filename,
>         path: filePath,
> 	mediaType: mediaType,
> 	mimeType: mediaMimetype,
> }, req.feathers);
> ```

Is there a reason why params aren't automatically passed in? Is the context lost? Is that a design decision?
