### ISSUE TITLE
Service methods (create, update, patch, remove) on multi-records emit many events (one for each record) instead of one event

### ISSUE THREAD

**Issue by wz5899** [feathersjs/feathers#2724]
### Steps to reproduce

When a service method makes change to multi records, upon return it emits many events (one for each record changed) instead of one event for the method called.

For example:
Back end code periodically disables the users who never logged in:
`app.service('users').patch(null, { isEnabled: false }, { query: { lastLoggedIn: null } } }`

If there are 20 users never logged in, the code above will emit 20 'patched' events upon return. The event listener on the front end will be called 20 times.
`app.service('users').on('patched', updateUsersInfo)`

This generates a lot of network traffic. And it will become a performance drag if someone needs to patch hundreds of records in one method call in the back end and also handle the resulting service events in the front end.

My guess is that the service method is not executed atomically. So each patch record emits its own event. Is there a way to make the service method call atomic and only emit one patched event after the call?  

### System configuration

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by daffl** [comment]
This is by design. The service call does happen atomically but if the response contains multiple items an event will be sent for each item. You can disable event emitting for a service call by setting [context.event to null](https://docs.feathersjs.com/api/hooks.html#context-event) in a hook.

**Comment by wz5899** [comment]
Does context.event null disable custom events or just standard service events? I am thinking using custom event as a workaround: In after hooks, emit custom events such as myCreated, myPatched that aggregate the multi-items into the custom event data.

**Comment by daffl** [comment]
Yes, it will only disable the default event, you can still send the custom events you want. For most real-time integrations the individual standard events is probably the way to go but you can do it the way you suggested as well.
