### ISSUE TITLE
Error with Babel-node after npm start 

### ISSUE THREAD

**Issue by FreakDroid** [feathersjs/feathers#273]
Hi guys, yesterday I tried to follow the example that you've in your [page](http://docs.feathersjs.com/getting-started/scaffolding.html) But I'm getting this error:

```
C:\Users\Jully\Documents\Feathers\feathers-chat>npm start

> feathers-chat@0.0.0 start C:\Users\Jully\Documents\Feathers\feathers-chat
> babel-node src/

module.js:327
    throw err;
    ^

Error: Cannot find module 'feathers-authentication'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (index.js:3:24)
    at Module._compile (module.js:409:26)
    at loader (C:\Users\Jully\Documents\Feathers\feathers-chat\node_modules\babe
l-register\lib\node.js:126:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\Jully\D
ocuments\Feathers\feathers-chat\node_modules\babel-register\lib\node.js:136:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Jully\\AppData\\
Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.4.0
npm ERR! npm  v3.8.2
npm ERR! code ELIFECYCLE
npm ERR! feathers-chat@0.0.0 start: `babel-node src/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the feathers-chat@0.0.0 start script 'babel-node src/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the feathers-chat package
,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node src/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs feathers-chat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls feathers-chat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Jully\Documents\Feathers\feathers-chat\npm-debug.log

C:\Users\Jully\Documents\Feathers\feathers-chat>
```

For any reason that I don't know `babel-node src/` is failing.

Any help for this error???

Cheers.

**Comment by FreakDroid** [comment]
For any rason I did not installed feather-autentication, So npm install feathers-authentication and that Works. Remeber install python first.

Thanks.

**Comment by FreakDroid** [comment]
I have stilling problems trying to install the workplace to do the tutorial, one of them was after I installed python and feathers-autentication I needed to install node bcrypt, but one of this [issues](https://github.com/ncb000gt/node.bcrypt.js/issues/98) for windows, is that you'll need to install first [node-gyp](https://github.com/nodejs/node-gyp#installation) and after you could run feather-autentication without any problems.

**Comment by ekryski** [comment]
It's definitely your environment and not a Feathers issue. Try checking out this article: https://futurestud.io/blog/how-to-build-nodegyp-to-run-bcrypt-on-windows.

I'm going to close this because it's not really a Feathers issue but feel free to drop by Slack and we can try and help you out.

**Comment by FreakDroid** [comment]
@ekryski Ok Erick not problem :) I saw this article yesterday and you are rigth is another problem. Thanks for the support.

**Comment by daffl** [comment]
I did create a follow-up issue for us to investigate switching to a JS only version of bcrypt.

**Comment by FreakDroid** [comment]
@daffl That's will be great, although I fixed my problem following @ekryski link suggested, I lost a lot of time, Maybe other Windows's users would be stuck as me and that will help.
