### ISSUE TITLE
Custom events received by the client with socket.io transport but not with REST transport  

### ISSUE THREAD

**Issue by wz5899** [feathersjs/feathers#2741]
### Steps to reproduce

I have a number of custom events (e.g. 'customCreated', 'customPatched') emitted on the server in the service hook using context.service.emit. I added these events in service class this.events list. 

On the client side, I added the listeners to these custom events. For example, service.on('customCreated', () => { console.log('customCreated') }).

The client can receive these custom events if I use a real time transport (socket.io), but not with REST transport. Standard events such as created, patched can be received with both transports. Are custom events for real time transport only? The document doesn't say so.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by daffl** [comment]
Events are only sent with a real time connection. As [noted in the REST client docs](https://docs.feathersjs.com/api/client/rest.html#feathersjs-rest-client):

> REST client services do emit `created`, `updated`, `patched` and `removed` events but only locally for their own instance. Real-time events from other clients can only be received by using a real-time transport ([Socket.io](https://docs.feathersjs.com/api/client/socketio.html)

**Comment by wz5899** [comment]
I see. This explains the behavior.
