### ISSUE TITLE
Type error when compiling a newly generated sequelize app

### ISSUE THREAD

**Issue by LinusOP** [feathersjs/feathers#2743]
### Steps to reproduce

- Create a feathers app using the following options: https://cdn.discordapp.com/attachments/1017195623235199117/1017195623482675241/unknown.png
- Run `yarn start`

### Expected behavior
The app should compile into javascript which should then run

### Actual behavior
The compilation results in the following errors: https://i.imgur.com/bwgg6Mo.png
`yarn dev` however does work fine and the app runs.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
- `"sequelize": "^6.20.1"`
- `"feathers-sequelize": "^6.3.4"`

**NodeJS version**: 16.16.0

**Operating System**: Fedora 35

**Comment by daffl** [comment]
This might be another TypeScript breaking change the Sequelize module which can only be worked around by setting `skipLibCheck: true` in your `tsconfig.json` until it is fixed. Another option is also to test out the [prerelease](https://dove.feathersjs.com/guides/) which will be official in the next few weeks.
