### ISSUE TITLE
getGrantConfig being hard-coded to use http on local dev not ideal for some setups

### ISSUE THREAD

**Issue by barankyle** [feathersjs/feathers#2764]
We recently did a long-overdue dependency update, with one of those updates being a conversion from pre.10 versions of Feathers packages to pre.29. I noticed that in local dev, our oauth logins weren't working any more. I see in the new getGrantConfig in authentication-oauth/src/utils.ts  that, if NODE_ENV is 'development', it's hard-coding the protocol to be 'http' and adding a non-'80' port onto the host. We use https when running locally and were already adding the port onto the host in order to work in prior versions. The latter isn't too much of an issue to change, but the former is more of a problem, since we're not going to switch to http.

I don't think assuming that everyone runs http locally is a good assumption, as we can't be the only people who use https in order to more closely mirror production (and prevent warnings/issues with mixed fetching of http and https resources). 

I can get around this by setting NODE_ENV to production locally, and as it turns out we don't seem to be running any important logic off of NODE_ENV so this shouldn't mess up our local dev process, but I don't think NODE_ENV !== 'production' should be forcing http. There may very well be others who are using NODE_ENV to set other logic, which would force them to either not be able to easily test OAuth locally, have to switch to http (which may be impractical), or change that other logic to be conditional on something else.

### Expected behavior
http vs. https for origin urls on local dev (NODE_ENV !== 'production') should be configurable

### Actual behavior
local dev forces http on origin urls

**Comment by daffl** [comment]
I added a test in #2795 that shows how to override the origin in the default settings. It looks like this:

```ts
{
  defaults: {
    prefix: '/auth',
    origin: 'https://localhost:3344'
  },
  github: {
    key: 'some-key',
    secret: 'a secret secret',
    dynamic: true
  }
}
```

This will use `https://localhost:3344` as the base URL.
