### ISSUE TITLE
app.service('users').get(undefined) throws error, making our resolves a bit shaky

### ISSUE THREAD

**Issue by tvld** [feathersjs/feathers#2765]
When resolving:

```js
 properties: {
    user: async (value, experience, { app }) =>
      app.service('users').get(experience.userId)
  }
```
An error is thrown when ``experience userId === undefined``. In our case, it can happen with database & initialization timing. Would it be ok to allow ``app.service('users').get(undefined)`` and return empty data? 

Now we need to solve every resolver population with an extra check:

```js
properties: {
    user: async (value, experience, { app }) =>
      experience.userId ? app.service('users').get(experience.userId) : {}
  }
```

**Comment by daffl** [comment]
Unfortunately I think returning empty data for `undefined` would be a bit of a breaking change but I think it could be made a little less clunky with a resolver helper. I was thinking of starting to collect some of those to maybe eventually have a similar library to the common hooks. In this case I was thinking something like this:

```ts
const withProperty = (name, callback, default = () => ({})) =>
  async (value, obj, context) =>
    obj[name] !== undefined ? callback(obj[name], context) : default(value, obj, context)

// ...
properties: {
  user: withProperty('userId', async (userId, { app }) => app.service('users').get(userId))
}
```

**Comment by tvld** [comment]
Ah, super. I really liked the common-hooks lib. After you get the hang of it, it gave a smile every time using one of those ))) So yeah, a small light lib can:

1.  help reducing boilerplate 
2. teach new people development pattern suggestions
