### ISSUE TITLE
unuse() does not work for routes with parameters

### ISSUE THREAD

**Issue by steffanhalv** [feathersjs/feathers#2767]
### Steps to reproduce

```js
await app.unuse('path/:id')
app.use('path/:id', ...)
```

### Expected behavior
Should unregister like this:
```js
await app.unuse('path')
app.use('path', ...)
```

### Actual behavior
Throws error:
```
Error: Path path/:id already exists
```

### System configuration

**Feathers Dove**: Built from source

https://github.com/feathersjs/feathers/pull/2756

**Comment by daffl** [comment]
What is the rest of your setup? This test is passing for me:

```ts
  it('can unregister a service (#2035, #2767)', async () => {
    app.use('service/:id', {
      async get(id: string | number) {
        return { id }
      }
    })

    assert.strictEqual(app.lookup('service/123').service, app.service('service/:id'))

    app.unuse('service/:id')

    assert.strictEqual(app.lookup('service/123'), null)

    app.use('service/:id', {
      async get(id: string | number) {
        return { id }
      }
    })
  })
```

**Comment by steffanhalv** [comment]
I had problems when trying to `unuse('oauth/:provider')` for update oauth credentials in a cluster dynamically and then re-register again with `app.configure(oauth())`. But it looks like it actually was a problem with one cluster crashing with another app.

Adding a key to sync fixed the problem, so it does not crash with other node apps using same redis connection on the same server:

```js
app.configure(sync({
  uri: process.env.redis || 'redis://localhost:6379',
  key: process.env.name || 'feathers-sync'
}))
```

Btw. app.unuse() is really handy ;)

**Comment by daffl** [comment]
This is an interesting usecase. There might be a way to extend the oAuth provider service for this and allowing to override the configuration dynamically e.g. through `params`.
