### ISSUE TITLE
dove-docs: add docs for `passwordHash` resolver & update & deprecation notice of `hashPassword` hook

### ISSUE THREAD

**Issue by fratzinger** [feathersjs/feathers#2769]
The `hashPassword` hook of `@feathersjs/authentication-local` shows a deprecation notice to use `passwordHash` resolver:
<img width="632" alt="image" src="https://user-images.githubusercontent.com/22286818/192818000-2b7edc59-58e0-4d17-bb1e-f4f91a1dab71.png">

It's hard to migrate this without any further instructions. I would have expected an url in the deprecation notice. There's no documentation about `hashPassoword` at all, right? I think there should be a page for local auth resolvers with `passwordHash`, the same as there is https://dove.feathersjs.com/api/authentication/hook.html .

Maybe it's reasonable to add this to the migration guide somehow as well.

This is the source code:
https://github.com/feathersjs/feathers/blob/dove/packages/authentication-local/src/hooks/hash-password.ts#L17

**Comment by daffl** [comment]
You are totally right, this really should be documented. Added via #2812
