### ISSUE TITLE
Recommended templating engine to use with Feathers?

### ISSUE THREAD

**Issue by NetOperatorWibby** [feathersjs/feathers#277]
Hi everyone!

I've recently switched to using FeathersJS from Jekyll for a client project. However, I need a view engine that will allow me to use partials and templates because I'd rather not write raw HTML for every page, of which there are many. I think HandlebarsJS would be a great tool to use, but I am unsure of how to integrate it into the Feathers workflow.

Can someone point me in the right direction?

**Comment by kulakowka** [comment]
@NetOperatorWibby you can read about rendering views here: http://docs.feathersjs.com/middleware/express.html#rendering-views

You can choose any template engine.

**Comment by NetOperatorWibby** [comment]
@kulakowka Ah, I didn't see that! I wish the views section was clearly visible in the sidebar.

**Comment by ekryski** [comment]
@NetOperatorWibby that's some good feedback! Thanks!
