### ISSUE TITLE
feathers dove: default is ignored for

### ISSUE THREAD

**Issue by prajwal497** [feathersjs/feathers#2776]
### Steps to reproduce
Create a Schema with a nested object property for any class.
Give default: (any value) inside properties of that nested object (type) like below:

```td
export const courseDataSchema = schema({
    $id: 'CourseData',
    type: 'object',
    additionalProperties: false,
    required: ['account', 'has_certificate'], //
    properties: {
      title: { type: 'string' },
      nested_obj: {
        name: { type: 'string' },
        status: { type: 'string', default: 'active'},
      }
  }
});
```

### Expected behavior
This should work without any error.
### Actual behavior
Error: strict mode: default is ignored for: data16.status

**Feathersjs version**: "^5.0.0-pre.29"

**NodeJS version**: "16.17.0"

**Operating System**: 

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by daffl** [comment]
It appears this is the default AJV behaviour - to enable this, the `useDefaults` Ajv option needs to be set. See https://ajv.js.org/options.html#usedefaults and https://dove.feathersjs.com/api/schema/schema.html#ajv

**Comment by prajwal497** [comment]
It is already enabled and it does work on a simple structured schema with no sub or nested objects,
but does not work for sub documents.

**Comment by daffl** [comment]
My guess is that it is because your nested object definition should look like this:

```ts
export const courseDataSchema = schema({
  $id: "CourseData",
  type: "object",
  additionalProperties: false,
  required: ["account", "has_certificate"], //
  properties: {
    title: { type: "string" },
    nested_obj: {
      type: "object",
      properties: {
        name: { type: "string" },
        status: { type: "string", default: "active" },
      }
    },
  },
});
```

**Comment by prajwal497** [comment]
Whats the diffference?

**Comment by daffl** [comment]
Yours is invalid JSON schema. An object definition (including nested ones) always needs to have a

```js
nested_obj: {
  type: "object",
  properties: {
  }
}
```

**Comment by prajwal497** [comment]
Yes i may have missed that in the example but my code does have types for all sub documents (objects and arrays):
Updated Example:

```td
export const courseDataSchema = schema({
    $id: 'CourseData',
    type: 'object',
    additionalProperties: false,
    required: [], //
    properties: {
      title: { type: 'string' },
      nested_obj: {
        type: 'object',
        additionalProperties: false,
        properties:{
           name: { type: 'string' },
           status: { type: 'string', default: 'active'}
        }
      }
  }
});
```
or

```td
export const courseDataSchema = schema({
  $id: 'CourseData',
  type: 'object',
  additionalProperties: false,
  required: [], //
  properties: {
    title: { type: 'string' },
    nested_array: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        properties: {
          name: { type: 'string' },
          status: { type: 'string', default: 'active' }
        }
      }
    }
  }
});
```

**Comment by daffl** [comment]
This appears to still be a limitation of AJV. As noted in https://github.com/ajv-validator/ajv/issues/1710#issuecomment-886007416 if the top level object does not exist the nested schema (and its defaults) will never be evaluated. One thing to try would be setting an empty object in a resolver before the validator runs:

```ts
courseDataResolver = resolve({
  properties: {
    nested_obj: async value => (value || {})
  }
})
```

**Comment by prajwal497** [comment]
I will test this and get back to you
