### ISSUE TITLE
custom defaultValue gets cached in sequelize

### ISSUE THREAD

**Issue by cmauf** [feathersjs/feathers#2778]
Not sure if this is an issue of feathers or any of the dependencies. 

I have a custom method that I want to use as `defaultValue`in one of my models. It's a simple string of random bytes. For reference:

``` createVerificationToken.ts
import { randomBytes } from 'crypto'

export default (length: number): string => {
  return randomBytes(length).toString('hex')
}
```

I imported into my `accounts.model.ts`. My model definition:

``` accounts.model.ts
const accounts = sequelizeClient.define('accounts', {
    avatar: {
      type: DataTypes.STRING
    },
    email: {
      type: DataTypes.STRING,
      allowNull: false,
      unique: true
    },
    emailVerified: {
      type: DataTypes.BOOLEAN,
      defaultValue: false
    },
    lang: {
      type: DataTypes.STRING,
      allowNull: false,
      defaultValue: 'en'
    },
    locked: {
      type: DataTypes.DATE,
      defaultValue: null
    },
    password: {
      type: DataTypes.STRING,
      allowNull: false
    },
    role: {
      type: DataTypes.STRING,
      allowNull: false
    },
    username: {
      type: DataTypes.STRING,
      allowNull: false,
      unique: true
    },
    verificationToken: {
      type: DataTypes.UUID,
      defaultValue: createVerificationToken(16)
    }
  }, {
    hooks: {
      beforeCount (options: any): HookReturn {
        options.raw = true
      }
    }
  });
```

edit: checked if changing `type` to `DataTypes.STRING` fixes it, but the problem prevails

### Steps to reproduce

- create a model like the one above
- create several instances 

### Expected behavior
For each new instance, my `accounts` model should call the `createVerificationToken` method to create a new unique token. 

### Actual behavior
It creates the token once and uses it for each new instance. Have confirmed this with a simple test:

``` js
it('creates unique verification code', async () => {
      let verificationCode: string
      for (let i = 0; i < 10; i++) {
        await createUser() // shorthand for creating an `accounts` instance with random input
          .then(async (resp: any) => {
            console.log(resp.verificationToken)
            if (verificationCode !== undefined) {
              expect(resp.verificationToken).not.toEqual(verificationCode)
            }
            verificationCode = resp.verificationToken
          })
      }
    })
```

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

@feathersjs/feathers: ^4.5.15
feathers-sequelize: ^6.3.3
sequelize: ^6.19.2

**NodeJS version**:
16.15.1

**Operating System**:
Operating System: Manjaro Linux                   
Kernel: Linux 5.15.65-1-MANJARO

**Browser Version**:

**React Native Version**:

**Module Loader**:
npm 8.12.1

**Comment by daffl** [comment]
The defaultValue needs to be a function to be called every time the model is created:

```js
    verificationToken: {
      type: DataTypes.UUID,
      defaultValue: () => createVerificationToken(16)
    }
```
