### ISSUE TITLE
dove: missing dependency `@sinclair/typebox` in `@feathersjs/schema`

### ISSUE THREAD

**Issue by fratzinger** [feathersjs/feathers#2786]
This is a problem which @mdartic encountered here: https://github.com/feathersjs-ecosystem/feathers-authentication-management/pull/196#discussion_r990638194

`@sinclair/typebox` is imported here: https://github.com/feathersjs/feathers/blob/dove/packages/schema/src/json-schema.ts#L3
But not listed in dependencies here: https://github.com/feathersjs/feathers/blob/dove/packages/schema/package.json

**Comment by daffl** [comment]
I noticed that as well and added the fix in https://github.com/feathersjs/feathers/pull/2783 making both modules import their a `getDataValidator` and `getValidator` with their own types.

**Comment by daffl** [comment]
Should be fixed in the next prerelease :)

**Comment by fratzinger** [comment]
Thanks!
