### ISSUE TITLE
Service middleware custom property not working

### ISSUE THREAD

**Issue by jesslekova** [feathersjs/feathers#2790]
In the newest release v5.0.0-pre.30, when I follow the below snippet (from the official FeathersJS documentation) on how to set properties on the service method params, it wouldn't actually show up in the service's params.

```js
app.configure(rest())
  .use(json())
  .use(urlencoded({ extended: true }))
  .use(function (req, res, next) {
    req.feathers.fromMiddleware = 'Hello world'
    next()
  })
```

**Comment by daffl** [comment]
This is indeed something that changed in v5 in that `app.configure(rest())` now has to happen __after__ any other middleware. This is how we now get much faster routing (than built-in Express) and service unregistration at runtime.

This should work which I will update in the docs as well:

```js
app
  .use(json())
  .use(urlencoded({ extended: true }))
  .use(function (req, res, next) {
    req.feathers.fromMiddleware = 'Hello world'
    next()
  })
  .configure(rest())
```

**Comment by jesslekova** [comment]
Thank you so much!
