### ISSUE TITLE
How to provide unique index property in feathers dove schema just like feathers dove mongoose models 

### ISSUE THREAD

**Issue by prajwal497** [feathersjs/feathers#2791]
### Steps to reproduce

Give unique:true to any property in any schema. 

### Expected behavior
It should work like it used to in previous feathers verion with 
### Actual behavior
Gives error
 Error: strict mode: unknown keyword: "unique"

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by prajwal497** [comment]
@daffl can you help me on this?

**Comment by daffl** [comment]
In your `src/mongodb` file add

```ts
mongoClient.then(async db => {
  // Create your indexes here
  await db.collection('movies').createIndex({ title: 1 }, { unique: true });
})
```

**Comment by prajwal497** [comment]
Yes i know that, but mongoose provided unique index property in schema itself
is there no option for that?
Also it will require to add mongoose adapter in dove same as crow, is that going to be included in future release?

**Comment by daffl** [comment]
This is now documented in https://feathersjs.com/api/databases/mongodb.html#indexes
