### ISSUE TITLE
Adapters need built-in sanitation hooks

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers#280]
From @ekryski's https://github.com/feathersjs/feathers-authentication/issues/132#issuecomment-201924532authentication/issues/132#issuecomment-201915333
> One thing we may want to do though, is have a built in hook that runs on every POST, PATCH, PUT request and escapes script code rather than relying on making sure the ORM or the developer handle it.

We ought to provide this for at least the db adapters that don't have an ORM that does it already.  I'm pretty sure Mongoose takes care of this, but we ought to check everything.

**Comment by ekryski** [comment]
Yes I think it should just be a common hook that gets put into every app or is at least added by the generator automatically for you.

**Comment by harangue** [comment]
I'd definitely prefer for it to be an explicit, separate hook in `feathers-hooks`. Sure, people might hate having to add the extra line, but I think any sanitation solution will modify things significantly enough that it should be clearly visible in the code. Plus it allows people to sub it for different solutions, or customize things. How about [https://github.com/theSmaw/Caja-HTML-Sanitizer](Google Caja's HTML Sanitizer)?

**Comment by ekryski** [comment]
@harangue that was kind of my thought as well. I think a happy medium is what we do currently with the other auth hooks; add it using the generator by default and document it.

**Comment by marshallswain** [comment]
I completely agree.  Implicit magic functionality always ends up costing time.

**Comment by ekryski** [comment]
Maybe this should actually be an issue in `feathers-hooks` then. Let's create one there and link to this one.

**Comment by marshallswain** [comment]
Yeah.  It makes sense to put it there, since it's not the adapter that needs it, but the DB itself.

**Comment by marshallswain** [comment]
Closing in favor of https://github.com/feathersjs/feathers-hooks/issues/62
