### ISSUE TITLE
App not running from feathersjs\cli@5.0.0-pre.31 : feathers generate app command

### ISSUE THREAD

**Issue by prajwal497** [feathersjs/feathers#2800]
start script is node lib.
feathers is not creating lib

```feathers generate app
? Do you want to use JavaScript or TypeScript? TypeScript
? What is the name of your application? dove_test
? Write a short description
? Which HTTP framework do you want to use? Express
? What APIs do you want to offer? HTTP (REST), Real-time
? Which package manager are you using? npm
? Which database are you connecting to? Other databases can be added at any time MongoDB
? Enter your database connection string mongodb://localhost:27017/dove_test
? Which authentication methods do you want to use? Other methods and providers can be added at any time. Email + Password
```

### Expected behavior
Should start app

### Actual behavior
error : Cannot find module {project_path}\lib

### System configuration

**feathers Version**: ^5.0.0-pre.31

**Comment by daffl** [comment]
This has been changed to allow for proper production deploys. For a TypeScript app you have to run `npm run compile` before starting it or use the development mode with `npm run dev`.

**Comment by prajwal497** [comment]
I replaced node lib/ script with ts-node src/

**Comment by daffl** [comment]
The step is now documented in the CLI guide at https://dove.feathersjs.com/guides/cli/declarations.html
