### ISSUE TITLE
Add 'findOrCreate' method to service interface

### ISSUE THREAD

**Issue by petermikitsh** [feathersjs/feathers#281]
This is a feature request to add a `findOrCreate` method to the [service interface](http://docs.feathersjs.com/services/readme.html#service-methods).

`findOrCreate(data, params [, callback])` - Attempts to find a resource with `data`. If no resource is found, creates a new resource with `data`. The method should return a Promise with the newly created or existing `data`.

One particular use case where it would be beneficial to have is in creating custom authentication implementation adapters. This proposed service method could be used in the [OAuth implementation](https://github.com/feathersjs/feathers-authentication/blob/master/src/services/oauth2/index.js#L35-L61) :)

Thoughts? It's not a strictly conventional CRUD type of operation, but more of a nice-to-have.

**Comment by marshallswain** [comment]
Sticking to RESTful services is definitely one of our values.  There is a way to expose custom service methods manually through Express, but it's not available on all providers: http://docs.feathersjs.com/help/faq.html#can-i-expose-custom-service-methods

In my experience, `findOrCreate` is typically a behavior that you want always turned on on certain services, for all queries.  You can actually do it either as a before-hook or an after-hook on `create`.  The most basic version of what I think you're after would be a before-hook on `create`:

```js
'use strict';
/**
 * If the record doesn't already exist, create it and return it to the user.
 */
module.exports = function(){
  return function(hook){
    const service = hook.app.service('/api/records');

    return new Promise(function(resolve, reject){
      let params = {
        query: hook.params.data,
        user: hook.params.user
      };
      
      function processRequest(response){
        // If a service has pagination enabled or not, handle either way.
        if (response.length || response.data && response.data.length) {
          // Set the result to skip the call to `create` if a record was found.
          hook.result = response.data ? response.data[0] : response[0];
        }
        resolve(hook);
      }

      service.find(params)
        .then(response => processRequest(response))
        .catch(e => {
          console.log('Error message.', hook.data, e);
          reject(e);
        });
    });
  };
};
```

**Comment by petermikitsh** [comment]
For my particular use case, I didn't even want to expose it externally over HTTP or Websockets. A hook is more appropriate. Thanks for the recommendation.
