### ISSUE TITLE
How to output text/plain using hook

### ISSUE THREAD

**Issue by takaaptech** [feathersjs/feathers#282]
For some reason, i want to out put some text in get/find method, for example: http://localhost:3030/messages?param=abc
will output: some text here
- If i set hook.result = 'some text here' , it will output "some text here" (include " in result, so how can i remove " symbol)
- How to change format to text/plain in hook

Thank!

**Comment by marshallswain** [comment]
You change the format using the `Accept` header.  It's not done in a hook.  The client app has to specify it in the request.

**Comment by marshallswain** [comment]
Try using Postman and setting the header in the request: https://www.getpostman.com

**Comment by marshallswain** [comment]
Found it in the docs: 

> If you want to have the response in json format be sure to set the Accept header in your request to application/json otherwise the default error handler will return HTML.

**Comment by ekryski** [comment]
@takaaptech actually what @marshallswain said is only partly right. You will probably also need to overwrite the response formatter function. [See here for more detail](http://docs.feathersjs.com/rest/readme.html#customizing-the-response-format).

**Comment by takaaptech** [comment]
OK, i just implement and it works. But i want other method like create,update works as normal (no change). How can i do this?
 If i set:
 .use('/messages', {
    
    get(id, params) {
      return Promise.resolve({
        text: 'Feathers is great!'
      });
    },

    find(id, params) {
      return Promise.resolve({
        text: 'Feathers is great!'
      });
    }

  })

When post new record, it throws error:
info: MethodNotAllowed: Method `create` is not supported by this endpoint.
    at Object.construct (/Users/macbook/nodejs_projects/apiserver/node_modules/core-js/modules/es6.reflect.construct.js:22:24)
    at MethodNotAllowed.ExtendableBuiltin (/Users/macbook/nodejs_projects/apiserver/node_modules/feathers-errors/lib/index.js:21:28)

**Comment by ekryski** [comment]
@takaaptech you either need to implement those methods yourself or [extend a service adapter](http://docs.feathersjs.com/databases/extending.html).

Glad that worked for you. I'm going to close this as the original issue looks to be resolved. :smile:
