### ISSUE TITLE
Virtual resolver properties

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers#2821]
## The problem

Currently, there is no differentiation between resolver properties that come from the database and "computed" properties like a `fullName` which is composed from `user.firstName` and `user.lastName`. Consider the following resolver:

```ts
type User = {
  firstName: string
  lastName: string
  fullName: string
}

const userResolver = resolve<User, Context>({
  properties: {
    fullName: async (_value, user, context) => {
      return `${user.firstName} ${user.lastName}`
    }
  }
})
```

Currently we don't know if this property is completely computed or already exists in the database. Some of the repercussions in a Feathers app is that we can't use the [$select query syntax](https://dove.feathersjs.com/api/databases/querying.html#select) for resolvers because we don't know what fields are in the database and which are dynamically resolved so a `$select: [ 'fullName', 'firstName' ]` would pass `fullName` as a field to select from to the database and causes an error. Additionally we don't know that the `fullName` resolver requires a `firstName` and `lastName` to be present on the original data.

## Suggestion

Create `computed` property resolver wrapper that indicates a computed property and optionally pass the names of the dependent fields (a fairly common pattern already in web development, e.g. in React hook effects). This could also address an additional concern brought up by @DaddyWarbucks that the `value` (the first argument) for a computed resolver will always be `undefined`. For the above example this would look like this:

```ts
import { resolve, computed } from '@feathersjs/schema'

type User = {
  firstName: string
  lastName: string
  fullName: string
}

const userResolver = resolve<User, Context>({
  properties: {
    fullName: computed<User, Context>(async (user, context) => {
      return `${user.firstName} ${user.lastName}`
    }, ['firstName', 'lastName'])
  }
})
```

It is a little more verbose but would allow tools using the resolver (like `schemaHooks.resolveResult`) to create a `$select` that is database friendly and also making sure that all dependent properties are selected.

Related to

- https://github.com/feathersjs/feathers/issues/2595
- https://github.com/feathersjs/feathers/issues/2604

**Comment by DaddyWarbucks** [comment]
This makes sense!

I think  `computed` should take the same arguments as a regular resolver. No need to solve `undefined` argument here.

I don't think I would call it `computed`. Because this could still be used on resolvers that are not necessarily "computed" but also have dependencies.  For example
```js
import { resolve, computed } from '@feathersjs/schema'

type User = {
  firstName: string
  nickName: string
}

const userResolver = resolve<User, Context>({
  properties: {
    nickName: computed<User, Context>(async (user, context) => {
      return user.nickName || user.firtName;
    }, ['firstName'])
  }
})
```

So its really two problems. Maybe its two functions?

```js
import { resolve, computed, dependent } from '@feathersjs/schema'

const userResolver = resolve({
  properties: {
    fullName: computed(
      dependent(
        async (user, context) => {
          return `${user.firstName} ${user.lastName}`;
        },
        ['firstName', 'lastName']
      )
    ),
    nickName: dependent(
      async (user, context) => {
        return user.nickName || user.firstName;
      },
      ['firstName']
    )
  }
});
```

**Comment by DaddyWarbucks** [comment]
Heres is some code I threw around in a Discord chat about this problem too. Maybe its helpful for reference.
```js
class Select {
  constructor() {
    this.selects = {};
  }

  // Too bad we don't automatically know the resolver key
  result(resolverKey, deps, resolver) {
    this.selects[resolverKey] = deps;
    return resolver;
  }

  select() {
    return ($select, query) => {
      // Hmmm. query.$resolve may have its own resolver query running on it
      // if so it needs to be resolved first.
      if (!query.$resolve) {
        return $select;
      }

      const selects = [];
      Object.entries(this.selects).forEach((key, deps) => {
        if (query.$resolve.includes(key)) {
          selects.concat(deps);
        }
      });

      if (!$select) {
        return selects;
      }

      return [].concat($select, selects).filter((item, index, self) => {
        return self.indexOf(item) === index;
      });
    };
  }
}

const select = new Select();

// query resolvers.
{
  // If you need a resolver for the $resolve query, you need
  // to break this out into its own resolver and call resolveQuery twice
  // $resolve: () => {}

  $select: select.select()
}

// result resolvers
{
  // Too bad we don't automatically know the resolver key
  user: select.result('user', ['user_id'], (value, result, context) => {
   // result.user_id is guaranteed to be here
   ...load the user
  })
}
```

**Comment by daffl** [comment]
Yeah I didn't think `computed` was a great name either. My other thought was `virtual`. Looking at your snippets I'm actually wondering if this could address the other thing you were mentioning in executing dependent resolver properties as well 🤔 

```ts
import _ from 'lodash'
import { resolve, computed } from '@feathersjs/schema'

type User = {
  firstName: string
  lastName: string
  fullName: string
  userName: string
}

const userResolver = resolve<User, Context>({
  properties: {
    userName: computed<User, Context>(async (user, context) => {
      return _.camelCase(user.fullName)
    }, ['fullName']),
    fullName: computed<User, Context>(async (user, context) => {
      return `${user.firstName} ${user.lastName}`
    }, ['firstName', 'lastName'])
  }
})
```

**Comment by AshotN** [comment]
+1 for virtual instead of computed

**Comment by daffl** [comment]
I'm going to close this since virtual property resolvers [are now available](https://dove.feathersjs.com/api/schema/resolvers.html#virtual-property-resolvers). We can create a follow-up issue on how to handle dependencies.
