### ISSUE TITLE
dove-docs: footer on mobile is displaced

### ISSUE THREAD

**Issue by fratzinger** [feathersjs/feathers#2825]
The footer of the new docs looks like this on mobile:

![Screenshot_20221021-063803_Chrome](https://user-images.githubusercontent.com/22286818/197113419-35347a23-123f-499e-bd19-1feca11fd1e2.jpg)

For example here: https://dove.feathersjs.com/api/hooks.html

System: Android
Device: Samsung S21 FE
Browser: Webview (Samsung Browser (?) and Android Chrome)

**Comment by daffl** [comment]
Can confirm. This must've gotten borked when @marshallswain and I fiddled with it. For some reason it adds a `sidebar-adjust` with a huge margin:

<img width="419" alt="Screenshot 2022-10-21 at 8 17 52 AM" src="https://user-images.githubusercontent.com/338316/197230786-a39f7274-3044-4cd6-ade7-72d711ecfd42.png">

**Comment by daffl** [comment]
The problem is the 

```html
<style>
/* Only indent the footer on pages other than home-page */
#app:not(.home-page) .feathers-footer.sidebar-open .sidebar-adjust {
  margin-left: 272px;
}
</style>
```

in https://github.com/feathersjs/feathers/blob/dove/docs/components/Footer.vue#L61-L66
