### ISSUE TITLE
Upload File

### ISSUE THREAD

**Issue by dondyb** [feathersjs/feathers#283]
Hi,

What's the best practice to do a file upload using Feathers? Any example?

**Comment by daffl** [comment]
Although you closed it, https://github.com/expressjs/multer (or any other Express middleware for file upload) might help here.

**Comment by dondyb** [comment]
Sorry, I was trigger happy before clicking close. 

And yes, If I use Multer or multipart won't it conflict with body-parser?

Regards,

**Comment by daffl** [comment]
I haven't used it yet but I don't think bodyParser parses multiPart uploads. Were you able to give it a try?

**Comment by marshallswain** [comment]
@daffl thanks for pointing out multer.  I feel a demo app coming up.

**Comment by ekryski** [comment]
I've created an issue in the docs repo: https://github.com/feathersjs/feathers-docs/issues/111. Although this isn't resolved I would like to close and refer to that one.
