### ISSUE TITLE
Debugging network traffic using React Native.

### ISSUE THREAD

**Issue by yberstad** [feathersjs/feathers#284]
Hi!
I trying to create a React Native app, using FeatherJS as backend, but I am having issues to see/debug the network traffic when debugging the React Native app in Chrome.

I’m using the “hack” you are referring to for RN, but I cannot get it to work even when using RN 21. When using RN 22.2, the “hack” does not work at all, as Erik Kryski stated on his article on medium.com. Do you know of when (if) this will be fixed? Is there an option to use Primus with SockJS, or will I run into the same issues?

I have run through the React chat tutorial, and everything worked fine regarding viewing the WS network traffic in Chrome.

I have tried to get some help on SO, but no response so far. I am therefore hoping you guys might give me some guidance? I feel a bit lost without having the opportunity to debug/view what is on the wire, while I’m developing... 

This is my SO question:
http://stackoverflow.com/questions/36252580/debugging-network-traffic-using-featherjs-socket-io-and-react-native

Thanks in advance!

-Kind regards, Øyvind.

**Comment by ekryski** [comment]
@yberstad I did see your SO question. I need to verify something before I respond. Regarding a fix for RN 22+ in either RN or Socket.io that's out of our control right so I don't know how long. We might fork engine.io until this issue gets merged: https://github.com/socketio/engine.io-parser/pull/55.

**Comment by yberstad** [comment]
@ekryski, thank you so much for your quick response, I really appreciate it!  

Sorry if this came out as been impaction, I know you guy's have a lot to do, but I was not sure if SO was the right/best place for asking questions regarding FeatherJS.

Looking forward to hear from you again.

**Comment by ekryski** [comment]
@yberstad nope all good. I'll do a proper answer on there as well once I have one for you. Just give me a day or two.

**Comment by yberstad** [comment]
Sweet, thanks! :)

**Comment by yberstad** [comment]
@ekryski Hi Erik, it's not much happening over at engine.io-parser, is there... ;-) Sorry to say, but I had to jump over to Meteor for now, I needed some real time communication and the latest versions of RN. Their ddp-client works with RN and they now support NPM from the 1.3 version, which was one of my main concerns with Meteor. Thanks for your help, I'll have you guys in the back of my head for my projects to come :-)

**Comment by ekryski** [comment]
We've updated instructions in the docs on how to use socket.io with react native. Works like a champ! You can inspect websocket traffic by using the chrome inspector tab.

**Comment by yberstad** [comment]
@ekryski Sweet, thanks!
