### ISSUE TITLE
Cryptic error message on "setup-only" service.

### ISSUE THREAD

**Issue by HatiEth** [feathersjs/feathers#285]
Just noticed if you create a service with only a Service#setup(...) function and `app.use(...)` it. 
You get a cryptic error message ( my guess - it's coming from express ), "Router.use() requires middleware function but got a Object".

Example:
```
// Error
const SomeService = {
	setup(app, path) {}
}
​
// No Error
​
const AnoterService = {
	setup(app, path) {},
	create(data, params, cb) {}
}
​
​
app.use('/some', SomeService); // cryptic error
app.use('/another', AnotherService); // Fine
```

**Comment by ekryski** [comment]
@HatiEth great bug report! Thank you. This is cryptic. This might stay open for a bit but we'll definitely address this.
