### ISSUE TITLE
docs: Lorem Ipsum

### ISSUE THREAD

**Issue by fratzinger** [feathersjs/feathers#2867]
Just a reminder to change lorem placeholders on the front page:

<img width="1680" alt="Bildschirmfoto 2022-11-08 um 10 09 21" src="https://user-images.githubusercontent.com/22286818/200522999-d1367081-a5ad-45e2-88d1-ea35bb8d5cbb.png">

https://dove.feathersjs.com/

Source Code:
- https://github.com/feathersjs/feathers/blob/1226facff1c89906c612868f8f1ebb316bef0b76/docs/components/HomeSupporter.vue
- https://github.com/feathersjs/feathers/blob/1226facff1c89906c612868f8f1ebb316bef0b76/docs/components/HomeIndustryPartners.vue

**Comment by daffl** [comment]
This has been fixed yesterday. We're planning on adding more content but the homepage at https://dove.feathersjs.com/ should be good to go now.
