### ISSUE TITLE
page parameter "total" is not the actual number of items in the database when using composite primary key

### ISSUE THREAD

**Issue by Leo843** [feathersjs/feathers#2869]
### Description

When a GET request is made to the REST API, parameter "total" in the response is not the actual number of items in the database table.

This behavior occurs when a service uses Sequelize with PostgreSQL and the model is defined with a composite primary key (more than one primary key).

### Steps to reproduce

I made a [repo](https://github.com/Leo843/feathersjs-composite-primary-key-issue) to reproduce the issue. Clone the repository and run `docker compose run test-runner`.

### Expected behavior

Parameter "total" must always be the actual number of items in the table, even when the model uses a composite primary key.

**Comment by daffl** [comment]
This is likely a duplicate of https://github.com/feathersjs-ecosystem/feathers-sequelize/issues/343

**Comment by Leo843** [comment]
> Just stumbled on this. Waiting for a fix, but until then try adding this to your Sequelize model (syntax as of Sequelize v4):
> 
> ```js
> hooks: {
>   beforeCount(options) {
>     options.distinct = false;
>   },
> },
> ```

_Originally posted by @1valdis in https://github.com/feathersjs-ecosystem/feathers-sequelize/issues/343#issuecomment-874798529_

Doing this, fixed the issue for me.
