### ISSUE TITLE
Dove: typebox, validateQuery, resolveQuery, querySyntax, queryProperties, queryProperty, resolveExternal  questions

### ISSUE THREAD

**Issue by primozs** [feathersjs/feathers#2871]
### Example code

```ts
import { resolve } from '@feathersjs/schema';
import {
  Type,
  getDataValidator,
  getValidator,
  querySyntax,
  Static,
} from '@feathersjs/typebox';
import { passwordHash } from '@feathersjs/authentication-local';
import type { HookContext } from '../../declarations';
import { dataValidator, queryValidator } from '../../schemas/validators';

export const userSchema = Type.Object(
  {
    id: Type.String(),
    email: Type.String({ format: 'email' }),
    password: Type.String({ minLength: 8 }),
    full_name: Type.String(),

    permissions: Type.ReadonlyOptional(Type.String()),
    resetExpires: Type.ReadonlyOptional(Type.Date()),
    resetToken: Type.ReadonlyOptional(Type.String()),
    verified: Type.Readonly(Type.Boolean()),
    createdAt: Type.Optional(Type.Date()),
    updatedAt: Type.Optional(Type.Date()),
  },
  { $id: 'User', additionalProperties: false },
);

export type User = Static<typeof userSchema>;

export const userResolver = resolve<User, HookContext>({
  properties: {},
});

export const userExternalResolver = resolve<User, HookContext>({
  properties: {
    password: async () => undefined,
    resetExpires: async () => undefined,
    resetToken: async () => undefined,
    verified: async () => undefined,
  },
});

export const userDataSchema = Type.Pick(
  userSchema,
  ['email', 'password', 'full_name'],
  {
    $id: 'UserData',
    additionalProperties: false,
  },
);
export type UserData = Static<typeof userDataSchema>;

export const userDataValidator = getDataValidator(
  userDataSchema,
  dataValidator,
);

export const userDataResolver = resolve<User, HookContext>({
  properties: {
    password: passwordHash({ strategy: 'local' }),
    updatedAt: async () => new Date(),
  },
});

const userQueryProperties = Type.Pick(userSchema, ['id', 'email'], {
  additionalProperties: false,
});

const userQuerySchema = querySyntax(userQueryProperties);

export type UserQuery = Static<typeof userQuerySchema>;

export const userQueryValidator = getValidator(userQuerySchema, queryValidator);

export const userQueryResolver = resolve<UserQuery, HookContext>({
  properties: {
    id: async (value, user, context) => {
      if (context.params.user) {
        return context.params.user.id;
      }
      return value;
    },
  },
});

```

### Questions
1. userQueryProperties has specified "id", "email", additionalProperties:false but its not limiting queries by optional resetToken or random property that is not int the schema. I would expect additionalProperties:false to work. 
2. where should the error happen for non existing properties?  validateQuery or resolveQuery. querySyntax seams to have additionalProperties set to false and is also using queryProperties which also has additionalProperties set to false should validator throw an error?
3. how to silently remove invalid query property? 
4. how to use queryProperties, queryProperty in user codebase?
5. userQueryResolver: how to examples from feathers-authentication-hooks, feathers-permissions specifically how to do something like this:

```ts
app.service('messages').hooks({
  before: {
    find: [
      checkPermissions({
        roles: ['super_admin', 'admin'],
        field: 'roles',
        error: false
      }),
      iff(context => !context.params.permitted,
        setField({
          from: 'params.user._id',
          as: 'params.query.userId'
        })
      )
    ]
  }
});
```

6 resolveExternal / depricated protect
```ts
   it('get user does not expose user application data', async () => {
      const service = app.service('users');

      const user1 = await service.create(
        {
          full_name: full_name1,
          email: email1,
          password: password1,
        },
        {
// test external works for "protect" but it does not work for "resolveExternal"
          provider: 'rest',
        },
      );

      await service.remove(user1.id);

      assert.ok(!user1.password);
      assert.ok(!user1.resetExpires);
      assert.ok(!user1.resetToken);
      assert.ok(!user1.verified);
    });
```

**Comment by marshallswain** [comment]
> I would expect additionalProperties:false to work

Agreed.  It should work.  A minimal reproduction would be really useful, if you can spare the time.

> where should the error happen...

the validate hooks.

> how to silently remove invalid query property?

Probably by replacing `context.params.query` with a new object made by `_.pick(context.params.schema, ...Object.keys(querySchema.properties)`

> how to use queryProperties, queryProperty in user codebase?

- You can see in the source that queryProperties just applies `queryProperty` to each key in the provided object.  
- There's an example of `queryProperty` in the JSON Schema page of the docs: https://dove.feathersjs.com/api/schema/schema.html#queryproperty
- There's a test example: https://github.com/feathersjs/feathers/blob/dove/packages/schema/test/schema.test.ts#L120
- I think there's an example in each generated service in the schema file toward the bottom, in the query schema section.

> 5 userQueryResolver...

I'll get back to this one after sleepy time.

> 6 resolveExternal / depricated protect

Need more info.  The question isn't popping out to me.

**Comment by primozs** [comment]
@marshallswain Hello, thank you very much!
1. query validation
If I take basic cli generated app: Typescript, Express, Typebox, Sql, migrate run. 
in the users service hook before all, at the last place I put
```ts
(ctx) => {
          console.log(ctx.params.query)
        }
```
Then, create user and login, then query users with full_name=Something, prints:
```
{ full_name: 'Something', id: 1 }
I would expect to throw before and console.log not to run.
```

Also I am getting sqlite error instead of validation error. It runs service method, I would expect not to run it.
```
{
  "name": "BadRequest",
  "message": "select `users`.* from `users` where `full_name` = 'Something' and `id` = 1 order by `users`.`id` asc limit 10 - SQLITE_ERROR: no such column: full_name",
  "code": 400,
  "className": "bad-request"
}
```

6. About question 6. sorry for not elaborating.

resolveExternal Actually works if I call the api with Insomnia for example. If I run the test with params.provider I would expect to simulate external request. In this case it still returns the "unwanted" properties. resolveExternal is the last after hook. If I test the same thing with "protect" hook it does remove the unwanted properties as expected. It seams resolveExternal does not take into account params.provider somehow or in some case . Or I don't know how to test this.

**Comment by daffl** [comment]
You're right, there seems to be a problem with the `querySyntax` helper and unless explicitly defined, `Type.Intersect` does allow additional properties 😐 I'm working on finalising some of those helpers (we still have to add support for custom operators as well) so that'll definitely be solved.

As for some of the other questions:

You can set the [removeAdditional](https://ajv.js.org/options.html#removeadditional) option for the `queryValidator` in `src/schema/validators.ts` (going forward `src/validators.ts`) to silently remove additional properties.

For permissions you'd still use the permission hook. Then you can replace the entire `feathers-authentication-hooks` package and the `iff` and `setField` hook with a three-line query property resolver:

```ts
export const messageQueryResolver = resolve<MessageQuery, HookContext>({
  properties: {
    userId: async (value, user, context) => {
      if (!context.params.permitted) {
        return context.params.user.id
      }

      return value
    }
  }
})
```

Note that the order is important, `checkPermissions` has to run before `schemaHooks.resolveQuery`.

```ts
app.service('messages').hooks({
  before: {
    find: [
      checkPermissions({
        roles: ['super_admin', 'admin'],
        field: 'roles',
        error: false
      }),
     schemaHooks.resolveQuery(messageQueryResolver)
    ]
  }
});
```

**Comment by primozs** [comment]
@daffl Thank you for the info and examples.
