### ISSUE TITLE
channels.ts app.on('login') authenticated **user**

### ISSUE THREAD

**Issue by jbridgenet** [feathersjs/feathers#2874]
1) Created an sample app:
`npm create feathers@pre feathers-chat
`

2) modified channels.ts:
 app.on('login', (authResult: any, { connection }: Params) => {
    // connection can be undefined if there is no
    // real-time connection, e.g. when logging in via REST
    ```
console.log('login:')
    console.log('authResult:', authResult)
    console.log('connection:', connection)
```
    if (connection) {

3) run test:
`npm run test
`

4) console.log:
Feathers application tests
    ✔ starts and shows the index page
    ✔ shows a 404 JSON error

  application client tests
    ✔ initialized the client
login:
authResult: {
  accessToken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6ImFjY2VzcyJ9.eyJpYXQiOjE2NjgxOTkyMTYsImV4cCI6MTY2ODI4NTYxNiwiYXVkIjoiaHR0cHM6Ly95b3VyZG9tYWluLmNvbSIsInN1YiI6IjYzNmViMzMwNDZlNTdiMTNhMTVjMzk2YiIsImp0aSI6IjQzMzA0OTlkLTBkMjUtNDdmYy1hYTlkLWIwNGM3ZDhhMWVjOCJ9.Of5HZxv2QyByhgaAC5RD8tUEkyAAidzMnGZ7TyiXx08',
  authentication: {
    strategy: 'local',
    payload: {
      iat: 1668199216,
      exp: 1668285616,
      aud: 'https://yourdomain.com',
      sub: '636eb33046e57b13a15c396b',
      jti: '4330499d-0d25-47fc-aa9d-b04c7d8a1ec8'
    }
  },
  user: {
    _id: new ObjectId("636eb33046e57b13a15c396b"),
    email: 'someone@example.com',
    password: '$2a$10$I./.4jK4BTZVlHgw5Ez0eOrUHCE7FyIir1JDP8/BGXh653jyGHKpa'
  }
}
connection: undefined
    ✔ creates and authenticates a user with email and password (263ms)

  users service
    ✔ registered the service

  5 passing (341ms)

5): question:

Note that: authenticated **user** is attached to 'authResult', not to 'connection'.

in your code, you stated:
By default it is located in connection.user once the client has authenticated on the socket (usually by calling app.authenticate() on the [client](https://dove.feathersjs.com/api/client.html)).

**Comment by daffl** [comment]
That test is using an HTTP client which is not a real-time protocol and therefore does not have a `connection` object (as the comment above mentions). You will see a `connection` if you update the `test/client.test` to use the [Socket.io client](https://dove.feathersjs.com/api/client/socketio.html).

**Comment by marshallswain** [comment]
Closing for now.  Feel free to reopen if you still find a problem after you try a real-time adapter.
