### ISSUE TITLE
UNMET PEER DEPENDENCY yo@>=1.0.0

### ISSUE THREAD

**Issue by egonisgone** [feathersjs/feathers#288]
I'm getting this warning after installing feathers:

```
└─┬ feathers-cli@1.2.2
  └── UNMET PEER DEPENDENCY yo@>=1.0.0

npm WARN generator-feathers-plugin@0.6.9 requires a peer of yo@>=1.0.0 but none was installed.
```

Sorry if the fix is obvious, I'm a novice. I haven't been able to find a solution on the internet or by myself (I tried to update feathers-cli and yo manually and stuff like that...).

**Comment by derek-watson** [comment]
Thanks @egonisgone, the fix was addressed [here](https://github.com/feathersjs/feathers-cli/commit/0942cc5ca86001f7e3e5377bdca786ff5603ca75).

I've moved this issue over to feathersjs/feathers-cli#13 to track it against a forthcoming 1.2.3 release.
