### ISSUE TITLE
[crow] Update grant and other dependencies 

### ISSUE THREAD

**Issue by skinofstars** [feathersjs/feathers#2886]
### Steps to reproduce

Grant (along with many other dependencies) is out of date. Please can we get them updated on Feathers 4?

### Expected behavior

Packages dependencies for stable branch are kept up to date

### Actual behavior

In most cases, dependencies haven't been updated for 6 months

### System configuration

Feathers 4 - crow

**Comment by daffl** [comment]
Unfortunately this is not possible since they all come with major breaking changes. You can update the dependencies to v5 by [following the migration guide](https://dove.feathersjs.com/guides/migrating.html).
