### ISSUE TITLE
Seeding data

### ISSUE THREAD

**Issue by khwerhahn** [feathersjs/feathers#290]
How can data be seeded? Does anyone have a good method (sequelize)?

**Comment by marshallswain** [comment]
I generally use a database manager for whichever DB I'm using, or issue supported import commands for the DB directly from the command line.

**Comment by marshallswain** [comment]
Which DB?

**Comment by khwerhahn** [comment]
sequelize postgres

**Comment by marshallswain** [comment]
I'd recommend using a utility like Postico.  https://eggerapps.at/postico/  Convert your JSON data to and SQL insert and paste it in.

![screen shot 2016-04-03 at 1 51 34 pm](https://cloud.githubusercontent.com/assets/128857/14234571/60f1022c-f9a3-11e5-930e-8f8f95d00697.jpg)

**Comment by marshallswain** [comment]
Another option is to use a utility like Paw: https://luckymarmot.com/paw
Paste in your JSON into a POST request body and send it in through Feathers.
![screenshot_1 2x-6052515863](https://cloud.githubusercontent.com/assets/128857/14234585/b4fc89a4-f9a3-11e5-9cf9-8ea5c7627574.png)

Postman for Chrome would work, too.

Hopefully that's helpful.  I'm going to close this issue as it's not really something that's within the scope of Feathers.

**Comment by marshallswain** [comment]
Since services support creating many records by sending an array of records, the second solution is probably the way to go.  It will work no matter which database you use.

**Comment by daffl** [comment]
You can also initialize seed data by requiring the app in a separate file and then using `app.service`. Something like:

```js
const app = require('./app');
const data = require('./data/seed.json');

app.service('messages').create(data);
```

**Comment by khwerhahn** [comment]
thanks everyone! @daffl @marshallswain

**Comment by EmirGluhbegovic** [comment]
@daffl I am trying to seed data to the my sequalize postgres db.  I am using your approach but the issue I am having is that I get that the error: relation  {TABLE} does not exist. If I restart the code then it runs. So every time its a fresh start how can I ensure that the tables are ready?

**Comment by daffl** [comment]
You can use

```js
const app = require('../../src/app');

module.exports = async () => {
  app.setup();

  await app.get('sequelizeSync');

  // Do seeding here
};
```
