### ISSUE TITLE
[dove] how to keep value across services and hooks

### ISSUE THREAD

**Issue by anonimusprogramus** [feathersjs/feathers#2911]
In file channels upon `"on connection" `event, a user needs to join his own channels using his Id. So I call a service to fetch complete user profile from db by Id, then join him properly.

Question:

1. To minimize db call, the result of fetching user will be used later in hooks & services; where can I keep it so I can access it later? _(as recommended, app.set is not a choice)_

2. The argument given for "on connection" event is **connection** object (Partial<Params>), the argument given for services is full **params**, for hooks is **context**; I read somewhere that this is by-design. Are they separated and exclusive? Is it possible to access the same app (feathers) object? 

Thank you

**Comment by daffl** [comment]
The `params` object is the same across all hooks and the service call. You can add any value to it at any time in the call. Note that it'll have to be passed explicitly to other service calls.

**Comment by anonimusprogramus** [comment]
Alright, I just tried,

```javascript
// channels.ts
app.on('connection', async (connection: Partial<Params>) => {
  if (connection) {
    console.log(connection)

    const user = await app.service('auth').fetchUser({ calledFromChannel: true }, connection)
    if (user) {
      for (const group of user.groups) {
        app.channel(group + '/' + user.id).join(connection)
      }
    }
  }
})
```

and here's the log
```javascript
{
  provider: 'socketio',
  headers: {
    host: 'localhost:3030',
    connection: 'keep-alive',
    userid: 'user:z5vsxeidf7nic49hfk11',
    accept: '*/*',
    'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36',
    'sec-gpc': '1',
    'accept-language': 'en-US,en',
    origin: 'http://localhost:5173',
    'sec-fetch-site': 'same-site',
    'sec-fetch-mode': 'cors',
    'sec-fetch-dest': 'empty',
    referer: 'http://localhost:5173/',
    'accept-encoding': 'gzip, deflate, br'
  }
}
```

As shown above, the `connection` object is just sub/part of full params.
Is there a way to pass full `params` explicitly from channel to that auth service?

**Comment by daffl** [comment]
A user won't be available until in the `login` event. The `connection` even always happens before that.

**Comment by anonimusprogramus** [comment]
Oh sorry David, my bad :see_no_evil:
I forget to tell that currently I'm not using `@feathersjs/authentication`, but just a simple ACL with JWT to fetch user, and it's working.

But that's where I'm curious about where to keep fetched user -- inside` params.user`, or else -- because channel has only `connection`.

**Comment by anonimusprogramus** [comment]
I can confirm that adding values to params (as you pointed) works fine, thanks.
Here's what I come so far -- not best practice but serves the need.

```javascript
// declarations.ts
export interface IContainer {
  user?: IUser
  blockpassed?: boolean
}

declare module '@feathersjs/feathers' {
  interface Params {
    container?: IContainer
  }
}
```

```javascript
// in channels.ts
app.on('connection', async (connection: Partial<Params>) => {
  if (connection) {
    // strip any sent values
    connection.container = {}

    const user = await app.service('auth').fetchUser({ calledFromChannel: true }, connection)
    if (user) {
      for (const group of user.groups) {
        app.channel(group + '/' + user.id).join(connection)
      }
    }
  }
})
```

```javascript
// auth.ts (service)
async fetchUser(data: any, params: Params): Promise<IUser | undefined> {
  // just return fetched user if available
  if (params.container?.user) {
    return params.container.user
  }

  // get safe & complete user from db

  params.container!.user = user
  return user
}
```

I'm closing this. Thanks @daffl :+1:
