### ISSUE TITLE
Documentation for Configuration, TypeBox and .dotenv

### ISSUE THREAD

**Issue by tvld** [feathersjs/feathers#2912]
Has the [documentation](https://dove.feathersjs.com/api/configuration.html#configuration-validation) for configuration been updated to latest TypeBox? 

The latest ``npm create...`` (v.33) gave me not the file as in the docs, but  this ``configuration.ts``:
```ts
import { Type, getValidator, defaultAppConfiguration } from '@feathersjs/typebox'
import type { Static } from '@feathersjs/typebox'

import { dataValidator } from './validators'

export const configurationSchema = Type.Intersect([
  defaultAppConfiguration,
  Type.Object({
    host: Type.String(),
    port: Type.Number(),
    public: Type.String()
  })
])

export type ApplicationConfiguration = Static<typeof configurationSchema>

export const configurationValidator = getValidator(configurationSchema, dataValidator)

```

Problem is that I am struggling to use ``.env`` and  change default ``mongodb`` string into an object
 ``/config/default.json``:
```json
 "mongodb": {
    "host": "localhost:27017"
  },
```

 ``/config/custom-environment-variables.json``:
```json
 "mongodb": {
    "database": "MONGO_INITDB_DATABASE",
    "username": "MONGO_INITDB_ROOT_USERNAME",
    "password": "MONGO_INITDB_ROOT_PASSWORD"
 },
```

```ts
// src/mongodb.ts
  const mngDef = app.get('mongodb') as any
  console.log(mngDef.username) // gives: undefined and validation error
```

**Comment by tvld** [comment]
Ok, it's easier than I thought:

Just add to ``src/configuration.ts``:

```ts
// ...
export const configurationSchema = Type.Intersect([
  defaultAppConfiguration,
  Type.Object({
    host: Type.String(),
    port: Type.Number(),
    public: Type.String(),
    mongodb: Type.Object({ // will replace the original type, if any
      host: Type.String(),
      database: Type.String(), // no need for Type.Optional(...) as the config is combined from all config files together
      username: Type.String(),
      password: Type.String()
    })
  })
])
//...
```

Also when using ``.dotenv``, do not forget to add at the top of ``app.ts``:

```ts
import { feathers } from '@feathersjs/feathers'

// dotenv replaces all environmental variables from ~/.env in ~/config/custom-environment-variables.json
import * as dotenv from 'dotenv'
dotenv.config()

import configuration from '@feathersjs/configuration'
// ... 
```

**Comment by daffl** [comment]
I'm going to reopen this since now that the CLI app structure guide is up we should add this information in https://dove.feathersjs.com/guides/cli/configuration.html and https://dove.feathersjs.com/guides/cli/custom-environment-variables.html

**Comment by tvld** [comment]
You might wanna add that I made mistake above ( I think ..;) ):

It is good to realize that ``default.json`` and ``custom-environment-variables.json`` **do not get deep-merged**. For example:

/config/default.json:
```json
 "mongodb": {
    "host": "localhost:27017"
  },
```
/config/custom-environment-variables.json:
```json
 "mongodb": {
    "database": "MONGO_INITDB_DATABASE",
    "username": "MONGO_INITDB_ROOT_USERNAME",
    "password": "MONGO_INITDB_ROOT_PASSWORD"
 },
```
Will make you *loose* ``host`` from ``app.get('mongodb')``.

**Comment by daffl** [comment]
Docs added via https://github.com/feathersjs/feathers/pull/2979 - I'm wondering why your above example doesn't work. I just tested it with the `FEATHERS_SECRET` but I didn't see the loosing other values.

**Comment by tvld** [comment]
I just tested again, and now it works... hmmmmm.... 

Maybe it was related to ``defaultAppConfiguration``. If I try for example

_config/default.json_
```json

"paginate": {
    "default": 10,
    "max": 50
  },
```
_config/custom-environment-variables.json_
```ts
"paginate": {
    "default": 10
  }
```

Gives: 
```
/node_modules/config/lib/config.js:1115
        throw Error(msg);
              ^
Error: Illegal key type for substitution map at paginate: number
```
But before I thought it failed silently. Not with this error... well... Keep it closed ;-)

**Comment by daffl** [comment]
I think that error happens because `custom-environment-variables.json` needs an environment variable string name not a number value. We'll leave this closed but if you encounter another reproducible problem please feel free to open a new issue.

**Comment by tvld** [comment]
Clear. Actually, now I think of it, ``environment-variables.json`` might have been a better name..?. The ``custom`` somehow made it appear to me it can do more than just env's... Anyway, I'll keep an eye on it )))
