### ISSUE TITLE
dove: KnexService customization - Typescript error

### ISSUE THREAD

**Issue by rmtngh** [feathersjs/feathers#2918]
### Steps to reproduce
1- Generate an app using `npm create feathers@pre feathers-chat` with:
Typescript, KoaJS, HTTP & Real time, yarn, TypeBox, PostgreSQL

2- Add a custom implementation to `Users` service (doc: https://dove.feathersjs.com/guides/cli/service.class.html#service-customization)

Example:

```
import type { Params } from '@feathersjs/feathers'
import { KnexService } from '@feathersjs/knex'
import type { KnexAdapterParams, KnexAdapterOptions } from '@feathersjs/knex'

import type { Application } from '../../declarations'
import type { User, UserData, UserQuery } from './users.schema'

export interface UserParams extends KnexAdapterParams<UserQuery> {}

// By default calls the standard Knex adapter service methods but can be customized with your own functionality.
export class UserService<ServiceParams extends Params = UserParams> extends KnexService<
  User,
  UserData,
  ServiceParams
> {
  find(params: ServiceParams) {
    return super.find(params)
  }
  create(data: UserData, params: ServiceParams){
    return super.create(data, params)
  }
}

export const getOptions = (app: Application): KnexAdapterOptions => {
  return {
    paginate: app.get('paginate'),
    Model: app.get('postgresqlClient'),
    name: 'users'
  }
}

```

### Expected behavior

Custom `find` and `create` methods should override KnexService's methods with no errors.

### Actual behavior
Typescript error:

```
Property 'create' in type 'UserService<ServiceParams>' is not assignable to the same property in base type 'KnexService<{ password?: string | undefined; googleId?: string | undefined; auth0Id?: string | undefined; id: number; email: string; }, { password?: string | undefined; googleId?: string | undefined; auth0Id?: string | undefined; email: string; }, ServiceParams>'
```

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
<img width="460" alt="image" src="https://user-images.githubusercontent.com/20207426/206921782-556f7e8f-54ff-4328-b125-2d3f7ca32b45.png">

**NodeJS version**: v16.18.1

**Operating System**: MacOS 11.5

**Browser Version**: N/A

**React Native Version**: N/A

**Module Loader**:

**Comment by daffl** [comment]
You are correct, that did not work. The page at https://dove.feathersjs.com/guides/cli/service.class.html has been updated now with more complete examples that should work as expected. Note that the docs are for `.pre.34` which has a patch schema now.

**Comment by rmtngh** [comment]
Hi @daffl 
Thanks a lot for the fix and your reply,
I tried generating a `Message` service with the latest version and pasted the `create` methods from the [doc](https://dove.feathersjs.com/guides/cli/service.class.html ):

<img width="618" alt="image" src="https://user-images.githubusercontent.com/20207426/208453400-1c375466-c5f3-4f46-8523-0db4df310ede.png">

There is another ts error:
```
error TS2769: No overload matches this call.
  Overload 1 of 2, '(data: { text: string; }, params?: MessageParams | undefined): Promise<{ id: number; text: string; }>', gave the following error.
    Argument of type '{ text: string; } | { text: string; }[]' is not assignable to parameter of type '{ text: string; }'.
      Property 'text' is missing in type '{ text: string; }[]' but required in type '{ text: string; }'.
  Overload 2 of 2, '(data: { text: string; }[], params?: MessageParams | undefined): Promise<{ id: number; text: string; }[]>', gave the following error.
    Argument of type '{ text: string; } | { text: string; }[]' is not assignable to parameter of type '{ text: string; }[]'.
      Type '{ text: string; }' is missing the following properties from type '{ text: string; }[]': length, pop, push, concat, and 29 more.

22     return super.create(data, params)
```
Here are the dependencies:
<img width="442" alt="image" src="https://user-images.githubusercontent.com/20207426/208453996-0df6384c-237c-48d1-bf83-d325e9aeedd3.png">

**Comment by daffl** [comment]
Urgh, it turns out that those signatures weren't exported. This will be fixed via https://github.com/feathersjs/feathers/pull/2943 but for now it'll probably have to be `async create(data: any` in the implementation.
