### ISSUE TITLE
Firebase support

### ISSUE THREAD

**Issue by hieple7985** [feathersjs/feathers#292]
Any database adapter support firebase

**Comment by marshallswain** [comment]
Not yet. I actually started brainstorming on this one a couple days ago.

**Comment by ekryski** [comment]
Honestly, I actually see Feathers as more of a Firebase alternative. It currently provides all the same stuff as Firebase except for OAuth1 (which is coming) but Feathers is self-hosted. We're working on making deploying easier so I'm not really sure if this makes sense.

@marshallswain convinced me in a private discussion that there is value in helping people transition to Feathers but I think [this article](https://blog.feathersjs.com/using-feathersjs-as-an-open-source-alternative-to-firebase-b5d93c200cee) put together by @daffl does it justice (at least for now).

We have so many other things to take care of that this is pretty low priority I think, so I'm going to close. I think a better thing might be to eventually create a more comprehensive guide on how you can switch from Firebase to Feathers.

**Comment by pathikvejani** [comment]
Can anyone please help to solve the query?
Please refer this link:
[http://stackoverflow.com/questions/36866024/how-to-update-firebase-data]
How can I update the records using PHP?

How to update status = 0 in firebase database where status = 1.

What I have tried is:

    <?php
    require __DIR__.'/vendor/autoload.php';
    use Kreait\Firebase\Configuration;
    use Kreait\Firebase\Firebase;
    $firebase = new Firebase('LINK', $configuration);
    $users = $firebase->get('/users');
    for ($i=0; $i < count($users) ; $i++) {
    	$data = array('status' => '0');
    	$nodeUpdateContent = $firebase->update(['status' => '1'],$users[$i].'/presence/status');
    	print_r($nodeUpdateContent);
    }
    ?>

But when I see in the firebase database, it is not updating anything. Why so?

I am following this link: [Firebase-php][1]


Update data using this link: [Update-data][2]

I am getting in `$users`:

    <?php
    [1] => Array
    (
    	[presence] => Array
    	(
    		[loginTimestamp] => 1460117596561
    		[status] => 1
    	)
    
    )
    
    [2] => Array
    (
    	[presence] => Array
    	(
    		[loginTimestamp] => 1460117596561
    		[status] => 1
    	)
    )
    
    [3] => Array
    (
    	[presence] => Array
    	(
    		[loginTimestamp] => 1460117596561
    		[status] => 1
    	)
    )
    
    ?>

I am getting response for this: <br>**$nodeUpdateContent = $firebase->update(['status' => '1'],$users[$i].'/presence/status');**

    Array
    (
        [status] => 1
    )
    Array
    (
        [status] => 1
    )
    Array
    (
        [status] => 1
    )
    Array
    (
        [status] => 1
    )
    Array
    (
        [status] => 1
    )

`It is just printing the status which value is 1, but not updating it.`

    getting error here: Array to string conversion --> $nodeUpdateContent = $firebase->update(['status' => '1'],$users[$i].'/presence/status');


  [1]: https://github.com/kreait/firebase-php/tree/c0adb0ced970b2a8a2968a7bf6f803786a2f7ca2
  [2]: https://github.com/kreait/firebase-php/blob/master/doc/firebase.md

**Comment by manwithsteelnerves** [comment]
Is this still the case @ekryski ?
