### ISSUE TITLE
converter is not a function | 5.0.0-pre.33 | $populate 

### ISSUE THREAD

**Issue by palmtown** [feathersjs/feathers#2923]
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/dove/.github/contributing.md#report-a-bug) - if it is a general question or suggestion please start a [Discussion](https://github.com/feathersjs/feathers/discussions))

- [x] Tell us what broke. The more detailed the better.
- [x] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc. This makes it much easier for us to debug and issues that have a reproducable example will get higher priority.

When setting $populate as a filter as described at https://github.com/feathersjs/feathers/pull/2607 and https://dove.feathersjs.com/guides/migrating.html by setting {$populate: true}, feathers throws an error "converter is not a function."  I traced the error to file node_modules/@feathersjs/adapter-commons/lib/filter-query.js, line 69.  Only when I remove this from the filter, feathers works, however, prevents the usage of $populate.

### Expected behavior

$populate should be an allowed filter and populates the requested data.

### Actual behavior

Got error "converter is not a function"

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working): 5.0.0-pre.33

**NodeJS version**: 

**Operating System**:  Ubuntu

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by palmtown** [comment]
@daffl 

Great work on feathers!  Just wanted to ensure that the $populate filter will be supported in v5 and if this is a bug or simply a task list item pending?  If pending or a bug, do you have an estimated time when it might be completed? This will help me make decisions in the interim.  

Again, great work and thank you for your time..

**Comment by daffl** [comment]
Hm, I'll need to have another look at this. The goal going forward is definitely to replace all of those settings with proper query schemas because it's basically just an awkward way of doing query validation but allowing those properties should still work.

**Comment by palmtown** [comment]
Hello @daffl 

First, thanks for your response, much appreciated.  Secondly, it surely helps to understand the direction and how to better prepare.  Look forward to your update and love the work you're doing!

**Comment by daffl** [comment]
This should be fixed in the latest prerelease now. As noted before, the recommended way going forward is to use a query schema to validate against.
