### ISSUE TITLE
Installing Feathes client gives:  Socket.io client version 3 or later with Feathers v4 issue

### ISSUE THREAD

**Issue by tvld** [feathersjs/feathers#2926]
Trying to install Feathers on the client:

```sh
@feathersjs/feathers @feathersjs/authentication-client feathers-hooks-common @feathersjs/socketio-client  socket.io-client
```
Gives in the browser console when I start my app:

```
Error: You are trying to use the Socket.io client version 3 or later with Feathers v4 which only supports Socket.io version 2.
 Please use socket.io-client version 2 instead.
```
 I also reported here https://github.com/marshallswain/feathers-pinia/issues/95  but I suppose this is _feathers_ v4 - v5 attention point?

**Comment by tvld** [comment]
Ok, I tried this:

```sh
npm rm socket.io-client
npm install socket.io-client@2
```
But now I am getting:

```log
websocket.js:124 WebSocket connection to 'ws://localhost:3030/socket.io/?EIO=3&transport=websocket' failed: Invalid frame header
WS.doOpen @ websocket.js:124
Transport.open @ transport.js:84
Socket.open @ socket.js:250
Socket @ socket.js:122
Socket @ socket.js:28
Manager.open.Manager.connect @ manager.js:226
(anonymous) @ manager.js:544
```

**Comment by tvld** [comment]
Seems going full for pre is the best?
```
npm install @feathersjs/feathers@pre  @feathersjs/authentication-client@pre  @feathersjs/socketio-client@pre  socket.io-client
```
This works. Just make sure you use `` import { feathers } from '@feathersjs/feathers' `` with the ``{ }``

Fine to close issue as for me; maybe just a bit extra info in doc about socket v3 x v2 or mention the "pre" addition in the client install for now ?

**Comment by daffl** [comment]
Thanks for reporting that. I updated all the installation commands in the docs to include the `@pre` flag.
