### ISSUE TITLE
Scheduled Tasks

### ISSUE THREAD

**Issue by khwerhahn** [feathersjs/feathers#293]
It would be very nice if feathers would support running recurring (scheduled) tasks just like the guys in [nodal](http://www.nodaljs.com/static/docs/index.html#SchedulerEntry) introduced.

**Comment by daffl** [comment]
It could be a plugin. Is there anything Feathers specific though that can't be done with existing tools like [node-schedule](https://www.npmjs.com/package/node-schedule)?

**Comment by ekryski** [comment]
Yes I agree with @daffl. This could easily be supported as a plugin or using a third-party module (even cron) to run a work that connects to a Feathers API as a client.

I personally, think it is a mistake that Nodal is baking it into the framework. Not everyone needs that functionality and in reality you would probably have any background jobs or worker tasks running on a different machine so they don't compete for resources with your app server.

**Comment by daffl** [comment]
Thank you again for the suggestion! I'm going to close it though since I don't think it will become a core team focus. Of course we will do anything we can to help if someone decides to take it on as a Feathers plugin.
