### ISSUE TITLE
Updating from feather 33 pre-release to 34 gives json schema errors for type 

### ISSUE THREAD

**Issue by prajwal497** [feathersjs/feathers#2933]
### Steps to reproduce

Can not create query syntax schema for property 'modes'. Only types string, number, integer, boolean, null are allowed.

    modes: { type: 'array', items: { type: 'string' } },

### Expected behavior
**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by prajwal497** [comment]
@daffl Hello can you please assist me urgently on this?

**Comment by daffl** [comment]
The query syntax does not work reliably with arrays. You can add your own properties to the query syntax as a union or intersect type (e.g. see https://dove.feathersjs.com/api/schema/typebox.html#querysyntax) or extend the querySyntax JSON schema with the property you want to allow.

**Comment by prajwal497** [comment]
But i am using JSON schema and i need nested schema structure (array and objects) in main data model schema
Union type is supported in TypeBox, right?

**Comment by daffl** [comment]
I'll revert the handling of this in https://github.com/feathersjs/feathers/pull/2941 - the main reason why it threw an error was when using `$ref` which definitely does not work. However, `any` and things like that should be avoided as well.
