### ISSUE TITLE
Feathers should appear on 'Web application frameworks' showcase

### ISSUE THREAD

**Issue by mrpatiwi** [feathersjs/feathers#294]
I think it would be great for this framework to appear on:
https://github.com/showcases/web-application-frameworks

**Comment by ekryski** [comment]
Thanks for suggesting! I'm obviously biased but I agree. I had seen that as well. Does anyone @github know how we can make this happen?

**Comment by daffl** [comment]
We tried to get in touch with Github twice but haven't heard anything back so far. Although I'd really like to see this happen I don't think there is anything actionable we can do about it so I hope it's ok if I close this issue.
