### ISSUE TITLE
About using JWT tokens

### ISSUE THREAD

**Issue by anhldbk** [feathersjs/feathers#296]
In [User Management](http://docs.feathersjs.com/getting-started/user-management.html), the document said that: `This token needs to be set in the Authorization header for any subsequent requests that require authentication.`

But when I look at a certain HTTP request header, I see a different thing:

![screenshot from 2016-04-11 23-03-04](https://cloud.githubusercontent.com/assets/3270746/14433704/9dce74d0-0039-11e6-9f4a-fbfbb1112d95.png)

Any explanation?

**Comment by marshallswain** [comment]
Could you please provide more detail about what you see and where?

**Comment by ekryski** [comment]
@anhldbk When using the Feathers client the JWT is automatically parsed from the cookie and added to the header for you. Take a look at http://docs.feathersjs.com/authentication/readme.html#how-does-it-work to learn more about how auth works. Don't worry you are doing things correctly 😄
