### ISSUE TITLE
Additional AJV-formats crash app

### ISSUE THREAD

**Issue by b-steel** [feathersjs/feathers#2960]
Following the [Documentation for Additional Types](https://github.com/feathersjs/feathers/blob/d93fe4e24a161e18bf59023ce125daeeadb4dff2/docs/api/schema/typebox.md?plain=1#L276) and adding any of the 'additional' types (such as `iso-date-time`) to `validators.ts`, typescript complains that `iso-date-time` is not a valid option. Furthermore, using those types in a schema causes the app to crash.

### Steps to reproduce
`npx @feathersjs/cli@pre generate app` accept all defaults
Edit `validators.ts` by adding `'iso-date-time'` to the list of formats (have to add `//@ts-ignore` for `ts-node` to not complain)
Edit `users.schema.ts` to add an attribute `createdAt: Type.String({ format: 'iso-date-time' })`
Run `yarn dev`
App Crashes

[Repro](https://github.com/b-steel/feathers-ajv-repro)

Looking at `@feathersjs/schema` it specifies `ajv-format@2.1.1`, which looking at that [version](https://github.com/ajv-validator/ajv-formats/blob/c1cb46cad79f984020a9a0ef569e9c091ce24400/src/formats.ts), `iso-date-time` is not included in that version.  It is however included in `ajv-formats@3.0.0-rc.0` which their (ajv-formats) readme references.  

So as far as I can tell, the feathers documentation references some options for the release candidate `ajv-formats` package but that is not the package references in `@feathersjs/schema`'s `package.json`.  

If I'm missing some step that I should have done to make this work then I apologize 

### Expected behavior

Should be able to enable that additional options in `validators.ts` that are shown in the documentation

### Actual behavior

The app crashes with the message 
`unknown format "iso-date-time" ignored in schema at path "#/properties/modules/items/properties/createdAt"`

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
```
"dependencies": {
    "@feathersjs/adapter-commons": "^5.0.0-pre.34",
    "@feathersjs/authentication": "^5.0.0-pre.34",
    "@feathersjs/authentication-client": "^5.0.0-pre.34",
    "@feathersjs/authentication-local": "^5.0.0-pre.34",
    "@feathersjs/authentication-oauth": "^5.0.0-pre.34",
    "@feathersjs/configuration": "^5.0.0-pre.34",
    "@feathersjs/errors": "^5.0.0-pre.34",
    "@feathersjs/feathers": "^5.0.0-pre.34",
    "@feathersjs/knex": "^5.0.0-pre.34",
    "@feathersjs/koa": "^5.0.0-pre.34",
    "@feathersjs/schema": "^5.0.0-pre.34",
    "@feathersjs/socketio": "^5.0.0-pre.34",
    "@feathersjs/transport-commons": "^5.0.0-pre.34",
    "@feathersjs/typebox": "^5.0.0-pre.34",
    "knex": "^2.3.0",
    "pg": "^8.8.0",
    "winston": "^3.8.2"
  },
```
**NodeJS version**:
16.15.1
**Operating System**:
OSX 12.6.1
**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by daffl** [comment]
It looks like these formats are only available in the ajv-formats pre-release and not in the officially published version which is used here. You can use this version by adding the prerelease to your project:

```
npm install ajv-formats@v3.0.0-rc.0 --save
```

And then changing

```ts
import { Ajv, addFormats } from '@feathersjs/schema'
```

To

```ts
import { Ajv } from '@feathersjs/schema'
import addFormats from 'ajv-formats'
```

**Comment by b-steel** [comment]
Thanks for the help

**Comment by victor-gabou** [comment]
UP (@daffl)

The ajv-formats package haven't been updated since more than 2 years, we still have to force ajv to 3.0.0-rc to prevent issues with iso-date-time

Shouldn't feathers update ajv package to prevent this issue on future users?
Is ajv still a thing and shouldn't be avoided?

Whats the news about it?

kind regards,

**Comment by daffl** [comment]
This is an issue with the ajv-formats package. https://github.com/ajv-validator/ajv-formats/issues/75 has the discussion on what would be necessary to get the latest version published.

**Comment by victor-gabou** [comment]
Thanks a lot for the related issue!
