### ISSUE TITLE
Mocha discourages arrow functions in tests

### ISSUE THREAD

**Issue by wkw** [feathersjs/feathers#297]
Just getting started with first FJS project. Was working on initial tests this morning and ran into this while trying to increase a test's timeout:

> Passing arrow functions to Mocha is discouraged. 
> Their lexical binding of the this value makes them unable to access the Mocha context, and statements like this.timeout(1000); will not work inside an arrow function.

[https://mochajs.org/#arrow-functions](https://mochajs.org/#arrow-functions)

Are there any arguments for sticking with Arrow functions for generated tests?

**Comment by daffl** [comment]
Not really, it is probably a good idea to change it back to normal functions as they suggest. If you have the time, a pull request changing the test files in https://github.com/feathersjs/generator-feathers/tree/master/generators would be awesome.

**Comment by wkw** [comment]
OK, I'll take a look through the genies and try to get a suitable PR put together. 
Be good to have a little involvement with the project.

**Comment by wkw** [comment]
@daffl any advice on how I tell Yeoman to use my modified generators for testing the changes? I've only dealt with Yo as a user and not even that often.

**Comment by daffl** [comment]
In the generator repository run `npm link`. Then any calls to `yo feathers:*` will use that linked repository. For those changes you can also just run `npm test` to see if they are still all passing.

**Comment by wkw** [comment]
One thing that stumped me after I first updated the generated tests was that none of the non-transform tests were succeeding, all for exit codes not being zero. I eventually added a console.log to show the tmp dir path so I could go in and run the tests directly on the generated app. It was jshint complaining about semicolons. Seems like there should be a way to pipe those jshint failures to the output so it's clearer why the test failed. I'm not sure how that would be accomplished, but would gladly take pointers and work up another PR.

**Comment by daffl** [comment]
Thanks a lot for the PR! I noticed, too that there wasn't a lot of error reporting when the app test command fails so I added https://github.com/feathersjs/generator-feathers/commit/f006e4dd4d6ca63e551d0a740d1a864c71c1b60f to the tests. Now we should get an error with the full output of the test run.

I'm going to close this issue and will make a new release of the generator shortly.

**Comment by wkw** [comment]
@daffl I saw your commit earlier for the better error reporting and of course had to try it out. Perfect!
