### ISSUE TITLE
Allow function array in resolvers? (feature idea)

### ISSUE THREAD

**Issue by tvld** [feathersjs/feathers#2976]
Would it be an idea to allow resolvers properties not only handle functions, but _array_ of functions as well? Just like we have in hooks already? Would make it a bit more familiar and easier.
 
```ts
export const userDataResolver = resolve<User, HookContext>({
  properties: {
    lastName: defaultVal('Jonny'),
    firstName: trimVal(),
    displayName: [ defaultVal('John Doe'), trimVal() ] // => *not* working for now
  }
})

// ** Helper to set a default value
//    Example: readTimeSeconds: defaultVal(60), or tags: defaultVal([]),
//
function defaultVal<ValueType>(defaultValue: ValueType) {
  return async <ValueType, DataType>(value: ValueType, data: DataType, context: HookContext) => {
    return context.method === 'create' && value === undefined ? defaultValue : value
  }
}
// Remove leading and trailing spaces
//   Example: lastName: trimVal(),
//
function trimVal() {
  return async <ValueType, DataType>(value: ValueType, data: DataType, context: HookContext) => {
    return value !== undefined && value !== null ? value.toString().trim() : value
  }
}
```

Also, we could introduce the package ``feathers-resolvers-common`` , which could include functions like setting default value or trim a string as I use here...

**Comment by daffl** [comment]
I can definitely see something like a `feathers-resolvers-common` happen very soon where this would totally fit. I'd also like a schema based resolver that takes a schema and resolves data based on e.g. the format (`obejctId` etc.) and default values set in that schema.

It already is possible to chain multiple resolvers but it's definitely more verbose:

```ts
export const userDataDefaultsResolver = resolve<User, HookContext>({
  lastName: defaultVal('Jonny'),
  displayName: defaultVal('John Doe')
})

export const userDataResolver = resolve<User, HookContext>({
  firstName: trimVal(),
  displayName: trimVal()
})

schemaHooks.resolveData(userDataDefaultsResolver, userDataResolver)
```

**Comment by tvld** [comment]
Great... I will close it for now, as I suppose the ``feathers-resolvers-common`` idea is existing all over already;-)
