### ISSUE TITLE
jsonwebtoken dependency update in feathers v4

### ISSUE THREAD

**Issue by SevenWaysDP** [feathersjs/feathers#2978]
Hello dear Feathers team,
They updated it in https://github.com/feathersjs/feathers/pull/2966. Thanks for that.

But we need it in Feathers v4, would it be possible to release it?

Thank you and Happy New Year!

**Comment by hgenr** [comment]
Would be great, we are also on v4.

Thanks for featherjs!

**Comment by shsangha** [comment]
Hey Feathers team, was wondering if we could please get this patch into version 4?

**Comment by rraina** [comment]
@marshallswain @daffl feels like a critical fix for v4 users (especially since v5 isn't GA yet). Is this something folks would be open to looking into?

**Comment by daffl** [comment]
The update has been published now in v4.5.16. Note that new 4.x releases will from now on be available under the `crow` npm dist-tag.

**Comment by hgenr** [comment]
Great, thank you!
