### ISSUE TITLE
chat.html is no where to be found in the docs

### ISSUE THREAD

**Issue by ameesters** [feathersjs/feathers#298]
I was following the documentations on http://docs.feathersjs.com/getting-started/user-management.html
and there is talk about a `chat.html`, but it is no where to be found?

Could somebody please add it?

**Comment by marshallswain** [comment]
The chat page is added in each individual framework guide.  That might need to be made more clear if it's not already mentioned somewhere.

**Comment by daffl** [comment]
Very good point. I added a clarification and a link to the framework guides in that section.
