### ISSUE TITLE
.returning() is not supported by mysql and will not have any effect.

### ISSUE THREAD

**Issue by 8BallBomBom** [feathersjs/feathers#2989]
Randomly came across this warning.
Seems [the](https://github.com/feathersjs-ecosystem/feathers-knex/issues/209) issue that was reported and fixed before Knex was moved over is occurring again.

**Comment by daffl** [comment]
Probably reintroduced via https://github.com/feathersjs/feathers/pull/2934 but for a different reason. Might have to be reverted again - it was a fix for allowing database functions that generated ids (like UUIDs) but I think the recommendation should now just be to do it in a resolver.
