### ISSUE TITLE
Custom errors thrown in query resolvers are swallowed and result in generic BadRequest error instead

### ISSUE THREAD

**Issue by tobiasheldring** [feathersjs/feathers#2991]
Hello! Just upgraded from v4 to v5, love it great job 👏 One issue found below that did not behave as I expected

### Steps to reproduce

Create a query resolver that could throw custom errors depending on the value or existance of a query parameter.
Example below:

```typescript
// users.schema.ts
const userQuerySchema = querySyntax(
  Type.Object({
    some_param: Type.String(),
  })
);
export type UserQuery = Static<typeof userQuerySchema>;
export const userQueryValidator = getValidator(
  userQuerySchema,
  queryValidator
);
export const userQueryResolver = resolve<
  UserQuery,
  HookContext<UsersService>
>({
  some_param: async (value, query, context) => {
    if (!value) {
        throw new BadRequest("Query parameter some_param is required")
    }
    else if (value == "42") {
        throw new Forbidden("You do not have access to this")
    }
 
    return value;
  },
});
```
```typescript
// users.ts
...
before: {
    all: [
      schemaHooks.validateQuery(userQueryValidator),
      schemaHooks.resolveQuery(userQueryResolver),
    ],
...
```

### Expected behavior

Service returns whatever custom errors are thrown in resolvers, in this case  `BadRequest: Query parameter some_param is required` or `Forbidden: You do not have access to this` for those specific cases

### Actual behavior

Service always returns `BadRequest: Error resolving data`

### System configuration

Feathers `v5.0.0-pre.34`

**Comment by daffl** [comment]
Since all resolvers run in parallel it will return all errors based on their key in `error.data`. The error data and JSON response will look similar to this:

```json
{
  "name": "BadRequest",
  "message": "Error resolving data",
  "data": {
    "some_params": {
      "name": "BadRequest",
      "message": "Query parameter some_param is required"
    }
  }
}
```

There was a mistake in the error logger fixed in https://github.com/feathersjs/feathers/pull/2977 but in earlier apps you want to do the same thing and log

```ts
 if (error.data) {
  logger.error('Data: %O', error.data)
}
```

To get a list of all errors (this will also show validation errors).

**Comment by tobiasheldring** [comment]
Ah right, makes sense. Have confirmed that it works as you describe, thanks 🙏

**Comment by BenPortner** [comment]
For those who were lead here by google: `error.toJSON()` will give you a consistent error experience, returning `error.data.code` for custom errors and `error.code` for 'normal' errors.
