### ISSUE TITLE
Refusing to install feathers as a dependency of itself

### ISSUE THREAD

**Issue by hedikasmanto** [feathersjs/feathers#300]
Hello, I have installed feathers-cli, and run "feathers generate". And an error occurs like below information.

OS : OSX 10.11
Node : 5.10.0
npm : 3.8.5
 
npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/forte/.nvm/versions/node/v5.10.0/bin/node" "/Users/forte/.nvm/versions/node/v5.10.0/bin/npm" "install" "feathers@^2.0.0" "feathers-hooks@^1.5.0" "feathers-errors@^2.0.1" "feathers-configuration@^0.2.1" "serve-favicon" "compression" "winston" "body-parser" "feathers-rest@^1.0.0" "feathers-socketio@^1.0.0" "cors" "feathers-authentication@^0.7.0" "passport" "nedb" "feathers-nedb@^2.0.0" "--save"
npm ERR! node v5.10.0
npm ERR! npm  v3.8.5
npm ERR! code ENOSELF

npm ERR! Refusing to install feathers as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

And this is result of generated package.json (Missing a lot of feathers module)

{
  "name": "feathers",
  "description": "",
  "version": "0.0.0",
  "homepage": "",
  "main": "src/",
  "keywords": [
    "feathers"
  ],
  "license": "MIT",
  "repository": {},
  "author": {},
  "contributors": [],
  "bugs": {},
  "engines": {
    "node": ">= 0.12.0"
  },
  "scripts": {
    "test": "npm run jshint && npm run mocha",
    "jshint": "jshint src/. test/. --config",
    "start": "node src/",
    "mocha": "mocha test/ --recursive"
  },
  "devDependencies": {
    "jshint": "^2.9.1",
    "mocha": "^2.4.5",
    "request": "^2.71.0"
  },
  "dependencies": {
    "feathers-nedb": "^2.2.3"
  }
}

**Comment by ekryski** [comment]
Is your project called "feathers", if so you need to use a different name.

**Comment by ekryski** [comment]
Try running `feathers generate app` instead.

**Comment by daffl** [comment]
I am going to add some project name sanitization to the generator which will also include an error thrown when you name your project `feathers` (and probably any other of the modules that will be installed).

**Comment by hedikasmanto** [comment]
I have tried to create another folder, and error still occurs.
Note : I use "fish console"

~/W/feathers-nedb feathers generate app                              14:59:14

? Project name feathers-nedb
? Description 
? What type of API are you making? REST, Realtime via Socket.io
? CORS configuration Enabled for all domains
? What database do you primarily want to use? NeDB
? What authentication providers would you like to support? local
   create package.json
   create src/services/authentication/index.js
   create src/services/index.js
   create LICENSE
   create public/favicon.ico
   create public/index.html
   create src/hooks/index.js
   create src/index.js
   create src/middleware/logger.js
   create src/middleware/not-found-handler.js
   create test/app.test.js
   create .editorconfig
   create .jshintrc
   create .npmignore
   create .gitignore
   create README.md
   create src/app.js
   create src/middleware/index.js
   create config/default.json
   create config/production.json
   create src/services/user/index.js
   create src/services/user/hooks/index.js
   create test/services/user/index.test.js
npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/forte/.nvm/versions/node/v5.10.0/bin/node" "/Users/forte/.nvm/versions/node/v5.10.0/bin/npm" "install" "feathers@^2.0.0" "feathers-hooks@^1.5.0" "feathers-errors@^2.0.1" "feathers-configuration@^0.2.1" "serve-favicon" "compression" "winston" "body-parser" "feathers-rest@^1.0.0" "feathers-socketio@^1.0.0" "cors" "feathers-authentication@^0.7.0" "passport" "nedb" "feathers-nedb@^2.0.0" "--save"
npm ERR! node v5.10.0
npm ERR! npm  v3.8.5
npm ERR! code ENOSELF

npm ERR! Refusing to install feathers-nedb as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/forte/Workspace/feathers-nedb/npm-debug.log
fetchMetadata → network   ▄ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
^C~

**Comment by daffl** [comment]
`feathers-nedb` is also a dependency that is being installed. If you name it something like `feathers-test` or `my-app` it will work.

**Comment by ekryski** [comment]
I'm going to close. @daffl's suggestion will work. This is not a problem with Feathers. In node projects you can't name your project the same thing as one of it's dependencies.

As part of the CLI we might want to throw a better warning if someone tries to use the same name.
