### ISSUE TITLE
feathers should log uncaught errors when calling service methods

### ISSUE THREAD

**Issue by juodumas** [feathersjs/feathers#301]
Wouldn't it be nice of feathers to show uncaught errors in situations like below?
```
const feathers = require('feathers')
const memoryService = require('feathers-memory')

const app = feathers()

app.use('things', memoryService())
app.service('things').create({id: 1})
app.service('things').create({id: 1})

app.listen(3030)
```

The second `app.service('things').create({id: 1})` throws a `Conflict: A record with id: 1 already exists` error, but feathers is silent about it without a `.catch()`.

**Comment by ahdinosaur** [comment]
hey @juodumas, is [`loud-rejection`](https://www.npmjs.com/package/loud-rejection) what you're looking for?

**Comment by ekryski** [comment]
👍  @ahdinosaur. That is great! Maybe we should actually roll that into the generator actually.

**Comment by juodumas** [comment]
Thanks for the pointer, @ahdinosaur.

Looks like only  `process.on('unhandledRejection', ...)` is [needed](https://nodejs.org/api/process.html#process_event_unhandledrejection).

Most examples in feathers-docs don't provide the rejection callback, so I was hoping for something more fundamental, but maybe it's impossible without becoming too opinionated.

**Comment by ekryski** [comment]
@juodumas ya that's what I've generally just been using. I think there is value in adding that in the main `index.js` file that gets spit out by the generator though.

**Comment by ekryski** [comment]
I've added [an issue](https://github.com/feathersjs/generator-feathers/issues/120) to the generator to track this.

I also added a bit [in the error handling section](http://docs.feathersjs.com/middleware/error-handling.html#catching-global-server-side-errors) in the docs.

Going to close.
