### ISSUE TITLE
Knex: Unnecessary default ORDER BY clause added in find()

### ISSUE THREAD

**Issue by tobiasheldring** [feathersjs/feathers#3047]
### Steps to reproduce

1. Run app with knex debugging `DEBUG=knex:query npm run dev`
2. Call `find` with `paginate:false` for a KnexService with a potentially large database table. eg:
```ts
   const events = await this.app.service("event-log").find({
      paginate: false,
      query: {
        company_id: someCompanyId,
        created_at: { $gt: someDate },
      },
    });
```
3. Check resulting sql in the log, it contains an unexpected `ORDER BY` clause which could potentially make the sql query heavier to execute or affect query execution planning
`knex:query select "event_log".* from "event_log" where "company_id" = $1 and "created_at" > $2 order by "event_log"."id" asc`

### Expected behavior

User can control whether queries should be sorted in DB request or not for non-paginated queries. For paginated queries it makes sense to force a default sorting but surely it is not needed for non-paginated requests or am I missing something? At least there could be some way of opting out of DB sorting like if setting `$sort: null` or such.

### Actual behavior

`ORDER BY` clause is added to all select statements from `find` and there is no way to opt out of the sorting.
https://github.com/feathersjs/feathers/blob/dove/packages/knex/src/adapter.ts#L184

**Comment by daffl** [comment]
This has been added in https://github.com/feathersjs-ecosystem/feathers-knex/pull/142 because it turned out that Microsoft SQL server _does_ need this unnecessary clause for some reason. Maybe it is another one of those that needs to be done conditionally.

**Comment by tobiasheldring** [comment]
But in the [PR you link to](https://github.com/feathersjs-ecosystem/feathers-knex/pull/142) default sorting is only added if `$skip` is defined while in the [current implementation](https://github.com/feathersjs/feathers/blob/dove/packages/knex/src/adapter.ts#L184) it is **always** added, so there's a difference there. 

I'm no DB expert so I have full respect for complexity that I might be missing, but in my naive view it could make sense to set default sorting for paginated selects with limit/skip (since DBs might not have consistent default sorting themselves) but leave it completely up to the user for non paginated selects?

--
EDIT:
On second thought I'm leaning towards that I don't think the framework should ever have any opinion on this, and that it should be completely up the user to control the resulting sql queries, including knowing their own database and forming queries that can run successfully on their database, what do you think?

**Comment by daffl** [comment]
It should indeed not, the problem is just that a normal query won't work with MSSQL server without adding a sorting mechanism. I think the best solution is to make it conditional just for that database client.
