### ISSUE TITLE
Missing import in React Native gist on landing-page

### ISSUE THREAD

**Issue by mrpatiwi** [feathersjs/feathers#305]
`const io = require('socket.io-client/socket.io');` is missing and should be added before

```js
if (window.navigator && Object.keys(window.navigator).length == 0) {
  window = Object.assign(window, {navigator: {userAgent: 'ReactNative'}});
}
```

![image](https://cloud.githubusercontent.com/assets/7570744/14590550/cca04038-04d3-11e6-9893-2e7db1bd30c0.png)

**Comment by marshallswain** [comment]
Needs to be updated here: https://gist.github.com/ekryski/6c4d2b511ce4eea847dc

```js
import io from 'socket.io-client';
```

**Comment by ekryski** [comment]
Fixed. Thank you!
