### ISSUE TITLE
$in TypeScript error

### ISSUE THREAD

**Issue by tvld** [feathersjs/feathers#3064]
## In short

Type error on 'tags' in backend:  `` .find({ query: { tags: { $in:['sales', 'marketing'] } } })``. 
Same call from the front-end works ok and returns a filtered set of teams.

## Replicate

```ts
// teams.schema.ts

export const teamsSchema = Type.Object(
  {
    _id: Type.String({ objectid: true }),
   tags: Type.Optional(Type.Array(Type.String())),
  },
  { $id: 'Teams', additionalProperties: false }
)

export const teamsQueryProperties = Type.Omit(teamsSchema, [])
export const teamsQuerySchema = Type.Intersect(
  [
    querySyntax(teamsQueryProperties, {
      tags: {
        $in: Type.Array(Type.String())
      }
    })
  ],
  { additionalProperties: false }
)
```
Error:
```ts
  const response = await context.app
            .service('teams')
            .find({ query: { tags: { $in:['achievement'] } } }) // >> Error Type 'string[]' is not assignable to type 'string[][]'
```

``(property) tags: {
    $in: string[];
}
No overload matches this call.
  Overload 1 of 4, '(params?: (TeamsParams & { paginate?: PaginationOptions | undefined; }) | undefined): Promise<Paginated<{ userId?: string | undefined; isOwner?: boolean | undefined; ... 11 more ...; updatedAt: string; }>>', gave the following error.
    Type '{ $in: string[]; }' is not assignable to type 'string[] | Partial<{ $gt?: string[] | undefined; $gte?: string[] | undefined; $lt?: string[] | undefined; $lte?: string[] | undefined; $ne?: string[] | undefined; $in: string[][]; $nin: string[][]; } & { $in: string[]; }> | undefined'.
      Types of property '$in' are incompatible.
        Type 'string[]' is not assignable to type 'string[][] & string[]'.
          Type 'string[]' is not assignable to type 'string[][]'.
            Type 'string' is not assignable to type 'string[]'.
  Overload 2 of 4, '(params?: (TeamsParams & { paginate: false; }) | undefined): Promise<{ userId?: string | undefined; isOwner?: boolean | undefined; nrOfMembers?: number | undefined; description?: string | undefined; ... 9 more ...; updatedAt: string; }[]>', gave the following error.
    Type '{ $in: string[]; }' is not assignable to type 'string[] | Partial<{ $gt?: string[] | undefined; $gte?: string[] | undefined; $lt?: string[] | undefined; $lte?: string[] | undefined; $ne?: string[] | undefined; $in: string[][]; $nin: string[][]; } & { $in: string[]; }> | undefined'.
      Types of property '$in' are incompatible.
        Type 'string[]' is not assignable to type 'string[][] & string[]'.
  Overload 3 of 4, '(params?: TeamsParams | undefined): Promise<Paginated<{ userId?: string | undefined; isOwner?: boolean | undefined; nrOfMembers?: number | undefined; description?: string | undefined; ... 9 more ...; updatedAt: string; }> | { ...; }[]>', gave the following error.
    Type '{ $in: string[]; }' is not assignable to type 'string[] | Partial<{ $gt?: string[] | undefined; $gte?: string[] | undefined; $lt?: string[] | undefined; $lte?: string[] | undefined; $ne?: string[] | undefined; $in: string[][]; $nin: string[][]; } & { $in: string[]; }> | undefined'.
      Types of property '$in' are incompatible.
        Type 'string[]' is not assignable to type 'string[][] & string[]'.ts(2769)
``

Note: when trying to extending query for an 1:n relation, $in works:
```ts
export const teamsQueryResolver = resolve<TeamsQuery, HookContext>({
  // only return teams that this user is member of
  _id: async (value, team, context) =>
    context.params?.user ? { $in: context.params.user.teamIds } : value
})
```

In the same fashion, this also fails:
```ts
async ({ app, params, data, result }: HookContext) => {
   const response = await app
            .service('users')
            .find({ query: { teamIds: { $in: [result._id] } } })
```

Complaining it is not an array:
``error: [{"instancePath":"/teamIds","schemaPath":"#/properties/teamIds/anyOf/0/type","keyword":"type","params":{"type":"array"},"message":"must be array"},{"instancePath":"/teamIds/$in/0","schemaPath":"#/properties/teamIds/anyOf/1/properties/%24in/anyOf/0/items/type","keyword":"type","params":{"type":"array"},"message":"must be array"},{"instancePath":"/teamIds/$in/0","schemaPath":"#/properties/teamIds/anyOf/1/properties/%24in/anyOf/1/items/type","keyword":"type","params":{"type":"string"},"message":"must be string"},{"instancePath":"/teamIds/$in","schemaPath":"#/properties/teamIds/anyOf/1/properties/%24in/anyOf","keyword":"anyOf","params":{},"message":"must match a schema in anyOf"},{"instancePath":"/teamIds","schemaPath":"#/properties/teamIds/anyOf","keyword":"anyOf","params":{},"message":"must match a schema in anyOf"}]``

**Comment by tvld** [comment]
Closing ... as I believe now, needs to test more, that is was my own mistake after all...)

**Comment by tvld** [comment]
Yeah, this will do it:. But gosh how tricky this all is ...
```ts
import { ObjectId } from 'mongodb'

remove: [
      // also remove  the new _id from all the user's teamIds
      async ({ app, params, data, result, id }: HookContext) => {
        if (id) {
          const _id = new ObjectId(id as string)
          await app.service('users').patch(
            null,
            { $pull: { teamIds: _id } },
            { query: { teamIds: _id as any } }
          )
        }
      }
    ]
```
```ts
//  user.model.ts
export const userSchema = Type.Object(
  {
    _id: Type.String({ objectid: true }),
    teamIds: Type.Optional(Type.Array(Type.String({ objectid: true }))),
  
    // Mongodb operators
    $push: Type.Optional(Type.Object({})), // { $push: { teamIds: result._id } }
    $pull: Type.Optional(Type.Object({})) // { $pull: { teamIds: result._id } }
  },
  { $id: 'User', additionalProperties: false }
)

**Comment by daffl** [comment]
The most likely problem is that you defined `$in` in the `querySyntax` when it is already included by default. The idea of the `querySyntax` helper is to create the schemas for the [standard query syntax](https://feathersjs.com/api/databases/querying.html). Doing

```ts
    querySyntax(teamsQueryProperties)
```

And it should work as expected. I will update the docs to make that more clear.

**Comment by tvld** [comment]
Eh, no... seems not. I tested on 3 places in my tables and each time,  as soon as; 
```ts
querySyntax(teamsQueryProperties, {
      tags: {
        $in: Type.Array(Type.String())
      }
    })
```
with
```ts
querySyntax(teamsQueryProperties, {
     
    })
```
I can no longer filter on tags at all: ``BadRequest: validation failed``.  So for me, the ``tags{ $in..}`` is required. I tested a bit more and the issue still stands  (v38), so I reopen )).

**Comment by tvld** [comment]
One more test to show that $in really has some bugs hidden:

```ts
// user.schema.ts
export const userQueryResolver = resolve<UserQuery, HookContext>({
  teamIds: async (value, userData, { params, provider, method }) => {
    const { user, query } = params
    if (!user || !user._id || !value) return value
    return {
      $in: value.$in.filter((x: any) => user.teamsIds.includes(x)) //>>> error: Property '$in' does not exist on type 'string[] | Partial<{ $gt?: 
    }
  },
```

**Comment by tvld** [comment]
> I will update the docs to make that more clear

Maybe an idea to show documentation how to do simple population of 1:n relationship?  Where the parent contains an array of id's?:
```
 user: {
  _id, 
   teamIds: [ id, id, id] ,
   teams: {...} // how ?
 }
 
 team: {  
   _id,
  name
 }
```

**Comment by daffl** [comment]
I may have missed this before but the problem probably is that the query syntax is not built for arrays or nested objects. `$in` only works for individual fields, not arrays - it just happens to work in MongoDB but wouldn't with e.g. an SQL database adapter.

This is part of the reason why the query schema is an intersection so that you can add any non-standard queries you'd want to support. So defining it in the object under `// Add additional query properties here` is probably the easiest way and should work as expected:

```ts
export const teamsQueryProperties = Type.Omit(teamsSchema, [])
export const teamsQuerySchema = Type.Intersect(
  [
    querySyntax(teamsQueryProperties),
    // Add additional query properties here
    Type.Object({
      tags: {
        $in: Type.Array(Type.String())
      }
    }, { additionalProperties: false })
  ],
  { additionalProperties: false }
)
```

This will support querying `tags` with `$in` as an array. It is probably worth noting that `tags` should not be included in `teamsQueryProperties` (which is an empty object in the above example).

In my ideal world there wouldn't be a `querySyntax` helper at all and everybody just explicitly defines the queries they want to support but as always that also has its downsides.

**Comment by tvld** [comment]
Did you try that?  It gives ts error:
```ts
 >>> Type '{ $in: TArray<TString<string>>; }' is missing the following properties from type 'TSchema': params, static, [Kind]ts(2739)  
```

I am thinking, maybe we should extend the bug in that in Dove 1:n relationships are no longer working when using MongoDB? (I have seen several attempts in Discord but no working examples so far). For myself,  I get around the issue by issuing a couple of calls from the client and populating there, but it's hardly elegant...

**Comment by daffl** [comment]
Whoops sorry, it's

```ts
    Type.Object({
      tags: Type.Object({
        $in: Type.Array(Type.String())
      }, { additionalProperties: false })
    }, { additionalProperties: false })
```

If you can provide a complete example to reproduce how 1:n relationships are not working with latest we can totally have another look. I just tested the following in the latest feathers-chat and MongoDB and it worked like expected:

```ts
export const messageSchema = Type.Object(
  {
    id: Type.Number(),
    text: Type.String(),
    createdAt: Type.Number(),
    userId: Type.Number(),
    users: Type.Array(Type.Ref(userSchema))
  },
  { $id: 'Message', additionalProperties: false }
)
export type Message = Static<typeof messageSchema>
export const messageValidator = getValidator(messageSchema, dataValidator)
export const messageResolver = resolve<Message, HookContext>({
  users: virtual(async (message, context) => {
    const users = await context.app.service('users').find({
      paginate: false,
      query: {
        _id: { $in: [message.userId] }
      }
    })

    return users
  })
})
```

**Comment by tvld** [comment]
The solution might be in the combination of what you mention and  ``using Type.Ref()``, which I did not know was needed. People even [discourage](https://discord.com/channels/509848480760725514/930352418179391528/1078593419796033656) to use it: 

I am getting closer by exact copy of your code and the chat app, but now, this error. Which is strange as  ``users: Type.Array(Type.Ref(userSchema))`` uses ``userSchema`` and not ``User``...  Digging deeper ))


```ts
  if (schOrEnv === undefined) throw new MissingRefError(it.opts.uriResolver, baseId, $ref)
                                      ^
MissingRefError: can't resolve reference User from id #
 //...
/index.ts:500:5) {
  missingRef: 'User',
  missingSchema: 'User'
```
When I tried suggestion ``dataValidator.addSchema(userSchema)`` in https://github.com/feathersjs/feathers/issues/2993 it complains ``Error: schema with key or id "User" already exists``.
I will try to generate a complete new app with 5.0.0 and see if I can use Type.Ref() then without errors

**Comment by daffl** [comment]
Could you share your entire schema and/or a repository that illustrates your problem? The only place where references won't work at the moment is in a `query` schema. It should work everywhere else as long as it has the equivalent `export const messageValidator = getValidator(messageSchema, dataValidator)` line exists.

**Comment by tvld** [comment]
The line exists there, I suppose it would not complain it exists if it weren't,,.

I would be grateful, but our repo is on GitLab, can I share that with you? I suppose I need email to invite you ? Or maybe it is enough to just share the three schema's?

**Comment by tvld** [comment]
I [forked](https://github.com/tvld/feathers-chat-groups/tree/groups) the feathers-chat app, as it is close to what I like to achieve. I added groups, where users can assemble in groups and messages are then available in groups:

- users `` 1:n `` messages
- users ``n:m`` groups
- groups ``n:m`` messages
-
All works straightforward there, within 60 minutes while in my app it has been taking hours to move one little step.  I start to get why Dove is loved ;-))

So, I got a hunch that the issues are because of Mongodb + Object Id troubles, typescript / TypeBox gets just _very_ picky. 
So, I tried this... and it is finally working :))) :

```ts
  teams: virtual(async (userData, { params, app }) => {
    const { user } = params
    if (user && user.teamIds && user.teamIds.length > 0) {
      const teamIds = user.teamIds.map((id: any) => id.toString()) // required !!
      const response = await app
        .service('teams') 
        .find({ query: { _id: { $in: teamIds } } })
      if (response && response.data) return response.data // needed as well
    }
    return [] as Object[] // required !!
  }),
```

**Comment by tvld** [comment]
I will close the issue, although I did not get ``Type.Array(Type.Ref(userSchema))`` working in my Mongo app. Only in the feathers-chat fork it works...

**Comment by daffl** [comment]
Hm, yeah I did notice that TypeScript can be really finicky when working with e.g. the inferred types in resolvers and the error messages are... at least not easy to read. I'm hoping there will be ways to improve that going forward and at least add some better troubleshooting guidelines.

If you are able to update everything to the [latest ObjectId handling](https://feathersjs.com/api/databases/mongodb.html#objectids) (adding the keyword and using the `ObjectIdSchema` helper) I think that might also help. There was indeed a bit back-and-forth about this but I think we have a fairly decent solution now.

**Comment by tvld** [comment]
I just moved to ObjectId and indeed, seems painless (knock on wood) :))). I assume this is the intended way? :

```ts
// user.schema
   _id: ObjectIdSchema(), // used to be Type.String({ objectid: true }),
    teamIds: Type.Optional(Type.Array(ObjectIdSchema())),
    teams: Type.Optional(Type.Array(ObjectIdSchema())), // virtual, populated by resolver
    
// experiences.schema
   _id: ObjectIdSchema(),
    userId: Type.Optional(ObjectIdSchema()), // will be set by resolver OR admin
    user: Type.Optional(Type.Object({})), // virtual, populated by resolver // Error: Type.Optional(Type.Ref(userSchema)),
    teamIds: Type.Optional(Type.Array(ObjectIdSchema())), // will be set by resolver OR admin
    teams: Type.Optional(Type.Array(Type.Object({}))), // virtual, populated by resolver
    
// teams.schema
    _id: ObjectIdSchema(),
    userId: Type.Optional(ObjectIdSchema()),
    users: Type.Optional(Type.Array(Type.Object({}))),
    isOwner: Type.Optional(Type.Boolean()), // userId === user._id; virtual, resolved / not in db,
```

**Comment by tvld** [comment]
I tried [this](https://feathersjs.com/api/databases/mongodb.html#resolveobjectid), but the docs are not so clear on the ``resolveObjectId`` usage versus the ObjectIdSchema.  Maybe even a mistake there?

```ts
export const messageDataResolver = resolve<Message, HookContext>({
  properties: {
    userId: resolveObjectId // ==> is this really correct?
  }
})
```
