### ISSUE TITLE
Update framework benchmark lists

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers#3074]
There are a few framework benchmark repositories, the one I currently know about is https://github.com/the-benchmarker/web-frameworks that should be updated to v5

**Comment by vonagam** [comment]
The mentioned repository was updated on the day you opened this issue. Small note about that: 

In the benchmark you can see `koa` and `express` results. `koa` is two times faster than `express` with 54k requests per second vs 23k. Feathers has 22k, but it uses `@featheres/express`, as benchmark is pretty bare bone, I would expect if instead `@feathers/koa` was used (and it is recommended one on official website) than you would get twice as bigger number.
