### ISSUE TITLE
Dove 5.0 logger page not found keeps popping in console if logger is set to info or debug

### ISSUE THREAD

**Issue by haniyasin** [feathersjs/feathers#3077]
### Steps to reproduce
1- fresh app created  Feathers 5.0 using CLI
express transport, javascript, noschema, no auth, mysql 
first error received is :
Error: ENOENT: no such file or directory, open 'C:\Users\haniy\Downloads\monorepo\260223\erp-server2\migrations\20230226141123_ledgertransactions.js'
I ignored it since i depend on direct DB schema modeling and dont use migrations
2- created a service using CLI, SQL service with no authentication with same name of table inside MySQL
3- run the app using npm run dev
4- queried the service using the browser 

started to receive console log (continuously)
info: Page not found {"className":"not-found","code":404,"data":{"url":"/feathers-debugger?$sort[ts]=1&$limit=500&ts[$gt]=1677421006112&$version=1.3.0"},"name":"NotFound","type":"FeathersError"}

**changing logger level to warning will stop the messages** 
**changing the logger level to info or debug will reult  in these messages coming**

- [x] Tell us what broke. The more detailed the better.
- [x] If you can, please create a simple example that reproduces the issue and link to a gist, jrepo, etc. This makes it much easier
- [x]  for us to debug and issues that have a reproducible example will get higher priority.
[https://drive.google.com/file/d/1MhH5hIXVTSSirHflmZt9WGwyIsooZXTq/view?usp=sharing]

### Expected behavior
i dont know if something is broken because the message is not indeciating what is it that is not found

Tell us what should happen

### Actual behavior

Tell us what happens instead

### System configuration

Tell us about the applicable parts of your setup.

**NodeJS version**:v18.12.1

**Operating System**: Win 11

**Module Loader**:
"dependencies": {
    "@feathersjs/adapter-commons": "^5.0.0",
    "@feathersjs/authentication": "^5.0.0",
    "@feathersjs/authentication-client": "^5.0.0",
    "@feathersjs/configuration": "^5.0.0",
    "@feathersjs/errors": "^5.0.0",
    "@feathersjs/express": "^5.0.0",
    "@feathersjs/feathers": "^5.0.0",
    "@feathersjs/knex": "^5.0.0",
    "@feathersjs/schema": "^5.0.0",
    "@feathersjs/socketio": "^5.0.0",
    "@feathersjs/transport-commons": "^5.0.0",
    "compression": "^1.7.4",
    "knex": "^2.4.2",
    "mysql": "^2.18.1",
    "winston": "^3.8.2"
  },
  "devDependencies": {
    "@feathersjs/cli": "^5.0.0",
    "@feathersjs/rest-client": "^5.0.0",
    "axios": "^1.3.4",
    "cross-env": "^7.0.3",
    "mocha": "^10.2.0",
    "nodemon": "^2.0.20",
    "prettier": "^2.8.4"
  }

**Comment by daffl** [comment]
It looks like you still have the prototype of the feathers-debugger Chrome extension installed.

**Comment by haniyasin** [comment]
Yes , confirmed, sorry for that forgot about the extension

**Comment by daffl** [comment]
I'd definitely like to look into updating it for v5. It's doing some interesting things.
