### ISSUE TITLE
How to add Unique Key in Typebox Schema

### ISSUE THREAD

**Issue by itoonx** [feathersjs/feathers#3088]
I'm using Feathers 5 CLI to generate the project, So i'm confuse about new schema for mongodb and i have question
how to add unique key in string to phoneNumber ? I never see in the documents.

Thanks for reply

```
export const userSchema = Type.Object(
  {
    _id: ObjectIdSchema(),
    phoneNumber: Type.String(),
    password: Type.Optional(Type.String()),
    googleId: Type.Optional(Type.String()),
    facebookId: Type.Optional(Type.String())
  },
  { $id: 'User', additionalProperties: false }
)
```

**Comment by daffl** [comment]
This is shown in the [MongoDB indexes API documentation](https://feathersjs.com/api/databases/mongodb.html#indexes).
