### ISSUE TITLE
node version needs to be above 4

### ISSUE THREAD

**Issue by af-bergstrom** [feathersjs/feathers#309]
This is merely a suggestion, I was running node ~0.12 and I got this syntax error when running feathers generate complaining about syntax error "Use of const in strict mode". This was easily solved by upgrading node. 

I thought the generator might be able to catch this by checking the node version first and maybe prompt to upgrade, much like you do with feathers itself.

**Comment by daffl** [comment]
The generator already checks for the Node version and if it is older than 5.0 adds Babel automatically as long as you start the server with `npm start`.

**Comment by ekryski** [comment]
It might be just that we are shouldn't be using strict mode maybe. Thanks for the suggestion @af-bergstrom I think in a couple weeks time we'll start to really invest in the onboarding/CLI portion of things. We've had a lot of good feedback so there are some areas we can make it even easier to get ramped up with Feathers.

**Comment by daffl** [comment]
For Node 5 you need strict mode to use things like `const` and `class` in your files. What I'm saying is that the generated app should work with any Node version from 0.12 and up, there shouldn't be any errors.

**Comment by af-bergstrom** [comment]
The thing is, this was when I was trying to generate a new app.

**Comment by ekryski** [comment]
I was able to reproduce on node v0.12.9 using the feathers-cli. @af-bergstrom did you not get a warning from Yeoman? I got some pretty apparent ones...

```
npm install -g feathers-cli
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm

> spawn-sync@1.0.15 postinstall /Users/eric/.nvm/versions/node/v0.12.9/lib/node_modules/feathers-cli/node_modules/generator-feathers/node_modules/yeoman-generator/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall


> spawn-sync@1.0.15 postinstall /Users/eric/.nvm/versions/node/v0.12.9/lib/node_modules/feathers-cli/node_modules/generator-feathers-plugin/node_modules/yeoman-generator/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

/
> yo@1.7.0 postinstall /Users/eric/.nvm/versions/node/v0.12.9/lib/node_modules/feathers-cli/node_modules/yo
> yodoctor


Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✖ Node.js version

Your Node.js version is outdated.
Upgrade to the latest version: https://nodejs.org

✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✖ npm version

Your npm version is outdated.

Upgrade to the latest version by running:
npm install -g npm


Found potential issues on your machine :(
/Users/eric/.nvm/versions/node/v0.12.9/bin/feathers -> /Users/eric/.nvm/versions/node/v0.12.9/lib/node_modules/feathers-cli/bin/feathers.js
feathers-cli@1.2.6 /Users/eric/.nvm/versions/node/v0.12.9/lib/node_modules/feathers-cli
├── yeoman-environment@1.5.3 (escape-string-regexp@1.0.5, log-symbols@1.0.2, grouped-queue@0.3.2, text-table@0.2.0, untildify@2.1.0, chalk@1.1.3, debug@2.2.0, diff@2.2.2, globby@4.0.0, mem-fs@1.1.2, inquirer@0.11.4, lodash@3.10.1)
├── yo@1.7.0 (titleize@1.0.0, cli-list@0.1.6, figures@1.5.0, humanize-string@1.0.1, user-home@2.0.0, opn@3.0.3, string-length@1.0.1, chalk@1.1.3, root-check@1.0.0, sort-on@1.2.2, repeating@2.0.1, async@1.5.2, yeoman-character@1.1.0, yosay@1.1.1, configstore@1.4.0, package-json@2.3.2, cross-spawn-async@2.2.2, npm-keyword@4.2.0, update-notifier@0.6.3, fullname@2.1.0, meow@3.7.0, read-pkg-up@1.0.1, inquirer@0.11.4, insight@0.7.0, got@5.6.0, lodash@3.10.1, yeoman-doctor@2.1.0)
├── vorpal@1.10.10 (in-publish@2.0.0, strip-ansi@3.0.1, node-localstorage@0.6.0, minimist@1.2.0, chalk@1.1.3, wrap-ansi@2.0.0, log-update@1.0.2, inquirer@0.11.0, lodash@4.11.1, babel-polyfill@6.7.4)
├── generator-feathers-plugin@0.6.9 (lodash@3.10.1, yeoman-generator@0.21.1)
└── generator-feathers@0.8.5 (ast-traverse@0.1.1, i@0.3.4, string-length@1.0.1, repeating@2.0.1, chalk@1.1.3, string@3.3.1, cross-spawn-async@2.2.2, object.assign@4.0.3, recast@0.11.5, update-notifier@0.6.3, yeoman-generator@0.22.6)
eric : test  $ feathers generate app

/Users/eric/.nvm/versions/node/v0.12.9/lib/node_modules/feathers-cli/node_modules/generator-feathers/generators/app/index.js:386
      const devDependencies = [
      ^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.defineProperty.get [as feathers:app] (/Users/eric/.nvm/versions/node/v0.12.9/lib/node_modules/feathers-cli/node_modules/yeoman-environment/lib/store.js:40:23)
    at Store.get (/Users/eric/.nvm/versions/node/v0.12.9/lib/node_modules/feathers-cli/node_modules/yeoman-environment/lib/store.js:64:35)
    at Environment.get (/Users/eric/.nvm/versions/node/v0.12.9/lib/node_modules/feathers-cli/node_modules/yeoman-environment/lib/environment.js:259:21)
```

Regardless, having some checks and warnings is definitely valuable. I'll add something to the docs and we should just create a separate issue in the Feathers CLI repo.

**Comment by af-bergstrom** [comment]
This is the complete dump from my bash

`/Users/Rasmus/.node/lib/node_modules/feathers-cli/node_modules/generator-feathers/generators/app/index.js:386
      const devDependencies = [
      ^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.defineProperty.get [as feathers:app] (/Users/Rasmus/.node/lib/node_modules/feathers-cli/node_modules/yeoman-environment/lib/store.js:40:23)
    at Store.get (/Users/Rasmus/.node/lib/node_modules/feathers-cli/node_modules/yeoman-environment/lib/store.js:64:35)
    at Environment.get (/Users/Rasmus/.node/lib/node_modules/feathers-cli/node_modules/yeoman-environment/lib/environment.js:259:21)
~/Projects/Personal/feathers-chat ➔ node -v
v0.12.4`

**Comment by ekryski** [comment]
@af-bergstrom did you already have yeoman installed prior to running the CLI tool?

**Comment by daffl** [comment]
Ugh... the generator shouldn't use ES6. I guess I'm so used to it now that I didn't notice although I have no idea why the [tests passed on 0.12](https://travis-ci.org/feathersjs/generator-feathers/jobs/124646844).

**Comment by af-bergstrom** [comment]
Yes, I had yeoman installed

**Comment by af-bergstrom** [comment]
Let me just say I really like feathers and where it's going, you're doing a great job. My node was overdue for an update anyway :)

**Comment by ekryski** [comment]
@daffl damn... glad we nailed it down though. I've created two separate issues to track this. Thanks for reporting @af-bergstrom!

https://github.com/feathersjs/feathers-cli/issues/24
https://github.com/feathersjs/generator-feathers/issues/118
