### ISSUE TITLE
Subscribe and unsubscripe to rethinkDb change feed

### ISSUE THREAD

**Issue by syvuilliot** [feathersjs/feathers#310]
Hello all,

I'm quitte new to feathers but I like the approach and I really enjoyed reading the doc which is really high quality.
For what I have seen, the real time aspect of feathers is provided by emitting 'events' when there is a change on a collection (table). But if I want to only listen to changes made on a small scope of the collection (say the last 10 messages sent by Alice with 'unread' status) I have to do the filtering on the client side which is quitte inefficient (since it is a dynamic query, it can't be done server side actually).

Beacause that's the sort of thing, rethinkDb was made for, I would like to be able to leverage this feature via feathers. But the challenge is the ability to subscribe and unsubscribe from query.

What would be the best approach to do it ?

I thought about 2:
1) add 'watch' and 'unwatch' methods on services, but as far as I know, we cannot add 'custom' methods to services. Perhaps should we add them as 'official' optional (depending on the db) methods ?
2) create a service that allow to 'create' and 'remove' subscriptions to another service. Like a 'messages/subscriptions' service that allow to 'create' a query subscription on a 'messages' service

I know this would only work with rethinkDb since it is the only real time database able to handle this type of subscription to a query but I think, this is a right approach to real time and feathers would benefit from supporting it well in its architecture. And perhaps could it be used with others db with change feeds like couchDb and mongoDb.

Thanks all for your answers

Sylvain

**Comment by daffl** [comment]
I was actually thinking about how to create a [custom service](http://docs.feathersjs.com/real-time/events.html#custom-events) event to subscribe to a RethinkDB changefeed.

I am not sure if client side dynamic queries are that inefficient though. As a user of the app you normally get all change events pertaining to you so you can just update your client-side state automatically. This is basically what [feathers-rx](https://github.com/feathersjs/feathers-rx) does. You can issue a query like:

```
app.service('messages').find({ query: { user: 'Alice', unread: true, $limit: 10, $sort: { date: 1 } } })
  .subscribe(messages => console.log('Alices last messages', messages);
```

And you will get the last 10 unread messages for Alice. Whenever you get a `messages` service related event that changes that list of messages (e.g. a new message for Alice got created or a message got marked as read), a `console.log` with the updated list will show up.

**Comment by syvuilliot** [comment]
Hello David and thanks for your answer,

I'm aware of feathers-rx and I think it's a good way to consume data from feathers but it still requires that you load all the service data client side to do the filtering and sorting (I'm ok that without sorting you can only keep the relevant data).
But my use case is for when you want to work only on a subset of the data and can't / don't want to load all the data to compute the query client side. For example, in this example, if the messages history is quite long or if you have a lot of users.

In this case, I think it could be useful to have an API to subscribe/unsubscribe to/from a subset of the events of a service as can be provided by a realtime db like rethinkDb. In the example provided, the client would not receive events about messages from other users or about 'read' messages or even about older messages than the last 10.

For now, I'm working on option 2: a 'subscription' service that manage creation and removal of scoped events subscription about others data services (backed by rethinkDb).
But I think it's not the best approach and there should a better way for client to subscribe dynamically to events send by a service (even the standard ones). For example:
`
messagesService.on('created', listener)
messagesService.off('created', listener)
`
Server side, that would manage filtering of events for sending only the events the client is interested in.

What do you think about it ?

Sylvain

**Comment by daffl** [comment]
I'm wondering if we are talking about the same thing but I am missing something so let me know if I'm totally missing the point here 😄

With feathers-rx you do not have to load all the service data. It loads the data you request (e.g. the last 10 messages) and then listens to single message `created`, `updated` and `removed` events to keep that list up-to date. When it can't say for sure if an event that happened modified the current list it can re-run the query. Using [event filters](http://docs.feathersjs.com/real-time/filtering.html) we can limit the dispatching of events only to the relevant users.

What would be nice is to keep track of the data a user requested and only send updated/patched events for those data. I can see that not having that might become an issue in noisy high volume systems (although there may be many ways to optimize the custom event filters). I made an example for this before but I can't seem to find it at the moment. The hard part is figuring out when to clean up ids a user does not listen to anymore.

**Comment by syvuilliot** [comment]
I think we are on the same point :-)
You're right, depending on the complexity of the query you can sometimes update the result incrementally client side by listening to 'created', 'updated', 'removed' events and otherwise rerun the query each time on every event.
What we are talking about is a way to do it more efficiently by allowing a client to explicitly subscribing to the events it needs and no more. That's what you call `keep track of the data a user requested`.
But to do it well, you need to have an API for subscribing and for unsubscribing like on an event emitter with `addEventListener` and `removeEventListener` or in RxJS with `subscribe`and `unsubscribe`. On top of that you can have helpers/tooling to make it easier to manage these subscriptions like the RxJS library but at a low level it's a good thing to not have to "guess" if a client is interested anymore.

That's why I propose to define an API to allow a client subscribing to certains events and also unsubscribing from these events when it is not interested anymore.
It could be use for the "standard" events (created, updated, ...) and also for custom events.
That could be the base to implement what I talk at the beginning: a way to subscribe to events from a rethinkDb query change feeds and so having a very efficient way to only receive events for the data we are interested about even if the collection is quite large and the number of changes quite high as it can be the case in a real time collaborative application.

Does my explanation help ? And thank you a lot for taking time on this.

**Comment by marshallswain** [comment]
Another (maybe possible) option would be to use a custom attribute like `{$subscribe: true}` and `{$subscribe: false}` to grant some more granularity in per-query control of subscriptions.

**Comment by daffl** [comment]
This all makes sense and we should definitely pursue this further. Personally I'm not sure what exactly to do about it yet. @ekryski and I have been talking quite a bit about GraphQL which might play into this as well. @syvuilliot If you have a prototype of even a proposed API on how it would look I'd love to see it.

**Comment by syvuilliot** [comment]
@daffl I will enjoy helping as much as I can: I only have short experience with either RethinkDb and Feathers, but some expertise with the reactive approach due to my mainly frontend experience.

So what I've done so far is a "service on a service". Following our example, giving a "message" service mounted on `/messages` (which uses feathers-rethinkdb), I create a "messageSubscription" service mounted on `/messages/subscriptions` like that 
```javascript
  app.use('/messages/subscriptions', new WatchService({
    db: r,
    table: 'messages',
    service: '/messages',
  }))
  app.service('/messages/subscriptions').before({
    all: hooks.before.all, // authentication hooks
  })
```
Only `create` and `remove` methods are available.

On `create` we must provide a subscription object with the following properties: `id`, `type` ('item' or 'query') and `params`.
The `id` will be used as the event name for the client to listen to. It is defined by the client since we can receive the initial event before the response to `create`.
The `type` indicate if we are interested in watching for a single item (in this case, we provide the item id in `params`) or for a query (in that case, `params` contains the query).
```javascript
app.service('messages/subscriptions').on('change', msg => {
  msg.key // equals subscriptionId
  msg.value // response returned by either messages#find ou messages#get
})
app.service('/messages/subscriptions').create({
  id: 'recentMessages',
  type: 'query',
  params: {room: roomId, $limit: 10, $sort: {createdAt: -1}},
}) 
// ...
app.service('/messages/subscriptions').remove('recentMessages') 
```
I have a very early implementation available [here](https://github.com/KAESapps/feathers-rdb-watch) but basically what I do is: 
- create a change feed based on the query params
- run it and store a reference to the cursor associated to the couple clientId + subscriptionId
- call `find` or `get` on the messages service depending on the case and send the result to the client via an direct emit the socket (we can't use feathers custom events since we are not interested in broadcasting here)
- then, on each event from the change feed, rerun the call to the original messages service and send it to the client

On `remove` (and when the client socket disconnect), I close the rethinkDb cursor and release the reference to it.

I choose, not to send the events from the rethinkDb change feed directly for many reasons:
- it's easier for the client
- we are not coupled with the rethinkDb change feed format
- and more importantly, we reuse the hooks of the original service

So the strategy here is really to rerun the query each time it is necessary... no less, no more.

Perhaps could we benefit from having a more "integrated" API like a `watch` and `unwatch` methods on the same service, but the approach here is pragmatic and has the benefits of being clear about the fact that you are creating a side effect on the server when you're watching something... which is quite new when you come from a strict stateless REST approach.

The other thing that could be improved, is the way to send unicast messages to a client. I simply added a socketio middleware to expose the raw socketio object on the feathers params object. But I think, following the feathers approach, that should be abstracted a little bit.

Finally, considering the GraphQL API, I have no experience with it. For me it is an enhanced declarative query language that allow to express queries joining multiple collections/tables but is not concerned by the reactive approach... or am I wrong ?

**Comment by ekryski** [comment]
Related to #21 I think.

**Comment by rnenjoy** [comment]
Any new ideas to this?

**Comment by marshallswain** [comment]
@rnenjoy We're a pretty WYSIWYG org.  It's all in the issues.  Thanks for checking.

**Comment by daffl** [comment]
@rnenjoy The RethinkDB adapter listens to changefeeds and sends the proper service events. Our answer to client side changefeeds is [feathers-reactive](https://github.com/feathersjs/feathers-reactive), as mentioned above. An added bonus is that it works with every Feathers service, not just RethinkDB. With the RethinkDB adapter, that should get you end-to-end realtime. There also is a proposal for clients to only register to listen to a limited set of events in https://github.com/feathersjs/feathers/issues/421.

Personally I think we can close this issue because everything needed for end-to-end changefeeds with RethinkDB is now available. I did some brief research if it might be worthwile to keep track of what data clients requested on the server but it I don't think it is a path that Feathers is going take. It is easier and way more performant to stay stateless and send and discard events that may not be used on the client instead of adding all the complexity and performance hits that Meteor and Horizon (used to) have to deal with.

**Comment by daffl** [comment]
Here is a video how to use RethinkDB + feathers-reactive to create a real-time voting app: https://youtu.be/fMd72fycz7U?t=1h24m53s which might demonstrate a little better how it all looks like.

**Comment by rnenjoy** [comment]
Very nice video @daffl ! I didnt know Feathers had the power do this already. I havnt understood the docs at all it appears. I thought that i had to manually filter on the client all changes that happens, and not just subscribe like this.

But i have a question. Can i filter the query before subscribing? In the example you use order, but can i also filter on ownerUserId for example, to limit the result more?

**Comment by daffl** [comment]
feathers-reactive will filter everything that matches the query. The following will keep a real-time list of the 10 most recent orders:

```js
app.service('orders').find({ query: { ownerUserId: 1234, $limit: 10, $sort: { updatedAt: -1 } } })
  . subscribe(orders => console.log('Got orders', oders));
```

Keep in mind that you still have to [filter events](https://docs.feathersjs.com/real-time/filtering.html) on the server that the user is not allowed to see. Besides that, sending too many events that are just discarded (by yourself or feathers-reactive) normally isn't really that big of a deal.
