### ISSUE TITLE
Empty $and and $or parameters

### ISSUE THREAD

**Issue by luciamaj** [feathersjs/feathers#3111]
How can I define the $and and $or parameters in TypeBox? When I pass them as parameters, such as in this query string "/products?$and[0][has_variants]=true", and debug the query, the "$and" object appears to be empty. Thank you.

### System configuration
"@feathersjs/typebox": "^5.0.1"

**Comment by luciamaj** [comment]
Understood, I cannot use operators $and or $or with additional query properties, I solved my issue defining my custom properties in the main schema and deleting them in a before hook.

**Comment by daffl** [comment]
This is definitely still something that can be clarified or made easier. I'm just not entirely sure exactly how.
