### ISSUE TITLE
Configuring or modifying default REST handlers?

### ISSUE THREAD

**Issue by kokujin** [feathersjs/feathers#312]
This is a re-post of my question because I posted it in the wrong repositoty

Feathers can handle REST request out of the box. This is great. I read the docs on hooks, what I missed was the standard way of configuring handlers, not during the before or after lifecycles.
 
1. I can find the docs for Express compatible middle-ware.
2. I can find the docs for hooks and the life-cycles.

What I cant find are the docs to modify or customize the default Feathers REST handlers.

If I generate an app using the CLI, I ca fire request at the app using Postman for example, this is fine, but where are these REST handlers defined? What is the preferred Feathers way to modify them?

Thanks

**Comment by daffl** [comment]
Ah sorry, I think my reply in https://github.com/feathersjs/feathers-demos/issues/11 was a little off then. You can find the documentation how to customize the response format in http://docs.feathersjs.com/rest/readme.html#customizing-the-response-format.

**Comment by daffl** [comment]
Service specific formatters can be added as a custom middleware like this:

```js
app.use('/todos', todoService, function(req, res) {
  res.json(res.data);
});
```

**Comment by daffl** [comment]
I'm going to close this issue since I think I answered the question this time around 😉
