### ISSUE TITLE
Best practice for Express middle-ware and other things

### ISSUE THREAD

**Issue by kokujin** [feathersjs/feathers#313]
I am slightly confused, please bear with me.

- Services only or Express middle-ware and Services? What is preferred or when should I choose one method over the other? ( Taken from the docs)

-  What is the preferred  way to register services

Taken from a scaffolded app
`````
// Connect to the db, create and register a Feathers service.
app.use('/messages', service({
  Model: db,
  paginate: {
    default: 2,
    max: 4
  }
}));
`````
or, from the docs....
``````
// Register your message service
app.configure('/api/messages', memory());
``````

- According to the docs, Feathers uses Express compatible middle-ware. But the docs show examples using promises, something non Express standard. Why?
 
Thanks

**Comment by daffl** [comment]
Ah I can see how that is confusing, `app.configure('/api/messages', memory());` was definitely wrong in the documentation and has been fixed. It is always `app.use('/api/messages', memory());`. 

However, even with the [REST API provider](http://docs.feathersjs.com/rest/readme.html) configured, passing a service object to `app.use` will behave different than just passing middleware. Think of a service as its own router that sets up all the routes that you normally would (e.g. `GET /users, GET/users/:id`, `POST /users` etc) automatically and maps them to the [services method](http://docs.feathersjs.com/services/readme.html) (`find`, `get`, `create` etc.). So in the context of a HTTP REST API, a service is basically just a collection of middleware with its [own formatter](http://docs.feathersjs.com/rest/readme.html#customizing-the-response-format) and you can add your own middleware before or after.

Although Feathers is fully compatible with Express and its middleware services have a major advantage though: They are protocol independent and also work [via websockets](http://docs.feathersjs.com/real-time/readme.html) and possibly other protocols in the future. You can also use them on the client. In the [Philosophy section](http://docs.feathersjs.com/why/philosophy.html) we outlined the reasons why we think that is important and the [Feathers + Express & Socket.io](http://docs.feathersjs.com/why/vs/express-socketio.html) discusses a little more how both play together.

To answer the question which to use when: Use Services and hooks whenever possible. You can still use Express middleware for the parts of the app that are used via a HTTP REST API but unlike services, Express middleware does not work with websockets.

**Comment by kokujin** [comment]
That helped @daffl , Thanks. One last thing, for now.

-  Promises in middle-ware

 Feathers uses Express compatible middle-ware. But the docs show examples using promises, something non Express standard. Why? Express uses res.send, res.render or just next() in the case of middleware

**Comment by daffl** [comment]
You can use the legacy callback in services and hooks support a legacy `next` callback but Feathers always prefers promises. Promises are a part of Node now and make working with asynchronous code _much_ easier to avoid [callback hell](http://callbackhell.com/). They also will work with ES2016 `async` and `await` which will become part of Node in the future.

Lastly, everything you mentioned is very Express specific. While Feathers currently only works with Express on the server there are plans to also make it more decoupled and compatible with other server frameworks like Koa and Hapi (see https://github.com/feathersjs/feathers/issues/258).

**Comment by daffl** [comment]
Closing this one as well. Hope that answered all your questions.
