### ISSUE TITLE
docs: Ecosystem outdated

### ISSUE THREAD

**Issue by fratzinger** [feathersjs/feathers#3132]
The new ecosystem page is outdated: https://feathersjs.com/ecosystem. For example see the dove packages are not displayed: https://feathersjs.com/ecosystem/?core=true&old=true&sort=stars

The cloudflare worker does not update. The cron job is running but the data on the endpoint does not get updated. I don't know why, though.

**Comment by daffl** [comment]
This should be fixed now, thank you for putting up the pull request!
