### ISSUE TITLE
use test database and test ENV while testing

### ISSUE THREAD

**Issue by naifen** [feathersjs/feathers#315]
I'm wondering how to specify a test database and use test ENV for test.  
Also need more information on how to test middleware, http request or service CRUD methods. (couldn't find much of related info in docs)
In case I missed anything in the docs please point it out.
Thanks 😄

**Comment by daffl** [comment]
Everything you need to get environment specific settings should be discussed in the documentation for configuration: http://docs.feathersjs.com/configuration/readme.html.

There is not much documentation regarding testing in the documentation yet but the generator (`feathers generate`) sets up all the tests and placeholders automatically and has everything set up to get you started.

**Comment by daffl** [comment]
Hope that helps. We should be able to add a guide for testing in the next release but I'll close this issue.
