### ISSUE TITLE
Configuring a database for a particular service

### ISSUE THREAD

**Issue by kokujin** [feathersjs/feathers#316]
Is it possible to configure different databases for different services using the config files? Thanks

**Comment by ccummings** [comment]
It's pretty easy to do using the existing DB adapters.

For example, you could store your users in Postgres by using `feathers-sequelize` to create your `users` service. Then you can use `feathers-mongodb` to create a mongodb backed `messages` service.

The config for each DB would be stored in your config files.

With hooks you can even combine data from different services (different DBs) like in this example: http://docs.feathersjs.com/hooks/examples.html#fetching-related-items

**Comment by kokujin** [comment]
Great @ccummings! One thing though, I have not found the place in the docs where I can set an ORM/ DB Adapter for a service when configured. Any idea?

**Comment by ccummings** [comment]
There is a dedicated page for each ORM in the [feathers docs](http://docs.feathersjs.com/databases/readme.html). Here's [Sequelize](http://docs.feathersjs.com/databases/sequelize.html) and [mongodb](http://docs.feathersjs.com/databases/mongodb.html). You always do 3 things:

1) Create instance of ORM (using your config)
2) Create store/schema/container/whatever
3) Use feathers adapter to create a service for the store/schema/container/whatever

For configuration, you can use [`feathers-configuration`](https://github.com/feathersjs/feathers-configuration) which makes all of your configuration values available via `app.get`. Or you can use any number of other config utilities like [`nconf`](https://www.npmjs.com/package/nconf).

**For Example:**
Using the generator, you'll get a service that looks like [this](https://github.com/feathersjs/feathers-chat/blob/master/src/services/message/index.js), which is a bit more structured and uses `feathers-configuration` [here](https://github.com/feathersjs/feathers-chat/blob/master/src/services/message/index.js#L12) to retrieve [this](https://github.com/feathersjs/feathers-chat/blob/master/config/default.json#L4) value.

**Comment by kokujin** [comment]
Ahh, I get it now, the format that the config uses is not particularly specific, I can add my own attributes as I see fit. Thanks

**Comment by daffl** [comment]
Looks like this is all figured out, thanks @ccummings!
