### ISSUE TITLE
Broken Docs: Migration to v5 Service Types Code not rendering properly

### ISSUE THREAD

**Issue by Yahyaali1** [feathersjs/feathers#3162]
### Steps to reproduce

- Visit https://feathersjs.com/guides/migrating.html  
- No code is visible under header https://feathersjs.com/guides/migrating.html#service-types 

### Expected behavior

Tell us what should happen
Docs served at https://feathersjs.com/guides/migrating.html 
<img width="755" alt="Screenshot 2023-04-14 at 12 18 29 PM" src="https://user-images.githubusercontent.com/28826599/231972296-38aeea77-501e-4d4a-91c0-c393c1d07d61.png">

### Actual behavior
It works fine if I setup it locally
<img width="707" alt="Screenshot 2023-04-14 at 12 19 15 PM" src="https://user-images.githubusercontent.com/28826599/231972428-b354d4f1-c574-4e4f-b2ed-ac5d83bfee6d.png">

**Comment by daffl** [comment]
Did you happen to choose JavaScript as the code language? If so, that block will indeed show nothing.

**Comment by Yahyaali1** [comment]
Yes I did. It does makes sense but it isn't intuitive. It kind of looks odd.
