### ISSUE TITLE
API Docs

### ISSUE THREAD

**Issue by beevelop** [feathersjs/feathers#317]
Developing a Feathers application I found myself quite often combing through the [official Docs](http://docs.feathersjs.com/). As most parts (authentication, client, socket, rest,...) are in some way or another interconnected it would be great to have a purely technical one-stop destination with a clear definition of what methods are available and what options can be used (or just a suitable reference to the underlying technologies' documentations).

I personally think something pretty straight forward like the [Underscore Docs](http://underscorejs.org/) would be suitable and significantly improve the development workflow.

**Comment by daffl** [comment]
Good idea. A cheat-sheet, maybe as a guide, would be nice.

**Comment by ekryski** [comment]
@beevelop I assume you mean more than just this: http://docs.feathersjs.com/api/readme.html.

Although this is definitely valuable this is actually a pretty task because there are so many different repos. In this case I would sort of defer to just looking at the code, unless you have some specific examples. I know that auth docs could be improved quite a bit.

**Comment by kulakowka** [comment]
I have done a utility that builds a table of contents for the feathers docs. Here's how it looks:

> - **[Introduction](http://docs.feathersjs.com/)**
>   - [Feathers](http://docs.feathersjs.com/#feathers)
> - **[What is Feathers](http://docs.feathersjs.com/getting-started/introduction.html)**
>   - [Minimalist](http://docs.feathersjs.com/getting-started/introduction.html#minimalist)
>   - [Service oriented](http://docs.feathersjs.com/getting-started/introduction.html#service-oriented)
>   - [Modern Applications](http://docs.feathersjs.com/getting-started/introduction.html#modern-applications)
>   - [Real-time At The Core](http://docs.feathersjs.com/getting-started/introduction.html#real-time-at-the-core)
> - **[Quick Start](http://docs.feathersjs.com/getting-started/quick-start.html)**
>   - [What's next?](http://docs.feathersjs.com/getting-started/quick-start.html#whats-next)
> - **[Your First App](http://docs.feathersjs.com/getting-started/readme.html)**
>   - **[Getting Set Up](http://docs.feathersjs.com/getting-started/setting-up.html)**
>     - [Node Version Manager](http://docs.feathersjs.com/getting-started/setting-up.html#node-version-manager)
>     - [Babel](http://docs.feathersjs.com/getting-started/setting-up.html#babel)
>   - **[Scaffolding and Services](http://docs.feathersjs.com/getting-started/scaffolding.html)**
>     - [Generate The App](http://docs.feathersjs.com/getting-started/scaffolding.html#generate-the-app)
>     - [What Just Happened](http://docs.feathersjs.com/getting-started/scaffolding.html#what-just-happened)
>     - [Creating Our First Message](http://docs.feathersjs.com/getting-started/scaffolding.html#creating-our-first-message)
>     - [What's next?](http://docs.feathersjs.com/getting-started/scaffolding.html#whats-next)
>   - **[User Management](http://docs.feathersjs.com/getting-started/user-management.html)**
>     - [Creating and authenticating users](http://docs.feathersjs.com/getting-started/user-management.html#creating-and-authenticating-users)
>     - [Authorization](http://docs.feathersjs.com/getting-started/user-management.html#authorization)
>   - **[Manipulating data](http://docs.feathersjs.com/getting-started/formatting-and-hooks.html)**
>     - [Adding information with hooks](http://docs.feathersjs.com/getting-started/formatting-and-hooks.html#adding-information-with-hooks)
>     - [Message authorization](http://docs.feathersjs.com/getting-started/formatting-and-hooks.html#message-authorization)
>   - **[Building a Front-end](http://docs.feathersjs.com/getting-started/frontend.html)**
> - **[Why Feathers](http://docs.feathersjs.com/why/readme.html)**
>   - **[Philosophy](http://docs.feathersjs.com/why/philosophy.html)**
>     - [The services concept](http://docs.feathersjs.com/why/philosophy.html#the-services-concept)
>     - [Built on the Shoulders of Giants](http://docs.feathersjs.com/why/philosophy.html#built-on-the-shoulders-of-giants)
>   - **[Built with Feathers](http://docs.feathersjs.com/why/showcase.html)**
>     - [Applications](http://docs.feathersjs.com/why/showcase.html#applications)
>     - [Starter stacks, Examples and Tutorials](http://docs.feathersjs.com/why/showcase.html#starter-stacks-examples-and-tutorials)
>     - [Community Plug-ins](http://docs.feathersjs.com/why/showcase.html#community-plug-ins)
>   - **[Features](http://docs.feathersjs.com/why/features.html)**
>   - **[Feathers vs. X](http://docs.feathersjs.com/why/vs/readme.html)**
>     - [Feature Comparison](http://docs.feathersjs.com/why/vs/readme.html#feature-comparison)
> - **[Services](http://docs.feathersjs.com/services/readme.html)**
>   - [Services for Data Storage](http://docs.feathersjs.com/services/readme.html#services-for-data-storage)
>   - [Services for External APIs](http://docs.feathersjs.com/services/readme.html#services-for-external-apis)
>   - [Services that Real-time Proxy a Legacy Server](http://docs.feathersjs.com/services/readme.html#services-that-real-time-proxy-a-legacy-server)
>   - [A Basic Example](http://docs.feathersjs.com/services/readme.html#a-basic-example)
>   - [Retrieving services](http://docs.feathersjs.com/services/readme.html#retrieving-services)
>   - [Service methods](http://docs.feathersjs.com/services/readme.html#service-methods)
>   - [The setup method](http://docs.feathersjs.com/services/readme.html#the-setup-method)
>   - [Events](http://docs.feathersjs.com/services/readme.html#events)
>   - [Protecting Service Methods](http://docs.feathersjs.com/services/readme.html#protecting-service-methods)
>   - [Extending or Customizing Services](http://docs.feathersjs.com/services/readme.html#extending-or-customizing-services)
> - **[Providers](http://docs.feathersjs.com/providers/)**
>   - [Using providers together](http://docs.feathersjs.com/providers/#using-providers-together)
>   - [Creating your own provider](http://docs.feathersjs.com/providers/#creating-your-own-provider)
> - **[REST](http://docs.feathersjs.com/rest/readme.html)**
>   - [Usage](http://docs.feathersjs.com/rest/readme.html#usage)
>   - [Query, route and middleware parameters](http://docs.feathersjs.com/rest/readme.html#query-route-and-middleware-parameters)
>   - [Customizing The Response Format](http://docs.feathersjs.com/rest/readme.html#customizing-the-response-format)
> - **[Realtime](http://docs.feathersjs.com/real-time/readme.html)**
>   - **[Socket.io](http://docs.feathersjs.com/real-time/socket-io.html)**
>     - [Server Side Usage](http://docs.feathersjs.com/real-time/socket-io.html#server-side-usage)
>     - [Client Side Usage](http://docs.feathersjs.com/real-time/socket-io.html#client-side-usage)
>   - **[Primus](http://docs.feathersjs.com/real-time/primus.html)**
>     - [Server Side Usage](http://docs.feathersjs.com/real-time/primus.html#server-side-usage)
>     - [Client Side Usage](http://docs.feathersjs.com/real-time/primus.html#client-side-usage)
>   - **[Real-time Events](http://docs.feathersjs.com/real-time/events.html)**
>     - [Standard Events](http://docs.feathersjs.com/real-time/events.html#standard-events)
>     - [Custom events](http://docs.feathersjs.com/real-time/events.html#custom-events)
>     - [Listening For Events](http://docs.feathersjs.com/real-time/events.html#listening-for-events)
>     - [Hooks vs Events](http://docs.feathersjs.com/real-time/events.html#hooks-vs-events)
>   - **[Event Filtering](http://docs.feathersjs.com/real-time/filtering.html)**
>     - [Registering filters](http://docs.feathersjs.com/real-time/filtering.html#registering-filters)
>     - [Filter examples](http://docs.feathersjs.com/real-time/filtering.html#filter-examples)
>     - [Filtering Custom Events](http://docs.feathersjs.com/real-time/filtering.html#filtering-custom-events)
> - **[Databases](http://docs.feathersjs.com/databases/readme.html)**
>   - **[Pagination and sorting](http://docs.feathersjs.com/databases/pagination.html)**
>     - [Pagination](http://docs.feathersjs.com/databases/pagination.html#pagination)
>     - [Sorting, limiting and selecting](http://docs.feathersjs.com/databases/pagination.html#sorting-limiting-and-selecting)
>   - **[Querying](http://docs.feathersjs.com/databases/querying.html)**
>   - **[Extending adapters](http://docs.feathersjs.com/databases/extending.html)**
>   - **[In Memory](http://docs.feathersjs.com/databases/memory.html)**
>     - [Getting Started](http://docs.feathersjs.com/databases/memory.html#getting-started)
>     - [Options](http://docs.feathersjs.com/databases/memory.html#options)
>     - [Complete Example](http://docs.feathersjs.com/databases/memory.html#complete-example)
>   - **[KnexJS](http://docs.feathersjs.com/databases/knexjs.html)**
>     - [Getting Started](http://docs.feathersjs.com/databases/knexjs.html#getting-started)
>     - [Options](http://docs.feathersjs.com/databases/knexjs.html#options)
>     - [Complete Example](http://docs.feathersjs.com/databases/knexjs.html#complete-example)
>   - **[localStorage/AsyncStorage](http://docs.feathersjs.com/databases/localstorage.html)**
>     - [Getting Started](http://docs.feathersjs.com/databases/localstorage.html#getting-started)
>     - [Options](http://docs.feathersjs.com/databases/localstorage.html#options)
>     - [Browser Usage](http://docs.feathersjs.com/databases/localstorage.html#browser-usage)
>     - [Server Usage](http://docs.feathersjs.com/databases/localstorage.html#server-usage)
>     - [React Native Usage](http://docs.feathersjs.com/databases/localstorage.html#react-native-usage)
>   - **[Mongoose](http://docs.feathersjs.com/databases/mongoose.html)**
>     - [Getting Started](http://docs.feathersjs.com/databases/mongoose.html#getting-started)
>     - [Options](http://docs.feathersjs.com/databases/mongoose.html#options)
>     - [Migrating](http://docs.feathersjs.com/databases/mongoose.html#migrating)
>     - [Validation](http://docs.feathersjs.com/databases/mongoose.html#validation)
>     - [Modifying results with the toObject hook](http://docs.feathersjs.com/databases/mongoose.html#modifying-results-with-the-toobject-hook)
>   - **[MongoDB](http://docs.feathersjs.com/databases/mongodb.html)**
>     - [Getting Started](http://docs.feathersjs.com/databases/mongodb.html#getting-started)
>     - [Options](http://docs.feathersjs.com/databases/mongodb.html#options)
>     - [Complete Example](http://docs.feathersjs.com/databases/mongodb.html#complete-example)
>   - **[NeDB](http://docs.feathersjs.com/databases/nedb.html)**
>     - [Getting Started](http://docs.feathersjs.com/databases/nedb.html#getting-started)
>     - [Options](http://docs.feathersjs.com/databases/nedb.html#options)
>     - [Complete Example](http://docs.feathersjs.com/databases/nedb.html#complete-example)
>   - **[Sequelize](http://docs.feathersjs.com/databases/sequelize.html)**
>     - [Getting Started](http://docs.feathersjs.com/databases/sequelize.html#getting-started)
>     - [Options](http://docs.feathersjs.com/databases/sequelize.html#options)
>     - [Validation](http://docs.feathersjs.com/databases/sequelize.html#validation)
>     - [Migrations](http://docs.feathersjs.com/databases/sequelize.html#migrations)
>   - **[Waterline](http://docs.feathersjs.com/databases/waterline.html)**
>     - [Installation](http://docs.feathersjs.com/databases/waterline.html#installation)
>     - [Getting Started](http://docs.feathersjs.com/databases/waterline.html#getting-started)
>     - [Options](http://docs.feathersjs.com/databases/waterline.html#options)
>     - [Complete Example](http://docs.feathersjs.com/databases/waterline.html#complete-example)
>   - **[LevelUP](http://docs.feathersjs.com/databases/levelup.html)**
>     - [Installation](http://docs.feathersjs.com/databases/levelup.html#installation)
>     - [Getting Started](http://docs.feathersjs.com/databases/levelup.html#getting-started)
>     - [Key Order](http://docs.feathersjs.com/databases/levelup.html#key-order)
>     - [Range Queries](http://docs.feathersjs.com/databases/levelup.html#range-queries)
>     - [Complete Example](http://docs.feathersjs.com/databases/levelup.html#complete-example)
>   - **[RethinkDB](http://docs.feathersjs.com/databases/rethinkdb.html)**
>     - [Getting Started](http://docs.feathersjs.com/databases/rethinkdb.html#getting-started)
>     - [Options](http://docs.feathersjs.com/databases/rethinkdb.html#options)
>     - [Complete Example](http://docs.feathersjs.com/databases/rethinkdb.html#complete-example)
> - **[Hooks](http://docs.feathersjs.com/hooks/readme.html)**
>   - [Getting Started](http://docs.feathersjs.com/hooks/readme.html#getting-started)
>   - **[Usage](http://docs.feathersjs.com/hooks/usage.html)**
>     - [Before hooks](http://docs.feathersjs.com/hooks/usage.html#before-hooks)
>     - [After hooks](http://docs.feathersjs.com/hooks/usage.html#after-hooks)
>     - [As service properties](http://docs.feathersjs.com/hooks/usage.html#as-service-properties)
>     - [Asynchronous hooks](http://docs.feathersjs.com/hooks/usage.html#asynchronous-hooks)
>     - [Chaining / Registering Multiple Hooks](http://docs.feathersjs.com/hooks/usage.html#chaining--registering-multiple-hooks)
>     - [Communicating with other services](http://docs.feathersjs.com/hooks/usage.html#communicating-with-other-services)
>     - [Customizing Built In Hooks](http://docs.feathersjs.com/hooks/usage.html#customizing-built-in-hooks)
>   - **[Examples](http://docs.feathersjs.com/hooks/examples.html)**
>     - [Setting Timestamps](http://docs.feathersjs.com/hooks/examples.html#setting-timestamps)
>     - [Fetching Related Items](http://docs.feathersjs.com/hooks/examples.html#fetching-related-items)
>     - [Validation](http://docs.feathersjs.com/hooks/examples.html#validation)
>     - [Sanitization](http://docs.feathersjs.com/hooks/examples.html#sanitization)
>     - [Soft Delete](http://docs.feathersjs.com/hooks/examples.html#soft-delete)
>   - **[Built-in hooks](http://docs.feathersjs.com/hooks/bundled.html)**
>     - [populate](http://docs.feathersjs.com/hooks/bundled.html#populate)
>     - [disable](http://docs.feathersjs.com/hooks/bundled.html#disable)
>     - [remove](http://docs.feathersjs.com/hooks/bundled.html#remove)
>     - [removeQuery](http://docs.feathersjs.com/hooks/bundled.html#removequery)
>     - [pluck](http://docs.feathersjs.com/hooks/bundled.html#pluck)
>     - [pluckQuery](http://docs.feathersjs.com/hooks/bundled.html#pluckquery)
>     - [lowerCase](http://docs.feathersjs.com/hooks/bundled.html#lowercase)
> - **[Client Use](http://docs.feathersjs.com/clients/readme.html)**
>   - [Feathers as the client](http://docs.feathersjs.com/clients/readme.html#feathers-as-the-client)
>   - [Direct communication](http://docs.feathersjs.com/clients/readme.html#direct-communication)
>   - [Framework support](http://docs.feathersjs.com/clients/readme.html#framework-support)
>   - **[Feathers Client](http://docs.feathersjs.com/clients/feathers.html)**
>     - [Usage in NodeJS and client Module Loaders](http://docs.feathersjs.com/clients/feathers.html#usage-in-nodejs-and-client-module-loaders)
>     - [Usage with React Native](http://docs.feathersjs.com/clients/feathers.html#usage-with-react-native)
>     - [feathers-client](http://docs.feathersjs.com/clients/feathers.html#feathers-client)
>   - **[Direct connection](http://docs.feathersjs.com/clients/vanilla.html)**
> - **[Frameworks](http://docs.feathersjs.com/frameworks/readme.html)**
>   - **[React](http://docs.feathersjs.com/frameworks/react.html)**
>     - [Setting up the HTML page](http://docs.feathersjs.com/frameworks/react.html#setting-up-the-html-page)
>     - [Application Bootstrap](http://docs.feathersjs.com/frameworks/react.html#application-bootstrap)
>     - [Adding components](http://docs.feathersjs.com/frameworks/react.html#adding-components)
>     - [Rendering and authenticating](http://docs.feathersjs.com/frameworks/react.html#rendering-and-authenticating)
>   - **[React Native](http://docs.feathersjs.com/frameworks/react-native.html)**
>   - **[jQuery](http://docs.feathersjs.com/frameworks/jquery.html)**
>     - [Setting up the HTML page](http://docs.feathersjs.com/frameworks/jquery.html#setting-up-the-html-page)
>     - [jQuery code](http://docs.feathersjs.com/frameworks/jquery.html#jquery-code)
>   - **[CanJS](http://docs.feathersjs.com/frameworks/canjs.html)**
>   - **[Angular](http://docs.feathersjs.com/frameworks/angular.html)**
>   - **[Angular 2](http://docs.feathersjs.com/frameworks/angular2.html)**
>     - [Using TypeScript](http://docs.feathersjs.com/frameworks/angular2.html#using-typescript)
>     - [Using ES5](http://docs.feathersjs.com/frameworks/angular2.html#using-es5)
>     - [Setup](http://docs.feathersjs.com/frameworks/angular2.html#setup)
>     - [Creating our first resource](http://docs.feathersjs.com/frameworks/angular2.html#creating-our-first-resource)
>     - [Using a service in a component](http://docs.feathersjs.com/frameworks/angular2.html#using-a-service-in-a-component)
>     - [Wrapping up](http://docs.feathersjs.com/frameworks/angular2.html#wrapping-up)
>   - **[Vue.js](http://docs.feathersjs.com/frameworks/vuejs.html)**
>     - [Setting up the HTML page](http://docs.feathersjs.com/frameworks/vuejs.html#setting-up-the-html-page)
>     - [Application Bootstrap](http://docs.feathersjs.com/frameworks/vuejs.html#application-bootstrap)
>     - [Initialising our Vue instance](http://docs.feathersjs.com/frameworks/vuejs.html#initialising-our-vue-instance)
>     - [Adding components](http://docs.feathersjs.com/frameworks/vuejs.html#adding-components)
>     - [Further study](http://docs.feathersjs.com/frameworks/vuejs.html#further-study)
>   - **[iOS](http://docs.feathersjs.com/frameworks/ios.html)**
>   - **[Android](http://docs.feathersjs.com/frameworks/android.html)**
> - **[Middleware](http://docs.feathersjs.com/middleware/readme.html)**
>   - **[Express Middleware](http://docs.feathersjs.com/middleware/express.html)**
>     - [Rendering views](http://docs.feathersjs.com/middleware/express.html#rendering-views)
>     - [Custom service middleware](http://docs.feathersjs.com/middleware/express.html#custom-service-middleware)
>     - [Setting service parameters](http://docs.feathersjs.com/middleware/express.html#setting-service-parameters)
>   - **[Routing and Versioning](http://docs.feathersjs.com/middleware/routing.html)**
>     - [Nested routes](http://docs.feathersjs.com/middleware/routing.html#nested-routes)
>     - [Versioning](http://docs.feathersjs.com/middleware/routing.html#versioning)
>     - [As sub-applications](http://docs.feathersjs.com/middleware/routing.html#as-sub-applications)
>   - **[HTTPS, VHost, sub-apps](http://docs.feathersjs.com/middleware/mounting.html)**
>     - [Sub-Apps](http://docs.feathersjs.com/middleware/mounting.html#sub-apps)
>     - [HTTPS](http://docs.feathersjs.com/middleware/mounting.html#https)
> - **[Authentication](http://docs.feathersjs.com/authentication/readme.html)**
>   - [Usage](http://docs.feathersjs.com/authentication/readme.html#usage)
>   - [How does it work?](http://docs.feathersjs.com/authentication/readme.html#how-does-it-work)
>   - [What's next?](http://docs.feathersjs.com/authentication/readme.html#whats-next)
>   - **[Token (JWT)](http://docs.feathersjs.com/authentication/token.html)**
>     - [Usage](http://docs.feathersjs.com/authentication/token.html#usage)
>   - **[Local (username & password)](http://docs.feathersjs.com/authentication/local.html)**
>     - [Usage](http://docs.feathersjs.com/authentication/local.html#usage)
>   - **[Oauth1 (Twitter, etc)](http://docs.feathersjs.com/authentication/oauth1.html)**
>   - **[OAuth2 (Facebook, etc)](http://docs.feathersjs.com/authentication/oauth2.html)**
>     - [Usage](http://docs.feathersjs.com/authentication/oauth2.html#usage)
>   - **[Two Factor](http://docs.feathersjs.com/authentication/two-factor.html)**
>   - **[Password Management](http://docs.feathersjs.com/authentication/password.html)**
>   - **[Feathers Client](http://docs.feathersjs.com/authentication/client.html)**
>     - [API](http://docs.feathersjs.com/authentication/client.html#api)
>     - [Usage](http://docs.feathersjs.com/authentication/client.html#usage)
> - **[Authorization](http://docs.feathersjs.com/authorization/readme.html)**
>   - [Security](http://docs.feathersjs.com/authorization/readme.html#security)
>   - [Creating a custom authorization hook](http://docs.feathersjs.com/authorization/readme.html#creating-a-custom-authorization-hook)
>   - **[Bundled Hooks](http://docs.feathersjs.com/authorization/bundled-hooks.html)**
>     - [hashPassword](http://docs.feathersjs.com/authorization/bundled-hooks.html#hashpassword)
>     - [verifyToken](http://docs.feathersjs.com/authorization/bundled-hooks.html#verifytoken)
>     - [verifyOrRestrict](http://docs.feathersjs.com/authorization/bundled-hooks.html#verifyorrestrict)
>     - [populateUser](http://docs.feathersjs.com/authorization/bundled-hooks.html#populateuser)
>     - [populateOrRestrict](http://docs.feathersjs.com/authorization/bundled-hooks.html#populateorrestrict)
>     - [restrictToAuthenticated](http://docs.feathersjs.com/authorization/bundled-hooks.html#restricttoauthenticated)
>     - [queryWithCurrentUser](http://docs.feathersjs.com/authorization/bundled-hooks.html#querywithcurrentuser)
>     - [associateCurrentUser](http://docs.feathersjs.com/authorization/bundled-hooks.html#associatecurrentuser)
>     - [restrictToOwner](http://docs.feathersjs.com/authorization/bundled-hooks.html#restricttoowner)
>     - [restrictToRoles](http://docs.feathersjs.com/authorization/bundled-hooks.html#restricttoroles)
>     - [hasRoleOrRestrict](http://docs.feathersjs.com/authorization/bundled-hooks.html#hasroleorrestrict)
> - **[Error Handling](http://docs.feathersjs.com/middleware/error-handling.html)**
>   - [Options](http://docs.feathersjs.com/middleware/error-handling.html#options)
>   - [Catching Global Server Side Errors](http://docs.feathersjs.com/middleware/error-handling.html#catching-global-server-side-errors)
>   - [Feathers Error Types](http://docs.feathersjs.com/middleware/error-handling.html#feathers-error-types)
>   - [FeathersError API](http://docs.feathersjs.com/middleware/error-handling.html#featherserror-api)
> - **[Logging](http://docs.feathersjs.com/middleware/logging.html)**
> - **[Configuration](http://docs.feathersjs.com/configuration/readme.html)**
>   - [Usage](http://docs.feathersjs.com/configuration/readme.html#usage)
>   - [Example](http://docs.feathersjs.com/configuration/readme.html#example)
> - **[Debugging](http://docs.feathersjs.com/debugging/readme.html)**
>   - [Moar Logs!](http://docs.feathersjs.com/debugging/readme.html#moar-logs)
>   - [Using Hooks](http://docs.feathersjs.com/debugging/readme.html#using-hooks)
> - **[Testing](http://docs.feathersjs.com/testing/readme.html)**
> - **[Security](http://docs.feathersjs.com/SECURITY.html)**
>   - [Where should I report security issues?](http://docs.feathersjs.com/SECURITY.html#where-should-i-report-security-issues)
>   - [Security Considerations](http://docs.feathersjs.com/SECURITY.html#security-considerations)
>   - [Some of technologies we employ](http://docs.feathersjs.com/SECURITY.html#some-of-technologies-we-employ)
>   - [XSS Attacks](http://docs.feathersjs.com/SECURITY.html#xss-attacks)
> - **[Core API](http://docs.feathersjs.com/api/readme.html)**
>   - [configure](http://docs.feathersjs.com/api/readme.html#configure)
>   - [listen](http://docs.feathersjs.com/api/readme.html#listen)
>   - [setup](http://docs.feathersjs.com/api/readme.html#setup)
>   - [use](http://docs.feathersjs.com/api/readme.html#use)
>   - [service](http://docs.feathersjs.com/api/readme.html#service)
> - **[Guides](http://docs.feathersjs.com/guides/readme.html)**
>   - **[Migrating to Feathers 2](http://docs.feathersjs.com/guides/migrating.html)**
>     - [Provider modules](http://docs.feathersjs.com/guides/migrating.html#provider-modules)
>     - [Database adapters](http://docs.feathersjs.com/guides/migrating.html#database-adapters)
>     - [Feathers client](http://docs.feathersjs.com/guides/migrating.html#feathers-client)
>   - **[Using A View Engine](http://docs.feathersjs.com/guides/using-a-view-engine.html)**
>     - [A Single "Monolithic" App](http://docs.feathersjs.com/guides/using-a-view-engine.html#a-single-monolithic-app)
>     - [Feathers As A Sub-App](http://docs.feathersjs.com/guides/using-a-view-engine.html#feathers-as-a-sub-app)
>     - [Feathers As A Separate App](http://docs.feathersjs.com/guides/using-a-view-engine.html#feathers-as-a-separate-app)
>   - **[Uploading files](http://docs.feathersjs.com/guides/file-uploading.html)**
>     - [Basic upload with feathers-blob and feathers-client](http://docs.feathersjs.com/guides/file-uploading.html#basic-upload-with-feathers-blob-and-feathers-client)
>     - [Feathers-blob with multipart support.](http://docs.feathersjs.com/guides/file-uploading.html#feathers-blob-with-multipart-support)
>   - **[Creating a plugin](http://docs.feathersjs.com/guides/creating-a-plugin.html)**
>     - [Verifying our Service](http://docs.feathersjs.com/guides/creating-a-plugin.html#verifying-our-service)
>     - [Expanding our Plugin](http://docs.feathersjs.com/guides/creating-a-plugin.html#expanding-our-plugin)
>     - [Usage](http://docs.feathersjs.com/guides/creating-a-plugin.html#usage)
>     - [Testing](http://docs.feathersjs.com/guides/creating-a-plugin.html#testing)
> - **[Help](http://docs.feathersjs.com/help/readme.html)**
>   - **[FAQ](http://docs.feathersjs.com/help/faq.html)**
>     - [How do I debug my app](http://docs.feathersjs.com/help/faq.html#how-do-i-debug-my-app)
>     - [Can I expose custom service methods?](http://docs.feathersjs.com/help/faq.html#can-i-expose-custom-service-methods)
>     - [I am getting plain text errors with a 500 status code](http://docs.feathersjs.com/help/faq.html#i-am-getting-plain-text-errors-with-a-500-status-code)
>     - [How can I do custom methods like findOrCreate?](http://docs.feathersjs.com/help/faq.html#how-can-i-do-custom-methods-like-findorcreate)
>     - [How do I do nested routes?](http://docs.feathersjs.com/help/faq.html#how-do-i-do-nested-routes)
>     - [How do I do I render templates?](http://docs.feathersjs.com/help/faq.html#how-do-i-do-i-render-templates)
>     - [How do I create channels or rooms](http://docs.feathersjs.com/help/faq.html#how-do-i-create-channels-or-rooms)
>     - [I got a possible EventEmitter memory leak detected warning](http://docs.feathersjs.com/help/faq.html#i-got-a-possible-eventemitter-memory-leak-detected-warning)
>     - [How do I do validation?](http://docs.feathersjs.com/help/faq.html#how-do-i-do-validation)
>     - [How do I return related entities?](http://docs.feathersjs.com/help/faq.html#how-do-i-return-related-entities)
>     - [What about Koa/Hapi/X?](http://docs.feathersjs.com/help/faq.html#what-about-koahapix)
>     - [How do I filter emitted service events?](http://docs.feathersjs.com/help/faq.html#how-do-i-filter-emitted-service-events)
>     - [How do I access the request object in hooks or services?](http://docs.feathersjs.com/help/faq.html#how-do-i-access-the-request-object-in-hooks-or-services)
>     - [How do I mount sub apps?](http://docs.feathersjs.com/help/faq.html#how-do-i-mount-sub-apps)
>   - **[Contributing](http://docs.feathersjs.com/contributing.html)**
>     - [Contributing Guidelines](http://docs.feathersjs.com/contributing.html#contributing-guidelines)
>   - **[Changelog](http://docs.feathersjs.com/changelog.html)**
> - **[License](http://docs.feathersjs.com/license.html)**
>   - [The MIT license](http://docs.feathersjs.com/license.html#the-mit-license)

**Comment by kulakowka** [comment]
It parses gitbook, and builds a table of contents based on the headings and subheadings for each page.

**Comment by kulakowka** [comment]
May be we can use something like [JSDoc](http://usejsdoc.org) for creating API Docs?

I think it would be convenient if we make the documentation in all official plugins on a single page.

**Comment by kulakowka** [comment]
I found a theme for jsdoc: [minami](https://github.com/nijikokun/minami)

[underscorejs](http://underscorejs.org/) uses it.

![687474703a2f2f7075752e73682f674f794e652f363663336164636239372e706e67](https://cloud.githubusercontent.com/assets/557190/18272082/7c4c9192-743e-11e6-9200-ef8e51421ec0.png)

**Comment by kulakowka** [comment]
We can create API docs in markdown format with [documentation.js](http://documentation.js.org/).
This will allow us to automatically generate documents for API, and then we can use the usual gitbook.

**Comment by NetOperatorWibby** [comment]
I personally like how Slate looks for documentation https://github.com/lord/slate

**Comment by kulakowka** [comment]
Today I tried this: [jsdoc-to-markdown](https://github.com/jsdoc2md/jsdoc-to-markdown)

It's amazing! And very simple!

**Comment by kulakowka** [comment]
For preview docs i uses [markserv](https://www.npmjs.com/package/markserv). It serves Markdown files as GitHub style HTML and LiveReloads your files in the browser as you edit.

```
cd path/to/docs
markserv
```

**Comment by daffl** [comment]
We are going to restructure the documentation for the next release with every page containing a Summary + API, Example and detailed explanations and a big Ecosystem chapter (for discussion see https://github.com/feathersjs/feathers-docs/issues/251#issuecomment-258071621). This will hopefully make finding the API easier while not requiring two documentation sections.

**Comment by daffl** [comment]
This has been done for Auk and is available at https://docs.feathersjs.com/api/readme.html
