### ISSUE TITLE
Chat guide forgets to mention to remove a default user hook.

### ISSUE THREAD

**Issue by roelvan** [feathersjs/feathers#319]
hi guys, following the chat app guide, I had to remove this before user hook (get): `auth.restrictToOwner({ ownerField: '_id' })`. If not, the sentBy user was only populated for my own messages. Not sure if this is hook is added by default or if I added it accidentally. But if so, it could confuse newcomers.

**Comment by daffl** [comment]
This has been fixed in the latest Auk chat guide.
