### ISSUE TITLE
How to use $set in patch or update?

### ISSUE THREAD

**Issue by patrickpereira** [feathersjs/feathers#323]
Hi Feathers team, 

I've been trying to use $set in a update or a patch, but I can't seem to figure out how to use it. I'm using feathers with Mongoose.

Any help would be highly appreciated.

Best regards
Patrick

**Comment by marshallswain** [comment]
@patrickpereira, feathers-mongoose uses `$set` internally, already: https://github.com/feathersjs/feathers-mongoose/blob/master/src/service.js#L183

**Comment by daffl** [comment]
Yes, `patch` uses `$set`. You should also be able to use `$set` in `update`. `app.service('messages').update(id, { $set: mydata })` didn't work?

**Comment by patrickpereira** [comment]
Thanks for the swift replies, I forgot to mention that I dont have id, so I was putting in null instead and also it's a subdocument that I'm trying to find and update with $set. 

So far I had to manually require the mongoose model and I solved it like this:

```
text_messages.findOneAndUpdate({
			'result.customid': params.query.customid,
			'result.id': params.query.id
		}, {
			$set: {
			    "result.$.status": params.query.status,
			    "result.$.date": new Date(parseInt(params.query.date)*1000),
			    "result.$.statusText": statusCodes[parseInt(params.query.status)]
			}
		}, {
			new: true
		},
		(err, res) => {
			console.log(err,res);
			this.emit('status', res);
		})
```

Is there a better way to do this using the builtin services in feathers?

**Comment by ekryski** [comment]
I think [this issue](https://github.com/feathersjs/feathers-mongoose/issues/68) is somewhat related. Basically you want to be able to supply additional query options similar to how we handle it with sequelize (https://github.com/feathersjs/feathers-sequelize/pull/27).
