### ISSUE TITLE
Accessing remote_address in before hook from REST provider

### ISSUE THREAD

**Issue by patrickpereira** [feathersjs/feathers#324]
Hi feathers,

Is it possible to access the remote_address in the before hook and if so, how is it done?

Best regards
Patrick

**Comment by daffl** [comment]
You can [add a middleware](http://docs.feathersjs.com/rest/readme.html#query-route-and-middleware-parameters) and set the `req.feathers` object with that information:

```js
app.use(function(req, res, next) {
  req.feathers.ip = req.ip;
});
```

Now it will be available for every REST call in the service parameters as `params.ip`. For websocket connections you will have to do the [same thing in a Socket.io middleware](http://docs.feathersjs.com/real-time/socket-io.html#configuration).

**Comment by patrickpereira** [comment]
Brilliant, thanks!

**Comment by daffl** [comment]
Glad to help. Closing.

**Comment by KidkArolis** [comment]
Up to date documentation can be found at: https://docs.feathersjs.com/faq/readme.html#how-do-i-access-the-request-object-in-hooks-or-services

### REST example
https://docs.feathersjs.com/api/express.html#params

### Web Sockets example
https://docs.feathersjs.com/api/socketio.html#appconfiguresocketiocallback
