### ISSUE TITLE
Socket io logger

### ISSUE THREAD

**Issue by patrickpereira** [feathersjs/feathers#325]
Hi feathers,

What's the best approach to log all socket io events server side?

**Comment by corymsmith** [comment]
You can run start your server with 

'DEBUG=* node /src'

If you want to filter only on certain libs you'll have to specify vs using the *

**Comment by corymsmith** [comment]
Or you can use Chrome dev tools to view the WebSocket frames

**Comment by daffl** [comment]
What @corymsmith said. You can find more info in the [Feathers debugging](http://socket.io/docs/logging-and-debugging/) chapter and the [Socket.io Logging and Debugging](http://socket.io/docs/logging-and-debugging/) page. It should give you all the information you need.
