### ISSUE TITLE
Authorization for Web Socket connections

### ISSUE THREAD

**Issue by anhldbk** [feathersjs/feathers#328]
This is the demo code on [using SocketIO](http://docs.feathersjs.com/clients/socket-io.html) with Feathers.
```js
  var socket = io('http://api.feathersjs.com');
  var app = feathers()
    .configure(feathers.hooks())
    .configure(feathers.socketio(socket));

  var messageService = app.service('messages');

  messageService.on('created', function(message) {
    console.log('Someone created a message', message);
  });

  messageService.create({
    text: 'Message from client'
  });
```

My question is: how to authenticate & authorize such connections? Are we gonna using [Filtering](http://docs.feathersjs.com/real-time/filtering.html)

**Comment by marshallswain** [comment]
Have you already taken a look at the `feathers-authentication` plugin?  When used together with the `feathers-client` it provides a pretty clean method of making this happen.

http://docs.feathersjs.com/clients/feathers.html
http://docs.feathersjs.com/authentication/client.html  There is an example on this page.

**Comment by daffl** [comment]
I think you question should be answered in the authentication chapter @marshallswain linked. We are also doing websocket authentication in the [getting started guide](http://docs.feathersjs.com/getting-started/readme.html).
