### ISSUE TITLE
Can't create new DELETE route

### ISSUE THREAD

**Issue by kozzztya** [feathersjs/feathers#329]
I have mongoose service `/some`. And I need another route DELETE `/some/unregister`. So I tried to create new service for this, but have error:

```
error: (400) Route: /some/unregister - Cast to ObjectId failed for value "unregister" at path "_id"
```

**Comment by daffl** [comment]
Just like with Express, order matters. In this case, the `/some` service runs because it matches the `/some/:id` route thinking that `unregister` is the id you want to delete.

If you register the `/some/unregister` service __before__ the `/some` service it should work.
