### ISSUE TITLE
oauth ignores redirect url on error

### ISSUE THREAD

**Issue by thiemogries** [feathersjs/feathers#3292]
I think #3284 introduced a new bug where `oauth.origins` / `oauth.redirect` is ignored for failed authentication requests. 

### Steps to reproduce

- setup github oauth process
- during the authorization step on https://github.com/login/oauth/authorize?... press _Cancel_ instead of _Authorize_

### Expected behavior

- I should get redirected to the `oauth.redirect` url (with the error message)

### Actual behavior

- I stay on the feathers url and see the plain JSON error instead

Moving the error check inside the `try ... catch` block fixes it for me but I don't know if this reintroduces some problems from #3275 #3266 #3276 

_@feathersjs/authentication-oauth/src/service.ts_
```
    try { 
      if (payload.error) {
        throw new OAuthError(payload.error_description || payload.error, payload)
      }
      debug(`Calling ${authService}.create authentication with strategy ${name}`)
      ...
    } catch (error: any) {
      const location = await strategy.getRedirect(error, authParams)
      ...
    }
```

**Comment by daffl** [comment]
You are totally right. I was so sure I had it in the block where it is supposed to be. Will be fixed in the next release via #3297
