### ISSUE TITLE
Unable to install feathers-cli

### ISSUE THREAD

**Issue by brec-c** [feathersjs/feathers#331]
calling like this: npm install -g feathers-cli
using node 6.2 / nam 3.8.9 on OS X 10.11.5

get response:

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "feathers-cli"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! path /usr/local/lib/node_modules/feathers-cli/node_modules/yo/lib/cli.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/feathers-cli/node_modules/yo/lib/cli.js'
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/feathers-cli/node_modules/yo/lib/cli.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/brec/Google Drive/projects/feathersjs/npm-debug.log
npm ERR! code 1

hopefully this is useful and not a dupe. thanks.

**Comment by aminmeyghani** [comment]
I have a feeling you need to have `yo` installed: `npm i yo -g`

**Comment by brec-c** [comment]
installing yo had the same issue.  feeling less like a feathersjs issue and more of an environmental / npm issue.  interesting.  and doh.

**Comment by aminmeyghani** [comment]
It seems like the issue is related to YO, not feathers: https://github.com/yeoman/yo/issues/437

**Comment by aminmeyghani** [comment]
@brec-c you can try installing it again now: https://github.com/feathersjs/feathers-cli/issues/26

**Comment by ekryski** [comment]
Yup this is fixed. I froze the `yo` version. We'll be moving away from yeoman in the future.
