### ISSUE TITLE
getting started guide - email to lower case

### ISSUE THREAD

**Issue by Evanion** [feathersjs/feathers#333]
Just copy/pasted from slack:

I’m sitting with the getting started guide .. and just noticed something … There should be a step (global hook?) that makes sure the users email is always lowercase. It’s just good usability. A simple tutorial is no reason for slacking ;)

**Comment by ekryski** [comment]
@Evanion care to open a PR? :grin: You can simply click "Edit this page" at the top of the docs.

**Comment by Evanion** [comment]
I will try and get the time for it.

**Comment by daffl** [comment]
Closing since it has been over a month without any activity. We still welcome a pull request of course.
