### ISSUE TITLE
Socket.io client not working with ackTimeout

### ISSUE THREAD

**Issue by mrabczuk75** [feathersjs/feathers#3336]
### Issue
In V5, setting up a socket.io client with an ackTimeout:
```
const socket = io(
  'http://api.feathersjs.com',
  {
    ackTimeout: 5000
  }
)
app.configure(socketio(socket))
```

changes socket.io client's ack callback arguments from:

`(response) => { }`
to
`(err, response) => { }`

which effectively breaks response handling for any service call.

### Proposed solution:

Check if socket timeout exists in Service.send() method (transport-commons/client) and handle the args correspondigly:
```
const socketTimeout = this.connection.flags.timeout || this.connection._opts.ackTimeout
args.push(function (error, ...args) {
   return !socketTimeout
      ? error ? reject(convert(error)) : resolve(args[0])
      : error || args[0] ? reject(convert(error || args[0])) : resolve(args[1])
})
```

**Comment by daffl** [comment]
This seems really strange but I could indeed not get the chat working with this setting either. Since this behaviour does not seem to be documented anywhere, it seems like a bug in Socket.io though.

**Comment by mrabczuk75** [comment]
I’d disagree – it’s related to socket timeout, which is documented here: https://socket.io/docs/v4/client-api/#sockettimeoutvalue

See also example inside https://socket.io/docs/v4/client-api/#socketemitwithackeventname-args

**Comment by jd1378** [comment]
I just got this bug today, and its as mrabczuk75 describes
adding `ackTimeout` breaks the client, removing it brings back the correct behavior

**Comment by daffl** [comment]
Oh yes, I was able to confirm this but apparently didn't reply here. If we can have tests for the proposed fix it probably makes sense to include it.

**Comment by jd1378** [comment]
if the ack feature is always used, why not use `emitWithAck` instead of `emit`, since `emitWithAck` seems to be always returning a promise

edit: now I see that `emitWithAck` does not return all ack values, investigating on socket.io side ...
edit 2: it seems socketio uses `emit` for `emitWithAck` under the hood anyway

**Comment by jd1378** [comment]
I'm trying to hack a patch on my code to test it but I can't really find where the magic is happening exactly

I have found these so far but still haven't figure it out:
https://github.com/feathersjs/feathers/blob/181fedb026e21f5978cc32cecfc16c176cf78e59/packages/transport-commons/src/client.ts#L11
https://github.com/feathersjs/feathers/blob/181fedb026e21f5978cc32cecfc16c176cf78e59/packages/transport-commons/src/client.ts#L95
https://github.com/feathersjs/feathers/blob/181fedb026e21f5978cc32cecfc16c176cf78e59/packages/socketio-client/src/index.ts#L34

**Comment by jd1378** [comment]
Okay, tested and made it a bit more clear
it works
I'll try to make a PR

**Comment by jd1378** [comment]
I made the PR and added a test, but the test is probably not good since it isn't the actual socket io calling the callback, meaning if it breaks later (behavior change of socket io I mean), we won't know
