### ISSUE TITLE
Support $search in query syntax

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers#334]
I am consolidating all the individual issues and discussions here:

This is a proposed special attribute that allows you to fuzzy match a property. Possibly even multiple properties and/or nested documents.

Suggested syntax:

``` js
name: {
  $search: ['alice', 'Alice', 'bo', /$bob/i]
}
```

Following similar syntax to our other special query filters, this would allow you to filter by a singular value, multiple values (treated like an **or**) and/or regular expressions directly.
### Service Adapter Completion
- [ ] NeDB
- [ ] MongoDB
- [ ] Mongoose
- [ ] Sequelize
- [ ] Knex
- [ ] Waterline
- [ ] RethinkDB
- [ ] Memory
- [ ] Localstorage
- [ ] LevelUp
- [ ] Blob?? (maybe to support fuzzy matching filenames?)

**Comment by daffl** [comment]
Also related:

- https://github.com/feathersjs/feathers-query-filters/pull/11
- https://github.com/feathersjs/feathers-service-tests/issues/7

**Comment by alnour-altegani** [comment]
any news on this feature ?
if it is not implemented , **how to fuzzy match a property now without this special attribute** ?

**Comment by daffl** [comment]
You can create a hook that for e.g. MongoDB converts the `$search` query to a [$regex](https://docs.mongodb.com/manual/reference/operator/query/regex/):

```js
app.service('todos').before({
  find(hook) {
    const query = hook.params.query;
    if(query.name.$search) {
      query.name = { $regex: new RegExp(query.name.$search) }
    }
  }
});
```

**Comment by alnour-altegani** [comment]
the way to make fuzzy match for some field in collection before your comment was to use **custom route** and write native query with same service db engine like "mongo" or "nedb" .
but this way is very good and show me new use case to use hooks in featherjs

**Comment by alnour-altegani** [comment]
what about this hook as simple solution for search in mongodb & nedb
```js
exports.searchRegex = function () {
	return function (hook) {
    const query = hook.params.query;
    for (let field in query) {
      if(query[field].$search && !query[field].includes('$')) {
        query[field] = { $regex: new RegExp(query[field].$search) }
      }
    }
    hook.params.query = query
    return hook
  }
}
```
and simply include it in the 
```bash
src/services/ServiceName/hooks
```
like
```js
exports.before = {
  all: [],
  find: [globalHooks.searchRegex()]
}
```

**Comment by ruddfawcett** [comment]
@alnour-altegani The above is working for you? Just gave it a test run and no luck.

**Comment by ruddfawcett** [comment]
For those interested, you can make the above code posted by @alnour-altegani case insensitive by changing
```js
 query[field] = { $regex: new RegExp(query[field].$search) }
```
to:
```js
 query[field] = { $regex: new RegExp(query[field].$search, 'i') } // note the 'i'
```

**Comment by beeplin** [comment]
so why $search, not $regex?
hope it compatible with mongo's original syntax.

**Comment by beeplin** [comment]
so why $search, not $regex?
hope it compatible with mongoDB's original syntax, which is available now out-of-box already, so we don't need to change it in the future.

**Comment by cklmercer** [comment]
Just stumbled upon this after fighting with the Mongoose adapter for half an hour. This would be a super nice addition.

**Comment by daffl** [comment]
There is a working hook two comments above. Mongoose already supports it, you just have to convert the query into a regular expression in a `before` hook.

By now, I am also leaning more towards not adding this. Defining an abstract search format for all databases isn't really possible. Some support `%like%` queries, others use regular expressions and some do not support searching at all.

**Comment by cklmercer** [comment]
Thanks for the quick reply.

**Comment by marshallswain** [comment]
@daffl I agree 100%.  This feature just became more of a per-adapter documentation issue, imo.

**Comment by daffl** [comment]
I am going to close this issue for the reasons mentioned above that the search syntax is very database specific and hard to abstract. Most databases already support their own search syntax that can be converted to in a hook:

- Regular expressions (converted in a a hook) for Mongoose, MongoDB and NeDB, see [this comment](https://github.com/feathersjs/feathers/issues/334#issuecomment-234432108)
- [$like for Sequelize](http://docs.sequelizejs.com/en/latest/docs/querying/)
- KnexJS with [where('like')](http://knexjs.org/#Builder-where)
- Others like `feathers-memory` and Redis do not have any search at all

**Comment by frastlin** [comment]
Could an example hook please be posted for sequelize?
I would like to do some regular expressions or contains on a parameter like getting all titles that start with "pro".
Thanks,

**Comment by daffl** [comment]
Most likely it is anything that the [SQL LIKE operator](http://dev.mysql.com/doc/refman/5.7/en/string-comparison-functions.html) supports for your database.

**Comment by sajov** [comment]
I tried the above suggested hook with feathers-nedb
and got following error
"Unknown logical operator $search"
Whats wrong?

**Comment by daffl** [comment]
@sajov Example linked in the comment above: https://github.com/feathersjs/feathers/issues/334#issuecomment-234432108

**Comment by sajov** [comment]
got it, my fault. Thanks

**Comment by alnour-altegani** [comment]
@sajov thank you for sharing your work . but, can you give example of how to use this code to search with $or operator ?

**Comment by sajov** [comment]
@ruddfawcett i use it in a datatable context like this

```javascript
for (var i = 0;i < opts.tableHeader.length; i++) {
                        let q = {};
                        q[opts.tableHeader[i]] = {$search: queryObj.search.value.value};
                        query.$or.push(q);
                    }
```

**Comment by MidnightP** [comment]
@sajov Were you able to write a README ? I'd be very interested to see how I could use this case in combination with an ```$or``` -array e.g. like 
```
[
    { _id: searchInput },
    { type: searchInput }
]
```

**Comment by sajov** [comment]
@MidnightP 

Hook example which treat `$search` as `{ $regex: new RegExp(value, 'i') };`
https://github.com/sajov/riot-crud/blob/master/example/src/hooks/index.js#L50-L53

Client example 
https://github.com/sajov/riot-crud/blob/master/tags/themes/bootstrap/views/crud-views.tag#L140-L141
```javascript
query.$or = [
    {fieldA : {$search: value}},
    {fieldB : {$search: value}},
];
```

hope that answer your question

**Comment by MidnightP** [comment]
@sajov Thanks!

I rewrote things a bit and ended up using the hook below for a client side query containing this:
```
orRegex: [
  { 
    fieldA: {
      $search: 'searchinput'
    }
  },
  { 
    fieldB: {
      $search: 'searchinput'
    }
  },
  et cetera...
]
```

```
return function(hook) {
    const { query } = hook.params

    if( Object.keys(query).includes('orRegex') )  {
      const or = query.orRegex.map((field) => {
        console.log('Object.keys(field)[0]: ', Object.keys(field)[0] )

        const attribute = Object.keys(field)[0]

        return {
          [attribute]: {
            $regex: new RegExp(field[Object.keys(field)[0]]['$search']), $options: 'ix'
          }
        }
      })

      delete(query.orRegex)

      hook.params.query['$or'] = or
    }
    return hook
  }
```

**Comment by daffl** [comment]
Maybe @eddyystop has some thoughts if this can be turned into a common hook.

**Comment by eddyystop** [comment]
Just saw this now. I've created an issue in feathers-hooks-common https://github.com/feathersjs/feathers-hooks-common/issues/141

**Comment by arve0** [comment]
Here is a fuzzy match for NeDB, it searches all properties case insensitive:

```js
module.exports = function (options = {}) { // eslint-disable-line no-unused-vars
  return function (hook) {
    if (hook.params.query && hook.params.query.$search) {
      hook.params.query.$where = fuzzySearch(hook.params.query.$search)
      delete hook.params.query.$search
    }
    return hook
  }
}

/**
 * Returns a $where function for NeDB. The function search all
 * properties of objects and returns true if `str` is found in
 * one of the properties. Searching is not case sensitive.
 *
 * @param {string} str search for this string
 * @return {function}
 */
function fuzzySearch (str) {
  let r = new RegExp(str, 'i')

  return function () {
    for (let key in this) {
      // do not search _id and similar fields
      if (key[0] === '_' || !this.hasOwnProperty(key)) {
        continue
      }
      if (this[key].match(r)) {
        return true
      }
    }
    return false
  }
}
```

I actually found this to be a bit quicker than single property regex. With fuzzy search I got 47 ms average time for `service.find()`, versus ~68 ms for single field `$regex`. Times are average of 50 times loop over 7 different search terms, and the DB contains about 14000 rows, each object has four properties, all of them text. Only one property has a lengthy, 140 chars, text field. I guess the implementation is vulnerable to DOS attacks, but `$regex` should also be.

**Comment by arve0** [comment]
Based on my comment above I've made to plugins:

- [NeDB fuzzy search](https://www.npmjs.com/package/feathers-nedb-fuzzy-search)
- [MongoDB fuzzy search](https://www.npmjs.com/package/feathers-mongodb-fuzzy-search)

**Comment by ulrichborchers** [comment]
Hi,

stumbled into this thread from querying.md:
https://github.com/feathersjs/docs/blob/master/api/databases/querying.md

... which is referring here.

Noticed a little mistake in the querying sample URI for the $in,$nin example.

If I am not mistaken it should be:
`/messages?roomId[$in][]=2&roomId[$in][]=5`

instead of:
`/messages?roomId[$in]=2&roomId[$in]=5`

because $in is an array in the query.

**Comment by glazs** [comment]
Hi everybody! I'm trying to use feathers-nedb-fuzzy-search

My query is: http://localhost:3030/messages?$sort[date]=-1&$skip=0&$search=2

And result: {"name":"BadRequest","message":"Invalid query parameter $where","code":400,"className":"bad-request","data":{"$sort":{"date":"-1"},"$skip":"0"},"errors":{}}

error: BadRequest: Invalid query parameter $where
    at new BadRequest (/home/glazs/workspace/lmt/server/node_modules/@feathersjs/errors/lib/index.js:86:17)
    at _.each (/home/glazs/workspace/lmt/server/node_modules/@feathersjs/adapter-commons/lib/filter-query.js:48:17)
    at Object.keys.forEach.key (/home/glazs/workspace/lmt/server/node_modules/@feathersjs/commons/lib/utils.js:12:39)
    at Array.forEach (<anonymous>)
    at Object.each (/home/glazs/workspace/lmt/server/node_modules/@feathersjs/commons/lib/utils.js:12:24)
    at cleanQuery (/home/glazs/workspace/lmt/server/node_modules/@feathersjs/adapter-commons/lib/filter-query.js:41:7)
    at filterQuery (/home/glazs/workspace/lmt/server/node_modules/@feathersjs/adapter-commons/lib/filter-query.js:107:18)
    at Object.filterQuery (/home/glazs/workspace/lmt/server/node_modules/@feathersjs/adapter-commons/lib/service.js:46:20)
    at Object._find (/home/glazs/workspace/lmt/server/node_modules/feathers-nedb/lib/index.js:36:47)
    at callMethod (/home/glazs/workspace/lmt/server/node_modules/@feathersjs/adapter-commons/lib/service.js:9:20)
error: TypeError: Expected a string
    at module.exports (/home/glazs/workspace/lmt/server/node_modules/escape-string-regexp/index.js:7:9)
    at fuzzySearch (/home/glazs/workspace/lmt/server/node_modules/feathers-nedb-fuzzy-search/index.js:49:22)
    at Object.<anonymous> (/home/glazs/workspace/lmt/server/node_modules/feathers-nedb-fuzzy-search/index.js:33:34)
    at promise.then.hookObject (/home/glazs/workspace/lmt/server/node_modules/@feathersjs/commons/lib/hooks.js:142:73)
What's wrong with my Feathers/NeDB?

**Comment by daffl** [comment]
In the latest versions of all database adapters non-standard query parameters have to be [explicitly whitelisted](https://crow.docs.feathersjs.com/migrating.html#whitelisting). 

```js
nedbService({
  whitelist: [ '$where', '$search' ]
});
```

**Comment by jscottsf** [comment]
The whitelisting seems to break feathers-vuex since it uses commons. Not related to this thread tho. I'll dig deeper on that and log an issue over there.

https://github.com/feathers-plus/feathers-vuex

**Comment by 1MikeMakuch** [comment]
> what about this hook as simple solution for search in mongodb & nedb
> 
> ```js
> exports.searchRegex = function () {
>   return function (hook) {
>     const query = hook.params.query;
>     for (let field in query) {
>       if(query[field].$search && field.indexOf('$') == -1) {
>         query[field] = { $regex: new RegExp(query[field].$search) }
>       }
>     }
>     hook.params.query = query
>     return hook
>   }
> }
> ```
> 
> and simply include it in the
> 
> ```shell
> src/services/ServiceName/hooks
> ```
> 
> like
> 
> ```js
> exports.before = {
>   all: [],
>   find: [globalHooks.searchRegex()]
> }
> ```

Works for me.

**Comment by benitezluis** [comment]
From client **strength: 1**

```
const query = { name: { $regex: value } };
const collation = { strength: 1 };
clients.find({ query, collation }).then( ... );
```

**Comment by Zalasanjay** [comment]
While using `feathers-mongodb-fuzzy-search` module If you got an error like `Invalid $regex`

Then you can try `whitelist` attribute to white list that keywords in your mongoose service configuration in `<service_name>.service.js` file

```
const options = {
    paginate,
    whitelist: ['$regex', '$options']
};
```

**Comment by lcampanis** [comment]
**This is an ALL inclusive search - meaning it looks for a match in all fields:** 
> what about this hook as simple solution for search in mongodb & nedb
> 
> ```js
> exports.searchRegex = function () {
>   return function (hook) {
>     const query = hook.params.query;
>     for (let field in query) {
>       if(query[field].$search && field.indexOf('$') == -1) {
>         query[field] = { $regex: new RegExp(query[field].$search) }
>       }
>     }
>     hook.params.query = query
>     return hook
>   }
> }
> ```
> 
> and simply include it in the
> 
> ```shell
> src/services/ServiceName/hooks
> ```
> 
> like
> 
> ```js
> exports.before = {
>   all: [],
>   find: [globalHooks.searchRegex()]
> }
> ```

**This will match any of the fields with $or:**
```js
exports.searchRegEx = function () {
  return function (hook) {
    const query = hook.params.query;
    for (let field in query) {
      if(query[field].$search && field.indexOf('$') == -1) {
        query.$or = [...(query.$or || []), { [field]: { $regex: new RegExp(query[field].$search, 'ig') } }];
        delete query[field];
      }
    }
    hook.params.query = query
    return hook
  }
}
`

**Comment by DaddyWarbucks** [comment]
Here are a couple examples of how I typically handle this in both Sequelize and Mongo/Mongoose

Sequelize
```js
export const withSearch = (searchProps, idProps) => (context) => {
  if (!context.params.query) {
    return context;
  }

  const { $search, ...query } = context.params.query;

  if (!$search) {
    context.params.query = query;
    return context;
  }

  const $or = [];

  searchProps.forEach((prop) => {
    $or.push({ [prop]: { $iLike: `%${$search}%` } });
  });

  if (idProps && isValidInteger($search)) {
    idProps.forEach((prop) => {
      $or.push({ [prop]: $search });
    });
  }

  context.params.query = {
    ...query,
    $or: [...(query.$or || []), ...$or]
  };

  return context;
};
```

Mongo/Mongoose
```js
const traverse = require('traverse');

// https://stackoverflow.com/questions/3446170/escape-string-for-use-in-javascript-regex
const escapeRegExp = (string) => {
  return string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
};

module.exports.searchRegex = (stringProps, numberProps) => (context) => {
  if (!context.params.query) {
    return context;
  }

  // TODO: Deepclone? Or is traverse immutable?
  const query = { ...context.params.query };
  const $search = query.$search;
  delete query.$search;

  // Find and replace any `$search` properties, even when
  // nested in query or query arrays
  traverse(query).forEach(function (value) {
    if (this.parent && this.parent.node.$search !== undefined) {
      this.parent.node.$regex = new RegExp(escapeRegExp(value), 'i');
      delete this.parent.node.$search;
    }
  });

  if ($search && stringProps) {
    query.$or = query.$or || [];
    stringProps.forEach((prop) => {
      query.$or.push({
        [prop]: { $regex: new RegExp(escapeRegExp($search), 'i') }
      });
    });
  }

  if ($search && !isNaN(Number($search)) && numberProps) {
    query.$or = query.$or || [];
    numberProps.forEach((prop) => {
      query.$or.push({
        [prop]: Number($search)
      });
    });
  }

  context.params.query = query;

  return context;
};
```

The Sequelize example is pretty similar to many I have seen here already, except it handles Integer fields as well. The Mongo/Mongoose example is better because it uses `traverse` and can handle deeply nested queries in `$and`, `$or`, etc. The Sequelize example should be updated to include that
