### ISSUE TITLE
Best approach of logging user login/logout events to DB

### ISSUE THREAD

**Issue by patrickpereira** [feathersjs/feathers#335]
Hi Feathers,

What's the best way of achieving this in feathers?

Best regards

**Comment by marshallswain** [comment]
I don't know that there's a single best approach to the architecture of this, but there are a few general guidelines that will universally apply.  

1. Choose a db/adapter (say, feathers-mongodb) http://docs.feathersjs.com/databases/readme.html
2. Create a hook for either the auth/local service (for username/password auth) or the users service (for OAuth-type logins).  Inside this hook you'll simply do a `create` on your logging service. http://docs.feathersjs.com/hooks/readme.html  
3. Disable external access to the logging service to prevent sensitive data from leaking. http://docs.feathersjs.com/hooks/bundled.html#disable

**Comment by ekryski** [comment]
I agree with @marshallswain 💯 . Basically you'll probably need middleware (at least for logout) in order to log when a user logs in and out. As @marshallswain suggested you can use an `after` hook on the auth service (whichever ones you are using) and do your logging. Which might look like this:

```js
app.service('auth/local').after({
  create: function(hook) {
    return hook.app.service('logs')
       .create({ event: 'user logged in', user: hook.params.user.id });
       .then(() => hook);
  }
});
```

Something to that effect.

**Comment by ekryski** [comment]
An update that we have some stuff coming in a new auth release that allows you to just do `app.on('login', function(data){...}` and `app.on('logout', function(data){...})`

**Comment by patrickpereira** [comment]
Amazing, when is the update coming?

**Comment by ekryski** [comment]
@patrickpereira end of this week most likely. We just have to fix some of the broken tests and update docs/examples.

**Comment by ramsestom** [comment]
would the `app.on('logout', function(data){...})` also consider 'dirty' logout cases (where the client just end connection without calling some 'logout' function)?

**Comment by ekryski** [comment]
@ramsestom yes it handles when a socket just disconnects as well.

**Comment by patrickpereira** [comment]
Any updated ETA on the update?

**Comment by marshallswain** [comment]
@patrickpereira Most of the refactoring is done.  We are rewriting tests.

**Comment by durden2** [comment]
When is the update coming? Is it going to be implemented at all?

**Comment by eddyystop** [comment]
Thanks for asking.

We are putting many hours into it. Permissions and a rewrite of the docs remain to be finalized.

**Comment by daffl** [comment]
You can already use it by installing `feathers-authentication@pre`. See the docs from [here](https://github.com/feathersjs/feathers-authentication/tree/master) and the [migration guide](https://github.com/feathersjs/feathers-authentication/blob/master/docs/migrating.md).

**Comment by issy123** [comment]
are the app.on('login' supposed to be used only for logging?

My usecase is more about check if user is disabled and disallow login?

I feel like the authentication login/register/forgot pass etc hooks are either not documented or do not exist?

**Comment by daffl** [comment]
It can also be used for marking a user as online (by `patch`ing them) or to [assign the real-time connection to channels](https://docs.feathersjs.com/api/channels.html).

If you need forgot password and similar functionality you can find one approach in the [feathers-authentication-management](https://github.com/feathers-plus/feathers-authentication-management) module.

**Comment by issy123** [comment]
Thank you sir I will check if the module suits my needs!

**Comment by issy123** [comment]
It does do kinda what i want but i want to do it in a different way e.g. storing reset & verify tokens in a seperate table.

Anyone else who's reading this might find this useful:
https://docs.feathersjs.com/faq/readme.html#how-do-i-create-custom-methods

It has a great example of how you could handle reset password.

i'm implementing my own register user/reset password application logic.
