### ISSUE TITLE
Chat for group and one-to-one.

### ISSUE THREAD

**Issue by soniaparikh** [feathersjs/feathers#339]
I am working on application in which I want to integrate chat module. I see the message service for feathers. I would like to make some changes like, I want to keep track of which message is sent by which user. Can I make changes to data base. I am using mySQL database. I also want functionally like one-to-one chat and group chat. Please let me know if feathers support this all features.

**Comment by ekryski** [comment]
@soniaparikh you can do all of that stuff but it doesn't come for free. You need to implement that ability. You might want to look at [the full working example](https://github.com/feathersjs/feathers-chat). It doesn't support 1-1 messaging or channels (yet) but it should be a good starting point.

**Comment by soniaparikh** [comment]
Thank you for reply. Can I make this chat as private? I mean if two users are communicating, the third person can not see their chat.

**Comment by ekryski** [comment]
Yup for sure.

**Comment by soniaparikh** [comment]
Thank you.
