### ISSUE TITLE
Error: require is not defined when running feathers-create

### ISSUE THREAD

**Issue by patamimbre** [feathersjs/feathers#3394]
### Steps to reproduce

Run `npm create feathers@latest feathers-chat` as described [in the docs](https://feathersjs.com/guides/basics/generator.html)

It is caused after fixing https://github.com/feathersjs/feathers/issues/3392

### Expected behavior

It should create a base project

### Actual behavior

It throws Error: require is not defined

### System configuration

**Module versions** (especially the part that's not working):
create-feathers@5.0.16

**NodeJS version**:
v21.5.0 (tried with node v20 too)

**Operating System**:
Macos Sonoma 14.2.1

**Comment by patamimbre** [comment]
@daffl - seems related to https://github.com/feathersjs/feathers/issues/3392

**Comment by daffl** [comment]
Thanks. I was expecting there to be problems, there's been a lot of pain with ES modules :| Reopening since it looks like it's still not fully working.

**Comment by daffl** [comment]
This should actually work now in v5.0.18.
