### ISSUE TITLE
Sub-app issue with different authentication configuration

### ISSUE THREAD

**Issue by mcchrish** [feathersjs/feathers#341]
I have 2 sub-apps with each of their own auth configs, like:
App1:

```
{
  "local": {
    "usernameField": "username",
    "password": "password"
  }
}
```

App2:

```
{
  "local": {
    "usernameField": "emailAddress",
    "password": "password"
  }
}
```

But it seems one is overwriting the other depending on the order of mounting to a main feathers app.

**Comment by ekryski** [comment]
@mcchrish any chance you can put together a quick gist or github repo replicating the issue? We haven't really tested auth with sub-apps but I'd like to be able to support it.

**Comment by mcchrish** [comment]
@ekryski here you go https://github.com/mcchrish/feathers-sub-app

Based on the feathers-cli generated app.
One app have a `usernameField: username`, the other is `usernameField: email`.
Only one of them will work depending on the order of require or import here:
https://github.com/mcchrish/feathers-sub-app/blob/master/src/index.js

**Comment by mcchrish** [comment]
Hey. I just want to ask if there's a chance this issue will be solve anytime soon. If not, I guess I'll have to refactor and split my project into two separate feathers servers for the time being.

**Comment by daffl** [comment]
We recently made a fix in https://github.com/feathersjs/feathers-socket-commons/pull/18 and https://github.com/feathersjs/feathers-socketio/pull/27 so make sure you have the latest versions installed. It may fix it but we have not tested it yet. For v1 we will definitely make sure this configuration works but that might be another month or two.

**Comment by daffl** [comment]
This has been addressed in Feathers v4 which allows to register and connect to multiple authentication services. See the [Migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information on how to upgrade.
