### ISSUE TITLE
Schema resolving to unknown or any with queryProperty

### ISSUE THREAD

**Issue by desudo** [feathersjs/feathers#3413]
The schema is resolving into type unknown or any when using queryProperty from `@feathers/schema`. 
`mytest` would resolve in the structure I intend to have, `Schema` does not.

```
import { FromSchema, queryProperty } from '@feathersjs/schema';

const detailsQueryProperty = {
  // eslint-disable-next-line no-useless-escape
  '^(details.[1-9][0-9]{0,2})$': {
    ...queryProperty({ type: 'string' }),
  },
} as const;

const schema = {
  type: 'object',
  patternProperties: {
    ...detailsQueryProperty,
  },
} as const;

const myschema = {
  type: 'object',
  patternProperties: {
    '^(details.[1-9][0-9]{0,2})$': {
      anyOf: [
        { type: 'string' },
        {
          type: 'object',
          additionalProperties: false,
          properties: {
            $gt: { type: 'string' },
            $gte: { type: 'string' },
            $lt: { type: 'string' },
            $lte: { type: 'string' },
            $ne: { type: 'string' },
            $in: { type: 'array', items: { type: 'string' } },
            $nin: { type: 'array', items: { type: 'string' } },
          },
        },
      ],
    },
  },
} as const;

type mytest = FromSchema<typeof myschema>;

type Schema = FromSchema<typeof schema>;

```

I also have a working example, on Stackblitz: [Example](https://typescript-zwkeai.stackblitz.io)

**Additional Information:**

NodeJs: v16.20.2
npm: v8.19.4
TypeScript: v5.3.3
@feathers/schema: 5.0.14

Thanks for any help!

**Comment by daffl** [comment]
Pattern matching for keys like the above is not possible in TypeScript which is why it can't resolve to a known type.

**Comment by desudo** [comment]
Yes, that is correct. 
Even if I use a genuine property, `queryProperty` still does not resolve as you can see in the screenshot.

![Screenshot 2024-01-30 at 09 47 05](https://github.com/feathersjs/feathers/assets/7853069/3d951d04-462d-4eb8-bcde-1e3bdbd67ef5)

When using `queryProperty` by itself, it does work out just fine:

![Screenshot 2024-01-30 at 09 45 48](https://github.com/feathersjs/feathers/assets/7853069/2f149ec5-b938-4ac9-aac1-355ad46a8e40)

I'm sorry if my initial example confused you.

**Comment by daffl** [comment]
Looks like it's one of the odd and mysterious TypeScript quirks. This appears to work:

```ts
import { JSONSchema } from 'json-schema-to-ts'
import { PropertyQuery, schema, Infer } from '@feathersjs/schema'

const queryPropertyWrapper = <T extends JSONSchema>(schema: T) => schema as PropertyQuery<T, unknown>

const testSchema = schema({
  $id: 'something',
  type: 'object',
  properties: {
    name: queryPropertyWrapper({ type: 'string' })
  }
} as const)

type Test = Infer<typeof testSchema>
```

**Comment by desudo** [comment]
This helped quite a lot. Thank you for your patience and time :)
