### ISSUE TITLE
Allow for asynchronous service initialization

### ISSUE THREAD

**Issue by joshuajabbour** [feathersjs/feathers#342]
This might be a task for the [generator](https://github.com/feathersjs/generator-feathers), but right now it's not possible to have asynchronous service initialization without constructing your own method of loading.

The generator currently just loads in all services, assuming they are synchronous (or not caring). This can present problems like the app listening for requests before the service has been able to connect to the database. Therefore, causing requests to fail.

In solving this, I reworked my app init to support promises, but it required using promises all the way down into the individual service configuration (I use a similar layout to the generator). This could be updated in the generator code, but a better way might be to make `use` and `configure` handle promises transparently if they are passed. This might allow for better backwards compatibility, more flexibility, and less boilerplate.

**Comment by daffl** [comment]
We kind of cheated by not including the databases that require asynchronous initialization in the generator and we should definitely include the ability to do so in the next release.

I'm not sure if it is possible to implement and stay backwards compatible (`app.listen` would return a promise instead of the server instance I assume).

**Comment by joshuajabbour** [comment]
Yeah, I don't think it'd be possible to make it completely backwards compatible, so maybe a generator change would be the first step. That said, having the base Feathers functions understand promises would be a huge boon, so it should be considered at some point.

**Comment by daffl** [comment]
In order to address this issue we created the [feathers-bootstrap](https://github.com/feathersjs/feathers-bootstrap) plugin. It allows to configure your application with JSON files and to set asynchronous configuration values (via [json-di](https://github.com/daffl/json-di)).
