### ISSUE TITLE
Node Webkit (nwjs) support

### ISSUE THREAD

**Issue by kk86bioinfo** [feathersjs/feathers#343]
I know feathersjs can work in browser, but do it work well with nwjs? 
[http://nwjs.io](http://nwjs.io)

**Comment by daffl** [comment]
Since the environment is much less restrictive than React Native and Feathers works there as well there is no reason it wouldn't. [MySam](https://github.com/mysamai/mysam) is using it both on the server and the client with Electron.

**Comment by kk86bioinfo** [comment]
Interesting with MySam, I would give it a try with nwjs using featherjs.

**Comment by daffl** [comment]
Cool. I quickly tried it with NW and didn't notice any problem so I'm going to close this issue. Please reopen if you run into any problems that seem nw.js related.
