### ISSUE TITLE
Set status code and header for response

### ISSUE THREAD

**Issue by kozzztya** [feathersjs/feathers#344]
Hi! How I can set custom headers and status 200 for some POST requests? Can I did it in hooks?

**Comment by daffl** [comment]
You can use a [custom middleware](http://docs.feathersjs.com/middleware/express.html#custom-service-middleware) after the service and in it set the status code:

```js
function setStatusCode(req, res, next) {
  // res.data: data returned from the service
  if(req.method === 'POST') {
    res.status(200);
  }

  next();
}

app.use('/myservice', myService, setStatusCode);
```

**Comment by kozzztya** [comment]
Thanks, that works!
