### ISSUE TITLE
options method

### ISSUE THREAD

**Issue by rickmed** [feathersjs/feathers#345]
hello, just started learning about feathers...
I see an app.options method in the getting started exampled, but can't find it in the api docs, what is it?

off topic: no gitter channel?

thanks!

**Comment by daffl** [comment]
[The core API documentation](http://docs.feathersjs.com/api/readme.html) briefly mentions that any `app` API that isn't documented can be found in the [Express 4 documentation](http://expressjs.com/en/4x/api.html). `app.options` is one of [app.METHOD](http://expressjs.com/en/4x/api.html#app.METHOD) methods.

If you want to chat you are welcome to [join our Slack channel](http://slack.feathersjs.com/). We used to have that Gitter and IRC but didn't want to fragment across ten different chat services.

**Comment by rickmed** [comment]
@daffl yes! (passed over app.METHOD methods section)

joined the chat!
thanks!
