### ISSUE TITLE
Generated package.json is missing a `migrate:make` script

### ISSUE THREAD

**Issue by silvestreh** [feathersjs/feathers#3461]
### Steps to reproduce

1. Generate an app through `npm create`
2. Pick TypeScript, Koa, TypeBox, and SQLite when prompted
3. Open `package.json` and look for the `scripts` key
4. `migrate:make` is defined as an empty string.

### Expected behavior

I would expect `scripts['migrate:make']` to contain a command, like `knex migrate:make -x mjs`, to create a migration file.

### Actual behavior

`scripts['migrate:make']` is an empty string

**Comment by silvestreh** [comment]
Same happens when selecting PostgreSQL instead of SQLite.

**Comment by ShadowOfThePenguin** [comment]
same

**Comment by jascholle** [comment]
The github repo has it as  `"migrate:make": "knex migrate:make"`
https://github.com/feathersjs/feathers-chat/blob/c7a7cf7fd99d6591dad372d11e04d3d574518492/feathers-chat-ts/package.json#L46C5-L46C40
