### ISSUE TITLE
Elasticsearch adapter

### ISSUE THREAD

**Issue by kethan** [feathersjs/feathers#347]
Would it be great to integrate this?

**Comment by marshallswain** [comment]
@kethan do you have any experience with it?  Nobody has built an adapter for it, yet.

**Comment by kethan** [comment]
no i dont have too would it be more powerful to implement ... similar to what https://www.algolia.com/ using elasticsearch (https://www.npmjs.com/package/elasticsearch)

**Comment by ekryski** [comment]
I think someone was doing some stuff with solr. It would probably be similar. Would be awesome to have if someone was willing to pick this up. Core team is likely too busy to tackle this any time soon.

**Comment by daffl** [comment]
I don't think the core team will take this on any time soon. Let's keep this issue open for another month to see if anybody is interested in helping out.

**Comment by daffl** [comment]
Thanks again for the suggestion! I'm going to close this since it does not look like it will be taken on soon. If anybody is interesting in starting an adapter we'll do everything we can to help of course.
