### ISSUE TITLE
How can I debug a feathersjs application with npm start command?

### ISSUE THREAD

**Issue by UlyssesAlves** [feathersjs/feathers#349]
As far as I know, feathersjs applications are (or can be) started by running **npm start** at the root folder of the application. 

I need a way to debug my application so that it is run the same way as when it's run by npm start. Something like "node-debug npm start" (of course I know this doesn't work, it's just an example of what I'm trying to accomplish).

Some tips on how to debug feathersjs applications with Visual Studio Code would be much appreciated also. Thanks.

**Comment by daffl** [comment]
I you look at the `start` script in `package.json` all it does is run `node src/` so you can just add a `debug` script with `node-debug src/` and then run it with `npm run debug`.

If you want, it would be great if you could add a section for that in http://docs.feathersjs.com/debugging/readme.html.
