### ISSUE TITLE
How to implement file uploads

### ISSUE THREAD

**Issue by borkowsky** [feathersjs/feathers#3493]
Hello. I want to create file uploading service, I'm new in koa version. The documentation site shows a method for an older version of the framework. I use "@feathersjs/koa": "^5.0.24"

**Comment by eXigentCoder** [comment]
@borkowsky did you get this working with V5 (Dove)?

**Comment by borkowsky** [comment]
> @borkowsky did you get this working with V5 (Dove)?

Yes, I did it
