### ISSUE TITLE
feathersjs.com Discord Link Is Invalid

### ISSUE THREAD

**Issue by jwd-dev** [feathersjs/feathers#3500]
As seen at if you press the discord icon: https://feathersjs.com/api/authentication/service.html

The invalid link: https://discord.com/invite/qa8kez8QBx

**Comment by daffl** [comment]
What does it show for you? I just tried it on several devices and browser and it appears to be working as expected.

**Comment by jwd-dev** [comment]
Odd, it was showing that the invite was invalid. It's working now as well.
