### ISSUE TITLE
Usage docs generic models

### ISSUE THREAD

**Issue by kokujin** [feathersjs/feathers#351]
Can someone point me to the usage docs of generic models? Or just models? Thanks

**Comment by marshallswain** [comment]
There is no built-in model.  The service API is used in a few places as a wrapper around other ORMs with models, like Mongoose, Knex and Sequelize.  We do have a custom definitions & validations syntax that we're working on, but it will not add ORM-like model behavior to services.  If you need an ORM-style model, please use one of the mentioned adapters.

**Comment by kokujin** [comment]
I come from sails, so I'm familiar with Waterline models, I have tried out Mongoose too.. The feathers generator allows the scaffolding of a generic type model though:

``````
feathers generate model
``````

And then subsequently ask to choose a type (Generic, Mongoose or sequelize) and then which service it should be paired to. So, out of curiosity, how are the generic models used?

**Comment by marshallswain** [comment]
Similar to how you can generate a generic service that is just a basic object literal with the service methods as keys, you can generate a generic model. Both options are for you to be able to easily do something custom.  You can see the options for modles here, as well as the code each generates: https://github.com/feathersjs/generator-feathers/tree/master/generators/model/templates

**Comment by marshallswain** [comment]
But again, these models are for services that are designed to use an ORM.

**Comment by ekryski** [comment]
Yeah. Typically you don't need models if you aren't using an ORM, or if you do it's simply a JSON schema or an object literal that defines the properties you expect for that resource.

**Comment by kokujin** [comment]
So it just generates a basic model that needs to be modified for the ORM in question. Got it. Thanks
