### ISSUE TITLE
How to change a user's password?

### ISSUE THREAD

**Issue by UlyssesAlves** [feathersjs/feathers#352]
I changed a user's password with the update method of the "users" service, but I think this is not the right way to change passwords, because the password was not automatically encrypted the same way as it is when the user are first created.

```
var userService = app.service("users");

userService.update(userId, 
	        			{ 
	        				$set: {
	        					password: "newpassword"
	        				} 
	        			}
	        		)
	        		.then(updatedUser => {
                                        // this will print "newpassword", instead of something like this: $2a$10$VAu.u509vo7YAffGeyLrUu0zqi.COdGHSKOqo/V9aHBYWsMekiAUS
	        			console.log(updatedUser.password);
	        		})
```

I searched the source code but I didn't find where is the password being encrypted when the user is created. How can I update the password field and keep it in the same pattern as the passwords are stored when the user is created?

**Comment by daffl** [comment]
Add the [auth.hashPassword](http://docs.feathersjs.com/authorization/bundled-hooks.html#hashpassword) hook and use `patch` instead of `update` with `$set`:

```js
app.service('users').before({
  patch: auth.hasPassword()
});
```

**Comment by UlyssesAlves** [comment]
Thanks for the fast support!

How does patch knows it is supposed to change the password field, since in your example you didn't pass the name of the field to be "patched"?

**Comment by UlyssesAlves** [comment]
Do you mean something like this?

`userService.patch(userId, {password: newPassword});`

**Comment by UlyssesAlves** [comment]
Yes, it did work. Thank you very much.
