### ISSUE TITLE
Error: strict mode: unknown keyword: "instanceOf" with Type.Date() and Postgres

### ISSUE THREAD

**Issue by Spioune** [feathersjs/feathers#3524]
Hi,

I am trying to use FeathersJS with Postgres.
My goal is to get feathers.js to work with postgres timestamptz.
I want feathers.js to return postgres timestamptz columns as javascript date objects.

### Steps to reproduce

In Postgres I have a histo table with a column created_at of type "timestamptz".
In FeathersJS I have the following schema:

```js
export const histoSchema = Type.Object({
  created_at: Type.Date()
},
{ $id: 'Histo', additionalProperties: false })
```

When I try to get every items with `app.service('histo').find()` I get the following error:

<img width="851" alt="image" src="https://github.com/user-attachments/assets/ef52182a-3cc8-4f61-87d7-16a449f84da2">

If I replace `created_at: Type.Date()` with `date: Type.String()` I don't get the error. But I get a string "2024-08-12T17:10:25.172Z" instead of a date.

### Expected behavior

I expect `app.service('histo').find()` to return a list of objects with created_at columns typed as a javascript date object.

### System configuration

**Module versions** (especially the part that's not working):
"@feathersjs/typebox": "^5.0.29"
"@feathersjs/schema": "^5.0.29"
"@feathersjs/feathers": "^5.0.29"

**NodeJS version**: Node.js v20.8.1

**Operating System**: MacOS Sonoma 14.1 (23B74)

**Browser Version**: Google Chrome Version 127.0.6533.100 (Official Build) (arm64)

**Comment by Spioune** [comment]
Looking at the [documentation](https://feathersjs.com/api/schema/typebox#extended) I found out I can extend AJV to validate "Date" objects.
But doing so still returns strings instead of Date objects when I call .get() or .find() so it seems it is better to use Type.String({format:'date-time'})

Do I really need to manually write "new Date(created_at)" everywhere in my frontend ?
Or do I really need to write custom hooks to do "new Date(date_column)" everywhere I have a date column? :sad:

**Comment by AshotN** [comment]
This doesn't have much to do with AJV, if you are using `pg` for postgres you need to instruct it not to convert Date objects from the database to a string

```
  // Prevent node-postgres from converting Postgres DATE type
  PG.types.setTypeParser(1082, function (value) {
    return value
  })

```
