### ISSUE TITLE
Handling validation errors in a service

### ISSUE THREAD

**Issue by kokujin** [feathersjs/feathers#353]
What is the preferred way to handle validation errors thrown by a service? I have a unique constraint on a NeDB collection. I get this result from the service after a failed "Create/ Post"

`````
{
  "name": "GeneralError",
  "message": "Can't insert key 12345, it violates the unique constraint",
  "code": 500,
  "className": "general-error",
  "data": {},
  "errors": {}
}

``````

I have tried using hooks, but I noticed that "after" hooks are not being called when this error occurs, and a  before hook doe not hold errors. How can I add validation error handlers in my services? Thanks

**Comment by kokujin** [comment]
I just noticed that I could write middleware to handle this as in:

`````
return function (error, req, res, next) {
       if(error.errorType === 'uniqueViolated'){
                winston.error(message);
            }
.....
````

**Comment by daffl** [comment]
I am planning on adding error hook processing. For now you could [extend the service](http://docs.feathersjs.com/databases/extending.html#classes-es6) and re-throw your own errors:

```js
class MyService extends Service {
  create(data, params) {
    return super.create(data, params).catch(error => {
      throw new convertToOtherError(error);
    });
  }
}
```

**Comment by ekryski** [comment]
We've also added documentation on how you can wrap existing hooks to catch errors and convert them to something else. http://docs.feathersjs.com/hooks/usage.html#customizing-built-in-hooks
