### ISSUE TITLE
@feathersjs/authentication-jwt depend on a vulnerable lodash version

### ISSUE THREAD

**Issue by ayoubmehd** [feathersjs/feathers#3542]
@feathersjs/authentication-jwt depend on a vulnerable lodash version https://github.com/advisories/GHSA-p6mc-m468-83gw

### Npm audit report

| High          | Prototype Pollution in lodash                     |
| ------------- | ------------------------------------------------- |
| Package       | lodash.pick                                       |
| Patched in    | No patch available                                |
| Dependency of | @feathersjs/authentication-jwt                    |
| Path          | @feathersjs/authentication-jwt > lodash.pick      |
| More info     | https://github.com/advisories/GHSA-p6mc-m468-83gw |

### Expected behavior

A new patch with upgraded lodash

### Actual behavior

Latest patch 2.0.10 still show the same report after rerunning npm audit

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working): @feathersjs/authentication-jwt@2.0.10

**NodeJS version**: node v16.17.1

**Operating System**: 

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by daffl** [comment]
This is a module from a 6 year old version of Feathers that is no longer maintained. You should upgrade to a new version which has JWT authentication build into the `@feathersjs/authentication` package.
