### ISSUE TITLE
Can't connect to a service called 'engineType'

### ISSUE THREAD

**Issue by jeremyjs** [feathersjs/feathers#355]
I created a new service called `engineType`, but I couldn't get any data from feathers-client. I renamed it `engine` and now it works fine. There must be a namespace conflict somewhere; I'll leave it to others to verify, but be warned. If this is the case, we should have a warning that you can't register a service called `engineType`.

**Comment by daffl** [comment]
Thank you for reporting. Currently the generator pluralizes service names so the actual name is `engineTypes`. It looks like everything works as expected using `app.service('engineTypes')`. The next version of the generator will remove pluralization which is tracked in https://github.com/feathersjs/generator-feathers/issues/44 so I'm closing this as a duplicate.
