### ISSUE TITLE
Cannot read property 'on' of undefined - React Native

### ISSUE THREAD

**Issue by mcchrish** [feathersjs/feathers#356]
```js
messagesService.create({})
  .catch(error => {
    // Error: Cannot read property 'on' of undefined(…)
    console.log(error)
  })
```
Can be replicated here:
https://github.com/mcchrish/react-native-feathers-error
Run iOS `react-native run-ios`
You can use this server to test: https://github.com/mcchrish/feathers-fetch-error

**Comment by daffl** [comment]
I don't have RN set up but maybe @ekryski can double check. It looks like it should work. Is there a reason you are using REST fetch instead of websockets (I guess it makes sense if you don't want your app to be real-time)?

**Comment by mcchrish** [comment]
For our current needs, we think websocket is a "nice-to-have" feature so we purposely opt-out for now.
For what it's worth, I also tried websocket but gives a different error:
https://github.com/mcchrish/react-native-feathers-error/tree/websocket
`Timeout of 5000ms exceeding calling messages::create`.

**Comment by daffl** [comment]
Do you have the full stack trace of the error? I can't think of anywhere Feathers would call `.on` if websockets are not configured. The timeout with websockets usually happens when the service or the service method does not exist can you verify it does?

**Comment by mcchrish** [comment]
Not sure if this stack trace would be useful (this the REST only):
```
Error: Cannot read property 'on' of undefined
    at convert (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&hot=true:72297:70)
    at toError (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&hot=true:71400:34)
    at tryCallOne (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&hot=true:14592:8)
    at http://localhost:8081/index.ios.bundle?platform=ios&dev=true&hot=true:14678:9
    at JSTimersExecution.callbacks.(anonymous function) (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&hot=true:12220:13)
    at Object.callTimer (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&hot=true:11816:1)
    at Object.callImmediatesPass (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&hot=true:11874:19)
    at Object.callImmediates (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&hot=true:11889:25)
    at http://localhost:8081/index.ios.bundle?platform=ios&dev=true&hot=true:11148:43
    at guard (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&hot=true:11062:1)
```
Only thing I noticed is that the `error` object of the catch promise is undefined.

Sorry I take it back. The websocket actually worked! I had any issue with the chrome debugger and just restarted the application. It only longer timeout and gives the appropriate error object.

**Comment by mcchrish** [comment]
I was able to replicate the issue on the example react-native chat app by changing socket.io to rest.

**Comment by daffl** [comment]
From the error `Provider 'rest' can not call 'create'` it seems like you disabled calling `create` for at least the REST provider using the [disable hook](http://docs.feathersjs.com/hooks/bundled.html#disable).

**Comment by mcchrish** [comment]
Yes, that's on purpose to simulate the error scenario. But it should be the same on any error e.g. `NotAuthenticated` or `BadRequest`. As long as it's in the `catch` chain.

**Comment by daffl** [comment]
I think I fixed this yesterday via https://github.com/feathersjs/feathers-rest/pull/63.
