### ISSUE TITLE
Custom Events

### ISSUE THREAD

**Issue by clintberry** [feathersjs/feathers#36]
It would be nice to have a way to send custom events to websocket clients. Is there an easy way to tap into the event system for that?

**Comment by chikamichi** [comment]
Hi,

To readers who may be lurking around: the link above is "dead" (the example has changed and does not make use of the feature anymore), but extended documentation is available in [the API section about the socket](http://feathersjs.com/api/#toc3).

**Comment by daffl** [comment]
Thank you! I edited the comment with the correct link as well.
