### ISSUE TITLE
Service method `get` ignores params

### ISSUE THREAD

**Issue by kozzztya** [feathersjs/feathers#361]
I use this url `/alerts/559305289550112f53f54bb0?message=some` without any success. 
It gives me alert by id but ignore params.

**Comment by daffl** [comment]
`{ message: 'some' }` will be in `params.query` of the service call. So

```js
app.use('/alerts', {
  get(id, params) {
    return Promise.resolve({ id, params.query });
  }
});
```

For your example should return:

```js
{
  "id": "559305289550112f53f54bb0",
  "message": "some"
}
```

**Comment by kozzztya** [comment]
Thanks. But I thought that it works out of the box.

**Comment by kozzztya** [comment]
In documentation method `get` params but for mongoose service it does nothing. That confuses. Also I migrated from loopback and there params for single instance worked.

**Comment by daffl** [comment]
What is that supposed to do? By default `get` just returns a record by its id, adding a query wouldn't really change anything about that. If you want to find a record by two parameters you can use `/alerts?id= 559305289550112f53f54bb0&message=some`. It is possible to add this behaviour to the `get` method with your own [hook](http://docs.feathersjs.com/hooks/readme.html):

```js
app.service('alerts').before({
  get(hook) {
    const query = Object.assign({
      id: hook.id
    }, hook.params.query);

    return app.service('alerts').find({ query }).then(alerts => {
      if(alerts.length === 1) {
        hook.result = alerts[0];
        return hook;
      }
    });
  }
});
```

**Comment by kozzztya** [comment]
Thanks for detailed answer.
