### ISSUE TITLE
Unsubscribing to a service subscription is not available (client)

### ISSUE THREAD

**Issue by tkornblit** [feathersjs/feathers#362]
Hey guys,

When using the 'on' handler for a Feathers service, there's no way to unsubscribe using the Feathers service API.

My particular use case is in React:

`
componentDidMount(props) {
this.userService = userService.on('updated', (newUser) => { // Some code here };`
}
`

I'd like to basically do:

`
componentWillUnmount() {
 this.userService.unsubscribe("updated")
}`

And currently I don't believe thats supported. Any help here would be appreciated.

Thanks.

-Tom

**Comment by daffl** [comment]
All services are an [EventEmitter](https://nodejs.org/dist/latest-v6.x/docs/api/events.html#events_class_eventemitter). Unsubscribing can be done using [removeListener](https://nodejs.org/dist/latest-v6.x/docs/api/events.html#events_emitter_removelistener_eventname_listener) or [removeAllListeners](https://nodejs.org/dist/latest-v6.x/docs/api/events.html#events_emitter_removealllisteners_eventname):

```
componentWillUnmount() {
  this.userService.removeListener("updated", this.updateListener);
}

componentWillUnmount() {
  this.userService.removeAllListeners("updated");
}
```

**Comment by tkornblit** [comment]
Thank you for the quick response.

I'm just finishing some hardcore sprinting on a project in chatbots.

As soon as I'm done with this sprint I'd love to help you with feathers.

I think you're doing an awesome job.

Let me know how I can help.

-Tom

**Comment by tkornblit** [comment]
Btw - just checked and it seems that the user service does not have either of those methods…

This is using feathers on the client btw.

Any ideas?
--
Tom Kornblit

**Comment by daffl** [comment]
Ah yes, sorry, it's `off` instead of `removeEventListener` for the socket client. I created a follow-up issue in https://github.com/feathersjs/feathers-socket-commons/issues/22.

And thank you! We'd definitely appreciate any help we can get 😄

**Comment by daffl** [comment]
I made a fix in https://github.com/feathersjs/feathers-socket-commons/pull/23 that should now enable all available EventEmitter methods (including `off`).
