### ISSUE TITLE
Feathers filter socket to channel

### ISSUE THREAD

**Issue by indie314** [feathersjs/feathers#363]
Hello,

I'm building a chat app using `react-native` and `feathers.js`.

My app is structured something like this

> auth -> channel -> messages

So I have a service for messages, what I'm trying to achieve is to use `/messages/:channel_id` and get all the messages which have the `message.channel === params.channel_id` and on the client side `message.on('created', data => { // console log if the message created is in the current channel }` (I can do this whith if(data.channel === currentChannelId) but feels dirty, I would like to do this on the server side).

I tried to use something like this on the server side `app.use('/messages/:channelId')` and on the client `var messages = app.service('messages/currentChannelId')` but dosent seems to work (request timeout)

My message service:

```
'use strict';

const service = require('feathers-mongoose');
const messages = require('./messages-model');
const filters = require('../../filters');
const hooks = require('./hooks');

module.exports = function() {
    const app = this;

    const options = {
        Model: messages
    };

    // Initialize our service with any options it requires
    app.use('/messages', service(options));

    // Get our initialize service to that we can bind hooks
    const messagesService = app.service('/messages');

    // Setup up filter
    messagesService.filter(filters.restrictToAuthenticated);

    // Set up our before hooks
    messagesService.before(hooks.before);

    // Set up our after hooks
    messagesService.after(hooks.after);
};

```

I'm doing something wrong?
Would be nice to see an complex of feathers where services communicate.

Much love for feathers team 👏

**Comment by marshallswain** [comment]
By default, any route like `message/1` will try to get the message with id of 1, but you want to modify it.  You could use a hook for this. Something along these lines.

```js
function(hook){
  // Get the channel id and use it to modify the query params.
  hook.params.query.channelId = hook.id;

  return new Promise((resolve, reject) => {
    hook.app.service('messages').find({query: hook.params.query})
    .then(response => {
      // Set hook.result so the normal `get` operation doesn't happen.
      hook.result = response;
      resolve(hook);
    });
  });
}
```

The downside of this API is that you won't be able to query a message by id.  I would recommend using the normal endpoint for `/messages` and use find to query all messages where {channelId: currentChannelId}

**Comment by indie314** [comment]
Hey @marshallswain, thanks for your quick answer.

Will your hook prevent firing events on messages that are not in the current channel?

`messages.on('created', function() { // do something })` - I dont want this to fire if someone else post messages in other channel.


Thanks!

**Comment by marshallswain** [comment]
No. You would use an event filter for that, separately. Check out the
filtering section in the docs.

**Comment by indie314** [comment]
Thanks, I used filter before BUT how can I send my channel id to the filter, thats the thing I dont know...

**Comment by marshallswain** [comment]
Hook data is available in the filter.  Check out the final examples here: http://docs.feathersjs.com/real-time/filtering.html <http://docs.feathersjs.com/real-time/filtering.html>

**Comment by indie314** [comment]
I know but how can I add the channelId into hook.data, its not there by default.

**Comment by marshallswain** [comment]
You can add properties to hook.params

**Comment by indie314** [comment]
So, not sure if I'm right but in order to make the filter work I need to have the current channel id inside the connection object in my filter so I can compare the hook.data.channel from the message to connection, right?

How can I add the current id to my connection object?

**Comment by daffl** [comment]
Your issue is related to https://github.com/feathersjs/feathers/issues/304 but there also is more information how to do rooms in https://github.com/feathersjs/feathers-socketio/issues/32#issuecomment-230640717. Basically you want to add rooms to a socket either by adding it to the user object or creating a custom `join` event which will add the channel to the socket.

**Comment by daffl** [comment]
I added it to the FAQ at http://docs.feathersjs.com/help/faq.html#how-do-i-create-channels-or-rooms

**Comment by indie314** [comment]
Thanks @daffl, 

I think I follow now, in case I want to use the socket.io join event, In the client I should do something like:

`app.io.emit('join', currentId);`

I am right?

Btw, I think this should be 2.
> 1. Create a custom join event with a room id and then filter based on it

**Comment by daffl** [comment]
Exactly. 1. is better if you want to e.g. keep track of all users in the channel and display them as online/offline (you can do that with 2. as well if you update the user when the sent the `join` event).

**Comment by indie314** [comment]
@daffl, @marshallswain thanks guys for your help.

you can close this!

**Comment by indie314** [comment]
just notice, if I create a room, and then join to the room I cant recive the messages, because in connection.user the rooms are not updated, because connection.user is the token decoded, right?

Its there a way which I can refresh the token?

**Comment by daffl** [comment]
Unless you changed it only the user id is encoded in the token. The problem is that in the current authentication the user is not listening to real-time event once the connection is established. This will be added in the next release. The workaround for now is to probably `.get` the user with `connection.feathers.token` as the id every time.

**Comment by indie314** [comment]
@daffl thanks man, when the next version will be released?

**Comment by alterx** [comment]
Hey @daffl , is this still doable in the new version? https://legacy.docs.feathersjs.com/help/faq.html#how-do-i-create-channels-or-rooms

I haven't been able to get the `rooms` field to show up in the `connection.user` object. It only shows password, id, and email even though I've added the `rooms` field to the model and event added it to the JWT token.

Any ideas?

**Comment by daffl** [comment]
It should. @ekryski any ideas if/why that might've changed?
