### ISSUE TITLE
How to separate `multer` middleware out of GET request

### ISSUE THREAD

**Issue by supasate** [feathersjs/feathers#364]
I'm going to make some APIs for my photo service. 
1) GET /photos 
- to retrieve photos

2) POST /photos
- to upload a photo

I read from [this](http://docs.feathersjs.com/guides/file-uploading.html) that we can use `multer` as a middleware to handle multipart file uploading like the following.

``` javascript
...
class PhotosService {
  get(id, params) {}
  create(params) {}
  ...
}

module.exports = function() {
  const app = this
  app.use('/photos', 
    multer().single('uri'),
    function(req, res, next) {
      req.feathers.file = req.file;
      next();
    },
    new PhotosService()
  )
}
```

However, if I understand correctly, the `multer` middleware is triggered even we request with GET /photos which it doesn't need to upload a file.

What is the right (or recommended) way to separate `multer` out of the lookup APIs (like `get` and `find`)?

**Comment by daffl** [comment]
You can wrap it into your own middleware that checks for the request methods:

```js
const multer = multer().single('uri')

app.use('/photos', 
  function(req, res, next) {
    if(req.method.toLowerCase() === 'post') {
      return multer(req, res, next);
    }

    next();
  },
  function(req, res, next) {
    req.feathers.file = req.file;
    next();
  },
  new PhotosService()
)
```

**Comment by supasate** [comment]
Thank you very much for your extremely fast response @daffl. I really appreciate your help.
