### ISSUE TITLE
How can a method in a generic service determine what provider its invocation came in on?

### ISSUE THREAD

**Issue by eddyystop** [feathersjs/feathers#365]
My case: Some browser SPA clients use feathers-sockerio, others use feathers-rest. There is a generic (i.e. non DB) service on the server which emails URLs to reset forgotten passwords, etc.

These URLs cause the server to deliver HTML which loads the SPA. The SPA handles the request after looking at the routing info.

I need to send slightly different URLs for socketio and rest SPAs so as to reload the same flavor of SPA are initiated the original request.

Is there a way for the service method to determine what provider caused it to be invoked?

Thanks ahead of time.

**Comment by daffl** [comment]
In the service call `params.provider` will be set to either `socketio` or `rest` (or nothing if used internally).

**Comment by ekryski** [comment]
Closing.
