### ISSUE TITLE
Test with Tape

### ISSUE THREAD

**Issue by andresgallego** [feathersjs/feathers#366]
Can I use tape instead of mocha? if so, what should be the change in my package.json file please?

**Comment by ekryski** [comment]
Of course you can! 😄  You might need to tweak the generated tests as I'm not familiar with Tape but you just need to change the dev dependencies and the `test` field in the `package.json` for how you would run Tape tests from the command line. You can probably google how to do that.

**Comment by daffl** [comment]
Just like with the generated Mocha tests you can require the application and run your tests with tape. A simple test can look like this:

```js
const test = require('tape');
const app = require('../src/app');

test('todo service creates a todo', function (t) {
  t.plan(2);
  app.listen(3030).on('listening', () => {
    const service = app.service('todos');
    service.create({ text: 'I have to do dishes' }).then(todo => {
      t.ok(todo._id);
      t.equal(todo.text, 'I have to do dishes');
    });
  });
});
```

You have to remove the `mocha` script in the `package.json` and update the `test` script and add a `tape` npm script:

```
"scripts": {
  "test": "npm run jshint && npm run tape",
  "tape": "node path/to/tests.js"
```
