### ISSUE TITLE
One time use hooks, or ability to remove hooks

### ISSUE THREAD

**Issue by jayalfredprufrock** [feathersjs/feathers#371]
I'm curious to know if there is a way to add/remove a hook on a service call temporarily (i.e. when retrieving the service), or perhaps remove a hook after it has been added. I'm not familiar enough with the feathers' architecture to know the implications of allowing such behavior, but in my case it would be super useful and allow the reuse some services internally instead of re-registering a duplicate service with a different hook configuration. Hopefully I'm making sense...

**Comment by marshallswain** [comment]
I don't think it's supported.  Couldn't you just run the hook conditionally?

**Comment by jayalfredprufrock** [comment]
You're totally right, it looks like conditional hooks via the callback parameter could work well for my case. I totally overlooked that all the service methods can take that parameter. Thanks for your help, I'll close this

**Comment by daffl** [comment]
You could also splice the callback out of `service.__beforeHooks` and `service.__afterHooks` but I'd also recommend running it conditionally (unless you register a large number of one-time hooks since it'd create a memory leak).

**Comment by jayalfredprufrock** [comment]
I thought about modifying __beforeHooks and __afterHooks directly, but it seemed dangerous seeing as I'm new to feathers. The problem with conditional hooks is that the condition is shared between all registered hooks on the service which makes it difficult to turn on/off one hook without affecting any other conditional hooks. Honestly I don't envision a whole lot of one time hooks, let alone combining them in a single service, so that's probably a non-issue. 

I read somewhere that the conditional hook approach was being deprecated. Should I expect the callback parameter to the service methods to disappear at some point?

**Comment by ekryski** [comment]
@jayalfredprufrock at some point in the future yes the plan is to deprecate callbacks for services and just return promises or move to `async` `await`. Conditional hooks are definitely the way to go I think.

I'm curious... what's the use case?

**Comment by jayalfredprufrock** [comment]
The use case that started all this was a hook I wrote called "findExactlyOne" which can only be applied as an "after" hook for the "find" method. It basically returns undefined if 0 or > 1 results are returned, else it returns the single unwrapped array value, additionally accounting for services with pagination enabled. Since this changes the type of value the "find" method returns, I wanted to make sure I could explicitly turn on this functionality when using services with that hook added. Extending the service API to include a method like "findExactlyOne" is probably the most elegant solution, however sometimes I make things more challenging for myself when learning a new framework.

I have other theoretical use cases that I have yet to implement that deal with temporarily disabling certain authentication requirements, however I think it's likely I could come up with a more complicated hook to accomplish the same thing. Still, being able to enable/disable a hook at service call time seems to, at first glance, encourage simpler hooks with less side effects, and when you want to veer from the standard service behavior, the side effect is not tucked away in a hook somewhere, but rather right there. 

Anyways, I wouldn't be surprised if my opinion on all of this completely changes in the future, but if anybody else is interested, here is a little code I whipped up:

```
const checkCondition = (name, hook, type) => {

    //check to make sure we have the expected parameters
    if (typeof name != 'string' || typeof hook != 'object') {

        throw new Error('Improper use of conditional hook!');
    }

    const defaultReturn = type != 'enable';

    //callbacks should be a function that returns an object or promise
    //first, lets get the initial function result
    let callbackResult = hook.callback(hook);

    //at this point we should definitely have an object
    //if not, bail with default
    if (typeof callbackResult != 'object') {

        return defaultReturn;
    }

    //we break the result checking into a function to handle the promise case
    const checkCallbackResult = (result) => {

        //if an array, make sure the name appears in it,
        //otherwise assume it is a string and look for exact match
        return Array.isArray(result[type]) ? result[type].indexOf(name) !== -1 : result[type] == name;
    };

    //is the result a promise?
    if (typeof callbackResult.then == 'function') {

        //yes so execute promise and run the check function afterwards
        return callbackResult.then(checkCallbackResult).catch(() => defaultReturn);
    }

    //not a promise, so just pass result directly
    return checkCallbackResult(callbackResult);
};

module.exports = {
    isEnabled: (name, hook) => checkCondition(name, hook,'enable'),
    isDisabled: (name, hook) => checkCondition(name, hook, 'disable')
};
```
In a hook it would be used like this:

```
import errors from 'feathers-errors';
import conditionalHook from './conditionalHook';

export default function() {

    return function(hook) {

        if (hook.type !== 'after') {

            throw new Error(`The 'findExactlyOne' hook should only be used as a 'after' hook.`);
        }

        if (hook.method !== 'find') {

            throw new errors.MethodNotAllowed(`The 'findExactlyOne' hook should only be used on the 'find' method.`);
        }

        //since this is a fairly destructive hook and changes the data type retured
        //require that a callback be explicitly passed to the service that prevents
        //side-effects from not fully understanding what this hook does...
        if (conditionalHook.isEnabled('findExactlyOne', hook)) {

            const results = Array.isArray(hook.result) ? hook.result : hook.result.data;
            hook.result = results.length === 1 ? results[0] : undefined;
        }

        return hook;
    };
}
```

Finally a service call could "enable" this hook explicitly like this:

```
const service = this.app.service('auth/users');
const query = { query: { email: emailToMatch }};

service.find(query, () =>({enable:'findExactlyOne'})).then(user => {
     
      if (!user)  return done(null, false); //either 0 or > 1 results were returned
      
      //here user is an object, not an array of length 1
});
