### ISSUE TITLE
4 questions / comments

### ISSUE THREAD

**Issue by babakness** [feathersjs/feathers#372]
1)   React Native 

I've noticed some open issues and a Medium post about RN + Sockets.io. While we wait for a patch on that, is it possible to use something like Primus and void the issue (since Engine.io is already patched)?

2)  Filtering--Hooks or Model?

If we want to pull up just the messages between users in a group chat, do we do this with Hooks, Models, or make some kind of custom Service? 

Coming from Meteor, I thought of Feathers Services as a hybrid between Meteor Methods and Collections. With Collections there is, given my experience, a straight forward way do the stated task above with plenty of examples for developers. I'm sure this is easy with Feathers, this is very common--I just couldn't find example patterns.

I'm not certain about what is going on under-the-hood. I imagine the service that wraps the database works with the driver to filters down to the database rather than pull in the data then filter.

3) Example patterns for some authenticated / public data.

Meteor has this one Todo example:
https://www.meteor.com/articles/todos-example-app

It has both public and private lists which demonstrate how to filter data to specific authenticated users. A similar demonstration app would really help in setting up the right pattern for users starting with FeathersJS.

4) Having a RethinkDB integration is great! I also think the feather-cli tool is great; it would be nice if this tool could scaffold out RethinkDB files as well. I'm sure this is already on the plate, just thought to cast my vote as well.

---

Thanks for your efforts on this great framework.

**Comment by daffl** [comment]
1) There is a workaround for using Socket.io with React Native. It is [documented in the React Native client setup section](http://docs.feathersjs.com/clients/feathers.html#usage-with-react-native). Unfortunately, there still doesn't seem to much information on how to use Primus with React Native.

2) This is what [event filters](http://docs.feathersjs.com/real-time/filtering.html) are used for. A way for how to do rooms or channels is [outlined in the FAQ](http://docs.feathersjs.com/help/faq.html#how-do-i-create-channels-or-rooms)

3) We do eventually want to extend the simple chat example. For now, more info about authorization can be found [here](http://docs.feathersjs.com/authorization/readme.html) including how to only limit requests to the current user or user groups etc. Most of it can usually also be done directly through [hooks](http://docs.feathersjs.com/hooks/readme.html).

4) It is indeed. We are working on a [new CLI](https://github.com/feathersjs/feathers-cli/tree/2.0) and generator which will include RethinkDB.

**Comment by ekryski** [comment]
Looks like @daffl did a good job of answering. Going to close. Feel free to comment or re-open if that's not the case @babakness.
