### ISSUE TITLE
Non-string and non-numeric params in query

### ISSUE THREAD

**Issue by Mangatt** [feathersjs/feathers#373]
Hi guys,
when I try filter results of query with any non-numeric or non-string value (_null_, _undefined_ or _new Date()_) I've got error. Are there any plans for adding support for these, so following would work?
- hook.params.query.date = null
- hook.params.query.date = undefined
- hook.params.query.date = new Date()

After some research I've found that **advanced criteria work** just fine:
- hook.params.query.date = {$in: [null]}
- hook.params.query.date = {$in: [new Date()]}

**Comment by daffl** [comment]
This depends on the database. We might want to add some service tests for those cases. Since you seem to be using MongoDB for now you can also use the [$eq operator](https://docs.mongodb.com/manual/reference/operator/query/eq/).

**Comment by Mangatt** [comment]
It's RethinkDB actually.

**Comment by ekryski** [comment]
Related to https://github.com/feathersjs/feathers-mongoose/issues/122. @eddyystop possibly we can check for these types as well and coerce them from the querystring into their actual datatypes.

**Comment by daffl** [comment]
That might be tricky (and cause potentially unwanted conversions) without a schema definition for what we are querying.

**Comment by eddyystop** [comment]
Perhaps an optional `hook.params.sanitizeQuery` could indicate what to do. Primitive but ...

**Comment by ekryski** [comment]
@daffl that was my thought as well. If it was a hook that is documented you would be aware of the consequences and could optionally use it or not. I was thinking the coercion might just be for:

- booleans
- null
- ints

but you are right might be better to couple with some sort of schema definition for normalization/validation.

**Comment by daffl** [comment]
This specific problem for RethinkDB should be fixed via https://github.com/feathersjs/feathers-rethinkdb/pull/53 (v0.3.0) now.

Closing since I don't think we can do too much for the more general case (without separate schema definitions).
