### ISSUE TITLE
Gracefully shutting down feathers for testing purposes

### ISSUE THREAD

**Issue by jayalfredprufrock** [feathersjs/feathers#377]
I'm trying to setup a test harness using supertest + tape. It works great except after all my tests run, tape doesn't exit because there are processes still running in the background, even after explicitly closing the express server (I'm using the sub-app method). Is there an official way to stop a feathersjs application, such that any events or processes spawned are removed/stopped?

**Comment by daffl** [comment]
The only thing I know of is to make sure that when using Sockets on the client do disconnect the socket and then closing the server. We usually have something like the following in our Mocha tests:

```js
after(function(function(done) {
  this.socket.disconnect();
  this.server.close(done);
});
```

In our tests.

**Comment by jayalfredprufrock** [comment]
Hmm, I'm only using the rest() middleware so I don't think it's a socket connection that's being left open. My guess is it's some kind of database connection? For now I can get my tests to end by using process.exit(0), but when I have some extra time I'll see if I can identify exactly what is being leaked and report back.

**Comment by daffl** [comment]
Did you find out what it was? It seems to be something with your application setup since I haven't seen this problem before other than not closing the client socket.

**Comment by jayalfredprufrock** [comment]
Somebody suggested I use https://www.npmjs.com/package/leaked-handles to try and identify the processes that aren't quitting - I'll give that a shot and let you know what I find.

**Comment by daffl** [comment]
Definitely let us know your findings. Closing the issue for now though until we have a reason to reopen.

**Comment by eighthletter** [comment]
For me it was the mongoose connection, this should work:
``` node

const test = require('tape')
const app = require('../src/app')
const server = app.listen(3030)

test.onFinish(() => {
  app.get('mongooseClient').disconnect()
  server.close()
})

server.on('listening', () => {
  // Don't know if it's the best practice, but I add my tests here
  test('Sample Service', (assert) => {
    const service = app.service('samples')
    service.create({ text: 'foo' }).then((sample) => {
      assert.ok(sample, 'Created sample')
      assert.end()
    })
  })
})
```

Useful for this issue too #366
