### ISSUE TITLE
How to turn off info messages logged to console

### ISSUE THREAD

**Issue by jayalfredprufrock** [feathersjs/feathers#378]
When testing for routes designed to fail my console gets littered with info/debug messages making the test output difficult to read. Is there a way to silence log messages? I tried experimenting with the DEBUG environment variable but wasn't able to get it to work.

**Comment by daffl** [comment]
Logging is only enabled in the generated app. Have a look at `src/middleware/logger.js`, it has the setup for [Winston](https://github.com/winstonjs/winston) where you can also set the log level.

**Comment by realdubb** [comment]
I found it in `src/hooks/logger.js`

Added the following line to the hook, since I set `NODE_ENV` during tests

```
export default () => (hook) => {
  if (process.env.NODE_ENV === 'test') return;
```
