### ISSUE TITLE
patch() creating a new entry rather than modifying existing one

### ISSUE THREAD

**Issue by ramsestom** [feathersjs/feathers#379]
Hi

  I created my first feathers powered app (a react-native chat app) with a feathers local server following the getting-started tutorial: http://docs.feathersjs.com/getting-started/readme.html
However, now I decided to add new fields to my users (gender, adress...) that where previously only containing an email and a password. So I created a new form in my app and used the service('users').patch() function to update a user information. 
But, rather than patching the existing user entry in my NeDB users database, it end-up duplicating the existing entry with new fields. So I have:

```
{"email":"test@yahoo.fr","password":"$2a$10$CZIkWJ8kKtRwCvKBK0GP5uf9J0SuKxMwpK5otJ8t5ZRDbdZeyjFmO","_id":"Ljk1B6xJCwSXZQLd"}
{"email":"test@yahoo.fr","password":"$2a$10$CZIkWJ8kKtRwCvKBK0GP5uf9J0SuKxMwpK5otJ8t5ZRDbdZeyjFmO","_id":"Ljk1B6xJCwSXZQLd","name":"tom","gender":"M","birthdate":"1980-12-23T23:00:00.000Z","adress":"somewhere","country":"France ","langs":["français","english"]}
```

the _id, email and password of these two lines is strictly identical so the patch function automatically retrieved email and password from first entry (if just passed _id and new user information to the patch() function) to duplicate it on second one...
Really weird

**Comment by daffl** [comment]
How are you using `patch` and setting up the service? You have to send the existing record `_id` or set the `id` property in the configuration so that it knows what it has to update. I guess NeDBs default behaviour is to create a new record otherwise.

**Comment by ramsestom** [comment]
In my app, I initiate feathers this way:
```
 const options = {transports: ['websocket'], jsonp: false, forceNew: true};
 const socket = io('http://192.168.8.100:3030', options);

     this.app = feathers()
      .configure(socketio(socket))
      .configure(hooks())
      .configure(authentication({
        storage: AsyncStorage
      }));
```

on the server side, the configuration is identical to the one on the "getting-started" tutorial

Then, to perform the patch of a user, I do:
```
 this.app.service('users').patch(this.app.get('user')._id, infos).then((result) => {
         Actions.main(); //go back to main menu
      }).catch((err) => {
        console.log('err');
        console.log(err);
        //Alert.alert('Error', err.message);
      });
```
where "infos" has this kind of structure:

```
var infos = {
          name: "name",
          gender: "M",
          birthdate: new Date(),          
          adress: "somewhere",
          country: "FR",
          langs: ["fr","en"] 
      };
```

**Comment by daffl** [comment]
That's good to know. At least we have a lot of options when it comes to database 😄
