### ISSUE TITLE
Streaming large data through service?

### ISSUE THREAD

**Issue by ramsestom** [feathersjs/feathers#384]
Hi

  I have an app where users should be able to post and retrieve large data files (photos, documents...) to/from the server. I read the file uploading tutorial (http://docs.feathersjs.com/guides/file-uploading.html) but I have many concerns regarding it:
- From what I understood, large data files should be post using multiform post data protocol. That means that it would only work with the rest provider. So, if my app currently uses websockets, I would have to reopen an http rest connection to upload my large files. Is there any other option that could allow me to stream large data through websocket to the feathersjs server?
- I was planning on storing my large datafiles directly into a mongoDB database (using GridFS) rather than having to handle them with the filesystem. But here also, it doesn't seems to exists any solution, yet, to stream large data directly from a fethersjs server to a client through websocket service calls. So I would probably have to extract the data from the database, put it into a temporary file (which would consume RAM and CPU on the server) and expose it through the rest provider if I want my client to be able to download a stored file... Am I wrong?  

So is there any solution to stream data using a feathersjs service (express seems to handle readable and writable stream objects: https://nodejs.org/api/stream.html#stream_event_pipe) that could be used to upload/download large data files using websockets?

**Comment by daffl** [comment]
You are correct, currently all data are expected to arrive at once so uploading large files has to be done via Express's file uploading mechanism or [Socket.io streams](https://github.com/nkzawa/socket.io-stream).

It would be interesting to investigate handling `data` input streams for `create`, `patch` and `update` service methods. On the other hand we may just need a documented way how to stream files via Socket.io.

**Comment by ramsestom** [comment]
handling data output streams for `get` would be nice too.
I found an express-stream middleware (https://www.npmjs.com/package/express-stream) that could probably be used.

**Comment by kulakowka** [comment]
For stream with websocket you can use [websocket-stream](https://www.npmjs.com/package/websocket-stream). It works in browser and server.

**Comment by idibidiart** [comment]
If you do implement streaming GET there should be some considerations. One of thos considerations is built-in back pressure in Node Streams, which (by design) causes the stream to go at the rate of the slowest client that's consuming the stream. I've seen this workaround for it, fyi: http://ey3ball.github.io/posts/2014/07/17/node-streams-back-pressure/ @daffl

**Comment by daffl** [comment]
Further progress on this is being tracked in https://github.com/feathersjs/feathers/issues/609
