### ISSUE TITLE
[Question] Setting cookies in after hooks

### ISSUE THREAD

**Issue by kmees** [feathersjs/feathers#385]
What's the intended way to set cookies in an after hook (or directly in a services `create` method).
Currently i have middleware that sets a cookie jar on the `req.feathers` object

```js
import Cookies from 'cookies'

export default function createCookieJarMiddleware(settings) {
  return function cookieJarMiddleware(req, res, next) {
    req.feathers = {
      ...req.feathers,
      jar: new Cookies(req, res, { keys: settings.web.cookieSecret })
    }

    next()
  }
}
```

and then use that jar in the after hook

```js
export default class MyService extends Service {
  //...

  after = {
    create: [
      ({ params, result }) => {
        params.jar.set(result.id, 1, {
          expires: new Date(9999, 1, 1) // never
        })
      }, //...
    ]
  }
}
```

But something feels odd about this. Is there a better way to to this?

**Comment by marshallswain** [comment]
Not sure if there's a better way.   What's the use case for setting a cookie from a service?  I've never found the need to do it.

**Comment by kmees** [comment]
To ensure a user only votes once (or at least making it harder to vote multiple times) if storing IP is not an option.

**Comment by daffl** [comment]
That definitely works. I usually recommend to keep protocol specific functionality in their respective protocol handlers however (e.g. in this case, setting the cookie this way won't work via websockets or other protocols). In this case, I think the cookie handler should really go into [a custom service middleware](http://docs.feathersjs.com/middleware/express.html) instead of the service:

```js
app.service('myservice', myService, function(req, res, next) {
  jar.set(res.data.id, 1, {
    expires: new Date(9999, 1, 1) // never
  });
  next();
});
```

**Comment by kmees** [comment]
@daffl i tried that but the middleware doesn't run after the service that handles the post (votes service in my case) because the service already sends the reponse

**Comment by kmees** [comment]
@daffl nevermind, i didn't know about the 

```
app.use('/todos', ensureAuthenticated, logRequest, todoService, updateData);
```

syntax. I'll try that. Thanks 👍

**Comment by ekryski** [comment]
@kmees yup that will work for you. We're actually doing that in auth.
