### ISSUE TITLE
Add Github bot to make reviewing and organizing easier

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers#387]
We can either use [facebook's](https://github.com/facebook/mention-bot) or borrow ideas from it and build our own. Ideally I'd like it to:
- [ ] automatically tag things appropriately
  - question
  - bug
  - feature
  - documentation
  - needs review
  - task
- [ ] if it's a question have an auto-reply for suggested resources to look first
  - docs
  - faq
  - github issues
  - slack (especially if we add history)
- [ ] mention the right reviewer
  - based on git blame or most active contributor to that repo or simply just a random core team member

**Comment by daffl** [comment]
To me it doesn't seem like a huge pain at the moment. I think with the PR and issue templates added we are pretty good. From what I've seen in other projects that used them so far, GitHub bots (especially the ones that close issues) seem to be more annoying to anybody submitting issues than they help.

Should we close this and revisit later if and when we get more issue duplicates?

**Comment by ekryski** [comment]
Sure
