### ISSUE TITLE
Recommended rest api in react-native?

### ISSUE THREAD

**Issue by ramsestom** [feathersjs/feathers#392]
From the 4 different possible rest api currently supported by feathers-client (jQuery, request, Superagent or Fetch), which is the one recommended to be used in a react-native app?
jQuery probably wouldn't work as, as far as I know, jQuery is not compatible with react-native for now (heavily rely on some HTML DOM that react-native doesn't support). But would any of the 3 others work (I never tried them)? 
Has anyone already used a feathersjs rest service inside a react-native app?

**Comment by daffl** [comment]
We always recommend websockets as the first choice. It is much faster and you get real-time for free (extra nice with [feathers-reactive](https://github.com/feathersjs/feathers-reactive)).

If it has to be REST I'd say `fetch` since it is built into RN.

**Comment by ramsestom** [comment]
ok thanks. I will try fetch (for this app I don't need real-time. So it would be lighter for the server to only have rest requests rather than handling permanent websocket connections to each client. Of course I could open and close a websocket connection for each request but I think there is no advantage to do that rather than just doing http rest requests in my case)

**Comment by daffl** [comment]
No that makes sense. I think fetch is definitely the way to go here. I'll close this issue but let us know if you are running into any issues.
