### ISSUE TITLE
Patching multiple records that update the queried value doesn't emit any service events

### ISSUE THREAD

**Issue by danielang** [feathersjs/feathers#393]
I tried this with the Mongoose and the NeDB service.
- I create some records:

``` js
service.create({text: 'Test 1', number: 123});
service.create({text: 'Test 1', number: 123});
service.create({text: 'Test 1', number: 123});
```
- I bind the `patched` event to a callback:

``` js
service.on('patched', function(patchedObject) { 
  debugger;
  console.log(patchedObject);
});
```
- Then I patch the `number` property of all entries who has the `text: 'Test 1'`:

``` js
service.patch(null, {number: 456}, { query: { text: 'Test 1' }});
```

The patch was successful in DB, the event-callback is fired for 3 times and the promise was resoved with an array[3].
- I patch all entries who has the `text: 'Test 1'` to `text: 'Test 2'`

``` js
service.patch(null, {text: 'Test 2'}, { query: { text: 'Test 1' }});
```

The patch in the DB was successful, **but** no event was fired and the resolved promise contains an empty array.

**Comment by danielang** [comment]
Ok... I figured it out.
It is a 'bug' in the patch method. After you patched the datas in the DB, the service tries to find the patched data with the old query, but after the patch the values of the query has been changed.

A workaround could be this (I wrote this in the compiled ES5 file)
```js
function patch(id, data, params) {
  var _this = this;

  var _multiOptions = (0, _utils.multiOptions)(id, this.id, params);

  var query = _multiOptions.query;
  var options = _multiOptions.options;

  // Run the query

  return (0, _utils.nfcall)(this.Model, 'update', query, {
    $set: (0, _lodash2.default)(data, this.id, '_id')
  }, options).then(function () {
    Object.keys(params.query).forEach(key => {
      if (data.hasOwnProperty(key)) {
        params.query[key] = data[key];
      }
    });


    return _this._findOrGet(id, params);
  });
}
```

**Comment by daffl** [comment]
Good catch. Might be tricky to fix though because you'd have to know how the database is querying records (e.g. in MongoDB we'd have to turn the new data into a dot-notation query). Ideally the db would return all changed records (or at least the id of all changed records) but *SQL dbs seem to make that a little more difficult.

**Comment by daffl** [comment]
Related: https://github.com/feathersjs/feathers-knex/issues/52

**Comment by daffl** [comment]
Tests have been added in https://github.com/feathersjs/feathers-service-tests/commit/af1add313a10d6b26a362dd4fc109bf646b91cbf and fixed and released in all official adapters.
