### ISSUE TITLE
Allow patching many by corresponding IDs

### ISSUE THREAD

**Issue by Mangatt** [feathersjs/feathers#397]
There should by way for updating/patching many DB entries with corresponding IDs. When you use following code it will update only required items (although probably only because DB adapter):

```javascript
app.service('todos').patch( null, {id:1,completed:true} );
app.service('todos').patch( null, {id:2,completed:true} );
```
It would be great to allow following code to work:
```javascript
app.service('todos').patch( null, [{id:1,completed:true},{id:2,completed:true}] );
```
It is not that unusual when you need to update selected items, not batch update by parameters (eg. completed:false)

**Comment by danielang** [comment]
Hey
If the data payload is always the same (like `{completed: true}` ) you can use `app.service('todos').patch(null, {completed: true}, { query: { id: {$in:[1, 2]}}}`

Look in the FeathersJS Doc under: http://docs.feathersjs.com/databases/querying.html

I wrote this from mobile, so sorry for typos, etc.

**Comment by Mangatt** [comment]
Yeah, but this is not unfortunately the case. Think of mass updating of each entry in table row.

**Comment by daffl** [comment]
In the database adapters, mass `patch` is only meant for updating multiple records with the same data. If you want to update several records with different ids and different data you will have to implement your own logic (e.g. in a hook) or use something like [feathers-batch](https://github.com/feathersjs/feathers-batch).

**Comment by Mangatt** [comment]
Yes, I've already done done that. Just thought it would be nice if Feathers could have this feature in future. Thanks @daffl

**Comment by daffl** [comment]
Thanks again for the suggestion @Mangatt. I would be open to a pull request for the service tests and database adapters to support this functionality.

I don't think anybody from the team will get to taking this on any time soon though (personally I'd rather bring the feathers-batch plugin up to date which would allow to do the same thing) so I hope it's ok if I close this.
