### ISSUE TITLE
Querying with logical AND

### ISSUE THREAD

**Issue by Mangatt** [feathersjs/feathers#398]
Hey guys, I've just run into strange thing - when you want to find entries within certain range, you unfortunately couldn't:

``` javascript
app.service('articles').find({query:{
    comments: {
        $lte: 100,
        $gt: 10
    }
}})
```

**In this case you are trying to find all articles with comment count between 10 and 100**. But it takes into account only first argument ($lte in this case) so it will select all articles with less than 100 comments, when you switch $gt with $lte, it selects all articles with more than 10 comments.

I'm really not sure about workaround in this case. Using only one of arguments is not an option and loading huge number of entries and filteing them in application is neither.

Any suggestions?

**Comment by daffl** [comment]
I thought I used this syntax with MongoDB before so it might be a bug with a specific database adapter.

**Comment by Mangatt** [comment]
RethinkDB. I thought that adding $and parameter could help (at https://github.com/feathersjs/feathers-rethinkdb/blob/master/src/index.js#L102 )

```javascript
if (query.$and) {
        (function () {
          // andQuery will be built and passed to row('rowName').filter().
          var andQuery = void 0;
          // params.query.$and looks like [ { name: 'Alice' }, { name: 'Bob' } ]
          // Needs to become:
          // r.row("name").eq('Alice').and(r.row("name").eq('Bob'))
          query.$and.forEach(function (queryObject, i) {
            // queryObject looks like { name: 'Alice' }
            var keys = Object.keys(queryObject);

            keys.forEach(function (qField) {
              // The queryObject's value: 'Alice'
              var qValue = queryObject[qField];

              // Build the subQuery based on the qField.
              var subQuery = void 0;
              // If the qValue is an object, it will have special params in it.
              if ((typeof qValue === 'undefined' ? 'undefined' : _typeof(qValue)) !== 'object') {
                subQuery = r.row(qField).eq(qValue);
              }

              // At the end of the current set of attributes, determine placement.
              if (i === 0) {
                andQuery = subQuery;
              } else {
                andQuery = andQuery.and(subQuery);
              }
            });
          });

          q = q.filter(andQuery);
          query = (0, _lodash2.default)(query, '$and');
        })();
      }
```
But unfortunately I didn't noticed that $or parameter does not supports other special parameters (like $gt inside $or).

**Comment by daffl** [comment]
That's definitely a problem with the RethinkDB adapter. I'll have a look and make sure that more complex queries like the ones you would like to do work properly (we have to update the service tests to include them as well).

**Comment by ekryski** [comment]
@daffl is this one resolved now?

**Comment by daffl** [comment]
https://github.com/feathersjs/feathers-mongoose/pull/124, https://github.com/feathersjs/feathers-levelup/pull/14, https://github.com/feathersjs/feathers-waterline/pull/25 and https://github.com/feathersjs/feathers-rethinkdb/pull/44 are still outstanding.

**Comment by daffl** [comment]
Those have all been merged and released now.
