### ISSUE TITLE
Making sure $or query filter doesn't create security issues

### ISSUE THREAD

**Issue by jayalfredprufrock** [feathersjs/feathers#404]
It appears that in some database adapters (KnexJs in particular), it's easy to circumvent certain query restrictions created by hooks and services by simply adding an $or query filter on the client side. Since this could potentially open up a big vulnerability, it might be worth taking a closer look at all the database drivers to see if the situation can be improved or at the very least making sure users are aware of the security risk.

**Comment by ekryski** [comment]
@jayalfredprufrock sorry this slipped by our radar. Would you be able to put together an short example of what you think the vulnerability is?

**Comment by daffl** [comment]
This should now be tested and fixed for all official adapters. We can reopen if someone can find cases where it is still a problem.
