### ISSUE TITLE
params.id undefined when used in middleware parameter

### ISSUE THREAD

**Issue by petermikitsh** [feathersjs/feathers#407]
```js
module.exports = function () {
  const app = this;

  app.use('/foo/:id', {
    create(data, params) {
      console.log(params.id); // problem
   }
}
```

Expected result:

if I go to POST /foo/bar, params.id should be `bar`.

Actual result:

params.id is `undefined`.

Monkeypatch:

Don't use `id`. Using any other value for the parameter seems to work.

**Comment by daffl** [comment]
It's because `:id` route is already defined [here](https://github.com/feathersjs/feathers-rest/blob/master/src/index.js#L33). I guess we could rename it to something less likely to clash, maybe `__feathersId`.

**Comment by petermikitsh** [comment]
Something obscure would be preferable. I could imagine others may have attempted to use an `:id` parameter.

**Comment by petermikitsh** [comment]
Thanks @daffl! 👍
