### ISSUE TITLE
Universal / Server Side Rendering

### ISSUE THREAD

**Issue by fridays** [feathersjs/feathers#409]
Hello, I am new to feathers and React, it looks great. Is there a simple way to use universal / server side rendering of the React components?
Thank you!

**Comment by marshallswain** [comment]
@fridays This functionality is not in Feathers.  It's a bit beyond the scope of what a Feathers API server would handle.

**Comment by daffl** [comment]
Feathers works on both, the client and the server. There isn't really much else it needs to do to support server side rendering. The [Using A View Engine](https://docs.feathersjs.com/guides/using-a-view-engine.html) guide should show everything needed to perform server side rendering.

**Comment by ekryski** [comment]
You can also take a look at something like this: https://github.com/foxhound87/rfx-stack.

I'm going to close this issue. If we start to get more requests for this then we'll look to add a guide in the future. Happy to take a contribution from the community if someone wanted to write a guide.
