### ISSUE TITLE
Can't use service at client side

### ISSUE THREAD

**Issue by zawmyohtet1** [feathersjs/feathers#410]
Hi All,

pls, help me.

I created service 'categories' by running feathers generate service.
My code is
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/core-js/2.1.4/core.min.js"></script>
<script type="text/javascript" src="//unpkg.com/feathers-client@^1.0.0/dist/feathers.js"></script>
const app = feathers();
const categoryService = app.service('categories');
categoryService.create( {text : 'something...'} );

I got an error. "TypeError: categoryService is undefined".

Pls, guide me to solve this error.

Thanks.

**Comment by marshallswain** [comment]
@zawmyohtet1 you forgot to setup a transport provider like Feathers-rest or Feathers-socketio. https://docs.feathersjs.com/clients/feathers.html

**Comment by zawmyohtet1** [comment]
@marshallswain
Thank you. It is working now. :)
