### ISSUE TITLE
Wrong doc statements about parse-server

### ISSUE THREAD

**Issue by oallouch** [feathersjs/feathers#411]
Hi,
Feathersjs looks fine, but [its comparison](https://docs.feathersjs.com/why/vs/parse.html) to [parse-server](https://github.com/ParsePlatform/parse-server) contains a lot of mistakes:
. parse-server is also a real-time framework. It is called LiveQuery . A WebSocket server is open next to the main app (here is the [server doc](https://parseplatform.github.io/docs/parse-server/guide/#live-queries) and [the js client doc](https://parseplatform.github.io/docs/js/guide/#live-queries))
. [parse-server supports OAuth](https://parseplatform.github.io/docs/parse-server/guide/#oauth-and-3rd-party-authentication), with Twitter, Meetup, LinkedIn, Google, Instagram and Facebook out of the box. The client provides the token and parse-server returns a Parse.User .
. it supports mongodb, but has also an experimental support of postgres

Thx,
Olivier Allouch

**Comment by daffl** [comment]
Thank you. You can correct it by [editing this documentation page](https://github.com/feathersjs/feathers-docs/edit/master/why/vs/parse.md) and submitting a pull request.

**Comment by oallouch** [comment]
Done
Thx

**Comment by marshallswain** [comment]
@oallouch, I looked for your PR, but I don't see it in the feathers-docs repo?
https://github.com/feathersjs/feathers-docs/pulls

**Comment by daffl** [comment]
I was able to submit a pull request and merge the changes.
