### ISSUE TITLE
Stand alone feathers.js & feathers.css files

### ISSUE THREAD

**Issue by yieme** [feathersjs/feathers#415]
Any potential of having a stand alone `feathers.js`, `feathers.css`,  `feathers.min.js` and `feathers.min.css` files?

**Comment by daffl** [comment]
I'm not sure what a `feathers.css` would contain. Standalone [Feathers for the browser](https://docs.feathersjs.com/clients/feathers.html#feathers-client) is already available through the [feathers-client](https://github.com/feathersjs/feathers-client) repository (in the [dist/](https://github.com/feathersjs/feathers-client/tree/master/dist) folder or through a CDN via [unpkg.com](https://unpkg.com).
