### ISSUE TITLE
How to expose a param in every route using Primus?

### ISSUE THREAD

**Issue by IvoPereira** [feathersjs/feathers#416]
Hello,

From what I've seen from the example I am able to use Primus to expose params to be used in services and hooks in a specific route:

```
app.configure(primus({
  transformer: 'sockjs'
}, function(primus) {
  // Do something with primus
  primus.before('todos::create', function(socket, done){
    // Exposing a request property to services and hooks
    socket.request.feathers.referrer = socket.request.referrer;
    done();
  });
}));

app.use('messages', {
  create(data, params, callback) {
    // When called via Primus:
    params.provider // -> primus
    params.user // -> { name: 'David' }
  }
});
```

> https://docs.feathersjs.com/real-time/primus.html#middleware-and-service-parameters

However, how can I expose it in every route?

I am looking to access the ip of the user that made the request. [I've seen I was able to make it](https://github.com/feathersjs/feathers/issues/324#issuecomment-217076338) but using Primus it looks a little different regarding multiple routes.

Any ideas?

Thanks

**Comment by daffl** [comment]
I looks like @ekryski changed the documentation to this for some reason but I'm pretty sure you can still use the `authorize` method:

```js
  // Set up Primus authorization here
  primus.authorize(function (req, done) {
    req.feathers.user = { name: 'David' };

    done();
  });
```

**Comment by IvoPereira** [comment]
Hey @daffl,

Thanks for answering. I've tried using `authorize`method, however it seems the callback is never fired. I have a console.log there that never gets shown up

Does the callback only on happen on any specific moment?

Thanks

**Comment by daffl** [comment]
It looks like it is being tested in https://github.com/feathersjs/feathers-primus/blob/master/test/index.test.js#L31. How do you connect to the socket?

**Comment by IvoPereira** [comment]
I was using it in my app bootstrap file, like this:

```javascript
import path from 'path';
import feathers, { static as serveStatic } from 'feathers';
import favicon from 'serve-favicon';
import compress from 'compression';
import cors from 'cors';
import configuration from 'feathers-configuration';
import hooks from 'feathers-hooks';
import rest from 'feathers-rest';
import bodyParser from 'body-parser';
import primus from 'feathers-primus';
import middleware from './middleware';
import services from './services';

const app = feathers();

app.configure(configuration(path.join(__dirname, '..')));

app.use(compress())
  .options('*', cors())
  .use(cors())
  .use(favicon(path.join(app.get('public'), 'favicon.ico')))
  .use('/', serveStatic(app.get('public')))
  .use(bodyParser.json())
  .use(bodyParser.urlencoded({ extended: true }))
  .configure(hooks())
  .configure(rest())
  .configure(primus({ transformer: 'websockets' }, (primus) => {
    console.log('Before primus before'); // This logs

    primus.authorize((req, done) => {
      // Exposing a request property to services and hooks
      req.feathers.ip = req.ip; // This don't
      done();
    });
  }))

  .configure(services)
  .configure(middleware);

export default app;
```

The inner console.log doesn't seem to be trigged unfortunately.

**Comment by daffl** [comment]
That looks right, odd. How are you connecting to it on the client? Also, does `primus.before('todos::create', function(socket, done){` work? Is there a wildcard `before` event or could you just do `primus.before(function(socket, done){`?

**Comment by marshallswain** [comment]
@IvoPereira were you able to figure this out?

**Comment by daffl** [comment]
I'd be curious about this, too but since it has been a coupe of weeks I am going to close this. If this is a recurring issue or somebody has more information please feel free to comment and we will reopen.
