### ISSUE TITLE
How to expose data from a hook to another?

### ISSUE THREAD

**Issue by bertho-zero** [feathersjs/feathers#417]
This is my scenario:

I try to login via Facebook with feathers-authentication, if the user does not exist it tries to create it, except that it lacks information. Why I redirected to the finalization of the registration and refer the request with all required information.
That is why I would like to expose my data users in a hook before the call of create method of 'auth/facebook' service and be able to recover it in a hook before creating the user.

As a hook.params but persistent. Or is there perhaps already a way to do that?

**Comment by bertho-zero** [comment]
I managed to do what I wanted by changing this line: (https://github.com/feathersjs/feathers-authentication/blob/0.8/src/services/oauth2.js#L72)

From:
`return app.service(options.userService).create(data)`
To
`return app.service(options.userService).create(data, {body: req.body})`

Waiting to learn what can be done, thanks!

**Comment by daffl** [comment]
Let's move the discussion over to https://github.com/feathersjs/feathers-authentication/pull/298 (thank you for that) since it is more Authentication than general Feathers related.
