### ISSUE TITLE
Quickstart Bugs

### ISSUE THREAD

**Issue by machineghost** [feathersjs/feathers#418]
I recently tried to complete the feathers quick start, and ran in to this on the `feathers generate` step:

>Woot! We've created your "feathers-chat" app!
>To start your feathers server run `npm start`.
>local@me~$ 
>local@me~$ npm start
>
>  Invalid Command. Showing Help:
>
>  Commands:

Evidently the `generate` command dumps you in to some sort of feathers command shell afterwards, and you need to hit `CTRL + C` twice to get out of it before you can run `npm anything`.  This should probably be added to the quick start instructions.

**Comment by marshallswain** [comment]
Thanks for pointing this out.  I've added a note in step 4.

**Comment by machineghost** [comment]
Thanks!
