### ISSUE TITLE
can only access feathers server via localhost:3030, not real IP

### ISSUE THREAD

**Issue by beeplin** [feathersjs/feathers#420]
this question might be too basic, but when I use `feathers-cli` to genearate a new app and run it on port 3030, I can only connect with it by `localhost:3030`, not by my real IP or web adress. Why? Is this normal?

**Comment by daffl** [comment]
To access a server without the port number it has to run on port `80`. Can you access it with `http://<real-ip>:3030` or `http://<web-address>:3030` (if not a firewall might block that port)?

You can run on port `80` by starting the generated application with `NODE_ENV=production PORT=80 NODE_ENV FEATHERS_AUTH_SECRET=supersecret npm start`

**Comment by beeplin** [comment]
solved! thx!
