### ISSUE TITLE
RSA token secret

### ISSUE THREAD

**Issue by lontongcorp** [feathersjs/feathers#423]
I'm new to feathersjs, and really like it. Thanks for the great work!

Using [node-rsa](https://github.com/rzcoder/node-rsa), export it to keyfile, as default token secret rather than hardcode it in config file will be better option I think. Reduce unnecessary steps to create new (good) token, production ready, and rotating it in every x days/wk/mo will make it more secure. Will be awesome if I can have this internally from feathers without any more lines to code :)

**Comment by marshallswain** [comment]
@lontongcorp I think this is a great idea.  Would you mind moving this issue to the Feathers-authentication repo?
