### ISSUE TITLE
how does real-time work?

### ISSUE THREAD

**Issue by sarkistlt** [feathersjs/feathers#424]
I mean it works as in Meteor just pulling requests each 'n'ms trough Socket, or like in graphQL through subscription?

Because the first one is not the best solution for big projects.

**Comment by marshallswain** [comment]
@sarkistlt, it works however you setup the transports for whichever provider plugin you use.  Both Socket.io and Primus support multiple transports.  

See http://socket.io/blog/introducing-socket-io-1-0/#new-engine or https://github.com/primus/primus#supported-real-time-frameworks

So, technically, it can be either.  But generally, just as you mentioned, for performance reasons you would use subscription.  Here's an example of how to lock in the socket.io provider to only allow subscriptions over websockets:

```
const io = require('socket.io-client/socket.io');
const socket = io('http://api.feathersjs.com', { 
  transports: ['websocket'] 
});
const app = feathers()
  .configure(feathers.hooks())
  .configure(socketio(socket));
```

**Comment by marshallswain** [comment]
Sorry.  Didn't mean to close this.  Please reopen if I didn't answer your question.

**Comment by sarkistlt** [comment]
Thanks for quick answer, that sounds great!

**Comment by sarkistlt** [comment]
One more thing. When I try to ```const io = require('socket.io-client/socket.io');```

I get following error:
```
var isAndroid = navigator.userAgent.match(/Android/i);
	                ^

ReferenceError: navigator is not defined
    at Object.<anonymous> (/Users/Sarkis/Documents/_projects/Coda/hum-app_v2/node_modules/socket.io-client/socket.io.js:4796:18)
...
...
...
```

**Comment by marshallswain** [comment]
If you're working in node, just do `const io = require('socket.io-client');`

**Comment by marshallswain** [comment]
`navigator` is a global browser object

**Comment by sarkistlt** [comment]
works now, thanks again)

**Comment by sarkistlt** [comment]
BTW, the doc server responded with a status of 502

**Comment by marshallswain** [comment]
Yeah GitBooks is down, but you can use the https://github.com/feathersjs/feathers-docs repo.
