### ISSUE TITLE
Update modules to use ESlint semistandard

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers#432]
For each repo we need to:
- remove `.jshintrc`
- update the `.gitignore` and `.npmignore files`
- update `package.json` file
  - add a `lint` task
  - install `semistandard`
  - install `eslint-if-supported` (if repo supports < node v4)
  - remove any inline jshint directives
  - Add the semistandard config:

```
  "semistandard": {
    "env": [
      "mocha"
    ],
    "ignore": [
      "/lib"
    ]
  },
```
### Repos
- [x] feathers-authentication
- [x] feathers-cli
- [x] feathers-permissions
- [x] generator-feathers-plugin
- [x] feathers https://github.com/feathersjs/feathers/pull/434
- [x] feathers-memory https://github.com/feathersjs/feathers-memory/pull/37
- [x] feathers-mongodb https://github.com/feathersjs/feathers-mongodb/pull/71
- [x] feathers-mongoose https://github.com/feathersjs/feathers-mongoose/pull/131
- [x] feathers-nedb https://github.com/feathersjs/feathers-nedb/pull/48
- [x] feathers-query-filters https://github.com/feathersjs/feathers-query-filters/pull/26
- [x] feathers-hooks https://github.com/feathersjs/feathers-hooks/pull/116
- [x] feathers-hooks-common
- [x] feathers-commons https://github.com/feathersjs/feathers-commons/pull/37
- [x] feathers-rethinkdb https://github.com/feathersjs/feathers-rethinkdb/pull/50
- [x] feathers-rest https://github.com/feathersjs/feathers-rest/pull/81
- [x] feathers-socketio https://github.com/feathersjs/feathers-socketio/pull/46
- [x] feathers-primus https://github.com/feathersjs/feathers-primus/pull/30
- [x] feathers-sendgrid https://github.com/feathersjs/feathers-sendgrid/pull/13
- [x] feathers-mailgun https://github.com/feathersjs/feathers-mailgun/pull/4
- [x] feathers-mailer https://github.com/feathersjs/feathers-mailer/pull/3
- [x] feathers-stripe https://github.com/feathersjs/feathers-stripe/pull/10
- [x] feathers-twilio https://github.com/feathersjs/feathers-twilio/pull/5
- [x] feathers-reactive https://github.com/feathersjs/feathers-reactive/pull/36
- [x] feathers-blob https://github.com/feathersjs/feathers-blob/pull/12
- [x] feathers-levelup https://github.com/feathersjs/feathers-levelup/pull/17
- [x] feathers-waterline https://github.com/feathersjs/feathers-waterline/pull/29
- [x] feathers-socket-commons https://github.com/feathersjs/feathers-socket-commons/pull/30
- [x] feathers-localstorage https://github.com/feathersjs/feathers-localstorage/pull/23
- [x] feathers-sequelize https://github.com/feathersjs/feathers-sequelize/pull/72
- [x] feathers-batch https://github.com/feathersjs/feathers-batch/pull/22
- [x] feathers-service-tests https://github.com/feathersjs/feathers-service-tests/pull/26
- [x] feathers-knex https://github.com/feathersjs/feathers-knex/pull/80
- [x] feathers-bootstrap https://github.com/feathersjs/feathers-bootstrap/pull/7
- [x] feathers-sync https://github.com/feathersjs/feathers-sync/pull/34
- [x] feathers-generator https://github.com/feathersjs/feathers-generator/pull/17
- [x] feathers-errors https://github.com/feathersjs/feathers-errors/pull/52
- [x] feathers-client https://github.com/feathersjs/feathers-client/pull/101
- [x] feathers-configuration https://github.com/feathersjs/feathers-configuration/pull/28
- [x] feathers-authentication-client
- [x] feathers-authentication-oauth1
- [x] feathers-authentication-oauth2
- [x] feathers-authentication-jwt
- [x] feathers-authentication-local
- [x] feathers-redis

**Comment by marshallswain** [comment]
Instead of a `semistandard` npm script, let's just use `lint`, so it's future proof.

**Comment by daffl** [comment]
I think we got them all now.
