### ISSUE TITLE
Update repos to use new changelog generator

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers#433]
We're going with either
- https://github.com/rafinskipg/git-changelog, or
- https://github.com/conventional-changelog/conventional-changelog-cli

Will update issue after I've tested it on a repo or two.
### Repos
- [ ] feathers
- [ ] feathers-memory
- [ ] feathers-mongodb
- [ ] feathers-mongoose
- [ ] feathers-nedb
- [ ] feathers-errors
- [ ] feathers-query-filters
- [ ] feathers-hooks
- [ ] feathers-commons
- [ ] feathers-hooks-common
- [ ] feathers-rethinkdb
- [ ] feathers-rest
- [ ] feathers-socketio
- [ ] feathers-primus
- [ ] feathers-authentication
- [ ] feathers-authentication-oauth2
- [ ] feathers-authentication-local
- [ ] feathers-sendgrid
- [ ] feathers-mailgun
- [ ] feathers-mailer
- [ ] feathers-stripe
- [ ] feathers-twilio
- [ ] feathers-reactive
- [ ] feathers-blob
- [ ] feathers-levelup
- [ ] feathers-permissions
- [ ] generator-feathers-plugin
- [ ] feathers-cli
- [ ] feathers-generator
- [ ] feathers-socket-commons
- [ ] feathers-localstorage
- [ ] feathers-sequelize
- [ ] feathers-knex
- [ ] feathers-reactive
- [ ] feathers-waterline
- [ ] feathers-configuration
- [ ] feathers-batch
- [ ] feathers-sync
- [ ] feathers-bootstrap
- [ ] feathers-service-tests?

**Comment by daffl** [comment]
The problem with all of those from what I can tell is that unlike the Ruby `github_changelog_generator` they are using special formatted git commit messages. I think that generating the changelog from GitHub PRs and issues is still a much easier way to get the same thing (at least that's what I've always pretty much been doing manually before).

If there is a Node based equivalent we should definitely do it but I'd like to avoid having to pester contributors with formatting their commit messages.

**Comment by ekryski** [comment]
We don't need to rush this. I'll look into this, this week for sure. Even if it means quickly writing our own module. It's really not that hard. @corymsmith and I both have written scripts using github and git to commit things.

I'm drawing a hard line on having to have ruby installed. On mac it is a non-issue because you at least have system ruby installed. On every other platform that isn't the case. I don't want people to need to install ruby just to get contributions in or be part of the core team. The less friction to contributions the better.

If we force ruby that will also mean anyone on windows has to do feathers dev in a virtual environment. Technically you can get ruby working on windows but it's a total mine field as a bunch of gems are impossibly hard to get to compile.

**Comment by daffl** [comment]
I know you feel strongly about this but I think we can close this 😉  Now that only a hand full of people make core module releases, I don't think that having to install the Ruby script is a show stopper. After investigating the Node alternatives the Ruby `github_changelog_generator` is simply the one that works best for our workflows (generating the changelog from GitHub issues and PRs).
