### ISSUE TITLE
Add issue and PR templates to all repos

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers#435]
We should add a `.github` folder to each repo with issue and PR templates. Let's figure out what the wording should be or if there is a good example we can copy and then I think we can write a quick script to add this to each repo.

### Repos
- [x] feathers
- [x] feathers-memory
- [x] feathers-mongodb
- [x] feathers-mongoose
- [x] feathers-nedb
- [x] feathers-query-filters
- [x] feathers-errors
- [x] feathers-hooks
- [x] feathers-hooks-common
- [x] feathers-commons
- [x] feathers-rethinkdb
- [x] feathers-rest
- [x] feathers-socketio
- [x] feathers-primus
- [x] feathers-authentication
- [x] feathers-authentication-oauth2
- [x] feathers-authentication-local
- [x] feathers-sendgrid
- [x] feathers-mailgun
- [x] feathers-mailer
- [x] feathers-stripe
- [x] feathers-twilio
- [x] feathers-reactive
- [x] feathers-blob
- [x] feathers-levelup
- [x] feathers-permissions
- [x] generator-feathers-plugin
- [x] feathers-cli
- [x] feathers-generator
- [x] feathers-socket-commons
- [x] feathers-localstorage
- [x] feathers-sequelize
- [x] feathers-knex
- [x] feathers-reactive
- [x] feathers-waterline
- [x] feathers-configuration
- [x] feathers-batch
- [x] feathers-sync
- [x] feathers-bootstrap
- [x] feathers-service-tests?
- [x] feathers-client

**Comment by corymsmith** [comment]
This has been completed.
