### ISSUE TITLE
Canno start the server with "node app" command

### ISSUE THREAD

**Issue by galioy** [feathersjs/feathers#437]
I stumbled upon the problem that I cannot start the server with the `node app` command. I get the following error and stack trace:
```
module.js:327
    throw err;
    ^

Error: Cannot find module '<my_project_dir>/app'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
```
The command `node app.js` will  just give the error `Cannot find module '.../app.js'`.

I noticed that changes to the `package.json` `main` attribute make a difference, but only lead to different errors.

I need to run the server with `node app` instead of `npm start`, because I want to use the `nodemon` module.

Any ideas?

**Comment by marshallswain** [comment]
Can you do node src/index.js?

**Comment by galioy** [comment]
Yeah, I can now see that `index.js` is the starting script, not `app.js`. But index only invokes methods on the `app` object. What is the use for `index.js` then? Wouldn't it be easier to just put
```
const port = app.get('port');
const server = app.listen(port);
server.on('listening', () =>
  console.log(`Feathers application started on ${app.get('host')}:${port}`)
);
```
at the end of the `app.js` script, right before the `module.exports = app;` ?

**Comment by daffl** [comment]
Not really because we still want to be able to do `const app = require('app')` to test and call services internally without implicitly starting the server.
