### ISSUE TITLE
Cannot get feathers runing on my domain

### ISSUE THREAD

**Issue by kieusonlam** [feathersjs/feathers#438]
Hi,

I trying to deloy my little feathers app to my vps using Ubuntu 14. I config my nginx with
```
server {

    access_log /var/log/nginx/mydomain.com.access.log rt_cache;
    error_log /var/log/nginx/mydomain.com.net.error.log;

    server_name mydomain.com   www.mydomain.com;

    location / {
        proxy_pass http://localhost:3030;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

}
```
start app with
`npm start`

Every thing work fine on when i go to 'myipadress:3030' but I when trying to access to the webpage with my domain got this error
```
GET http://mydomain.com/socket.io/socket.io.js 
GET http://mydomain.com/app.js 
GET http://mydomain.com/socket.io/socket.io.js 404 (Not Found)
GET http://mydomain.com/app.js 404 (Not Found) transform.load @ browser.min.js:4run @ browser.min.js:4runScripts @ browser.min.js:4
browser.min.js:4 Uncaught Error: Could not load http://mydomain.com/app.js
    at XMLHttpRequest.xhr.onreadystatechange (http://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.23/browser.min.js:4:28673)
```
I did try to change host to 'localhost', 'my ip adress', 'mydomain.com' from feathers config file but still no hope
```
{
  "host": "localhost",
  "port": 3030,
  "mysql": "mysql://user:passs@111.222.333.444.555:3306/feathersChat",
  "public": "../public/",
  "auth": {
    "idField": "id",
    "token": {
      "secret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    },
    "local": {},
    "successRedirect": "/chat.html"
  }
}
```
am I missing something?

My node version: v5.11.0

**Comment by daffl** [comment]
Does it work if you go to `mydomain.com:3030` (assuming the port is open)?

**Comment by kieusonlam** [comment]
Thanks for your response. I did try that too its not working and yes, port was open. I found that on domain we have to load the script from public folder
`http://mydomain.com/public/app.js `
I dont know why server provide difference link for the resource between domain and ip. With socket.io I have to load it from another source.
`https://cdn.socket.io/socket.io-1.4.5.js`

**Comment by daffl** [comment]
Did you set `NODE_ENV=production` on the server? It could be that something in your `config/default.json` or `config/production.json` is set wrong. Is `mydomain.com:3030/socket.io/socket.io.js` available?

**Comment by kieusonlam** [comment]
No i did not set `NODE_ENV=production` on the server, my both config file are the same. Yes `mydomain.com:3030/socket.io/socket.io.js` is available. I though nginx Virtual Hosts should have taken care of that. I will try to figure it out. I think the problem is solved. Thank you for helping me.
