### ISSUE TITLE
How to change FeathersJs cookies expiration time?

### ISSUE THREAD

**Issue by cwsdeepak** [feathersjs/feathers#439]
I am new in feathersjs. I setup feathersjs with MongoDb my system and its working fine. For my website, I want to modify cookies expiration time (default 30 second). I already checked feathersjs document for this issue. Below is the link: [https://docs.feathersjs.com/authentication/readme.html#cookie-options](https://docs.feathersjs.com/authentication/readme.html#cookie-options)

I also getting an error while executing any query with feathersjs. "Uncaught (in promise) Error: You are not authenticated.".

Can anyone help me in fixing this issue?

Thanks in advance.

**Comment by marshallswain** [comment]
I believe you got your answer in the Slack help channel. Did that solve your issue?

As for the "not authenticated" issue, the request is missing the token, more than likely.  Are you using Feathers Client or another method of connecting to the server?  If you are using the Feathers client, you need to call app.authenticate() before making any other requests.  Please let me know how you are connecting and I'll see if I can help more.

**Comment by cwsdeepak** [comment]
I used that solution, but its not working for me. 

I am using jquery feathers client. I am using following code in my app.js file. 

// app.js code
'use strict';

// Establish a Socket.io connection
const socket = io();
// Initialize our Feathers client application through Socket.io
// with hooks and authentication.
const app = feathers()
	.configure(feathers.socketio(socket))
	.configure(feathers.hooks())
	// Use localStorage to store our login token
	.configure(feathers.authentication({
		storage: window.localStorage
	}));

// Get the Feathers services we want to use
const userService = app.service('users');

$('.logout').on('click', function() {
	app.logout().then(() => window.location.href = '/admin/');
});

app.authenticate().then((result) => {
	console.log(result);
	console.log(app.get('token'));
	console.log(app.get('user'));
	// Find all users
	userService.find().then(page => {
		console.log(page.data);
	});
})
// On errors we just redirect back to the login page
.catch(error => window.location.href = '/login.html');


This code showing me "not authenticated" issue at  **userService.find()**. Also **app.get('user')** function not returning any details currently logged in user.

Thanks for replaying me.

**Comment by marshallswain** [comment]
Looks like you using the socketio provider, so the issue is probably related to this: https://github.com/feathersjs/feathers-authentication/issues/275#issuecomment-249392987

Try locking the socket connection to use the websocket transport as is demonstrated there.  The next version will automatically take care of this.

**Comment by cwsdeepak** [comment]
I checked that article, but my issue is different. Feather cookies expired, before my code complete its execution. I am trying to fix this issue. If you have any idea about changing expiration time. Please guide me. I am using [https://docs.feathersjs.com/authentication/readme.html#cookie-options](url)  as reference.

**Comment by marshallswain** [comment]
Weird.  I thought I just fixed this in the docs, but I guess it got lost.  It uses Express cookie settings, so change 'expires' to 'maxAge'

**Comment by ekryski** [comment]
@cwsdeepak @marshallswain's suggestion works with newer beta versions of auth but if you are usin v0.7.x you can hack around it by setting `auth.cookie.expires` to a future date in code right before you initialize your authentication service. `maxAge` is not supported < 0.8.

Sorry it's kind of hack will be much easier in the 1.0 version of auth.

**Comment by cwsdeepak** [comment]
@marshallswain @ekryski I checked my package.json and find out that I am using 0.7.11 version of feathers-authentication.

**Comment by ekryski** [comment]
@cwsdeepak ok cool. Try you need to do what I mentioned above. Try this:

```js
let authOptions = app.get('auth');
const now = new Date();
const DAYS = 2;
authOptions.cookie.expires = now.setTime( now.getTime() + DAYS * 86400000 );
app.set('auth', authOptions);
app.configure(authentication(authOptions));
```

**Comment by cwsdeepak** [comment]
@ekryski I used your solution and its working for me. Thanks @ekryski and @marshallswain for helping
