### ISSUE TITLE
How to add custom passport strategy

### ISSUE THREAD

**Issue by abartolo** [feathersjs/feathers#440]
Hello,

I've been stuck trying to understand how to add custom passport strategy to the authentication. Looking forward to using Feathers for my new app but in order to move from my old express app I need to get this authentication piece working. 

In my current Express App I have the following strategy below...

`
var passport = require('passport');
    var jwt = require('jsonwebtoken');
    var AtlassianCrowdStrategy = require('passport-atlassian-crowd').Strategy;

    passport.use(new AtlassianCrowdStrategy({
      crowdServer: "...",
      crowdApplication: "..",
      crowdApplicationPassword: "..",
      retrieveGroupMemberships: true
    }, function atlassianCrowdStrategyCustomCallback(userprofile, done) {

      console.log("Inside Crowd Strategy Custom Callback");

      // if user in DB then return user
      // else create user in DB.

      // Return
      return done(null, {
        user: doc.value
      });

    }));
`

Is there a way or do I have to create a separate route and hooks?

**Comment by daffl** [comment]
This is a little tricky in the current version (0.7) but we're just about to wrap up https://github.com/feathersjs/feathers-authentication/pull/336 which will make it much easier.

**Comment by abartolo** [comment]
@daffl thanks for the reply. This is a crucial piece for my project so I ended up using express alone since I didn't want to break anything in Feathers.. I've been following up with feathers and looking forward using it in my future project. I read alot of great things on its way.

**Comment by daffl** [comment]
You can always come back. Feathers is a drop-in replacement for Express (literally replacing `require('express')` with `require('feathers')`) so what you did in Express will work with Feathers as well. What `feathers-authentication` does additionally is to take care of making sure websockets are authenticated the same way.
