### ISSUE TITLE
Update repos to get Travis to notify slack instead of email

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers#441]
Simply add this to the `.travis.yml` right above the `before_script` section:

```
notifications:
  slack: feathersjs:T4tvpJFt27wJZABjLSg5OqMv
  email: false
```

**Note:** technically these tokens are semi-secret so we should probably generate a new one and encrypt as Travis recommends so that our channel can't be spammed. https://docs.travis-ci.com/user/notifications#Slack-notifications

### Repos
- [x] generator-feathers-plugin
- [x] feathers-service-tests?
- [x] feathers
- [x] feathers-authentication
- [x] feathers-socket-commons
- [x] feathers-knex
- [x] feathers-permissions
- [x] feathers-hooks
- [x] feathers-memory
- [x] feathers-mongodb
- [x] feathers-mongoose
- [x] feathers-nedb
- [x] feathers-errors
- [x] feathers-query-filters
- [x] feathers-hooks-common
- [x] feathers-commons
- [x] feathers-rethinkdb
- [x] feathers-rest
- [x] feathers-socketio
- [x] feathers-primus
- [x] feathers-authentication-oauth2
- [x] feathers-authentication-local
- [x] feathers-sendgrid
- [x] feathers-mailgun
- [x] feathers-mailer
- [x] feathers-stripe
- [x] feathers-twilio
- [x] feathers-reactive
- [x] feathers-blob
- [x] feathers-levelup
- [x] feathers-cli
- [x] feathers-generator
- [x] feathers-localstorage
- [x] feathers-sequelize
- [x] feathers-reactive
- [x] feathers-waterline
- [x] feathers-configuration
- [x] feathers-batch
- [x] feathers-sync
- [x] feathers-bootstrap

**Comment by corymsmith** [comment]
@ekryski @daffl Do we only want to be notified when builds break or also when they pass? Just thinking with Greenkeeper theres still lots of noise so broken builds could still get lost in all the other notifications.

**Comment by ekryski** [comment]
Hmm. Not sure. I'm thinking still when they pass for now. It will be noisy but might be handy or PRs and stuff. That channel in Slack will be more for visibility and quick glances and so that we're not getting emails for damn build that happens.

**Comment by corymsmith** [comment]
All repos have been updated with Slack notifications vs email

**Comment by ekryski** [comment]
💥
