### ISSUE TITLE
Update repos to use rimraf vs rm 

### ISSUE THREAD

**Issue by corymsmith** [feathersjs/feathers#443]
- [x] feathers-mongodb
- [x] feathers-generator
- [x] feathers-cli
- [x] feathers-authentication
- [x] feathers-batch
- [x] feathers-blob
- [x] feathers-client
- [x] feathers-errors
- [x] feathers-levelup
- [x] feathers-mailer
- [x] feathers-mailgun
- [x] feathers-sendgrid
- [x] feathers-sequelize
- [x] feathers-stripe
- [x] feathers-service-tests
- [x] feathers-twilio
- [x] feathers-waterline
- [x] feathers-nebd
- [x] feathers-query-filters
- [x] feathers-hooks-common
- [x] feathers-commons
- [x] feathers-rethinkdb
- [x] feathers-socket-commons
- [x] feathers-configuration
- [x] feathers-knex
- [x] feathers-primus
- [x] feathers-socketio
- [x] feathers-rest
- [x] feathers-memory

**Comment by appurist** [comment]
As discussed, I resolved this one for feathers-memory https://github.com/feathersjs/feathers-memory/pull/38 plus the relative _mocha change, so that one has been taken care of.  (Only N-1 to go.)

**Comment by corymsmith** [comment]
All of the repos above have been migrated to rifraf
