### ISSUE TITLE
Feature request. Method convert between hook and middleware

### ISSUE THREAD

**Issue by harish2704** [feathersjs/feathers#444]
Hi, This is not an issue. But just a query or just sharing my thought

The Point is,

As we know, RestProvider is able to convert a **Service method** to equivalent **REST API endpoint**, 

I suggest , It will be great if, there is a mechanism to convert a **Hook** to a equivalent **Express Middleware**

**Comment by daffl** [comment]
Do you have an example how that would that look like?

We are currently trying to work more towards making Feathers framework independent (see #258)  and avoid adding any more Express specific functionality. It could work as a plugin though.

**Comment by harish2704** [comment]
Hi,
Sorry for the inconvenience.
I think this can be closed for now.

Point was this.
provide an API for converting Hooks and Services to independent, freely mountable express middle ware.

Example use case. Suppose I dont use the Rest-Provider in my app
But I want to expose a single action of a auth service as an API.


But Now I understand this is not the right place to ask this question and I can see the possibilities of workarounds.

Sorry
