### ISSUE TITLE
Possibly an improved way to handle callbacks in service methods

### ISSUE THREAD

**Issue by eddyystop** [feathersjs/feathers#445]
The code to convert a service method promise to a callback seems to be [this](https://github.com/feathersjs/feathers/blob/master/src/mixins/promise.js#L11)

``` javascript
 if (typeof callback === 'function' && isPromise(result)) {
    result.then(data => callback(null, data), error => callback(error));
  }
```

Any subsequent `.catch` the promise has will get run if the callback throws. If there is no `.catch` Node has been logging unhandled rejection messages to the console in some tests I have.

I found my way to this code because of an issue someone created in one of my repos:

"So, when I call changeEmail from client and try to change an email to an existing one, it will cause duplicate key error on the server side. But currently this error is not caught by users.update(..., function (err, user12) {...}, and so the error is consumed on the server-side without feeding back to front-end, leading to a time-out error on the front-end."

I can't attest to the veracity of this as I can't run MongoDB at the moment. But I wonder if the above code had anything to do with it.

The callback could be completely detached from the promise with something like

``` javascript
function promiseToCallback(promise) {
  return function (cb) { promise.then(
    data => { process.nextTick(cb, null, data); },
    err => { process.nextTick(cb, err); });
  };
}

const promise = ...
promiseToCallback(promise)(cb);
```

Of course this depends on what you intend should happen.

**Comment by daffl** [comment]
A service mixin for this could look like this:

```js
app.mixins.push(service => {
  const mixin = {};

  app.methods.forEach(method => {
    if(typeof service[method] === 'function') {
      mixin[method] = function(...args) {
        if(typeof args[args.length - 1] === 'function') {
          const callback = args.pop();
          const promise = this._super(...args);

          return promise.then(res => callback(null, res)).catch(callback);
        }

        return this._super(... args);
      }
    }
    service.mixin(mixin);
  });
});
```
