### ISSUE TITLE
Considering falcor or Graphql/Relay integration ?

### ISSUE THREAD

**Issue by shrynx** [feathersjs/feathers#447]
I want to use falcor with feathers, is there any guideline on setting it up ?
And or maybe support it via cli tool ?

**Comment by marshallswain** [comment]
This GraphQL post is all you'll get right now: http://halcyonlabs.io/blog/2016/07/13/eagle-has-landed/

**Comment by ekryski** [comment]
I've been keen to try out Falcor but haven't had a lot of time. I actually think it *might* mate even easier than GraphQL. @shrynx if you wanted to take a stab and report back on findings that would be amazing. 🏆

**Comment by shrynx** [comment]
@marshallswain Thanks, really cool link. This will help a lot.
@ekryski I am really keen on using falcor, It is dead simple and quite powerful. I am not at all fluent with GraphQL/Relay. So will definitely try this approach to integrate with falcor.

**Comment by rollymaduk** [comment]
@shrynx I wrote a little feathers plugin that wraps the apollo server here: https://github.com/rollymaduk/feathers-apollo-server. you might find it useful

**Comment by diegopamio** [comment]
@shrynx did you have any luck with that?

**Comment by daffl** [comment]
It looks like many people are using Feathers with GraphQL with the resources linked but built-in GraphQL support is out of the scope of Feathers core.
