### ISSUE TITLE
No link to home or docs from the blog

### ISSUE THREAD

**Issue by joeframbach** [feathersjs/feathers#448]
I landed on a Feathers blog post from Google and wanted to find a "quick start". Ended up poking through every link I could find on the site and couldn't find even what Feathers is at all. Just blog posts. So I did a Google search for Feathers and discovered that the blog is totally disjoint from the rest of the Feathers site.

Adding a link back to the home page, or even the Quick Start, in the footer of the blog would be helpful for people who find Feathers through search engines (SEO is weighted toward pages with more content anyway), and would help SEO on the home page as well (more inbound links).

Since the blog isn't on github I couldn't think of any better place to let you know. Keep up the great work.

**Comment by ekryski** [comment]
Thanks @joeframbach! Good suggestion. Since the blog is on Medium I can only add one link but I added a link to the docs. Hopefully Medium will add the ability to add more links but I think that is probably the best one for now.
