### ISSUE TITLE
Apollo Client + Feathers Client?

### ISSUE THREAD

**Issue by evgenyboxer** [feathersjs/feathers#449]
Hey all,

Anyone played with Apollo Client + Feathers Client? From my understanding, Apollo Client provide a custom network interface that we can implement and use websockets (or any other transport).

Just wondering if anyone has an example :)

Cheers!

**Comment by daffl** [comment]
You can find an Apollo + Feathers example at https://github.com/swarthout/feathers-apollo and a blog article about it at http://halcyonlabs.io/blog/2016/07/13/eagle-has-landed/. As far as I know Apollo still does not support any real-time functionality yet though.

**Comment by daffl** [comment]
There will be more about GraphQL + Feathers soon but I think the links I sent should answer this specific question.
