### ISSUE TITLE
allow $select in params query when get

### ISSUE THREAD

**Issue by beeplin** [feathersjs/feathers#450]
The service method `get` allows a `params` to be passed in, but currently just ignores it, as @daffl explained in [here](https://github.com/feathersjs/feathers/issues/361):
> By default get just returns a record by its id, adding a query wouldn't really change anything about that. 

But in fact `$select` in the query does change something. It would pluck the record and only returns the fields you need. This is particularly useful when you have a client-side cache of the record and want to see if the record is expired: you can just do:

```js
service.get(id, {query: {$select: ['updatedAt']}}
.then (data) => {
  // check if data.updatedAt is newer than the local updatedAt 
} 
```

By doing this we could just transfer a small part of the record (only the id and the updatedAt time), and then be able to check if the cache is expired. If does, call `get` again to get the whole record; if not, just use the cache.

But currently, when calling `get` for the first time, it always return the whole record (might be very very large), making the client-side cache totally useless.

**Comment by daffl** [comment]
Indeed. There is several issues for this (https://github.com/feathersjs/feathers-service-tests/issues/25 being the starting point). The current workaround for this is a three line hook:

```js
const pick = require('lodash.pick');

app.service('myservice').after(function(hook) {
  if(hook.params.query.$select) {
    hook.result = pick(hook.result, hook.params.query.$select);
  }  
});
```

**Comment by beeplin** [comment]
hmmm.. dose `lodash.pick` support dot notation of fields?

I would go with this workaround by now, but to be frankly it's painful to add this hook to all services in an app. I understand that making this change to `get` is a huge work since all database adapters must be modified and tested. I am wondering if there are any schedules for this?

**Comment by daffl** [comment]
This will be released for all adapters shortly. But I just wanted to point out that it is now pretty easy to add a hook to all services with [application hooks](https://blog.feathersjs.com/feathers-application-and-error-hooks-7a5982e70024?source=user_profile---------1-) in `feathers-hook` v1.6.0.

**Comment by beeplin** [comment]
cool~！



来自 魅族 PRO 6



-------- 原始邮件 --------
发件人：David Luecke <notifications@github.com>
时间：周五 11月11日 11:39
收件人：feathersjs/feathers <feathers@noreply.github.com>
抄送：Beep LIN <beeplin@gmail.com>,Assign <assign@noreply.github.com>
主题：Re: [feathersjs/feathers] allow $select in params query when get (#450)


This will be released for all adapters shortly. But I just wanted to point out that it is now pretty easy to add a hook to all services with application hooks<https://blog.feathersjs.com/feathers-application-and-error-hooks-7a5982e70024?source=user_profile---------1-> in feathers-hook v1.6.0.

**Comment by daffl** [comment]
This has now been merged and released as a minor version in all official adapters.
