### ISSUE TITLE
setup method of service cannot run automatically on client-side

### ISSUE THREAD

**Issue by beeplin** [feathersjs/feathers#451]
according to the docs, the `setup` method of a service could run automatically when the service is initialized. This is true on the server side, but on client side it's not working. For example, after configuring `app`, run this code in client side: (in coffeescript)
```coffee
app.use 'test',
  find: -> console.log 'find'
  setup: -> console.log 'setup'

app.service('test').find()
```
the console prints `find` but no `setup`. This means the client-side `test` service was successfully created, but the `setup` method didn't run.

**Comment by daffl** [comment]
As documented in https://docs.feathersjs.com/api/readme.html#setup:

> Normally app.setup will be called automatically when starting the application via app.listen([port]) but there are cases when you need to initialize the server separately 

So both on the server and the client you will have to either call `app.listen()` (which won't do anything on the client but call all services `setup`) or `app.setup` directly.

**Comment by beeplin** [comment]
it works after calling `app.listen()`. I didn't realize even on client side it's still needed. Thanks!

**Comment by daffl** [comment]
It's up to you but if you want to be more explicit I'd call `app.setup` instead (since that's all `app.listen` does on the client).
