### ISSUE TITLE
Database adapter updates

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers#452]
For the Auk release we are going to include the following database adapters updates:

- `$select` support for all methods
- [feathers-rethinkdb](https://github.com/feathersjs/feathers-rethinkdb)
- Improving service tests with more complex use cases and security considerations

__Deprecate:__

Due to very low usage numbers the following adapters will be removed from the documentation and not updated with new features unless a maintainer can be found. They will continue to function as is:

- [feathers-waterline](https://github.com/feathersjs/feathers-waterline)
- [feathers-levelup](https://github.com/feathersjs/feathers-levelup/)

**Comment by frastlin** [comment]
Hello,
With support for Waterline being dropped, this means only one true multi-database ORM will be supported. I'm wondering if another ORM, Bookshelf could please be added?
https://github.com/feathersjs/feathers/issues/453

**Comment by kokujin** [comment]
Thats sad. Waterline was one of my reasons for using feathers. Re-use of my Waterline collections and models.

**Comment by daffl** [comment]
@kokujin From the package download numbers it looks like you are the only one 😞 and as much as we'd like to support it we currently do not have the resources to do so.

It will continue to work as-is. If you are interested in taking it on, all we are looking for is someone to keep an eye on it.

**Comment by daffl** [comment]
Everything in this Epic has been released now.
