### ISSUE TITLE
Feathers client code should not depend on Node API

### ISSUE THREAD

**Issue by ntrp** [feathersjs/feathers#456]
I am trying to integrate feathers in a NativeScript application and at the moment it seems this is not possible because the client depends on NodeJS APIs. In my opinion this is wrong, the client should not be depending on anything which is server side.

**Comment by daffl** [comment]
As long as you make sure to log `feathers/client` (and not `feathers` directly), the only internal Node API used is [EventEmitter](https://nodejs.org/dist/latest-v7.x/docs/api/events.html#events_class_eventemitter) which all browser module loaders (Browserify, Webpack etc.) provide a browser shim for.

If NativeScript doesn't you can probably install https://www.npmjs.com/package/events as the fallback or use the UMD build at `dist/feathers` which already includes it.

**Comment by ntrp** [comment]
I followed this example:

https://docs.feathersjs.com/clients/feathers.html#usage-in-nodejs-and-client-module-loaders

The require chain is this one `feathers/client` calls `require(´../featers´)` -> `require(´./application´)` -> `require(´debug´)` -> `require(´tty´)`. The module `tty` if NodeJS based so it is not working.

I tried to create a sample project on a different computer and the `debug` module that gets pulled in is different.. I will try to understand why there is this difference.

Another problem I encountered was the fact that I cannot use the import from statements as suggested in the guide. I am using Typescript, do I need to configure something in particular inside of the ts config to make it work? (the require syntax is working but not with the module name ´feathers/client´ but with ´feathers/lib/client´).

**Comment by daffl** [comment]
Does NativeScript not respect the `browser` field? It is set in the [debug module](https://github.com/visionmedia/debug) at https://github.com/visionmedia/debug/blob/master/package.json#L28. It is either a flag for whatever module loader NativeScript is using or the `debug` module name has to be mapped to `debug/browser` manually.

**Comment by ntrp** [comment]
Hmm it could be, it is not technically a browser and all the rendering is done via a custom rendering engine because there is no DOM.

**Comment by daffl** [comment]
I would give it a try. If that doesn't work there is always the [feathers-client build](https://github.com/feathersjs/feathers-client/tree/master/dist) that does not have any external dependencies

**Comment by ntrp** [comment]
I was finally able to make it work but I was forced to create a custom version of the `debug` module with the main field set to browser.js. I have also included feathers-reactive and I pushed everything to this repo -> https://github.com/ntrp/nativescript-ng2-feathers.

p.s. the feathers-client was giving me some issues in the build system.. The project seems very interesting but I think you guys should work on a client rewrite in typescript and on making it completely environment agnostic. That would enable much easier integration in every platform!

**Comment by daffl** [comment]
The client is completely environment agnostic but there is no way to account for every module loader/client combination possible. Did you try mapping `debug` to `debug/browser` in NativeScripts module loader configuration? It shouldn't require any custom forks. We can also look into why the pre-built client wasn't working.

I'm not seeing how rewriting something in Typescript will make existing Node modules environment agnostic and there are no plans to do that. We are going to stick with modern ES features for the foreseeable future.

**Comment by daffl** [comment]
Closing since it looks like you found a workaround for this and the fix would be not with Feathers but the [debug](https://github.com/visionmedia/debug) module which has to be made compatible with NativeScript.
