### ISSUE TITLE
Should uWebSockets replace Socket.io?

### ISSUE THREAD

**Issue by NetOperatorWibby** [feathersjs/feathers#458]
I found [this](https://github.com/uWebSockets/uWebSockets) via HackerNews and it claims to be better and faster than Socket.io so it seems like it's worth investigating.

**Comment by daffl** [comment]
Feathers also [supports Primus](https://docs.feathersjs.com/real-time/primus.html) which is an abstraction for many other popular websocket libraries [including uWebSockets](https://github.com/primus/primus#uws).

**Comment by NetOperatorWibby** [comment]
Oh okay, cool.
