### ISSUE TITLE
How to get by arbitrary field

### ISSUE THREAD

**Issue by jiangts** [feathersjs/feathers#460]
I have a service where I don't want to expose the database id's to end users, as I don't want other resource locations to be guessable.

Can I still somehow achieve `app.service('serviceName').get("non-sequential-id")` or do I need to find by the non sequential id and forsake get altogether?

**Comment by eddyystop** [comment]
I'd say you have to use `find`.

**Comment by daffl** [comment]
`get` is only meant for the primary id. For the database adapters you can change the primary id and it is also possible to `find` by the given id in a before `get` hook and setting the result:

```js
app.service('myservice').hooks({
  before: {
    get(hook) {
      return this.find({
        query: { somOtherField: hook.id }
      }).then(page => {
        const { data } = page;
        if(data.length === 0) {
          throw new Error('Not found');
        }

        hook.result = data[0];

        return hook
      });
    }
  }
});
```

 `find` will always let you query by any field.
