### ISSUE TITLE
Is it possible to change successRedirect based on user role in feathersjs local authentication?

### ISSUE THREAD

**Issue by cwsdeepak** [feathersjs/feathers#461]
In my feathersJs application, I want to manage multiple success redirection based on user role:
1. When a admin login into our application, then I want to redirect to admin/dashboard.html
2. When a user login into our application, then I want to redirect to user/dashboard.html
3. When a stylist login into our application, then I want to redirect to stylist/dashboard.html

How we can implement this in feathersJs? Also how can we manage multiple user roles in feathersJs?

**Comment by exppro** [comment]
I'm getting stuck with same behaivor, seems there is no help

**Comment by cwsdeepak** [comment]
@exppro You can use client side authentication.
https://docs.feathersjs.com/v/auk/authentication/readme.html#client-side

**Comment by marshallswain** [comment]
Hi @exppro, sorry you feel like there's no help.  This is exploring territory that we haven't had to deal with in production apps, yet.  So y'all might be the pioneers of your desired workflow with Feathers.  Thanks for helping @cwsdeepak.

**Comment by daffl** [comment]
I also recommend to use client side authentication and on success either redirect to the new page or load the appropriate components.
