### ISSUE TITLE
Client does not receive custom realtime events

### ISSUE THREAD

**Issue by tprobinson** [feathersjs/feathers#463]
I don't know if this is really related to Kue, it may simply happen to anything that Feathers subscribes to events from. To help testing, I generated a fresh project and pasted in code from a project of mine that has this problem. The repository and instructions are [here](https://github.com/tprobinson/feathers-issuerep).

If I can provide any additional testing or information, please let me know.

----

### Steps to reproduce
1. Add Kue to a project
2. Create a service to proxy Kue's realtime job events to clients (job created, job progress, job complete, etc)
3. Subscribe to these custom events on the client
4. Create a Kue job

### Expected behavior
The client should receive these custom events, as detailed on [the docs](https://docs.feathersjs.com/real-time/events.html#custom-events).

### Actual behavior
The client does not receive these events.

### System configuration
**Module versions**:
feathers-commons@0.7.8
feathers-hooks-common@2.0.1
feathers-hooks@1.6.1
feathers-query-filters@2.1.1
feathers-rest@1.5.2
feathers-socket-commons@2.3.1
feathers-socketio@1.4.2
feathers@2.0.2
kue@0.11.5

**NodeJS version**: v6.9.1

**Operating System**: Ubuntu 16.04 x64

**Browser Version**:
Chrome Version 54.0.2840.90 (64-bit)
Firefox 49.0.2

**Client Versions**:
(this is what I have on the HTML's head)
//unpkg.com/feathers-client@^1.0.0/dist/feathers.js
/socket.io/socket.io.js

**React Native Version**: N/A

**Module Loader**: Tried with Webpack and plain Babel

**Comment by daffl** [comment]
I finally got a chance to look at it and could verify that custom events work. My guess is that you are listening to the wrong events on the client. In https://github.com/tprobinson/feathers-issuerep/blob/master/public/app.jsx#L158 

```js
jobsService.on('jobs start', this.genProgFunc('start'));
```

Should just be 

```
jobsService.on('start', this.genProgFunc('start'));
```

Since it is the event you are emitting in https://github.com/tprobinson/feathers-issuerep/blob/master/src/services/jobs/index.js#L26.

`jobs start` is the event name that will be sent through the socket but it'll be split up automatically into the same event you emitted on the server by the client.

**Comment by tprobinson** [comment]
Yep, this worked. I would suggest a documentation revision, as the current page at https://docs.feathersjs.com/real-time/events.html says:

> Now clients can listen to the `<servicepath> status` event.

This is what gave me the impression I needed to prefix the event with the service name.
Thanks for your quick response!

**Comment by gwuhaolin** [comment]
I also suffer this issue, follow doc https://docs.feathersjs.com/real-time/events.html server not emit custom events to client. Is there any successful custom events demo?

**Comment by daffl** [comment]
What version of `feathers-mongoose` are you using? In later versions should be able to just pass the `events` array in the [service options](https://github.com/feathersjs/feathers-chat/blob/master/src/services/users/users.service.js#L12).

**Comment by gwuhaolin** [comment]
@daffl  version is  `"feathers-mongoose": "^5.1.0"`
register service by 
```js
module.exports = async function () {
  const app = this;
  let service = mongooseService({
    Model: Page,
    events: ['start', 'done'],
  });
  app.use('page', service);
  service = app.service('page');
}
```
emit events by:
```js
const pageService = this.app.service('page');
pageService.emit('start', job.id);
```
here is my debug trace:
<img width="2560" alt="screen shot 2017-06-30 at 10 51 20 am" src="https://user-images.githubusercontent.com/5773264/27719038-6e2b3b6c-5d82-11e7-9c6f-4ea01e72d07b.png">

**Comment by gwuhaolin** [comment]
@daffl I'am so sorry about it, it's my fault. `job.id` is `undefined` lead to this issue.
how to get `id` value create by mongoose service?
