### ISSUE TITLE
Do the client socket and the server connection inside the event filters share some unique id?

### ISSUE THREAD

**Issue by sunabozu** [feathersjs/feathers#464]
I can get the unique id on the client via `feathers.io.id`. I also can see it in the server's socket pool inside `app.io.sockets.sockets`. But can I identify a connection by it inside my event filter? I went through the `connection` argument, but couldn't find anything. Is it possible?

**Comment by daffl** [comment]
You can set the socket id [in a Socket.io middleware](https://docs.feathersjs.com/real-time/socket-io.html#configuration):

```js
const app = feathers()
  .configure(socketio(function(io) {
    // Registering Socket.io middleware
    io.use(function (socket, next) {
      socket.feathers.socketId = socket.id;
      next();
    });
  }));
```

Now it will be available as `connection.socketId`.

**Comment by sunabozu** [comment]
@daffl 
Thank you! I overlooked that paragraph, sorry.
