### ISSUE TITLE
consider supporting deepstream.io?

### ISSUE THREAD

**Issue by beeplin** [feathersjs/feathers#465]
[https://deepstream.io/blog/deepstream-2.0-more-than-1000-times-faster-than-socket.io/](https://deepstream.io/blog/deepstream-2.0-more-than-1000-times-faster-than-socket.io/) 

deepstream.io is a new realtime framework which has reported remarkable high performance. 

I have been suffering from the low performance of socket.io and sometimes had to turn off realtime feathers in my projects. The new deepstream.io project seems a new way out.

I am not sure if the primus team is interested in supporting deepstream.io (I have opened an issue for this there.). If not, is it possible to directly support it via a new feathers plugin? Or, is it easy to wrap it manually as a "fake" feathers-socketio?

**Comment by daffl** [comment]
I'd first see if [Primus](https://github.com/primus/primus) will add support for it (since that is what it's really for). Primus also already supports more performant websocket libraries if you were having issues with Socket.io.

**Comment by ahdinosaur** [comment]
from https://github.com/primus/primus/issues/511#issuecomment-262463679, the Primus author recommends using [`uws`](https://github.com/primus/primus#uws)

> Deepstream is nothing more than code on top of uws. So instead of supporting that you could just use uws directly in primus

**Comment by beeplin** [comment]
got it. thanks!
