### ISSUE TITLE
Hooks and Middlewares

### ISSUE THREAD

**Issue by shahen94** [feathersjs/feathers#469]
## QUESTION
I can't find answer of my question in stackoverflow.

Is it possible to execute middleware before hooks and how ?

**Comment by daffl** [comment]
There is a chapter about [using Express middleware in the documentation](https://docs.feathersjs.com/middleware/express.html). You can use service specific middleware or app wide middleware. Middleware will always run before hooks.

**Comment by shahen94** [comment]
Even if I using rest provider ?
I mean my hooks never calles in this case

**Comment by shahen94** [comment]
I added middleware before my service
```
aoo.use('/posts', multipartUpload, mainService)
```

**Comment by daffl** [comment]
I'm not sure what you are asking. Express middleware will only run for the REST provider. Hooks are only run on services (not for Express middleware).

**Comment by shahen94** [comment]
Got it. But my service and hooks never invokes after middleware

**Comment by daffl** [comment]
Probably because the `multiPartUppload` middleware sends its own response instead of calling `next`.

**Comment by shahen94** [comment]
```

export default function (req, res, next) {
  const contentType = req.headers['content-type'];
  const form = new multiparty.Form({ maxFieldsSize: Infinity });
  const hasOwn = Object.prototype.hasOwnProperty;

  if (req.method.toLowerCase() !== 'post') {
    next();
  }
  if (!contentType || contentType.toLowerCase().indexOf('multipart/form-data') === -1) {
    next();
  }

  req.feathers.data = Object.assign({}, req.feathers.data);

  const keysShouldBeParsed = ['voting', 'videos', 'emojiUnicodes', 'postToSelected'];
  form.parse(req, (err, fields) => {
    if (err) {
      throw new Error('Parsing form data failed', err);
    }
    for (const key in fields) {
      if (!hasOwn.call(fields, key)) {
        continue;
      }
      req.feathers.data[key] = keysShouldBeParsed.includes(key)
        ? JSON.parse(fields[key][0])
        : fields[key][0];
    }
    next();
  });
}

```
Here is my code. When I put console log before next it called

**Comment by shahen94** [comment]
@daffl I figured this out. I just should pass `hook.data = hook.params.data`

I'm going to close this issue.
Thanks !
