### ISSUE TITLE
Feathers Command Not Found

### ISSUE THREAD

**Issue by ICEDBANK** [feathersjs/feathers#474]
I am a newbie when it comes to figuring this stuff out but I had the same problem with angular-cli.
( ng command not found ) but after making an alias in my .bashrc file. example looks like this
alias ng="/Users/EXAMPLE/npm-global/lib/node_modules/angular-cli/bin/ng" I was hoping to accomplish it the same way with feathers but no luck. I have no idea why I am having so many problems with these type of files so any insight would be greatly appreciated. I do have feathers-cli stored globally, my computer just does not recognize the commands.
![screen shot 2016-12-11 at 10 25 56 pm](https://cloud.githubusercontent.com/assets/5601883/21087161/394ee512-bff1-11e6-8903-52221068ef39.png)

**Comment by daffl** [comment]
I recommend reading our [instructions on how to get set up](https://docs.feathersjs.com/getting-started/setting-up.html). All those problems you are mentioning are usually permissions related and will just go away when using [nvm](https://github.com/creationix/nvm).

**Comment by ICEDBANK** [comment]
Thank You sir!! I appreciate it greatly

**Comment by conciousweb** [comment]
I use nvm and this issue remains. Additionally your link is outdated and contains no information regarding this issue...
