### ISSUE TITLE
Validate scopes of a request

### ISSUE THREAD

**Issue by anhldbk** [feathersjs/feathers#477]
From my understanding, to verify if a request is matched with a predefined scope, we must implement a [custom verifier](https://github.com/feathersjs/feathers-authentication-jwt#customizing-the-verifier)

```js
import jwt, { Verifier } from 'feathers-authentication-jwt';

class CustomVerifier extends Verifier {
  // The verify function has the exact same inputs and 
  // return values as a vanilla passport strategy
  verify(req, payload, done) {
    // do your custom stuff. You can call internal Verifier methods
    // and reference this.app and this.options. This method must be implemented.
    done(null, payload);
  }
}

app.configure(jwt({ Verifier: CustomVerifier }));
```

My question is: How to efficiently validate scopes? Is there any way to define scopes for a service method?

**Comment by daffl** [comment]
What do you mean by scopes? A service method is scoped by the hooks that you add to it. So you can add individual hooks initialized with the scope you would like the service to be in or read `hook.path` to get the services path (which I assume could also act as a scope).

**Comment by daffl** [comment]
We'll need more information for further discussion. Closing for now.
