### ISSUE TITLE
Feathers environment on Windows

### ISSUE THREAD

**Issue by zoulja** [feathersjs/feathers#478]
I'm trying to "Create your first real-time app in minutes"
### Steps to reproduce
Execute 'feathers generate'
### Expected behavior
Some magic happens
### Actual behavior
cmd.exe crashes silently
PowerShell console lives longer and provides some logs:

C:\>"$basedir/C:/Users/user/AppData/Local/Yarn/config/global/node_modules/.bin/feathers.cmd"   "$@"

The filename, directory name, or volume label syntax is incorrect.

C:\>exit $?

I was able to execute 'feathers generate' using correct (for Windows) full path , but failed again because of another issue(path.js throw new TypeError('Path must be a string. Received ' + inspect(path));)

I will appreciate if some expert would verify "Create your first real-time app in minutes" on Windows using the latest versions
### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working): feathers-cli@1.2.7
**NodeJS version**: v7.2.1
**Operating System**: Windows 7
**Browser Version**:n/a
**React Native Version**:n/a
**Module Loader**:n/a

**Comment by jerfowler** [comment]
This looks to be an issue with it installed with `yarn global`, I can verify and have the same problem. 

Works fine with just `npm -g`, though.

**Comment by zoulja** [comment]
Ok, by some reason feathers.cmd contained wrong configuration (related to yarn), but it was not removed during reinstalation/uninstallation
I deleted it manually, reinstalled feathers and now it's ok
