### ISSUE TITLE
What Do you think about this chain?

### ISSUE THREAD

**Issue by biapar** [feathersjs/feathers#479]
What Do you think about this chain?

React Native<-> FeathterJS <-> .NET Core WebAPI + ( option GraphQL DotNet )<-> SQL Server
or FeathterJS is an overlap stack of  .NET Core WebAPI?

**Comment by marshallswain** [comment]
Is .NET core web API realtime and RESTful?

**Comment by biapar** [comment]
Yes....NET Core or NET Standard WebApi can be real-time with SignalR package. The only problem for client javascript side is that SignalR js client require JQuery.
With .NET WebAPI you can build RESTful logic application https://www.asp.net/web-api/overview/older-versions/build-restful-apis-with-aspnet-web-api.

**Comment by daffl** [comment]
I wrote a short [article about how to use Feathers to make an existing API real-time](https://blog.feathersjs.com/using-feathersjs-to-make-your-existing-api-real-time-813f7c3fd892#.gnnnb8hjs). When using Feathers as a proxy that way, SignalR might not even be needed. If the .NET stack already provides everything you need it might be redundant though as you pointed out.
