### ISSUE TITLE
Is't possible to use Visual Studio2015 with Node.js tools for developping on Feathers?

### ISSUE THREAD

**Issue by biapar** [feathersjs/feathers#480]
Is't possible to use Visual Studio2015 with Node.js tools for developping on Feathers?

https://github.com/Microsoft/nodejstools/wiki

**Comment by marshallswain** [comment]
@biapar I use Visual Studio ***Code*** for everything.  It has a sweet debugger, and I imagine that a lot of that tech is borrowed from the full version of Visual Studio's Node debugger.  If it has a configuration similar to what's on [this page](https://code.visualstudio.com/Docs/editor/debugging#_launch-configurations), then all you have to do to get it to work with Feathers is make sure that the `program` attribute is the full path of the entry point, including the filename and extension.  The node shorthand for modules, like '/server/` meaning `/server/index.js` doesn't work.  You have to put the full path.

**Comment by marshallswain** [comment]
I think you'll probably be able to use the instructions in this section of their docs: https://github.com/Microsoft/nodejstools/wiki/Projects#create-project-from-existing-files

**Comment by biapar** [comment]
I try today
