### ISSUE TITLE
How to mimic firebase referencing

### ISSUE THREAD

**Issue by DevEclipse** [feathersjs/feathers#483]
in firebase we do this on our client side

let db = firebase().database();

let refUsers = db.ref('users');

how can i do this on feathers js?

where i dynamically create a service based on the path

like
in firebase

db.ref('users/test')

app.service('users/test')

**Comment by marshallswain** [comment]
@DevEclipse `app.service('users/test')` basically does what you're looking for.  The difference is that you have to pass a database adapter config as the second argument.  Firebase doesn't support multiple databases, so it's not even an option to pass a database config.

**Comment by DevEclipse** [comment]
@marshallswain so i'd do it like this?

app.service('users/test',new NeDb()) ??

**Comment by marshallswain** [comment]
@DevEclipse, yep.  If you take a look at the code, you'll see that `app.use` just calls `app.service`.  So, in the case of registering new services, `app.use` and `app.service` are ***exactly*** the same: https://github.com/feathersjs/feathers/blob/master/src/application.js#L23

**Comment by daffl** [comment]
That is what [Feathers on the client](https://docs.feathersjs.com/clients/feathers.html) does already. So if you have a [browser setup](https://docs.feathersjs.com/clients/feathers.html#feathers-client) like this (refer to the other section on that page when using a module loader like Webpack):

```html
<script type="text/javascript" src="socket.io/socket.io.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/core-js/2.1.4/core.min.js"></script>
<script type="text/javascript" src="//unpkg.com/feathers-client@^1.0.0/dist/feathers.js"></script>
<script type="text/javascript">
  var socket = io('http://api.my-feathers-server.com');
  var app = feathers()
    .configure(feathers.hooks())
    .configure(feathers.socketio(socket));

  var messageService = app.service('messages');

  messageService.on('created', function(message) {
    console.log('Someone created a message', message);
  });

  messageService.create({
    text: 'Message from client'
  });
</script>
```

`var messageService = app.service('messages');` will automatically create a client service that connect to the `messages` service on the server the socket is connected to.

On the server the services that are available have to be pre-initialized (we don't want to allow any client to create random services for themselves).

**Comment by DevEclipse** [comment]
Can i allow dynamic??? creation of services from client?

i see too many repetitive code so if i do a mapping of every service and apply somewhat same on the firebase Rules system and parse to the apply on the before hooks??

can this be implemented its a bit hassle if i want to change something on the server i need to change it to the client can't this be an isomorphic app?

**Comment by DevEclipse** [comment]
The main reason i use featherjs is that its open source free and easy to use but i can't implement what firebase does i really want to mimic what they do its easy when you want to change or add something in the database

**Comment by marshallswain** [comment]
We are definitely open to discussing and providing support when somebody decides to champion this feature.  It's not on the list for the next two release cycles, currently, because the core team is working on other important improvements.

**Comment by daffl** [comment]
I don't see how Firebase can let any client create any kind of database that they can do whatever they want with. You have to create your services at some point, what's the difference if you initialize the ones you need on the server or on the client (except that doing it on the client is not secure)?

To not repeat setup code you can use `app.before` and `app.after` [hooks](https://blog.feathersjs.com/feathers-application-and-error-hooks-7a5982e70024#.aoqtft1xr) and a service mixin like

```
app.mixins.push(function(service) {
  // do something here with every `service` that is being registered
});
```

There also would be a workaround to allow creating services from the client (go inception and make a service creation service) but I really don't recommend it.

**Comment by DevEclipse** [comment]
hmmmm so firebase isn't secured when it comes to client intializtion of references?

well what if i have a service on my client that doesn't exist in the server?

can i have a function where it creates a server service from the client?

sorry for being a firebase guy though but its just so easy to setup if you want something to be added

is the idea of firebase client referencing from a database a bad IDEA?

**Comment by DevEclipse** [comment]
firebase has a rules system where you can check if the user is authenticated or something like that and an API like you do like this:
```

let item = {
```
 name: 'test',
quantity: 1
}
database.ref('user/items').push(item);
```
```
Im also using Vue JS and Vuex as my front end and state management for firebase I just want to recreate my work using Feathers JS

**Comment by marshallswain** [comment]
Creating a Firebase clone with Feathers is definitely possible, with a good bit of work.

**Comment by daffl** [comment]
You probably have seen it already but I wrote a short blog post [how to migrate a simple service form Firebase](https://blog.feathersjs.com/using-feathersjs-as-an-open-source-alternative-to-firebase-b5d93c200cee#.3fxetk7wl).

The big difference to Firebase is that a Feathers server is not a black box. You have full control over it so what I was getting at is that - unlike Firebase - there is no reason to give the client as much power. I still think it's a big disadvantage of Firebase that you basically have to implement all your sever logic - visible to everybody - on the client because it is essentially just a fancy data storage.

A Feathers client is only supposed to use the services (API) you defined on the server not implement any server-like functionality itself.

**Comment by DevEclipse** [comment]
Great point but is there an instance where a client or a hacker or something creates a firebase reference using the firebase config and pushes data on the database? even its compiled and splitted by webpack?

**Comment by DevEclipse** [comment]
Great point.

But have you encountered a firebase referencing from a client or hacker pushing invalid or malicious data in firebase?

**Comment by daffl** [comment]
I'm not too familiar with Firebase so I can't say for sure. What I'm trying to say is that - even though it is possible with Feathers - you would be fighting the system by trying to allow a client to create arbitrary services.

However, for completeness and to close this issues, here is how a service that would allow to create other services could be implemented:

```js
const stripSlashes = require('feathers-commons').stripSlashes;

app.use('/__service', {
  create(data) {
    const path = stripSlashes(data.path);

    if(!app.services[path]) {
      app.use(`/${path}`, service(configuration));
    }

    return Promise.resolve(data);
  }
});
```

On the client a new service can then be initialized and then used with:

```js
app.service('__service').create({ path: '/test' }).then(() => {
  app.service('test').create({ text: `this is a test message` });
});
```

**Comment by fernozzle** [comment]
I just want to note for future readers that @DevEclipse's initial question may have been misunderstood. When someone asks about a bizarre feature from a different project, it might be helpful to know **why** they might want such a bizarre feature.

>how can i do this on feathers js?
>where i dynamically create a service based on the path like in firebase
>db.ref('users/test')

@marshallswain's reply (and the replies that followed) seemed be under the assumption that `users/test` was the name of a service (unrelated to a service possibly named `users`).

---

In Firebase, there's one "service", a single JSON object that might look like this:

```
{
  'users': {
    'user123': { mood: 'happy' },
    'user456': { mood: 'angry' }
  },
  'groups': {...},
  'weather': 'cloudy'
}
```

You could listen to real-time changes for all of `users`...

```
db.ref('users')
  .on('child_changed', ...)
```

...or just one child of a child named `user123`:

```
db.ref('users/user123/mood')
  .on('value', ...)
```

These refs act like Feathers' services but are dynamically created, and the only events sent are changes **at or deeper than** the listener's requested path. This recursive "lensing" is a feature I really miss from Firebase :(
