### ISSUE TITLE
Sort returns inverse order

### ISSUE THREAD

**Issue by swina** [feathersjs/feathers#484]
Testing a very simple find using a service created with standard hook when I send a simple GET like:

`http://localhost:3030/carts`

I get all records in natural inserted order. Each record has a field used to group them (groupid). If I try to send a GET like

`http://localhost:3030/carts?$sort[groupid]`

I get all records ordered by groupid but in reverse order (like DESC).

DB is mySQL

Any idea ?

**Comment by daffl** [comment]
You are not giving it any sort order so it probably assumes `1`. You probably want `http://localhost:3030/carts?$sort[groupid]=-1` (ASC) or `http://localhost:3030/carts?$sort[groupid]=-1` (DESC).

**Comment by swina** [comment]
Hey,
thank you very much for your quick answer. 
If I omit the sort order type (ASC or DESC) it gives the DESC as default (looks unusual). 
I set to 

`http://localhost:3030/carts?$sort[groupid]=1`

it gives me the correct order (ASC).

Thank you again

Antonio

**Comment by daffl** [comment]
We didn't really define (or document) what happens if you don't give a sort order. If it's the wrong way and you would like to use it you can always modify the query accordingly in a hook:

```js
app.service('carts').before({
  find(hook) {
    const { query } = hook.params;

    if(query.$sort) {
      Object.keys(query.$sort).forEach(key = {
        if(!query.$sort[key]) {
          query.$sort[key] = -1;
        }
      });
    }
  }  
});
```
