### ISSUE TITLE
Calling service method 'get' with undefined returns all records

### ISSUE THREAD

**Issue by petermikitsh** [feathersjs/feathers#485]
### Steps to reproduce

```js
app
  .service('myService')
  .get(undefined)
  .then((result) => {
   // #=> result is an array of myService entities
  });
```

### Expected behavior

I would suspect the promise to:
- resolve with `result === null`, or 
- reject for supplying an invalid id to the get method.

### Actual behavior

`result` was an array of myService records.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions**  Feathers 2.0.3
**NodeJS version**: 6.0.0
**Operating System**: OS X
**Browser Version**: Chrome Latest
**React Native Version**: N/A
**Module Loader**: Webpack 1.x

**Comment by daffl** [comment]
I think this is mainly a problem of the Feathers REST clients but I'll also create a database service test to make sure there isn't a wrong default behaviour.

**Comment by petermikitsh** [comment]
That makes a lot of sense actually. I normally use a websocket connection. I temporarily switched over to the REST client (when trying to debug my upgrade to authentication@1.0, making sure the JWT was being passed correctly, etc) when I noticed this.
