### ISSUE TITLE
Combining signup and auth

### ISSUE THREAD

**Issue by rstegg** [feathersjs/feathers#486]
I feel like there isn't very much explanation on the 'magic' behind authentication.  I would like to combine my signup action to return a JWT token.  Could anyone help me?

I think it would be something like:

* middleware/signup.js
```js
const newUser = { 
  user: req.body.user,
  pass: req.body.pass
}
app.service('users').create(newUser)
.then(I dont know what to do here, quick guess):
.then(user => app.authenticate(user)) // authenticate not defined though
.then(authenticatedUser => res.json(authenticatedUser));
````

Can I get any help or explanation of how to use auth outside of the magical realm? Thanks!

Edit: I made this an issue because I feel like there should be more documentation on manual authentication.  This is more of a demonstration, I already know there is an issue on this, such as #467

**Comment by rstegg** [comment]
Also, I don't feel like a ninja redirect to login is an actual solution but rather a work-around.

**Comment by marshallswain** [comment]
@rstegg it looks like you're pretty close.  If `app.authenticate()` is undefined, you probably are using the signup middleware before the authentication plugin.  Make sure the auth plugin gets used, first.

```js
const newUser = { 
  user: req.body.user,
  pass: req.body.pass
}
app.service('users').create(newUser)
  .then(user => app.authenticate(user)) // authenticate will be defined if you register middleware in the correct order.
  .then(jwt => res.json(jwt));
```

**Comment by daffl** [comment]
The generated app will still use old authentication though in which case it'll have to be

```js
const { email, password } = req.body;

app.service('users').create({ email, password })
.then(user => app.service('auth/local').create({ email, password })) // authenticate not defined though
.then(authenticatedUser => res.json(authenticatedUser));
```

**Comment by rstegg** [comment]
Thanks guys, your dedication is remarkable!
