### ISSUE TITLE
Possible to redirect in an after hook?

### ISSUE THREAD

**Issue by rstegg** [feathersjs/feathers#487]
Is it possible to reference of `res` from an after hook?

I want to manipulate some data then send the user that data when it's finished, so I'm using a service with before and after hooks.

**Comment by daffl** [comment]
See https://docs.feathersjs.com/help/faq.html#how-do-i-access-the-request-object-in-hooks-or-services.

Basically, you can but we don't recommend it since services shouldn't know about how they are being accessed. Is there a way to figure out based on the data if you want to do a redirect? Then it can be done in a custom Express middleware after the service:

```js
app.use('/myservice', service(), function(req, res, next) {
  // res.data is the service call result
  const redirectUrl = getRedirectUrl(res.data);

  if(redirectUrl) {
    res.redirect(redirectUrl);
  } else {
    next();
  }
});
```

**Comment by rstegg** [comment]
Ahha! You think of everything don't you?  Two addendum, how do I define a middleware to a service? and I am interested in implementing the feathers-stripe library, but there isn't really any documentation on how 😢  is there an example or *baby's first* I can check out?

**Comment by daffl** [comment]
Service specific middleware can be registered right with the service (e.g. https://github.com/feathersjs/feathers-chat/blob/master/src/services/message/index.js#L25) just like the code sample.

If you have any specific questions about the Stripe service please head over to https://github.com/feathersjs/feathers-stripe/issues and open a new issue.

**Comment by rstegg** [comment]
Thank you! A little bit of feedback, you should try to organize the docs as redux does: http://redux.js.org/docs/introduction/

Where everything isn't collapsed, I mean.
