### ISSUE TITLE
Usege of custom error handler, instead of the default feathers-errors, renders undesired response format

### ISSUE THREAD

**Issue by galioy** [feathersjs/feathers#489]
I want to use a custom error handler module, instead of the included `feathers-errors`, but when I disable the default `feathers-errors` handler, my errors are returned as HTML instead of JSON. How can I control/fix that?

### Steps to reproduce
1. Disable the default `feathers-errors/handler` module by commenting out the line `app.use(handler());` in `/src/middleware/index.js`.
2. Create a custom error (**not** using the `feathers-errors` module) in a service (or somewhere else) and make a request to the application, so that it's thrown back as a response.

### Expected behavior
Return the error object as JSON, the same way it is returned when I use the `feathers-errors` handler for throwing errors.

### Actual behavior
Returns the created error as HTML.

### System configuration

**NodeJS version**:
`v6.9.1`
**Operating System**:
OSX El Capitan
**Browser Version**:
Postman

**Comment by daffl** [comment]
Formatting the error as JSON is what the `feathers-errors` handler is for 😉

In general, error handling is the exact same as [Express' error handling](https://expressjs.com/en/guide/error-handling.html) so you will have to register your own error formatting middleware if you don't want to use the one that comes with Feathers:

```
app.use(function (error, req, res, next) {
  console.error(err.stack);
  res.status(500).json({ message: error.message });
});
```
