### ISSUE TITLE
Calling a REST API with authenticate

### ISSUE THREAD

**Issue by swina** [feathersjs/feathers#491]
I have the following code (client) to update a database thru a service

```
var myService = appSocket.service('someservice');
app.authenticate().then(response=>{
 myService.patch ( id , 
                    { 
                        field1: fieldvalue , 
                        ...
                    } 
                )   
```

Hook is like the following (to protect only to authenticated users.

```

const globalHooks = require('../../../hooks');
const hooks = require('feathers-hooks');
const auth = require('feathers-authentication').hooks;

exports.before = {
  all: [
    auth.verifyToken(),
    auth.populateUser(),
    auth.restrictToAuthenticated()
  ],
  find: [],
  get: [],
  create: [],
  update: [],
  patch: [],
  remove: []
};

exports.after = {
  all: [],
  find: [],
  get: [],
  create: [],
  update: [],
  patch: [],
  remove: []
};
```

I authenticate correctly (I get the JWT token), but anything happens (no update on the database and no errors on server or client). 
If I remove the authentication check from the hook and I remove app.authenticate().then(...) from the client code database is updated regularly.

**Comment by daffl** [comment]
Try `app.authenticate().then(response=>{}).catch(error => console.log(error))` and you should see if there is any other error (which there probably is if nothing happens).

**Comment by swina** [comment]
Hi,
thank you for your answer, but I don't get any error and if I try to log the response I got the right authentication data and jwt token too but no errors even in the server log. 
It looks like it doesn't run the myService.patch ( or even update ) when I set in

 `app.authenticate().then( response=>{ ... })` . 

If I try to use jquery $.ajax POST type PUT, without using app.authenticate(), it works but I need to send the authorization header with the correct JWT token (also for $.ajax GET).
It's unusual because if I don't set authentication required in the hook and so I don't use `app.authenticate().then()`, service REST (find, get, put, patch and update) work perfectly.

**Comment by daffl** [comment]
If no response is coming in there has to be an error somewhere. This will log errors from `.patch` as well:

```js
const myService = appSocket.service('someservice');

app.authenticate().then(response=> {
  return myService.patch ( id , { 
    field1: fieldvalue , 
    ...
  })
}).catch(error => console.log(error));
```

**Comment by swina** [comment]
Ok, I catched the error ...

```
app.authenticate().then(response=>{
   myService.patch ( id , 
     field: fieldValue,
     ...
})
}).catch(error=>console.log(error));

```
I got `Error: Authentication token missing`

**Comment by daffl** [comment]
`app.authenticate()` (without any parameters) will try to get the token from localStorage. A token will be put into the storage when calling `app.authenticate({ email, password })` at one point or using the login page from the chat guide.
