### ISSUE TITLE
Problem working through the tutorial

### ISSUE THREAD

**Issue by p-adams** [feathersjs/feathers#494]
I am following along the tutorial to build the real-time chat and I am having some strange issues. I set up the login and signup portions (copying and pasting what is in the docs), and I cannot type input into the signup input fields. Has anyone else experienced a similar problem?

**Comment by HintikkaKimmo** [comment]
Hi same here for me the app does not even start. Attached node debug log below. Not sure what is happening. 

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/7.4.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start' ]
2 info using npm@4.0.5
3 info using node@v7.4.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle feathers-chat@0.0.0~prestart: feathers-chat@0.0.0
6 silly lifecycle feathers-chat@0.0.0~prestart: no script for prestart, continuing
7 info lifecycle feathers-chat@0.0.0~start: feathers-chat@0.0.0
8 verbose lifecycle feathers-chat@0.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle feathers-chat@0.0.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/Kimmo/Documents/feathers-chat/node_modules/.bin:/Users/Kimmo/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/Kimmo/n/bin
10 verbose lifecycle feathers-chat@0.0.0~start: CWD: /Users/Kimmo/Documents/feathers-chat
11 silly lifecycle feathers-chat@0.0.0~start: Args: [ '-c', 'node src/' ]
12 silly lifecycle feathers-chat@0.0.0~start: Returned: code: 1  signal: null
13 info lifecycle feathers-chat@0.0.0~start: Failed to exec start script
14 verbose stack Error: feathers-chat@0.0.0 start: `node src/`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid feathers-chat@0.0.0
16 verbose cwd /Users/Kimmo/Documents/feathers-chat
17 error Darwin 16.3.0
18 error argv "/usr/local/Cellar/node/7.4.0/bin/node" "/usr/local/bin/npm" "start"
19 error node v7.4.0
20 error npm  v4.0.5
21 error code ELIFECYCLE
22 error feathers-chat@0.0.0 start: `node src/`
22 error Exit status 1
23 error Failed at the feathers-chat@0.0.0 start script 'node src/'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the feathers-chat package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node src/
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs feathers-chat
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls feathers-chat
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by miramolin** [comment]
Hi, for me the app starts and runs. On the signup page, the password box doesn't 'do anything' when I type.

**Comment by ekryski** [comment]
I think this should be resolved in the new docs and https://github.com/feathersjs/feathers-chat. We're still working on finalizing the authentication section of the guide in the new docs but you should be able to refer to the chat repo.

**Comment by daffl** [comment]
This has indeed been fixed now. New frontend guides coming shortly.
