### ISSUE TITLE
Is there a way to overide paginate from URL querystring or feathers client?

### ISSUE THREAD

**Issue by davigmacode** [feathersjs/feathers#499]
In some case i need to return all data without pagination, 
based on issue #219 i can do something like this

`app.service('orders').find({paginate: false})`

but its only work internally from the server side, not from the client,
may it will be nice if it can work from the client or from querystring like this

`http://api.com/orders?$limit=-1`
when service.paginate.max = false

or

`http://api.com/orders?$paginate=false`

**Comment by daffl** [comment]
By default this is disabled for good reasons (when you have several thousand records disabling pagination can bring down both, the server and the client) but it is possible to map the the query parameter to disable pagination as you suggested with a simple [hook](https://docs.feathersjs.com/hooks/readme.html):

```js
app.service('myservice').before({
  find(hook) {
    if(hook.params.query.$limit === '-1') {
      hook.params.paginate = false;
      delete hook.params.query.$limit;
    }
  }
});
```

**Comment by davigmacode** [comment]
it works, thanks for youre fast response
