### ISSUE TITLE
external api data only

### ISSUE THREAD

**Issue by rrubio** [feathersjs/feathers#501]
Hi Guys,

I know how to call an external api from hooks in order to populate my own data. How would I go about calling an external api from my server and return all the data from that endpoint back to my app i.e. never touches my database just a thirdparty call.

**Comment by marshallswain** [comment]
Usually the API would publish data on how you would connect.  More than likely you would use something like super agent or axios. You could put it in a hook or actually create a service wrapper like Feathers-mailgun.

**Comment by daffl** [comment]
You would implement [your own service](https://docs.feathersjs.com/services/readme.html). I wrote about how to proxy to an external API in https://blog.feathersjs.com/using-feathersjs-to-make-your-existing-api-real-time-813f7c3fd892#.ave1gtmq8

**Comment by rrubio** [comment]
Brilliant! thank you :-)
