### ISSUE TITLE
Middleware (signup) does not execute service's (users) after-hook 

### ISSUE THREAD

**Issue by chuan137** [feathersjs/feathers#505]
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

Signup middleware
```
module.exports = function(app) {
  return function(req, res, next) {
    app.service('users').create({
      email: req.body.email,
      password: req.body.password
    })
    .then(user => {
      res.send(user);
      console.log('send user');
    })
    .catch(next);
  };
};
```

user service
```
'use strict';

const service = require('feathers-sequelize');
const user = require('./user-model');
const hooks = require('./hooks');

module.exports = function(){
  const app = this;

  const options = {
    Model: user(app.get('sequelize')),
    paginate: {
      default: 5,
      max: 25
    }
  };

  // Initialize our service with any options it requires
  app.use('/users', service(options));

  // Get our initialize service to that we can bind hooks
  const userService = app.service('/users');

  // Set up our before hooks
  userService.before(hooks.before);

  // Set up our after hooks
  userService.after(hooks.after);
};
```
service hooks
```

exports.before = {
  find: [
    auth.hooks.authenticate(['jwt'])
  ],
  create: [
    local.hooks.hashPassword({ passwordField: 'password' }),
    defaultRole('user'),
    verifyHooks.addVerification()
  ]
};

exports.after = {
  all: [hooks.remove('password'), globalHooks.myHook()],
  find: [],
  get: [],
  create: [],
  update: [],
  patch: [],
  remove: []
};
```
### Expected behavior
expect password is removed from returned json object.

### Actual behavior
both after hooks, hooks.remove('password') and globalHooks.myHook() have not been executed.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by daffl** [comment]
As pointed out [here](https://docs.feathersjs.com/hooks/bundled-deprecated.html#remove):

> **ProTip:** This hook will only fire when params.provider has a value (ie. when it is an external request over REST or Sockets.) or if you have passed your own custom condition function.

Because you are calling it internally in a middleware you have to set your own provider flag in `params` which will cause the hook to run:

```js
app.service('users').create({
      email: req.body.email,
      password: req.body.password
    }, { provider: 'server' })
```

**Comment by chuan137** [comment]
Thanks for the remote answer.
