### ISSUE TITLE
Typed tests

### ISSUE THREAD

**Issue by AbraaoAlves** [feathersjs/feathers#508]
With #507 PR, feathersJS already has typed definitions.

But dts are code and any code has been tested. To solve this:

My proposal:
Transform: test/*.js -> test/*.ts and config package.json to run mocha with ts-node instead of babel.

Reason:
The best way to check if definition file is aligned with source code is executing it inside code base. We have a great test code base and can enjoy it.

Or in another way, make a `type-test` folder with specific typescript tests.

Feedback, please.

**Comment by daffl** [comment]
Can we do this during test time? As in run the tests with Babel and then copy the test files as `test.ts` (since they should all be valid Typescript anyway) and run with Typescript? Should we wait with releasing your definition PRs until we have tests?

**Comment by AbraaoAlves** [comment]
I'm taking longer than I expected to finish the tests, my goal is to do something totally compatible with existing code today. But looking at the releases that are already, we can take this strategy of updating the definitions via patchs (minor).

**Comment by marshallswain** [comment]
Issue moved to [feathersjs/feathers-typescript #3](https://github.com/feathersjs/feathers-typescript/issues/3) via [**ZenHub**](https://www.zenhub.com/)
