### ISSUE TITLE
Create user on validation fail

### ISSUE THREAD

**Issue by rrubio** [feathersjs/feathers#513]
Hi Guys,

Currently if a username/password is incorrect i get a "NotAuthenticated" message (perfect). 

On failure i would to check if email/username already exists, if not then create them and respond with token. Any tips are much appreciated!

**Comment by zusamann** [comment]
```js
app.service('/users').find({
  query: {
    email: 'abc@def.com'
  }
})
.then(res => {
  // do something here if user is found
})
.catch(rej => {
  // do somethign here if user is not found
})
```

Something like the above might help?

**Comment by rrubio** [comment]
@zusamann would this be a middleware?

**Comment by zusamann** [comment]
https://docs.feathersjs.com/hooks/readme.html

Read up on hooks above, they are added to a service to pre/post process data. Really powerful way of handling such behaviour.

My guess is it would be a hook that gets added after the auth hook in your service. Which checks `isAuthenticated` and then on the basis of that runs the above query.

**Comment by rrubio** [comment]
Yes, i thought hooks would be the way to go, but i'm lost about creating the user and then returning a token.

**Comment by zusamann** [comment]
If you have a service you can easily do a CRUD on them, refer to services in the documentation.

```js
app.service('/users').create({
   email: abc@def.com,
   password: // provide here if you're using passwords
})
.then(res => {
  // do something here
})
.catch(rej => {
  // do something here
})
```

**Comment by daffl** [comment]
To add to what @zusamann said, with auth 0.7 you can create a token by calling `create` on the `auth/local` service with the login information:

```js
const login = {
   email: abc@def.com,
   password: password << use this if you're using passwords
};

app.service('/users').create(login)
  .then(res => app.service('auth/local').create(login))
```

**Comment by rrubio** [comment]
Thanks guys!

**Comment by rrubio** [comment]
Apologies, just one question. I can't seem to access "service" under my new hook. I've tried the following and no luck.

`const hooks   = require('feathers-hooks');
const service = require('feathers-mongoose');

module.exports = function(options) {

  const app = this;
`

**Comment by rrubio** [comment]
Apologies, just one question. I can't seem to access "service" under my new hook. I've tried the following and no luck.

`const hooks = require('feathers-hooks');
const service = require('feathers-mongoose');

module.exports = function(options) {

const app = this;
`

**Comment by rrubio** [comment]
I just learned that i can only have one hook doing a find, i had another hook doing a query based on the query string(not using find). My above issue is now solved, i'm also able to create the user. However,  the "auth/local" section of code below isn't giving me a token.

`app.service('/users').create(login)
  .then(res => app.service('auth/local').create(login))`

**Comment by daffl** [comment]
What is it giving you (if nothing `app.service('auth/local').create(login).catch(e => console.log(e))` might help)?

**Comment by rrubio** [comment]
on catch i'm only getting the following "{}" empty.

**Comment by rrubio** [comment]
Actually... i was trying to stringify the response. Now i'm getting the following:

> ReferenceError: app is not defined

**Comment by daffl** [comment]
The most common reason for invalid logins is that the `hashPassword` hook is not being registered on `create` of the user service. Besides that I don't think we can be of much more help without a complete breaking example.

**Comment by rrubio** [comment]
Here's the code i'm running if that helps?

`'use strict';

// src/services/user/hooks/queryUserInfo.js
//
// Use this hook to manipulate incoming or outgoing data.
// For more information on hooks see: http://docs.feathersjs.com/hooks/readme.html

const defaults = {};

module.exports = function(options) {
  options = Object.assign({}, defaults, options);

  return function(hook) {
    hook.queryUserInfo = true;

    // The authenticated user
    if(hook.params.hasOwnProperty('user')){
      const user = hook.params.user;

      // get promotions belonging to user request only.    
      hook.params.query._id = user._id;
      return hook;
    } else {

      console.log('user not found - create');

      const login = {
          email: 'abc@test.com',
          password: 'password321'
        };

        hook.app.service('/users').create(login)
          .then(res => hook.app.service('auth/local').create(loginEnter))
          .catch(e => console.log('error :: ' + e));

      return hook;
    }

  };
};
`

**Comment by daffl** [comment]
What service is this hook for? Where does the login information come from? Also, for asynchronous hooks (I'm assuming this one should wait until the user is created and logged in) you need to return a promise (`return hook.app.service('/users').create(login)`).

**Comment by rrubio** [comment]
The service is 'user' and the login information is via a REST call angular2 'http.post' app.

**Comment by daffl** [comment]
Ok, so if you want to create a user upon authentication you have to add the hook before the `auth/local` service:

```js
app.service('auth/local').before({
  create(hook) {
    const query = { email: hook.data.email };
    const userService = app.service('users');

    // Look up the user to see if it exists
    return userService.find({ query }).then(page => {
      // If it doesn't, create the user
      if(page.data.length === 0) {
        return userService.create(hook.data);
      }

      // Otherwise do nothing and let local auth do its thing
    }).then(() => hook);
  }
});
```

**Comment by rrubio** [comment]
Hi @daffl thank you for the help man, really appreciate it! 

With the sample above? does this still go under my users hook? And under hooks? how can i view/grab all posted data e.g password? i only see the email at the moment.

**Comment by daffl** [comment]
How you set it up and where you put it doesn't matter. You can put this anywhere after configuring authentication and where you have access to the `app` object (e.g. right at the end of `app.js`). 

Remember that `auth/token` is just another service that on `create` takes the login data and [any hook](https://docs.feathersjs.com/hooks/readme.html) will work accordingly.

**Comment by rrubio** [comment]
@daffl thank you man! :-)
