### ISSUE TITLE
Universal/Isomorphic Express

### ISSUE THREAD

**Issue by Download** [feathersjs/feathers#515]
I just wanted to point you guys to a discussion happening in the Express project that, in a roundabout way, was actually triggered in part by Feathers JS.

Feathers JS has an application object (Feathers) that mimics the Express API. I really liked that aspect of Feathers so I looked how you did it and it inspired me to try to take it a step further, by also enabling the `use` method to work on the client... I ended up building [uexpress](https://github.com/download/uexpress). 

I asked [a question](https://github.com/expressjs/express/issues/3198) about the Express source code on their issue tracker and it was seen by Wesley Todd, who, with his project [nighthawk](https://github.com/wesleytodd/nighthawk), was doing something similar. He somehow got it scheduled on an [Express TC meeting](https://github.com/expressjs/discussions/issues/51) and they [discussed](http://youtu.be/Ol-gr_OQuHg) what it would take in the core of Express 5 to allow projects like nighthawk, uexpress and Feathers JS to assemble their own Express-compatible servers, using the same parts used by Express core (factored out into separate packages).

Since you guys have a lot of experience in writing isomorphic code with Express, and are (as I understand it) looking at generalizing this concept over to multiple server types (Koa, etc), I think you would be able to weigh in on this discussion with your insights.

**Comment by eddyystop** [comment]
@daffl

**Comment by daffl** [comment]
What we are planning for the next version is basically turning our current client (https://github.com/feathersjs/feathers/blob/master/src/client/express.js) into core and then mixing in framework specific functionality as plugins (`app.configure(feathersExpress())`). Our client looks very similar to what you did in https://github.com/Download/uexpress/blob/master/uexpress.js#L40.

Some random thoughts:

- From our experience, sub-apps with websockets and authentication are hard (and annoying). I'm not entirely sure what we want to do about that yet.
- Feathers itself does not really need any routing functionality
- I'd like to discourage using a view rendering engine in Feathers. The better way to use it on the server would be importing the Feathers app (and potentially authentication) into a separate Express application and use it that way.

Anyway, if there is anything we can do to help we'd be more than happy to. Currently I am not entirely sure how exactly that would look like though - without sub-apps, routing or view rendering it's basically only `.get`, `.set` and the event emitter that Feathers is relying on.

**Comment by Download** [comment]
> Our client looks very similar to what you did

Lol that is no coincidence... I stole a lot from you guys. Thanks for that BTW!

> I'd like to discourage using a view rendering engine in Feathers. 

I agree.

I was more looking at it the other way around... what if Feathers would be able to rely on a standard Express For Browsers or whatever it would be called, that would basically be what your client/express.js is doing now?

**Comment by daffl** [comment]
Oh, that's exactly what you said, sorry 😉 It would be great for us to rely on a standard browser Express as long as it still works when mixing in different app objects like Koa.

Any specific things we could do to help move this forward?

**Comment by Download** [comment]
I think it would help if you guys chimed in over at this discussion on the Nighthawk project.
I think Wesley Todd is willing and able to take the lead in this. He is the guest that appears halfway the video of the TC Meeting to discuss this (I can imagine you did not watch the video :) )

This is probably a long term thing.... But I am hoping we can convince the Express JS team that taking the browser into consideration for Express 5 in order to offer a clear path towards truly isomorphic code would be very welcome by the community. I think if they would identify a browser version of Express JS as a noble and worthy goal and started a project (using a merge of Nighthawk and UExpress as a starting point perhaps), it would create a clear path for the community to contribute to this.

**Comment by fega** [comment]
Hello @daffl, I was thinking about the assets management in feathers, but reading this topic I get a question.

You discourage the use of a view engine in feathers, but what about the statics assets contained in the public folder? you think that it should be in a separated app?

if not, What about automatically delete the .html extension from the URLs? like using "http://myapp/chat" instead of "http://myapp/chat.html" is this a good idea?

**Comment by daffl** [comment]
Static assets are fine - although in production they are normally hosted using a CDN anyway. I wouldn't delete the file extension. I wouldn't remove the `.html` extension for an HTML file.

**Comment by fega** [comment]
No, xD, I was referring about having a Middleware that re-route the html file automatically to a route without an extension

**Comment by cpsubrian** [comment]
Just to pin a note here, if express were part of the http/socket 'providers', then there could in theory be an AWS lambda provider that wouldn't need express at all (and thus probably a faster function startup time). The provider would prescribe the function input to look sorta like http ({headers, query, body, w/e}) and that could then be mapped to API Gateway (or whatever). Just been thinking about how well either services would map to functions or even just a whole api as one function (but startup time is important then).
