### ISSUE TITLE
All other users get denied access to the find method of a service, after one user uses the create method of that service.

### ISSUE THREAD

**Issue by Probotect0r** [feathersjs/feathers#518]
### Steps to reproduce
Here is the application in concern: https://github.com/Probotect0r/cloud-chat-app

These are the steps I am taking: 
Create user1, hit `GET /messages`, works ok.
Create user2, hit `GET /messages`, works ok.
As user2, hit `POST /messages`, works ok.
As user2, hit `GET /messages`, works ok.
As user1, hit `GET /messages`, access denied.
As user2, hit `POST /messages`, works ok.
As user1, hit `POST /messages`, works ok.

### Expected behavior
All users should be able to hit `GET /messages`, as long as they provide a proper token.

### Actual behavior
Only the first user to hit `POST /messages` is allowed access to `GET /messages`.

### System configuration

Tell us about the applicable parts of your setup.
Only change made was to the model of the messages. I added a 'user' field to associate messages with their sender. I also added a before hook for create, which automatically adds the calling user's id to the data.user field.

**Module versions** (especially the part that's not working):
    "body-parser": "^1.16.1",
    "compression": "^1.6.2",
    "cors": "^2.8.1",
    "feathers": "^2.0.3",
    "feathers-authentication": "^0.7.12",
    "feathers-configuration": "^0.3.3",
    "feathers-errors": "^2.5.0",
    "feathers-hooks": "^1.7.1",
    "feathers-rest": "^1.6.0",
    "feathers-sequelize": "^1.4.0",
    "feathers-socketio": "^1.4.2",
    "fs-extra": "^2.0.0",
    "passport": "^0.3.2",
    "sequelize": "^3.30.2",
    "serve-favicon": "^2.3.2",
    "sqlite3": "^3.1.8",
    "winston": "^2.3.1"

**NodeJS version**:
7.4.0

**Operating System**:
Arch Linux

**Comment by daffl** [comment]
Did you get a chance to try it with NeDB instead of Sequelize as we discussed on Slack? If that is causing the same problem we'll have to do more digging but currently I'm not seeing anything else that could cause this behaviour in the app.

**Comment by Probotect0r** [comment]
Hey, just tried this with NeDB. Same code, same steps, same result. Still getting access denied on the `GET /messages` for all other users except for the first user to create a message.

**Comment by daffl** [comment]
Sorry this has been sitting for a while but you might have more luck now generating a new application with the new CLI. Quite a bit has changed there and this issue might not happen.
