### ISSUE TITLE
Problems with sorting 

### ISSUE THREAD

**Issue by pedrommuller** [feathersjs/feathers#519]
### Steps to reproduce
Hi guys,

I like to sort a query with pagination to the users' collection in MongoDB so far what I've been doing is to send a JSON structure like this:

```
query: {
  $limit: items,
  $skip: page*items,
  $sort: {createdAt: -1}
}
```
 
where could be items = number of rows, page = current page

this translate to this in the url:
http://localhost:3030/api/v1/users?$limit=10&$skip=0&$sort=%7B%22createdAt%22:-1%7D
decoded is this:
http://localhost:3030/api/v1/users?$limit=10&$skip=0&$sort={"createdAt":-1} 

in the query for the hook params I get:
```
{ 
  query: { '$limit': '10', '$skip': '0', '$sort': '{"createdAt":-1}' },
  provider: 'rest',
  token: undefined 
}

```
but it seems like $sort isn't working for me, how is the proper way to pass the query parameter?

### Expected behavior
Do sorting by specified field

### Actual behavior
doesn't sort

### System configuration

**Module versions** (especially the part that's not working):

**NodeJS version**:
V6.7.0
**Operating System**:
Ubuntu 14.04
**Browser Version**:
Chrome 55.02
**Module Loader**:
web pack 1.x

**Comment by daffl** [comment]
It's

```
http://localhost:3030/api/v1/users?$limit=10&$skip=0&$sort[createdAt]=-1
```

More info can be found in the [qs module documentation](https://github.com/ljharb/qs).

**Comment by pedrommuller** [comment]
@daffl so thanks, I installed it and stringify the object before pass it as query string and it works,

I'm just pasting my implementation for any reference:

From my client (react /redux / saga)

```
export function* fetchUsersAsync(action){
  try {
    let response = yield call(api.get,`/users?${qs.stringify(action.query)}`);
    yield put(actions.fetchUsersSucceed(response.data));
  } catch (e) {
    yield put(actions.fetchUsersFailed(e.message));
  }
}
```
parsed the query to:

```
{ query: { '$limit': '10', '$skip': '0', '$sort': { createdAt: '-1' } },
  provider: 'rest',
  token: undefined }

```
