### ISSUE TITLE
Event Ordering and Persistence (Questions)

### ISSUE THREAD

**Issue by idibidiart** [feathersjs/feathers#524]
1. What happens when many clients mutate the same resource on the server? Is the order of mutation events preserved for the consuming clients even when you run multiple instances and use feathers-sync... will the mutation events get to each client in the same order? 

2. If the network goes down, can clients request all events they missed since they lost network connectivity? Or are events not persisted on the server?

**Comment by daffl** [comment]
In general those questions are probably best answered by the websocket library you are using because Feathers does not do anything special other than wrap them but I'll give it a try:

1. It depends but in general yes, Socket.io processes events in the order they are received/sent.

2. There is no cache or any other server side state for that matter. If a client is not there it will not receive anything. For shorter offline periods clients will try to re-send their messages. I don't believe the server does the same thing though. Again, this might depend on the websocket library however.

**Comment by eddyystop** [comment]
As an small aside, database mutations on the server are not, in general, resolved in the same order they are started. Your only assurance is that mutations on the same record will be performed in order.

This determines the order in which events are emitted.

**Comment by idibidiart** [comment]
Thanks for clarifying the stuff about the socket library. But I think the issue with event ordering is not about a single instance of Feathers with idealized network connections but multiple instances of Feathers with unpredictable network connections. We could use something like Kafka to distribute events globally across Feathers instances with guaranteed order and stateless persistence (stateless in the sense that each client is responsible for recalling their last position in the queue of events.) But Kafka is a giant job to setup and administer. AWS has something similar that might be easier to use. But to simplify things, I won't care when events that happen very closely in time lose absolute order. I will also poll when I need to catch up , e.g. after network interruption or when client gets online initially.

**Comment by idibidiart** [comment]
@eddyystop just noticed your response

To clarify, mutations across services are promisified and chained via .then(), so each mutation awaits the resolution of one(s) it depends on before it is invoked. So no issue there.

**Comment by idibidiart** [comment]
@eddyystop to clarify, concurrency control in the scenario I'm working with is done via conditional updates to db. My concern has to do with fault recovery schemes involving storing and replaying events in order to recreate state after a crash. It's clearly outside the scope of Feathers.

**Comment by idibidiart** [comment]
I think the mutation events is not what I'm looking for in this context. If there is a distributed transaction being coordinated I want to capture the transaction state (searate from db state) so that if a client crashes or loses network in the middle of it I can recover. This clarifies a lot for me. Thanks for the answers and comments @daffl @eddyystop

**Comment by idibidiart** [comment]
So, the right way of handling failure during a distributed transaction turns out to be a feature that's built into the db, which is, namely, two-phase commit. 

I was also interested in persistence and ordering of mutation event for chat clients, where breakage in connectivity between instances of Feathers may cause to loss of some mutation events (chat messages in this case) and order of messages is obviously important from a UX perspective and that could be resolved with timestamp field in events and use of NTP to sync up servers' clocks. That is if we're worried about message order on a very high resolution time scale. 

With respect to persistence and UI state, it's obvious that we have to treat mutation events as signal (to refetch relevant data) and not assume that the mutation represents all that has changed.

Anyway, learned a lot from this exercise. Thanks.
