### ISSUE TITLE
Getting "Possible EventEmitter memory leak detected" warning when setting too much feathers service

### ISSUE THREAD

**Issue by StanleyAM** [feathersjs/feathers#528]
When I set too much feathers service(app.use), I will get the warning message:
> (node:12440) Warning: Possible EventEmitter memory leak detected. 65 connection listeners added. Use emitter.setMaxListeners() to increase limit

I already check #222, so can I ignore the warning? Or do I need to do some adjustments?
Thanks.

Below are versions of feathers packages:
> NodeJs version: v6.9.5
feathers@2.0.2
feathers-authentication@0.7.12
feathers-errors@2.5.0
feathers-hooks@1.6.1
feathers-memory@0.7.5
feathers-mongodb@2.6.0
feathers-rest@1.5.2
feathers-socketio@1.4.2
feathers-sync@0.1.1
socket.io-client@1.6.0

**Comment by daffl** [comment]
From [our FAQ]( FAQhttps://docs.feathersjs.com/help/faq.html#i-got-a-possible-eventemitter-memory-leak-detected-warning):

> This warning is not as bad as it sounds. If you got it from Feathers you most likely registered more than 64 services and/or event listeners on a Socket. If you don't think there are that many services or event listeners you may have a memory leak. Otherwise you can increase the number in the Socket.io configuration via io.sockets.setMaxListeners(number) and with Primus via primus.setMaxListeners(number). number can be 0 for unlimited listeners or any other number of how many listeners you'd expect in the worst case.

**Comment by metareason** [comment]
Updated FAQ link: 
https://docs.feathersjs.com/faq/readme.html#possible-eventemitter-memory-leak-detected-warning
