### ISSUE TITLE
Feathers generate not working

### ISSUE THREAD

**Issue by scq000** [feathersjs/feathers#530]
When I execute the command
```
feathers generate
```
in my project folder. But there aren't any files and folders generated in my project folder.And npm start is also not work.

The console shows:
```
 backend git:(master) ✗ feathers generate
local@SCQImac~$


Just found a `.yo-rc.json` in a parent directory.
Setting the project root at: /Users/kingdee

```

**Feathers version**
feathers-cli@1.2.7

**NodeJS version**:
v7.6.0

**Operating System**:
Mac OSX 10.11.6

**Comment by daffl** [comment]
The status message pretty much says it all:

```
Just found a `.yo-rc.json` in a parent directory.
Setting the project root at: /Users/kingdee
```

Means Yeoman found a `.yo-rc.json` in `/Users/kingdee` and will set the project there. Try removing `/Users/kingdee/.yo-rc.json` to get everything to work properly.

**Comment by scq000** [comment]
Thanks! It works!
