### ISSUE TITLE
[bug] `after all` hooks run before `after create/get/...` hooks

### ISSUE THREAD

**Issue by beeplin** [feathersjs/feathers#533]
### Steps to reproduce

simply create a new project with `feathers-cli` and generate a service names `someService` whatever, and in its hooks write:

```js
exports.before = {
  all: [() => console.log('before all')],
  find: [() => console.log('before find')],
  get: [() => console.log('before get')],
  create: [() => console.log('before create')],
  update: [() => console.log('before update')],
  patch: [() => console.log('before patch')],
  remove: [() => console.log('before remove')]
};

exports.after = {
  all: [() => console.log('after all')],
  find: [() => console.log('after find')],
  get: [() => console.log('after get')],
  create: [() => console.log('after create')],
  update: [() => console.log('after update')],
  patch: [() => console.log('after patch')],
  remove: [() => console.log('after remove')]
};
```

and then run ` app.service('someService').create({})`

it prints:

```
Feathers application started on localhost:3030
before all
before create
after all
after create
```
Clearly `after all` hook runs before `after create`, which is not what the docs say:

![image](https://cloud.githubusercontent.com/assets/13058150/24086828/8bf1f13a-0d51-11e7-9ba6-dea6d95c9e0c.png)

**Comment by daffl** [comment]
The first note about `all` hooks is correct. I removed the wrong one.

**Comment by beeplin** [comment]
In fact it might be better to follow the docs and make 'after all' hooks run _after all_ other hooks literally. This fits more situations during development.

**Comment by daffl** [comment]
We can keep track of it in a [new issue](https://github.com/feathersjs/feathers-hooks/issues/new) but it would be a major breaking change.

**Comment by eddyystop** [comment]
I would think there are some projects that expect the `all` after hook to
run last as per the docs. The issue just hasn't been noticed.

`feathers-profiler` would be an example. It now appears its measurements
are off.

**Comment by daffl** [comment]
Application level `after` hooks always run last. It's only when registering `all` hooks in the same object. Maybe the `all` key should just go away and you have to be more explicit either by using a function (`app.hooks({ after: function() {} })`) or adding the hook to every method explicitly.

**Comment by eddyystop** [comment]
Good to know about `app.hook`. Thanks.
