### ISSUE TITLE
Feathers Scaling Question

### ISSUE THREAD

**Issue by kethan** [feathersjs/feathers#534]
Hi All,
I am about to create PaaS like architecture similar to Parse or Firebase using feathers. But each services like UserService, AppService, DBService, FileService, etc will made as docker containers and will be scaled according to the traffic for each service. I will be using kubernates or Marathon to Orchestrate.

So how do i design this ? How will socket connection scale?
I have seen feathers-sync and few articles
but I don't know how to make proper use of it??
https://github.com/feathersjs/feathers/issues/121
https://github.com/feathersjs/feathers/issues/332
https://github.com/feathersjs/feathers/issues/157
https://github.com/feathersjs/feathers/issues/118
https://github.com/nanobox-quickstarts/nanobox-feathers

Can somebody give a example app structure so i can start with?

Thank You,
Kethan

**Comment by slajax** [comment]
HI @kethan your question is pretty broad and unfortunately some of this falls outside the feathers domain. Ideally you will want to use feathers-sync to synchronous events across your services. This would be similar to how you would do it with a "cluster" of processes. Aside from syncing events, the rest of feathers is stateless by default and so the normal rules would apply to scaling your infrastructure. We don't unfortunately have an "example" persay as infrastructure concerns are somewhat unique to your implementation but aside from syncing events, there isn't anything unique about feathers that should cause you much pain in this regard as long as you follow the best practices of the orchestration framework that you end up using.
