### ISSUE TITLE
Feature Query: Document Revisions

### ISSUE THREAD

**Issue by zusamann** [feathersjs/feathers#537]
What is the recommended approach to store document revisions in a way that is DB agnostic and can play well with existing DB/ORM plugins.

Is it even theoretically possible to have a `feathers-revisions` plugin or something that can handle this automatically?

Either way, how is something like this handled right now by various feathers users?

**Comment by ekryski** [comment]
Definitely possible. You might want to look at https://www.npmjs.com/package/feathers-mongodb-revisions, either for inspiration or to just use straight up.

It depends on your requirements really, but what I normally do is have a collection/DB table that has the history of the records or diffs/changes to the record, and each row/document has a foreign key to the most recent object.

Hopefully that answers your question. Going to close this to keep issues curated. It's not a core Feathers concern/function and is more of an engineering pattern in how you model your data based on the requirements of your app. There are a couple different ways that you can store revision data depending on your read/write load.

**Comment by omeid** [comment]
I think it is possible to have a library that abstracts away the common aspect of document revisions in the context of feathers services. Is there any reason that this couldn't be part of the feathers ecosystem?

**Comment by daffl** [comment]
Nope, no reason, if somebody wants to take it on, we're happy to help where we can.
