### ISSUE TITLE
const name are not generated correctly in services

### ISSUE THREAD

**Issue by idealley** [feathersjs/feathers#539]
### Steps to reproduce

Create a service with the generator:

`feathers generate service`

Type a composed name for the service name such as `name-separated-with-dashes`
Create a generic service with no authentication

This will create a folder `name-separated-with-dashes` in the `services`folder

In the newly created `index.js`of the service the `const` name that has been created is:

`name-separated-with-dashesService`

Which is not a valid javascript variable/const name.

On the other hand  the `index.js`at the root of the `services` folder imported the module correctly and the 'const' was passed correctly to the `configure()`method.
```
  const nameSeparatedWithDashes = require('./name-separated-with-dashes');
  app.configure(nameSeparatedWithDashes);
```

### Expected behavior
the `const` in the created service should also have been named with camel case and Service happened at the end of the name

### Actual behavior
the named stayed separated with dashes

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**: 6.5.0

**Operating System**: Mac

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by marshallswain** [comment]
Hi, @idealley good catch.  Would you mind opening this issue in the `generator-feathers` repo?  Please also include which version of the feathers-cli do you have installed.

**Comment by daffl** [comment]
This has been fixed in `feathers-cli@pre` (related issue: https://github.com/feathersjs/generator-feathers/issues/113).

**Comment by DaddyWarbucks** [comment]
I am not sure this is the best place to ask, but I do not want to open a new ticket and cannot find answers elsewhere.
Is there a convention for service names regarding camelCase vs dash-case?

**Comment by daffl** [comment]
Yes, they should always be `dash-case` (and lowercase) since HTTP does not guarantee case sensitivity.

**Comment by DaddyWarbucks** [comment]
Great point! I think I lost the forrest in the trees when "naming" the service through the CLI. I always made the path appropriate, but was unsure of the service "name".
