### ISSUE TITLE
Is possible setting different port for sokect.io to deploy GAE Fixble

### ISSUE THREAD

**Issue by ausir0726** [feathersjs/feathers#540]
hi ,

I want deploy feathers to GAE Fixble  ( google app engine )
Unfortunately, the loadbalancer of Google App Engine doesn't support websockets.
so , I need set socket.io listen port different with rest api ( 80 , 443 )
Is possible setting different port for sokect.io ? 

thanks .

**Comment by daffl** [comment]
You should be able to start the REST part like this:

```js
const http = require('http');

http.createServer(app).listen(80);
```

And then the socket server via:

```js
const socketServer = http.createServer().listen(3889);

app.setup(socketServer);
```

**Comment by ausir0726** [comment]
thanks for your help , even I have some static ip to handle with socket .
but I have a first step with deploy on GAE flexible .

this is my current index.js

```
'use strict';

const http = require('http');
const app = require('./app');
const port = process.env.PORT || app.get('port');
const socketServer = http.createServer().listen(3889);
app.setup(socketServer);
const server = http.createServer(app).listen(port);
//  app.listen(port);

server.on('listening', () =>
  console.log(`Feathers application started on ${app.get('host')}:${port}`)
);
```
