### ISSUE TITLE
User session based WebSockets

### ISSUE THREAD

**Issue by mkharibalaji** [feathersjs/feathers#544]
Hi Guys,
          First of all,it's a fantastic work guys.Keep Going 👍 I wanted to implement a user session based webscoket.Can you guide through some example how to implement in feathers.

**Comment by marshallswain** [comment]
@mkharibalaji what is a user session based WebSocket?  Maybe a socket that's authenticated with the user attached?

**Comment by mkharibalaji** [comment]
@marshallswain - yes,Your answer correlates with the user session based websockets.What I am looking for the one is something like the one in the below link

http://stackoverflow.com/questions/12182651/expressjs-websocket-session-sharing

I am also expecting with the issue  #421,#388  (w.r.to Channel based chat rooms )

Say if a user create's a user service and he want's to emit the saved user data only to his session rather than emitting the data to all the subscribers which is somewhat similar to the #388 but in an authenticated way.

**Comment by marshallswain** [comment]
Can you identify the differences between what you want to implement and what we have implemented with `feathers-authentication`?

**Comment by daffl** [comment]
What you are asking should already be possible. Related:

- https://docs.feathersjs.com/real-time/filtering.html is also relevant here
- https://docs.feathersjs.com/help/faq.html#how-do-i-create-channels-or-rooms

**Comment by mkharibalaji** [comment]
Thanks a lot @daffl @marshallswain I will give it a spin and let you know.

**Comment by marshallswain** [comment]
Please reopen if you need more help.
