### ISSUE TITLE
Issue associating hook

### ISSUE THREAD

**Issue by nanomag** [feathersjs/feathers#548]
Hey,
Sorry if I'm posting in the wrong channel but I'm new in Feathers.

*Problem:* I'm trying to associated a new hook to `find` but I always get timeout.

New hook:
```
'use strict';

module.exports = function(options) {
  return function(hook) {
    const user = hook.params.user;
    const productService = hook.app.service('products');

    return productService.find({
      query: { userId: user._id }
    })
    .then((page) => {
      const products = page.data;

      hook.data = { products };

      return hook;
    });
  };
};
```

Hook call:
```
exports.before = {
      ...
      find: [filterByUser()],
      ...
}
```

Call in the frontend:
```
app.service('products').find()
        .then((result) => {
          console.log('Products!', result);
        }).catch((error) => {
          console.error('Error getting products!', error);
        });
```

Error raised:
`Error getting products! Error: Timeout of 5000ms exceeded calling products::find`

Thanks for your help.

**Comment by marshallswain** [comment]
Nothing stands out to me.  Maybe try setting some breakpoints: https://blog.feathersjs.com/debugging-feathers-with-visual-studio-code-406e6adf2882

**Comment by daffl** [comment]
`hook.data` will only be set for `create`, `update` and `patch`, not for `find`.

To change a `find` query to include the current user in the query just update `hook.params.query` in the  hook like this:

```js
'use strict';

module.exports = function(options) {
  return function(hook) {
    const user = hook.params.user;

    hook.params.query.userId = user._id;

    return hook;
  };
};
```

The timeout probably happens because your hook is recursively calling itself (by running `productService.find` which will run the same hook and so on).

**Comment by nanomag** [comment]
@daffl It worked perfectly! Thank you so much!
