### ISSUE TITLE
Add Flow typings

### ISSUE THREAD

**Issue by Andreyco** [feathersjs/feathers#550]
Flow, similarly to Typescript, helps you keep type safety - it's static type checker.

It would be great to ship Flow typings with the project or publish via Flow Typed, which is central repository for Flow library definitions.

**Comment by eddyystop** [comment]
None of the core-team use Flow (or TypeScript) so Flow typings would have to be a community contribution, like the TypeScript ones are.

We would be delighted to get a PR from you.

**Comment by Andreyco** [comment]
TY for response. Despite this is long run, let's see what community can do...

**Comment by ForsakenHarmony** [comment]
if you want it then you have to start yourself, not wait for the community

**Comment by eddyystop** [comment]
@Andreyco We are **very happy** to help those who want to contribute to Feathers, who want to make it better, easier or more convenient in some way.

The Feathers core-team consists of 6 part-time people and we  contribute (ridiculous amounts of time) working on foundational things.

**Comment by rayfoss** [comment]
PayPal has been [using them](https://www.youtube.com/watch?v=RNGCrz5Rx14)... Would love to see better support for it in Feathers... can't find docs on it for Feathers
