### ISSUE TITLE
Tests fail if a custom folder is chosen using the generator

### ISSUE THREAD

**Issue by kokujin** [feathersjs/feathers#554]
If one choses a folder other than the default "src" folder, the tests fail.
````
> f_gen_test@0.0.0 mocha /home/kokujin/Development/Research/f_gen_test
> mocha test/ --recursive

module.js:471
    throw err;
    ^

Error: Cannot find module '../src/app'
`````

**Comment by marshallswain** [comment]
Issue moved to [feathersjs/generator-feathers #202](https://github.com/feathersjs/generator-feathers/issues/202) via [**ZenHub**](https://www.zenhub.com/)
