### ISSUE TITLE
feathers-loopback-connector plugin

### ISSUE THREAD

**Issue by kethan** [feathersjs/feathers#556]
Hi All,
**I am sorry to post here and it is not an issue with feathers**

https://github.com/kethan/feathers-loopback-connector.

This is my first attempt to create a feathers plugin. I created for loopback-connector.
Still, it is in alpha stage.
Can anyone look at the code and give their feedback.
I tried running feathers-service-tests I am having 4 issues can anyone help me resolve it.

Thanks.

**Comment by marshallswain** [comment]
@kethan, I'll try to look soon.  What is the benefit that this adapter will provide?
I'm not familiar with loopback connector. Will this plugin provide access to the databases listed in this page? http://loopback.io/doc/en/lb2/Database-connectors.html

**Comment by kethan** [comment]
@marshallswain Yes you are right it will work all the databases listed and any other built for future too it will work.

**Comment by daffl** [comment]
@kethan This looks great, nice job! I can definitely help with the failing tests. Can I just clone your repository and run the tests to see what is happening or is there any setup involved?

**Comment by kethan** [comment]
@daffl I am just a beginner and  I learned seeing many of your repo you are an expert friend. You can just clone it and run the tests. But please note the code is not perfect and optimised as yours.

**Comment by kethan** [comment]
@marshallswain Did you check? was it useful?
@daffl Did you clone? Were you able to run the tests?

**Comment by daffl** [comment]
@kethan Yep I cloned it and it looks great (sorry, I've been meaning to reply earlier but I was hoping I could just make a PR but didn't get a chance yet)! I can see why those tests are failing. Do you know if nested `$or` queries are possible with Loopback at all? How would they look like?

**Comment by kethan** [comment]
@daffl Thanks.
Hi yes it is possible
```js
//it should be like this 
or : [
or: [conditions],
or: [conditions],
]
//From loopback docs
//Example using the “or” operator to finds posts that either have title of “My Post” or content of “Hello”.

Post.find({where: {or: [{title: 'My Post'}, {content: 'Hello'}]}}, 
          function (err, posts) {
            ...
});
//More complex example. The following expresses (field1= foo and field2=bar) OR field1=morefoo:

{
   or: [
     { and: [{ field1: 'foo' }, { field2: 'bar' }] },
     { field1: 'morefoo' }
   ]
 }

```

**Comment by daffl** [comment]
Thanks again for sharing this. I'm closing this issue since I never used Loopback and unfortunately don't have the time to look into it more. I added it to [our Feathers list](https://github.com/feathersjs/awesome-feathersjs) though.
