### ISSUE TITLE
[Question] app.configure without scope?

### ISSUE THREAD

**Issue by cpsubrian** [feathersjs/feathers#558]
Since I'm fairly new to using feathers, I was wondering the philosophy behind the pervasive use of scope in various parts of the API. I used to design APIs this way as well but lately have preferred more functional/explicit designs.

For example:

```
function myPlugin (options) {
  return function () {
    var app = this
  }
}
app.configure(myPlugin({}))
```

vs.

```
function myPlugin (options) {
  return function (app) {}
}
app.configure(myPlugin({}))
```

I understand that it would be a huge breaking change (and thus probably not realistic), but at least in this case it could be changed in a backwards compatible way (but other things like hooks and services are tricker).

**Comment by marshallswain** [comment]
There's a comment about this in the code: https://github.com/feathersjs/feathers/blob/master/src/application.js#L110

**Comment by daffl** [comment]
This was how Express used to do it. It wouldn't be a huge change to additionally pass the `app` as an argument.

**Comment by cpsubrian** [comment]
@daffl Indeed, and I could easily override with my own version that does this ... was more just curious if it was a core API design opinion.

**Comment by daffl** [comment]
This has been added in v3 (see linked PR)
