### ISSUE TITLE
Search by attributes starting with `_` fail (no results)

### ISSUE THREAD

**Issue by nriesco** [feathersjs/feathers#563]
### The problem

A full project to reproduce this issue can be found here: https://github.com/riescorp/feathers2-mongodb-error 

Summary: search by any attribute starting with `_` fails. I tried to replicate the error on feathers-rest (https://github.com/feathersjs/feathers-rest/pull/112) and feathers-mongodb (https://github.com/feathersjs/feathers-mongodb/pull/87) but both of them it works. Feathers seems like the obvious next step but the tests are quite complex to me and I don't fully understand feathers' architecture. I suspect there might be some sort of hook filtering parameters with `_`

#### Step 1: install @pre

`npm install -g feathers-cli@pre`

#### Step 2: generate app

`feathers generate app`

```
? Project name feathers2-mongodb-error
? Description
? What folder should the source files live in? src
? Which package manager are you using (has to be installed globally)? npm
? What type of API are you making? (Press <space> to select, <a> to toggle all,
<i> to inverse selection)REST, Realtime via Socket.io
```

#### Step 3: DB + model

`feathers generate service`

```
? What kind of service is it? MongoDB
? What is the name of the service? country
? Which path should the service be registered on? /country
? What is the database connection string? mongodb://localhost:27017/feathers_2_mongodb_error
```

#### Step 4: Populate

```
curl --request POST \
  --url http://localhost:3030/country \
  --header 'cache-control: no-cache' \
  --header 'content-type: application/json' \
  --header 'postman-token: 4eeeafdb-b24f-ce0a-5b6e-000e038db1ec' \
  --data '{\n  "name": "USA",\n  "code": "US"\n}'
```

```
curl --request POST \
  --url http://localhost:3030/country \
  --header 'cache-control: no-cache' \
  --header 'content-type: application/json' \
  --header 'postman-token: 4eeeafdb-b24f-ce0a-5b6e-000e038db1ec' \
  --data '{\n  "name": "Chile",\n  "code": "CL"\n}'
```

### Expected behavior

Searching by an existing `_id` should return an element.

[http://localhost:3030/country/58eb934727eeb422c899f430](http://localhost:3030/country/58eb934727eeb422c899f430) should return one element (assuming that `_id` is an existing one of course)

### Actual behavior

Searching by `_id` key is not working. Actually searching by any field starting with `_` just won't show any results.

##### Show all

[http://localhost:3030/country](http://localhost:3030/country)

##### Search by code (OK)

[http://localhost:3030/country?code=US](http://localhost:3030/country?code=US)

##### Get by _id (OK)

(use a valid id here)

[http://localhost:3030/country/58eb934727eeb422c899f430](http://localhost:3030/country/58eb934727eeb422c899f430)

##### Search by _id (FAIL)

[http://localhost:3030/country?_id=58eb934727eeb422c899f430](http://localhost:3030/country?_id=58eb934727eeb422c899f430)

### System configuration

NPM: 3.10.10
node: v6.10.2
OS: Darwin Gris.local 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64
feathers: 2.0.0

**Comment by ekryski** [comment]
Thanks for creating the issue @nriesco! Great job! We'll dig into it as soon as we can.

**Comment by daffl** [comment]
I just tried to reproduce and I am not seeing the problem. One thing to note for the MongoDB adapter however is that all properties need to be converted to the actual type you are looking for in a `before` hook. Mongoose does that already (since it has the schema) but with the plain MongoDB driver you have to convert booleans, numbers and in the case of `_id` Mongo object ids yourself.

Searching for `_id` was possible using this hook:

```
const ObjectID = require('mongodb').ObjectID;

module.exports = function (options = {}) {
  return function (hook) {
    if(hook.params.query._id) {
      hook.params.query._id  = new ObjectID(hook.params.query._id);
    }

    return Promise.resolve(hook);
  };
};
```

**Comment by ekryski** [comment]
> One thing to note for the MongoDB adapter however is that all properties have to be converted to the actual type you are searching for in a before hook. Mongoose does that already (since it has the schema) but with the plain MongoDB driver you have to convert booleans, numbers and in the case of _id Mongo object ids yourself.

@daffl Yeah I had mentioned that in Slack as well. @nriesco said it didn't matter whether you used `_id` or something like `__foo`. My gut feeling is it is a cohersion issue or maybe mongoose is doing something weird with keys prefixed with `_`.

**Comment by daffl** [comment]
It must be something else then. @nriesco I'd also make sure that you have the latest `feathers-cli` (*not* `@pre`). `feathers --version` should show v2.0.5

**Comment by nriesco** [comment]
@daffl Thank you for your time, I think the issue can be solved with the code you describe. Although it is somehow an issue, searching by other attributes starting with `_` it is quite infrequent. So I guess just a note on the docs would suffice.

**Comment by daffl** [comment]
I still feel like the `_` is a red herring but if you can share a simple repository to reproduce we can look into it more. I added a note how to convert query values in https://github.com/feathersjs/feathers-docs/pull/551 so I hope it's ok to close this.
