### ISSUE TITLE
Suppress transmission of stack traces to socket.io clients?

### ISSUE THREAD

**Issue by matt222r** [feathersjs/feathers#564]
For instance, using the example of feathers-chat, I could issue something like this from a feathers-client:

```
app.get( 'messages' ).patch( -99999, { bogus: 5 } ).catch( (err) => {
     console.log( err );
});
```

and get a server stack trace on the client. I'd prefer to suppress the socket.io stack traces, just like they are for 404s, etc. I'm using

`
Error.stackTraceLimit = 0;
`

in production right now. Of course, that removes all the stack traces, including the ones I might like to log, etc. Maybe you guys have a better way?

**Comment by daffl** [comment]
You can modify the error in an [error hook](https://docs.feathersjs.com/api/hooks.html) on the server. I think removing specific stack traces should be possible with something like

```js
app.service( 'messages' ).hooks({
  error(hook) {
    // For external calls, remove the `stack` from the error
    if(hook.params.provider) {
      delete hook.error.stack;
    }
  }
});
```

**Comment by ekryski** [comment]
Yup that works. We've done that on a few projects. You also likely want to delete `hook.error.hook`.

**Comment by matt222r** [comment]
That code works as written. Thank you all.

It's worth noting that the stack trace in my example is actually a client stack trace, not a server stack trace. However, the server stack trace does fly across the wire (it appears to be gzip'd), if you don't have a solution like the above in place.
