### ISSUE TITLE
Re-using services

### ISSUE THREAD

**Issue by Mattchewone** [feathersjs/feathers#566]
In ref to feathers-hooks issue [#154](https://github.com/feathersjs/feathers-hooks/issues/154)

There was an issue when using a service under a different route path, ie:
```
  app.use('/projects', createService(options));

  const service = app.service('/projects');

  app.use('/me/projects', service)
```
The __hooks object was being overwritten, which has since been fixed but now in the console there is the following output:
```
express:router <anonymous>  : /projects +8ms
feathers-errors NotFound(404): Page not found +1ms
express:router <anonymous>  : /projects +0ms
finalhandler default 404 +1ms
finalhandler cannot 404 after headers sent +0ms
Error: Can't set headers after they are sent.
  at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:356:11)
  at ServerResponse.header
....
```

It seems as though it is trying to route it again and not finding the route and trying to throw NotFound error but a response has already been set with headers. 

As per @daffl suggestion to post this in here.

Thanks

**Comment by daffl** [comment]
Thank you! This is definitely an issue. I really thought I tested it somewhere but it doesn't seem so.

**Comment by Mattchewone** [comment]
@daffl Been having a little dig into this and with some debugging, I can see that after the `/me/projects` call that the not-found handler is called which I believe is then trying to set headers even though they are already set from the service call. 

Here is a little output I have put together:
```
  feathers:rest getHandler
  feathers:rest REST handler calling `find` from `/projects` +5s
  service:call lookup
  info: after: projects - Method: find
  feathers-rest formatter..
```
```
  feathers:rest getHandler
  feathers:rest REST handler calling `find` from `/me/projects` +5s
  service:call lookup
  info: after: me/projects - Method: find
  feathers-rest formatter..
  feathers-errors not-found
```

I can't quite work out where a next() is being called to trigger the `not-found` handler to catch the request.

I found a work-a-round but would be good to know what is triggering the next call.
```javascript
import errors from './index';

export default function() {
	return function(req, res, next) {
		if (!res.headersSent) {
			next(new errors.NotFound('Page not found'));
		}
	};
}
```

If you have any suggestions that would be awesome.
