### ISSUE TITLE
Explicit authentication for emitting messages but not for listening

### ISSUE THREAD

**Issue by knappdev** [feathersjs/feathers#567]
### Steps to reproduce
REST API works with one time authentication. But socket needs authentication everytime

import socketio from 'feathers-socketio/client';

this.app = feathers()
      .configure(socketio(socket))
      .configure(hooks())
      .configure(authentication({
        storage: AsyncStorage // To store our accessToken
      }));
app.io.emit('messages::create', {
  "text": "I really have to iron"
}, (error, message) => {
  console.log('Todo created', message);
});

emit results in no output as socket is not explicitly authenticated

### Expected behavior
we can listen to server message without explicit authentication. shouldn't the behaviour be same for both emitting and listening to messages

### Actual behavior
 console.: Todo created undefined

**React Native Version**:0.43.4

**Comment by daffl** [comment]
If you `console.log(error)` instead of the message you will see that you get the not authenticated error.

This is exactly the same call that the client service using `this.app.service('messages').create({ text }).then(message => {}).catch(error => {})` does internally.

**Comment by knappdev** [comment]
@daffl I agree. As you said I am getting Not Authenticated error. But the issue I want to point out is that why we can receive messages without authenticating the socket?

**Comment by marshallswain** [comment]
Because you need to filter messages on the server.  There are so many different types of auth implementations that it's impossible to even provide a basic setup out of the box.

https://docs.feathersjs.com/api/events.html#event-filtering

**Comment by knappdev** [comment]
@marshallswain thanks for pointing that out. Then this behavior is as per implementation.

**Comment by daffl** [comment]
As @marshallswain pointed out, you have to explicitly add event filtering. We are working on improving this (see https://github.com/feathersjs/feathers/issues/388#issuecomment-239564856) but for now this is indeed how it is intended. Going to close this issue.
