### ISSUE TITLE
Protect ressources

### ISSUE THREAD

**Issue by Clowning** [feathersjs/feathers#568]
Hi there, first of all, thanks for Feathers it's awesome! 

But i've a question about policies !

I've a Notifications table linked with a user_id and more endpoint like that. Datas are linked to a user each time ! So how can i filter to return only ressources of a specific user ? 

If i call http://domain.me/notifications and how can i have only user notification based on JWT ? 
Or when a user call http://domain.me/notifications/2 if the user_id ressource is different from id in JWT ? 

Thanks by advance :) !

**Comment by victorm95** [comment]
Hi, you can use the hook `queryWithCurrentUser`.

https://docs.feathersjs.com/api/authentication/hooks.html#querywithcurrentuser

**Comment by daffl** [comment]
You can use what @victorm95 suggested or [write your own hook](https://docs.feathersjs.com/api/hooks.html). The authenticated user will always be available in `hook.params.user` and the query against the database can be modified by changing `hook.params.query`.
