### ISSUE TITLE
Is it possible to use feathers client with the `fs` module?

### ISSUE THREAD

**Issue by camstuart** [feathersjs/feathers#571]
I'm working with tabris-js for mobile development and attempting to use the feathers client.

However this platform does not have `fs` available. Is that a show stopper, or can I stub `fs` and use in memory auth storage, or perhaps even write my own?

**Comment by eddyystop** [comment]
See if the new feathers-fs is what you need.

**Comment by camstuart** [comment]
Not quite i'm afraid; `path` is also not available. So I wound up with a circular dependancy:

`require('feathers-fs');` results in `cannot find module 'path'`

So I add before it, the compatibility module `tabris-js-node` which results in `cannot find module 'fs'`

**Comment by marshallswain** [comment]
The fs package for sure won't work.  You might check out using an fs API-compliant package, like https://www.npmjs.com/package/browserify-fs.

**Comment by camstuart** [comment]
Good call @marshallswain that gets past that problem, and now Tabris complains it's missing `stream` I wonder how far this will go!

**Comment by marshallswain** [comment]
https://www.npmjs.com/package/stream-browserify

**Comment by camstuart** [comment]
It's odd. installing that package and `require('stream');` as the docs suggest still results in `Cannot find module stream`

Even if I comment out all my other code in that file

**Comment by daffl** [comment]
The `fs` module should not be required anywhere by the client. What does your setup look like?

**Comment by marshallswain** [comment]
@camstuart, based on [the name in that package](https://github.com/substack/stream-browserify/blob/master/package.json#L2), I'd think you would have to do `require('stream-browserify')`.  There may be some convention for using it the other way if you're using Browserify, but I don't know.

**Comment by capotti** [comment]
A general section in the documentations about "extending tabris with node modules" could help.
Expecially to understand, how to use standard libraries like fs, path, util, ...
most packages use `var fs = require('fs');` itself
How to solve?

**Comment by marshallswain** [comment]
What is Tabris

**Comment by daffl** [comment]
I'm going to close this since I still think the problem was requiring the wrong module. We can reopen if that is not the case.
