### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by paranoid-android** [feathersjs/feathers#574]
I am a huge fan of Feathers. I've been using it over a year. However, I want to add some authentication and authorization. Specifically, I want to authenticate using Google OAuth. I then want to give that user access to some new routes. For example, I want unauthenticated users to have access to these routes:

```
app.get('/login', function(req, res) {
  res.render('views/login.html', {});            
});    

app.get('/about', function(req, res) {
  res.render('views/about.html', {});            
});    

app.get('/contact', function(req, res) {
  res.render('views/contact.html', {});            
});    

app.get('/', function(req, res) {
  res.render('views/index.html', {});            
});
```
However, a user must be authenticated before being able to access the following routes:
```
app.get('/dashboard', function(req, res) {
  res.render('views/dashboard/index.html', {});            
});    

app.get('/dashboard/report', function(req, res) {
  res.render('views/dashboard/report.html', {});            
});    

app.get('/registered', function(req, res) {
  res.render('views/registered.html', {});            
}); 
```

The reason I'm opening an issue is because, the [documentation](https://docs.feathersjs.com/guides/auth/readme.html) isn't very clear in regards to how to do this. In addition, the "Auk" release has muddied the waters a bit. I think some updated authentication docs would be super helpful and valuable to the community. 

Thank you for your consideration and work on Feathers.

**Comment by daffl** [comment]
There is now a recipe showing how to use Feathers authentication with Express middleware at https://docs.feathersjs.com/guides/auth/recipe.express-middleware.html
