### ISSUE TITLE
TypeScript: Move Service definition into seperate repo to make feathers-reactive work

### ISSUE THREAD

**Issue by j2L4e** [feathersjs/feathers#575]
We have a problem with typing feathers-reactive:

The standard feathers behavior includes service methods returning a Promise

    get?(id: number | string, params?: Params, callback?: any): Promise<T>;

Feathers-reactive overrides service methods and changes their return type:

    get?(id: number | string, params?: Params, callback?: any): Thenable<T> & Observable<T>;

The way TypeScript works is that it looks through the list of typings and uses the first one that matches the method name and its arguments. Thus a method _cannot be overridden_ with a method taking the same arguments and argument types but returning a type different from the original method's return type.
Unfortunately this is exactly what feathers-reactive does. I see two options here:

-  change the service method's return type to `Promise<T> & Observable<T>` and tack method stubs on the promises return by service methods to warn the user when they use `service.whatever()` as an Observable without having `feathers-reactve` installed
- split the definitions of `service` from the `feathers` into `feathers-types-service-promise` so they don't conflict with `feathers-reactive`'s typings when you install that.

Option 1 pollutes the service for non-rx-users, option 2 requires them to install one more dependency in both cases.

**Comment by daffl** [comment]
I think the ideal way of solving this problem would be by implementing https://github.com/feathersjs/feathers-reactive/issues/43 suggested by @garbles which would make `feathers-reactive` usable like this:

```js
import {Observable} from 'rxjs';
import app from './app'; // some feathers app

const messages = app.service('messages');

const messages$ = Observable.from(messages.find());
```

I definitely want to move away from the mixin approach that some plugins have and have a pre-defined core interface that is not going to be changed by any plugin.
