### ISSUE TITLE
Exposing both REST/Socket interfaces behind API prefix

### ISSUE THREAD

**Issue by claustres** [feathersjs/feathers#579]
I have some hard time enabling both REST/Socket interfaces behind an API prefix on my Feathers app and I cannot find much documentation on this, so I open an issue.

First, in order to get rid of the API prefix internally I added this small function on the Feathers app in the frontend/backend side:
```
app.getService = function (path) {
  return app.service(app.get('apiPath') + '/' + path)
}
```
Indeed, retrieving Feathers services is always based on a path and not on a service name so you need to know the details of the API prefix, don't know if there is a better way to abstract the code from this ?

Then I prepend the API path to all my service pathes when declaring them. I configured the auth module like this in the backend:
```
authentication: {
    strategies: [
      'jwt',
      'local'
    ],
    path: API_PREFIX + '/authentication',
    service: API_PREFIX + '/users'
  }
```
and like this in the frontend:
```
app.configure(feathers.authentication({
    storage: window.localStorage,
    path: config.apiPath + '/authentication'
  }))
```
Last, I configured my socket end point like this in the frontend/backend:
```
app.configure(socketio({
  path: app.get('apiPath')
}))
```

If my client app used sockets it worked fine but my REST API was broken responding error *code 0 "Transport unknown"*. It seems that having the same end point for socket/REST is not a good idea (although before adding the prefix it seemed to work), so I modified the API prefix for sockets only by adding a `ws` suffix. Now everything is fine when my client uses socket, I can also reach my REST end points with POSTMAN for instance. However, if I switch my client app transport to REST not sockets, then I get *401 (Unauthorized)* response from my REST end points although if I made requests through POSTMAN it works. On the client side the calls to `app.authenticate()` and `app.passport.verifyJWT(accessToken)` seems to be fine but then when I call my users service the auth token does not seem to be attached...

My Feathers versions are the following:
```
    "feathers": "^2.1.1",
    "feathers-authentication": "^1.2.2",
    "feathers-authentication-jwt": "^0.3.1",
    "feathers-authentication-local": "^0.3.3",
    "feathers-configuration": "^0.4.1",
    "feathers-errors": "^2.6.3",
    "feathers-hooks": "^2.0.1",
    "feathers-hooks-common": "^3.0.0",
    "feathers-levelup": "^1.1.1",
    "feathers-mongodb": "^2.8.0",
    "feathers-nedb": "^2.6.2",
    "feathers-rest": "^1.7.1",
    "feathers-socketio": "^1.5.2",
```

Thanks for your help and continue developing this great framework !

**Comment by claustres** [comment]
My bad, the error was that I initialized the authentication module **before** the REST module so client hooks for the token were not correctly registered, you can close the issue.

I suggest this PR https://github.com/feathersjs/feathers-docs/pull/683

**Comment by marshallswain** [comment]
Hey, terrific issue, @claustres!  I just merged your docs PR.  So does everything work you would expect once you fix the plugin order?

**Comment by claustres** [comment]
Yes it seems to be so far, by configuration my app can now correctly switch between websockets/REST.

**Comment by rishavs** [comment]
Is it possible to have API_Prefix as a config json attribute where everywhere in the code this prefix is used?

**Comment by rishavs** [comment]
@claustres I am currently using that post. Thanks for it.

Here I meant if we can have API_Prefix as a setting itself so that it is always available by default and we don't have to change anything in the code to implement it. This IMO is a very essential feature which I believe every api developer will be using at some point in time, and it will be nice to have it as configuration only.

**Comment by claustres** [comment]
Well I think it is not so important to make it part of the Feathers core. Indeed it can also be managed using a reverse proxy without requiring any changes in a standard Feathers app. By only changing the default config a little bit then override `app.service()` you can easily manage API prefix.

**Comment by daffl** [comment]
Funny enough, API prefixes are actually _not_ the best way to version REST APIs. The GitHub API got it right by using the [versioning media types in the Accept header](https://developer.github.com/v3/media/#request-specific-version).
Anyway, non-expressified Feathers apps should now also be properly usable as sub-apps:

```js
const app = express(feathers());

const v1 = feathers();

v1.use('/messages', {
  async get(id) {
    return { id };
  }
});

app.use('/v1', v1);

app.service('/v1/messages').get()
```

**Comment by Brianchat** [comment]
Could you expand a bit on what you mean by non-expressified?

**Comment by daffl** [comment]
The one from the example that is just calling `feathers()` instead of `express(feathers())`.
