### ISSUE TITLE
Koa version

### ISSUE THREAD

**Issue by pspeter3** [feathersjs/feathers#58]
I can imagine the desire for something supports the feathers service api but with Koa. Do you guys have thoughts on this?

**Comment by myuseringithub** [comment]
I wish you had Koa support. Its an amazing framework limiting it to Express isn't. 
Thanks

**Comment by marshallswain** [comment]
@myuseringithub you can try using @daffl's [comment](https://github.com/feathersjs/feathers/issues/58#issuecomment-41423120) to create an adapter.  We haven't seen that Koa provides us with anything that we can't do with the current version, but if you see the need, please fill it.  We will be as supportive of your work as we possibly can with what time we have.

**Comment by myuseringithub** [comment]
Thanks @marshallswain , currently I won't use feathers. I think it adds an abstraction layer, that  I don't like. I'm turning into building server with pure nodejs, as it gives more control. & I've implemented a simple version of CRUD REST API for Rethinkdb that fits my needs. 
Would really like to see feathers as separated modules that are added as a supplement to the main server/app not a framework that should be extended, and will end up being the app itself.
Still learning, maybe afterward will have a different view or would see more options.
