### ISSUE TITLE
is .remove(id, {cascade:true}) actually supported?

### ISSUE THREAD

**Issue by PavelPolyakov** [feathersjs/feathers#585]
### Steps to reproduce

In the documentation it's stated that it's possible to send `cascade:true`, and `feathers` would, probably, remove all the connected entities from the database:
https://docs.feathersjs.com/api/socketio.html#remove

However I can not find anything about it in the driver:
https://github.com/feathersjs/feathers-nedb/blob/master/src/index.js

 and in the feathers code itself (searched by the keyword `cascade`)

### Expected behavior
To have an option of the `cascade` removal.

### Actual behavior
Probably the documentation is outdated.

Probably I should try first, but I'm not yet there in my project. Please, share the light.

Regards,

**Comment by bertho-zero** [comment]
It is a property of the query that can be used in a hook, nothing more I think.

**Comment by PavelPolyakov** [comment]
@bertho-zero ah that, yes, that would explain.
Let's wait for the maintainer's view, or I would close it later.
Thank you.

**Comment by marshallswain** [comment]
@bertho-zero is correct.

**Comment by PavelPolyakov** [comment]
@marshallswain 
thank you
