### ISSUE TITLE
Override service object method dynamically

### ISSUE THREAD

**Issue by claustres** [feathersjs/feathers#586]
I have a Feathers app where I want to be database-agnostic, this means that I only know the DB adapter to be used at run time. So I can't create my services by extending Feathers classes/proto but instead I have to dynamically add the methods of my services on top of the basic Feathers service objects created depending on my configuration. As far as I understand by looking at the documentation and existing issues, Feathers services are created using https://github.com/daffl/uberproto. So I started using https://github.com/daffl/uberproto#mixins to create my services like this:
```javascript
...
const createFeathersService = require('feathers-' + app.db.adapter)
let service = createFeathersService()
const serviceMixin = require(name + '.service')
service.mixin(serviceMixin)
```

Everything worked fine with hooks calling some of my service methods. However when I had to override the default service method **create** on one of my service it stoppped working. It seems that the method never returns (hooks are not called anymore and a timeout is raised on the client side). According to the documentation I can't find the mistake in this code:
```javascript
create(data, params) {
    return new Promise((resolve, reject) => {
      // In some cases I don't have to create object in DB
      if (...) {
        // Tested with the debugger this statement is reached but then nothing more happens
        resolve(data)
      }
      // Otherwise call the default create method to fill the DB in
      else {
        resolve(this._super(data, params))
      }
    })
  }
```

My Feathers versions are the following:
```
    "feathers": "^2.1.1",
    "feathers-authentication": "^1.2.2",
    "feathers-authentication-jwt": "^0.3.1",
    "feathers-authentication-local": "^0.3.3",
    "feathers-configuration": "^0.4.1",
    "feathers-errors": "^2.6.3",
    "feathers-hooks": "^2.0.1",
    "feathers-hooks-common": "^3.0.0",
    "feathers-levelup": "^1.1.1",
    "feathers-mongodb": "^2.8.0",
    "feathers-nedb": "^2.6.2",
    "feathers-rest": "^1.7.1",
    "feathers-socketio": "^1.5.2",
```

Thanks for your help and continue developing this great framework !

**Comment by daffl** [comment]
What did you need to override/extend that couldn't be done using [Hooks](https://docs.feathersjs.com/api/hooks.html) directly (which ideally should be database independent)?

**Comment by claustres** [comment]
Depending on the create request options I would like to avoid creating the object in the database, cannot find how to do this with a hook except by raising a "fake" error...

But I also wonder why my approach does not work ?

Thanks for your help

**Comment by eddyystop** [comment]
Setting `hook.result` in a before hook will skip the DB call. Could you do that?

**Comment by claustres** [comment]
OK I will try this but I probably have some refactor to do. Indeed my processing rely on "after" hooks so I wonder if I set the result in a before hook will it stop the complete hook chain or simply the DB adapter call ?

**Comment by eddyystop** [comment]
It will skip the DB call and start running the after hooks. https://docs.feathersjs.com/guides/step-by-step/basic-feathers/testing-hooks.html

**Comment by claustres** [comment]
Just to confirm that it worked fine, thanks very much, however I still  wonder why the approach to override service method does not work ?

**Comment by daffl** [comment]
It will only work when registering the service because Feathers adds [its own functionality](https://docs.feathersjs.com/api/application.html#servicepath) and [methods](https://docs.feathersjs.com/api/services.html#feathers-functionality) around it.

**Comment by daffl** [comment]
It will only work when registering the service not later because Feathers adds its [own functionality](https://docs.feathersjs.com/api/application.html#servicepath) at that time which will be lost once you overwrite it.

**Comment by claustres** [comment]
Belived the goal of ubberproto was to avoid such overwrite by keeping track of previous methods with _super doesn't it ?

**Comment by daffl** [comment]
Yes but in this case it will mess up the order (it will run the Feathers modified method first and then your own code which is almost never the intention).

I'd really make sure that all methods are defined during registration to avoid any weirdness. We intentionally took out Uberproto references (`.extend` etc.) from the documentation in favour of ES6 class extension and hooks (which can be added dynamically at any time).

**Comment by claustres** [comment]
OK got it, thanks for the explanation
