### ISSUE TITLE
hook.path is not set in filter function

### ISSUE THREAD

**Issue by mxgr7** [feathersjs/feathers#589]
### Steps to reproduce

```
app.service('example').filter(function (data, connection, hook) {
  if (hook.path !== 'example')
    throw new Error(`hook.path is ${hook.path}`)
  return data;
})
```

### Expected behavior
`hook.path` should be set (to `'example'` in the above example), therefore the filter above should not throw an error.

### Actual behavior
`hook.path` is `undefined`, so the above filter throws an error.

### System configuration

Tested with feathers version 2.1.3.

**Comment by daffl** [comment]
This will be fixed in the next version via #408 

A workaround for right now should be

```js
app.service('example').filter(function (data, connection, hook) {
  const path = Object.keys(app.services).find(current => app.services[current] === this);
  
  return data;
})
```
