### ISSUE TITLE
Can't access services with URL parameters through socket.io client

### ISSUE THREAD

**Issue by thedeadc0der** [feathersjs/feathers#591]
### Steps to reproduce

I have a service that has URL parameters, configured like so

```javascript
app.use('/users/:user/messages', {
    find: params => {
        // ...
    }
});
```
Where `:user` is the ID of the user whose messages are being accessed. I am able to access the service via REST using Postman. However, when using the feathers client library with `feathers-socketio/client`, like so:

```javascript
app.service('/users/1/messages').find().then( r => {
    console.log('result: ', r);
    debugger;
});
```
### Expected behavior
The promise should resolve with the result of the service.

### Actual behavior
The promise is not resolved and, besides the usual timeout, no error is generated.

### What I tried
After testing, this behavior is the same as when accessing a non-existent service, which leads me to think that Feathers didn't register the service.

### System configuration

I don't think my configuration is responsible because I have other services without URL parameters that aren't affected by the problem.

**Comment by thedeadc0der** [comment]
I was able to communicate with the service by repeating the URL parameters like so:

```javascript
const service = app.service('/users/:user/message');

service.find().then( r => {
    debugger;
});
```
But the URL parameters are set to `undefined` in the service method. 

Looking further, I found in the FAQ that [params can't be passed to the server](https://docs.feathersjs.com/faq/readme.html#why-cant-i-pass-params-from-the-client) for security reasons. However, that would also make it impossible to access sub-services from socket-based clients, which is inconsistent with the REST interface, which allows these.

**Comment by eddyystop** [comment]
Perhaps the `setSlug` hook would help https://docs.feathersjs.com/api/hooks-common.html#setslug

**Comment by thedeadc0der** [comment]
@eddyystop That solved my problem, thank you.

**Comment by daffl** [comment]
Also related: https://docs.feathersjs.com/faq/readme.html#how-do-i-do-nested-or-custom-routes
