### ISSUE TITLE
Invalid URL on homepage

### ISSUE THREAD

**Issue by comerc** [feathersjs/feathers#592]
![2017-06-04 13 44 13](https://cloud.githubusercontent.com/assets/1025241/26760891/050c4424-492c-11e7-8e1b-35127875f541.png)

https://docs.feathersjs.com/api/services.htmll

**Comment by eddyystop** [comment]
Where is this URL located? I scanned for it in the docs unsuccessfully.

**Comment by comerc** [comment]
https://feathersjs.com/

**Comment by eddyystop** [comment]
Thanks!
