### ISSUE TITLE
doesn't support couchdb

### ISSUE THREAD

**Issue by kamal250** [feathersjs/feathers#593]
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by daffl** [comment]
For reference there is the community created [feathers-couchdb](https://github.com/lontongcorp/feathers-couchdb). We are happy to officially include database adapters once they support the features tested in the [latest common service tests](https://github.com/feathersjs/feathers-service-tests) as well as documentation and generator support. I am sure @lontongcorp would love to see contributions to make that happen.
