### ISSUE TITLE
How to authenticate two or more different user (entities) services in the same app

### ISSUE THREAD

**Issue by GHNewbiee** [feathersjs/feathers#595]
How to authenticate **two** or **more different user** (**entities**) **services** (eg. customer, employee, and supplier) in the same app?

**Comment by marshallswain** [comment]
The simplest way I can think of would be to use `feathers-authentication-local` with a custom Verifier and custom attributes for identifying the other entities in the `feathersClient.authenticate()` call.  https://docs.feathersjs.com/api/authentication/local.html

**Comment by GHNewbiee** [comment]
Thanks for your immediate/prompt reply!

**Comment by marshallswain** [comment]
I'm going to go ahead and close this.  Feel free to reopen or post additional information.
