### ISSUE TITLE
.get , distinguishing front-end and back-end

### ISSUE THREAD

**Issue by PavelPolyakov** [feathersjs/feathers#600]
### Steps to reproduce
Hi,

Imagine I have a service `users`, where I have two "private" fields - `password` and `amount`. 
Let's say I don't want to pass this fields to the front-end in any case for the method `.get`.

In order to achieve that I do the appropriate `hook` in the service:
```
after: {
       get: [
            function (hook) {
                    delete hook.result.password;
                    delete hook.result.amount;
                }
        ]
}
```

Everything works great. Then, on the server side I want to have a method which actually does some operation on the `amount` field. So I do `yield app.service('users').get('id')` and receive the user object, but the `amount` is not there. First time it was a little unexpected for me :)

### Expected behavior
I believe there should be an option to distinguish `front-end` and `back-end` queries. It's already possible to do something like:
```
            const userRecord = await app.service('users').get(payload.userId, paramsForServer({ frontEnd: true }));
```

but it's not safe, as still it's possible to remove that `paramForServer` and receive the whole object.

What are your thoughts on this matter? Maybe there is some existing solution?

Regards,

**Comment by daffl** [comment]
You can use the [discard hook](https://docs.feathersjs.com/api/hooks-common.html#discard) with a conditional `isProvider`

```js
const { discard, when, isProvider } = require('feathers-hooks-common');

after: {
 get: [
    when(isProvider('external'), discard('password', 'amount'))
  ]
}
```

This will only remove `password` and `amount` if it was an external API call.

**Comment by PavelPolyakov** [comment]
Thank you, this should help!Отправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail20.06.2017, 19:03, "David Luecke" <notifications@github.com>:You can use the discard hook with a conditional isProvider
const { discard, when, isProvider } = require('feathers-hooks-common');

after: {
 get: [
    when(isProvider('external'), discard('password', 'amount'))
  ]
}
This will only remove password and amount if it was an external API call.
