### ISSUE TITLE
Fail / disallow service.create if service.get(id) already exists

### ISSUE THREAD

**Issue by arve0** [feathersjs/feathers#601]
I expected `service.create(obj)` to fail when existing entry with same `id` in database already existed. Not sure if this is in the scope of feathers, the specific database service interface (here feathers-nedb) or feathers-hooks-common.

### Steps to reproduce
```js
const feathers = require('feathers');
const NeDB = require('nedb');
const service = require('feathers-nedb');

const app = feathers()
app.use('/users', service({ Model: userModel(), id: 'email' }));

const users = app.service('/users');
let user = { email: 'jane.doe@gmail.com', password: '11111', role: 'admin' }
Promise.all([
  users.create(user),
  users.create(user)
]).then(results => console.log(results))
  .catch(err => console.log('Error occurred:', err));

function userModel() {
  return new NeDB({
    filename: 'users.db',
    autoload: true
  });
}
```

### Expected behavior
I expected second `users.create` to fail.

### Actual behavior
Same user is added to database twice.

### Proposed hook
```js
const { validate } = require('feathers-hooks-common')

/**
 * Checks if item with same id already exists.
 */
module.exports = function unique () {
  return validate((values, hook) => {
    return hook.service.get(values[hook.service.id])
      .catch(() => null)  // not found, pass null to next .then
      .then(res => res === null
        ? null
        : Promise.reject(new Error(`${res[hook.service.id]} already exists in db`)))
  })
}
```

**Comment by eddyystop** [comment]
As an aside on hooks, there's a commonly missed issue with your hook, the `param` value. For example, no authentication info is passed with the `get`. See how the hook `stashBefore` handles it.

**Comment by marshallswain** [comment]
This is a problem that should generally be handled by the database for efficiency reasons.  It's definitely possible to implement as a hook, but it won't be nearly as efficient as using NeDB unique constraint indexes: https://github.com/louischatriot/nedb/wiki/Indexing

**Comment by arve0** [comment]
Thanks for the help. Here's the solution, if others stumbles over the same:

```js
function userModel() {
  let Model = new NeDB({
    filename: 'users.db',
    autoload: true
  });

  Model.ensureIndex({ fieldName: 'myUniqueID', unique: true }, err => {
    if (err) throw err
  });

  return Model;
}
```

**Comment by daffl** [comment]
The generator already creates a unique index on emails [in the user service](https://github.com/feathersjs/generator-feathers/blob/master/generators/service/templates/model/nedb-user.js#L11) so in your case you just add the same thing for `id` (I'm pretty sure there already is a unique constraint on NeDBs standard `_id`).
