### ISSUE TITLE
Authenticating socket.io connection while using REST

### ISSUE THREAD

**Issue by adanielyan** [feathersjs/feathers#604]
My client side app uses REST for CRUD operations. However I want to receive events in my client (not CRUD operations related) from the server through socket.io. I use [Direct connection](https://docs.feathersjs.com/api/socketio.html#direct-connection) method for that. I want to send these events only to relevant users using event filters. However in my client app I can only provide either REST or socket, but not both. I.e. 

`export const app = feathers().configure(rest(host).superagent(superagent))`

And I don't know how to get the currently logged in user in my server side event filter, which usually is in the `connection` argument. But because I configure my client app as REST I don't get the user in that `connection` argument. I suppose the authentication token or user object should be set in socket.io configuration on client side every time the user logs in and then sent to the server when socket connection is (re-)established, but I am not sure how to do that securely.

What is a right way to do this?

**Comment by daffl** [comment]
There is almost never a good reason to use REST and websockets in the same application. All of Feathers uses Websockets for communication in both directions. If you already have to establish a websocket connection to get real-time events you might as well use it for everything else.

**Comment by adanielyan** [comment]
Thank you for a quick response. I am new to Feathers and have more experience with traditional REST than with sockets. 

Is socket.io/primus a recommended transport for Feathers app? I mean should I consider using sockets by default unless there is a strong justification for using REST?

**Comment by daffl** [comment]
Yep, that is basically it. REST is an architecture, not a protocol (although most people are used to REST via the HTTP protocol). Even if you are using Feathers through websockets everything is still mostly [RESTful](https://en.wikipedia.org/wiki/Representational_state_transfer).

The points for and against a certain transport are basically

- For an extremely high number of simultaneous clients (tens of thousands or more) that make many requests, if there is an existing HTTP infrastructure (load balancers, clusters etc) or for easier integration with third party services use REST
- If you want real-time, the client is written in JavaScript or another good websocket client exists, use websockets

The nice thing about Feathers is that it is not an either or choice. You always get *both* by default so even if other apps or third party developers connect via REST HTTP to your API, real-time on your existing clients will still work just the same.

**Comment by adanielyan** [comment]
Great, thanks! I will use websockets then.

**Comment by escobar5** [comment]
Hi @daffl, I have doubt about this one, 

I'm not sure if i don't get it, but I'm also facing this, I have a React app with some simple CRUD operations, and I have a specific case for real time (messaging). My first guess was to use two transports, REST for the CRUD operations, Websockets for the messaging.

I really don't need nor want real-time in my CRUD operations, I don't want for example a table of users to be refreshing without the user asking for a refresh.

How would you handle this use case with a single transport?

**Comment by daffl** [comment]
You can still disable sending of certain real-time events using [channels](https://docs.feathersjs.com/api/channels.html). I wrote more [here](https://blog.feathersjs.com/http-vs-websockets-a-performance-comparison-da2533f13a77) about the performance benefits of using websockets.

**Comment by escobar5** [comment]
Thanks, I think I get it now, I thought when using websockets everything must be done with events, but I see that you can just emit a find and get the results
