### ISSUE TITLE
Remove Babel Compilation - Drop Support For Node v4

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers#608]
Starting with the next release (Buzzard) we would like to remove Babel compilation from all server side and React Native modules where appropriate and for modules that can be used in the browser  swap over to using Webpack in order to leverage hoisting.

Client side versions of modules are already being moved into their own repos in this release (https://github.com/feathersjs/feathers-client/issues/137), so now seems like the best time to do this.

As a result the next Buzzard release will drop support for Node v4 a bit early. Even though there is still 6 months of official LTS left for v4 from Node, we don't believe many people are using Feathers with Node v4.x. Feathers works without compilation on Node v6+ and Node v8.x is the current stable version.

Node has a good migration path so it shouldn't be a blocker for many people if they do need to upgrade and because we use semver Feathers Auk will continue to work on Node v4+ with Babel compilation so migrating current Feathers apps onto new versions of Node is a non-issue.

**As a result you should probably start now if you are on Node v4.x.**

## Why Change This

- We will be able to install modules from a github repo. This will make it easier for people to have private forks and contribute fixes. 🎉 
- Reduced dependencies are always great 🙌
- Easier debugging and less code bloat
- Less tooling to maintain
- No need for people to compile and/or `watch` files when developing, testing modules, etc.
- We're currently restructuring some modules and breaking out client builds into their own repos

## What Changes

- The next major version of all the modules below will not be supported on NodeJS versions older than v4. You will need to use babel to compile them yourself.
- Switch to webpack for client side builds
- For most modules it is simply the `import` and `export`s that will change and updating the tests

---

The @feathersjs/core-team has decided that this is totally worth but if you feel this is cause for concern please let us know! Feel free to comment or simply give a 👍 or 👎 .

### Core Modules

- [x] feathers https://github.com/feathersjs/feathers/pull/614
- [ ] feathers-query-filters
- [x] ~~feathers-hooks~~ (this is moved into core)
- [x] feathers-commons https://github.com/feathersjs/feathers-commons/pull/53
- [ ] feathers-socket-commons
- [ ] feathers-primus
- [ ] feathers-socketio
- [ ] feathers-rest
- [ ] feathers-service-tests?
- [ ] feathers-hooks-common (need a client build?)
- [ ] feathers-authentication
- [ ] feathers-authentication-local
- [ ] feathers-authentication-oauth1
- [ ] feathers-authentication-oauth2
- [ ] feathers-authentication-ldap
- [ ] feathers-authentication-jwt
- [ ] feathers-authentication-client (needs a client build)
- [ ] feathers-errors (needs a client build)
- [ ] feathers-cli
- [ ] feathers-generator
- [ ] generator-feathers
- [ ] generator-feathers-plugin
- [ ] feathers-configuration (needs a client build??)

### Service Adapters
- [x] feathers-memory (need a client build?) https://github.com/feathersjs/feathers-memory/pull/53
- [ ] feathers-knex
- [ ] feathers-localstorage (needs a client build)
- [ ] feathers-sequelize
- [ ] feathers-waterline
- [ ] feathers-sendgrid
- [ ] feathers-mailgun
- [ ] feathers-mailer
- [ ] feathers-stripe
- [ ] feathers-twilio
- [ ] feathers-blob
- [ ] feathers-levelup
- [ ] feathers-rethinkdb
- [ ] feathers-nedb
- [ ] feathers-mongodb
- [x] feathers-mongoose https://github.com/feathersjs/feathers-mongoose/pull/201
- [ ] feathers-elasticsearch

### Other Modules
- [ ] feathers-reactive (needs a client build)
- [ ] feathers-batch
- [ ] feathers-sync
- [ ] feathers-bootstrap
- [ ] feathers-permissions (needs a client build?)

## Related Issues

This is an Epic so use the Zenhub plugin to see all related issues and PRs.

**Comment by eddyystop** [comment]
feathers-hooks-common does need a client build.

Services with memory resident options or that can persist on the client also need client versions. These gain in inportance with feathers-offline-*.

Are there others than feathers-memory, feathers-nedb, feathers-localStorage?

**Comment by bisubus** [comment]
Since Node version doesn't impose a constraint, wouldn't it be beneficial for the codebase to get rid of odd `uberproto` thing in favour of ES6 classes? They are idiomatic and easier to comprehend for both humans and IDEs.

**Comment by daffl** [comment]
@bisubus This came up before so let me try and explain why this will continue to be necessary:

Feathers fully supports and encourages ES6 classes and all references  [Uberproto](https://github.com/daffl/uberproto) usage will be removed from the documentation in the future.

However, Uberproto will continue to be used to _mix in functionality_  to existing services. ES6 classes do _not_ support Mixins or multiple inheritance so it is not enough to add e.g. hooks functionality. Instead of always having to safe a reference and overriding the method manually we instead use a tiny library of 86 lines of code with three methods and less than half a kilobyte in size to do that.

**Comment by bisubus** [comment]
@daffl The unquestionable benefit of ES6 classes is that they currently have better support in IDEs for autocompletion, etc (technically, they've got *some* support while custom inheritance utils have none), even with no JSDoc or TS typings.

The reason why this came up is that Uberproto `proxy` doesn't seem to be used in framework code, while the rest of Uberproto functionality already has idiomatic counterparts (guess this wasn't so when the project started).

In my experience, the alternative to Uberproto 'init' feature is to follow the convention that requires to put all initialization logic to `_init` prototype method that could be extended or overridden in ancestors. And mixins are as simple in ES6 as `Object.assign(Foo.prototype, Bar.prototype)` - thanks to classes for heavy promotion of prototype methods.

Just wanted to clarify this for Buzzard contribution guidelines.

**Comment by zusamann** [comment]
Should also add UMD builds for client side modules, so they can be directly loaded of CDNs like unpkg.com.

**Comment by zusamann** [comment]
Should also add UMD builds for client side modules, so that they can be loaded of CDNs like unpkg.com

**Comment by daffl** [comment]
This has been implemented for all `@feathersjs` core modules in v3. Ecosystem and other plugins can be rolled out later.
