### ISSUE TITLE
Event filtering not working

### ISSUE THREAD

**Issue by tention** [feathersjs/feathers#610]
### Steps to reproduce

Using the following code in React to register all created events on **messages**, and it works fine.
`this.props.app.service('messages').on('created', this.props.addMessage);`

It stopped working if I replace it with Event Filtering with the following code.
`this.props.app.service('messages').filter('created', function(data, connection, hook) {});`

Failed with the following error.
`Uncaught (in promise) TypeError: this.props.app.service(...).filter is not a function
    at Conversation.componentDidMount (Conversation.js:56)
    at ReactCompositeComponent.js:265
    at measureLifeCyclePerf (ReactCompositeComponent.js:75)
    at ReactCompositeComponent.js:264
    at CallbackQueue.notifyAll (CallbackQueue.js:76)
    at ReactReconcileTransaction.close (ReactReconcileTransaction.js:80)
    at ReactReconcileTransaction.closeAll (Transaction.js:206)
    at ReactReconcileTransaction.perform (Transaction.js:153)
    at batchedMountComponentIntoNode (ReactMount.js:126)
    at ReactDefaultBatchingStrategyTransaction.perform (Transaction.js:140)`

All these seems to work except .filter.
app.service('messages').on
app.service('messages').patch
app.service('messages').removeListener
app.service('messages').create

Running:
"feathers": "^2.0.3",
"feathers-hooks": "^2.0.1",
"feathers-hooks-common": "^3.3.2",
"feathers-socketio": "^2.0.0",

**Comment by eddyystop** [comment]
Don't filters have to return `data` or `false`? In your example you're returning `undefined` which is falsey.

**Comment by tention** [comment]
Yup, i did include the return like this:
`this.props.app.service('conversationsMessages').filter('created', function (data, connection, hook) {
      return data;
});`

But it keep complained that the filter is not a function.
`Uncaught (in promise) TypeError: this.props.app.service(...).filter is not a function`

**Comment by eddyystop** [comment]
Check that `this.props.app.service('conversationsMessages')` returns an object which looks like other service objects.

**Comment by daffl** [comment]
It looks like  you are trying to use event filters on the client. They only work on the server.

**Comment by tention** [comment]
I'm not sure if running it on the server will works. I'm using the socket for real time messaging, so I need to know which room he is currently in, to decide whether to use the received event.

The steps in FAQ works, but what if the user opened multiple tabs of different rooms? The `rooms` would have multiple IDs in it. Wouldn't all rooms received the same message?

`// On the client`
`function joinRoom(roomId) {`
`  const user = app.get('user');`
`  return app.service('users').patch(user.id, { rooms: user.rooms.concat(roomId) });`
`}`

`// On the server`
`app.service('messages').filter(function(message, connection) {`
`  return connection.user.rooms.indexOf(message.room_id) !== -1;`
`});`

Would it be possible to get certain parameter from the listener, or maybe the route path to determine whether to send/receive the event?

**Comment by tention** [comment]
If I were to use the steps in FAQ, all the tabs/rooms that a user opened will received the event, and I will have to perform another filter on the client end, to determine whether to use the received event based on the roomID. Is my understanding correct? Or I missed out something?

**Comment by daffl** [comment]
That is correct. If you are just listening to real-time events (instead of also updating your data when the service call returns) you shouldn't have to do any filtering to determine if the client sent it or not though.
