### ISSUE TITLE
What is the best way to use external rest API

### ISSUE THREAD

**Issue by adanielyan** [feathersjs/feathers#611]
My application needs to access an external read only rest API to load some data that will be used in one of the service hooks. Shall I create a plugin that will work as another service or do I do the data fetch directly in a hook? What's the best practice?

**Comment by eddyystop** [comment]
That's a personal choice I think. I would fetch if its only ever used in one place because why increase the cognative load?

**Comment by daffl** [comment]
[Axios](https://github.com/mzabriskie/axios) has also become quite popular but as @eddyystop said, there isn't really anything Feathers specific to consuming an external API.

I also wrote up a blog post a while ago on how to use Feathers as a real-time proxy for an existing API at https://blog.feathersjs.com/using-feathersjs-to-make-your-existing-api-real-time-813f7c3fd892 (that one is using [request](https://github.com/request/request))

**Comment by adanielyan** [comment]
Thank you daffl, that's exactly what I needed.
