### ISSUE TITLE
Why aren't services secured by default?

### ISSUE THREAD

**Issue by OfekA** [feathersjs/feathers#612]
I find myself oftentimes having to do this for most services:

```
exports.before = {
  all: [], // can't use this most of the times
  find: [
    hooks.disallow('external'),
    auth.hooks.authenticate('jwt'),
    restrictToOwner({ idField: 'id', ownerField: 'userId' })
  ],
  ...
  update: [
    hooks.disallow('external'),
    auth.hooks.authenticate('jwt'),
    restrictToOwner({ idField: 'id', ownerField: 'userId' })
  ]
}
```

And since I sometimes need to expose only one HTTP method I can't use the 'all' property.
It seems weird to me that all services are fully exposed by default. 

I know you want to make people's life easier but I feel like in the long run this can easily turn into an unsuspected security hole.   

Wondering what you guys are thinking, or if I missed a way to secure by default.

**Comment by daffl** [comment]
Mainly because those restrictions are assumptions that are introduced by an optional plugin (`feathers-authentication`) and your data model (`userId` with `restrictToOwner`). This is often the case but definitely not always. As for not repeating yourself so often, you can create your own wrapper hook that can be used as an `all` hook, e.g. using [commonHooks.iffElse](https://docs.feathersjs.com/api/hooks-common.html#iffelse):

```js
const commons = require('feathers-hooks-common');

function whiteList(... methods) {
  return commons.iffElse(
    // Returns if the method is not within the allowed methods
    hook => methods.indexOf(hook.method) === -1,
    // If not, disable external access
    commons.disallow('external'),
    // If it is, add restrictions
    auth.hooks.authenticate('jwt'),
    restrictToOwner({ idField: 'id', ownerField: 'userId' })
  )
}
```

And use it like:

```js
exports.before = {
  all: [ whiteList('create', 'find') ]
}
```

**Comment by OfekA** [comment]
I see, I suppose this is the trade-off when having this many plugins.

As for the wrapper, thanks, much more elegant, I'll definitely use that!

**Comment by daffl** [comment]
It's also a design decision when it comes to flexibility. We learned the hard way that eventually someone will want to change any implicit assumption you make (in this case that the service data belongs to a user and that it requires authentication).

We do try to set up some sane defaults in the generated application (and keep it up to date with the latest things we learn) though - while ideally not adding to many prompts for every kind of scenario.
