### ISSUE TITLE
How to configure Mailer dynamically for gmail in feathersjs

### ISSUE THREAD

**Issue by asuhag007** [feathersjs/feathers#613]
hiii i am using feather mailer to send email. i need some help 

right now i am using this code in my sendemail service 

```
   app.use('/sendemail', Mailer(smtpTransport({
     service: 'gmail',
     auth: {
         user: app.get["gmail"],
         pass: app.get["gmailpassword"]
     }
 })));
```
its working fine and taking input from defalut.json file. but i have to pass these gmail id and password from front end.
Is it possible to change these user and pass dynamically each time from front end and send attachment with each email from front end ?

**Comment by ForsakenHarmony** [comment]
this doesn't seem like an issue with feathers, but rather a question, can you join the slack and ask there?

**Comment by daffl** [comment]
If you look at [the code](https://github.com/feathersjs/feathers-mailer/blob/master/src/index.js#L9) you can see that you can set `app.service('sendemail').transport` to the node mailer instance you need dynamically before sending the email, e.g. in a before hook:

```js
app.service('/sendemail').hooks({
  before: {
    create(hook) {
      hook.service.transport = Mailer.createTransport(transport, hook.data.emailSettings);
    }
  }
});
```
