### ISSUE TITLE
Maximum url size in HTTP GET - How to use POST for find ?

### ISSUE THREAD

**Issue by thaiat** [feathersjs/feathers#615]
Hi,

I understand the reasons behind the service apis (`find`, `create`, etc...) and how they actually bind to http verbs. 
Now my question is how do you deal with a `find (GET)` where the query payload is very large and could go over the standard limit of 2KB for the url size.
Would you make a new service that uses the `create (POST)` method to achieve the `find` ?

In that case how on the client side would you use a reactive query so that it still triggers the subscribe when an actual `create` on the original service happens ?

**Comment by daffl** [comment]
My recommended solution would be to use websockets instead of REST which seems what you'd want to do anyway when using `feathers-reactive` right?

**Comment by thaiat** [comment]
i just had my a-ah moment ;) thks !!!

**Comment by daffl** [comment]
Sweet. Messages through websockets are not as size restricted as HTTP URIs and since you can use Feathers the same way through both, that's definitely the way to go in this case.
