### ISSUE TITLE
No native ios client library included?

### ISSUE THREAD

**Issue by internalG** [feathersjs/feathers#616]
As I read the feathersjs has a React Native client only. So if I have a native ios app that uses afnetworkning2 for c/s communications, I have to write my own code right? And there's a socketio-swift for ios, is it compatible with feathers fully?

**Comment by daffl** [comment]
You can connect directly to the AP (e.g. [via Socket.io](https://docs.feathersjs.com/api/socketio.html#direct-connection) or [REST](https://docs.feathersjs.com/api/rest.html#direct-connection) or use the [Swift](https://github.com/feathersjs/feathers-swift) client.

If you encounter any specific issues or have questions about using the Swift client it is probably best to open an issue there.
