### ISSUE TITLE
Cannot modify result in after hook

### ISSUE THREAD

**Issue by Metamist** [feathersjs/feathers#617]
First of all, I am new to feathers and I may be doing something wrong, but as far as my research tells me, it should be fine.

I am trying to assign a JWT token to registered users, but when I check the database afterwards the token is not there.
I'm using `feathers-rethinkdb` at the moment, but using `feathers-memory` yields the same result.

```javascript
const issueJWT = () => {
  return hook => {
    const app = hook.app;
    const id = hook.result.id;

    return app.passport.createJWT({ userId: id }, app.get('authentication')).then(accessToken => {
      hook.result.accessToken = accessToken;

      debug(`Created access token ${accessToken}`);

      return hook;
    });
  };
};

module.exports = {
  after: {
    create: [
      issueJWT(),
    ],
  },
};
```
Also, when using RethinkDB, the after hook runs twice (Probably the same issue as feathersjs/feathers-rethinkdb#80), but this is unrelated to my current issue.

**Comment by daffl** [comment]
After hooks run *after* the database call happens and let you modify what is returned to the client not what gets put into the database. If you want to change the data that are being saved you have to register a `before` create hook and modify `hook.data`. For more examples on this, have a look at the [hooks API page](https://docs.feathersjs.com/api/hooks.html).

**Comment by Metamist** [comment]
Hm, okay, seems like I misunderstood something from the examples I've looked at. Should have thought about that, though.
One question though; if the JWT access token is not stored in the database, how does feathers authenticate against it?

**Comment by marshallswain** [comment]
> One question though; if the JWT access token is not stored in the database, how does feathers authenticate against it?

The JWT contains a payload, a signature, and an expiration.  Check out https://jwt.io to see the internals color coded.  It's really helpful.

**Comment by daffl** [comment]
I also think you should look into [feathers-authentication oauth2](https://docs.feathersjs.com/api/authentication/oauth2.html). Using it together with [Feathers on the client](https://docs.feathersjs.com/api/client.html) all the JWT issuing, consuming and storing int localstorage will be done for you automatically already.

**Comment by Metamist** [comment]
I assumed passport-steam didn't work with the OAuth2 package because it's OpenID rather than OAuth2?
Are you saying it works fine with it?

**Comment by marshallswain** [comment]
I'm pretty sure it works.

**Comment by Metamist** [comment]
Alright, I've hooked up the steam strategy to the oauth2 service.
First of all, the package requires a clientID and a clientSecret, but `passport-steam` does not require any of those (only `apiKey`).
After I sign in and get redirected back to `returnURL`, I am met with a RethinkDB query error:
```
r.db("feather_test").table("users").filter(function(var_3) {
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return r.expr({}).and(var_3("steamId").eq(undefined))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
}).limit(1)
^^

error:  ReqlRuntimeError
    at Function.Term.run (E:\Development\FeathersJS\meta-drm\node_modules\rethinkdbdash\lib\term.js:43:17)
    at Function.Term.then (E:\Development\FeathersJS\meta-drm\node_modules\rethinkdbdash\lib\term.js:2876:15)
    at process._tickCallback (internal/process/next_tick.js:109:7)
error: Unhandled Rejection at: Promise  Promise {
  <rejected> TypeError: done is not a function
    at E:\Development\FeathersJS\meta-drm\node_modules\feathers-authentication-oauth2\lib\verifier.js:139:24 } TypeError: done is not a function
    at E:\Development\FeathersJS\meta-drm\node_modules\feathers-authentication-oauth2\lib\verifier.js:139:24
```
The service is set up like this
```
  app.configure(oauth2({
    name: 'steam',
    Strategy: SteamStrategy,
    clientID: 'not needed',
    clientSecret: 'not needed',
    apiKey: '<steam api key>',
    returnURL: 'http://localhost:3030/auth/steam/callback',
  }));
```
OpenID requires a returnURL, not callbackURL as the oauth2 service specifies by default.

Apologize that this issue has kind of been everywhere by now, I'm simply trying to get into the whole feathers.js mindset.

**Comment by marshallswain** [comment]
Maybe this issue will help: https://github.com/feathersjs/feathers-authentication/issues/154

**Comment by Metamist** [comment]
That's the exact issue that I looked at to write the initial code, the one that didn't give me a JWT token and didn't use oauth2.
Are you telling me to switch back, again?

**Comment by marshallswain** [comment]
Nope.  I just remembered seeing it and I'm trying to help while I do other things.  ;)

**Comment by Metamist** [comment]
The reason the oauth2 verifier fails with this is partly due to the SteamStrategy not returning OAuth2 tokens.
See:
https://github.com/liamcurry/passport-steam/blob/master/lib/passport-steam/strategy.js#L103
https://github.com/feathersjs/feathers-authentication-oauth2/blob/master/src/verifier.js#L74

OAuth2 expects the strategy to get the params `req, accessToken, refreshToken, profile, done`, while `passport-steam` passes `req, identity, profile, done` instead.

**Comment by daffl** [comment]
You can probably solve this by [customizing the verifier](https://docs.feathersjs.com/api/authentication/oauth2.html#verifier) since it gets passed the same params as the callback.

**Comment by Metamist** [comment]
Oh yeah, I remember reading that page. I totally disregarded the fact that I could customize the verifier. Will try this, thanks!

**Comment by Metamist** [comment]
Alright, I have configured the oauth2 package with a custom verifier and the login is now successful. The users are updated/patched whenever you sign in. However, the client still tells me 
```json
{
  "name": "NotAuthenticated",
  "message": "Could not find stored JWT and no authentication strategy was given",
  "code": 401,
  "className": "not-authenticated",
  "errors": {}
}
```

```javascript
app.configure(auth());

app.authenticate()
  .then(response => {
    console.info('Feathers Client has Authenticated with the JWT access token!');
    console.log(response);
  })
  .catch(error => {
    console.info('We have not logged in with OAuth, yet.  This means there\'s no cookie storing the accessToken.  As a result, feathersClient.authenticate() failed.');
    console.log(error);
  });
```

**Comment by Metamist** [comment]
Issue solved, I was not pointing my returnURL to the right location.
Should be `/auth/steam/callback` rather than `/auth/steam/return`. Oops.
Thanks for the help, though!
