### ISSUE TITLE
Add custom method to database endpoint

### ISSUE THREAD

**Issue by nabeards** [feathersjs/feathers#618]
I'd like to add a method to an instance within an endpoint that is managed by a db adapter.
Example: /templates/:id/preview

I built a custom class that extends the db adapter, and added a `setup` function to the class:
```
    class TemplateService extends Service {
        setup(app, path) {
            app.get('/' + path + '/:__feathersId/preview', ((req, res) => {
                res.send('hello');
            }));
        }
    }
```

Looking at `app._router.stack` reveals that my endpoint is registered.

However, when I attempt to call the endpoint on id 15, I just get
`info: (404) Route: /templates/15/preview - Page not found`

Is there a way to add this method successfully to maintain RESTful pathing?

Info:
Feathers 2.1.1
NodeJS 7.7.3
macOS Sierra

**Comment by daffl** [comment]
I would do it as a `before` `get` hook on the templates service itself, check for a `preview` flag being set (so it would look like `/templates/:id?preview=true`) and then set `hook.result` to the preview form of what you are looking for.

For anything else you'd be fighting the system (see [this FAQ entry](https://docs.feathersjs.com/faq/readme.html#how-do-i-create-custom-methods) on more information why Feathers does not support this kind of custom method).

**Comment by nabeards** [comment]
So feathers doesn't support verbs that don't map to CRUD (a subset of what RESTful endpoints can [normally] support)?

That's ok if it does, and I can use your methodology instead, just would like to verify that.

For what I'm working to accomplish, I want the HTML version of that template (with sample data) to be sent to me. Wondering if there would be a more appropriate call to use with feathers, such as /templates/15.html or specifying that I want HTML as the return type in the headers?

Thanks!

**Comment by daffl** [comment]
RESTful endpoints _should not_ support other verbs, only the standard HTTP verbs (see https://en.wikipedia.org/wiki/Representational_state_transfer#Applied_to_Web_services). It is one of the things that Feathers tries to force you into.

You can [customize the formatter](https://docs.feathersjs.com/api/rest.html#appconfigurerestformatter) or register [your own service specific middleware](https://docs.feathersjs.com/api/express.html#custom-service-middleware) to send the HTML. Alternatively you can also create [custom routes that do the rendering](https://docs.feathersjs.com/guides/advanced/using-a-view-engine.html) to send HTML or course.

**Comment by nabeards** [comment]
> RESTful endpoints should not support other verbs, only the standard HTTP verbs

I wasn't questioning that, sorry for not being clear in my question. I meant verbs as in an endpoint location itself (specifically, a verb appearing in the URL itself, mainly used for long-running command kick-offs as described in Mark Masse's book).

Regardless, your other links to give me a better idea on accomplishing this. Thank you!

**Comment by daffl** [comment]
Personally I usually prefer to do this through POST as well but makes sense.

One more thing you could do would be to register your service with a URL parameter to request the type:

```js
class TemplateService extends Service {
  get(id, params) {
    const { type } = params;
  }
}

app.service('/templates/:type', new TemplateService());
```

Which would allow you to do something like `/templates/preview/15`.

Closing since it's hopefully enough information to go on but feel free to reopen if it doesn't work 😄
