### ISSUE TITLE
Feathers PouchDB

### ISSUE THREAD

**Issue by endyjasmi** [feathersjs/feathers#620]
First and foremost, apology if this is not the right place to post this. I'm not sure where I should discuss this.

I saw somewhere in the issues about Feathers PouchDB providing free replication. Here is my attempt at it.

https://github.com/endyjasmi/feathers-pouchdb

Currently there are two things which I know is not working properly:
1. Total attribute used in pagination is not working due to CouchDB/PouchDB mango queries not supporting `count` operation.
2. In order to use sort properly, according to [this](http://docs.couchdb.org/en/2.0.0/api/database/find.html#sort-syntax)
> - At least one of the sort fields is included in the selector.
> - There is an index already defined, with all the sort fields in the same
order.
> - Each object in the sort array has a single key.

Anyone have any thought on how I should go around this? Also any feedback is greatly appreciated.

**Comment by daffl** [comment]
This looks great @endyjasmi! Some quick thoughts:

1) What is the normal way to get the total count of a find operation for PouchDB?
2) This is just a limitation that has to be documented right?

**Comment by endyjasmi** [comment]
Hi @daffl thanks for the reply.
1. Normally we'll use map reduce to count the number of record in the index. In the case of this plugin, it is using the mango query which have no way of returning count currently. I am in dilemma of should I implement the map reduce index within the library or let the user decides outside of the library.
2. Currently there are simple documentation on the `README.md`. I'll update it with more information when I got the time.

**Comment by daffl** [comment]
I might do it but add a flag to turn if off if someone wants to do it manually. Could you add a link to the repository to the [Ecosystem](https://docs.feathersjs.com/ecosystem/readme.html) page? Thanks again for sharing this, closing since it's not a Feathers issue.
