### ISSUE TITLE
Patched event document changes

### ISSUE THREAD

**Issue by er1x** [feathersjs/feathers#622]
Is there a way to receive only document changes when a patch event is triggered? 

I'm using a patch method to update a small part of a document. When patched event triggers, the full document is provided as the listener function argument. For performance reasons I'd rather prefer to receive only the modified part.

Can I achieve this with patch or should I use a custom event?

**Comment by marshallswain** [comment]
You can use an after hook.  

```js
hook.result = hook.data
```

Customize the data however you'd like before assigning it to hook.result.
