### ISSUE TITLE
Proposal: Release compatible packages in @feathers(-release) scope

### ISSUE THREAD

**Issue by j2L4e** [feathersjs/feathers#623]
When Auk was out, there was a lot of confusion about which modules and which versions work together. Also it remains unclear from the package names if they are officially supported or 3rd party.
With Buzzard on the horizon the same thing's going to happen all over again, my proposal is the following:

Release everything that is auk under @feathers-auk (or @feathers-buzzard resp.) scope, so people can  be sure that what they import actually works together.

Actually the package itself doesn't need to be released under that scope, but we could build packages that only include a package.json that pulls in the actual package:

```
// @feathers-buzzard/feathers package.json
"dependencies" : {
  "feathers": "^3.0.0"
}

// @feathers-auk/feathers package.json
"dependencies" : {
  "feathers": "^2.0.0"
}
```

I know feathers uses greenkeeper and I also came across #462 . I'm not sure what both are capable of and have not yet thought about a technical solution, but it doesn't seem to be too complicated.

Edit: Also I vote for "Cockatoo" being the version after buzzard

**Comment by daffl** [comment]
We have been talking before about moving all official (and maybe just core) packages into the `@feathers` namespace. A new release might be a good time for that.

Release specific namespaces would add the overhead of having to re-release packages that didn't need to be changed. For example, the database adapters won't have to be changed at all for the next release.

One thing I'd definitely like to implement is for plugins to do a version check against `app.version` and throw an error if they are not compatible. So for example `feathers-rest@2.0` would throw an error for any non `feathers@^3.0.0` app.

**Comment by kfern** [comment]
Sounds good 👍

**Comment by eddyystop** [comment]
I like the version check idea.

**Comment by j2L4e** [comment]
This seems feasible

```
// feathers
const semver = require('semver')
function assertVersion(version) {
 if (!semver.satisfies(app.version, version)) {
    throw `feathers core version ${present} doesn't satisfy ${needed}`
  }
}

in the plugin:
neededCore = '^2.1.5 || 13.3.7';
app.assertVersion(neededCoreVersion);
```

**Comment by marshallswain** [comment]
> One thing I'd definitely like to implement is for plugins to do a version check against app.version and throw an error if they are not compatible. So for example feathers-rest@2.0 would throw an error for any non feathers@^3.0.0 app.

Yes!

**Comment by sorxrob** [comment]
Hi guys! How can I do `feathers generate service` in my old feathers app when I installed the new version? Thank you.

**Comment by eddyystop** [comment]
The new generator is not compatible with modules created by the old
generators.

The service generator, like all the generators, writes little code. I'd
just copy the modules from an old service and modify by hand.

**Comment by daffl** [comment]
Although we didn't implement the per-release organization, all core modules for the v3 pre-release have been moved to the `@feathersjs` scope. Upgrade instructions for beta testing can be found at https://gist.github.com/daffl/e718f93acc7bfe32fd1e5aed0f8e7827
