### ISSUE TITLE
Postgres isn't connecting with serialize - bad module somewhere?

### ISSUE THREAD

**Issue by Arc009** [feathersjs/feathers#626]
### Steps to reproduce
Hi , i have a brand new feathers installation, just creating a service, scaffolding with both Yarn or Npm gives me the same outcome, 
Serialize comes with this:

info: Feathers application started on localhost:3030
error: Unhandled Rejection at: Promise  Promise {
  _bitField: 18087936,
  _fulfillmentHandler0: 
   TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
       at Promise.then.result (/Users/Projects/pap/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:157:31)
       at tryCatcher (/Users//Projects/pap/node_modules/bluebird/js/release/util.js:16:23)

I tried with no success to use previous Serialize versions though with no luck. Both mac and windows.
Any advice?

**Module Loader**:Serialize 4.4 (last release)
Node version stable 6.11

**Comment by zusamann** [comment]
Can you share your code?

**Comment by Arc009** [comment]
Hi, there is no custom code,  everything has been generated by Feathers CLI.
- feathers generate app
- feathers generate service ( Postgres through Serialize support) 
I'm sure connection configuration is correct as it was in many different projects.

Default.json
  "host": "localhost",
  "port": 3030,
  "public": "../public/",
  "paginate": {
    "default": 10,
    "max": 50
  },
  "postgres": "postgres://postgres:password@localhost:5432/Testdb"
}

Part of the dependencies

 "dependencies": {
    "body-parser": "^1.17.2",
    "compression": "^1.7.0",
    "cors": "^2.8.4",
    "feathers": "^2.1.7",
    "feathers-configuration": "^0.4.1",
    "feathers-errors": "^2.8.2",
    "feathers-hooks": "^2.0.2",
    "feathers-hooks-common": "^3.5.5",
    "feathers-postgres": "^1.0.0",
    "feathers-rest": "^1.8.0",
    "feathers-sequelize": "^2.1.0",
    "feathers-socketio": "^2.0.0",
    "helmet": "^3.6.1",
    "pg": "^7.0.1",
    "sequelize": "^4.4.0",
    "serve-favicon": "^2.4.3",
    "winston": "^2.3.1"

Hope it helps.

**Comment by marshallswain** [comment]
Hi @Arc009 this should be fixed as of an hour ago.  There is an incompatibility in the `pg@7.0.x` module for node-postgres, which was published a couple of days ago.  It should work if you downgrade that module in your app by doing `npm install pg@6`  You can also `npm install -g feathers-cli@latest` and generate a new app

You can read up on the details, here: https://github.com/feathersjs/generator-feathers/issues/246

Feel free to close this issue once you've verified that it's working.

**Comment by Arc009** [comment]
Tested with the latest Feathers CLI, now it's working.
Great response team.
