### ISSUE TITLE
[Question] How write test for service.filter

### ISSUE THREAD

**Issue by huytran0605** [feathersjs/feathers#629]
I'm using feather cli to generate service, all my services have this to register filters 
```
 const service = app.service('users');
  service.hooks(hooks);
  if (service.filter) {
    service.filter(filters);
  }
```
So how can I write test for `else` path case? I'm still stuck when trying to find solution for this case...
Thanks

**Comment by daffl** [comment]
This is a conditional in case you decide to not set up Websockets (Primus or Socket.io). If you have those set up you can just remove the `if` statement.

**Comment by daffl** [comment]
Another way to test this branch would be to register the service on an app that does not have Socket.io set up. Closing since one of those two suggestions should work.
