### ISSUE TITLE
JSON API support

### ISSUE THREAD

**Issue by pspeter3** [feathersjs/feathers#63]
http://jsonapi.org/ 

This seems like a reasonable API format to support. What do you think?

**Comment by jokeyrhyme** [comment]
For other people looking for this, the REST service layer was extracted out to this project: https://github.com/feathersjs/feathers-rest
So a JSON API service layer could be built in a similar fashion.

**Comment by berlincount** [comment]
Any idea whether someone has done this in the end, and where to get the result? Cheers!

**Comment by ekryski** [comment]
@berlincount we decided to consciously *not* implement this yet. At the time the JSON API spec was still changing a lot. I'm not sure how stable it is now even (I stopped following it super close). Personally, we also feel that it can be a bit bloated at times. The biggest thing we are missing is automatic API discovery and we have an issue for that here: https://github.com/feathersjs/feathers-rest/issues/2.

Let's continue any further discussion over there.

**Comment by daffl** [comment]
Another tricky question is how this would work over Sockets. The spec only really targets HTTP as far as I know. If anybody would like to discuss this more, feel free to open a new issue in https://github.com/feathersjs/feathers-rest. We should keep track of ideas and it would be awesome if somebody would be interested in taking this on.
