### ISSUE TITLE
how feather hooks work, can we execute hooks asynchronous and synchronous

### ISSUE THREAD

**Issue by chiragob** [feathersjs/feathers#630]

**Comment by daffl** [comment]
First I'd recommend reading the guide about hooks ([part 1](https://docs.feathersjs.com/guides/step-by-step/basic-feathers/hooks-1.html) and [part 2](https://docs.feathersjs.com/guides/step-by-step/basic-feathers/hooks-2.html)).

The [API documentation for hooks](https://docs.feathersjs.com/api/hooks.html) has further information, including a section on [asynchronous hooks](https://docs.feathersjs.com/api/hooks.html#asynchronous-hooks).

**Comment by chiragob** [comment]
thanks for the reply
i go through hooks documentation.
i am trying to implement in before hook called another service. its not executed asynchronously, its always wait for hook response and then continue execution. 
when i am trying to call another service in after hook its executed asynchronously. its not wait for service response. 
so can we execute another service asynchronously in before hook.

**Comment by eddyystop** [comment]
You would need to have something like `return messages.create(...)`. I suspect you do not have the `return`.

**Comment by daffl** [comment]
As @eddyystop said you just don't return the Promise for the asynchronous operation. The API documentation example adjusted accordingly looks like this:

```js
app.service('messages').hooks({
  after: {
    get: [
      function(hook) {
        const userId = hook.result.userId;

        // Kick off the asynchronous processing
        hook.app.service('users').get(userId).then(sendEmail);

        // Just return the hook (NOT THE PROMISE)
        return hook;
      }
    ]
  }
});
```

**Comment by chiragob** [comment]
yes this works asynchronously in after hook
but when we set this in before hook, its not work asynchronously. its wait for email response.

```
app.service('messages').hooks({
  before: {
    get: [
      function(hook) {
        const userId = hook.result.userId;

        // Kick off the asynchronous processing
        hook.app.service('users').get(userId).then(sendEmail);

        // Just return the hook (NOT THE PROMISE)
        return hook;
      }
    ]
  }
});
```

**Comment by daffl** [comment]
There is no difference how before and after hooks work, it must be something else then.

**Comment by daffl** [comment]
There is no difference how before and after hooks work, I'm pretty sure it is something else which is easiest to track down with a reproducible example.
