### ISSUE TITLE
Is there anyway to get IP and port of running feathers app in test.app.js file?

### ISSUE THREAD

**Issue by HarshOB** [feathersjs/feathers#631]
I need IP and Port of my service, in fact I know when I run that service but I don't want to give that manually. I want to fetch and get that in app.test.js file. When I run my service in another server then IP will change. So, I want to fetch from service and not enter manually.

**Comment by eddyystop** [comment]
Anything you place in `req.feathers` in Express middleware will be in `hook.params` in hooks. You might apply a similar idea for your needs.

**Comment by daffl** [comment]
Something like

```js
app.use(function(res, res, next) {
  const ip = req.headers['x-forwarded-for'] || req.connection.remoteAddress;

  req.feathers.ip = ip;

  next();
});
```

Before registering the service should add the requests ip address to `params.ip`. You also might want to add an [websocket middleware](https://docs.feathersjs.com/api/socketio.html#middleware-and-service-parameters) that does the same thing.
