### ISSUE TITLE
hook.params.user undefined for internal service calls

### ISSUE THREAD

**Issue by nishantv87** [feathersjs/feathers#632]
### Steps to reproduce
1. Create a service say service1
2. Add authentication hook for this service with jwt
3. Create a second service say service2. 
4. Add authentication hook for service2 with jwt.
5. Create an after hook (s1ah1) for service1 create method in which call service 2 create method.
6. Create a before hook (s2bh2) for service2 create method  which checks if user is eligible to do operation by checking usertype of logged in user.
7. We get the error usertype of undefined when s2bh2 hook is being executed.

### Expected behavior
when we try to get hook.params.user in s2bh2 hook, it should give the authenticated user details.

### Actual behavior
We get it as undefined

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working): 
    "feathers": "^2.1.1",
    "feathers-authentication": "^1.2.2",
    "feathers-authentication-hooks": "^0.1.2",
    "feathers-authentication-jwt": "^0.3.1",
    "feathers-authentication-local": "^0.3.3"

**NodeJS version**: 
7.10.1

**Operating System**:
ubuntu 14.4

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by marshallswain** [comment]
Hi, @nishantv87.  We tried to avoid any kind of magic in Feathers, so the user has to be explicitly passed in for internal calls.  Notice in the below example how I'm adding the `user` property in the `params` next to `query`.

```
function manuallyPopulateGolfClubs (context) {
  const { user } = context.params
  return context.app.service('golf-clubs').find({
    query: { _id: { $in: user.golfClubIds } },
    paginate: false,
    user
  }).then(result => {
    context.result.golfClubs = result
    return context
  })
}```

**Comment by nishantv87** [comment]
Thank you.

**Comment by Zalasanjay** [comment]
How to make GET request like : ```
app.service('golf-clubs').find({
    query: { _id: { $in: user.golfClubIds } },
    paginate: false,
    user
  })
```

**Comment by marshallswain** [comment]
The full params object is not passed from the client, since being allowed to pass the user from the client would circumvent all security.  Only the query is passed to the server.

If you feel like designing an API that allows such queries, just promise yourself you don’t handle anybody else’s financial or other important data with such an API.  Then you can check out Feathers-hooks-common utilities like paramsFromClient (or something like that)
