### ISSUE TITLE
Create an associated model after creating another model

### ISSUE THREAD

**Issue by hounsellal** [feathersjs/feathers#636]
I have two models: user and company.
Every user has one company. Every company belongs to one user.

When a user signs up (is created) I want to create the company object at the same time.

How do I do this with an after:create hook?

**Comment by hounsellal** [comment]
Problem solved. The hook object has access to the app. So the solution:

1) generate an after:create hook on the user service
2) in the hook that is generated, create a company with:

`return hook.app.service('companies').create({userId: hook.result.id}).then(()=> {return hook});`

**Comment by eddyystop** [comment]
The more general solution is to use the populate common hook

**Comment by daffl** [comment]
Does populate allow creating related entities? Either way, glad you figured it out. Maybe you can share the complete solution as an answer to your Stackoverflow question at https://stackoverflow.com/questions/45464940/in-feathers-js-how-do-i-create-an-associated-object-after-creating-the-initial

**Comment by eddyystop** [comment]
"Does populate allow creating related entities?" No. I misread the question. Such is life.
