### ISSUE TITLE
$set is empty

### ISSUE THREAD

**Issue by jobobo21** [feathersjs/feathers#638]
### Steps to reproduce
`axios({
      method: "patch",
      url: "http://localhost:3030/profile/" + this.props.rtinfo._id,
      data: {
        info: payload
      }
    });`
I cannot manage to get feathers to perform patch request using standard mongodb orm (not mongoose).
I have created new project with repeated results.

### Expected behavior
Patch to replace info object with payload param from parent function.

### Actual behavior
`error:  GeneralError: '$set' is empty. You must specify a field like so: {$set: {<field>: ...}}
    at GeneralError (*/node_modules/feathers-errors/lib/index.js:177:17)
    at errorHandler (*/node_modules/feathers-mongodb/lib/error-handler.js:22:21)
    at process._tickCallback (internal/process/next_tick.js:109:7)
`

### System configuration

**Module versions** (especially the part that's not working):

**NodeJS version**:  feathers: 2.1.7, feathers-mongodb: 2.9.0

**Operating System**: Ubuntu 16.04.2 lts

**Browser Version**: Chromium 59.0.3071.109

**React Native Version**:

**Module Loader**:

**Comment by daffl** [comment]
Two things to double check first:

- The `ContentType` header has to be set to `application/json` or form encoded.
- Could `this.props.rtinfo._id` be empty or null?

**Comment by jobobo21** [comment]
No problem I can recreate the issue using feathers-client as well. Axios I believe uses application/json by default but I forced it just for good measure. I logged this.props.rtinfo._id and it comes back no problem. In chromium it comes back with 500 error.

Both patch requests in React return the same error message from feathers console

```
 handleSave (payload) {
    var config = {
      headers: { "Content-Type": "application/json" }
    };
  /*
    axios.patch(
      "http://localhost:3030/profile/" + this.props.rtinfo._id,
      {
        info: payload
      },
      config
    );
*/
    const profileservice = app.service("profile");
    profileservice.patch(this.props.rtinfo._id, { info: payload }, {});
console.log(this.props.rtinfo._id);
  }
```

**Comment by daffl** [comment]
I can't reproduce this the issue. I ran the following Axios commands against a standard CLI generated application and the [MongoDB example application](https://github.com/feathersjs/feathers-mongodb/blob/master/example/app.js) and it was working as expected:

```js
const axios = require('axios');

axios({
  method: 'post',
  url: 'http://localhost:3030/messages',
  data: {
    text: 'Hello world'
  }
})
.then(res => res.data)
.then(data => {
  return axios({
    method: 'patch',
    url: `http://localhost:3030/messages/${data._id}`,
    data: {
      text: 'Updated message'
    }
  }).then(res => res.data);
})
.then(updated => console.log('Updated', updated));
```

**Comment by jobobo21** [comment]
Yeah ok so did some more intensive consolelog soul searching and found out it was self error. There was an promise issue causing that handleSave to execute before payload was resolved. Sorry for the bother. The error message really made it seem like it was a feathers issue
