### ISSUE TITLE
Password is missing from patch before hook

### ISSUE THREAD

**Issue by michalg42** [feathersjs/feathers#642]
### Steps to reproduce
I used repo this repo: https://github.com/feathersjs/feathers-authentication and modified example like this: https://gist.github.com/michalg42/1a8d79a4360f68e636dd4add3a0dac74.
Then I run
node example/app.js
and
node example/client.js

### Expected behavior
In first terminal password should be shown (from console.log in patch before hook)

### Actual behavior
First one is shown, then it's undefined.

I guess that's because there is discard in patch after hook, because if I remove it, both console.log's show password.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
Exaclty the same as here: https://github.com/feathersjs/feathers-authentication/blob/master/package.json

**NodeJS version**:
8.1.2

**Operating System**:
Linux Mint 17

**Comment by daffl** [comment]
> I guess that's because there is discard in patch after hook, because if I remove it, both console.log's show password.

Is your answer. If the request is made through the API, the password will always be removed before it is sent to the client.

**Comment by michalg42** [comment]
But I'm talking about console.log in before hook in server part. I umderstand that it's removed from response  (that's what I wanted to achieve) but why is it missing from before hook in user service in app.js?

**Comment by daffl** [comment]
Is `hooks.params.user` populated? I think it will also use the provider so that the password is removed is to be expected. Since it has been verified already you should not have to use it.
