### ISSUE TITLE
Get options of a service

### ISSUE THREAD

**Issue by HelloEdit** [feathersjs/feathers#643]
<small>Maybe noob question ... 👼 </small>

I would like to know if it is possible to retrieve the options of a service already created, and if it's no possible, Would there be any other means ? Or it's could be a cool feature !

The service options are defined in [service_name] .service.js and look like this most of the time:

```
const options = {
  Name: 'module-manager',
  paginate
}
```

I also wanted to know if I could put my own property in and use them in my application.

Thanks,

**Comment by daffl** [comment]
There is no [common API](https://docs.feathersjs.com/api/databases/common.html) for storing the options on service adapters. Most services use `.id`, `.paginate` and `.Model` though.

You can always add properties separately via `app.service('myservice').options = myoptions` though which you can then use in a hook as `hook.service.options`.

**Comment by HelloEdit** [comment]
Thank for your answer !

Entirely, I would just like to include some customized options in the options object. They will never change, and I will not add to it afterwards. Do you think this is the right place for such things? For example, in addition to the name, I would like to add an custom `id` to each service and a `description`. Do you think I can put it in "options"?

**Comment by daffl** [comment]
I don't see a problem with that. If you don't want to add properties after the service has been registered but in the options object instead you will have to [extend the adapter classes](https://docs.feathersjs.com/api/databases/common.html#classes-es6) and use those though:

```js
'use strict';

const Service = require( 'feathers-<database>').Service;

class MyService extends Service {
  constructor(options) {
    super(options);
    this.options = options;
  }
}
```

**Comment by HelloEdit** [comment]
Thank for your precious precisions !
