### ISSUE TITLE
[Question] Provider and Token in request

### ISSUE THREAD

**Issue by idibidiart** [feathersjs/feathers#644]
Hi,

I see this in the request body:

feathers: { provider: 'rest', token: undefined },

Given I'm not using the feathers client, how do I pass in the token?

In other words, what do I need to put in the request header (or body?) that would then cause feathers to populate the token? and how is the provider getting populated?

Just trying to understand how this works. 

Thanks

**Comment by daffl** [comment]
By adding the `Authentication` header with the token. A Postman example can be found [in the chat guide](https://docs.feathersjs.com/guides/chat/authentication.html#getting-a-token) and the documentation in the [direct JWT usage for REST](https://docs.feathersjs.com/api/authentication/jwt.html#direct-usage).

**Comment by idibidiart** [comment]
Thank you @daffl 

It worked but I added 'Bearer ' before token. Not sure it's required. Is it?

**Comment by daffl** [comment]
Both should work. It didn't without?

**Comment by idibidiart** [comment]
Yes it does. Makes sense.
