### ISSUE TITLE
How to disable client side populate?

### ISSUE THREAD

**Issue by DominikTrenz** [feathersjs/feathers#645]
What's the proper way to disable all client side populates by default and enable them selectively on server side?
So that something like this won't work:

http://localhost/someservice?$populate[]=user

**Comment by eddyystop** [comment]
Does the client require feathers-hooks-common?

If not, you can disable populates for calls initiated by client by using `iff(context => !context.params.provider, populate(...))`. Calls initiated on the server have `context.params.provider === undefined` while ones from the client have `rest`, `socketio` or `primus`.

**Comment by DominikTrenz** [comment]
And whats the syntax for populate(...) to disable? Should it be a before all hook?
And is it possible to write this in the global hooks file (app.hooks.js) and later activate a populate again for some fields on some services?
