### ISSUE TITLE
What's the easiest way to run the feathers server forever ? 

### ISSUE THREAD

**Issue by jpca999** [feathersjs/feathers#646]
Pm2 or 
Also what kind of package does the community use for monitoring CPU and stuff ? 

### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by daffl** [comment]
Anything that works with Express so as you mentioned, [pm2](http://pm2.keymetrics.io/) or [forever](https://github.com/foreverjs/forever) should do.

**Comment by daffl** [comment]
Thank you for bringing up the question 😄  I'm going to close it since there shouldn't be anything Feathers specific and any resource about keeping Node servers running should do.
