### ISSUE TITLE
[Question] Range queries / Windowing

### ISSUE THREAD

**Issue by idibidiart** [feathersjs/feathers#647]
Hi,

Is there a way in the Feathers Query DSL to specify a range that is based on an arbirary integer index? For example, I want to get items 30 to 35 and then in another query items 31 to 36. The range length may or may not be fixed and the there is no max jump so I could request 30 to 35 then 500 to 520. In other words, I need to support from/to queries on some integer index (including Unix timestamps etc) --I don't want to use an array of id's as that wouldn't be the same S supplying a range.

Does feathers-mongoose or any other data store adapter support range queries?

**Comment by daffl** [comment]
I usually use [$lte](https://docs.feathersjs.com/api/databases/querying.html#lt-lte) and [$gte](https://docs.feathersjs.com/api/databases/querying.html#gt-gte) for that. For example the following gets every item created in the past week:

```js
app.service('myservice').find({
  query: {
    createdAt: {
      $gte: moment().subtract('week', 1).toDate(),
      $lte: moment().toDate(),
    }
  }
});
```

**Comment by 1sinhaa** [comment]
Great! 

This is very cool and it works for time-series data in a database as well as for any data that can be queried via an ordinal value. It does answer my immediate question.

But what I was asking about also includes the following more advanced scenario:

Let's say I need to get non-time-series data from in-memory state on the server (by querying the current in-memory state of some compute engine) and display in a data-grid component and refresh as the user scrolls. In this case, I need to get a 2D range of cells to populate the current grid view (which is defined by client based on x,y cell position of x/y mouse scroll.) I would specify x and y (or grid row and column), e.g. x=0 to x=40 and y=20 to y=50, and the compute engine returns the 2D range. Each data cell on the server has an x and a y value, and I'm getting the intersection (let's sayI can do that extremely efficiently)

What this means is that I need the ability to extend the Feathers Query DSL and build an adapter to talk to the compute engine. 

Would that be the way to go? ... just making sure :-)

**Comment by idibidiart** [comment]
Great!

This is very cool and it works for time-series data in a database as well as for any data that can be queried via an ordinal value. It does answer my immediate question.

But what I was asking about also includes the following more advanced scenario:

Let's say I need to get non-time-series data from in-memory state on the server (by querying the current in-memory state of some compute engine) and display in a data-grid component and refresh as the user scrolls. In this case, I need to get a 2D range of cells to populate the current grid view (which is defined by client based on x,y cell position of x/y mouse scroll.) I would specify x and y (or grid row and column), e.g. x=0 to x=40 and y=20 to y=50, and the compute engine returns the 2D range. Each data cell on the server has an x and a y value, and I'm getting the intersection (let's sayI can do that extremely efficiently)

What this means is that I need the ability to extend the Feathers Query DSL and build an adapter to talk to the compute engine.

Would that be the way to go? ... just making sure :-)

**Comment by daffl** [comment]
Yes, that sounds like it'll have to be a [custom service](https://docs.feathersjs.com/api/services.html).
