### ISSUE TITLE
Primus transport method not working

### ISSUE THREAD

**Issue by marcelgoya** [feathersjs/feathers#648]
### Steps to reproduce

Hi guys, 

I've followed your chat tutorial but I've been using Primus with engine.io instead of socket.io as transport method. I'm getting some really strange behaviour because the client is connecting via websocket but it's not sending any messages to the server. I've spent pretty much all day trying to figure out whats wrong here but it's not working. It would be great if you could help me. Below my code:
```

let socket = new Primus('http://localhost:3030', { websockets: true });

let client = feathers()
        .configure(feathers.hooks())
        .configure(feathers.primus(socket));

      socket.on('open', (spark) => {
        console.log('CONNECTION is alive and kicking');        
      });

      socket.on('error', (err) => {
        console.error('Something horrible has happened', err.stack);
      });

      let messages = client.service('messages');

      messages.on('created', message =>
        alert(`New message from ${message.name}: ${message.text}`)
      );

      messages.create({
        text: 'BLAAAA',
        name: 'UPPS'
      });

      messages.find().then(page => console.log('Current messages are', page));

```
Cheers,
Marcel

**Comment by marcelgoya** [comment]
I also forgot to mention that the primus.send() function which is mentioned in your docs is not working anymore. It seems to be replaced with primus.write().

**Comment by daffl** [comment]
What are the versions of the modules you are using? 7.x seems to be the latest and that's what `feathers-primus` is using. The `.send` method is provided by the [primus-emitter](https://github.com/cayasso/primus-emitter) plugin.

You do have to [load the client library generated by Primus](https://docs.feathersjs.com/api/primus.html#loading-the-primus-client-library).

**Comment by marcelgoya** [comment]
Alright, just found a good workaround by using socket.io with uws as engine. So problem solved :) Cheers
