### ISSUE TITLE
Demo App shows nothing but a static page

### ISSUE THREAD

**Issue by wowcut** [feathersjs/feathers#649]
I do not understand what the demo app described on your website below "Create your first real-time app in minutes." is about - it does not show any specific real-time features, I see only a simple static web page with the name "Feathers", followed by "A REST and realtime API layer for modern applications." - the footer shows a link to the feathers documentation site, however there is nothing that shows me anything about specific Feathers features.

I would like to suggest to add some nifty real-time features to that demo app to make potential users better understand what Feathers is about - a static page can be generated by anything.

**Comment by Jaden-Giordano** [comment]
Great Idea! What did you have in mind? I would be glad to jump on board and work on this!

**Comment by daffl** [comment]
This is the generator that is used to create a new application so it shouldn't have anything that has to be deleted pre set up. The text below should the CLI commands should probably link to the [chat app tutorial](https://docs.feathersjs.com/guides/chat/readme.html) though.
