### ISSUE TITLE
Modifiers $pull, $push or $addToSet don't work with NeDB in update nor patch method.

### ISSUE THREAD

**Issue by ellogwen** [feathersjs/feathers#651]
### Steps to reproduce

I tried to use the modifiers $push, $pull or $addToSet with a NeDB in an update or patch but neither did work. I got several error message like "illegal logical operator "$push" or "do not mix operators with fields" or "field names must not start with a $-sign"

`service('projects').update("<id>", { $addToSet : { userIds: "<newUserId>" } } );`

### Expected behavior
the `<newUserId>` should be added to the list userIds of a project resource when it not already is in the list.

### Actual behavior
error message that $signs are not allowed for fields, that $addToSet is an illegal operator or that you are not allowed to mix fields and modifiers.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
2.1.7
**NodeJS version**:
6.11.1

**Operating System**:
Windows and Linux

**Browser Version**:
Chrome Version 60.0.3112.90 (Official Build) (64-bit)

**React Native Version**:
not in use

**Module Loader**:
Webpack

**Comment by daffl** [comment]
Fixed in `feathers-nedb@2.7.0`
