### ISSUE TITLE
Application-level error hook responses inconsistent across transports

### ISSUE THREAD

**Issue by petermikitsh** [feathersjs/feathers#653]
### Steps to reproduce

Add the following hook to the end of your feathers application (and force all responses to be JSON):

```js
const app = feathers();

app.use(error({html: false})); // force JSON responses for the HTTP transport

app.hooks({
  error(hook) {
    Object.assign(hook.error, {
      errors: { // override a property within the conventional shape of a feathers errors object
         foo: 'bar'
      },
      _error: 'bazzz' // add a new property
    });
    return Promise.resolve(hook);
  }
});
```

Then, call a service method that will throw an error.

Over the HTTP transport, the observed response body is:

```js
{
  "name": "BadRequest",
  "message": "Validation Error",
  "code": 400,
  "className": "bad-request",
  "errors": {
    "foo": "bar"
  }
}
```

<img width="282" alt="screen shot 2017-08-19 at 6 39 51 pm" src="https://user-images.githubusercontent.com/1571918/29491346-ef275216-850d-11e7-8f9a-bc9df70a5742.png">

The `_error` property is missing. (`errors` is overridden as expected).

Over the websocket transport, the response is:

```js
{
  className: "bad-request",
  code: 400,
  errors: {foo: "bar"},
  message: "Validation Error",
  name: "BadRequest",
  stack: "<really long string>",
  type: "FeathersError",
  _error: "bazzz"
}
```

<img width="217" alt="screen shot 2017-08-19 at 6 40 11 pm" src="https://user-images.githubusercontent.com/1571918/29491345-e499bee2-850d-11e7-805e-29d44cb4ed8c.png">

All mutations are present in the websockets response. :+1:

### Expected behavior

When you mutate `hook.error`, you should observe the same mutations across all transports.

### Actual behavior

The HTTP transport is missing some mutations.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working): `feathers@2.2.1`; `feathers-errors@2.9.1`.
**NodeJS version**: 6.0.0
**Module Loader**: Webpack

**Comment by daffl** [comment]
The problem might be in https://github.com/feathersjs/feathers-errors/blob/master/src/index.js#L66 which does not include dynamically added properties vs https://github.com/feathersjs/feathers-socket-commons/blob/master/src/utils.js#L29 iterates through all own properties.

I think the best solution would be to make `toJSON` in `feathers-errors` account for dynamic properties and for `feathers-socket-commons` normalize error to use `toJSON` instead of copying if it is available.
