### ISSUE TITLE
[Best practice] Calling a service from an other service's class

### ISSUE THREAD

**Issue by idealley** [feathersjs/feathers#655]
I am migrating an app from feathers 1 to the latest version. It the previous version I could simply do `this.app.service('other-service'); ` now the app is not available from the `myservice.class.js`

What would you consider best practice in order to give access to another service?

```javascript
  const other-service = app.service('other-service');

  const options = {
    name: 'calendar',
    paginate,
    other-service
  };
```

that can be accessed in the `class` with the following: `this.options.relatives`

is there a better way? 

Thank you

**Comment by daffl** [comment]
It should still be the same. In the `myservice.class.js` just add

```js
setup(app) {
  this.app = app;
}
```

**Comment by idealley** [comment]
Oh, I see. Thank you!

**Comment by idealley** [comment]
Tested. That works perfectly. Thank you.
