### ISSUE TITLE
[question] share hooks with community

### ISSUE THREAD

**Issue by idealley** [feathersjs/feathers#656]
For an api I am writing I created a series of hooks and a middleware for caching requests with redis.

I was wondering if there is an "official" way of packaging and sharing it? I saw the tutorial for plugins, but hooks are not services... 

The middleware simply adds some cache routes (clear a single key, a group of keys, the whole cache).

The hooks add the ability to cache any route by simply adding `cache()` or `cache({duration: 86400})` and there are a before and an after hook that manage the redis stuff. If the before hooks finds a key it sends back the cached content right away.

Let me know if it might be interesting and how to package it thank you!

**Comment by zusamann** [comment]
look at https://github.com/feathersjs/feathers-hooks-common

**Comment by idealley** [comment]
@zusamann nice thank you. 

Can I use prefix feathers-hook-* in the repo/package name?

**Comment by zusamann** [comment]
Yes that would make sense. But why don't you add your hooks to the above repo itself?

**Comment by daffl** [comment]
The easiest way would be to publish them as your own module and add that to the [Ecosystem page](https://docs.feathersjs.com/ecosystem/readme.html).

There is also the [feathers-community-hooks](https://github.com/feathersjs/feathers-community-hooks) repository.

**Comment by idealley** [comment]
I have published a first version: https://github.com/idealley/feathers-hooks-rediscache and updated the documentation for the Ecosystem. Thank you for your help.

**Comment by daffl** [comment]
@idealley Did you make a PR against https://docs.feathersjs.com/ecosystem/readme.html ? I'm not seeing it but will be happy to merge once it is up. Thank you for sharing!

**Comment by idealley** [comment]
@daffl  already sleeping. forgot to commit.
