### ISSUE TITLE
FEATURE PROPOSAL: add a query operator to skip results count in the service find() method

### ISSUE THREAD

**Issue by ramsestom** [feathersjs/feathers#657]
For the find() service method, would be great to add a `$noCount` query operator that allows to skip the results count phase (and speedup the query) when not necessary (in many case, I don't need the results total count and requesting it each time is increasing the load on the server unecessary). I did it on my feathers-sequelize local version by calling `findAll` rather than `findAndCountAll` when this operator is present in the query but it would be fantastic if it was officially supported and for all database adapters ;)

**Comment by DesignByOnyx** [comment]
The reference (and merged) PR allows for this type of functionality now. You can disable pagination by setting `paginate: false` in the service options:

```js
  const options = {
    name: 'some-service',
    Model,
    paginate: false
  };
```

... or for individual service calls by setting `params.paginate = false`.

```js
service.find({ foo: 'bar' }, { paginate: false });
```

**Comment by daffl** [comment]
Indeed, this is handled the same with all database adapters now.

**Comment by dmitry-tuzenkov** [comment]
```
// at mixins.js file

module.exports = function () {
  return function (app) {
    app.mixins.push(function (service) {
      service.findAll = (params = {}) => {
        params.paginate = false
        return service.find(params)
      }
    })
  }
}

// at app.js
...
// Set up mixins
app.configure(mixins)
// Set up our services (see `services/index.js`)
app.configure(services)
...

// at service file

const allSettings = await app.service('settings').findAll({
  query: {
    enabled: true,
  },
})

```
