### ISSUE TITLE
The Site Docs Showing Page Not Found

### ISSUE THREAD

**Issue by korneliuskristianr** [feathersjs/feathers#658]
I'm accessing the docs site at https://docs.feathersjs.com/ it show page not found.

**Comment by thngdude** [comment]
bump

**Comment by zusamann** [comment]
duplicate of https://github.com/feathersjs/feathers-docs/issues/817

**Comment by daffl** [comment]
Looks like a Netlify deploy went wrong. https://docs.feathersjs.com/ is back up.

Although not ideal, in cases like this you can still browse the same documentation in the markdown files at https://github.com/feathersjs/feathers-docs with [SUMMARY.md](https://github.com/feathersjs/feathers-docs/blob/master/SUMMARY.md) as the entry point.
