### ISSUE TITLE
approach to link existing local accounts with oauth2

### ISSUE THREAD

**Issue by LowM4N** [feathersjs/feathers#661]
Have any one an approach or tips, how to link local accounts with oauth2?

**Comment by LowM4N** [comment]
I found this in the default verifier:

verifier.js
```
      // Check request object for an existing entity
      if (req && req[options.entity]) {
        existing = req[options.entity];
      }

      // Check the request that came from a hook for an existing entity
      if (!existing && req && req.params && req.params[options.entity]) {
        existing = req.params[options.entity];
      }

      // If there is already an entity on the request object (ie. they are
      // already authenticated) attach the profile to the existing entity
      // because they are likely "linking" social accounts/profiles.
      if (existing) {
        return this._updateEntity(existing, data).then(function (entity) {
          return done(null, entity);
        }).catch(function (error) {
          return error ? done(error) : done(null, error);
        });
      }
```

It looks like it do this what i want, but the problem are the cookies.
My backend doesn't recognize my login, because the cookie is on the frontend domain (localhost:8000) and my backend runs on localhost:3030.

Frontend:
  - Host: localhost
  - Port: 8000
  - Express Proxy (http-proxy-middleware) from http://localhost:8000/auth/... to http://localhost:3030/auth/...

Proxy section of my server.js
```
app.use('/auth', proxy({
  target: process.env.BACKEND_URL || 'http://localhost:3030',
  changeOrigin: true
}))
```

Backend:
  - Host: localhost
  - Port: 3030

Have any one a solution for that? Or how u handle your cookies with a separate backend?

**Comment by claustres** [comment]
Section 4 in https://blog.feathersjs.com/how-to-setup-oauth-flow-with-featherjs-522bdecb10a8 might help. If everything is setup correctly this should work, I guess you might have mixed front/back URLs in your OAuth2 provider and app configs.

**Comment by LowM4N** [comment]
@claustres 
Thank you for the link, they mention the same problem in the 'Cross-domain issue' section and they give two approaches for that. I will try it :)

**Comment by daffl** [comment]
With cookies enabled and the existing JWT set as `feathers-jwt` in the cookie, account linking is now possible with `@feathersjs/authentication-jwt@^2.0.0` and `@feathersjs/authentication-oauth@^1.2.0`.
