### ISSUE TITLE
[advice] add new hook step 

### ISSUE THREAD

**Issue by pandada8** [feathersjs/feathers#663]
Currently we have `before.all` and `after.all` to prepend and append some hooks to the whole hooks chains. I am requesting  to add new type to append to the before hooks and prepend to the after hooks

### Why need this ?
I am using `softDelete` and want to prepend my custom verification hooks before softDelete, currently I am using  something like
```
_.mapValues(_.omit(module.exports.before, ['all']), values => {
  values.push(softDelete())
})
```
which is not very straightforward  and neat

**Comment by daffl** [comment]
In general, we recommend keeping the complete hook chain explicitly in one file. People usually add `[ ...customsteps, softDelete() ]` in the `.hooks.js` file for re-usable custom steps.

**Comment by pandada8** [comment]
just make 
```
  before: {
    all: [some()],
    find: [a(), b(), softDelete()],
    get: [c(), d(), softDelete()],
    create: [e(), f(), softDelete()],
    update: [g(), h(), softDelete()],
    patch: [i(), j(), softDelete()],
    remove: [k(), l(), softDelete()]
  }
```
into 
```
  before: {
    all: [some()],
    find: [a(), b()],
    get: [c(), d()],
    create: [e(), f()],
    update: [g(), h()],
    patch: [i(), j()],
    remove: [k(), l()],
    finally: [softDelete()],
  }
```
I think there could be a better name for 'finally', but this is definitely make things more concise and easier to read and modify.

**Comment by daffl** [comment]
You can call `.hooks` multiple times and they will be chained. In your case it would be

```
app.hooks({
  before: {
    all: [some()],
    find: [a(), b()],
    get: [c(), d()],
    create: [e(), f()],
    update: [g(), h()],
    patch: [i(), j()],
    remove: [k(), l()],
  }
}).hooks({
  before: softDelete()
})
```

This should do exactly what you want.

**Comment by pandada8** [comment]
that's impressive
