### ISSUE TITLE
"Authentication strategy 'local' is not registered

### ISSUE THREAD

**Issue by jordanbtucker** [feathersjs/feathers#666]
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by jordanbtucker** [comment]
Sorry. Not sure how this duplicate got created.

**Comment by StellarTabi** [comment]
Here's the duplicate since this is the first result on Google: https://github.com/feathersjs/feathers/issues/667
