### ISSUE TITLE
Sequelize data is not showing correct

### ISSUE THREAD

**Issue by devfelipereis** [feathersjs/feathers#673]
Hello guys.. I'm trying to learn feathers and my api is not showing the data correct.

![screenshot from 2017-09-14 23-32-39](https://user-images.githubusercontent.com/5348752/30464801-09120b0c-99aa-11e7-8bf3-02a7c774012b.png)

I have users and users can have "shopping lists".

In users model I have: this.hasMany(models.shopping_lists, {foreignKey: "user_id"});

And a hook for user model like this: 

```
hook.params.sequelize = {
    distinct: true, // must set this in order to get correct total count
    include: [{ all: true, nested: true }]
 };
```

Anyone knows why my data showing in that way?

I was expecting users with an array of shopping lists.

Thanks!

**Comment by daffl** [comment]
See https://github.com/feathersjs/feathers-sequelize/issues/149. Try setting `raw: false` in your [service options](https://github.com/feathersjs/generator-feathers/blob/master/generators/service/templates/service.js#L13).

**Comment by devfelipereis** [comment]
@daffl Perfect! Now my 1:N and N:N relations are working fine.
I read the issue and now I understand.
Thanks for the info.
