### ISSUE TITLE
get query for $in array of ObjectId 

### ISSUE THREAD

**Issue by neerajincaendo** [feathersjs/feathers#674]
How can query to find all records with $in in get query method having array of mongoid's in roomId? 

i am trying this
GET /messages?roomId[$in]=59b8b7fcef9651220d205f5a 

Getting a general error in response : $in needs an array

And when i use like this:  GET /messages?roomId[$in]=[59b8b7fcef9651220d205f5a] , i am getting error Cast to ObjectId failed for value ["59b8b7fcef9651220d205f5a"] 

here's my mongoose schema :     roomId: [{ type: Schema.Types.ObjectId, ref: 'room' }],

**Comment by daffl** [comment]
Since a query string does not have any type information you have to indicate that you want it to be converted to an array for `$in` by adding `[]` like this:

```
/messages?roomId[$in][]=59b8b7fcef9651220d205f5a
```

Reference: [qs documentation](https://github.com/ljharb/qs#parsing-arrays).
