### ISSUE TITLE
sequelize - connection string - problem with password containing an @

### ISSUE THREAD

**Issue by FredericLatour** [feathersjs/feathers#676]
It looks like it doesn't work when having a password containing a **@** directly in the connection string for sequelize:

- "mysql": "mysql://user:pwd@host:port/database"

I imagine (just a guess) that it has something to do with the @ that is used to separate the `password` and the `host`. It certainly mess up the parsing to have another @.

**Comment by daffl** [comment]
SQL connection strings with special characters have to be URL encoded:

```js
encodeURIComponent('my@password') // -> 'my%40password'
```

**Comment by FredericLatour** [comment]
Not a show stopper but not very intuitive especially in those days when we are force to include weird chars into passwords.
Is it possible to provide a config object instead of this connection string?
```
{
user: '',
pwd:'',
host: '',
etc ...
}

```

**Comment by daffl** [comment]
You can always change the connection as [shown in the Sequelize documentation](http://docs.sequelizejs.com/manual/installation/getting-started.html#setting-up-a-connection) in the [connection file set up by the generator](https://github.com/feathersjs/generator-feathers/blob/master/generators/connection/templates/sequelize.js#L6).

**Comment by FredericLatour** [comment]
I suppose I'd better not hacking this file and stick with your solution. It's not like I will have a password to encode every day, after all.
Thanks for the help (will close the issue).
