### ISSUE TITLE
For when feathers for babel 7 ?

### ISSUE THREAD

**Issue by simonjoom** [feathersjs/feathers#678]
I saw that feathers still use old plugin add-module-export and the code module is babel 6 

When do you think you will update code to support babel7 ? (to allow common-js and tree shaking)

**Comment by daffl** [comment]
I was not aware that there is an official version of Babel 7.

Anyway, Feathers will be using ES6 imports natively only once it is officially enabled in all Node versions that Feathers supports. For now we are actually going back to `require` (see #608) to make things usable without a transpiler.

A Feathers v3 client build will be even smaller already (at about 8k min+gziped) so I don't think there is that much of a benefit from tree shaking.

**Comment by simonjoom** [comment]
yes it's not really about tree-shaking but compatibility with babel 7 who will become standard.
the version babel 7 beta is already out, and work for me.

**Comment by daffl** [comment]
We'll be removing Babel completely in the next version so there isn't really a reason to upgrade to v7.
