### ISSUE TITLE
Auth0 is not working

### ISSUE THREAD

**Issue by ishrak-imam** [feathersjs/feathers#679]
I am trying to integrate Auth0 authentication with feathersJS and I followed the example provided in the authentication guide of feathersJS doc. I selected Auth0 after `feathers generate authentication` command and configured my Auth0 clientId, secret and domain in the default.json file and when Auth0 calls back to the provided callback url with a code in query string there is a 500 internal server error like in th following screenshot.
![screenshot from 2017-09-21 23-45-09](https://user-images.githubusercontent.com/16683923/30710309-f5811ba0-9f26-11e7-9da5-560ee774dbcb.png)

**Comment by marshallswain** [comment]
For me this issue has usually come up because of a misconfigured app setup in Auth0.  

Hmm.  Maybe disable the error handler middleware to see a better error.
