### ISSUE TITLE
Example of async/await for hooks needed

### ISSUE THREAD

**Issue by ozerfrettelter** [feathersjs/feathers#680]
It would be really great if someone could give a working example of a hook function that is using ES7 async/await pattern.

The generator generates a stub like this:

```
// Use this hook to manipulate incoming or outgoing data.
// For more information on hooks see: http://docs.feathersjs.com/api/hooks.html

module.exports = function (options = {}) { // eslint-disable-line no-unused-vars
  return function myHook (hook) {
    // Hooks can either return nothing or a promise
    // that resolves with the `hook` object for asynchronous operations
    return Promise.resolve(hook);
  };
};
```

I couldn't find a way to make an awaitable call like 

`response = await request('https://whatever.com')`

inside the myHook. Any help is greatly appreciated!

**Comment by daffl** [comment]
You just have to make `return function myHook` async:

```js
// Use this hook to manipulate incoming or outgoing data.
// For more information on hooks see: http://docs.feathersjs.com/api/hooks.html

module.exports = function (options = {}) { // eslint-disable-line no-unused-vars
  return async function myHook (hook) {
    const body = await request('https://whatever.com');
    return hook;
  };
};
```

**Comment by daffl** [comment]
I was thinking this morning of adding some examples though indeed.

**Comment by ozerfrettelter** [comment]
Thanks a lot! After removing my stupid mistake and using your example everything works perfect! I think it's a good idea to add an example to the docs since async/await makes the code so much more readable.
