### ISSUE TITLE
Translate not only REST PHP backend into FeathersJS

### ISSUE THREAD

**Issue by donlucacorleone** [feathersjs/feathers#683]
I'm very new to Feathers JS and similar Node.JS frameworks. I know it's "An open source REST and realtime API layer for modern applications." and I already studied the docs and samples.

I'd like to develop a web app that's not only a REST but instead a real app. For the sake of semplicity, let's assume it's a slideshow app controllable via some remote clients. This is a brief description of how it should work:

- slideshow.js (client-side) picks an image from a database and shows it. Every 10 seconds it requests a new image from the DB. This part is REST-compliant (e.g. using GET verb).
- remote.js (client-side) knows which image is currently shown by the slideshow app (again, I think it's REST-compliant since it can ask the server about the slideshow status).
- remote.js can send a message to the server in order to advance to next image. Is this a REST pattern?! I don't tink so...

Basically I'd like to:

1. send messages from remote.js instances to server (using WebSockets)
2. process them on the server using my custom app logic (e.g. searching for next image on the db)
3. send a message from the server to slideshow.js, telling it to display the image found by the server
4. and send a message from the server to all the connected remote.js to notify them the new image is changed.

I already create this things in PHP and JavaScript, so I've no doubt about the logic. I need help translating the server side using FeathersJS concepts since I'm really new to them and I find really difficult to catch them.

I created a images service to store the actual images.

Do I have to create a command service to store the commands the remote.js instances send to slideshow.js ?

Do I need to create an after create hook bound to command service that emits a Socket.IO message to all remote.js instances notifying about the new image ?

Or is better to create a status service? In this case it ain't to be a database because it's actually a status (e.g. containing an index of the image currently shown)

**Comment by daffl** [comment]
One of the key insights of Feathers is the fact that every app is ultimately a REST application. In your case, the Slideshow is tied to a user (or similar entity) which has a `currentSlide` property that contains the slide information they are currently watching. Real-time updates are accomplished by `PATCH`ing that entity with the new `currentSlide` data. Basically the `status` service you are describing.

Services don't have to be tied to a database. They can be in-memory or even point to other APIs.

**Comment by donlucacorleone** [comment]
A-ah! I got it! Thank you for your helpful reply.
To extend the slideshow example, let's say we need also a `direction` property (used to store current forward/backward direction).
Do you suggest to build a `generic status` service, or it's better to have a separate service for each of the properties? I mean, one `currentSlide` service and one `direction` service.

**Comment by daffl** [comment]
Wouldn't the client know in what direction it goes? Anyway, I would just store an `offset` property that contains `1` or `-1` for the direction. Going to close this issue since it is a pretty broad question. Happy to help out with any more specific issues though.
