### ISSUE TITLE
How to resolve the google gmail errors ?

### ISSUE THREAD

**Issue by jpca999** [feathersjs/feathers#690]
This isnt really related to feathers, but i want to how other people try to use google gmail auth ?

My app requires users to be send emails out from within the app, but usual setup with node mailer is failing on me. 

Will  using google's auth help to avoid these errors coz user already logged in via the google auth ?

![image](https://user-images.githubusercontent.com/1026325/31443675-236484ee-ae68-11e7-89ed-14e73d7cc387.png)

### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by daffl** [comment]
I haven't seen that one before but according to [this Stackoverflow question](https://stackoverflow.com/questions/19877246/nodemailer-with-gmail-and-nodejs) using an  XOAuth2 token or enabling the flag to allow less secure applications might work.
