### ISSUE TITLE
@types/express in dependencies

### ISSUE THREAD

**Issue by sonycamera** [feathersjs/feathers#693]
feathers: "^2.1.1"

When I built my project for production, I found there are some @types/ packages in ./node_modules/ which should not be included in 'production' release (npm install --only=production). I checked modules and found the dependence is introduced in feathers/package.json:
```
  "dependencies": {
    "@types/express": "~4.0.35",
    "babel-runtime": "^6.26.0",
    "debug": "^3.1.0",
    "events": "^1.1.1",
     ...
```

I think '@types/express' should be removed to 'devDependencies' section, and all 'devDependencies' packages should be remove out from package-lock.json.

**Comment by daffl** [comment]
Makes sense, thank you. Will be fixed in #696
