### ISSUE TITLE
http verbs

### ISSUE THREAD

**Issue by GlauberF** [feathersjs/feathers#700]
### to limit http verbs

Hello, how can I restrict the use of HTTP verbs in certain services. I have a service called log, in this service I can only accept the methods (all, find, get, create) the rest (update, patch, remove) I have to disable for this service.

If you can help me, I thank you.

**Comment by daffl** [comment]
You can use the [disallow common hook](https://docs.feathersjs.com/api/hooks-common.html#disallow).

**Comment by GlauberF** [comment]
ok, thank you
