### ISSUE TITLE
before executing HTTP verb

### ISSUE THREAD

**Issue by GlauberF** [feathersjs/feathers#701]
### before executing HTTP verb

before any call http, example (get). I need to analyze if some data is present in the request headers, if present I let it run normally, otherwise I end the execution before even calling the HTTP verb.

**Comment by daffl** [comment]
Use a [custom Express middleware](https://docs.feathersjs.com/api/express.html#custom-service-middleware) before registering the service.

**Comment by GlauberF** [comment]
Right, if it is not present what I want in the headers how do I cancel the request?

Another question, how do I make it global, be applied in all my services?

**Comment by daffl** [comment]
It's exactly the same as normal [Express middleware](http://expressjs.com/en/guide/writing-middleware.html). So to cancel you either use `res.send` or `res.json` and don't call `next` or call `next(error)` with an error to trigger the error handler.

Also just like in Express, if you `app.use(myMiddleware)` before registering any services (`app.configure(services)` in the generated application) it will run for all routes.

**Comment by GlauberF** [comment]
Okay, it worked. I applied globally.

But it needs to be globally applied, at least to a URL.

I've set up to apply globally, my question now is, how to remove this Middleware from only one route in a service.

**Comment by daffl** [comment]
You'll have to [add it on a route](http://expressjs.com/en/guide/routing.html) using a regular expression that excludes that route or check for the condition you want to exclude.
