### ISSUE TITLE
service with different mongodb connections

### ISSUE THREAD

**Issue by GlauberF** [feathersjs/feathers#702]
### service with different mongodb connections

Hello, can I get more than one mongodb connection in the same project?

Example I need a database to access a database and my other services another database.

how could I work with it?

**Comment by daffl** [comment]
Have a look at how the generator sets up the connection at https://github.com/feathersjs/generator-feathers/blob/master/generators/connection/templates/mongodb.js. Copy the file and configure it the same way with a different connection string from the configuration and `app.set` it under a different name (`app.set('mongoClient2', promise);`), then use that name to get the Model in your generated MongoDB service (https://github.com/feathersjs/generator-feathers/blob/master/generators/service/templates/types/mongodb.js#L19).
