### ISSUE TITLE
Can't skip create service method call when setting hook.result

### ISSUE THREAD

**Issue by dschnare** [feathersjs/feathers#705]
### Steps to reproduce

Use the generator to create a really simple service (books) that is backed by memory. Put this hook as a `before:create` hook:

```js
hook => {
  console.warn('we are skipping the create service, so we think!')
  hook.result = [ 'we have been skipped!' ]
  return hook
}
```

Now try hitting your `books` service like so:

```js
app.service('books').create('can send anything because the create should be skipped!')
```

### Expected behavior

The create service method should be skipped.

### Actual behavior

The create service method is called as usual, despite the hook having a `result` property set by a before hook.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working): Feathers 2.1.7

**NodeJS version**: 6.11.3

**Operating System**: OSX 10.12.6

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by dschnare** [comment]
Actually, I think my exact problem I'm having is I want a hook to short circuit the entire chain of before hooks iff `hook.result` is set. Never mind guys, I'll assume the create service method works as expected if the last before hook sets `hook.result` then the create service method will be skipped.

**Comment by kremer-io** [comment]
@dschnare @daffl I'ld still expect, that no record should be created, because you already set `hook.result` to some value in a **before hook.** 

From [here](https://docs.feathersjs.com/api/hooks.html#contextresult):
> `context.result` can also be set in ...  before hook to skip the actual service method (database) call

**Comment by schurigh** [comment]
+1 same here

**Comment by daffl** [comment]
No record _will_ be created. I just confirmed that this is the case in the [feathers-chat](https://github.com/feathersjs/feathers-chat).

**Comment by kremer-io** [comment]
Thx @daffl. You're right, I also just confirmed it. Nevermind.
