### ISSUE TITLE
pagination

### ISSUE THREAD

**Issue by GlauberF** [feathersjs/feathers#707]
### pagination with agularjs

Could anyone help me, how can I work with paging on feathers with angularjs ??

**Comment by subodhpareek18** [comment]
Can you please join the slack channel of feathersjs and ask questions there rather than creating issues for such problem statements.

https://feathersjs.slack.com

**Comment by GlauberF** [comment]
ok

**Comment by daffl** [comment]
Related:

- https://docs.feathersjs.com/api/databases/common.html#pagination 
- https://docs.feathersjs.com/api/databases/querying.html#limit
- https://docs.feathersjs.com/api/databases/querying.html#skip

I agree with @subodhpareek18 however that the Slack channel is better suited for this type of questions.
