### ISSUE TITLE
why are there 2 mongo plugins with feathers  mongoose and mongoDB

### ISSUE THREAD

**Issue by jpca999** [feathersjs/feathers#709]
1) is there feathers forum thtat i can ask you quetsions on 

2) so why do we have mongoose and mongoDB ?

Just after creating a feathers service, why do i get this error  ?

![image](https://user-images.githubusercontent.com/1026325/32072647-47116b6e-ba61-11e7-8134-9bbd560497e2.png)

**Comment by daffl** [comment]
You are probably calling `app.configure()` somewhere without passing a function. Also, Mongoose is an "Object modelling" tool for MongoDB so it is not the same as using plain MongoDB directly.

There is no forum. For questions, either use Stackoverflow with the `feathersjs` tag or [join the Slack channel](http://slack.feathersjs.com/).

**Comment by jpca999** [comment]
K great, thanks :-)
