### ISSUE TITLE
Cannot find module 'express-serve-static-core'

### ISSUE THREAD

**Issue by nikogamulin** [feathersjs/feathers#710]
Hi,

Up until now everything worked fine, but after deleting node_modules folder and running npm install and then ng serve, the following errors appeared:

`ERROR in /Users/nikogamulin/workspace/anxamo/md-angular-v1.4.1/node_modules/feathers/index.d.ts (2,30): Cannot find module 'express-serve-static-core'.
ERROR in /Users/nikogamulin/workspace/anxamo/md-angular-v1.4.1/node_modules/feathers/index.d.ts (24,13): All declarations of 'Service' must have identical type parameters.
ERROR in /Users/nikogamulin/workspace/anxamo/md-angular-v1.4.1/node_modules/feathers-reactive/index.d.ts (26,13): All declarations of 'Service' must have identical type parameters.
ERROR in /Users/nikogamulin/workspace/anxamo/md-angular-v1.4.1/node_modules/feathers-hooks/index.d.ts (6,15): All declarations of 'Service' must have identical type parameters.
`
This is an angular 2 app. In case it might be helpful to resolve the issue, below is the copy of package.json file used in the app:

```
{
  "name": "md-free-angular-cli",
  "version": "1.4.1",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.4.6",
    "@angular/cdk": "2.0.0-beta.10",
    "@angular/common": "4.3.1",
    "@angular/compiler": "4.3.1",
    "@angular/core": "4.3.1",
    "@angular/forms": "4.3.1",
    "@angular/http": "4.3.1",
    "@angular/material": "2.0.0-beta.10",
    "@angular/platform-browser": "4.3.1",
    "@angular/platform-browser-dynamic": "4.3.1",
    "@angular/router": "4.3.1",
    "@toverux/ngsweetalert2": "^2.0.1",
    "@types/socket.io-client": "^1.4.31",
    "angular2-jwt": "^0.2.3",
    "angular2-notifications": "^0.7.8",
    "angular2-tag-input": "^1.2.3",
    "arrive": "2.4.1",
    "body-parser": "^1.18.2",
    "bootstrap": "3.3.7",
    "bootstrap-material-design": "0.5.10",
    "bootstrap-notify": "3.1.3",
    "chartist": "0.11.0",
    "core-js": "2.4.1",
    "feathers": "^2.2.3",
    "feathers-authentication": "^1.2.7",
    "feathers-authentication-jwt": "^0.3.2",
    "feathers-authentication-local": "^0.4.4",
    "feathers-errors": "^2.9.2",
    "feathers-hooks": "^2.1.0",
    "feathers-memory": "^1.3.0",
    "feathers-reactive": "^0.5.3",
    "feathers-rest": "^1.8.0",
    "feathers-socketio": "^2.0.0",
    "googleapis": "19.0.0",
    "jquery": "3.2.1",
    "moment": "2.18.1",
    "ngx-chips": "^1.5.3",
    "rxjs": "5.1.0",
    "socket.io-client": "^2.0.3",
    "sweetalert2": "^6.11.0",
    "zone.js": "0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.4.2",
    "@angular/compiler-cli": "4.3.1",
    "@types/jasmine": "2.5.38",
    "@types/node": "6.0.73",
    "codelyzer": "2.0.0",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "3.2.0",
    "karma": "1.4.1",
    "karma-chrome-launcher": "2.0.0",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "0.2.0",
    "karma-jasmine": "1.1.0",
    "karma-jasmine-html-reporter": "0.2.2",
    "protractor": "5.1.0",
    "ts-node": "2.0.0",
    "tslint": "4.5.0",
    "typescript": "2.3.4"
  }
}


```

**Comment by daffl** [comment]
This should be fixed now by updating `feathers-reactive` to version 0.5.4.

**Comment by nikogamulin** [comment]
@daffl I updated geathers-reactive to 0.5.4. Some of the errors have been solved but the following remained:

ERROR in /Users/nikogamulin/workspace/anxamo/md-angular-v1.4.1/node_modules/feathers/index.d.ts (2,30): Cannot find module 'express-serve-static-core'.

**Comment by nikogamulin** [comment]
I solved the issue by deleting feathers folder in node_modules and then running again npm install feathers --save

**Comment by dottodot** [comment]
I'm getting the error `]: ERROR in node_modules/feathers/index.d.ts(2,30): error TS2307: Cannot find module 'express-serve-static-core'.` as well

It's fine on my local installation by not when I push to my server. I'm using flynn which is a bit like heroku

**Comment by daffl** [comment]
Looks like it is an error in the TypeScript definitions. You should probably deploy a compiled version without TypeScript to your production server.

**Comment by dottodot** [comment]
Think it was due to dependencies adding express-serve-static-core to my package.json sorted it

**Comment by shirakaba** [comment]
I experienced this error in a `ts-node` project due to my globally-installed Node (which `ts-node` depends upon) being out-of-date (v4.8.7). I updated it to v8.9.4 and it worked fine.

Perhaps that this newer version of `express-serve-static-core` uses newer ECMAScript features that the old Node doesn't understand, indirectly causing its import to fail.
