### ISSUE TITLE
WebSocket is closed before the connection is established

### ISSUE THREAD

**Issue by musicformellons** [feathersjs/feathers#712]
I had the feathersjs with quasar chat app working locally. Then I moved the server on a remote server and now I keep getting this error in the browser console:
`WebSocket connection to 'ws://mydomain.com:8089/socket.io/?EIO=3&transport=websocket' failed: WebSocket is closed before the connection is established.`

I can ping the server and netstat tells me port 8089 is listened on. I do not know what's wrong. I have no experience with websockets. I choose Primus with ws. Could that maybe cause this? Other suggestions?

**Comment by musicformellons** [comment]
The actual output from netstat:


	tcp6       0      0 :::8089                 :::*                    LISTEN      0          191916      22828/node      
	tcp6       0      0 <server-ip-address>:8089     <client/local-ip-address>:57168    CLOSE_WAIT  0          216624      22828/node      
	tcp6       0      0 <server-ip-address>:8089     <client/local-ip-address>:57740    CLOSE_WAIT  0          216636      22828/node      
	tcp6       0      1 <server-ip-address>:8089     <client/local-ip-address>:55256    LAST_ACK    0          0           -               
	tcp6       0      1 <server-ip-address>:8089     <client/local-ip-address>:54280    LAST_ACK    0          0           -               
	tcp6       0      1 <server-ip-address>:8089     <client/local-ip-address>:56086    LAST_ACK    0          0           -               
	tcp6       0      0 <server-ip-address>:8089     <client/local-ip-address>:57496    CLOSE_WAIT  0          216629      22828/node      
	tcp6       0      1 <server-ip-address>:8089     <client/local-ip-address>:55182    LAST_ACK    0          0           -               
	tcp6       0      1 <server-ip-address>:8089     <client/local-ip-address>:54774    LAST_ACK    0          0           -               
	tcp6       0      0 <server-ip-address>:8089     <client/local-ip-address>:57414    CLOSE_WAIT  0          216626      22828/node      
	tcp6       0      1 <server-ip-address>:8089     <client/local-ip-address>:55552    LAST_ACK    0          0           -               
	tcp6       0      0 <server-ip-address>:8089     <client/local-ip-address>:56808    CLOSE_WAIT  0          216615      22828/node      
	tcp6       0      0 <server-ip-address>:8089     <client/local-ip-address>:56342    CLOSE_WAIT  0          216606      22828/node      
	tcp6       0      1 <server-ip-address>:8089     <client/local-ip-address>:55470    LAST_ACK    0          0           -               
	tcp6       0      0 <server-ip-address>:8089     <client/local-ip-address>:56594    CLOSE_WAIT  0          216613      22828/node      
	tcp6       0      0 <server-ip-address>:8089     <client/local-ip-address>:56174    CLOSE_WAIT  0          216604      22828/node      
	tcp6       0      1 <server-ip-address>:8089     <client/local-ip-address>:54848    LAST_ACK    0          0           -               
	tcp6       0      1 <server-ip-address>:8089     <client/local-ip-address>:55884    LAST_ACK    0          0           -               
	tcp6       0      1 <server-ip-address>:8089     <client/local-ip-address>:55796    LAST_ACK    0          0           -               
	tcp6       0      1 <server-ip-address>:8089     <client/local-ip-address>:54366    LAST_ACK    0          0           -               
	tcp6       0      0 <server-ip-address>:8089     <client/local-ip-address>:58310    ESTABLISHED 0          216782      22828/node      
	tcp6       0      0 <server-ip-address>:8089     <client/local-ip-address>:56428    CLOSE_WAIT  0          216608      22828/node      
	tcp6       0      0 <server-ip-address>:8089     <client/local-ip-address>:57980    CLOSE_WAIT  0          216640      22828/node      
	tcp6       0      1 <server-ip-address>:8089     <client/local-ip-address>:55630    LAST_ACK    0          0           -               
	tcp6       0      0 <server-ip-address>:8089     <client/local-ip-address>:57902    CLOSE_WAIT  0          216638      22828/node      
	tcp6       0      0 <server-ip-address>:8089     <client/local-ip-address>:57086    CLOSE_WAIT  0          216619      22828/node      
	tcp6       0      0 <server-ip-address>:8089     <client/local-ip-address>:57574    CLOSE_WAIT  0          216631      22828/node      
	tcp6       0      0 <server-ip-address>:8089     <client/local-ip-address>:58066    CLOSE_WAIT  0          216643      22828/node      
	tcp6       0      1 <server-ip-address>:8089     <client/local-ip-address>:55104    LAST_ACK    0          0           -       

So I think it is listened on but can not really connect although trying.

**Comment by musicformellons** [comment]
For more details, see:
https://stackoverflow.com/questions/46997652/websocket-is-closed-before-the-connection-is-established-using-feathersjs

**Comment by musicformellons** [comment]
I now tried with socketio instead of primus & ws, and then it works! So the issue is primus & ws related.

**Comment by musicformellons** [comment]
I was hoping the generator would take care of ‘everything’ when selecting Primus. I am now trying to get Primus working with uws.

On the server I installed uws:
`npm install uws --save`

On the server I changed this part in app.js:
`app.configure(primus({ transformer: 'uws' }));`

In my webapp client I added in index.html (it's a vue app so that's the only html file...?!) just before the </body> tag:
```
<script type="text/javascript" src="primus/primus.js"></script> 
<script>
  var socket = new Primus('http://<myserver-ip>:port');
</script>
```

Unclear to me:
1. Probably I need to provide primus.js from a static folder primus/primus.js in my app or something? How do I do that?
2. “The socket connection URL has to point to the server root which is where Feathers will set up Primus.” I suppose that is  http://<myserver-ip>:port in my case…?!


Other questions based on the docs in this area:

1. “Note: A client application can only use a single transport (either REST, Socket.io or Primus). Using two transports in the same client application is normally not necessary.” So how do I prevent myself from using two transport protocols? Could you give an example of an abnormal case which uses REST and websockets simultaneously? E.g. I have a geomap in my app which get its tiles with REST, so that applies I suppose?
2. In the docs of both feathers and primus I find “creating a server side client” and “If you want to use the client interface inside of Node.js”. When would I need that? I think I don’t but I’m not sure…?!
3. On Primus readme it says “uws is a WebSocket only transformer”. How do socketio and uws differ? When does uws fall short, as it seems like a stripped down websocket library or something…? For e.g. I see people use socketio with uws as the engine; why do they do that?

**Comment by daffl** [comment]
The client library is generated dynamically so you will have to reference it directly (with `//api.mydomain.com/primus/primus.js` or generate and save it [as shown in the Primus documentation](https://github.com/primus/primus#client-library).

For the other questions:

1. You don't have to prevent it, it just isn't possible (unless you initialize the client services manually). This is only talking about the connection to the Feathers API through the client, you can still always make HTTP requests to other resources.
2. Other Node applications can connect to another Feathers server just like the browser does. This is important if you want to e.g. distribute your application across multiple micro-services.
3. Socket.io has long-polling and other fallbacks when websockets are not available (even if you are using it with uws).

**Comment by musicformellons** [comment]
Thanks for you answers! Do you maybe have an example project, as I am still a bit unsure how to go about the client library?

**Comment by daffl** [comment]
The Feathers chat has client side implementations for plain JavaScript and jQuery at https://github.com/feathersjs/feathers-chat/tree/master/public. There is also 

- https://github.com/feathersjs-ecosystem/feathers-chat-react
- https://github.com/feathers-plus/feathers-chat-vuex
- https://github.com/feathersjs-ecosystem/feathers-chat-angular

**Comment by musicformellons** [comment]
I was more referring to using primus (with uws) in the client. As I noticed that socketio is using uws under the hood I think I am going that way as that setup just works instantly, whereas I do not find any example with primus & uws. Thanks for your help and making feathers!
