### ISSUE TITLE
Filtering events of non-authenticated users

### ISSUE THREAD

**Issue by ComputerCarl** [feathersjs/feathers#717]
I am struggling to understand how to emit events to only the client whom made the origianl request.

* I am using FeathersJS on the backend and create-react-app on the front and I have them successfully communicating via socket.io.
* There is a service defined whose endpoint is called `sample` and is registered on both client and server.
* There is no `users` service or authentication.
* The user issues a `find` command and (almost) immediately a message (promise) is returned from the original request (e.g., to tell the client their request was OK)
* At some time in the future, another event is emitted on the server.. which I would like ionly the original client to "hear".

````js
// etc on client
const sampleService = client.service('/sample');

sampleService.on('sendResult', (data) => console.log(data));

const myID = 4; // UUID number checked/set on first visit
const findSomething = () => {
  sampleService
    .find({query: {keywords: "anything", userlessid: myID}})
    .then((result) => console.log(result))
    .catch((err) => console.error(err));
}

findSomething();
````

````js
// server
var sampleService = app.use('/sample', {
  events: ['sendResult'],
  find: function (params) {
    params.userlessid // person's ID
    console.log('find function params ', params);
    // emit event filtered to whomever requested (userlessid: 4)
    setTimeout(() => {this.emit('sendResult', {result: 'huge stuff', forID: params.userlessid})}, 3000);
    return Promise.resolve({message: "queued"});
  }
});
````

**Comment by daffl** [comment]
In order for the server to know the generated id you will probably have to register it on the socket with a [custom Socket.io event](https://docs.feathersjs.com/api/socketio.html#appconfiguresocketiocallback):

```js
app.configure(socketio(function(io) {
  io.on('connection', function(socket) {
    socket.on('register-id', data => {
      socket.feathers.userlessid = data.id;
    });
  });
}));
```

Then in a [filter](https://docs.feathersjs.com/api/events.html#event-filtering) you can check if the ids (on `connection.userlessid`) matches:

```js
messages.filter('sendResult', function(data, connection) {
  if(!connection.userlessid !== data.forID) {
    return false;
  }

  return data;
});
```

**Comment by ComputerCarl** [comment]
I've spent countless hours at this and thought this was the silver bullet when I found it in the channel/rooms FAQs but I whenever I did the filter comparison, there was never anything added to the connection object and I was left with only {provider: 'socketio'}.

Your expertise once again got me in working order, so thank you!

I have also created Gists for *Working FeathersJS - React Socket.IO Communication and Event Listeing Filtering without Authentication* if anyone should need examples

**Comment by daffl** [comment]
Glad it worked! Oh and for completeness, using [v3 and channels](https://gist.github.com/daffl/e718f93acc7bfe32fd1e5aed0f8e7827) this would look like this:

```js
app.configure(socketio(function(io) {
  io.on('connection', function(socket) {
    socket.on('register-id', data => {
      // socket.feathers is a valid connection that channels can join
      app.channel(data.id).join(socket.feathers);
    });
  });
}));

app.service('sample').publish('sendResult', eventData => app.channel(eventData.forID));
```

Or, if you know the id already before connecting to the socket you could do:

```js
app.configure(socketio(function(io) {
  io.use((socket, next) => {
    socket.feathers.userlessid = socket.request.query.userlessid;
    
    next();
  });
}));

app.on('connection', connection => {
  if(connection.userlessid) {
    app.channel(connection.userlessid).join(connection);
  }
})

app.service('sample').publish('sendResult', eventData => app.channel(eventData.forID));
```

Then on the client:

```js
const socket = io("http://127.0.0.1:3000/", { query: "userlessid=<id here>" });
```
