### ISSUE TITLE
Mount service at root

### ISSUE THREAD

**Issue by sergiuwd** [feathersjs/feathers#718]
I am building a microservices architecture using FeathersJS and I only need one service per application, so I will mount that service to the root (`/`) of each app.
I have tried to do that using `/` as a path when I'm generating the service (Mongoose) and deleting the `app.use('/', express.static(app.get('public')));` line from `app.js` and it works as it should when I'm accessing the base path (it lists all entries), but when I try `/421jsadi23o1sj` to find an entry, it returns 404.

I think it gets that ID as being a service's path and looks for it.

This is my *businesses.service.js* file:

    const createService = require('feathers-mongoose');
    const createModel = require('../../models/businesses.model');
    const hooks = require('./businesses.hooks');
    
    module.exports = function (app) {
      const Model = createModel(app);
      const paginate = app.get('paginate');
    
      const options = {
        name: 'businesses',
        Model,
        paginate
      };
    
      // Initialize our service with any options it requires
      app.use('/', createService(options));
    
      // Get our initialized service so that we can register hooks and filters
      const service = app.service('/');
    
      service.hooks(hooks);
    
      app.publish(() => {
        // Here you can add event publishers to channels set up in `channels.js`
        // To publish only for a specific event use `app.publish(eventname, () => {})`
    
        // e.g. to publish all service events to all authenticated users use
        // return app.channel('authenticated');
      });
    };

Had anyone came across this issue? Any ideas about how it can be solved?

**Comment by daffl** [comment]
I would consider this to be an undefined behaviour because in general a service is expected to always have a name (and an empty string as the name might have weird side effects since it is falsy). Maybe this should even throw an error.

In short, always give a service a name 😄

**Comment by keesee** [comment]
@daffl is correct.  Strange issues when name is false.   Issue is closed, but I'm adding a solution for those whom might be search for this answer.  

We solved it via:
Adding the micro-service name to the config for the app, using it in the service and then adding middleware that handles forwarding from '/'.

```
module.exports = function () {
  const chassis   = this;
  const Model     = createModel(chassis);
  const paginate  = chassis.get('paginate');
  const name      = chassis.get('name')
  const options   = { name: name, Model, paginate };
  // Initialize our service with any options it requires
  chassis.use(`/${name}`, createService(options));
  const service = chassis.service(name);
  service.hooks(chassis.get('service-hooks') || []);

  if (chassis.get('service-filters')) {
    service.filter(chassis.get('service-filters'));
  }
};
```

and then the following middleware.  order matters so this needs to run before you configure services on the chassis (app).


```
  chassis.use('/', function (req, res, next) {
    req.url = '/'+chassis.get('name');
    next();
  });
```
