### ISSUE TITLE
Why the relationship between the tables not work? [sequelize]

### ISSUE THREAD

**Issue by vodniciarv** [feathersjs/feathers#721]
I have:
 - the framework Feathers ^2.2.3
 - ORM sequelize (feathers-sequelize ^2.3.2)
 - MySQL database
 - 2 tables (between them should work communication)

in file **category.model.js** describe the relationship:

```
category.associate = function (models) {
        models.category.belongsTo(models.category_translate, {
          foreignKey: 'id',
          targetKey: 'category_id',
          as: 'translate'
        });
};
```

Now if you open **localhost:3030/category** then the result of this query is showed:

```SELECT `id`, `icon`, `parent` FROM `category` AS `category` LIMIT 10;```

Tried so **localhost:3030/category?$select[]=translate**, to access the fields from a linked table, but there was an error.

What I'm doing wrong?
How can I access data from another link table from the current model?

Thank You in advance for the answers!

**Comment by daffl** [comment]
[This answer](https://stackoverflow.com/questions/42841810/feathers-js-sequelize-service-with-relations-between-two-models/42846215#42846215) should have all the information you need, specifically that you have to set `hook.params.sequelize.include` in a `before` hook.

**Comment by vodniciarv** [comment]
You helped me a lot, thank You!
