### ISSUE TITLE
Getting the user details when authenticated via client

### ISSUE THREAD

**Issue by sorxrob** [feathersjs/feathers#725]
First of all, sorry for not following the proper format and this is not actually an issue.

In the legacy version, I can get the user details with this code:

```
app.authenticate({
    type: 'local',
    'email': 'admin@feathersjs.com',
    'password': 'admin'
}).then(response => {
    // response is user data with token
})
```

And using the latest version, I would do something like this:

```
app.authenticate({
  strategy: 'local',
  email: 'admin@feathersjs.com',
  password: 'admin'
})
.then(response => {
  console.log('Authenticated!', response);
  return app.passport.verifyJWT(response.accessToken);
})
.then(payload => {
  console.log('JWT Payload', payload);
  return app.service('users').get(payload.userId);
})
.then(user => {
  app.set('user', user);
  console.log('User', app.get('user'));
})
```

Can I still make the code smaller? Or is there any other way than this? Thank you in advance!

**Comment by daffl** [comment]
You can also add the user information in an `after` `create` hook for the authentication service on the server.

**Comment by huggler** [comment]
const jwtToken = require('jsonwebtoken');  
app.service('authentication').hooks({
    before: {
      create: [
        authentication.hooks.authenticate(config.strategies)
      ],
      remove: [
        authentication.hooks.authenticate('jwt')
      ]
    },
    after: {
      create: [(context) => {
        const token = context.result.accessToken;
        console.log('token => ', token);
        const user =  jwtToken.decode(token);

const {app} = context;
app.get('usuario/'+ user._id).then(resp)....

context.result.user = resp
return context

      }]
    }
