### ISSUE TITLE
How to work with the relationship table from URL query?

### ISSUE THREAD

**Issue by vodniciarv** [feathersjs/feathers#726]
I will read [the quering documentation](https://docs.feathersjs.com/api/databases/querying.html).
For example:
`GET /category?$select[]=parent&$select[]=icon`
select columns `parent` and `icon` from `category`

Now if the `category` model have a relation with `translate` model, how to select columns from the `translate` model from URL? 

![screenshot_4](https://user-images.githubusercontent.com/14403446/32525157-b71ab5fe-c42b-11e7-97aa-caebf3545ee6.png)

**Comment by daffl** [comment]
Technically `$select[][translate.name]` should work but it this might also be a Sequelize or [feathers-sequelize](https://github.com/feathersjs-ecosystem/feathers-sequelize) specific question.

**Comment by vodniciarv** [comment]
Thanks for the reply.
```$select[][translate.name]``` not working, 
```
{
    "name": "GeneralError",
    "message": "Unknown column 'translate.name' in 'field list'",
    "code": 500,
    "className": "general-error",
    "data": {},
    "errors": {}
}
```
but I'm going to read the sequelize documentation
I think I'll do it

**Comment by vodniciarv** [comment]
Here https://github.com/feathersjs-ecosystem/feathers-sequelize/issues/176 is the answer.
Thank you @DesignByOnyx
