### ISSUE TITLE
generator with yarn

### ISSUE THREAD

**Issue by ZeroSoulEater** [feathersjs/feathers#730]
### Steps to reproduce
feathers generate app

select yarn

yarn oder npm start

Error: Cannot find module 'winston'

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:
v8.9.1
**Operating System**:
MacOS

**Comment by daffl** [comment]
Unfortunately we can't do much about those non-reproducible errors that seem to be Yarn related. Reinstalling (`rm -rf node_modules && yarn install`) the dependencies should fix it.

**Comment by ZeroSoulEater** [comment]
sadly it won't fix this. Don't know why. But everything works fine if I select npm  in the installation 👍

**Comment by daffl** [comment]
I can't reproduce the issue with Yarn 0.24.5

**Comment by ZeroSoulEater** [comment]
hmm I got yarn 0.27.5 sorry for not answering for 3 days

**Comment by daffl** [comment]
Also can't reproduce with Yarn 1.3.2 - updating to the latest might help or just using npm instead.
