### ISSUE TITLE
Question: How can i control what to populate in REST API

### ISSUE THREAD

**Issue by ranhsd** [feathersjs/feathers#735]
Hi, I created some project with feathers and i really like it!

I have a question regarding the $populate feature. I have 2 services Task and SubTask and have n:1 relationship between them so my sub task service holds a reference to the task identifier and store it in a **taskId** property. 

I wanted in one REST call to the Task service to populate the sub tasks for each task in the list as well. After reading the docs i choose to not use mongoose but do it via hooks because i think it's very important to be DB agnostic. So my code goes like this: 

```
const {populate} = require('feathers-hooks-common');

const taskSubTasksSchema = {
  include: {
    service: 'subtask',
    nameAs: 'subtasks',
    parentField: '_id',
    childField: 'taskId'
  }
};


module.exports = {
  after: {
    all: [
      populate({ schema: taskSubTasksSchema })   
    ],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  }, 
...
```

Everything works well so when i am executing the following request http://localhost:3030/task it retrieves me all tasks with sub tasks. 
The only question that i have is how i can control on it? I want to be able to do something like the following: http://localhost:3030/task?include='subtasks' in order to populate the sub tasks in addition to the tasks so basically when i will execute http://localhost:3030/task i will get **only** list of tasks without sub tasks but if i will execute http://localhost:3030/task?include='subtasks' i will get the sub tasks as well. 

I tried to do it by checking the hook but it's not really working for me so i wanted to know if there is some standard way to do it or maybe there are some helpers and if there isn't what are the best practices to deal with such requirement? 

Thanks in advanced!

**Comment by RobIsHere** [comment]
Don't know if thats the "official recommended way", but I would wrap populate in an iff common hook like this
```
iff(hook.params.query.include && hook.params.query.include === "subtasks", populate({ schema: taskSubTasksSchema }) )
```
see https://docs.feathersjs.com/api/hooks-common.html#iff

Hope that helps.

**Comment by ranhsd** [comment]
Hi @RobIsHere thanks but i requested something more generic. subtasks is only one example but i wanted to know if there is something more than just writing if commands inside the hook. 
let's assume that sometimes you will request some children and maybe you want also to populate children of children's and so on

**Comment by daffl** [comment]
I think @RobIsHere's suggestion sounds reasonable. If you need more flexibility of the populate you may want to [open an issue in the feathers-hooks-common repository](https://github.com/feathers-plus/feathers-hooks-common/issues/new) for further discussion.
