### ISSUE TITLE
Question: Return object model in other API response

### ISSUE THREAD

**Issue by nanomag** [feathersjs/feathers#737]
Hi, I'm a bit new on Feathers and Promises, and I'm having an issue. I'm trying to send a user object inside other object.

I have a service named `stuffs` and other `users`. I have the 'userId' in 'stuff' but I need to send some user data for each 'stuff' returned. I'm handling it in the 'after find' in 'stuffs'.

This is the 'after find' of 'stuffs':
```
find: [
      (hook) => {
        const data = hook.result.data.map(service =>
          const user = hook.app.service('users').get(userId)
            .then(user => user)
            .catch(() => {});
          service.user = {
            name: user.name,
          };
        );
        hook.result.data = data;
        return hook;
      }
],
```

I know that I need to solve the promise but I've not found the way to handle it.

**Can you help with an example please of how I can get each 'user' and add it to the each 'stuff' object before sending the JSON response?**

This is an example of what I want:
```
[
  {
    id: '',
    name: '',
    user: {
      name: '',
      lastName: ''
    }
  },
  { ... },
]
```

**Comment by daffl** [comment]
If you are using Node 8+ you can skip much of the pain of learning Promises and switch to [async/await](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function) right away (the only thing to know about here is [Promise.all](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all):

```js
find: [
  async (hook) => {
    // `async` functions always return a promise so using `map` with
    // `async` will return a list of promises
    const promises = hook.result.data.map(async (stuff) => {
      // Get the user from the current `stuff.userId`
      const user = await hook.app.service('users').get(stuff.userId);

      // Add the user to current `stuff`
      stuff.user = user;

      // Return the modified object
      return stuff;
    });

    // Wait for all promises to resolve in parallel
    hook.result.data = await Promise.all(promises);

    return hook;
  }
],
```

**Comment by nanomag** [comment]
It worked perfectly! Thank you so much!
