### ISSUE TITLE
[Question] Why my feathers client token changed after reload browser?

### ISSUE THREAD

**Issue by radiegtya** [feathersjs/feathers#745]
I am using standard feathers client authentication JWT with localStrategy. My question is Why my feathers client token changed after reload browser?

I am using this stack:
- React
- Feathers client with jwt
- local storage
- React Router to pass feathersClient to props

**Comment by subodhpareek18** [comment]
Are you trying to authenticate with the credentials every time? If so a new JWT will be created. What you could instead is at your root container authenticate without credentials in which case if you were storing the token in localstorage the client will use that. If it errors out you can redirect to a signin page where the user enters the credentials.

**Comment by radiegtya** [comment]
Thank for your help, it very helpful and just works.. But I have another question. 

```
feathersClient.authenticate().then(()=>{
  console.log(feathersClient.get('user'))
})
```

above code, user obj exists on after login, when changed to another router without login, it also still available. But when I did refresh the page, the user gone..

**Comment by subodhpareek18** [comment]
There are a few things to take care of. I have a setup that works on web (should work on a react native app too). You might not need to follow the exact setup but can take away the principles.

1) Give a storage to feathers client (LocalStorage or AsyncStorage) to store the token
This enables further requests to use that token, which I guess you are already doing

2) Persist a part of your app state into the device and rehydrate it later
This enables you to first check for any stored token when page loads and use it for authentication, if it can't find anything it will error out, letting you redirect to the signin page

The way I achieve the second is as follows, I use `redux` for state management, with feathers I use `feathers-redux` and `feathers-reduxify-authentication` plugins to make all my api calls with the feathers client via redux, even the authentication one. 

So far so good.

Lastly I use `redux-persist` to save the auth related part of my store into the device and every time my root component mounts I try to rehydrate the store first, then perform an authentication the redux way so the call can use the auth part of the persisted store, then if that fails I go signin page.

It might be a bit too much to set up if you're not familiar with redux, so you could try and achieve the same in some other way.

```js
import { persistStore } from 'redux-persist';

export default class Root extends Component {
  state = { rehydrated: false };
  async componentWillMount() {
    persistStore(store, { whitelist: ['auth'] }, () => {
      this.setState({ rehydrated: true });
    });
    try {
      await services.auth.authenticate(); // <-- a redux action dispatcher
    } catch (e) {
      console.log(`[${e.name}] ${e.message}`);
    }
  }
  render() {
    if (!this.state.rehydrated) {
      return <LoadingComponent />;
    }
    return (
      <Provider store={store}>
        ...
      </Provider>
    );
  }
}
```

**Comment by radiegtya** [comment]
nice explanation. Btw I am using feathers-redux too. But I never found this part

```
services.auth.authenticate();

//or equals to

store.dispatch(services.auth.authenticate());
```

can you explain, what is that? where "services.auth" come from? and are you using autobind, so you don't call dispatch?

**Comment by subodhpareek18** [comment]
If you're using feathers-redux then you shouldn't have any issue understanding this.

```js
/** api/client.js */

import feathers from 'feathers-client';
import io from 'socket.io-client';
const url = process.env.REACT_APP_API_URL;
const socket = io(url);

const client = feathers()
  .configure(feathers.socketio(socket, { timeout: 30000 }))
  .configure(feathers.hooks())
  .configure(
    feathers.authentication({
      storage: window.localStorage
    })
  );

export default client;
```
```js
/** store/reducers.js */

import { combineReducers } from 'redux';
import reduxifyServices from 'feathers-redux';
import reduxifyAuth from 'feathers-reduxify-authentication';
import R from 'ramda';
import client from 'api/client';

const serviceMap = {
  'db/tasks': 'tasks',
  users: 'users',
};

const auth = reduxifyAuth(client, {
  token: 'accessToken'
});

export const rawServices = {
  ...reduxifyServices(client, serviceMap),
  auth
};

const feathersServices = R.map(x => x.reducer, rawServices);

export default combineReducers({
  ...feathersServices
});
```
```js
/** store/index.js */

import { applyMiddleware, createStore, compose } from 'redux';
import { createLogger } from 'redux-logger';
import thunk from 'redux-thunk';
import promise from 'redux-promise-middleware';
import { autoRehydrate } from 'redux-persist';
import { bindWithDispatch } from 'feathers-redux';

import rootReducer, { rawServices } from 'store/reducers';

const middleware = applyMiddleware(
  promise(),
  thunk,
  createLogger({ collapsed: true })
);

const store = createStore(
  rootReducer,
  compose(
    middleware,
    autoRehydrate(),
    window.devToolsExtension ? window.devToolsExtension() : f => f
  )
);

export const services = bindWithDispatch(store.dispatch, rawServices);

export default store;
```
```js
/** Root.js */
import React, { Component } from 'react';
import { BrowserRouter as Router, Route, Switch } from 'react-router-dom';
import { Provider } from 'react-redux';
import { persistStore } from 'redux-persist';

import store, { services } from 'store';
import { App, Signin, FourOFour } from 'containers';
import { Preloader } from 'components';

class Root extends Component {
  state = { rehydrated: false };
  async componentWillMount() {
    persistStore(store, { whitelist: ['auth'] }, () => {
      this.setState({ rehydrated: true });
    });
    try {
      await services.auth.authenticate();
    } catch (e) {
      console.log(`[${e.name}] ${e.message}`);
    }
  }
  render() {
    if (!this.state.rehydrated) {
      return <Preloader />;
    }
    return (
      <Provider store={store}>
        <Router>
          <Switch>
            <Route exact path="/" component={Signin} />  // this container redirects to App if authed
            <Route path="/app" component={App} /> // this container redirects to Signin if not authed
            <Route component={FourOFour} />
          </Switch>
        </Router>
      </Provider>
    );
  }
}
export default Root;
```

**Comment by radiegtya** [comment]
I see, so that is from "feathers-reduxify-authentication". Thank u for very clear explanation with example. I'll close this. :)
