### ISSUE TITLE
TypeError: service.filter is not a function

### ISSUE THREAD

**Issue by kszmigiel** [feathersjs/feathers#746]
I'm trying to add filters to my service, basically using generated code:
```
const createService = require('feathers-mongodb');
const hooks = require('./test.hooks');
const filters = require('./test.filters');

module.exports = function () {
  const app = this;
  const paginate = app.get('paginate');
  const mongoClient = app.get('mongoClient');
  const options = { paginate };

  // Initialize our service with any options it requires
  app.use('/test', createService(options));

  // Get our initialized service so that we can register hooks and filters
  const service = app.service('test');

  mongoClient.then(db => {
    service.Model = db.collection('test');
  });

  service.hooks(hooks);

  //if (service.filter) {
    service.filter(filters);
  //}
};
```

But when I try to run app, I get this error:
```
/home/kacper/filtrykurwaniedzialaja/src/services/test/test.service.js:25
    service.filter(filters);
            ^

TypeError: service.filter is not a function
```
Any ideas why is it so? Code from the docs looks quite the same :/

**Comment by daffl** [comment]
This can have two reasons:

1) You only chose the REST provider and no real-time provider when creating the application. In that case there is no external events and no reason to filter.
2) You ran `feathers upgrade` or are using the new `@feathersjs/cli` in which case there is no more `.filter`. That functionality has been replaced by [channels](https://buzzard.docs.feathersjs.com/api/channels.html).
