### ISSUE TITLE
Call a feathers service from Middleware

### ISSUE THREAD

**Issue by HarshOB** [feathersjs/feathers#747]
Feather service call form middleware and get a response

```
  const service = app.service('flows-dir-listing');
  console.log("service",service)
  let response = service.get()
  console.log("response........", response)
```
Got error Cannot read property 'get' of undefined and got service undefined.

**Comment by daffl** [comment]
Most likely a service named `flows-dir-listing` does not exist (or exist yet at the time you call it).

**Comment by HarshOB** [comment]
It exist and if I call using AXIOS it will call and I got response as well.

**Comment by daffl** [comment]
You didn't provide enough information to look at what might be going on there. `.get` always needs to be passed an `id`. How is the application set up? Are you doing this on the client or the server?

**Comment by HarshOB** [comment]
This is my axios call. What should I do to call direct feathers service without axios?

```
async function getTotal(params) {
  let op = await(axios.get(baseUrl + '/flows-dir-listing?website=harshp'))
  console.log('resule', op.data.children.length)      
  return op.data.children.length
}
let totalMessage = await getTotal() 
console.log("totalMsg",totalMessage)
```

**Comment by daffl** [comment]
It's documented [here](https://docs.feathersjs.com/api/rest.html#restbaseurl).
