### ISSUE TITLE
feathers generate authentication & mariadb

### ISSUE THREAD

**Issue by blondie63** [feathersjs/feathers#748]
Following docs https://docs.feathersjs.com/guides/step-by-step/generators/gen-authentication.html i've found an issue on latest generator:
i choosed provider : username + password (local)
entity users
service Sequelize
database MariaDB
This is wrong because now Sequelize 4 has removed this dialect (http://docs.sequelizejs.com/manual/tutorial/upgrade-to-v4.html#breaking-changes)
Anyway i've changed to mysql but running npm start i've this error:
url.js:103
    throw new TypeError('Parameter "url" must be a string, not ' + typeof url);

Some help?

**Comment by edwardsmarkf** [comment]
this worked for me:

https://github.com/feathersjs/docs/compare/master...edwardsmarkf:patch-3

function databaseConnect() {
  const sequelize = new Sequelize( 'Users', 'Mark', 'HV7LmKG2YRvwxt' ,
                         { host: '35.199.152.176', port: 3306, dialect : 'mariadb' }
  );

**Comment by blondie63** [comment]
I solved changing to mysql dialect and installing mysql2 (npm install --save mysql2)
Docs need to be update :)
