### ISSUE TITLE
NotAuthenticated error

### ISSUE THREAD

**Issue by Modifa** [feathersjs/feathers#749]
```
error:  NotAuthenticated: Invalid login     at new NotAuthenticated (/mnt/c/Users/Laptop 1/feathers-app/feathers-chat /node_modules/feathers-errors/lib/index.js:100:17)     at /mnt/c/Users/Laptop 1/feathers-app/feathers-chat/node_modules/feathers -authentication/lib/hooks/authenticate.js:102:31     at <anonymous>
```

### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc. This makes it much easier for us to debug and issues that have a reproducable example will get higher priority.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by Modifa** [comment]
i Keep getting this error, its refusing to read my authentication method. help anyone?

**Comment by daffl** [comment]
Not with that little information. What does your setup look like? The authentication call? Is that the full stack trace?
