### ISSUE TITLE
Automatically generate documentation

### ISSUE THREAD

**Issue by lodi-g** [feathersjs/feathers#750]
Hi

## Problem

When working with front-end developers who don't know feathersjs (or are not interested in it) ; it's quite redundant and really uninteresting to create a documentation for your API considering it's mostly everytime the same thing.

## Proposal

It'd be quite nice to have a loopback-style documentation generator referencing services ; their routes and hooks (maybe with a jsdoc style comment explaining what the hook is doing?) and associated models.
We can safely imagine a `feathers generate docs` which would parse the whole code and generate .html file.

Thanks

**Comment by daffl** [comment]
Thank you. This is what [feathers-swagger](https://github.com/feathersjs-ecosystem/feathers-swagger/) is for. There is definitely room for improvement and there is a discussion to parse JSDoc comments in https://github.com/feathersjs-ecosystem/feathers-swagger/issues/81 so I think we can continue further discussion over there.
