### ISSUE TITLE
removed event behavior when calling .remove(null)

### ISSUE THREAD

**Issue by realshaft** [feathersjs/feathers#753]
### Steps to reproduce
- Listen to removed event
- calling await context.app.service('servicename').remove(null);
- check type and length of the emmitted object

-> If you have i.e. 5 entries which all shall being deleted with the mentioned command (remove(null)), on the client side <feathersService>.on('removed', t => this.onDeleted(t)); is called 5 times as expected. But on every call you get an array of all deleted entries instead of one object

### Expected behavior
onDelete should be called on every removed entry with the current removed entry. And not as an array.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
@feathersjs/feathers   3.0.1 

**NodeJS version**:
8.9.1

**Operating System**:
macOS

**Browser Version**:
chrome 62

**Angular Native Version**:
5.0.4

**Module Loader**:
webpack

**Comment by daffl** [comment]
Thank you, I knew I missed this but totally forgot about it. Fixed in `@feathersjs/socket-commons` version 3.1.3.

**Comment by daffl** [comment]
Ah, you're right. Published another fix that I think should actually do it (hopefully).

**Comment by realshaft** [comment]
ust tested with 3.1.5. Looks good. I do only get one call per object.

Thanks David!

**Comment by daffl** [comment]
Perfect, thanks for double checking.
