### ISSUE TITLE
How to join a channel from a hook

### ISSUE THREAD

**Issue by jakobrosenberg** [feathersjs/feathers#754]
I read somewhere that the ``params`` property is the same as ``connection``, but for some reason I'm unable to join a channel from a hook using the ``params`` prop.

```javascript    
find: [
  (context) => {
    const connection = context.params
    context.app.channel('mychannel').join(connection)
  }
]
```

**Comment by daffl** [comment]
Channels are not persistent (and local to the Feathers instance) and should really just represent persisted data (like the user/room assigned) so I'd say the best place to update channels are event listeners. I posted a code sample that I think is related in https://github.com/feathersjs/docs/issues/950#issuecomment-352301687, hopefully it helps.

**Comment by daffl** [comment]
For future reference, the `connection` is now available as [params.connection](https://docs.feathersjs.com/api/socketio.html#paramsconnection) for any call made with real-time provider (Socket.io, Primus).
