### ISSUE TITLE
fs dependency of socket.io not found

### ISSUE THREAD

**Issue by musicformellons** [feathersjs/feathers#756]
I ran the cli upgrade script on my app (client). Then I get this error message when serving my app:

```
[HPM] Proxy created: /api  ->  http://localhost:3030
 ERROR  Failed to compile with 1 errors17:34:07

This dependency was not found:

* fs in ./node_modules/socket.io/lib/index.js

To install it, you can run: npm install --save fs
```

When I install fs as instructed error remains. When I go into the node_modules/socket.io/   folder and install fs there, error also remains.

**Comment by daffl** [comment]
What's your configuration? Did you try reinstalling (`rm-rf package-lock.json node_modules`)?

**Comment by daffl** [comment]
It looks like it is trying to `require('@feathersjs/socketio')` instead of `require('@feathersjs/socketio-client')`. Might be something wrong with the mappings. Can you find the file and how the import looked before/after?

**Comment by musicformellons** [comment]
Yeah, I did reinstall.

You mean this file?: `./node_modules/socket.io/lib/index.js`

**Comment by daffl** [comment]
Actually, I meant my second comment:

> It looks like it is trying to require('@feathersjs/socketio') instead of require('@feathersjs/socketio-client').

**Comment by daffl** [comment]
Can you find `require('@feathersjs/socketio')` or the import to `@feathersjs/socketio`? It should be `@feathersjs/socketio-client` instead.

**Comment by musicformellons** [comment]
Yeah, that solved it! Thanks!
