### ISSUE TITLE
Using find() with &in returns zero records

### ISSUE THREAD

**Issue by ComputerCarl** [feathersjs/feathers#757]
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc. This makes it much easier for us to debug and issues that have a reproducable example will get higher priority.

### Expected behavior
Expected to return two items from the databse

### Actual behavior
Returned no records

### System configuration
create-react-app and feathers-cli g app

Using find and $in on a MongoDB service, the results I receive are;
````js
{
  "total": 0,
  "limit": 20,
  "skip": 0,
  "data": []
}
````

The two records below are valid `_id`s of record in the `cards` service;
`http://localhost:3030/cards?_id[$in]=5a344774f254c60f9c083aab&_id[$in]=5a344791f254c60f9c083ab1`

Using the following URL, I can see those records;
`http://localhost:3030/cards`

i receive the same results via socket;
````js
        cardsService.find({
          query: {
            _id: {
              $in: ['5a344774f254c60f9c083aab', '5a344791f254c60f9c083ab1']
            }
          }
        })
        .then(result => {
            console.log("cards: ", result);
          })
          .catch(err => console.warn(err));
````

**Comment by daffl** [comment]
If you are using plain MongoDB you always have to convert your data to the correct type, in this case a [MongoDB ObjectId](https://mongodb.github.io/node-mongodb-native/api-bson-generated/objectid.html), e.g. in a `before` `find` hook:

```js
const { ObjectID } = require('mongodb');

module.exports = function() {
  return async context => {
    const { query = {} } = context.params;

    if(query._id) {
      if(typeof query._id === 'string') {
        query._id = new ObjectID(query._id);
      } else if(query._id.$in) {
        query._id.$in = query._id.$in.map(id => new ObjectID(id));
      }
    }
  }
}
```

**Comment by ComputerCarl** [comment]
Thanks again for your expertise!

The ObjectID for the _id field seems overly complicated. I switched my services to Mongoose to avoid having to deal with that. I should have checked the Mongo console before posting this issue in Feathers issues.

**Comment by daffl** [comment]
Yep, Mongoose will do this for you automatically. The MongoDB adapter could also do this for ids but then we'd have the same problem again for other properties - which we'll never know what to do with since there is no schema.
