### ISSUE TITLE
Client Side Timeout

### ISSUE THREAD

**Issue by Ryan8765** [feathersjs/feathers#761]
Either I am missing something very basic - or there seems to be a bug associated with the client build.  Details to replicate:

1. Create a new Feathers application
2. Create a messages service
3. Set up the index.js page to match the [suggested "Load from CDN" section](https://docs.feathersjs.com/api/client.html#load-from-cdn-with-script).
4. Run the server and try adding a message in Chrome/Edge (haven't tested other browsers).  Timeout should be seen.  With the following error message:

```
client.js:66 Uncaught (in promise) Error: Timeout of 5000ms exceeded calling create on messages
    at client.js:66
```

See[ linked repository with project setup](https://github.com/Ryan8765/feathersTimeout) complete to replicate this issue.  I am running this locally (3030) on two separate windows 10 computers.

**Comment by daffl** [comment]
Your server side application has been created with an old (v2) version of the CLI but you are loading `@feathersjs/feathers@^3.0.0` in the browser which uses a Socket.io message format that is not supported by a v2 server.

`feathers --version` should show `3.3.0` or later. You can either follow the [migration guide](https://docs.feathersjs.com/migrating.html) to upgrade or install the latest `@feathersjs/cli` and regenerate the application.

**Comment by Ryan8765** [comment]
Worked perfect, thanks!
