### ISSUE TITLE
Problem with used port in tests

### ISSUE THREAD

**Issue by kszmigiel** [feathersjs/feathers#763]
I'm testing a few hooks, and in each one I need to run my app in order to authenticate user:
```
await client.configure( rest( 'http://localhost:3030' ).superagent(superagent) )
    .configure(auth({ storage: localStorage }))
    .authenticate({
      strategy: 'local',
      email: 'test@email.com',
      password: 'www'
      })
      .then(response => {
        token =  response.accessToken;
      });
```
The problem is what when I run `npm test`, I usually get at least one error that looks like this:
`Uncaught Error: listen EADDRINUSE :::3030`
I've googled it, but found no correct solution. Any ideas? TIA

**Comment by daffl** [comment]
You have to make sure that you either only start the server once or wait for it to shut down. The [close method](https://nodejs.org/api/http.html#http_server_close_callback) should allow to do that:

```js
describe('some test', () => {
  let server;

  beforeEach(done => {
    server = app.listen(3030);
    server.once('listening', () => done());
  });

  afterEach(done => server.close(done));
});

```
