### ISSUE TITLE
DataType for ID column

### ISSUE THREAD

**Issue by VanMen** [feathersjs/feathers#764]
I'm planning to make an App using feathersjs.
My App should capable to store more than 10 millions users.
I'm planning to use sequelize and mysql as my database.
The problem is, when I create a new service by default feathers will use DataType int for ID column.
FYI, DataType int max value is around 4 millions.
So, I cannot use DataType int in my users service, if I'm planning to store 10 millions users.

Is it possible to change the default DataType from int to bigint for ID column?

**Comment by daffl** [comment]
The maximum value for integers in SQL is `2,147,483,647` and you can also define a field of a different data type and set the  `primaryKey` value as [documented in the Sequelize documentation](http://docs.sequelizejs.com/manual/tutorial/models-definition.html).
