### ISSUE TITLE
Testing : stub services' hooks impossible

### ISSUE THREAD

**Issue by kamiky** [feathersjs/feathers#766]
Hello,

i was writing some tests for my feathers application and noticed you cannot modify a service hooks when it has been registered.

I have an authentication hook used within a service

```
module.exports = {
  before: {
    all: [],
    find: [
      sessionHooks.authenticate('jwt')
   ], ...
```

i tried to stub (sinonjs) the authenticate method, which would allow me to call my service without generating a user token in my tests, but there's no way to achieve this after the service has been registered.

PS : I managed to make it work by stubing this method at the beginning of my tests, before the app is launched, but obviously this is not a solution

```
sinon.stub(sessionHooks, 'authenticate').callsFake((strategy) => {
    return (hook) => {
  console.log('stubAuthenticateHook', strategy)
    return Promise.resolve()
  }
})
const app = require('../src/app')
```

I think i saw in feathers source code that you make a copy of the initial hook object which would explain why it's not working.

I even tried to register a new hook object in my test, but didn't work out

```
it('registered the service', (done) => {
    const service = app.service('messages')
    let hooks = require(__base + 'src/services/messages/messages.hooks')
    hooks.before.find = [ session.authenticate('jwt') ]
    service.hooks(hooks)

    session.authenticate('jwt')({}) /* this is calling my stub method */
    service.find({}) /* this result in an error because the stub method isnt called and i dont provide an auth token */
    .then(result => {
      console.log('service find')
      done()
    }).catch(e => {
      console.error('ERROR', e.code)
      done()
    })
})
```

Is there any way to achieve this ?
Testing a service without being able to stub or mock any hook gonna be an hell of a job

Btw i'm using feathers 2.1.1.

**Comment by daffl** [comment]
The normal `authenticate` hook will be bypassed if called internally (meaning `params.provider` being `undefined`). I wouldn't stub it out if I actually wanted to test it but instead make sure that a valid token is generated and the user is populated (from a dummy user service) on authenticated requests.

To test specific hooks I recommend to wire up a testable Feathers application and making sure the output is as expected. An example can be found in [feathers-chat](https://github.com/feathersjs/feathers-chat/blob/master/test/hooks/process-message.test.js).
