### ISSUE TITLE
I migrated my product to V3 but socketio is not enable

### ISSUE THREAD

**Issue by lagmanzaza** [feathersjs/feathers#770]
after I migrated my product, I have not been used socket IO.
my feathersJS configuration
https://gist.github.com/lagmanzaza/51982bccd3abf3be2c67bfe9f2fe960f

my channel
https://gist.github.com/lagmanzaza/e8aebb4c7815f11ef9a3d56821a69d2f

**Comment by daffl** [comment]
I'm pretty sure https://gist.github.com/lagmanzaza/e8aebb4c7815f11ef9a3d56821a69d2f#file-channel-L33 is trying to access an undefined variable and is throwing an error. I think you want

```js
return [ app.channel('authenticated'), app.channel('anonymous') ];
```

I might have to double check if this error is just getting swallowed of does show up somewhere.

**Comment by lagmanzaza** [comment]
https://gist.github.com/lagmanzaza/e8aebb4c7815f11ef9a3d56821a69d2f#file-channel-L4

I check this when app.channel is not Function then when I start server that shows 
"please enable web socket" 
I don't know how to enable socket

**Comment by daffl** [comment]
The [@feathersjs/socketio](https://docs.feathersjs.com/api/socketio.html) should happen __before__ calling `app.configure(channels)`.

**Comment by lagmanzaza** [comment]
Thank you. now it's work
