### ISSUE TITLE
Why does the server say timeout after 10 minutes of inactive application?

### ISSUE THREAD

**Issue by MackayBravo** [feathersjs/feathers#771]
Why do I make a request to the server 10 minutes after the inactive application, does the response come in timeout? How to solve this problem?

**Comment by daffl** [comment]
Do you have more information? What versions? What operating system? How are you running the server? What request is causing the timeout?

**Comment by MackayBravo** [comment]
@daffl let's say the phone just lies on the table with the mobile application turned on. After 10 minutes, I take the phone and make a request to the server to retrieve the news, but the server does not give an answer, it feels like the client is dropping connections. featherjs on client gave timeout server. But I'm making second requests to the server, and everything is ok.
The server has ubuntu installed
feathersjs: 2.1.7
feathersjs client: 2.3.0

**Comment by daffl** [comment]
I just tried with the Feathers chat and am not seeing the issue and have not encountered it anywhere else yet so I think it might have something to do with your setup.

Are you running this on Heroku or some other hosting instance that potentially spins down on inactivity?

**Comment by daffl** [comment]
Going to close but reopen if this issue continues and there is more information or a reproducible example.
