### ISSUE TITLE
Build fails with create-react-app

### ISSUE THREAD

**Issue by Jank1310** [feathersjs/feathers#774]
### Steps to reproduce

```
# install and init create-react-app
npm install -g create-react-app
create-react-app my-app
# add feathers
yarn add @feathersjs/feathers
# add import statement to src/App.js
import feathers from '@feathersjs/feathers';
# try to build with
yarn build
```

### Expected behavior
Correctly execute build command.

### Actual behavior
Fails at minifying with:
```
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/@feathersjs/commons/lib/utils.js:8 

Read more here: http://bit.ly/2tRViJ9
````

### Question
Is there any way to use feathers (buzzard) with create-react-app?

**Comment by daffl** [comment]
Yes. It is documented at https://docs.feathersjs.com/api/client.html#create-react-app

**Comment by compwright** [comment]
When you import, I've found that you have to:

```javascript
import feathers from '@feathersjs/client/dist/feathers'
```

rather than:

```javascript
import feathers from '@feathersjs/client'
```

**Comment by daffl** [comment]
That seems odd because the `package.json` main entry is pointing to the [index file](https://github.com/feathersjs/client/blob/master/index.js) which is loading exactly that file.
