### ISSUE TITLE
Conditionnally configure JWT expireIn?

### ISSUE THREAD

**Issue by D219** [feathersjs/feathers#776]
I have a use case where some users will need a JWT with a longer timeout. I know that in a standard app, I can edit src/authentication.js to add a `expireIn` flag, but this result in all JWT having the extended validation time.

Is there a way, for example in a hook, to change the expireIn option for just that request? By manually searching inside it, the only thing I found is `hook.app.authentication.jwt.expireIn`, which doesn't look like what I want.

**Comment by daffl** [comment]
You should be able to set JWT options dynamically in `params.jwt` in a `before` `create`hook:

```js
app.service('authentication').hooks({
  before: {
    create(context) {
      context.params.jwt.expiresIn = '2d';
    }
  }
});
```

**Comment by D219** [comment]
It did work, thanks a lot :)
