### ISSUE TITLE
Not work with nodejs v8.9.4

### ISSUE THREAD

**Issue by trixxxden** [feathersjs/feathers#777]
What i do:

- Install `feathers-cli`: `sudo npm i feathers-cli`
- Generate new app: `feathers generate app`, with rest and socket.io transports
- Generate authentication: `feathers generate authentication`

Now, i have service `users`. Send request `GET localhost:3030/users`, take response `ERROR: not authenticated`, it's right.

I delete `authenticate('jwt')` on users.before hooks. Send again request `GET localhost:3030/users`. I expect take empty array, right? I take nothing, with unlimited loading.

Same problem, when i send socket requests. I'l not take any responses.

**Comment by daffl** [comment]
Please try installing the latest `@feathersjs/cli` (not the old `feathers-cli`) as documented on the [homepage](https://feathersjs.com/) and the [guides](https://docs.feathersjs.com/guides/readme.html) and see if the issue is still reproducible.

**Comment by trixxxden** [comment]
@daffl , i tried. Nothing changed.

**Comment by daffl** [comment]
I can't reproduce the problem. If I remove `authenticate('jwt')` from `users.hooks.js` to make it look like this:

```js
const { authenticate } = require('@feathersjs/authentication').hooks;

const {
  hashPassword, protect
} = require('@feathersjs/authentication-local').hooks;

module.exports = {
  before: {
    all: [],
    find: [],
    get: [],
    create: [ hashPassword() ],
    update: [ hashPassword() ],
    patch: [ hashPassword() ],
    remove: [ ]
  },

  after: {
    all: [ 
      // Make sure the password field is never sent to the client
      // Always must be the last hook
      protect('password')
    ],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  },

  error: {
    all: [],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  }
};
```

Run `npm start` and go to [http://localhost:3030/users](http://localhost:3030/users) I see an empty list of users.

**Comment by trixxxden** [comment]
@daffl i am so sorry. The problem was in internal nodejs package in [Solus](https://solus-project.com/)

**Comment by daffl** [comment]
👍  Glad you figured it out.
