### ISSUE TITLE
pass Array of Array to $sort triggers MongoError: `bad sort specification`

### ISSUE THREAD

**Issue by frantic1048** [feathersjs/feathers#778]
I'm implementing multi-field sorting recently. And I see [MongoDB's document](https://mongodb.github.io/node-mongodb-native/api-generated/cursor.html#sort), the `.sort()` method accepts an Array like `[['gender', 1], ['age', -1]]` to perform a multi-field sorting.

However, the feathers document does not mention the multi-field sorting usage in the [doc](https://github.com/feathersjs/docs/blob/master/api/databases/querying.md#sort).

I tried to make a query like:

```js
service.find({
  $sort: {
    gender: 1,
    age: -1
  }
})
```

It works as I want: sorting the result by gender firstly, then by age.

But that is a little weird to pass order dependent keys with an object. 

Because I want to compose the `$sort` property dynamically according to URL query parameters. Then I can't ensure the final key order is as  I want. The spec says the [order of enumerating the properties is not specified](https://tc39.github.io/ecma262/#sec-enumerate-object-properties)

I'm concerning the sort result I get is not stable.

According to [MongoDB's doc](https://github.com/feathersjs/docs/blob/master/api/databases/querying.md#sort), I tried to make $sort be an Array of Array as doc describes but no luck. I got `MongoError: bad sort specification`

Then I dig into feathers codebase, I found interesting lines in `feathers-query-filters` package, I found the key function `convertSort()` in both [feathersjs/commons/lib/filter-query.js](https://github.com/feathersjs/commons/blob/6d619c24b307da25ff28448fa5d44b0540224c42/lib/filter-query.js#L26) and [feathersjs-ecosystem/feathers-query-filters/src/index.js](https://github.com/feathersjs-ecosystem/feathers-query-filters/blob/0d5e491ac54a9c058e34abfd244accdd8f98ca31/src/index.js).

I've no idea which is currently active repo. `feathersjs/commons` seems newer by last commit date. `feathersjs-ecosystem/feathers-query-filters` seems more related by name.

Here is that function:

```js
// Makes sure that $sort order is always converted to an actual number
function convertSort (sort) {
  if (typeof sort !== 'object') {
    return sort;
  }

  const result = {};

  Object.keys(sort).forEach(key => {
    result[key] = typeof sort[key] === 'object'
      ? sort[key] : parseInt(sort[key], 10);
  });

  return result;
}
```

It seems going to iterate the sort argument when it is an Object. But not other stuff(used Object.keys() after the condition statement)

And the fact is `typeof [] === 'object'` and `typeof {} === 'object'`, the function could not distinguish an Array and an Object...

I modified the `typeof sort !== 'object'` into `Object.prototype.toString.call(sort) !== '[object Object]'`, and made query like `{ $sort: [['gender', 1], ['age', -1]]}`. Every thing works well.

I'm wondering if my modification is the purpose of the function.

BTW, why the function does a key iteration to copy object's keys and return a object with same keys?

**Comment by daffl** [comment]
Yep, it should definitely let you pass an array through. Fixed via https://github.com/feathersjs/commons/pull/66

One thing to note is that this is not part of the [Feathers query syntax](https://docs.feathersjs.com/api/databases/querying.html) and will only work for MongoDB.
