### ISSUE TITLE
Async load inside service.js

### ISSUE THREAD

**Issue by gpietro** [feathersjs/feathers#781]
I'm using [feathers-swagger](https://github.com/feathersjs-ecosystem/feathers-swagger) with a [library](https://github.com/whitlockjc/json-refs) for loading refs from schema.
This library works asynchronously.
What would be the best approach for making an async call to init the application on start?

#### example.service.js

```
const path = require('path');
const createService = require('feathers-nedb');
const createModel = require('../../models/example.model');
const hooks = require('./example.hooks');
const schemaPath = path.join(__dirname, '../schema')
const schema = require(path.join(schemaPath,'Example.json'));
const JsonRefs = require('json-refs');

const asyncLoad = async () => {
  const fullSchema = await JsonRefs.resolveRefsAt(
    path.join(schemaPath,'Example.json'), 
    {location: schemaPath}
  ).then(res => Promise.resolve(res.resolved))

  Promise.resolve(fullSchema)
}

module.exports = function (app) {
  const Model = createModel(app);
  const paginate = app.get('paginate');
  
  const options = {
    name: 'example',
    Model,
    paginate
  };

  const example = createService(options)

  // add swagger spec of the service
  example.docs = asyncLoad()

  app.use('/example', example)

  const service = app.service('example');

  service.hooks(hooks);
};

```

**Comment by daffl** [comment]
I think this is very similar to #509. You can find an example for a plugin that can do this in https://github.com/feathersjs/feathers/issues/509#issuecomment-342871157.

The most important thing is to only register the middleware (`notFound` and error handler) once those promises have been resolved.

**Comment by gpietro** [comment]
@daffl  You override the configure method right? I don't understand how should I use this plugin and there seems to be a syntax error ("return this" inside Promise.resolve).

**Comment by daffl** [comment]
Ha, good point, that indeed won't work. I added a better complete example in https://github.com/feathersjs/feathers/issues/509#issuecomment-358039365

**Comment by gpietro** [comment]
Thanks for the example but with an async configure, the services aren't reachable anymore (the resource rest, 404 page). Why do you copy the reference to the old configure? Do we still need it? and app.ready when must be used inside the application?
I did try two implementation inside app.js and inside service/index.js.

https://gist.github.com/gpietro/1559bc5181a66114e1a96f1494e491f1

**Comment by daffl** [comment]
Hm, I think it's because https://gist.github.com/gpietro/1559bc5181a66114e1a96f1494e491f1#file-app-js-L46-L48 has to be wrapped in a configure as well:

```js
app.configure(() => {
  // Configure a middleware for 404s and the error handler
  app.use(express.notFound());
  app.use(express.errorHandler({ logger }));
});
```

**Comment by gpietro** [comment]
I didn't manage it neither that way. Here is a solution I came up with:
https://gist.github.com/gpietro/e08eb515dfbe5040f72998c8b0fc0f18
