### ISSUE TITLE
Parameters to Hook registration

### ISSUE THREAD

**Issue by ricardopolo** [feathersjs/feathers#782]
I have hooks where I pass sequelize params, like these

`hook.js`
````js
module.exports = function (options = {}) { // eslint-disable-line no-unused-vars
  return context => {
    if (!context.params.sequelize) context.params.sequelize = {};
    context.params.sequelize.raw = false;
    context.params.sequelize.include = [ context.app.services.users.Model ]
    return context;
  };
};
````

`service.hooks.js`
````js
const hook = require('../../hooks/hook');
module.exports = {
  before: {
    all: [],
    find: [],
    get: [hook()],
    create: [],
    update: [],
    patch: [],
    remove: []
  },
````

Understanding that sequelize services are only REST I think I will need lots of hooks like these, for showing related data in the API.

So, how can I pass the parameter `include` in the file of hooks registration. How can I acess the models from this file to pass to hooks?

I this a best practice or a flaw of desing?

**Comment by daffl** [comment]
That's what the `options` are for. Pass the string service names for references and use [app.service](https://docs.feathersjs.com/api/application.html#servicepath) to get the `Model`:

```js
module.exports = function (options = { include: [] }) {
  return context => {
    if (!context.params.sequelize) {
      context.params.sequelize = {};
    }

    const raw = false;
    const include = options.include.map(name => {
      const service = context.app.service('name');
      
      return service.Model
    });

    Object.assign(context.params.sequelize, { include, raw });

    return context;
  };
};
```


```
const hook = require('../../hooks/hook');
module.exports = {
  before: {
    all: [],
    find: [],
    get: [ hook('users', 'accounts') ],
    create: [],
    update: [],
    patch: [],
    remove: []
  },
```

**Comment by ricardopolo** [comment]
@daffl Works!

With this minor change (`name` without quotes)
```js
module.exports = function (options = { include: [] }) {
  return context => {
    if (!context.params.sequelize) {
      context.params.sequelize = {};
    }

    const raw = false;
    const include = options.include.map(name => {
      const service = context.app.service(name);
      return service.Model
    });

    Object.assign(context.params.sequelize, { include, raw });

    return context;
  };
};
````

Why `Object.assign(context.params.sequelize, { include, raw }); works? in the signature of params.sequelize `include` is the first param an `raw` the second?

On last question: how would you pass a full include object, not retrieving the service but also additional params like `where`?

**Comment by daffl** [comment]
I would get them dynamically during runtime since then you can be sure that everything is initialized. 

Another option would be to return a [configure function](https://docs.feathersjs.com/guides/basics/generator.html#configure-functions) which takes the `app` object and you do `service.hooks(myhooks(app))`.

**Comment by ricardopolo** [comment]
thanks @daffl
