### ISSUE TITLE
Live Query "like" concept in FeathersJS

### ISSUE THREAD

**Issue by ranhsd** [feathersjs/feathers#783]
Hi, 
I have a [parse-server](https://github.com/parse-community/parse-server) app and I am trying to convert it to FeathersJS. I like the idea of microservices in FeathersJS because I need to use multiple databases in my project and currently in parse-server I can use only one DB (either MongoDB or Postgresql). I managed to tackle the following use cases with FeathersJS: 

- REST calls

- Authentication (Local and Social) + Reset password 

- File storage 

- Push notifications (I'm currently working on it)

- Server side hooks (in parse-server I use cloud code hooks and here I use the built-in hooks mechanism) 

The only thing that I didn't managed to figure is the **Live Query** concept and how I can implement it in Feathers. In live query the client can subscribe to **Live Events** from the server. In Feathers it can be done either via Socket.IO or Primus the only difference is that in Live Query you can subscribe to **Specific Query** so you can build query + conditions and parse-server will emit the events only when those conditions are fulfilled. 

In Feathers you can subscribe to events like: **created, updated, deleted** and so on but you cannot subscribe to **specific query** for example: I want to subscribe to the messages service and receive the events only and only if the messages has been sent to me. In parse-server it is possible by constructing a query and add (equalTo: <MY_USER_ID>) and in Feathers I didn't manage to do it. 

So I wanted to know if this is currently possible with Feathers or it is planned to be supported in the future? 

Thanks,
Ran.

**Comment by daffl** [comment]
The Feathers real-time events (*created*, *updated*,  *removed* and *patched*) can be converted on the client into a live query stream. This often depends on the framework you are using, a generic approach to this using Functional Reactive Programming with [RxJS](http://reactivex.io/rxjs/) has been implemented with [feathers-reactive](https://github.com/feathersjs-ecosystem/feathers-reactive):

```js
const feathers = require('feathers');
const memory = require('feathers-memory');
const rx = require('feathers-reactive');

const app = feathers()
  .configure(rx({idField: "id"}))
  .use('/messages', memory());

const messages = app.service('messages');

messages.create({
  text: 'A test message'
}).then(() => {
  // Get and watch a specific message with id 0. Emit the message data once it resolves
  // and every time it changes e.g. through an updated or patched event
  messages.watch().get(0).subscribe(message => console.log('My message', message));

  // Find and watch all messages and emit a new list every time anything changes
  messages.watch().find().subscribe(messages => console.log('Message list', messages));
});
```

**Comment by ranhsd** [comment]
Hi @daffl thanks for your answer. But that’s mean that anyway it will be sent to my client by the server right ? So I cannot save this call... the idea is to save the call so the server will not even emit the payload if it will not fulfill the query conditions and this way you can reduce the number of data that is being transported from server to client. Another advantage is that you can react to those specific events when they occur and subscribe to multiple events of the same object with various conditions. 

What do you think? It is possible via Feathers? (By possible I mean maybe I can add some logic on the server side in order to make it happen)

Btw my client is iOS swift and not web app ...

Thanks!

**Comment by daffl** [comment]
It is possible using [channels](https://docs.feathersjs.com/api/channels.html) but by default Feathers is stateless and does not keep track of what the clients subscribed to on the server. Events are fairly cheap and as long as the client is allowed to see them for most applications it turned out to be much better for performance, scalability and ease of use to keep it this way.

**Comment by ranhsd** [comment]
Hi @daffl to be honest I don’t understand how it is stateless . In my feathers project I use socket.IO and subscribe to events on specific entity (let’s say messages) so I have an open connection with the server so when a new message is being created I immediately in real time get it... so the server must “know” all the clients that are connected to it. That is correct? Or what you just described is the default scenarios of feathers of REST only ?

**Comment by daffl** [comment]
What I mean is that there is no "session information" on that connection other than the authenticated user.

It puts much less stress on the server to just fire and forget events and let the clients figure out what they want to do with those. Like I mentioned, it is still possible to create a channel for each query and store that information but it has to be implemented manually and there are challenges when it comes to scaling and cleaning up cached data.

**Comment by ranhsd** [comment]
Hi @daffl ok I think I got it... So the best way as I see it is to implement it like how you describe in your first comment. Thank you very much!

BTW. parse-server solve the scaling challenge by putting pub-sub server ahead of the live query servers  (I use google pub-sub but you can also use Redis and other solutions)

Thanks again.

**Comment by daffl** [comment]
There is definitely things that can be done in that area. It depends on the application of course (especially if it generates a huge amount of events at once) but in the cases I encountered so far and by limiting events e.g. to the current user or company using channels, there didn't seem to be too many issues with just discarding unneeded events on the client and it helps to avoid many challenges when it comes to scaling and performance. We can always get more clever once the need arises 😉
