### ISSUE TITLE
after generating two service in mongoose, the API stopped working

### ISSUE THREAD

**Issue by GlauberF** [feathersjs/feathers#785]
after generating two service in mongoose, the API stopped working.
Are they in conflict?

When generating two mongoose-based services, do you need to do some additional configuration?

**Comment by daffl** [comment]
First, please update to the latest `@feathersjs/cli` (it should show `3.5.0` or later). Then also make sure that MongoDB is running and available locally on the default connection string.

I just generated two different Mongoose services and everything worked as expected.

**Comment by GlauberF** [comment]
Are the two services you generated connected to the same mongo database?

**Comment by daffl** [comment]
Yes. The generator (and Mongoose default) does not support multiple databases, those will have to be set up manually by adding a second [Mongoose connection file](https://github.com/feathersjs/generator-feathers/blob/master/generators/connection/templates/mongoose.js) using `mongoose.createConnection` and giving it a different name:

```js
const mongoose = require('mongoose');

module.exports = function (app) {
  const client = mongoose.createConnection(app.get('mongodb1'), {
    useMongoClient: true
  });

  app.set('mongoose1', client);
};
```
