### ISSUE TITLE
Are events emmited to all clients?

### ISSUE THREAD

**Issue by ricardopolo** [feathersjs/feathers#786]
We are creating a multi tenant app. So we have a service with lots of entries, but each user see only the ones that are related with his tenant. We do this adding a query param based on the authenticated user.

I understand that when the create  of a service is successful, feathers emit an event.
My question is: this wont over load my server and clients receiving events that are not relevant to them? Clients are not subscribed to the event but it will still receive the data?

And lastly, how can I have a filtered create event, that when something is create I only send the event to the clients that are from the tenant when the entry was created?

Thanks

**Comment by daffl** [comment]
That's what [channels](https://docs.feathersjs.com/api/channels.html) are used for. When a user authenticates, add them to a channel specific to their company/organization. When any event is sent, look if the data has organization information and if so dispatch to that channel:

```js
app.on('login', (payload, { connection }) => {
  // connection can be undefined if there is no
  // real-time connection, e.g. when logging in via REST
  if(connection) {
    const { user } = connection;

    // Join a channel just for the company
    app.channel(`companies/${user.companyId}`).join(connection);
  }
});

app.publish(data => {
  const { companyId } = data;

  // If the data is associated to a company send it to the company channel
  if(companyId) {
    return app.channel(`companies/${companyId}`);
  }
});
```

Now connected clients will only receive updates from within their own organization. This is just a basic example and you can customize everything to your needs. Refer to the [channel documentation](https://docs.feathersjs.com/api/channels.html) for more information.

**Comment by ricardopolo** [comment]
Thanks @daffl 
I still have this question about the default behavior. If the clients are not subscribed to the create even, they will still receive the data inside the webhook and just drop it or the data is not send?

My use case is a little bit differents and that why i think channels wont work.
We have users using a web ui, and we have machines using a windows service.

The user select a machine in the web ui, and press a button to start an execution in the windows client. We need to create an execution in the server, but how can I push the "new execution available to you" to the windows service. 
I don't like to have 1 channel per machine.

I would like to register a "websocketId" when they connected to the app, and the use that Id to push the data when the user press the button.

Any advice?

**Comment by daffl** [comment]
What's wrong with one channel per machine? That's really what they are for (e.g. in a chat you would also have one channel per user to allow private chats).

I usually recommend not to use non-persistent identifiers (like websocket ids) and instead use what is stored in the database (and those ids) as the source of truth.

**Comment by mogadanez** [comment]
What about restrict standard events like created/patched? 
even if service have **restrictToOwner** hooks on most methods, created/patched sent to all clients (including even not authenticated) and can have sensitive information (payments, balance, etc.. )

**Comment by daffl** [comment]
This was one of the big (and probably most important) changes in the [latest version](https://docs.feathersjs.com/migrating.html). Events are not sent out by default anymore and you have to decide who can see them or not.

Events are still different from restricting method calls though. A user might only request and view their own Todos but an admin may still want to be notified about any new todo.

**Comment by mogadanez** [comment]
Probably hook "publish" can help with own rules

17 янв. 2018 г. 3:30 ДП пользователь "David Luecke" <
notifications@github.com> написал:

**Comment by ricardopolo** [comment]
Perfect. Thanks!!
