### ISSUE TITLE
faild to minify inferno application

### ISSUE THREAD

**Issue by sxwebdev** [feathersjs/feathers#787]
when I updated my client application to "@feathersjs/feathers": "^3.0.5" version, I got error, that described here [https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify)

how to resolve this ?

thanks in advance

![capture](https://user-images.githubusercontent.com/3129246/35013534-bff81764-fb1e-11e7-831c-e705932ab21f.PNG)

**Comment by daffl** [comment]
Please see the [documentation section about Webpack and create-react-app](https://docs.feathersjs.com/api/client.html#webpack).

**Comment by sxwebdev** [comment]
thank. this helped me.
