### ISSUE TITLE
how get user object at 'after hooks'?

### ISSUE THREAD

**Issue by sultra** [feathersjs/feathers#794]
### Expected behavior
Is it possible to get user infomation at  the 'after hooks' ?

### Actual behavior
when at the 'before hooks' I can get that which is 'hook.params.user' however at the 'after hooks' 'hook.params.user' return is null ! 

### System configuration

Tell us about the applicable parts of your setup.

**Module Loader**: require('feathers-authentication').hooks

**Comment by daffl** [comment]
The hook object is the same, so `hook.params.user` should not return `null` unless you modified it in your own hooks.

**Comment by sultra** [comment]
Thanks answers @daffl 
Maybe I did not explain clearly,I mean my problems that at the ''after hooks' and specifically,it happened in 'create' method,BTW I really didn't modify `hook.params` in that process.

Using feathers version is '2.1.7', feathers-hooks version is '2.0.2'

**Comment by daffl** [comment]
Do you have an example to reproduce?

**Comment by sultra** [comment]
the code sample as below, it can console `hook.params.user` when there is no such 'console.log('after hook user', hook.params.user.id);' and but console `hook.params.user.id` is error happened what tell me 'TypeError: Cannot read property 'id' of undefined'

``` javascript
const {
  authenticate
} = require('feathers-authentication').hooks;
const {
  disallow,
  discard
} = require('feathers-hooks-common');

module.exports = {
  before: {
    all: [authenticate('jwt')],
    find: [],
    get: [],
    create: [hook => {
      console.log('before hook user', hook.params.user.id);
    }],
    update: [disallow()],
    patch: [],
    remove: [disallow()]
  },

  after: {
    all: [],
    find: [discard('_createTime', '_updateTime')],
    get: [discard('_createTime', '_updateTime')],
    create: [discard('_createTime', '_updateTime'),
    (hook)=>{
      console.log('after hook user', hook.params.user.id);
    }
  ],
    update: [],
    patch: [discard('_createTime', '_updateTime')],
    remove: []
  },

  error: {
    all: [],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  }
};

```

**Comment by sultra** [comment]
Finally, I know the reason,which is the 'feathers-rethinkdb' module caused what called twice 'after create hooks' . the first `hook.params.user` is 'undefined' and the second `hook.params.user` has right value
