### ISSUE TITLE
Two table of users

### ISSUE THREAD

**Issue by ricardopolo** [feathersjs/feathers#795]
In our product we have users and computers. Users via web, computers via a windows service using web sockets.

Do you think we can use feathers authentication for authenticated both of theam?
Ideally having feathers local working for the both tables (users and computers)?

I dont want to mix computers and users in the same table!

Thanks

**Comment by daffl** [comment]
You probably want to authenticate against an "entity" instead which then links to either a user or a device.

**Comment by ricardopolo** [comment]
So a table with

**Comment by daffl** [comment]
To clarify, I think a table with

```js
{
  "username": "",
  "password": "",
  "userId": "linked user id or null",
  "machineId": "linked machine or null"
}
```

Would work and then a hook that can populate the user/machine respectively:

```js
app.service('entity').hooks({
  async after(context) {
    const results = (context.method === 'find' ? context.result.data : [ context.result ]);
    const populate = async item => {
      if(item.userId) {
        item.user = await context.app.service('users').get(item.userId);
      }

      if(item.machineId) {
        item.machine = await context.app.service('machine').get(item.machineId);
      }
    }

    const updatedResults = await Promise.all(results.map(populate));

    if(context.method === 'find') {
      context.result.data = updatedResults;
    } else {
      context.result = updatedResults[0];
    }

    return context;
  }
});
```

Another option would also be to use a [different authentication strategy](https://docs.feathersjs.com/guides/auth/recipe.custom-auth-strategy.html) like API keys to authenticate machines.
