### ISSUE TITLE
Help. Reset connection socket.io (Saw setTimeout with duration 85000ms)

### ISSUE THREAD

**Issue by shanematte** [feathersjs/feathers#797]
Hello. Already asked, and it seems I understood what the problem is. Raises a warning from react native.
"Setting a timer for a long period of time, i.e. multiple minutes, is a performance and correctness issue on Android as it keeps the timer module awake, and timers can only be called when the app is in the foreground. See https://github.com/facebook/react-native/issues/12981 for more info.
(Saw setTimeout with duration 85000ms)"

https://github.com/facebook/react-native/issues/12981 did not help

That's the problem. when the application is hidden, and after 2 minutes to go back, an error when data is fetched. How many searched, and did not solve this problem, help.

react native 0.50.0
"feathers": "^2.1.7"
"feathers-client": "^2.3.0"
"socket.io": "^2.0.3"

**Comment by daffl** [comment]
Isn't that what the last part in https://docs.feathersjs.com/api/client.html#react-native should solve?

**Comment by shanematte** [comment]
@daffl yes :) thanks. I write pingTimeout:5000000 and everything works fine
