### ISSUE TITLE
Wrong cdn-url in docs

### ISSUE THREAD

**Issue by xstable** [feathersjs/feathers#799]
I had  a view at feathersjs, but found, that the docs have an error. 

Here in Getting started for the "Webpage-Setup" ... the CDN "unpgk.com" don't have an featherjs-package available: https://docs.feathersjs.com/guides/basics/starting.html#in-the-browser

And didn't found  another cdn which have. Please replace this dead link with a working one.

**Comment by subodhpareek18** [comment]
Yo, I just opened the link in the docs and got the code.
https://unpkg.com/@feathersjs/client@3.1.2/dist/feathers.js
![image](https://user-images.githubusercontent.com/12589797/35218783-eed99096-ff95-11e7-8b0a-1f4dca47ef1e.png)

**Comment by xstable** [comment]
Strange, work now. 
Ok. thank you for your reply
