### ISSUE TITLE
Create a generator for a feathers app

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers#80]
Possibly a yeoman generator? Or maybe just a CLI like express does. It should initially scaffold out an app structure and a `package.json` file that has all the dependencies that a normal express app needs, especially now that they are separate from express now.

I'm thinking an app structure could look like this:

```
public/
  -> fonts/
  -> images/
  -> js/
  -> styles/
  -> test/
server/
  -> config/
  -> lib/
  -> services/
  -> test/
  -> views/
.jshintrc
package.json
README.md
```

**Comment by daffl** [comment]
We can now keep track for this in https://github.com/feathersjs/generator-feathers
