### ISSUE TITLE
React Native Rest Not Working for feathers/client

### ISSUE THREAD

**Issue by riftshock** [feathersjs/feathers#802]
So i just followed the documentation with the configuration using axios:
`const axios = require('axios');`
`const restClient = rest('<my-server>');`
`app.configure(restClient.axios(axios));`

but when I do

`app.authenticate({ strategy: 'local', email: '<my-email>', password: '<my-password>' });`

it returns 'Error: Network Error';

does this package work with rest for React Native? I tried socket and socket works perfectly.

**ReactNative v0.51.0**
**@feathersjs/client: v3.1.2
@feathersjs/feathers v3.0.5
@feathersjs/authentication-client v1.0.2
@axios v0.17.1**

**Comment by daffl** [comment]
Are you able to use Axios to POST to the server directly? Looking at https://github.com/axios/axios/issues/751 there might be some configuration necessary on the server.

Or just go insteadwith [fetch which is supported by React Native](https://facebook.github.io/react-native/docs/network.html).

**Comment by riftshock** [comment]
@daffl thanks for replying David.

so I tried it on Android and it works perfectly fine as long as I don't put "/" slash at the end of the server url: 
`const restClient = rest('http://my-url.com')`

but doesn't work on IOS which returns `'Error: Network Error'`;  
`
     <key>NSAppTransportSecurity</key>
	<dict>
	    <key>NSAllowsArbitraryLoads</key>
	    <true/>
	</dict>
`

**Comment by riftshock** [comment]
@daffl thanks of replying David.

so I tried it on my Android device and works perfectly fine **as long as I don't put` "/"  slash`** at the end of my server url: 

 `const restClient = rest('http://my-server-url.com')`

also tried @wkarim86 solution about adding

```
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
</dict>
```
on the **info.plist** but it says that the info.plist `isn’t in the correct format`.

Is it possible that the error is because my server is configured as 

`http` 

which should be 

`https`

Adding SSL isn't possible for me right now.

my **Xcode** btw is on **version 9.2** and **Deployment target is 9.0**. Dunno if it matters.

Regarding **fetch** I don't really know how to implement it with feathers.

should I do it like this `app.configure(restClient.fetch(fetch))`??

**Comment by daffl** [comment]
Yes, `app.configure(restClient.fetch(fetch))` should be all there is to it. As for the configuration, I would highly recommend to use HTTPS in production. It is free and easy to set up on almost any platform by now and there are good reasons that it is a requirement and difficult to work around by now.

**Comment by riftshock** [comment]
So I found this hacky solution which worked:

![allowarbitraryloads](https://user-images.githubusercontent.com/4627358/35499342-e3918014-050c-11e8-90c9-1810d727ae78.png)

which results to Info.plist setting to:
```
<key>NSAppTransportSecurity</key>
<dict>
	<key>NSAllowsArbitraryLoads</key>
	<true/>
	<key>NSExceptionDomains</key>
	<dict>
		<key>localhost</key>
		<dict>
			<key>NSExceptionAllowsInsecureHTTPLoads</key>
			<true/>
		</dict>
	</dict>
</dict>
```

and yes I agree HTTPS should be used in production. For now we're only just waiting for the devops team to finish the configuration on our development server.

Anyway thanks for your time David. Really appreciated it.
I'm gonna close this now. Have a nice day =)

**Comment by edwardsmarkf** [comment]
i hope a feathers cookbook is forthcoming.  this would make an excellent
entry.


Thank you,

Mark Edwards
