### ISSUE TITLE
Disable default socket service emits

### ISSUE THREAD

**Issue by micheleangioni** [feathersjs/feathers#803]
### Steps to reproduce

Use a cli-generated service.

### Expected behavior

It should be possible to disable default emits.

### Actual behavior

Default emits cannot been disabled?

### More

This is the same as #142 but in the new version I do not find a way to achieve that. How can this be done?

**Comment by daffl** [comment]
Event emitting can be controlled by [channels](https://docs.feathersjs.com/api/channels.html). The default in a current generated application (using the latest `@feathersjs/cli`) is to send all events to all authenticated clients. You can control what events are being send in the `src/channels.js` file.

**Comment by micheleangioni** [comment]
Ok, so I need to disable them manually for each service.
I was already using something like

```
app.service('articles').publish((article, context) => { // eslint-disable-line no-unused-vars
    const userId = article.userId.toString()

    return app.channel(`user-${userId}`);
  });
```

to send the events only to a specific channel, I was wondering whether there was a more general way.
Thanks for you answer, keep up the good work on Feathers :)

**Comment by daffl** [comment]
You could also just remove the `return app.channel('authenticated');` in the `channels.js` file. That would disable all event dispatching and you can enable it on a per service basis.

**Comment by micheleangioni** [comment]
Nice, thanks for the hint
