### ISSUE TITLE
How to handle a search in multiple models with a single request?

### ISSUE THREAD

**Issue by lean** [feathersjs/feathers#804]
### Steps to reproduce

- The user fills an input. The data could be an User or a Team name
- The frontend sends a request with the name value to search

### Expected behavior
The API should do a search in the User table and in the Team table as well

**How should be the best way to handle this in a single request?**

**Comment by daffl** [comment]
For dashboards and cases like this [a custom service](https://docs.feathersjs.com/guides/basics/services.html) that redirects the search to the appropriate ones works best.

```js
app.use('/user-team', {
  async find(params) {
    const { name } = params.query || {};
    const query = {
      name: { $regexp: newRegExp(name) }
    };
    const users = app.service('users').find({ query });
    const teams = app.service('teams').find({ query });

    return { users, teams };
  }
});
```

As outlined in [this FAQ](https://docs.feathersjs.com/faq/readme.html#how-do-i-do-search) you may have to adapt the search method to your database of choice.
