### ISSUE TITLE
Problem when use feathers with next.js

### ISSUE THREAD

**Issue by Albert-Gao** [feathersjs/feathers#811]
I created a minimal setup which supposes to get `feathers.js` + `next.js`, however, it has some issues.

This is a file for `next.js`:
```javascript
const next = require('next');

const dev = process.env.NODE_ENV !== 'production';
const nextApp = next({ dev });
const handle = nextApp.getRequestHandler();

module.exports = {
  nextApp,
  handle
};
```

This is the `middleware`:

```javascript
const nextApp = require('../nextApp').nextApp;
const handle = require('../nextApp').handle;

// eslint-disable-next-line no-unused-vars
module.exports = function (app) {
  app.get('/index', (req, res) => {
    return nextApp.render(req, res, '/index', req.query);
  });

  app.use('*', (req, res) => {
    return handle(req, res);
  });
};
```

This is how I combine `next` with `feathers` in `app.js`, I just wrap some part in the `nextApp.prepare()`'s promise:

```javascript
const nextApp = require('./nextApp').nextApp;

nextApp.prepare().then(() => {
  app.configure(middleware);
  app.configure(services);
  app.configure(channels);

  app.use(express.notFound());
  app.use(express.errorHandler({ logger }));

  app.hooks(appHooks);
});

module.exports = app;
```

It generates a feathers app with feathers generator. Then add `next` support by using `npm i next react react-dom`.

I created a [repo](https://github.com/Albert-Gao/feathers-next-error-example) here: 

## How to re-produce this error?

1. `npm run build`
2. `npm run startc`
3. Open `http://localhost:3050/index`
4. The page get renders. But there are errors in the console.

## What is the error in the chrome console?

> This error won't be there when created an example with `express.js`.

```bash
Refused to execute script from 'http://localhost:3030/_next/1517717442914/manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
index:1 Refused to execute script from 'http://localhost:3030/_next/1517717442914/commons.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
index:1 Refused to execute script from 'http://localhost:3030/_next/1517717442914/main.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
index:1 Refused to execute script from 'http://localhost:3030/_next/1517717442914/page/index.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
index:1 Refused to execute script from 'http://localhost:3030/_next/1517717442914/page/_error.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
```

For the versions:
I use `next@latest`, `"@feathersjs/feathers": "^3.1.0"` and `node 8.9.4`

**Comment by Albert-Gao** [comment]
In case someone has the same problem or has question on how to setup feathers with next.js, here is my blog post about it: http://www.albertgao.xyz/2018/02/04/how-to-do-server-side-rendering-with-feathersjs-and-nextjs/

**Comment by daffl** [comment]
Thank you for sharing the blog post!

**Comment by Albert-Gao** [comment]
You are welcome. And I added a pull request to https://github.com/feathersjs/awesome-feathersjs :)
