### ISSUE TITLE
What are the pros and cons of using Feathers for a non-real-time app?

### ISSUE THREAD

**Issue by eammer** [feathersjs/feathers#812]
Or, to what degree using Feathers for a non-real-time app is an overkill?

**Comment by daffl** [comment]
Feathers is primarily a library that helps build your applications according to [REST principles](https://en.wikipedia.org/wiki/Representational_state_transfer). It eliminates most of the repetitive boilerplate you'd have to write with plain Express and most other web frameworks when building [CRUD](https://en.wikipedia.org/wiki/Create,_read,_update_and_delete) APIs while still giving you the same amount of flexibility. From our own and other people's experience a code reduction of 50% or more compared to the same functionality in a traditional Express application is not unusual (which is not bad given that Feathers core including the Express integration is less than 500 lines of code).

Additionally it does this in a way that is __protocol independent__. If people hear REST they mostly think of HTTP APIs but although most often used in the context of HTTP, Representational State Transfer (REST) is an __architectural design pattern__ and not a transport protocol. The HTTP protocol is just one implementation of the REST architecture. This means that the two small core concepts of Feathers, namely [services](https://docs.feathersjs.com/guides/basics/services.html) and [hooks](https://docs.feathersjs.com/guides/basics/hooks.html) can be used through not just HTTP but other protocols as well. If the other protocol - like websockets - also supports bidirectional communication, real-time updates are just a happy side effect of Feathers architecture. Besides that very small core (explained in the [basics guide](https://docs.feathersjs.com/guides/basics/readme.html))  __everything else in Feathers is optional__ so any overkill usually comes from additional things people think they want or need.

That said, Feathers is primarily intended to build APIs and not - although possible - for traditional websites that render views on the server so if that is your main use case you may want to stick with Express.
