### ISSUE TITLE
Wrong version of visionmedia/debug pulled when used in browser with ES6 modules

### ISSUE THREAD

**Issue by bitflower** [feathersjs/feathers#813]
### Steps to reproduce

I'm developing an app with the new Stencil web components compiler by the IONIC team (Great tool - like feathers 👍  ). It features ES6 module loading (lazy) and uses rollup internally.

After adding feathers in the browser app I found out that feathers pulls the node version of ```debug``` "[hard-wired](https://github.com/feathersjs/feathers/blob/14e41c947f6f1acd32b4d8f753b852511cb202be/lib/application.js#L1
)" instead of sensibly using the [decision inside index.js](https://github.com/visionmedia/debug/blob/master/src/index.js).

I'm not an expert with ES6 module loading nor bundlers like webpack or rollup but something is wrong here.

In the bundle of the I found this:
```javascript
/**
 * This is the Node.js implementation of `debug()`.
 *
 * Expose `debug()` as the module.
 */
```

EDIT:
The process.type property is something [added by Electron](https://github.com/electron/electron/blob/master/docs/api/process.md#processtype).

**So to make feathers ES6 compatable with debug() we could just set process.type to 'renderer' and use the workaround that is built in debug() for Electron apps?**

### System configuration

**Module versions** (especially the part that's not working):
@stencil/core@0.3.0-5
@feathersjs/feathers@3.1.0
debug@3.1.0

**NodeJS version**:
8.9.4

**Operating System**:
macOS 10.13.3

**Browser Version**:
Chrome 63

**Module Loader**:
Rollup? (Not sure)

**Comment by daffl** [comment]
If your process type is `browser` and not `renderer` it probably assumes that you are using a browser module bundler which [should use this mapping in the `debug` package.json](https://github.com/visionmedia/debug/blob/master/package.json#L42). An alternative is also to use the browser friendly [@feathersjs/client](https://docs.feathersjs.com/api/client.html#feathersjsclient).

**Comment by daffl** [comment]
I'm going to close this since it isn't really a Feathers issue and can also be solved by using `@feathersjs/client` in Electron.
