### ISSUE TITLE
auth not working with rethinkdb

### ISSUE THREAD

**Issue by danny-waite** [feathersjs/feathers#817]
guys, great project, really enjoying using feathers.

I've reached an issue where I cannot get authentication to work when using rethinkdb, spent a good few hours debugging this.

Essentially if you use the feathers-cli like so:

```
feathers g app
feathers g authentication
feathers g service
npm start
```

when trying to login from a React client I get `Authentication timed out`

If I do the exact same thing using nedb, it works a treat.

On further investigation it looks like when using rethinkdb, I don't see the following messages on start

```
@feathersjs/authentication:index registering Socket.io authentication middleware +85ms
@feathersjs/authentication:sockets Setting up Socket.io authentication middleware with options: { path: '/authentication',
```

I guess this is a pretty common use case, any help appreciated.

**Comment by daffl** [comment]
This can now be fixed by upgrading to `feathers-rethinkdb@0.5.1` and changing `src/rethinkdb.js` as in the PR at https://github.com/feathersjs/generator-feathers/pull/337/files
