### ISSUE TITLE
Specific channels for unauthenticated users

### ISSUE THREAD

**Issue by samburgers** [feathersjs/feathers#820]
Hi, 

Potential noob question... Just wondering how one might go about subscribing an unauthenticated user/client to a specific channel based purely on a `service` `_id` they were accessing (via URL or otherwise). 

For example, a public endpoint might be `/feeds/jkh345klj34h`, to which a number of `posts` can be published to. `posts` could by nature appear in multiple `feeds`

So an anonymous user could hit the `/feeds/jkh345klj34h` endpoint, and ideally have them subscribe to socket updates for `posts` only from that feed, rather than subscribe to a common `unauthenticated` channel containing updates from all posts.

In the docs it is very clear about how to subscribe authenticated users to specific channels, as the database would contain access levels for each user, but for unauthenticated users i cant really see how to subscribe to specific channels in a performant way. 

many thanks!

**Comment by samburgers** [comment]
in `channels.js` i would imagine i might be able add something like this. is there a way to pass a channel id down to the connection via the client?

```
app.on('connection', connection => {
  app.channel(`feeds/${connection.feed_id}`).join(connection);
});
```

**Comment by kbychkov** [comment]
I think you could write a custom hook for the `feeds` service, for example
```javascript
module.exports = function () {
  return context => {
    const { app, params, id } = context;

    app.channel(`feeds/${id}`).join(params.connection);

    return context;
  };
}
```

**Comment by samburgers** [comment]
Thank you!
