### ISSUE TITLE
How to require/import a service in an isolated function

### ISSUE THREAD

**Issue by ComputerCarl** [feathersjs/feathers#821]
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc. This makes it much easier for us to debug and issues that have a reproducable example will get higher priority.

### Expected behavior
I would like to use a service "outside" of a hook/service

### Actual behavior
I cannot

### System configuration
Latest and greatest everything

Whilst programming.. I usually put everything into a single huge file.
In my current predicament, I am writing everything in a custom class, in which I have access to the `app` object via;
````js
class Service {
  setup(app) {
    this.app = app;
  }
...

 var widgets= this.app.service('widgets');
````

However, I am trying to refactor my code and split it into separate functions.
I have tried everything possible (considering my JS abilities only slightly exceed my Feathers abilities).

What is the best way to do this? Pass the app/service to the function? Are/is there some files(s) I can require to get this working?

````js
// setYay.js
const widgets = require('../how/do/I/get it');

module.exports = (params) => {
  widgets.create({text: 'yay!'});
};
````

**Comment by daffl** [comment]
You have to pass the `app` object. This can be done by requiring `src/app` or using a [configure function](https://docs.feathersjs.com/guides/basics/generator.html#configure-functions):

In `messages.service.js`:

```js
const memory = require('feathers-memory');

module.exports = function(app) {
  app.use('messages', memory({
    paginate: {
      default: 10,
      max: 25
    }
  }));
};
```

Then in another file:

```js
const feathers = require('@feathersjs/feathers');
const memory = require('feathers-memory');
const configureMessages = require('./messages.service.js');

const app = feathers();

app.configure(configureMessages);
```

**Comment by ComputerCarl** [comment]
Thanks for your quick reply!
When you say "requiring src/app", I have tried with zero success things like;
````js
const app = require('../app');
and
const widgets= require('../services/widgets/widgets.service');
````
and 20 other combinations..

Which was is best? it looks that that way will bypass the hooks and things already set up in the main Feather app.
Sorry if I'm not understanding properly.

**Comment by ComputerCarl** [comment]
I have create a test at https://github.com/ComputerCarl/test_feathers_service to demonstrate.

**Comment by daffl** [comment]
Yes, I meant you can do

```js
const app = require('../app');
```

And then retrieve your services via [app.service](https://docs.feathersjs.com/api/application.html#servicepath) under the name the service is registered:

```js
const widgets = app.service('widgets');
```

**Comment by ComputerCarl** [comment]
I thought this was a trivial matter that I just wasn't getting, but it's still not working.

I'd seen your solution and it looked so simple and familiar; it was one of the first things I'd tried after reading and re-reading two versions of the Feathers docs service sections. The following is the error;
````
C:\Users\interim\Projects\test_feathers_service\src\services\things\writeWidgets.js:6
const widgets = app.service('widgets');
                    ^

TypeError: app.service is not a function
    at Object.<anonymous> (C:\Users\interim\Projects\test_feathers_service\src\services\things\writeWidgets.js:6:21)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\interim\Projects\test_feathers_service\src\services\things\things.class.js:2:22)
    at Module._compile (module.js:643:30)
````

**Comment by ComputerCarl** [comment]
Passing the app to the function makes perfect sense, especially after your explanation of what I was doing wrong; coding myself into a circle.

I was wondering why the imported `app.js` was always an empty object.

Thank you for your expertise once again and taking the time to explain this.
