### ISSUE TITLE
[Question] [Nedb] How make a true fuzzy string search?

### ISSUE THREAD

**Issue by AlexVFornazieri** [feathersjs/feathers#822]
I need to do an approximate string match search, I thought the [feathers-nedb-fuzzy-search](https://github.com/arve0/feathers-nedb-fuzzy-search) would solve the problem, but by the tests I did, it did not work. Maybe i am doing someting wrong :(

I need a search functionality that returns approximately equal words as a result, as described at https://en.wikipedia.org/wiki/Approximate_string_matching

I believe, if this does occur, punctuation marks (and accents) will also be ignored in the comparison.

If this is exactly what the feature in this repository does, what I am doing wrong for this don't work accordingly? Now, if this is not the proposal, how can I achieve this?

Thank you all for the attention.

**Comment by daffl** [comment]
It will only match actual string occurrences, not similar ones and I don't believe NeDB supports this feature. You will have to do [Levensthein distance](https://github.com/hiddentao/fast-levenshtein) comparisons manually or implement a search indexing tool like [Lunr](https://www.npmjs.com/package/lunr).

**Comment by daffl** [comment]
Hope that helps and you're able to find the right tool for it. Closing since it isn't really a Feathers specific issue.
