### ISSUE TITLE
Channel namespace unsubscibe all

### ISSUE THREAD

**Issue by samburgers** [feathersjs/feathers#824]
Is there, by some miracle, a way to unsubscribe from an entire namespace of channels at once? Something like this:

```
channel('article/*').leave(connection);
```

**Comment by daffl** [comment]
[app.channels](https://docs.feathersjs.com/api/channels.html#appchannels) returns an array of all channel names. You can filter it according to your criteria and return a [combined channel](https://docs.feathersjs.com/api/channels.html#appchannelnames):

```
const articleChannels = app.channels.filter(name => name.startsWith('article/'));

app.channel(... articleChannels).leave(connection);
```

**Comment by samburgers** [comment]
That is perfect, thank you!
