### ISSUE TITLE
"no auth token" while accessing another service from a hook

### ISSUE THREAD

**Issue by ishrak-imam** [feathersjs/feathers#825]
Here is one of my hook which access another service (requires authentication).

```javascript
module.exports = function (options = {}) { // eslint-disable-line no-unused-vars
  return function systemMessageAfterTrip (hook) {
    // Hooks can either return nothing or a promise
    // that resolves with the `hook` object for asynchronous operations
    return hook.app.service('messages').create({
      from: hook.params.admin._id,
      to: hook.params.user._id,
      trip: hook.result._id,
      text: `message`,
      message_type: 'SYSTEM',
      custom_event: null
    }).then(_ => {
      return Promise.resolve(hook);
    }).catch(err => {
      console.log(err);
      return Promise.resolve(hook);
    });
  };
};
```

The problem is the hook work ok. It does what it needs to do in the messages service but after that is goes to the `catch` block with an `no auth token` error. But the behaviour is not consistent. Sometimes it is in the `then` block and works ok.

The whole scenario is,  I api request to one service say `service-1` and the above hook is used as an after(create) hook of that service which access another service say `service-2` which is a normal service requiring authentication. But sometimes the `service-2` call returns with an `no auth token` error.

**Comment by daffl** [comment]
I am making calls like this quite often and never experienced that problem. It came up most frequently in combination with `feathers-hooks-common`, specifically the `populate` hook. You can find further discussion in https://github.com/feathersjs/authentication/issues/577. Going to close this one as a duplicate.

**Comment by eddyystop** [comment]
When you call a service from within a hook, you have to consider what props in `context.params` have to included in the service call. You can start reading around https://auk.docs.feathersjs.com/guides/step-by-step/basic-feathers/writing-hooks.html#calling-a-service

**Comment by ishrak-imam** [comment]
@eddyystop 
I have read the docs and as it said I have to consider the `context.params` while making a service call from inside a hook for `get` method. As you can see that I am making a `create` call to a service from indie a hook and the signature is `.create(data, params)` as in doc says params are for extra data, like it can be the authenticated user. But in this case what I am supposed to provide in params while making a `create` call.

And it's not that my hook is not working. It works and doesn't work, the behaviour is not consistent.

@daffl 
As you can see that I have a `console.log(err)` inside the `catch` block. Is there any mistake in my writing  a hook, if not then why sometimes I get a log of an error `no auth token` from the `catch` block. You may not experienced a problem like that, but does it mean I am lying?
And its not that when I am getting an error in the `catch` block the create operation is not being done. The data is inserted successfully but it returns a `no auth token` error.

To mention I am using feathers rest and socket connectivity. My client connects with feathers through socket

Please just don't close the issue for the sake of 
> I am making calls like this quite often and never experienced that problem

**Comment by daffl** [comment]
I am closing issues that don't have enough information to reproduce it and your code sample does not do that. If you can provide a complete application that reproduces your issue I am happy to look into it.
