### ISSUE TITLE
no headers object in hook/context

### ISSUE THREAD

**Issue by kairos666** [feathersjs/feathers#826]
I implemented [API key authentication](https://docs.feathersjs.com/guides/auth/recipe.custom-auth-strategy.html#creating-a-custom-api-key-auth-strategy) example according to documentation sample

I have already done so with V2 auk feathersJS. So repeating the same process for V3 buzzard.
Everything seems fine until defining the hook (cli generated hook with up-to-date cli)

```javascript
commonHooks.iffElse(
      // if the specific header is included
      ctx => ctx.params.headers['x-api-key'],
      // authentication with this strategy
      auth.hooks.authenticate('apiKey'),
      // else fallback on the jwt strategy
      auth.hooks.authenticate(['jwt'])
)
```
Unfortunately **headers** property in predicate **ctx => ctx.params.headers['x-api-key']** is undefined
```console
error: Error in 'mood-updates-achievements' service method 'find' TypeError: Cannot read property 'x-api-key' of undefined
    at commonHooks.iffElse.commonHooks.iffElse.ctx (C:\_data\_githubs_repo\moodys-backend-achievements\src\hooks\api-authenticate.js:40:34)
    at C:\_data\_githubs_repo\moodys-backend-achievements\node_modules\feathers-hooks-common\lib\common\iff-else.js:17:63
    at promise.then.hookObject (C:\_data\_githubs_repo\moodys-backend-achievements\node_modules\@feathersjs\commons\lib\hooks.js:174:73)
    at <anonymous>
```

Same with the **context parameter (called hook in V2)** object passed to the hook. So the common Hooks are not at fault here. 
I'm sure the context params are not being accessed or deleted anywhere else in some custom code because my app is pretty barebone at the moment.

I expected that headers properties would be populated as usual. 
What could be wrong here ? 
Am I missing a step to enable passing headers values to the context object or did i ran into a bug ?

**Additional details**
- get/find service (pristine after being generated through CLI)
- hook throwing error is the first one to be applied **before/all - service level**
- logger hook at **after/all - app level**
- error-handler hook at **error/all - app level**

Thanks in advance ... featherJS is awesome by the way!

**Comment by arifNislam** [comment]
Same here, need a specific header value before executing a **create** operation, but there is no **header** in hook **context**. Though header is accessible using a **middleware** function before registering a service, but i need it in the hooks because all validation is in the hook.

**Comment by kairos666** [comment]
Ok found a solution to my problem ... silly me.
I actually forgot to configure the authentication strategy in **app.js**

```javascript
app.configure(authentication);
```

Doing so solved my issue. **headers** are now available in context object of a hook.

Therefore I repurpose this issue as a simple question.
For which reason headers are not available in a hook context by default ?

**Comment by daffl** [comment]
Because they shouldn't be. It breaks with the concept of services as protocol independent interfaces and the next breaking version of the authentication plugin will probably removed this default behaviour.

There is an [FAQ entry about this here](https://docs.feathersjs.com/faq/readme.html#how-do-i-access-the-request-object-in-hooks-or-services).

**Comment by kairos666** [comment]
thanks @daffl for the FAQ pointer and the explanation. All clear now.
