### ISSUE TITLE
Help: Nuxt.js integration

### ISSUE THREAD

**Issue by gianniskarmas** [feathersjs/feathers#828]
With so many changes in feathers v3 can you please give an example of using it with nuxt.js?

**Comment by bertho-zero** [comment]
You can found an example here: https://github.com/nuxt/nuxt.js/tree/master/examples/with-feathers

**Comment by gianniskarmas** [comment]
Thank you @bertho-zero but unfortunately all these use feathers v2 and when try to migrate or upgrade things crash so I was wondering if someone has a working example with nuxt and all dependencies for v3.
Many Thanks

**Comment by daffl** [comment]
The only change using Feathers on the client is the module names and having your module loader include the `node_modules/@feathersjs` folder. The module names [can be updated automatically using the CLI](https://docs.feathersjs.com/migrating.html#updating-client-side-applications).

**Comment by gianniskarmas** [comment]
I'm new on this and trying to understand the process:
```
git clone https://github.com/nuxt/nuxt.js.git
cd nuxt.js/examples/with-feathers
yarn install
feathers -V
3.6.1
feathers upgrade
11 unmodified
yarn install
npm run dev
/src/services/user/hooks/index.js:9
    auth.verifyToken(),
         ^
TypeError: auth.verifyToken is not a function
```
What am I doing wrong and how should I proceed from here?

**Comment by daffl** [comment]
Looks like that example is still using the extra old version of Feathers authentication. It would be great if someone could update the example in the Nuxt.js repository.

**Comment by joshua1** [comment]
I tried using current version of feathers, but get an error in the nuxt middleware 
```
Error: '(req, res, next) => {
    render(req, res, next)
  }' is not a valid service path.
```
from my index.js midddleware i have 
```
const { render } = require('./nuxt')

module.exports = function(app) {
  // Add your custom middleware here. Remember, that
  // just like Express the order matters, so error
  // handling middleware should go last.
  // const app = this
  console.log(!!render)
  app.use((req, res, next) => {
    render(req, res, next)
  })
}
```
and in nuxt.js in middleware folder i have 
```
// @ts-nocheck
const { Nuxt, Builder } = require('nuxt')
const logger = require('winston')
const config = require('../../nuxt.config')

const nuxt = new Nuxt(config)

if (config.dev) {
  new Builder(nuxt)
    .build()
    .then(() => process.emit('nuxt:build:done'))
    .catch((error) => {
      logger.error(error)
      process.exit(1)
    })
} else {
  process.nextTick(() => process.emit('nuxt:build:done'))
}

module.exports = nuxt

```
what am i doing wrong here. feathers3 breaks everything with nuxt . should we just stick with 2 then

**Comment by daffl** [comment]
There is a clear migration path outlined in the [migration guide](https://docs.feathersjs.com/migrating.html) much of which can be done [automatically via the CLI](https://docs.feathersjs.com/migrating.html#quick-upgrade) (your problem is outlined [here](https://docs.feathersjs.com/migrating.html#framework-independent)).

The problem with the example at https://github.com/nuxt/nuxt.js/tree/master/examples/with-feathers is that it uses a pretty outdated, more than 2 year old version of the authentication plugin. The migration guide for that [can be found here](https://github.com/feathersjs/authentication/blob/auk/docs/migrating.md) and should be done first.

**Comment by joshua1** [comment]
@daffl nothing there speaks to the nuxt integration. I dont know what app in middleware/index.js represents , i just imported nuxt into src/index.js and did ```app.use``` and it worked. I actually started the project using feathers 3 cli.
```
const nuxt = require('./middleware/nuxt')

app.use((req, res, next) => {
  nuxt.render(req, res, next)
})
```

**Comment by kharhys** [comment]
Take a look at [feathers-nuxt template](https://github.com/feathers-nuxt/template-app) for a boilerplate project set up with feathers and nuxt with a few extra niceties such as user authentication, authorization, logging, transpilation of server code, live reload among others. Documentation and more features to be added in the future. 

The project is a WIP, at very early stage actually, but still a good source of ideas for anyone looking to integrate feathers and nuxt!
