### ISSUE TITLE
Detail event filtering in Buzzard

### ISSUE THREAD

**Issue by trixden** [feathersjs/feathers#829]
Hi, guys. Doubtless, channels in Buzzard - it's good system, but it less functional than the filter. Or I missed something.

For example, i have 2 channels: `guests`, and `admins`. To `guests` channel i send events for `articles` model, and don't send anything more. Ok, but, how to send them articles only with property `publish: true`?

In Auk it was easy. But what should I do in Buzzard?

**Comment by daffl** [comment]
I'm not sure if this isn't explained well in the docs but you can set [service specific publishers](https://docs.feathersjs.com/api/channels.html#servicepublishevent-fn) and then check the `data` (you also get the hook context):

```js
app.service('articles').publish((article, context) => {
  if(data.published) {
    // Publish to `guests` and `admins`
    return app.channel('guests', 'admins');
  } else {
    // Only `admins` can see updates to unpublished articles
    return app.channel('admins');
  }
});
```

**Comment by trixden** [comment]
Perfectly. Thanks)
