### ISSUE TITLE
Koa version? 

### ISSUE THREAD

**Issue by MathRobin** [feathersjs/feathers#83]
Hi guys! Thank for your work! 

Is there will be a version compatible for Koa framework. Koa is the Express future, designed by the express team with EcmaScript 6 features...

Things are a few different but the change is really interesting. Do you think about a migration/fork for it?

I use Koa, performances are awesome in comparison of express. Fork feathers for it could be awesome too

**Comment by ekryski** [comment]
No problem @MathRobin, thanks for weighing in!

**Comment by myuseringithub** [comment]
@daffl 
How far is it from being decoupled from Express ?  I would like to use Koa v2 with it.
Thanks

**Comment by marshallswain** [comment]
@myuseringithub A Koa adapter needs to be created.  `feathers-rest` is for Express.  If you want to get started on it, you can check out the `feathers-rest` code and make something similar that will work for Koa.
