### ISSUE TITLE
Best way to implement "Somebody is typing" indicator in chat app

### ISSUE THREAD

**Issue by EliSadaka** [feathersjs/feathers#830]
I'm building a chat app and want to implement a feature so that if someone begins typing out a message, everyone in that chatroom will receive a small indicator saying that that person is typing. What would be the best way to implement such a feature? Every chatroom is its own channel so I was thinking I could send out a custom event when someone is typing and publish it to everyone else in the same channel, but according to the FeathersJS docs clients cannot send custom events to the server so how would I let the server know when someone in a specific channel is typing? Any help is appreciated.

**Comment by subodhpareek18** [comment]
Maybe make a field in the model of the chatroom/conversation db model. And update that everytime someone starts typing/stops typing. It could be an array so that you could store multiple people typing. This is maybe not the best approach, but this is show I'd start with this feature.

**Comment by daffl** [comment]
Yep, that's definitely one way. Another would be to create a `room-activity` service that tracks (and sends events) on room activity. Generate a `room-activity` custom service with authentication that looks like this:

```js
class RoomActivity {
  async create(data, params) {
    const { type, roomId } = data;
    const userId = params.user._id;
    const id = `${userId}/${type}`;

    return { id, type, userId, roomId };
  }
}
```

Then on the client you can listen to `keydown` to trigger the `typing-start` activity and after a delay when typing stopped sent the `typing-end` activity:

```js
let typing = false;
let timeout;

document.getElementById('message-field').addEventListener('keydown', () => {
  if(!typing) {
    typing = true;

    app.service('room-activity').create({
      type: 'typing-start',
      roomId: roomId
    });
  }
  
  // Assume that the user has stopped typing after one second of no key pressed
  clearTimeout(timeout);
  
  timeout = setTimeout(() => {
    app.service('room-activity').create({
      type: 'typing-start'
    });
  }, 1000)
});
```

Then the status can be updated by listening to the `room-activity` service `created` events:

```js
app.service('room-activity').on('created', data => {
  if(data.type === 'typing-start') {
    console.log(`${data.userId} is typing`);
  }

  if(data.type === 'typing-end') {
    console.log(`${data.userId} stopped typing`);
  }
});
```
