### ISSUE TITLE
Created event on websocket client is not fired.

### ISSUE THREAD

**Issue by PowerMogli** [feathersjs/feathers#831]
### Steps to reproduce

Client side code
```js
const feathers = require('@feathersjs/feathers');
const socketio = require('@feathersjs/socketio-client');
const io = require('socket.io-client');
this.socket = io.connect('http://localhost:3005');

const app = feathers();

app.configure(socketio(this.socket));

this.socket.on('connect_error', _ => {
  console.log(_);
});

this.socket.on('error', _ => {
  console.log('ERROR!!');
});

var service = app.service('messages');
service.on('created', item => {
  console.log(item);
});

this.socket.on('messages created', item => {
  console.log(item);
});

service.create({ blah: 'blah' }).then(result => {
  console.log(result);
});

```

Server side code
```js
const express = require('@feathersjs/express');
const feathers = require('@feathersjs/feathers');
const socketio = require('@feathersjs/socketio');
const app = express(feathers());

app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.configure(express.rest());
app.configure(socketio.default(3005));
app.use('/messages', {
  create(data, params) {
    return Promise.resolve(data);
  }
});
// app.configure(setupProxy);
app.use(express.notFound());
app.use(express.errorHandler());

app.listen(3006);

```
### Expected behavior
Created-Event on client should be fired.

### Actual behavior
Neither on socket nor on service the created-event is fired.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working): 
@feathersjs/feathers": "^3.1.3"
@feathersjs/socketio-client": "^1.1.0"
"socket.io-client": "^2.0.4"

**NodeJS version**: 9.3.0

**Operating System**: Windows

**Comment by daffl** [comment]
Feathers Buzzard introduced a more secure default behaviour for sending events. Please have a look a the example at [feathersjs.com](https://feathersjs.com/), the [real-time basics guide](https://docs.feathersjs.com/guides/basics/real-time.html) and the [channels documentation](https://docs.feathersjs.com/api/channels.html).

If you are coming from a previous version, also see the [channels section int the migration guide](https://docs.feathersjs.com/migrating.html#adding-channels).

**Comment by FelixButzbach** [comment]
Sorry for hijacking this issue, but it seams related to my question.
I am playing around with the feathers-chat-react example app and I am trying to discover if the backend is offline. I can get the socket event 'error' or 'connection_error' when using the original socket object, but when using the feathers client wrapped socket object those events are not being fired. 
Why is this? Because of security? If so, what is the best way to handle this? 
Thanks

**Comment by daffl** [comment]
Since Feathers is transport agnostic, the client will only convey the abstracted service related events, not anything specific to the transport you are using. The socket you are looking for is in `app.io` (which is the original socket).
