### ISSUE TITLE
events - not working

### ISSUE THREAD

**Issue by GlauberF** [feathersjs/feathers#832]
### events - not working

something changed with the events, after I update my feather, events like userService.on ('created', callback) are no longer working on my client side.

**Comment by daffl** [comment]
Did you follow the [migration guide](https://docs.feathersjs.com/migrating.html) specifically the manual part of [setting up event channels](https://docs.feathersjs.com/migrating.html#adding-channels)?

**Comment by GlauberF** [comment]
no, but I just upgraded feathers-cli to @ feathersjs / cli.
Will this alone influence events already?
And do the events no longer work automatically, as before, in previous versions?

**Comment by daffl** [comment]
Yes it will, that's why is a breaking change 😉 The migration guide has all the information you need. After running the upgrade command you have to copy & paste one file and add one line of code.

**Comment by GlauberF** [comment]
only receive socket events, who is logged in?

I need to issue, for those who are disconnected too, as in previous versions;

**Comment by daffl** [comment]
Please review the migration guide (it even has [an old version polyfill](https://docs.feathersjs.com/migrating.html#basic-service-filter)) and [channel documentation](https://docs.feathersjs.com/api/channels.html). All that's needed to get the previous behaviour is to change `return app.channel('authenticated');` to `return app.channel('authenticated', 'anonymous');` or using the code from on the [Feathers homepage](https://feathersjs.com/):

```js
// Add any new real-time connection to the `everybody` channel
app.on('connection', connection => app.channel('everybody').join(connection));
// Publish all events to the `everybody` channel
app.publish(data => app.channel('everybody'));
```

There were good reasons for this change though. Usually you don't want anybody to be able to listen to all events that are happening in your application.

**Comment by GlauberF** [comment]
I use this lib for angularjs, but it should be outdated (https://github.com/beevelop/ng-feathers) what should I change to work now with the new version?
Can you help me, indicate what to change in it?

**Comment by daffl** [comment]
Your frontend will still work, it does not have to be upgrade right away.

If you want to submit a pull request to that library however, all that needs to be changed is removing the one line at https://github.com/beevelop/ng-feathers/blob/master/src/ng-feathers.js#L37.

**Comment by GlauberF** [comment]
worked 100%
My next step is to understand how authentication works and to release some unique channels to who is connected.

**Comment by daffl** [comment]
Sweet 👍, closing this issue then.
