### ISSUE TITLE
issue with app.get('public')

### ISSUE THREAD

**Issue by idealley** [feathersjs/feathers#833]
Could some one point me to the right direction?

I have an app, that works perfectly locally, that builds on travis, all tests are passing, but it refuses to start on the production server while everything was fine till now. I do not know even how to reproduce the bug.

Here is the message I get:

```
path.js:39
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'path', 'string');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:39:11)
    at Object.join (path.js:1218:7)
    at Object.<anonymous> (/home/clients/74d8b4b64a924ae990bc3821c8a5961d/api/api-ers/src/app.js:38:22)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/clients/74d8b4b64a924ae990bc3821c8a5961d/api/api-ers/src/feathers.js:4:13)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
```

It corresponds to the following line: `app.use(favicon(path.join(app.get('public'), 'favicon.ico')));``

If I replace manually the path (app.get('public)) then the server starts, but it will crash everytime there is app.get() called. I have deleted the node_modules, reinstalled everything etc. I do not know what to do else.

I have tried with different node version on the production server (the same with which tests are passing)
I have the following packages installed:

```js
  "dependencies": {
    "@feathersjs/authentication": "^2.1.2",
    "@feathersjs/authentication-client": "^1.0.2",
    "@feathersjs/authentication-jwt": "^2.0.0",
    "@feathersjs/authentication-local": "^1.1.0",
    "@feathersjs/configuration": "^1.0.2",
    "@feathersjs/errors": "^3.3.0",
    "@feathersjs/express": "^1.2.0",
    "@feathersjs/feathers": "^3.1.3",
    "@feathersjs/rest-client": "^1.3.3",
    "@feathersjs/socketio": "^3.2.0",
    "axios": "^0.18.0",
    "body-parser": "^1.18.2",
    "chalk": "^2.3.2",
    "compression": "^1.7.2",
    "cors": "^2.8.4",
    "dotenv": "^4.0.0",
    "elasticsearch": "^14.1.0",
    "ers-utils": "^0.2.1",
    "feathers-authentication-hooks": "^0.1.7",
    "feathers-hooks-common": "^4.8.0",
    "feathers-hooks-rediscache": "^1.0.2",
    "feathers-mongoose": "^6.1.0",
    "feathers-swagger": "^0.6.0",
    "gitana": "^1.0.256",
    "graphql": "^0.13.1",
    "graphql-server-express": "^1.3.2",
    "graphql-tools": "^2.21.0",
    "helmet": "^3.12.0",
    "mongodb": "^3.0.2",
    "mongoose": "^5.0.6",
    "proxy-agent": "^2.2.0",
    "redis": "^2.8.0",
    "request-promise": "^4.2.2",
    "serve-favicon": "^2.4.5",
    "validator": "^9.4.1",
    "winston": "^2.4.0"
  },
```

it is running on apache (unfortunately) 

It is as if get() is not returning anything but undefined.

Any pointer?

**Comment by idealley** [comment]
the build: https://travis-ci.org/EuropeanRespiratorySociety/api-ers
the repo: https://github.com/EuropeanRespiratorySociety/api-ers

**Comment by daffl** [comment]
Did you set the `NODE_ENV` environment variable to `production`?

**Comment by idealley** [comment]
Yes I did :(

**Comment by daffl** [comment]
In that case, either your `default.json` or your `public.json` provides a value for `public`.

Only `development.json` has one. The idea is that `default.json` should provide default values that should be available for any environment (unless overwritten). You probably want to move both, `public` and `paginate` into `default.json`.

**Comment by idealley** [comment]
Oh thank you. I got lost yesterday. I was looking in the wrong direction. I do not know why my config changed, but that is fixed now.
