### ISSUE TITLE
new Russian sponsor

### ISSUE THREAD

**Issue by vodniciarv** [feathersjs/feathers#837]
Yesterday I received a [Telegram](https://t.me/featherjs) message from a person who wants to sponsor an OpenSource framework,  he asked me to post Feathers statistics, but I don’t have access, @daffl can you contribute?
![photo_2018-03-16_11-53-49](https://user-images.githubusercontent.com/14403446/37514664-38646c14-2911-11e8-8b58-3bbdbc59e4d2.jpg)

**Comment by daffl** [comment]
Which ones are you looking for? [This blog post](https://blog.feathersjs.com/flying-into-2018-13bda623f089) has some from last year and so far this year has been similar:

<img width="408" alt="screen shot 2018-03-16 at 8 00 32 am" src="https://user-images.githubusercontent.com/338316/37527807-24717d44-28f0-11e8-864a-22f8f5c93a1f.png">

**Comment by vodniciarv** [comment]
Thank You!
