### ISSUE TITLE
Migration error: MethodNotAllowed(405) Provider 'socketio' can not call 'create

### ISSUE THREAD

**Issue by Elminday** [feathersjs/feathers#849]
### Problem

After migration to v3 feathers calling user service create method I get this error:

_**MethodNotAllowed(405): Provider 'socketio' can not call 'create'. (disableMethod)**_

**Module versions** (especially the part that's not working):
    "@feathersjs/socketio": "^3.2.0",

**NodeJS version**: 8.9.1

**Operating System**: Ubuntu

**Module Loader**:Webpack

I added channel.js

```
module.exports = (app) => {
  if (typeof app.channel !== 'function') {
    return;
  }

  app.on('connection', (connection) => {
    app.channel('anonymous').join(connection);
  });

  app.on('login', (authResult, { connection }) => {
    if (connection) {
      const user = connection.user;
      app.channel('anonymous').leave(connection);
      app.channel('authenticated').join(connection);
    }
  });

  app.publish((data, hook) => { // eslint-disable-line no-unused-vars
    app.channel('authenticated');
  });
};
```

and used channel in app.js

```

import feathers from '@feathersjs/feathers';
import auth from '@feathersjs/authentication-client';
import socket from '@feathersjs/socketio-client';
import io from 'socket.io-client';
import channels from '../channels';

let instance = false;
const config = global.CONFIG;
const storage = (global.TYPE === 'CLIENT') ? window.localStorage : null;
const uri = ['http://', config.io.host, ':', config.io.port].join('');
export function app() {
  if (instance) return instance;

  instance = feathers()
    .configure(socket(io(uri)))
    .configure(channels)
    .configure(auth({ storage }));

  return instance;
}

export function service(name) {
  return app().service(name);
}
```

In my autoLoader.js class I changed from:

```
service.before(require(dir + '/hooks.before.js').default);
service.after(require(dir + '/hooks.after.js').default);
```
to:
```
this.app.hooks({
    before: require(dir + '/hooks.before.js').default,
    after: require(dir + '/hooks.after.js').default 
  });
```

**Comment by daffl** [comment]
The error is coming from the `disallow` common hook. I'd check the services where it has been registered. Have you upgraded `feathers-hooks-common` to the latest version as well?

**Comment by Elminday** [comment]
I was using 3.6.1 feather-common-hooks.
Upgraded to 4.10.0 but the problem persists.

**Comment by daffl** [comment]
Do you see in the stack trace what service it is coming from? Nothing major really has changed there but there could've been a bug fixes (e.g. passing the params as they were intended to) that changed the behaviour.

**Comment by Elminday** [comment]
Auth-management. We use commonHooks.disallow('external') for 'all' hooks.before.

Our service:
```
const authManagement = require('feathers-authentication-management');
const notifier = require('./notifier');
const configUser = require('../user/config');

module.exports = app => authManagement({
  notifier: notifier(app).notifier,
  service: configUser.namespace,
  identifyUserProps: ['username', 'email', 'phone'],
});

```

**Comment by Elminday** [comment]
Up

**Comment by daffl** [comment]
Yes, please also bring it up in https://github.com/feathers-plus/feathers-authentication-management.

**Comment by daffl** [comment]
Looks like it has been resolved in the related issue. Thanks for sharing the solution.
