### ISSUE TITLE
MongoDB _id queries not working correctly

### ISSUE THREAD

**Issue by EliSadaka** [feathersjs/feathers#851]
I'm using MongoDB for my services and I'm trying to convert my ids to ObjectId before I perform a find query but it doesn't seem to be working properly. I followed the example given [here](https://github.com/feathersjs/feathers/issues/757#issuecomment-352881878) so this is what I have in my before find hook:

```
const ObjectID = require('mongodb').ObjectID;

module.exports = function (options = {}) {
  return async context => {
    const { query = {} } = context.params;

    if(query._id) {
      if(typeof query._id === 'string') {
        query._id = new ObjectID(query._id);
      } else if(query._id.$in) {
        query._id.$in = query._id.$in.map(id => new ObjectID(id));
      } else if (query._id.$ne) {
        query._id.$ne = query._id.$ne.map(id => new ObjectID(id));
      }
    }

    context.params.query = query;
    return Promise.resolve(context);
  }
};
```

And this is an example of one of the queries I'm trying to perform:

```
users.find({
   query: {
	_id: { $ne: [userId] },
   }
})
```
This should return all of the users except for the one with an _id that equals `userId`, but instead it returns every user including that one. I'm guessing the error is somewhere in the before hook but I'm not sure what I'm doing wrong. Any help?

**Comment by daffl** [comment]
[$ne](https://docs.feathersjs.com/api/databases/querying.html#ne) does not take an array, it just takes a single element.

If you want to check multiple use [$nin](https://docs.feathersjs.com/api/databases/querying.html#in-nin).

**Comment by EliSadaka** [comment]
Thanks, that fixed it.

Another query I'm having the same problem with is this one:

```
chatrooms.find({
   query: {
	roomMembers: {
	   $in: [userId]
	}
   }
})
```
`roomMembers` is an array of ids and I'm trying to retrieve all the chatrooms that have `userId` in its array of `roomMembers`, but my query isn't returning any results.

Instead of manually converting every id to ObjectId for queries, is there a way to initialize a service so that the id is a string?

**Comment by daffl** [comment]
Have a look at the [MongoDB array query operators](https://docs.mongodb.com/manual/reference/operator/query-array/). What you are looking for is probably `$elemMatch` (`$in` is not for querying in an array but a single value against a list of possible values).

MongoDB always requires to for query parameters to be of the same type since it does not have a schema. [Mongoose](https://github.com/feathersjs-ecosystem/feathers-mongoose) includes schema definitions and will do the conversion for you.

**Comment by EliSadaka** [comment]
Thanks for the help. Looks like this works fine as long as I manually specify to have roomMembers converted to ObjectId in the before find hook:

```
chatrooms.find({
   query: {
	roomMembers: userId,
   }
})
```

```
const ObjectID = require('mongodb').ObjectID;

module.exports = function (options = {}) {
  return async context => {
    const { query = {} } = context.params;

    if (query.roomMembers) {
        if(typeof query.roomMembers === 'string') {
           query.roomMembers = ObjectID(query.roomMembers);
        }
    }

    context.params.query = query;
    return Promise.resolve(context);
  }
};
```
