### ISSUE TITLE
[suggestion] Channels API join/leave might be confusing

### ISSUE THREAD

**Issue by beeplin** [feathersjs/feathers#859]
This might not be a big issue but I found the naming of channels API is somehow confusing: My understanding is: 

connections join/leave channels;
channels add/remove connections

However the current API says `channel('name').join(connection)`  `channel('name').leave(connection)`

I know it's impossible to roughly replace the API, but it would be super nice to have an pair of aliases like `add/remove`.

**Comment by daffl** [comment]
That is a good point, I am just hesitant to add method aliases since it turned out that they can be just as confusing (people don't read the documentation and will keep asking what the difference is).

**Comment by daffl** [comment]
Thanks again for the suggestion @beeplin. I'm going to close the issue since currently Feathers core does not contain any aliases and I'd like to try and keep it that way and I don't think it is major enough to justify a breaking API change.
