### ISSUE TITLE
Writing tests for unauthenticated users / remote service calls

### ISSUE THREAD

**Issue by jakobrosenberg** [feathersjs/feathers#860]
I can fake a user with ``{ params: { user } }``, but how do I fake a guest?

I can omit the user, but then it's just a server call.

Is it possible to fake the origin of a service call?

**Comment by daffl** [comment]
External calls are indicated by [params.provider](https://docs.feathersjs.com/api/hooks.html#contextparams). So `{ params: { provider: 'test' } }` will indicate an external call.
