### ISSUE TITLE
Official way to access Feathers app externally

### ISSUE THREAD

**Issue by kokujin** [feathersjs/feathers#861]
I have a legacy Expresse application that would need to access a feathers based application API. At the moment, I am doing something like this:

```````
var apiApp = require("./../api/src/app");
var usersService = apiApp.service('users');
```````

This works, but I suspect it might not be the proper way, is there any information on this? Thanks

**Comment by kokujin** [comment]
I had expected that there was an official way that included importing and initializing feathers based on the config data from the Feathers API application. Thanks!

**Comment by daffl** [comment]
That is already done as long as you set the proper `NODE_ENV`.

**Comment by kokujin** [comment]
HI @daffl, I#m having problems with my imported Feathers API. I am seeing "missing dbpath'(NEDB) errors , empty queries that are fine when executed on the Feathers API server. IS there something I have missed? What did you mean by setting the proper NODE_ENV? I am just calling "npm start" with defaults except a different port. Thanks

**Comment by kokujin** [comment]
This is how I am importing the Feathers app.
```````
if (config.get('useapi')) {
    var apiApp = require(config.get('apipath'));
    var usersService = apiApp.service('users');

    usersService.find({})
        .then(function (results) {
            console.log('results ', results); // <-- TEST, results is an empty array
        });
    app.set('usersService', usersService);
}

**Comment by daffl** [comment]
You should run it from the same folder as the app, otherwise you will have to set the [NODE_CONFIG_DIR](https://github.com/lorenwest/node-config/wiki/Environment-Variables#node_config_dir) to load point to the folder with the correct configuration.

**Comment by kokujin** [comment]
Thanks
