### ISSUE TITLE
It is not possible to use a Symbol as a property key on a service.

### ISSUE THREAD

**Issue by bertho-zero** [feathersjs/feathers#863]
### Steps to reproduce

```js
const feathers = require('@feathersjs/feathers');
const prop = Symbol('test-it');

const app = feathers()
  .use('users', {
    create() {},
    [prop]: 'ok'
  });

const service = app.service('users')
console.log(service[prop]); // undefined
// should be 'ok'
```

### Expected behavior
It should be possible to recover a value with a Symbol key.

### Actual behavior
The key disappears.

### System configuration

**Module versions** (especially the part that's not working):
`@feathersjs/feathers@^3.1.4`

**NodeJS version**:
v8.11.1

**Operating System**:
Ubuntu 16.04

**Comment by daffl** [comment]
It's because `Object.getOwnPropertyNames` does not include symbols (which is happening at https://github.com/daffl/uberproto/blob/master/lib/proto.js#L81).

**Comment by daffl** [comment]
Closed via https://github.com/feathersjs/feathers/pull/880, https://github.com/daffl/uberproto/pull/13 and https://github.com/feathersjs/feathers/pull/881
