### ISSUE TITLE
authenticate('jwt') hook doesn't throw 401 unauthorized if user not found

### ISSUE THREAD

**Issue by taras-d** [feathersjs/feathers#869]
### Steps to reproduce
1. Create app + authentication with sequelize adapter
2. Create service (e.g. /messages) which requires authentication - `authenticate('jwt')`
3. Create user (POST /users) and authenticate him (POST /authentication) to get auth token
4. Try to get messages with auth token in header (GET /messages) - everything is ok
5. Remove user from database and perform step 4 - **request succeed although user doesn't exist**

### Expected behavior
I expect that in step **5** `authenticate('jwt')` will throw 401 unauthorized if user not found in database

### Actual behavior
`authenticate('jwt')` doesn't check if user actually exist in database

### System configuration

**Module versions** (especially the part that's not working):
```json
    "@feathersjs/authentication": "^2.0.1",
    "@feathersjs/authentication-jwt": "^1.0.1",
    "@feathersjs/authentication-local": "^1.0.1",
    "@feathersjs/feathers": "^3.1.5",
    "feathers-sequelize": "^2.4.0",
    "sequelize": "^4.32.7"
```

**NodeJS version**: 8.11.1

**Comment by ibrahimyu** [comment]
I think this is not a bug, `authenticate('jwt')` only needs to check token's validity, not to check user's existence in database. You can't get that token without a valid user, and that token will only valid for 1 day. So if you delete the user from database, that user can't renew that token on the next day.

If for some reason you really need to check user's existence in database, you might want to write a before hook:

```
async verifyUserExists => {
  return async context => {
   let user = await context.app.service('users').get(context.user.id)
   if (!user) {
    throw new Error('User not exist.')
   }
  }
}
```

**Comment by taras-d** [comment]
@ibrahimyu thanks for the response.

I already found solution. I can [customize JWT verifier](https://docs.feathersjs.com/api/authentication/jwt.html#verifier) and in case of user doesn't exist throw 401.
