### ISSUE TITLE
Distinct in mongodb

### ISSUE THREAD

**Issue by nexequ** [feathersjs/feathers#870]
### Steps to reproduce
None
### Expected behavior
It should be possible to select distinct

### Actual behavior
None

So how to find distinct with mongodb like in mongodb documentation:
db.collection.distinct()

**Comment by nexequ** [comment]
I like the idea of feathers, but without reasonable documentation, creating REST service can take months, not days.

Probably I've got wrong link, because there is nothing about creating custom service methods in there.

Also I done it like that in users.hooks.js:
`
async function buildCustomQuery(context) {
  const { params, service } = context;

      if (isDistinctQuery(params.query)) {
        context.result = await service.Model.distinct();
      }

      return context
}
module.exports = {
  before: {
    all: [],
    find: [
      buildCustomQuery,
      authentication.hooks.authenticate('jwt')
    ]
`

An error I get:
"isDistinctQuery is not defined".

**Comment by daffl** [comment]
If that is a problem, it is likely that you didn't read the [basics guide](https://docs.feathersjs.com/guides/basics/readme.html) which covers both, the service concept and how hooks work fairly thoroughly. The pre-built database adapters cover the 90% use case and the generator can get you up and running quickly but that does not mean understanding how it all fits together isn't necessary.

**Comment by nexequ** [comment]
Actaully, I read all documentation. But it lacks in some cases. Could you provide working examples of extending services and hooks in documentation?

**Comment by daffl** [comment]
There is some documentation in the [Extending Adapters](https://docs.feathersjs.com/api/databases/common.html#extending-adapters) chapter of the [Common API documentation](https://docs.feathersjs.com/api/databases/common.html).

**Comment by nexequ** [comment]
OK, you are right. I will read documentation again. 

But actually, why not extend documentation with my case? I guess that it would be helpful for rest of newbies like me.

In my users collection I've got column with array of tags:

Now my problem evolved:

```
async function buildWithDistinct(context) {
  const { params, service } = context;

      if (params.query.$distinct) {
        context.result = await service.Model.distinct("tags");
      }

      return context
}
module.exports = {
  before: {
    all: [],
    find: [
      buildWithDistinct,
      authentication.hooks.authenticate('jwt')
    ],
```

context.result contains array with object with each letter separated like that:
```
0: Object […]
​​
0: "o"
​​
1: "k"
​​
2: "o"
​​
__proto__: Object { … }
​
1: Object […]
​​
0: "t"
​​
1: "e"
​​
2: "s"
​​
3: "t"
```

Why tags are splited for letters?

Also is my code right at this moment?

**Comment by daffl** [comment]
That is true, I was thinking of writing up potentially a blog post that expands on using models a little more. Your code looks right but there are two things to look out for:

1) What does `.distinct()` return? Does it have to be converted somehow to work well with `JSON.stringify`?
2) Are you using any `after` hooks? Some pre-built hooks expect the data to be either an array or the [Feathers page format](https://docs.feathersjs.com/api/databases/common.html#pagination)
