### ISSUE TITLE
Adding hook to Users service does not show method selection

### ISSUE THREAD

**Issue by puredevotion** [feathersjs/feathers#871]
I'm trying to create the gravatar hook for the user service by following the step from section 3.3 of the getting-started tutorial, but after specifying the service, I don't get the option to select a method as detailed in the tutorial. It does create the files as expected. 
I tried using the `yo feathers:hook` command, but same result: everything works as expected except for the method selection.

I'm running OSX, npm 5.6.0 node 8.11.2
featherjs/feathers 3.15
featherjs/cli 3.6.3
generator-feathers 2.4.3
genrator-feathers-plugin 1.0.0

**Comment by daffl** [comment]
As the hint text mentions, you have to confirm the service selection with the __Space__ key _before_ pressing enter:

<img width="653" alt="screen shot 2018-05-21 at 9 33 53 am" src="https://user-images.githubusercontent.com/338316/40318632-1aefc816-5cda-11e8-8b72-08b9383b001c.png">

**Comment by puredevotion** [comment]
I'm so sorry for reading over this! 
i've been searching for 20 mins or so into google, trying to fix all kinds of things (a.o. npm issues, unrelated apparently, when trying to run yo feathers:hook), before posting. 

Sorry for wasting your time!

**Comment by daffl** [comment]
This was a legit problem. It was pretty easy to just skip it without selecting anything. The latest version of `@feathersjs/cli` will now complain if you don't select a service.
