### ISSUE TITLE
doubt about service / hooks

### ISSUE THREAD

**Issue by bilicio** [feathersjs/feathers#873]
Hi guys!

Im creating my own mail service with node mailer.
Everything is working fine, my only problem is that my hooks (after) is executing before my email is sended.

My service is built around the sendmail.class.js created by the frame work.
here is the snipped:

# sendmail.class.js
...
async create (data, params) {
    
    asyncMail(data, function(err,data){
      console.log('ASYNC: ' + data);
    });

    return data;
  }
...

--------------------------------------------------------------------

# sendmail.service.js
...
const service = app.service('sendmail').hooks({
    after: {
      create: [
        async function(context) {
          console.log("HOOK HERE: ", context.result);
          return context;
        }
      ]
    }
  });
...

--------------------------------------------------------------------

when i make a postman request the hook came with the console.log(HOOK HERE) and 4 seconds later my  function asyncMail came with the log (ASYNC).

How do i set the async create function to wait for the asyncMail to finish and then send the message for the hook to realize and dispatch the after hook method? 

by the way, is there any place like a community where i can ask this doubts about the framework? or here is the only option?

thank you!

**Comment by daffl** [comment]
Have a look at [JavaScript promises](https://developers.google.com/web/fundamentals/primers/promises) and how [async/await works](https://javascript.info/async-await). Because your mail function takes a callback you have to turn it into a promise:

```js
create (data, params) {
  return new Promise((resolve, reject) => {
    asyncMail(data, (err, data) => {
      if(err) {
        reject(err);
      } else {
        resolve(data)'
      }
    });
  });
}
```

[feathers-mailer](https://github.com/feathersjs-ecosystem/feathers-mailer) takes care of most of that for you already.

**Comment by bilicio** [comment]
great @daffl ! thank you! im pretty new to react/redux/feathersjs. but im running against the time to study and get the most of every functionality. feathersjs is amazing! i will look into it know and how works!
