### ISSUE TITLE
Authentication error with Sequelize; Invalid login

### ISSUE THREAD

**Issue by pawelsas** [feathersjs/feathers#876]
### Steps to reproduce

I tried to reproduce the authentication guide using Sequelize instead of NeDB.
I changed the user data model to following:

```
// See http://docs.sequelizejs.com/en/latest/docs/models-definition/
// for more of what you can do here.
const Sequelize = require('sequelize');
const DataTypes = Sequelize.DataTypes;

module.exports = function (app) {
  const sequelizeClient = app.get('sequelizeClient');
  const user = sequelizeClient.define('user', {
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true
    },
    email: {
      type: DataTypes.STRING,
      unique: true,
      allowNull: false
    },
    password: {
      type: DataTypes.STRING,
      allowNull: false
    }
  }, {
    hooks: {
      beforeCount(options) {
        options.raw = true;
      }
    }
  });

  // eslint-disable-next-line no-unused-vars
  user.associate = function (models) {
    // Define associations here
    // See http://docs.sequelizejs.com/en/latest/docs/associations/
  };

  return user;
};

```
Furthermore set the sync option for Sequelize to { force: true }.

### Expected behavior
A POST to http://localhost:3030/authentication passing correct email and password should return 200 and the token.

### Actual behavior
Code 401, name: "NotAuthenticated" and message: "Invalid login" is returned. 
The passed credentials are correct.

### System configuration

**Module versions** (especially the part that's not working):
 ```
"dependencies": {
    "@feathersjs/authentication": "^2.1.1",
    "@feathersjs/authentication-jwt": "^1.0.2",
    "@feathersjs/authentication-local": "^1.0.4",
    "@feathersjs/configuration": "^1.0.2",
    "@feathersjs/errors": "^3.2.1",
    "@feathersjs/express": "^1.1.2",
    "@feathersjs/feathers": "^3.0.5",
    "@feathersjs/socketio": "^3.0.2",
    "compression": "^1.7.2",
    "cors": "^2.8.4",
    "feathers-sequelize": "^3.1.0",
    "helmet": "^3.9.0",
    "pg": "^7.4.3",
    "sequelize": "^4.37.10",
    "serve-favicon": "^2.4.5",
    "winston": "^2.4.0"
  },
  "devDependencies": {
    "eslint": "^4.19.1",
    "mocha": "^4.1.0",
    "request": "^2.85.0",
    "request-promise": "^4.2.2"
  }
```

**NodeJS version**:
8.5.0

**Operating System**:
Mac OS

**Browser Version**:
current

**Comment by daffl** [comment]
I just generated a new application with Sequelize and PostgreSQL and could not reproduce the issue. I would double check that

- The database has been created
- The database connection has been established successfully (this is the most likely cause of the problem)
- The user you are trying to authenticate has been created
- You are passing `"strategy": "local"` in the `/authentication` call

**Comment by pawelsas** [comment]
The latter was the case.
Thanks!
