### ISSUE TITLE
custom_id is null in result

### ISSUE THREAD

**Issue by musicformellons** [feathersjs/feathers#877]
I am on buzzard and have a photos table in postgres using sequelize. When I create a photo (photo_id, user_id, url) I get as a result the correct user_id and url, but the photo_id is null. When I check in postgres I see the entry has a proper photo_id. What is wrong, i.e. why do I not receive the photo_id?

I think I setup the custom id properly in the service:
```
  const options = {
    name: 'photos',
    id: 'photo_id',
    Model,
    paginate
  };
```

**Comment by daffl** [comment]
The first calls [Sequelize Model.bulkCreate](https://github.com/feathersjs-ecosystem/feathers-sequelize/blob/master/lib/index.js#L155) which should work. Maybe you can open another issue in [feathers-sequelize](https://github.com/feathersjs-ecosystem/feathers-sequelize) with a complete example (based on the [readme example](https://github.com/feathersjs-ecosystem/feathers-sequelize#example)) that doesn't work.
