### ISSUE TITLE
ManyToMany with sequelize

### ISSUE THREAD

**Issue by nexequ** [feathersjs/feathers#879]
### Steps to reproduce

I guess, that manyToMany relationship through sequelize doesn't work.

### Expected behavior

I'm trying to save posts with tags throught table posts_tags.

Tags should be created if they not exists, and then relation should be saved to posts_tags.

### Actual behavior

For instance, I'm getting error that addTag is not a function.

With sequelize docs (http://docs.sequelizejs.com/manual/tutorial/associations.html) during making association like that:

```
tags.associate = function (models) {
    // Define associations here
    tags.belongsToMany(models.posts, {as: 'tags', through: 'posts_tags'});
    // See http://docs.sequelizejs.com/en/latest/docs/associations/
  };
```

```
posts.associate = function (models) {
    posts.belongsToMany(models.tags, {as: 'posts', through: 'posts_tags'});
  };
```

Later on I should have method like addTag added to tags, but I've got undefined.

```
const tags = hook.app.services.tags.Model;
tags.addTag({name: "testtag" })
```

Am I doing somewith wrong? Or mayby it's not possible to save associations with feathers and sequelize and I should do everything from scratch?

If it's possible to save assocations with different way, please share an example.

**Comment by daffl** [comment]
`.associate` will be called during `app.setup` (or `app.listen`). Those methods will only be available once the application is running.

**Comment by nexequ** [comment]
So I should get those methods only on client side? On client side I've got:
`this.$feathers.service(...).addTag is not a function`

With calling it like that:
`this.$feathers.service('posts').addTag({ name: "test"})`

Am I doing something wrong?

Maybe there is another method to save associations?

**Comment by daffl** [comment]
Those methods can not be used on the client, it has to be implemented in hooks on the server [see here how to interact with Sequelize](https://github.com/feathersjs-ecosystem/feathers-sequelize#setting-paramssequelizeinclude).

You can also use these methods in your own [custom service](https://docs.feathersjs.com/guides/basics/services.html). There already is a further discussion about relationship in https://github.com/feathersjs-ecosystem/feathers-sequelize/issues/211

**Comment by nexequ** [comment]
I get it. What you think to mention about that in documentation?

**Comment by nexequ** [comment]
Unfortunately, even in after hook method like addTag or addTags is not a function.

**Comment by daffl** [comment]
You also have to set [`raw: false`](https://github.com/feathersjs-ecosystem/feathers-sequelize#sequelize-raw-queries)

**Comment by nexequ** [comment]
Raw is set to false actually.

**Comment by daffl** [comment]
If `raw` is false you should definitely get an instance of a Sequelize model in an `after` hook.

**Comment by daffl** [comment]
You may have to access the instances in the `data` array if you are using `find`. Closing since I think this should solve it.
