### ISSUE TITLE
Unable to  change the usernameField while using basic auth

### ISSUE THREAD

**Issue by rishavs** [feathersjs/feathers#883]
Hi. I want to change the default username field for my local auth from `email` to `username`. 
So, I tried making a few changes in some logical places.

In Config> default.json, I changed
```
"local": {
      "entity": "user",
      "usernameField": "username",
      "passwordField": "password"
    }
```
and in users.model.js, I changed the model to;
```
table.increments('id');
table.string('username').unique();
table.string('name');
table.string('email');
table.string('password');
```
however, now when I try to authenticate with
```
{ 
    "strategy": "local", 
    "username": "eve", 
    "password": "p@ssword" 
}
```
I get the error in reply;
```
{
    "name": "BadRequest",
    "message": "Missing credentials",
    "code": 400,
    "className": "bad-request",
    "data": {
        "message": "Missing credentials"
    },
    "errors": {}
}
```

As suggested in the chat, i tried to remove `entity` in the config default.json to;
```
In Config> default.json, I changed
```
"local": {
      "usernameField": "username",
      "passwordField": "password"
    }
```
Unfortunately that didnt help either. It seems that either the defaults in auth-local package are not getting overwritten or I am missing some more places where in to make the changes.

**Comment by daffl** [comment]
On Windows systems `username` will be replaced with the `username` environment variable in the configuration. To get the actual value it has to be escaped (see https://github.com/feathersjs/configuration/issues/58):

```js
 local: {
      entity: 'user',
      usernameField: '\\userName',
      passwordField: 'password'
  }
```
