### ISSUE TITLE
context.params.provider bug

### ISSUE THREAD

**Issue by sxwebdev** [feathersjs/feathers#884]
When a client makes a request to the server via rest or socketio, `context.params.connection` contains the correct value of provider. `context.params.provider` contains an invalid value and = undefined.

Full description and example you can see here [https://github.com/feathers-plus/feathers-hooks-common/issues/398](https://github.com/feathers-plus/feathers-hooks-common/issues/398)

this hook can fix it:

```js
hook => { hook.provider = hook.params.connection ? hook.params.connection.provider : hook.params.provider}
```

```
"@feathersjs/configuration": "^1.0.2"
"@feathersjs/errors": "^3.3.0"
"@feathersjs/express": "^1.2.3"
"@feathersjs/feathers": "^3.1.6"
"@feathersjs/socketio": "^3.2.2"
````

**Comment by daffl** [comment]
Can you please provide a minimal breaking example. It seems very unlikely this is happening in a standard setup and I am not able to reproduce this using the [feathers-chat](https://github.com/feathersjs/feathers-chat).
