### ISSUE TITLE
Noisy Error reporting

### ISSUE THREAD

**Issue by MartinBucko** [feathersjs/feathers#887]
### Steps to reproduce

After `npm update` it show in error report lot of code. Its to noisy and i have always problem spot the error cause.

https://gist.github.com/MartinBucko/82c91b7a35b63f8e260a52e07ee799d3

It happen only on local development mode and in production too and sorry i don't have public repo for this project...

### Expected behavior

Shold not contain code preview in context error.

### System configuration

OS Linux Ubuntu 

**Module versions** (especially the part that's not working):

in gits link..

**NodeJS version**:

v8.11.1

**Operating System**:

LSB Version:    core-9.20160110ubuntu5-amd64:core-9.20160110ubuntu5-noarch:security-9.20160110ubuntu5-amd64:security-9.20160110ubuntu5-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 17.10
Release:        17.10
Codename:       artful

**Comment by daffl** [comment]
This is probably because of the latest version of Winston. Change `logger.error(context.error)` to `logger.error(context.error.stack)` in the logger file.

**Comment by dottodot** [comment]
I'm still having this issue even though I'm using `context.error.stack`. Is there anyway to identify what's causing and struggling to find the issue.

**Comment by MartinBucko** [comment]
@dottodot i generate new dummy project and replace logging thinks in my old app from this dummy project. That help mi fix that.

**Comment by daffl** [comment]
The pull request at https://github.com/feathersjs/feathers-chat/pull/97 shows how to update to the newest version of Winston manually.
