### ISSUE TITLE
Error when using in react native on android

### ISSUE THREAD

**Issue by chris-me** [feathersjs/feathers#888]
I get the following error on Android when trying to use feathers via react-native:

![screenshot](https://user-images.githubusercontent.com/3713630/41497931-560861ac-7160-11e8-987e-ff58f4cc5e41.jpg)

### Steps to reproduce

* create a new project via expo client or create-react-native-app (had the issue in both)
* add the example code from https://docs.feathersjs.com/api/client.html#react-native
* trying to paste the example code line by line works until pasting this line:

```javascript
const messageService = client.service('messages');
```

Tested this with two android devices and react-native on Windows 10 and Ubuntu 18.04. I'm not sure if I'm doing anything wrong here or if it's an issue with feathers at all but this would be my first stop for asking for help with this.

Additionally, there are no issues running the code on iOS.

I've also set up an example repository to reproduce the issue [here](https://github.com/chris-me/react-native-feathers)

**Comment by daffl** [comment]
Fixed in v3.1.6

**Comment by chris-me** [comment]
Confirmed it works now. Thanks!
