### ISSUE TITLE
Listen On Custom Route

### ISSUE THREAD

**Issue by Crackz** [feathersjs/feathers#890]
how would i listen on custom route like /workers/:id/orders 

Order Model: {
  worker,
  customer,
   text
}

and emit events to only related worker and customer

here is a [full example](https://github.com/Crackz/test-feathers)

**Comment by daffl** [comment]
Unfortunately this is not possible at the moment. Events are only being dispatched on the "real" service name (`workers/:id/orders` in your case).

**Comment by Crackz** [comment]
i have managed to make it  by using custom route for my http requests ( [Feathers FAQ Custom Route](https://docs.feathersjs.com/faq/readme.html#how-do-i-do-nested-or-custom-routes) )
and listening to real/parent Service for any changes 
which emits to related customer and worker only

Thanks for your great effort
