### ISSUE TITLE
querying null values 

### ISSUE THREAD

**Issue by moayadnajd** [feathersjs/feathers#894]
Sorry if my question is stupid but i am new to feathers 

I'am trying to get users where there phone number is null

`GET /users?phone=null` this is not working 

 so what is the best way to do this ?

Thanks

**Comment by bertho-zero** [comment]
Query is always a string, so you have to coerce this.

**Comment by eddyystop** [comment]
Look at the first example here https://feathers-plus.github.io/v1/feathers-hooks-common/#traverse

**Comment by daffl** [comment]
That's definitely the way to go. For reference here is how it could be done in a plain hook:

```js
app.service('myservice').hooks({
  before: {
    find(context) {
      const { params: { query = {} } } = context;

      if(query.phone === 'null') {
        query.phone = null;
      }

      context.params.query = query;

      return context;
    }
  }
});
```
