### ISSUE TITLE
Another database service

### ISSUE THREAD

**Issue by bilicio** [feathersjs/feathers#896]
@daffl  Do you have plans to include Pouchdb as a service on feathersjs? if not, could you recommend a database service with local offline and online synchronization?

thank you!

**Comment by daffl** [comment]
There are no plans to add any other databases at the moment unless someone decides to contribute and maintain them (as has happened with [feathers-elasticsearch](https://github.com/feathersjs-ecosystem/feathers-elasticsearch)).

Implementing other databases is fairly straightforward using [a custom service](https://docs.feathersjs.com/api/services.html). There are several [community provided database adapters](https://github.com/feathersjs/awesome-feathersjs#database) and there is also a [feathers-pouchdb](https://github.com/endyjasmi/feathers-pouchdb) project. You can either contribute to it or start your own Feathers plugin with `feathers generate plugin`. The reference implementation for database adapters to get an idea where to start is [feathers-memory](https://github.com/feathersjs-ecosystem/feathers-memory).

**Comment by bilicio** [comment]
Alright! i will do that! thank you! :)

**Comment by daffl** [comment]
For future reference, I added an [FAQ about new database adapters](https://docs.feathersjs.com/faq/readme.html#can-you-support-another-database).
