### ISSUE TITLE
Support for Prisma ORM

### ISSUE THREAD

**Issue by gijo-varghese** [feathersjs/feathers#897]
Quite recently Prisma was open sourced with an automatic Graphql server generator and an ORM (https://www.prisma.io/). 

Is it possible to use Prisma with Feathers as an ORM?

**Comment by daffl** [comment]
Similar to what I mentioned in #896, Feathers works with any database and ORM by implementing a custom service. This is covered fairly extensively in the [basics guide](https://docs.feathersjs.com/guides/basics/readme.html) and the [services API](https://docs.feathersjs.com/api/services.html).

New database adapters have to be community contributions. There are several [community provided database adapters](https://github.com/feathersjs/awesome-feathersjs#database) that can be used as a reference. You can start your own Feathers plugin with `feathers generate plugin` and the reference implementation for "official" database adapters is [feathers-memory](https://github.com/feathersjs-ecosystem/feathers-memory).

**Comment by gijo-varghese** [comment]
Cool. Thanks

**Comment by daffl** [comment]
For future reference, I added an [FAQ about new database adapters](https://docs.feathersjs.com/faq/readme.html#can-you-support-another-database).
