### ISSUE TITLE
Simulating "groupBy" queries

### ISSUE THREAD

**Issue by kokujin** [feathersjs/feathers#900]
Is there some way to simulate groupBy queries generically for all adapters? Thanks

**Comment by daffl** [comment]
Since some databases (like NeDB) don't support grouping, there is no common functionality for this. For other databases it can be accomplished with the database specific parameters (e.g. [params.sequelize](https://github.com/feathersjs-ecosystem/feathers-sequelize#paramssequelize)) for Sequelize).

**Comment by daffl** [comment]
Also related:

- For MongoDB: https://github.com/feathersjs-ecosystem/feathers-mongodb/issues/114
- For Mongoose: https://github.com/feathersjs-ecosystem/feathers-mongoose/issues/212
