### ISSUE TITLE
new database adaptor

### ISSUE THREAD

**Issue by HosseinAlipour** [feathersjs/feathers#902]
I need MySQL DevApi adaptor for Feathersjs, where do I Start to make a storage adaptor for this?

**Comment by daffl** [comment]
A lot of it is covered already in the [basics guide](https://docs.feathersjs.com/guides/basics/readme.html). Generate a [custom service](https://docs.feathersjs.com/guides/basics/services.html) ([API](https://docs.feathersjs.com/api/services.html)) and write your database queries just like you would with any other framework.

Please also see https://github.com/feathersjs/feathers/issues/897 or https://github.com/feathersjs/feathers/issues/896.

**Comment by daffl** [comment]
For future reference, I added an [FAQ about new database adapters](https://docs.feathersjs.com/faq/readme.html#can-you-support-another-database).
