### ISSUE TITLE
Generating a service to get all models.

### ISSUE THREAD

**Issue by shomalgan** [feathersjs/feathers#903]
How can i return a list of all models object within a custom service?

```
class Service {
    constructor(options) {
        this.options = options || {};
    }
    async find(params) {
        return [...myModels];
    }

```

**Comment by daffl** [comment]
You can get a list of all services by going through [app.services](https://docs.feathersjs.com/api/application.html#services) where the `app` object can be obtained through [service.setup](https://docs.feathersjs.com/api/services.html#setupapp-path):

```js
class Service {
  constructor(options) {
    this.options = options || {};
  }

  async find(params) {
    const paths = Object.keys(this.app.services);

    path.forEach(path => {
      const { Model } = app.service(path);

      if(Model) {
        // do something with model here
      }
    });
  }

  setup(app) {
    this.app = app;
  }
}
```

Now the question would be what you mean by returning those models. A serialized version of them will probably not contain much useful information for a client.
What should those models contain? I would

**Comment by daffl** [comment]
Ah, makes sense. I think the example above should give you everything you need then. Good luck 😄

**Comment by shomalgan** [comment]
Finally, I made my custom-service in this way, now it works only with PostgreSQL, but works!


```
  async find(params) {
    const services = { ...this.app.services };
    const sequelize = this.app.get("sequelizeClient");
    await sequelize
      .query(
        "select * from information_schema.columns WHERE table_schema='public' AND  table_catalog='blog'"
      )
      .then(function(rows) {

```
with the schema, I retrieved from DB and name of services, I made this object
![image](https://user-images.githubusercontent.com/2883620/44382696-3e2b4500-a52b-11e8-93cb-570cc174e7e9.png)

to be honest, I don't like this way! but did not find a better way.
