### ISSUE TITLE
Does feathersjs support websocket without using any frameworks?

### ISSUE THREAD

**Issue by ShawTim** [feathersjs/feathers#905]
I have a Feathersjs application and I want to expose a websocket interface `ws://mydomain/ws` sth like that. And then any clients can connect the websocket interface with their favourite way. Just like what we do for REST: clients can use any REST lib to connect.

Currently Feathersjs support Socket.io and Primus. However, it seems that you must use their own client to connect to the websocket service (or implement by your own):
- https://github.com/primus/primus/issues/309#issuecomment-61714669
- https://stackoverflow.com/questions/46854733/can-a-socket-io-server-communicate-with-a-non-socket-io-client

Is it possible to configure Feathersjs to expose a websocket interface which based on websocket protocol only without requiring any framework dependency on client-side? (can still apply framework on server-side though)

**Comment by daffl** [comment]
Although Feathers does support adapting to different transport mechanisms currently only Express, Socket.io and Primus transports exist. https://github.com/feathersjs/feathers/issues/840 discusses how an adapter for MQTT could be implemented which I think would probably look very similar to plain websocket usage. My personal priorities currently are a transport that uses HTTP/HTTP2 directly without a framework in between and MQTT. Other transports need to be championed by someone else.

When it comes to connecting to an existing Socket.io server, you could also look at how some of the Socket.io adapters for other languages are implement, e.g. [socket.io-client-java](https://github.com/socketio/socket.io-client-java).

**Comment by daffl** [comment]
I'm suspecting that there is a reason that pretty much all websocket libraries require their own client because there are a lot of things on low level websockets that need to be taken care of manually (reconnects, keep-alive, browser inconsistencies etc.). Going to close this since I think there is more value in implementing other transports like MQTT but I'm happy to help if anybody is interested in taking this on.
