### ISSUE TITLE
BelongsToMany associations in after/before hooks

### ISSUE THREAD

**Issue by lozah** [feathersjs/feathers#908]
Hi,

I'm trying to make a many to many relation working with feathers.
An user has channels and a channel has users.

Models are well defined, when I log my channel's properties I got as expected the generated methods from the belongsToMany association : 

```[ 'constructor',
  '_customGetters',
  '_customSetters',
  'validators',
  '_hasCustomGetters',
  '_hasCustomSetters',
  'id',
  'name',
  'createdAt',
  'updatedAt',
  'rawAttributes',
  'attributes',
  '_isAttribute',
  'getUsers',
  'countUsers',
  'hasUser',
  'hasUsers',
  'setUsers',
  'addUser',
  'addUsers',
  'removeUser',
  'removeUsers',
  'createUser',
  'getMessages',
  'countMessages',
  'hasMessage',
  'hasMessages',
  'setMessages',
  'addMessage',
  'addMessages',
  'removeMessage',
  'removeMessages',
  'createMessage' ]
```

My first wish was to associate users to channel after channel creation.

So what I did was creating an after hook on the create method, then getting result object from context and finally calling the addUsers method on result.

But this didn't work and the only response i got was : 
`result.addUsers is not a function`

result's properties : 

`[ 'id', 'name', 'updatedAt', 'createdAt' ]`

Why result is not an instance of the channel class ? 
I know in javascript object casting doesn't exist so how should I proceed to access these methods ? 

Thank you ! :)

**Comment by daffl** [comment]
If you want model properties the [`raw` service option](https://github.com/feathersjs-ecosystem/feathers-sequelize#sequelize-raw-queries) has to be set to `false`

**Comment by lozah** [comment]
Thank you for your answer.

I've already tried setting raw option to false in both my models user and channel but it didn't change anything.

**BUT !!** It works like a charm using hydrate after hook, thank you for your link that made me discover about it.
