### ISSUE TITLE
FeathersJs Not Parsing JSON Properly

### ISSUE THREAD

**Issue by lajap** [feathersjs/feathers#910]
### FeathersJs Not Parsing JSON Properly

I followed the chat tutorial to get me started with feathers, but it's not posting properly.
After creating the message service, I posted `{ "name": "Curler", "text": "Hello from the command line!" }` to `http://localhost:3030/messages/` in **Postman**. 

Result: 
```
{
    "_id": "cWoiNwyGNiXhHKRg"
}
```

I made a get call to `http://localhost:3030/messages/`
Result:
```
{
    "total": 1,
    "limit": 10,
    "skip": 0,
    "data": [
        {
            "_id": "cWoiNwyGNiXhHKRg"
        }
    ]
}
```

**I thought the result is meant to be something like this:**
```
{
    "total": 1,
    "limit": 10,
    "skip": 0,
    "data": [
        {
            "_id": "cWoiNwyGNiXhHKRg",
            "name": "Curler", 
            "text": "Hello from the command line!"
        }
    ]
}
```

**Comment by daffl** [comment]
You have to set the `Content-Type` header to `application/json` as it is shown in [the linked Postman collection](https://app.getpostman.com/run-collection/9668636a9596d1e4a496).

**Comment by lajap** [comment]
Damn I missed that. Thanks.
