### ISSUE TITLE
Serverless documentation

### ISSUE THREAD

**Issue by samuelthompson189** [feathersjs/feathers#911]
Are  there any guides or examples of feathers being used with AWS lamda? I am wanting to go totally serverless but most of the examples and the CLI tool use an  express http server.

Could you point me in the right direction?

Thanks

**Comment by daffl** [comment]
Although it is possible to add other transport mechanisms, currently only Express, Socket.io and Primus are supported. Future plans include direct Node HTTP/HTTP2 and potentially MQTT.

Personally I am not planning on adding support for any proprietary technologies but if that is something you would like to look into, the [code of @feathersjs/express](https://github.com/feathersjs/express) would probably be a good starting point (it's only ~200 lines).

**Comment by leob** [comment]
I think that, using the Serverless framework and using this article as inspiration and as a starting point (it's not about Feathers but about Apollo with Express on top of the Serverless framework) it should be doable to get a basic Feathers app up and running:

https://hackernoon.com/create-a-serverless-graphql-server-using-express-apollo-server-and-aws-lambda-c3850a2092b5

I could give it a shot and play around a bit.

**Comment by banisirohi** [comment]
It's been a while that this thread is open. @leob Were you able to figure out this. Can you please share your understanding on this so far. Thanks!

**Comment by leob** [comment]
@banisirohi Haha okay I totally forgot about this ... no to be honest I didn't dive into it, so I don't have any insights to share, sorry ... I don't really have time to look at it either, busy with a ton of other things. Sorry about that!

**Comment by banisirohi** [comment]
@leob Thanks for responding and sharing those link. Will look through. Cheers

**Comment by daffl** [comment]
I am going to close this issue, since I don't think there will be much further activity. In summary:

- If you are interested in implementing (and maintaining) a serverless transport adapter, please comment here
- If you would like to support development of a serverless transport adapter, you can sign up for a [gold or platinum sponsorship](https://github.com/sponsors/daffl) and contact me directly

**Comment by aka47-24** [comment]
We're interested, and we're already implementing the serverless transport adapter. 
We use [middy.js framework](https://middy.js.org/) as:
- it supports typescript
- It is a "middleware engine" and extensible.
- It's very similar to express.js
- recommended by AWS [here](https://aws.amazon.com/blogs/compute/simplifying-serverless-best-practices-with-aws-lambda-powertools-for-typescript/)

We will contribute to Feathersjs as soon as we solve the key challenges:
key challenges we have:
- The socket.io-client can't connect to the AWS API gateway. We need a WebSocket client.
- Middy doesn't support HTTP and WS at the same time. We need a custom router for it.
- To distribute services between multiple lambda functions we have to emit feathers event on aws Event-Bridge (the most challenging part)
- Handling the setup and teardown cycles in lambda. We need a lambda extension to receive the proper events.
- Possibly a proper build solution is required after all above.

Please share, any related links, issues, and discussions about this and contribution to the project.

**Comment by daffl** [comment]
This sounds great, let me know if you need anything! I've been meaning to put together the tooling for a generic websocket/messaging transport adapter which might help here as well. I'll hopefully get to put a proposal for that together some time this month.
