### ISSUE TITLE
join in services query?

### ISSUE THREAD

**Issue by HosseinAlipour** [feathersjs/feathers#912]
I have read query section in the documentation but a few things probably are missing, for example how do I join a database service together or distinct a field? I'm using sequelize.

**Comment by daffl** [comment]
Please refer to the [associations section of the feathers-sequelize documentation](https://github.com/feathersjs-ecosystem/feathers-sequelize#associations), as well as [this FAQ](https://docs.feathersjs.com/faq/readme.html#how-do-i-do-associations). [Testing sequelize queries in isolation](https://github.com/feathersjs-ecosystem/feathers-sequelize#testing-sequelize-queries-in-isolation) is also relevant.
