### ISSUE TITLE
Allow $populate in params query when Get/Remove

### ISSUE THREAD

**Issue by tissiwb** [feathersjs/feathers#914]
### Steps to reproduce

```
// Client
app.service('tasks').get(id, {
    query: {
      $select: ['name', 'creator_id'],
      $populate: {
        creator: [['name']],
      },
    },
  }).then(result => {
    console.log(result)
})

```

```
// Hook
fastJoin(context => {

    return {
      joins: {
        creator: {
          resolver: $select => {

            let users = context.app.service('users')

            return async task => task.creator = (await users.find({
              query: {
                id: task.creator_id,
                $select: $select,
              },

              paginate: false,

            }))[0]

          },
        },
      },
    }

  }, context => context.params.query.$populate)
```

### Expected behavior
Task name with author name

### Actual behavior
Error `No record found for id '${id}'`

**Comment by daffl** [comment]
I recommend reopening this issue in the https://github.com/feathers-plus/feathers-hooks-common repository.

**Comment by tissiwb** [comment]
@daffl, I just wanted to say that it would be nice if the "get" method had a whitelist of queries starting with "$" (these fields should not be used to filter models by data in fields). Now this method correctly takes only "$select" query.

I use "$populate" for the "fastJoin" hook. This works fine in the "find" method (this method does not use "$populate" to filter models by fields), but in "get" it fails.

Sorry for the level of literacy - the language barrier ._.
