### ISSUE TITLE
[Question] per query update subscriptions

### ISSUE THREAD

**Issue by Johnhhorton** [feathersjs/feathers#916]
I'm looking for a simple framework with support for realtime updates to replace a firebase firestore implementation. I've been searching through docs and issues, but I'm still unclear on this.

Question: It looks like updates are pushed to all users listening on a channel (from what I understand of socket.io). Can/Does FeathersJs push updates for individual queries, or on the model as a whole? I want to make sure that users are only getting updates for the items they're listening to, as well as updates they're allowed to see.

Thanks in advance.

**Comment by daffl** [comment]
Feathers event dispatching on the server is [accomplished through channels](https://docs.feathersjs.com/api/channels.html). It is up to you to decide which connection belongs to a channel or not. You could implement your own subscription mechanism but websocket events are cheap and so far we found it was pretty much always enough to let the client decide if they want to use the data or just ignore it as long as they are allowed to see it at all.

If you are looking for live-updating query streams on the client, have a look at [feathers-reactive](https://github.com/feathersjs-ecosystem/feathers-reactive).
