### ISSUE TITLE
[Question] Feathers + Nuxt

### ISSUE THREAD

**Issue by guzz** [feathersjs/feathers#918]
I'm creating an app that is using feathers and nuxt, but right now my app is separated in 2 reps one for nuxt and one for feathers. They have 2 different endpoints and I'm wondering if that's the best approach.

I see some projects like (https://github.com/silvestreh/feathers-nuxt) that use both on the same repo but I'm not sure which approach to use. I see problems with both:

Using separated repositories I have a problem with my cookieStorage since they are in 2 different subdomains they don't share the same cookies.

Using the same repository nuxt takes control of all the routing for the app, so I can only use socket as communication and I lose all the pre-configured oauth signup from feathers.

Does anyone have thoughts on what is the best approach? 
Thanks for your attention.

**Comment by subodhpareek18** [comment]
I generally use two different servers. One simple one for serving the frontend and then the other one as the regular backend.

I also don't let the frontend directly talk to the backend but use the frontend server to proxy the calls. Also I have mostly used JWTs for auth and not used cookies in general so not sure about that part.

But yes it's totally fine to have separate servers and repos to keep the client and api different.

**Comment by guzz** [comment]
Thanks @subodhpareek18 

I am using JWTs for auth to, but for nuxt I use a library feathers-vuex and it keeps the auth in the client through cookies, I managed to solve the problem authenticating the user every time it refreshes the page and if it has the jwt token stored. That works but I wonder if there is a better way. 

About your proxy, doesn´t it take to much load on your frontend server? Are you making this proxy through socket?

**Comment by microcipcip** [comment]
@guzz I use two servers as well, Nuxt is so slow compiling that it would make the server side work too cumbersome.

**Comment by daffl** [comment]
There is also a new boilerplate at https://github.com/fexell/FeathersJS-NuxtJS. Closing the issue here, I recommend directing other VueJS related questions to https://github.com/feathers-plus/feathers-vuex
