### ISSUE TITLE
Why is internal service call failing without throwing an exception

### ISSUE THREAD

**Issue by nidkil** [feathersjs/feathers#928]
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc. This makes it much easier for us to debug and issues that have a reproducable example will get higher priority.

### Expected behavior
I have the following code and expect it to create a document. Or if it cannot throw an exception and display debugging and logging information (i.e. the call to the log hook).

```
    Object.values(collections).forEach(async collection => {
      if (collection.enabled) {
        let service = app.service(collection.service);
        let params = {};
    
        // Create the collection documents
        collection.data.forEach(async doc => {
          // console.log('item', doc);
    
          if (doc.__userId) {
            const userColl = lookupByField(collections, 'name', 'users')[0];
            const user = lookupByField(userColl, '_id', doc.__userId)[0];
            params = { user: user };
          }
    
          result = await service.create(doc, params).catch(err => console.error(err));
            
          console.log('item', result);
        });  
      }
    });
```

I also have debugging set to DEBUG=*.

### Actual behavior
Tell us what happens instead

When the service.create line is called It fails silently. No exception is thrown and no debugging or logging information is displayed (i.e. the call to the log hook).

When I run the code outside the forEach blok (placing it right beofe the block) it does work, incl. throwing exceptions and logging and debugging is displayed.

```
    const collection = collections[1];
    const doc = collection.data[2];
    let params = {};

    if (doc.__userId) {
      const userColl = lookupByField(collections, 'name', 'users')[0];
      const user = lookupByField(userColl, '_id', doc.__userId)[0];
      params = { user: user };
    }

    result = await service.create(doc, params).catch(err => console.error(err));
      
    console.log('result', result);
```

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

  "dependencies": {
    "@feathersjs/authentication": "^2.1.7",
    "@feathersjs/authentication-jwt": "^2.0.1",
    "@feathersjs/authentication-local": "^1.2.1",
    "@feathersjs/configuration": "^1.0.2",
    "@feathersjs/errors": "^3.3.0",
    "@feathersjs/express": "^1.2.3",
    "@feathersjs/feathers": "^3.1.7",
    "@feathersjs/socketio": "^3.2.2",
    "compression": "^1.7.3",
    "cors": "^2.8.4",
    "feathers-mongoose": "^6.1.2",
    "helmet": "^3.12.1",
    "mongoose": "^5.2.5",
    "serve-favicon": "^2.5.0",
    "underscore": "^1.9.1",
    "winston": "^3.0.0"
  },

**NodeJS version**:

v8.10.0

**Operating System**:

Windows 10

**Browser Version**:

NA

**React Native Version**:

NA

**Module Loader**:

NPM

**Comment by daffl** [comment]
This probably happens because `forEach` won't wait for the asynchronous methods to complete. This can be accomplished using [Array.map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) and [Promise.all](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all):

```js
await Promise.all(Object.values(collections).map(async collection => {
  if (collection.enabled) {
    let service = app.service(collection.service);
    let params = {};

    // Create the collection documents
    await Promise.all(collection.data.map(async doc => {
      // console.log('item', doc);

      if (doc.__userId) {
        const userColl = lookupByField(collections, 'name', 'users')[0];
        const user = lookupByField(userColl, '_id', doc.__userId)[0];
        params = { user: user };
      }

      result = await service.create(doc, params).catch(err => console.error(err));
        
      console.log('item', result);
    }));  
  }
});
```

**Comment by nidkil** [comment]
Thx man! It works now!
