### ISSUE TITLE
Koa style middleware: Hooks for any asynchronous method

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers#932]
Hooks are a powerful way to control the flow of asynchronous methods. Koa popularized a new kind of middleware that allows an even more flexible approach to control this flow. I propose to adapt this pattern as a new `async` hook type.

## Problem

Currently, [Feathers hooks](https://docs.feathersjs.com/api/hooks.html) are split into three types, `before`, `after` and `error`:

![feathers-hooks-old](https://user-images.githubusercontent.com/338316/44229860-34ca6300-a14e-11e8-8d78-0b0923721737.png)

While this pattern works quite well, it is a little cumbersome to implement functionality that needs to have access to the `before`, `after` and/or `error` flow at the same time. For example functionality for a profiler that logs the method runtime or extracting and storing data (e.g. associations) that will be used after the method call returns requires a `before` and an `after` hook.

## Proposal

With [async/await](https://javascript.info/async-await) now being fully supported by all recent versions of Node - and the ability to fall back to Promises for Node 6 - we now have a powerful new way to create middleware that can control the whole flow within a single function.

This pattern has been implemented already in [KoaJS](https://koajs.com/) for processing HTTP requests. However, similar to [what I wrote before about Express style middleware](https://blog.feathersjs.com/api-service-composition-with-hooks-47af13aa6c01), this also doesn't have to be limited to the HTTP request/response cycle but can apply to any asynchronous function, including Feathers services. Basically this new kind of hook will wrap _around_ the following hooks and the service method call like this:

![feathers-hooks-2 1](https://user-images.githubusercontent.com/338316/44229864-3b58da80-a14e-11e8-934d-642e2f6cf880.png)

### How it works

Additionally to the [hook context](https://docs.feathersjs.com/api/hooks.html#hook-context) `async` hooks also get an asynchronous `next` function that controls passing the flow to the next hook in the chain.

The following example registers an application wide before, after and error logger and profiler for all service method calls:

```js
app.hooks({
  async: [
    async (context, next) => {
      try {
        const start = new Date().getTime();

        console.log(`Before calling ${context.method} on ${context.path}`);

        await next();

        console.log(`Successfully called ${context.method} on ${context.path}`, context.result);
        console.log('Calling ${context.method} on ${context.path} took ${new Date().getTime() - start}ms');
        return context;
      } catch(error) {
        console.error(`Error in ${context.method} on ${context.path}`, error.message);
        // Not re-throwing would swallow the error
        throw error;
      }
    }
  ]
});
```

The following example extracts the `address` association for a user `create` method and saves it with the `userId` reference:

```js
app.service('users').hooks({
  async: {
    create: [
      async (context, next) => {
        const { app, data } = context;
        const { address } = data;

        context.data = _.omit(data, 'address');

        // Get the result from the context returned by the next hook
        // usually the same as accessing `context.result` after the `await next()` call
        // but more flexible and functional
        const { result } = await next();

        // Get the created user id
        const userId = context.result.id;

        // Create address with user id reference
        await app.service('addresses').create(Object.assign({
          userId
        }, address));

        return context;
      }
    ]
  }
});
```

### `async` hook type

The core of `async` hooks would be implemented as an individual module that allows to add hooks to any asynchronous method. This has been inspired by the great work @bertho-zero has been doing in #924 to allow using hooks on other service methods. I created a first prototype in https://github.com/daffl/async-hooks (test case can be found [here](https://github.com/daffl/async-hooks/blob/master/test/index.test.js)). It uses Koa's middleware composition module [koa-compose](https://github.com/koajs/compose).

`async` hooks would be implemented as an additional hook type but all hook dispatching will be done using the new middleware composition library. Existing `before` `after` and `error` hooks will be wrapped and registered in a backwards compatible way:

```js
app.service('users').hooks({
  async: {
    all: [],
    create: [],
    find: []
    // etc.
  },

  // Continue using all your existing hooks here
  before: {
    all: [],
    find: []
    // etc.
  },

  after: {},

  error: {}
});
```

`async` hooks will have precedence so the execution order would be `async -> before -> after`. Even when only using the old hooks there are several advantages:

- Better stack traces
- Slightly better performance
- Less custom code to maintain and the potential to collaborate with the Koa project

## Migration path

There will be two breaking changes:

1.  The currently still supported (but undocumented and not recommended) `function(context, next)` signature for existing `before`, `after` and `error` hooks will no longer work.
2. `koa-compose` does not allow to replace the entire context. Returning the context is still possible but other hooks have to retrieve it from the `await next();` call with `const ctx = await next();`.

**Comment by daffl** [comment]
This should definitely work for a caching hook. If it is one of the first registered, it can set `context.result` and not call `next()` which will skip all other hooks:

```js
app.hooks({
  async: [
    async (context, next) => {
      const { app, method, params } = context;

      if(method === 'find' || method === 'get') {
        const key = JSON.stringify(context.params.query);
        const cached = app.cache[key];

        if(cached) {
          context.result = cached;

          // Just return the context, don't call `next`
          return context;
        }

        const { result } = await next();

        app.cache[key] = result;
      }
      
      return context;
    }
  ]
});
```

For skipping hooks we could add an additional parameter (similar to the `returnHook` flag) to method calls that indicates that it shouldn't run any of the hooks:

```js
// Return the hook object
app.service('users').get(id, hooks.RETURN);

// Skip all hooks
app.service('users').get(id, hooks.SKIP);
```

To skip specific ones, I'm not sure if there is a way around wrapping them in a conditional hook or having a hook check it themselves.

**Comment by eddyystop** [comment]
I would suggest the cache contain the records returned by the DB call itself. That way the hooks intended after the DB call can customize the response for the specifics of that call, e.g. the role of the user.

Perhaps the "after" hooks can do that.

**Comment by eddyystop** [comment]
Its been a while since I looked at Koa, but doesn't it run its middleware bubble downstream and then bubble upstream?

Perhaps you can consider running the async hooks before the 'before" hooks, and before the "after" hooks, and maybe even before the "error" hooks.

I assume `type` would still have the `before` and `after` so the async function can know what it should do. I would be practical to have another property indicating if the hook is running as an async hook or not so hooks can prevent themselves from being run in the wronmg context.

Maybe `type` should just be `before`, `after`, `async_before` and `async_after`.

**Comment by daffl** [comment]
Maybe it's not clear in the proposal but the idea is that Koa style middleware has access to the whole flow that can be controlled by calling `next()` so there is no explicit *before* or *after*:

```js
// Before hook
const beforeHook = async (context, next) => {
  console.log('Before');

  await next();
}

// After hook
const afterHook = async (context, next) => {
  await next();

  console.log('After');
}

// Error hook
const errorHook = async (context, next) => {
  try {
    await next();
  } catch(error) {
    console.error('Error', error.message);
    throw error;
  }
}

// Before, after and error
const afterHook = async (context, next) => {
  try {
    console.log('Before');

    await next();

    console.log('After');
  } catch(error) {
    console.error('Error', error.message);
    throw error;
  }
}
```

**Comment by beeplin** [comment]
Totally agree with the proposal. One suggestion: instead of using `service.hooks({async: [function]})`, just simply use `service.hooks([function])`. The new koa-style hook is meant to replace the old before/after/error hooks, and in the future there will be only one kind of hooks, so no need to wrap them in the `async` property.

**Comment by beeplin** [comment]
BTW it would be nice if in the next major version we gave `service.hooks` an alias like `service.registerHooks`. `.hooks` is the only public service API that uses a noun as a method name.

**Comment by eddyystop** [comment]
I've been too busy to contribute on ths issue and will continue to be till the 12th. 

However, as I mentioned above, its important a (async?) hook be able to get/find a record from its own or from another service, without any of the hooks on that service being run. Is this possible?

**Comment by bertho-zero** [comment]
I'm waiting for it impatiently.

**Comment by bertho-zero** [comment]
How do you want to proceed to attach hooks directly to methods? 

The ideal would be to use the services even without app.

Does it mean that there will be hooks for every method, every service and every app?

**Comment by daffl** [comment]
Yes. [The Readme of the prototype](https://github.com/feathersjs/feathers/tree/hooks/packages/hooks) has a few examples for this:

```js
const { hooks } = require('@feathersjs/hooks');

const addExclamation = context => {
  context.result += '!!!';
}

const helloWithHook = hooks(async function() {
  return 'Hello world';
}, addExclamation);

console.log(await helloWithHook());

class HelloWorld {
  sayHello () {
    return 'Hello world';
  }
}

hooks(HelloWorld, {
});

**Comment by daffl** [comment]
Personally most looking forward to the decorator option because you see how everything fits together in a single place:

```js
// As a JavaScript or TypeScrip decorator
class HelloWorld {
  @hooks([ addExclamation ])
  sayHello () {
    return 'Hello world';
  }
}
```

There will probably be a backwards compatible `.hooks` method as well that will also support the old `before`, `after` and `error` style hooks (so far I think it should be able to wrap them backwards compatible).

**Comment by bertho-zero** [comment]
I think of something like that, what do you think? This could replace the `all` gradually.

```js
@hooks([
  reportErrors, 
  logRuntime
])
class HelloWorld {
  @hooks([
    addExclamation
  ])
  async sayHello () {
    return 'Hello world';
  }
}
```

**Comment by daffl** [comment]
Absolutely. I have to look at how to make that work with a decorator but I think that's a pretty nice way to see everything that is happening.

**Comment by rayfoss** [comment]
> Maybe it's not clear in the proposal but the idea is that Koa style middleware has access to the whole flow that can be controlled by calling `next()` so there is no explicit _before_ or _after_:
> 
> ```js
> // Before hook
> const beforeHook = async (context, next) => {
>   console.log('Before');
> 
>   await next();
> }
> 
> // After hook
> const afterHook = async (context, next) => {
>   await next();
> 
>   console.log('After');
> }
> 
> // Error hook
> const errorHook = async (context, next) => {
>   try {
>     await next();
>   } catch(error) {
>     console.error('Error', error.message);
>     throw error;
>   }
> }
> 
> // Before, after and error
> const afterHook = async (context, next) => {
>   try {
>     console.log('Before');
> 
>     await next();
> 
>     console.log('After');
>   } catch(error) {
>     console.error('Error', error.message);
>     throw error;
>   }
> }
> ```

This seems to hider hook type conversions... What if a service hook converts a patch call to an update. App hooks before next would have to be gated somehow...

**Comment by daffl** [comment]
I just published the first version of `@feathersjs/hooks` as a standalone module. You can find it (and all documentation) at https://github.com/feathersjs/hooks/

**Comment by bertho-zero** [comment]
Best news of 2020, eager to see more.

**Comment by bertho-zero** [comment]
My wrappers:

```js
function firstHook(context, next) {
  context.type = 'before';
  return next();
}

function lastHook(context, next) {
  context.type = 'after';
  return next();
}

function toBeforeHook(hook) {
  return async (context, next) => {
    await hook(context);
    await next();
  };
}

function toAfterHook(hook) {
  return async (context, next) => {
    await next();
    await hook(context);
  };
}

function beforeWrapper(...hooks) {
  return [firstHook, ...hooks.map(toBeforeHook)];
}

function afterWrapper(...hooks) {
  return [...hooks.reverse().map(toAfterHook), lastHook];
}

function wrap({ async = [], before = [], after = [] } = {}) {
  return [
    ...[].concat(async),
    firstHook,
    ...[].concat(before).map(toBeforeHook),
    ...[]
      .concat(after)
      .reverse()
      .map(toAfterHook),
    lastHook
  ];
}

module.exports = {
  wrap,
  beforeWrapper,
  afterWrapper,
  toBeforeHook,
  toAfterHook
};
```
