### ISSUE TITLE
Channels Architecture

### ISSUE THREAD

**Issue by jafri** [feathersjs/feathers#934]
I have been thinking about the proper channel architecture and implementation for the following problem:

All my users are `anonymous`. Lets say there are 3 pages that they are interested in:
1. Blocks
2. Transactions
3. Actions

Each of these pages will have their respective elements streamed in real-time. How can a user subscribe to only one of these at a time, and quickly switch?

More so, a user may have `blocks` open on one page and `transactions` open on another.

Currently, I use a global publisher so essentially the client receives all the events. However, the client may be receiving up to 500 updates a second, which it does not need. With a global publisher for example, the user may be on the `blocks` page and receive 100s of messages that contain `transactions` and `actions`.

All the recommendations I have seen for channels revolve around persistent state in the database, however I have no persistent data for the client.

**Comment by daffl** [comment]
Given that part of [our current business](https://www.bidali.com/) is creating APIs to efficiently watch distributed ledgers I can't give you the whole answer (maybe join the waitlist though 😉) but part of the trick is using joining the right channels in an `after` hook on `find` and `get` using [params.connection](https://docs.feathersjs.com/api/socketio.html#paramsconnection) or letting the client manage their channels manually through its own service:

```js
app.use('watcher', {
  async create(data, params) {
    this.app.channel(data.channel).join(params.connection);

    return data;
  },

  async remove(id, params) {
    this.app.channel(id).leave(params.connection);
  }

  setup(app) {
    this.app = app;
  }
});
```

**Comment by jafri** [comment]
Lets say I have channels in an after hook on find and get, and a user joins a few channels. If the client closes their webpage (effectively disconnecting ws), will the channel automatically remove the connection?

**Comment by daffl** [comment]
Yes. Disconnected sockets will be removed from channels automatically and channels with no connections in them will be cleaned up as well.

**Comment by jafri** [comment]
Just to note:

```
app.use('watcher', {
  async create(data, params) {
    this.app.channel(data.channel).join(params.connection);

    return data;
  },

  async remove(id, params) {
    this.app.channel(id).leave(params.connection);

    return { id }:
  }

  setup(app) {
    this.app = app;
  }
});
```
This worked perfectly on bloks.io
