### ISSUE TITLE
502 error comes frequently for feathersjs rest api with feathers-vuex on front end

### ISSUE THREAD

**Issue by pardeepgoel83** [feathersjs/feathers#936]
### Steps to produce
Rest api build with feathersjs
Frontend is build on feathers-vuex
Server iss using ngnix too redirect the requests to api

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc. This makes it much easier for us to debug and issues that have a reproducable example will get higher priority.

### Expected behavior
Should not get to 502 error

### Actual behavior
Getting 502 error frequently

### System configuration
Linux system 

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:
0.10

**Operating System**:
Linux centos

**Browser Version**:
Chrome
**React Native Version**:
NA
**Module Loader**:
Webpack

**Comment by daffl** [comment]
This is probably an issue with your NginX configuration because unless you throw it yourself, nothing in Feathers that error.
