### ISSUE TITLE
How to do Authorisation (not authentication)

### ISSUE THREAD

**Issue by gijo-varghese** [feathersjs/feathers#937]
I've seen the [Authentication](https://github.com/feathersjs/authentication) module in FeathersJS, however, I couldn't find anything for Authorization. In the case of [Loopback](https://loopback.io/), I can use their own ACL(Acess Control List) generator. 

What is the preferred way of doing Authorization in FeathersJS?

In my case I have router like
`http://localhost:3030/users/1`
which will give:
```
{
 id: 1,
 name: "Adam"
 tags: ["new","loyal customer","needs reply"]
}
```
Based on the token if its `admin` or `super admin` all fields have to be shown
But if its `user` (adam itself) then the tags should be hidden.

I know it can be done using `hooks`. But for a large application, it will be too complex

**Comment by perzanko** [comment]
I think hooks are the most feathersjs way to provide this feature. You can create i.e. hook `restrictFieldsToUserRoles(['tags'], ['admin', 'superadmin'])`, when field `tags` will be shown only for `admin` and `superadmin` roles.

**Comment by daffl** [comment]
Yep, that's exactly it. You can use any third party module for this or write your own. A basic generic hook of what @perzanko is suggesting without any dependencies is a few lines of code:

```js
const _ = require('lodash');

module.exports = function(fieldMap) {
  return async context => {
    const { result, method } = context;
    // User type (e.g. superadmin, admin)
    const type = context.params.user.type;
    // List of fields to omit for the result
    const fieldsToOmit = Object.keys(fieldMap).filter(field => {
      const roles = fieldMap[field];

      return !roles.includes(type);
    });
    const omitFields = item => _.omit(item, fieldsToOmit);

    if(method === 'find') {
      context.result.data = result.data.map(omitFields);
    } else {
      context.result = omitFields(result);
    }
  }
}
```

And can be used like

```js
app.service('users').hooks({
  after: {
    all: [ protectFields({
      name: [ 'superadmin' ],
      tags: [ 'admin', 'superadmin' ]
    }) ]
  }
})
```

If anyone would be interested in turning this into a separate open source module it is always a welcome sight of course.

There are also several blog posts about authorization in general, e.g. https://blog.feathersjs.com/access-control-strategies-with-feathersjs-72452268739d and https://blog.feathersjs.com/authorization-with-casl-in-feathersjs-app-fd6e24eefbff
