### ISSUE TITLE
Find fails with badRequest on limit over 20

### ISSUE THREAD

**Issue by beaverusiv** [feathersjs/feathers#944]
I have a function:
```
  async getUpdatedRows (table, time) {
    const totalRows = await this.app.service(`api/v1/rest/${table}`).find({ query: { $limit: 0 } } );
    if (totalRows.total > 21) {
      totalRows.total = 21;
    }
    return this.app
      .service(`api/v1/rest/${table}`)
      .find({
        paginate: false,
        $ignoreDeletedAt: true,
        query: {
          $limit: totalRows.total || 1,
          $or: {
            created_at: { $gt: time },
            updated_at: { $gt: time }
          }
        }
      });
  }
```

This works fine, but if I take the limit out or even make it 22 I get an error:

```
error: BadRequest: select count(`tide`.`id`) as `total` from `tide` where `$in` = '1' and `$in` = '2' and `$in` = '3' and `$in` = '4' and `$in` = '5' and `$in` = '6' and `$in` = '7' and `$in` = '8' and `$in` = '9' and `$in` = '10' and `$in` = '11' and `$in` = '12' and `$in` = '13' and `$in` = '14' and `$in` = '15' and `$in` = '16' and `$in` = '17' and `$in` = '18' and `$in` = '19' and `$in` = '20' and `$in` = '21' and `$in` = '22' and `deleted_at` = -1 - Unknown column '$in' in 'where clause'
```

It looks like the params are turned into an object instead of an array when the limit is above 21:

```
{ '$limit': '20',
  id: 
   { '$in': 
      [ '1',
        '2',
        '3',
        '4',
        '5',
        '6',
        '7',
        '8',
        '9',
        '10',
        '11',
        '12',
        '13',
        '14',
        '15',
        '16',
        '17',
        '18',
        '19',
        '20' ] } }
```

```
{ '$limit': '22',
  id: 
   { '$in': 
      { '0': '1',
        '1': '2',
        '2': '3',
        '3': '4',
        '4': '5',
        '5': '6',
        '6': '7',
        '7': '8',
        '8': '9',
        '9': '10',
        '10': '11',
        '11': '12',
        '12': '13',
        '13': '14',
        '14': '15',
        '15': '16',
        '16': '17',
        '17': '18',
        '18': '19',
        '19': '20',
        '20': '21',
        '21': '22' } } }
```

Is there a known fix for this? I've narrowed it down to the hook code between my `find()` call and `feathers-knex#find()` is called.

**Comment by daffl** [comment]
Please see the FAQ [Why are queries with arrays failing?](https://docs.feathersjs.com/faq/readme.html#why-are-queries-with-arrays-failing)

**Comment by beaverusiv** [comment]
Thanks so much, that worked. Might I suggest a rewording of the docs to mention `$limit` in that section as I'm not using any arrays myself and I have been searching for limits everywhere (knex, feathers-knex, feathersjs) to find a solution - might help someone else in the future.

**Comment by beaverusiv** [comment]
I understand that but that array is not made by me it is an intermediate object (only surfaced by logging inside third-party packages) created by the underlying code. To the end coder it looks as though `$limit` can't go above 21. Either way hopefully this issue will come up in search results for people with similar issues.

**Comment by daffl** [comment]
You did not mention that you were using a third party package (or which one). It might be an issue worth raising there since it is a well documented restriction with Express itself.

**Comment by beaverusiv** [comment]
Third party for me, as in featherjs. But as I said, hopefully my issue will serve as documentation. Have a good day and thanks.

**Comment by daffl** [comment]
I guess that's why I'm not following. A standard Feathers setup doesn't change or add query parameters on the client. It has to be some plugin or other functionality added in your application on the client that is doing that.
