### ISSUE TITLE
User is having multiple subscriptions on each channel

### ISSUE THREAD

**Issue by hatimn02** [feathersjs/feathers#957]
Whenever a user logged in, it gets subscribe to list of channels
On logged out we are unable to receive on.(logout) event
And when that same user logged in again after logout then it gets subscribed to the same channels twice

**Comment by daffl** [comment]
The problem is that at the moment, connections will only be automatically removed from channels on `disconnect`, not on `logout`. For now disconnecting on logout or adding the following to your `channels.js` should do it:

```js
app.on('logout', (result, { connection }) => {
  if(connection) {
    app.channel(app.channels).leave(connection);
  }
});
``
