### ISSUE TITLE
CLI not working after implementing eslint rules (es6 syntax)

### ISSUE THREAD

**Issue by gijo-varghese** [feathersjs/feathers#958]
After generating the app using cli, this is how the `services/index.js` looks like:
```
// eslint-disable-next-line no-unused-vars
module.exports = function (app) {
    
};
```

We heavily using `eslint airbnb rules`. So we had to modify the file to:
```
// eslint-disable-next-line no-unused-vars
export default (app) => {};
```

After this when I try to create a file, I get this error:
```
conflict src/feathers/services/index.js seems to have morethan one function declaration and we can not register the new service. Did you modify it?     info You will need to add the next lines manually to the file
     info const customers = require('./customers/customers.service.js');     info app.configure(customers);
```

Anyway to fix this?

**Comment by daffl** [comment]
Not super trivial but the code transformations for this are done in https://github.com/feathersjs/feathers/blob/master/packages/generator-feathers/generators/service/index.js#L108. That part and https://github.com/feathersjs/tools/blob/master/lib/transform.js#L69 needs to be updated to include arrow functions and default exports as well.

https://astexplorer.net is pretty useful when it comes to testing out codemods. Or you just do what the message suggests and add it manually.

**Comment by gijo-varghese** [comment]
ok. Got it

**Comment by daffl** [comment]
`@feathersjs/cli@4.0.0@pre` now supports TypeScript which is the recommended way to use ES6 import syntax until it lands in Node natively.
