### ISSUE TITLE
Implement Featherjs 3.0 with Expo

### ISSUE THREAD

**Issue by pankajtft** [feathersjs/feathers#964]
In one of our Expo project previously we were using the Featherjs(V 2.0)(https://docs.feathersjs.com) and  application was running smoothly . Few month ago a new version of featherjs was released(3.0) and we think to migrate the feather 2.0 to 3.0. We follow this link for migration([https://docs.feathersjs.com/migrating.html]. After updating and making all these the change when we run the application we got following error.

The package at "node_modules/@feathersjs/socketio/lib/index.js" attempted to import the Node standard library module "http". It failed because React Native does not include the Node standard library. Read more at https://docs.expo.io/versions/latest/introduction/faq.html#can-i-use-nodejs-packages-with-expo

as per above link of expo we could not use the code node apis with react-native and expo.
so there is any way to resolve this error i mean how to configure the node http api in expo project.

![screenshot_2018-08-29-14-51-36-904_host exp exponent](https://user-images.githubusercontent.com/41910283/44778943-d2d11b00-ab9b-11e8-8de0-f13d72d70fd8.png)

**Comment by subodhpareek18** [comment]
Why would you use feathers inside expo. Feathers is a server side library, you need feathers client [https://www.npmjs.com/package/@feathersjs/client] inside expo.

**Comment by daffl** [comment]
You can still use the individual packages but it looks like you are trying to load `@feathersjs/socketio` which is indeed a server side library. You probably want `@feathersjs/socketio-client` instead.

**Comment by pankajtft** [comment]
Thanks daffl, yes i was using the wrong package at client side. That was my fault.
