### ISSUE TITLE
Implement custom paths like /count, /exists

### ISSUE THREAD

**Issue by gijo-varghese** [feathersjs/feathers#966]
After looks at Loopback/StrongLoop, I found the following methods very useful.

```
http://localhost:3030/users/count
http://localhost:3030/users/1/exists
http://localhost:3030/users/replaceOrCreate
http://localhost:3030/users/upsertWithWhere
```

I use `feathers-sequelize`. How can easily implement these kinds of methods for all my models?

**Comment by daffl** [comment]
As discussed in [this FAQ](https://docs.feathersjs.com/faq/readme.html#how-do-i-create-custom-methods) Feathers intentionally does not support custom methods like that. The key point is:

> Feathers is built around the REST architectural constraints and there are many good reasons for it. In general, almost anything that may require custom methods or RPC style actions can also be done either by creating a custom service or through hooks.

For example, you can already get the user count by calling `http://localhost:3030/users?$limit=0`. This will return a [page object](https://docs.feathersjs.com/api/databases/common.html#pagination) with a `total` property. `replaceOrCreate` can be implemented as a hook shown in [this FAQ](https://docs.feathersjs.com/faq/readme.html#how-can-i-do-custom-methods-like-findorcreate).

If you want to create nested routes, this is discussed [in this FAQ](https://docs.feathersjs.com/faq/readme.html#how-do-i-do-nested-or-custom-routes).
