### ISSUE TITLE
Cannot use service with Postman if it is protected with authenticate('jwt') hook

### ISSUE THREAD

**Issue by jordiblanchcarles** [feathersjs/feathers#968]
### Steps to reproduce

I've created a Feathersjs app from scratch using feathers-cli:

$ feathers g app

Selected to create both REST and Socket.io APIs.
Then created the authentication service:

$ feathers g authentication

Selected to use only local authentication, and use NeDB database.
Then created a "fake" service:

$ feathers g service

Selected NeDB and require authentication

After that, just started the app:

$ npm start

Then using Postman, and following the chat application example, I create a user with password. After the user is created, I create the accessToken using strategy: local, the user email and the password. The response from server is an accessToken.
And then, when I try to use this token to create a new entry with the "fake" service that is protected with the authenticate('jwt') hook, then there is the "NotAuthenticated: No auth token" error.
I'm adding to the POST request the "Authorisation" header with the value returned by the server when asked for the token.

Could somebody tell me what I'm doing wrong?

### Expected behavior

The new "fake" service object should be created in the NeDB.

### Actual behavior

The server throws a "NotAuthenticated: No auth token" error.

### System configuration

**Module versions** (especially the part that's not working):
+ @feathersjs/errors@3.3.0
+ serve-favicon@2.5.0
+ compression@1.7.3
+ cors@2.8.4
+ @feathersjs/express@1.2.3
+ @feathersjs/express@1.2.3
+ winston@3.0.0
+ @feathersjs/feathers@3.1.7
+ @feathersjs/socketio@3.2.2
+ helmet@3.13.0
+ @feathersjs/configuration@2.0.0
+ @feathersjs/authentication@2.1.7
+ @feathersjs/authentication-local@1.2.1
+ @feathersjs/authentication-jwt@2.0.1
+ request-promise@4.2.2
+ request@2.88.0
+ mocha@5.2.0
+ eslint@5.4.0
+ nodemon@1.18.4
+ nedb@1.8.0

**NodeJS version**:
v9.11.2

**Operating System**:
Linux PC 4.4.0-103-generic #126-Ubuntu SMP Mon Dec 4 16:23:28 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by daffl** [comment]
Although we do speak the Queen's English here in Canada 🇨🇦, the header name is `Authorization` not `Authorisation`

**Comment by jordiblanchcarles** [comment]
Hello Daffi, sorry, I made a mistake when writing the issue, in Postman I wrote Authorisation correctly, so it is not working (at least for me).

![image](https://user-images.githubusercontent.com/26330752/44874646-23c83880-ac9c-11e8-8f3e-8d175a08ccce.png)


Have you tried my steps? Does it work for you?

Thank you!

**Comment by jordiblanchcarles** [comment]
Oh!!! Sorry!!!! I didn't realize!!!! :cold_sweat: 
Thank you very much for your fast answer...
