### ISSUE TITLE
authenticating from one single app

### ISSUE THREAD

**Issue by kemijibola** [feathersjs/feathers#972]
I have 2 apps
is it possible to manage users,authentication and permissions from app1 and use the token returned for the loggedin user from app1 in app2.

**Comment by daffl** [comment]
Yes if they both share the same [authentication secret](https://github.com/feathersjs/feathers-chat/blob/master/config/default.json#L11). If you use the standard setup you will need a `/users` service that points to a shared database or you can [customize the JWT payload](https://docs.feathersjs.com/guides/auth/recipe.customize-jwt-payload.html) and [the verifier](https://docs.feathersjs.com/api/authentication/jwt.html#verifier) to not require a shared service.

**Comment by kemijibola** [comment]
Thanks @daffl,
I tried it and it worked.The apps have users in shared database but i will be going with managing roles,user roles, permissions on app2. users will mainly be created and authenticated on app1
