### ISSUE TITLE
Wrong path to the model

### ISSUE THREAD

**Issue by fexell** [feathersjs/feathers#980]
### Steps to reproduce

Just by installing "authentication".

### Expected behavior

It should not have an extra "../".

### Actual behavior

It tries to find the models in a non-existing folder.

Here's the line that gets installed:
`const createModel = require('../../../models/api.model');`

What it should read:
``const createModel = require('../../models/api.model');``

**Comment by daffl** [comment]
Which database/service type did you pick?

**Comment by fexell** [comment]
@daffl Mongoose

**Comment by fexell** [comment]
This seems to have been fixed now. Thank you and keep up the good work! :)

**Comment by daffl** [comment]
I don't think anything changed but I wasn't able to reproduce it either so I think we can close it. The generator expects to run in the root folder, maybe you ran in it a different folder before.
