### ISSUE TITLE
$geoNear, $near, and $nearSphere are not allowed in this context

### ISSUE THREAD

**Issue by Polqk** [feathersjs/feathers#981]
Hi,
After mongoose, mongodb update i have an error message with $near, I don't know if it's feathers,
 mongodb or mongoose problem, before update it's work fine, thanks for help

api :
![near](https://user-images.githubusercontent.com/36846411/45159634-9a5abe00-b1e7-11e8-94df-b6ec20278236.png)

client :
![near2](https://user-images.githubusercontent.com/36846411/45159816-181ec980-b1e8-11e8-86d2-6452ffbc29f8.png)

client code :
![near3](https://user-images.githubusercontent.com/36846411/45159800-0b9a7100-b1e8-11e8-8bb4-83fac62f2a6f.png)

I also have this warning in API :
![near4](https://user-images.githubusercontent.com/36846411/45159638-a0509f00-b1e7-11e8-8af9-6cb29d06dd46.png)

upgraded versions :

mongoose 5.0.6 to 5.2.13
mongodb 3.0.2 to 3.1.4
mongodb-core 3.1.3

My collection that uses $near :

```js
module.exports = function (app) {
  const mongooseClient = app.get('mongooseClient');
  const { Schema } = mongooseClient;

  const places = new Schema({
    reference: { type: String }, // Faut mettre unique parking_id + reference
    price: Number,
    name: String,
    fees: Number,
    deposit: Number,
    available: Boolean,
    type: String, // parking, box, moto
    handicapped: Boolean,
    double: Boolean,
    outdoor: Boolean,
    owner_type: String,
  });

  const address = new Schema({
    number: { type: String, required: true },
    street: { type: String, required: true },
    zipcode: { type: String, required: true },
    city: { type: String, required: true },
    country: { type: String, required: true },
    streetview_url: String,
  });

  const parkings = new Schema({
    managers: [{
      type: Schema.Types.ObjectId, ref: 'users'
    }],
    agency_id: { type: Schema.Types.ObjectId, ref: 'agencies' },
    address,
    location: {
      type: { type: String, default: 'Point' },
      coordinates: { type: [Number], default: [0, 0] }
    },
    places: [places],
    reference_nomad: { type: String, required: true, index: { unique: true } },
    reference_owner: { type: String, required: true, index: { unique: true } },
    size: String,
    brightness: Boolean,
    available: Boolean,
    disable_reason: String, //orders_limit, availability, manager_inert, manual, manager_missing, address_missing, holidays
    images: [String],
    cctv: Boolean,
    enable_date: Date
  }, {
      timestamps: true
    });

  parkings.index({ location: '2dsphere' });
  return mongooseClient.model('parkings', parkings);
};
```

You can see me post in mongoose repo there : 
https://github.com/Automattic/mongoose/issues/6981#issuecomment-419040162

Thanks

**Comment by daffl** [comment]
Nothing changed in `feathers-mongoose` so it is probably a regression somewhere else. Have you tried running the query directly against the model?
