### ISSUE TITLE
Passing hostUrl dynamically to socket io()

### ISSUE THREAD

**Issue by kemijibola** [feathersjs/feathers#986]
I have a class in my angular client where I initialized and configured my feathers app 'socketService'. My client will be utilizing 2 apps but I don't want to create another class for the second  app. I used observables to emit the hostUrl to use in the constructor of socketService

Behaviour : on first creation of socketService,  the data from observable emits null,  and this makes the line of code fail

var socket = io(hostUrl)

I am thinking my saving grace will be to create another socketService2 , define a const hostUrl1 & hostUrl2 and initialize both socketService and socketService2 with respective hostUrls

Is there any other way I can get this done ?

**Comment by daffl** [comment]
Can you provide an example? Maybe it's because I am not familiar with Angular but I'm not following the problem.

**Comment by kemijibola** [comment]
I have resolved emitting new hostUrl to my socketService. below is the angular configuration for feathers

        this.socket = io(hostUrl);
        this.socket
        this._app = feathers()
          .configure(socketio(this.socket))
          .configure(rx({ idField: "_id", listStrategy: 'always' }))
          .configure(authentication({ storage: window.localStorage }));

The problem now is, on first request of a socket service method, it returns connection to previous hostUrl. i.e 
if login component talks to http://localhost:3031 ,then the observable data returned to hostUrl is http://localhost:3031 but if the request from getTitles talks to http://localhost:3030, the hostUrl is changed to http://localhost:3030 ,currently the socket still connects to http://localhost:3031, and on second call it connects to correct hostUrl http://localhost:3030. Could it be that socket is caching url? how do i make this change effective?

**Comment by kemijibola** [comment]
I just read about feathers Sub-Apps. 
I think i will look into this. If they both share same authentication secret, then i can authenticate from mainApp.

**Comment by daffl** [comment]
Yes, each application will use the socket it has been configured with. The most common and straightforward way to talk to different servers is to initialized different applications.

```js
this._app1 = feathers().configure(socketio('http://localhost:3030'));
this._app2 = feathers().configure(socketio('http://localhost:3031'));
```

**Comment by kemijibola** [comment]
This is how i implemented 1 angular client multiple feathers authentication.
First, I configured my mainApp in the constructor of my feathers-client.service.ts using code below
      this.socket = io(HOST);
      this._app = feathers()
        .configure(socketio(this.socket))
        .configure(rx({ idField: "_id", listStrategy: 'always' }))
        .configure(authentication({ storage: window.localStorage }));

Each time i want to make a call to second feathers app, I configure my socket with the main app with below code
    const socket2 = io('http://localhost:3030', {
          
      transports: ['polling', 'websocket'],
      polling: {
        extraHeaders: {
          Authorization: this.locker.get('auth')
        }
      }
    });

    this._app = feathers()
     .configure(socketio(socket2))
     .configure(rx({ idField: "_id", listStrategy: 'always' }))
     .configure(authentication({ storage: window.localStorage }));

The important thing here is to configure the socket on the _app and not _app2. 
With this setup,i was able to authenticate on _app and use token generated from _app to make request to my feathers app2.

**Comment by daffl** [comment]
Closing then since it seems to be solved.
