### ISSUE TITLE
Allow to set oAuth2 redirect URLs dynamically

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers#990]
Sometimes it might be required to set the oAuth2 URLs dynamically during the oAuth flow. Allowing this will be part of the next release of Feathers authentication.

**Comment by gauravdhiman** [comment]
@daffl any update on this request ?

**Comment by daffl** [comment]
This will be possible with authentication v3 (development branch [here](https://github.com/feathersjs/feathers/tree/authentication/v3)) which will use [Grant](https://github.com/simov/grant) and its [dynamic overrides](https://github.com/simov/grant#dynamic-override) for oAuth. Pre release should be available this month.

**Comment by daffl** [comment]
This is now available in Feathers v4 authentication. See the [Migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information on how to upgrade.
