### ISSUE TITLE
mongodb config does not seem to wait for the connection to resolve

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers#996]
_From @eddyystop on July 30, 2017 20:45_

The relevent code in src/services/monododb.js is
```javascript
  const config = app.get('mongodb');
  const promise = MongoClient.connect(config);
  app.set('mongoClient', promise);
```

My test apparently used a mongodb service before the connection was established. It looks like it threw because `app.service(...)` was undefined. It did not throw once I delayed the test with a setTimeout.

I think the main concern is that an app using mongodb may sometimes boot and sometimes not.

_Copied from original issue: feathersjs/generator-feathers#253_

**Comment by daffl** [comment]
I think adding something like

```js
before(() => app.get('mongoClient'));
```

In the tests should also wait for the client to connect and run your tests reliably.

**Comment by daffl** [comment]
_From @eddyystop on July 30, 2017 21:20_

These are not mocha tests, rather some test apps. I think this should at least be documented as its a time sink to track down.

**Comment by daffl** [comment]
I wonder if there is a good way for the generator to wait for the connection before starting the server.

**Comment by daffl** [comment]
_From @eddyystop on August 1, 2017 17:35_

That is the conundrum.

One positive point is that MongoDB can only be used on the server. Can anything be done with async/await?

**Comment by daffl** [comment]
This will be addressed with https://github.com/feathersjs/feathers/issues/853 and https://github.com/feathersjs/feathers/issues/509

**Comment by AmberByte** [comment]
For everyone coming here from google, I've worked around this by using a custom event which is emitted when the setup is finished.
I'm using mongoose but it should work the same way for mongodb as well

### src/mongoose.ts:
```` typescript
import mongoose from 'mongoose';
import { Application } from './declarations';
import logger from './logger';

export default function (app: Application) {
  mongoose.connect(
    app.get('mongodb'),
    { useCreateIndex: true, useNewUrlParser: true, useUnifiedTopology: true },
  ).then(() => {
   // This emits a event called mognoose-ready on app instance
    app.emit('mongoose-ready');
  }).catch((err) => {
    logger.error(err);
    process.exit(1);
  });

  mongoose.Promise = global.Promise;

  app.set('mongooseClient', mongoose);
}

````

### src/app.test.ts
```` typescript
  beforeAll((done) => {
    // Waits for mongoose to be initialized and ready then executed tests
    app.on('mongoose-ready', () => {
      done();
    });
  });

  afterAll(() => {
      app.get('mongooseClient').disconnect();
  })

````
