### ISSUE TITLE
I”m getting an error on facebook login “This authorization code has been used”, google “invalid_grant”

### ISSUE THREAD

**Issue by SeunghunSunmoonLee** [feathersjs/feathers#998]
### Steps to reproduce
https://blog.feathersjs.com/how-to-setup-oauth-flow-with-featherjs-522bdecb10a8
Hi! 
I”m getting an error on facebook login “This authorization code has been used”, google “invalid_grant”

any clues? I”m running server on localhost:3030 client on localhost:3000

### Expected behavior
after clicking my account on redirected google/facebook signin page it should redirect to localhost:3000 with authentication. 

### Actual behavior
after clicking my account on redirected google/facebook signin page it just waits for long and returns wrong response. 

### System configuration

**Module versions** (especially the part that's not working):
    "@feathersjs/authentication": "^2.0.1",
    "@feathersjs/authentication-jwt": "^2.0.0",
    "@feathersjs/authentication-local": "^1.0.2",
    "@feathersjs/authentication-oauth2": "^1.2.2",
    "@feathersjs/configuration": "^1.0.1",
    "@feathersjs/errors": "^3.2.0",
    "@feathersjs/express": "^1.1.2",
    "@feathersjs/feathers": "^3.0.2",
    "@feathersjs/socketio": "^3.0.1",
    "compression": "^1.7.1",
    "cors": "^2.8.4",
    "feathers-mongoose": "^6.1.4",
    "feathers-sync": "^1.0.3",
    "helmet": "^3.9.0",
    "mongoose": "^5.2.13",
    "passport-facebook": "^2.1.1",
    "passport-google-oauth2": "^0.1.6",
    "serve-favicon": "^2.4.5",
    "winston": "^3.0.0"

**NodeJS version**:  v9.11.1

**Operating System**: mac os

**Browser Version**: chrome

**React Native Version**: 

**Module Loader**:

**Comment by daffl** [comment]
I think this should be solved with the new v4 oAuth authentication. See the [migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information.
